IF NOT EXISTS (SELECT CONFIG_OPTION FROM CONFIG WHERE  CONFIG_OPTION='UPDATE_TOTAL_CASHDISCOUNTAMOUNT' AND VALUE=1)
BEGIN
	
	  -- UPDATING TOTALS IN PIM TABLE  
  UPDATE A SET TOTAL_CASHDISCOUNTAMOUNT=B.CASHDISCOUNTAMOUNT  
  FROM PIM01106 A 
  JOIN  
  (    
	   SELECT MRR_ID, SUM(CASHDISCOUNTAMOUNT) AS CASHDISCOUNTAMOUNT
	   FROM PID01106   
	   GROUP BY MRR_ID    
  ) B ON  A.MRR_ID = B.MRR_ID    
  WHERE ISNULL(A.TOTAL_QUANTITY,0)<> ISNULL(B.CASHDISCOUNTAMOUNT,0)
  
  
      

	IF NOT EXISTS (SELECT CONFIG_OPTION FROM CONFIG WHERE CONFIG_OPTION='UPDATE_TOTAL_CASHDISCOUNTAMOUNT')
		INSERT CONFIG (CONFIG_OPTION,VALUE,ROW_ID,LAST_UPDATE)
			   VALUES ('UPDATE_TOTAL_CASHDISCOUNTAMOUNT',1,'',GETDATE())	
	ELSE
		UPDATE CONFIG SET VALUE='1' WHERE CONFIG_OPTION='UPDATE_TOTAL_CASHDISCOUNTAMOUNT'
	
END		
