
---------------
IF NOT EXISTS ( SELECT LEAVE_CODE FROM EMP_LEAVE_MASTER WHERE LEAVE_CODE = '0000000' )
	INSERT INTO EMP_LEAVE_MASTER(LEAVE_CODE,LEAVE_NAME,NO_OF_LEAVES,ALIAS,ENCASHMENT,CALC_METHOD,REMARKS )
	VALUES ('0000000', '',0,'',0,1,'')
	
