IF NOT EXISTS (SELECT CONFIG_OPTION FROM CONFIG WHERE CONFIG_OPTION='UPDATE_PIM_MRR_CREATION_DEPT_ID' AND VALUE=1)
BEGIN
	PRINT 'UPDATING MRR_CREATION_DEPT_ID  IN PIM01106'
	/*Rohit 30-10-2024
	UPDATE PIM01106 SET MRR_CREATION_DEPT_ID=(CASE WHEN ISNULL(ACCOUNTS_DEPT_ID,'')<>'' THEN ACCOUNTS_DEPT_ID ELSE DEPT_ID END)
	WHERE ISNULL(MRR_CREATION_DEPT_ID,'')=''
	*/
	UPDATE PIM01106 SET MRR_CREATION_DEPT_ID=(CASE WHEN ISNULL(ACCOUNTS_DEPT_ID,'')<>'' THEN ACCOUNTS_DEPT_ID ELSE LOCATION_CODE END)
	WHERE ISNULL(MRR_CREATION_DEPT_ID,'')=''

	IF NOT EXISTS (SELECT CONFIG_OPTION FROM CONFIG WHERE CONFIG_OPTION='UPDATE_PIM_MRR_CREATION_DEPT_ID')
		INSERT CONFIG (CONFIG_OPTION,VALUE,ROW_ID,LAST_UPDATE)
			   VALUES ('UPDATE_PIM_MRR_CREATION_DEPT_ID',1,'',GETDATE())	
	ELSE
		UPDATE CONFIG SET VALUE='1' WHERE CONFIG_OPTION='UPDATE_PIM_MRR_CREATION_DEPT_ID'
	
END		
