IF NOT EXISTS (SELECT TOP 1 'U' FROM COUNTRY WHERE COUNTRY_CODE='0000000') 
BEGIN
    
     INSERT COUNTRY	( COUNTRY_CODE, COUNTRY_NAME, LAST_UPDATE, INACTIVE )  
     SELECT '0000000'  COUNTRY_CODE, 'INDIA' AS  COUNTRY_NAME,GETDATE() LAST_UPDATE,0 AS  INACTIVE 

END
