


--**** GENERATE KEYS TABLE USER WISE TO BE REFERRED IN SAVETRAN OF RETAIL SALES
IF CURSOR_STATUS('GLOBAL','KEYSCUR') IN (0,1)
BEGIN
	CLOSE KEYSCUR
	DEALLOCATE KEYSCUR
END	

DECLARE @CUSERALIAS VARCHAR(5),@CKEYSTABLE VARCHAR(50),@BUPDATEKEYS BIT,@CCMD NVARCHAR(MAX) 

DECLARE KEYSCUR CURSOR FOR SELECT DISTINCT USER_ALIAS FROM USERS 

OPEN KEYSCUR
FETCH NEXT FROM KEYSCUR INTO @CUSERALIAS
WHILE @@FETCH_STATUS=0
BEGIN

	EXEC SP_CREATE_DYNAMIC_KEYSTABLE 'KEYS_CMM',@CUSERALIAS
	
	SET @CKEYSTABLE='KEYS_CMM_'+@CUSERALIAS
	
	SET @CCMD=N'IF NOT EXISTS (SELECT TOP 1 TABLENAME FROM ['+@CKEYSTABLE+'])
					SET @BUPDATEKEYSOUT=1
				ELSE
					SET @BUPDATEKEYSOUT=0'
	EXEC SP_EXECUTESQL @CCMD,N'@BUPDATEKEYSOUT BIT OUTPUT',@BUPDATEKEYSOUT=@BUPDATEKEYS OUTPUT				
	
	IF @BUPDATEKEYS=1
	BEGIN
		SET @CCMD=N'INSERT ['+@CKEYSTABLE+'] ( TABLENAME, LASTKEYVAL, COLUMNNAME, PREFIX, FINYEAR ) 
				    SELECT ''CMM01106'' AS TABLENAME,MAX(CM_NO) AS LASTKEYVAL,''CM_NO'' AS COLUMNNAME,
				    LEFT(CM_NO,5) AS PREFIX,FIN_YEAR AS FINYEAR FROM CMM01106 WHERE 
				    SUBSTRING(CM_NO,3,2)='''+@CUSERALIAS+''' AND SUBSTRING(CM_NO,5,1) =''-''
				    GROUP BY LEFT(CM_NO,5),FIN_YEAR'
		EXEC SP_EXECUTESQL @CCMD		

		SET @CCMD=N'INSERT ['+@CKEYSTABLE+'] ( TABLENAME, LASTKEYVAL, COLUMNNAME, PREFIX, FINYEAR ) 
				    SELECT ''CMM01106'' AS TABLENAME,MAX(CM_NO) AS LASTKEYVAL,''CM_NO'' AS COLUMNNAME,
				    LEFT(CM_NO,6) AS PREFIX,FIN_YEAR AS FINYEAR FROM CMM01106 WHERE 
				    SUBSTRING(CM_NO,3,2)='''+@CUSERALIAS+''' AND SUBSTRING(CM_NO,5,1) IN (''N'',''A'')
				    GROUP BY LEFT(CM_NO,6),FIN_YEAR'
		EXEC SP_EXECUTESQL @CCMD				    
	END						
	FETCH NEXT FROM KEYSCUR INTO @CUSERALIAS
END

CLOSE KEYSCUR
DEALLOCATE KEYSCUR

