

IF NOT EXISTS (SELECT HEAD_CODE FROM HD01106 WHERE HEAD_NAME ='SHARE HOLDERS FUND' )
AND EXISTS(SELECT HEAD_CODE FROM HD01106)
BEGIN
	INSERT HD01106 (HEAD_CODE, HEAD_NAME, MAJOR_HEAD_CODE, PHYSICAL, ALIAS, CREDITOR_DEBTOR_CODE, COMPANY_CODE, LAST_UPDATE, PRINT_HEAD, UPLOADED_TO_ACTIVSTREAM,INACTIVE)
	 VALUES ('00DEF00032', 'SHARE HOLDERS FUND', '00DEF00032', 0, '', '', '01', '', 0, 0,0)
	 INSERT HD01106 (HEAD_CODE, HEAD_NAME, MAJOR_HEAD_CODE, PHYSICAL, ALIAS, CREDITOR_DEBTOR_CODE, COMPANY_CODE, LAST_UPDATE, PRINT_HEAD, UPLOADED_TO_ACTIVSTREAM,INACTIVE)
	 VALUES ('00DEF00033', 'NON CURRENT LIABILITIES', '00DEF00033', 0, '', '', '01', '', 0, 0,0)
	 INSERT HD01106 (HEAD_CODE, HEAD_NAME, MAJOR_HEAD_CODE, PHYSICAL, ALIAS, CREDITOR_DEBTOR_CODE, COMPANY_CODE, LAST_UPDATE, PRINT_HEAD, UPLOADED_TO_ACTIVSTREAM,INACTIVE)
	 VALUES ('00DEF00034', 'NON CURRENT ASSETS', '00DEF00034', 0, '', '', '01', '', 0, 0,0)

END
