IF NOT EXISTS(SELECT TOP 1 'U' FROM TILL_SMS_TMPLT)
BEGIN
	PRINT 'INSERTING DEFAULT VALUES FOR TILL SMS TEMPLATES.'
	INSERT TILL_SMS_TMPLT	( TMPLT_TYPE, TMPLT_NAME, TMPLT_TEXT )  
	SELECT 	1 AS TMPLT_TYPE,'LIMIT REACHED' AS TMPLT_NAME,'' AS TMPLT_TEXT 
	UNION ALL
	SELECT 	2 AS TMPLT_TYPE,'CASH DIFF' AS TMPLT_NAME,'' AS TMPLT_TEXT 
	UNION ALL
	SELECT 	0 AS TMPLT_TYPE,'BOTH' AS TMPLT_NAME,'' AS TMPLT_TEXT 
END
