	





IF NOT EXISTS (SELECT CONFIG_OPTION FROM CONFIG WHERE CONFIG_OPTION='UPDATE_ARC_TAXABLE_VALUE' AND VALUE=1)
BEGIN
	PRINT 'UPDATING TAXABLE VALUE COLUMN IN ADVANCE/RECEIPT MEMOS AGAINST GST CALCULATED.....PLEASE STANDBY '
	
	UPDATE ARC01106 SET TAXABLE_VALUE=NET_AMOUNT-(NET_AMOUNT*GST_PERCENTAGE/(100+GST_PERCENTAGE)),OH_TAX_METHOD=2,
	IGST_AMOUNT=(CASE WHEN ISNULL(IGST_AMOUNT,0)<>0 THEN NET_AMOUNT*GST_PERCENTAGE/(100+GST_PERCENTAGE) ELSE 0 END),
	CGST_AMOUNT=(CASE WHEN ISNULL(CGST_AMOUNT,0)<>0 THEN (NET_AMOUNT*GST_PERCENTAGE/(100+GST_PERCENTAGE))/2 ELSE 0 END),
	SGST_AMOUNT=(CASE WHEN ISNULL(SGST_AMOUNT,0)<>0 THEN (NET_AMOUNT*GST_PERCENTAGE/(100+GST_PERCENTAGE))/2 ELSE 0 END)
	WHERE ISNULL((IGST_AMOUNT+CGST_AMOUNT+SGST_AMOUNT),0)<>0 

	IF NOT EXISTS (SELECT CONFIG_OPTION FROM CONFIG WHERE CONFIG_OPTION='UPDATE_ARC_TAXABLE_VALUE')
		INSERT CONFIG (CONFIG_OPTION,VALUE,ROW_ID,LAST_UPDATE)
			   VALUES ('UPDATE_ARC_TAXABLE_VALUE',1,'',GETDATE())	
	ELSE
		UPDATE CONFIG SET VALUE=1 WHERE CONFIG_OPTION='UPDATE_ARC_TAXABLE_VALUE'
END
