


IF NOT EXISTS (SELECT CONFIG_OPTION FROM CONFIG WHERE  CONFIG_OPTION='UPDATE_DONOTSENDCHALLANWITHOUTDISPATCH_IN_LOCATION' AND VALUE=1)
BEGIN
	PRINT ' UPDATE DONOTSENDCHALLANWITHOUTDISPATCH IN LOCATION '
	
	UPDATE LOCATION SET DONOTSENDCHALLANWITHOUTDISPATCH=1

	IF NOT EXISTS (SELECT CONFIG_OPTION FROM CONFIG WHERE 
	 CONFIG_OPTION='UPDATE_DONOTSENDCHALLANWITHOUTDISPATCH_IN_LOCATION')
		INSERT CONFIG (CONFIG_OPTION,VALUE,ROW_ID,LAST_UPDATE)
			   VALUES ('UPDATE_DONOTSENDCHALLANWITHOUTDISPATCH_IN_LOCATION',1,'',GETDATE())	
	ELSE
		UPDATE CONFIG SET VALUE='1' WHERE CONFIG_OPTION='UPDATE_DONOTSENDCHALLANWITHOUTDISPATCH_IN_LOCATION'
	
END		
