


IF NOT EXISTS (SELECT CONFIG_OPTION FROM CONFIG WHERE CONFIG_OPTION='UPDATE_SKU_FORMID' AND VALUE=1)
BEGIN
	PRINT 'UPDATING FORM ID IN SKU TABLE AT HO'
	

	DECLARE @CHOLOCID CHAR(2) ,@CCURLOCID CHAR(2)
	
	SELECT TOP 1 @CCURLOCID=VALUE FROM CONFIG WHERE CONFIG_OPTION='LOCATION_ID'
	SELECT TOP 1 @CHOLOCID=VALUE FROM CONFIG WHERE CONFIG_OPTION='HO_LOCATION_ID'

	IF NOT EXISTS (SELECT CONFIG_OPTION FROM CONFIG WHERE CONFIG_OPTION='UPDATE_SKU_FORMID')
		INSERT CONFIG (CONFIG_OPTION,VALUE,ROW_ID,LAST_UPDATE)
			   VALUES ('UPDATE_SKU_FORMID','1','',GETDATE())	
	ELSE
		UPDATE CONFIG SET VALUE='1' WHERE CONFIG_OPTION='UPDATE_SKU_FORMID'
	
	UPDATE A SET FORM_ID=B.FORM_ID FROM SKU A JOIN PID01106 B ON A.PRODUCT_CODE=B.PRODUCT_CODE
	JOIN PIM01106 C ON C.MRR_ID=B.MRR_ID
	WHERE A.FORM_ID<>B.FORM_ID AND LEFT(C.MRR_ID,2)=@CCURLOCID
	
	IF @CCURLOCID=@CHOLOCID
		UPDATE A SET FORM_ID=B.FORM_ID FROM SKU A JOIN PID01106 B ON A.PRODUCT_CODE=B.PRODUCT_CODE
		LEFT OUTER JOIN (SELECT MRR_ID FROM PIM01106 WHERE LEFT(MRR_ID,2)=@CCURLOCID) C ON C.MRR_ID=B.MRR_ID
		JOIN LOCATION D ON D.DEPT_ID=LEFT(B.MRR_ID,2)
		WHERE A.FORM_ID<>B.FORM_ID AND C.MRR_ID IS NULL AND D.PUR_LOC=1
	
END		
