
IF NOT EXISTS (SELECT TOP 1'U' FROM BUYER_ORDER_WPS_LINK)
BEGIN
 INSERT BUYER_ORDER_WPS_LINK	( BO_DET_ROW_ID, WPS_DET_ROW_ID )  
 SELECT 	  BO_DET_ROW_ID,A.ROW_ID  WPS_DET_ROW_ID 
 FROM WPS_DET A (NOLOCK)
 JOIN WPS_MST B (NOLOCK) ON A.PS_ID=B.PS_ID 
 join BUYER_ORDER_DET bd on bd.row_id =a.BO_DET_ROW_ID
 WHERE B.CANCELLED =0 AND B.ENTRY_MODE =3
 AND A.BO_DET_ROW_ID <>''
 


UPDATE A SET INV_QTY =B.INV_QTY  FROM BUYER_ORDER_DET A
JOIN
(

SELECT B.BO_DET_ROW_ID ,SUM(B.QUANTITY) AS INV_QTY FROM BUYER_ORDER_WPS_LINK A
JOIN WPS_DET  B (NOLOCK) ON A.WPS_DET_ROW_ID =B.ROW_ID 
JOIN WPS_MST MST (NOLOCK) ON B.PS_ID =MST.PS_ID 
WHERE MST.CANCELLED =0 AND MST.ENTRY_MODE =3
GROUP BY B.BO_DET_ROW_ID
) B ON A.ROW_ID =B.BO_DET_ROW_ID 


END 


IF NOT EXISTS (SELECT TOP 1'U' FROM BUYER_ORDER_WSL_LINK)
BEGIN
 INSERT BUYER_ORDER_WSL_LINK	( BO_DET_ROW_ID, IND_ROW_ID )  
 SELECT 	  BO_DET_ROW_ID,A.ROW_ID  WPS_DET_ROW_ID 
 FROM ind01106 A 
 JOIN inm01106 B ON A.inv_id=B.inv_id 
 join BUYER_ORDER_DET bd on bd.row_id =a.BO_DET_ROW_ID
 WHERE B.CANCELLED =0 AND B.ENTRY_MODE =3
 AND A.BO_DET_ROW_ID <>''


UPDATE A SET INV_QTY =isnull(a.INV_QTY,0)+isnull(B.INV_QTY,0) 
FROM BUYER_ORDER_DET A
JOIN
(

SELECT B.BO_DET_ROW_ID ,SUM(B.QUANTITY) AS INV_QTY FROM BUYER_ORDER_WSL_LINK A
JOIN ind01106  B (nolock) ON A.IND_ROW_ID =B.ROW_ID 
JOIN INM01106 MST (nolock) ON B.inv_id =MST.inv_id 
WHERE MST.CANCELLED =0 AND MST.ENTRY_MODE =3
GROUP BY B.BO_DET_ROW_ID
) B ON A.ROW_ID =B.BO_DET_ROW_ID 


END 