
-- FUNCTION TO RETURN TEXT STRING CONTAINING VOUCHER DETAILS WITH
-- A/C NAME AND DR/CR AMOUNT AGAINST A GIVEN VOUCHER ID

CREATE FUNCTION FN_GETVDDETAILSSTR (@CVMID VARCHAR(100),@CTABLENAME VARCHAR(30),@CDEPTID CHAR(2),@DVOUCHERDT DATETIME )
RETURNS VARCHAR(500)
--WITH ENCRYPTION
AS
BEGIN
	DECLARE @CACNAME VARCHAR(50),@NAMOUNT NUMERIC(10,2),@CEXPR VARCHAR(8000),
	@CAMOUNTSTR VARCHAR(50) 
	
	IF @CTABLENAME='VM_DATAAUDIT'
		DECLARE ABCDATAAUDIT CURSOR FOR SELECT AC_NAME,SUM(DEBIT_AMOUNT-CREDIT_AMOUNT)  AS AMOUNT FROM VD_DATAAUDIT A 
		JOIN LM01106 B ON A.AC_CODE=B.AC_CODE JOIN VM_DATAAUDIT C ON C.VM_ID=A.VM_ID 
		WHERE (DEBIT_AMOUNT<>0 OR CREDIT_AMOUNT<>0) AND 
		((@CVMID<>'' AND A.VM_ID=@CVMID ) OR (@CVMID='' AND DEPT_ID=@CDEPTID AND BILL_DT=@DVOUCHERDT AND
		 BILL_TYPE='SLS')) GROUP BY AC_NAME
	ELSE
		DECLARE ABCDATAAUDIT CURSOR FOR SELECT AC_NAME,SUM(DEBIT_AMOUNT-CREDIT_AMOUNT) AS AMOUNT FROM VD01106 A
		JOIN LM01106 B ON A.AC_CODE=B.AC_CODE JOIN VM01106 C ON C.VM_ID=A.VM_ID
		WHERE (DEBIT_AMOUNT<>0 OR CREDIT_AMOUNT<>0) AND
		((@CVMID<>'' AND A.VM_ID=@CVMID ) OR (@CVMID='' AND  DEPT_ID=@CDEPTID AND BILL_DT=@DVOUCHERDT AND
		  BILL_TYPE='SLS' AND CANCELLED=0)) GROUP BY AC_NAME
	
	SET @CEXPR=''
	OPEN ABCDATAAUDIT
	FETCH NEXT FROM ABCDATAAUDIT INTO @CACNAME,@NAMOUNT
	WHILE @@FETCH_STATUS=0
	BEGIN
		SET @CAMOUNTSTR=LTRIM(RTRIM(STR(@NAMOUNT,10,2)))+' '+(CASE WHEN @NAMOUNT>0 THEN 'DR' ELSE 'CR' END)
		
		SET @CEXPR=@CEXPR+(CASE WHEN @CEXPR<>'' THEN ',     ' ELSE '' END)+@CACNAME+'-'+@CAMOUNTSTR
		FETCH NEXT FROM ABCDATAAUDIT INTO @CACNAME,@NAMOUNT
	END
	
	CLOSE ABCDATAAUDIT
	DEALLOCATE ABCDATAAUDIT
	
	RETURN @CEXPR
END
