CREATE FUNCTION FN3S_FINYEAR_DISPLAY
(
	@CFINYEAR VARCHAR(10)
)
RETURNS 
VARCHAR(10)
AS
BEGIN
DECLARE @CDIS_FINYEAR VARCHAR(10)

SET @CDIS_FINYEAR='20'
				  +CONVERT(VARCHAR(2),(CONVERT(NUMERIC(2),RIGHT(@CFINYEAR,2))-1))
				  +'-'
				  +RIGHT(@CFINYEAR,2)

RETURN @CDIS_FINYEAR
END
--END OF FUNCTION - FN3S_FINYEAR_DISPLAY
