CREATE FUNCTION FN_CHECKHO() 
RETURNS BIT
--WITH ENCRYPTION
AS
BEGIN
	DECLARE @CCURLOCID CHAR(2),@CHOLOCID CHAR(2),@BHO BIT
	
	SELECT TOP 1 @CCURLOCID=VALUE FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION='LOCATION_ID'	
	SELECT TOP 1 @CHOLOCID=VALUE FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION='HO_LOCATION_ID'
	
	IF @CCURLOCID=@CHOLOCID
		SET @BHO=1
	ELSE
		SET @BHO=0
	
	RETURN @BHO
END
