CREATE FUNCTION FN_LAST_DATE
( @NMONTH INT, @NYEAR INT )
RETURNS DATETIME
--WITH ENCRYPTION
AS 
BEGIN
	IF @NMONTH = 12
		SELECT @NMONTH = 1, @NYEAR=@NYEAR+1
	ELSE 
		SET @NMONTH = @NMONTH + 1

	RETURN DATEADD(DD, -1, CAST( CAST(@NYEAR AS VARCHAR(10))+'-'+CAST(@NMONTH AS VARCHAR(10))+'-1' AS DATETIME ) )
END
