CREATE FUNCTION DBO.FN3S_CHECK_DUP_WOD_PRODUCT_CODE
(
	 @CROW_ID VARCHAR(40)
	,@CPRODUCT_CODE VARCHAR(50)
)
RETURNS BIT
AS
BEGIN
	DECLARE @BDUPEXISTS BIT
	SET @BDUPEXISTS=0

	IF EXISTS(SELECT TOP 1 'U' FROM WSL_ORDER_DET WHERE PRODUCT_CODE=@CPRODUCT_CODE AND ISNULL(CANCELLED,0)=0 AND ISNULL(@CPRODUCT_CODE,'')<>'' AND ROW_ID<>@CROW_ID)
		SET @BDUPEXISTS=1

	RETURN @BDUPEXISTS
END