CREATE FUNCTION FN_GETTIME
( @DDATETIME DATETIME )
RETURNS VARCHAR(10)
--WITH ENCRYPTION
AS 
BEGIN
	RETURN  (CASE WHEN DATEPART(HH, @DDATETIME)<10 THEN '0' ELSE '' END) + 
				CAST(DATEPART(HH, @DDATETIME) AS VARCHAR(2)) + 
			(CASE WHEN DATEPART(MI, @DDATETIME)<10 THEN '0' ELSE '' END) + 
				CAST(DATEPART(MI, @DDATETIME) AS VARCHAR(2)) +
			(CASE WHEN DATEPART(SS, @DDATETIME)<10 THEN '0' ELSE '' END) + 
				CAST(DATEPART(SS, @DDATETIME) AS VARCHAR(2))
END
