
CREATE FUNCTION DBO.CUST_ADDRESS(@CODE VARCHAR(100),@MODE INT,@PART INT,@TYPE VARCHAR(100)='CUS')
RETURNS VARCHAR(500)    
AS    
BEGIN    
  DECLARE @ADD VARCHAR(500)--,@TYPE VARCHAR(100)='CUS'    
  SET @MODE=1  
  IF @MODE=1 AND @TYPE='CUS'   
     BEGIN    
       IF @PART=0--PARTY_ADDRESS_1  
               SELECT TOP 1 @ADD=isnull(C.ADDRESS1 ,'')
               FROM CUSTDYM C      
               WHERE C.CUSTOMER_CODE=@CODE    
       ELSE IF @PART=1--PARTY_ADDRESS_2  
               SELECT TOP 1 @ADD=ADDRESS2    
			   FROM CUSTDYM C      
               WHERE C.CUSTOMER_CODE=@CODE    
       ELSE IF @PART=2--PARTY_ADDRESS_3  
               SELECT TOP 1 @ADD=ADDRESS0 
			   FROM CUSTDYM C      
               WHERE C.CUSTOMER_CODE=@CODE    
       ELSE IF @PART=3--PARTY_CITY  
               SELECT TOP 1 @ADD=CT.CITY    
               +CASE WHEN ISNULL(A.PINCODE,'')<>'' THEN '-'+A.PINCODE ELSE '' END    
               +CASE LEN(ST.[STATE]) WHEN 0 THEN '' ELSE CHAR(13) END+ST.[STATE]    
               FROM CUSTDYM C     
               JOIN AREA A ON C.AREA_CODE=A.AREA_CODE    
               JOIN CITY CT ON CT.CITY_CODE=A.CITY_CODE    
               LEFT JOIN [STATE] ST ON ST.STATE_CODE=CT.STATE_CODE    
               WHERE C.CUSTOMER_CODE=@CODE    
     END    
  ELSE IF @MODE=1 AND @TYPE='AC'      
	 BEGIN
	    SET @MODE=1
	    SELECT @ADD=ISNULL(ADDRESS0,'')
	    FROM LMV01106 WHERE AC_CODE=@CODE AND @PART=0
	    SELECT @ADD=ISNULL(ADDRESS1,'')
	    FROM LMV01106 WHERE AC_CODE=@CODE AND @PART=1
	    SELECT @ADD=ISNULL(ADDRESS2,'')
	    FROM LMV01106 WHERE AC_CODE=@CODE AND @PART=2
	    SELECT @ADD=ISNULL(AREA_NAME,'')+ISNULL(' '+CITY,'')+ISNULL(' '+[STATE],'')+ISNULL(' '+PINCODE,'')
	    FROM LMV01106 WHERE AC_CODE=@CODE AND @PART=3
	    --SELECT ADDRESS0,ADDRESS1,ADDRESS2,AREA_NAME,PINCODE,CITY,[STATE],REGION_NAME 
	    --FROM LMV01106 WHERE AC_CODE='0100000003'
	 END  
  ELSE    
     BEGIN    
        IF @PART=0--PARTY_ADDRESS_1  
			SELECT TOP 1 @ADD=TLAR.AREA_NAME  
			FROM LOCATION TL (NOLOCK)    
			LEFT JOIN AREA TLAR (NOLOCK) ON TL.AREA_CODE=TLAR.AREA_CODE        
			LEFT JOIN CITY TLCT (NOLOCK) ON TLAR.CITY_CODE=TLCT.CITY_CODE    
			WHERE TL.DEPT_ID=@CODE    
		ELSE IF @PART=1--PARTY_ADDRESS_2       
			SELECT TOP 1 @ADD=''  
		ELSE IF @PART=2--PARTY_ADDRESS_3  
			SELECT TOP 1 @ADD=''  
		ELSE IF @PART=3--PARTY_CITY  
			SELECT TOP 1 @ADD=TLCT.CITY    
			FROM LOCATION TL (NOLOCK)    
			LEFT JOIN AREA TLAR (NOLOCK) ON TL.AREA_CODE=TLAR.AREA_CODE        
			LEFT JOIN CITY TLCT (NOLOCK) ON TLAR.CITY_CODE=TLCT.CITY_CODE    
			WHERE TL.DEPT_ID=@CODE    
     END    
  SET @ADD=LTRIM(RTRIM(ISNULL(@ADD,'')))  
  --SET @ADD=CASE @PART WHEN 3 THEN REPLACE(LTRIM(RTRIM(@ADD)),'(WC)','') ELSE @ADD END  
  RETURN REPLACE(@ADD,'(WC)','')  
END


