CREATE FUNCTION DBO.IMAGE_SET_ON()
RETURNS VARCHAR(100)
AS
BEGIN
   DECLARE @SET_IMG VARCHAR(100)
   IF EXISTS(SELECT TOP 1 * FROM IMAGE_INFO_CONFIG WHERE SECTION=1)
	  SET @SET_IMG='SECTION'
   ELSE IF EXISTS(SELECT TOP 1 * FROM IMAGE_INFO_CONFIG WHERE SUB_SECTION=1)
   	  SET @SET_IMG='SUB_SECTION'
   ELSE IF EXISTS(SELECT TOP 1 * FROM IMAGE_INFO_CONFIG WHERE ARTICLE=1)
  	  SET @SET_IMG='ARTICLE'
   ELSE IF EXISTS(SELECT TOP 1 * FROM IMAGE_INFO_CONFIG WHERE PARA1=1)
  	  SET @SET_IMG='PARA1'
   ELSE IF EXISTS(SELECT TOP 1 * FROM IMAGE_INFO_CONFIG WHERE PARA2=1)
      SET @SET_IMG='PARA2'
   ELSE IF EXISTS(SELECT TOP 1 * FROM IMAGE_INFO_CONFIG WHERE PARA3=1)
      SET @SET_IMG='PARA3'
   ELSE IF EXISTS(SELECT TOP 1 * FROM IMAGE_INFO_CONFIG WHERE PARA4=1)
      SET @SET_IMG='PARA4'
   ELSE IF EXISTS(SELECT TOP 1 * FROM IMAGE_INFO_CONFIG WHERE PARA5=1)
	  SET @SET_IMG='PARA5'
   ELSE IF EXISTS(SELECT TOP 1 * FROM IMAGE_INFO_CONFIG WHERE PARA6=1)
      SET @SET_IMG='PARA6'
   ELSE IF EXISTS(SELECT TOP 1 * FROM IMAGE_INFO_CONFIG WHERE PRODUCT=1)
      SET @SET_IMG='PRODUCT'
   RETURN @SET_IMG  
END