CREATE FUNCTION DBO.FN_GETBILLSADJ(@CARCID VARCHAR(22))
RETURNS VARCHAR(1000)
--WITH ENCRYPTION
AS
BEGIN
	DECLARE @CBILLIDS VARCHAR(1000)
	
	SELECT @CBILLIDS=ISNULL(LTRIM(RTRIM(@CBILLIDS))+',','')+LTRIM(RTRIM(B.CM_NO)) 
	FROM CMM_CREDIT_RECEIPT A
	JOIN CMM01106 B ON A.CM_ID=B.CM_ID
	WHERE ADV_REC_ID=@CARCID
	
	RETURN @CBILLIDS
END
