CREATE PROCEDURE SP3S_VALIDATE_RACK_DATA(@NSPID INT)
AS
BEGIN
DECLARE @ERR BIT=0,@ERROR_MSG VARCHAR(1000)=''

SELECT TOP 1 @ERROR_MSG='Location '''+U.DEPT_ID+''' does not found'  
FROM RACKSETUP_IMPORT_UPLOAD U (NOLOCK)
LEFT JOIN LOCATION L (NOLOCK) ON U.DEPT_id=L.DEPT_id
WHERE  L.DEPT_ID IS NULL AND U.SP_ID=@nSPID
IF ISNULL(@ERROR_MSG,'')<>''
BEGIN
    SET @ERR=1
    GOTO END_PROC
END



IF OBJECT_ID('TEMPDB..#TMPDUPLICATE','U') IS NOT NULL 
   DROP TABLE #TMPDUPLICATE

SELECT DEPT_ID ,RACK_NO  
INTO #TMPDUPLICATE 
FROM RACKSETUP_IMPORT_UPLOAD A
WHERE SP_ID=@nSPID
GROUP BY DEPT_ID ,RACK_NO 
HAVING COUNT(*)>1

IF EXISTS (SELECT TOP 1'U' FROM #TMPDUPLICATE)
BEGIN
   SET @ERR=1
   SET @ERROR_MSG='DUPLICATE RECORD FOUND'
END



END_PROC:  
IF @ERR=0
   SELECT L.DEPT_ID,L.DEPT_NAME,L.dept_alias,L.area_code
		,A.rack_no, A1.area_name AS DEPT_AREA,C1.CITY AS DEPT_CITY,S1.state AS DEPT_STATE,''ERRMSG 
		FROM RACKSETUP_IMPORT_UPLOAD A (NOLOCK)
		JOIN LOCATION L (NOLOCK) ON A.DEPT_ID=L.DEPT_ID
		LEFT OUTER JOIN AREA A1(NOLOCK) ON A1.area_code=L.area_code
		LEFT OUTER JOIN CITY C1(NOLOCK) ON C1.CITY_CODE=A1.city_code
		LEFT OUTER JOIN STATE S1(NOLOCK) ON C1.state_code=S1.state_code

ELSE
	BEGIN
	  IF @ERROR_MSG ='DUPLICATE RECORD FOUND'
	  BEGIN
		   SELECT @ERROR_MSG AS ERRMSG,A.DEPT_ID,A.RACK_NO
		   FROM RACKSETUP_IMPORT_UPLOAD A
		   JOIN #TMPDUPLICATE B ON A.DEPT_ID=B.DEPT_ID AND A.RACK_NO=B.RACK_NO
		   WHERE A.SP_ID=@nSPID
	  END
	  ELSE
	   SELECT @ERROR_MSG ERRMSG     

	END 
END