create PROCEDURE SP_PROCESS_IMPORTDATA_SLSTRG
(
 @NSPID NUMERIC(4,0)=0
)        
AS        
BEGIN        
     
     DECLARE @NSTEP INT,@CERRORMSG varchar(1000)
  BEGIN TRY  
       
            PRINT 'DEPT NAME VALIDATION'  
            
           
            UPDATE A SET ERRMSG=' INVALID DEPT ID'
            FROM SLSTRG_IMPORT_UPLOAD A (NOLOCK)
            LEFT JOIN LOCATION B (NOLOCK) ON A.DEPT_ID =B.DEPT_ID 
            WHERE  SP_ID=@NSPID AND B.DEPT_NAME IS NULL
            
            IF OBJECT_ID ('TEMPDB..#TMPVALICATE','U') IS NOT NULL
               DROP TABLE #TMPVALICATE
           
            SELECT * 
            INTO #TMPVALICATE
            FROM SLSTRG_SLSTARGET_SETUP_UPLOAD
            WHERE  SP_ID=@NSPID
            
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='SUB_SECTION_NAME')
            BEGIN
                  
                  UPDATE A SET ERRMSG=' SUB SECTION  Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN SECTIOND SD (NOLOCK) ON A.SUB_SECTION_NAME =sd.sub_section_name
                  WHERE ISNULL(A.SUB_SECTION_NAME,'')<>'' AND sd.SUB_SECTION_NAME IS NULL
                  AND ISNULL(A.ERRMSG,'')=''
            
            END
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='SECTION_NAME')
            BEGIN
                  
                  UPDATE A SET ERRMSG= ' SECTION Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN SECTIONM SM (NOLOCK) ON A.SECTION_NAME =SM.section_name
                  WHERE ISNULL(A.SECTION_NAME,'')<>'' AND SM.SECTION_NAME IS NULL
                  AND ISNULL(A.ERRMSG,'')=''
            
            END
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ARTICLE_NO')
            BEGIN
                  UPDATE A SET ERRMSG= ' ARTICLE Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ARTICLE ART (NOLOCK) ON A.ARTICLE_NO =ART.ARTICLE_NO
                  WHERE ISNULL(A.ARTICLE_NO,'')<>'' AND ART.ARTICLE_NO IS NULL
                  AND ISNULL(A.ERRMSG,'')=''
            
            END
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='PARA1_NAME')
            BEGIN
                  UPDATE A SET ERRMSG=' COLOR Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN para1  P1 (NOLOCK) ON A.PARA1_NAME  =P1.PARA1_NAME
                  WHERE ISNULL(A.PARA1_NAME,'')<>'' AND P1.PARA1_NAME IS NULL
                  AND ISNULL(A.ERRMSG,'')=''
            
            END
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='PARA2_NAME')
            BEGIN
            
                  UPDATE A SET ERRMSG=' SIZE Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN PARA2  P1 (NOLOCK) ON A.PARA2_NAME  =P1.PARA2_NAME
                  WHERE ISNULL(A.PARA2_NAME,'')<>'' AND P1.PARA2_NAME IS NULL
                  AND ISNULL(A.ERRMSG,'')=''
            
            END
            
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='PARA3_NAME')
            BEGIN
                  UPDATE A SET ERRMSG= ' PARA3 Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN PARA3  P1 (NOLOCK) ON A.PARA3_NAME  =P1.PARA3_NAME
                  WHERE ISNULL(A.PARA3_NAME,'')<>'' AND P1.PARA3_NAME IS NULL
                  AND ISNULL(A.ERRMSG,'')=''
            
            END
            
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='PARA4_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='PARA4 Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN PARA4  P1 (NOLOCK) ON A.PARA4_NAME  =P1.PARA4_NAME
                  WHERE ISNULL(A.PARA4_NAME,'')<>'' AND P1.PARA4_NAME IS NULL
                  AND ISNULL(A.ERRMSG,'')=''
            
            END
           
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='PARA5_NAME')
            BEGIN
                  UPDATE A SET ERRMSG=' PARA5 Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN PARA5  P1 (NOLOCK) ON A.PARA5_NAME  =P1.PARA5_NAME
                  WHERE ISNULL(A.PARA5_NAME,'')<>'' AND P1.PARA5_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='PARA6_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='PARA6 Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN PARA6  P1 (NOLOCK) ON A.PARA6_NAME  =P1.PARA6_NAME
                  WHERE ISNULL(A.PARA6_NAME,'')<>'' AND P1.PARA6_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR1_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR1_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR1_MST  MST (NOLOCK) ON A.ATTR1_KEY_NAME  =MST.ATTR1_KEY_NAME
                  WHERE ISNULL(A.ATTR1_KEY_NAME,'')<>'' AND MST.ATTR1_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR2_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR2_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR2_MST  MST (NOLOCK) ON A.ATTR2_KEY_NAME  =MST.ATTR2_KEY_NAME
                  WHERE ISNULL(A.ATTR2_KEY_NAME,'')<>'' AND MST.ATTR2_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR3_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR3_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR3_MST  MST (NOLOCK) ON A.ATTR3_KEY_NAME  =MST.ATTR3_KEY_NAME
                  WHERE ISNULL(A.ATTR3_KEY_NAME,'')<>'' AND MST.ATTR3_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR4_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR4_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR4_MST  MST (NOLOCK) ON A.ATTR4_KEY_NAME  =MST.ATTR4_KEY_NAME
                  WHERE ISNULL(A.ATTR4_KEY_NAME,'')<>'' AND MST.ATTR4_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR5_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR5_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR5_MST  MST (NOLOCK) ON A.ATTR5_KEY_NAME  =MST.ATTR5_KEY_NAME
                  WHERE ISNULL(A.ATTR5_KEY_NAME,'')<>'' AND MST.ATTR5_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR6_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR6_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR6_MST  MST (NOLOCK) ON A.ATTR6_KEY_NAME  =MST.ATTR6_KEY_NAME
                  WHERE ISNULL(A.ATTR6_KEY_NAME,'')<>'' AND MST.ATTR6_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR7_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR7_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR7_MST  MST (NOLOCK) ON A.ATTR7_KEY_NAME  =MST.ATTR7_KEY_NAME
                  WHERE ISNULL(A.ATTR7_KEY_NAME,'')<>'' AND MST.ATTR7_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR8_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR8_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR8_MST  MST (NOLOCK) ON A.ATTR8_KEY_NAME  =MST.ATTR8_KEY_NAME
                  WHERE ISNULL(A.ATTR8_KEY_NAME,'')<>'' AND MST.ATTR8_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR9_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR9_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR9_MST  MST (NOLOCK) ON A.ATTR9_KEY_NAME  =MST.ATTR9_KEY_NAME
                  WHERE ISNULL(A.ATTR9_KEY_NAME,'')<>'' AND MST.ATTR9_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR10_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR10_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR10_MST  MST (NOLOCK) ON A.ATTR10_KEY_NAME  =MST.ATTR10_KEY_NAME
                  WHERE ISNULL(A.ATTR10_KEY_NAME,'')<>'' AND MST.ATTR10_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR11_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR11_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR11_MST  MST (NOLOCK) ON A.ATTR11_KEY_NAME  =MST.ATTR11_KEY_NAME
                  WHERE ISNULL(A.ATTR11_KEY_NAME,'')<>'' AND MST.ATTR11_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR12_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR12_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR12_MST  MST (NOLOCK) ON A.ATTR12_KEY_NAME  =MST.ATTR12_KEY_NAME
                  WHERE ISNULL(A.ATTR12_KEY_NAME,'')<>'' AND MST.ATTR12_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR13_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR13_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR13_MST  MST (NOLOCK) ON A.ATTR13_KEY_NAME  =MST.ATTR13_KEY_NAME
                  WHERE ISNULL(A.ATTR13_KEY_NAME,'')<>'' AND MST.ATTR13_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            
           IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR14_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR14_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR14_MST  MST (NOLOCK) ON A.ATTR14_KEY_NAME  =MST.ATTR14_KEY_NAME
                  WHERE ISNULL(A.ATTR14_KEY_NAME,'')<>'' AND MST.ATTR14_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            
           IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR15_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR15_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR15_MST  MST (NOLOCK) ON A.ATTR15_KEY_NAME  =MST.ATTR15_KEY_NAME
                  WHERE ISNULL(A.ATTR15_KEY_NAME,'')<>'' AND MST.ATTR15_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            
           IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR16_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR16_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR16_MST  MST (NOLOCK) ON A.ATTR16_KEY_NAME  =MST.ATTR16_KEY_NAME
                  WHERE ISNULL(A.ATTR16_KEY_NAME,'')<>'' AND MST.ATTR16_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR17_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR17_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR17_MST  MST (NOLOCK) ON A.ATTR17_KEY_NAME  =MST.ATTR17_KEY_NAME
                  WHERE ISNULL(A.ATTR17_KEY_NAME,'')<>'' AND MST.ATTR17_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            
           IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR18_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR18_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR18_MST  MST (NOLOCK) ON A.ATTR18_KEY_NAME  =MST.ATTR18_KEY_NAME
                  WHERE ISNULL(A.ATTR18_KEY_NAME,'')<>'' AND MST.ATTR18_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            
           IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR19_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR19_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR19_MST  MST (NOLOCK) ON A.ATTR19_KEY_NAME  =MST.ATTR19_KEY_NAME
                  WHERE ISNULL(A.ATTR19_KEY_NAME,'')<>'' AND MST.ATTR19_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            
           IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR20_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR20_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR20_MST  MST (NOLOCK) ON A.ATTR20_KEY_NAME  =MST.ATTR20_KEY_NAME
                  WHERE ISNULL(A.ATTR20_KEY_NAME,'')<>'' AND MST.ATTR20_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            
           IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR21_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR21_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR21_MST  MST (NOLOCK) ON A.ATTR21_KEY_NAME  =MST.ATTR21_KEY_NAME
                  WHERE ISNULL(A.ATTR21_KEY_NAME,'')<>'' AND MST.ATTR21_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR22_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR22_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR22_MST  MST (NOLOCK) ON A.ATTR22_KEY_NAME  =MST.ATTR22_KEY_NAME
                  WHERE ISNULL(A.ATTR22_KEY_NAME,'')<>'' AND MST.ATTR22_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            
           IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR23_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR23_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR23_MST  MST (NOLOCK) ON A.ATTR23_KEY_NAME  =MST.ATTR23_KEY_NAME
                  WHERE ISNULL(A.ATTR23_KEY_NAME,'')<>'' AND MST.ATTR23_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR24_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR24_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR24_MST  MST (NOLOCK) ON A.ATTR24_KEY_NAME  =MST.ATTR24_KEY_NAME
                  WHERE ISNULL(A.ATTR24_KEY_NAME,'')<>'' AND MST.ATTR24_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='ATTR25_KEY_NAME')
            BEGIN
                  UPDATE A SET ERRMSG='ATTR25_KEY_NAME Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN ATTR25_MST  MST (NOLOCK) ON A.ATTR25_KEY_NAME  =MST.ATTR25_KEY_NAME
                  WHERE ISNULL(A.ATTR25_KEY_NAME,'')<>'' AND MST.ATTR25_KEY_NAME IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            IF EXISTS (SELECT TOP 1 'U' FROM #TMPVALICATE WHERE SLSTARGET_PARA_NAME='emp_name')
            BEGIN
                  UPDATE A SET ERRMSG='emp Name Does Not Exists'
                  FROM  SLSTRG_IMPORT_UPLOAD A (NOLOCK)
                  LEFT JOIN employee   MST (NOLOCK) ON A.emp_name  =MST.emp_name 
                  WHERE ISNULL(A.emp_name,'')<>'' AND MST.emp_name IS NULL
                   AND ISNULL(A.ERRMSG,'')=''
            
            END
            
           
            
            UPDATE A SET DEPT_NAME =B.DEPT_NAME ,
                         ARTICLE_CODE=ISNULL(ART.ARTICLE_CODE,'00000000'),
                         SUB_SECTION_CODE=ISNULL(SD.SUB_SECTION_CODE ,'00000000'),
                         SECTION_CODE=ISNULL(SM.section_code ,'00000000'),
                         PARA1_CODE=ISNULL(P1.PARA1_CODE ,'0000000'),
                         PARA2_CODE=ISNULL(P2.PARA2_CODE ,'0000000'),
                         PARA3_CODE=ISNULL(P3.PARA3_CODE ,'0000000'),
                         PARA4_CODE=ISNULL(P4.PARA4_CODE ,'0000000'),
                         PARA5_CODE=ISNULL(P5.PARA5_CODE ,'0000000'),
                         PARA6_CODE=ISNULL(P6.PARA6_CODE ,'0000000'),
                         ATTR1_KEY_CODE=ISNULL(ATTR1_MST.ATTR1_KEY_CODE ,'0000000'),
                         ATTR2_KEY_CODE=ISNULL(ATTR2_MST.ATTR2_KEY_CODE ,'0000000'),
                         ATTR3_KEY_CODE=ISNULL(ATTR3_MST.ATTR3_KEY_CODE ,'0000000'),
                         ATTR4_KEY_CODE=ISNULL(ATTR4_MST.ATTR4_KEY_CODE ,'0000000'),
                         ATTR5_KEY_CODE=ISNULL(ATTR5_MST.ATTR5_KEY_CODE ,'0000000'),
                         ATTR6_KEY_CODE=ISNULL(ATTR6_MST.ATTR6_KEY_CODE ,'0000000'),
                         ATTR7_KEY_CODE=ISNULL(ATTR7_MST.ATTR7_KEY_CODE ,'0000000'),
                         ATTR8_KEY_CODE=ISNULL(ATTR8_MST.ATTR8_KEY_CODE ,'0000000'),
                         ATTR9_KEY_CODE=ISNULL(ATTR9_MST.ATTR9_KEY_CODE ,'0000000'),
                         ATTR10_KEY_CODE=ISNULL(ATTR10_MST.ATTR10_KEY_CODE ,'0000000'),
                         ATTR11_KEY_CODE=ISNULL(ATTR11_MST.ATTR11_KEY_CODE ,'0000000'),
                         ATTR12_KEY_CODE=ISNULL(ATTR12_MST.ATTR12_KEY_CODE ,'0000000'),
                         ATTR13_KEY_CODE=ISNULL(ATTR13_MST.ATTR13_KEY_CODE ,'0000000'),
                         ATTR14_KEY_CODE=ISNULL(ATTR14_MST.ATTR14_KEY_CODE ,'0000000'),
                         ATTR15_KEY_CODE=ISNULL(ATTR15_MST.ATTR15_KEY_CODE ,'0000000'),
                         ATTR16_KEY_CODE=ISNULL(ATTR16_MST.ATTR16_KEY_CODE ,'0000000'),
                         ATTR17_KEY_CODE=ISNULL(ATTR17_MST.ATTR17_KEY_CODE ,'0000000'),
                         ATTR18_KEY_CODE=ISNULL(ATTR18_MST.ATTR18_KEY_CODE ,'0000000'),
                         ATTR19_KEY_CODE=ISNULL(ATTR19_MST.ATTR19_KEY_CODE ,'0000000'),
                         ATTR20_KEY_CODE=ISNULL(ATTR20_MST.ATTR20_KEY_CODE ,'0000000'),
                         ATTR21_KEY_CODE=ISNULL(ATTR21_MST.ATTR21_KEY_CODE ,'0000000'),
                         ATTR22_KEY_CODE=ISNULL(ATTR22_MST.ATTR22_KEY_CODE ,'0000000'),
                         ATTR23_KEY_CODE=ISNULL(ATTR23_MST.ATTR23_KEY_CODE ,'0000000'),
                         ATTR24_KEY_CODE=ISNULL(ATTR24_MST.ATTR24_KEY_CODE ,'0000000'),
                         ATTR25_KEY_CODE=ISNULL(ATTR25_MST.ATTR25_KEY_CODE ,'0000000'),
                         emp_CODE=ISNULL(employee.emp_code  ,'0000000')
            FROM SLSTRG_IMPORT_UPLOAD A (NOLOCK)
            LEFT JOIN LOCATION B (NOLOCK) ON A.DEPT_ID =B.DEPT_ID 
            LEFT JOIN ARTICLE ART  (NOLOCK) ON ART.article_no  =ISNULL(A.ARTICLE_NO ,'')
            LEFT JOIN Sectiond SD (NOLOCK) ON SD.sub_section_name =ISNULL(A.sub_section_name ,'')
            LEFT JOIN SectionM SM (NOLOCK) ON SM.section_name =ISNULL(A.section_name ,'')
            LEFT JOIN PARA1 P1 (NOLOCK) ON P1.PARA1_NAME=ISNULL(A.PARA1_NAME ,'')
            LEFT JOIN PARA2 P2 (NOLOCK) ON P2.PARA2_NAME=ISNULL(A.PARA2_NAME ,'')
            LEFT JOIN PARA3 P3 (NOLOCK) ON P3.PARA3_NAME=ISNULL(A.PARA3_NAME ,'')
            LEFT JOIN PARA4 P4 (NOLOCK) ON P4.PARA4_NAME=ISNULL(A.PARA4_NAME ,'')
            LEFT JOIN PARA5 P5 (NOLOCK) ON P5.PARA5_NAME=ISNULL(A.PARA5_NAME ,'')
            LEFT JOIN PARA6 P6 (NOLOCK) ON P6.PARA6_NAME=ISNULL(A.PARA6_NAME ,'')
			LEFT JOIN ATTR1_MST (NOLOCK) ON ATTR1_MST.attr1_key_name=A.ATTR1_KEY_NAME
			LEFT JOIN ATTR2_MST (NOLOCK) ON ATTR2_MST.ATTR2_KEY_NAME=A.ATTR2_KEY_NAME
			LEFT JOIN ATTR3_MST (NOLOCK) ON ATTR3_MST.ATTR3_KEY_NAME=A.ATTR3_KEY_NAME
			LEFT JOIN ATTR4_MST (NOLOCK) ON ATTR4_MST.ATTR4_KEY_NAME=A.ATTR4_KEY_NAME
			LEFT JOIN ATTR5_MST (NOLOCK) ON ATTR5_MST.ATTR5_KEY_NAME=A.ATTR5_KEY_NAME
			LEFT JOIN ATTR6_MST (NOLOCK) ON ATTR6_MST.ATTR6_KEY_NAME=A.ATTR6_KEY_NAME
			LEFT JOIN ATTR7_MST (NOLOCK) ON ATTR7_MST.ATTR7_KEY_NAME=A.ATTR7_KEY_NAME
			LEFT JOIN ATTR8_MST (NOLOCK) ON ATTR8_MST.ATTR8_KEY_NAME=A.ATTR8_KEY_NAME
			LEFT JOIN ATTR9_MST (NOLOCK) ON ATTR9_MST.ATTR9_KEY_NAME=A.ATTR9_KEY_NAME
			LEFT JOIN ATTR10_MST (NOLOCK) ON ATTR10_MST.ATTR10_KEY_NAME=A.ATTR10_KEY_NAME
			LEFT JOIN ATTR11_MST (NOLOCK) ON ATTR11_MST.ATTR11_KEY_NAME=A.ATTR11_KEY_NAME
			LEFT JOIN ATTR12_MST (NOLOCK) ON ATTR12_MST.ATTR12_KEY_NAME=A.ATTR12_KEY_NAME
			LEFT JOIN ATTR13_MST (NOLOCK) ON ATTR13_MST.ATTR13_KEY_NAME=A.ATTR13_KEY_NAME
			LEFT JOIN ATTR14_MST (NOLOCK) ON ATTR14_MST.ATTR14_KEY_NAME=A.ATTR14_KEY_NAME
			LEFT JOIN ATTR15_MST (NOLOCK) ON ATTR15_MST.ATTR15_KEY_NAME=A.ATTR15_KEY_NAME
			LEFT JOIN ATTR16_MST (NOLOCK) ON ATTR16_MST.ATTR16_KEY_NAME=A.ATTR16_KEY_NAME
			LEFT JOIN ATTR17_MST (NOLOCK) ON ATTR17_MST.ATTR17_KEY_NAME=A.ATTR17_KEY_NAME
			LEFT JOIN ATTR18_MST (NOLOCK) ON ATTR18_MST.ATTR18_KEY_NAME=A.ATTR18_KEY_NAME
			LEFT JOIN ATTR19_MST (NOLOCK) ON ATTR19_MST.ATTR19_KEY_NAME=A.ATTR19_KEY_NAME
			LEFT JOIN ATTR20_MST (NOLOCK) ON ATTR20_MST.ATTR20_KEY_NAME=A.ATTR20_KEY_NAME
			LEFT JOIN ATTR21_MST (NOLOCK) ON ATTR21_MST.ATTR21_KEY_NAME=A.ATTR21_KEY_NAME
			LEFT JOIN ATTR22_MST (NOLOCK) ON ATTR22_MST.ATTR22_KEY_NAME=A.ATTR22_KEY_NAME
			LEFT JOIN ATTR23_MST (NOLOCK) ON ATTR23_MST.ATTR23_KEY_NAME=A.ATTR23_KEY_NAME
			LEFT JOIN ATTR24_MST (NOLOCK) ON ATTR24_MST.ATTR24_KEY_NAME=A.ATTR24_KEY_NAME
			LEFT JOIN ATTR25_MST (NOLOCK) ON ATTR25_MST.ATTR25_KEY_NAME=A.ATTR25_KEY_NAME
			LEFT JOIN employee (NOLOCK) ON employee.emp_name =A.emp_name
            where a.SP_ID=@NSPID
            
            SELECT A.* 
            FROM SLSTRG_IMPORT_UPLOAD A
            WHERE A.SP_ID =@NSPID
            
           
           
         

  GOTO END_PROC        
          
 END TRY        
         
 BEGIN CATCH        
  SET @CERRORMSG = 'PROCEDURE SP_PROCESS_IMPORTDATA_SLSTRG : STEP- ' + LTRIM(STR(@NSTEP)) + ' SQL ERROR: #' + LTRIM(STR(ERROR_NUMBER())) + ' ' + ERROR_MESSAGE()        
  GOTO END_PROC        
 END CATCH        
         
END_PROC:        
        
END        
---END OF PROCEDURE - SP_PROCESS_IMPORTDATA_SLSTRG
