
create PROCEDURE SP_PROCESS_IMPORTDATA_BUYPLAN
@CSOURCETABLE VARCHAR(200),
@CTARGETTABLE VARCHAR(200),
@CBUDGETPLANMEMONO VARCHAR(10)='' 
--WITH ENCRYPTION
AS
BEGIN
	
	BEGIN TRY

		DECLARE @OUTPUT TABLE(TYPE VARCHAR(50),MESSAGE VARCHAR(200),VALUE VARCHAR(200)) 
		
		DECLARE @TERROR TABLE(SORTORDER INT,TYPE VARCHAR(50),MESSAGE VARCHAR(200),VALUE VARCHAR(200)) 
		
		DECLARE @TNUMCOLUM TABLE (NUMERICCOLUMN VARCHAR(100))

		DECLARE @CCMD NVARCHAR(MAX),@NSTEP INT,@CERRORMSG VARCHAR(MAX),@CCOLNAME VARCHAR(100),@BPROCEED BIT
		,@BDONOTCREATEMASTER BIT,@CPARA1NAME VARCHAR(50),@CPARA2NAME VARCHAR(50),@CPARA3NAME VARCHAR(50)
		,@CPARA4NAME VARCHAR(50),@CPARA5NAME VARCHAR(50),@CPARA6NAME VARCHAR(50),@CPOROWID VARCHAR(MAX)
		,@CSEARCHBUDGETPLAN VARCHAR(200)
		
		
		SELECT @CSOURCETABLE=REPLACE(@CSOURCETABLE,'[','')
		SELECT @CSOURCETABLE=REPLACE(@CSOURCETABLE,']','')
		SELECT @CTARGETTABLE=REPLACE(@CTARGETTABLE,'[','')
		SELECT @CTARGETTABLE=REPLACE(@CTARGETTABLE,']','')
		
		SET @NSTEP=10
		
		SELECT TOP 1 @CSEARCHBUDGETPLAN=BUDGET_PLAN_NAME FROM BUDGET_PLAN_MST WHERE MEMO_NO=@CBUDGETPLANMEMONO
				
		IF ISNULL(@CSEARCHBUDGETPLAN,'')=''
		BEGIN
			INSERT @TERROR(SORTORDER,TYPE,VALUE,MESSAGE)
			SELECT 1,'BUDGET PLAN','','INVALID BUDGET PLAN NAME SELECTED'
			
			GOTO END_PROC
		END	
		
		INSERT INTO @TNUMCOLUM 
		SELECT 'PURCHASE_PRICE' UNION
		SELECT 'QUANTITY' UNION
		SELECT 'MRP' 
		SET @NSTEP=20
		WHILE EXISTS (SELECT TOP 1 * FROM  @TNUMCOLUM)
		BEGIN
			 SET @CCOLNAME = (SELECT TOP 1 NUMERICCOLUMN FROM @TNUMCOLUM)

			 SET @CCMD=N'IF EXISTS(SELECT TOP 1 ''U'' FROM SYSCOLUMNS WHERE ID=OBJECT_ID('''+@CSOURCETABLE+''')
									   AND NAME='''+@CCOLNAME+''')		
							SET @BPROCEED=1
						 ELSE
							SET @BPROCEED=0'
			 EXEC SP_EXECUTESQL  @CCMD,N'@BPROCEED BIT OUTPUT',@BPROCEED OUTPUT
			 
			 SET @NSTEP=30
			 IF @BPROCEED=1
			 BEGIN
			 					 	 			   		 
				 SET @CCMD = N'SELECT ''ALERT'' AS TYPE, '''+@CCOLNAME+' SHOULD BE NUMERIC AND NOT NEGATIVE'' AS MESSAGE,'+@CCOLNAME+' AS VALUE
							   FROM '+@CSOURCETABLE+' WHERE (ISNUMERIC('+@CCOLNAME+') = 0 OR LEFT(LTRIM('+@CCOLNAME+'),1) = ''-'' OR CHARINDEX('','','+@CCOLNAME+')>0) AND '+@CCOLNAME+' IS NOT NULL' 
				 PRINT @CCMD
				 INSERT INTO @TERROR(TYPE,MESSAGE,VALUE)
				 EXEC SP_EXECUTESQL @CCMD
				 
			 END
			
			 DELETE FROM @TNUMCOLUM WHERE NUMERICCOLUMN= @CCOLNAME
		END
			
		SET @NSTEP=40
		DECLARE @CROWID VARCHAR(200),@CFILTER VARCHAR(200),@NLOOP INT
		
		--SET @CCMD=N'UPDATE '+@CSOURCETABLE+' SET ROW_ID=''LATER_''+LTRIM(RTRIM(NEWID()))'
		--PRINT @CCMD
		--EXEC SP_EXECUTESQL @CCMD
		
		
		
	   SET @NSTEP=50  

	  
	  IF OBJECT_ID('TEMPDB..#TMPMASTERSENC','U') IS NOT NULL
			DROP TABLE #TMPMASTERSENC
	  
	  SELECT ARTICLE_NO,PARA1_NAME,PARA2_NAME,PARA3_NAME,PARA4_NAME,PARA5_NAME,PARA6_NAME,product_code 		
	  INTO #TMPMASTERSENC FROM SKU A 
	  JOIN ARTICLE B ON A.ARTICLE_CODE=B.ARTICLE_CODE
	  JOIN PARA1 P1 ON P1.PARA1_CODE=A.PARA1_CODE
	  JOIN PARA2 P2 ON P2.PARA2_CODE=A.PARA2_CODE
	  JOIN PARA3 P3 ON P3.PARA3_CODE=A.PARA3_CODE
	  JOIN PARA4 P4 ON P4.PARA4_CODE=A.PARA4_CODE
	  JOIN PARA5 P5 ON P5.PARA5_CODE=A.PARA5_CODE
	  JOIN PARA6 P6 ON P6.PARA6_CODE=A.PARA6_CODE
	  WHERE 1=2
	  
	  SET @CCMD=N'UPDATE '+@CSOURCETABLE+' SET PARA3_NAME=ISNULL(PARA3_NAME,''NA''),PARA4_NAME=ISNULL(PARA4_NAME,''NA''),
				  PARA5_NAME=ISNULL(PARA5_NAME,''NA''),PARA6_NAME=ISNULL(PARA6_NAME,''NA'')'
	  EXEC SP_EXECUTESQL @CCMD    
	  
	   SET @CCMD=N'  UPDATE A SET ARTICLE_CODE=B.ARTICLE_CODE,
	  PARA1_CODe=P1.PaRA1_CODE,
	  PARA2_CODE=P2.PARA2_CODE
	   FROM  '+@CSOURCETABLE+' A
	  join sku (nolock) on a.product_code=sku.product_code 
	  JOIN ARTICLe B ON sku.ARTIClE_code=B.ARTICle_code  
	  JOIN PARa1 P1 oN P1.PARA1_code =sku.PARA1_code 
	  JOiN PARA2 P2 ON P2.PARa2_code=sku.PARA2_code 
	  where a.product_code<>'''' '
	  EXEC SP_EXECUTESQL @CCMD                      
	  
	  SET @NSTEP=60
	  
	  SET @CCMD=N'  UPDATE A SET ARTICLE_CODE=B.ARTICLE_CODE,
	  PARA1_CODe=P1.PaRA1_CODE,
	  PARA2_CODE=P2.PARA2_CODE
	   FROM  '+@CSOURCETABLE+' A
	  JOIN ARTICLe B ON A.ARTIClE_NO=B.ARTICle_NO 
	  JOIN PARa1 P1 oN P1.PARA1_NAMe=A.PARA1_NAMe 
	  JOiN PARA2 P2 ON P2.PARa2_NAmE=A.PARA2_NAME 
	  where a.product_code='''' '
	  EXEC SP_EXECUTESQL @CCMD  
	  
	  
	  
	   SET @CCMD=N'  UPDATE A SET PrODUCT_CODE =B.PrODUCT_CODE
	   FROM  '+@CSOURCETABLE+' A
	  JOIN SKU B ON A.ARTICLE_cODE=B.ARTICLE_CODE AND A.PARA1_CoDE=B.PARA1_CODE ANd A.PARa2_COde=B.PaRA2_CODE 
	   JOIN ARTICLE ART ON ART.ARTICLE_CODE=B.ARTICLE_CODE 
	   WHERE ISNULL(ART.coding_scheme,0)=1 AND ISNULL(A.PRODUCT_CODE,'''')=''''  '
	  EXEC SP_EXECUTESQL @CCMD      

	  
	  
	  SET @NSTEP=70  
	  SET @CCMD=N'INSERT #TMPMASTERSENC (ARTICLE_NO,PARA1_NAME,PARA2_NAME,PARA3_NAME,  
			 PARA4_NAME,PARA5_NAME,PARA6_NAME,product_code)  
			 
		   SELECT DISTINCT ISNULL(ARTICLE_NO,''''),ISNULL(PARA1_NAME,''''),ISNULL(PARA2_NAME,''''),
		   ISNULL(PARA3_NAME,''NA''),ISNULL(PARA4_NAME,''NA''),ISNULL(PARA5_NAME,''NA''),ISNULL(PARA6_NAME,''NA''),
		   ISNULL(product_code,'''')
		   FROM '+@CSOURCETABLE 
		  
		PRINT      @CCMD                     
		EXEC SP_EXECUTESQL @CCMD  
		
	
		
		   SET @NSTEP=80  
		INSERT @TERROR(SORTORDER,TYPE,VALUE,MESSAGE)
		SELECT DISTINCT 3,'PRODUCT_CODE',A.product_code,'PRODUCT CODE DOES NOT EXIST.'
		FROM #TMPMASTERSENC A
		LEFT JOIN SKU B ON A.product_code=B.product_code
		WHERE B.product_code IS NULL AND ISNULL(A.product_code,'') <>''                      
	

		IF NOT EXISTS (SELECT TOP 1 * FROM @TERROR)
		BEGIN
			SET @NSTEP=145

			EXEC UPDATEMASTERXN '',@CSOURCETABLE,'',@CTARGETTABLE,'ARTICLE_CODE','PARA1_CODE','PARA2_CODE',0,'',0,'',0,'',1
            
          SET @CCMD=N'  UPDATE A SET PARA3_CODe=P3.PaRA3_CODE,
		  PARA4_CODE=P4.PARA4_CODE,
		  PARA5_CODE=P5.PARA5_CODE,
		  PARA6_CODE=P6.PARA6_CODE
		   FROM  '+@CTARGETTABLE+' A
		  JOIN PARa3 P3 oN P3.PARA3_NAMe=A.PARA3_NAMe 
		  JOiN PARA4 P4 ON P4.PARa4_NAmE=A.PARA4_NAME
		  JOIN PARa5 P5 oN P5.PARA5_NAMe=A.PARA5_NAMe 
		  JOiN PARA6 P6 ON P6.PARa6_NAmE=A.PARA6_NAME
		   where isnull(a.product_code,'''')='''''
		   PRINT @CCMD
		  EXEC SP_EXECUTESQL @CCMD  

		    SET @CCMD=N'  UPDATE A SET PARA3_CODe=sku.PaRA3_CODE,
		  PARA4_CODE=sku.PARA4_CODE,
		  PARA5_CODE=sku.PARA5_CODE,
		  PARA6_CODE=sku.PARA6_CODE
		  FROM  '+@CTARGETTABLE+' A
		  JOIN SKU (NOLOCK) ON A.PRODUCT_CODE =SKU.PRODUCT_CODE 
		  where isnull(a.product_code,'''')<>'''''
		   PRINT @CCMD
		  EXEC SP_EXECUTESQL @CCMD  
		  
			SET @NSTEP=150	
		   SET @CCMD=N'UPDATE '+@CTARGETTABLE+' SET QUANTITY=ISNULL(QUANTITY,0),  
			 ARTICLE_CODE=ISNULL(ARTICLE_CODE,''''),PARA1_CODE=ISNULL(PARA1_CODE,''0000000''),PARA2_CODE=ISNULL(PARA2_CODE,''0000000''),  
			 PARA3_CODE=ISNULL(PARA3_CODE,''0000000''),PARA4_CODE=ISNULL(PARA4_CODE,''0000000''),PARA5_CODE=ISNULL(PARA5_CODE,''0000000''),  
			 PARA6_CODE=ISNULL(PARA6_CODE,''0000000'')'  
		  PRINT @CCMD  
		  EXEC SP_EXECUTESQL @CCMD 

			SET @NSTEP=152
			SET @CCMD=N'UPDATE A SET SUB_SECTION_NAME=C.SUB_SECTION_NAME,SECTION_NAME=D.SECTION_NAME
						FROM '+@CTARGETTABLE+' A
						JOIN  ARTICLE B ON A.ARTICLE_NO=B.ARTICLE_NO
						JOIN  SECTIOND C ON C.SUB_SECTION_CODE=B.SUB_SECTION_CODE
						JOIN  SECTIONM D ON D.SECTION_CODE=C.SECTION_CODE'
			EXEC SP_EXECUTESQL @CCMD

			
			--SET @NSTEP=155
			--SET @CCMD=N'UPDATE '+@CTARGETTABLE+' SET ARTICLE_CODE=B.ARTICLE_CODE FROM ARTICLE B 
			--            WHERE B.ARTICLE_NO='+@CTARGETTABLE+'.ARTICLE_NO'
			--EXEC SP_EXECUTESQL @CCMD
			
			--SET @NSTEP=160			
			--SET @CCMD=N'UPDATE '+@CTARGETTABLE+' SET PARA1_CODE=B.PARA1_CODE FROM PARA1 B 
			--            WHERE B.PARA1_NAME='+@CTARGETTABLE+'.PARA1_NAME'
			--EXEC SP_EXECUTESQL @CCMD
			
			--SET @NSTEP=170
			--SET @CCMD=N'UPDATE '+@CTARGETTABLE+' SET PARA2_CODE=B.PARA2_CODE FROM PARA2 B 
			--            WHERE B.PARA2_NAME='+@CTARGETTABLE+'.PARA2_NAME'
			--EXEC SP_EXECUTESQL @CCMD

			--SET @NSTEP=175
			--SET @CCMD=N'UPDATE '+@CTARGETTABLE+' SET PARA3_CODE=B.PARA3_CODE FROM PARA3 B 
			--            WHERE B.PARA3_NAME='+@CTARGETTABLE+'.PARA3_NAME'
			--EXEC SP_EXECUTESQL @CCMD

			--SET @NSTEP=180
			--SET @CCMD=N'UPDATE '+@CTARGETTABLE+' SET PARA4_CODE=B.PARA4_CODE FROM PARA4 B 
			--            WHERE B.PARA4_NAME='+@CTARGETTABLE+'.PARA4_NAME'
			--EXEC SP_EXECUTESQL @CCMD

			--SET @NSTEP=190
			--SET @CCMD=N'UPDATE '+@CTARGETTABLE+' SET PARA5_CODE=B.PARA5_CODE FROM PARA5 B 
			--            WHERE B.PARA5_NAME='+@CTARGETTABLE+'.PARA5_NAME'
			--EXEC SP_EXECUTESQL @CCMD

			--SET @NSTEP=200
			--SET @CCMD=N'UPDATE '+@CTARGETTABLE+' SET PARA6_CODE=B.PARA6_CODE FROM PARA6 B 
			--            WHERE B.PARA6_NAME='+@CTARGETTABLE+'.PARA6_NAME'
			--EXEC SP_EXECUTESQL @CCMD
			
			
		
										
															
									
		END
				
		GOTO END_PROC
		
	END TRY
	
	BEGIN CATCH
		SET @CERRORMSG = 'PROCEDURE SP_PROCESS_IMPORTDATA_BUYPLAN : STEP- ' + LTRIM(STR(@NSTEP)) + ' SQL ERROR: #' + LTRIM(STR(ERROR_NUMBER())) + ' ' + ERROR_MESSAGE()
		
		
		GOTO END_PROC
	END CATCH
	
END_PROC:

IF ISNULL (@CERRORMSG,'') = ''
	INSERT @OUTPUT ( TYPE, MESSAGE,VALUE) VALUES('SUCCESS',ISNULL(@CERRORMSG,''),'')
ELSE
	INSERT @OUTPUT ( TYPE, MESSAGE,VALUE) VALUES('ERROR',@CERRORMSG,'')

IF (SELECT TOP 1 'U' FROM @TERROR) = 'U'
	SELECT TYPE,VALUE,MESSAGE FROM @TERROR
	ORDER BY SORTORDER
 ELSE	
	SELECT * FROM @OUTPUT
END
---END OF PROCEDURE - SP_PROCESS_IMPORTDATA_BUYPLAN


