create PROCEDURE SP_ARTICLE_TRAN_HISTORY
(
@CFROMDT DATETIME,
@CTODT DATETIME,
@CWHERE VARCHAR(100),
@CDEPTID VARCHAR(100),
@CPRODUCTCODE VARCHAR(100)
)
--WITH ENCRYPTION

AS
BEGIN
--(dinkar) Replace  left(memoid,2) to Location_code 

DECLARE @CPRODUCT VARCHAR(100)

IF ISNULL(@CPRODUCTCODE,'')=''
BEGIN

SELECT @CPRODUCT= PRODUCT_CODE 
FROM SKU A  
JOIN ARTICLE  B ON A.ARTICLE_CODE= B.ARTICLE_CODE
WHERE A.ARTICLE_CODE= @CWHERE AND B.CODING_SCHEME= 1

 SET @CPRODUCTCODE= @CPRODUCT

END
 
 
SELECT C.ARTICLE_CODE,C.ARTICLE_NO,ISNULL(MBQ,0) AS MBQ,
       SUM(ISNULL(CMM.QUANTITY,0)) AS SLS_QTY,(P.QUANTITY_IN_STOCK) AS CBS
FROM SKU B             
LEFT JOIN 
(
 SELECT A.CM_ID,PRODUCT_CODE,QUANTITY FROM CMM01106 CMM
 JOIN CMD01106 A (NOLOCK) ON CMM.CM_ID=A.CM_ID
 WHERE CM_DT BETWEEN @CFROMDT AND @CTODT
AND cmm.location_Code = @CDEPTID AND CM_MODE=1
)CMM ON B.PRODUCT_CODE = CMM.PRODUCT_CODE 
LEFT  OUTER JOIN 
(
  SELECT PRODUCT_CODE,DEPT_ID,SUM(QUANTITY_IN_STOCK) AS QUANTITY_IN_STOCK
  FROM PMT01106 (NOLOCK) WHERE PRODUCT_CODE =@CPRODUCTCODE 
  GROUP BY  PRODUCT_CODE,DEPT_ID
) P  ON B.PRODUCT_CODE=P.PRODUCT_CODE
JOIN ARTICLE C (NOLOCK) ON B.ARTICLE_CODE = C.ARTICLE_CODE 
LEFT OUTER JOIN 
(
  SELECT PRODUCT_CODE, DEPT_ID ,
  SUM(CASE WHEN MONTH= DATEPART(MONTH ,@CTODT) AND YEAR= DATEPART(YEAR ,@CTODT)  THEN MBQ ELSE 0 END) AS MBQ  
  FROM MBQ_DET (NOLOCK) WHERE PRODUCT_CODE= @CPRODUCTCODE AND DEPT_ID= @CDEPTID
  GROUP BY PRODUCT_CODE,DEPT_ID
) D ON B.PRODUCT_CODE = D.PRODUCT_CODE  
WHERE B.PRODUCT_CODE= @CPRODUCTCODE 
--AND CM_DT BETWEEN @CFROMDT AND @CTODT
GROUP BY C.ARTICLE_CODE,C.ARTICLE_NO,MBQ,P.QUANTITY_IN_STOCK

 
--SELECT C.ARTICLE_CODE,C.ARTICLE_NO,ISNULL(MBQ,0) AS MBQ,
--       SUM(A.QUANTITY) AS SLS_QTY,(P.QUANTITY_IN_STOCK) AS CBS                
--FROM CMD01106 A (NOLOCK)
--JOIN CMM01106 CMM ON A.CM_ID = CMM.CM_ID 
--JOIN SKU B (NOLOCK) ON A.PRODUCT_CODE = B.PRODUCT_CODE 
--RIGHT OUTER JOIN 
--(
--  SELECT PRODUCT_CODE,DEPT_ID,SUM(QUANTITY_IN_STOCK) AS QUANTITY_IN_STOCK
--  FROM PMT01106 (NOLOCK) WHERE PRODUCT_CODE =@CPRODUCTCODE 
--  GROUP BY  PRODUCT_CODE,DEPT_ID
--) P  ON B.PRODUCT_CODE=P.PRODUCT_CODE

--JOIN ARTICLE C (NOLOCK) ON B.ARTICLE_CODE = C.ARTICLE_CODE 
--LEFT OUTER JOIN 
--(
--  SELECT PRODUCT_CODE, DEPT_ID ,
--  SUM(CASE WHEN MONTH= DATEPART(MONTH ,@CTODT) AND YEAR= DATEPART(YEAR ,@CTODT)  THEN MBQ ELSE 0 END) AS MBQ  
--  FROM MBQ_DET (NOLOCK) WHERE PRODUCT_CODE= @CPRODUCTCODE AND DEPT_ID= @CDEPTID
--  GROUP BY PRODUCT_CODE,DEPT_ID
--) D ON B.PRODUCT_CODE = D.PRODUCT_CODE  
--WHERE B.PRODUCT_CODE= @CPRODUCTCODE AND LEFT(CMM.CM_NO,2)= @CDEPTID AND CM_MODE=1
--AND CM_DT BETWEEN @CFROMDT AND @CTODT
--GROUP BY C.ARTICLE_CODE,C.ARTICLE_NO,MBQ,P.QUANTITY_IN_STOCK

END
