create PROC VALIDATEXN_TRF_TRD_BEFORE_EDIT 
@CMEMOID VARCHAR(30),
@BCANCELXN BIT,
@CERRORMSG VARCHAR(200) OUTPUT,
@CEXPRERRORMSG VARCHAR(200) OUTPUT
--WITH ENCRYPTION
AS
BEGIN
	
	DECLARE @CTEXT VARCHAR(10),@CPRODUCTCODE VARCHAR(50),@NTOTALCOUNT NUMERIC(10)
	
	SELECT @CPRODUCTCODE=''
	
	SET @CTEXT=(CASE WHEN @BCANCELXN=1 THEN 'CANCEL' ELSE 'EDIT' END)
	
	;WITH TRF
	AS
	(
		SELECT (CASE WHEN ISNULL(B.TRADING_PRODUCT_CODE,'')<>'' THEN B.TRADING_PRODUCT_CODE ELSE A.PRODUCT_CODE END) as PRODUCT_CODE  ,
		SUM(QUANTITY) AS QTY
		FROM TRANSFER_TO_TRADING_DET A (nolock)
		Join JOBWORK_PMT b (nolock) on a.PRODUCT_CODE =b.PRODUCT_CODE 
		WHERE MEMO_ID=@CMEMOID
		GROUP BY (CASE WHEN ISNULL(B.TRADING_PRODUCT_CODE,'')<>'' THEN B.TRADING_PRODUCT_CODE ELSE A.PRODUCT_CODE END)
	),
	PMT AS
	(
		SELECT PRODUCT_CODE ,SUM(QUANTITY_IN_STOCK) AS QTY
		FROM PMT01106 
		GROUP BY PRODUCT_CODE
	)
	SELECT @NTOTALCOUNT=COUNT(TRF.PRODUCT_CODE)
	FROM TRF
	JOIN PMT ON PMT.PRODUCT_CODE= TRF.PRODUCT_CODE
	WHERE PMT.QTY<> TRF.QTY
	
	
	IF @NTOTALCOUNT>0
	BEGIN	
		SET @CERRORMSG='BARCODE ALREADY USED IN TRADING.........CAN NOT '+@CTEXT
		RETURN
	END
END
