CREATE PROCEDURE SAVETRAN_LEDGER_CREATION           
(          
 @AC_CODE           VARCHAR(10) = '',          
 @AC_NAME          VARCHAR(300)='',          
 @ALIAS            VARCHAR(50) = '',          
 @INACTIVE           BIT = 0,          
 @HEAD_CODE         VARCHAR(10) = '',          
 @ADDRESS0          VARCHAR(MAX)='',          
 @ADDRESS1          VARCHAR(MAX)='',          
 @ADDRESS2          VARCHAR(MAX)='',          
 @AREA_CODE         VARCHAR(7) = '',          
 @CITY_CODE          VARCHAR(10) = '',          
 @TIN_NO           VARCHAR(40) = '',          
 @PAN_NO           VARCHAR(40) = '',          
 @PHONES_O          VARCHAR(50) = '',          
 @PHONES_R          VARCHAR(50) = '',          
 @PHONES_FAX         VARCHAR(50) = '',          
 @MOBILE           VARCHAR(50) = '',          
 @ENABLE_EMAIL        BIT = 0,          
 @E_MAIL           VARCHAR(250) = '',          
 @ALLOW_CREDITOR_DEBTOR   BIT = 0,          
 @CONSIDER_JOB_WORK_AGENCY VARCHAR(1) = '',          
 @USER_CODE         VARCHAR(7) = '',          
 @ERRMSG_OUT        VARCHAR(MAX) OUT ,
 @CREMARKS          VARCHAR(MAX)=''    ,
 @CAC_GST_NO	    VARCHAR(50)='',
 @NREGISTERED_GST_DEALER	INT=0,
 @CAC_GST_STATE_CODE	VARCHAR (10)=''
)          
AS          
BEGIN          
 DECLARE @CSTEP INT          
 DECLARE @TEMP_AC_CODE VARCHAR(10) = '', @TEMP_AGENCY_CODE VARCHAR(5) = ''          
           
 BEGIN TRY       
 BEGIN TRAN         
  SET @ERRMSG_OUT = ''          
         
 IF @AREA_CODE=''        
 SET @AREA_CODE='0000000'        
 IF @CITY_CODE=''        
 SET @CITY_CODE='0000000'        
          
  IF (RTRIM(LTRIM(@AC_CODE)) = '')          
  BEGIN          
   IF EXISTS(SELECT AC_NAME FROM [LM01106] WHERE AC_NAME = @AC_NAME)          
    BEGIN          
    SET @CSTEP=5          
    SET @ERRMSG_OUT = 'A/C NAME: '+@AC_NAME + ' ALREADY EXIST.'          
    PRINT @ERRMSG_OUT          
   END          
   ELSE          
   BEGIN          
    SET @CSTEP=10          
    EXEC DBO.GETNEXTKEY 'LM01106', 'AC_CODE', 10, '00', 1, '', 2, @TEMP_AC_CODE OUTPUT           
    PRINT 'A/C CODE: ' + @TEMP_AC_CODE          
              
    SET @CSTEP=15          
    INSERT LM01106 ( COMPANY_CODE, UPLOADED_TO_ACTIVSTREAM, USER_CODE, EDT_USER_CODE, ALIAS_TO_BE_SUFFIXED, LAST_UPDATE, OPENING_BALANCE,           
            OPENING_BALANCE_CR_DR, TDS_CODE, INACTIVE, AC_CODE, AC_NAME, ALIAS, HEAD_CODE, CLOSING_BALANCE, CLOSING_BALANCE_CR_DR,           
            PRINT_LEDGER, LAST_MODIFIED_ON,LM_REMARKS )          
    VALUES('01', 0, @USER_CODE, @USER_CODE, '', GETDATE(), 0.00, '', '0000000', @INACTIVE, @TEMP_AC_CODE , @AC_NAME, @ALIAS, @HEAD_CODE, 0.00, '', 0, GETDATE(),@CREMARKS)          
    PRINT 'A/C NAME: '+@AC_NAME + '. MASTER CREATED SUCCESSFULLY.'    
         
     
              
    SET @CSTEP=20          
    INSERT LMP01106 ( DPWEF_DT, TIN_NO, TIN_DT, CST_PERCENTAGE, PAN_NO, FORM_ID, AREA_CODE, INV_RATE_TYPE, CUSTOMER_CODE, UPLOADED_TO_ACTIVSTREAM,           
              GLN_NO, MP_PERCENTAGE, MRP_CALC_MODE, AC_CODE, PRINT_NAME, ADDRESS0, ADDRESS1, SALES_AC_CODE, DEFAULT_RATE_TYPE,           
              PUR_CAL_METHOD, RESTRICT_PUR_ENTRY, WP_PERCENTAGE, WSL_RATE_CALC_METHOD, EOSS_DISCOUNT_SHARE, EOSS_DISCOUNT_PER,           
              PURCHASE_AGAINST_TERMS, SHIPPING_ADDRESS, SHIPPING_ADDRESS2, SHIPPING_ADDRESS3, CUSTOM_RATE_TYPE, DO_NOT_ALLOW_DIRECT_PUR,           
              ADDRESS2, CITY_CODE, CST_NO, CST_DT, SST_NO, SST_DT, PHONES_R, PHONES_O, PHONES_FAX, MOBILE, E_MAIL, TAX_CODE, CREDIT_DAYS,           
              DISCOUNT_PERCENTAGE, BILL_BY_BILL, ON_HOLD, THROUGH_BROKER, BROKER_AC_CODE, BROKER_COMM_PERCENT, CREDIT_LIMIT,           
              OUTSTATION_PARTY, ALLOW_CREDITOR_DEBTOR, LAST_UPDATE, COMPANY_CODE, ENABLE_EMAIL,AC_GST_NO,REGISTERED_GST_DEALER,AC_GST_STATE_CODE )            
    VALUES('', @TIN_NO, '', 0, @PAN_NO, '0000000', @AREA_CODE, 1, '000000000000', 0, '', 0, 0, @TEMP_AC_CODE, @AC_NAME, @ADDRESS0, @ADDRESS1, '0000000000', 1, NULL, NULL, NULL, 1,           
         NULL, NULL, NULL, '', '', '', NULL, NULL, @ADDRESS2, @CITY_CODE, '', '', '', '', @PHONES_R, @PHONES_O, @PHONES_FAX, @MOBILE, @E_MAIL, '', 0, 0, 0, 0, 0, '0000000000', 0, 0, 0,           
         @ALLOW_CREDITOR_DEBTOR, GETDATE(), '01', @ENABLE_EMAIL,@CAC_GST_NO,@NREGISTERED_GST_DEALER,@CAC_GST_STATE_CODE)          
    PRINT 'A/C NAME: '+@AC_NAME + '. DETAIL CREATED SUCCESSFULLY.'      
      
     
    IF @CONSIDER_JOB_WORK_AGENCY ='Y'          
    BEGIN          
     SET @CSTEP=25          
     EXEC DBO.GETNEXTKEY 'PRD_AGENCY_MST', 'AGENCY_CODE', 5, '00', 1, '', 2, @TEMP_AGENCY_CODE OUTPUT           
               
     INSERT PRD_AGENCY_MST (AC_CODE, INACTIVE, AGENCY_CODE, AGENCY_NAME, REMARKS )            
     VALUES(@TEMP_AC_CODE, 0, @TEMP_AGENCY_CODE, @AC_NAME, '')          
     PRINT 'A/C NAME: '+@AC_NAME + '. JOB AGENCY CREATED SUCCESSFULLY.'          
    END          
          
            
              
    SET @ERRMSG_OUT =  'A/C NAME: '+@AC_NAME + ' CREATED SUCCESSFULLY.'          
    PRINT @ERRMSG_OUT          
   END          
  END          
  ELSE          
  BEGIN          
   SET @TEMP_AC_CODE = @AC_CODE          
   PRINT 'A/C CODE: ' + @TEMP_AC_CODE          
             
   IF NOT EXISTS(SELECT AC_CODE FROM [LM01106] WHERE AC_CODE = @TEMP_AC_CODE)          
   BEGIN          
    SET @CSTEP=30          
    INSERT LM01106 ( COMPANY_CODE, UPLOADED_TO_ACTIVSTREAM, USER_CODE, EDT_USER_CODE, ALIAS_TO_BE_SUFFIXED, LAST_UPDATE, OPENING_BALANCE,           
            OPENING_BALANCE_CR_DR, TDS_CODE, INACTIVE, AC_CODE, AC_NAME, ALIAS, HEAD_CODE, CLOSING_BALANCE, CLOSING_BALANCE_CR_DR,           
            PRINT_LEDGER, LAST_MODIFIED_ON ,LM_REMARKS,MAJOR_AC_CODE)            
    VALUES('01', 0, @USER_CODE, @USER_CODE, '', GETDATE(), 0.00, '', '0000000', @INACTIVE, @TEMP_AC_CODE, @AC_NAME, @ALIAS, @HEAD_CODE, 0.00, '', 0, GETDATE(),@CREMARKS,@TEMP_AC_CODE )          
              
    SET @ERRMSG_OUT =  'A/C NAME: '+@AC_NAME + '. LEDGER MASTER CREATED SUCCESSFULLY.'       
    
    PRINT @ERRMSG_OUT      
   END          
   ELSE          
   BEGIN          
    SET @CSTEP=35          
    UPDATE [LM01106]          
    SET AC_NAME = @AC_NAME, ALIAS = @ALIAS, INACTIVE = @INACTIVE, HEAD_CODE = @HEAD_CODE,           
      USER_CODE = @USER_CODE, LAST_MODIFIED_ON = GETDATE(), LAST_UPDATE = GETDATE() ,LM_REMARKS=@CREMARKS          
    WHERE AC_CODE = @TEMP_AC_CODE          
              
    SET @ERRMSG_OUT =  'A/C NAME: '+@AC_NAME +'. LEDGER MASTER UPDTED SUCCESSFULLY.'          
    PRINT @ERRMSG_OUT    
     
   END          
             
   IF NOT EXISTS(SELECT AC_CODE FROM [LMP01106] WHERE AC_CODE = @TEMP_AC_CODE)          
   BEGIN          
    SET @CSTEP=40          
    INSERT LMP01106 (DPWEF_DT, TIN_NO, TIN_DT, CST_PERCENTAGE, PAN_NO, FORM_ID, AREA_CODE, INV_RATE_TYPE, CUSTOMER_CODE, UPLOADED_TO_ACTIVSTREAM,           
             GLN_NO, MP_PERCENTAGE, MRP_CALC_MODE, AC_CODE, PRINT_NAME, ADDRESS0, ADDRESS1, SALES_AC_CODE, DEFAULT_RATE_TYPE,           
            PUR_CAL_METHOD, RESTRICT_PUR_ENTRY, WP_PERCENTAGE, WSL_RATE_CALC_METHOD, EOSS_DISCOUNT_SHARE, EOSS_DISCOUNT_PER,           
            PURCHASE_AGAINST_TERMS, SHIPPING_ADDRESS, SHIPPING_ADDRESS2, SHIPPING_ADDRESS3, CUSTOM_RATE_TYPE, DO_NOT_ALLOW_DIRECT_PUR,           
            ADDRESS2, CITY_CODE, CST_NO, CST_DT, SST_NO, SST_DT, PHONES_R, PHONES_O, PHONES_FAX, MOBILE, E_MAIL, TAX_CODE, CREDIT_DAYS,           
            DISCOUNT_PERCENTAGE, BILL_BY_BILL, ON_HOLD, THROUGH_BROKER, BROKER_AC_CODE, BROKER_COMM_PERCENT, CREDIT_LIMIT,           
            OUTSTATION_PARTY, ALLOW_CREDITOR_DEBTOR, LAST_UPDATE, COMPANY_CODE, ENABLE_EMAIL,AC_GST_NO,REGISTERED_GST_DEALER,AC_GST_STATE_CODE  )            
    VALUES('', @TIN_NO, '', 0, @PAN_NO, '0000000', @AREA_CODE, 1, '000000000000', 0, '', 0, 0, @TEMP_AC_CODE, @AC_NAME, @ADDRESS0, @ADDRESS1, '0000000000', 1, NULL, NULL, NULL, 1,           
         NULL, NULL, NULL, '', '', '', NULL, NULL, @ADDRESS2, @CITY_CODE, '', '', '', '', @PHONES_R, @PHONES_O, @PHONES_FAX, @MOBILE, @E_MAIL, '', 0, 0, 0, 0, 0, '0000000000', 0, 0, 0,           
         @ALLOW_CREDITOR_DEBTOR, GETDATE(), '01', @ENABLE_EMAIL,@CAC_GST_NO,@NREGISTERED_GST_DEALER,@CAC_GST_STATE_CODE)          
         
    SET @ERRMSG_OUT =  'A/C NAME: '+@AC_NAME + '. LEDGER DETAIL CREATED SUCCESSFULLY.'         
                 
    PRINT @ERRMSG_OUT          
   END          
   ELSE          
   BEGIN          
    SET @CSTEP=45          
    UPDATE [LMP01106]          
    SET PRINT_NAME = @AC_NAME, ADDRESS0 = @ADDRESS0, ADDRESS1 = @ADDRESS1, ADDRESS2 = @ADDRESS2,           
      AREA_CODE = @AREA_CODE, CITY_CODE = @CITY_CODE, TIN_NO = @TIN_NO, PAN_NO = @PAN_NO,           
      PHONES_O = @PHONES_O, PHONES_R = @PHONES_R, PHONES_FAX = @PHONES_FAX, MOBILE = @MOBILE,           
      ENABLE_EMAIL = @ENABLE_EMAIL, E_MAIL = @E_MAIL, ALLOW_CREDITOR_DEBTOR = @ALLOW_CREDITOR_DEBTOR   ,
      AC_GST_NO=@CAC_GST_NO,REGISTERED_GST_DEALER=@NREGISTERED_GST_DEALER,AC_GST_STATE_CODE=@CAC_GST_STATE_CODE       
    WHERE AC_CODE = @TEMP_AC_CODE          
    SET @ERRMSG_OUT =  'A/C NAME: '+@AC_NAME +'. LEDGER DETAIL UPDTED SUCCESSFULLY.'          
    PRINT @ERRMSG_OUT   
             
   END          
          
   IF @CONSIDER_JOB_WORK_AGENCY = 'Y'          
   BEGIN          
    IF NOT EXISTS(SELECT AC_CODE FROM PRD_AGENCY_MST WHERE AC_CODE = @TEMP_AC_CODE)          
    BEGIN          
     SET @CSTEP=50          
     EXEC DBO.GETNEXTKEY 'PRD_AGENCY_MST', 'AGENCY_CODE', 5, '00', 1, '', 2, @TEMP_AGENCY_CODE OUTPUT           
     INSERT PRD_AGENCY_MST (AC_CODE, INACTIVE, AGENCY_CODE, AGENCY_NAME, REMARKS )            
     VALUES(@TEMP_AC_CODE, 0, @TEMP_AGENCY_CODE, @AC_NAME, '')          
     PRINT 'A/C NAME: '+@AC_NAME + '. JOB AGENCY CREATED SUCCESSFULLY.'     
      
    END          
    ELSE          
    BEGIN          
     SET @CSTEP=55          
     UPDATE PRD_AGENCY_MST SET AGENCY_NAME = @AC_NAME,  INACTIVE = 0 WHERE AC_CODE = @TEMP_AC_CODE          
     PRINT 'A/C NAME: '+@AC_NAME + '. JOB AGENCY UPDATED SUCCESSFULLY.'   
     
    END          
   END          
   ELSE          
   BEGIN          
    SET @CSTEP=60          
    UPDATE PRD_AGENCY_MST SET AGENCY_NAME = @AC_NAME,  INACTIVE = 1 WHERE AC_CODE = @TEMP_AC_CODE          
    PRINT 'A/C NAME: '+@AC_NAME + '. JOB AGENCY UPDATED SUCCESSFULLY.'    
    
   END          
  END   
   SELECT  @ERRMSG_OUT AS ERRORMSG,@TEMP_AC_CODE AS AC_CODE         
  COMMIT TRAN       
 END TRY            
 BEGIN CATCH        
  ROLLBACK           
  SET @ERRMSG_OUT='ERROR: [P]: SAVETRAN_LEDGER_CREATION, [STEP]: '+CAST(@CSTEP AS VARCHAR(5))+', [MESSAGE]: ' + ERROR_MESSAGE()          
  PRINT @ERRMSG_OUT          
   SELECT  @ERRMSG_OUT AS ERRORMSG,@TEMP_AC_CODE AS AC_CODE          
  GOTO END_PROC            
 END CATCH             
          
END_PROC:            
 IF  ISNULL(@ERRMSG_OUT,'')=''           
  SET @ERRMSG_OUT = ''           
END
