CREATE PROCEDURE SP_WL_PRD_CREDIT_NOTE  
  
 @NQUERYID NUMERIC (3,0) ,  
 @CMEMOID VARCHAR(40) = '',  
 @CWHERE  VARCHAR(500) = '',  
 @NNAVMODE NUMERIC(1,0) = 0,  
 @CFINYEAR VARCHAR(5)='',  
 @CWHERE1 VARCHAR(500) = ''  
--WITH ENCRYPTION
  
AS  
BEGIN  
  
DECLARE @CCMD NVARCHAR(4000)  
  
IF @NQUERYID = 1  
GOTO LBLNAVIGATE  
  
ELSE IF @NQUERYID = 2  
GOTO LBLGETMASTER  
  
ELSE IF @NQUERYID = 3  
GOTO LBLGETDETAIL  
  
ELSE IF @NQUERYID = 4  
GOTO LBLFORMS  
  
ELSE IF @NQUERYID = 5  
GOTO LBLCUSTOMER  
  
ELSE IF @NQUERYID = 6  
GOTO LBLSTOCKDETAILS  
  
ELSE IF @NQUERYID = 7  
GOTO LBLREPORTS  
ELSE IF @NQUERYID = 8  
GOTO LBLPRODUCTCODELIST  
ELSE IF @NQUERYID = 9   
GOTO LBLIMPRTLOG   
ELSE IF @NQUERYID = 10  
GOTO LBLGETBILL  
  
ELSE IF @NQUERYID = 11  
GOTO LBLGETBILLMASTER  
  
ELSE IF @NQUERYID = 12  
GOTO LBLGETBILLDET  

ELSE IF @NQUERYID=13
GOTO LBLCHECKSTOCK
  
ELSE  
  
GOTO LAST  
LBLNAVIGATE:  
  
 EXECUTE SP_NAVIGATE 'PRD_CNM01106',@NNAVMODE,@CMEMOID,@CFINYEAR,'CN_NO','CN_DT','CN_ID',@CWHERE  
  
GOTO LAST  
  
LBLGETMASTER:  
  
 SELECT T1.*,T2.USERNAME,T3.FORM_NAME,T4.AC_NAME,T4.ADDRESS0+' '+T4.ADDRESS1+' ' +T4.ADDRESS2+' '   
 +T4.AREA_NAME+' ' +T4.CITY+' ' +T4.[STATE]+' '+T4.PINCODE AS PARTY_ADDRESS,  
 ISNULL(T5.DEPT_NAME,'') AS PARTY_DEPT_NAME  
 FROM PRD_CNM01106 T1   
 JOIN USERS T2  ON T1.USER_CODE = T2.USER_CODE  
 JOIN FORM T3  ON T3.FORM_ID = T1.FORM_ID  
 JOIN LMV01106 T4 ON T4.AC_CODE = T1.AC_CODE  
 LEFT OUTER JOIN LOCATION T5 ON T5.DEPT_ID = T1.PARTY_DEPT_ID   
 WHERE T1.CN_ID = @CMEMOID  
   
GOTO LAST  
  
LBLGETDETAIL:  
  
 --SELECT T1.*,ROW_NUMBER() OVER (ORDER BY T1.TS) AS S_NO,T2.*,(T1.QUANTITY*T1.RATE)-T1.DISCOUNT_AMOUNT AS AMOUNT  
 --FROM PRD_CND01106 T1  
 --JOIN PMV01106 T2 ON T2.PRODUCT_UID = T1.PRODUCT_UID  
 --WHERE T1.CN_ID = @CMEMOID  
   
 SELECT T1.*,ROW_NUMBER() OVER (ORDER BY T1.TS) AS S_NO,  
   B.ARTICLE_CODE, B.ARTICLE_NO, B.ARTICLE_NAME, S.PARA1_CODE,    
   C.PARA1_NAME, S.PARA2_CODE, D.PARA2_NAME, S.PARA3_CODE, F.PARA3_NAME, E.UOM_NAME,       
   T1.DEPT_ID, B.CODING_SCHEME,  B.INACTIVE, 0 AS QUANTITY_IN_STOCK,    
   S.PURCHASE_PRICE,  S.MRP,S.WS_PRICE,  '' AS SCHEME_ID, SM.SECTION_NAME, SD.SUB_SECTION_NAME,    
   S.PARA4_CODE,S.PARA5_CODE,S.PARA6_CODE,    
   PARA4_NAME,PARA5_NAME,PARA6_NAME,E.UOM_CODE,ISNULL(E.UOM_TYPE,0) AS [UOM_TYPE],    
   B.DT_CREATED AS [ART_DT_CREATED],F.DT_CREATED AS [PARA3_DT_CREATED],S.DT_CREATED AS [SKU_DT_CREATED],    
   B.STOCK_NA,(T1.QUANTITY*T1.RATE)-T1.DISCOUNT_AMOUNT AS AMOUNT,FRM.FORM_NAME ,  
      CAST(0 AS INT) AS STK  
 FROM PRD_CND01106 T1  
 JOIN PRD_SKU S ON T1.PRODUCT_UID = S.PRODUCT_UID     
 JOIN ARTICLE B ON S.ARTICLE_CODE = B.ARTICLE_CODE      
 JOIN SECTIOND SD ON B.SUB_SECTION_CODE = SD.SUB_SECTION_CODE    
 JOIN SECTIONM SM ON SD.SECTION_CODE = SM.SECTION_CODE    
 JOIN PARA1 C ON S.PARA1_CODE = C.PARA1_CODE      
 JOIN PARA2 D ON S.PARA2_CODE = D.PARA2_CODE      
 JOIN PARA3 F ON S.PARA3_CODE = F.PARA3_CODE      
 JOIN PARA4 G ON S.PARA4_CODE = G.PARA4_CODE      
 JOIN PARA5 H ON S.PARA5_CODE = H.PARA5_CODE      
 JOIN PARA6 I ON S.PARA6_CODE = I.PARA6_CODE      
 JOIN UOM   E ON B.UOM_CODE = E.UOM_CODE     
 JOIN FORM  FRM ON T1.ITEM_FORM_ID = FRM.FORM_ID   
 WHERE T1.CN_ID = @CMEMOID  
  
GOTO LAST  
  
LBLFORMS:  
  
 SELECT * FROM FORM WHERE FORM_ID <> '0000000' AND INACTIVE=0  
  
GOTO LAST  
  
LBLCUSTOMER:  
  
DECLARE @CHEADCODESTR VARCHAR(1000),@CHEADCODESTR1 VARCHAR(1000)    
  SELECT @CHEADCODESTR = DBO.FN_ACT_TRAVTREE('0000000018')      
  SELECT @CHEADCODESTR1 = DBO.FN_ACT_TRAVTREE('0000000021')      
  SELECT AC_CODE, AC_NAME, ADDRESS0,ADDRESS1,ADDRESS2 AREA_NAME , CITY, [STATE], PINCODE ,      
  ISNULL(DISCOUNT_PERCENTAGE,0) AS DISCOUNT_PERCENTAGE      
  FROM LMV01106        
  WHERE ((CHARINDEX(HEAD_CODE,@CHEADCODESTR)>0 OR CHARINDEX(HEAD_CODE,@CHEADCODESTR1)>0)      
  OR ALLOW_CREDITOR_DEBTOR=1) AND AC_CODE <>'0000000000'      
  AND INACTIVE=0      
  ORDER BY AC_NAME    
    
GOTO LAST  
  
LBLSTOCKDETAILS:  
  
   
 SET @CCMD = N' SELECT TOP 1 T1.PRODUCT_UID,T1.QUANTITY,T1.DEPT_ID,  
 B.ARTICLE_NO,T1.PRODUCT_UID, B.ARTICLE_CODE, B.ARTICLE_NO, B.ARTICLE_NAME, S.PARA1_CODE,    
   C.PARA1_NAME, S.PARA2_CODE, D.PARA2_NAME, S.PARA3_CODE, F.PARA3_NAME, E.UOM_NAME,       
   T1.DEPT_ID, B.CODING_SCHEME,  B.INACTIVE, ISNULL(P.QUANTITY_IN_STOCK,0) AS QUANTITY_IN_STOCK,    
   S.PURCHASE_PRICE,  S.MRP,S.WS_PRICE,  '''' AS SCHEME_ID, SM.SECTION_NAME, SD.SUB_SECTION_NAME,    
   S.PARA4_CODE,S.PARA5_CODE,S.PARA6_CODE,    
   PARA4_NAME,PARA5_NAME,PARA6_NAME,E.UOM_CODE,ISNULL(E.UOM_TYPE,0) AS [UOM_TYPE],    
   B.DT_CREATED AS [ART_DT_CREATED],F.DT_CREATED AS [PARA3_DT_CREATED],S.DT_CREATED AS [SKU_DT_CREATED],    
   B.STOCK_NA,ISNULL(B1.QUANTITY,0) AS RET_QTY,  
 T1.RATE,T1.DISCOUNT_PERCENTAGE,T1.DISCOUNT_AMOUNT,
 F1.FORM_ID ,F1.TAX_PERCENTAGE,F1.FORM_NAME   
 FROM IND01106 T1  
 JOIN INM01106 T2 ON T1.INV_ID = T2.INV_ID  
 LEFT OUTER JOIN PMT01106 P ON T1.PRODUCT_UID = P.PRODUCT_UID AND P.DEPT_ID=T1.DEPT_ID    
  JOIN SKU S ON P.PRODUCT_UID = S.PRODUCT_UID     
  JOIN ARTICLE B ON S.ARTICLE_CODE = B.ARTICLE_CODE      
  JOIN SECTIOND SD ON B.SUB_SECTION_CODE = SD.SUB_SECTION_CODE    
  JOIN SECTIONM SM ON SD.SECTION_CODE = SM.SECTION_CODE    
  JOIN PARA1 C ON S.PARA1_CODE = C.PARA1_CODE      
  JOIN PARA2 D ON S.PARA2_CODE = D.PARA2_CODE      
  JOIN PARA3 F ON S.PARA3_CODE = F.PARA3_CODE      
  JOIN PARA4 G ON S.PARA4_CODE = G.PARA4_CODE      
  JOIN PARA5 H ON S.PARA5_CODE = H.PARA5_CODE      
  JOIN PARA6 I ON S.PARA6_CODE = I.PARA6_CODE      
  JOIN UOM   E ON B.UOM_CODE = E.UOM_CODE    
  JOIN FORM F1 ON F1.FORM_ID=T1.ITEM_FORM_ID    
 LEFT OUTER JOIN   
 (  
   SELECT SUM(T4.QUANTITY) AS QUANTITY,T4.PRODUCT_UID  
   FROM PRD_CND01106 T4  
   JOIN PRD_CNM01106 T5 ON T4.CN_ID = T5.CN_ID  
   JOIN SKU T6 ON T4.PRODUCT_UID = T6.PRODUCT_UID   
   WHERE T5.AC_CODE = '''+@CWHERE+''' AND T4.PRODUCT_UID = '''+@CMEMOID+'''  
   AND T5.CANCELLED = 0 GROUP BY T4.QUANTITY,T4.PRODUCT_UID  
 )B1 ON T1.PRODUCT_UID = B1.PRODUCT_UID  
 WHERE T1.PRODUCT_UID = '''+@CMEMOID+'''  
 AND T2.CANCELLED = 0'  
 PRINT @CCMD  
 EXECUTE SP_EXECUTESQL @CCMD  
  
GOTO LAST  
  
LBLREPORTS:  
  
 SELECT * FROM VW_WL_PRD_WSRINV_REP WHERE CN_ID = @CMEMOID  
  
GOTO LAST  
LBLPRODUCTCODELIST:  
  
 --SELECT DISTINCT T3.ARTICLE_NO,T1.PRODUCT_UID,P1.PARA1_NAME,P2.PARA2_NAME,T3.ARTICLE_NAME,T1.PURCHASE_PRICE AS RATE  
 --FROM PRD_IND01106 IND   
 --JOIN PRD_INM01106 INM ON INM.INV_ID=IND.INV_ID  
 --JOIN PRD_SKU T1 ON T1.PRODUCT_UID=IND.PRODUCT_UID  
 --JOIN ARTICLE T3 ON T1.ARTICLE_CODE = T3.ARTICLE_CODE  
 --JOIN PARA1 P1 ON P1.PARA1_CODE=T1.PARA1_CODE
 --JOIN PARA2 P2 ON  P2.PARA2_CODE=T1.PARA2_CODE
 --WHERE T1.PRODUCT_UID <> '' AND INM.CANCELLED=0   
 --ORDER BY T3.ARTICLE_NO
 
  SELECT DISTINCT T3.ARTICLE_NO,T1.PRODUCT_UID,P1.PARA1_NAME,P2.PARA2_NAME,T3.ARTICLE_NAME,T1.PURCHASE_PRICE AS RATE    
 FROM PRD_IND01106 IND     
 JOIN PRD_INM01106 INM ON INM.INV_ID=IND.INV_ID    
 JOIN PRD_SKU T1 ON T1.PRODUCT_UID=IND.PRODUCT_UID    
 JOIN ARTICLE T3 ON T1.ARTICLE_CODE = T3.ARTICLE_CODE    
 JOIN PARA1 P1 ON P1.PARA1_CODE=T1.PARA1_CODE  
 JOIN PARA2 P2 ON  P2.PARA2_CODE=T1.PARA2_CODE  
 JOIN PRD_PMT PMT ON T1.PRODUCT_UID= PMT.PRODUCT_UID 
 WHERE T1.PRODUCT_UID <> '' AND INM.CANCELLED=0   AND  PMT.DEPARTMENT_ID = @CWHERE1  AND INM.AC_CODE = @CWHERE 
 ORDER BY T3.ARTICLE_NO
 
   
 GOTO LAST  
  
LBLIMPRTLOG:  
   SELECT RM_ID,CN_ID,RECEIPT_DT FROM CNM01106 (NOLOCK)  
   WHERE RM_ID=@CWHERE  
     
     
   GOTO LAST  
  
LBLGETBILL:    
  SELECT A.INV_ID,COUNT(B.INV_NO) AS ITEMCOUNT    
  FROM PRD_IND01106 A (NOLOCK)    
  JOIN PRD_INM01106 B (NOLOCK) ON A.INV_ID = B.INV_ID     
  JOIN PRD_SKU SKU(NOLOCK) ON SKU.PRODUCT_UID = A.PRODUCT_UID   
  JOIN ARTICLE C ON SKU.ARTICLE_CODE = C.ARTICLE_CODE      
  WHERE A.PRODUCT_UID =@CWHERE1 AND C.CODING_SCHEME =1
  GROUP BY  A.INV_ID    
GOTO LAST    
         
         
LBLGETBILLMASTER:    
         
      SELECT DISTINCT CAST('' AS NVARCHAR(10)) AS SRNO, CAST(0 AS BIT) AS BILLCHECK,       
                      A.INV_ID,A.INV_NO,A.INV_DT,A.NET_AMOUNT , C.AC_NAME ,A.AC_CODE  ,   B.PRODUCT_UID AS PRODUCT_CODE     
      FROM PRD_INM01106  A (NOLOCK)    
      JOIN PRD_IND01106 B (NOLOCK) ON A.INV_ID=B.INV_ID     
      JOIN LMV01106 C (NOLOCK) ON A.AC_CODE = C.AC_CODE     
      WHERE A.CANCELLED = 0  AND B.QUANTITY > 0      
      AND B.PRODUCT_UID=@CWHERE1    
         
        GOTO LAST    
         
LBLGETBILLDET:    
 SELECT  PM.INV_ID,PM.INV_DT,PM.AC_CODE, F.UOM_TYPE, H.SECTION_NAME, G.SUB_SECTION_NAME, PD.PRODUCT_UID,        
 CONVERT(VARCHAR, PM.INV_DT, 105) AS INV_DATE, PM.INV_NO,LM.AC_NAME,          
 PD.MRP, B.ARTICLE_CODE, B.ARTICLE_NO, B.ARTICLE_NAME, B.ARTICLE_DESC,     
 C.PARA1_NAME, D.PARA2_NAME,  E.PARA3_NAME, P4.PARA4_NAME, P5.PARA5_NAME , P6.PARA6_NAME,     
 F.UOM_CODE, F.UOM_NAME, PD.ITEM_TAX_AMOUNT, PD.ITEM_FORM_ID,         
 I.FORM_NAME,  PD.ITEM_TAX_PERCENTAGE, 0 AS QUANTITY_IN_STOCK,        
 PD.RATE , ISNULL(B.DT_CREATED,'') AS [ART_DT_CREATED],  
 ISNULL(E.DT_CREATED,'') AS [PARA3_DT_CREATED], ISNULL(B.DT_CREATED,'') AS [SKU_DT_CREATED],   
 PM.INV_NO ,B.CODING_SCHEME,B.DISCON,'' AS CITY,    
 CAST( 0  AS BIT) AS BILLCHECK,PD.QUANTITY ,I.FORM_NAME,CAST(1 AS INT) AS STK  ,PD.PRODUCT_UID AS PRODUCT_CODE  
 FROM PRD_IND01106 PD      
 JOIN PRD_INM01106 PM ON PD.INV_ID = PM.INV_ID     
 JOIN PRD_SKU J (NOLOCK) ON PD.PRODUCT_UID = J.PRODUCT_UID         
 JOIN ARTICLE B (NOLOCK) ON J.ARTICLE_CODE = B.ARTICLE_CODE              
 JOIN PARA1 C (NOLOCK) ON J.PARA1_CODE = C.PARA1_CODE              
 JOIN PARA2 D (NOLOCK) ON J.PARA2_CODE = D.PARA2_CODE             
 JOIN PARA3 E (NOLOCK) ON J.PARA3_CODE = E.PARA3_CODE              
 JOIN PARA4 P4 (NOLOCK) ON J.PARA4_CODE = P4.PARA4_CODE              
 JOIN PARA5 P5 (NOLOCK) ON J.PARA5_CODE = P5.PARA5_CODE              
 JOIN PARA6 P6 (NOLOCK) ON J.PARA6_CODE = P6.PARA6_CODE               
 JOIN UOM F (NOLOCK) ON B.UOM_CODE = F.UOM_CODE             
 JOIN SECTIOND G (NOLOCK) ON B.SUB_SECTION_CODE = G.SUB_SECTION_CODE              
 JOIN SECTIONM H (NOLOCK) ON G.SECTION_CODE = H.SECTION_CODE             
 JOIN FORM I (NOLOCK) ON PD.ITEM_FORM_ID = I.FORM_ID             
 JOIN LM01106 LM (NOLOCK) ON PM.AC_CODE = LM.AC_CODE      
 WHERE PM.CANCELLED = 0   AND PD.QUANTITY > 0          
 AND  PD.PRODUCT_UID=@CWHERE1      
    
   GOTO LAST  
     
     LBLCHECKSTOCK:
     DECLARE @NSTKQTY NUMERIC(10,3),@CPRDCODE VARCHAR(100)        
       
 IF @CPRDCODE IS NULL    
  SELECT @CPRDCODE=PRODUCT_UID FROM PRD_SKU WHERE PRODUCT_UID=@CMEMOID
       
 IF @CPRDCODE IS NULL        
  SELECT 'SELECTED ARTICLE NOT FOUND....PLEASE CHECK' AS RETMSG        
 ELSE          
  SELECT '' AS RETMSG 
          
  
      
  SELECT  A.PRODUCT_UID, A.ARTICLE_CODE, B.ARTICLE_NO, B.ARTICLE_NAME, A.PARA1_CODE,        
  C.PARA1_NAME, A.PARA2_CODE, D.PARA2_NAME, A.PARA3_CODE, F.PARA3_NAME, E.UOM_NAME,           
  PMT.DEPARTMENT_ID, B.CODING_SCHEME,  B.INACTIVE, PMT.QUANTITY_IN_STOCK,        
  A.PURCHASE_PRICE,A.MRP AS MRP,    
  A.WS_PRICE,      
  '' AS SCHEME_ID, SM.SECTION_NAME, SD.SUB_SECTION_NAME,        
  A.PARA4_CODE,A.PARA5_CODE,A.PARA6_CODE,        
  PARA4_NAME,PARA5_NAME,PARA6_NAME,B.UOM_CODE,ISNULL(E.UOM_TYPE,0) AS [UOM_TYPE],        
  B.DT_CREATED AS [ART_DT_CREATED],F.DT_CREATED AS [PARA3_DT_CREATED],A.DT_CREATED AS [SKU_DT_CREATED],        
  B.STOCK_NA,  
  F1.FORM_ID,F1.FORM_NAME,F1.TAX_PERCENTAGE,A.MRP AS RATE  
  FROM PRD_PMT PMT          
  JOIN PRD_SKU A ON A.PRODUCT_UID=PMT.PRODUCT_UID      
  JOIN ARTICLE B ON A.ARTICLE_CODE = B.ARTICLE_CODE --AND A.PARA1_CODE=B.PARA1_CODE AND A.PARA2_CODE=B.PARA2_CODE       
  JOIN SECTIOND SD ON B.SUB_SECTION_CODE = SD.SUB_SECTION_CODE        
  JOIN SECTIONM SM ON SD.SECTION_CODE = SM.SECTION_CODE        
  JOIN PARA1 C ON A.PARA1_CODE = C.PARA1_CODE          
  JOIN PARA2 D ON A.PARA2_CODE = D.PARA2_CODE          
  JOIN PARA3 F ON A.PARA3_CODE = F.PARA3_CODE          
  JOIN PARA4 G ON A.PARA4_CODE = G.PARA4_CODE          
  JOIN PARA5 H ON A.PARA5_CODE = H.PARA5_CODE          
  JOIN PARA6 I ON A.PARA6_CODE = I.PARA6_CODE          
  JOIN UOM E ON B.UOM_CODE = E.UOM_CODE     
  JOIN FORM F1 ON A.FORM_ID=F1.FORM_ID     
  WHERE  PMT.PRODUCT_UID=@CMEMOID 
   GOTO LAST
      
   
LAST:  
END
