create PROC VALIDATEXN_WSL_BEFORE_EDIT   
@CMEMOID VARCHAR(50),  
@BCANCELXN BIT,  
@CERRORMSG VARCHAR(200) OUTPUT,  
@CEXPRERRORMSG VARCHAR(200) OUTPUT  
--WITH ENCRYPTION
AS  
BEGIN  
   
 DECLARE @CTEXT VARCHAR(10),@CPRODUCTCODE VARCHAR(50) ,@CVALUE  VARCHAR(10),@CDONOTSENDCHALLANWODISPATCHDETAILS VARCHAR(2),
 @NMODE INT,@CANGADIADETAIL VARCHAR(500)
   
 SELECT @CPRODUCTCODE=''  
   
 SET @CTEXT=(CASE WHEN @BCANCELXN=1 THEN 'CANCEL' ELSE 'EDIT' END)  
   
 SELECT @CVALUE = VALUE  FROM CONFIG  WHERE CONFIG_OPTION ='NEW_ACCOUNT_SYSTEM'

 IF EXISTS (SELECT TOP 1 INV_ID FROM INM01106 WHERE INV_ID=@CMEMOID AND CANCELLED=0 AND ISNULL(EINV_IRN_NO,'')<>'') AND @BCANCELXN<>1
 BEGIN   
	SET @CERRORMSG='EINVOICE GENERATED.........CAN NOT '+@CTEXT  
	RETURN  
 END  

   
 IF EXISTS (SELECT TOP 1 INV_ID FROM INM01106 A JOIN VM01106 B ON A.INV_ID=B.BILL_ID   
           WHERE A.INV_ID=@CMEMOID AND B.BILL_TYPE='WSL' AND  B.CANCELLED=0 
           AND ISNULL(@CVALUE,'')<> '1')  
 BEGIN   
	SET @CERRORMSG='THIS BILL HAS BEEN POSTED INTO ACCOUNTS.........CAN NOT '+@CTEXT  
	RETURN  
 END  


 DECLARE @CPARTY_DEPT_ID VARCHAR(5)
 SELECT TOP 1 @NMODE=INV_MODE,@cparty_dept_id =party_dept_id 
 FROM INM01106 (NOLOCK) WHERE INV_ID=@CMEMOID
	

	--SOURCE AND TARGET CENTALIZED THEN EDIT PARCEL
 IF @NMODE=2
 BEGIN
        
		IF   EXISTS (SELECT TOP 1 'U' FROM PARCEL_MST A (NOLOCK) 
		           JOIN PARCEL_DET B (NOLOCK)  ON A.PARCEL_MEMO_ID=B.PARCEL_MEMO_ID
                   WHERE A.CANCELLED=0 AND REF_MEMO_ID=@CMEMOID AND A.XN_TYPE='WSL')
		BEGIN

			IF(  EXISTS (SELECT TOP  1 'U' FROM LOCATION (nolock) WHERE DEPT_ID =LEFT(@CMEMOID,2) and server_loc =0)
			  or  EXISTS (SELECT TOP  1 'U' FROM LOCATION (nolock) WHERE DEPT_ID =@cparty_dept_id and server_loc =0) )
			begin

				SET @CERRORMSG='THIS GROUP INVOICE HAS BEEN SENT TO TARGET LOCATION.........CAN NOT '+@CTEXT
				RETURN			

			end
		END
 END 
 
 --IF EXISTS (SELECT TOP 1 INV_ID FROM INM01106 A JOIN RECON_LOG B ON A.INV_ID=B.MEMO_ID
	--			   WHERE A.INV_ID=@CMEMOID AND B.XN_TYPE='WSL'  ) 
	--	BEGIN	
	--		SET @CERRORMSG='AUTO GENERATED INVOICE  .........CAN NOT '+@CTEXT
	--		RETURN
 --END
 	
END




