CREATE PROCEDURE SP_SEND_MIRROR_ARC_DATA_NEW--(LocId 3 digit change only increased the parameter width by Sanjay:01-11-2024)
(	
	 @CREQXNID VARCHAR(50)
    ,@CCURLOCID VARCHAR(4)
    ,@CARCT VARCHAR(20)    
	,@BDONOTCHKPENDINGCUST BIT=0    
	,@BACKNOWLEDGE BIT=0
	,@CERRMSG VARCHAR(1000) OUTPUT
)	
--WITH ENCRYPTION
AS 
/*
	SP_SEND_MIRROR_ARC_DATA_208_05_02_14 : THIS PROCEDURE WILL SEND APPROVAL RETURN DATA FROM LOCATION TO HO.
*/
BEGIN
	DECLARE @CMEMOID VARCHAR(50),
	@BRECFOUND BIT,@CSTEP VARCHAR(5),@CFILTERCONDITION VARCHAR(MAX),@CCUTOFFDATE VARCHAR(20)
	,@CKEYFIELD VARCHAR(100),@BPENDINGMSTFOUND BIT
BEGIN TRY 	
	---- CALL ACKNOWLEDGEMENT OF MEMO SUCCESSFUL MERGING AT MIRRORING SERVER
	
	SET @CSTEP=10
	SET @CMEMOID=@CREQXNID
	
	IF @BACKNOWLEDGE=1
		GOTO LBLTABLEINFO
    		
	SET @CSTEP=50
	
	SET @BPENDINGMSTFOUND=0
	
	IF @BDONOTCHKPENDINGCUST=0
		EXEC SP_SEND_MIRROR_XNSMST_DATA_NEW 'ARC',@CMEMOID,@CCURLOCID,@BDONOTCHKPENDINGCUST,@BPENDINGMSTFOUND OUTPUT,@CERRMSG OUTPUT
	
	PRINT (CASE WHEN @BPENDINGMSTFOUND=1 THEN 'PMST-Y' ELSE 'PMST-N' END)
	
	IF ISNULL(@BPENDINGMSTFOUND,0)=1
		GOTO END_PROC

LBLTABLEINFO:			
	---- POPULATE LIST OF TABLES 
/*ARC01106,LM01106,LMP01106,HD01106,CUSTDYM,AREA,CITY,STATE,EMPLOYEE,PAYMODE_XN_DET,PAYMODE_MST,PAYMODE_GRP_MST*/
	
	
	IF @BACKNOWLEDGE=1
		GOTO END_PROC
		
	SET @CSTEP=50
	---- SEND THE ARC MEMO MASTER TABLE
	SELECT DISTINCT 'ARC_ARC01106_MIRROR' AS TARGET_TABLENAME,A.*,@CMEMOID AS XN_ID FROM ARC01106 A WHERE A.ADV_REC_ID=@CMEMOID
	

	SET @CSTEP=55
	---- SEND THE WSL_ORDER_ADV_RECEIPT RELATED TO ARC TABLE  -
	SELECT DISTINCT 'ARC_WSL_ORDER_ADV_RECEIPT_MIRROR' AS TARGET_TABLENAME,A.* FROM WSL_ORDER_ADV_RECEIPT A
	WHERE A.ADV_REC_ID=@CMEMOID
	
	
	SET @CSTEP=60
	---- SEND THE EMPLOYEE HEAD RELATED TO LEDGERS TABLE
	SELECT DISTINCT 'ARC_PAYMODE_XN_DET_MIRROR' AS TARGET_TABLENAME,A.* FROM PAYMODE_XN_DET A
	WHERE XN_TYPE='ARC' AND A.MEMO_ID=@CMEMOID 
	
	SET @CSTEP=65
	---- SEND THE EMPLOYEE HEAD RELATED TO LEDGERS TABLE
	SELECT DISTINCT 'ARC_CMM_CREDIT_RECEIPT_MIRROR' AS TARGET_TABLENAME,A.* FROM CMM_CREDIT_RECEIPT A
	WHERE A.ADV_REC_ID=@CMEMOID 

	SET @CSTEP=70
	---- SEND THE GV'S SOLD DETAIL
	SELECT DISTINCT 'ARC_ARC_GVSALE_DETAILS_MIRROR' AS TARGET_TABLENAME,A.* FROM ARC_GVSALE_DETAILS A
	WHERE A.ADV_REC_ID=@CMEMOID 

	---- SEND THE GV'S SOLD DETAIL
	SELECT DISTINCT 'ARC_HBD_RECEIPT_MIRROR' AS TARGET_TABLENAME,A.* FROM HBD_RECEIPT A
	WHERE A.ADV_REC_ID=@CMEMOID 
	
	SET @CSTEP=75
	---- SEND THE CUSTOMER DATA
	SELECT DISTINCT 'ARC_CUSTDYM_MIRROR' AS TARGET_TABLENAME,A.*,@CMEMOID AS ARC_MEMO_ID FROM CUSTDYM A
	JOIN ARC01106 B ON A.CUSTOMER_CODE=B.CUSTOMER_CODE
	WHERE A.CUSTOMER_CODE<>'000000000000' AND B.ADV_REC_ID= @CMEMOID 

END TRY
BEGIN CATCH
	SET @CERRMSG='P: SP_SEND_MIRROR_ARC_DATA_NEW, STEP:'+@CSTEP+', MESSAGE:'+ERROR_MESSAGE()
	GOTO END_PROC
END CATCH 		

END_PROC:

END
---END OF PROCEDURE - SP_SEND_MIRROR_ARC_DATA_NEW
