CREATE PROCEDURE SP_RECAL_EXCISE
(
  @CMEMO_ID VARCHAR(100),
  @CERRORMSG VARCHAR(200) OUTPUT 
)
--WITH ENCRYPTION
AS
BEGIN
     
     DECLARE @ROW_ID VARCHAR(100),@PRODUCT_CODE VARCHAR(100),@AC_CODE VARCHAR(50),@CDEPTID VARCHAR(4),
     @CFORM_ID VARCHAR(20),@QTY NUMERIC(10,3),@ENABLE_EXCISE_DUTY VARCHAR(10),@CUSTOM_RATE_TYPE INT,@NSTEP VARCHAR(10),
     @INV_DT DATETIME,@CCUTOFDATE DATETIME
     IF OBJECT_ID ('TEMPDB..#TMPIND','U') IS NOT NULL
        DROP TABLE #TMPIND
      
   BEGIN TRY
      
      SET @NSTEP=10
      SELECT TOP 1 @ENABLE_EXCISE_DUTY=VALUE FROM CONFIG WHERE CONFIG_OPTION='ENABLE_EXCISE_DUTY'
      
      IF ISNULL(@ENABLE_EXCISE_DUTY,'')<>'1'
      GOTO END_PROC
      
      SET @CCUTOFDATE='2016-03-01' ---EXCISE ENABLED ON AFTER INVOICE MARCH 2016
      
      SELECT @AC_CODE=AC_CODE,@CDEPTID=PARTY_DEPT_ID,@INV_DT=INV_DT  FROM INM01106 WHERE INV_ID =@CMEMO_ID
      
      SET @NSTEP=20
      SELECT TOP 1 @CUSTOM_RATE_TYPE=CUSTOM_RATE_TYPE  FROM LMP01106 WHERE AC_CODE =@AC_CODE
      IF ISNULL(@CUSTOM_RATE_TYPE,0)<>1
      GOTO END_PROC
      
      UPDATE IND01106 SET ITEM_EXCISE_ACCESSIBLE_PERCENTAGE=0,
                           ITEM_EXCISE_ACCESSIBLE_AMOUNT=0,
                          ITEM_EXCISE_DUTY_PERCENTAGE=0,
                          ITEM_EXCISE_DUTY_AMOUNT=0,
                          ITEM_EXCISE_EDU_CESS_PERCENTAGE=0,
                          ITEM_EXCISE_EDU_CESS_AMOUNT=0,
                          ITEM_EXCISE_HEDU_CESS_PERCENTAGE=0,
                           ITEM_EXCISE_HEDU_CESS_AMOUNT=0
       WHERE INV_ID=@CMEMO_ID
      
      
      IF @INV_DT<= @CCUTOFDATE
      GOTO END_PROC
      
      SET @NSTEP=30
	  SELECT ROW_ID,PRODUCT_CODE ,QUANTITY,ITEM_FORM_ID 
	  INTO #TMPIND
	  FROM IND01106 WHERE INV_ID =@CMEMO_ID AND ISNULL(PRODUCT_CODE,'')<>''
      
     
       DECLARE  @TBLEXCISE TABLE (PRODUCT_CODE VARCHAR(50), RATE NUMERIC(12,2),	DISCOUNT_PERCENTAGE NUMERIC(12,2),DISCOUNT_AMOUNT NUMERIC(12,2),	
       OCTROI_PERCENTAGE NUMERIC(12,2),	OCTROI_AMOUNT NUMERIC(12,2),	NET_RATE NUMERIC(12,2),	
       RATE1 NUMERIC(12,2),	RATE2 NUMERIC(12,2),	RATE3 NUMERIC(12,2),	TAX_AMOUNT NUMERIC(12,2),	
       TAX_STATUS VARCHAR(50),TAX_PERCENTAGE NUMERIC(12,2),INV_TAX_STATUS VARCHAR(50),	
       TAX_METHOD NUMERIC(12,2),CURRENT_TAX_PERCENTAGE NUMERIC(12,2),	ITEM_EXCISE_MRP NUMERIC(12,2),	
       ITEM_EXCISE_ACCESSIBLE_PERCENTAGE NUMERIC(12,2),	ITEM_EXCISE_ACCESSIBLE_AMOUNT NUMERIC(12,2),	
       ITEM_EXCISE_DUTY_PERCENTAGE NUMERIC(12,2),	ITEM_EXCISE_DUTY_AMOUNT NUMERIC(12,2),	
       ITEM_EXCISE_EDU_CESS_PERCENTAGE NUMERIC(12,2),	
       ITEM_EXCISE_EDU_CESS_AMOUNT NUMERIC(12,2),	
       ITEM_EXCISE_HEDU_CESS_PERCENTAGE NUMERIC(12,2),	ITEM_EXCISE_HEDU_CESS_AMOUNT NUMERIC(12,2))
 
	WHILE EXISTS (SELECT TOP 1 'U' FROM #TMPIND)  
	BEGIN
    
    SELECT @ROW_ID='',@PRODUCT_CODE='',@CFORM_ID='',@QTY=0
    
    SELECT TOP 1 @ROW_ID=ROW_ID,@PRODUCT_CODE=PRODUCT_CODE,@CFORM_ID=ITEM_FORM_ID,@QTY = QUANTITY
    FROM #TMPIND
    
     SET @NSTEP=50
     INSERT INTO @TBLEXCISE(PRODUCT_CODE,RATE,DISCOUNT_PERCENTAGE,DISCOUNT_AMOUNT ,OCTROI_PERCENTAGE ,	OCTROI_AMOUNT ,	NET_RATE ,	
       RATE1 ,RATE2,	RATE3 ,	TAX_AMOUNT ,TAX_STATUS ,TAX_PERCENTAGE ,INV_TAX_STATUS ,TAX_METHOD ,
       CURRENT_TAX_PERCENTAGE ,	ITEM_EXCISE_MRP,ITEM_EXCISE_ACCESSIBLE_PERCENTAGE ,	ITEM_EXCISE_ACCESSIBLE_AMOUNT ,	
       ITEM_EXCISE_DUTY_PERCENTAGE ,ITEM_EXCISE_DUTY_AMOUNT,ITEM_EXCISE_EDU_CESS_PERCENTAGE ,ITEM_EXCISE_EDU_CESS_AMOUNT ,	
       ITEM_EXCISE_HEDU_CESS_PERCENTAGE ,	ITEM_EXCISE_HEDU_CESS_AMOUNT )
	 
	  EXEC SP_GETINVRATE
			@CPRODUCTCODE=@PRODUCT_CODE,
			@CACCODE=@AC_CODE,
			@CDEPTID=@CDEPTID,
			@CFORMID=@CFORM_ID,
			@NITEMLEVELDISCOUNT=0,
			@NQUANTITY=@QTY,
			@NBILLLEVELDISCOUNT=0
			

    
    SET @NSTEP=60
    UPDATE A SET ITEM_EXCISE_ACCESSIBLE_PERCENTAGE=ISNULL(B.ITEM_EXCISE_ACCESSIBLE_PERCENTAGE,0),
                 ITEM_EXCISE_ACCESSIBLE_AMOUNT=ISNULL(B.ITEM_EXCISE_ACCESSIBLE_AMOUNT,0),
                 ITEM_EXCISE_DUTY_PERCENTAGE=ISNULL(B.ITEM_EXCISE_DUTY_PERCENTAGE,0) ,
                 ITEM_EXCISE_DUTY_AMOUNT=ISNULL(B.ITEM_EXCISE_DUTY_AMOUNT,0),
                 ITEM_EXCISE_EDU_CESS_PERCENTAGE=ISNULL(B.ITEM_EXCISE_EDU_CESS_PERCENTAGE,0) ,
                 ITEM_EXCISE_EDU_CESS_AMOUNT=ISNULL(B.ITEM_EXCISE_EDU_CESS_AMOUNT,0),
                 ITEM_EXCISE_HEDU_CESS_PERCENTAGE=ISNULL(B.ITEM_EXCISE_HEDU_CESS_PERCENTAGE,0) ,
                 ITEM_EXCISE_HEDU_CESS_AMOUNT=ISNULL(B.ITEM_EXCISE_HEDU_CESS_AMOUNT,0)
    FROM IND01106 A
    JOIN
    (
     SELECT ITEM_EXCISE_ACCESSIBLE_PERCENTAGE,
			ITEM_EXCISE_ACCESSIBLE_AMOUNT,
			ITEM_EXCISE_DUTY_PERCENTAGE,
			ITEM_EXCISE_DUTY_AMOUNT,
			ITEM_EXCISE_EDU_CESS_PERCENTAGE,
			ITEM_EXCISE_EDU_CESS_AMOUNT,
			ITEM_EXCISE_HEDU_CESS_PERCENTAGE,
			ITEM_EXCISE_HEDU_CESS_AMOUNT
     FROM @TBLEXCISE
    ) B ON 1=1
    WHERE A.INV_ID =@CMEMO_ID AND ROW_ID=@ROW_ID
 
    DELETE FROM @TBLEXCISE 
    DELETE FROM #TMPIND WHERE ROW_ID =@ROW_ID
    

     END
  
   UPDATE A SET EXCISE_ACCESSIBLE_AMOUNT=ISNULL(B.ITEM_EXCISE_ACCESSIBLE_AMOUNT,0),
               EXCISE_DUTY_AMOUNT=ISNULL(B.ITEM_EXCISE_DUTY_AMOUNT,0),
               EXCISE_EDU_CESS_AMOUNT=ISNULL(B.ITEM_EXCISE_EDU_CESS_AMOUNT,0),         
               EXCISE_HEDU_CESS_AMOUNT=ISNULL(B.ITEM_EXCISE_HEDU_CESS_AMOUNT,0)
	FROM INM01106 A
	  JOIN 
	  (
		SELECT INV_ID ,
			   SUM(ISNULL(ITEM_EXCISE_ACCESSIBLE_AMOUNT,0)) AS ITEM_EXCISE_ACCESSIBLE_AMOUNT,
				SUM(ISNULL(ITEM_EXCISE_DUTY_AMOUNT,0)) AS ITEM_EXCISE_DUTY_AMOUNT,
				SUM(ISNULL(ITEM_EXCISE_EDU_CESS_AMOUNT,0)) AS ITEM_EXCISE_EDU_CESS_AMOUNT,
				SUM(ISNULL(ITEM_EXCISE_HEDU_CESS_AMOUNT,0)) AS ITEM_EXCISE_HEDU_CESS_AMOUNT
		 FROM IND01106
		 WHERE INV_ID =@CMEMO_ID
		 GROUP BY INV_ID
	  ) B ON A.INV_ID=B.INV_ID
	 WHERE A.INV_ID =@CMEMO_ID
     
     
 END TRY
	BEGIN CATCH
		SET @CERRORMSG = 'SP_RECAL_EXCISE : STEP- ' + LTRIM(STR(@NSTEP)) + ' SQL ERROR: #' + LTRIM(STR(ERROR_NUMBER())) + ' ' + ERROR_MESSAGE()
	GOTO END_PROC
	END CATCH
     
END_PROC:

END
