CREATE PROC VALIDATEXN_BDGPL_BEFORE_EDIT 
@CMEMOID VARCHAR(30),
@BCANCELXN BIT,
@CERRORMSG VARCHAR(200) OUTPUT,
@CEXPRERRORMSG VARCHAR(200) OUTPUT
--WITH ENCRYPTION
AS
BEGIN
	
	DECLARE @CTEXT VARCHAR(10),@EXPIRTY_DT DATETIME
	
	SET @CTEXT=(CASE WHEN @BCANCELXN=1 THEN 'CANCEL' ELSE 'EDIT' END)
		
	IF EXISTS(SELECT TOP 1 A.MEMO_NO FROM BUDGET_PLAN_MST A JOIN BUY_PLAN_MST B ON A.MEMO_NO=B.BUDGET_PLAN_MEMO_NO
			  WHERE A.MEMO_NO=@CMEMOID AND B.CANCELLED=0 )				  
	
	BEGIN
		SET @CERRORMSG='THIS MEMO HAS BEEN SETTLED IN BUY PLAN.........CAN NOT '+@CTEXT
		RETURN
	END
	
	SELECT TOP 1 @EXPIRTY_DT=EXPIRY_DT FROM BUDGET_PLAN_MST WHERE MEMO_NO=@CMEMOID
	
	
	IF DATEDIFF(DD,@EXPIRTY_DT,GETDATE()) > 0				  
	BEGIN
		SET @CERRORMSG='EXPIRY DATE OF MEMO SHOULD NOT BE GREATOR THEN CURRENT DATE.........CAN NOT '+@CTEXT
		RETURN
	END
	
END
