create PROCEDURE SALECONTRIBUTION	
(
	@CLAYOUTCOL VARCHAR(MAX),
	@CFILTERCOLS VARCHAR(MAX),
	@CLOCATIONID CHAR(4)='',
	@DTODT DATETIME,
	@MODE NUMERIC(1) 
)
--WITH ENCRYPTION
AS
/*
	@MODE=1 : BASED ON PURCHASE PRICE
	@MODE=2 : BASED ON MRP
	@MODE=3 : BASED ON QUANTITY
*/
BEGIN
	DECLARE @CCMD NVARCHAR(MAX),@NTOTAL_SALE NUMERIC(18,2)
	,@CWHERECLAUSE VARCHAR(MAX),@DFROMDT DATETIME,@CJOINCLAUSE NVARCHAR(MAX)
	
	SET @CWHERECLAUSE=''
	SET @CJOINCLAUSE=''
	
	IF @CLOCATIONID=''
		SELECT TOP 1 @CLOCATIONID=DEPT_ID FROM NEW_APP_LOGIN_INFO (nolock) WHERE SPID=@@SPID 
	
	IF @CLOCATIONID<>''
		SET @CWHERECLAUSE=' WHERE CMM01106.Location_code='''+@CLOCATIONID+''''
	
	SELECT @DFROMDT=DBO.FN_GETFINYEARDATE('01'+DBO.FN_GETFINYEAR(@DTODT),1)
	--IF @DFROMDT=''
		--SELECT @DFROMDT='2013-04-01',@DTODT='2013-07-31'
	
	SET @CWHERECLAUSE=@CWHERECLAUSE+(CASE WHEN @CWHERECLAUSE<>'' THEN ' AND ' ELSE ' WHERE ' END)+
					  ' CM_DT BETWEEN '''+CONVERT(VARCHAR,@DFROMDT,110)+''' AND '''+CONVERT(VARCHAR,@DTODT,110)+'''
					   AND CM_MODE=1 AND CANCELLED=0'	
	
	SET @CWHERECLAUSE=@CWHERECLAUSE+(CASE WHEN @CFILTERCOLS<>'' THEN ' AND ' ELSE '' END)+@CFILTERCOLS
	
	IF OBJECT_ID('TEMPDB..#ALL','U') IS NOT NULL
		DROP TABLE #ALL
		
	IF OBJECT_ID('TEMPDB..#ALLSTOCK','U') IS NOT NULL
		DROP TABLE #ALLSTOCK

	CREATE TABLE #ALL(LAYOUTCOL VARCHAR(200),CONTRIBUTION NUMERIC(6),SALE_AMOUNT NUMERIC(18,2),TOTAL_SALE NUMERIC(18,2))
	CREATE TABLE #ALLSTOCK(LAYOUTCOL VARCHAR(200),CONTRIBUTION_PP NUMERIC(6),CONTRIBUTION_MRP NUMERIC(6),CONTRIBUTION_QUANTITY NUMERIC(6),STOCK_PP NUMERIC(18,2),STOCK_MRP NUMERIC(18,2),STOCK_QUANTITY NUMERIC(18,2),TOTAL_STOCK_PP NUMERIC(18,2),TOTAL_STOCK_MRP NUMERIC(18,2),TOTAL_STOCK_QUANTITY NUMERIC(18,2))
	
	-----FORMATION OF JOIN CLAUSE
	IF CHARINDEX('PARA1_NAME',@CLAYOUTCOL)<>0 OR CHARINDEX('PARA1_NAME',@CFILTERCOLS)<>0
		SET @CJOINCLAUSE=@CJOINCLAUSE+' JOIN PARA1 (NOLOCK) ON SKU.PARA1_CODE=PARA1.PARA1_CODE '
	IF CHARINDEX('PARA2_NAME',@CLAYOUTCOL)<>0 OR CHARINDEX('PARA2_NAME',@CFILTERCOLS)<>0
		SET @CJOINCLAUSE=@CJOINCLAUSE+' JOIN PARA2 (NOLOCK) ON SKU.PARA2_CODE=PARA2.PARA2_CODE '
	IF CHARINDEX('PARA3_NAME',@CLAYOUTCOL)<>0 OR CHARINDEX('PARA3_NAME',@CFILTERCOLS)<>0
		SET @CJOINCLAUSE=@CJOINCLAUSE+' JOIN PARA3 (NOLOCK) ON SKU.PARA3_CODE=PARA3.PARA3_CODE '	
	IF CHARINDEX('PARA4_NAME',@CLAYOUTCOL)<>0 OR CHARINDEX('PARA4_NAME',@CFILTERCOLS)<>0
		SET @CJOINCLAUSE=@CJOINCLAUSE+' JOIN PARA4 (NOLOCK) ON SKU.PARA4_CODE=PARA4.PARA4_CODE '
	IF CHARINDEX('PARA5_NAME',@CLAYOUTCOL)<>0 OR CHARINDEX('PARA5_NAME',@CFILTERCOLS)<>0
		SET @CJOINCLAUSE=@CJOINCLAUSE+' JOIN PARA5 (NOLOCK) ON SKU.PARA5_CODE=PARA5.PARA5_CODE '
	IF CHARINDEX('PARA6_NAME',@CLAYOUTCOL)<>0 OR CHARINDEX('PARA6_NAME',@CFILTERCOLS)<>0
		SET @CJOINCLAUSE=@CJOINCLAUSE+' JOIN PARA6 (NOLOCK) ON SKU.PARA6_CODE=PARA6.PARA6_CODE '			
	IF CHARINDEX('LMV01106.',@CLAYOUTCOL)<>0 OR CHARINDEX('LMV01106.',@CFILTERCOLS)<>0
		SET @CJOINCLAUSE=@CJOINCLAUSE+' JOIN LM01106 LMV01106 (NOLOCK) ON SKU.AC_CODE=LMV01106.AC_CODE '				
		
	--CALCULATING SALE AMOUNT CONTRIBUTION
	SET @CCMD=N'SELECT '+@CLAYOUTCOL+',(CASE WHEN NET.TOTAL_SALE=0 THEN 0 ELSE (SUM(CMD01106.RFNET)/NET.TOTAL_SALE)*100 END) AS CONTRIBUTION
				,SUM(CMD01106.RFNET) AS SALE_AMOUNT,NET.TOTAL_SALE AS TOTAL_SALE 
				FROM CMM01106 (NOLOCK) 
				JOIN CMD01106 (NOLOCK) ON CMM01106.CM_ID=CMD01106.CM_ID
				JOIN SKU (NOLOCK) ON CMD01106.PRODUCT_CODE=SKU.PRODUCT_CODE
				JOIN ARTICLE (NOLOCK) ON SKU.ARTICLE_CODE=ARTICLE.ARTICLE_CODE
				'+@CJOINCLAUSE+'
				LEFT OUTER JOIN article_fix_attr ATTR  (NOLOCK) ON article.article_code = ATTR.ARTICLE_CODE 
				LEFT OUTER JOIN attr1_mst at1 (NOLOCK) ON at1.attr1_key_code=ATTR.attr1_key_code
				LEFT OUTER JOIN attr2_mst at2 (NOLOCK) ON at2.attr2_key_code=ATTR.attr2_key_code
				LEFT OUTER JOIN attr3_mst at3 (NOLOCK) ON at3.attr3_key_code=ATTR.attr3_key_code
				LEFT OUTER JOIN attr4_mst at4 (NOLOCK) ON at4.attr4_key_code=ATTR.attr4_key_code
				LEFT OUTER JOIN attr5_mst at5 (NOLOCK) ON at5.attr5_key_code=ATTR.attr5_key_code
				LEFT OUTER JOIN attr6_mst at6 (NOLOCK) ON at6.attr6_key_code=ATTR.attr6_key_code
				LEFT OUTER JOIN attr7_mst at7 (NOLOCK) ON at7.attr7_key_code=ATTR.attr7_key_code
				LEFT OUTER JOIN attr8_mst at8 (NOLOCK) ON at8.attr8_key_code=ATTR.attr8_key_code
				LEFT OUTER JOIN attr9_mst at9 (NOLOCK) ON at9.attr9_key_code=ATTR.attr9_key_code
				LEFT OUTER JOIN attr10_mst at10 (NOLOCK) ON at10.attr10_key_code=ATTR.attr10_key_code
				LEFT OUTER JOIN attr11_mst at11 (NOLOCK) ON at11.attr11_key_code=ATTR.attr11_key_code
				LEFT OUTER JOIN attr12_mst at12 (NOLOCK) ON at12.attr12_key_code=ATTR.attr12_key_code
				LEFT OUTER JOIN attr13_mst at13 (NOLOCK) ON at13.attr13_key_code=ATTR.attr13_key_code
				LEFT OUTER JOIN attr14_mst at14 (NOLOCK) ON at14.attr14_key_code=ATTR.attr14_key_code
				LEFT OUTER JOIN attr15_mst at15 (NOLOCK) ON at15.attr15_key_code=ATTR.attr15_key_code
				LEFT OUTER JOIN attr16_mst at16 (NOLOCK) ON at16.attr16_key_code=ATTR.attr16_key_code
				LEFT OUTER JOIN attr17_mst at17 (NOLOCK) ON at17.attr17_key_code=ATTR.attr17_key_code
				LEFT OUTER JOIN attr18_mst at18 (NOLOCK) ON at18.attr18_key_code=ATTR.attr18_key_code
				LEFT OUTER JOIN attr19_mst at19 (NOLOCK) ON at19.attr19_key_code=ATTR.attr19_key_code
				LEFT OUTER JOIN attr20_mst at20 (NOLOCK) ON at20.attr20_key_code=ATTR.attr20_key_code
				LEFT OUTER JOIN attr21_mst at21 (NOLOCK) ON at21.attr21_key_code=ATTR.attr21_key_code
				LEFT OUTER JOIN attr22_mst at22 (NOLOCK) ON at22.attr22_key_code=ATTR.attr22_key_code
				LEFT OUTER JOIN attr23_mst at23 (NOLOCK) ON at23.attr23_key_code=ATTR.attr23_key_code
				LEFT OUTER JOIN attr24_mst at24 (NOLOCK) ON at24.attr24_key_code=ATTR.attr24_key_code
				LEFT OUTER JOIN attr25_mst at25(NOLOCK) ON at25.attr25_key_code=ATTR.attr25_key_code
				JOIN SECTIOND (NOLOCK) ON ARTICLE.SUB_SECTION_CODE=SECTIOND.SUB_SECTION_CODE
				JOIN SECTIONM (NOLOCK) ON SECTIOND.SECTION_CODE=SECTIONM.SECTION_CODE
				LEFT JOIN
				(
					SELECT SUM(RFNET) AS TOTAL_SALE 
					FROM CMM01106 (NOLOCK)
					JOIN CMD01106 (NOLOCK) ON CMM01106.CM_ID=CMD01106.CM_ID
					JOIN SKU (NOLOCK) ON CMD01106.PRODUCT_CODE=SKU.PRODUCT_CODE
					JOIN ARTICLE (NOLOCK) ON SKU.ARTICLE_CODE=ARTICLE.ARTICLE_CODE
					'+@CJOINCLAUSE+'
					LEFT OUTER JOIN article_fix_attr ATTR  (NOLOCK) ON article.article_code = ATTR.ARTICLE_CODE 
				LEFT OUTER JOIN attr1_mst at1 (NOLOCK) ON at1.attr1_key_code=ATTR.attr1_key_code
				LEFT OUTER JOIN attr2_mst at2 (NOLOCK) ON at2.attr2_key_code=ATTR.attr2_key_code
				LEFT OUTER JOIN attr3_mst at3 (NOLOCK) ON at3.attr3_key_code=ATTR.attr3_key_code
				LEFT OUTER JOIN attr4_mst at4 (NOLOCK) ON at4.attr4_key_code=ATTR.attr4_key_code
				LEFT OUTER JOIN attr5_mst at5 (NOLOCK) ON at5.attr5_key_code=ATTR.attr5_key_code
				LEFT OUTER JOIN attr6_mst at6 (NOLOCK) ON at6.attr6_key_code=ATTR.attr6_key_code
				LEFT OUTER JOIN attr7_mst at7 (NOLOCK) ON at7.attr7_key_code=ATTR.attr7_key_code
				LEFT OUTER JOIN attr8_mst at8 (NOLOCK) ON at8.attr8_key_code=ATTR.attr8_key_code
				LEFT OUTER JOIN attr9_mst at9 (NOLOCK) ON at9.attr9_key_code=ATTR.attr9_key_code
				LEFT OUTER JOIN attr10_mst at10 (NOLOCK) ON at10.attr10_key_code=ATTR.attr10_key_code
				LEFT OUTER JOIN attr11_mst at11 (NOLOCK) ON at11.attr11_key_code=ATTR.attr11_key_code
				LEFT OUTER JOIN attr12_mst at12 (NOLOCK) ON at12.attr12_key_code=ATTR.attr12_key_code
				LEFT OUTER JOIN attr13_mst at13 (NOLOCK) ON at13.attr13_key_code=ATTR.attr13_key_code
				LEFT OUTER JOIN attr14_mst at14 (NOLOCK) ON at14.attr14_key_code=ATTR.attr14_key_code
				LEFT OUTER JOIN attr15_mst at15 (NOLOCK) ON at15.attr15_key_code=ATTR.attr15_key_code
				LEFT OUTER JOIN attr16_mst at16 (NOLOCK) ON at16.attr16_key_code=ATTR.attr16_key_code
				LEFT OUTER JOIN attr17_mst at17 (NOLOCK) ON at17.attr17_key_code=ATTR.attr17_key_code
				LEFT OUTER JOIN attr18_mst at18 (NOLOCK) ON at18.attr18_key_code=ATTR.attr18_key_code
				LEFT OUTER JOIN attr19_mst at19 (NOLOCK) ON at19.attr19_key_code=ATTR.attr19_key_code
				LEFT OUTER JOIN attr20_mst at20 (NOLOCK) ON at20.attr20_key_code=ATTR.attr20_key_code
				LEFT OUTER JOIN attr21_mst at21 (NOLOCK) ON at21.attr21_key_code=ATTR.attr21_key_code
				LEFT OUTER JOIN attr22_mst at22 (NOLOCK) ON at22.attr22_key_code=ATTR.attr22_key_code
				LEFT OUTER JOIN attr23_mst at23 (NOLOCK) ON at23.attr23_key_code=ATTR.attr23_key_code
				LEFT OUTER JOIN attr24_mst at24 (NOLOCK) ON at24.attr24_key_code=ATTR.attr24_key_code
				LEFT OUTER JOIN attr25_mst at25(NOLOCK) ON at25.attr25_key_code=ATTR.attr25_key_code
					JOIN SECTIOND (NOLOCK) ON ARTICLE.SUB_SECTION_CODE=SECTIOND.SUB_SECTION_CODE
					JOIN SECTIONM (NOLOCK) ON SECTIOND.SECTION_CODE=SECTIONM.SECTION_CODE
					'+@CWHERECLAUSE+' 
				)NET ON 1=1 
				'
				+@CWHERECLAUSE
				+' GROUP BY NET.TOTAL_SALE,'+@CLAYOUTCOL
	PRINT @CCMD	
	INSERT #ALL
	EXEC SP_EXECUTESQL @CCMD
	
	--CALCULATING STOCK AMOUNT CONTRIBUTION
	IF @CLOCATIONID<>''
		SET @CWHERECLAUSE=' WHERE A.DEPT_ID='''+@CLOCATIONID+''''
	ELSE
		SET @CWHERECLAUSE='' 
	
	SET @CWHERECLAUSE=@CWHERECLAUSE+(CASE WHEN @CWHERECLAUSE<>'' THEN ' AND ' ELSE ' WHERE ' END)+
					  ' ARTICLE.STOCK_NA=0 AND A.XN_DT BETWEEN '''+CONVERT(VARCHAR,@DFROMDT,110)+''' AND '''+CONVERT(VARCHAR,@DTODT,110)+''''
					  
	SET @CWHERECLAUSE=@CWHERECLAUSE+(CASE WHEN @CFILTERCOLS<>'' THEN ' AND ' ELSE '' END)+@CFILTERCOLS					  	
	
	SET @CCMD=N'SELECT '+@CLAYOUTCOL+'
				,(CASE WHEN NET.TOTAL_STOCK_PP=0 THEN 0 ELSE ((SUM(CASE WHEN A.XN_TYPE IN (''OPS'', ''PUR'',''CHI'',''SLR'',''UNC'',''APR'', ''WSR'', ''PFI'', ''BCG'',''MRP'',''DCI'',''PSB'',''JWR'') 
							THEN A.XN_QTY*(SKU.PURCHASE_PRICE-ISNULL(SKU_OH.DISCOUNT_AMOUNT,0)+(CASE WHEN POST_TAX_SEPARATELY=1 THEN 0
							ELSE ISNULL(SKU_OH.TAX_AMOUNT,0) END)) 
							WHEN A.XN_TYPE IN (''PRT'',''CHO'',''SLS'',''CNC'',''APP'',''WSL'',''CIP'',''DCO'',''MIP'',''CSB'',''JWI'',''DLM'') 
							THEN -XN_QTY*(SKU.PURCHASE_PRICE-ISNULL(SKU_OH.DISCOUNT_AMOUNT,0)+(CASE WHEN POST_TAX_SEPARATELY=1 THEN 0
							ELSE  ISNULL(SKU_OH.TAX_AMOUNT,0) END)) ELSE 0 END))/NET.TOTAL_STOCK_PP)*100 END) AS CONTRIBUTION_PP
				,(CASE WHEN NET.TOTAL_STOCK_MRP=0 THEN 0 ELSE ((SUM(CASE WHEN A.XN_TYPE IN (''OPS'', ''PUR'',''CHI'',''SLR'',''UNC'',''APR'', ''WSR'', ''PFI'', ''BCG'',''MRP'',''DCI'',''PSB'',''JWR'') 
							THEN A.XN_QTY*SKU.MRP
							WHEN A.XN_TYPE IN (''PRT'',''CHO'',''SLS'',''CNC'',''APP'',''WSL'',''CIP'',''DCO'',''MIP'',''CSB'',''JWI'',''DLM'') 
							THEN -XN_QTY*SKU.MRP ELSE 0 END))/NET.TOTAL_STOCK_MRP)*100 END) AS CONTRIBUTION_MRP
				,(CASE WHEN NET.TOTAL_STOCK_QUANTITY=0 THEN 0 ELSE ((SUM(CASE WHEN A.XN_TYPE IN (''OPS'', ''PUR'',''CHI'',''SLR'',''UNC'',''APR'', ''WSR'', ''PFI'', ''BCG'',''MRP'',''DCI'',''PSB'',''JWR'') 
							THEN A.XN_QTY
							WHEN A.XN_TYPE IN (''PRT'',''CHO'',''SLS'',''CNC'',''APP'',''WSL'',''CIP'',''DCO'',''MIP'',''CSB'',''JWI'',''DLM'') 
							THEN -XN_QTY ELSE 0 END))/NET.TOTAL_STOCK_QUANTITY)*100 END) AS CONTRIBUTION_QUANTITY
				,SUM(CASE WHEN A.XN_TYPE IN (''OPS'', ''PUR'',''CHI'',''SLR'',''UNC'',''APR'', ''WSR'', ''PFI'', ''BCG'',''MRP'',''DCI'',''PSB'',''JWR'') 
							THEN A.XN_QTY*(SKU.PURCHASE_PRICE-ISNULL(SKU_OH.DISCOUNT_AMOUNT,0)+(CASE WHEN POST_TAX_SEPARATELY=1 THEN 0
							ELSE ISNULL(SKU_OH.TAX_AMOUNT,0) END)) 
							WHEN A.XN_TYPE IN (''PRT'',''CHO'',''SLS'',''CNC'',''APP'',''WSL'',''CIP'',''DCO'',''MIP'',''CSB'',''JWI'',''DLM'') 
							THEN -XN_QTY*(SKU.PURCHASE_PRICE-ISNULL(SKU_OH.DISCOUNT_AMOUNT,0)+(CASE WHEN POST_TAX_SEPARATELY=1 THEN 0
							ELSE  ISNULL(SKU_OH.TAX_AMOUNT,0) END)) ELSE 0 END) AS STOCK_PP							
				,SUM(CASE WHEN A.XN_TYPE IN (''OPS'', ''PUR'',''CHI'',''SLR'',''UNC'',''APR'', ''WSR'', ''PFI'', ''BCG'',''MRP'',''DCI'',''PSB'',''JWR'') 
							THEN A.XN_QTY*SKU.MRP
							WHEN A.XN_TYPE IN (''PRT'',''CHO'',''SLS'',''CNC'',''APP'',''WSL'',''CIP'',''DCO'',''MIP'',''CSB'',''JWI'',''DLM'') 
							THEN -XN_QTY*SKU.MRP ELSE 0 END) AS STOCK_MRP										
				,SUM(CASE WHEN A.XN_TYPE IN (''OPS'', ''PUR'',''CHI'',''SLR'',''UNC'',''APR'', ''WSR'', ''PFI'', ''BCG'',''MRP'',''DCI'',''PSB'',''JWR'') 
							THEN A.XN_QTY
							WHEN A.XN_TYPE IN (''PRT'',''CHO'',''SLS'',''CNC'',''APP'',''WSL'',''CIP'',''DCO'',''MIP'',''CSB'',''JWI'',''DLM'') 
							THEN -XN_QTY ELSE 0 END) AS STOCK_QUANTITY
				,NET.TOTAL_STOCK_PP 
				,NET.TOTAL_STOCK_MRP 
				,NET.TOTAL_STOCK_QUANTITY 
				FROM '+DB_NAME()+'_RFOPT..RF_OPT A (NOLOCK) 
				JOIN SKU (NOLOCK) ON A.PRODUCT_CODE=SKU.PRODUCT_CODE
				JOIN FORM (NOLOCK) ON FORM.FORM_ID=SKU.FORM_ID
				LEFT JOIN SKU_OH (NOLOCK) ON SKU_OH.PRODUCT_CODE=SKU.PRODUCT_CODE
				JOIN ARTICLE (NOLOCK) ON SKU.ARTICLE_CODE=ARTICLE.ARTICLE_CODE
				'+@CJOINCLAUSE+'
				LEFT OUTER JOIN article_fix_attr ATTR  (NOLOCK) ON article.article_code = ATTR.ARTICLE_CODE 
				LEFT OUTER JOIN attr1_mst at1 (NOLOCK) ON at1.attr1_key_code=ATTR.attr1_key_code
				LEFT OUTER JOIN attr2_mst at2 (NOLOCK) ON at2.attr2_key_code=ATTR.attr2_key_code
				LEFT OUTER JOIN attr3_mst at3 (NOLOCK) ON at3.attr3_key_code=ATTR.attr3_key_code
				LEFT OUTER JOIN attr4_mst at4 (NOLOCK) ON at4.attr4_key_code=ATTR.attr4_key_code
				LEFT OUTER JOIN attr5_mst at5 (NOLOCK) ON at5.attr5_key_code=ATTR.attr5_key_code
				LEFT OUTER JOIN attr6_mst at6 (NOLOCK) ON at6.attr6_key_code=ATTR.attr6_key_code
				LEFT OUTER JOIN attr7_mst at7 (NOLOCK) ON at7.attr7_key_code=ATTR.attr7_key_code
				LEFT OUTER JOIN attr8_mst at8 (NOLOCK) ON at8.attr8_key_code=ATTR.attr8_key_code
				LEFT OUTER JOIN attr9_mst at9 (NOLOCK) ON at9.attr9_key_code=ATTR.attr9_key_code
				LEFT OUTER JOIN attr10_mst at10 (NOLOCK) ON at10.attr10_key_code=ATTR.attr10_key_code
				LEFT OUTER JOIN attr11_mst at11 (NOLOCK) ON at11.attr11_key_code=ATTR.attr11_key_code
				LEFT OUTER JOIN attr12_mst at12 (NOLOCK) ON at12.attr12_key_code=ATTR.attr12_key_code
				LEFT OUTER JOIN attr13_mst at13 (NOLOCK) ON at13.attr13_key_code=ATTR.attr13_key_code
				LEFT OUTER JOIN attr14_mst at14 (NOLOCK) ON at14.attr14_key_code=ATTR.attr14_key_code
				LEFT OUTER JOIN attr15_mst at15 (NOLOCK) ON at15.attr15_key_code=ATTR.attr15_key_code
				LEFT OUTER JOIN attr16_mst at16 (NOLOCK) ON at16.attr16_key_code=ATTR.attr16_key_code
				LEFT OUTER JOIN attr17_mst at17 (NOLOCK) ON at17.attr17_key_code=ATTR.attr17_key_code
				LEFT OUTER JOIN attr18_mst at18 (NOLOCK) ON at18.attr18_key_code=ATTR.attr18_key_code
				LEFT OUTER JOIN attr19_mst at19 (NOLOCK) ON at19.attr19_key_code=ATTR.attr19_key_code
				LEFT OUTER JOIN attr20_mst at20 (NOLOCK) ON at20.attr20_key_code=ATTR.attr20_key_code
				LEFT OUTER JOIN attr21_mst at21 (NOLOCK) ON at21.attr21_key_code=ATTR.attr21_key_code
				LEFT OUTER JOIN attr22_mst at22 (NOLOCK) ON at22.attr22_key_code=ATTR.attr22_key_code
				LEFT OUTER JOIN attr23_mst at23 (NOLOCK) ON at23.attr23_key_code=ATTR.attr23_key_code
				LEFT OUTER JOIN attr24_mst at24 (NOLOCK) ON at24.attr24_key_code=ATTR.attr24_key_code
				LEFT OUTER JOIN attr25_mst at25(NOLOCK) ON at25.attr25_key_code=ATTR.attr25_key_code
				JOIN SECTIOND (NOLOCK) ON ARTICLE.SUB_SECTION_CODE=SECTIOND.SUB_SECTION_CODE
				JOIN SECTIONM (NOLOCK) ON SECTIOND.SECTION_CODE=SECTIONM.SECTION_CODE
				LEFT JOIN
				(
					SELECT 
							SUM(CASE WHEN A.XN_TYPE IN (''OPS'', ''PUR'',''CHI'',''SLR'',''UNC'',''APR'', ''WSR'', ''PFI'', ''BCG'',''MRP'',''DCI'',''PSB'',''JWR'') 
							THEN A.XN_QTY*(SKU.PURCHASE_PRICE-ISNULL(SKU_OH.DISCOUNT_AMOUNT,0)+(CASE WHEN POST_TAX_SEPARATELY=1 THEN 0
							ELSE ISNULL(SKU_OH.TAX_AMOUNT,0) END)) 
							WHEN A.XN_TYPE IN (''PRT'',''CHO'',''SLS'',''CNC'',''APP'',''WSL'',''CIP'',''DCO'',''MIP'',''CSB'',''JWI'',''DLM'') 
							THEN -XN_QTY*(SKU.PURCHASE_PRICE-ISNULL(SKU_OH.DISCOUNT_AMOUNT,0)+(CASE WHEN POST_TAX_SEPARATELY=1 THEN 0
							ELSE  ISNULL(SKU_OH.TAX_AMOUNT,0) END)) ELSE 0 END) AS TOTAL_STOCK_PP 
						   ,SUM(CASE WHEN A.XN_TYPE IN (''OPS'', ''PUR'',''CHI'',''SLR'',''UNC'',''APR'', ''WSR'', ''PFI'', ''BCG'',''MRP'',''DCI'',''PSB'',''JWR'') 
							THEN A.XN_QTY*SKU.MRP
							WHEN A.XN_TYPE IN (''PRT'',''CHO'',''SLS'',''CNC'',''APP'',''WSL'',''CIP'',''DCO'',''MIP'',''CSB'',''JWI'',''DLM'') 
							THEN -XN_QTY*SKU.MRP ELSE 0 END) AS TOTAL_STOCK_MRP 
						   ,SUM(CASE WHEN A.XN_TYPE IN (''OPS'', ''PUR'',''CHI'',''SLR'',''UNC'',''APR'', ''WSR'', ''PFI'', ''BCG'',''MRP'',''DCI'',''PSB'',''JWR'') 
						    THEN A.XN_QTY
							WHEN A.XN_TYPE IN (''PRT'',''CHO'',''SLS'',''CNC'',''APP'',''WSL'',''CIP'',''DCO'',''MIP'',''CSB'',''JWI'',''DLM'') 
							THEN -XN_QTY ELSE 0 END) AS TOTAL_STOCK_QUANTITY 
					FROM '+DB_NAME()+'_RFOPT..RF_OPT A (NOLOCK) 
					JOIN SKU (NOLOCK) ON A.PRODUCT_CODE=SKU.PRODUCT_CODE
					JOIN FORM (NOLOCK) ON FORM.FORM_ID=SKU.FORM_ID
					LEFT JOIN SKU_OH (NOLOCK) ON SKU_OH.PRODUCT_CODE=SKU.PRODUCT_CODE
					JOIN ARTICLE (NOLOCK) ON SKU.ARTICLE_CODE=ARTICLE.ARTICLE_CODE
					'+@CJOINCLAUSE+'
					LEFT OUTER JOIN article_fix_attr ATTR  (NOLOCK) ON article.article_code = ATTR.ARTICLE_CODE 
				LEFT OUTER JOIN attr1_mst at1 (NOLOCK) ON at1.attr1_key_code=ATTR.attr1_key_code
				LEFT OUTER JOIN attr2_mst at2 (NOLOCK) ON at2.attr2_key_code=ATTR.attr2_key_code
				LEFT OUTER JOIN attr3_mst at3 (NOLOCK) ON at3.attr3_key_code=ATTR.attr3_key_code
				LEFT OUTER JOIN attr4_mst at4 (NOLOCK) ON at4.attr4_key_code=ATTR.attr4_key_code
				LEFT OUTER JOIN attr5_mst at5 (NOLOCK) ON at5.attr5_key_code=ATTR.attr5_key_code
				LEFT OUTER JOIN attr6_mst at6 (NOLOCK) ON at6.attr6_key_code=ATTR.attr6_key_code
				LEFT OUTER JOIN attr7_mst at7 (NOLOCK) ON at7.attr7_key_code=ATTR.attr7_key_code
				LEFT OUTER JOIN attr8_mst at8 (NOLOCK) ON at8.attr8_key_code=ATTR.attr8_key_code
				LEFT OUTER JOIN attr9_mst at9 (NOLOCK) ON at9.attr9_key_code=ATTR.attr9_key_code
				LEFT OUTER JOIN attr10_mst at10 (NOLOCK) ON at10.attr10_key_code=ATTR.attr10_key_code
				LEFT OUTER JOIN attr11_mst at11 (NOLOCK) ON at11.attr11_key_code=ATTR.attr11_key_code
				LEFT OUTER JOIN attr12_mst at12 (NOLOCK) ON at12.attr12_key_code=ATTR.attr12_key_code
				LEFT OUTER JOIN attr13_mst at13 (NOLOCK) ON at13.attr13_key_code=ATTR.attr13_key_code
				LEFT OUTER JOIN attr14_mst at14 (NOLOCK) ON at14.attr14_key_code=ATTR.attr14_key_code
				LEFT OUTER JOIN attr15_mst at15 (NOLOCK) ON at15.attr15_key_code=ATTR.attr15_key_code
				LEFT OUTER JOIN attr16_mst at16 (NOLOCK) ON at16.attr16_key_code=ATTR.attr16_key_code
				LEFT OUTER JOIN attr17_mst at17 (NOLOCK) ON at17.attr17_key_code=ATTR.attr17_key_code
				LEFT OUTER JOIN attr18_mst at18 (NOLOCK) ON at18.attr18_key_code=ATTR.attr18_key_code
				LEFT OUTER JOIN attr19_mst at19 (NOLOCK) ON at19.attr19_key_code=ATTR.attr19_key_code
				LEFT OUTER JOIN attr20_mst at20 (NOLOCK) ON at20.attr20_key_code=ATTR.attr20_key_code
				LEFT OUTER JOIN attr21_mst at21 (NOLOCK) ON at21.attr21_key_code=ATTR.attr21_key_code
				LEFT OUTER JOIN attr22_mst at22 (NOLOCK) ON at22.attr22_key_code=ATTR.attr22_key_code
				LEFT OUTER JOIN attr23_mst at23 (NOLOCK) ON at23.attr23_key_code=ATTR.attr23_key_code
				LEFT OUTER JOIN attr24_mst at24 (NOLOCK) ON at24.attr24_key_code=ATTR.attr24_key_code
				LEFT OUTER JOIN attr25_mst at25(NOLOCK) ON at25.attr25_key_code=ATTR.attr25_key_code
					JOIN SECTIOND (NOLOCK) ON ARTICLE.SUB_SECTION_CODE=SECTIOND.SUB_SECTION_CODE
					JOIN SECTIONM (NOLOCK) ON SECTIOND.SECTION_CODE=SECTIONM.SECTION_CODE
					'+@CWHERECLAUSE+' 
				)NET ON 1=1 
				'
				+@CWHERECLAUSE
				+' GROUP BY NET.TOTAL_STOCK_PP,NET.TOTAL_STOCK_MRP,NET.TOTAL_STOCK_QUANTITY,'+@CLAYOUTCOL
	PRINT @CCMD	
	INSERT #ALLSTOCK(LAYOUTCOL,CONTRIBUTION_PP,CONTRIBUTION_MRP,CONTRIBUTION_QUANTITY,STOCK_PP,STOCK_MRP,STOCK_QUANTITY,TOTAL_STOCK_PP,TOTAL_STOCK_MRP,TOTAL_STOCK_QUANTITY)
	EXEC SP_EXECUTESQL @CCMD
	
	IF OBJECT_ID('TEMPDB..#TOP5','U') IS NOT NULL
	DROP TABLE #TOP5
	
	IF OBJECT_ID('TEMPDB..#TOP5_STOCK_PP','U') IS NOT NULL
	DROP TABLE #TOP5_STOCK_PP
	
	IF OBJECT_ID('TEMPDB..#TOP5_STOCK_MRP','U') IS NOT NULL
	DROP TABLE #TOP5_STOCK_MRP

	IF OBJECT_ID('TEMPDB..#TOP5_STOCK_QTY','U') IS NOT NULL
	DROP TABLE #TOP5_STOCK_QTY
	
	SELECT TOP 5 * 
	INTO #TOP5
	FROM #ALL
	ORDER BY SALE_AMOUNT DESC
	
	SELECT TOP 5 LAYOUTCOL,CONTRIBUTION_PP AS CONTRIBUTION,STOCK_PP AS STOCK
	INTO #TOP5_STOCK_PP
	FROM #ALLSTOCK
	ORDER BY STOCK_PP DESC
	
	SELECT TOP 5 LAYOUTCOL,CONTRIBUTION_MRP AS CONTRIBUTION,STOCK_MRP AS STOCK
	INTO #TOP5_STOCK_MRP
	FROM #ALLSTOCK
	ORDER BY STOCK_MRP DESC
	
	SELECT TOP 5 LAYOUTCOL,CONTRIBUTION_QUANTITY AS CONTRIBUTION,STOCK_QUANTITY AS STOCK
	INTO #TOP5_STOCK_QTY
	FROM #ALLSTOCK
	ORDER BY STOCK_QUANTITY DESC

	SELECT LAYOUTCOL,CONTRIBUTION
	,RTRIM(UPPER(LAYOUTCOL))+' : [ '+CONVERT(VARCHAR, CONTRIBUTION) +' % ]' AS LAYOUT_CONTRI
	FROM #TOP5
	UNION ALL
	SELECT 'OTHERS' AS LAYOUTCOL,(100.00-SUM(ISNULL(CONTRIBUTION,0))) AS CONTRIBUTION
	,'OTHERS : [ '+CONVERT(VARCHAR, CONVERT(NUMERIC(6),(100-ISNULL(SUM(CONTRIBUTION),0)))) +' % ]' AS LAYOUT_CONTRI
	FROM #TOP5
	HAVING SUM(ISNULL(CONTRIBUTION,0))>0

IF @MODE=1
BEGIN	
	SELECT LAYOUTCOL,CONTRIBUTION
	,RTRIM(UPPER(LAYOUTCOL))+' : [ '+CONVERT(VARCHAR, CONTRIBUTION) +' % ]' AS LAYOUT_CONTRI
	FROM #TOP5_STOCK_PP
	UNION ALL
	SELECT 'OTHERS' AS LAYOUTCOL,(100.00-SUM(ISNULL(CONTRIBUTION,0))) AS CONTRIBUTION
	,'OTHERS : [ '+CONVERT(VARCHAR, CONVERT(NUMERIC(6),(100-ISNULL(SUM(CONTRIBUTION),0)))) +' % ]' AS LAYOUT_CONTRI
	FROM #TOP5_STOCK_PP
	HAVING SUM(ISNULL(CONTRIBUTION,0))>0
END	
ELSE IF @MODE=2
BEGIN	
	SELECT LAYOUTCOL,CONTRIBUTION
	,RTRIM(UPPER(LAYOUTCOL))+' : [ '+CONVERT(VARCHAR, CONTRIBUTION) +' % ]' AS LAYOUT_CONTRI
	FROM #TOP5_STOCK_MRP
	UNION ALL
	SELECT 'OTHERS' AS LAYOUTCOL,(100.00-SUM(ISNULL(CONTRIBUTION,0))) AS CONTRIBUTION
	,'OTHERS : [ '+CONVERT(VARCHAR, CONVERT(NUMERIC(6),(100-ISNULL(SUM(CONTRIBUTION),0)))) +' % ]' AS LAYOUT_CONTRI
	FROM #TOP5_STOCK_MRP
	HAVING SUM(ISNULL(CONTRIBUTION,0))>0
END	
ELSE IF @MODE=3
BEGIN	
	SELECT LAYOUTCOL,CONTRIBUTION
	,RTRIM(UPPER(LAYOUTCOL))+' : [ '+CONVERT(VARCHAR, CONTRIBUTION) +' % ]' AS LAYOUT_CONTRI
	FROM #TOP5_STOCK_QTY
	UNION ALL
	SELECT 'OTHERS' AS LAYOUTCOL,(100-SUM(ISNULL(CONTRIBUTION,0))) AS CONTRIBUTION
	,'OTHERS : [ '+CONVERT(VARCHAR, CONVERT(NUMERIC(6),(100.00-ISNULL(SUM(CONTRIBUTION),0)))) +' % ]' AS LAYOUT_CONTRI
	FROM #TOP5_STOCK_QTY
	HAVING SUM(ISNULL(CONTRIBUTION,0))>0
END	
END
--END OF PROCEDURE - SALECONTRIBUTION
