CREATE PROCEDURE SP_ARTICLE_COMPONENT_SETUP_SUFFIX      
@NQUERYID NUMERIC(3,0),          
@CMEMO VARCHAR(50)='',  
@CFINYEAR VARCHAR(5) ,  
@CWHERE VARCHAR(5000)='',  
@NNAVMODE NUMERIC(1,0),
@CMODE VARCHAR(10)   
   
--WITH ENCRYPTION 
AS         
BEGIN          
    
IF @NQUERYID=1       
   GOTO LBLNAVIGATE     
ELSE IF @NQUERYID=2      
   GOTO LBLMASTER             
ELSE IF @NQUERYID=3 
   GOTO LBLSCCDETAIL  
ELSE     
 GOTO LAST    
               
LBLNAVIGATE:  -- CREATING LOOK UP TABLE   

	DECLARE @CCMD NVARCHAR(MAX)
	SET @CCMD = ''
	PRINT @CWHERE
	PRINT CONVERT(VARCHAR,@CWHERE)
	SET @CCMD =N'EXEC SP_NAVIGATE ''PRD_COMPONENT_MST'','+
			CONVERT(VARCHAR,@NNAVMODE)+', '''+
			CONVERT(VARCHAR,@CMEMO)+''','''+
			CONVERT(VARCHAR,@CFINYEAR)+''',''MEMO_NO'',''MEMO_DT'',''MEMO_ID'','''+
			@CWHERE+'''' 
	PRINT @CCMD
	EXECUTE SP_EXECUTESQL @CCMD
	GOTO LAST                          
	                             
             
LBLMASTER:    

	SELECT A.*,S.SECTION_CODE,S.SECTION_NAME,SU.SUB_SECTION_CODE, SU.SUB_SECTION_NAME 
	      ,U.USER_CODE
	FROM PRD_COMPONENT_MST A (NOLOCK)   
	JOIN DBO.SECTIOND SU WITH(NOLOCK) ON A.SUB_SECTION_CODE=SU.SUB_SECTION_CODE
	JOIN DBO.SECTIONM S WITH(NOLOCK) ON SU.SECTION_CODE=S.SECTION_CODE 
	JOIN DBO.USERS U WITH(NOLOCK) ON A.USERNAME=U.USERNAME
	WHERE A.MEMO_ID= @CMEMO 
	    
	GOTO LAST;
                
LBLSCCDETAIL:      
            
	SELECT * FROM PRD_COMPONENT_DET A (NOLOCK)        
	WHERE A.MEMO_ID= @CMEMO                               
	ORDER BY A.SRNO          
	GOTO LAST;     
       
LAST:
            
END
