CREATE PROCEDURE SP_MERGE_MIRROR_MSTPRM
 (
   @NMODE INT
  ,@XN_TYPE VARCHAR(50) ='MSTPRM'
 )
--WITH ENCRYPTION
AS
BEGIN
       DECLARE @CSTEP VARCHAR(100),@DTSQL NVARCHAR(MAX),@NMERGE_ORDER NUMERIC(5)
              ,@CTEMPLOCTABLE VARCHAR(100),@CSTATECODEOUT CHAR(7),@CSTATECODE VARCHAR(10)
              ,@CCURDEPTID VARCHAR(10),@CHODEPTID VARCHAR(10),@BHOLOC BIT,@NLOCTYPE VARCHAR(50)
              ,@BPURLOC VARCHAR(10),@CTABLENAME VARCHAR(100),@CTMP_TABLENAME VARCHAR(100)
              ,@CKEYFIELD1 VARCHAR(100),@CTEMPLOCSSTTABLE VARCHAR(500),@CTEMPTABLE VARCHAR(500)
              ,@CTEMPLOCSSTMSTTABLE VARCHAR(500),@BPROCEED BIT,@CKEYFIELD2 VARCHAR(500),@CKEYFIELD3 VARCHAR(500) 
	          ,@CSOURCETABLE VARCHAR(1000),@NXNSMERGINGORDER INT,@CSOURCEDB VARCHAR(200),
	          @CERRORMSG VARCHAR(MAX)	,@CCMD NVARCHAR(MAX)
	          
      DECLARE @TXNSMERGEINFO TABLE (ORG_TABLENAME VARCHAR(50),TMP_TABLENAME VARCHAR(50),XN_ID VARCHAR(40))
       
BEGIN TRY

	  SELECT @CSOURCEDB=''	


      IF ISNULL(@NMODE,0) = 1
         GOTO END_PROC;

	  BEGIN TRANSACTION
      
      SET @CSTEP = 00  
  
	  SELECT @CCURDEPTID = VALUE FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION='LOCATION_ID'  
	  SELECT @CHODEPTID = VALUE FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION='HO_LOCATION_ID'  
	  
	  IF @CCURDEPTID=@CHODEPTID
	  BEGIN
			SET @CERRORMSG='P:SP_MERGE_MIRROR_MSTPRM, CANNOT CALL MERGING PROC AT HEAD OFFICE'
			GOTO END_PROC
  	  END					

	  SET @CSTEP = 05    
	    
	  SELECT @NLOCTYPE=LOC_TYPE,@BPURLOC=PUR_LOC FROM LOCATION WHERE DEPT_ID=@CCURDEPTID  
	       

	  SET @CSTEP = 10   

  	  DELETE FROM PARTY_RATE_DET
	  DELETE FROM PARTY_RATE_MST
	  DELETE FROM PARTY_RATE_LOC
	  
	   SET @CKEYFIELD2 =''
	   SET @CKEYFIELD3 =''


	   SET @CSTEP = 12   	
	   SET @CTABLENAME ='HD01106'
	   --SET @CKEYFIELD1='ROW_ID'
	   SET @CKEYFIELD1='HEAD_CODE'
	   SET @CSOURCETABLE='MSTPRM_HD01106_MIRROR'
	   SET @CTEMPTABLE=@CSOURCEDB+@CSOURCETABLE
	   PRINT 'MERGE MASTER :'+@CTABLENAME+'  '+@CSOURCETABLE
	   
	   EXEC UPDATEMASTERXN
	   @CSOURCEDB=@CSOURCEDB,
	   @CSOURCETABLE=@CSOURCETABLE,
	   @CDESTDB='',
	   @CDESTTABLE=@CTABLENAME,
	   @CKEYFIELD1=@CKEYFIELD1,
	   @CKEYFIELD2=@CKEYFIELD2,
	   @CKEYFIELD3=@CKEYFIELD3,
	   @LINSERTONLY=0,
	   @CFILTERCONDITION='',
	   @LUPDATEONLY=0,
	   @BALWAYSUPDATE=1
	   
	   
	   set @CSTEP=13
		UPDATE A SET MAJOR_AC_CODE=A.AC_CODE  
		FROM MSTPRM_LM01106_MIRROR A
		left join lm01106 b on a.major_ac_code=b.ac_code
		LEFT JOIN MSTPRM_LM01106_MIRROR c on c.ac_code=a.major_ac_code
		where b.AC_CODE IS NULL AND c.AC_CODE IS NULL


	   SET @CSTEP = 15   
	   SET @CTABLENAME ='LM01106'
	   --SET @CKEYFIELD1='ROW_ID'
	   SET @CKEYFIELD1='AC_CODE'
	   SET @CSOURCETABLE='MSTPRM_LM01106_MIRROR'
	   SET @CTEMPTABLE=@CSOURCEDB+@CSOURCETABLE

	   SET @CSTEP = 16  


	   PRINT 'MERGE MASTER :'+@CTABLENAME+'  '+@CSOURCETABLE
	   
	   EXEC UPDATEMASTERXN
	   @CSOURCEDB=@CSOURCEDB,
	   @CSOURCETABLE=@CSOURCETABLE,
	   @CDESTDB='',
	   @CDESTTABLE=@CTABLENAME,
	   @CKEYFIELD1=@CKEYFIELD1,
	   @CKEYFIELD2=@CKEYFIELD2,
	   @CKEYFIELD3=@CKEYFIELD3,
	   @LINSERTONLY=0,
	   @CFILTERCONDITION='',
	   @LUPDATEONLY=0,
	   @BALWAYSUPDATE=1
		
	  
	  --SET @DTSQL =N'UPDATE '+@TEMP_TABLE+' WITH (ROWLOCK)  SET EDT_USER_CODE=''0000000'', USER_CODE =''0000000'''
	--EXEC SP_EXECUTESQL @DTSQL
	
	   UPDATE MSTPRM_PARTY_RATE_MST_MIRROR WITH (ROWLOCK)  SET EDT_USER_CODE='0000000', USER_CODE ='0000000'

	   SET @CSTEP = 20   
	   SET @CTABLENAME ='PARTY_RATE_MST'
	   --SET @CKEYFIELD1='ROW_ID'
	   SET @CKEYFIELD1='MEMO_ID'
	   SET @CSOURCETABLE='MSTPRM_PARTY_RATE_MST_MIRROR'
	   SET @CTEMPTABLE=@CSOURCEDB+@CSOURCETABLE
	   PRINT 'MERGE MASTER :'+@CTABLENAME+'  '+@CSOURCETABLE
	   
	   EXEC UPDATEMASTERXN
	   @CSOURCEDB=@CSOURCEDB,
	   @CSOURCETABLE=@CSOURCETABLE,
	   @CDESTDB='',
	   @CDESTTABLE=@CTABLENAME,
	   @CKEYFIELD1=@CKEYFIELD1,
	   @CKEYFIELD2=@CKEYFIELD2,
	   @CKEYFIELD3=@CKEYFIELD3,
	   @LINSERTONLY=0,
	   @CFILTERCONDITION='',
	   @LUPDATEONLY=0,
	   @BALWAYSUPDATE=1
	   
	   SET @CSTEP = 30   
	   SET @CTABLENAME ='PARTY_RATE_DET'
	   SET @CKEYFIELD1='MEMO_ID'
	   SET @CSOURCETABLE='MSTPRM_PARTY_RATE_DET_MIRROR'
	   SET @CTEMPTABLE=@CSOURCEDB+@CSOURCETABLE
	   PRINT 'MERGE MASTER :'+@CTABLENAME+'  '+@CSOURCETABLE
	   
	   EXEC UPDATEMASTERXN
	   @CSOURCEDB=@CSOURCEDB,
	   @CSOURCETABLE=@CSOURCETABLE,
	   @CDESTDB='',
	   @CDESTTABLE=@CTABLENAME,
	   @CKEYFIELD1=@CKEYFIELD1,
	   @CKEYFIELD2=@CKEYFIELD2,
	   @CKEYFIELD3=@CKEYFIELD3,
	   @LINSERTONLY=0,
	   @CFILTERCONDITION='',
	   @LUPDATEONLY=0,
	   @BALWAYSUPDATE=1
		
--

	 
	   
	    SET @CSTEP = 45   	
	   SET @CTABLENAME ='LMP01106'
	   SET @CKEYFIELD1='AC_CODE'
	   SET @CSOURCETABLE='MSTPRM_LMP01106_MIRROR'
	   SET @CTEMPTABLE=@CSOURCEDB+@CSOURCETABLE
	   PRINT 'MERGE MASTER :'+@CTABLENAME+'  '+@CSOURCETABLE
	   
	   SET @CCMD=N'UPDATE A SET  AC_CODE=ISNULL(C.AC_CODE,''0000000000''),
	                             AREA_CODE = ISNULL(B.AREA_CODE,''0000000'')
	                             FROM '+@CSOURCETABLE+' A
	                             LEFT JOIN AREA B ON A.AREA_CODE=B.AREA_CODE
	                             LEFT JOIN LM01106 C ON C.AC_CODE=A.AC_CODE'
	   EXEC SP_EXECUTESQL @CCMD                          
	   
	   
	   EXEC UPDATEMASTERXN
	   @CSOURCEDB=@CSOURCEDB,
	   @CSOURCETABLE=@CSOURCETABLE,
	   @CDESTDB='',
	   @CDESTTABLE=@CTABLENAME,
	   @CKEYFIELD1=@CKEYFIELD1,
	   @CKEYFIELD2=@CKEYFIELD2,
	   @CKEYFIELD3=@CKEYFIELD3,
	   @LINSERTONLY=0,
	   @CFILTERCONDITION='',
	   @LUPDATEONLY=1,
	   @BALWAYSUPDATE=1 
	   
	   SET @CSTEP = 50   	
	   SET @CTABLENAME ='LOC_BILLING_RULES'
	   --SET @CKEYFIELD1='ROW_ID'
	   SET @CKEYFIELD1='PARTY_RATE_MEMO_ID'
	   SET @CSOURCETABLE='MSTPRM_LOC_BILLING_RULES_MIRROR'
	   SET @CTEMPTABLE=@CSOURCEDB+@CSOURCETABLE
	   PRINT 'MERGE MASTER :'+@CTABLENAME+'  '+@CSOURCETABLE
	   
	   EXEC UPDATEMASTERXN
	   @CSOURCEDB=@CSOURCEDB,
	   @CSOURCETABLE=@CSOURCETABLE,
	   @CDESTDB='',
	   @CDESTTABLE=@CTABLENAME,
	   @CKEYFIELD1='SOURCE_DEPT_ID',
	   @CKEYFIELD2='TARGET_DEPT_ID',
	   @CKEYFIELD3=@CKEYFIELD3,
	   @LINSERTONLY=0,
	   @CFILTERCONDITION='',
	   @LUPDATEONLY=1,
	   @BALWAYSUPDATE=1
	     
    GOTO END_PROC
END TRY

BEGIN CATCH
	SET @CERRORMSG='P:SP_MERGE_MIRROR_MSTPRM, STEP:'+@CSTEP+', MESSAGE:'+ERROR_MESSAGE()
	GOTO END_PROC
END CATCH

END_PROC:
	
	IF @@TRANCOUNT>0
	BEGIN
		IF ISNULL(@CERRORMSG,'')='' 
			COMMIT
		ELSE
			ROLLBACK	
	END
	
	IF ISNULL(@CERRORMSG,'')='' 
	BEGIN   
	
	   DELETE FROM MSTPRM_HD01106_MIRROR
	   DELETE FROM MSTPRM_LM01106_MIRROR
	   DELETE FROM MSTPRM_LMP01106_MIRROR

	   DELETE FROM MSTPRM_PARTY_RATE_MST_MIRROR
	   DELETE FROM MSTPRM_PARTY_RATE_DET_MIRROR
	   DELETE FROM MSTPRM_LOC_BILLING_RULES_MIRROR
	END
		
	SELECT 'MSTPRM' AS MEMO_ID,@CERRORMSG AS ERRMSG   	  
END
----- END OF PROCEDURE SP_MERGE_MIRROR_MSTPRM
