CREATE PROCEDURE SP3S_REMOVE_MIRROR_DULICATE_MSTERS
(
 @CMEMOID VARCHAR(40)='',
 @NVERSIONNO INT,
 @CXN_TYPE VARCHAR(10)
)
AS
BEGIN
    
	RETURN
	DECLARE @DTSQL NVARCHAR(MAX),@CTEMPTABLENAME VARCHAR(100),
	@CTABLENAME VARCHAR(100),@CKEYFIELDNAME VARCHAR(30)

	IF @CXN_TYPE='PUR'
	   SET @CKEYFIELDNAME=' A.PUR_MEMO_ID'
    ELSE IF @CXN_TYPE='DOCWSL'
	   SET @CKEYFIELDNAME=' A.DOCWSL_MEMO_ID'
	ELSE IF @CXN_TYPE='DOCPRT'
	   SET @CKEYFIELDNAME=' A.DOCPRT_MEMO_ID'
	ELSE IF @CXN_TYPE='DOCIRT'
	   SET @CKEYFIELDNAME=' A.DOCIRT_MEMO_ID'

    
	
	--PRINT '1. UPDATE DUPLICATE SECTION MASTER '

	if @CXN_TYPE='docwsl'
	begin
		SET @CTABLENAME='LM01106'
		SET @CTEMPTABLENAME=@CXN_TYPE+'_'+@CTABLENAME+'_MIRROR'
     
	  SET @DTSQL=N' UPDATE b SET AC_NAME =b.AC_NAME+''_''+b.AC_CODE 
		FROM '+@CTEMPTABLENAME+' A (NOLOCK)
		JOIN LM01106 B (NOLOCK) ON A.AC_NAME =B.AC_NAME 
		WHERE A.AC_CODE <>B.AC_CODE 
		AND '+@CKEYFIELDNAME+' ='''+@CMEMOID+'''
		 '

		EXEC SP_EXECUTESQL @DTSQL


	
	end

	PRINT '1. UPDATE DUPLICATE SECTION MASTER '
	SET @CTABLENAME='SECTIONM'
	SET @CTEMPTABLENAME=@CXN_TYPE+'_'+@CTABLENAME+'_MIRROR'

 
 SET @DTSQL=N' UPDATE b SET SECTION_NAME =b.SECTION_NAME+''_''+b.SECTION_CODE 
	FROM '+@CTEMPTABLENAME+' A (NOLOCK)
	JOIN SECTIONM B (NOLOCK) ON A.SECTION_NAME =B.SECTION_NAME 
	WHERE A.SECTION_CODE <>B.SECTION_CODE 
	AND  LEFT(A.SECTION_CODE,2) =LEFT(B.SECTION_CODE ,2)
	AND '+@CKEYFIELDNAME+' ='''+@CMEMOID+'''
	 '

	EXEC SP_EXECUTESQL @DTSQL

 


	PRINT '2. UPDATE DUPLICATE SUB SECTION MASTER '


	SET @CTABLENAME='SECTIOND'
	SET @CTEMPTABLENAME=@CXN_TYPE+'_'+@CTABLENAME+'_MIRROR'

	
 SET @DTSQL=N' UPDATE b SET SUB_SECTION_NAME =b.SUB_SECTION_NAME+''_''+b.SUB_SECTION_CODE
	FROM '+@CTEMPTABLENAME+' A (NOLOCK)
	JOIN SECTIOND B (NOLOCK) ON A.SUB_SECTION_NAME =B.SUB_SECTION_NAME AND A.section_code=B.section_code
	WHERE A.SUB_SECTION_CODE <>B.SUB_SECTION_CODE 
	AND LEFT(A.SUB_SECTION_CODE,2) =LEFT(B.SUB_SECTION_CODE ,2)
	AND '+@CKEYFIELDNAME+' ='''+@CMEMOID+'''
	 '

	EXEC SP_EXECUTESQL @DTSQL


	SET @CTABLENAME='ARTICLE'
	SET @CTEMPTABLENAME=@CXN_TYPE+'_'+@CTABLENAME+'_MIRROR'

 SET @DTSQL=N' UPDATE b SET ARTICLE_NO =b.ARTICLE_NO+''_''+b.ARTICLE_CODE
	FROM '+@CTEMPTABLENAME+' A (NOLOCK)
	JOIN ARTICLE B (NOLOCK) ON A.ARTICLE_NO =B.ARTICLE_NO 
	WHERE A.ARTICLE_CODE <>B.ARTICLE_CODE 
	AND LEFT(A.ARTICLE_CODE,2) =LEFT(B.ARTICLE_CODE,2)
	AND '+@CKEYFIELDNAME+' ='''+@CMEMOID+'''
	 '

	EXEC SP_EXECUTESQL @DTSQL




	

	SET @CTABLENAME='PARA1'
	SET @CTEMPTABLENAME=@CXN_TYPE+'_'+@CTABLENAME+'_MIRROR'

SET @DTSQL=N' UPDATE b SET PARA1_NAME =b.PARA1_NAME+''_''+b.PARA1_CODE
	FROM '+@CTEMPTABLENAME+' A (NOLOCK)
	JOIN PARA1 B (NOLOCK) ON A.PARA1_NAME =B.PARA1_NAME 
	WHERE A.PARA1_CODE <>B.PARA1_CODE 
	AND LEFT(A.PARA1_CODE,2)=LEFT(B.PARA1_CODE,2)
	AND '+@CKEYFIELDNAME+' ='''+@CMEMOID+''' 
	 '

	EXEC SP_EXECUTESQL @DTSQL

 
	SET @CTABLENAME='PARA2'
	SET @CTEMPTABLENAME=@CXN_TYPE+'_'+@CTABLENAME+'_MIRROR'

SET @DTSQL=N' UPDATE b SET PARA2_NAME =b.PARA2_NAME+''_''+b.PARA2_CODE
	FROM '+@CTEMPTABLENAME+' A (NOLOCK)
	JOIN PARA2 B (NOLOCK) ON A.PARA2_NAME =B.PARA2_NAME 
	WHERE A.PARA2_CODE <>B.PARA2_CODE 
	AND LEFT(A.PARA2_CODE,2)=LEFT(B.PARA2_CODE,2)
	AND '+@CKEYFIELDNAME+' ='''+@CMEMOID+'''
	 '

	EXEC SP_EXECUTESQL @DTSQL


	SET @CTABLENAME='PARA3'
	SET @CTEMPTABLENAME=@CXN_TYPE+'_'+@CTABLENAME+'_MIRROR'

 SET @DTSQL=N' UPDATE b SET PARA3_NAME =b.PARA3_NAME+''_''+b.PARA3_CODE
	FROM '+@CTEMPTABLENAME+' A (NOLOCK)
	JOIN PARA3 B (NOLOCK) ON A.PARA3_NAME =B.PARA3_NAME 
	WHERE A.PARA3_CODE <>B.PARA3_CODE 
	AND LEFT(A.PARA3_CODE,2)=LEFT(B.PARA3_CODE,2)
	AND '+@CKEYFIELDNAME+' ='''+@CMEMOID+'''
	'

	EXEC SP_EXECUTESQL @DTSQL



	SET @CTABLENAME='PARA4'
	SET @CTEMPTABLENAME=@CXN_TYPE+'_'+@CTABLENAME+'_MIRROR'

 SET @DTSQL=N' UPDATE b SET PARA4_NAME =b.PARA4_NAME+''_''+b.PARA4_CODE
	FROM '+@CTEMPTABLENAME+' A (NOLOCK)
	JOIN PARA4 B (NOLOCK) ON A.PARA4_NAME =B.PARA4_NAME 
	WHERE A.PARA4_CODE <>B.PARA4_CODE 
	AND LEFT(A.PARA4_CODE,2)=LEFT(B.PARA4_CODE,2)
	AND '+@CKEYFIELDNAME+' ='''+@CMEMOID+'''
	 '

	EXEC SP_EXECUTESQL @DTSQL



	SET @CTABLENAME='PARA5'
	SET @CTEMPTABLENAME=@CXN_TYPE+'_'+@CTABLENAME+'_MIRROR'

SET @DTSQL=N' UPDATE b SET PARA5_NAME =b.PARA5_NAME+''_''+b.PARA5_CODE 
	FROM '+@CTEMPTABLENAME+' A (NOLOCK)
	JOIN PARA5 B (NOLOCK) ON A.PARA5_NAME =B.PARA5_NAME 
	WHERE A.PARA5_CODE <>B.PARA5_CODE 
	AND LEFT(A.PARA5_CODE,2)=LEFT(B.PARA5_CODE,2)
	AND '+@CKEYFIELDNAME+' ='''+@CMEMOID+'''
	'

	EXEC SP_EXECUTESQL @DTSQL




	SET @CTABLENAME='PARA6'
	SET @CTEMPTABLENAME=@CXN_TYPE+'_'+@CTABLENAME+'_MIRROR'

SET @DTSQL=N' UPDATE b SET PARA6_NAME =b.PARA6_NAME+''_''+b.PARA6_CODE
	FROM '+@CTEMPTABLENAME+' A (NOLOCK)
	JOIN PARA6 B (NOLOCK) ON A.PARA6_NAME =B.PARA6_NAME 
	WHERE A.PARA6_CODE <>B.PARA6_CODE 
	AND LEFT(A.PARA6_CODE,2)=LEFT(B.PARA6_CODE,2)
	AND '+@CKEYFIELDNAME+' ='''+@CMEMOID+''' 
	 '

	EXEC SP_EXECUTESQL @DTSQL





END