CREATE PROCEDURE SP_SEND_MIRROR_DOCWBO_OPT_DATA_NEW --(LocId 3 digit change by Sanjay:30-10-2024)
	 @CREQXNID VARCHAR(50)
	,@CTARGETLOCID VARCHAR(5)
	,@CREQCHALLANNO VARCHAR(20)=''
	,@CREQCHALLANFINYEAR VARCHAR(20)=''
	,@BACKNOWLEDGE BIT=0
	,@CERRMSG VARCHAR(1000) OUTPUT
AS
/*

	SP_SEND_MIRROR_DOCWBO_OPT_DATA_NEW : THIS PROCEDURE USE TO SEND DOCPO DATA
*/
BEGIN
	DECLARE @DTSQL NVARCHAR(MAX),@CTEMPTABLE VARCHAR(500),@CMEMOID VARCHAR(50),
	@CTEMPEMPLOYEETABLE VARCHAR(200),@DMEMOLASTUPDATE DATETIME,@CTABLENAME VARCHAR(100),
	@BRECFOUND BIT,@CSTEP VARCHAR(5),@CFILTERCONDITION VARCHAR(MAX),@CCUTOFFDATE VARCHAR(20),
	@CTEMPMASTERTABLE VARCHAR(200),@CTEMPDETAILTABLE VARCHAR(200),@CTEMPLMTABLE VARCHAR(200),
	@CTEMPLMPTABLE VARCHAR(200),@CTEMPAREATABLE VARCHAR(200),@CTEMPCITYTABLE VARCHAR(200),
	@CTEMPPMODEXNTABLE VARCHAR(200),@CTEMPPMODETABLE VARCHAR(200),@CSTNAPPROVAL BIT,
	@CCLOCID VARCHAR(10),@BSENDPURINFOLOC BIT,
	@CTEMPSKUTABLE VARCHAR(500),@CTEMPSKUOHTABLE VARCHAR(500),
	@NTARGETLOCTYPE INT,@BTARGETPURLOC BIT,@CTEMPSLSBCTABLE VARCHAR(500),@CTEMPSLSDETTABLE VARCHAR(500), 
	@BGETCHALLANTHRUMIRROR BIT,@CPARTYDEPTID VARCHAR(5),@NMODE INT,
	@BCOMPLETED BIT,@BEXPORTED BIT,@CDISPATCHDETAILS VARCHAR(500),@CDONOTSENDCHALLANWODISPATCHDETAILS VARCHAR(2),
	@CJOINSTR VARCHAR(1000),@BTEMPDATADELETED BIT,@NSPID INT,@BDONOTSENDCHALLANWITHOUTDISPATCH BIT
	
	SET @NSPID = @@SPID
	
LBLSTART:
	
	PRINT 'ENTER SP_SEND_MIRROR_DOCPO_OPT_DATA_NEW'
	 	
	DECLARE @TXNSSENDINFO TABLE (ORG_TABLENAME VARCHAR(500),TMP_TABLENAME VARCHAR(500),XN_ID VARCHAR(40))  
	


BEGIN TRY 	
			
	SET @CSTEP=10	
	SET @CFILTERCONDITION=''
	
	
	IF @BACKNOWLEDGE=1
		GOTO LBLTABLEINFO
 
LBLTABLEINFO:
	
	SET @CMEMOID = @CREQXNID

	IF @BACKNOWLEDGE=1
		GOTO END_PROC
		
	SET @CSTEP=50
	---- POPULATE LIST OF TABLES 
		
	PRINT 'SEND CHALLAN DIRECTLY OPT-2'
	
	SET @CFILTERCONDITION=' B.ORDER_ID='''+@CMEMOID+''''
	
	---- SEND THE PURCHASE ORDER MEMO MASTER TABLE
	
	SELECT 	@CMEMOID AS XN_ID,'DOCWBO_BUYER_ORDER_MST_MIRROR' AS TARGET_TABLENAME,* FROM BUYER_ORDER_MST (NOLOCK) WHERE ORDER_ID=@CMEMOID
	
	SELECT 	'DOCWBO_BUYER_ORDER_DET_MIRROR' AS TARGET_TABLENAME,* FROM BUYER_ORDER_DET (NOLOCK) WHERE ORDER_ID=@CMEMOID		
	
	--SELECT 	DISTINCT 'DOCPO_SKU_MIRROR' AS TARGET_TABLENAME,@CMEMOID AS DOCWBO_MEMO_ID,A.* FROM SKU A (NOLOCK)
	--JOIN BUYER_ORDER_DET B (NOLOCK) ON A.PRODUCT_CODE=B.PRODUCT_CODE WHERE ORDER_ID=@CMEMOID					

	
			
	SELECT 	DISTINCT 'DOCWBO_LM01106_MIRROR' AS TARGET_TABLENAME,@CMEMOID AS DOCWBO_MEMO_ID,A.* FROM LM01106 A (NOLOCK)
	JOIN BUYER_ORDER_MST C (NOLOCK) ON C.AC_CODE=A.AC_CODE
	WHERE ORDER_ID=@CMEMOID
	
	
	SELECT 	DISTINCT 'DOCWBO_LMP01106_MIRROR' AS TARGET_TABLENAME,@CMEMOID AS DOCWBO_MEMO_ID,A.* FROM LMP01106 A (NOLOCK)
	JOIN BUYER_ORDER_MST C (NOLOCK) ON C.AC_CODE=A.AC_CODE
	WHERE ORDER_ID=@CMEMOID						
				
	
	SELECT 	DISTINCT 'DOCWBO_HD01106_MIRROR' AS TARGET_TABLENAME,@CMEMOID AS DOCWBO_MEMO_ID,A.* FROM HD01106 A (NOLOCK)
	JOIN LM01106 B (NOLOCK) ON A.HEAD_CODE=B.HEAD_CODE
	JOIN BUYER_ORDER_MST D (NOLOCK) ON D.AC_CODE=B.AC_CODE
	WHERE ORDER_ID=@CMEMOID					
	
		
	SELECT 	DISTINCT 'DOCWBO_ARTICLE_MIRROR' AS TARGET_TABLENAME,@CMEMOID AS DOCWBO_MEMO_ID,A.* FROM ARTICLE A (NOLOCK)
	JOIN BUYER_ORDER_DET C (NOLOCK) ON C.ARTICLE_CODE=A.ARTICLE_CODE
	WHERE ORDER_ID=@CMEMOID
	
	
	SELECT 	DISTINCT 'DOCWBO_UOM_MIRROR' AS TARGET_TABLENAME,@CMEMOID AS DOCWBO_MEMO_ID,U.* 
	FROM UOM U(NOLOCK) 
	JOIN ARTICLE A (NOLOCK) ON A.UOM_CODE=U.UOM_CODE
	JOIN BUYER_ORDER_DET C (NOLOCK) ON C.ARTICLE_CODE=A.ARTICLE_CODE
	WHERE ORDER_ID=@CMEMOID
	
	

	SELECT 	DISTINCT 'DOCWBO_SECTIOND_MIRROR' AS TARGET_TABLENAME,@CMEMOID AS DOCWBO_MEMO_ID,A.* FROM SECTIOND A (NOLOCK)
	JOIN ARTICLE B (NOLOCK) ON B.SUB_SECTION_CODE=A.SUB_SECTION_CODE
	JOIN BUYER_ORDER_DET D (NOLOCK) ON D.ARTICLE_CODE=B.ARTICLE_CODE
	WHERE ORDER_ID=@CMEMOID
	UNION
	SELECT 	DISTINCT 'DOCWBO_SECTIOND_MIRROR' AS TARGET_TABLENAME,@CMEMOID AS DOCWBO_MEMO_ID,A.* FROM SECTIOND A (NOLOCK)
	JOIN BUYER_ORDER_DET D (NOLOCK) ON A.sub_section_code=D.sub_section_code
	WHERE ORDER_ID=@CMEMOID

	
	SELECT 	DISTINCT 'DOCWBO_SECTIONM_MIRROR' AS TARGET_TABLENAME,@CMEMOID AS DOCWBO_MEMO_ID,A.* FROM SECTIONM A (NOLOCK)
	JOIN SECTIOND B (NOLOCK) ON B.SECTION_CODE=A.SECTION_CODE
	JOIN ARTICLE C (NOLOCK) ON C.SUB_SECTION_CODE=B.SUB_SECTION_CODE
	JOIN BUYER_ORDER_DET E (NOLOCK) ON E.ARTICLE_CODE=C.ARTICLE_CODE
	WHERE ORDER_ID=@CMEMOID
	UNION
	SELECT 	DISTINCT 'DOCWBO_SECTIONM_MIRROR' AS TARGET_TABLENAME,@CMEMOID AS DOCWBO_MEMO_ID,A.* FROM SECTIONM A (NOLOCK)
	JOIN BUYER_ORDER_DET E (NOLOCK) ON A.SECTION_CODE=E.SECTION_CODE
	WHERE ORDER_ID=@CMEMOID

	SELECT 	DISTINCT 'DOCWBO_PARA1_MIRROR' AS TARGET_TABLENAME,@CMEMOID AS DOCWBO_MEMO_ID,A.* FROM PARA1 A (NOLOCK)
	JOIN BUYER_ORDER_DET C (NOLOCK) ON C.PARA1_CODE=A.PARA1_CODE
	WHERE ORDER_ID=@CMEMOID

	SELECT 	DISTINCT 'DOCWBO_PARA2_MIRROR' AS TARGET_TABLENAME,@CMEMOID AS DOCWBO_MEMO_ID,A.* FROM PARA2 A (NOLOCK)
	JOIN BUYER_ORDER_DET C (NOLOCK) ON C.PARA2_CODE=A.PARA2_CODE
	WHERE ORDER_ID=@CMEMOID

	SELECT 	DISTINCT 'DOCWBO_PARA3_MIRROR' AS TARGET_TABLENAME,@CMEMOID AS DOCWBO_MEMO_ID,A.* FROM PARA3 A (NOLOCK)
	JOIN BUYER_ORDER_DET C (NOLOCK) ON C.PARA3_CODE=A.PARA3_CODE
	WHERE ORDER_ID=@CMEMOID
	
	
	SELECT 	DISTINCT 'DOCWBO_PARA4_MIRROR' AS TARGET_TABLENAME,@CMEMOID AS DOCWBO_MEMO_ID,A.* FROM para4 A (NOLOCK)
	JOIN BUYER_ORDER_DET C (NOLOCK) ON C.PARA4_CODE=A.PARA4_CODE
	WHERE ORDER_ID=@CMEMOID
	
	
	SELECT 	DISTINCT 'DOCWBO_PARA5_MIRROR' AS TARGET_TABLENAME,@CMEMOID AS DOCWBO_MEMO_ID,A.* FROM para5 A (NOLOCK)
	JOIN BUYER_ORDER_DET C (NOLOCK) ON C.PARA5_CODE=A.PARA5_CODE
	WHERE ORDER_ID=@CMEMOID
	
	SELECT 	DISTINCT 'DOCWBO_PARA6_MIRROR' AS TARGET_TABLENAME,@CMEMOID AS DOCWBO_MEMO_ID,A.* FROM para6 A (NOLOCK)
	JOIN BUYER_ORDER_DET C (NOLOCK) ON C.PARA6_CODE=A.PARA6_CODE
	WHERE ORDER_ID=@CMEMOID
	
	SELECT 	DISTINCT 'DOCWBO_PARA7_MIRROR' AS TARGET_TABLENAME,@CMEMOID AS DOCWBO_MEMO_ID,A.* FROM PARA7 A (NOLOCK)
	JOIN BUYER_ORDER_DET C (NOLOCK) ON C.para7_code=A.para7_code
	WHERE ORDER_ID=@CMEMOID and isnull(c.para7_code,'')<>''
	
	
	SELECT  DISTINCT 'DOCWBO_ARTICLE_FIX_ATTR_MIRROR' AS TARGET_TABLENAME,@CMEMOID AS DOCBO_MEMO_ID,A.* FROM ARTICLE_FIX_ATTR A (NOLOCK)  
	 JOIN BUYER_ORDER_DET D (NOLOCK) ON D.ARTICLE_CODE =A.ARTICLE_CODE  
	 WHERE ORDER_ID =@CMEMOID  
   
	
	 DECLARE @NCOUNT INT,@BLOOP INT,@CCMD NVARCHAR(MAX)  
	 SET @NCOUNT=25  
	 SET @BLOOP=1  
	 WHILE (@BLOOP <=@NCOUNT )  
	 BEGIN  
   

	   SET @CCMD=N'  
		SELECT  DISTINCT ''DOCWBO_ATTR'+RTRIM(LTRIM(RTRIM(LTRIM(STR(@BLOOP)))))+'_MST_MIRROR'' AS TARGET_TABLENAME,'''+@CMEMOID+''' AS DOCWBO_MEMO_ID,ATTR'+RTRIM(LTRIM(STR(@BLOOP)))+'_MST.*   
		FROM ATTR'+RTRIM(LTRIM(STR(@BLOOP)))+'_MST(NOLOCK)  
		JOIN ARTICLE_FIX_ATTR A (NOLOCK) ON ATTR'+RTRIM(LTRIM(STR(@BLOOP)))+'_MST.attr'+RTRIM(LTRIM(STR(@BLOOP)))+'_key_code=A.attr'+RTRIM(LTRIM(STR(@BLOOP)))+'_key_code  
		JOIN BUYER_ORDER_DET D (NOLOCK) ON D.ARTICLE_CODE=A.ARTICLE_CODE  
		WHERE ORDER_ID='''+@CMEMOID+'''  
		and  ATTR'+RTRIM(LTRIM(STR(@BLOOP)))+'_MST.attr'+RTRIM(LTRIM(RTRIM(LTRIM(STR(@BLOOP)))))+'_key_code <> ''0000000''  
		SELECT  DISTINCT ''DOCWBO_ATTR'+RTRIM(LTRIM(RTRIM(LTRIM(STR(@BLOOP)))))+'_MST_MIRROR'' AS TARGET_TABLENAME,'''+@CMEMOID+''' AS DOCWBO_MEMO_ID,ATTR'+RTRIM(LTRIM(STR(@BLOOP)))+'_MST.*   
		FROM ATTR'+RTRIM(LTRIM(STR(@BLOOP)))+'_MST(NOLOCK)  
		JOIN BUYER_ORDER_DET A (NOLOCK) ON ATTR'+RTRIM(LTRIM(STR(@BLOOP)))+'_MST.attr'+RTRIM(LTRIM(RTRIM(LTRIM(STR(@BLOOP)))))+'_key_code=A.attr'+RTRIM(LTRIM(STR(@BLOOP)))+'_key_code  
		WHERE ORDER_ID='''+@CMEMOID+'''  
		and  ATTR'+RTRIM(LTRIM(STR(@BLOOP)))+'_MST.attr'+RTRIM(LTRIM(RTRIM(LTRIM(STR(@BLOOP)))))+'_key_code <> ''0000000'' 
		 '  
      
		 PRINT  @CCMD  
		 EXEC SP_EXECUTESQL @CCMD  
          
		 SET @BLOOP=@BLOOP +1  
     
	 END  

	SELECT 	DISTINCT 'DOCWBO_PAYMODE_MST_MIRROR' AS TARGET_TABLENAME,@CMEMOID AS DOCWBO_MEMO_ID,A.* FROM paymode_mst  A (NOLOCK)
	JOIN BUYER_ORDER_MST C (NOLOCK) ON a.paymode_name=c.Tendermode
	WHERE ORDER_ID=@CMEMOID and c.MODE =3 and isnull(c.Tendermode,'')<>''

	

	SELECT 	DISTINCT 'DOCWBO_SalesOrderProcessing_MIRROR' AS TARGET_TABLENAME,@CMEMOID AS DOCWBO_MEMO_ID,A.* FROM SalesOrderProcessing  A (NOLOCK)
	WHERE RefMemoId=@CMEMOID  and XnType ='order'

	
	GOTO END_PROC
	
END TRY
BEGIN CATCH
	SET @CERRMSG='P: SP_SEND_MIRROR_DOCWBO_OPT_DATA_NEW, STEP:'+@CSTEP+', MESSAGE:'+ERROR_MESSAGE()
	GOTO END_PROC
END CATCH 		

END_PROC:
		
END
---END OF PROCEDURE - SP_SEND_MIRROR_DOCWBO_OPT_DATA_NEW

