CREATE PROC SP_PREPAYANALYSIS            
(          
	@CDEPTID CHAR(7) = '',          
	@NMONTH VARCHAR(3),          
	@NYEAR VARCHAR(5)          
)      
--WITH ENCRYPTION    
AS          
BEGIN          
	DECLARE @CQUERY NVARCHAR(MAX),          
			@CTEMP VARCHAR(100)          

	IF @CDEPTID = ''          
		SET @CTEMP = ''          
	ELSE          
		SET @CTEMP = 'AND EM.DEPARTMENT_ID = ''' + @CDEPTID + ''''          

	SET @CQUERY = N'SELECT  EM.EMP_ID,EM.REF_ID,          
							EM.EMP_TITLE' + ' + '' '' + ' + 'EM.EMP_FNAME' + ' + '' '' + ' + 'EM.EMP_LNAME AS EMPNAME,           
							EDEPT.DEPARTMENT_NAME,EDEPT.DEPARTMENT_ID,EM.WEEKLY_OFF1,EM.WEEKLY_OFF2,EM.PF_ENABLED,EM.ESI_ENABLED,          
							EM.BASIC_SALARY,ISNULL(L.TAKEN_LEAVES,0.00) AS TAKEN_LEAVE,          
							ISNULL((SELECT SUM(NO_OF_LEAVES) FROM EMP_LEAVE_MASTER)/12,0) AS TOTAL_LEAVE,          
							0.00 AS BALANCE_LEAVE,0.00 AS WORKING_DAYS,0.00 AS ATTENDANCE,          
							ISNULL(LM.APPROVEDAMT,0)  AS LOAN_AMOUNT,ISNULL(LM.EMIAMT,0) AS EMI_AMOUNT,        
							ISNULL(LM.TENURE,0) AS TENURE,0 AS PER_DAY_SALARY,0 AS TOT_BASIC_SALARY,0 AS EARNINGS,0 AS DEDUCTIONS,0 AS NET_SALARY          
					FROM EMP_MST EM           
					LEFT OUTER JOIN 
					(           
						SELECT A.EMP_ID, SUM(A.NO_OF_LEAVES)AS TAKEN_LEAVES            
						FROM EMP_LEAVE_DETAILS A (NOLOCK)               
						WHERE A.APPROVED=1 AND A.LEAVE_DR_CR=''DR'' AND MONTH(A.APPLICATION_DT)='''+@NMONTH+''' AND             
						YEAR(A.APPLICATION_DT) = ''' + @NYEAR + ''' GROUP BY A.EMP_ID           
					) L ON EM.EMP_ID=L.EMP_ID            
					LEFT OUTER JOIN 
					(
						SELECT B.EMP_ID,ISNULL(SUM(B.APPROVED_AMOUNT),0) AS APPROVEDAMT,ISNULL(SUM(B.EMI_AMOUNT),0) AS EMIAMT,ISNULL(SUM(B.TENURE),0) AS TENURE        
						FROM EMP_LOAN_MST B        
						WHERE B.APPROVED_AMOUNT>0 AND B.LOAN_STATUS=1 AND B.SETTLED=0 AND MONTH(B.LOAN_DATE)='''+@NMONTH+'''        
						GROUP BY B.EMP_ID
					)  LM ON EM.EMP_ID=LM.EMP_ID          
					INNER JOIN EMP_DEPARTMENT EDEPT ON EM.DEPARTMENT_ID=EDEPT.DEPARTMENT_ID           
					WHERE EM.EMP_ID<>''0000000'' AND EM.EMP_STATUS=0 ' + @CTEMP + '          
					GROUP BY EM.EMP_ID,EM.REF_ID,EM.EMP_TITLE,EM.EMP_FNAME,EM.EMP_LNAME,          
					EDEPT.DEPARTMENT_NAME,EDEPT.DEPARTMENT_ID,EM.BASIC_SALARY,L.TAKEN_LEAVES ,EM.EMP_STATUS,EM.WEEKLY_OFF1,EM.WEEKLY_OFF2,EM.PF_ENABLED,EM.ESI_ENABLED,LM.APPROVEDAMT,LM.EMIAMT,LM.TENURE'          

	IF @CQUERY <> ''          
	BEGIN          
		PRINT @CQUERY          
		EXEC SP_EXECUTESQL @CQUERY          
	END          
END
