CREATE PROCEDURE SP_GETPURHISTORY
@CARTICLECODE VARCHAR(9),
@CACCODE CHAR(10)=''	 
--WITH ENCRYPTION
AS
BEGIN
	DECLARE @CPRODUCTCODE VARCHAR(50),@CLASTROWID VARCHAR(40),@NLOOPCNT INT,@NCNT INT
	
	DECLARE @TPURHISTORY TABLE (AC_NAME VARCHAR(100),PURCHASE_PRICE NUMERIC(10,2),DISCOUNT_PERCENTAGE NUMERIC(6,2),
								LANDED_COST NUMERIC(10,2),BILL_NO VARCHAR(30),BILL_DT DATETIME,SRNO INT)
	
	
	IF @CARTICLECODE=''
	BEGIN
		SELECT * FROM @TPURHISTORY 
		RETURN 
	END	
	
	SET @NLOOPCNT=1
	
	SET @NCNT=(CASE WHEN @CACCODE='' THEN 5 ELSE 1 END)
	WHILE @NLOOPCNT<=@NCNT
	BEGIN
		SET @CPRODUCTCODE=''
		
		SELECT TOP 1 @CPRODUCTCODE=A.PRODUCT_CODE FROM SKU A
		JOIN LM01106 B ON A.AC_CODE=B.AC_CODE
		WHERE A.ARTICLE_CODE =@CARTICLECODE AND A.PURCHASE_PRICE<>0 
		AND ( @CACCODE='' OR A.AC_CODE=@CACCODE)
		AND AC_NAME+A.INV_NO+CONVERT(VARCHAR,A.INV_DT) NOT IN (SELECT AC_NAME+BILL_NO+CONVERT(VARCHAR,BILL_DT)
		FROM @TPURHISTORY)
		ORDER BY A.RECEIPT_DT DESC
		
		
		IF ISNULL(@CPRODUCTCODE,'')<>''
			INSERT @TPURHISTORY
			SELECT AC_NAME,C.PURCHASE_PRICE,C.DISCOUNT_AMOUNT/A.PURCHASE_PRICE AS DISCOUNT_PERCENTAGE,
			C.LANDED_COST,A.INV_NO,A.INV_DT,5-(@NLOOPCNT-1)
			FROM SKU A JOIN LM01106 B ON A.AC_CODE=B.AC_CODE
			JOIN VW_STOCKVALUE C ON C.PRODUCT_CODE=A.PRODUCT_CODE
		    WHERE A.PRODUCT_CODE=@CPRODUCTCODE
		ELSE
			BREAK
			    

		SET @NLOOPCNT=@NLOOPCNT+1	   
	END	   
	
	SELECT AC_NAME,PURCHASE_PRICE,DISCOUNT_PERCENTAGE,LANDED_COST,SRNO FROM @TPURHISTORY
END
