CREATE PROCEDURE SP_MBQ_DET_WH  
(   
  @CDTFROM VARCHAR(15),  
  @CDTTO VARCHAR(15),  
  @CWHERE VARCHAR(50) = '',  
  @CDEPTID VARCHAR(10) = '',  
  @INTMONTH INT = 0,  
  @INTYEAR INT = 0,
  @CARTICLE VARCHAR(50) = '',  
  @CPRODUCT VARCHAR(50) = '',
  @CSECTION VARCHAR(50) = '',
  @CSUBSECTION VARCHAR(50) = ''    
)  
AS  
BEGIN  
DECLARE @DTSQL NVARCHAR(MAX),@RFOPT VARCHAR(100),@CFILTER VARCHAR(MAX),@CADDJOINSTR VARCHAR(MAX)

SET @RFOPT=DB_NAME()+'_RFOPT.DBO.RF_OPT'

IF OBJECT_ID('TEMPDB..#SQ1','U') IS NOT NULL
	DROP TABLE #SQ1


SELECT PRODUCT_CODE,SUM(MBQ) AS MBQ,SUM(ISNULL(MST,0)) AS MST   
INTO #SQ1	 
FROM  MBQ_DET MST  (NOLOCK)    
WHERE MST.MONTH = @INTMONTH AND MST.YEAR =@INTYEAR
AND (@CDEPTID ='' OR MST.DEPT_ID =@CDEPTID)   
AND MST.DEPT_ID <> 'W1'   
GROUP BY PRODUCT_CODE    

IF OBJECT_ID('TEMPDB..#SQ2','U') IS NOT NULL
	DROP TABLE #SQ2
	
SELECT PRODUCT_CODE,SUM(MBQ) AS MBQ,SUM(ISNULL(MST,0)) AS MST    
INTO #SQ2 
FROM  MBQ_DET MST (NOLOCK)     
JOIN LOCATION LO (NOLOCK) ON LO.DEPT_ID = MST.DEPT_ID   
WHERE  MST.MONTH = @INTMONTH AND MST.YEAR =  @INTYEAR
AND LO.PUR_LOC=1 AND LO.DEPT_ID='W1'
GROUP BY PRODUCT_CODE    


SET @CFILTER='1=1'

SET @CFILTER=@CFILTER+(CASE WHEN @CDEPTID<>'' THEN ' AND LO.DEPT_ID ='''+@CDEPTID+'''' ELSE '' END)+ 
		(CASE WHEN @CSECTION<>'' THEN ' AND E.SECTION_CODE = '''+@CSECTION+'''' ELSE '' END)+ 
		(CASE WHEN @CSUBSECTION<>'' THEN ' AND E.SUB_SECTION_CODE = '''+@CSUBSECTION+'''' ELSE '' END)+ 
		(CASE WHEN @CARTICLE<>'' THEN ' AND D.ARTICLE_CODE = '''+@CARTICLE+'''' ELSE '' END)+ 
		(CASE WHEN @CPRODUCT<>'' THEN ' AND B.PRODUCT_CODE  = '''+@CPRODUCT+'''' ELSE '' END)

SELECT @CADDJOINSTR=(CASE WHEN @CSUBSECTION<>'' OR @CSECTION<>'' THEN ' JOIN SECTIOND E (NOLOCK) ON D.SUB_SECTION_CODE = E.SUB_SECTION_CODE ' ELSE '' END)+
					(CASE WHEN @CSECTION<>'' THEN ' JOIN SECTIONM F (NOLOCK) ON E.SECTION_CODE = F.SECTION_CODE'  ELSE '' END)      

SET @DTSQL=N'SELECT A.PRODUCT_CODE AS ARTICLE_NO,J.PARA1_NAME AS SECTION_NAME,H.PARA2_NAME AS PARA2_SET
			,B.PRODUCT_NAME AS SUB_SECTION_NAME,A.ARTICLE_NO AS PRODUCT_CODE,A.MRP,ISNULL(MST.MBQ,0) AS MBQ_QTY
			,ISNULL(MST.MST,0) AS MST_QTY,ISNULL(MSTWH.MBQ,0) AS MBQ_QTY_WH, ISNULL(MSTWH.MST,0) AS MST_QTY_WH
			,SUM(ISNULL(A.STOCK_QTY_WH,0)) AS STOCK_QTY_WH, SUM(ISNULL(A.STOCK_QTY,0)) AS STOCK_QTY
			,SUM(ISNULL(A.SLS_QTY,0)) AS SLS_QTY,SUM(ISNULL(A.SLS_QTY,0)*A.MRP) AS  SLS_VAL
FROM 
(SELECT A.PRODUCT_CODE,D.ARTICLE_NO,ISNULL(LOCSP.LOC_MRP,B.MRP) AS MRP,
SUM((CASE WHEN A.XN_TYPE IN (''OPS'', ''PUR'', ''CHI'', ''SLR'',''UNC'',''APR'', ''WSR'', ''PFI'',     
		  ''PFG'', ''BCG'',''MRP'',''DCI'',''PSB'',''JWR'') AND LO.PUR_LOC= 1  THEN 1 
		  WHEN A.XN_TYPE IN (''PRT'',''CHO'',''SLS'',''CNC'',''APP'',''WSL'',''CIP'', ''CRM'', ''DCO'',''MIP'',''CSB'',    
		  ''JWI'',''DLM'') AND LO.PUR_LOC=1 THEN -1 ELSE 0 END) * (XN_QTY)) AS STOCK_QTY_WH ,
SUM((CASE WHEN A.XN_TYPE IN (''OPS'', ''PUR'', ''CHI'', ''SLR'',''UNC'',''APR'', ''WSR'', ''PFI'',     
		  ''PFG'', ''BCG'',''MRP'',''DCI'',''PSB'',''JWR'') AND LO.PUR_LOC=0  THEN 1 
		  WHEN A.XN_TYPE IN (''PRT'',''CHO'',''SLS'',''CNC'',''APP'',''WSL'',''CIP'', ''CRM'', ''DCO'',''MIP'',''CSB'',    
		  ''JWI'',''DLM'') AND LO.PUR_LOC=0 THEN -1 ELSE 0 END) * (XN_QTY)) AS STOCK_QTY,
		  CONVERT(NUMERIC(10,2),0) AS SLS_QTY
FROM  '+@RFOPT+' A WITH (NOLOCK)
JOIN SKU B (NOLOCK) ON A.PRODUCT_CODE = B.PRODUCT_CODE 
JOIN LOCATION LO (NOLOCK) ON LO.DEPT_ID = A.DEPT_ID    
JOIN ARTICLE D (NOLOCK) ON D.ARTICLE_CODE=B.ARTICLE_CODE
LEFT OUTER JOIN LOCSKUSP_CURRENT LOCSP (NOLOCK) ON LOCSP.PRODUCT_CODE=B.PRODUCT_CODE AND LOCSP.DEPT_ID=LO.DEPT_ID '+@CADDJOINSTR+' 
WHERE XN_DT <= '''+@CDTTO+''' AND '+@CFILTER+' AND LO.INACTIVE=0 AND LO.DEPT_ID NOT IN (''R1'',''00'',''44'',''DM'',''F1'',''F5'',''MD'',''R1'',''W2'',''W4'')
GROUP BY A.PRODUCT_CODE,D.ARTICLE_NO,ISNULL(LOCSP.LOC_MRP,B.MRP)
UNION
SELECT A.PRODUCT_CODE,D.ARTICLE_NO,ISNULL(LOCSP.LOC_MRP,B.MRP) AS MRP,
CONVERT(NUMERIC(10,2),0) AS STOCK_QTY_WH,CONVERT(NUMERIC(10,2),0) AS STOCK_QTY,
SUM( CASE WHEN A.XN_TYPE=''SLS''  THEN XN_QTY WHEN A.XN_TYPE=''SLR''  THEN - (ABS(XN_QTY)) 
		  ELSE 0 END) AS SLS_QTY
FROM  '+@RFOPT+' A WITH (NOLOCK)
JOIN SKU B (NOLOCK) ON A.PRODUCT_CODE = B.PRODUCT_CODE 
JOIN LOCATION LO (NOLOCK) ON LO.DEPT_ID = A.DEPT_ID    
JOIN ARTICLE D (NOLOCK) ON D.ARTICLE_CODE=B.ARTICLE_CODE
LEFT OUTER JOIN LOCSKUSP_CURRENT LOCSP (NOLOCK) ON LOCSP.PRODUCT_CODE=B.PRODUCT_CODE AND LOCSP.DEPT_ID=LO.DEPT_ID '+@CADDJOINSTR+' 
WHERE XN_DT BETWEEN '''+@CDTFROM+''' AND '''+@CDTTO+''' AND '+@CFILTER+' AND LO.INACTIVE=0 
AND LO.DEPT_ID NOT IN (''R1'',''00'',''44'',''DM'',''F1'',''F5'',''MD'',''R1'',''W2'',''W4'')
GROUP BY A.PRODUCT_CODE,D.ARTICLE_NO,ISNULL(LOCSP.LOC_MRP,B.MRP)
) A
JOIN SKU B (NOLOCK) ON A.PRODUCT_CODE = B.PRODUCT_CODE  
JOIN PARA2 H (NOLOCK) ON B.PARA2_CODE = H.PARA2_CODE     
JOIN PARA1 J (NOLOCK) ON B.PARA1_CODE = J.PARA1_CODE '
SET @DTSQL=@DTSQL+N' LEFT OUTER JOIN     
#SQ1 MST  ON  MST.PRODUCT_CODE= B.PRODUCT_CODE   
LEFT OUTER JOIN  #SQ2 MSTWH  ON  MSTWH.PRODUCT_CODE= MST.PRODUCT_CODE 
GROUP BY A.PRODUCT_CODE,J.PARA1_NAME,H.PARA2_NAME,B.PRODUCT_NAME,A.ARTICLE_NO,
A.MRP, ISNULL(MST.MBQ,0),ISNULL(MST.MST,0),ISNULL(MSTWH.MBQ,0) , ISNULL(MSTWH.MST,0)
ORDER BY SLS_VAL  DESC'
PRINT @DTSQL
EXEC SP_EXECUTESQL @DTSQL
  
END
