CREATE PROCEDURE SP_MBQ_DET 
( 
@NQUERYID NUMERIC(3,0),  

@CMEMOID VARCHAR(22) = '',  --SUB SECTION CODE
@CWHERE  VARCHAR(200)= '',  --ARTICLE CODE
@CFINYEAR  VARCHAR(10)= '',
@NMONTH  NUMERIC(2) = 0,  
@NYEAR  NUMERIC(4) = 0,  

@DFROMDT DATETIME = '',  
@DTODT  DATETIME = '',  

@DEPTID VARCHAR(10) ='',
@CSECTIONCODE VARCHAR(50) ='',
@CPRODUCTCODE VARCHAR(50) =''  
) 
--WITH ENCRYPTION

AS  
BEGIN  
  
DECLARE @CCMD NVARCHAR(4000)  
DECLARE @CCMD2 NVARCHAR(4000)  
  
IF @NQUERYID = 1  
GOTO LBLSUBSECTION  
  
ELSE   
IF @NQUERYID = 2  
GOTO LBLGETINLIST  
  
ELSE   
IF @NQUERYID = 3  
GOTO LBLGETARTICLE  
  
ELSE   
IF @NQUERYID = 4  
GOTO LBLGETINLISTIMPORT  
ELSE   
IF @NQUERYID = 5  
GOTO LBLGETLOCATION  
ELSE   
IF @NQUERYID = 6  
GOTO LBLGETPRODUCT  

  
LBLSUBSECTION:  
		 SELECT D.SUB_SECTION_NAME,M.SECTION_NAME,D.SUB_SECTION_CODE,D.SECTION_CODE      
		 FROM SECTIONM M 
		 JOIN SECTIOND D ON M.SECTION_CODE = D.SECTION_CODE 
		 WHERE D.SUB_SECTION_NAME <> '' AND D.INACTIVE =0 AND M.SECTION_CODE <> '0000000'  
 GOTO LAST  
  
LBLGETINLIST:  
		  SET @CCMD = N'SELECT ROW_NUMBER() OVER (PARTITION BY F.DEPT_ID ORDER BY A.PRODUCT_CODE) AS SNO
		  ,A.PRODUCT_CODE,F.DEPT_ID,F.DEPT_NAME,D.SECTION_CODE,D.SECTION_NAME  
		  ,ISNULL(M.MBQ,0) AS MBQ
		  ,ISNULL(M.MST,0) AS MST  
		  ,ISNULL(M.MONTH,'+ STR(@NMONTH)+') AS MONTH
		  ,ISNULL(M.YEAR,'+ STR(@NYEAR)+') AS YEAR 
		  ,NEWID() AS ROW_ID 
		  FROM SKU A   
		  JOIN ARTICLE B ON A.ARTICLE_CODE = B.ARTICLE_CODE   
		  JOIN SECTIOND C ON B.SUB_SECTION_CODE = C.SUB_SECTION_CODE   
		  JOIN SECTIONM D ON C.SECTION_CODE = D.SECTION_CODE   
		  JOIN LOCATION F ON 1=(CASE WHEN '+ RTRIM(STR(@NMONTH))+' = 0 THEN 2 ELSE 1  END)  
		  LEFT OUTER JOIN MBQ_DET M ON M.PRODUCT_CODE = A.PRODUCT_CODE  
		  AND M.DEPT_ID = F.DEPT_ID  AND M.MONTH = '+ STR(@NMONTH)+' AND M.YEAR = '+ STR(@NYEAR)+' 
		  WHERE  F.INACTIVE = 0 AND A.PRODUCT_CODE <> ''''
		  AND (ISNULL(M.MBQ,0) > 0 OR  ISNULL(M.MST,0) > 0)
		  AND F.DEPT_ID = '+ CASE WHEN @DEPTID = '' THEN 'F.MAJOR_DEPT_ID' ELSE ''''+ @DEPTID +''''  END +'  
		  '+ CASE WHEN @CSECTIONCODE = '' THEN '' ELSE ' AND C.SECTION_CODE = '''+ @CSECTIONCODE +''' ' END  +' 
		  '+ CASE WHEN @CMEMOID = '' THEN '' ELSE ' AND C.SUB_SECTION_CODE = '''+ @CMEMOID +''' ' END  +' 
		  '+ CASE WHEN @CWHERE = '' THEN '' ELSE ' AND B.ARTICLE_CODE = '''+ @CWHERE +''' ' END  +' 
		  '+ CASE WHEN @CPRODUCTCODE = '' THEN '' ELSE ' AND A.PRODUCT_CODE = '''+ @CPRODUCTCODE +''' ' END  +' ' 
		   PRINT @CCMD  
		 EXEC SP_EXECUTESQL @CCMD 
GOTO LAST  
  
LBLGETARTICLE:  
		 SET @CCMD = N'SELECT A.ARTICLE_CODE,A.ARTICLE_NAME,A.ARTICLE_NO,C.SECTION_NAME,B.SUB_SECTION_NAME   
		 FROM ARTICLE A 
		 JOIN SECTIOND B ON A.SUB_SECTION_CODE = B.SUB_SECTION_CODE 
		 JOIN SECTIONM C ON B.SECTION_CODE = C.SECTION_CODE 
		 WHERE ARTICLE_CODE <>'''' AND A.INACTIVE = 0 
		 '+ CASE WHEN @CSECTIONCODE = '' THEN '' ELSE ' AND C.SECTION_CODE = '''+ @CSECTIONCODE +''' ' END  +' 
		 '+ CASE WHEN @CMEMOID = '' THEN '' ELSE ' AND B.SUB_SECTION_CODE = '''+ @CMEMOID +''' ' END  +' '
		 PRINT @CCMD  
		 EXEC SP_EXECUTESQL @CCMD 
GOTO LAST  
  
LBLGETINLISTIMPORT:  
		  SET @CCMD = N'SELECT  ROW_NUMBER() OVER (PARTITION BY F.DEPT_ID ORDER BY MST.PRODUCT_CODE) AS SNO
		  ,MST.PRODUCT_CODE 
		  ,F.DEPT_ID,F.DEPT_NAME ,D.SECTION_CODE,D.SECTION_NAME  
		  ,ISNULL(SUM(CAST(MST.MBQ AS NUMERIC(14,3))),0) AS MBQ, ISNULL(SUM(CAST(MST.MST AS NUMERIC(14,3))),0) AS MST  
		  ,'+ STR(@NMONTH)+' AS MONTH,'+STR(@NYEAR)+' AS YEAR  , NEWID() AS ROW_ID 
		  FROM TEMP_EXCEL_IMPORT_MONTHLY_SALE_TARGET_'+@CWHERE+' MST  
		  JOIN SKU A ON MST.PRODUCT_CODE = A.PRODUCT_CODE  
		  JOIN ARTICLE B ON A.ARTICLE_CODE = B.ARTICLE_CODE   
		  JOIN SECTIOND C ON B.SUB_SECTION_CODE = C.SUB_SECTION_CODE   
		  JOIN SECTIONM D ON C.SECTION_CODE = D.SECTION_CODE   
		  JOIN LOCATION F ON MST.DEPT_ID = F.DEPT_ID   
		  WHERE F.DEPT_ID = F.MAJOR_DEPT_ID AND F.INACTIVE = 0  
		  GROUP BY  MST.PRODUCT_CODE ,F.DEPT_ID,F.DEPT_NAME,D.SECTION_CODE,D.SECTION_NAME'  
		  PRINT @CCMD  
		  EXEC SP_EXECUTESQL @CCMD  
GOTO LAST
  
LBLGETLOCATION:  
			SELECT * FROM LOCATION WHERE DEPT_ID = MAJOR_DEPT_ID AND INACTIVE = 0  
GOTO LAST  

LBLGETPRODUCT:  
			SET @CCMD = N'SELECT S.PRODUCT_CODE,S.PRODUCT_NAME 
			FROM SKU (NOLOCK) S 
			JOIN ARTICLE (NOLOCK) A ON S.ARTICLE_CODE = A.ARTICLE_CODE 
			JOIN SECTIOND (NOLOCK) B ON A.SUB_SECTION_CODE = B.SUB_SECTION_CODE 
			JOIN SECTIONM (NOLOCK) C ON B.SECTION_CODE = C.SECTION_CODE
			WHERE S.PRODUCT_CODE <>'''' 
			'+ CASE WHEN @CSECTIONCODE = '' THEN '' ELSE ' AND C.SECTION_CODE = '''+ @CSECTIONCODE +''' ' END  +' 
			'+ CASE WHEN @CMEMOID = '' THEN '' ELSE ' AND B.SUB_SECTION_CODE = '''+ @CMEMOID +''' ' END  +' 
			'+ CASE WHEN @CWHERE = '' THEN '' ELSE ' AND A.ARTICLE_CODE = '''+ @CWHERE +''' ' END  +' ' 
			PRINT @CCMD  
		    EXEC SP_EXECUTESQL @CCMD  
GOTO LAST  


LAST:  
END
