CREATE PROCEDURE SP_DEFINE_CHALLANSERIES
(
   @NUPDATEMODE INT ,
   @CSOURCE_DEPT_ID VARCHAR(100)='',
   @CTARGETD_DEPT_ID VARCHAR(100)='',
   @NSPID INT=0
)
AS
BEGIN
     IF @NUPDATEMODE=1
     BEGIN
         
         SELECT L.SOURCE_DEPT_ID,LM.DEPT_NAME AS SOURCE_DEPT_NAME ,L.TARGET_DEPT_ID,LM1.DEPT_NAME AS TARGET_DEPT_NAME,L.WSL_SERIES,PRT_SERIES,
                ROW_ID=NEWID()
         FROM LOC_GROUPTRANSFER_SERIES L (NOLOCK)
         JOIN LOCATION LM (NOLOCK) ON LM.DEPT_ID=L.SOURCE_DEPT_ID
         JOIN LOCATION LM1 (NOLOCK) ON LM1.DEPT_ID=L.TARGET_DEPT_ID
         WHERE (@CSOURCE_DEPT_ID='' OR L.SOURCE_DEPT_ID=@CSOURCE_DEPT_ID)
         AND   (@CTARGETD_DEPT_ID='' OR L.TARGET_DEPT_ID=@CTARGETD_DEPT_ID)
       
     END
     ELSE IF @NUPDATEMODE=2
     BEGIN
     
          IF OBJECT_ID ('TEMPDB..#TMPGRPTRSERIES','U') IS NOT NULL 
             DROP TABLE #TMPGRPTRSERIES
             
             CREATE TABLE #TMPGRPTRSERIES(SOURCE_DEPT_ID VARCHAR(2),TARGET_DEPT_ID VARCHAR(2),WSL_SERIES VARCHAR(100),PRT_SERIES VARCHAR(100))
     
     
         IF @CSOURCE_DEPT_ID<>'' AND @CTARGETD_DEPT_ID=''
         
				 INSERT INTO #TMPGRPTRSERIES
				 SELECT SOURCE_DEPT_ID=CASE WHEN @CSOURCE_DEPT_ID<>'' THEN @CSOURCE_DEPT_ID ELSE L.DEPT_ID END,
						TARGET_DEPT_ID=CASE WHEN @CSOURCE_DEPT_ID<>'' THEN L.DEPT_ID ELSE '' END,'',''
						FROM LOCATION L (NOLOCK)  
						WHERE L.DEPT_ID<>@CSOURCE_DEPT_ID 
                
         ELSE IF @CSOURCE_DEPT_ID='' AND @CTARGETD_DEPT_ID<>''
         
                  INSERT INTO #TMPGRPTRSERIES
				  SELECT SOURCE_DEPT_ID=CASE WHEN @CTARGETD_DEPT_ID<>'' THEN L.DEPT_ID ELSE '' END,
						 TARGET_DEPT_ID=CASE WHEN @CTARGETD_DEPT_ID<>'' THEN @CTARGETD_DEPT_ID ELSE  L.DEPT_ID END,'',''
				        FROM LOCATION L (NOLOCK)  WHERE L.DEPT_ID<>@CTARGETD_DEPT_ID --AND L.DEPT_ID<>@SRC
				        
       ELSE IF @CSOURCE_DEPT_ID<>'' AND @CTARGETD_DEPT_ID<>''
       
                 INSERT INTO #TMPGRPTRSERIES
                 SELECT DISTINCT  SOURCE_DEPT_ID=CASE WHEN DEPT_ID=@CTARGETD_DEPT_ID THEN @CSOURCE_DEPT_ID ELSE DEPT_ID  END,
                       TARGET_DEPT_ID=CASE WHEN DEPT_ID=@CSOURCE_DEPT_ID THEN @CTARGETD_DEPT_ID ELSE DEPT_ID  END,'',''
                       FROM LOCATION L (NOLOCK)
                       
                      SELECT T.SOURCE_DEPT_ID,LM.DEPT_NAME AS SOURCE_DEPT_NAME ,T.TARGET_DEPT_ID,LM1.DEPT_NAME AS TARGET_DEPT_NAME,WSL_SERIES=ISNULL(L.WSL_SERIES,''),PRT_SERIES=ISNULL(L.PRT_SERIES,''),ROW_ID=NEWID()
                            FROM  #TMPGRPTRSERIES T 
                            LEFT JOIN
                            (
                             SELECT L.SOURCE_DEPT_ID,L.TARGET_DEPT_ID,L.WSL_SERIES,L.PRT_SERIES  
                             FROM  LOC_GROUPTRANSFER_SERIES L (NOLOCK)
                            ) L ON L.SOURCE_DEPT_ID =T.SOURCE_DEPT_ID AND L.TARGET_DEPT_ID=T.TARGET_DEPT_ID 
                           JOIN LOCATION LM (NOLOCK) ON LM.DEPT_ID=T.SOURCE_DEPT_ID
                           JOIN LOCATION LM1 (NOLOCK) ON LM1.DEPT_ID=T.TARGET_DEPT_ID
                       
                     
         
     END
     ELSE IF @NUPDATEMODE=3
     BEGIN
          DECLARE @CMASTERTABLENAME VARCHAR(100),
				  @CTEMPMASTERTABLE VARCHAR(100),
				  @CTEMPMASTERTABLENAME VARCHAR(100),
				  @CTEMPDBNAME VARCHAR(100),		
				  @NSTEP VARCHAR(10),
				  @CKEYFIELD VARCHAR(100),
				  @CKEYFIELD1 VARCHAR(100),
				  @CERRORMSG VARCHAR(1000),
				  @CCMD NVARCHAR(MAX)
				  
				  
		  DECLARE @OUTPUT TABLE(ERRMSG VARCHAR(2000),SOURCE_DEPT_ID VARCHAR(100),TARGET_DEPT_ID VARCHAR(100))
          SET @NSTEP = 0		-- SETTTING UP ENVIRONMENT		
          SET @CTEMPDBNAME =  DB_NAME()+'.DBO.'
          SET @CMASTERTABLENAME ='LOC_GROUPTRANSFER_SERIES'		
		
		 SET @CTEMPMASTERTABLE  ='TEMP_LOC_GROUPTRANSFER_SERIES_'+LTRIM(RTRIM(STR(@NSPID)))		
		 SET @CTEMPMASTERTABLENAME = @CTEMPDBNAME + @CTEMPMASTERTABLE
		 
		
		 SET @CKEYFIELD = 'SOURCE_DEPT_ID'
		 SET @CKEYFIELD1 = 'TARGET_DEPT_ID'
       
         SET @NSTEP = 10		-- BEGIN TRANSACTION    
         BEGIN TRY
	     BEGIN TRANSACTION
	      
	     SET @CCMD=N'DELETE FROM '+@CTEMPMASTERTABLENAME+' WHERE  ISNULL(WSL_SERIES,'''')='''' AND ISNULL(PRT_SERIES,'''')='''' '
	     PRINT @CCMD
	     EXEC SP_EXECUTESQL @CCMD
	      
         SET @NSTEP = 20	   
				EXEC UPDATEMASTERXN 
					  @CSOURCEDB	= @CTEMPDBNAME
					, @CSOURCETABLE = @CTEMPMASTERTABLE
					, @CDESTDB		= ''
					, @CDESTTABLE	= @CMASTERTABLENAME
					, @CKEYFIELD1	= @CKEYFIELD
					, @CKEYFIELD2	= @CKEYFIELD1
					, @BALWAYSUPDATE = 1
				
		
	  
	     END TRY
         BEGIN CATCH
				SET @CERRORMSG = 'STEP- ' + LTRIM(STR(@NSTEP)) + ' SQL ERROR: #' + LTRIM(STR(ERROR_NUMBER())) + ' ' + ERROR_MESSAGE()
				GOTO END_PROC
        END CATCH
END_PROC:
		IF @@TRANCOUNT>0
		BEGIN
			IF ISNULL(@CERRORMSG,'')=''
				COMMIT TRANSACTION
			ELSE
			ROLLBACK 	
		END 
		SELECT ISNULL(@CERRORMSG,'') AS ERRMSG
				SET @CCMD = N'IF OBJECT_ID('''+@CTEMPMASTERTABLENAME+''',''U'') IS NOT NULL
							DROP TABLE '+@CTEMPMASTERTABLENAME+''
					PRINT @CCMD
					EXEC SP_EXECUTESQL @CCMD   		   		    
     END
END
