CREATE PROCEDURE SP3S_RESTRICT_CNRF_ISSUE
@CCMID VARCHAR(40),
@NUPDATEMODE INT,
@CUSERCODE CHAR(7),
@NSPID VARCHAR(40)='',
@CERRORMSG VARCHAR(500) OUTPUT
AS
BEGIN
	DECLARE @CDONOTALLOWCNREFUND VARCHAR(2),@CCUSTOMERCODE VARCHAR(15),@CPAYMODECODE CHAR(7),
	@NBALANCE NUMERIC(10,2),@nCashCNAmt NUMERIC(10,2),@cStep VARCHAR(20)
	

	SET @CSTEP='V-9.1.1'
	EXEC SP_CHKXNSAVELOG 'SLS',@cStep,0,@NSPID,1		
	SET @CERRORMSG=''
	
	SELECT TOP 1 @CDONOTALLOWCNREFUND=VALUE FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION='DONOT_ENFORCE_CREDIT_REFUND'
	
	IF ISNULL(@CDONOTALLOWCNREFUND,'')='1'
		RETURN
		
	IF @CCMID<>''
		SELECT @CCUSTOMERCODE=CUSTOMER_CODE FROM CMM01106 (NOLOCK) WHERE CM_ID=@CCMID
	ELSE
		SELECT @CCUSTOMERCODE=CUSTOMER_CODE FROM SLS_CMM01106_UPLOAD (NOLOCK)  WHERE SP_ID=@NSPID
	
	IF ISNULL(@CCUSTOMERCODE,'')='000000000000'	
		RETURN
		
	SET @CSTEP='V-9.1.2'
	EXEC SP_CHKXNSAVELOG 'SLS',@cStep,0,@NSPID,1		

	--	select * from paymode_mst
	IF @CCMID<>''	
		SELECT @nCashCNAmt=SUM(amount) FROM PAYMODE_XN_DET a (NOLOCK) 
		JOIN paymode_mst b (NOLOCK) ON a.paymode_code=b.paymode_code
		WHERE MEMO_ID=@CCMID AND XN_TYPE='SLS'
		AND (a.PAYMODE_CODE IN ('0000000','0000004') OR paymode_grp_code IN ('0000001','0000002')) AND AMOUNT<0
	ELSE
		SELECT @nCashCNAmt=SUM(amount) FROM SLS_PAYMODE_XN_DET_UPLOAD a (NOLOCK)
		JOIN paymode_mst b (NOLOCK) ON a.paymode_code=b.paymode_code WHERE
		SP_ID=@NSPID AND XN_TYPE='SLS' 
		AND (a.PAYMODE_CODE IN ('0000000','0000004') OR paymode_grp_code IN ('0000001','0000002')) AND AMOUNT<0
		
	IF ISNULL(@nCashCNAmt,0)=0
		RETURN
	
	SET @CSTEP='V-9.1.4'
	EXEC SP_CHKXNSAVELOG 'SLS',@cStep,0,@NSPID,1		

	IF @NUPDATEMODE=2
		SELECT @CCMID=CM_ID FROM SLS_CMM01106_UPLOAD (NOLOCK) WHERE SP_ID=@NSPID
			
	SET @CSTEP='V-9.1.6'
	EXEC SP_CHKXNSAVELOG 'SLS',@cStep,0,@NSPID,1		

	DECLARE @TBAL TABLE (CLOSING_BALANCE NUMERIC(10,2))
		
	INSERT @TBAL
	EXEC USP_CUSTBAL @CCUSTOMERCODE,@CCMID
	
	SELECT TOP 1 @NBALANCE=CLOSING_BALANCE FROM @TBAL

	DECLARE @NCREDITREFUND NUMERIC(10,2)	

	IF @NBALANCE>0
	BEGIN

		SET @CSTEP='V-9.1.8'
		EXEC SP_CHKXNSAVELOG 'SLS',@cStep,0,@NSPID,1		

		IF @CCMID<>''
			SELECT @NCREDITREFUND=ABS(SUM(AMOUNT)) FROM PAYMODE_XN_DET (NOLOCK) WHERE MEMO_ID=@CCMID AND XN_TYPE='SLS'
			AND PAYMODE_CODE='CMR0001'
		ELSE
			SELECT @NCREDITREFUND=ABS(SUM(AMOUNT)) FROM SLS_PAYMODE_XN_DET_UPLOAD (NOLOCK) WHERE SP_ID=@NSPID
			AND PAYMODE_CODE='CMR0001'
		
		SET @NBALANCE=@NBALANCE-ISNULL(@NCREDITREFUND,0)
	END
	
	SET @CSTEP='V-9.1.10'
	EXEC SP_CHKXNSAVELOG 'SLS',@cStep,0,@NSPID,1		
	
	IF @NBALANCE>0 AND ISNULL(@NCREDITREFUND,0)=0
		SET @CERRORMSG='(S)CASH REFUND OR CREDIT NOTE ISSUE NOT ALLOWED FOR THIS CUSTOMER...(Balance:('+str(isnull(@NBALANCE,0),10,2)+
					   ') Refund :'+str(ISNULL(@NCREDITREFUND,0),10,2)+')'
END


