CREATE PROCEDURE SP_RETAILSALE_16 --(LocId 3 digit change by Sanjay:30-10-2024)
(  
	 @CQUERYID			NUMERIC(2),  
	 @CWHERE			VARCHAR(MAX)='',  
	 @CFINYEAR			VARCHAR(5)='',  
	 @CDEPTID			VARCHAR(4)='',  
	 @NNAVMODE			NUMERIC(2)=1,  
	 @CWIZAPPUSERCODE	VARCHAR(10)='',  
	 @CREFMEMOID		VARCHAR(40)='',  
	 @CREFMEMODT		DATETIME='',  
	 @BINCLUDEESTIMATE	BIT=1,  
	 @CFROMDT			DATETIME='',  
	 @CTODT				VARCHAR(50)='',
	 @bCardDiscount		BIT=0,
	 @cCustCode			VARCHAR(15)=''
) 
AS  
BEGIN  
 SELECT  CAST(0 AS BIT) AS CHK, A.HOLD_ID, 'SESSION#' + LTRIM(RTRIM(STR(SESSION_ID))) AS [SESSION_ID],    
 ISNULL(B.USER_CUSTOMER_CODE+'-'+B.CUSTOMER_FNAME+' '+B.CUSTOMER_LNAME,'') AS CUSTOMER,C.QUANTITY, A.NET_AMOUNT,  
 ISNULL(F.EMP_NAME,'') AS EMP_NAME    
 FROM CMM_HOLD A    (NOLOCK)  
 JOIN     
 (    
  SELECT HOLD_ID,SUM(QUANTITY) AS QUANTITY     
  FROM CMD_HOLD    (NOLOCK)  
  GROUP BY HOLD_ID    
 )C ON C.HOLD_ID=A.HOLD_ID    
  
 LEFT OUTER JOIN       
 (      
   SELECT HOLD_ID,B.EMP_NAME    
  FROM CMM_HOLD A  (NOLOCK)    
  JOIN EMPLOYEE B  (NOLOCK) ON B.EMP_CODE = DBO.FN_GETBILLHOLDEMPCODE(A.HOLD_ID)  
  WHERE A.USER_CODE=(CASE WHEN @CWHERE   ='0000000' THEN A.user_code ELSE @CWHERE END)
      
 )F ON F.HOLD_ID=A.HOLD_ID      
  
 LEFT OUTER JOIN CUSTDYM B  (NOLOCK) ON B.CUSTOMER_CODE=A.CUSTOMER_CODE    
 WHERE A.USER_CODE=(CASE WHEN @CWHERE   ='0000000' THEN A.user_code ELSE @CWHERE END)  
 AND a.hbd_location_code= @CDEPTID  AND A.CM_DT BETWEEN  @CFROMDT AND  @CTODT 
end
