CREATE PROCEDURE SP3S_GET_HBD_STATUS_LAST_UPDATE
AS
BEGIN
	DECLARE @dtINV DATETIME,@dtImage DATETIME
	DECLARE @cCMD NVARCHAR(MAX)
	select @dtINV=MAX(HBD_STATUS_UPDATED_ON)  from hold_back_deliver_det(NOLOCK) where memo_id<>''
	SET @dtINV=ISNULL(@dtINV,'') 
	SELECT @dtINV AS LAST_UPDATE	
END