CREATE PROCEDURE SP_RESENDXNSDATA_REQ
(
	@CXNTYPE VARCHAR(10),
	@CXNID VARCHAR(50)
)
--WITH ENCRYPTION
AS
BEGIN
	
	DECLARE @CTABLENAME VARCHAR(100),@CCMD NVARCHAR(MAX),@CKEYFIELD VARCHAR(100),@CREFXNTYPE VARCHAR(10),
			@NSTEP INT,@CERRORMSG VARCHAR(MAX)
	
	BEGIN TRY
		
		SET @NSTEP=10	
				
		SELECT TOP 1  @CTABLENAME=TABLENAME,@CKEYFIELD=KEYFIELD FROM XNSINFO (NOLOCK) 
		WHERE XN_TYPE=@CXNTYPE AND ISNULL(MEMODTCOL,'')<>''
		
		SET @NSTEP=20
		IF @CXNTYPE='DOCCHO_WSL'
		BEGIN
			SET @CCMD=N'UPDATE INM01106 SET UPLOADED_TO_ACTIVSTREAM=0,EXPORTED=1 WHERE INV_ID='''+@CXNID+''''
		END	
		ELSE
		IF @CXNTYPE='DOCCHO_PRT'
		BEGIN
			SET @CCMD=N'UPDATE RMM01106 SET UPLOADED_TO_ACTIVSTREAM=0,EXPORTED=1 WHERE INV_ID='''+@CXNID+''''
		END	
		ELSE
		IF @CXNTYPE='XNSOPS'
		BEGIN
			SET @CCMD=N'UPDATE OPS01106 SET LAST_UPDATE=GETDATE()'			
		END			
		ELSE		
		BEGIN
			SET @CCMD=N'UPDATE '+@CTABLENAME+' SET LAST_UPDATE=GETDATE() WHERE '+@CKEYFIELD +'='''+@CXNID+''''
		END
		
		SET @NSTEP=30
		PRINT @CCMD
		EXEC SP_EXECUTESQL @CCMD
	
	END TRY
	
	BEGIN CATCH
		
		SELECT @CERRORMSG='PROCEDURE : SP_RESENDXNSDATA_REQ STEP: '+STR(@NSTEP)+' LINE NO. :'+
		ISNULL(LTRIM(RTRIM(STR(ERROR_LINE()))),'NULL LINE')+'MSG :'+ISNULL(ERROR_MESSAGE(),'NULL MSG')
		
	END CATCH

END
--********************************************** END OF PROCEDURE SP_RESENDXNSDATA_REQ
