CREATE PROCEDURE SP_GETXNSAPPROVAL
--WITH ENCRYPTION
AS
BEGIN
	DECLARE @TABLE_XNTYPE TABLE   (XN_TYPE VARCHAR(10),MODULE_NAME VARCHAR(50))
	INSERT INTO @TABLE_XNTYPE(XN_TYPE ,MODULE_NAME)
	VALUES ('PUR','PURCHASE INVOICE')
	
	INSERT INTO @TABLE_XNTYPE(XN_TYPE ,MODULE_NAME)
	VALUES ('PRT','PURCHASE RETURN')
	
	INSERT INTO @TABLE_XNTYPE(XN_TYPE ,MODULE_NAME)
	VALUES ('PTC','PETTY CASH')
	
	INSERT INTO @TABLE_XNTYPE(XN_TYPE ,MODULE_NAME)
	VALUES ('VCH','VOUCHERS')
	
	SELECT A.XN_TYPE,A.MODULE_NAME,A.DEPT_ID,A.DEPT_ID+'-'+A.DEPT_NAME AS [DEPT_NAME],ISNULL(B.CHK,0) AS CHK ,GETDATE() AS [LAST_UPDATE] 
	FROM
	(
		SELECT A.XN_TYPE,A.MODULE_NAME,B.DEPT_ID,B.DEPT_NAME,CONVERT(BIT,0) AS [CHK]
		FROM @TABLE_XNTYPE A,LOCATION B
		WHERE B.INACTIVE=0 AND B.MAJOR_DEPT_ID=B.DEPT_ID
	)A
	LEFT OUTER JOIN 
	(
		SELECT A.XN_TYPE,A.MODULE_NAME,A.DEPT_ID,B.DEPT_NAME,CONVERT(BIT,1) AS [CHK]
		FROM LOC_XNSAPPROVAL A
		JOIN LOCATION B ON B.DEPT_ID=A.DEPT_ID
	)B ON A.XN_TYPE=B.XN_TYPE AND A.DEPT_ID=B.DEPT_ID
	ORDER BY MODULE_NAME,A.DEPT_NAME
END
