create Procedure sp3s_PendingPoreport
(
  @cAc_name varchar(10)='',
  @Dason dateTime='2024-03-01'
 
)
as
begin

    
		SELECT  C.PO_DT ,C.REF_NO,C.PACKING_DT, ART.ARTICLE_NO,ART.ARTICLE_NAME ,
		       PARA1_NAME ,PARA2_NAME,PARA3_NAME ,B.PURCHASE_PRICE,B.MRP ,C.PO_NO ,B.DELIVERY_DT ,B.PRODUCT_CODE ,
			   LM.ALIAS AS  SUPPLIERALIAS,LM.AC_NAME AS SUPPLIERNAME,LM.LM_REMARKS  AS 	SUPPLIERREMARKS,
			   OEM.ALIAS AS  OEMALIAS,OEM.AC_NAME AS OEMNAME,OEM.LM_REMARKS  AS 	OEMEMARKS,
			   sd.sub_section_name ,sm.section_name ,
			   SUM(CASE WHEN A.XNTYPE='PURCHASEORDER' THEN A.QTY ELSE 0 END) AS POQTY,
			   SUM(CASE WHEN A.XNTYPE='PURCHASEINVOICE' THEN A.QTY ELSE 0 END) AS PIQTY,
			   SUM(CASE WHEN A.XNTYPE='PURCHASEORDER' THEN A.QTY ELSE -1*A.QTY END) AS PENDINGQTY
			    INTO #TMPPOQTY
        FROM PURCHASEORDERPROCESSINGNEW A (NOLOCK)
		JOIN POD01106 B (NOLOCK) ON A.REFROWID =B.ROW_ID 
		JOIN POM01106 C (NOLOCK) ON C.PO_ID =B.PO_ID 
		JOIN PARA1 P1 (NOLOCK) ON P1.PARA1_CODE =B.PARA1_CODE 
		JOIN PARA2 P2 (NOLOCK) ON P2.PARA2_CODE =B.PARA2_CODE 
		JOIN PARA3 P3 (NOLOCK) ON P3.PARA3_CODE =B.PARA3_CODE 
		JOIN ARTICLE ART (NOLOCK) ON ART.ARTICLE_CODE =B.ARTICLE_CODE 
		join sectiond sd (nolock) on sd.sub_section_code =art.sub_section_code 
		join sectionm sm (nolock) on sm.section_code =sd.section_code  
		JOIN LM01106 LM (NOLOCK) ON LM.AC_CODE =C.AC_CODE 
		left JOIN LM01106 OEM (NOLOCK) ON OEM.AC_CODE =C.SHIPPING_FROM_AC_CODE  
		WHERE C.CANCELLED=0 AND ISNULL(C.SHORT_CLOSE,0)=0  
		AND C.PO_DT <=@DASON
		AND (@CAC_NAME='' OR LM.AC_NAME =@CAC_NAME)
		GROUP BY C.PO_DT ,C.REF_NO,C.PACKING_DT ,ART.ARTICLE_NO,ART.ARTICLE_NAME ,  sd.sub_section_name ,sm.section_name ,
		PARA1_NAME ,PARA2_NAME,PARA3_NAME ,B.PURCHASE_PRICE,B.MRP ,C.PO_NO ,B.DELIVERY_DT ,B.PRODUCT_CODE,LM.ALIAS,LM.AC_NAME ,LM.LM_REMARKS  ,
		 OEM.ALIAS ,OEM.AC_NAME ,OEM.LM_REMARKS  
		HAVING  SUM(CASE WHEN A.XNTYPE='PURCHASEORDER' THEN A.QTY ELSE -1*A.QTY END)>0
		
		
		select * from #TMPPOQTY
		order by po_dt

end