CREATE PROCEDURE  SP3S_SYNCH_UPLOADDATA_TTM_OPT
(
    @nSpId VARCHAR(50)
   ,@CERRMSG VARCHAR(1000) OUTPUT
)
AS
SET NOCOUNT ON
BEGIN


DECLARE @CSTEP VARCHAR(100),@DTSQL NVARCHAR(MAX)
	   ,@CTABLENAME VARCHAR(200),@CKEYFIELD VARCHAR(200),@CTMP_TABLENAME VARCHAR(200),@LINSERTONLY VARCHAR(1)
	   ,@CFILTERCONDITION VARCHAR(200),@LUPDATEONLY VARCHAR(1),@BALWAYSUPDATE VARCHAR(1)
	   ,@CCURDEPTID VARCHAR(5),@CTEMPMASTERTABLE VARCHAR(200),@CTEMPDETAILTABLE1 VARCHAR(200),
	    @CTEMPDETAILTABLE2 VARCHAR(200), @CTEMPDETAILTABLE3 VARCHAR(200), @CTEMPDETAILTABLE4 VARCHAR(200)
	   ,@BADDMODE BIT,@CSOURCEDB VARCHAR(200),@CMERGEDB VARCHAR(200)
	   ,@BMSTINSERTONLY BIT,@BSERIESMISMATCHFOUND BIT,@CMEMOID VARCHAR(40),@CPREVMEMONO VARCHAR(20)
	   ,@NPREVMEMONO NUMERIC(5,0),@NLENVALUE INT,@CPREVMEMONOSEARCH VARCHAR(20),@CMEMOIDSEARCH VARCHAR(40)
	   ,@NVERSIONNO INT,@CJOINSTR VARCHAR(MAX)
	   ,@CTEMPIMPTABLE VARCHAR(200),@CCMD NVARCHAR(MAX),@bcancelled bit,
	   @cUpdatestr VARCHAR(MAX),@cLocId varchar(5)
	

BEGIN TRY
	
	
	SET @CSTEP=10

	SELECT @CSOURCEDB='',@CMERGEDB='',@BMSTINSERTONLY=1,@BSERIESMISMATCHFOUND=0
	
	SET @CSTEP=15
    	
    SELECT TOP 1 @CCURDEPTID=VALUE FROM CONFIG WHERE CONFIG_OPTION='LOCATION_ID'

	SELECT @CTEMPMASTERTABLE=@CSOURCEDB+'TTM_TRANSFER_TO_TRADING_MST_UPLOAD',
		   @CTEMPDETAILTABLE1=@CSOURCEDB+'TTM_TRANSFER_TO_TRADING_DET_UPLOAD' ,
		   @CTEMPDETAILTABLE2=@CSOURCEDB+'TTM_TRANSFER_TO_TRADING_BOM_UPLOAD', 
		   @CTEMPDETAILTABLE3=@CSOURCEDB+'TTM_TRANSFER_TO_TRADING_JOBS_UPLOAD', 
		   @CTEMPDETAILTABLE4=@CSOURCEDB+'TTM_TRANSFER_TO_TRADING_SUB_DET_UPLOAD' 
		   
	
    

LBLSTART:
    
    BEGIN TRANSACTION
    
    SELECT @CMEMOID='',@NVERSIONNO=0
		

    SET @CSTEP=30
    SELECT TOP 1 @CMEMOID = B.MEMO_ID ,@bcancelled=cancelled ,@cLocId = B.location_code 
    FROM TTM_TRANSFER_TO_TRADING_MST_upload B (NOLOCK)
	where sp_id=@nSpId
    
    
    IF ISNULL(@CMEMOID,'')=''
		GOTO EXIT_PROC
		
    SET @CFILTERCONDITION = 'B.MEMO_ID='''+@CMEMOID+''' AND B.sp_id='''+@nSpId+''''
	

	SET @CSTEP=40
	SET @CMEMOIDSEARCH=''
	SELECT TOP 1 @CMEMOIDSEARCH=A.MEMO_ID FROM TRANSFER_TO_TRADING_MST A (NOLOCK) WHERE A.MEMO_ID=@CMEMOID
	
	IF ISNULL(@CMEMOIDSEARCH,'')<>''
		SET @BADDMODE=0
	ELSE
		SET @BADDMODE=1


	IF @BADDMODE=0
	BEGIN	
	     
		 IF @bCancelled=1 
		BEGIN
			UPDATE SNC_MST WITH (ROWLOCK) SET cancelled=1 WHERE MEMO_ID=@cMemoid
			GOTO lblUpdatePmt
		END

		IF EXISTS (SELECT TOP 1 tablename FROM savetran_updcols_updatestr (NOLOCK) WHERE sp_id=@nSPID)
			DELETE FROM savetran_updcols_updatestr WITH (ROWLOCK) WHERE sp_id=@nSpId

		INSERT savetran_updcols_updatestr (sp_id,tablename,updatestr)
		SELECT @nSPId as sp_id,tablename,'' from mirrorxnsinfo (NOLOCK)
		WHERE tablename IN ('TRANSFER_TO_TRADING_MST','TRANSFER_TO_TRADING_DET','TRANSFER_TO_TRADING_BOM','TRANSFER_TO_TRADING_JOBS','TRANSFER_TO_TRADING_SUB_DET')


		EXEC SP3S_VERIFY_TTMDATA_MERGE_CHANGES
		@cMemoId=@cMemoId,
		@nSpId=@nSpid


	END

	
	DECLARE @cMissingROW_ID VARCHAR(40)

	IF @BADDMODE=0
	BEGIN	

		SET @CSTEP=27

		SELECT TOP 1 @cMissingROW_ID=a.row_id FROM TRANSFER_TO_TRADING_SUB_DET A (NOLOCK) 
		LEFT JOIN 
		(SELECT row_id FROM TTM_TRANSFER_TO_TRADING_SUB_DET_UPLOAD B (NOLOCK) WHERE sp_id=@nSpId) b
		ON A.row_ID =B.row_ID WHERE A.MEMO_ID =@CMEMOID AND b.row_id IS NULL

		IF ISNULL(@cMissingROW_ID,'')<>''
		BEGIN		
			SET @CSTEP=30


			DELETE A FROM TRANSFER_TO_TRADING_SUB_DET A WITH (ROWLOCK) LEFT JOIN 
			(SELECT row_id FROM TTM_TRANSFER_TO_TRADING_SUB_DET_UPLOAD B (NOLOCK) WHERE sp_id=@nSpId) b
			ON A.row_ID =B.row_ID WHERE A.MEMO_ID =@CMEMOID AND b.row_id IS NULL
		END

		SET @CSTEP=32
	

		SELECT TOP 1 @cMissingROW_ID=a.ROW_ID FROM TRANSFER_TO_TRADING_JOBS A (NOLOCK) 
		LEFT JOIN 
		(SELECT ROW_ID FROM TTM_TRANSFER_TO_TRADING_JOBS_upload B (NOLOCK) WHERE sp_id=@nSpId) b
		ON A.ROW_ID =B.ROW_ID WHERE A.MEMO_ID =@CMEMOID AND b.ROW_ID IS NULL
				
		IF ISNULL(@cMissingROW_ID,'')<>''
		BEGIN		
			SET @CSTEP=35
		  
			DELETE A FROM TRANSFER_TO_TRADING_JOBS A WITH (ROWLOCK) LEFT JOIN 
			(SELECT ROW_ID FROM TTM_TRANSFER_TO_TRADING_JOBS_upload B (NOLOCK) WHERE sp_id=@nSpId) b
			ON A.ROW_ID =B.ROW_ID WHERE A.MEMO_ID =@CMEMOID AND b.ROW_ID IS NULL
		END

			SET @CSTEP=40
	

		SELECT TOP 1 @cMissingROW_ID=a.ROW_ID FROM TRANSFER_TO_TRADING_BOM A (NOLOCK) 
		LEFT JOIN 
		(SELECT ROW_ID FROM TTM_TRANSFER_TO_TRADING_BOM_upload B (NOLOCK) WHERE sp_id=@nSpId) b
		ON A.ROW_ID =B.ROW_ID WHERE A.MEMO_ID =@CMEMOID AND b.ROW_ID IS NULL
				
		IF ISNULL(@cMissingROW_ID,'')<>''
		BEGIN		
			SET @CSTEP=45
		  
			DELETE A FROM TRANSFER_TO_TRADING_BOM A WITH (ROWLOCK) LEFT JOIN 
			(SELECT ROW_ID FROM TTM_TRANSFER_TO_TRADING_BOM_upload B (NOLOCK) WHERE sp_id=@nSpId) b
			ON A.ROW_ID =B.ROW_ID WHERE A.MEMO_ID =@CMEMOID AND b.ROW_ID IS NULL
		END

		SET @CSTEP=50
	

		SELECT TOP 1 @cMissingROW_ID=a.ROW_ID FROM TRANSFER_TO_TRADING_DET A (NOLOCK) 
		LEFT JOIN 
		(SELECT ROW_ID FROM TTM_TRANSFER_TO_TRADING_DET_upload B (NOLOCK) WHERE sp_id=@nSpId) b
		ON A.ROW_ID =B.ROW_ID WHERE A.MEMO_ID =@CMEMOID AND b.ROW_ID IS NULL
				
		IF ISNULL(@cMissingROW_ID,'')<>''
		BEGIN		
			SET @CSTEP=55
		  
			DELETE A FROM TRANSFER_TO_TRADING_DET A WITH (ROWLOCK) LEFT JOIN 
			(SELECT ROW_ID FROM TTM_TRANSFER_TO_TRADING_DET_upload B (NOLOCK) WHERE sp_id=@nSpId) b
			ON A.ROW_ID =B.ROW_ID WHERE A.MEMO_ID =@CMEMOID AND b.ROW_ID IS NULL
		END




	END
	
LBLMERGE:

	

	SET @CFILTERCONDITION = 'B.MEMO_ID='''+@CMEMOID+''' AND B.SP_ID='''+@nSpId +''''
	
	
    SET @CTABLENAME='TRANSFER_TO_TRADING_MST'
	SET @CTMP_TABLENAME='TTM_TRANSFER_TO_TRADING_MST_UPLOAD'
	SET @CKEYFIELD='MEMO_ID'

	
	
	SET @CSTEP=70	 
	
	SELECT @cUpdatestr=updatestr FROM  savetran_updcols_updatestr (NOLOCK) WHERE sp_id=@nspid and tablename='TRANSFER_TO_TRADING_MST'
	SET @LUPDATEONLY = (CASE WHEN @BADDMODE=0 THEN 1 ELSE 0 END)	

	EXEC UPDATEMASTERXN_opt @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=@BADDMODE,@CFILTERCONDITION=@CFILTERCONDITION,@LUPDATEONLY=@LUPDATEONLY
							  ,@BALWAYSUPDATE=1,@lUpdateXns=1,@cUpdatestrPara=@cUpdatestr,@bThruUpdatestrPara=1  
							  
				  
							 							  
    SET @CTABLENAME='TRANSFER_TO_TRADING_DET'
	SET @CTMP_TABLENAME='TTM_TRANSFER_TO_TRADING_DET_UPLOAD'
	SET @CKEYFIELD='ROW_ID'

	
	SET @CSTEP=80
	SELECT @cMissingROW_ID='',@lUpdateonly=0
	IF @BADDMODE=0
	BEGIN
		SET @CSTEP=85
	

		SELECT TOP 1 @cMissingROW_ID=b.row_id FROM 
		(SELECT row_id  FROM TTM_TRANSFER_TO_TRADING_DET_UPLOAD (NOLOCK) WHERE sp_id=(LEFT(@nSPId,38)+@cLocId )) A
		RIGHT OUTER JOIN 
		(SELECT row_id FROM TTM_TRANSFER_TO_TRADING_DET_UPLOAD (NOLOCK) WHERE sp_id=@nSpId) b ON 
		a.row_id=b.row_id WHERE a.row_id IS NULL


		IF ISNULL(@cMissingROW_ID,'')='' 
			SET @lUpdateonly=1
	END

	SET @CSTEP=90
   

	SELECT @cUpdatestr=updatestr FROM  savetran_updcols_updatestr (NOLOCK) WHERE sp_id=@nspid and tablename='TRANSFER_TO_TRADING_DET'

	EXEC UPDATEMASTERXN_opt @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=@BADDMODE,@CFILTERCONDITION=@CFILTERCONDITION,@LUPDATEONLY=@lUpdateonly
							  ,@BALWAYSUPDATE=1,@lUpdateXns=@BADDMODE,@cUpdatestrPara=@cUpdatestr,@bThruUpdatestrPara=1 



						  							  
	SET @CTABLENAME='TRANSFER_TO_TRADING_BOM'
	SET @CTMP_TABLENAME='TTM_TRANSFER_TO_TRADING_BOM_UPLOAD'
	SET @CKEYFIELD='ROW_ID'

	
	SET @CSTEP=95
	SELECT @cMissingROW_ID='',@lUpdateonly=0
	IF @BADDMODE=0
	BEGIN
		SET @CSTEP=100
	

		SELECT TOP 1 @cMissingROW_ID=b.row_id FROM 
		(SELECT row_id  FROM TTM_TRANSFER_TO_TRADING_BOM_UPLOAD (NOLOCK) WHERE sp_id=(LEFT(@nSPId,38)+@cLocId )) A
		RIGHT OUTER JOIN 
		(SELECT row_id FROM TTM_TRANSFER_TO_TRADING_BOM_UPLOAD (NOLOCK) WHERE sp_id=@nSpId) b ON 
		a.row_id=b.row_id WHERE a.row_id IS NULL


		IF ISNULL(@cMissingROW_ID,'')='' 
			SET @lUpdateonly=1
	END

	
	SELECT @cUpdatestr=updatestr FROM  savetran_updcols_updatestr (NOLOCK) WHERE sp_id=@nspid and tablename='TRANSFER_TO_TRADING_BOM'

	EXEC UPDATEMASTERXN_opt @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=@BADDMODE,@CFILTERCONDITION=@CFILTERCONDITION,@LUPDATEONLY=@lUpdateonly
							  ,@BALWAYSUPDATE=1,@lUpdateXns=@BADDMODE,@cUpdatestrPara=@cUpdatestr,@bThruUpdatestrPara=1 


						  
    SET @CTABLENAME='TRANSFER_TO_TRADING_JOBS'
	SET @CTMP_TABLENAME='TTM_TRANSFER_TO_TRADING_JOBS_UPLOAD'
	SET @CKEYFIELD='ROW_ID'

	
	SET @CSTEP=110
	SELECT @cMissingROW_ID='',@lUpdateonly=0
	IF @BADDMODE=0
	BEGIN
		SET @CSTEP=120
	

		SELECT TOP 1 @cMissingROW_ID=b.row_id FROM 
		(SELECT row_id  FROM TTM_TRANSFER_TO_TRADING_JOBS_UPLOAD (NOLOCK) WHERE sp_id=(LEFT(@nSPId,38)+@cLocId )) A
		RIGHT OUTER JOIN 
		(SELECT row_id FROM TTM_TRANSFER_TO_TRADING_JOBS_UPLOAD (NOLOCK) WHERE sp_id=@nSpId) b ON 
		a.row_id=b.row_id WHERE a.row_id IS NULL


		IF ISNULL(@cMissingROW_ID,'')='' 
			SET @lUpdateonly=1
	END

	SELECT @cUpdatestr=updatestr FROM  savetran_updcols_updatestr (NOLOCK) WHERE sp_id=@nspid and tablename='TRANSFER_TO_TRADING_JOBS'

	EXEC UPDATEMASTERXN_opt @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=@BADDMODE,@CFILTERCONDITION=@CFILTERCONDITION,@LUPDATEONLY=@lUpdateonly
							  ,@BALWAYSUPDATE=1,@lUpdateXns=@BADDMODE,@cUpdatestrPara=@cUpdatestr,@bThruUpdatestrPara=1 


							  
							  
    SET @CTABLENAME='TRANSFER_TO_TRADING_SUB_DET'
	SET @CTMP_TABLENAME='TTM_TRANSFER_TO_TRADING_SUB_DET_MIRROR'
	SET @CKEYFIELD='ROW_ID'

	
	SET @CSTEP=110
	SELECT @cMissingROW_ID='',@lUpdateonly=0
	IF @BADDMODE=0
	BEGIN
		SET @CSTEP=120
	

		SELECT TOP 1 @cMissingROW_ID=b.row_id FROM 
		(SELECT row_id  FROM TTM_TRANSFER_TO_TRADING_SUB_DET_MIRROR (NOLOCK) WHERE sp_id=(LEFT(@nSPId,38)+@cLocId )) A
		RIGHT OUTER JOIN 
		(SELECT row_id FROM TTM_TRANSFER_TO_TRADING_SUB_DET_MIRROR (NOLOCK) WHERE sp_id=@nSpId) b ON 
		a.row_id=b.row_id WHERE a.row_id IS NULL


		IF ISNULL(@cMissingROW_ID,'')='' 
			SET @lUpdateonly=1
	END

	SELECT @cUpdatestr=updatestr FROM  savetran_updcols_updatestr (NOLOCK) WHERE sp_id=@nspid and tablename='TRANSFER_TO_TRADING_SUB_DET'

	EXEC UPDATEMASTERXN_opt @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=@BADDMODE,@CFILTERCONDITION=@CFILTERCONDITION,@LUPDATEONLY=@lUpdateonly
							  ,@BALWAYSUPDATE=1,@lUpdateXns=@BADDMODE,@cUpdatestrPara=@cUpdatestr,@bThruUpdatestrPara=1 


lblUpdatePmt:

	EXEC SP3S_MERGE_LOCPMT  
	@cTempTable='TTM_PMT01106_UPLOAD',  
	@cMemoIdCol='SP_ID',  
	@cMemoId =@nSpId


	SET @CSTEP=100  

		DECLARE @nSpIdCopy VARCHaR(50)

	SET @nSpIdCopy=LEFT(@nSPId,38)+@cLocId 

	EXEC SP3S_DELETEupload_TTMmerge_TABLES @nSpId

	IF @BADDMODE=0
	EXEC SP3S_DELETEupload_TTMmerge_TABLES @nSpIdCopy	
	  		


END TRY
BEGIN CATCH
	SET @CERRMSG='P:SP3S_SYNCH_UPLOADDATA_TTM_OPT, MEMO ID :'+@CMEMOID+' STEP:'+@CSTEP+', MESSAGE:'+ERROR_MESSAGE()
	GOTO EXIT_PROC
END CATCH

EXIT_PROC:

	
	IF @@TRANCOUNT>0
	BEGIN
		IF ISNULL(@CERRMSG,'')='' AND @BSERIESMISMATCHFOUND<>1
			COMMIT
		ELSE
			ROLLBACK
    END
	
END	
---END OF PROCEDURE - SP_SYNCH_MIRRORDATA_TTM_SINGLE
