CREATE PROCEDURE GETAPPLOGININFO
(
	@NMODE NUMERIC(1,0)=0,
	@CDBNAME VARCHAR(50),
	@CCOMPUTERNAME VARCHAR(500),
	@NUSERLOGINCNT NUMERIC(5) OUTPUT  
)
--WITH ENCRYPTION
AS
BEGIN
-- PARAMETERS : @NMODE - 1 FOR UPDATING LOGININFO,2 FOR GETTING COUNT OF USERS LOGGED IN;
--						@NMODE = 0 WILL DO BOTH PROCESSING AT ONCE
--				@CDBNAME - CURRENT DATABASE NAME
--				@CCOMPUTERNAME - WINDOWS USER LOGIN NAME WITH COMPUTER NAME STUFFED		 			
	
	DECLARE @CPARENTDBNAME VARCHAR(500),@CCMD NVARCHAR(4000)
	
	SET @NUSERLOGINCNT = 0	
	SELECT @CPARENTDBNAME = VALUE FROM CONFIG WHERE 
		   CONFIG_OPTION='PARENT_DATABASE'

	SET @CPARENTDBNAME = (CASE WHEN ISNULL(@CPARENTDBNAME,'')='' THEN '' ELSE @CPARENTDBNAME+'.DBO.' END)
	
	IF @NMODE IN (0,1)
	BEGIN
		SET @CCMD = 'IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME=''WIZAPPDBNAMES'') 
					 BEGIN
						IF NOT EXISTS (SELECT TOP 1 DB_NAME FROM WIZAPPDBNAMES)
							INSERT WIZAPPDBNAMES (DB_NAME) VALUES ('''+@CDBNAME+''')
					 END'
						 
		EXEC SP_EXECUTESQL @CCMD

		SET @CCMD ='IF EXISTS (SELECT * FROM '+@CPARENTDBNAME+'APPLOGININFO WHERE DB_NAME='''+@CDBNAME+'''
			 				 AND SPID=@@SPID)
			 			UPDATE '+@CPARENTDBNAME+'APPLOGININFO SET USERNAME ='''+@CCOMPUTERNAME+''',LAST_LOGIN=GETDATE() 
			 			WHERE DB_NAME='''+@CDBNAME+''' AND SPID=@@SPID 
					ELSE 
			 			INSERT '+@CPARENTDBNAME+'APPLOGININFO (DB_NAME,SPID,USERNAME,LAST_LOGIN) VALUES 
						('''+@CDBNAME+''',@@SPID,'''+@CCOMPUTERNAME+''',GETDATE())'
		
		EXEC SP_EXECUTESQL @CCMD
	END


	IF @NMODE IN (0,2)
	BEGIN
		SET @CCMD = 'IF EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME=''WIZAPPDBNAMES'') 
						 AND EXISTS (SELECT NAME FROM SYSOBJECTS WHERE NAME=''APPLOGININFO'') 

					 	SELECT @NUSERLOGINCNTOUTPUT=COUNT(DISTINCT ISNULL(USERNAME,'''')) 
					 	FROM MASTER.DBO.SYSPROCESSES A (NOLOCK) JOIN '+@CPARENTDBNAME+'
						APPLOGININFO B ON A.SPID=B.SPID AND DB_NAME(A.DBID)=B.DB_NAME WHERE DBID > 0 
					 	AND (PROGRAM_NAME='''' OR CHARINDEX(''VISUAL FOXPRO'',PROGRAM_NAME)>0 
							 OR CHARINDEX(''.NET SQLCLIENT'',PROGRAM_NAME)>0) AND DB_NAME(DBID) IN 
							(SELECT DB_NAME FROM '+@CPARENTDBNAME+'WIZAPPDBNAMES) 
					 ELSE 
						SET @NUSERLOGINCNTOUTPUT=0 '
		
		EXEC SP_EXECUTESQL @CCMD,N'@NUSERLOGINCNTOUTPUT NUMERIC(5,0) OUTPUT',@NUSERLOGINCNTOUTPUT=@NUSERLOGINCNT OUTPUT
		
	END	
END
