CREATE PROCEDURE SP3S_DELETEUPLOADTABLES_SLS
@nSpId VARCHAR(50)
AS
BEGIN
    DELETE FROM SLS_CMM01106_UPLOAD WITH (ROWLOCK)   WHERE SP_ID=@NSPId
    DELETE FROM SLS_CMD01106_UPLOAD WITH (ROWLOCK)   WHERE SP_ID=@NSPID
    DELETE FROM SLS_PAYMODE_XN_DET_UPLOAD WITH (ROWLOCK) WHERE SP_ID=@NSPID
	DELETE FROM SLS_COUPON_REDEMPTION_INFO_UPLOAD WITH (ROWLOCK) WHERE SP_ID=@NSPID
	DELETE FROM SLS_PACK_SLIP_Ref_UPLOAD WITH (ROWLOCK) WHERE SP_ID=@NSPID
	DELETE FROM SLS_DAILOGFILE_UPLOAD WITH (ROWLOCK) WHERE SP_ID=@NSPID
	DELETE FROM SLS_CMD_MANUALBILL_ERRORS_UPLOAD WITH (ROWLOCK) WHERE SP_ID=@NSPID	
	DELETE FROM sls_gst_taxinfo_calc WITH (ROWLOCK) WHERE sp_id=@nSpId
	DELETE FROM sls_gst_xns_hsn WITH (ROWLOCK) WHERE sp_id=@nSpId	
	DELETE FROM SAVETRAN_BARCODE_NETQTY WITH (ROWLOCK) WHERE sp_id=@nSpId	
	DELETE FROM SLS_cmd_cons_UPLOAD WITH (ROWLOCK) WHERE sp_id=@nSpId	
END


