create PROCEDURE SAVETRAN_MERGE_MIRROR_DOCPRT_DATA        --(LocId 3 digit change by Sanjay:05-11-2024)
(        
	 @CMEMOID VARCHAR(50),        
	 @DRECEIPTDT DATETIME,        
	 @CMEMONOPREFIX VARCHAR(10),
	 @CWIZAPPUSERCODE CHAR(7),
	 @CLOCID VARCHAR(4)='',	 
	 @CCNID VARCHAR(50) OUTPUT,
	 @BNEGSTOCKFOUND BIT OUTPUT,
	 @CERRMSG VARCHAR(MAX) OUTPUT ,
	 @DLOGINDT DATETIME='',
	 @BCALLEDFORSISLOC BIT=0 ,
	 @CCHI_ENTRY_REF_NO varchar(100)=''
	          
)         
AS       
BEGIN  
      
 /*
	  @BCALLEDFORSISLOC use transaction Open in parcel modules & Direct Git Recieve for sis Location
 */



 
 DECLARE @DTSQL NVARCHAR(MAX),@CSOURCEDB VARCHAR(200),@CTMP_TABLENAME VARCHAR(200)        
   ,@CJOINSTR VARCHAR(MAX),@CERRORMSG VARCHAR(MAX),@CTABLESUFFIX VARCHAR(100)        
   ,@CTABLENAME VARCHAR(200),@CERRMSGOUT VARCHAR(MAX),@CSTEP VARCHAR(20),@CKEYFIELD VARCHAR(100)        
   ,@CKEYFIELD1 VARCHAR(100),@CMERGEDB VARCHAR(50),@DCNMRECEIPTDT DATETIME      
    ,@CFINYEAR VARCHAR(10),@CN_NO VARCHAR(50),@RM_ID VARCHAR(50),@cErrPRODUCTCODE VARCHAR(50)      
   ,@TEMP_TABLE1 VARCHAR(20),@CCMD NVARCHAR(MAX),@CCURDEPTID varCHAR(4),@CHODEPTID VARCHAR(4)
   ,@BSOURCEPURLOC BIT,@BTARGETPURLOC BIT,@BGENERATEAUTOSERIES BIT,@CSOURCELOCID VARCHAR(4), @BHOLOC BIT
   ,@BMSTINSERTONLY BIT,@CPARTYDEPTID VARCHAR(5),@BCANCELLED BIT,@bBlankBillDetails BIT
   ,@BCHALLANRECEIVEDPREV BIT,@CTABLESSTR VARCHAR(MAX),@BGETCHALLANTHRUMIRROR BIT,@CTEMPCNDTABLE VARCHAR(500)
   ,@CFILTERCONDITION VARCHAR(1000),@CFILTERCONDITION1 VARCHAR(1000),@CFILTERCONDITION2 VARCHAR(1000),@CFILTERCONDITIONPARA VARCHAR(1000)
   ,@CCMDOUTPUT VARCHAR(40),@CASKPREFIX VARCHAR(10)
   ,@NTARGETLOCTYPE NUMERIC(1,0),@BSENDPURINFOLOC BIT,@CGSTCUTOFFDATE VARCHAR(12),@BGSTBILL BIT,@DRMDT DATETIME
   ,@CMEMOPREFIXPROC VARCHAR(25),@CSEACRCHRMID VARCHAR(50),@CRECEIVEDCNID VARCHAR(50),@CENABLEOPTIMIZEDSCHEMES BIT
   ,@NUPDATEMODENEW INT, @DCN_DT DATETIME
 BEGIN TRY       
    
    SET @CSTEP=10
	SET @bBlankBillDetails=0

	PRINT 'DOCPRT-1'
    
    IF @CLOCID=''    	 
      SELECT @CCURDEPTID = VALUE FROM CONFIG (NOLOCK) WHERE  CONFIG_OPTION='LOCATION_ID'
    ELSE 
       SET @CCURDEPTID=@CLOCID
       
    SELECT @CHODEPTID = VALUE FROM CONFIG (NOLOCK) WHERE  CONFIG_OPTION='HO_LOCATION_ID'

	IF ISNULL(@BCALLEDFORSISLOC,0)=0
	BEGIN TRAN

	if @DLOGINDT in('','1900-01-01')
    SELECT @DLOGINDT=LAST_UPDATE FROM NEW_APP_LOGIN_INFO WHERE SPID=@@SPID
	


	SET @CSOURCEDB=DB_NAME()+'.DBO.'        
	SET @CTABLESUFFIX=REPLACE(@CMEMOID,'-','_')        
	SET @CTMP_TABLENAME=@CSOURCEDB+'DOCPRT_RMM01106_MIRROR'

    SELECT TOP 1 @DRMDT=RM_DT,@CSOURCELOCID=location_code FROM DOCPRT_RMM01106_MIRROR B (NOLOCK)
    WHERE RM_ID=@CMEMOID

	IF @DLOGINDT IN('','1900-01-01')
    begin
	    SET @CERRMSG = 'Login Date can not Be blank'
		GOTO EXIT_PROC
	end
 	  
	    
	SELECT @CFILTERCONDITION1=' A.RM_ID='''+@CMEMOID+'''',
	  	   @CFILTERCONDITION2=' B.DOCPRT_MEMO_ID='''+@CMEMOID+''''
	  	  
	SET @CCMD=N'SELECT @CPARTYDEPTID=PARTY_DEPT_ID FROM '+@CTMP_TABLENAME+' A WHERE '+@CFILTERCONDITION1
	EXEC SP_EXECUTESQL @CCMD,N'@CPARTYDEPTID VARCHAR(5) OUTPUT',@CPARTYDEPTID OUTPUT
	
	declare @bServerLoc BIT
  SET @bServerLoc=0
  
  IF EXISTS(SELECT TOP 1'U' FROM location (NOLOCK) WHERE DEPT_ID=@CPARTYDEPTID AND server_loc=1)
  OR EXISTS(SELECT TOP 1'U' FROM location (NOLOCK) WHERE DEPT_ID=@CCURDEPTID AND server_loc=1)
		SET @bServerLoc=1

	IF @bServerLoc=0
    BEGIN
	  
		IF @CPARTYDEPTID<>@CCURDEPTID
		BEGIN
			SET @CERRMSG = 'THE CHALLAN NO.:'+RIGHT(@CMEMOID,10)+' BELONGS TO LOCATION ID :'+@CPARTYDEPTID+' OTHER THAN CURRENT LOCATION ID:'+@CCURDEPTID		
			GOTO EXIT_PROC
		END
		
	END
   ELSE 
      SET @CCURDEPTID=@CPARTYDEPTID
	
    SELECT TOP 1 @BSOURCEPURLOC=PUR_LOC FROM LOCATION (NOLOCK) WHERE DEPT_ID=@CSOURCELOCID
    SELECT TOP 1 @BTARGETPURLOC=PUR_LOC,@NTARGETLOCTYPE=LOC_TYPE,@BSENDPURINFOLOC=UPD_PURINFO
    FROM LOCATION (NOLOCK) WHERE DEPT_ID=@CCURDEPTID
  
    SET @BHOLOC=0
    IF @CCURDEPTID=@CHODEPTID
	  SET @BHOLOC=1

    SET @CSTEP = 15       
    SELECT TOP 1 @CSEACRCHRMID = RM_ID,@DCN_DT=CN_DT FROM CNM01106 (NOLOCK)  WHERE RM_ID =@CMEMOID  AND CANCELLED=0      

   
	SET @cStep = 16.4
	SELECT TOP 1 @cErrPRODUCTCODE=product_code from DOCPRT_rmd01106_mirror a (NOLOCK)
	JOIN DOCPRT_rmm01106_mirror b (NOLOCK) ON a.rm_id=b.rm_id
	WHERE a.rm_id=@cMemoId AND (bill_no='' or bill_dt='') AND memo_type<>2
	
	DECLARE @CALLOW_BLANK_BILLDETAILS VARCHAR(10)
	SELECT @CALLOW_BLANK_BILLDETAILS=VALUE  FROM CONFIG WHERE CONFIG_OPTION ='ALLOW_BLANK_BILLDETAILS'

	DECLARE @bDupEntryFound BIT
	SET @bDupEntryFound=0	
	IF ISNULL(@cErrProductCode,'')<>'' and ISNULL(@CALLOW_BLANK_BILLDETAILS,'')<>'1'
	BEGIN
		SELECT @cErrormsg='Blank Bill details not allowed'
			
		SELECT A.PRODUCT_CODE,0 QUANTITY_IN_STOCK,'Blank Bill details not allowed' AS ERRMSG
		FROM  DOCPRT_rmd01106_mirror a (NOLOCK) WHERE rm_id=@cMemoId AND (bill_no='' or bill_dt='')

		SET @bBlankBillDetails =1
		GOTO EXIT_PROC
	END	

	IF EXISTS (SELECT TOP 1 'U'  FROM CNM01106  WHERE RM_ID =@CMEMOID  AND CANCELLED=0 AND ISNULL(IRN_QR_CODE,'')<>''   )
	BEGIN
	     	SELECT @cErrormsg='IRN_QR_CODE has been Generated.You cannot Receive it.'
			GOTO EXIT_PROC
	END


	SET @cStep = 18
	SELECT row_id INTO #tmpDup from DOCPRT_rmd01106_mirror (NOLOCK) WHERE rm_id=@cMemoId 
	GROUP BY row_id HAVING count(*)>1
		
	IF EXISTS (SELECT TOP 1 * FROM #tmpDup)
	BEGIN
		SELECT @cErrormsg='Duplicate entries found in Challan .... Cannot Save'
		 
		SELECT A.PRODUCT_CODE,0 QUANTITY_IN_STOCK,@cErrormsg AS ERRMSG
		FROM  DOCPRT_rmd01106_mirror a (NOLOCK) JOIN #tmpDup b ON a.row_id=b.row_id

		SET @bDupEntryFound =1

		GOTO EXIT_PROC
	END	
	    
    PRINT 'DOCPRT-2'    
    SET @CSTEP = 25        
    SET @CMERGEDB=DB_NAME()+'.DBO.'      
    SET @CERRORMSG=''        
            
	
	PRINT 'DOCPRT-3'
	IF (@BSOURCEPURLOC=0 OR @BTARGETPURLOC=1 OR @BHOLOC=1 OR @bServerLoc=1) AND @CSOURCELOCID<>@CHODEPTID 
		SET @BMSTINSERTONLY = 1
    ELSE
		SET @BMSTINSERTONLY = 0
		
	PRINT 'DOCPRT-4'	    
    /*INM,IND,PAYMODE_XN_DET,PAYMODE_MST,PAYMODE_GRP_MST*/        
    SET @CSTEP = 30        
    --SET @CSOURCEDB=DB_NAME()   
     
    DECLARE @cTargetBinId varchar(100)

	UPDATE DOCPRT_RMM01106_MIRROR WITH (ROWLOCK)  SET BIN_ID=TARGET_BIN_ID WHERE RM_ID=@CMEMOID
	

	SELECT @cTargetBinId=target_bin_id FROM DOCPRT_RMM01106_MIRROR (NOLOCK) WHERE RM_ID=@CMEMOID

	SET @CSTEP=32
	UPDATE a WITH (ROWLOCK)  SET AC_CODE=(CASE WHEN SUBSTRING(b.loc_gst_no,3,10)=SUBSTRING(c.loc_gst_no,3,10) THEN  b.dept_ac_code
				      ELSE b.invoice_control_ac_code END) FROM DOCPRT_RMM01106_MIRROR a
	JOIN LOCATION B on b.dept_id=A.location_Code
	JOIN LOCATION c on c.dept_id=a.party_dept_id
	WHERE  RM_ID=@CMEMOID 

	SET @CSTEP=34
	
	IF ISNULL(@CSEACRCHRMID,'')=''
	UPDATE DOCPRT_RMM01106_MIRROR WITH (ROWLOCK)  SET USER_CODE=@CWIZAPPUSERCODE,EDT_USER_CODE='0000000' WHERE RM_ID=@CMEMOID
	ELSE
	UPDATE DOCPRT_RMM01106_MIRROR WITH (ROWLOCK)  SET  USER_CODE=@CWIZAPPUSERCODE,EDT_USER_CODE=@CWIZAPPUSERCODE WHERE RM_ID=@CMEMOID
	
	SELECT TOP 1  @CGSTCUTOFFDATE=VALUE FROM CONFIG WHERE CONFIG_OPTION='GST_CUT_OFF_DATE'
	IF ISNULL(@CGSTCUTOFFDATE,'')<>''
	BEGIN
		IF @DRMDT>=CONVERT(DATE,@CGSTCUTOFFDATE)
			SET @BGSTBILL=1

	END
	
		--CHANGE BY BAIJNATH SET HSN CODE TEN TIME ZERO WHEN IT IS BLANK -- 
		UPDATE DOCPRT_RMD01106_MIRROR WITH (ROWLOCK)  SET HSN_CODE='0000000000' WHERE RM_ID=@CMEMOID AND ISNULL(HSN_CODE,'')=''
		UPDATE DOCPRT_ARTICLE_MIRROR WITH (ROWLOCK)  SET HSN_CODE='0000000000' WHERE DOCPRT_MEMO_ID=@CMEMOID AND ISNULL(HSN_CODE,'')=''
		UPDATE DOCPRT_RMM01106_MIRROR WITH (ROWLOCK)  SET PARTY_STATE_CODE='00' WHERE RM_ID=@CMEMOID AND ISNULL(PARTY_STATE_CODE,'')=''
		UPDATE DOCPRT_RMM01106_MIRROR WITH (ROWLOCK)  SET FREIGHT_HSN_CODE='0000000000' WHERE RM_ID=@CMEMOID AND ISNULL(FREIGHT_HSN_CODE,'')=''
		UPDATE DOCPRT_RMM01106_MIRROR WITH (ROWLOCK)  SET OTHER_CHARGES_HSN_CODE='0000000000' WHERE RM_ID=@CMEMOID AND ISNULL(OTHER_CHARGES_HSN_CODE,'')=''
		UPDATE DOCPRT_SKU_MIRROR WITH (ROWLOCK)  SET HSN_CODE='0000000000' WHERE DOCPRT_MEMO_ID=@CMEMOID AND ISNULL(HSN_CODE,'')=''


		---Have to do this in special case of Octave client issue Where duplciate bar codes were there isn source challans
		--- and when we try to insert this in target su even with distinct last_update columns comes different for same bar code
		--- application is changing this last_update  before putting into docprt_sku_mirror table (Date:15-04-2021)
		UPDATE DOCPRT_SKU_MIRROR WITH (ROWLOCK)  SET last_update=getdate() WHERE DOCPRT_MEMO_ID=@CMEMOID
		UPDATE DOCPRT_PARCEL_MST_MIRROR WITH (ROWLOCK)  SET USER_CODE ='0000000' WHERE DOCPRT_MEMO_ID=@CMEMOID

	IF(@BSENDPURINFOLOC=0) OR @NTARGETLOCTYPE=2
	BEGIN
		SET @CSTEP=36
		UPDATE DOCPRT_SKU_MIRROR WITH (ROWLOCK)  SET PURCHASE_PRICE=0,AC_CODE='0000000000' WHERE DOCPRT_MEMO_ID=@CMEMOID
	END

	SET @CSTEP=38
	UPDATE DOCPRT_FORM_MIRROR WITH (ROWLOCK) 
	SET PURCHASE_AC_CODE='0000000000',SALE_AC_CODE='0000000000',
	TAX_AC_CODE='0000000000',
	PUR_RETURN_AC_CODE='0000000000',
	SALE_RETURN_AC_CODE='0000000000',
	EXCISE_DUTY_AC_CODE='0000000000',
	EXCISE_EDU_CESS_AC_CODE='0000000000' ,
	EXCISE_HEDU_CESS_AC_CODE='0000000000'
	WHERE DOCPRT_MEMO_ID=@CMEMOID

	UPDATE DOCPRT_ANGM_MIRROR WITH (ROWLOCK)  SET AC_CODE='0000000000' WHERE DOCPRT_MEMO_ID=@CMEMOID
	
	IF @NTARGETLOCTYPE=2
	BEGIN
		SET @CSTEP=40
		UPDATE DOCPRT_STATE_MIRROR WITH (ROWLOCK)  SET REGION_CODE='0000000' WHERE DOCPRT_MEMO_ID=@CMEMOID
	END    

    SET @CSTEP=45
	UPDATE B SET PURCHASE_AC_CODE=A.PURCHASE_AC_CODE,SALE_AC_CODE=A.SALE_AC_CODE,
	TAX_AC_CODE=A.TAX_AC_CODE,PUR_RETURN_AC_CODE=A.PUR_RETURN_AC_CODE,
	SALE_RETURN_AC_CODE=A.SALE_RETURN_AC_CODE,EXCISE_DUTY_AC_CODE=A.EXCISE_DUTY_AC_CODE,
	EXCISE_EDU_CESS_AC_CODE=A.EXCISE_EDU_CESS_AC_CODE,EXCISE_HEDU_CESS_AC_CODE=A.EXCISE_HEDU_CESS_AC_CODE
	FROM FORM A (NOLOCK) JOIN DOCPRT_FORM_MIRROR B WITH (ROWLOCK) ON A.FORM_ID=B.FORM_ID 
	WHERE B.DOCPRT_MEMO_ID=@CMEMOID


	EXEC SP3S_REMOVE_MIRROR_DULICATE_MSTERS @CMEMOID,0,'DOCPRT'
    
    SET @CSTEP = 50        
    SET @CTABLENAME='FORM'        
    SET @CTMP_TABLENAME='DOCPRT_'+@CTABLENAME+'_MIRROR'        
    SET @CKEYFIELD='FORM_ID'        

    --SELECT @CSOURCEDB AS CSOURCEDB,@CTMP_TABLENAME AS CSOURCETABLE,@CMERGEDB AS CDESTDB,
			 --@CTABLENAME AS CDESTTABLE, @CKEYFIELD AS CKEYFIELD1         
    EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
         ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''        
         ,@LINSERTONLY=1,@CJOINSTR='',@LUPDATEONLY=0        
         ,@BALWAYSUPDATE=1,@CFILTERCONDITION=@CFILTERCONDITION2        
                 
    SET @CSTEP = 60        
    SET @CTABLENAME='STATE'        
    SET @CTMP_TABLENAME='DOCPRT_'+@CTABLENAME+'_MIRROR'        
    SET @CKEYFIELD='STATE_CODE'        
    
    EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
         ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''        
         ,@LINSERTONLY=@BMSTINSERTONLY,@CJOINSTR='',@LUPDATEONLY=0        
         ,@BALWAYSUPDATE=1,@CFILTERCONDITION=@CFILTERCONDITION2        
                    
    SET @CSTEP = 70        
    SET @CTABLENAME='CITY'        
    SET @CTMP_TABLENAME='DOCPRT_'+@CTABLENAME+'_MIRROR'        
    SET @CKEYFIELD='CITY_CODE'        
            
    EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
         ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''        
         ,@LINSERTONLY=@BMSTINSERTONLY,@CJOINSTR='',@LUPDATEONLY=0        
         ,@BALWAYSUPDATE=1,@CFILTERCONDITION=@CFILTERCONDITION2       
            
	SET @CSTEP = 80       
    SET @CTABLENAME='AREA'        
    SET @CTMP_TABLENAME='DOCPRT_'+@CTABLENAME+'_MIRROR'        
    SET @CKEYFIELD='AREA_CODE'        
    
    EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
         ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''        
         ,@LINSERTONLY=@BMSTINSERTONLY,@CJOINSTR='',@LUPDATEONLY=0        
         ,@BALWAYSUPDATE=1,@CFILTERCONDITION=@CFILTERCONDITION2       

         
    SET @CSTEP = 90       
    SET @CTABLENAME='HD01106'        
    SET @CTMP_TABLENAME='DOCPRT_'+@CTABLENAME+'_MIRROR'        
    SET @CKEYFIELD='HEAD_CODE'        

    EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
         ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''        
         ,@LINSERTONLY=@BMSTINSERTONLY,@CJOINSTR='',@LUPDATEONLY=0        
         ,@BALWAYSUPDATE=1,@CFILTERCONDITION=@CFILTERCONDITION2  
     
	 


    SET @CSTEP = 100       
    SET @CTABLENAME='LM01106'        
    SET @CTMP_TABLENAME='DOCPRT_'+@CTABLENAME+'_MIRROR'        
    SET @CKEYFIELD='AC_CODE' 
	
	DECLARE @CWHERE VARCHAR(200)
	SET @CWHERE=' AND A.DOCPRT_MEMO_ID='''+@CMEMOID+''''

	EXEC SP3S_INACTIVE_MASTERS @CTEMPTABLE=@CTMP_TABLENAME,@CTABLENAME=@CTABLENAME,@CCOLNAME='AC_NAME',@CCOLKEYNAME=@CKEYFIELD,@CWHERE=@CWHERE

    EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
         ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''        
         ,@LINSERTONLY=@BMSTINSERTONLY,@CJOINSTR='',@LUPDATEONLY=0        
         ,@BALWAYSUPDATE=1,@CFILTERCONDITION=@CFILTERCONDITION2            

    SET @CSTEP = 110
    SET @CTABLENAME='LMP01106'        
    SET @CTMP_TABLENAME='DOCPRT_'+@CTABLENAME+'_MIRROR'        
    SET @CKEYFIELD='AC_CODE'        
           
    PRINT @DTSQL        
    EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
         ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''        
         ,@LINSERTONLY=@BMSTINSERTONLY,@CJOINSTR='',@LUPDATEONLY=0        
         ,@BALWAYSUPDATE=1,@CFILTERCONDITION=@CFILTERCONDITION2 
    
    SET @CSTEP = 120     

	UPDATE DOCPRT_SECTIONM_MIRROR SET ITEM_TYPE=1 WHERE DOCPRT_MEMO_ID=@CMEMOID AND ISNULL(ITEM_TYPE,0)=0 
    
    SET @CTABLENAME='SECTIONM'
	SET @CTMP_TABLENAME='DOCPRT_'+@CTABLENAME+'_MIRROR'
	SET @CKEYFIELD='SECTION_CODE'

	EXEC SP3S_INACTIVE_MASTERS @CTEMPTABLE=@CTMP_TABLENAME,@CTABLENAME=@CTABLENAME,@CCOLNAME='SECTION_NAME',@CCOLKEYNAME=@CKEYFIELD,@CWHERE=@CWHERE
	
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
         ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''        
         ,@LINSERTONLY=@BMSTINSERTONLY,@CJOINSTR='',@LUPDATEONLY=0        
         ,@BALWAYSUPDATE=1,@CFILTERCONDITION=@CFILTERCONDITION2	
         
    SET @CSTEP=130
    
	SET @CTABLENAME='SECTIOND'
	SET @CTMP_TABLENAME='DOCPRT_'+@CTABLENAME+'_MIRROR'
	SET @CKEYFIELD='SUB_SECTION_CODE'

	EXEC SP3S_INACTIVE_MASTERS @CTEMPTABLE=@CTMP_TABLENAME,@CTABLENAME=@CTABLENAME,@CCOLNAME='SUB_SECTION_NAME',@CCOLKEYNAME=@CKEYFIELD,@CWHERE=@CWHERE

	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
         ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''        
         ,@LINSERTONLY=@BMSTINSERTONLY,@CJOINSTR='',@LUPDATEONLY=0        
         ,@BALWAYSUPDATE=1,@CFILTERCONDITION=@CFILTERCONDITION2   
    
    SET @CSTEP=140
	SET @CTABLENAME='PARA1'
	SET @CTMP_TABLENAME='DOCPRT_'+@CTABLENAME+'_MIRROR'
	SET @CKEYFIELD='PARA1_CODE'

	EXEC SP3S_INACTIVE_MASTERS @CTEMPTABLE=@CTMP_TABLENAME,@CTABLENAME=@CTABLENAME,@CCOLNAME='PARA1_NAME',@CCOLKEYNAME=@CKEYFIELD,@CWHERE=@CWHERE

	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
         ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''        
         ,@LINSERTONLY=@BMSTINSERTONLY,@CJOINSTR='',@LUPDATEONLY=0        
         ,@BALWAYSUPDATE=1,@CFILTERCONDITION=@CFILTERCONDITION2
              
    SET @CSTEP=150
	SET @CTABLENAME='PARA2'
	SET @CTMP_TABLENAME='DOCPRT_'+@CTABLENAME+'_MIRROR'
	SET @CKEYFIELD='PARA2_CODE'

	EXEC SP3S_INACTIVE_MASTERS @CTEMPTABLE=@CTMP_TABLENAME,@CTABLENAME=@CTABLENAME,@CCOLNAME='PARA2_NAME',@CCOLKEYNAME=@CKEYFIELD,@CWHERE=@CWHERE

	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
         ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''        
         ,@LINSERTONLY=@BMSTINSERTONLY,@CJOINSTR='',@LUPDATEONLY=0        
         ,@BALWAYSUPDATE=1,@CFILTERCONDITION=@CFILTERCONDITION2
       
    SET @CSTEP=160
	SET @CTABLENAME='PARA3'
	SET @CTMP_TABLENAME='DOCPRT_'+@CTABLENAME+'_MIRROR'
	SET @CKEYFIELD='PARA3_CODE'

	EXEC SP3S_INACTIVE_MASTERS @CTEMPTABLE=@CTMP_TABLENAME,@CTABLENAME=@CTABLENAME,@CCOLNAME='PARA3_NAME',@CCOLKEYNAME=@CKEYFIELD,@CWHERE=@CWHERE

	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
         ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''        
         ,@LINSERTONLY=@BMSTINSERTONLY,@CJOINSTR='',@LUPDATEONLY=0        
         ,@BALWAYSUPDATE=1,@CFILTERCONDITION=@CFILTERCONDITION2
         
    SET @CSTEP=170
	SET @CTABLENAME='PARA4'
	SET @CTMP_TABLENAME='DOCPRT_'+@CTABLENAME+'_MIRROR'
	SET @CKEYFIELD='PARA4_CODE'

	EXEC SP3S_INACTIVE_MASTERS @CTEMPTABLE=@CTMP_TABLENAME,@CTABLENAME=@CTABLENAME,@CCOLNAME='PARA4_NAME',@CCOLKEYNAME=@CKEYFIELD,@CWHERE=@CWHERE


	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
         ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''        
         ,@LINSERTONLY=@BMSTINSERTONLY,@CJOINSTR='',@LUPDATEONLY=0        
         ,@BALWAYSUPDATE=1,@CFILTERCONDITION=@CFILTERCONDITION2
         
    SET @CSTEP=180
	SET @CTABLENAME='PARA5'
	SET @CTMP_TABLENAME='DOCPRT_'+@CTABLENAME+'_MIRROR'
	SET @CKEYFIELD='PARA5_CODE'

	EXEC SP3S_INACTIVE_MASTERS @CTEMPTABLE=@CTMP_TABLENAME,@CTABLENAME=@CTABLENAME,@CCOLNAME='PARA5_NAME',@CCOLKEYNAME=@CKEYFIELD,@CWHERE=@CWHERE

	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
         ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''        
         ,@LINSERTONLY=@BMSTINSERTONLY,@CJOINSTR='',@LUPDATEONLY=0        
         ,@BALWAYSUPDATE=1,@CFILTERCONDITION=@CFILTERCONDITION2
   
    SET @CSTEP=190
	SET @CTABLENAME='PARA6'
	SET @CTMP_TABLENAME='DOCPRT_'+@CTABLENAME+'_MIRROR'
	SET @CKEYFIELD='PARA6_CODE'
	
	EXEC SP3S_INACTIVE_MASTERS @CTEMPTABLE=@CTMP_TABLENAME,@CTABLENAME=@CTABLENAME,@CCOLNAME='PARA6_NAME',@CCOLKEYNAME=@CKEYFIELD,@CWHERE=@CWHERE

	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
         ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''        
         ,@LINSERTONLY=@BMSTINSERTONLY,@CJOINSTR='',@LUPDATEONLY=0        
         ,@BALWAYSUPDATE=1,@CFILTERCONDITION=@CFILTERCONDITION2 
    
    SET @CSTEP=200
	SET @CTABLENAME='ARTICLE'
	SET @CTMP_TABLENAME='DOCPRT_'+@CTABLENAME+'_MIRROR'
	SET @CKEYFIELD='ARTICLE_CODE'

	EXEC SP3S_INACTIVE_MASTERS @CTEMPTABLE=@CTMP_TABLENAME,@CTABLENAME=@CTABLENAME,@CCOLNAME='ARTICLE_NO',@CCOLKEYNAME=@CKEYFIELD,@CWHERE=@CWHERE

	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
         ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''        
         ,@LINSERTONLY=@BMSTINSERTONLY,@CJOINSTR='',@LUPDATEONLY=0        
         ,@BALWAYSUPDATE=1,@CFILTERCONDITION=@CFILTERCONDITION2

		IF EXISTS (SELECT TOP 1 'U' FROM DOCPRT_HSN_MST_MIRROR A (NOLOCK)
		LEFT JOIN HSN_MST B (NOLOCK) ON A.HSN_CODE =B.HSN_CODE WHERE B.HSN_CODE IS NULL AND A.DOCPRT_MEMO_ID =@CMEMOID )
		begin
			--hsn changes--
			  SET @CSTEP=172
			 SET @CTABLENAME='HSN_MST'
			SET @CTMP_TABLENAME='DOCPRT_'+@CTABLENAME+'_MIRROR'
			SET @CKEYFIELD='HSN_CODE'
			EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
			  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''        
			  ,@LINSERTONLY=1,@CJOINSTR='',@LUPDATEONLY=0        
			  ,@BALWAYSUPDATE=1,@CFILTERCONDITION=@CFILTERCONDITION2      
		  
        end 

    SET @CSTEP = 240    
    SET @CTABLENAME='SKU'        
    SET @CTMP_TABLENAME='DOCPRT_'+@CTABLENAME+'_MIRROR'        
    SET @CKEYFIELD='PRODUCT_CODE'        
           
    EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
         ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''        
         ,@LINSERTONLY=@BMSTINSERTONLY,@CJOINSTR='',@LUPDATEONLY=0        
         ,@BALWAYSUPDATE=1,@CFILTERCONDITION=@CFILTERCONDITION2  

    --in case of offline location first time return barcode without batch insert in sku
	   
	   if @CCURDEPTID<>@CHODEPTID
	   begin
	        		
			;WITH CTE AS
			(
			SELECT *,
			PRODUCT_CODE_WO_BATCH= LEFT(A.PRODUCT_CODE, ISNULL(NULLIF(CHARINDEX ('@',A.PRODUCT_CODE)-1,-1),LEN(A.PRODUCT_CODE ))),
			SR=ROW_NUMBER() OVER (PARTITION BY LEFT(A.PRODUCT_CODE, ISNULL(NULLIF(CHARINDEX ('@',A.PRODUCT_CODE)-1,-1),LEN(A.PRODUCT_CODE )))
			ORDER BY LEFT(A.PRODUCT_CODE, ISNULL(NULLIF(CHARINDEX ('@',A.PRODUCT_CODE)-1,-1),LEN(A.PRODUCT_CODE ))))
			FROM DOCPRT_SKU_MIRROR A (NOLOCK)
			WHERE CHARINDEX ('@',PRODUCT_CODE)>0
			AND A.DOCPRT_MEMO_ID=@CMEMOID
			)

			SELECT A.* INTO #TMPSKU FROM CTE A
			LEFT JOIN SKU_NAMES B (NOLOCK ) ON A.PRODUCT_CODE_WO_BATCH =B.PRODUCT_CODE 
			WHERE B.PRODUCT_CODE IS NULL AND A.SR=1

			IF EXISTS (SELECT TOP 1'U' FROM #TMPSKU)
			BEGIN

			    DECLARE @CCOLNAME VARCHAR(MAX)
				UPDATE #TMPSKU SET PRODUCT_CODE =PRODUCT_CODE_WO_BATCH
			    SELECT  @CCOLNAME=INSERTSTR FROM MIRRORXNSINFO WHERE TABLENAME ='SKU'

				SET @DTSQL=N' INSERt INTO SKU ('+@CCOLNAME+')
							  SELECT '+@CCOLNAME+' FROM #TMPSKU '

                PRINT @DTSQL
				EXEC SP_EXECUTESQL @DTSQL

			end

	   end
	  
	    
	--


    SET @CSTEP = 250    
    SET @CTABLENAME='SKU_OH'        
    SET @CTMP_TABLENAME='DOCPRT_'+@CTABLENAME+'_MIRROR'        
    SET @CKEYFIELD='PRODUCT_CODE'        
    SET @CSTEP= 190        
    EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
         ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''        
         ,@LINSERTONLY=@BMSTINSERTONLY,@CJOINSTR='',@LUPDATEONLY=0        
         ,@BALWAYSUPDATE=1,@CFILTERCONDITION=@CFILTERCONDITION2 
                  
    SET @CSTEP = 260       
    SET @CTABLENAME='RMM01106'        
    SET @CTMP_TABLENAME='DOCPRT_'+@CTABLENAME+'_MIRROR'        
    SET @DTSQL=N'SELECT @cFinYear=''01''+ DBO.FN_GETFINYEAR(CASE WHEN '''+CONVERT(VARCHAR,@DRECEIPTDT,110)+''' 
	not in(''01-01-1900'','''') THEN  '''+CONVERT(VARCHAR,@DRECEIPTDT,110)+''' ELSE '''+CONVERT(VARCHAR,@dlogindt,110)+''' END ) ,
	@CPARTYDEPTID = location_code 
				 FROM  '+@CSOURCEDB+@CTMP_TABLENAME+' WHERE RM_ID = '''+@CMEMOID+''''       
    PRINT @DTSQL      
    EXEC SP_EXECUTESQL @DTSQL , N'@CFINYEAR VARCHAR(5) OUTPUT,@CPARTYDEPTID VARCHAR(5) OUTPUT',@CFINYEAR OUTPUT ,@CPARTYDEPTID OUTPUT       
    
	SET @CSTEP = 270  
	
	     
	
	IF  ISNULL(@CSEACRCHRMID,'')=''
	BEGIN
		REGENRATE:    
		
		SET @CSTEP = 275        
		
		EXEC SAVETRAN_GETMEMOPREFIX
		@CXNTYPE='GRP_WSR',
		@CUSERCODE=@CWIZAPPUSERCODE,
		@CFINYEAR=@CFINYEAR,
		@CSOURCELOCID=@CCURDEPTID,
		@CTARGETLOCID='',
		@CMANUALPREFIX=@CMEMONOPREFIX,
		@CMEMOID=@CMEMOID,
		@CMEMOPREFIX=@CMEMOPREFIXPROC OUTPUT,
		@CERRORMSG=@CERRORMSG OUTPUT
		
		IF ISNULL(@CERRORMSG,'')<>''
			GOTO EXIT_PROC

			

		
		SET @CSTEP = 280        
		
		DECLARE @NMEMONOLEN NUMERIC(10,0)
		SET @NMEMONOLEN=LEN(@CMEMOPREFIXPROC)+6
		
		
		
	 	EXEC GETNEXTKEY 'CNM01106', 'CN_NO', @NMEMONOLEN, @CMEMOPREFIXPROC, 1,@CFINYEAR,0, @CN_NO  OUTPUT      
		
		PRINT @CN_NO      
		IF @CN_NO IS NULL          
		BEGIN      
		    SET @CERRORMSG = 'STEP- ' + LTRIM(STR(@CSTEP)) + ' ERROR CREATING NEXT CN_NO....'           
			GOTO EXIT_PROC              
		END
		
		IF EXISTS (SELECT TOP 1 * FROM CNM01106 WHERE CN_NO = @CN_NO AND FIN_YEAR = @CFINYEAR )
			GOTO REGENRATE 
			
	    SET @CCNID = @CCURDEPTID + right(@CFINYEAR,2)+ ISNULL(REPLICATE('0', (22-LEN(@CCURDEPTID + RIGHT(@CFINYEAR,2)))-LEN(LTRIM(RTRIM(@CN_NO)))),'') + LTRIM(RTRIM(@CN_NO)) 
		
		SET @CSTEP = 290        
		      
		IF @CCNID  IS NULL            
		BEGIN          
			SET @CERRORMSG = 'STEP- ' + LTRIM(STR(@CSTEP)) + ' ERROR CREATING NEXT CN_ID.'          
			GOTO EXIT_PROC          
		END 

		IF EXISTS (SELECT TOP 1 * FROM CNM01106 (NOLOCK) WHERE CN_ID = @cCnId)
			GOTO REGENRATE 		
    END
    ELSE
    BEGIN
		SET @CSTEP = 295        
		SELECT TOP 1 @CCNID= CN_ID,@CN_NO= CN_NO FROM CNM01106 WHERE RM_ID = @CMEMOID AND CANCELLED=0

		SELECT TOP 1 @CRECEIVEDCNID = CN_ID FROM CNM01106 A WHERE A.RM_ID =@CMEMOID AND RECEIPT_DT<>'' AND CANCELLED=0
        
		IF ISNULL(@DRECEIPTDT,'')<>''
		UPDATE CNM01106 WITH (ROWLOCK) SET RECEIPT_DT=@DRECEIPTDT WHERE RM_ID = @CMEMOID --AND RECEIPT_DT=''	
		
		UPDATE CNM01106 WITH (ROWLOCK) SET CN_DT=@DRECEIPTDT WHERE RM_ID = @CMEMOID AND cn_dt=''		
    END            
    
      PRINT 'CHECK UPDATE'      
      PRINT  @CN_NO      
      PRINT @CCNID
      
      
      SET @CSTEP = 310
      
    
      SET @DTSQL = N'UPDATE A SET CN_NO = '''+@CN_NO+''',FIN_YEAR='''+@CFINYEAR+''' FROM DOCPRT_RMM01106_MIRROR A WITH (ROWLOCK) 
					 WHERE '+@CFILTERCONDITION1
      PRINT @DTSQL
      EXEC SP_EXECUTESQL @DTSQL 
      
      
      
      IF ISNULL(@DRECEIPTDT,'')=''
      SET @DCN_DT=@DLOGINDT
      ELSE 
      SET @DCN_DT =CASE WHEN @DCN_DT<>'' THEN @DCN_DT ELSE @DRECEIPTDT END
        
      SET @CSTEP = 320
  	  DELETE FROM wsr_cnd01106_upload WITH (ROWLOCK) WHERE cn_id=@cCnId
	  DELETE FROM wsr_cnm01106_upload WITH (ROWLOCK) WHERE cn_id=@cCnId



	  INSERT wsr_cnm01106_upload (sp_id,ac_code,entry_mode,rm_id,challan_source_location_code, PARTY_DEPT_ID,cn_id,cn_dt,cn_no,bin_id,CHECKED_BY,company_code,cn_type,dt_code,BILLED_FROM_DEPT_ID,CN_TIME,
	  manual_inv_no,manual_dn_no,manual_dn_dt,receipt_dt,memo_type,PARTY_STATE_CODE,freight_hsn_code,other_charges_hsn_code,fin_year ,mode,remarks,subtotal,discount_percentage ,discount_amount ,total_amount,TOTAL_QUANTITY,
	  TOTAL_QUANTITY_STR ,Total_Gst_Amount,SOURCE_BIN_ID,Total_Gst_Cess_Amount,freight,FREIGHT_TAXABLE_VALUE,freight_cgst_amount,freight_sgst_amount,freight_igst_amount ,freight_gst_percentage,
	  other_charges,other_charges_TAXABLE_VALUE,other_charges_cgst_amount,other_charges_sgst_amount,other_charges_igst_amount,other_charges_gst_percentage,round_off ,chi_entry_ref_no,user_code,
      shipping_address3,shipping_area_code,shipping_pin,shipping_area_name,shipping_city_name,shipping_state_name,shipping_address,SHIPPING_AC_CODE,SHIPPING_MODE,
	  docprt_parcel_memo_id,ParcelDetails,location_code)

	  SELECT rm_id as sp_id,ac_code,1 as entry_mode,rm_id,@CPARTYDEPTID challan_source_location_code, @CPARTYDEPTID as party_dept_id, @CCNID AS CN_ID,@DCN_DT as cn_dt,@Cn_No as cn_no,a.target_bin_id as bin_id,'' as checked_by,
	  '01' company_code,dn_type as cn_type,'0000000' dt_code,@cCurDeptId BILLED_FROM_DEPT_ID,getdate() cn_time,A.RefNo AS MANUAL_INV_NO,A.RM_NO AS MANUAL_DN_NO,--as per pankaj ji A.RefNo (manual Inv no ) 20012023
	  A.RM_DT AS MANUAL_DN_DT,@DRECEIPTDT as receipt_dt,memo_type,PARTY_STATE_CODE,freight_hsn_code,other_charges_hsn_code,
	   @CFINYEAR fin_year ,a.mode ,a.REMARKS
	  ,subtotal,discount_percentage ,discount_amount ,total_amount,TOTAL_QUANTITY,TOTAL_QUANTITY_STR ,Total_Gst_Amount,a.TARGET_BIN_ID ,Total_Gst_Cess_Amount ,

	  freight,FREIGHT_TAXABLE_VALUE,freight_cgst_amount,freight_sgst_amount,freight_igst_amount ,freight_gst_percentage,
	  other_charges,other_charges_TAXABLE_VALUE,other_charges_cgst_amount,other_charges_sgst_amount,other_charges_igst_amount,other_charges_gst_percentage,round_off,
	  @CCHI_ENTRY_REF_NO as CHI_ENTRY_REF_NO,a.user_code ,
	  shipping_address3,shipping_area_code,shipping_pin,shipping_area_name,shipping_city_name,shipping_state_name,shipping_address,SHIPPING_AC_CODE,SHIPPING_MODE,
	  docprt_parcel_memo_id,a.ParcelDetails,@cCurDeptId location_code
	  
	  FROM DOCPRT_RMM01106_MIRROR A (NOLOCK) WHERE rm_id=@CMEMOID
     
	 SET @CSTEP = 322 
 
    UPDATE A SET A.RECEIPT_DT=ISNULL(B.RECEIPT_DT,''),FIN_YEAR= B.FIN_YEAR FROM wsr_cnm01106_upload A WITH (ROWLOCK) 
	JOIN CNM01106 B (NOLOCK) ON A.CN_ID=B.CN_ID 
	WHERE a.cn_id=@cCnId AND B.RECEIPT_DT<>''
	
	IF  ISNULL(@CRECEIVEDCNID,'')<>''
	  SET @NUPDATEMODENEW=2
	
	IF  ISNULL(@CRECEIVEDCNID,'')=''
	  SET @NUPDATEMODENEW=1

	SET @cStep=330
	EXEC SP3S_upd_qty_lastupdate
	@nUpdateMode=@NUPDATEMODENEW,
	@cXnType='WSR',
	@cMemoId=@cCnId,
	@nSpId=@@spid,
	@cMasterTable='CNM01106',
	@cMemoIdCol='cn_id',
	@cXnDtCol='receipt_dt',
	@CERRORMSG=@CERRORMSG OUTPUT
	
	IF ISNULL(@cErrormsg,'')<>''
		GOTO EXIT_PROC	

    SET @CSTEP = 338
    
    
    IF  ISNULL(@CRECEIVEDCNID,'')<>''
    BEGIN
		 SET @CSTEP = 345
		 EXEC SP3S_UPDATEPMT_PRTCHI
			   @CMemoId	=  @cMemoId
			  , @bREvertFlag  = 1        
			  , @cErrormsg = @cErrmsg OUTPUT
			  , @BNEGSTOCKFOUND    = @BNEGSTOCKFOUND OUTPUT

		IF ISNULL(@cErrmsg,'')<>''	  
		BEGIN
		    GOTO EXIT_PROC
		END		 	  
    END
        -----CHANGE BY BAIJNATH -----
    
        UPDATE S SET S.AC_CODE ='0000000000'
		FROM DOCPRT_ANGM_MIRROR S WITH (ROWLOCK)
		LEFT OUTER JOIN LM01106  T WITH (NOLOCK)
		ON T.AC_CODE =S.AC_CODE
		WHERE S.DOCPRT_MEMO_ID =@CMEMOID AND T.AC_CODE IS NULL
        
		SET @CSTEP=1001
		SET @CTABLENAME='ANGM'
		SET @CTMP_TABLENAME='DOCPRT_'+@CTABLENAME+'_MIRROR'
		SET @CKEYFIELD='ANGADIA_CODE'
		SET @CSTEP=1002
		EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
						  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
						  ,@LINSERTONLY=0,@CFILTERCONDITION=@CFILTERCONDITION2,@LUPDATEONLY=0
						  ,@BALWAYSUPDATE=1 
		
		update DOCPRT_parcel_mst_mirror set bilty_no=parcel_memo_no where DOCPRT_MEMO_ID=@CMEMOID and
	    isnull(bilty_no,'')=''
		
		SET @CSTEP=1002
		SET @CTABLENAME='PARCEL_MST'
		SET @CTMP_TABLENAME='DOCPRT_'+@CTABLENAME+'_MIRROR'
		SET @CKEYFIELD='PARCEL_MEMO_ID'
		SET @CSTEP=1003
		EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
								  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
						  ,@LINSERTONLY=0,@CFILTERCONDITION=@CFILTERCONDITION2,@LUPDATEONLY=0
						  ,@BALWAYSUPDATE=1
		
		SET @CSTEP=1004

	 
	  DECLARE @CMERGELOCID VARCHAR(2)
	  SELECT @CMERGELOCID = VALUE FROM CONFIG (NOLOCK) WHERE  CONFIG_OPTION='LOCATION_ID'

      if @CMERGELOCID <> @CHODEPTID
	   BEGIN

		SET @DTSQL = N'DELETE A FROM PARCEL_DET A (nolock)
		               JOIN PARCEL_MST MST (NOLOCK) ON A.PARCEL_MEMO_ID=MST.PARCEL_MEMO_ID
		               LEFT JOIN DOCPRT_PARCEL_DET_MIRROR B ON A.ROW_ID=B.ROW_ID
		               WHERE A.ref_memo_id = '''+@CMEMOID+''' AND MST.XN_TYPE=''PRT'' AND B.ROW_ID IS NULL'
		PRINT @DTSQL
		EXEC SP_EXECUTESQL @DTSQL

		end
		
				
		SET @CSTEP=1005
		SET @CTABLENAME='PARCEL_DET'
		SET @CTMP_TABLENAME='DOCPRT_'+@CTABLENAME+'_MIRROR'
		SET @CKEYFIELD='PARCEL_MEMO_ID'
		SET @CSTEP=1006
		EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
						  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='ROW_ID',@CKEYFIELD3=''
						  ,@LINSERTONLY=0,@CFILTERCONDITION=@CFILTERCONDITION2,@LUPDATEONLY=0
						  ,@BALWAYSUPDATE=1 
		-----------END CHANGE BY BAIJNATH ---------
        
        
        
    
	SET  @CFILTERCONDITION=' b.cn_ID='''+@cCnId+''''    

    SET @CSTEP = 350       
    SET @CTABLENAME='CNM01106'        
    SET @CTMP_TABLENAME='WSR_CNM01106_UPLOAD'
    SET @CKEYFIELD='CN_ID'        

    EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CMERGEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
         ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''        
         ,@LINSERTONLY=0,@LUPDATEONLY=0,@CFILTERCONDITION=@CFILTERCONDITION
         ,@BALWAYSUPDATE=1


		   
	
   
    
    SET @CSTEP = 360        
    SELECT  @CCNID = CN_ID  FROM CNM01106  WHERE RM_ID =@CMEMOID AND CANCELLED=0
    PRINT 'DATA FOUND IN GROUP CN'   
	 
	PRINT 'PP'
    
    SET @CSTEP = 370        
	
	INSERT wsr_cnd01106_upload	( AUTO_SRNO, bill_level_tax_method, BIN_ID, BOX_ID, CESS_AMOUNT, cgst_amount, challan_id, cn_id, cn_tax_method, CNMDISCOUNTAMOUNT,
	custom_duty_amt, custom_duty_per, cvd_amt, cvd_per, dept_id, discount_amount, discount_percentage, Edu_cess_custom, Edu_cess_cvd, emp_code, emp_code1, emp_code2,
	excise_mrp, gross_rate, gst_percentage, H_Edu_cess_custom, H_Edu_cess_cvd, hsn_code, igst_amount, IND_DISCOUNT_AMOUNT, IND_DISCOUNT_PERCENTAGE, ind_rate, 
	inm_discount_amount, inm_discount_percentage, inv_dt, inv_net_rate, inv_no, invoice_quantity, item_form_id, item_tax_amount, item_tax_percentage, last_update, 
	LOCAL_TAX_STATUS, manual_discount, manual_Rate, net_rate, ONLINE_BILL_REF_NO, ORDER_NO, print_label, product_code, ps_id, quantity, RATE, rate_per_conv_uom, 
	ref_inv_id, rfnet, rfnet_wotax, row_id, scheme_quantity, sgst_amount, SP_ID, tax_round_off, total_custom_duty_amt, xn_value_with_gst, xn_value_without_gst,Gst_Cess_Percentage ,Gst_Cess_Amount  )  
	SELECT AUTO_SRNO, bill_level_tax_method,@cTargetBinId as BIN_ID, BOX_ID, CESS_AMOUNT, cgst_amount, '' challan_id, @cCnId cn_id,
	bill_level_tax_method cn_tax_method,RMMDISCOUNTAMOUNT as CNMDISCOUNTAMOUNT, 
	0 custom_duty_amt, 0 custom_duty_per,0 cvd_amt,0 cvd_per,@CPARTYDEPTID dept_id,dn_discount_amount discount_amount, 
	dn_discount_percentage discount_percentage, 
	0 Edu_cess_custom, 0 Edu_cess_cvd,'0000000' emp_code,'0000000' emp_code1,'0000000' emp_code2,0 excise_mrp, 
	rate gross_rate, gst_percentage,0 H_Edu_cess_custom,0 H_Edu_cess_cvd, hsn_code, igst_amount, 
	pur_discount_amount IND_DISCOUNT_AMOUNT,PUR_DISCOUNT_PERCENTAGE IND_DISCOUNT_PERCENTAGE,PUR_PURCHASE_PRICE ind_rate, 
	discount_amount inm_discount_amount,discount_percentage	inm_discount_percentage,bill_dt inv_dt, inv_rate inv_net_rate, 
	bill_no inv_no, invoice_quantity, item_form_id, item_tax_amount, item_tax_percentage, last_update, 
	'' LOCAL_TAX_STATUS, manual_discount, manual_Rate,purchase_price  net_rate,'' ONLINE_BILL_REF_NO,'' ORDER_NO,0 print_label, 
	product_code, ps_id, quantity,gross_purchase_price RATE,0 rate_per_conv_uom,'' ref_inv_id, rfnet,
	 rfnet_wotax,newid() as row_id,scheme_quantity, sgst_amount,rm_id  SP_ID, tax_round_off, 
	 0 total_custom_duty_amt, xn_value_with_gst, xn_value_without_gst ,Gst_Cess_Percentage ,Gst_Cess_Amount 
	 FROM docprt_rmd01106_mirror  (NOLOCK) WHERE rm_id=@cMemoId
	 
	 
	  -- Calculate Gst if source Location is composite or UnRegistered
	 IF EXISTS  (SELECT * FROM LOCATION WHERE DEPT_ID = @CSOURCELOCID AND REGISTERED_GST IN(0,2))
	 AND EXISTS (SELECT * FROM LOCATION WHERE DEPT_ID = @CCURDEPTID AND REGISTERED_GST =1)
	 begin 
	  
	  if not  exists (select top 1 'U' from WSR_CND01106_UPLOAD  a (nolock) where a.SP_ID =@cMemoid and  isnull(igst_amount,0)+isnull(cgst_amount,0)<>0)
	  begin
	      
	    IF OBJECT_ID('TEMPDB..#TMPHSNWSR','U') IS NOT NULL
			DROP TABLE #TMPHSNWSR

		;WITH CTE AS
		(
		SELECT B.HSN_CODE,ISNULL(C.TAX_PERCENTAGE,0)  AS TAX_PERCENTAGE,ISNULL(C.RATE_CUTOFF,0) AS RATE_CUTOFF,
		       ISNULL(C.RATE_CUTOFF_TAX_PERCENTAGE,0) AS RATE_CUTOFF_TAX_PERCENTAGE,
			  SR=ROW_NUMBER() OVER (PARTITION BY A.ROW_ID ORDER BY C.WEF DESC),
			  ISNULL(C.GST_CAL_BASIS,1) AS GST_CAL_BASIS,
			  cast('' as varchar(2)) LOC_STATE_CODE,
			  cast('' as varchar(2))  PARTY_STATE_CODE ,a.row_id ,
			  NET_VALUE=CAST((net_rate *quantity )-isnull(CNMDISCOUNTAMOUNT ,0) as numeric(14,2)),
			  NET_VALUE_WOTAX=CAST(0 as numeric(14,2))  ,
			  gst_percentage ,igst_amount ,cgst_amount ,sgst_amount ,a.quantity ,
			  xn_value_without_gst 
		FROM wsr_cnd01106_upload A (NOLOCK)
		JOIN HSN_MST B (NOLOCK) ON A.HSN_CODE =B.HSN_CODE 
		LEFT JOIN HSN_DET C (NOLOCK) ON B.HSN_CODE =C.HSN_CODE 
		AND C.WEF  <=@DRMDT 
		WHERE A.SP_ID =@cMemoid
		)
		SELECT * INTO #TMPHSNWSR FROM CTE WHERE SR=1
		
		
		UPDATE A SET LOC_STATE_CODE=(CASE WHEN ISNULL(b.LOC_GST_NO,'')='' THEN   B.GST_STATE_CODE ELSE LEFT(b.LOC_GST_NO,2) END ),
		             PARTY_STATE_CODE=(CASE WHEN ISNULL(C.LOC_GST_NO,'')='' THEN   c.GST_STATE_CODE ELSE LEFT(C.LOC_GST_NO,2) END )
		FROM #TMPHSNWSR A
		JOIN LOCATION B (NOLOCK) ON B.DEPT_ID =@CCURDEPTID
		JOIN LOCATION C (NOLOCK) ON C.DEPT_ID =@CSOURCELOCID
		
	   SET @CSTEP = 375
	   
	 
	   UPDATE HM  SET  NET_VALUE_WOTAX = ROUND(NET_VALUE-((NET_VALUE)*( (HM.RATE_CUTOFF_TAX_PERCENTAGE/  
												   (100 + HM.RATE_CUTOFF_TAX_PERCENTAGE)))),2)
	   FROM  #TMPHSNWSR HM
	 
	   SET @CSTEP = 380
	   			   			
	   UPDATE hm SET GST_PERCENTAGE=ISNULL(CASE WHEN HM.RATE_CUTOFF<ABS(hm.NET_VALUE_WOTAX)/ABS(hm.QUANTITY) 
	   THEN HM.TAX_PERCENTAGE ELSE RATE_CUTOFF_TAX_PERCENTAGE END ,0),
	   IGST_AMOUNT=0,SGST_AMOUNT=0
	   FROM #TMPHSNWSR HM 
	  
		SET @CSTEP = 382
		
		UPDATE HM SET XN_VALUE_WITHOUT_GST =ROUND(NET_VALUE-(NET_VALUE*( ((ISNULL(HM.GST_PERCENTAGE,0))/  
		(100 + ISNULL(HM.GST_PERCENTAGE,0))))),2)
		FROM #TMPHSNWSR HM
		
		
		SET @CSTEP = 385
		
        UPDATE TMP SET IGST_AMOUNT =ROUND(CASE WHEN LOC_STATE_CODE <>PARTY_STATE_CODE  THEN 
        NET_VALUE*( (TMP.GST_PERCENTAGE/ (100 + TMP.GST_PERCENTAGE)))
		ELSE 0 END,2) ,
		
		CGST_AMOUNT=ROUND((CASE WHEN LOC_STATE_CODE<>PARTY_STATE_CODE THEN 0
		ELSE NET_VALUE*((TMP.GST_PERCENTAGE/ (100 + TMP.GST_PERCENTAGE))) 
		 END)/2,2),
		 
		SGST_AMOUNT=ROUND((CASE WHEN LOC_STATE_CODE<>PARTY_STATE_CODE THEN 0
		ELSE NET_VALUE*( (TMP.GST_PERCENTAGE/  
		(100 + TMP.GST_PERCENTAGE)) ) 
		END)/2,2)
		FROM #TMPHSNWSR TMP 
		
		
		Update a set hsn_code =b.hsn_code ,
		             gst_percentage =b.gst_percentage ,
		             xn_value_without_gst =b.xn_value_without_gst ,
		             cgst_amount =b.cgst_amount ,
		             sgst_amount =b.sgst_amount ,
		             igst_amount =b.igst_amount ,
		             xn_value_with_gst =b.xn_value_without_gst+ISNULL(b.cgst_amount,0)+ISNULL(b.sgst_amount,0)+ISNULL(b.igst_amount,0)
		from WSR_CND01106_UPLOAD A (nolock)
		join #TMPHSNWSR b on a.row_id =b.row_id 
		where SP_ID =@cMemoid
	
	END	
	END
      
	 

	--SET @DTSQL = N' SELECT '''+@CCNID+''' AS CN_ID,'''' AS LOCAL_TAX_STATUS,'''' AS CHALLAN_ID,0 AS CN_TAX_METHOD,
	--			  PURCHASE_PRICE AS NET_RATE,''0000001'' AS RATE_PER_CONV_UOM,0 AS CUSTOM_DUTY_PER,
	--			  0 AS CUSTOM_DUTY_AMT,0 AS CVD_PER,0 AS EDU_CESS_CVD,0 AS H_EDU_CESS_CVD,0 AS CVD_AMT,
	--			  0 AS EDU_CESS_CUSTOM,'''' AS PRINT_LABEL,'''' AS REF_INV_ID,
	--			  PUR_DISCOUNT_PERCENTAGE AS IND_DISCOUNT_PERCENTAGE,
	--			  0 AS TOTAL_CUSTOM_DUTY_AMT,0 AS H_EDU_CESS_CUSTOM,BILL_NO AS INV_NO,BILL_DT AS INV_DT,
	--			  ''0000000'' AS EMP_CODE,
	--			  0 AS EXCISE_MRP,''0000000'' AS EMP_CODE1,''0000000'' AS EMP_CODE2,
	--			  PUR_DISCOUNT_AMOUNT AS IND_DISCOUNT_AMOUNT,GROSS_PURCHASE_PRICE AS GROSS_RATE,
	--			  PUR_PURCHASE_PRICE AS IND_RATE,DISCOUNT_PERCENTAGE AS INM_DISCOUNT_PERCENTAGE,
	--			  DISCOUNT_AMOUNT AS INM_DISCOUNT_AMOUNT,INV_RATE AS INV_NET_RATE
	--			  ,* INTO '+@TEMP_TABLE1+' FROM DOCPRT_RMD01106_MIRROR A WHERE '+@CFILTERCONDITION1
 --   PRINT @DTSQL
 --   PRINT 'PPPP'
 --   EXEC SP_EXECUTESQL @DTSQL
      
   
    UPDATE A SET A.BIN_ID = B.BIN_ID FROM wsr_cnm01106_upload A WITH (ROWLOCK)  
	JOIN CNM01106 B (NOLOCK) ON A.CN_ID = B.CN_ID
	WHERE sp_id=@cMemoid
	  
    SET @CSTEP = 400
       
    DELETE FROM CND01106 WHERE CN_ID = @CCNID
       

    PRINT 'DOCPRT-5'    
   --SELECT BIN_ID,* FROM CND01106 WHERE BIN_ID <> '000'
    SET @CSTEP = 410
    
    SET @CTABLENAME='CND01106'        
    SET @CTMP_TABLENAME='wsr_cnd01106_upload'
    SET @CKEYFIELD='CN_ID'        
     
    EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CMERGEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
         ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''        
         ,@LINSERTONLY=0,@LUPDATEONLY=0 ,@CFILTERCONDITION=@CFILTERCONDITION       
         ,@BALWAYSUPDATE=1
         
   
	SET @CSTEP = 420      
	SET @BCHALLANRECEIVEDPREV=1
	
	SELECT @BCANCELLED=CANCELLED,@DCNMRECEIPTDT=RECEIPT_DT FROM CNM01106 (NOLOCK) WHERE CN_ID=@CCNID
	
	IF  ISNULL(@BCANCELLED,0)=0  AND ISNULL(@DCNMRECEIPTDT,'')<>'' 
    BEGIN
		 EXEC SP3S_UPDATEPMT_PRTCHI
			   @cMemoId   =  @cMemoId
			  , @bREVERTFLAG  = 0      
			  , @cErrormsg = @cErrmsg OUTPUT
			  , @BNEGSTOCKFOUND    = @BNEGSTOCKFOUND OUTPUT

		IF ISNULL(@cErrmsg,'')<>''	  
			GOTO EXIT_PROC
    
    END
    
    IF NOT EXISTS (SELECT TOP 1 CN_ID FROM CND01106 (NOLOCK) WHERE CN_ID = @CCNID)
    BEGIN
		SET @CSTEP = 430
		SET @CERRMSG = 'BLANK GROUP CREDIT NOTE DETAILS CANNOT BE SAVED...PLEASE CHECK'
		GOTO EXIT_PROC 
    END    
    
    SET @CSTEP = 440
    SET @DTSQL = N'IF EXISTS (SELECT TOP 1 A.PRODUCT_CODE FROM DOCPRT_RMD01106_MIRROR A (NOLOCK) 
							  LEFT OUTER JOIN SKU B (NOLOCK) ON A.PRODUCT_CODE=B.PRODUCT_CODE
							  WHERE '+@CFILTERCONDITION1+' AND B.PRODUCT_CODE IS NULL)
						SET @CERRMSGOUT = ''SOME BAR CODE DETAILS NOT UPDATED AGAINST THE GROUP CHALLAN SOURCE DATA...PLEASE CHECK'''			  
	EXEC SP_EXECUTESQL @DTSQL,N'@CERRMSGOUT VARCHAR(MAX) OUTPUT',@CERRMSGOUT= @CERRMSG OUTPUT

	

	/*Rohit : 01-04-2023 : After DIscussion with sir on phone commenting this line
	 IF EXISTS (SELECT TOP 1 'U'   FROM CNM01106 A (NOLOCK) WHERE RECEIPT_DT<>''
	AND '01'+DBO.FN_GETFINYEAR(RECEIPT_DT )<>fin_year  AND CN_ID  =@cCnId)
	BEGIN
		SET @CERRMSG = 'RECEIPT DATE DOES NOT BELONGS TO RECEIPT FIN Year Please check '
		GOTO EXIT_PROC 

	END
	*/
	 IF EXISTS (SELECT TOP 1 'U'   FROM CNM01106 A (NOLOCK) WHERE RECEIPT_DT<>''
	AND CONVERT(DATE,receipt_dt) not between CONVERT(DATE,manual_dn_dt)  and convert(date,getdate())
	AND CN_ID  =@cCnId)
	BEGIN
		SET @CERRMSG = 'Receipt Date Must be between Purchase Return Date and ToDay date '
		GOTO EXIT_PROC 

	END

	 IF EXISTS (SELECT TOP 1 'U'   FROM CNM01106 A (NOLOCK) WHERE 
	 CONVERT(DATE,cn_dt) not between CONVERT(DATE,manual_dn_dt)  and convert(date,getdate())  AND CN_ID  =@cCnId)
	BEGIN
		SET @CERRMSG = 'Credit Note Date Must be between Purchase Return Date and ToDay Date '
		GOTO EXIT_PROC 

	END

	IF EXISTS (SELECT TOP 1'U' FROM cnm01106 A (NOLOCK) WHERE A.rm_id =@CMEMOID AND A.CANCELLED =0 AND A.cn_id <>@cCnId)
	BEGIN
	    SET @CERRMSG = 'Challan has already Received ...PLEASE CHECK'
		GOTO EXIT_PROC 

	END

 --  	DELETE A  FROM BOXD A
	--JOIN DOCPRT_BOXM_MIRROR B ON A.BOX_ID =B.BOX_ID 
	--WHERE B.DOCPRT_MEMO_ID =@CMEMOID 

	--DELETE A  FROM BOXM A
	--JOIN DOCPRT_BOXM_MIRROR B ON A.BOX_ID =B.BOX_ID 
	--WHERE B.DOCPRT_MEMO_ID =@CMEMOID 

   
	SET @CTABLENAME='BOXM'        
    SET @CTMP_TABLENAME='DOCPRT_BOXM_MIRROR'       
    SET @CKEYFIELD='BOX_ID'        
    SET @CSTEP= 770
    

    EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CMERGEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
         ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''        
         ,@LINSERTONLY=0,@LUPDATEONLY=0,@BALWAYSUPDATE=1,@CFILTERCONDITION=@CFILTERCONDITION2
  

  
	SET @CTABLENAME='BOXD'        
    SET @CTMP_TABLENAME='DOCPRT_BOXD_MIRROR'       
    SET @CKEYFIELD='BOX_ID'        
    SET @CSTEP= 780
    

    EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CMERGEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
         ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='ROW_ID',@CKEYFIELD3=''        
         ,@LINSERTONLY=0,@LUPDATEONLY=0,@BALWAYSUPDATE=1,@CFILTERCONDITION=@CFILTERCONDITION2
  
  -- as per ved ji & sanjay sir donot insert barcode in  group dn  
	--if @BCANCELLED=0
	--EXEC SP3S_UPD_SKUXFPNEW 'wsr',@cCnId,0
	

 END TRY        
 
 BEGIN CATCH
      SET @CERRMSG='P:SAVETRAN_MERGE_MIRROR_DOCPRT_DATA, STEP:'+LTRIM(RTRIM(STR(@CSTEP)))+', MESSAGE:'+ERROR_MESSAGE()        
 
	  GOTO EXIT_PROC
 END CATCH        
        
EXIT_PROC:  
	
	UPDATE cnm01106 WITH (ROWLOCk) SET last_update=getdate(),HO_SYNCH_LAST_UPDATE ='' WHERE cn_id=@cCnId

	IF ISNULL(@CERRMSG,'')='' AND ISNULL(@CERRORMSG,'')<>''
		SET @CERRMSG=@CERRORMSG
	
	SET @CSTEP = 450        
      	
	SET @CTABLESSTR='FORM,STATE,CITY,AREA,HD01106,LM01106,LMP01106,SECTIONM,SECTIOND,PARA1,PARA2,PARA3,PARA4,PARA5,PARA6,ARTICLE,SKU,SKU_OH,SKU_BO,RMM01106,RMD01106,XNSTABLELIST'
	
	IF ISNULL(@CERRMSG,'')=''  AND @DRECEIPTDT<>'' AND ISNULL(@CCMDOUTPUT,'')=''	  
	BEGIN

		DELETE FROM DOCPRT_FORM_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID
		DELETE FROM DOCPRT_STATE_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID
		DELETE FROM DOCPRT_CITY_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID
		DELETE FROM DOCPRT_AREA_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID
		DELETE FROM DOCPRT_HD01106_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID
		DELETE FROM DOCPRT_LM01106_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID
		DELETE FROM DOCPRT_LMP01106_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID
		DELETE FROM DOCPRT_LOCSST_MST_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID
		DELETE FROM DOCPRT_LOCSST_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID
		DELETE FROM DOCPRT_LOCSSTADD_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID
		DELETE FROM DOCPRT_SECTIONM_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID
		DELETE FROM DOCPRT_SECTIOND_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID
		DELETE FROM DOCPRT_PARA1_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID
		DELETE FROM DOCPRT_PARA2_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID
		DELETE FROM DOCPRT_PARA3_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID
		DELETE FROM DOCPRT_PARA4_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID
		DELETE FROM DOCPRT_PARA5_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID
		DELETE FROM DOCPRT_PARA6_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID
		DELETE FROM DOCPRT_ARTICLE_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID
		DELETE FROM DOCPRT_SKU_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID
		DELETE FROM DOCPRT_SKU_OH_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID
		
		DELETE FROM DOCPRT_PARCEL_MST_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID
		DELETE FROM DOCPRT_PARCEL_DET_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID
		DELETE FROM DOCPRT_ANGM_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID

		DELETE FROM DOCPRT_BOXm_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID
		DELETE FROM DOCPRT_BOXD_MIRROR WITH (ROWLOCK)  WHERE DOCPRT_MEMO_ID=@CMEMOID

		DELETE FROM DOCPRT_RMD01106_MIRROR WITH (ROWLOCK)  WHERE RM_ID=@CMEMOID
		DELETE FROM DOCPRT_RMM01106_MIRROR WITH (ROWLOCK)  WHERE RM_ID=@CMEMOID

	END	


	--select * from pmt01106 where product_code in('08281','YFIX')

	 IF @@trancount>0 AND  ISNULL(@BCALLEDFORSISLOC,0)=0
	 BEGIN
		IF ISNULL(@cErrmsg,'')=''
		BEGIN
			commit
			DELETE A  FROM XNTYPE_CHECKSUM_MST A  WITH (ROWLOCK)  WHERE SP_ID=@CMEMOID	
		END
		ELSE
		begin
			ROLLBACK
			DELETE A  FROM XNTYPE_CHECKSUM_MST A  WITH (ROWLOCK)  WHERE SP_ID=@CMEMOID
		end
	 END

	  IF ISNULL(@CERRORMSG,'')='' AND  @BMSTINSERTONLY=0
	 BEGIN
	
		 EXEC SP3S_UPDATE_SKUNAMES @CCNID,'WSR','CND01106','CN_ID'
	 END

END 
------ END OF CREATING PROCEDURE - SAVETRAN_MERGE_MIRROR_DOCPRT_DATA
