CREATE PROCEDURE SP3S_XTREME_REPORTTOTALSXTAB
@cRepId VARCHAR(40),
@cTempTable VARCHAR(200)
AS
BEGIN
       DECLARE @CCOLUMN_NAME VARCHAR(100),@CMESUREMENT_COL VARCHAR(100),@CCALCOLUMNLIST VARCHAR(MAX),
	   @CCOLUMNLIST VARCHAR(MAX),@CDISPLAYCOLUMNLIST VARCHAR(MAX)

       SELECT @CCOLUMN_NAME=col_expr FROM REP_DET WHERE REP_ID=@CREPID  AND DIMENSION=1
	   SELECT @CMESUREMENT_COL=key_col FROM REP_DET WHERE REP_ID=@CREPID AND MESUREMENT_COL=1


	   SELECT @CCALCOLUMNLIST=COALESCE(@CCALCOLUMNLIST+',','') +'SUM('+key_col+') AS ['+key_col+']'  
	   FROM  REP_DET   WHERE REP_ID=@CREPID AND MESUREMENT_COL=0 AND DIMENSION=0 AND Calculative_col=1

	   SELECT @CCOLUMNLIST=COALESCE(@CCOLUMNLIST+',','') +col_expr
	   FROM  REP_DET   WHERE REP_ID=@CREPID AND MESUREMENT_COL=0 AND DIMENSION=0 AND Calculative_col=0

	   IF ISNULL(@CCALCOLUMNLIST,'')<>''
	   SET @CCALCOLUMNLIST=','+@CCALCOLUMNLIST

	   SET @CDISPLAYCOLUMNLIST=@CCOLUMNLIST+ISNULL(@CCALCOLUMNLIST,'')


	   if object_id('tempdb..##tmppivot','u') is not null
	      drop table ##tmppivot

		DECLARE @CRETCOLSTR VARCHAR(MAX)   
		DECLARE @CCMD NVARCHAR(MAX) 
		EXEC CROSSTABSTR_XPERTREPORTING  @CTEMPTABLE, @CCOLUMN_NAME, @CCOLUMN_NAME, @CMESUREMENT_COL, '', '', @CRETCOLSTR OUTPUT  

		IF ISNULL(@CRETCOLSTR,'')=''
		SET @CRETCOLSTR='1 AS SR'


		
		SET @CCMD = N'SELECT '+@CDISPLAYCOLUMNLIST+'
		, ' + @CRETCOLSTR + ',SUM('+@CMESUREMENT_COL+') AS TOTAL
		into ##tmppivot
		FROM '+@CTEMPTABLE+'
		GROUP BY '+@CCOLUMNLIST+'
		ORDER BY '+@CCOLUMNLIST+' ' 
		PRINT @CCMD
		EXEC SP_EXECUTESQL @CCMD 


	

end
