CREATE PROCEDURE SP3S_SENDOPSDATA
(
	@CUPLOADEDXNID VARCHAR(40)='',
	@BUPLOADREQUEST BIT=0
)
--WITH ENCRYPTION
AS
BEGIN
	
	DECLARE @CERRORMSG VARCHAR(1000), @CCURDEPTID VARCHAR(5), @CHODEPTID VARCHAR(5), @CCMD NVARCHAR(MAX),
			@CMASTERTABLENAME VARCHAR(100), @BPROCEED BIT, @CTABLENAME VARCHAR(100), @BFIRST BIT,
			@CKEYFIELD VARCHAR(100), @CMASTERKEYFIELD VARCHAR(100), @CSENDTABLENAME VARCHAR(100),
			@CTARGETTABLENAME VARCHAR(100),@CPARENTTABLENAME VARCHAR(100), @CPARENTPARANAME VARCHAR(100),
			@CCHILDPARANAME VARCHAR(100),@CWHERECLAUSE VARCHAR(500), @CJOINSTR VARCHAR(1000),
			@CMEMOID VARCHAR(40), @NSPID INT,@CTARGETDEPTID VARCHAR(2), @CFLAGCOL VARCHAR(100),
			@LMASTERTABLE BIT,@CADDCOLS NVARCHAR(MAX),@NLOCTYPE INT,@BDONOTSEND BIT,@NRECCOUNT INT,
			@CSENDKEYFIELD VARCHAR(100),@CSENDKEYFIELDVAL VARCHAR(50),@CTEMPTABLENAME VARCHAR(200),
			@CSENDTEMPTABLENAME VARCHAR(200),@BDONOTSENDPURINFOCONFIG BIT,@CSENDPURINFOCONFIG VARCHAR(100),
			@BSENDPURINFOLOC BIT,@BPROCESSED BIT,@DMEMOLASTUPDATE DATETIME,@CADDWHERECLAUSE VARCHAR(500),
			@CSENDCOLS VARCHAR(MAX),@CDISTINCTSTR VARCHAR(20),@CXNTYPE VARCHAR(10),@BPURLOC BIT,
			@CSENDSLSBCINFO BIT,@BCHALLANFROMPOS BIT,@BTARGETPURLOC BIT,@NTARGETLOCTYPE INT,@LASTUPDATE DATETIME
			
	SELECT @CERRORMSG='',@BPROCEED=1,@NSPID=@@SPID,@CADDCOLS='',@CXNTYPE='XNSOPS'

	SELECT TOP 1 @CCURDEPTID = [VALUE] FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION='LOCATION_ID'
	SELECT TOP 1 @CHODEPTID = [VALUE] FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION='HO_LOCATION_ID'
	
	SELECT @NLOCTYPE=LOC_TYPE,@BPURLOC=PUR_LOC FROM LOCATION (NOLOCK) WHERE DEPT_ID=@CCURDEPTID
	
	DECLARE @TXNSSENDINFO TABLE (ORG_TABLENAME VARCHAR(50),TMP_TABLENAME VARCHAR(50),XN_ID VARCHAR(40),
								 DEPT_ID VARCHAR(2),MEMO_LAST_UPDATE DATETIME)
	
	IF @CUPLOADEDXNID<>''
		GOTO LBLSETFLAG		
	
	--OPS DATA SHOULD NOT BE OUT AS XNS FROM HO
	IF @CCURDEPTID=@CHODEPTID
		GOTO LBLLAST
	
	---CHECK IF OPS DATA EXISTS AT NON-HO LOCATION
	IF NOT EXISTS(SELECT TOP 1 'U' FROM OPS01106 A 
				  JOIN LOCATION L ON A.DEPT_ID=L.DEPT_ID
				  LEFT JOIN XFERLOG B ON L.MAJOR_DEPT_ID=B.XN_ID AND B.XN_TYPE='XNSOPS'
				  WHERE L.MAJOR_DEPT_ID=@CCURDEPTID AND (B.XN_ID IS NULL OR A.LAST_UPDATE<>B.LAST_UPDATE))
		GOTO LBLLAST
	
	--SET @CMEMOID=@CCURDEPTID
	
	SET @CTARGETDEPTID=@CHODEPTID
	SET @DMEMOLASTUPDATE=GETDATE()
	PRINT '@CTARGETDEPTID  ' + @CTARGETDEPTID 

LBLSEND:
	--- NOW, SEND TRANSACTIONS DATA ONE BY ONE
	DECLARE SENDCUR CURSOR FOR 
	SELECT	TABLENAME, KEYFIELD, PARENT_TABLENAME, PARENT_PARA_NAME,
			CHILD_PARA_NAME, WHERECLAUSE,TEMP_TABLE_NAME
	FROM XNSINFO (NOLOCK) 
	WHERE XN_TYPE=@CXNTYPE 
	ORDER BY XNS_SENDING_ORDER, TABLENAME
	OPEN SENDCUR
	FETCH NEXT FROM SENDCUR INTO @CTABLENAME, @CKEYFIELD, @CPARENTTABLENAME, @CPARENTPARANAME, @CCHILDPARANAME, @CWHERECLAUSE, @CTEMPTABLENAME
	WHILE @@FETCH_STATUS=0
	BEGIN
		PRINT 'DROPPING TABLE...' + @CTABLENAME
		
		PRINT 'CHECK SENDING :'+@CXNTYPE+'-'+@CTABLENAME+'-'+@CTEMPTABLENAME


		SET @CTEMPTABLENAME	= ISNULL(@CTEMPTABLENAME,'')
			
		--PRINT ISNULL(@CJOINSTR,'NULL JOINSTR')
		SET @CTARGETTABLENAME = (CASE WHEN @CTEMPTABLENAME='' THEN @CTABLENAME ELSE @CTEMPTABLENAME END)
		
		PRINT '208  : '+@CTARGETTABLENAME
		SET @CCMD=N' IF OBJECT_ID(''TMP_'+@CTARGETTABLENAME+'_'+LTRIM(RTRIM(STR(@NSPID)))+''',''U'') IS NOT NULL
						DROP TABLE TMP_'+@CTARGETTABLENAME+'_'+LTRIM(RTRIM(STR(@NSPID)))
		
		PRINT @CCMD
		EXEC SP_EXECUTESQL @CCMD							
		
		SELECT @CSENDTABLENAME=@CTABLENAME,@CSENDTEMPTABLENAME=@CTEMPTABLENAME,@BFIRST=1
		
		WHILE @@FETCH_STATUS=0 AND @CTABLENAME=@CSENDTABLENAME AND @CTEMPTABLENAME=@CSENDTEMPTABLENAME
		BEGIN
			SELECT @CJOINSTR = DBO.FN_CREATEXNSJOINSTR(@CXNTYPE,@CTABLENAME,@CPARENTTABLENAME,@CPARENTPARANAME,'',@CWHERECLAUSE,@CMEMOID )			
			
			SET @CJOINSTR = ISNULL(@CJOINSTR,'')
			
			PRINT '@CJOINSTR ' + @CJOINSTR
			SELECT @CADDWHERECLAUSE='',@CADDCOLS=''	
			
			IF @CTABLENAME='OPS01106'
				SET @CADDWHERECLAUSE=' JOIN LOCATION B ON B.DEPT_ID=OPS01106.DEPT_ID WHERE B.MAJOR_DEPT_ID='''+@CCURDEPTID+''''
				
			IF @BFIRST=1	
			BEGIN
				--SET @CADDCOLS = ',CONVERT(DATETIME,'''') AS RECEIPT_DT,CONVERT(BIT,0) AS STOCKINSERTED,'''' AS CH_REMARKS'
				
				SET @CSENDCOLS = @CTABLENAME+'.*'
				
				SET @CDISTINCTSTR=' DISTINCT '
								 
				SET @CCMD = 'SELECT '+@CDISTINCTSTR+@CSENDCOLS+@CADDCOLS+' INTO TMP_'+@CTARGETTABLENAME + '_'+LTRIM(RTRIM(STR(@NSPID)))+
						    ' FROM ' + @CTABLENAME + @CJOINSTR+@CADDWHERECLAUSE
				
	
				SET @CADDCOLS=''		    
			END			    
			ELSE
				SET @CCMD = @CCMD + ' UNION ' + CHAR(13) + 'SELECT DISTINCT ' + @CTABLENAME + '.* FROM ' + @CTABLENAME + @CJOINSTR

			SET @BFIRST=0	
			
			LBLNEXTTABLE:
			
			FETCH NEXT FROM SENDCUR INTO @CTABLENAME, @CKEYFIELD, @CPARENTTABLENAME, @CPARENTPARANAME, @CCHILDPARANAME, @CWHERECLAUSE, @CTEMPTABLENAME
	
		END

		PRINT @CCMD
		EXEC SP_EXECUTESQL @CCMD
		
		PRINT 'SEND TABLE NAME'+@CSENDTABLENAME
				
		SET @CCMD=N'SELECT @NRECCOUNTOUT=COUNT(*) FROM TMP_' + @CTARGETTABLENAME + '_'+LTRIM(RTRIM(STR(@NSPID)))
		PRINT @CCMD
		EXEC SP_EXECUTESQL @CCMD,N'@NRECCOUNTOUT INT OUTPUT',@NRECCOUNTOUT=@NRECCOUNT OUTPUT
		
		
		PRINT @CTARGETTABLENAME+' RECCOUNT('+LTRIM(RTRIM(STR(@NRECCOUNT)))+')'
		SET @BDONOTSEND=0
		
		IF @NRECCOUNT=0
			SET @BDONOTSEND=1
		
		IF @BDONOTSEND=0
			INSERT @TXNSSENDINFO VALUES (@CTARGETTABLENAME, 'TMP_'+@CTARGETTABLENAME+'_'+LTRIM(RTRIM(STR(@NSPID))),
			@CCURDEPTID, @CTARGETDEPTID,@DMEMOLASTUPDATE)
		
	END
	CLOSE SENDCUR
	DEALLOCATE SENDCUR
	
	
	GOTO LBLLAST
		
LBLSETFLAG:
			
	IF  @BUPLOADREQUEST=1
	BEGIN
		UPDATE O SET LAST_UPDATE=GETDATE()
		FROM OPS01106 O
		JOIN LOCATION L ON O.DEPT_ID=L.DEPT_ID
		WHERE L.MAJOR_DEPT_ID=@CCURDEPTID
	END
	ELSE
	BEGIN
			SET @LASTUPDATE=GETDATE()
			
					
			UPDATE O SET LAST_UPDATE=@LASTUPDATE
			FROM OPS01106 O
			JOIN LOCATION L ON O.DEPT_ID=L.DEPT_ID
			WHERE L.MAJOR_DEPT_ID=@CCURDEPTID
			
			
			IF EXISTS(SELECT TOP 1 'U' FROM XFERLOG WHERE XN_TYPE='XNSOPS' AND XN_ID=@CCURDEPTID)
				UPDATE XFERLOG SET LAST_UPDATE=@LASTUPDATE WHERE XN_TYPE='XNSOPS' AND XN_ID=@CCURDEPTID
			ELSE
				 INSERT XFERLOG	( XN_TYPE, XN_ID, LAST_UPDATE )  
				 SELECT 'XNSOPS' AS  XN_TYPE,@CCURDEPTID AS XN_ID,@LASTUPDATE AS LAST_UPDATE 
		
	END
LBLLAST:
	SELECT * FROM @TXNSSENDINFO
	
END
--********************************************** END OF PROCEDURE SP3S_SENDOPSDATA
