CREATE PROC [DBO].[SP_PRD_JOB_WORK_ISSUE]          
(          
  @IMODE INT ,          
  @CWHERE VARCHAR(4000)='',      
  @CAGENCYCODE CHAR(7)='',      
  @BMODE BIT = 0 ,    
  @FINYEAR VARCHAR(10)='' ,
    
  @DEPTID VARCHAR(10)='',   
  @DFROM_DT DATETIME='',
  @DTO_DT  DATETIME='',
  @CANCELLED INT= 0     
)      
--WITH ENCRYPTION
AS          
          
BEGIN          
          
 IF @IMODE =1          
 GOTO LBLLOOKUP          
           
 ELSE IF @IMODE =2          
 GOTO LBLMST          
           
 ELSE IF @IMODE =3          
 GOTO LBLDET          
           
 ELSE IF @IMODE =4          
 GOTO LBLHBDDET          
           
 ELSE IF @IMODE =5          
 GOTO LBLAGENCY          
           
 ELSE IF @IMODE =6          
 GOTO LBLAGJOBS          
       
 ELSE IF @IMODE=7       
  GOTO LBLGRID        
      
 ELSE IF @IMODE=8          
 GOTO LBLCANCELCHECK        
 
 ELSE IF @IMODE=9          
 GOTO  LBLJOBWORKISSUE   
 ELSE          
 GOTO LAST        
       
 DECLARE @CCMD NVARCHAR(MAX)         
           
LBLLOOKUP:        
    
  SELECT ISSUE_ID FROM PRD_JOBWORK_ISSUE_MST (NOLOCK)    
  WHERE FIN_YEAR=@FINYEAR AND LEFT(ISSUE_ID,2)=@CWHERE     
    
 GOTO LAST           
          
LBLMST:          
 SELECT A.*,B.AGENCY_NAME,--C.JOB_NAME,
 '' AS ADDRESS_F,U.USERNAME AS USER_NAME,  
 U1.USERNAME AS EDT_USER_NAME ,BIN.BIN_NAME        
 FROM PRD_JOBWORK_ISSUE_MST A (NOLOCK)             
 JOIN PRD_AGENCY_MST B (NOLOCK) ON A.AGENCY_CODE = B.AGENCY_CODE             
 --CHANGE JOIN JOBS C (NOLOCK) ON A.COMPANY_CODE = C.COMPANY_CODE            
 LEFT OUTER JOIN USERS U (NOLOCK) ON U.USER_CODE = A.USER_CODE     
 LEFT OUTER  JOIN USERS U1 (NOLOCK) ON U1.USER_CODE = A.EDT_USER_CODE   
 LEFT OUTER JOIN BIN (NOLOCK) ON BIN.BIN_ID=A.BIN_ID      
 WHERE A.ISSUE_ID = @CWHERE             
       
 GOTO LAST           
           
LBLDET:          
    SELECT CAST(0 AS BIT) AS CHKBILL, A.ISSUE_NO,A.ISSUE_ID,G.*,      
    ART.ARTICLE_CODE, ART.ARTICLE_NO, ART.ARTICLE_NAME, P1.PARA1_CODE,        
 PARA1_NAME, P2.PARA2_CODE,PARA2_NAME,P3.PARA3_CODE,PARA3_NAME,UOM_NAME,           
 CODING_SCHEME,CONVERT(NUMERIC(10,2),0) AS QUANTITY_IN_STOCK,SKU.PURCHASE_PRICE,      
  SKU.MRP,SKU.WS_PRICE,   SM.SECTION_NAME, SD.SUB_SECTION_NAME,        
 P4.PARA4_CODE,P5.PARA5_CODE,P6.PARA6_CODE,        
 PARA4_NAME,PARA5_NAME,PARA6_NAME,E.UOM_CODE,ISNULL(E.UOM_TYPE,0) AS [UOM_TYPE],        
 ART.DT_CREATED AS [ART_DT_CREATED],P3.DT_CREATED AS [PARA3_DT_CREATED],SKU.DT_CREATED AS [SKU_DT_CREATED],        
 ART.STOCK_NA,JOBS.JOB_CODE,JOBS.JOB_NAME,G.DUE_DT AS DELIVERY_DT ,  
 (G.JOB_RATE*G.QUANTITY) AS AMOUNT,ART.ALIAS AS ARTICLE_ALIAS,B.BIN_NAME,G.BIN_ID,PREVJOB.JOB_NAME AS PREV_JOB_NAME ,
 A.REMARKS AS MST_REMARKS               
 FROM PRD_JOBWORK_ISSUE_MST A (NOLOCK)             
 JOIN PRD_JOBWORK_ISSUE_DET G (NOLOCK)  ON A.ISSUE_ID = G.ISSUE_ID                        
 JOIN PRD_SKU SKU ON SKU.PRODUCT_UID=G.PRODUCT_UID   
 JOIN ARTICLE ART ON SKU.ARTICLE_CODE = ART.ARTICLE_CODE          
 JOIN SECTIOND SD ON ART.SUB_SECTION_CODE = SD.SUB_SECTION_CODE        
 JOIN SECTIONM SM ON SD.SECTION_CODE = SM.SECTION_CODE        
 JOIN PARA1 P1 ON SKU.PARA1_CODE = P1.PARA1_CODE          
 JOIN PARA2 P2 ON SKU.PARA2_CODE = P2.PARA2_CODE          
 JOIN PARA3 P3 ON SKU.PARA3_CODE = P3.PARA3_CODE          
 JOIN PARA4 P4 ON SKU.PARA4_CODE = P4.PARA4_CODE          
 JOIN PARA5 P5 ON SKU.PARA5_CODE = P5.PARA5_CODE          
 JOIN PARA6 P6 ON SKU.PARA6_CODE = P6.PARA6_CODE          
 JOIN UOM E ON ART.UOM_CODE = E.UOM_CODE       
 JOIN JOBS (NOLOCK) ON JOBS.JOB_CODE=G.JOB_CODE   
 LEFT JOIN JOBS PREVJOB (NOLOCK) ON PREVJOB.JOB_CODE=G.PREV_JOB_CODE  
 JOIN BIN B ON B.BIN_ID =G.BIN_ID         
  WHERE A.ISSUE_ID = @CWHERE            
 GOTO LAST           
      
LBLHBDDET:          
     
  SELECT CAST(0 AS BIT) AS CHKBILL,'' AS CM_ID,'' AS CM_NO,'' AS ROW_ID,CAST('01-01-1900' AS DATETIME) AS DELIVERY_DT,PMT.PRODUCT_CODE,PMT.QUANTITY_IN_STOCK,      
  CAST('1.00' AS NUMERIC(10,2)) AS QUANTITY,          
  ART.ARTICLE_CODE, ART.ARTICLE_NO, ART.ARTICLE_NAME, P1.PARA1_CODE,        
  PARA1_NAME, P2.PARA2_CODE,PARA2_NAME,P3.PARA3_CODE,PARA3_NAME,UOM_NAME,           
  CODING_SCHEME,CONVERT(NUMERIC(10,2),0) AS QUANTITY_IN_STOCK,SKU.PURCHASE_PRICE,      
   SKU.MRP,SKU.WS_PRICE,   SM.SECTION_NAME, SD.SUB_SECTION_NAME,        
  P4.PARA4_CODE,P5.PARA5_CODE,P6.PARA6_CODE,        
  PARA4_NAME,PARA5_NAME,PARA6_NAME,E.UOM_CODE,ISNULL(E.UOM_TYPE,0) AS [UOM_TYPE],        
  ART.DT_CREATED AS [ART_DT_CREATED],P3.DT_CREATED AS [PARA3_DT_CREATED],SKU.DT_CREATED AS [SKU_DT_CREATED],        
  ART.STOCK_NA,'' AS EMP_NAME ,'' AS JOB_NAME ,'' AS JOB_CODE ,0 AS JOB_RATE,ART.ALIAS AS ARTICLE_ALIAS           
  FROM PRD_PMT PMT          
  JOIN PRD_SKU SKU ON SKU.PRODUCT_UID=PMT.PRODUCT_UID      
  JOIN ARTICLE ART ON SKU.ARTICLE_CODE = ART.ARTICLE_CODE          
  JOIN SECTIOND SD ON ART.SUB_SECTION_CODE = SD.SUB_SECTION_CODE        
  JOIN SECTIONM SM ON SD.SECTION_CODE = SM.SECTION_CODE        
  JOIN PARA1 P1 ON SKU.PARA1_CODE = P1.PARA1_CODE          
  JOIN PARA2 P2 ON SKU.PARA2_CODE = P2.PARA2_CODE          
  JOIN PARA3 P3 ON SKU.PARA3_CODE = P3.PARA3_CODE          
  JOIN PARA4 P4 ON SKU.PARA4_CODE = P4.PARA4_CODE          
  JOIN PARA5 P5 ON SKU.PARA5_CODE = P5.PARA5_CODE          
  JOIN PARA6 P6 ON SKU.PARA6_CODE = P6.PARA6_CODE          
  JOIN UOM E ON ART.UOM_CODE = E.UOM_CODE       
 WHERE PMT.PRODUCT_CODE <> '' AND PMT.PRODUCT_CODE=@CWHERE     
 --AND PMT.DEPT_ID=@DEPTID     
      
 GOTO LAST           
          
LBLAGENCY:          
      
    SELECT * FROM PRD_AGENCY_MST (NOLOCK) WHERE  INACTIVE = 0 AND AGENCY_NAME <> ''         
 GOTO LAST           
          
LBLAGJOBS:          
 SELECT A.*,B.JOB_RATE ,B.AGENCY_CODE,'' AS ADDRESS_F 
 FROM JOBS (NOLOCK) A 
 JOIN AGENCY_JOBS B (NOLOCK)           
 ON A.JOB_CODE = B.JOB_CODE           
 JOIN PRD_AGENCY_MST C (NOLOCK) ON B.AGENCY_CODE = C.AGENCY_CODE      
 WHERE  B.AGENCY_CODE = @CWHERE           
 GOTO LAST           
          
LBLGRID:          
  SELECT  A.ISSUE_NO,G.QUANTITY,G.JOB_RATE,G.ROW_ID,G.REF_NO,    
    ART.ARTICLE_CODE, ART.ARTICLE_NO, ART.ARTICLE_NAME, P1.PARA1_CODE,        
 PARA1_NAME, P2.PARA2_CODE,PARA2_NAME,P3.PARA3_CODE,PARA3_NAME,UOM_NAME,           
 CODING_SCHEME,CONVERT(NUMERIC(10,2),0) AS QUANTITY_IN_STOCK,SKU.PURCHASE_PRICE,      
 SKU.MRP,SKU.WS_PRICE,   SM.SECTION_NAME, SD.SUB_SECTION_NAME,        
 P4.PARA4_CODE,P5.PARA5_CODE,P6.PARA6_CODE,        
 PARA4_NAME,PARA5_NAME,PARA6_NAME,E.UOM_CODE,ISNULL(E.UOM_TYPE,0) AS [UOM_TYPE],        
 ART.DT_CREATED AS [ART_DT_CREATED],P3.DT_CREATED AS [PARA3_DT_CREATED],SKU.DT_CREATED AS [SKU_DT_CREATED],        
 ART.STOCK_NA ,JOBS.JOB_CODE,JOBS.JOB_NAME,ART.ALIAS AS ARTICLE_ALIAS,
 A.REMARKS          
FROM PRD_JOBWORK_ISSUE_MST A (NOLOCK)           
JOIN PRD_JOBWORK_ISSUE_DET G (NOLOCK)  ON A.ISSUE_ID = G.ISSUE_ID           
JOIN PRD_SKU SKU (NOLOCK) ON SKU.PRODUCT_UID=G.PRODUCT_UID   
 JOIN ARTICLE ART (NOLOCK) ON SKU.ARTICLE_CODE = ART.ARTICLE_CODE          
 JOIN SECTIOND SD (NOLOCK) ON ART.SUB_SECTION_CODE = SD.SUB_SECTION_CODE        
 JOIN SECTIONM SM (NOLOCK) ON SD.SECTION_CODE = SM.SECTION_CODE        
 JOIN PARA1 P1 (NOLOCK) ON SKU.PARA1_CODE = P1.PARA1_CODE          
 JOIN PARA2 P2 (NOLOCK) ON SKU.PARA2_CODE = P2.PARA2_CODE          
 JOIN PARA3 P3 (NOLOCK)ON SKU.PARA3_CODE = P3.PARA3_CODE          
 JOIN PARA4 P4 (NOLOCK)ON SKU.PARA4_CODE = P4.PARA4_CODE          
 JOIN PARA5 P5 (NOLOCK)ON SKU.PARA5_CODE = P5.PARA5_CODE          
 JOIN PARA6 P6 (NOLOCK)ON SKU.PARA6_CODE = P6.PARA6_CODE          
 JOIN UOM E (NOLOCK)ON ART.UOM_CODE = E.UOM_CODE        
 JOIN JOBS  (NOLOCK) ON G.JOB_CODE=JOBS.JOB_CODE          
 WHERE A.ISSUE_ID =@CWHERE          
            
  GOTO LAST          
        
        
LBLCANCELCHECK:      
       
 SELECT Q.ISSUE_ID        
 FROM PRD_JOBWORK_RECEIPT_MST A (NOLOCK)                       
 JOIN PRD_JOBWORK_RECEIPT_DET B (NOLOCK) ON A.RECEIPT_ID = B.RECEIPT_ID          
 JOIN PRD_JOBWORK_ISSUE_DET M (NOLOCK) ON M.ROW_ID = B.REF_ROW_ID       
 JOIN PRD_JOBWORK_ISSUE_MST Q (NOLOCK) ON Q.ISSUE_ID = M.ISSUE_ID       
 WHERE Q.ISSUE_ID = @CWHERE       
      
 GOTO LAST  
 
 LBLJOBWORKISSUE:  
 SELECT A.ISSUE_NO,A.ISSUE_ID AS MEMO_ID,
 ISSUE_DT=CONVERT(VARCHAR,A.ISSUE_DT,105),
 CANCELLED=CASE WHEN A.CANCELLED=0 THEN '' ELSE 'CANCELLED' END,
 A.COMPANY_CODE,LAST_UPDATE=CONVERT(VARCHAR,A.LAST_UPDATE,105),A.FIN_YEAR,
 ISSUED_BY,A.CHECKED_BY,U.USERNAME,EDT_USER_NAME=U1.USERNAME,
 A.SUBTOTAL,A.DISCOUNT_PERCENTAGE,A.DISCOUNT_AMOUNT,A.ROUND_OFF,A.TOTAL_AMOUNT,
 A.REF_NO,D.AGENCY_NAME,A.REMARKS,A.ISSUE_TYPE,      
 --JOBS.JOB_NAME,
 CONVERT(VARCHAR,G.DUE_DT,105) AS DELIVERY_DT ,  
 SUM((G.JOB_RATE*G.QUANTITY)) AS AMOUNT,SUM((G.QUANTITY)) AS ISSUE_QUANTITY,
 B.BIN_NAME,G.BIN_ID,PREVJOB.JOB_NAME AS PREV_JOB_NAME                 
 FROM PRD_JOBWORK_ISSUE_MST A (NOLOCK)             
 JOIN PRD_JOBWORK_ISSUE_DET G (NOLOCK)  ON A.ISSUE_ID = G.ISSUE_ID                               
 --JOIN JOBS (NOLOCK) ON JOBS.JOB_CODE=G.JOB_CODE   
 JOIN USERS (NOLOCK) U ON A.USER_CODE=U.USER_CODE
 JOIN USERS (NOLOCK) U1 ON A.USER_CODE=U1.USER_CODE
 JOIN PRD_AGENCY_MST D (NOLOCK) ON A.AGENCY_CODE = D.AGENCY_CODE  
 LEFT JOIN JOBS PREVJOB (NOLOCK) ON PREVJOB.JOB_CODE=G.PREV_JOB_CODE  
 JOIN BIN B ON B.BIN_ID =G.BIN_ID  
 WHERE (A.ISSUE_DT >= @DFROM_DT OR @DFROM_DT='' OR @DFROM_DT IS NULL) 
     AND( A.ISSUE_DT<= @DTO_DT OR @DTO_DT='' OR @DTO_DT IS NULL) 
	AND (@CANCELLED=2 OR A.CANCELLED=@CANCELLED)
	AND (@CAGENCYCODE='' OR A.AGENCY_CODE=@CAGENCYCODE)     
 GROUP BY  A.ISSUE_NO,A.ISSUE_ID,
 A.ISSUE_DT,A.CANCELLED,A.COMPANY_CODE,A.LAST_UPDATE,A.FIN_YEAR,
 A.ISSUED_BY,A.CHECKED_BY,U.USERNAME,U1.USERNAME,
 A.SUBTOTAL,A.DISCOUNT_PERCENTAGE,A.DISCOUNT_AMOUNT,A.ROUND_OFF,A.TOTAL_AMOUNT,
 A.REF_NO,D.AGENCY_NAME,A.REMARKS,A.ISSUE_TYPE--,JOBS.JOB_NAME
 ,G.DUE_DT  ,B.BIN_NAME,G.BIN_ID,PREVJOB.JOB_NAME 
 GOTO LAST     
          
LAST:          
              
END
