CREATE PROCEDURE SP3S_Getdata_FOR_IMPORT_LEDGER
(
	@CSPID VARCHAR(10),
	@CLOCID VARCHAR(5)=''
)
AS
BEGIN
    
	BEGIN TRY
    DECLARE @CCMD NVARCHAR(MAX),@CSTEP VARCHAR(100),@CIMPORTTABLE VARCHAR(50),@CDB_NAME VARCHAR(100),
	        @LOCATINID varchar(5),@CHODEPT_ID VARCHAR(5),@CERRMSG VARCHAR(1000)

		SET @CERRMSG=''
		SELECT TOP 1 @CHODEPT_ID=VALUE  FROM CONFIG WHERE CONFIG_OPTION ='LOCATION_ID'

	    IF @CLOCID=''
		  SELECT @LOCATINID = DEPT_ID FROM NEW_APP_LOGIN_INFO (nolock) WHERE SPID=@@SPID 
		ELSE
		  SET @LOCATINID=@CLOCID


		 SET @CIMPORTTABLE='TEMP_LEDGER_'+@CSPID
		 SET @CDB_NAME = DB_NAME()+'.DBO.'


		SET @CSTEP=20
		
	  SET @CCMD = N'UPDATE  A SET AC_CODE=B.AC_CODE
		             FROM '+@CIMPORTTABLE+' A 
		             JOIN
		             (
		              SELECT AC_CODE,AC_NAME 
		              FROM LM01106 		            
		              GROUP BY AC_CODE,AC_NAME 
		             ) B ON A.AC_NAME=B.AC_NAME
		             WHERE ISNULL(A.AC_CODE,'''')='''''
		PRINT @CCMD
		EXEC SP_EXECUTESQL @CCMD


		  SET @CCMD = N'SELECT A.* FROM  '+@CIMPORTTABLE+' A 
		  ORDER BY CASE WHEN ISNULL(A.AC_CODE,'''')='''' THEN 0 ESLE 1 END,AC_NAME
		  '
		 PRINT @CCMD
		 EXEC SP_EXECUTESQL @CCMD
      

	END TRY
	
	BEGIN CATCH
	   SET @CERRMSG='P: SP3S_Getdata_FOR_IMPORT_LEDGER, STEP: '+@CSTEP+' MESSAGE: '+ERROR_MESSAGE()
	END CATCH
	
	EXIT_PROC:

	IF ISNULL(@CERRMSG,'')<>''
	SELECT @CERRMSG

END