CREATE PROCEDURE SP_REFRESH_APPVIEWS
--WITH ENCRYPTION
AS
BEGIN
	DECLARE @CCMD NVARCHAR(200),@CVIEWNAME VARCHAR(100)
	
	DECLARE ABC CURSOR FOR SELECT A.NAME FROM SYS.VIEWS A JOIN SYS.SQL_MODULES B ON A.OBJECT_ID=B.OBJECT_ID	
	OPEN ABC
	FETCH NEXT FROM ABC INTO @CVIEWNAME 
	WHILE @@FETCH_STATUS=0
	BEGIN
        
		PRINT @CVIEWNAME
		BEGIN TRY
		     SET @CCMD=N'EXEC SP_REFRESHVIEW '+@CVIEWNAME
			PRINT @CCMD
			EXEC SP_EXECUTESQL @CCMD	
		END TRY
		BEGIN CATCH
		     GOTO LABLE
		
		END CATCH
		
LABLE:
	FETCH NEXT FROM ABC INTO @CVIEWNAME 
	END
	CLOSE ABC
	DEALLOCATE ABC
END
