

-- RETURNS THE BAR CODES WITH APPLIED SCHEME DISCOUNTS
CREATE PROCEDURE SP3S_EOSS_SCHEMES_1
(
	@CSCHEMEDETROWID VARCHAR(50),
	@CSLSTITLE VARCHAR(500),
	@CROUNDITEMLEVEL VARCHAR(5),
	@CJOINSTRBUY VARCHAR(MAX),
	@CJOINSTRGET VARCHAR(MAX),
	@CPICKSLRDISCMODE VARCHAR(5),
	@CERRMSG VARCHAR(MAX) OUTPUT
)
AS 
BEGIN

	DECLARE @NORGBUYAMT NUMERIC(10,2),@NBUYAMT NUMERIC(10,2),@NGETAMT NUMERIC(10,2),@NREQGETAMT NUMERIC(10,2),
			@CPRODUCTCODE VARCHAR(50),@NMRP NUMERIC(10,2),@NQTY NUMERIC(10,2),
			@CCMDROWID VARCHAR(50),@NLOOPCNT INT,@NMODE INT,@BQUALIFIED BIT,
			@CROWID VARCHAR(100),@NSTEP INT,@NAMT NUMERIC(10,2),
			@CMRPORDER VARCHAR(10),@NREQBUYAMT NUMERIC(10,2),@BRETRY2NDCASE BIT,
			@CCMD NVARCHAR(MAX),@CBUYFILTER VARCHAR(MAX),@CGETFILTER VARCHAR(MAX),
			@CADDFILTER VARCHAR(MAX),@CORGADDFILTER VARCHAR(MAX),@NDISCMODE INT,
			@NFILTERMODE INT,@BPROCESSSLRENTRY BIT,@NGETFILTERMODE INT
	
	SET @BPROCESSSLRENTRY=0
START_PROC:

	SELECT @NORGBUYAMT=0,@CPRODUCTCODE='',@NBUYAMT=0,@NGETAMT=0,@NMRP=0,@NQTY=0,
		   @CCMDROWID='',@NLOOPCNT=0,@NREQGETAMT=0,@NMODE=0,@BQUALIFIED=0,@CROWID='',
		   @NSTEP=0,@NAMT=0,@CMRPORDER='',@NREQBUYAMT=0,@BRETRY2NDCASE=0,@CCMD='',
		   @NDISCMODE=0,@CBUYFILTER='',@CGETFILTER='',@CADDFILTER='',@NFILTERMODE=0,
		   @CADDFILTER='',@CORGADDFILTER='',@NGETFILTERMODE=0
			

	IF NOT EXISTS (SELECT TOP 1 * FROM #TMPCMD WHERE ABS(QUANTITY)-SCHEME_APPLIED_QTY>0)
		GOTO END_PROC

	IF @BPROCESSSLRENTRY=1
		SET @CORGADDFILTER='A.QUANTITY<0'
	ELSE
		SET @CORGADDFILTER='A.QUANTITY>0'
			
	IF CURSOR_STATUS('GLOBAL','SCHEMECUR') IN (0,1)
	BEGIN
		CLOSE SCHEMECUR
		DEALLOCATE SCHEMECUR
	END

BEGIN TRY        
		
	SET @NSTEP=10
	
	PRINT 'CHECK SCHEME SP3S_EOSS_SCHEMES_1'	
	SELECT @CMRPORDER='',@BQUALIFIED=0,@BRETRY2NDCASE=0
		
	IF OBJECT_ID('TEMPDB..#TEMPCMDPREV','U') IS NOT NULL
		DROP TABLE #TEMPCMDPREV

	IF OBJECT_ID('TEMPDB..#TMPCMDSCHEMES','U') IS NOT NULL
		DROP TABLE #TMPCMDSCHEMES

	SELECT @CBUYFILTER=(CASE WHEN FILTER_MODE IN (0,1) THEN  BUY_FILTER_CRITERIA ELSE '1=1' END),
		   @CGETFILTER=(CASE WHEN GET_FILTER_MODE IN (0,1) THEN  GET_FILTER_CRITERIA ELSE '1=1' END),
		   @NDISCMODE=DISC_METHOD,@NFILTERMODE=FILTER_MODE,@NGETFILTERMODE=GET_FILTER_MODE
	FROM SCHEME_SETUP_DET
	WHERE ROW_ID=@CSCHEMEDETROWID

	IF @NFILTERMODE NOT IN (0,1)
		SELECT @CADDFILTER=@CORGADDFILTER+' AND SLSDET.ROW_ID='''+@CSCHEMEDETROWID+''''
	ELSE
		SELECT @CADDFILTER=@CORGADDFILTER+' AND 1=1'			
					
	SET @NSTEP=15
	SELECT PRODUCT_CODE,MRP,QUANTITY,CMD_ROW_ID AS ROW_ID,CONVERT(INT,0) AS MODE,
	CONVERT(NUMERIC(10,2),0) AS DISCOUNT_AMOUNT,QUANTITY AS SCHEME_APPLIED_QTY INTO #TMPCMDSCHEMES FROM #TMPCMD
	WHERE 1=2 
	
	
	SET @CCMD=N' SELECT A.PRODUCT_CODE,A.MRP,(ABS(A.QUANTITY)-A.SCHEME_APPLIED_QTY)*(CASE WHEN A.QUANTITY<0 THEN -1 ELSE 1 END),
				 A.CMD_ROW_ID AS ROW_ID,1 AS MODE,
				 0 AS DISCOUNT_AMOUNT,0 FROM #TMPCMD A
				 JOIN #CMDITV ITV ON ITV.PRODUCT_CODE=A.PRODUCT_CODE '+@CJOINSTRBUY+'
				 WHERE ABS(A.QUANTITY)-A.SCHEME_APPLIED_QTY>0 AND '+@CBUYFILTER+' AND '+@CADDFILTER
	
	PRINT @CCMD				 
	INSERT #TMPCMDSCHEMES
	EXEC SP_EXECUTESQL @CCMD
	
	SET @NSTEP=20

	IF @NGETFILTERMODE NOT IN (0,1)
		SELECT @CADDFILTER=@CORGADDFILTER+' AND SLSDET.ROW_ID='''+@CSCHEMEDETROWID+''''
	ELSE
		SELECT @CADDFILTER=@CORGADDFILTER+' AND 1=1'			
	
	SET @CCMD=N' SELECT A.PRODUCT_CODE,A.MRP,(ABS(A.QUANTITY)-A.SCHEME_APPLIED_QTY)*(CASE WHEN A.QUANTITY<0 THEN -1 ELSE 1 END),
				 A.CMD_ROW_ID AS ROW_ID,2 AS MODE,
				 0 AS DISCOUNT_AMOUNT,0 FROM #TMPCMD A
				 JOIN #CMDITV ITV ON ITV.PRODUCT_CODE=A.PRODUCT_CODE '+@CJOINSTRGET+'
				 WHERE ABS(A.QUANTITY)-A.SCHEME_APPLIED_QTY>0 AND '+@CGETFILTER+' AND '+@CADDFILTER
				 
	INSERT #TMPCMDSCHEMES
	EXEC SP_EXECUTESQL @CCMD

	SET @NSTEP=25
	
	SELECT * INTO #TEMPCMDPREV FROM #TMPCMDSCHEMES


LBL1STCASE:
		
	SET @NREQGETAMT=0
			
	SELECT @NORGBUYAMT= BUY_AMOUNT,@NBUYAMT= BUY_AMOUNT,@NGETAMT=DISCOUNT_AMOUNT  FROM SCHEME_SETUP_DET
	WHERE ROW_ID=@CSCHEMEDETROWID
	
	SET @NSTEP=30
	
	IF @CMRPORDER=''
		DECLARE SCHEMECUR CURSOR FOR SELECT PRODUCT_CODE,MRP,QUANTITY,ROW_ID,MODE FROM
		#TMPCMDSCHEMES WHERE MODE=2 ORDER BY MRP DESC
	ELSE
		DECLARE SCHEMECUR CURSOR FOR SELECT PRODUCT_CODE,MRP,QUANTITY,ROW_ID,MODE FROM
		#TMPCMDSCHEMES WHERE MODE=2 ORDER BY MRP

	
	OPEN SCHEMECUR
	FETCH NEXT FROM SCHEMECUR INTO @CPRODUCTCODE,@NMRP,@NQTY,@CCMDROWID,@NMODE
	WHILE @@FETCH_STATUS=0
	BEGIN
		SET @NSTEP=40
		SET @NLOOPCNT=1
		WHILE @NLOOPCNT<=ABS(@NQTY)
		BEGIN
			SET @NAMT=(CASE WHEN @NREQGETAMT+@NMRP>@NGETAMT THEN @NGETAMT-@NREQGETAMT
							ELSE @NMRP END)
							
			SET @NREQGETAMT=@NREQGETAMT+@NAMT
		    
		    SET @NSTEP=50
			UPDATE #TMPCMDSCHEMES SET QUANTITY=QUANTITY-1,
			DISCOUNT_AMOUNT=ISNULL(DISCOUNT_AMOUNT,0)+@NAMT,
			SCHEME_APPLIED_QTY=SCHEME_APPLIED_QTY+1
			WHERE ROW_ID=@CCMDROWID
		    
		    PRINT '1:'+STR(@NREQGETAMT)+STR(@NGETAMT)
			IF @NREQGETAMT>=@NGETAMT
			BEGIN
				SET @BQUALIFIED=1				
				BREAK
			END
		    
		    SET @NSTEP=60
			IF @BQUALIFIED=1
				BREAK
				
			SET @NLOOPCNT=@NLOOPCNT+1
		END										
		
		IF @BQUALIFIED=1
			BREAK
			
		FETCH NEXT FROM SCHEMECUR INTO @CPRODUCTCODE,@NMRP,@NQTY,@CCMDROWID,@NMODE
	END
	CLOSE SCHEMECUR
	DEALLOCATE SCHEMECUR
	
	SET @NSTEP=70
	SET @BQUALIFIED=0
	
	DECLARE SCHEMECUR CURSOR FOR SELECT PRODUCT_CODE,MRP,QUANTITY FROM
	#TMPCMDSCHEMES WHERE MODE=1 AND QUANTITY>0 
	
	OPEN SCHEMECUR
	FETCH NEXT FROM SCHEMECUR INTO @CPRODUCTCODE,@NMRP,@NQTY
	
	WHILE @@FETCH_STATUS=0
	BEGIN
		SET @NSTEP=80
		SET @NLOOPCNT=1
		WHILE @NLOOPCNT<=ABS(@NQTY)
		BEGIN
			SET @NBUYAMT=@NBUYAMT-@NMRP	
		    
		    SET @NSTEP=90
		    
			IF @NBUYAMT<=0
			BEGIN
				SET @BQUALIFIED=1				
				BREAK
			END
		    
			IF @BQUALIFIED=1
				BREAK
				
			SET @NLOOPCNT=@NLOOPCNT+1
		END										
		
		SET @NSTEP=100
		IF @BQUALIFIED=1
			BREAK		
		FETCH NEXT FROM SCHEMECUR INTO @CPRODUCTCODE,@NMRP,@NQTY
	END
	
	SET @NSTEP=110
	
	CLOSE SCHEMECUR
	DEALLOCATE SCHEMECUR
	

	
	IF @BQUALIFIED=1
	BEGIN
		GOTO EXIT_PROC
	END
	
	IF @CMRPORDER='ASC'
		GOTO LBL5THCASE
---------- 1ST CASE ENDS HERE
	
LBL2NDCASE:
	--SELECT 'HANDLE 2ND CASE'

					
	IF @BRETRY2NDCASE=0
		SET @CMRPORDER=''
	
	SELECT @NREQGETAMT=0,@NREQBUYAMT=0

	DELETE FROM #TMPCMDSCHEMES
	
	INSERT #TMPCMDSCHEMES (PRODUCT_CODE,MRP,QUANTITY,ROW_ID,MODE,DISCOUNT_AMOUNT,SCHEME_APPLIED_QTY)
	SELECT PRODUCT_CODE,MRP,QUANTITY,ROW_ID,MODE,0,0 FROM #TEMPCMDPREV

	--SELECT @NREQBUYAMT,'CHK2NDCASE',PRODUCT_CODE,MRP,QUANTITY,ROW_ID,MODE 
	--FROM #TMPCMDSCHEMES 
	
	SET @NSTEP=30
	
	IF @CMRPORDER=''
		DECLARE SCHEMECUR CURSOR FOR SELECT PRODUCT_CODE,MRP,QUANTITY,ROW_ID,MODE FROM
		#TMPCMDSCHEMES WHERE MODE=1 AND PRODUCT_CODE NOT IN
		(SELECT PRODUCT_CODE FROM #TMPCMDSCHEMES WHERE MODE=2)  ORDER BY MRP 
	ELSE
		DECLARE SCHEMECUR CURSOR FOR SELECT PRODUCT_CODE,MRP,QUANTITY,ROW_ID,MODE FROM
		#TMPCMDSCHEMES WHERE MODE=1 AND PRODUCT_CODE NOT IN
		(SELECT PRODUCT_CODE FROM #TMPCMDSCHEMES WHERE MODE=2) ORDER BY MRP DESC
	
	OPEN SCHEMECUR
	FETCH NEXT FROM SCHEMECUR INTO @CPRODUCTCODE,@NMRP,@NQTY,@CCMDROWID,@NMODE
	WHILE @@FETCH_STATUS=0
	BEGIN
		SET @NSTEP=40
		SET @NLOOPCNT=1
		WHILE @NLOOPCNT<=ABS(@NQTY)
		BEGIN
			SET @NREQBUYAMT=@NREQBUYAMT+@NMRP									
		    
		    SET @NSTEP=50
			UPDATE #TMPCMDSCHEMES SET QUANTITY=QUANTITY-1,
			SCHEME_APPLIED_QTY=SCHEME_APPLIED_QTY+1
			WHERE ROW_ID=@CCMDROWID
		    
		    PRINT '2:'+ STR(@NREQGETAMT)+STR(@NGETAMT)
			IF @NREQBUYAMT>=@NORGBUYAMT
			BEGIN
				SET @BQUALIFIED=1				
				BREAK
			END
		    
		    SET @NSTEP=60
			IF @BQUALIFIED=1
				BREAK
				
			SET @NLOOPCNT=@NLOOPCNT+1
		END										
		
		IF @BQUALIFIED=1
			BREAK
		
		FETCH NEXT FROM SCHEMECUR INTO @CPRODUCTCODE,@NMRP,@NQTY,@CCMDROWID,@NMODE
	END
	CLOSE SCHEMECUR
	DEALLOCATE SCHEMECUR

	IF @BQUALIFIED=1
		GOTO LBLCHK2NDCASEGET
	
	
	--SELECT @NREQBUYAMT,'CHKOTHERITEMS',PRODUCT_CODE,MRP,QUANTITY,ROW_ID,MODE 
	--FROM #TMPCMDSCHEMES 
			
	IF @CMRPORDER=''
		DECLARE SCHEMECUR CURSOR FOR SELECT DISTINCT PRODUCT_CODE,MRP,QUANTITY,ROW_ID FROM
		#TMPCMDSCHEMES WHERE QUANTITY>0  ORDER BY MRP 
	ELSE
		DECLARE SCHEMECUR CURSOR FOR SELECT DISTINCT  PRODUCT_CODE,MRP,QUANTITY,ROW_ID FROM
		#TMPCMDSCHEMES WHERE QUANTITY>0 ORDER BY MRP DESC

	OPEN SCHEMECUR
	FETCH NEXT FROM SCHEMECUR INTO @CPRODUCTCODE,@NMRP,@NQTY,@CCMDROWID
	WHILE @@FETCH_STATUS=0
	BEGIN
		SET @NSTEP=40
		SET @NLOOPCNT=1
		WHILE @NLOOPCNT<=ABS(@NQTY)
		BEGIN
			SET @NREQBUYAMT=@NREQBUYAMT+@NMRP									
		    
		    SET @NSTEP=50
			UPDATE #TMPCMDSCHEMES SET QUANTITY=QUANTITY-1,
			SCHEME_APPLIED_QTY=SCHEME_APPLIED_QTY+1
			WHERE ROW_ID=@CCMDROWID
		    
		    PRINT '3:'+ STR(@NREQGETAMT)+STR(@NGETAMT)
			IF @NREQBUYAMT>=@NORGBUYAMT
			BEGIN
				SET @BQUALIFIED=1				
				BREAK
			END
		    
		    SET @NSTEP=60
			IF @BQUALIFIED=1
				BREAK
				
			SET @NLOOPCNT=@NLOOPCNT+1
		END										
		
		IF @BQUALIFIED=1
			BREAK
		
		FETCH NEXT FROM SCHEMECUR INTO @CPRODUCTCODE,@NMRP,@NQTY,@CCMDROWID
	END
	CLOSE SCHEMECUR
	DEALLOCATE SCHEMECUR
	
	--SELECT @NREQBUYAMT
	
	IF @BQUALIFIED=0
		GOTO LBL3RDCASE	
		
LBLCHK2NDCASEGET:								
	
	SET @NSTEP=70
	SELECT @BQUALIFIED=0,@NREQGETAMT=0
	
	--SELECT @NREQBUYAMT,@BRETRY2NDCASE, 'CHK3RDCASEGET', PRODUCT_CODE,MRP,QUANTITY,ROW_ID FROM
	--#TMPCMDSCHEMES WHERE MODE=2 AND QUANTITY>0 
	
	DECLARE SCHEMECUR CURSOR FOR SELECT PRODUCT_CODE,MRP,QUANTITY,ROW_ID FROM
	#TMPCMDSCHEMES WHERE MODE=2 AND QUANTITY>0 
	
	OPEN SCHEMECUR
	FETCH NEXT FROM SCHEMECUR INTO @CPRODUCTCODE,@NMRP,@NQTY,@CCMDROWID
	
	WHILE @@FETCH_STATUS=0
	BEGIN
		SET @BQUALIFIED=1
		
		SET @NSTEP=80
		SET @NLOOPCNT=1
		WHILE @NLOOPCNT<=ABS(@NQTY)
		BEGIN
			SET @NAMT=(CASE WHEN @NREQGETAMT+@NMRP>@NGETAMT THEN @NGETAMT-@NREQGETAMT
							ELSE @NMRP END)
							
			SET @NREQGETAMT=@NREQGETAMT+@NAMT
		    
		    SET @NSTEP=50
			UPDATE #TMPCMDSCHEMES SET DISCOUNT_AMOUNT=ISNULL(DISCOUNT_AMOUNT,0)+@NAMT,
			SCHEME_APPLIED_QTY=SCHEME_APPLIED_QTY+1
			WHERE ROW_ID=@CCMDROWID
		    
		    PRINT '4:'+ STR(@NREQGETAMT)+STR(@NGETAMT)
			IF @NREQGETAMT>=@NGETAMT
				BREAK

			SET @NLOOPCNT=@NLOOPCNT+1
		END										
		
		SET @NSTEP=100
		IF @NREQGETAMT>=@NGETAMT
			BREAK		
			
		FETCH NEXT FROM SCHEMECUR INTO @CPRODUCTCODE,@NMRP,@NQTY,@CCMDROWID
	END
	
	SET @NSTEP=110
	
	CLOSE SCHEMECUR
	DEALLOCATE SCHEMECUR
	
	--SELECT '2ND CASE',@BQUALIFIED,@NREQBUYAMT,@NREQGETAMT,@NBUYAMT,* FROM #TMPCMDSCHEMES
	
	
	IF @BQUALIFIED=1
	BEGIN
		GOTO EXIT_PROC
	END

	ELSE
	IF @BRETRY2NDCASE=1
		GOTO LBL5THCASE
		
LBL3RDCASE:
	
	IF @BRETRY2NDCASE=1
		GOTO LBL4THCASE

	--SELECT 'HANDLE 3RD CASE'
	
	DELETE FROM #TMPCMDSCHEMES
	
	INSERT #TMPCMDSCHEMES (PRODUCT_CODE,MRP,QUANTITY,ROW_ID,MODE,DISCOUNT_AMOUNT,SCHEME_APPLIED_QTY)
	SELECT PRODUCT_CODE,MRP,QUANTITY,ROW_ID,MODE,0,0 FROM #TEMPCMDPREV
	
	SELECT @CMRPORDER='DESC',@BRETRY2NDCASE=1
	
	--SELECT 'GOTO 3RD CASE'				
	GOTO LBL2NDCASE

LBL4THCASE:
	
	--SELECT 'HANDLE 4TH CASE'
	
	DELETE FROM #TMPCMDSCHEMES
	
	INSERT #TMPCMDSCHEMES (PRODUCT_CODE,MRP,QUANTITY,ROW_ID,MODE,DISCOUNT_AMOUNT,SCHEME_APPLIED_QTY)
	SELECT PRODUCT_CODE,MRP,QUANTITY,ROW_ID,MODE,0,0 FROM #TEMPCMDPREV
	
	--SELECT 'RECHECK',* FROM #TMPCMDSCHEMES
	SET @CMRPORDER='ASC'
	
	GOTO LBL1STCASE

LBL5THCASE:
	
	END TRY
	
	BEGIN CATCH
	  PRINT 'CATCH START'       
	  SET @CERRMSG='P:SP3S_EOSS_SCHEMES_1, STEP:'+LTRIM(RTRIM(STR(@NSTEP)))+', MESSAGE:'+ERROR_MESSAGE()        
	  GOTO EXIT_PROC
	END CATCH

EXIT_PROC:
		
	IF ISNULL(@CERRMSG,'')=''
	BEGIN
		IF @BQUALIFIED=0
		BEGIN
			UPDATE #TMPCMDSCHEMES SET DISCOUNT_AMOUNT=0
		END	
		ELSE
		BEGIN
			--SELECT 'SCHEMES FOUND',* FROM #TMPCMDSCHEMES
			
			SET @NSTEP=115
			UPDATE #TMPCMD SET DISCOUNT_AMOUNT=#TMPCMD.DISCOUNT_AMOUNT+(B.DISCOUNT_AMOUNT)*(CASE WHEN @BPROCESSSLRENTRY=1 THEN -1 ELSE 1 END),
			SLS_TITLE=SLS_TITLE+(CASE WHEN SLS_TITLE<>'' THEN ',' ELSE '' END)+@CSLSTITLE,SCHEME_SETUP_DET_ROW_ID=@CSCHEMEDETROWID,
			SCHEME_APPLIED_QTY=#TMPCMD.SCHEME_APPLIED_QTY+B.SCHEME_APPLIED_QTY
			FROM #TMPCMDSCHEMES B WHERE B.ROW_ID=#TMPCMD.CMD_ROW_ID 
			AND B.SCHEME_APPLIED_QTY<>0
			
			UPDATE #TMPCMD SET DISCOUNT_PERCENTAGE=ABS(ROUND((DISCOUNT_AMOUNT/(MRP*QUANTITY))*100,2)),
			NET=(MRP*QUANTITY)-DISCOUNT_AMOUNT
		END		

		IF @BPROCESSSLRENTRY=0 AND @CPICKSLRDISCMODE<>'3'
		BEGIN
			SET @BPROCESSSLRENTRY=1
			GOTO START_PROC
		END	
		ELSE
			GOTO END_PROC

	END	

END_PROC:

END
----- END OF PROCEDURE SP3S_EOSS_SCHEMES_1
