CREATE PROCEDURE SP3S_PUR_RGT
(
	@DFROMDT DATETIME,
	@DTODT DATETIME,
	@CFLT_HEAD VARCHAR(20)=''
)
--WITH ENCRYPTION
AS
BEGIN

IF OBJECT_ID('TEMPDB..#HEADS','U') IS NOT NULL
	DROP TABLE #HEADS

CREATE TABLE #HEADS(HEAD_CODE VARCHAR(10))	

INSERT #HEADS(HEAD_CODE)
SELECT * FROM DBO.FN3S_SUBHEADS(@CFLT_HEAD)

DECLARE @DTSQL NVARCHAR(MAX)
SET @DTSQL=N'	SELECT	
				  A.BILL_NO AS INV_NO
				, A.INV_DT AS INV_DT
				, B1.AC_NAME AS SUPPLIER
				, B1.CITY AS SUPPLIER_ADDRESS
				, B1.TIN_NO  AS TIN
				, SUM(PID.QUANTITY) AS QUANTITY
				, SUM( PID.RFNET-PID.TAX_AMOUNT ) AS SUBTOTAL
				,(F.FORM_NAME) AS TAX_PERCENTAGE
				,SUM(PID.TAX_AMOUNT) AS TAX_AMOUNT
				,SUM(PID.RFNET) AS TOTAL_AMOUNT,A.FREIGHT,A.OTHER_CHARGES
		FROM PIM01106 A  (NOLOCK)
		JOIN PID01106 PID (NOLOCK) ON A.MRR_ID=PID.MRR_ID
		JOIN FORM F (NOLOCK) ON PID.FORM_ID=F.FORM_ID
		JOIN LM01106 B (NOLOCK) ON F.TAX_AC_CODE = B.AC_CODE
		JOIN LMV01106 B1 (NOLOCK) ON A.AC_CODE = B1.AC_CODE
		LEFT JOIN #HEADS HD ON HD.HEAD_CODE = B.HEAD_CODE 
		WHERE A.RECEIPT_DT BETWEEN '''+CONVERT(VARCHAR,@DFROMDT,110)+''' AND '''+CONVERT(VARCHAR,@DTODT,110)+''' 
		AND A.MEMO_TYPE=1 AND  A.INV_MODE=1
		AND A.BILL_NO <> ''''  
		AND A.CANCELLED=0  
		AND  ROUND(A.SUBTOTAL,0) <>0  
		'+(CASE WHEN ISNULL(@CFLT_HEAD,'')='' THEN '' ELSE ' AND HD.HEAD_CODE IS NOT NULL ' END)+' 
		GROUP  BY	  A.INV_DT 
					, A.BILL_NO
					, B1.AC_NAME
					, B1.CITY
					, B1.TIN_NO  
					,(F.FORM_NAME)
					,A.FREIGHT
					,A.OTHER_CHARGES
		ORDER BY (F.FORM_NAME)'			
PRINT @DTSQL
EXEC SP_EXECUTESQL @DTSQL		
END
---END OF PROCEDURE - SP3S_PUR_RGT
