CREATE PROCEDURE SP_AGENCY_JOB_RATE
(
 @CAGENCY_CODE VARCHAR(100),
 @CJOB_CODE VARCHAR(10)
)
AS
BEGIN
     
    SELECT DISTINCT DEFAULT_BASIS, A.JOB_CODE,
	CASE WHEN ISNULL(DEFAULT_BASIS,0)=1  THEN JOB_RATE
				   WHEN ISNULL(DEFAULT_BASIS,0)=2  THEN JOB_RATE_PCS
				   WHEN ISNULL(DEFAULT_BASIS,0)=3  THEN JOB_RATE_DAYS
				   WHEN ISNULL(DEFAULT_BASIS,0)=4  THEN JOB_RATE_HOURS
			  ELSE 0 END AS JOB_RATE
	FROM AGENCY_JOBS A (NOLOCK)
	WHERE A.AGENCY_CODE=@CAGENCY_CODE
	AND A.JOB_CODE=@CJOB_CODE

END
