CREATE PROCEDURE SP_RETAILSALE_18--(LocId 3 digit change by Sanjay:06-11-2024)
(  
	 @CQUERYID			NUMERIC(2),  
	 @CWHERE			VARCHAR(MAX)='',  
	 @CFINYEAR			VARCHAR(5)='',  
	 @CDEPTID			VARCHAR(4)='',  
	 @NNAVMODE			NUMERIC(2)=1,  
	 @CWIZAPPUSERCODE	VARCHAR(10)='',  
	 @CREFMEMOID		VARCHAR(40)='',  
	 @CREFMEMODT		DATETIME='',  
	 @BINCLUDEESTIMATE	BIT=1,  
	 @CFROMDT			DATETIME='',  
	 @CTODT				VARCHAR(50)='',
	 @bCardDiscount		BIT=0,
	 @cCustCode			VARCHAR(15)=''
) 
AS  
BEGIN  
  SELECT A.*,B.PAYMODE_NAME,C.* ,CAST(0 AS BIT ) AS DELETED,        
   (CASE WHEN A.CURRENCY_CONVERSION_RATE> 0 THEN       
   CAST(A.AMOUNT/A.CURRENCY_CONVERSION_RATE AS NUMERIC(10,2)) ELSE A.AMOUNT END ) AS BASIC_AMOUNT,  
   ISNULL(S.CM_DT,ISNULL(R.ADV_REC_DT,'')) AS ADJ_MEMO_DT      
   FROM PAYMODE_XN_DET_HOLD A   (NOLOCK)      
   JOIN cmm_hold m (NOLOCK) ON m.hold_id=a.hold_id
   JOIN PAYMODE_MST B  (NOLOCK) ON B.PAYMODE_CODE=A.PAYMODE_CODE        
   JOIN PAYMODE_GRP_MST C  (NOLOCK) ON C.PAYMODE_GRP_CODE=B.PAYMODE_GRP_CODE        
   LEFT OUTER JOIN CMM01106 S  (NOLOCK) ON S.CM_ID=A.ADJ_MEMO_ID AND SUBSTRING(S.CM_NO,len(s.location_code)+3,1)='N'  
   LEFT OUTER JOIN ARC01106 R  (NOLOCK) ON R.ADV_REC_ID=A.ADJ_MEMO_ID AND R.ARC_TYPE=2    
   WHERE A.HOLD_ID=@CWHERE  AND m.hbd_location_code= @CDEPTID   
end

