CREATE PROCEDURE SP3S_CHECK_PARENTDATA
@CXNTYPE VARCHAR(10),
@CMEMOID VARCHAR(40),
@CLOCID VARCHAR(5),
@CSOURCEDB VARCHAR(200),
@CERRORMSG VARCHAR(MAX) OUTPUT
--WITH ENCRYPTION
AS
BEGIN
		
	DECLARE @CCMD NVARCHAR(MAX),@CTABLENAME VARCHAR(200),@CCHILDTABLENAME VARCHAR(200),@NSTEP INT,@CERRORMSGPROC VARCHAR(MAX),
			@CCHILDTEMPTABLE VARCHAR(500)
		
	DECLARE @TFKEYINFO TABLE (TABLENAME VARCHAR(200),CHILD_TABLENAME VARCHAR(200),CHILD_KEYFIELD VARCHAR(200),MERGE_ORDER INT)
	
	SET @CERRORMSG=''
	
	BEGIN TRY	
		
		SET @NSTEP = 10
		
		IF @CXNTYPE='PO'
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LM01106','POM01106',1)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LOCATION','POM01106',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('USERS','POM01106','EDT_USER_CODE',10)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('USERS','POM01106',15)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','POM01106',19)		
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('FORM','POD01106',21)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('ARTICLE','POD01106',23)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA1','POD01106',25)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA2','POD01106',28)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA3','POD01106',30)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA4','POD01106',35)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA5','POD01106',40)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA6','POD01106',45)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','POD01106',50)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('SKU','POD01106',55)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('ARTICLE','SKU',57)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA1','SKU',59)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA2','SKU',62)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA3','SKU',65)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA4','SKU',70)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA5','SKU',75)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA6','SKU',80)		
		END
		ELSE
		IF @CXNTYPE='PUR'
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LM01106','PIM01106',1)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LOCATION','PIM01106',10)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('USERS','PIM01106','EDT_USER_CODE',15)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('USERS','PIM01106',20)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('LM01106','PIM01106','BROKER_AC_CODE',25)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('EMPLOYEE','PIM01106',29)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','PIM01106',31)		
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('FORM','PID01106',33)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('ARTICLE','PID01106',35)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA1','PID01106',40)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA2','PID01106',45)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA3','PID01106',50)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA4','PID01106',55)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA5','PID01106',60)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA6','PID01106',65)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('ARTICLE','SKU',70)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA1','SKU',75)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA2','SKU',80)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA3','SKU',85)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA4','SKU',90)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA5','SKU',95)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA6','SKU',100)		
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('SKU','PID01106',105)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','PID01106',100)
		END
		ELSE
		IF @CXNTYPE='PO_ADJ'
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('USERS','PO_ADJ_MST','EDT_USER_CODE',1)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('USERS','PO_ADJ_MST',5)
		END
		ELSE
		IF @CXNTYPE='PBG'
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('USERS','PBM01106','EDT_USER_CODE',1)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('USERS','PBM01106',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LM01106','PBM01106',10)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('FORM','PBD01106',15)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('SKU','PBD01106',20)
		END
		ELSE
		IF @CXNTYPE='DNPS'
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('USERS','DNPS_MST','EDT_USER_CODE',1)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('USERS','DNPS_MST',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LM01106','DNPS_MST',10)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','DNPS_MST',15)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('LOCATION','DNPS_MST','PARTY_DEPT_ID',17)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('BIN','DNPS_MST','TARGET_BIN_ID',20)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('SKU','DNPS_DET',25)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','DNPS_DET',30)
		END
		ELSE
		IF @CXNTYPE='PRT'
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('USERS','RMM01106','EDT_USER_CODE',1)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('USERS','RMM01106',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LM01106','RMM01106',10)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('LM01106','RMM01106','BROKER_AC_CODE',14)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','RMM01106',17)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('BIN','RMM01106','TARGET_BIN_ID',20)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('LOCATION','RMM01106','PARTY_DEPT_ID',25)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LOCATION','RMD01106',30)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('SKU','RMD01106',35)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','RMD01106',40)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('FORM','RMD01106','ITEM_FORM_ID',45)
		END
		ELSE
		IF @CXNTYPE='SCF'
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('USERS','SCM01106','EDT_USER_CODE',1)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('USERS','SCM01106',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LOCATION','SCM01106',7)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LOCATION','SCC01106',10)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('ARTICLE','SCF01106',15)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA1','SCF01106',40)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA2','SCF01106',45)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA3','SCF01106',50)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA4','SCF01106',55)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA5','SCF01106',60)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA6','SCF01106',65)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('ARTICLE','SKU',70)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA1','SKU',75)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA2','SKU',80)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA3','SKU',85)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA4','SKU',90)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA5','SKU',95)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA6','SKU',100)		
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('SKU','SCC01106',105)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('SKU','SCF01106',110)
		END
		ELSE
		IF @CXNTYPE='IRR'
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('USERS','IRM01106','EDT_USER_CODE',1)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('USERS','IRM01106',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','IRM01106',7)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LOCATION','IRM01106',10)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('ARTICLE','IRD01106',15)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA1','IRD01106',40)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA2','IRD01106',45)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA3','IRD01106',50)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA4','IRD01106',55)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA5','IRD01106',60)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA6','IRD01106',65)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('ARTICLE','IRD01106','OLD_ARTICLE_CODE',70)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('PARA1','IRD01106','OLD_PARA1_CODE',75)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('PARA2','IRD01106','OLD_PARA2_CODE',80)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('PARA3','IRD01106','OLD_PARA3_CODE',85)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('PARA4','IRD01106','OLD_PARA4_CODE',90)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('PARA5','IRD01106','OLD_PARA5_CODE',95)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('PARA6','IRD01106','OLD_PARA6_CODE',100)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('UOM','IRD01106','OLD_UOM_CODE',105)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('UOM','IRD01106','UOM_CODE',107)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('FC','IRD01106','OLD_MRP_FC_CODE',110)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('FC','IRD01106','NEW_MRP_FC_CODE',112)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('ARTICLE','SKU',114)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA1','SKU',117)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA2','SKU',120)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA3','SKU',125)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA4','SKU',130)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA5','SKU',135)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA6','SKU',140)		
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('SKU','IRD01106',145)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('SKU','IRD01106','NEW_PRODUCT_CODE',150)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','IRD01106',155)
		END
		ELSE
		IF @CXNTYPE='APP'
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('USERS','APM01106',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LM01106','APM01106',10)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','APM01106',20)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('CUSTDYM','APM01106',25)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','APD01106',30)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('EMPLOYEE','APD01106','EMP_CODE',35)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('EMPLOYEE','APD01106','EMP_CODE1',40)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('EMPLOYEE','APD01106','EMP_CODE2',45)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LOCATION','APD01106',30)		
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('SKU','APD01106',50)
		END
		ELSE
		IF @CXNTYPE='APR'
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('USERS','APPROVAL_RETURN_MST',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LM01106','APPROVAL_RETURN_MST',10)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LOCATION','APPROVAL_RETURN_MST',20)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','APPROVAL_RETURN_MST',20)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('CUSTDYM','APPROVAL_RETURN_MST',25)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','APPROVAL_RETURN_DET',30)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('EMPLOYEE','APPROVAL_RETURN_DET',35)
		END
		ELSE
		IF @CXNTYPE IN ('ADV','ARC')
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('USERS','ARC01106',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('USERS','ARC01106','EDT_USER_CODE',7)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LM01106','ARC01106',10)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','ARC01106',20)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('CUSTDYM','ARC01106',25)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','ARC01106',30)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('EMPLOYEE','ARC01106',35)
		END
		ELSE
		IF @CXNTYPE='RPS'
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('USERS','RPS_MST',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','RPS_MST',10)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','RPS_DET',15)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('EMPLOYEE','RPS_DET','EMP_CODE',20)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('EMPLOYEE','RPS_DET','EMP_CODE1',25)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('EMPLOYEE','RPS_DET','EMP_CODE2',30)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('SKU','RPS_DET',35)
		END
		ELSE
		IF @CXNTYPE='SLS'
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('USERS','CMM01106',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('USERS','CMM01106','EDT_USER_CODE',7)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','CMM01106',10)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('DTM','CMM01106',12)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PAYMODE_MST','PAYMODE_XN_DET',7)			
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LM01106','CMM01106',15)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','CMM01106',25)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('CUSTDYM','CMM01106',30)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LOCATION','CMD01106',35)		
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','CMD01106',40)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('EMPLOYEE','CMD01106','EMP_CODE',45)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('EMPLOYEE','CMD01106','EMP_CODE1',50)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('EMPLOYEE','CMD01106','EMP_CODE2',55)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('SKU','CMD01106',60)
		END
		ELSE
		IF @CXNTYPE='PTC'
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('USERS','PEM01106',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LM01106','PED01106',10)
		END
		ELSE
		IF @CXNTYPE='HBD'
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('CUSTDYM','HOLD_BACK_DELIVER_MST',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('JOBS','HOLD_BACK_DELIVER_DET',10)
		END
		ELSE
		IF @CXNTYPE='WOD'
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('USERS','WSL_ORDER_MST',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('USERS','WSL_ORDER_MST','EDT_USER_CODE',7)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('USERS','WSL_ORDER_MST','CONVERTED_BY_USER_CODE',10)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LM01106','WSL_ORDER_MST',12)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('EMPLOYEE','WSL_ORDER_MST',20)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('EMPLOYEE','WSL_ORDER_MST','SALE_EMP_CODE',25)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('CUSTDYM','WSL_ORDER_MST',27)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('FC','WSL_ORDER_MST',30)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LOCATION','WSL_ORDER_MST',32)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('ARTICLE','WSL_ORDER_DET',35)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA1','WSL_ORDER_DET',40)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA2','WSL_ORDER_DET',45)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA3','WSL_ORDER_DET',50)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA4','WSL_ORDER_DET',55)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA5','WSL_ORDER_DET',60)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('PARA6','WSL_ORDER_DET',65)
		END
		ELSE
		IF @CXNTYPE='WPS'
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('USERS','WPS_MST',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('USERS','WPS_MST','EDT_USER_CODE',7)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','WPS_MST',10)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('BIN','WPS_MST','TARGET_BIN_ID',12)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LM01106','WPS_MST',15)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('LOCATION','WPS_MST','PARTY_DEPT_ID',22)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LOCATION','WPS_DET',25)		
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','WPS_DET',30)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('EMPLOYEE','WPS_DET','EMP_CODE',35)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('EMPLOYEE','WPS_DET','EMP_CODE1',40)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('EMPLOYEE','WPS_DET','EMP_CODE2',45)		
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('FORM','WPS_DET','ITEM_FORM_ID',50)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('SKU','WPS_DET',60)
		END
		ELSE
		IF @CXNTYPE='WSL'
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('USERS','INM01106',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('USERS','INM01106','EDT_USER_CODE',7)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','INM01106',10)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('BIN','INM01106','TARGET_BIN_ID',12)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LM01106','INM01106',15)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('LM01106','INM01106','BROKER_AC_CODE',22)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LOCATION','INM01106',27)		
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('LOCATION','INM01106','PARTY_DEPT_ID',29)	
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('EMPLOYEE','INM01106',31)		
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('LM01106','INM01106','RECEIVING_AC_CODE',33)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('DTM','INM01106',37)		
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LOCATION','IND01106',39)		
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','IND01106',41)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('EMPLOYEE','IND01106','EMP_CODE',43)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('EMPLOYEE','IND01106','EMP_CODE1',45)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('EMPLOYEE','IND01106','EMP_CODE2',47)		
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('FORM','IND01106','ITEM_FORM_ID',50)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('SKU','IND01106',60)
		END
		ELSE
		IF @CXNTYPE='WSR'
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('USERS','CNM01106',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('USERS','CNM01106','EDT_USER_CODE',7)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','CNM01106',10)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('BIN','CNM01106','TARGET_BIN_ID',12)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LM01106','CNM01106',15)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('LM01106','CNM01106','BROKER_AC_CODE',22)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('LOCATION','CNM01106','PARTY_DEPT_ID',30)		
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('LOCATION','CNM01106','BILLED_FROM_DEPT_ID',35)		
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('DTM','CNM01106',40)		
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LOCATION','CND01106',60)		
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','CND01106',65)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('EMPLOYEE','CND01106','EMP_CODE',70)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('EMPLOYEE','CND01106','EMP_CODE1',75)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('EMPLOYEE','CND01106','EMP_CODE2',80)		
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('FORM','CND01106','ITEM_FORM_ID',85)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('SKU','CND01106',90)
		END
		ELSE
		IF @CXNTYPE='JWI'
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('USERS','JOBWORK_ISSUE_MST',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('USERS','JOBWORK_ISSUE_MST','EDT_USER_CODE',7)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','JOBWORK_ISSUE_MST',10)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('PRD_AGENCY_MST','JOBWORK_ISSUE_MST','AGENCY_CODE',12)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LOCATION','JOBWORK_ISSUE_DET',25)		
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','JOBWORK_ISSUE_DET',30)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('JOBS','JOBWORK_ISSUE_DET',50)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('SKU','JOBWORK_ISSUE_DET',60)
		END
		ELSE
		IF @CXNTYPE='JWR'
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('USERS','JOBWORK_RECEIPT_MST',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('USERS','JOBWORK_RECEIPT_MST','EDT_USER_CODE',7)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','JOBWORK_RECEIPT_MST',10)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('PRD_AGENCY_MST','JOBWORK_RECEIPT_MST','AGENCY_CODE',12)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LM01106','JOBWORK_RECEIPT_MST',15)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LOCATION','JOBWORK_RECEIPT_MST',25)		
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('JOBS','JOBWORK_RECEIPT_MST',30)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','JOBWORK_RECEIPT_DET',40)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('SKU','JOBWORK_RECEIPT_DET',50)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('SKU','JOBWORK_RECEIPT_CON_DET',55)
		END
		ELSE
		IF @CXNTYPE='CNC'
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('USERS','ICM01106',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('USERS','ICM01106','EDT_USER_CODE',7)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','ICM01106',10)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LOCATION','ICM01106',15)		
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LOCATION','ICD01106',25)		
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','ICD01106',30)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('SKU','ICD01106',60)
		END
		ELSE
		IF @CXNTYPE='ACT'
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('USERS','VM01106',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('USERS','VM01106','AUDITED_USER_CODE',7)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LOCATION','VM01106',10)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('VCHTYPE','VM01106',12)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('LM01106','VD01106',15)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('LM01106','VD01106','COST_CENTER_AC_CODE',15)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('LM01106','VD01106','VS_AC_CODE',15)
		END												
		ELSE
		IF @CXNTYPE='ATD'
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('EMP_MST','EMP_WPAYATT',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('EMP_SHIFTS','EMP_WPAYATT',10)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('LOCATION','EMP_WPAYATT','LOCATION_ID',15)
		END													
		ELSE
		IF @CXNTYPE='BCO'
		BEGIN
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('BIN','FLOOR_ST_DET','SOURCE_BIN_ID',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('SKU','FLOOR_ST_DET','PRODUCT_CODE',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD,MERGE_ORDER) VALUES ('BIN','FLOOR_ST_MST','TARGET_BIN_ID',5)
			INSERT @TFKEYINFO (TABLENAME,CHILD_TABLENAME,MERGE_ORDER) VALUES ('BIN','FLOOR_ST_MST',10)
		END													
		
		BEGIN TRANSACTION
		
		SET @NSTEP=30
		SET @CERRORMSGPROC=''
		
		EXEC SP3S_GET_COMPANY_FKEYDATA	
		@CLOCID=@CLOCID,
		@CERRORMSG=@CERRORMSGPROC OUTPUT
		
		IF ISNULL(@CERRORMSGPROC,'')<>''
			GOTO END_PROC
		
		SET @NSTEP=35	
		DECLARE @CCHILDKEYFIELD VARCHAR(100),@CTABLESUFFIX VARCHAR(200)
		
		SELECT @CTABLESUFFIX=REPLACE(@CMEMOID,'-','_')
		
		IF CURSOR_STATUS('GLOBAL','FKEYCUR') IN (0,1)  
		BEGIN  
		   CLOSE FKEYCUR  
		   DEALLOCATE FKEYCUR
		END      
		
		DECLARE FKEYCUR CURSOR FOR SELECT TABLENAME,CHILD_TABLENAME,CHILD_KEYFIELD FROM @TFKEYINFO 
		OPEN FKEYCUR
		FETCH NEXT FROM FKEYCUR INTO @CTABLENAME,@CCHILDTABLENAME,@CCHILDKEYFIELD	
		WHILE @@FETCH_STATUS=0
		BEGIN
			SET @CERRORMSGPROC=''
			
			IF ISNULL(@CCHILDKEYFIELD,'')=''
				SELECT @CCHILDKEYFIELD=KEYFIELD FROM MIRRORXNSINFO WHERE TABLENAME=@CTABLENAME
			
			SET @CCHILDTEMPTABLE=@CSOURCEDB+'TMP_'+@CXNTYPE+'_'+@CCHILDTABLENAME+'_'+@CTABLESUFFIX	
			
			IF OBJECT_ID(@CCHILDTEMPTABLE,'U') IS NOT NULL
			BEGIN
				SET @CCMD=N'EXEC SP3S_GET_'+@CTABLENAME+'_FKEYDATA '''+@CSOURCEDB+''','''+@CCHILDTABLENAME+''',
							'''+@CCHILDKEYFIELD+''','''+@CXNTYPE+''','''+@CTABLESUFFIX+''','''+@CLOCID+''',
							@CERRORMSGPROC OUTPUT'
				PRINT ISNULL(@CCMD,'NULL COOMAND FOR SP3S_GET_'+@CTABLENAME+'_FKEYDATA')
				EXEC SP_EXECUTESQL @CCMD,N'@CERRORMSGPROC VARCHAR(MAX) OUTPUT',@CERRORMSGPROC OUTPUT
			END
			
			IF ISNULL(@CERRORMSGPROC,'')<>''
				GOTO END_PROC

			FETCH NEXT FROM FKEYCUR INTO @CTABLENAME,@CCHILDTABLENAME,@CCHILDKEYFIELD
		END
		
		CLOSE FKEYCUR  
		DEALLOCATE FKEYCUR
		
		GOTO END_PROC
	END TRY	
	
	BEGIN CATCH
		SELECT @CERRORMSG='PROCEDURE SP3S_CHECK_PARENTDATA : '+ISNULL(ERROR_PROCEDURE(),'NULL P')+'STEP :'+STR(ISNULL(@NSTEP,0))+ ' LINE NO. :'+
		ISNULL(LTRIM(RTRIM(STR(ERROR_LINE()))),'NULL LINE')+'MSG :'+ISNULL(ERROR_MESSAGE(),'NULL MSG')
		
		GOTO END_PROC
	END CATCH

END_PROC:

	IF ISNULL(@CERRORMSGPROC,'')<>''
		SET @CERRORMSG=@CERRORMSGPROC
				
	IF @@TRANCOUNT>0
	BEGIN
		IF ISNULL(@CERRORMSG,'')=''
			COMMIT TRANSACTION
		ELSE
			ROLLBACK	
	END	
	
END
-----END OF PROCEDURE SP3S_CHECK_PARENTDATA
