CREATE PROCEDURE SP_WL_PENDINGCN--(LocId 3 digit change by Sanjay:30-10-2024)
(
	@CCUSTOMERCODE VARCHAR(40),
	@CCURCMID VARCHAR(40)=''
)
--WITH ENCRYPTION
AS
BEGIN
	SELECT  '0000001' AS TYPE, B.CM_NO AS MEMO_NO, B.CM_ID AS MEMO_ID, ABS(A.AMOUNT) AS NET_AMOUNT ,B.CM_DT AS [MEMO_DT]  
	 FROM PAYMODE_XN_DET A  (NOLOCK)     
	 JOIN CMM01106 B (NOLOCK) ON A.MEMO_ID = B.CM_ID      
	 LEFT OUTER JOIN      
	 (      
	  SELECT P.ADJ_MEMO_ID       
	  FROM PAYMODE_XN_DET P (NOLOCK)     
	  JOIN CMM01106 Q (NOLOCK) ON P.MEMO_ID = Q.CM_ID      
	  WHERE P.PAYMODE_CODE = '0000001'      
	  AND   Q.CANCELLED = 0      
	  AND   Q.CM_ID <> @CCURCMID  
	  
	  UNION ALL  
	    
	  SELECT P.ADJ_MEMO_ID       
	  FROM PAYMODE_XN_DET P (NOLOCK)     
	  JOIN ARC01106 Q (NOLOCK) ON P.MEMO_ID = Q.ADV_REC_ID      
	  WHERE P.PAYMODE_CODE = '0000001'      
	  AND   Q.CANCELLED = 0      
	  AND   Q.ADV_REC_ID <> @CCURCMID  
		  	  
	 ) X ON B.CM_ID = X.ADJ_MEMO_ID      
	 WHERE B.CUSTOMER_CODE =@CCUSTOMERCODE  AND SUBSTRING(B.CM_NO,len(b.location_code)+3,1)='N' 
	 AND A.PAYMODE_CODE = '0000004'      
	 AND B.CANCELLED = 0  
	 AND A.AMOUNT < 0      
	 AND X.ADJ_MEMO_ID IS NULL      
	    
	 UNION ALL      
	    
	 SELECT '0000002' AS TYPE, ADV_REC_NO AS MEMO_NO, ADV_REC_ID AS MEMO_ID, 
	-- ABS(NET_AMOUNT) AS AMOUNT,
	  ABS(AMOUNT) AS AMOUNT,
	 A.ADV_REC_DT AS [MEMO_DT]      
	 FROM ARC01106 A (NOLOCK)     
	 LEFT OUTER JOIN      
	 (      
	  SELECT P.ADJ_MEMO_ID       
	  FROM PAYMODE_XN_DET P (NOLOCK)     
	  JOIN CMM01106 Q (NOLOCK) ON P.MEMO_ID = Q.CM_ID      
	  WHERE P.PAYMODE_CODE = '0000002'      
	  AND   Q.CANCELLED = 0      
	  AND   Q.CM_ID <> @CCURCMID  
	  UNION
	  SELECT P.ADJ_MEMO_ID       
	  FROM PAYMODE_XN_DET P   (NOLOCK)   
	  JOIN ARC01106 Q (NOLOCK) ON P.MEMO_ID = Q.ADV_REC_ID      
	  WHERE P.PAYMODE_CODE = '0000002'      
	  AND   Q.CANCELLED = 0      
	  AND   Q.ADV_REC_ID <> @CCURCMID    
	 ) X ON A.ADV_REC_ID = X.ADJ_MEMO_ID      
	 WHERE A.CUSTOMER_CODE =@CCUSTOMERCODE AND (A.ARC_TYPE = 1 AND A.ARCT = 2)  
	 AND   A.CANCELLED = 0      
	 AND   X.ADJ_MEMO_ID IS NULL  
	
END
