create PROCEDURE SP3S_GST_TAX_CAL_OH
(
  @CXN_TYPE VARCHAR(10)='',
  @NSPID VARCHAR(40)=0,
  @BREGISTERED_DELEER INT=1,
  @CLOC_GSTN_NO VARCHAR(100)='',
  @CPARTY_GSTN_NO VARCHAR(100)='',
  @CCURSTATE_CODE VARCHAR(10)='',
  @CPARTYSTATE_CODE VARCHAR(10)='',
  @CERRMSG VARCHAR(200) OUTPUT ,
  @BDONOTCALGSTINOH BIT=0
)
AS
BEGIN
      
      DECLARE @FREIGHT_HSN_CODE VARCHAR(15),@OTHER_CHARGES_HSN_CODE VARCHAR(15),
              @INSURANCE_HSN_CODE VARCHAR(15),@PACKING_HSN_CODE VARCHAR(15),@CSTEP VARCHAR(10),
			  @MANUAL_GST_PER_FREIGHT bit ,@MANUAL_GST_PER_OTH bit 
      
              
       BEGIN TRY 
      SET @CERRMSG=''
      SET @CSTEP='00'


      UPDATE TMP SET FREIGHT_TAXABLE_VALUE = ISNULL(FREIGHT_TAXABLE_VALUE,0),
	  OTHER_CHARGES_TAXABLE_VALUE = ISNULL(OTHER_CHARGES_TAXABLE_VALUE,0),
	  PACKING_TAXABLE_VALUE = ISNULL(PACKING_TAXABLE_VALUE,0),
	  INSURANCE_TAXABLE_VALUE = ISNULL(INSURANCE_TAXABLE_VALUE,0)
	  FROM GST_TAXINFO_CALC_OH TMP (NOLOCK)
	  WHERE TMP.SP_ID=LTRIM(RTRIM((@NSPID)))
		
		      
      IF (ISNULL(@BREGISTERED_DELEER,0)=1 and isnull(@BDONOTCALGSTINOH,0)=0)
      BEGIN
      
          IF @CXN_TYPE IN('PUR','PO','PRT','jwr','wsl','WSR')
          BEGIN
              
              SELECT @FREIGHT_HSN_CODE=FREIGHT_HSN_CODE  ,
                     @INSURANCE_HSN_CODE=INSURANCE_HSN_CODE ,
                     @OTHER_CHARGES_HSN_CODE=OTHER_CHARGES_HSN_CODE,
                     @PACKING_HSN_CODE=PACKING_HSN_CODE,
					 @MANUAL_GST_PER_FREIGHT=isnull(MANUAL_GST_PER_FREIGHT,0),
                     @MANUAL_GST_PER_OTH=isnull(MANUAL_GST_PER_OTH,0)
              FROM GST_TAXINFO_CALC_OH (NOLOCK) WHERE SP_ID=LTRIM(RTRIM((@NSPID)))  
             

			 IF ISNULL(@FREIGHT_HSN_CODE,'') IN('0000000000','') and @MANUAL_GST_PER_FREIGHT<>1
			 BEGIN
			       
				    IF EXISTS(SELECT TOP 1 'U' FROM GST_OH_CONFIG WHERE XN_TYPE=@CXN_TYPE)
					   SELECT TOP 1 @FREIGHT_HSN_CODE=HSN_CODE FROM GST_OH_CONFIG WHERE OH_NAME='FREIGHT' AND XN_TYPE=@CXN_TYPE
					ELSE 
					SELECT TOP 1 @FREIGHT_HSN_CODE=HSN_CODE FROM GST_OH_CONFIG WHERE OH_NAME='FREIGHT' 
					
			 END

			  IF ISNULL(@OTHER_CHARGES_HSN_CODE,'') IN('0000000000','') and @MANUAL_GST_PER_OTH<>1
			 BEGIN
			       
				    IF EXISTS(SELECT TOP 1 'U' FROM GST_OH_CONFIG WHERE XN_TYPE=@CXN_TYPE)
					   SELECT TOP 1 @OTHER_CHARGES_HSN_CODE=HSN_CODE FROM GST_OH_CONFIG WHERE OH_NAME='OC' AND XN_TYPE=@CXN_TYPE
					ELSE 
					SELECT TOP 1 @OTHER_CHARGES_HSN_CODE=HSN_CODE FROM GST_OH_CONFIG WHERE OH_NAME='OC' 
					
			 END

			 IF @CXN_TYPE='WSL'
			 begin
			      
				  
					 IF ISNULL(@INSURANCE_HSN_CODE,'') IN('0000000000','')
					 BEGIN
			       
							IF EXISTS(SELECT TOP 1 'U' FROM GST_OH_CONFIG WHERE XN_TYPE=@CXN_TYPE)
							   SELECT TOP 1 @INSURANCE_HSN_CODE=HSN_CODE FROM GST_OH_CONFIG WHERE OH_NAME='INSURANCE' AND XN_TYPE=@CXN_TYPE
							ELSE 
							SELECT TOP 1 @INSURANCE_HSN_CODE=HSN_CODE FROM GST_OH_CONFIG WHERE OH_NAME='INSURANCE' 
					
					 END

					  IF ISNULL(@PACKING_HSN_CODE,'') IN('0000000000','')
					 BEGIN
			       
							IF EXISTS(SELECT TOP 1 'U' FROM GST_OH_CONFIG WHERE XN_TYPE=@CXN_TYPE)
							   SELECT TOP 1 @PACKING_HSN_CODE=HSN_CODE FROM GST_OH_CONFIG WHERE OH_NAME='PACKING' AND XN_TYPE=@CXN_TYPE
							ELSE 
							SELECT TOP 1 @PACKING_HSN_CODE=HSN_CODE FROM GST_OH_CONFIG WHERE OH_NAME='PACKING' 
					
					 END


			 end
			
          
       
          end
          ELSE
          BEGIN
			   IF EXISTS(SELECT TOP 1 'U' FROM GST_OH_CONFIG WHERE XN_TYPE=@CXN_TYPE)
			   BEGIN
					SELECT TOP 1 @FREIGHT_HSN_CODE=HSN_CODE FROM GST_OH_CONFIG WHERE OH_NAME='FREIGHT' AND XN_TYPE=@CXN_TYPE
					SELECT TOP 1 @INSURANCE_HSN_CODE=HSN_CODE FROM GST_OH_CONFIG WHERE OH_NAME='INSURANCE' AND XN_TYPE=@CXN_TYPE
					SELECT TOP 1 @OTHER_CHARGES_HSN_CODE=HSN_CODE FROM GST_OH_CONFIG WHERE OH_NAME='OC' AND XN_TYPE=@CXN_TYPE
					SELECT TOP 1 @PACKING_HSN_CODE=HSN_CODE FROM GST_OH_CONFIG WHERE OH_NAME='PACKING' AND XN_TYPE=@CXN_TYPE
	           
			   END
			   ELSE
			   BEGIN
					SELECT TOP 1 @FREIGHT_HSN_CODE=HSN_CODE FROM GST_OH_CONFIG WHERE OH_NAME='FREIGHT' 
					SELECT TOP 1 @INSURANCE_HSN_CODE=HSN_CODE FROM GST_OH_CONFIG WHERE OH_NAME='INSURANCE' 
					SELECT TOP 1 @OTHER_CHARGES_HSN_CODE=HSN_CODE FROM GST_OH_CONFIG WHERE OH_NAME='OC'  
					SELECT TOP 1 @PACKING_HSN_CODE=HSN_CODE FROM GST_OH_CONFIG WHERE OH_NAME='PACKING'  
	           
			   END
           END
           
          
            SET @CSTEP='10'     
            SELECT TOP 1 @CERRMSG=CASE WHEN ISNULL(OTHER_CHARGES,0)>0 AND ISNULL(@OTHER_CHARGES_HSN_CODE,'') IN ('','0000000000')  and @MANUAL_GST_PER_OTH<>1
                                                THEN 'OTHER CHARGES HSN CODE NOT FOUND'
                                       WHEN ISNULL(INSURANCE,0)>0 AND ISNULL(@INSURANCE_HSN_CODE,'') IN ('','0000000000') 
                                                THEN 'INSURANCE HSN CODE NOT FOUND'
                                       WHEN ISNULL(PACKING,0)>0 AND ISNULL(@PACKING_HSN_CODE,'') IN ('','0000000000') 
                                                THEN 'PACKING HSN CODE NOT FOUND'
                                       WHEN ISNULL(FREIGHT,0)>0 AND ISNULL(@FREIGHT_HSN_CODE,'') IN ('','0000000000')  and @MANUAL_GST_PER_FREIGHT<>1
                                                THEN 'FREIGHT HSN CODE NOT FOUND'
                                  ELSE '' END
            FROM GST_TAXINFO_CALC_OH (NOLOCK)
            WHERE SP_ID=LTRIM(RTRIM((@NSPID))) 
            
            SET @CSTEP='20'
            
            IF ISNULL(@CERRMSG,'')<>''
            RETURN
            
            --UPDATE OH HSN CODE
            UPDATE TMP SET FREIGHT_HSN_CODE=CASE WHEN ISNULL(FREIGHT,0)<>0 THEN  @FREIGHT_HSN_CODE ELSE '0000000000' END,
                           OTHER_CHARGES_HSN_CODE=CASE WHEN ISNULL(OTHER_CHARGES,0)<>0 THEN  @OTHER_CHARGES_HSN_CODE ELSE '0000000000' END,
                           INSURANCE_HSN_CODE=CASE WHEN ISNULL(INSURANCE,0)<>0 THEN  @INSURANCE_HSN_CODE ELSE '0000000000' END,
                           PACKING_HSN_CODE=CASE WHEN ISNULL(PACKING,0)<>0 THEN  @PACKING_HSN_CODE ELSE '0000000000' END,
                           ISIGST=CASE WHEN @CCURSTATE_CODE<>@CPARTYSTATE_CODE THEN 1 ELSE 0 END
            FROM GST_TAXINFO_CALC_OH TMP (NOLOCK)
            WHERE TMP.SP_ID=LTRIM(RTRIM((@NSPID))) 
            
          
            
              SET @CSTEP='30'
              
             --MAXIMUM OC GST PERCENTAGE PICK 
                DECLARE @OCGST_PERCENTAGE NUMERIC(10,2),@FREIGHTGST_PERCENTAGE NUMERIC(10,2),
                        @PACKINGGST_PERCENTAGE NUMERIC(10,2),@INSURANCEGST_PERCENTAGE NUMERIC(10,2),
                        @MAXGST_PERCENTAGE NUMERIC(10,2),@DMEMO_DT DATETIME
                
              IF @CXN_TYPE IN('PUR','PBM','PO','prt','jwr','wsl','WSR')
              BEGIN
                   
                   
                   SELECT TOP 1 @DMEMO_DT=MEMO_DT FROM GST_TAXINFO_CALC WHERE SP_ID =LTRIM(RTRIM((@NSPID)))  
                   
                   IF EXISTS(SELECT TOP 1 'U' FROM GST_TAXINFO_CALC_OH WHERE SP_ID=LTRIM(RTRIM((@NSPID))) AND ISNULL(OTHER_CHARGES,0)<>0   ) and  @MANUAL_GST_PER_OTH<>1
                   BEGIN
						IF OBJECT_ID('TEMPDB..#TMPOCHSN','U') IS NOT NULL
						   DROP TABLE #TMPOCHSN

						;WITH CTE AS
						(
						SELECT B.HSN_CODE,ISNULL(C.TAX_PERCENTAGE,0) AS TAX_PERCENTAGE,ISNULL(C.RATE_CUTOFF,0) AS RATE_CUTOFF,
							   ISNULL(C.RATE_CUTOFF_TAX_PERCENTAGE,0) AS RATE_CUTOFF_TAX_PERCENTAGE,
							  ISNULL(C.WEF,'') AS WEF,ISNULL(B.TAXABLE_ITEM,'') AS TAXABLE_ITEM,ISNULL(B.HSN_TYPE ,'') AS HSN_TYPE  ,
							  SR=ROW_NUMBER() OVER (PARTITION BY A.SP_ID ORDER BY C.WEF DESC)
						FROM GST_TAXINFO_CALC_OH A (NOLOCK)
						JOIN HSN_MST B (NOLOCK) ON A.OTHER_CHARGES_HSN_CODE =B.HSN_CODE 
						LEFT JOIN HSN_DET C (NOLOCK) ON B.HSN_CODE =C.HSN_CODE AND C.WEF  <=@DMEMO_DT 
						WHERE A.SP_ID =LTRIM(RTRIM((@NSPID)))  
						)

					   SELECT * INTO #TMPOCHSN FROM CTE WHERE SR=1
						
					   UPDATE TMP SET  OTHER_CHARGES_TAXABLE_VALUE = ROUND(OTHER_CHARGES-(OTHER_CHARGES*(CASE WHEN OH_TAX_METHOD=2 THEN (HM.RATE_CUTOFF_TAX_PERCENTAGE/  
												   (100 + HM.RATE_CUTOFF_TAX_PERCENTAGE)) ELSE 0 END)),2)
					   FROM GST_TAXINFO_CALC_OH  TMP (NOLOCK)
					   JOIN #TMPOCHSN HM (NOLOCK) ON HM.HSN_CODE=TMP.OTHER_CHARGES_HSN_CODE 
					   WHERE TMP.SP_ID=LTRIM(RTRIM((@NSPID))) 
					    
					   PRINT '6.UPDATE GST PERCENTAGE '
	                        
					   UPDATE TMP SET OTHER_CHARGES_GST_PERCENTAGE=ISNULL(CASE WHEN HM.RATE_CUTOFF<ABS(TMP.OTHER_CHARGES_TAXABLE_VALUE) THEN HM.TAX_PERCENTAGE ELSE RATE_CUTOFF_TAX_PERCENTAGE END ,0),
					   OTHER_CHARGES_GST_AMOUNT=0
					   FROM GST_TAXINFO_CALC_OH TMP (NOLOCK)
					   JOIN #TMPOCHSN HM (NOLOCK) ON HM.HSN_CODE=TMP.OTHER_CHARGES_HSN_CODE 
					   WHERE TMP.SP_ID=LTRIM(RTRIM((@NSPID)))
	
					END	
					
				  IF EXISTS(SELECT TOP 1 'U' FROM GST_TAXINFO_CALC_OH WHERE SP_ID=LTRIM(RTRIM((@NSPID))) AND ISNULL(FREIGHT,0)<>0  ) and @MANUAL_GST_PER_FREIGHT<>1
                   BEGIN
						IF OBJECT_ID('TEMPDB..#TMPFREIGHTHSN','U') IS NOT NULL
						   DROP TABLE #TMPFREIGHTHSN

						;WITH CTE AS
						(
						SELECT B.HSN_CODE,ISNULL(C.TAX_PERCENTAGE,0) AS TAX_PERCENTAGE,ISNULL(C.RATE_CUTOFF,0) AS RATE_CUTOFF,
							   ISNULL(C.RATE_CUTOFF_TAX_PERCENTAGE,0) AS RATE_CUTOFF_TAX_PERCENTAGE,
							  ISNULL(C.WEF,'') AS WEF,ISNULL(B.TAXABLE_ITEM,'') AS TAXABLE_ITEM,ISNULL(B.HSN_TYPE ,'') AS HSN_TYPE  ,
							  SR=ROW_NUMBER() OVER (PARTITION BY A.SP_ID ORDER BY C.WEF DESC)
						FROM GST_TAXINFO_CALC_OH A (NOLOCK)
						JOIN HSN_MST B (NOLOCK) ON A.FREIGHT_HSN_CODE =B.HSN_CODE 
						LEFT JOIN HSN_DET C (NOLOCK) ON B.HSN_CODE =C.HSN_CODE AND C.WEF  <=@DMEMO_DT 
						WHERE A.SP_ID =LTRIM(RTRIM((@NSPID)))  
						)

					   SELECT * INTO #TMPFREIGHTHSN FROM CTE WHERE SR=1
						
					   UPDATE TMP SET  FREIGHT_TAXABLE_VALUE = ROUND(FREIGHT-(FREIGHT*(CASE WHEN OH_TAX_METHOD=2 THEN (HM.RATE_CUTOFF_TAX_PERCENTAGE/  
												   (100 + HM.RATE_CUTOFF_TAX_PERCENTAGE)) ELSE 0 END)),2)
					   FROM GST_TAXINFO_CALC_OH  TMP (NOLOCK)
					   JOIN #TMPFREIGHTHSN HM (NOLOCK) ON HM.HSN_CODE=TMP.FREIGHT_HSN_CODE 
					   WHERE TMP.SP_ID=LTRIM(RTRIM((@NSPID))) 
					    
					   PRINT '6.UPDATE GST PERCENTAGE '
	                        
					   UPDATE TMP SET FREIGHT_GST_PERCENTAGE=ISNULL(CASE WHEN HM.RATE_CUTOFF<ABS(TMP.FREIGHT_TAXABLE_VALUE) THEN HM.TAX_PERCENTAGE ELSE RATE_CUTOFF_TAX_PERCENTAGE END ,0),
					   FREIGHT_GST_AMOUNT=0
					   FROM GST_TAXINFO_CALC_OH TMP (NOLOCK)
					   JOIN #TMPFREIGHTHSN HM (NOLOCK) ON HM.HSN_CODE=TMP.FREIGHT_HSN_CODE 
					   WHERE TMP.SP_ID=LTRIM(RTRIM((@NSPID)))
	
					END	


					IF @CXN_TYPE IN('WSL')
					BEGIN
					     
						
						  IF EXISTS(SELECT TOP 1 'U' FROM GST_TAXINFO_CALC_OH WHERE SP_ID=LTRIM(RTRIM((@NSPID))) AND ISNULL(insurance,0)<>0  )
						   BEGIN
								IF OBJECT_ID('TEMPDB..#TMPinsuranceHSN','U') IS NOT NULL
								   DROP TABLE #TMPinsuranceHSN

								;WITH CTE AS
								(
								SELECT B.HSN_CODE,ISNULL(C.TAX_PERCENTAGE,0) AS TAX_PERCENTAGE,ISNULL(C.RATE_CUTOFF,0) AS RATE_CUTOFF,
									   ISNULL(C.RATE_CUTOFF_TAX_PERCENTAGE,0) AS RATE_CUTOFF_TAX_PERCENTAGE,
									  ISNULL(C.WEF,'') AS WEF,ISNULL(B.TAXABLE_ITEM,'') AS TAXABLE_ITEM,ISNULL(B.HSN_TYPE ,'') AS HSN_TYPE  ,
									  SR=ROW_NUMBER() OVER (PARTITION BY A.SP_ID ORDER BY C.WEF DESC)
								FROM GST_TAXINFO_CALC_OH A (NOLOCK)
								JOIN HSN_MST B (NOLOCK) ON A.insurance_hsn_code =B.HSN_CODE 
								LEFT JOIN HSN_DET C (NOLOCK) ON B.HSN_CODE =C.HSN_CODE AND C.WEF  <=@DMEMO_DT 
								WHERE A.SP_ID =LTRIM(RTRIM((@NSPID)))  
								)

							   SELECT * INTO #TMPinsuranceHSN FROM CTE WHERE SR=1
						
							   UPDATE TMP SET  INSURANCE_TAXABLE_VALUE = ROUND(INSURANCE-(INSURANCE*(CASE WHEN OH_TAX_METHOD=2 THEN (HM.RATE_CUTOFF_TAX_PERCENTAGE/  
														   (100 + HM.RATE_CUTOFF_TAX_PERCENTAGE)) ELSE 0 END)),2)
							   FROM GST_TAXINFO_CALC_OH  TMP (NOLOCK)
							   JOIN #TMPinsuranceHSN HM (NOLOCK) ON HM.HSN_CODE=TMP.INSURANCE_HSN_CODE 
							   WHERE TMP.SP_ID=LTRIM(RTRIM((@NSPID))) 
					    
							   PRINT '6.UPDATE GST PERCENTAGE '
	                        
							   UPDATE TMP SET INSURANCE_GST_PERCENTAGE=ISNULL(CASE WHEN HM.RATE_CUTOFF<ABS(TMP.INSURANCE_TAXABLE_VALUE) THEN HM.TAX_PERCENTAGE ELSE RATE_CUTOFF_TAX_PERCENTAGE END ,0),
							   INSURANCE_GST_AMOUNT=0
							   FROM GST_TAXINFO_CALC_OH TMP (NOLOCK)
							   JOIN #TMPinsuranceHSN HM (NOLOCK) ON HM.HSN_CODE=TMP.INSURANCE_HSN_CODE 
							   WHERE TMP.SP_ID=LTRIM(RTRIM((@NSPID)))

							   
	
							END	


							IF EXISTS(SELECT TOP 1 'U' FROM GST_TAXINFO_CALC_OH WHERE SP_ID=LTRIM(RTRIM((@NSPID))) AND ISNULL(packing,0)<>0  )
						   BEGIN
								IF OBJECT_ID('TEMPDB..#TMPPACKINGHSN','U') IS NOT NULL
								   DROP TABLE #TMPPACKINGHSN

								;WITH CTE AS
								(
								SELECT B.HSN_CODE,ISNULL(C.TAX_PERCENTAGE,0) AS TAX_PERCENTAGE,ISNULL(C.RATE_CUTOFF,0) AS RATE_CUTOFF,
									   ISNULL(C.RATE_CUTOFF_TAX_PERCENTAGE,0) AS RATE_CUTOFF_TAX_PERCENTAGE,
									  ISNULL(C.WEF,'') AS WEF,ISNULL(B.TAXABLE_ITEM,'') AS TAXABLE_ITEM,ISNULL(B.HSN_TYPE ,'') AS HSN_TYPE  ,
									  SR=ROW_NUMBER() OVER (PARTITION BY A.SP_ID ORDER BY C.WEF DESC)
								FROM GST_TAXINFO_CALC_OH A (NOLOCK)
								JOIN HSN_MST B (NOLOCK) ON A.packing_hsn_code =B.HSN_CODE 
								LEFT JOIN HSN_DET C (NOLOCK) ON B.HSN_CODE =C.HSN_CODE AND C.WEF  <=@DMEMO_DT 
								WHERE A.SP_ID =LTRIM(RTRIM((@NSPID)))  
								)

							   SELECT * INTO #TMPpackingHSN FROM CTE WHERE SR=1
						
							   UPDATE TMP SET  packing_TAXABLE_VALUE = ROUND(packing-(packing*(CASE WHEN OH_TAX_METHOD=2 THEN (HM.RATE_CUTOFF_TAX_PERCENTAGE/  
														   (100 + HM.RATE_CUTOFF_TAX_PERCENTAGE)) ELSE 0 END)),2)
							   FROM GST_TAXINFO_CALC_OH  TMP (NOLOCK)
							   JOIN #TMPpackingHSN HM (NOLOCK) ON HM.HSN_CODE=TMP.packing_HSN_CODE 
							   WHERE TMP.SP_ID=LTRIM(RTRIM((@NSPID))) 
					    
							   PRINT '6.UPDATE GST PERCENTAGE '
	                        
							   UPDATE TMP SET packing_GST_PERCENTAGE=ISNULL(CASE WHEN HM.RATE_CUTOFF<ABS(TMP.packing_TAXABLE_VALUE) THEN HM.TAX_PERCENTAGE ELSE RATE_CUTOFF_TAX_PERCENTAGE END ,0),
							   packing_GST_AMOUNT=0
							   FROM GST_TAXINFO_CALC_OH TMP (NOLOCK)
							   JOIN #TMPpackingHSN HM (NOLOCK) ON HM.HSN_CODE=TMP.packing_HSN_CODE 
							   WHERE TMP.SP_ID=LTRIM(RTRIM((@NSPID)))
	
							END	

					END
					
					SELECT 
					  @OCGST_PERCENTAGE=ISNULL(OTHER_CHARGES_GST_PERCENTAGE,0) ,
                      @FREIGHTGST_PERCENTAGE=ISNULL(FREIGHT_GST_PERCENTAGE,0) ,
                      @PACKINGGST_PERCENTAGE=ISNULL(packing_gst_percentage,0) ,
                      @INSURANCEGST_PERCENTAGE=ISNULL(insurance_gst_percentage,0)
                      FROM GST_TAXINFO_CALC_OH (NOLOCK)
                      WHERE SP_ID=LTRIM(RTRIM((@NSPID)))
                    
              
              end
              ELSE
              BEGIN
              
                     SELECT @MAXGST_PERCENTAGE=MAX(ISNULL(GST_PERCENTAGE,0))
                     FROM GST_TAXINFO_CALC TMP (NOLOCK) WHERE TMP.SP_ID=LTRIM(RTRIM((@NSPID)))
                     
                     SET @OCGST_PERCENTAGE=@MAXGST_PERCENTAGE
                     SET @FREIGHTGST_PERCENTAGE=@MAXGST_PERCENTAGE
                     SET @PACKINGGST_PERCENTAGE=@MAXGST_PERCENTAGE
                     SET @INSURANCEGST_PERCENTAGE=@MAXGST_PERCENTAGE
              
              END
        
             
                UPDATE GST_TAXINFO_CALC_OH
                SET OTHER_CHARGES_GST_PERCENTAGE=CASE  WHEN OTHER_CHARGES<>0 AND ISNULL(DO_NOT_CALC_GST_OH,0)=0 THEN  @OCGST_PERCENTAGE ELSE 0 END,
                PACKING_GST_PERCENTAGE=CASE  WHEN PACKING<>0 AND ISNULL(DO_NOT_CALC_GST_OH,0)=0 THEN  @PACKINGGST_PERCENTAGE ELSE 0 END,
                INSURANCE_GST_PERCENTAGE=CASE  WHEN INSURANCE<>0 AND ISNULL(DO_NOT_CALC_GST_OH,0)=0 THEN  @INSURANCEGST_PERCENTAGE ELSE 0 END,
                FREIGHT_GST_PERCENTAGE=CASE  WHEN FREIGHT<>0 AND ISNULL(DO_NOT_CALC_GST_OH,0)=0 THEN  @FREIGHTGST_PERCENTAGE ELSE 0 END
                WHERE SP_ID=LTRIM(RTRIM((@NSPID)))
               
            --EXCLUSIVE TAX UPDATE
             SET @CSTEP='40'
             
             UPDATE TMP SET FREIGHT_TAXABLE_VALUE =ROUND(FREIGHT-(FREIGHT*(CASE WHEN OH_TAX_METHOD =2 THEN ((ISNULL(TMP.FREIGHT_GST_PERCENTAGE,0))/  
			 (100 + ISNULL(TMP.FREIGHT_GST_PERCENTAGE,0))) ELSE 0 END)),2),
			 
			  OTHER_CHARGES_TAXABLE_VALUE =ROUND(OTHER_CHARGES-(OTHER_CHARGES*(CASE WHEN OH_TAX_METHOD =2 THEN ((ISNULL(TMP.OTHER_CHARGES_GST_PERCENTAGE,0))/  
			 (100 + ISNULL(TMP.OTHER_CHARGES_GST_PERCENTAGE,0))) ELSE 0 END)),2),
			 
			 PACKING_TAXABLE_VALUE =ROUND(PACKING-(PACKING*(CASE WHEN OH_TAX_METHOD =2 THEN ((ISNULL(TMP.PACKING_GST_PERCENTAGE,0))/  
			 (100 + ISNULL(TMP.PACKING_GST_PERCENTAGE,0))) ELSE 0 END)),2),
			 
			  INSURANCE_TAXABLE_VALUE =ROUND(INSURANCE-(INSURANCE*(CASE WHEN OH_TAX_METHOD =2 THEN ((ISNULL(TMP.INSURANCE_GST_PERCENTAGE,0))/  
			 (100 + ISNULL(TMP.INSURANCE_GST_PERCENTAGE,0))) ELSE 0 END)),2)

			  FROM GST_TAXINFO_CALC_OH TMP (NOLOCK)
			  WHERE TMP.SP_ID=LTRIM(RTRIM((@NSPID)))
				
			 
			    UPDATE TMP SET FREIGHT_GST_AMOUNT =
			    ROUND(
					ISNULL(FREIGHT,0)*(CASE WHEN OH_TAX_METHOD=2 THEN (TMP.FREIGHT_GST_PERCENTAGE/  
					(100 + TMP.FREIGHT_GST_PERCENTAGE)) ELSE (TMP.FREIGHT_GST_PERCENTAGE/100) END)
		        ,2 ) ,
		        
				OTHER_CHARGES_GST_AMOUNT=
				ROUND(
					ISNULL(OTHER_CHARGES,0)*(CASE WHEN OH_TAX_METHOD=2 THEN (TMP.OTHER_CHARGES_GST_PERCENTAGE/  
					(100 + TMP.OTHER_CHARGES_GST_PERCENTAGE)) ELSE (TMP.OTHER_CHARGES_GST_PERCENTAGE/100) END)
		        ,2 ),
				INSURANCE_GST_AMOUNT=
				ROUND(
					ISNULL(INSURANCE,0)*(CASE WHEN OH_TAX_METHOD=2 THEN (TMP.INSURANCE_GST_PERCENTAGE/  
					(100 + TMP.INSURANCE_GST_PERCENTAGE)) ELSE (TMP.INSURANCE_GST_PERCENTAGE/100) END)
		        ,2 ),
				PACKING_GST_AMOUNT=
				ROUND(
					ISNULL(PACKING,0)*(CASE WHEN OH_TAX_METHOD=2 THEN (TMP.PACKING_GST_PERCENTAGE/  
					(100 + TMP.PACKING_GST_PERCENTAGE)) ELSE (TMP.PACKING_GST_PERCENTAGE/100) END)
		        ,2 )
				FROM GST_TAXINFO_CALC_OH TMP (NOLOCK)
				WHERE TMP.SP_ID=LTRIM(RTRIM((@NSPID)))
				
          
            
      
      End
      ELSE
      BEGIN
          
          UPDATE TMP SET FREIGHT_HSN_CODE='0000000000',
                         OTHER_CHARGES_HSN_CODE='0000000000',
                         INSURANCE_HSN_CODE='0000000000',
                         PACKING_HSN_CODE='0000000000',
						 FREIGHT_GST_PERCENTAGE=0 ,
						 OTHER_CHARGES_GST_PERCENTAGE=0,
						 INSURANCE_GST_PERCENTAGE=0,
						 PACKING_GST_PERCENTAGE=0,
						 ISIGST=0,
						 FREIGHT_GST_AMOUNT=0,
						 OTHER_CHARGES_GST_AMOUNT=0,
						 INSURANCE_GST_AMOUNT=0,
						 PACKING_GST_AMOUNT=0,
						 FREIGHT_TAXABLE_VALUE=FREIGHT ,
						 OTHER_CHARGES_TAXABLE_VALUE=OTHER_CHARGES ,
						 PACKING_TAXABLE_VALUE=PACKING,
						 INSURANCE_TAXABLE_VALUE=INSURANCE
						 
						  				
		  FROM GST_TAXINFO_CALC_OH TMP (NOLOCK)
		  WHERE TMP.SP_ID=LTRIM(RTRIM((@NSPID))) 

		
      
      END

	   
  END TRY  
  BEGIN CATCH  
   SELECT @CERRMSG='ERROR MESSAGE IN PROCEDURE SP3S_GST_TAX_CAL_OH STEP#'+@CSTEP+' '+CAST(ERROR_MESSAGE() AS VARCHAR(MAX))+ '||'+ERROR_PROCEDURE()  
   PRINT 'ENTER CATCH IN SP3S_GST_TAX_CAL_OH'
  END CATCH  

END
