CREATE PROCEDURE SP3S_ARS_GETDATA    
(          
  @NQUERYID INT,          
  @CARS_ID VARCHAR(10)='',          
  @CCOLUMNNAME VARCHAR(MAX)='',          
  @CCOLUMNORDER VARCHAR(500)='',          
  @cFilterCriteria VARCHAR(MAX)=''          
)          
AS          
BEGIN          
    SET NOCOUNT ON                 
       DECLARE @DTSQL NVARCHAR(MAX),@CERRMSG VARCHAR(1000)          
       SET @CERRMSG=''          
       IF @NQUERYID =1           GOTO LBLPLAN    
       ELSE IF @NQUERYID =2      GOTO LBLARSMST    
       ELSE IF @NQUERYID =3      GOTO LBLARSDET    
       ELSE IF @NQUERYID =4      GOTO LBLSTOCKLEVEL    
       ELSE IF @NQUERYID =5      GOTO LOCDATA    
       ELSE IF @NQUERYID =6      GOTO LBLSEASONNAME                       
       ELSE IF @NQUERYID =7      GOTO ROLE_NAME    
       ELSE IF @NQUERYID =8      GOTO ROLE_USERS    
       ELSE IF @NQUERYID =9      GOTO LBLGENORDERBASE    
       --ON 2018-12-03          
       ELSE IF @NQUERYID =10     GOTO GET_ATTR    
       ELSE IF @NQUERYID =11     GOTO RETURN_EXCEL_MAPPED_FILEDS    
       ELSE IF @NQUERYID =12     GOTO EXPORT_EXCEL    
       ELSE IF @NQUERYID =13     GOTO RETURN_ATTRS    
       ELSE IF @NQUERYID =14     GOTO RETURN_PLAN_FIELDS    
       ELSE IF @NQUERYID =15     GOTO CREATE_ARO    
       ELSE IF @NQUERYID =16     GOTO GET_SEASON_PERIOD    
       ELSE IF @NQUERYID =17     GOTO GET_FILTERED_LOCATIONS    
       ELSE IF @NQUERYID =18     GOTO EXPORT_DATA_TO_EXCEL    
       ELSE IF @NQUERYID =19     GOTO RET_EXCEL_IMPORT_FILEDS    
       ELSE IF @NQUERYID =20     GOTO RET_LOCATIONS    
       ELSE IF @NQUERYID =21     GOTO GET_ARS_DET_ATTR
       GOTO END_PROC          
            
 RET_LOCATIONS:    
 SELECT CAST(0 AS BIT)CHK,DEPT_ID,DEPT_NAME FROM LOCATION (NOLOCK) WHERE inactive=0    
 GOTO END_PROC    
     
     
 LBLPLAN:          
   SELECT A.PLAN_NAME ,ARS_ID           
   FROM ARS_MST  A          
   WHERE (@CARS_ID='' OR ARS_ID =@CARS_ID)          
   ORDER BY ARS_ID           
   GOTO END_PROC           
           
 LBLARSMST:          
   SELECT A.ARS_ID,A.LAST_UPDATE,A.PLAN_NAME,A.SEASON_ID,A.USER_CODE,A.INACTIVE,A.REP_ID,A.FILTER_CRITERIA,A.FILTER_DETAILS    
   ,A.REMARKS,A.AUTHORIZATION_MODE,ISNULL(A.CANCELLED,0)CANCELLED,SM.SEASON_NAME ,U.USERNAME            
   --,DATEADD(YY,YEAR(GETDATE())-YEAR(Period_From),Period_From)From_DT          
   --,CASE WHEN YEAR(PERIOD_TO)>YEAR(GETDATE()) THEN PERIOD_TO ELSE DATEADD(YY,YEAR(GETDATE())-YEAR(PERIOD_TO),PERIOD_TO)END TO_DT          
   ,AUTO_CALCULATE_TARGET_SALES,ISNULL(TARGET_DAYS,0)TARGET_DAYS,FROM_DT,TO_DT    
   FROM ARS_MST A (NOLOCK)          
   JOIN SEASON_MST SM (NOLOCK) ON A.SEASON_ID =SM.SEASON_ID           
   JOIN USERS U (NOLOCK) ON U.USER_CODE =A.USER_CODE           
   WHERE ARS_ID =@CARS_ID          
   ORDER BY ARS_ID           
   GOTO END_PROC           
           
 LBLARSDET:          
   DECLARE @SEASON_DAYS INT=0                 
   IF @cFilterCriteria='' SET @cFilterCriteria=' 1=1 '          
         
   IF @CCOLUMNNAME=''          
      SELECT @CCOLUMNNAME=ISNULL(@CCOLUMNNAME+',','')+QUOTENAME(STK_LEVEL_PARA_NAME)          
      FROM ARS_STOCK_LEVEL_MST (NOLOCK)          
      WHERE STK_LEVEL_PARA_NAME<>'' AND ARS_ID =@CARS_ID          
      ORDER BY STK_LEVEL_PARA_NAME ASC          
   ELSE          
     SET @CCOLUMNNAME=','+@CCOLUMNNAME          
       
   SET @CCOLUMNNAME=REPLACE(@CCOLUMNNAME,'ARTICLE_NO','ARTICLE_NAME')      
       
   IF ISNULL(@CCOLUMNORDER,'')<>''          
      SET @CCOLUMNORDER=','+@CCOLUMNORDER          
   SELECT TOP 1 @SEASON_DAYS=DATEDIFF(DD,DBO.GET_SEASON_DT(A.SEASON_ID,'FROM'),DBO.GET_SEASON_DT(A.SEASON_ID,'TILL'))+1 FROM ARS_MST A(NOLOCK) WHERE A.ARS_ID=@CARS_ID         
   SET @SEASON_DAYS=ISNULL(@SEASON_DAYS,1)      
         
   SELECT ART.article_no,ART.ARTICLE_NAME,SM.section_name,SD.sub_section_name          
  ,P1.para1_name,P2.para2_name,P3.para3_name,P4.para4_name,P5.para5_name,P6.para6_name          
  ,A.MINIMUM_DAYS,A.TARGET_DAYS,A.MAXIMUM_DAYS          
  ,A.article_code,A.section_code,A.sub_section_code          
  ,A.para1_code,A.para2_code,A.para3_code,A.para4_code,A.para5_code,A.para6_code          
  ,A.dept_id,A.dept_id LOC_ID          
  ,A.ATTR1_KEY_CODE,A1.ATTR1_KEY_NAME          
  ,A.ATTR2_KEY_CODE,A2.ATTR2_KEY_NAME          
  ,A.ATTR3_KEY_CODE,A3.ATTR3_KEY_NAME          
  ,A.ATTR4_KEY_CODE,A4.ATTR4_KEY_NAME          
  ,A.ATTR5_KEY_CODE,A5.ATTR5_KEY_NAME          
  ,A.ATTR6_KEY_CODE,A6.ATTR6_KEY_NAME          
  ,A.ATTR7_KEY_CODE,A7.ATTR7_KEY_NAME          
  ,A.ATTR8_KEY_CODE,A8.ATTR8_KEY_NAME          
  ,A.ATTR9_KEY_CODE,A9.ATTR9_KEY_NAME          
  ,A.ATTR10_KEY_CODE,A10.ATTR10_KEY_NAME          
  ,A.ATTR11_KEY_CODE,A11.ATTR11_KEY_NAME          
  ,A.ATTR12_KEY_CODE,A12.ATTR12_KEY_NAME          
  ,A.ATTR13_KEY_CODE,A13.ATTR13_KEY_NAME          
  ,A.ATTR14_KEY_CODE,A14.ATTR14_KEY_NAME          
  ,A.ATTR15_KEY_CODE,A15.ATTR15_KEY_NAME          
  ,A.ATTR16_KEY_CODE,A16.ATTR16_KEY_NAME          
  ,A.ATTR17_KEY_CODE,A17.ATTR17_KEY_NAME          
  ,A.ATTR18_KEY_CODE,A18.ATTR18_KEY_NAME          
  ,A.ATTR19_KEY_CODE,A19.ATTR19_KEY_NAME          
  ,A.ATTR20_KEY_CODE,A20.ATTR20_KEY_NAME          
  ,A.ATTR21_KEY_CODE,A21.ATTR21_KEY_NAME          
  ,A.ATTR22_KEY_CODE,A22.ATTR22_KEY_NAME          
  ,A.ATTR23_KEY_CODE,A23.ATTR23_KEY_NAME          
  ,A.ATTR24_KEY_CODE,A24.ATTR24_KEY_NAME          
  ,A.ATTR25_KEY_CODE,A25.ATTR25_KEY_NAME          
  ,L.DEpt_name,A.ars_id,A.TARGET_DAILY_SALE--,row_id          
  ,CEILING(A.TARGET_DAILY_SALE*@SEASON_DAYS)ESTIMATED_SALE      
  ,CEILING(A.TARGET_DAYS*A.TARGET_DAILY_SALE*(1.00+ISNULL(A.SAFETY_LEVEL,0)/100)) STOCK_REQ_QTY          
  ,A.SAFETY_LEVEL,CONVERT(VARCHAR,GETDATE(),113) AS LAST_UPDATED_ON    
  FROM ARS_DET A (NOLOCK)          
  JOIN SECTIONM SM (NOLOCK) ON SM.SECTION_CODE=A.SECTION_CODE          
  JOIN SECTIOND SD (NOLOCK) ON SD.SUB_SECTION_CODE=A.SUB_SECTION_CODE          
  JOIN ARTICLE ART (NOLOCK) ON ART.ARTICLE_CODE=A.ARTICLE_CODE           
  JOIN LOCATION L (NOLOCK) ON L.DEPT_ID=A.DEPT_ID          
  LEFT JOIN PARA1 P1 (NOLOCK) ON P1.PARA1_CODE=A.PARA1_CODE          
  LEFT JOIN PARA2 P2 (NOLOCK) ON P2.PARA2_CODE=A.PARA2_CODE          
  LEFT JOIN PARA3 P3 (NOLOCK) ON P3.PARA3_CODE=A.PARA3_CODE          
  LEFT JOIN PARA4 P4 (NOLOCK) ON P4.PARA4_CODE=A.PARA4_CODE          
  LEFT JOIN PARA5 P5 (NOLOCK) ON P5.PARA5_CODE=A.PARA5_CODE          
  LEFT JOIN PARA6 P6 (NOLOCK) ON P6.PARA6_CODE=A.PARA6_CODE          
  LEFT JOIN ATTR1_MST A1 (NOLOCK) ON A1.ATTR1_KEY_CODE=A.ATTR1_KEY_CODE          
  LEFT JOIN ATTR2_MST A2 (NOLOCK) ON A2.ATTR2_KEY_CODE=A.ATTR2_KEY_CODE          
  LEFT JOIN ATTR3_MST A3 (NOLOCK) ON A3.ATTR3_KEY_CODE=A.ATTR3_KEY_CODE          
  LEFT JOIN ATTR4_MST A4 (NOLOCK) ON A4.ATTR4_KEY_CODE=A.ATTR4_KEY_CODE          
  LEFT JOIN ATTR5_MST A5 (NOLOCK) ON A5.ATTR5_KEY_CODE=A.ATTR5_KEY_CODE          
  LEFT JOIN ATTR6_MST A6 (NOLOCK) ON A6.ATTR6_KEY_CODE=A.ATTR6_KEY_CODE          
  LEFT JOIN ATTR7_MST A7 (NOLOCK) ON A7.ATTR7_KEY_CODE=A.ATTR7_KEY_CODE          
  LEFT JOIN ATTR8_MST A8 (NOLOCK) ON A8.ATTR8_KEY_CODE=A.ATTR8_KEY_CODE          
  LEFT JOIN ATTR9_MST A9 (NOLOCK) ON A9.ATTR9_KEY_CODE=A.ATTR9_KEY_CODE          
  LEFT JOIN ATTR10_MST A10 (NOLOCK) ON A10.ATTR10_KEY_CODE=A.ATTR10_KEY_CODE          
  LEFT JOIN ATTR11_MST A11 (NOLOCK) ON A11.ATTR11_KEY_CODE=A.ATTR11_KEY_CODE          
  LEFT JOIN ATTR12_MST A12 (NOLOCK) ON A12.ATTR12_KEY_CODE=A.ATTR12_KEY_CODE          
  LEFT JOIN ATTR13_MST A13 (NOLOCK) ON A13.ATTR13_KEY_CODE=A.ATTR13_KEY_CODE          
  LEFT JOIN ATTR14_MST A14 (NOLOCK) ON A14.ATTR14_KEY_CODE=A.ATTR14_KEY_CODE          
  LEFT JOIN ATTR15_MST A15 (NOLOCK) ON A15.ATTR15_KEY_CODE=A.ATTR15_KEY_CODE          
  LEFT JOIN ATTR16_MST A16 (NOLOCK) ON A16.ATTR16_KEY_CODE=A.ATTR16_KEY_CODE          
  LEFT JOIN ATTR17_MST A17 (NOLOCK) ON A17.ATTR17_KEY_CODE=A.ATTR17_KEY_CODE          
  LEFT JOIN ATTR18_MST A18 (NOLOCK) ON A18.ATTR18_KEY_CODE=A.ATTR18_KEY_CODE          
  LEFT JOIN ATTR19_MST A19 (NOLOCK) ON A19.ATTR19_KEY_CODE=A.ATTR19_KEY_CODE          
  LEFT JOIN ATTR20_MST A20 (NOLOCK) ON A20.ATTR20_KEY_CODE=A.ATTR20_KEY_CODE          
  LEFT JOIN ATTR21_MST A21 (NOLOCK) ON A21.ATTR21_KEY_CODE=A.ATTR21_KEY_CODE          
  LEFT JOIN ATTR22_MST A22 (NOLOCK) ON A22.ATTR22_KEY_CODE=A.ATTR22_KEY_CODE          
  LEFT JOIN ATTR23_MST A23 (NOLOCK) ON A23.ATTR23_KEY_CODE=A.ATTR23_KEY_CODE          
  LEFT JOIN ATTR24_MST A24 (NOLOCK) ON A24.ATTR24_KEY_CODE=A.ATTR24_KEY_CODE          
  LEFT JOIN ATTR25_MST A25 (NOLOCK) ON A25.ATTR25_KEY_CODE=A.ATTR25_KEY_CODE          
  WHERE A.ARS_ID=@CARS_ID          
 GOTO END_PROC           
           
           
          
 LBLSTOCKLEVEL:          
 SELECT * FROM    
 (    
 SELECT DISTINCT ISNULL(B.ARS_ID,'LATER') AS ARS_ID,A.STK_LEVEL_PARA_NAME,A.STK_LEVEL_PARA_desc,          
        (CASE WHEN b.STK_LEVEL_PARA_NAME IS NOT NULL THEN 1 ELSE 0 END) AS CHK          
 FROM          
 (          
  SELECT  'ARTICLE_NO' as STK_LEVEL_PARA_NAME,'Article' as  STK_LEVEL_PARA_desc union all          
  SELECT  'SECTION_NAME' as STK_LEVEL_PARA_NAME,'Section' as  STK_LEVEL_PARA_desc union all            
  SELECT  'SUB_SECTION_NAME' as STK_LEVEL_PARA_NAME,'Sub Section' as  STK_LEVEL_PARA_desc union all            
  SELECT CONFIG_OPTION+'_NAME',VALUE FROM CONFIG WHERE  config_option LIKE 'PARA[3-6]'+'_caption' union all           
  SELECT CONFIG_OPTION+'_NAME',VALUE FROM CONFIG WHERE  config_option LIKE 'PARA[1-2]'+'_caption' UNION ALL     
  SELECT UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE ISNULL(TABLE_CAPTION,'')<>''          
      
 ) a          
 LEFT JOIN ARS_ARS_STOCK_LEVEL_MST_UPLOAD B ON B.STK_LEVEL_PARA_NAME=A.STK_LEVEL_PARA_NAME AND B.ARS_ID=@CARS_ID AND sp_id=@cFilterCriteria         
 --WHERE (@CARS_ID='' OR (B.ARS_ID =@CARS_ID OR B.ARS_ID IS NULL))          
 )T    
 ORDER BY 1    
    
 GOTO END_PROC          
          
          
          
 LBLGENORDERBASE:          
 SELECT ISNULL(B.ARS_ID,'LATER') AS ARS_ID,A.order_by_para_name,A.order_by_para_desc    
    ,(CASE WHEN b.order_by_para_name IS NOT NULL THEN 1 ELSE 0 END) AS CHK          
 FROM    
 (          
  SELECT 'ARTICLE_NO' as order_by_para_name,'Article' as order_by_para_desc union all          
  SELECT 'PARA1_NAME' as order_by_para_name, 'Color' as order_by_para_desc union all          
  SELECT 'PARA3_NAME' as order_by_para_name, 'Style' as order_by_para_desc          
 ) a          
 LEFT JOIN ARS_GENORDERS_BASE B ON B.order_by_para_name=A.order_by_para_name AND B.ARS_ID=@CARS_ID          
 --WHERE (@CARS_ID='' OR (B.ARS_ID =@CARS_ID OR B.ARS_ID IS NULL))          
 ORDER BY ISNULL(B.ARS_ID,'LATER')          
            
           
           
            
            
 GOTO END_PROC          
           
 LOCDATA:          
        SELECT 'ALL' AS DEPT_ID,          
               'ALL' AS DEPT_NAME,          
               ORDER_PRIORITY=CAST(0 AS NUMERIC(8,0)),          
        LEAD_DAYS=CAST(0 AS NUMERIC(8,0))          
        UNION ALL          
        SELECT A.DEPT_ID,DEPT_NAME,          
        ORDER_PRIORITY=CAST(0 AS NUMERIC(8,0)),          
        LEAD_DAYS=CAST(0 AS NUMERIC(8,0))          
     FROM LOCATION  A          
     WHERE INACTIVE =0          
     ORDER BY DEPT_NAME           
           
 GOTO END_PROC          
           
 LBLSEASONNAME:          
               
   SELECT SEASON_ID ,SEASON_NAME    
   FROM SEASON_MST WHERE INACTIVE =0          
   ORDER BY SEASON_NAME          
               
  GOTO END_PROC          
            
            
    ROLE_NAME:          
                  
           SELECT CAST(0 AS BIT) AS CHK,          
           ROLE_ID ,ROLE_NAME            
           FROM USER_ROLE_MST           
                  
        GOTO END_PROC          
          
    ROLE_USERS:          
                  
           SELECT CAST(0 AS BIT) AS CHK,          
           ROLE_ID , a.user_code,username          
           FROM USERs a          
           LEFT OUTER JOIN ARS_PERMISSIONS_DET b ON a.user_code=b.user_Code AND b.ars_id=@CARS_ID          
           WHERE b.ars_id IS NULL          
                
     UNION ALL           
           SELECT DISTINCT CAST(1 AS BIT) AS CHK,          
           ROLE_ID,a.user_code,username          
           FROM ARS_PERMISSIONS_DET a          
           JOIN USERs b on b.user_code=a.user_code          
                        
        GOTO END_PROC                  
          
          
   GET_ATTR:          
   IF @CARS_ID=''          
      SELECT STK_LEVEL_PARA_name AS TABLE_NAME,STK_LEVEL_PARA_desc AS TABLE_CAPTION          
      FROM ARS_ARS_STOCK_LEVEL_MST_UPLOAD (NOLOCK) WHERE SP_ID=@cFilterCriteria        
   ELSE          
      SELECT TOP 1 'SECTION_NAME'AS TABLE_NAME,'Section' AS TABLE_CAPTION FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ISNULL(SECTION_CODE,'0000000') NOT IN ('','0000000') UNION          
      SELECT TOP 1 'SUB_SECTION_NAME','Sub Section' FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ISNULL(SUB_SECTION_CODE,'0000000') NOT IN ('','0000000') UNION          
      SELECT TOP 1 'ARTICLE_NO','Article' FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ISNULL(ARTICLE_CODE,'00000000') NOT IN ('','00000000') UNION          
      --PARA          
      SELECT TOP 1 'PARA1_NAME',C.value FROM ARS_DET A (NOLOCK) JOIN CONFIG C ON 1=1 AND  C.config_option LIKE 'PARA1_caption' WHERE ARS_ID=@CARS_ID AND ISNULL(A.PARA1_CODE,'0000000') NOT IN ('','0000000') UNION          
      SELECT TOP 1 'PARA2_NAME',C.value FROM ARS_DET A (NOLOCK) JOIN CONFIG C ON 1=1 AND  C.config_option LIKE 'PARA2_caption' WHERE ARS_ID=@CARS_ID AND ISNULL(A.PARA2_CODE,'0000000') NOT IN ('','0000000') UNION                
      SELECT TOP 1 'PARA3_NAME',C.value FROM ARS_DET A (NOLOCK) JOIN CONFIG C ON 1=1 AND  C.config_option LIKE 'PARA3_caption' WHERE ARS_ID=@CARS_ID AND ISNULL(A.PARA3_CODE,'0000000') NOT IN ('','0000000') UNION          
      SELECT TOP 1 'PARA4_NAME',C.value FROM ARS_DET A (NOLOCK) JOIN CONFIG C ON 1=1 AND  C.config_option LIKE 'PARA4_caption' WHERE ARS_ID=@CARS_ID AND ISNULL(A.PARA4_CODE,'0000000') NOT IN ('','0000000') UNION          
      SELECT TOP 1 'PARA5_NAME',C.value FROM ARS_DET A (NOLOCK) JOIN CONFIG C ON 1=1 AND  C.config_option LIKE 'PARA5_caption' WHERE ARS_ID=@CARS_ID AND ISNULL(A.PARA5_CODE,'0000000') NOT IN ('','0000000') UNION          
      SELECT TOP 1 'PARA6_NAME',C.value FROM ARS_DET A (NOLOCK) JOIN CONFIG C ON 1=1 AND  C.config_option LIKE 'PARA6_caption' WHERE ARS_ID=@CARS_ID AND ISNULL(A.PARA6_CODE,'0000000') NOT IN ('','0000000') UNION          
      --ATTR          
      SELECT TOP 1 'ATTR1_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR1_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR1_KEY_CODE,'0000000') NOT IN ('','0000000') UNION          
      SELECT TOP 1 'ATTR2_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR2_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR2_KEY_CODE,'0000000') NOT IN ('','0000000') UNION          
      SELECT TOP 1 'ATTR3_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR3_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR3_KEY_CODE,'0000000') NOT IN ('','0000000') UNION          
      SELECT TOP 1 'ATTR4_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR4_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR4_KEY_CODE,'0000000') NOT IN ('','0000000') UNION          
      SELECT TOP 1 'ATTR5_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR5_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR5_KEY_CODE,'0000000') NOT IN ('','0000000') UNION          
      SELECT TOP 1 'ATTR6_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR6_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR6_KEY_CODE,'0000000') NOT IN ('','0000000') UNION          
      SELECT TOP 1 'ATTR7_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR7_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR7_KEY_CODE,'0000000') NOT IN ('','0000000') UNION          
      SELECT TOP 1 'ATTR8_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR8_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR8_KEY_CODE,'0000000') NOT IN ('','0000000') UNION          
      SELECT TOP 1 'ATTR9_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR9_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR9_KEY_CODE,'0000000') NOT IN ('','0000000') UNION          
      SELECT TOP 1 'ATTR10_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR10_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR10_KEY_CODE,'0000000') NOT IN ('','0000000') UNION          
      SELECT TOP 1 'ATTR11_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR11_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR11_KEY_CODE,'0000000') NOT IN ('','0000000') UNION          
   SELECT TOP 1 'ATTR12_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR12_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR12_KEY_CODE,'0000000') NOT IN ('','0000000') UNION          
      SELECT TOP 1 'ATTR13_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR13_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR13_KEY_CODE,'0000000') NOT IN ('','0000000') UNION          
      SELECT TOP 1 'ATTR14_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR14_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR14_KEY_CODE,'0000000') NOT IN ('','0000000') UNION          
      SELECT TOP 1 'ATTR15_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR15_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR15_KEY_CODE,'0000000') NOT IN ('','0000000') UNION                
      SELECT TOP 1 'ATTR16_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR16_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR16_KEY_CODE,'0000000') NOT IN ('','0000000') UNION          
      SELECT TOP 1 'ATTR17_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR17_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR17_KEY_CODE,'0000000') NOT IN ('','0000000') UNION          
      SELECT TOP 1 'ATTR18_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR18_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR18_KEY_CODE,'0000000') NOT IN ('','0000000') UNION          
      SELECT TOP 1 'ATTR19_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR19_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR19_KEY_CODE,'0000000') NOT IN ('','0000000') UNION          
      SELECT TOP 1 'ATTR20_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR20_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR20_KEY_CODE,'0000000') NOT IN ('','0000000') UNION                
      SELECT TOP 1 'ATTR21_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR21_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR21_KEY_CODE,'0000000') NOT IN ('','0000000') UNION                
      SELECT TOP 1 'ATTR22_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR22_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR22_KEY_CODE,'0000000') NOT IN ('','0000000') UNION                
      SELECT TOP 1 'ATTR23_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR23_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR23_KEY_CODE,'0000000') NOT IN ('','0000000') UNION                
      SELECT TOP 1 'ATTR24_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR24_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR24_KEY_CODE,'0000000') NOT IN ('','0000000') UNION                
      SELECT TOP 1 'ATTR25_KEY_NAME',C.TABLE_CAPTION FROM ARS_DET A (NOLOCK) JOIN CONFIG_ATTR C ON 1=1 AND C.TABLE_NAME='ATTR25_MST' WHERE ARS_ID=@CARS_ID AND ISNULL(A.ATTR25_KEY_CODE,'0000000') NOT IN ('','0000000')       GOTO END_PROC                  


             
             
   RETURN_EXCEL_MAPPED_FILEDS:          
   IF OBJECT_ID('tempdb..#ARSPLAN') IS NOT NULL DROP TABLE #ARSPLAN          
   CREATE TABLE #ARSPLAN(MASTER_COL VARCHAR(MAX),MASTER_COL_EXPR VARCHAR(MAX),MAPPED_COL VARCHAR(MAX))          
   INSERT #ARSPLAN EXEC SP_EXCELDATA 'ARSPLAN'          
   SELECT *--A.MASTER_COL_EXPR          
   FROM IMPORT_CONFIG_DET M          
   JOIN #ARSPLAN A ON M.DEFAULT_PARA_NAME=A.MASTER_COL          
   WHERE M.MAPPING_CODE=@cFilterCriteria AND ISNULL(M.MAPPED_PARA_NAME,'')<>''          
   IF OBJECT_ID('tempdb..#ARSPLAN') IS NOT NULL DROP TABLE #ARSPLAN          
   GOTO END_PROC                  
             
             
   EXPORT_EXCEL:          
  IF OBJECT_ID('tempd..#ERR') IS NOT NULL DROP TABLE #ERR          
  SELECT           
    CASE WHEN SM.SECTION_CODE IS NULL THEN 'Section '+E.SECTION_NAME+' not found' ELSE ''END          
      +CASE WHEN SD.SUB_SECTION_CODE IS NULL THEN 'Sub-Section '+E.SUB_SECTION_NAME+' not found' ELSE '' END          
      +CASE WHEN A.ARTICLE_CODE IS NULL AND ISNULL(E.ARTICLE_NO,'')<>'' THEN 'Article '+E.ARTICLE_NO+' not found' ELSE '' END          
      +CASE WHEN P1.PARA1_CODE IS NULL  AND ISNULL(E.PARA1_NAME,'')<>'' THEN 'Para1 '+E.PARA1_NAME+' not found'   ELSE '' END          
      +CASE WHEN P2.PARA2_CODE IS NULL  AND ISNULL(E.PARA2_NAME,'')<>'' THEN 'Para2 '+E.PARA2_NAME+' not found'   ELSE '' END          
      +CASE WHEN P3.PARA3_CODE IS NULL  AND ISNULL(E.PARA3_NAME,'')<>'' THEN 'Para3 '+E.PARA3_NAME+' not found'   ELSE '' END          
      +CASE WHEN P4.PARA4_CODE IS NULL  AND ISNULL(E.PARA4_NAME,'')<>'' THEN 'Para4 '+E.PARA4_NAME+' not found'   ELSE '' END          
      +CASE WHEN P5.PARA5_CODE IS NULL  AND ISNULL(E.PARA5_NAME,'')<>'' THEN 'Para5 '+E.PARA5_NAME+' not found'   ELSE '' END          
      +CASE WHEN P6.PARA6_CODE IS NULL  AND ISNULL(E.PARA6_NAME,'')<>'' THEN 'Para6 '+E.PARA6_NAME+' not found'   ELSE '' END          
      +CASE WHEN A1.ATTR1_KEY_CODE IS NULL AND ISNULL(E.ATTR1_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR1_KEY_NAME+' not found in attribute '+CA1.TABLE_CAPTION ELSE '' END          
      +CASE WHEN A2.ATTR2_KEY_CODE IS NULL AND ISNULL(E.ATTR2_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR2_KEY_NAME+' not found in attribute '+CA2.TABLE_CAPTION ELSE '' END          
      +CASE WHEN A3.ATTR3_KEY_CODE IS NULL AND ISNULL(E.ATTR3_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR3_KEY_NAME+' not found in attribute '+CA3.TABLE_CAPTION ELSE '' END          
      +CASE WHEN A4.ATTR4_KEY_CODE IS NULL AND ISNULL(E.ATTR4_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR4_KEY_NAME+' not found in attribute '+CA4.TABLE_CAPTION ELSE '' END          
      +CASE WHEN A5.ATTR5_KEY_CODE IS NULL AND ISNULL(E.ATTR5_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR5_KEY_NAME+' not found in attribute '+CA5.TABLE_CAPTION ELSE '' END          
      +CASE WHEN A6.ATTR6_KEY_CODE IS NULL AND ISNULL(E.ATTR6_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR6_KEY_NAME+' not found in attribute '+CA6.TABLE_CAPTION ELSE '' END          
      +CASE WHEN A7.ATTR7_KEY_CODE IS NULL AND ISNULL(E.ATTR7_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR7_KEY_NAME+' not found in attribute '+CA7.TABLE_CAPTION ELSE '' END          
      +CASE WHEN A8.ATTR8_KEY_CODE IS NULL AND ISNULL(E.ATTR8_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR8_KEY_NAME+' not found in attribute '+CA8.TABLE_CAPTION ELSE '' END          
      +CASE WHEN A9.ATTR9_KEY_CODE IS NULL AND ISNULL(E.ATTR9_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR9_KEY_NAME+' not found in attribute '+CA9.TABLE_CAPTION ELSE '' END          
      +CASE WHEN A10.ATTR10_KEY_CODE IS NULL AND ISNULL(E.ATTR10_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR10_KEY_NAME+' not found in attribute '+CA10.TABLE_CAPTION ELSE '' END          
      +CASE WHEN A11.ATTR11_KEY_CODE IS NULL AND ISNULL(E.ATTR11_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR11_KEY_NAME+' not found in attribute '+CA11.TABLE_CAPTION ELSE '' END          
      +CASE WHEN A12.ATTR12_KEY_CODE IS NULL AND ISNULL(E.ATTR12_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR12_KEY_NAME+' not found in attribute '+CA12.TABLE_CAPTION ELSE '' END          
      +CASE WHEN A13.ATTR13_KEY_CODE IS NULL AND ISNULL(E.ATTR13_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR13_KEY_NAME+' not found in attribute '+CA13.TABLE_CAPTION ELSE '' END          
      +CASE WHEN A14.ATTR14_KEY_CODE IS NULL AND ISNULL(E.ATTR14_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR14_KEY_NAME+' not found in attribute '+CA14.TABLE_CAPTION ELSE '' END          
      +CASE WHEN A15.ATTR15_KEY_CODE IS NULL AND ISNULL(E.ATTR15_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR15_KEY_NAME+' not found in attribute '+CA15.TABLE_CAPTION ELSE '' END          
      +CASE WHEN A16.ATTR16_KEY_CODE IS NULL AND ISNULL(E.ATTR16_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR16_KEY_NAME+' not found in attribute '+CA16.TABLE_CAPTION ELSE '' END          
      +CASE WHEN A17.ATTR17_KEY_CODE IS NULL AND ISNULL(E.ATTR17_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR17_KEY_NAME+' not found in attribute '+CA17.TABLE_CAPTION ELSE '' END          
      +CASE WHEN A18.ATTR18_KEY_CODE IS NULL AND ISNULL(E.ATTR18_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR18_KEY_NAME+' not found in attribute '+CA18.TABLE_CAPTION ELSE '' END          
      +CASE WHEN A19.ATTR19_KEY_CODE IS NULL AND ISNULL(E.ATTR19_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR19_KEY_NAME+' not found in attribute '+CA19.TABLE_CAPTION ELSE '' END          
      +CASE WHEN A20.ATTR20_KEY_CODE IS NULL AND ISNULL(E.ATTR20_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR20_KEY_NAME+' not found in attribute '+CA20.TABLE_CAPTION ELSE '' END          
      +CASE WHEN A21.ATTR21_KEY_CODE IS NULL AND ISNULL(E.ATTR21_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR21_KEY_NAME+' not found in attribute '+CA21.TABLE_CAPTION ELSE '' END          
      +CASE WHEN A22.ATTR22_KEY_CODE IS NULL AND ISNULL(E.ATTR22_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR22_KEY_NAME+' not found in attribute '+CA22.TABLE_CAPTION ELSE '' END          
      +CASE WHEN A23.ATTR23_KEY_CODE IS NULL AND ISNULL(E.ATTR23_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR23_KEY_NAME+' not found in attribute '+CA23.TABLE_CAPTION ELSE '' END          
      +CASE WHEN A24.ATTR24_KEY_CODE IS NULL AND ISNULL(E.ATTR24_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR24_KEY_NAME+' not found in attribute '+CA24.TABLE_CAPTION ELSE '' END          
      +CASE WHEN A25.ATTR25_KEY_CODE IS NULL AND ISNULL(E.ATTR25_KEY_NAME,'')<>'' THEN 'Value '+E.ATTR25_KEY_NAME+' not found in attribute '+CA25.TABLE_CAPTION ELSE '' END          
      AS ErrMsg          
      ,E.*          
      INTO #ERR          
      FROM ARSPLAN_IMPORT_UPLOAD E (NOLOCK)          
      LEFT JOIN SECTIONM SM (NOLOCK) ON E.SECTION_NAME=SM.SECTION_NAME AND ISNULL(E.SECTION_NAME,'')<>''          
   LEFT JOIN SECTIOND SD (NOLOCK) ON E.SUB_SECTION_NAME=SD.SUB_SECTION_NAME AND ISNULL(E.SUB_SECTION_NAME,'')<>''          
   LEFT JOIN ARTICLE A (NOLOCK) ON E.ARTICLE_NO=A.ARTICLE_NO AND ISNULL(E.ARTICLE_NO,'')<>''          
   LEFT JOIN PARA1 P1 (NOLOCK) ON E.PARA1_NAME=P1.PARA1_NAME AND ISNULL(E.PARA1_NAME,'')<>''          
   LEFT JOIN PARA2 P2 (NOLOCK) ON E.PARA2_NAME=P2.PARA2_NAME AND ISNULL(E.PARA2_NAME,'')<>''          
   LEFT JOIN PARA3 P3 (NOLOCK) ON E.PARA3_NAME=P3.PARA3_NAME AND ISNULL(E.PARA3_NAME,'')<>''          
   LEFT JOIN PARA4 P4 (NOLOCK) ON E.PARA4_NAME=P4.PARA4_NAME AND ISNULL(E.PARA4_NAME,'')<>''          
   LEFT JOIN PARA5 P5 (NOLOCK) ON E.PARA5_NAME=P5.PARA5_NAME AND ISNULL(E.PARA5_NAME,'')<>''          
      LEFT JOIN PARA6 P6 (NOLOCK) ON E.PARA6_NAME=P6.PARA6_NAME AND ISNULL(E.PARA6_NAME,'')<>''          
   LEFT JOIN ATTR1_MST A1 (NOLOCK) ON E.ATTR1_KEY_NAME=A1.ATTR1_KEY_NAME AND ISNULL(E.ATTR1_KEY_NAME,'')<>''          
   LEFT JOIN CONFIG_ATTR CA1 (NOLOCK) ON 1=1 AND CA1.TABLE_NAME='ATTR1_MST'          
   LEFT JOIN CONFIG_ATTR CA2 (NOLOCK) ON 1=1 AND CA2.TABLE_NAME='ATTR2_MST'          
   LEFT JOIN CONFIG_ATTR CA3 (NOLOCK) ON 1=1 AND CA3.TABLE_NAME='ATTR3_MST'          
   LEFT JOIN CONFIG_ATTR CA4 (NOLOCK) ON 1=1 AND CA4.TABLE_NAME='ATTR4_MST'          
   LEFT JOIN CONFIG_ATTR CA5 (NOLOCK) ON 1=1 AND CA5.TABLE_NAME='ATTR5_MST'          
   LEFT JOIN CONFIG_ATTR CA6 (NOLOCK) ON 1=1 AND CA6.TABLE_NAME='ATTR6_MST'          
   LEFT JOIN CONFIG_ATTR CA7 (NOLOCK) ON 1=1 AND CA7.TABLE_NAME='ATTR7_MST'          
   LEFT JOIN CONFIG_ATTR CA8 (NOLOCK) ON 1=1 AND CA8.TABLE_NAME='ATTR8_MST'          
   LEFT JOIN CONFIG_ATTR CA9 (NOLOCK) ON 1=1 AND CA9.TABLE_NAME='ATTR9_MST'          
   LEFT JOIN CONFIG_ATTR CA10 (NOLOCK) ON 1=1 AND CA10.TABLE_NAME='ATTR10_MST'         
   LEFT JOIN CONFIG_ATTR CA11 (NOLOCK) ON 1=1 AND CA11.TABLE_NAME='ATTR11_MST'          
   LEFT JOIN CONFIG_ATTR CA12 (NOLOCK) ON 1=1 AND CA12.TABLE_NAME='ATTR12_MST'          
   LEFT JOIN CONFIG_ATTR CA13 (NOLOCK) ON 1=1 AND CA13.TABLE_NAME='ATTR13_MST'          
   LEFT JOIN CONFIG_ATTR CA14 (NOLOCK) ON 1=1 AND CA14.TABLE_NAME='ATTR14_MST'          
   LEFT JOIN CONFIG_ATTR CA15 (NOLOCK) ON 1=1 AND CA15.TABLE_NAME='ATTR15_MST'                         
   LEFT JOIN CONFIG_ATTR CA16 (NOLOCK) ON 1=1 AND CA16.TABLE_NAME='ATTR16_MST'                         
   LEFT JOIN CONFIG_ATTR CA17 (NOLOCK) ON 1=1 AND CA17.TABLE_NAME='ATTR17_MST'          
   LEFT JOIN CONFIG_ATTR CA18 (NOLOCK) ON 1=1 AND CA18.TABLE_NAME='ATTR18_MST'          
   LEFT JOIN CONFIG_ATTR CA19 (NOLOCK) ON 1=1 AND CA19.TABLE_NAME='ATTR19_MST'          
   LEFT JOIN CONFIG_ATTR CA20 (NOLOCK) ON 1=1 AND CA20.TABLE_NAME='ATTR20_MST'          
   LEFT JOIN CONFIG_ATTR CA21 (NOLOCK) ON 1=1 AND CA21.TABLE_NAME='ATTR21_MST'          
   LEFT JOIN CONFIG_ATTR CA22 (NOLOCK) ON 1=1 AND CA22.TABLE_NAME='ATTR22_MST'          
   LEFT JOIN CONFIG_ATTR CA23 (NOLOCK) ON 1=1 AND CA23.TABLE_NAME='ATTR23_MST'          
   LEFT JOIN CONFIG_ATTR CA24 (NOLOCK) ON 1=1 AND CA24.TABLE_NAME='ATTR24_MST'          
   LEFT JOIN CONFIG_ATTR CA25 (NOLOCK) ON 1=1 AND CA25.TABLE_NAME='ATTR25_MST'                         
   LEFT JOIN ATTR2_MST A2 (NOLOCK) ON E.ATTR2_KEY_NAME=A2.ATTR2_KEY_NAME AND ISNULL(E.ATTR2_KEY_NAME,'')<>''          
   LEFT JOIN ATTR3_MST A3 (NOLOCK) ON E.ATTR3_KEY_NAME=A3.ATTR3_KEY_NAME AND ISNULL(E.ATTR3_KEY_NAME,'')<>''          
   LEFT JOIN ATTR4_MST A4 (NOLOCK) ON E.ATTR4_KEY_NAME=A4.ATTR4_KEY_NAME AND ISNULL(E.ATTR4_KEY_NAME,'')<>''          
   LEFT JOIN ATTR5_MST A5 (NOLOCK) ON E.ATTR5_KEY_NAME=A5.ATTR5_KEY_NAME AND ISNULL(E.ATTR5_KEY_NAME,'')<>''          
   LEFT JOIN ATTR6_MST A6 (NOLOCK) ON E.ATTR6_KEY_NAME=A6.ATTR6_KEY_NAME AND ISNULL(E.ATTR6_KEY_NAME,'')<>''          
   LEFT JOIN ATTR7_MST A7 (NOLOCK) ON E.ATTR7_KEY_NAME=A7.ATTR7_KEY_NAME AND ISNULL(E.ATTR7_KEY_NAME,'')<>''          
   LEFT JOIN ATTR8_MST A8 (NOLOCK) ON E.ATTR8_KEY_NAME=A8.ATTR8_KEY_NAME AND ISNULL(E.ATTR8_KEY_NAME,'')<>''          
   LEFT JOIN ATTR9_MST A9 (NOLOCK) ON E.ATTR9_KEY_NAME=A9.ATTR9_KEY_NAME AND ISNULL(E.ATTR9_KEY_NAME,'')<>''          
   LEFT JOIN ATTR10_MST A10 (NOLOCK) ON E.ATTR10_KEY_NAME=A10.ATTR10_KEY_NAME AND ISNULL(E.ATTR10_KEY_NAME,'')<>''          
   LEFT JOIN ATTR11_MST A11 (NOLOCK) ON E.ATTR11_KEY_NAME=A11.ATTR11_KEY_NAME AND ISNULL(E.ATTR11_KEY_NAME,'')<>''          
   LEFT JOIN ATTR12_MST A12 (NOLOCK) ON E.ATTR12_KEY_NAME=A12.ATTR12_KEY_NAME AND ISNULL(E.ATTR12_KEY_NAME,'')<>''          
   LEFT JOIN ATTR13_MST A13 (NOLOCK) ON E.ATTR13_KEY_NAME=A13.ATTR13_KEY_NAME AND ISNULL(E.ATTR13_KEY_NAME,'')<>''          
   LEFT JOIN ATTR14_MST A14 (NOLOCK) ON E.ATTR14_KEY_NAME=A14.ATTR14_KEY_NAME AND ISNULL(E.ATTR14_KEY_NAME,'')<>''          
   LEFT JOIN ATTR15_MST A15 (NOLOCK) ON E.ATTR15_KEY_NAME=A15.ATTR15_KEY_NAME AND ISNULL(E.ATTR15_KEY_NAME,'')<>''          
   LEFT JOIN ATTR16_MST A16 (NOLOCK) ON E.ATTR16_KEY_NAME=A16.ATTR16_KEY_NAME AND ISNULL(E.ATTR16_KEY_NAME,'')<>''          
   LEFT JOIN ATTR17_MST A17 (NOLOCK) ON E.ATTR17_KEY_NAME=A17.ATTR17_KEY_NAME AND ISNULL(E.ATTR17_KEY_NAME,'')<>''          
   LEFT JOIN ATTR18_MST A18 (NOLOCK) ON E.ATTR18_KEY_NAME=A18.ATTR18_KEY_NAME AND ISNULL(E.ATTR18_KEY_NAME,'')<>''          
   LEFT JOIN ATTR19_MST A19 (NOLOCK) ON E.ATTR19_KEY_NAME=A19.ATTR19_KEY_NAME AND ISNULL(E.ATTR19_KEY_NAME,'')<>''          
   LEFT JOIN ATTR20_MST A20 (NOLOCK) ON E.ATTR20_KEY_NAME=A20.ATTR20_KEY_NAME AND ISNULL(E.ATTR20_KEY_NAME,'')<>''          
   LEFT JOIN ATTR21_MST A21 (NOLOCK) ON E.ATTR21_KEY_NAME=A21.ATTR21_KEY_NAME AND ISNULL(E.ATTR21_KEY_NAME,'')<>''          
   LEFT JOIN ATTR22_MST A22 (NOLOCK) ON E.ATTR22_KEY_NAME=A22.ATTR22_KEY_NAME AND ISNULL(E.ATTR22_KEY_NAME,'')<>''          
   LEFT JOIN ATTR23_MST A23 (NOLOCK) ON E.ATTR23_KEY_NAME=A23.ATTR23_KEY_NAME AND ISNULL(E.ATTR23_KEY_NAME,'')<>''          
   LEFT JOIN ATTR24_MST A24 (NOLOCK) ON E.ATTR24_KEY_NAME=A24.ATTR24_KEY_NAME AND ISNULL(E.ATTR24_KEY_NAME,'')<>''          
   LEFT JOIN ATTR25_MST A25 (NOLOCK) ON E.ATTR25_KEY_NAME=A25.ATTR25_KEY_NAME AND ISNULL(E.ATTR25_KEY_NAME,'')<>''          
   WHERE E.SP_ID=@cFilterCriteria AND           
   (          
  SM.SECTION_CODE IS NULL OR SD.SUB_SECTION_CODE IS NULL OR A.ARTICLE_CODE IS NULL          
  OR P1.PARA1_CODE IS NULL OR P2.PARA2_CODE IS NULL OR P3.PARA3_CODE IS NULL OR P4.PARA4_CODE IS NULL OR P5.PARA5_CODE IS NULL OR P6.PARA6_CODE IS NULL          
  OR A1.ATTR1_KEY_CODE IS NULL OR A2.ATTR2_KEY_CODE IS NULL OR A3.ATTR3_KEY_CODE IS NULL OR A4.ATTR4_KEY_CODE IS NULL OR A5.ATTR5_KEY_CODE IS NULL          
  OR A6.ATTR6_KEY_CODE IS NULL OR A7.ATTR7_KEY_CODE IS NULL OR A8.ATTR8_KEY_CODE IS NULL OR A9.ATTR9_KEY_CODE IS NULL OR A10.ATTR10_KEY_CODE IS NULL          
  OR A11.ATTR11_KEY_CODE IS NULL OR A12.ATTR12_KEY_CODE IS NULL OR A13.ATTR13_KEY_CODE IS NULL OR A14.ATTR14_KEY_CODE IS NULL OR A15.ATTR15_KEY_CODE IS NULL          
  OR A16.ATTR16_KEY_CODE IS NULL OR A17.ATTR17_KEY_CODE IS NULL OR A18.ATTR18_KEY_CODE IS NULL OR A19.ATTR19_KEY_CODE IS NULL OR A20.ATTR20_KEY_CODE IS NULL          
  OR A21.ATTR21_KEY_CODE IS NULL OR A22.ATTR22_KEY_CODE IS NULL OR A23.ATTR23_KEY_CODE IS NULL OR A24.ATTR24_KEY_CODE IS NULL OR A25.ATTR25_KEY_CODE IS NULL          
   )          
          
 DECLARE @COLS VARCHAR(MAX),@CHAR INT,@NUM INT            
 IF EXISTS(SELECT TOP 1 * FROM #ERR WHERE ISNULL(ErrMsg,'')<>'')          
    BEGIN          
      UPDATE #ERR SET ErrMsg=REPLACE(ErrMsg,'found','found; ')          
      UPDATE #ERR SET ErrMsg=REPLACE(ErrMsg,'not found;  in attribute','not found in attribute')          
      SELECT COLUMN_NAME,CHARACTER_MAXIMUM_LENGTH,NUMERIC_PRECISION INTO #C FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='ARSPLAN_IMPORT_UPLOAD' AND COLUMN_NAME NOT LIKE '%CODE' AND COLUMN_NAME NOT IN ('sp_id','dept_id')                
      DECLARE COL CURSOR FOR SELECT * FROM #C          
         OPEN COL          
         FETCH NEXT FROM COL INTO @COLS,@CHAR,@NUM          
         WHILE @@FETCH_STATUS=0          
           BEGIN          
              IF @CHAR IS NOT NULL          
                SET @DTSQL='IF EXISTS(SELECT TOP 1 ['+@COLS+'] FROM #ERR WHERE ISNULL('+@COLS+','''')='''')          
                DELETE #C WHERE COLUMN_NAME='''+@COLS+''''          
              ELSE          
                SET @DTSQL='IF EXISTS(SELECT TOP 1 ['+@COLS+'] FROM #ERR WHERE ISNULL('+@COLS+',0)=0)          
                DELETE #C WHERE COLUMN_NAME='''+@COLS+''''          
              --PRINT '@ '+@DTSQL          
              EXEC(@DTSQL)          
             FETCH NEXT FROM COL INTO @COLS,@CHAR,@NUM          
           END          
         CLOSE COL          
         DEALLOCATE COL          
         SET @DTSQL=''          
         SELECT @DTSQL=COALESCE(@DTSQL,'')+UPPER(COLUMN_NAME)+',' FROM #C          
         --PRINT '# '+@DTSQL          
      SET @DTSQL=CASE WHEN RIGHT(@DTSQL,1)=',' THEN LEFT(@DTSQL,LEN(@DTSQL)-1) ELSE ISNULL(@DTSQL,'') END          
      SET @DTSQL='SELECT ERRMSG,'+@DTSQL+' FROM #ERR'          
      --PRINT '## '+@DTSQL          
      IF ISNULL(@DTSQL,'')<>'' EXEC(@DTSQL)          
    END          
 ELSE          
    SELECT ''ErrMsg             
   GOTO END_PROC          
          
        
        
             
   RETURN_ATTRS:          
   SELECT UPPER(REPLACE(TABLE_NAME,'_MST','_KEY_NAME')) TABLE_NAME,TABLE_CAPTION FROM CONFIG_ATTR          
   GOTO END_PROC          
             
             
   RETURN_PLAN_FIELDS:          
   SELECT STK_LEVEL_PARA_NAME TABLE_NAME,STK_LEVEL_PARA_desc TABLE_CAPTION          
   FROM ARS_MST AM (NOLOCK) JOIN ARS_STOCK_LEVEL_MST SM (NOLOCK) ON AM.ARS_ID=SM.ARS_ID          
   WHERE AM.PLAN_NAME=@cFilterCriteria          
   GOTO END_PROC          
             
             
   CREATE_ARO:          
   PRINT 'PLAN '+@cFilterCriteria    
   PRINT 'LOC '+@CCOLUMNNAME    
   EXEC SP3S_PREPARE_ARS_ID_UPLOAD_DETAIL @cPlan_Name=@cFilterCriteria,@LOC=@CCOLUMNNAME--,@DT=@CCOLUMNNAME          
   GOTO END_PROC          
             
   GET_SEASON_PERIOD:     
   SELECT TOP 1 DBO.GET_SEASON_DT(Season_Id,'FROM')From_DT,DBO.GET_SEASON_DT(Season_Id,'TILL')TO_DT    
   FROM SEASON_MST (NOLOCK)           
   WHERE SEASON_ID=@CARS_ID AND INACTIVE=0          
   GOTO END_PROC          
             
             
   GET_FILTERED_LOCATIONS:    
   IF NOT EXISTS(SELECT TOP 1 * FROM SYSOBJECTS WHERE XTYPE='U' AND NAME='TEMP_LOCATION_ARS_'+LTRIM(RTRIM(@CARS_ID)))    
      SET @DTSQL=N'SELECT CAST(1 AS BIT) AS CHK,A.DEPT_ID,A.DEPT_ID+''-''+A.DEPT_NAME as DEPT_NAME,A.DEPT_ALIAS     
      ,A.GROWTH_FACTOR,A.safety_FACTOR AS safety_level,CAST('''+@CCOLUMNORDER+''' AS VARCHAR(20)) AS SEASON_ID     
      ,'''+@CCOLUMNNAME+''' AS filter_Criteria,'''' AS filter_details    
      ,CAST(0 AS INT) AS MINIMUM_DAYS,CAST(0 AS INT) AS TARGET_DAYS,CAST(0 AS INT) AS MAXIMUM_DAYS    
      FROM LOCATION a (NOLOCK)     
      JOIN LOCUSERS b (NOLOCK) ON b.dept_id=a.dept_id     
      WHERE A.INACTIVE=0 AND b.user_code=''0000000'''    
      +CASE @cFilterCriteria WHEN '' THEN '' ELSE ' AND A.DEPT_ID '+@cFilterCriteria END    
   ELSE       
      SET @DTSQL=N'SELECT CAST(1 AS BIT) AS CHK,A.DEPT_ID,A.DEPT_ID+''-''+A.DEPT_NAME as DEPT_NAME,A.DEPT_ALIAS     
      ,ISNULL(c.GROWTH_FACTOR,0)GROWTH_FACTOR,ISNULL(c.safety_level,0)safety_level,CAST('''+@CCOLUMNORDER+''' AS VARCHAR(20)) AS SEASON_ID    
      ,'''+@CCOLUMNNAME+''' AS filter_Criteria,'''' AS filter_details    
      ,c.MINIMUM_DAYS,c.TARGET_DAYS,c.MAXIMUM_DAYS    
      FROM LOCATION a (NOLOCK)     
      JOIN LOCUSERS b (NOLOCK) ON b.dept_id=a.dept_id     
      LEFT JOIN TEMP_LOCATION_ARS_'+LTRIM(RTRIM(@CARS_ID))+' c ON c.DEPT_ID=A.DEPT_ID    
      WHERE A.INACTIVE=0 AND b.user_code=''0000000'''    
      +CASE @cFilterCriteria WHEN '' THEN '' ELSE ' AND A.DEPT_ID '+@cFilterCriteria END    
   PRINT @DTSQL    
   EXEC(@DTSQL)    
   GOTO END_PROC          
       
       
 EXPORT_DATA_TO_EXCEL:    
 DECLARE @SELECT VARCHAR(MAX),@FROM VARCHAR(MAX),@WHERE VARCHAR(MAX)    
 SET @SELECT='SELECT AD.DEPT_ID,AD.TARGET_DAILY_SALE,AD.MINIMUM_DAYS,AD.TARGET_DAYS,AD.MAXIMUM_DAYS,AD.SAFETY_LEVEL'    
 SET @FROM='FROM ARS_MST AM (NOLOCK)'+CHAR(13)+'JOIN ARS_DET AD (NOLOCK) ON AM.ARS_ID=AD.ARS_ID'    
 SET @WHERE='WHERE AM.ARS_ID='''+@CARS_ID+''''    
     
 PRINT '18/1-SELECT: '+@SELECT     
 PRINT '18/1-FROM: '+@FROM     
 PRINT '18/1-WHERE: '+@WHERE     
    IF NOT EXISTS(SELECT TOP 1 ARS_ID FROM ARS_STOCK_LEVEL_MST (NOLOCK) WHERE ARS_ID=@CARS_ID)    
       BEGIN    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND SECTION_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,'SECTION_NAME','Section'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND SUB_SECTION_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,'SUB_SECTION_NAME','Sub Section'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ARTICLE_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,'ARTICLE_NO','Article'    
          --PARAS       
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND PARA1_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,'PARA1_NAME',VALUE FROM CONFIG WHERE CONFIG_OPTION LIKE 'PARA1_caption' 
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND PARA2_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,'PARA2_NAME',VALUE FROM CONFIG WHERE CONFIG_OPTION LIKE 'PARA2_caption' 
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND PARA3_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,'PARA3_NAME',VALUE FROM CONFIG WHERE CONFIG_OPTION LIKE 'PARA3_caption'   
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND PARA4_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,'PARA4_NAME',VALUE FROM CONFIG WHERE CONFIG_OPTION LIKE 'PARA4_caption'   
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND PARA5_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,'PARA5_NAME',VALUE FROM CONFIG WHERE CONFIG_OPTION LIKE 'PARA5_caption'   
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND PARA6_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,'PARA6_NAME',VALUE FROM CONFIG WHERE CONFIG_OPTION LIKE 'PARA6_caption'    
          --ATTRIBUTES       
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR1_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR1_MST'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR2_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR2_MST'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR3_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR3_MST'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR4_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR4_MST'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR5_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR5_MST'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR6_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR6_MST'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR7_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR7_MST'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR8_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR8_MST'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR9_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR9_MST'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR10_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR10_MST'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR11_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR11_MST'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR12_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR12_MST'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR13_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR13_MST'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR14_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR14_MST'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR15_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR15_MST'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR16_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR16_MST'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR17_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR17_MST'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR18_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR18_MST'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR19_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR19_MST'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR20_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR20_MST'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR21_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR21_MST'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR22_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR22_MST'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR23_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR23_MST'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR24_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR24_MST'    
          IF EXISTS(SELECT * FROM ARS_DET (NOLOCK) WHERE ARS_ID=@CARS_ID AND ATTR25_KEY_CODE!='0000000')    
             INSERT ARS_STOCK_LEVEL_MST SELECT @CARS_ID,UPPER(COLUMN_NAME),TABLE_CAPTION FROM CONFIG_ATTR WHERE TABLE_NAME LIKE 'ATTR25_MST'    
       END    
 IF EXISTS(SELECT TOP 1 ARS_ID FROM ARS_STOCK_LEVEL_MST (NOLOCK) WHERE ARS_ID=@CARS_ID)    
    SET @SELECT=ISNULL(@SELECT,'')+','    
 --PRINT '18/1+2-SELECT: '+@SELECT      
 DECLARE @SELECT2 VARCHAR(MAX)=''  
 SELECT @SELECT2=COALESCE(@SELECT2,'')    
 +CASE     
 WHEN STK_LEVEL_PARA_NAME LIKE 'ARTICLE_NO' THEN 'ARTICLE.ARTICLE_NO'    
 WHEN STK_LEVEL_PARA_NAME LIKE 'SECTION_NAME%' THEN 'SECTIONM.SECTION_NAME'    
 WHEN STK_LEVEL_PARA_NAME LIKE 'SUB_SECTION_NAME%' THEN 'SECTIOND.SUB_SECTION_NAME'    
 WHEN STK_LEVEL_PARA_NAME LIKE 'PARA[3-6]%NAME' THEN REPLACE(STK_LEVEL_PARA_NAME,'_NAME','')+'.'+STK_LEVEL_PARA_NAME    
 WHEN STK_LEVEL_PARA_NAME LIKE 'PARA1_NAME' THEN 'PARA1.PARA1_NAME'    
 WHEN STK_LEVEL_PARA_NAME LIKE 'PARA2_NAME' THEN 'PARA2.PARA2_NAME'    
 END+' AS ['+STK_LEVEL_PARA_DESC+'],'    
    
 ,@FROM=COALESCE(@FROM,'')    
 +CASE     
 WHEN STK_LEVEL_PARA_NAME LIKE 'ARTICLE_NO' THEN ' JOIN ARTICLE (NOLOCK) ON ARTICLE.ARTICLE_CODE=AD.ARTICLE_CODE'    
 WHEN STK_LEVEL_PARA_NAME LIKE 'SECTION_NAME' THEN ' JOIN SECTIONM (NOLOCK) ON SECTIONM.SECTION_CODE=AD.SECTION_CODE'    
 WHEN STK_LEVEL_PARA_NAME LIKE 'SUB_SECTION_NAME' THEN ' JOIN SECTIOND (NOLOCK) ON SECTIOND.SUB_SECTION_CODE=AD.SUB_SECTION_CODE'    
 WHEN STK_LEVEL_PARA_NAME LIKE 'PARA[3-6]%NAME' THEN ' JOIN '+REPLACE(STK_LEVEL_PARA_NAME,'_NAME','')+' (NOLOCK) ON '+REPLACE(STK_LEVEL_PARA_NAME,'_NAME','')+REPLACE(STK_LEVEL_PARA_NAME,'_NAME','_CODE')+'AD.'+REPLACE(STK_LEVEL_PARA_NAME,'_NAME','_CODE') 

   
 WHEN STK_LEVEL_PARA_NAME LIKE 'PARA1_NAME' THEN ' JOIN PARA1 (NOLOCK) ON PARA1.PARA1_CODE=AD.PARA1_CODE'    
 WHEN STK_LEVEL_PARA_NAME LIKE 'PARA2_NAME' THEN ' JOIN PARA2 (NOLOCK) ON PARA2.PARA2_CODE=AD.PARA2_CODE'    
 WHEN STK_LEVEL_PARA_NAME LIKE 'ATTR%KEY_NAME' THEN ' JOIN '+REPLACE(STK_LEVEL_PARA_NAME,'_KEY_NAME','_MST')+' (NOLOCK) ON '+REPLACE(STK_LEVEL_PARA_NAME,'_KEY_NAME','_MST')+'.'+REPLACE(STK_LEVEL_PARA_NAME,'NAME','CODE')+'=AD.'+REPLACE(STK_LEVEL_PARA_NAME,

'NAME','CODE')    
 END    
 FROM ARS_STOCK_LEVEL_MST (NOLOCK) WHERE ARS_ID=@CARS_ID    
    
 --PRINT '18/2-SELECT: '+@SELECT2     
 --PRINT '18/2-FROM: '+@FROM     
 --PRINT '18/2-WHERE: '+@WHERE     
  
  
SET @SELECT=LTRIM(RTRIM(@SELECT))+ISNULL(@SELECT2,'')    
 IF RIGHT(@SELECT,1)=',' SET @SELECT=LEFT(@SELECT,LEN(@SELECT)-1)    
 SET @SELECT=@SELECT+CHAR(13)+@FROM+CHAR(13)+@WHERE    
 PRINT '18:'+@SELECT    
 EXEC(@SELECT)       
 GOTO END_PROC    
     
     
 RET_EXCEL_IMPORT_FILEDS:    
 DECLARE @FILEDS VARCHAR(MAX)='CREATE TABLE #TAB(',@VALUES VARCHAR(MAX)='INSERT #TAB SELECT '    
 SELECT @FILEDS=COALESCE(@FILEDS,'')+'['+REPLACE(UPPER(STK_LEVEL_PARA_DESC),'_',' ')+'] VARCHAR(100),',@VALUES=COALESCE(@VALUES,'')+''''+UPPER(STK_LEVEL_PARA_DESC)+''','    
    FROM ARS_ARS_STOCK_LEVEL_MST_UPLOAD (NOLOCK) WHERE SP_ID=@cFilterCriteria          
    SET @FILEDS+='[Min Days] varchar(100),[Max Days] varchar(100),[Target Days] varchar(100),[Target Daily Sale] varchar(100),[Safety Level] varchar(100),[Location] varchar(100));'    
    SET @VALUES+='''Min Days'',''Max Days'',''Target Days'',''Target Daily Sale'',''Safety Level'',''Location'';'    
    SET @FILEDS+=/*@VALUES+*/'SELECT * FROM #TAB'    
    EXEC(@FILEDS)    
   GOTO END_PROC    
   
GET_ARS_DET_ATTR:       
SELECT TOP 1 'SECTION_CODE' ATTR FROM ARS_DET WHERE ARS_ID=@CARS_ID AND SECTION_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'SECTION_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND SUB_SECTION_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ARTICLE_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ARTICLE_CODE NOT LIKE '000%000'UNION 
SELECT TOP 1 'PARA1_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND PARA1_CODE NOT LIKE '0000000'UNION
SELECT TOP 1 'PARA2_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND PARA2_CODE NOT LIKE '0000000'UNION
SELECT TOP 1 'PARA3_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND PARA3_CODE NOT LIKE '0000000'UNION
SELECT TOP 1 'PARA4_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND PARA4_CODE NOT LIKE '0000000'UNION
SELECT TOP 1 'PARA5_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND PARA5_CODE NOT LIKE '0000000'UNION
SELECT TOP 1 'PARA6_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND PARA6_CODE NOT LIKE '0000000'UNION
SELECT TOP 1 'ATTR1_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR1_KEY_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ATTR2_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR2_KEY_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ATTR3_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR3_KEY_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ATTR4_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR4_KEY_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ATTR5_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR5_KEY_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ATTR6_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR6_KEY_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ATTR7_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR7_KEY_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ATTR8_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR8_KEY_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ATTR9_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR9_KEY_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ATTR10_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR10_KEY_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ATTR11_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR11_KEY_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ATTR12_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR12_KEY_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ATTR13_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR13_KEY_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ATTR14_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR14_KEY_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ATTR15_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR15_KEY_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ATTR16_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR16_KEY_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ATTR17_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR17_KEY_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ATTR18_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR18_KEY_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ATTR19_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR19_KEY_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ATTR20_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR20_KEY_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ATTR21_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR21_KEY_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ATTR22_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR22_KEY_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ATTR23_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR23_KEY_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ATTR24_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR24_KEY_CODE NOT LIKE '000%000' UNION
SELECT TOP 1 'ATTR25_KEY_CODE' FROM ARS_DET WHERE ARS_ID=@CARS_ID AND ATTR25_KEY_CODE NOT LIKE '000%000'
GOTO END_PROC



   END_PROC:          
             
   --- Changed by Sanjay (12-11-2018)          
   IF ISNULL(@CERRMSG,'')<>''         
      SELECT ISNULL(@CERRMSG,'') as errmsg          
END    