CREATE PROCEDURE SP_SEND_MIRROR_PRCL_DATA
(	
	 @CUPLOADEDXNID VARCHAR(50)=''
	,@CCURLOCID VARCHAR(5)	 
	,@CERRMSG VARCHAR(1000) OUTPUT
)
--WITH ENCRYPTION
AS
BEGIN
     DECLARE @DTSQL NVARCHAR(MAX),@CSTEP VARCHAR(10),@CFILTERCONDITION VARCHAR(MAX),
             @CMEMOID VARCHAR(50),@DMEMOLASTUPDATE DATETIME,
             @CTABLENAME VARCHAR(100),@CTEMPTABLE VARCHAR(100),@CTEMPMASTERTABLE VARCHAR(100),
             @CTEMPDETAILTABLE VARCHAR(100),@BRECFOUND BIT
     
     
     DECLARE @TXNSSENDINFO TABLE (ORG_TABLENAME VARCHAR(100),TMP_TABLENAME VARCHAR(100),XN_ID VARCHAR(100)) 
BEGIN TRY
     DECLARE @CTEMPDBNAME VARCHAR(100)
	 SET @CTEMPDBNAME=''

	 SET @CSTEP=00
	SET @CMEMOID=@CUPLOADEDXNID
	SET @CSTEP=220

	IF @CMEMOID=''
	   GOTO END_PROC

	---- SEND THE PRCL MEMO MASTER TABLE
	SELECT A.*,'PRCL_PARCEL_MST_UPLOAD' AS TARGET_TABLENAME FROM PARCEL_MST A (NOLOCK) WHERE A.parcel_memo_ID =@CMEMOID 
	

	SET @CSTEP=250
	---- SEND THE PRCL MEMO DETAIL TABLE
	SELECT A.*,'PRCL_PARCEL_DET_UPLOAD' AS TARGET_TABLENAME FROM PARCEL_DET A (NOLOCK) WHERE A.parcel_memo_ID =@CMEMOID 
	
	
	
	SET @CSTEP=270
	---- SEND THE PRCL MEMO DETAIL TABLE
	SELECT DISTINCT  A.*,'PRCL_ANGM_UPLOAD'  AS TARGET_TABLENAME FROM ANGM A (NOLOCK)
	JOIN PARCEL_MST B (NOLOCK) ON A.Angadia_code =B.angadia_code 
	
	
	GOTO END_PROC
	
	
	END TRY
BEGIN CATCH
	SET @CERRMSG='P: SP_SEND_MIRROR_PRCL_DATA, STEP:'+@CSTEP+', MESSAGE:'+ERROR_MESSAGE()
	GOTO END_PROC
END CATCH 	
	
END_PROC:
		
	
END
---'END OF CREATING PROCEDURE - SP_SEND_MIRROR_PRCL_DATA'
