CREATE PROCEDURE SPCAL_CUSTOM_DUTY
@DMEMODT DATETIME,
@CPRODUCTCODE VARCHAR(50),
@CFORMID VARCHAR(10),
@NMARKDOWNPCT NUMERIC(7,3),
@NQTY NUMERIC(10,2),
@NSPID INT=0
--WITH ENCRYPTION
AS
BEGIN
	DECLARE @CSTATECODE CHAR(7),@CCURLOCID VARCHAR(5),@CSSCODE VARCHAR(10),
			@CLOCSSTMEMOID VARCHAR(40),@NBASEPRICE NUMERIC(10,2),@NBCDPCT NUMERIC(7,3),
			@NCVDPCT NUMERIC(7,3),@NMINCUSTOMDUTY NUMERIC(10,2),@NFORMTAXPCT NUMERIC(7,3),
			@NECPCT1 NUMERIC(7,3),@NECPCT2 NUMERIC(7,3),@NECPCT NUMERIC(7,3),@NCVDACCPCT NUMERIC(7,3),
			@NBCDASSESSABLEVALUE NUMERIC(10,2),@NBCD NUMERIC(10,2),@NTOTALCUSTOMDUTY NUMERIC(10,2),
			@NMINCVD NUMERIC(10,2),@NLANDEDCOSTTOPARTY NUMERIC(10,2),@NCVDCOMPONENT NUMERIC(10,2),
			@NNETRATE NUMERIC(10,2),@NCVDAMT NUMERIC(10,2),@NFORMTAXAMT NUMERIC(10,2),
			@NCUSTOMDUTY NUMERIC(10,2),@CECPCT1 VARCHAR(20),@CECPCT2 VARCHAR(20),@CCVDACCPCT VARCHAR(20),
			@CBASEPRICE VARCHAR(5),@CCMD NVARCHAR(MAX),@CSOURCEPC VARCHAR(50)

	IF OBJECT_ID('TEMPDB..#TMPCUSTOM','U') IS NOT NULL
		DROP TABLE #TMPCUSTOM			
	
	SELECT PRODUCT_CODE,CONVERT(NUMERIC(10,2),0) AS QTY INTO #TMPCUSTOM FROM SKU WHERE 1=2
	
	IF @CPRODUCTCODE=''
	BEGIN
		SET @CCMD=N'SELECT PRODUCT_CODE,QUANTITY FROM TMP_CUSTOMDUTY_'+LTRIM(RTRIM(STR(@NSPID)))
		
		INSERT #TMPCUSTOM
		EXEC SP_EXECUTESQL @CCMD
	END	
	ELSE
		INSERT #TMPCUSTOM
		SELECT @CPRODUCTCODE,@NQTY
		
	DECLARE @TRETINV TABLE (PRODUCT_CODE VARCHAR(50),CUSTOM_DUTY_PER NUMERIC(7,3),CVD_AMT NUMERIC(10,2),CVD_PER NUMERIC(7,3),
	CUSTOM_DUTY_AMT NUMERIC(10,2),TOTAL_CUSTOM_DUTY_AMT NUMERIC(10,2),RATE NUMERIC(10,2),
	NET_RATE NUMERIC(10,2),TAX_PERCENTAGE NUMERIC(10,2),TAX_AMOUNT NUMERIC(10,2))
			
			
	SELECT TOP 1 @CCURLOCID=VALUE FROM CONFIG WHERE CONFIG_OPTION='LOCATION_ID'
	
	SELECT TOP 1 @CSTATECODE=STATE_CODE FROM LOCATION A JOIN AREA B ON A.AREA_CODE=B.AREA_CODE
	JOIN CITY C ON C.CITY_CODE=B.CITY_CODE WHERE DEPT_ID=@CCURLOCID
	
	SELECT @CSSCODE=SUB_SECTION_CODE FROM SKU A JOIN ARTICLE B ON A.ARTICLE_CODE=B.ARTICLE_CODE
	WHERE A.PRODUCT_CODE=@CPRODUCTCODE
		
    SELECT TOP 1 @CLOCSSTMEMOID = A.MEMO_ID     
	FROM LOCSST_MST A    
	JOIN LOCSST B ON B.MEMO_ID=A.MEMO_ID    
	WHERE A.FROM_DT<=@DMEMODT AND B.SUB_SECTION_CODE=@CSSCODE AND A.STATE_CODE=@CSTATECODE    
	ORDER BY A.FROM_DT DESC    
 
	SELECT TOP 1 @NBCDPCT=BCD_PERCENTAGE,@NCVDPCT  = CVD_PERCENTAGE,@NMINCVD=MIN_CUSTOM_DUTY
	FROM LOCSST WHERE MEMO_ID=@CLOCSSTMEMOID AND SUB_SECTION_CODE=@CSSCODE
	
	IF ISNULL(@NBCDPCT,0)=0
		GOTO END_PROC
	
	
	SELECT TOP 1 @CBASEPRICE = VALUE FROM CONFIG WHERE CONFIG_OPTION='CUSTOMDUTY_BASEPRICE'
					
	SELECT TOP 1 @NFORMTAXPCT=TAX_PERCENTAGE FROM FORM WHERE FORM_ID=@CFORMID
			
	SELECT TOP 1 @CECPCT1 = VALUE FROM CONFIG WHERE CONFIG_OPTION='EDU_CESS_ON_CVD'
	SELECT TOP 1 @CECPCT2 = VALUE FROM CONFIG WHERE CONFIG_OPTION='HIGHER_EDU_CESS_ON_CVD'
	SELECT TOP 1 @CCVDACCPCT=VALUE FROM CONFIG WHERE CONFIG_OPTION='CVD_ACCESSIBLEVAL_PCT'
	
	SET @NECPCT1=(CASE WHEN ISNULL(@CECPCT1,'')<>'' THEN CONVERT(NUMERIC(7,3),@CECPCT1) ELSE 0 END)
	SET @NECPCT2=(CASE WHEN ISNULL(@CECPCT2,'')<>'' THEN CONVERT(NUMERIC(7,3),@CECPCT2) ELSE 0 END)
	SET @NCVDACCPCT=(CASE WHEN ISNULL(@CCVDACCPCT,'')<>'' THEN CONVERT(NUMERIC(7,3),@CCVDACCPCT) ELSE 0 END)
	
	SET @NECPCT   = @NECPCT1+@NECPCT2

LBLNEXTPC:
	
	SELECT TOP 1 @CSOURCEPC=PRODUCT_CODE,@NQTY=QTY FROM #TMPCUSTOM
	
	IF ISNULL(@CSOURCEPC,'')=''
		GOTO END_PROC

	SELECT TOP 1 @NBASEPRICE=(CASE WHEN @CBASEPRICE='1' THEN  MRP ELSE WS_PRICE END) 
	FROM SKU WHERE PRODUCT_CODE=@CSOURCEPC
			
	SET @NLANDEDCOSTTOPARTY = @NBASEPRICE*@NMARKDOWNPCT/100
	SET @NCVDCOMPONENT = @NBASEPRICE*@NCVDACCPCT/100
	SET @NCVDAMT = ROUND(@NCVDCOMPONENT*@NCVDPCT/100, 2)
	
	IF @CBASEPRICE='1'
	BEGIN
		SET @NBCDASSESSABLEVALUE = ((@NBASEPRICE-@NLANDEDCOSTTOPARTY)/(100+@NFORMTAXPCT))*@NFORMTAXPCT
		SET @NBCDASSESSABLEVALUE = (@NBASEPRICE-@NLANDEDCOSTTOPARTY)-@NBCDASSESSABLEVALUE-@NCVDAMT
		SET @NBCD = ROUND((@NBCDASSESSABLEVALUE/(100+@NBCDPCT*2))*@NBCDPCT, 2)
	END
	ELSE
	BEGIN
		SELECT @NBCDASSESSABLEVALUE = @NCVDCOMPONENT,@NCVDAMT=0
		SET @NBCD=@NCVDCOMPONENT*@NCVDPCT/100
		
		SET @NMINCVD=@NMINCVD*@NBCDPCT/100
	END
	

	IF @NBCD<@NMINCVD
		SET @NBCD = @NMINCVD
	
	IF @CBASEPRICE='1'
		SET @NNETRATE = (@NBASEPRICE-@NLANDEDCOSTTOPARTY)/((100+@NFORMTAXPCT)/100)-(@NBCD+@NCVDAMT)
	ELSE
		SET @NNETRATE = @NBASEPRICE	

	SET @NFORMTAXAMT = ROUND((@NNETRATE+@NBCD+@NCVDAMT)*@NFORMTAXPCT/100, 2)
	
	SELECT @NCUSTOMDUTY=@NBCD*@NQTY,@NTOTALCUSTOMDUTY=(@NBCD+@NCVDAMT)*@NQTY
	
	
	INSERT @TRETINV
	SELECT @CSOURCEPC AS PRODUCT_CODE,@NBCDPCT AS CUSTOM_DUTY_PER,@NCVDAMT AS CVD_AMT,@NCVDPCT AS CVD_PER,@NCUSTOMDUTY AS CUSTOM_DUTY_AMT,
	@NTOTALCUSTOMDUTY AS TOTAL_CUSTOM_DUTY_AMT,
	(CASE WHEN @CBASEPRICE='1' THEN @NBCDASSESSABLEVALUE ELSE @NBASEPRICE END) AS RATE,
	(CASE WHEN @CBASEPRICE='1' THEN @NBCDASSESSABLEVALUE ELSE @NBASEPRICE END) AS NET_RATE,
	@NFORMTAXPCT AS TAX_PERCENTAGE,@NFORMTAXAMT AS TAX_AMOUNT
	
	DELETE FROM #TMPCUSTOM WHERE PRODUCT_CODE=@CSOURCEPC
		
	SET @CSOURCEPC=''
		
	GOTO LBLNEXTPC

END_PROC:
	SELECT * FROM @TRETINV
			
END
