

IF NOT EXISTS (SELECT CONFIG_OPTION FROM CONFIG WHERE CONFIG_OPTION='UDPATE_MSP_WSP_CMM' AND VALUE='1')
BEGIN
	UPDATE CMM01106
	SET MRP_WSP = 1 WHERE ISNULL(MRP_WSP,0)=0
	
	IF NOT EXISTS (SELECT CONFIG_OPTION FROM CONFIG WHERE CONFIG_OPTION='UDPATE_MSP_WSP_CMM')
       INSERT CONFIG (CONFIG_OPTION,VALUE,ROW_ID,LAST_UPDATE)
	   VALUES ('UDPATE_MSP_WSP_CMM','1','',GETDATE())	
	ELSE	
		UPDATE CONFIG SET VALUE='1' WHERE CONFIG_OPTION='UDPATE_MSP_WSP_CMM'
END
