CREATE  PROCEDURE SP_PRD_JOBWORK_REPORT_PCS  

(  
 @CAGENCY_CODE VARCHAR(100)='',  
 @NPENDING INT=0,
 @NSUMMARY INT=0,  -- 1 FOR SUMMARY 2 FOR DETAILS
 @CARTICLE_CODE VARCHAR(10)='',
 @DAS_ON DATETIME=''
)  
AS  
BEGIN  
       
      DECLARE @DTSQL NVARCHAR(MAX),@AC_CODE VARCHAR(100)  
     IF @CAGENCY_CODE=''  
     BEGIN  
     SET @AC_CODE=''  
     SET @CAGENCY_CODE='IN('''')'  
     END  
     ELSE   
     BEGIN  
     SET @AC_CODE='LATER'  
     END  
    
     IF OBJECT_ID ('TEMPDB..#TMPISSUE','U') IS NOT NULL  
        DROP TABLE #TMPISSUE  
        
       IF OBJECT_ID ('TEMPDB..#TMPISSUE','U') IS NOT NULL    
        DROP TABLE #TMPISSUE    
          
      SELECT ORD.WORK_ORDER_ID AS ORDER_ID, ORD.ORDER_NO,  A.REF_AGENCY_CODE AS AGENCY_CODE,B.PARA1_CODE,B.PARA2_CODE,B.ARTICLE_CODE,    
     C.AGENCY_NAME,P1.PARA1_NAME,P2.PARA2_NAME,    
     AR.ARTICLE_NO AS FG_ARTICLE_NO,    
     AR.ARTICLE_NAME AS FG_ARTICLE_NAME,    
     B.ISSUE_QTY AS ISSUE_QTY
     INTO #TMPISSUE    
     FROM PRD_AGENCY_ISSUE_MATERIAL_MST (NOLOCK) A    
     JOIN PRD_AGENCY_ISSUE_ROW_MATERIAL_DET (NOLOCK) B ON A.MEMO_ID =B.MEMO_ID   
     JOIN  
     (  
       SELECT MST.MEMO_NO AS ORDER_NO, A.MEMO_ID, REF_MATERIAL_ROW_ID,A.REF_PRD_WORKORDER_MEMOID AS WORK_ORDER_ID   
       FROM PRD_AGENCY_ISSUE_MATERIAL_DET A  
       JOIN PRD_WO_MST MST ON A.REF_PRD_WORKORDER_MEMOID=MST.MEMO_ID  
       GROUP BY MST.MEMO_NO,A.MEMO_ID, REF_MATERIAL_ROW_ID,A.REF_PRD_WORKORDER_MEMOID  
     ) ORD ON  ORD.MEMO_ID=B.MEMO_ID AND B.ROW_ID =ORD.REF_MATERIAL_ROW_ID    
     JOIN ARTICLE AR ON AR.ARTICLE_CODE=B.ARTICLE_CODE    
     JOIN PRD_AGENCY_MST (NOLOCK) C ON A.REF_AGENCY_CODE =C.AGENCY_CODE    
     JOIN PARA1 P1 ON P1.PARA1_CODE=B.PARA1_CODE    
     JOIN PARA2 P2 ON P2.PARA2_CODE=B.PARA2_CODE    
     WHERE  
     1=2    
        
          
    SET @DTSQL=N' SELECT ORD.WORK_ORDER_ID AS ORDER_ID, ORD.ORDER_NO,  A.REF_AGENCY_CODE AS AGENCY_CODE,B.PARA1_CODE,B.PARA2_CODE,B.ARTICLE_CODE,  
      C.AGENCY_NAME,P1.PARA1_NAME,P2.PARA2_NAME,  
     AR.ARTICLE_NO AS FG_ARTICLE_NO,  
     AR.ARTICLE_NAME AS FG_ARTICLE_NAME,  
     SUM(B.ISSUE_QTY) AS ISSUE_QTY  
     FROM PRD_AGENCY_ISSUE_MATERIAL_MST (NOLOCK) A  
     JOIN PRD_AGENCY_ISSUE_ROW_MATERIAL_DET (NOLOCK) B ON A.MEMO_ID =B.MEMO_ID 
     JOIN
     (
       SELECT MST.MEMO_NO AS ORDER_NO, A.MEMO_ID, REF_MATERIAL_ROW_ID,A.REF_PRD_WORKORDER_MEMOID AS WORK_ORDER_ID 
       FROM PRD_AGENCY_ISSUE_MATERIAL_DET A
       JOIN PRD_WO_MST MST ON A.REF_PRD_WORKORDER_MEMOID=MST.MEMO_ID
       GROUP BY MST.MEMO_NO,A.MEMO_ID, REF_MATERIAL_ROW_ID,A.REF_PRD_WORKORDER_MEMOID
     ) ORD ON  ORD.MEMO_ID=B.MEMO_ID AND B.ROW_ID =ORD.REF_MATERIAL_ROW_ID  
     JOIN ARTICLE AR ON AR.ARTICLE_CODE=B.ARTICLE_CODE  
     JOIN PRD_AGENCY_MST (NOLOCK) C ON A.REF_AGENCY_CODE =C.AGENCY_CODE  
     JOIN PARA1 P1 ON P1.PARA1_CODE=B.PARA1_CODE  
     JOIN PARA2 P2 ON P2.PARA2_CODE=B.PARA2_CODE  
     WHERE ('''+@AC_CODE+'''='''' OR C.AC_CODE  '+@CAGENCY_CODE+' )  
     AND ('''+@CARTICLE_CODE+'''='''' OR B.ARTICLE_CODE='''+@CARTICLE_CODE+''')  
     AND ('''+CONVERT(VARCHAR(10), @DAS_ON,121)+'''=''1900-01-01'' OR A.MEMO_DT<='''+CONVERT(VARCHAR(10), @DAS_ON,121)+''')    
     AND A.CANCELLED =0  
     GROUP BY ORD.WORK_ORDER_ID ,B.ARTICLE_CODE,A.REF_AGENCY_CODE,B.PARA1_CODE,B.PARA2_CODE,C.AGENCY_NAME,P1.PARA1_NAME,P2.PARA2_NAME,  
     AR.ARTICLE_NO ,  
     AR.ARTICLE_NAME ,ORD.ORDER_NO'
     
     PRINT @DTSQL  
     INSERT INTO #TMPISSUE  
     EXEC SP_EXECUTESQL @DTSQL  
     
     
      
       
       
     IF OBJECT_ID ('TEMPDB..#TMPREC','U') IS NOT NULL    
        DROP TABLE #TMPREC   
          
          
   SELECT ORD.ORDER_ID, B.AGENCY_CODE,A.ARTICLE_CODE ,PARA1_CODE,PARA2_CODE,    
   REC_QTY AS  REC_QTY
   INTO #TMPREC    
   FROM PRD_AGENCY_ROW_MATERIAL_RECEIPT_DET A    
   JOIN PRD_AGENCY_MATERIAL_RECEIPT_MST B ON A.MEMO_ID=B.MEMO_ID  
   JOIN  
   (  
      
   SELECT A.REF_MATERIAL_ROW_ID , A.MEMO_ID,B.ORDER_ID FROM PRD_AGENCY_MATERIAL_RECEIPT_DET A    
    JOIN    
    (    
     SELECT A.ROW_ID,A.REF_PRD_WORKORDER_MEMOID AS ORDER_ID FROM PRD_AGENCY_ISSUE_MATERIAL_DET A  
     JOIN PRD_AGENCY_ISSUE_MATERIAL_MST B ON A.MEMO_ID =B.MEMO_ID   
     WHERE CANCELLED =0  
          
     UNION     
     SELECT A.ROW_ID,A.REF_PRD_WORKORDER_MEMOID AS ORDER_ID FROM PRD_AGENCY_ISSUE_MATERIAL_DET_PENDING  A  
      JOIN PRD_AGENCY_ISSUE_MATERIAL_MST B ON A.MEMO_ID =B.MEMO_ID   
     WHERE CANCELLED =0    
    ) B ON A.REF_ROW_ID=B.ROW_ID    
    GROUP BY A.REF_MATERIAL_ROW_ID ,A.MEMO_ID,B.ORDER_ID    
   )ORD ON ORD.MEMO_ID=B.MEMO_ID    
   AND ORD.REF_MATERIAL_ROW_ID =A.ROW_ID   
  JOIN PRD_AGENCY_MST (NOLOCK) C ON B.AGENCY_CODE =C.AGENCY_CODE      
   WHERE 1=2  
    
   
     
   SET @DTSQL=N'SELECT ORD.ORDER_ID, B.AGENCY_CODE,A.ARTICLE_CODE ,PARA1_CODE,PARA2_CODE,  
   SUM(REC_QTY) AS  REC_QTY  
   FROM PRD_AGENCY_ROW_MATERIAL_RECEIPT_DET A  
   JOIN PRD_AGENCY_MATERIAL_RECEIPT_MST B ON A.MEMO_ID=B.MEMO_ID
   JOIN
   (
    
   SELECT A.REF_MATERIAL_ROW_ID , A.MEMO_ID,B.ORDER_ID FROM PRD_AGENCY_MATERIAL_RECEIPT_DET A  
    JOIN  
    (  
     SELECT A.ROW_ID,A.REF_PRD_WORKORDER_MEMOID AS ORDER_ID FROM PRD_AGENCY_ISSUE_MATERIAL_DET A
     JOIN PRD_AGENCY_ISSUE_MATERIAL_MST B ON A.MEMO_ID =B.MEMO_ID 
     WHERE CANCELLED =0
     AND ('''+CONVERT(VARCHAR(10), @DAS_ON,121)+'''=''1900-01-01'' OR B.MEMO_DT<='''+CONVERT(VARCHAR(10), @DAS_ON,121)+''') 
        
     UNION   
     SELECT A.ROW_ID,A.REF_PRD_WORKORDER_MEMOID AS ORDER_ID FROM PRD_AGENCY_ISSUE_MATERIAL_DET_PENDING  A
      JOIN PRD_AGENCY_ISSUE_MATERIAL_MST B ON A.REF_ISSUE_ID =B.MEMO_ID --MEMO_ID 
     WHERE CANCELLED =0  
     AND ('''+CONVERT(VARCHAR(10), @DAS_ON,121)+'''=''1900-01-01'' OR B.MEMO_DT<='''+CONVERT(VARCHAR(10), @DAS_ON,121)+''') 
    ) B ON A.REF_ROW_ID=B.ROW_ID  
    GROUP BY A.REF_MATERIAL_ROW_ID ,A.MEMO_ID,B.ORDER_ID  
   )ORD ON ORD.MEMO_ID=B.MEMO_ID  
   AND ORD.REF_MATERIAL_ROW_ID =A.ROW_ID 
  JOIN PRD_AGENCY_MST (NOLOCK) C ON B.AGENCY_CODE =C.AGENCY_CODE    
  WHERE ( '''+@AC_CODE+'''='''' OR C.AC_CODE '+@CAGENCY_CODE+')  
   AND ('''+@CARTICLE_CODE+'''='''' OR A.ARTICLE_CODE='''+@CARTICLE_CODE+''')    
   AND B.CANCELLED =0  
   GROUP BY ORD.ORDER_ID,B.AGENCY_CODE,A.ARTICLE_CODE ,PARA1_CODE,PARA2_CODE '
    
   PRINT @DTSQL  
   INSERT INTO #TMPREC  
   EXEC SP_EXECUTESQL @DTSQL  
   
   IF ISNULL(@NSUMMARY,0)=1
   BEGIN
	   SELECT A.AGENCY_NAME,  
			  A.FG_ARTICLE_NO,  
			  A.FG_ARTICLE_NAME,  
			  A.PARA1_NAME AS FG_COLOR,  
			  A.PARA2_NAME AS FG_SIZE,  
	   SUM(A.ISSUE_QTY) AS ISSUE_QTY ,  
	   SUM(ISNULL(B.REC_QTY,0)) AS REC_QTY,  
	   SUM(A.ISSUE_QTY)-SUM(ISNULL(B.REC_QTY,0)) AS PENDING_QTY  
	   FROM #TMPISSUE A  
	   LEFT OUTER JOIN   
	   (  
	      
		SELECT A.ORDER_ID, A.AGENCY_CODE,A.ARTICLE_CODE ,A.PARA1_CODE,A.PARA2_CODE,  
		A.REC_QTY   
		FROM #TMPREC A  
	      
	   ) B ON A.AGENCY_CODE=B.AGENCY_CODE AND A.PARA1_CODE =B.PARA1_CODE   
	   AND A.PARA2_CODE =B.PARA2_CODE AND A.ARTICLE_CODE=B.ARTICLE_CODE 
	   AND A.ORDER_ID=B.ORDER_ID
	   WHERE (@NPENDING=0 OR  A.ISSUE_QTY-ISNULL(B.REC_QTY,0) >0)
	   GROUP BY A.AGENCY_NAME,  
			  A.FG_ARTICLE_NO,  
			  A.FG_ARTICLE_NAME,  
			  A.PARA1_NAME ,  
			  A.PARA2_NAME 
	   ORDER BY AGENCY_NAME  
  END
  ELSE
  BEGIN
       
       SELECT A.ORDER_NO ,
			  A.AGENCY_NAME,  
			  A.FG_ARTICLE_NO,  
			  A.FG_ARTICLE_NAME,  
			  A.PARA1_NAME AS FG_COLOR,  
			  A.PARA2_NAME AS FG_SIZE,  
	   A.ISSUE_QTY ,  
	   ISNULL(B.REC_QTY,0) AS REC_QTY,  
	   A.ISSUE_QTY-ISNULL(B.REC_QTY,0) AS PENDING_QTY  
	   FROM #TMPISSUE A  
	   LEFT OUTER JOIN   
	   (  
	      
		SELECT A.ORDER_ID, A.AGENCY_CODE,A.ARTICLE_CODE ,A.PARA1_CODE,A.PARA2_CODE,  
		A.REC_QTY   
		FROM #TMPREC A  
	      
	   ) B ON A.AGENCY_CODE=B.AGENCY_CODE AND A.PARA1_CODE =B.PARA1_CODE   
	   AND A.PARA2_CODE =B.PARA2_CODE AND A.ARTICLE_CODE=B.ARTICLE_CODE 
	   AND A.ORDER_ID=B.ORDER_ID
	   WHERE (@NPENDING=0 OR  A.ISSUE_QTY-ISNULL(B.REC_QTY,0) >0)
	   ORDER BY AGENCY_NAME  
  
  END        
END
