CREATE PROCEDURE SP_PRD_PRODUCT_DETAIL    
(      
 @CPRODUCTCODE VARCHAR(50)      
) 
--WITH ENCRYPTION
     
AS       
BEGIN      
 SELECT TOP 1 A.AC_CODE, F.UOM_TYPE, H.SECTION_NAME, G.SUB_SECTION_NAME, A.PRODUCT_UID,      
 CONVERT(VARCHAR, A.INV_DT, 105) AS INV_DT, A.INV_NO,LM.AC_NAME,        
 A.PURCHASE_PRICE, A.MRP, B.ARTICLE_CODE, B.ARTICLE_NO, B.ARTICLE_NAME, B.ARTICLE_DESC, C.PARA1_NAME, D.PARA2_NAME,           
 E.PARA3_NAME, P4.PARA4_NAME, P5.PARA5_NAME , P6.PARA6_NAME, F.UOM_CODE, F.UOM_NAME,
  CAST(0 AS NUMERIC(10,2)) AS FREIGHT, CAST(0 AS NUMERIC(10,2)) AS  DISCOUNT_AMOUNT, CAST(0 AS NUMERIC(10,2)) AS TAX_AMOUNT, I.FORM_ID,       
 I.FORM_NAME, CAST(0 AS NUMERIC(10,2)) AS  OTHER_CHARGES, I.TAX_PERCENTAGE, ISNULL(PMT.QUANTITY_IN_STOCK,0) AS [QUANTITY_IN_STOCK],      
 A.PURCHASE_PRICE AS RATE ,      
 ISNULL(B.DT_CREATED,'') AS [ART_DT_CREATED],ISNULL(E.DT_CREATED,'') AS [PARA3_DT_CREATED],ISNULL(A.DT_CREATED,'') AS [SKU_DT_CREATED],    
 X.MRR_NO ,B.CODING_SCHEME,B.DISCON,LM.CITY,CAST(0 AS NUMERIC(10,2)) AS  ROUND_OFF ,CAST(0 AS NUMERIC(10,2)) AS  EXCISE_DUTY_AMOUNT ,
 X.BILL_NO	    
 FROM PRD_SKU A           
 JOIN ARTICLE B (NOLOCK) ON A.ARTICLE_CODE = B.ARTICLE_CODE            
 JOIN PARA1 C (NOLOCK) ON A.PARA1_CODE = C.PARA1_CODE            
 JOIN PARA2 D (NOLOCK) ON A.PARA2_CODE = D.PARA2_CODE           
 JOIN PARA3 E (NOLOCK) ON A.PARA3_CODE = E.PARA3_CODE            
 JOIN PARA4 P4 (NOLOCK) ON A.PARA4_CODE = P4.PARA4_CODE            
 JOIN PARA5 P5 (NOLOCK) ON A.PARA5_CODE = P5.PARA5_CODE            
 JOIN PARA6 P6 (NOLOCK) ON A.PARA6_CODE = P6.PARA6_CODE    
      
 JOIN UOM F (NOLOCK) ON B.UOM_CODE = F.UOM_CODE           
 JOIN SECTIOND G (NOLOCK) ON B.SUB_SECTION_CODE = G.SUB_SECTION_CODE            
 JOIN SECTIONM H (NOLOCK) ON G.SECTION_CODE = H.SECTION_CODE           
 JOIN FORM I (NOLOCK) ON A.FORM_ID = I.FORM_ID           
 LEFT OUTER JOIN PRD_PMT PMT (NOLOCK) ON PMT.PRODUCT_UID=A.PRODUCT_UID     
 LEFT OUTER JOIN     
 (    
  SELECT A.MRR_NO,A.BILL_NO,B.PRODUCT_UID FROM PRD_PIM01106 A JOIN PRD_PID01106 B ON B.MRR_ID=A.MRR_ID    
 )X ON X.PRODUCT_UID=A.PRODUCT_UID     
 JOIN LMV01106 LM (NOLOCK) ON A.AC_CODE = LM.AC_CODE       
 WHERE A.PRODUCT_UID = @CPRODUCTCODE    
END                         
--****  END OF PROCEDURE SP_WL_PRODUCT_DETAIL
