CREATE PROCEDURE SP_PPC_DAILY_PRODUCTION_REPORT 
(
 @DFM_DT DATETIME='',
 @DTO_DT DATETIME=''
)
AS
BEGIN
     --SP_PPC_DAILY_PRODUCTION_REPORT '2017-03-14','2017-03-17'
     
     IF OBJECT_ID('TEMPDB..#TMPORDER','U') IS NOT NULL
        DROP TABLE #TMPORDER
     
     SELECT A.ORDER_ID,A.BILL_NO AS ORDER_NO ,A.ORDER_DT ,B.ROW_ID,
           CONVERT(NUMERIC(10,0), QUANTITY) AS QUANTITY,
            B.PARA1_CODE,B.ARTICLE_CODE,ART.ARTICLE_NO,P1.PARA1_NAME,
            PARA3_NAME   
     INTO #TMPORDER
     FROM PPC_BUYER_ORDER_MST A (NOLOCK)
     JOIN PPC_BUYER_ORDER_DET B (NOLOCK) ON A.ORDER_ID=B.ORDER_ID
     JOIN ARTICLE ART (NOLOCK) ON ART.ARTICLE_CODE=B.ARTICLE_CODE
	 JOIN PARA1 P1 (NOLOCK) ON P1.PARA1_CODE=B.PARA1_CODE
	 JOIN PARA3 P3  (NOLOCK) ON P3.PARA3_CODE =B.PARA3_CODE 
     WHERE A .CANCELLED =0 
   --  AND ORDER_DT BETWEEN '2017-03-14' AND '2017-03-17'
     AND ORDER_DT BETWEEN @DFM_DT AND @DTO_DT
     
      IF OBJECT_ID('TEMPDB..#TMPBARCODE','U') IS NOT NULL
        DROP TABLE #TMPBARCODE
        
     SELECT B.PRODUCT_CODE ,TMP.ROW_ID
     INTO #TMPBARCODE
     FROM #TMPORDER TMP
     JOIN PPC_FGBCG_DET A (NOLOCK) ON TMP.ROW_ID =A.BO_DET_ROW_ID 
     JOIN PPC_FG_SKU B ON A.ROW_ID =B.PPC_FGBCG_DET_ROW_ID
	 JOIN PPC_FGBCG_MST C ON C.MEMO_ID =A.MEMO_ID
	 WHERE C.CANCELLED=0
	 
	  IF OBJECT_ID('TEMPDB..#TMPISSUE','U') IS NOT NULL
        DROP TABLE #TMPISSUE
	 
	 SELECT JOBS.JOB_NAME AS ORG_JOB_NAME, 'ISSUE '+JOBS.JOB_NAME AS JOB_NAME,LM.AC_NAME AS AGENCY_NAME,
	 A.PRODUCT_CODE ,A.ROW_ID AS BO_ROW_ID ,B.ISSUE_ROW_ID ,B.ISSUE_QTY
	 INTO #TMPISSUE  
	 FROM #TMPBARCODE A
	 JOIN
	 (
	  SELECT B.AC_CODE ,B.JOB_CODE, PRODUCT_CODE ,QUANTITY AS ISSUE_QTY ,A.ROW_ID AS ISSUE_ROW_ID
	  FROM PPC_AGENCY_ISSUE_FG_FIRST_DET  A (NOLOCK)
	  JOIN PPC_AGENCY_ISSUE_FG_FIRST_MST  B (NOLOCK) ON A.MEMO_ID =B.MEMO_ID 
	  WHERE B.CANCELLED =0 AND ISNULL(B.MEMO_TYPE,0)=1
	  UNION ALL
	  SELECT B.AC_CODE ,B.JOB_CODE, PRODUCT_CODE ,QUANTITY AS ISSUE_QTY,A.ROW_ID AS ISSUE_ROW_ID
	  FROM PPC_AGENCY_ISSUE_FG_DET A (NOLOCK)
	  JOIN PPC_AGENCY_ISSUE_FG_MST B (NOLOCK) ON A.MEMO_ID =B.MEMO_ID 
	  WHERE B.CANCELLED =0 AND ISNULL(B.MEMO_TYPE,0)=1
	 ) B ON A.PRODUCT_CODE=B.PRODUCT_CODE 
	 JOIN JOBS (NOLOCK) ON JOBS.JOB_CODE =B.JOB_CODE 
	 JOIN LM01106 LM (NOLOCK) ON LM.AC_CODE =B.AC_CODE 
	 
	IF OBJECT_ID('TEMPDB..#TMPREC','U') IS NOT NULL
       DROP TABLE #TMPREC
        
	 SELECT A.ORG_JOB_NAME AS REC_JOB_NAME, A.BO_ROW_ID , 'REC '+A.ORG_JOB_NAME AS JOB_NAME,A.AGENCY_NAME,B.PRODUCT_CODE ,B.QUANTITY 
	 INTO #TMPREC
	 FROM #TMPISSUE A
	 JOIN PPC_AGENCY_REC_FG_DET B (NOLOCK) ON A.PRODUCT_CODE =B.PRODUCT_CODE AND A.ISSUE_ROW_ID =B.REF_ROW_ID 
	 JOIN PPC_AGENCY_REC_FG_MST C (NOLOCK) ON B.MEMO_ID=C.MEMO_ID
	 WHERE C.CANCELLED=0 AND  ISNULL(C.MEMO_TYPE,0)=1
	 
	 DECLARE @CISSUEJOB_NAME VARCHAR(MAX),
	 @CRECJOB_NAME VARCHAR(MAX),
	 @DTSQL NVARCHAR(MAX)
	 
	 
	 SELECT @CISSUEJOB_NAME= ISNULL(@CISSUEJOB_NAME+',','')+QUOTENAME(A.JOB_NAME)
	 +CASE WHEN ISNULL(B.JOB_NAME,'') ='' THEN '' ELSE 
	 ','+ISNULL(@CRECJOB_NAME+',','')+QUOTENAME(ISNULL(B.JOB_NAME,'')) END 
	 FROM #TMPISSUE A 
	 LEFT JOIN #TMPREC B ON A.ORG_JOB_NAME=B.REC_JOB_NAME 
	 WHERE A.JOB_NAME<>''
	 GROUP BY A.JOB_NAME,B.JOB_NAME
	 ORDER BY A.JOB_NAME ASC  
	 
	
	 --SELECT @CRECJOB_NAME= ISNULL(@CRECJOB_NAME+',','')+QUOTENAME(JOB_NAME)
	 --FROM #TMPREC WHERE JOB_NAME<>''
	 --GROUP BY JOB_NAME
	 --ORDER BY JOB_NAME ASC  
	 
	 
	 SET @CRECJOB_NAME=ISNULL(@CRECJOB_NAME,'')
      IF ISNULL(@CRECJOB_NAME,'')=''
      SET @CRECJOB_NAME='A'
	 
	 SET @CISSUEJOB_NAME=ISNULL(@CISSUEJOB_NAME,'')
	

	 	IF ISNULL(@CISSUEJOB_NAME,'')<>''
		BEGIN
			
			SET @DTSQL=N' SELECT ORDER_NO AS [BUYER ORDER NO],PARA3_NAME AS  [BUYER STYLE NO],
			REPLACE (CONVERT(VARCHAR, ORDER_DT, 106),'' '',''/'')  AS [ORDER DT], 
			AGENCY_NAME AS [AGENCY NAME],ARTICLE_NO AS [STYLE NO],PARA1_NAME AS [COLOR],ORDER_QTY AS [ORDER QTY], 
			'+@CISSUEJOB_NAME+'
			FROM 
			 (
				SELECT ORDER_ID, ORDER_NO, ORDER_DT ,ARTICLE_CODE  ,PARA1_CODE ,A.ARTICLE_NO,A.PARA1_NAME,
				A.PARA3_NAME,
				SUM(QUANTITY ) AS ORDER_QTY
				FROM #TMPORDER A
				GROUP BY  ORDER_ID, ORDER_NO,ORDER_DT,ARTICLE_CODE,PARA1_CODE,A.ARTICLE_NO,A.PARA1_NAME,A.PARA3_NAME
			  ) A	
			LEFT  JOIN
			 (
				SELECT A.ORDER_ID AS ISSUE_ORDER_ID, A.ORDER_DT AS ISSUE_ORDER_DT,A.ARTICLE_CODE AS ISSUE_ARTICLE_CODE,
				A.PARA1_CODE AS ISSUE_PARA1_CODE ,B.AGENCY_NAME,B.JOB_NAME,
			    SUM(B.ISSUE_QTY) AS ISSUE_QTY
				FROM #TMPORDER A
				JOIN #TMPISSUE B ON A.ROW_ID =B.BO_ROW_ID 
				GROUP BY A.ORDER_ID,A.ORDER_DT,A.ARTICLE_CODE,A.PARA1_CODE ,B.AGENCY_NAME,B.JOB_NAME 
			) B ON A.ORDER_ID=B.ISSUE_ORDER_ID AND A.ARTICLE_CODE=B.ISSUE_ARTICLE_CODE 
			AND A.PARA1_CODE=B.ISSUE_PARA1_CODE 
			LEFT  JOIN
			 (
				SELECT A.ORDER_ID AS REC_ORDER_ID, A.ORDER_DT AS REC_ORDER_DT,A.ARTICLE_CODE AS REC_ARTICLE_CODE,
				A.PARA1_CODE AS REC_PARA1_CODE ,B.AGENCY_NAME AS REC_AGENCY_NAME,B.JOB_NAME AS REC_JOB_NAME,
			    SUM(B.QUANTITY) AS REC_QTY
				FROM #TMPORDER A
				JOIN #TMPREC B ON A.ROW_ID =B.BO_ROW_ID 
				GROUP BY A.ORDER_ID,A.ORDER_DT,A.ARTICLE_CODE,A.PARA1_CODE ,B.AGENCY_NAME,B.JOB_NAME 
			) C ON A.ORDER_ID=C.REC_ORDER_ID AND A.ARTICLE_CODE=C.REC_ARTICLE_CODE 
			AND A.PARA1_CODE=C.REC_PARA1_CODE AND B.AGENCY_NAME=C.REC_AGENCY_NAME
			PIVOT (SUM(ISSUE_QTY) FOR JOB_NAME IN ('+@CISSUEJOB_NAME+')) AS PTABLE
			PIVOT (SUM(REC_QTY) FOR REC_JOB_NAME IN ('+@CRECJOB_NAME+')) AS PTABLE1'
			PRINT @DTSQL
			EXEC SP_EXECUTESQL @DTSQL
			 
			 
			
		END
		ELSE 
		BEGIN
			SELECT ORDER_NO AS [BUYER ORDER NO],PARA3_NAME AS  [BUYER STYLE NO], 
			REPLACE (CONVERT(VARCHAR, ORDER_DT, 106),' ','/')  AS [ORDER DT], 
			ARTICLE_NO AS [STYLE NO],PARA1_NAME AS [COLOR],
			SUM(QUANTITY)   AS [ORDER QTY] 
			FROM #TMPORDER 
			GROUP BY ORDER_NO , REPLACE (CONVERT(VARCHAR, ORDER_DT, 106),' ','/') , 
			ARTICLE_NO ,PARA1_NAME ,PARA3_NAME
		
		END
	 
	
     

END
