CREATE PROCEDURE SP3S_DELETE_WSL_MIRROR_TABLES
@cMemoId VARCHAR(50)
AS
BEGIN
	DECLARE @cMemoIdCopy VARCHAR(50)
   
	SET @cMemoIdCopy=@cMemoId+LEFT(@cMemoId,2)
	
	TRUNCATE TABLE #t

	INSERT #T
	SELECT inv_id  
	FROM WSL_INM01106_MIRROR B (NOLOCK) WHERE inv_id=@cMemoId OR inv_id=@cMemoIdCopy

    IF EXISTS (SELECT TOP 1 'U' FROM #T)
	BEGIN
		DELETE A FROM WSL_INM01106_MIRROR A  JOIN #T B ON  A.inv_ID=B.inv_ID
	
		DELETE A FROM WSL_IND01106_MIRROR A JOIN #T B ON  A.inv_ID=B.inv_ID
		DELETE A FROM WSL_PAYMODE_XN_DET_MIRROR A WITH (ROWLOCK) JOIN #T B ON  A.memo_ID=B.inv_ID
	
		DELETE A FROM WSL_ANGM_MIRROR A JOIN #T B ON  A.wsl_memo_ID=B.inv_ID
		DELETE A FROM WSL_PARCEL_MST_MIRROR A  JOIN #T B ON  A.wsl_memo_ID=B.inv_ID
		DELETE A FROM WSL_PARCEL_DET_MIRROR A  JOIN #T B ON  A.wsl_memo_ID=B.inv_ID
		DELETE A FROM WSL_PMT01106_MIRROR A  JOIN #T B ON  A.wsl_memo_ID=B.inv_ID
	END
END