CREATE PRocEDURe SP_WSLINV_24--(LocId 3 digit change only increased the parameter width by Sanjay:04-11-2024)
	@CMEMOID	VARCHAR(40) = '',
	@CWHERE1	VARCHAR(500) = '',
	@NNAVMODE	NUMERIC(2,0) = 0,
	@CWHERE2	NVARCHAR(MAX)='',
	@DMEMODT DATETIME='',
	@CLOCID		VARCHAR(4)=''
----WITH ENCRYPTION
AS
BEGIN
	SELECT A.*
		  ,A.CITY AS CITY_NAME
		  ,A.STATE AS STATE_NAME
		  ,A.CITY+','+A.STATE+','+A.PIN AS LOCATION
		  ,A.ADDRESS1+','+A.ADDRESS2+','+A.ADDRESS3 AS [ADDRESS]	 
		  ,B.AC_NAME AS SHIPPING_AC_NAME
		  ,B.Ac_gst_no AS SHIPPING_GST_NO
	FROM LM_SHIPPING_DETAILS A	(NOLOCK)
	JOIN LMV01106 B (NOLOCK) ON B.AC_CODE=A.shipping_ac_code
	WHERE ISNULL(A.shipping_ac_code,'')<>'' AND ISNULL(A.shipping_ac_code,'0000000000')<>'0000000000' 
	AND  (A.AC_CODE=@CWHERE1 OR @NNAVMODE=99)--@CMEMOID
END