CREATE PROCEDURE SP3S_SEARCH_PRODUCT_CODE_FROM_ITEM_STATUS
(
	@cWhere VARCHAR(100)='%'
)
AS
BEGIN
	DECLARE @cCMD NVARCHAR(MAX)
	SET @cCMD='SELECT TOP 50 CMD.PRODUCT_CODE FROM CMD01106 CMD(NOLOCK) 
	JOIN ITEM_STATUS  M (NOLOCK) ON CMD.ROW_ID =M.REF_CMD_ROW_ID 
	WHERE ISNULL(M.REF_CMD_ROW_ID  ,'''')<>''''
	AND cmd.PRODUCT_CODE like '''+@cWhere+'''
	GROUP  BY CMD.PRODUCT_CODE 
	ORDER BY CMD.PRODUCT_CODE '

	PRINT @cCMD
	EXEC SP_EXECUTESQL @cCMD
END
