create PROCEDURE SP3S_UPDATE_FIX_BARCODE
AS
BEGIN
      
      DECLARE @CERRORMSG VARCHAR(MAX),@BATCH_WISE_BARCODE VARCHAR(10)
      SET @CERRORMSG=''
	
	BEGIN TRANSACTION
	BEGIN TRY
	
	
		UPDATE A SET ARTICLE_CODE =B.ARTICLE_CODE ,
		PARA1_CODE =B.PARA1_CODE ,PARA2_CODE =B.PARA2_CODE   
		FROM SKU A (NOLOCK)
		JOIN
		(

			SELECT A.PRODUCT_CODE ,A.ARTICLE_CODE,A.PARA1_CODE,A.PARA2_CODE
			FROM SKU  A (NOLOCK)
			WHERE 
			--BARCODE_CODING_SCHEME =1 AND
			 CHARINDEX ('@',PRODUCT_CODE)=0
		) B ON SUBSTRING (A.PRODUCT_CODE,1,CHARINDEX('@',A.PRODUCT_CODE)-1)=B.PRODUCT_CODE 
		join article art on art.article_code =a.article_code 
		WHERE CHARINDEX('@',A.PRODUCT_CODE)<>0
		AND (A.ARTICLE_CODE <>B.ARTICLE_CODE OR A.PARA1_CODE <>B.PARA1_CODE or A.PARA2_CODE <>B.PARA2_CODE )
		and isnull( art.PERISHABLE ,0)=0
 
   END TRY
	BEGIN CATCH
		SET @CERRORMSG = 'PROCEDURE SP3S_UPDATE_FIX_BARCODE: STEP-  SQL ERROR: #' + LTRIM(STR(ERROR_NUMBER())) + ' ' + ERROR_MESSAGE()
		GOTO END_PROC
	END CATCH
END_PROC:
	IF @@TRANCOUNT>0 
	BEGIN
	
		IF ISNULL(@CERRORMSG,'')='' 
		BEGIN
			COMMIT TRANSACTION
		END	
		ELSE
			ROLLBACK
	END
	

END
