CREATE PROCEDURE SP_STOCKSTATUSREPORT    
(    
  @CWORK_ORDER_ID VARCHAR(MAX)=''    
 ,@DFROMDT VARCHAR(12)    
 ,@DTODT VARCHAR(12)    
 ,@CDEPTNAME VARCHAR(100)=''    
 ,@NQUERYID NUMERIC(2,0)=1    
)
--WITH ENCRYPTION
    
AS    
BEGIN    
 DECLARE @CCMD NVARCHAR(MAX)    
    
IF @NQUERYID=1    
 GOTO LBLGETSTOCKREPORT    
IF @NQUERYID=2    
 GOTO LBLGETDETAILSTOCK     
    
LBLGETSTOCKREPORT:    
 SET @CCMD=N'SELECT     
    PWM.MEMO_NO AS WO_NO,PWM.REF_NO,    
    VW.DEPARTMENT,VW.ARTICLE_NO,P1.PARA1_NAME,P2.PARA2_NAME,VW.UOM_NAME    
    --,ART.ARTICLE_NO AS COMPONENT_NAME,CP1.PARA1_NAME AS COM_PARA1_NAME,CP2.PARA2_NAME AS COM_PARA2_NAME    
    ,PS.PURCHASE_PRICE AS XN_PP,PS.PURCHASE_PRICE    
       ,SUM((CASE WHEN XN_TYPE IN (''PUR'',''UNC'',''WSR'',''IMR'',''IMO'',''AMR'',''STRIN'',''RMR'',''OPF'',''AMI'',''OPW'',''FINC'') AND XN_DT<='''+@DTODT+''' THEN 1    
     WHEN XN_TYPE IN (''PRT'',''CNC'',''WSL'',''IMI'',''STROUT'',''OPC'',''OP'',''AMO'',''FINR'',''DTM'') AND XN_DT<='''+@DTODT+''' THEN -1 ELSE 0 END)*XN_QTY) AS STOCK_QTY    
    ,SUM((CASE WHEN XN_TYPE IN (''PUR'',''UNC'',''WSR'',''IMR'',''IMO'',''AMR'',''STRIN'',''RMR'',''OPF'',''AMI'',''OPW'',''FINC'') AND XN_DT<='''+@DTODT+''' THEN 1    
     WHEN XN_TYPE IN (''PRT'',''CNC'',''WSL'',''IMI'',''STROUT'',''OPC'',''OP'',''AMO'',''FINR'',''DTM'') AND XN_DT<='''+@DTODT+''' THEN -1 ELSE 0 END)*(XN_QTY*PS.PURCHASE_PRICE)) AS STOCK_VALUE       
    ,SUM((CASE WHEN XN_TYPE IN (''PUR'',''UNC'',''WSR'',''IMR'',''IMO'',''AMR'',''STRIN'',''RMR'',''OPF'',''AMI'',''OPW'',''FINC'') AND XN_DT<='''+@DTODT+''' THEN 1    
     WHEN XN_TYPE IN (''PRT'',''CNC'',''WSL'',''IMI'',''STROUT'',''OPC'',''OP'',''AMO'',''FINR'',''DTM'') AND XN_DT<='''+@DTODT+''' THEN -1 ELSE 0 END)*WIP_QTY) AS WIP_QTY    
    ,SUM((CASE WHEN XN_TYPE IN (''PUR'',''UNC'',''WSR'',''IMR'',''IMO'',''AMR'',''STRIN'',''RMR'',''OPF'',''AMI'',''OPW'',''FINC'') AND XN_DT<='''+@DTODT+''' THEN 1    
     WHEN XN_TYPE IN (''PRT'',''CNC'',''WSL'',''IMI'',''STROUT'',''OPC'',''OP'',''AMO'',''FINR'',''DTM'') AND XN_DT<='''+@DTODT+''' THEN -1 ELSE 0 END)*(WIP_QTY*PS.PURCHASE_PRICE)) AS WIP_VALUE       
 FROM VW_STOCKSTATUS_REPORT VW    
 JOIN PRD_SKU PS ON VW.PRODUCT_UID=PS.PRODUCT_UID    
 LEFT JOIN PRD_WO_MST PWM ON VW.WORK_ORDER_ID=PWM.MEMO_ID    
 JOIN PARA1 P1 ON VW.PARA1_CODE=P1.PARA1_CODE    
 JOIN PARA2 P2 ON VW.PARA2_CODE=P2.PARA2_CODE    
 LEFT JOIN PARA1 CP1 ON PS.COM_PARA1_CODE=CP1.PARA1_CODE    
 LEFT JOIN PARA2 CP2 ON PS.COM_PARA2_CODE=CP2.PARA2_CODE    
 LEFT JOIN ARTICLE ART ON PS.COMPONENT_CODE=ART.ARTICLE_CODE    
 WHERE 1=1 '+(CASE WHEN ISNULL(@CDEPTNAME,'')='' THEN '' ELSE ' AND VW.DEPARTMENT='''+@CDEPTNAME+'''' END)    
 +(CASE WHEN ISNULL(@CWORK_ORDER_ID,'')='' THEN '' ELSE ' AND VW.WORK_ORDER_ID='''+@CWORK_ORDER_ID+'''' END)    
 +'GROUP  BY PWM.MEMO_NO,PWM.REF_NO,    
 VW.DEPARTMENT,VW.ARTICLE_NO,P1.PARA1_NAME,P2.PARA2_NAME--,VW.XN_PP    
 ,VW.UOM_NAME,PS.PURCHASE_PRICE    
 --,ART.ARTICLE_NO,CP1.PARA1_NAME,CP2.PARA2_NAME    
 HAVING (SUM((CASE WHEN XN_TYPE IN (''PUR'',''UNC'',''WSR'',''IMR'',''IMO'',''AMR'',''STRIN'',''RMR'',''OPF'',''AMI'',''OPW'',''FINC'') AND XN_DT<='''+@DTODT+''' THEN 1    
     WHEN XN_TYPE IN (''PRT'',''CNC'',''WSL'',''IMI'',''STROUT'',''OPC'',''OP'',''AMO'',''FINR'',''DTM'') AND XN_DT<='''+@DTODT+''' THEN -1 ELSE 0 END)*XN_QTY)<>0    
  OR  SUM((CASE WHEN XN_TYPE IN (''PUR'',''UNC'',''WSR'',''IMR'',''IMO'',''AMR'',''STRIN'',''RMR'',''OPF'',''AMI'',''OPW'',''FINC'') AND XN_DT<='''+@DTODT+''' THEN 1    
     WHEN XN_TYPE IN (''PRT'',''CNC'',''WSL'',''IMI'',''STROUT'',''OPC'',''OP'',''AMO'',''FINR'',''DTM'') AND XN_DT<='''+@DTODT+''' THEN -1 ELSE 0 END)*WIP_QTY)<>0)    
     '     
 PRINT @CCMD    
GOTO LBLEND    
    
LBLGETDETAILSTOCK:    
SET @CCMD=N'SELECT   
--PWM.MEMO_NO AS WO_NO,PWM.REF_NO,  
VW.DEPARTMENT,VW.ARTICLE_NO,P1.PARA1_NAME,P2.PARA2_NAME,VW.UOM_NAME    
    ,ART.ARTICLE_NO AS COMPONENT_NAME,CP1.PARA1_NAME AS COM_PARA1_NAME,CP2.PARA2_NAME AS COM_PARA2_NAME    
    ,VW.XN_PP,PS.PURCHASE_PRICE    
       ,VW.XN_NO,VW.XN_DT,VW.XN_TYPE    
       ,SUM(VW.XN_QTY) AS STOCK_QTY    
    ,SUM(WIP_QTY) AS WIP_QTY    
 FROM VW_STOCKSTATUS_REPORT VW    
 JOIN PRD_SKU PS ON VW.PRODUCT_UID=PS.PRODUCT_UID    
 LEFT JOIN PRD_WO_MST PWM ON VW.WORK_ORDER_ID=PWM.MEMO_ID    
 JOIN PARA1 P1 ON VW.PARA1_CODE=P1.PARA1_CODE    
 JOIN PARA2 P2 ON VW.PARA2_CODE=P2.PARA2_CODE    
 LEFT JOIN PARA1 CP1 ON PS.COM_PARA1_CODE=CP1.PARA1_CODE    
 LEFT JOIN PARA2 CP2 ON PS.COM_PARA2_CODE=CP2.PARA2_CODE    
 LEFT JOIN ARTICLE ART ON PS.COMPONENT_CODE=ART.ARTICLE_CODE    
 WHERE VW.XN_DT BETWEEN '''+ @DFROMDT +''' AND '''+@DTODT+''''+(CASE WHEN ISNULL(@CDEPTNAME,'')='' THEN '' ELSE ' AND VW.DEPARTMENT='''+@CDEPTNAME+'''' END)    
 +(CASE WHEN ISNULL(@CWORK_ORDER_ID,'')='' THEN '' ELSE ' AND VW.WORK_ORDER_ID='''+@CWORK_ORDER_ID+'''' END)    
 +'GROUP  BY   
 --PWM.MEMO_NO,PWM.REF_NO,  
 VW.DEPARTMENT,VW.ARTICLE_NO,P1.PARA1_NAME,P2.PARA2_NAME,VW.XN_PP,VW.UOM_NAME,PS.PURCHASE_PRICE    
 ,ART.ARTICLE_NO,CP1.PARA1_NAME,CP2.PARA2_NAME,PS.COM_PARA2_CODE,VW.XN_NO,VW.XN_DT,VW.XN_TYPE'     
 PRINT @CCMD    
     
GOTO LBLEND     
    
LBLEND:    
EXEC SP_EXECUTESQL @CCMD    
END
