create PROCEDURE SAVETRAN_GETMEMOPREFIX
@CXNTYPE VARCHAR(20),
@CUSERCODE CHAR(7),
@CFINYEAR VARCHAR(5),
@CSOURCELOCID VARCHAR(10),
@CTARGETLOCID VARCHAR(10)='',
@CMANUALPREFIX VARCHAR(25),
@NSPID varchar(40)='',
@CMEMOID VARCHAR(50)='',
@CMEMOPREFIX VARCHAR(25) OUTPUT,
@CERRORMSG VARCHAR(MAX) OUTPUT
AS
BEGIN
	DECLARE @NSETUPMODE INT,@BPREFIXAPPLICABLE BIT,@BPREFIXUSERALIAS BIT,@CCMD NVARCHAR(MAX),
			@BPREFIXDESTLOCID BIT,@BPREFIXFINYEAR BIT,@CIGSTXNPREFIX VARCHAR(25),
			@CCGSTXNPREFIX VARCHAR(25),@CDELIVERYCHALLANPREFIX VARCHAR(25),@CUSERALIAS VARCHAR(2),
			@CFINYEARSTRING VARCHAR(5),@CSTEP VARCHAR(5),@NSERIESMODE NUMERIC(1,0),@CSOURCETABLE VARCHAR(200),
			@CXNTYPESEARCH VARCHAR(20),@CCURLOCID CHAR(4),@CXNTYPEPARA VARCHAR(20),
			@CPARTYGSTNO VARCHAR(50),@CPARTYSTATECODE VARCHAR(10),@NPARTYREGISTERED NUMERIC(1,0),
			@NGSTMODE INT,@CTABLENAME VARCHAR(300),@CKEYSTABLE VARCHAR(300),@CCOLUMNNAME VARCHAR(300),@cForcedPrefix VARCHAR(5),
			@xn_item_type INT,@nLocType NUMERIC(1,0),@cHoLocId VARCHAR(5),@nBillChallanMode NUMERIC(1,0),@nDnType NUMERIC(1,0)
			
			
			
BEGIN TRY			
	SET @CSTEP='10'
	SET @CERRORMSG=''
	SET @cForcedPrefix=''

	
    
	
		SET @CCURLOCID=@CSOURCELOCID

	

	IF ISNULL(@CCURLOCID,'')=''
	 BEGIN
		SET @CERRORMSG ='2. chk LOCATION ID CAN NOT BE BLANK  ' + STR(@@SPID)
		GOTO END_PROC    
	 END
		--select @CXNTYPESEARCH
	SET @CSOURCETABLE=(CASE WHEN @CXNTYPE='PO' THEN 'PO_PoM01106_UPLOAD' WHEN @CXNTYPE='PUR' THEN 'PUR_PIM01106_UPLOAD' WHEN LEFT(@CXNTYPE,3) in('PRT','FDN') THEN 'PRT_RMM01106_UPLOAD' 
							WHEN LEFT(@CXNTYPE,3)='WSL' THEN 'WSL_INM01106_UPLOAD' WHEN @CXNTYPE IN ('WSR','FCN')
							THEN 'WSR_CNM01106_UPLOAD' WHEN @CXNTYPE='GRP_PUR' THEN 'DOCWSL_INM01106_MIRROR'
							WHEN @CXNTYPE='QC' THEN 'QC_QC_XN_MST_UPLOAD'
							WHEN @CXNTYPE='ASN' THEN 'ASN_ASN_MST_UPLOAD'
							WHEN @CXNTYPE='JOB_CARD' THEN 'PFI_ORD_PLAN_MST_UPLOAD'
							ELSE 'DOCPRT_RMM01106_MIRROR' END)
	
	IF @CXNTYPE NOT IN ('GRP_PUR','GRP_WSR')
	BEGIN
		SET @CSTEP='15'
		SET @CMANUALPREFIX=''
		
		SET @CCMD=N'SELECT @CMANUALPREFIX=MEMO_PREFIX FROM '+@CSOURCETABLE+' WHERE SP_ID='''+LTRIM(RTRIM((@NSPID)))+''' '
	
		PRINT @CCMD		
		EXEC SP_EXECUTESQL @CCMD,N'@CMANUALPREFIX VARCHAR(25) OUTPUT',@CMANUALPREFIX OUTPUT
		
	END

	SET @xn_item_type=0

	IF LEFT(@CXNTYPE,3) in('PRT','FDN')
	BEGIN
		SELECT @nDntype=dn_type,@nBillChallanmode=bill_challan_mode FROM PRT_rmm01106_UPLOAD (NOLOCK)
		WHERE sp_id=@nSpId

		IF @nDnType=2 OR @nBillChallanMode=1
			SET @cForcedPrefix=(CASE WHEN @nDnType=2 THEN 'F' ELSE 'C' END)
	END

	IF @CXNTYPE IN ('PUR','WSL')
	BEGIN
		SET @CSTEP='18'
		SET @CCMD=N'SELECT @CSOURCELOCID=DEPT_ID FROM '+@CSOURCETABLE+' WHERE SP_ID='''+LTRIM(RTRIM((@NSPID)))+''''
		EXEC SP_EXECUTESQL @CCMD,N'@CSOURCELOCID VARCHAR(10) OUTPUT',@CSOURCELOCID OUTPUT
	END					

	IF @CXNTYPE IN ('PUR','WSL','WSR','PRT','FDN','PO','FCN','wsl_grp')
	BEGIN
		SET @CSTEP='20'
		SET @CCMD=N'SELECT @xn_item_type=xn_item_type FROM '+@CSOURCETABLE+' WHERE SP_ID='''+LTRIM(RTRIM((@NSPID)))+''''
		EXEC SP_EXECUTESQL @CCMD,N'@xn_item_type INT OUTPUT',@xn_item_type OUTPUT
	END

	SET @CSTEP='22'		
	SET @CXNTYPESEARCH=(CASE WHEN @CXNTYPE='GRP_PUR' THEN 'PUR_GRP' WHEN @CXNTYPE='GRP_WSR' THEN 'WSR_GRP' ELSE @CXNTYPE END)

	IF @CXNTYPESEARCH IN ('PRT_GRP','WSL_GRP')
	BEGIN
		SET @CSTEP='25'
		SET @cCmd=N'SELECT @nLocType=loc_type FROM '+@CSOURCETABLE+' A
					JOIN LOCATION C ON A.PARTY_DEPT_ID=C.DEPT_ID
					WHERE SP_ID='''+LTRIM(RTRIM((@NSPID)))+''''
					
		EXEC SP_EXECUTESQL @CCMD,N'@nLocType NUMERIC(1,0) OUTPUT',@nLocType OUTPUT						
	END
	ELSE
	IF @CXNTYPESEARCH IN ('PUR_GRP')
	BEGIN
		SET @CSTEP='27'
		SET @cCmd=N'SELECT @nLocType=loc_type FROM '+@CSOURCETABLE+' A
					JOIN LOCATION C ON A.LOCATION_CODE=C.DEPT_ID
					WHERE a.inv_id='''+@CMEMOID+''''
					
		EXEC SP_EXECUTESQL @CCMD,N'@nLocType NUMERIC(1,0) OUTPUT',@nLocType OUTPUT						
	END
	ELSE
	IF @CXNTYPESEARCH IN ('WSR_GRP')
	BEGIN
		SET @CSTEP='30'
		SET @cCmd=N'SELECT @nLocType=loc_type FROM '+@CSOURCETABLE+' A
					JOIN LOCATION C ON A.LOCATION_CODE=C.DEPT_ID
					WHERE a.rm_id='''+@CMEMOID+''''
					
		EXEC SP_EXECUTESQL @CCMD,N'@nLocType NUMERIC(1,0) OUTPUT',@nLocType OUTPUT						
	END
	
	SET @CSTEP='35'		
	IF RIGHT(@CXNTYPESEARCH,4)='_GRP'
	BEGIN
		SET @CXNTYPESEARCH=@CXNTYPESEARCH+(CASE WHEN @nLocType=2 THEN '_FR' ELSE '' END)
	END
	
	SET @CSTEP='40'						
	IF NOT EXISTS (SELECT TOP 1 * FROM SERIES_SETUP_MST WHERE XN_TYPE=@CXNTYPESEARCH AND DEPT_ID=@CSOURCELOCID
	AND (xn_item_type=@xn_item_type OR (ISNULL(@xn_item_type,0)=0 AND xn_item_type=1)))
	BEGIN
		DECLARE @bDOnotValidate BIT,@cPurDeptid VARCHAR(5)
		set @bDOnotValidate=0

		IF @CXNTYPESEARCH='PUR' 
		BEGIN
			IF @CCURLOCID<>@CSOURCELOCID
				SET @bDOnotValidate=1
		END

		IF @bDOnotValidate=0
		BEGIN
			SET @CERRORMSG='NO SERIES SETUP FOUND FOR XN TYPE :'+@CXNTYPESEARCH+' AND LOC ID:'+@CSOURCELOCID
			GOTO END_PROC
		END
	END	
	ELSE
	BEGIN
		SELECT @NSERIESMODE=SERIES_SETUP_MODE FROM SERIES_SETUP_MST WHERE XN_TYPE=@CXNTYPESEARCH AND DEPT_ID=@CSOURCELOCID
		AND (xn_item_type=@xn_item_type OR (ISNULL(@xn_item_type,0)=0 AND xn_item_type=1))
		
		IF @NSERIESMODE=1 AND ISNULL(@CMANUALPREFIX,'')='' and isnull(@xn_item_type,0)<>5
		BEGIN
			SET @CERRORMSG='MANUAL PREFIX NOT SELECTED BY USER ......PLEASE CHECK'
			GOTO END_PROC		
		END

	END
	SET @CSTEP='45'
	SELECT @NSETUPMODE=SERIES_SETUP_MODE FROM SERIES_SETUP_MST WHERE XN_TYPE=@CXNTYPESEARCH AND DEPT_ID=@CSOURCELOCID
	AND (xn_item_type=@xn_item_type OR (ISNULL(@xn_item_type,0)=0 AND xn_item_type=1))
	
	
	SELECT @CXNTYPEPARA=(CASE WHEN @CXNTYPESEARCH LIKE '%PUR%' THEN 'PUR' WHEN @CXNTYPE LIKE '%WSR%' 
							  THEN 'WSR' WHEN @CXNTYPE LIKE '%WSL%' THEN 'WSL'
							  WHEN @CXNTYPE LIKE '%PRT%' THEN 'PRT'  ELSE @CXNTYPE END)

	IF @CXNTYPE IN ('PRT','WSL','FDN','FCN')
	BEGIN
		SET @CSTEP='50'
		SET @CCMD=N'SELECT @CPARTYSTATECODE=(CASE WHEN ISNULL(PARTY_DEPT_ID,'''')<>'''' THEN C.GST_STATE_CODE
					ELSE B.AC_GST_STATE_CODE END),
					@CPARTYGSTNO=(CASE WHEN ISNULL(PARTY_DEPT_ID,'''')<>'''' THEN C.LOC_GST_NO
					ELSE B.AC_GST_NO END),@NPARTYREGISTERED=(CASE WHEN ISNULL(PARTY_DEPT_ID,'''')<>'''' 
					THEN ISNULL(C.REGISTERED_GST,0) ELSE ISNULL(B.REGISTERED_GST_DEALER,0) END)
					FROM '+@CSOURCETABLE+' A
					LEFT OUTER JOIN LMP01106 B ON A.AC_CODE=B.AC_CODE
					LEFT OUTER JOIN LOCATION C ON A.PARTY_DEPT_ID=C.DEPT_ID
					WHERE SP_ID='''+LTRIM(RTRIM((@NSPID)))+''''

	END				
	ELSE
	IF @CXNTYPE IN ('GRP_PUR','GRP_WSR')
	BEGIN
		SET @CSTEP='52'
		SET @CCMD=N'SELECT @CPARTYSTATECODE=B.GST_STATE_CODE,@CPARTYGSTNO=B.LOC_GST_NO,
					@NPARTYREGISTERED=ISNULL(B.REGISTERED_GST,0)
					FROM '+@CSOURCETABLE+' A 
					JOIN LOCATION B ON LEFT(A.'+(CASE WHEN @CXNTYPE='GRP_PUR' THEN 'INV_ID' ELSE 'RM_ID' END)
					+',2)=B.DEPT_ID WHERE '+(CASE WHEN @CXNTYPE='GRP_PUR' THEN 'INV_ID' ELSE 'RM_ID' END)+'='''+@CMEMOID+''''
									
	END				
	ELSE
	BEGIN
		SET @CSTEP='55'
		SET @CCMD=N'SELECT @CPARTYSTATECODE=B.AC_GST_STATE_CODE,@CPARTYGSTNO=B.AC_GST_NO,
					@NPARTYREGISTERED=ISNULL(B.REGISTERED_GST_DEALER,0) FROM '+@CSOURCETABLE+' A
					JOIN LMP01106 B ON A.AC_CODE=B.AC_CODE
					WHERE SP_ID='''+LTRIM(RTRIM((@NSPID)))+''' '

	END	
		
	EXEC SP_EXECUTESQL @CCMD,N'@CPARTYGSTNO VARCHAR(50) OUTPUT,@NPARTYREGISTERED INT OUTPUT,@CPARTYSTATECODE VARCHAR(5) OUTPUT',
	@CPARTYGSTNO OUTPUT,@NPARTYREGISTERED OUTPUT,@CPARTYSTATECODE OUTPUT
	
	IF @NSETUPMODE=1 ---- MANUAL SERIES
	BEGIN
		SET @CSTEP='60'
		SET @CMEMOPREFIX=@CSOURCELOCID+@cForcedPrefix+@CMANUALPREFIX
		GOTO LBLFINAL 
	END
	ELSE 
	BEGIN  ---- AUTO SERIES
		
			
		
		DECLARE @TGSTTYPE TABLE (GST_TYPE NUMERIC(1,0))
		
		SET @CSTEP='70'
		
		IF @CXNTYPE='PO'
			SET @NGSTMODE=0
		ELSE
		BEGIN
			INSERT @TGSTTYPE
			EXEC SP3S_GST_IDENTIFY
			@CXN_TYPE=@CXNTYPEPARA,
			@CPARTY_STATE_CODE=@CPARTYSTATECODE,
			@CPARTY_GST_NO=@CPARTYGSTNO,
			@CSOURCE_DEPT_ID=@CSOURCELOCID,
			@NPARTY_REGISTERED=@NPARTYREGISTERED
  		
  			SET @CSTEP='75'
  			SELECT TOP 1 @NGSTMODE=GST_TYPE FROM  @TGSTTYPE
		END  		
		
		SELECT @BPREFIXAPPLICABLE=PREFIX_APPLICABLE,@BPREFIXUSERALIAS=PREFIX_USER_ALIAS,
			   @BPREFIXDESTLOCID=PREFIX_DESTINATION_LOCID,
			   @BPREFIXFINYEAR=PREFIX_FINYEAR,@CIGSTXNPREFIX=IGST_XN_PREFIX,@CCGSTXNPREFIX=CGST_XN_PREFIX,
			   @CDELIVERYCHALLANPREFIX=DELIVERY_CHALLAN_PREFIX
			   FROM SERIES_SETUP_MST WHERE XN_TYPE=@CXNTYPESEARCH AND DEPT_ID=@CSOURCELOCID
			   AND (xn_item_type=@xn_item_type OR (ISNULL(@xn_item_type,0)=0 AND xn_item_type=1))
		
		IF @BPREFIXAPPLICABLE=0 
		BEGIN
			SET @CSTEP='80'
			SET @CMEMOPREFIX=@CSOURCELOCID+@cForcedPrefix 
			GOTO LBLFINAL
		END
		ELSE
		BEGIN
			SET @CSTEP='85'
			SELECT TOP 1 @CUSERALIAS=USER_ALIAS FROM USERS WHERE USER_CODE=@CUSERCODE
			
			SET @CMEMOPREFIX=@CSOURCELOCID+@cForcedPrefix
			
			SET @CSTEP='90'
			SET @CMEMOPREFIX=@CMEMOPREFIX+(CASE WHEN @BPREFIXDESTLOCID=1 AND @CTARGETLOCID<>'' THEN @CTARGETLOCID ELSE '' END)
			
			SET @CMEMOPREFIX=@CMEMOPREFIX+(CASE WHEN @BPREFIXUSERALIAS=1 THEN '/'+@CUSERALIAS ELSE '' END)
						
			IF @BPREFIXFINYEAR=1
			BEGIN
				SET @CSTEP='95'

				--As Per Sanjiv Sir  for octave Appearls - 24-25 when click on Series Setup  with fin year Pankaj  
				--SELECT @CFINYEARSTRING=LTRIM(RTRIM(STR(DATEPART(YY,DBO.FN_GETFINYEARDATE(@CFINYEAR,1))-2000)))				
				--SELECT @CFINYEARSTRING=@CFINYEARSTRING+'-'+LTRIM(RTRIM(STR(DATEPART(YY,DBO.FN_GETFINYEARDATE(@CFINYEAR,2))-2000)))
				SELECT @CFINYEARSTRING= LTRIM(RTRIM(STR(DATEPART(YY,DBO.FN_GETFINYEARDATE(@CFINYEAR,2))-2000)))
				
			
				SET @CMEMOPREFIX=@CMEMOPREFIX+'/'+@CFINYEARSTRING
			END
			
			SET @CSTEP='100'
			
			--SELECT @NGSTMODE,@nLocType,@CXNTYPE,@CPARTYGSTNO as CPARTYGSTNO
			
			SET @CMEMOPREFIX=@CMEMOPREFIX+(CASE WHEN @NGSTMODE=1 AND @CCGSTXNPREFIX<>'' THEN '/'+@CCGSTXNPREFIX ELSE '' END)+
			(CASE WHEN @NGSTMODE=2 AND @CIGSTXNPREFIX<>'' THEN '/'+@CIGSTXNPREFIX ELSE '' END)+
			(CASE WHEN @NGSTMODE=3 AND @CDELIVERYCHALLANPREFIX<>''  THEN '/'+@CDELIVERYCHALLANPREFIX ELSE '' END)
			
			
			GOTO LBLFINAL
		END
	END	


LBLFINAL:
	--SELECT @CSTEP AS LAST_STEP		
	SET @CSTEP='105'

	--if @@spid=442
	--	select @cSourceLocId sourcelocid, @bEnableEInvoice,@cPartygstNo,@cFinYear,@CMEMOPREFIX

	DECLARE @cOutputMemoPrefix VARCHAR(25)

	EXEC SP3S_GETENINVOICE_MEMOPREFIX
	@cXnType=@cXnType,
	@cPartyGstNo=@cPartyGstNo,
	@cSourceLocId=@cSourceLocId,
	@cFinyear=@cFinyear,
	@cInputMemoPrefix=@cMemoPrefix,
	@cErrormsg=@cErrormsg OUTPUT,
	@cOutputMemoPrefix=@cOutputMemoPrefix OUTPUT
	
	IF ISNULL(@cErrormsg,'')<>''
		GOTO END_PROC

	SET @CMEMOPREFIX=@cOutputMemoPrefix+(CASE WHEN RIGHT(@cOutputMemoPrefix,1)<>'-' THEN '-' ELSE '' END)

	--if @@spid=442
	--	select 'after assignment', @bEnableEInvoice,@cPartygstNo,@cFinYear,@CMEMOPREFIX	
	
	--FOR ESTIMATE BILL 
	IF @CXNTYPE IN('PUR','PRT','WSL','WSR','WPS','PRT_GRP','WSL_GRP','GRP_PUR','GRP_WSR')
	BEGIN
	    
	    DECLARE @CUPLOADTABLENAME VARCHAR(100),@NMEMOTYPE INT,
		@NPREFIX_XN_ITEM_TYPE INT
	    
	    SET @CUPLOADTABLENAME =	 ( CASE WHEN  @CXNTYPESEARCH LIKE '%PUR%' THEN 'PUR_PIM01106_UPLOAD' 	
									 WHEN @CXNTYPESEARCH LIKE '%PRT%' THEN 'PRT_RMM01106_UPLOAD'
									 WHEN @CXNTYPESEARCH LIKE '%FDN%' THEN 'PRT_RMM01106_UPLOAD'
									 WHEN @CXNTYPESEARCH LIKE '%WSL%' THEN 'WSL_INM01106_UPLOAD'
									 WHEN @CXNTYPESEARCH LIKE '%WSR%' THEN 'WSR_CNM01106_UPLOAD' 
									 WHEN @CXNTYPESEARCH LIKE '%WPS%' THEN 'WPS_WPS_MST_UPLOAD' 
								END)
	    SET @CCMD=N' SELECT @NMEMOTYPE=MEMO_TYPE FROM '+@CUPLOADTABLENAME+' WHERE SP_ID='''+LTRIM(RTRIM((@NSPID)))+''' '
	    PRINT @CCMD		
		EXEC SP_EXECUTESQL @CCMD,N'@NMEMOTYPE INT OUTPUT',@NMEMOTYPE OUTPUT
		
		IF @CUPLOADTABLENAME NOT IN('WPS_WPS_MST_UPLOAD')
		BEGIN
		
			SET @CCMD=N' SELECT @NPREFIX_XN_ITEM_TYPE=XN_ITEM_TYPE FROM '+@CUPLOADTABLENAME+' WHERE SP_ID='''+LTRIM(RTRIM((@NSPID)))+''' '
			PRINT @CCMD		
			EXEC SP_EXECUTESQL @CCMD,N'@NPREFIX_XN_ITEM_TYPE INT OUTPUT',@NPREFIX_XN_ITEM_TYPE OUTPUT

			IF @NSETUPMODE<>1 AND @NPREFIX_XN_ITEM_TYPE IN(2,5)
			BEGIN
		    
				IF @NPREFIX_XN_ITEM_TYPE =2
				 SET @CMEMOPREFIX= CAST(SUBSTRING(@CMEMOPREFIX,1,LEN(@CMEMOPREFIX)-1) AS VARCHAR(100))+'C'+'-'
				ELSE IF @NPREFIX_XN_ITEM_TYPE=5 AND  @CXNTYPESEARCH IN ('GRP_PUR','WSL_GRP','WSR_GRP','PUR_GRP')
				 SET @CMEMOPREFIX= CAST(SUBSTRING(@CMEMOPREFIX,1,LEN(@CMEMOPREFIX)-1) AS VARCHAR(100))+'R'+'-'
			END

		END


		IF ISNULL(@NMEMOTYPE,0)=2
		BEGIN
           SET @CMEMOPREFIX= CAST(SUBSTRING(@CMEMOPREFIX,1,LEN(@CMEMOPREFIX)-1) AS VARCHAR(100))+'E'+'-'
		END
	

	END
	
	--END OF ESTIMATE BILL 
	
	SET @CSTEP='110'
	IF LEN(LTRIM(RTRIM(@CMEMOPREFIX)))>25
	BEGIN
		SET @CERRORMSG='PREFIX :'+@CMEMOPREFIX+' LENGTH GETTING LONGER THAT 25 CHARACTERS .... CANNOT PROCEED'
		GOTO END_PROC
	END
	
	IF @NSETUPMODE=1 ---- MANUAL SERIES
	BEGIN
		IF EXISTS (SELECT TOP 1 A.* FROM SERIES_SETUP_MANUAL_DET A
				   JOIN SERIES_SETUP_MST B ON A.MEMO_ID=B.MEMO_ID
				   WHERE B.XN_TYPE=@CXNTYPESEARCH AND PREFIX=@CMANUALPREFIX AND ISNULL(A.START_FROM,0)>1
				   AND (xn_item_type=@xn_item_type OR (ISNULL(@xn_item_type,0)=0 AND xn_item_type=1)))			   
		BEGIN
			
			SET @CSTEP='115'
			
			SET @CTABLENAME =	 ( CASE WHEN  @CXNTYPESEARCH LIKE '%PUR%' THEN 'PIM01106' 	
									 WHEN @CXNTYPESEARCH LIKE '%PRT%' THEN 'RMM01106'
									 WHEN @CXNTYPESEARCH LIKE '%FDN%' THEN 'RMM01106'
									 WHEN @CXNTYPESEARCH LIKE '%WSL%' THEN 'INM01106'
									 WHEN @CXNTYPESEARCH LIKE '%PO%' THEN 'POM01106'
									 WHEN @CXNTYPESEARCH LIKE '%WSR%' THEN 'CNM01106' END)

			
			SET @CKEYSTABLE =	  ( CASE WHEN  @CXNTYPESEARCH LIKE '%PUR%' THEN 'KEYS_PUR' 	
									 WHEN @CXNTYPESEARCH LIKE '%PRT%' THEN 'KEYS_PRT'
									 WHEN @CXNTYPESEARCH LIKE '%FDN%' THEN 'KEYS_PRT'
									 WHEN @CXNTYPESEARCH LIKE '%WSL%' THEN 'KEYS_INM'
									 WHEN @CXNTYPESEARCH LIKE '%PO%' THEN 'KEYS'
									 WHEN @CXNTYPESEARCH LIKE '%WSR%' THEN 'KEYS_CNM' END )

			SET @CCOLUMNNAME =	  ( CASE WHEN  @CXNTYPESEARCH LIKE '%PUR%' THEN 'MRR_NO' 	
									 WHEN @CXNTYPESEARCH LIKE '%PRT%' THEN 'RM_NO'
									 WHEN @CXNTYPESEARCH LIKE '%FDN%' THEN 'RM_NO'
									 WHEN @CXNTYPESEARCH LIKE '%WSL%' THEN 'INV_NO'
									 WHEN @CXNTYPESEARCH LIKE '%PO%' THEN 'PO_NO'
									 WHEN @CXNTYPESEARCH LIKE '%WSR%' THEN 'CN_NO' END )

						
			SET @CSTEP='120'
			IF OBJECT_ID('TEMPDB..#KEYS','U') IS NOT NULL
				DROP TABLE #KEYS
			 
			SELECT TABLENAME, LASTKEYVAL, COLUMNNAME, PREFIX, FINYEAR INTO #KEYS
			FROM KEYS WHERE 1=2
			 
			SET @CSTEP='130'	
			SET @CCMD=N'SELECT '''+@CTABLENAME+''' AS TABLENAME,'''+@CCOLUMNNAME+''' AS COLUMNNAME,
			 '''+@CMEMOPREFIX+''' AS PREFIX,'''+@CFINYEAR+''' AS FINYEAR,'''+@CMEMOPREFIX+'''+
			 REPLICATE(''0'',6-LEN(LTRIM(RTRIM(STR(A.START_FROM-1)))))+LTRIM(RTRIM(STR(A.START_FROM-1))) AS LASTKEYVAL
			 FROM SERIES_SETUP_MANUAL_DET A
		     JOIN SERIES_SETUP_MST B ON A.MEMO_ID=B.MEMO_ID
		     WHERE B.XN_TYPE='''+@CXNTYPESEARCH+''' AND PREFIX='''+@CMANUALPREFIX+'''
			 AND (xn_item_type='+STR(@xn_item_type)+' OR (ISNULL('+STR(@xn_item_type)+',0)=0 AND xn_item_type=1))'
			
			PRINT @CCMD 
			INSERT #KEYS	( TABLENAME, COLUMNNAME, PREFIX, FINYEAR,LASTKEYVAL ) 			 			   
			EXEC SP_EXECUTESQL @CCMD 
			
			SET @CSTEP='135'
						
			SET @CCMD=N'INSERT '+@CKEYSTABLE+' ( TABLENAME, LASTKEYVAL, COLUMNNAME, PREFIX, FINYEAR )  
			 SELECT A.TABLENAME,A.LASTKEYVAL, A.COLUMNNAME,  A.PREFIX, A.FINYEAR
			 FROM #KEYS A LEFT OUTER JOIN '+@CKEYSTABLE+' B ON A.TABLENAME=B.TABLENAME AND A.COLUMNNAME=B.COLUMNNAME
			 AND A.PREFIX=B.PREFIX WHERE B.TABLENAME IS NULL'
			
			PRINT @CCMD 
			EXEC SP_EXECUTESQL @CCMD 
				 
		END		
	END
	
END TRY

BEGIN CATCH
	SET @CERRORMSG='ERROR IN PROCEDURE SAVETRAN_GETMEMOPREFIX AT STEP#'+@CSTEP+' '+ERROR_MESSAGE()
	GOTO END_PROC
END CATCH	

END_PROC:
	
END