CREATE PROCEDURE SP3S_PRINTRECEIPT_GST  
(  
 @CXN_TYPE VARCHAR(10)='',  
 @CXN_ID VARCHAR(100)='', 
 @TYP INT
)  
AS  
BEGIN  
--IF @TYP=3 SET @TYP=2       
DECLARE @DTSQL NVARCHAR(MAX),@CCOLNAME VARCHAR(MAX),@CERRMSG VARCHAR(100),@NCALQTYSUM NUMERIC(10,3),  
        @NSTOREDQTY NUMERIC(10,3),@CSTEP VARCHAR(10),@REF_NO VARCHAR(1000),@NTYPE INT,  
        @PAYMODE VARCHAR(MAX),@REP_TYPE VARCHAR(2),@locid varchar(5)
SET @CERRMSG=''  
SET @PAYMODE=''
SET @CSTEP=100  
  
IF @CXN_TYPE!='ARC'  
   RETURN  
SET NOCOUNT ON     
SELECT @NTYPE=ARC01106.ARCT,@locid=location_Code  FROM ARC01106(NOLOCK) WHERE ARC01106.ADV_REC_ID=@CXN_ID  
  --select emp_code,emp_code1,emp_code2,* from CMd01106
  --select emp_code,* from WSL_ORDER_MST
DECLARE @SALES_PERSON VARCHAR(MAX)=''  
IF @NTYPE=1
   SELECT @SALES_PERSON=ISNULL(@SALES_PERSON,'')+EMP_NAME+','
   FROM
   (SELECT DISTINCT E.EMP_NAME
   FROM CMM_CREDIT_RECEIPT R (NOLOCK) 
   JOIN CMD01106 C (NOLOCK) ON C.CM_ID=R.CM_ID   
   JOIN EMPLOYEE E (NOLOCK) ON E.EMP_CODE=C.EMP_CODE
   WHERE R.ADV_REC_ID=@CXN_ID AND C.EMP_CODE<>'0000000'
   UNION
   SELECT DISTINCT E.EMP_NAME
   FROM CMM_CREDIT_RECEIPT R (NOLOCK) 
   JOIN CMD01106 C (NOLOCK) ON C.CM_ID=R.CM_ID   
   JOIN EMPLOYEE E (NOLOCK) ON E.EMP_CODE=C.EMP_CODE1
   WHERE R.ADV_REC_ID=@CXN_ID AND C.EMP_CODE1<>'0000000'
   UNION
   SELECT DISTINCT E.EMP_NAME
   FROM CMM_CREDIT_RECEIPT R (NOLOCK) 
   JOIN CMD01106 C (NOLOCK) ON C.CM_ID=R.CM_ID   
   JOIN EMPLOYEE E (NOLOCK) ON E.EMP_CODE=C.EMP_CODE2
   WHERE R.ADV_REC_ID=@CXN_ID AND C.EMP_CODE2<>'0000000'
   )E
ELSE IF @NTYPE=2
   SELECT @SALES_PERSON=ISNULL(@SALES_PERSON,'')+EMP_NAME+','
   FROM (SELECT DISTINCT E.EMP_NAME
   FROM WSL_ORDER_ADV_RECEIPT R (NOLOCK)  
   JOIN WSL_ORDER_MST MST (NOLOCK) ON R.ORDER_ID=MST.ORDER_ID  
   JOIN EMPLOYEE E (NOLOCK) ON E.EMP_CODE=MST.EMP_CODE
   WHERE R.ADV_REC_ID=@CXN_ID AND E.EMP_CODE<>'0000000')E

IF @SALES_PERSON<>'' AND RIGHT(@SALES_PERSON,1)=','
   SET @SALES_PERSON=LEFT(@SALES_PERSON,LEN(@SALES_PERSON)-1)	
   
IF @NTYPE=1  
   SELECT @REF_NO=ISNULL(@REF_NO,'')+C.CM_NO+', '  
   FROM CMM_CREDIT_RECEIPT R (NOLOCK) 
   JOIN CMM01106 C (NOLOCK) ON C.CM_ID=R.CM_ID   
   WHERE R.ADV_REC_ID=@CXN_ID  
   ORDER BY C.CM_ID  
ELSE IF @NTYPE=2  
   SELECT @REF_NO=ISNULL(@REF_NO,'')+MST.ORDER_NO+', '  
   FROM WSL_ORDER_ADV_RECEIPT R (NOLOCK)  
   JOIN WSL_ORDER_MST MST (NOLOCK) ON R.ORDER_ID=MST.ORDER_ID  
   WHERE R.ADV_REC_ID=@CXN_ID  
   ORDER BY MST.ORDER_NO  
   
SELECT TOP 1 @REP_TYPE=CASE WHEN REPORT_NAME LIKE '%THERMAL%' THEN 'TH' ELSE 'A5' END 
FROM GST_REPORT_CONFIG WHERE XN_TYPE='ARC' AND DEFAULT1=1  --@CXN_TYPE

SET @REF_NO=RTRIM(ISNULL(@REF_NO,''))  
IF RIGHT(@REF_NO,1)=','  
   SET @REF_NO=LEFT(@REF_NO,LEN(@REF_NO)-1)  
 
 --PRINT CUSTOMER BALANCE
 IF ISNULL(@NTYPE,0) IN (1,2)
 BEGIN
    
    DECLARE @CUST_BAL DECIMAL(14,2),@DR_CR VARCHAR(20),@PRINTCUSBAL BIT
	SET @CUST_BAL=0
	SET @DR_CR=''
	SET @PRINTCUSBAL=0
	SELECT @PRINTCUSBAL=CAST(ISNULL(PRINTCUSBAL,0)AS BIT) FROM GST_SLS_CUSTOMER_CONFIG WHERE XN_TYPE='SLS'
	SET @PRINTCUSBAL=ISNULL(@PRINTCUSBAL,0)
	IF @PRINTCUSBAL=1
	   BEGIN
		  SELECT TOP 1 @DR_CR=CUSTOMER_CODE FROM ARC01106 (NOLOCK) WHERE ADV_REC_ID =@CXN_ID
		  SELECT @CUST_BAL=CUST_BAL  FROM custdym WHERE CUSTOMER_CODE=@DR_CR
		  SELECT @CUST_BAL=ISNULL(@CUST_BAL,0)
		  SET @DR_CR=CASE SIGN(@CUST_BAL) WHEN 1 THEN 'DR' WHEN -1 THEN 'CR' ELSE '' END
		  SET @CUST_BAL=ABS(@CUST_BAL)
	   END
 
 END
 --END OF CUSTOMER BALANCE    
BEGIN TRY  
  SET @CSTEP=10 
  DECLARE @NSERVELOC BIT,
  @loc_ADDRESS1 varchar(100),@loc_ADDRESS2 varchar(100) ,@loc_CITY varchar(100),
  @loc_PHONE varchar(100),@loc_TIN_NO varchar(100),@loc_TAN_NO varchar(100)

  SELECT @NSERVELOC=SERVER_LOC  FROM LOCATION  WHERE DEPT_ID=  @locid 


 
  
	 SELECT @LOC_ADDRESS1=isnull(ADDRESS1,''),
	 @LOC_ADDRESS2=isnull(ADDRESS2,'') ,@LOC_CITY=isnull(CITY,''),
	 @LOC_PHONE=isnull(PHONE ,''),
	 @LOC_TIN_NO=isnull(TIN_NO,''),
	 @LOC_TAN_NO=isnull(TAN_NO,'')
	 FROM LOC_VIEW  L (NOLOCK) WHERE DEPT_ID =@locid 

  
  --BLOCK 1 - COMPANY & PARTY INFO  
  IF OBJECT_ID('TEMPDB..#DATASET1') IS NOT NULL  
     DROP TABLE #DATASET1  
  SELECT l.Dept_Print_Name  COMPANY_NAME  
   ,isnull(@LOC_ADDRESS1,'' ) AS ADDRESS1
   ,ISNULL(@LOC_ADDRESS2,''  ) AS ADDRESS2
   ,ISNULL(@LOC_CITY,''  ) AS CITY
   ,ISNULL(@LOC_PHONE,'' ) AS PHONES_FAX
   ,ISNULL(@LOC_TIN_NO,''  ) AS TIN_NO
   ,ISNULL(@LOC_TAN_NO,'')  AS TAN_NO
   ,CIN=CASE LEN(ISNULL(CMP.CIN,'')) WHEN 0 THEN '' ELSE 'CIN: '+CMP.CIN END  
   ,CMP.LOGO_PATH  
   ,LOC_GST_NO=CASE LEN(ISNULL(L.LOC_GST_NO,'')) WHEN 0 THEN '' ELSE 'GSTIN: '+L.LOC_GST_NO END   
   ,CAST(0 AS NUMERIC(10,2)) AS REVERSE_CHARGES  
   ,CASE ISNULL(ARC.ADV_REC_NO,'') WHEN '' THEN '' ELSE 'NO: '+ARC.ADV_REC_NO END AS ADV_REC_NO  
   ,CASE YEAR(ISNULL(ARC.ADV_REC_DT,'')) WHEN 1900 THEN '' ELSE 'DATE: '+CONVERT(VARCHAR,ARC.ADV_REC_DT,105) END AS ADV_REC_DT  
   ,ISNULL(LOCS.GST_STATE_NAME,'') AS  LOC_GST_STATE_NAME  
   ,LOCS.GST_STATE_CODE AS LOC_GST_STATE_CODE  
     
   ,CASE WHEN LM.AC_CODE NOT IN('','0000000000') THEN AC_NAME ELSE CUSTOMER_FNAME +' '+CUSTOMER_LNAME END   
    +CASE LEN(CU.USER_CUSTOMER_CODE) WHEN 0 THEN '' ELSE ISNULL(' ( '+USER_CUSTOMER_CODE+' )','') END  
    AS PARTY_NAME   
      
   ,CASE WHEN ISNULL(ARC.CUSTOMER_CODE,'')IN ('','0000000000')  
         THEN RTRIM(LTRIM(LMP.ADDRESS0+' '+LMP.ADDRESS1+' '+LMP.ADDRESS2+' '+LA.AREA_NAME +' '+LC.CITY+' '+LA.PINCODE ))   
         ELSE RTRIM(LTRIM(CU.ADDRESS1+' '+CU.ADDRESS2+' '+' '+CA.AREA_NAME+CC.CITY+' '+CU .PIN ))    
    END AS PARTY_ADDRESS  
      
   ,CASE WHEN ISNULL(ARC.CUSTOMER_CODE,'')IN ('','0000000000')  
         THEN RTRIM(LTRIM(LMP.ADDRESS0))   
         ELSE RTRIM(LTRIM(CU.ADDRESS1))    
    END AS PARTY_ADDRESS1  

   ,CASE WHEN ISNULL(ARC.CUSTOMER_CODE,'')IN ('','0000000000')  
         THEN RTRIM(LTRIM(LMP.ADDRESS1))   
         ELSE RTRIM(LTRIM(CU.ADDRESS2))    
    END AS PARTY_ADDRESS2
    
   ,CASE WHEN ISNULL(ARC.CUSTOMER_CODE,'')IN ('','0000000000')  
         THEN RTRIM(LTRIM(LMP.ADDRESS2))
         ELSE RTRIM(LTRIM(CU.ADDRESS0))+' '+RTRIM(LTRIM(CU.ADDRESS9))    
    END AS PARTY_ADDRESS3
    
   ,CASE WHEN ISNULL(ARC.CUSTOMER_CODE,'')IN ('','0000000000')  
         THEN RTRIM(LTRIM(LC.CITY+' '+LA.PINCODE))   
         ELSE RTRIM(LTRIM(CA.AREA_NAME+' '+CC.CITY+' '+(SELECT AREA.PINCODE FROM AREA WHERE AREA_CODE=CA.AREA_CODE)))    
    END AS PARTY_CITY
    
   ,CASE WHEN ISNULL(ARC.CUSTOMER_CODE,'')IN ('','0000000000') THEN LMP.AC_GST_NO ELSE CUS_GST_NO END  
    AS PARTY_GST_NO  
      
   ,CASE WHEN ISNULL(ARC.CUSTOMER_CODE,'')IN ('','0000000000') THEN LS.GST_STATE_NAME ELSE CS.GST_STATE_NAME END  
    AS PARTY_STATE_NAME
    
   ,CASE WHEN ISNULL(ARC.CUSTOMER_CODE,'')IN ('','0000000000') THEN LS.GST_STATE_CODE ELSE CS.GST_STATE_CODE END  
    AS PARTY_STATE_CODE  
         
   ,CASE WHEN ARC.CANCELLED =1 THEN 'CANCELLED' ELSE '' END AS CANCELLED  
     
       
   ,CASE ARC.ARCT WHEN 1 THEN 'OUTSTANDING' WHEN 2 THEN 'ADVANCE' END+' VOUCHER'  
    AS INVOICE_TYPE----,'RECEIPT VOUCHER'  
     
   ,CASE ARC.ARCT WHEN 1 THEN CASE LEN(@REF_NO) WHEN 0 THEN '' ELSE 'AGAINST BILL NO: '+@REF_NO END   
                  WHEN 2 THEN CASE LEN(@REF_NO) WHEN 0 THEN '' ELSE 'AGAINST BO NO: '  +@REF_NO END  
    END                
    AS REF_NO  
     
   ,ISNULL(LOCS.UT,0) AS UT --CHECK & CHANGES  
   ,(SELECT TOP 1 ISNULL(IS_ENABLED,0) FROM GST_TNC WHERE XN_TYPE=@CXN_TYPE)AS PRINT_TERM  
   ,ISNULL(L.REGISTERED_ADD,'')REGISTERED_ADDRESS  
   ,'REMARKS: '+ISNULL(ARC.REMARKS,'')REMARKS  
   ,(SELECT TOP 1 ISNULL(LOGO,0) FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE)AS LOGO  
   ,(SELECT TOP 1 ISNULL(NAME,0) FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE)AS NAME  
   ,(SELECT TOP 1 ISNULL(ADDRESS1,0) FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE)AS [ADDRESS]  
   ,(SELECT TOP 1 ISNULL(TELEPHONE1,0) FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE)AS TELEPHONE1  
   ,(SELECT TOP 1 ISNULL(CIN_NO,0) FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE)AS CIN_NO  
   ,(SELECT TOP 1 ISNULL(DATE_WITH_TIME,0) FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE)AS DATE_WITH_TIME  
   ,(SELECT TOP 1 ISNULL(PRINT_SALE_PERSON,0) FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE)AS PRINT_SALE_PERSON  
   ,'NO: '+ADV_REC_NO AS INV_NO	
   ,'DATE: '+CONVERT(VARCHAR,ADV_REC_DT,106) AS INV_DT
    --03 FEB 2018
   ,(SELECT TOP 1 ISNULL(PRINT_AUTHORIZED_SIGNATURE,0) FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE)PRINT_AUTHORIZED_SIGNATURE  
   --06 FEB 2018
   ,CASE @REP_TYPE WHEN 'TH' THEN 0.00 ELSE (SELECT TOP 1 ISNULL(TOP_MARGIN,0.01) FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE) END AS TOP_MARGIN
   ,CASE @REP_TYPE WHEN 'TH' THEN 0.01 ELSE (SELECT TOP 1 ISNULL(BOTTOM_MARGIN,0.01) FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE) END AS BOTTOM_MARGIN
   ,CASE @REP_TYPE WHEN 'TH' THEN 0.01 ELSE (SELECT TOP 1 ISNULL(LEFT_MARGIN,0.09) FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE) END AS LEFT_MARGIN
   ,CASE @REP_TYPE WHEN 'TH' THEN 0.01 ELSE (SELECT TOP 1 ISNULL(RIGHT_MARGIN,0.00) FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE) END AS RIGHT_MARGIN
   --08 FEB 2018
   ,ISNULL((SELECT TOP 1 PRINT_COPIES FROM GST_SLS_CUSTOMER_CONFIG (NOLOCK) WHERE XN_TYPE=@CXN_TYPE),1)AS PRINT_COPIES
   ,ISNULL(@CUST_BAL,0) AS  CUST_BAL,ISNULL(@DR_CR,'') AS  BAL_TYPE,ISNULL(@PRINTCUSBAL,0) PRINTCUSBAL
   ,CAST(1 AS BIT) PRINT_ADDRESS1
   ,CASE WHEN ARC.arc_type =1 THEN 'PAYMENT' ELSE 'RECEIPT' END AS ARC_TYPE,EMP.EMP_NAME 
   INTO #DATASET1    
   FROM ARC01106 ARC (NOLOCK)    
   LEFT JOIN LMP01106 LMP (NOLOCK) ON LMP.AC_CODE=ARC.AC_CODE  
   LEFT JOIN CUSTDYM CU (NOLOCK) ON CU.CUSTOMER_CODE =ARC.CUSTOMER_CODE   
   LEFT JOIN LM01106 LM (NOLOCK) ON LM.AC_CODE=LMP.AC_CODE  
   LEFT JOIN AREA LA (NOLOCK) ON LA.AREA_CODE=LMP.AREA_CODE  
   LEFT JOIN CITY LC (NOLOCK) ON LC.CITY_CODE=LA.CITY_CODE  
   LEFT JOIN GST_STATE_MST LS (NOLOCK) ON LS.GST_STATE_CODE=LMP.AC_GST_STATE_CODE  
   LEFT JOIN AREA CA (NOLOCK) ON CA.AREA_CODE=CU.AREA_CODE  
   LEFT JOIN CITY CC (NOLOCK) ON CC.CITY_CODE=CA.CITY_CODE  
   LEFT JOIN GST_STATE_MST CS (NOLOCK) ON CS.GST_STATE_CODE=CU.CUS_GST_STATE_CODE   
   LEFT JOIN COMPANY CMP (NOLOCK) ON CMP.COMPANY_CODE='01'  
   LEFT OUTER JOIN LOCATION L (NOLOCK) ON L.DEPT_ID =ARC.location_Code 
   LEFT JOIN GST_STATE_MST LOCS (NOLOCK) ON LOCS.GST_STATE_CODE=L.GST_STATE_CODE 
    LEFT OUTER JOIN EMPLOYEE EMP (NOLOCK)  ON  ARC.EMP_CODE = EMP.EMP_CODE 
   WHERE ARC.ADV_REC_ID=@CXN_ID AND ARC.ARCT=@TYP
  
   UPDATE #DATASET1 SET ADDRESS1=REPLACE(ADDRESS1,'(WC)','')  
  ,ADDRESS2=REPLACE(ADDRESS2,'(WC)','')  
  ,CITY=REPLACE(CITY,'(WC)','')  
  ,PARTY_ADDRESS=REPLACE(PARTY_ADDRESS,'(WC)','')  
  ,PARTY_ADDRESS1=REPLACE(PARTY_ADDRESS1,'(WC)','')  
  ,PARTY_ADDRESS2=REPLACE(PARTY_ADDRESS2,'(WC)','')  
  ,PARTY_ADDRESS3=REPLACE(PARTY_ADDRESS3,'(WC)','')  
  ,PARTY_CITY=REPLACE(PARTY_CITY,'(WC)','')  
  ,PARTY_STATE_NAME=REPLACE(PARTY_STATE_NAME,'(WC)','')  
  --,PARTY_CITY=REPLACE(PARTY_CITY,'(WC)','')  
  SELECT *,@SALES_PERSON SALES_PERSON FROM #DATASET1   
  
  SET @DTSQL=N'SELECT SUM(A.NET_AMOUNT)NET_AMOUNT  
                     ,SUM(A.DISCOUNT_AMOUNT)DISC_PER
                     ,SUM(A.AMOUNT) RECEIPT_AMOUNT
               FROM ARC01106 A (NOLOCK)  
               WHERE A.ADV_REC_ID='''+@CXN_ID+'''  
               --GROUP BY ISNULL(A.GOODS_DESCRIPTION,''''),ISNULL(A.HSN_CODE,''000000000''),ISNULL(A.GST_PERCENTAGE,0)  
              '  
  PRINT @DTSQL         
  EXEC SP_EXECUTESQL @DTSQL         
  
  SELECT C.CM_NO BILL_NO,C.CM_DT DT,R.RECEIPT_AMOUNT AMOUNT
  FROM CMM_CREDIT_RECEIPT R (NOLOCK) JOIN CMM01106 C (NOLOCK)  ON C.CM_ID=R.CM_ID
  WHERE R.ADV_REC_ID=@CXN_ID AND @TYP=1


	IF ISNULL(@TYP,0)=4
	BEGIN
	 
	 SELECT * FROM ARC_GVSALE_DETAILS GV (NOLOCK)   
	  LEFT OUTER JOIN SKU_GV_MST GVSKU (NOLOCK) ON GVSKU.GV_SRNO=GV.GV_SRNO 
	 WHERE GV.ADV_REC_ID=@CXN_ID AND @TYP=4  

	END 
	 
  SET @PAYMODE=''
  SELECT @PAYMODE=COALESCE(@PAYMODE,'')+LTRIM(RTRIM(B.PAYMODE_NAME))+':'+REPLACE(CAST(CAST(SUM(A.AMOUNT) AS DECIMAL(14,2)) AS VARCHAR),'.00','')+', '
  FROM PAYMODE_XN_DET A (NOLOCK)  
  JOIN PAYMODE_MST B (NOLOCK) ON A.PAYMODE_CODE=B.PAYMODE_CODE  
  WHERE A.XN_TYPE ='ARC' AND A.MEMO_ID=@CXN_ID
  GROUP BY B.PAYMODE_NAME  
  SET @PAYMODE=REPLACE(LTRIM(RTRIM(@PAYMODE)),'INR','CASH')
  SET @PAYMODE=CASE LEN(@PAYMODE) WHEN 0 THEN '' ELSE LEFT(@PAYMODE,LEN(@PAYMODE)-1) END
  SELECT @PAYMODE+=CASE ISNULL(DISCOUNT_AMOUNT,0) WHEN 0 THEN '' ELSE ', DISC '+CAST(ISNULL(DISCOUNT_AMOUNT,0) AS VARCHAR) END
  FROM ARC01106 A (NOLOCK)  
  WHERE A.ADV_REC_ID=@CXN_ID
  
  SET @DTSQL=N'SELECT ROW_NUMBER() OVER (ORDER BY ISNULL(A.GOODS_DESCRIPTION,'''')) AS SR_NO  
         ,ISNULL(A.HSN_CODE,''000000000'') AS HSN_CODE  
         ,SUM(A.AMOUNT-ISNULL(A.DISCOUNT_AMOUNT*CASE '+CAST(@TYP AS VARCHAR)+' WHEN 2 THEN 0 ELSE 1 END,0)-ISNULL(A.IGST_AMOUNT,0)-ISNULL(A.SGST_AMOUNT,0)-ISNULL(A.CGST_AMOUNT,0)) AS TAXABLE_VALUES
         ,SUM(A.NET_AMOUNT)NET_AMOUNT  
         ,CAST(ROUND(CASE WHEN SUM(ISNULL(A.IGST_AMOUNT,0))>0 THEN ISNULL(A.GST_PERCENTAGE,0) ELSE 0 END,2) AS DECIMAL(10,2)) AS IGST_PER  
         ,SUM(ISNULL(A.IGST_AMOUNT,0))IGST_AMOUNT  
         ,CAST(ROUND(CASE WHEN SUM(ISNULL(A.CGST_AMOUNT,0))>0 THEN ISNULL(A.GST_PERCENTAGE,0)/2 ELSE 0 END,2) AS DECIMAL(10,2)) AS CGST_PER  
		 ,SUM(ISNULL(A.CGST_AMOUNT,0))CGST_AMOUNT  
		 ,CAST(ROUND(CASE WHEN SUM(ISNULL(A.SGST_AMOUNT,0))>0 THEN ISNULL(A.GST_PERCENTAGE,0)/2 ELSE 0 END,2) AS DECIMAL(10,2)) AS SGST_PER  
	     ,SUM(ISNULL(A.SGST_AMOUNT,0))SGST_AMOUNT  
		 --,SUM(A.NET_AMOUNT)AS ADV_RECEIPT_AMT
		 ,SUM(CASE '+CAST(@TYP AS VARCHAR)+' WHEN 2 THEN A.AMOUNT ELSE A.NET_AMOUNT END)AS ADV_RECEIPT_AMT
		 ,ISNULL(SUM(CGST_AMOUNT+SGST_AMOUNT+IGST_AMOUNT),0)AS [AMOUNT]  
		 ,'''+@PAYMODE+''' AS PAYMODE
		 ,CAST(ISNULL(A.GST_PERCENTAGE,0) AS DECIMAL(10,2)) AS [GST]
		 ,ISNULL(A.REMARKS,'''') AS REMARKS,AMOUNT
  FROM ARC01106 A (NOLOCK)  
  WHERE A.ADV_REC_ID='''+@CXN_ID+'''  
  GROUP BY ISNULL(A.GOODS_DESCRIPTION,''''),ISNULL(A.HSN_CODE,''000000000''),ISNULL(A.GST_PERCENTAGE,0),ISNULL(A.REMARKS,'''') ,AMOUNT 
  '  
  PRINT @DTSQL         
  EXEC SP_EXECUTESQL @DTSQL         
  
  /*
  
    
     
  SELECT B.PAYMODE_NAME   
  FROM PAYMODE_XN_DET A (NOLOCK)  
    JOIN PAYMODE_MST B (NOLOCK) ON A.PAYMODE_CODE=B.PAYMODE_CODE  
  WHERE A.XN_TYPE =@CXN_TYPE AND A.MEMO_ID=@CXN_ID  
  GROUP BY B.PAYMODE_NAME  
     
  --ADD NEW AS BLOCK FOR GST PERCENTAGE  
  SELECT *  
        ,[IGST_PER]=CASE ISNULL([IGST_AMOUNT],0) WHEN 0 THEN '0%' WHEN [GST_COLLECTION] THEN GST ELSE GST END  
        ,[CGST_PER]=CASE ISNULL([CGST_AMOUNT],0) WHEN 0 THEN '0%' ELSE DBO.CURR_GROUPING(ROUND(CAST(REPLACE([GST],'%','') AS DECIMAL(10,2))/2,2),'')+'%' END  
        ,[SGST_PER]=CASE ISNULL([SGST_AMOUNT],0) WHEN 0 THEN '0%' ELSE DBO.CURR_GROUPING(ROUND(CAST(REPLACE([GST],'%','') AS DECIMAL(10,2))/2,2),'')+'%' END  
  FROM  
   (  
     SELECT CAST(DBO.CURR_GROUPING(GST_PERCENTAGE,'') AS VARCHAR)+'%'[GST]  
    ,ISNULL(SUM(NET_AMOUNT-CGST_AMOUNT-SGST_AMOUNT-IGST_AMOUNT),0) AS [TAXABLE_VALUES]  
    ,ISNULL(SUM(CGST_AMOUNT),0) AS [CGST_AMOUNT]   
    ,ISNULL(SUM(SGST_AMOUNT),0) AS [SGST_AMOUNT]   
    ,ISNULL(SUM(IGST_AMOUNT),0) AS [IGST_AMOUNT]  
    ,ISNULL(SUM(CGST_AMOUNT+SGST_AMOUNT+IGST_AMOUNT),0)AS [GST_COLLECTION]  
    FROM ARC01106 (NOLOCK)   
    WHERE ADV_REC_ID=@CXN_ID  
    GROUP BY CAST(DBO.CURR_GROUPING(GST_PERCENTAGE,'') AS VARCHAR)  
   )GST  
   */     
   SELECT TNC_1,TNC_2,TNC_3,TNC_4,TNC_5,TNC_6  FROM GST_TNC WHERE XN_TYPE=@CXN_TYPE  
   
   GOTO END_PROC  
END TRY    
    
BEGIN CATCH    
  BEGIN  
    SELECT @CERRMSG='ERROR MESSAGE IN PROCEDURE SP3S_PRINTRECEIPT_GST STEP#'+@CSTEP+' '+CAST(ERROR_MESSAGE() AS VARCHAR(MAX))+ '||'+ERROR_PROCEDURE()    
    GOTO END_PROC  
  END  
END CATCH     
     
END_PROC:  
    SELECT @CERRMSG AS ERRMSG  
SET NOCOUNT OFF    
END--SP3S_PRINTRECEIPT_GST
