CREATE PROCEDURE SP3S_REBUILD_XN_RFNET
@dCutoffDate DATETIME=''
AS
BEGIN

		IF OBJECT_ID('TEMPDB..#TMPMRR','U') IS NOT NULL
		   DROP TABLE #TMPMRR
		
		IF @dCutoffDate=''
			SET @dCutoffDate='2021-04-01'

		SELECT A.RECEIPT_DT, A.MRR_ID ,A.TOTAL_AMOUNT ,RFNET 
		INTO #TMPMRR 
		FROM PIM01106 A (nolock)
		JOIN
		(
		  SELECT MRR_ID,SUM(RFNET) AS RFNET FROM PID01106 (nolock)
		   GROUP BY MRR_ID
		) B ON A.MRR_ID =B.MRR_ID 
		 WHERE  ABS(A.TOTAL_AMOUNT -ISNULL(B.RFNET,0))>1
		 AND receipt_dt >=@dCutoffDate AND CANCELLED=0


		 DECLARE @CMRR_ID VARCHAR(100)

		 WHILE EXISTS (SELECT TOP 1'U' FROM #TMPMRR)
		 BEGIN
    
			SELECT TOP 1 @CMRR_ID=MRR_ID FROM #TMPMRR

			EXEC SP3S_UPDATERFNET_PUR @CMRR_ID

			DELETE FROM #TMPMRR WHERE MRR_ID=@CMRR_ID

		 END

 

		IF OBJECT_ID('TEMPDB..#TMPINM','U') IS NOT NULL
		   DROP TABLE #TMPINM

		SELECT A.inv_dt, A.inv_id ,A.NET_AMOUNT ,RFNET 
		INTO #TMPINM 
		FROM INM01106 A (nolock)
		JOIN
		(
		  SELECT inv_id,SUM(RFNET) AS RFNET 
		   FROM ind01106  (nolock)
		   GROUP BY inv_id
		) B ON A.inv_id =B.inv_id 
		 WHERE  ABS(A.NET_AMOUNT -ISNULL(B.RFNET,0))>1
		 AND inv_dt >=@dCutoffDate AND CANCELLED=0


		 DECLARE @Cinv_ID VARCHAR(100)

		 WHILE EXISTS (SELECT TOP 1'U' FROM #TMPINM)
		 BEGIN
    
			SELECT TOP 1 @Cinv_ID=inv_id FROM #TMPINM

			EXEC SP3S_UPDATERFNET_wsl @Cinv_ID

			DELETE FROM #TMPINM WHERE inv_id=@Cinv_ID

		 END



 

		IF OBJECT_ID('TEMPDB..#TMPRMM','U') IS NOT NULL
		   DROP TABLE #TMPRMM

		SELECT A.rm_dt, A.RM_ID ,A.total_amount ,RFNET 
		INTO #TMPRMM 
		FROM rmm01106 A (nolock)
		JOIN
		(
		  SELECT rm_id,SUM(RFNET) AS RFNET 
		   FROM RMD01106  (nolock)
		   GROUP BY RM_ID
		) B ON A.rm_id =B.rm_id 
		 WHERE  ABS(A.total_amount -ISNULL(B.RFNET,0))>1
		 AND rm_dt >=@dCutoffDate AND CANCELLED=0


		 DECLARE @CRM_ID VARCHAR(100)

		 WHILE EXISTS (SELECT TOP 1'U' FROM #TMPRMM)
		 BEGIN
    
			SELECT TOP 1 @CRM_ID=RM_ID FROM #TMPRMM

			EXEC SP3S_UPDATERFNET_PRT @CRM_ID

			DELETE FROM #TMPRMM WHERE RM_ID=@CRM_ID

		 END

 
		IF OBJECT_ID('TEMPDB..#TMPCNM','U') IS NOT NULL
		   DROP TABLE #TMPCNM

		SELECT A.cn_dt, A.cn_id ,A.total_amount ,RFNET 
		INTO #TMPCNM 
		FROM cnm01106 A (nolock)
		JOIN
		(
		  SELECT cn_id,SUM(RFNET) AS RFNET 
		   FROM cnd01106  (nolock)
		   GROUP BY cn_id
		) B ON A.cn_id =B.cn_id 
		 WHERE  ABS(A.total_amount -ISNULL(B.RFNET,0))>1
		 AND (cn_dt >=@dCutoffDate OR receipt_dt>=@dCutoffDate) AND CANCELLED=0


		 DECLARE @CCN_ID VARCHAR(100)

		 WHILE EXISTS (SELECT TOP 1'U' FROM #TMPCNM)
		 BEGIN
    
			SELECT TOP 1 @CCN_ID=cn_id FROM #TMPCNM

			EXEC SP3S_UPDATERFNET_WSR @CCN_ID

			DELETE FROM #TMPCNM WHERE cn_id=@CCN_ID

		 END


END