CREATE PROCEDURE PPC_SAVETRAN_BO_JOBS_CONSUME     
(    
  @NSPID   INT=0 ,  
  @CROW_ID VARCHAR(100),  
  @CJOB_CODE VARCHAR(100),
  @CBOM_ARTICLECODE VARCHAR(9)
)    
----WITH ENCRYPTION    
AS    
BEGIN    
DECLARE @CERRMSG VARCHAR(500),@CSTEP VARCHAR(10)    
    ,@CCMD NVARCHAR(MAX)    
    
DECLARE @TOUTPUT TABLE(MEMO_ID VARCHAR(50),ERRMSG VARCHAR(500))    
    
---LIST OF TABLES TO SAVE    
DECLARE @TBO_BO_ART_JOBS VARCHAR(100)    
--,@TSKU VARCHAR(100)    
    
    
SET @TBO_BO_ART_JOBS='WSLORD_PPC_BO_ART_JOBS_CONSUME_UPLOAD'    
--SET @TSKU=@CTABLE_PREFIX+'SKU'+@CTABLE_SUFFIX    
    
BEGIN TRY    
BEGIN TRANSACTION    
     SET @CSTEP=10    
         
     IF EXISTS (SELECT TOP 1 'U' FROM WSLORD_PPC_BO_ART_JOBS_CONSUME_UPLOAD WHERE SP_ID=LTRIM(RTRIM(STR(@NSPID))) GROUP BY REF_ROW_ID,JOB_CODE,BOM_ARTICLE_CODE HAVING COUNT(*)>1)    
     BEGIN    
         SET @CERRMSG='DUPLICATE BOM FOUND PLEASE CHECK.'    
         GOTO END_PROC    
     END    
       
   --DELETE THE EXISTING RECORD FOR THIS PPC_BO_ART_BOM    
 SET @CSTEP = 130   
 SET @CCMD = N'UPDATE '+ @TBO_BO_ART_JOBS + ' SET ROW_ID = NEWID() WHERE  SP_ID='''+LTRIM(RTRIM(STR(@NSPID)))+''''  
 PRINT @CCMD   
 EXEC SP_EXECUTESQL @CCMD  
     
   --DELETE A FROM PPC_BO_ART_JOBS_CONSUME A  
   --JOIN PPC_BO_ART_JOBS  B ON A.REF_ROW_ID=B.ROW_ID  
   --WHERE B.REF_ROW_ID=@CROW_ID   
   --AND B.JOB_CODE=@CJOB_CODE
   
    DELETE A FROM PPC_BO_ART_JOBS_CONSUME A  
   WHERE A.REF_ROW_ID=@CROW_ID   
   AND A.JOB_CODE=@CJOB_CODE
   AND A.BOM_ARTICLE_CODE=@CBOM_ARTICLECODE  
     
     
       
 DECLARE @FILTER VARCHAR(MAX)    
 SET @FILTER=' B.SP_ID= '''+LTRIM(RTRIM(STR(@NSPID)))+''' '     
     
 --SP_INSERTSTR PPC_SIZEGROUP_PARA2    
    EXEC UPDATEMASTERXN     
    @CSOURCEDB=''    
   ,@CSOURCETABLE=@TBO_BO_ART_JOBS    
   ,@CDESTDB=''    
   ,@CDESTTABLE='PPC_BO_ART_JOBS_CONSUME'    
   ,@CKEYFIELD1='ROW_ID'    
   ,@CKEYFIELD2=''    
   ,@CKEYFIELD3=''    
   ,@LINSERTONLY=0    
   ,@CFILTERCONDITION=@FILTER    
   ,@LUPDATEXNS=0    
   ,@CXNTYPE=''    
   ,@LUPDATEONLY=0    
   ,@CUSERID=''    
   ,@BALWAYSUPDATE=1    
    
      
END TRY    
BEGIN CATCH     
 SET @CERRMSG='PPC_BO_JOBS_CONSUME: STEP - '+ISNULL(@CSTEP,'')+', MESSAGE - '+ERROR_MESSAGE()     
END CATCH    
    
END_PROC:    
    
IF @@TRANCOUNT>0      
 BEGIN      
  IF ISNULL(@CERRMSG,'')=''     
   COMMIT TRANSACTION      
  ELSE      
   ROLLBACK      
 END      
    
--DROP TEMP TABLES    
IF ISNULL(@CERRMSG,'')=''    
BEGIN    
    DELETE FROM WSLORD_PPC_BO_ART_JOBS_CONSUME_UPLOAD WHERE SP_ID=LTRIM(RTRIM(STR(@NSPID)))    
END    
    
INSERT @TOUTPUT(MEMO_ID,ERRMSG)    
SELECT '',ISNULL(@CERRMSG,'')    
    
SELECT * FROM @TOUTPUT    
    
END    
--END OF PROCEDURE - SAVETRAN_PPC_BO_ART_JOBS
