
CREATE PROCEDURE SP_PRD_WHOSALE_PENDING_REPORT    
(    
  @DFM_DT DATETIME='2018-04-01',    
  @DTODT DATETIME='2019-09-20',
  @CAC_CODE VARCHAR(MAX)='',--FILTER PENDING
  @NQTY_SKT INT=1,
  @CMERCHANT_CODE VARCHAR(MAX)=''    
      
)    
AS    
BEGIN    
          
      DECLARE @DTSQL NVARCHAR(MAX)  ,@CAC_STATUS VARCHAR(MAX) 
      ,@CMERCHANT_STATUS VARCHAR(MAX)  
    
   IF @CAC_CODE=''  
	BEGIN  
	   SET @CAC_STATUS=''  
	   SET @CAC_CODE='IN('''')'  
	END  
	ELSE   
	BEGIN  
	   SET @CAC_STATUS='LATER'  
	END  
  
      IF @CMERCHANT_CODE=''  
	BEGIN  
	   SET @CMERCHANT_STATUS=''  
	   SET @CMERCHANT_CODE='IN('''')'  
	END  
	ELSE   
	BEGIN  
	   SET @CMERCHANT_STATUS='LATER'  
	END  
  
      
     
   
  
  SET @DTSQL=N'SELECT BM.ORDER_ID AS ORDER_ID,
         BM.AC_CODE,LM.AC_NAME ,    
         BM.ORDER_NO,BM.ORDER_DT , 
         ART.ARTICLE_NO ,   
         A.PARA1_CODE ,P1.PARA1_NAME ,    
         A.PARA2_CODE ,P2.PARA2_NAME ,    
         OM.MEMO_NO AS WO_NO,    
         OM.MEMO_DT AS WO_DT ,    
         A.PRODUCT_CODE,
         A.QUANTITY AS QUANTITY,
         CAST(PMT.QUANTITY_IN_STOCK AS NUMERIC(10,0)) AS QUANTITY_IN_STOCK ,
         A.PRODUCT_CODE AS WIP_PRODUCT_CODE,
         B.MEMO_DT AS TTM_DT,
         B.MEMO_NO AS TTM_MEMO_NO,
         emp.emp_name as USERNAME
  FROM TRANSFER_TO_TRADING_DET A (NOLOCK)
  JOIN TRANSFER_TO_TRADING_MST B (NOLOCK) ON A.MEMO_ID =B.MEMO_ID
  JOIN PARA1 P1 (NOLOCK) ON P1.PARA1_CODE=A.PARA1_CODE     
  JOIN PARA2 P2 (NOLOCK) ON P2.PARA2_CODE =A.PARA2_CODE 
  JOIN ARTICLE ART (NOLOCK) ON ART.ARTICLE_CODE=A.ARTICLE_CODE 
  JOIN PMT01106 PMT (NOLOCK) ON PMT.PRODUCT_CODE =A.PRODUCT_CODE 
  JOIN JOBWORK_PMT JPMT (NOLOCK) ON JPMT.PRODUCT_CODE=A.PRODUCT_CODE
  JOIN ORD_PLAN_BARCODE_DET OD (NOLOCK) ON OD.PRODUCT_CODE =A.PRODUCT_CODE
  JOIN ORD_PLAN_DET DET (NOLOCK) ON DET.ROW_ID =OD.REFROW_ID
  JOIN ORD_PLAN_MST OM (NOLOCK) ON OM.MEMO_ID =DET.MEMO_ID 
  LEFT JOIN BUYER_ORDER_DET BD (NOLOCK) ON BD.ROW_ID=DET.WOD_ROW_ID
  LEFT JOIN BUYER_ORDER_MST BM (NOLOCK) ON Bm.ORDER_ID=ISNULL(JPMT.ORDER_ID ,BD.ORDER_ID )
  LEFT  JOIN LM01106 LM ON LM.AC_CODE =BM.AC_CODE 
  left join employee emp (nolock) on emp.emp_code=isnull(JPMT.item_merchant_code,bd.item_merchant_code)
  WHERE B.CANCELLED =0 AND  ISNULL(BM.CANCELLED,0)=0 AND OM.CANCELLED=0
  AND  B.MEMO_DT BETWEEN  '''+CONVERT(VARCHAR,@DFM_DT,121)+''' AND '''+CONVERT(VARCHAR,@DTODT,121)+'''
  AND ('''+RTRIM(LTRIM(STR(@NQTY_SKT)))+'''=0 OR  PMT.QUANTITY_IN_STOCK>0  ) 
  AND ('''+RTRIM(LTRIM(@CAC_STATUS))+'''='''' OR BM.AC_CODE '+@CAC_CODE+') 
  AND ('''+RTRIM(LTRIM(@CMERCHANT_STATUS))+'''='''' OR emp.EMP_CODE '+@CMERCHANT_CODE +') 
   '
  
  PRINT @DTSQL
  EXEC SP_EXECUTESQL @DTSQL
  
  --SET @DTSQL=N'SELECT ISNULL(UPC.ORDER_ID ,ORD.ORDER_ID ) AS ORDER_ID,
  --       BO.AC_CODE,LM.AC_NAME ,    
  --       BO.ORDER_NO,BO.ORDER_DT , 
  --       ART.ARTICLE_NO ,   
  --       A.PARA1_CODE ,P1.PARA1_NAME ,    
  --       A.PARA2_CODE ,P2.PARA2_NAME ,    
  --       MST.MEMO_NO AS WO_NO,    
  --       MST.MEMO_DT AS WO_DT ,    
  --       A.PRODUCT_CODE,
  --       A.QTY AS QUANTITY,
  --       CAST(PMT.QUANTITY_IN_STOCK AS NUMERIC(10,0)) AS QUANTITY_IN_STOCK ,
  --       A.WIP_PRODUCT_CODE,
  --       B.MEMO_DT AS TTM_DT,
  --       B.MEMO_NO AS TTM_MEMO_NO
  --FROM PRD_TRANSFER_MAIN_DET A
  --JOIN PRD_TRANSFER_MAIN_MST B ON A.MEMO_ID =B.MEMO_ID
  --JOIN PARA1 P1 ON P1.PARA1_CODE=A.PARA1_CODE     
  --JOIN PARA2 P2 ON P2.PARA2_CODE =A.PARA2_CODE 
  --JOIN ARTICLE ART ON ART.ARTICLE_CODE=A.ARTICLE_CODE 
  --JOIN PMT01106 PMT ON PMT.PRODUCT_CODE =A.PRODUCT_CODE 
  --JOIN PRD_WO_MST MST ON MST.MEMO_ID=A.REF_PRD_WORKORDER_MEMOID   
  --LEFT OUTER JOIN PRD_UPCPMT UPC ON UPC.PRODUCT_CODE =A.WIP_PRODUCT_CODE 
  --LEFT OUTER JOIN PRD_WO_ORDERS ORD ON ORD.MEMO_ID =A.REF_PRD_WORKORDER_MEMOID 
  --LEFT OUTER JOIN BUYER_ORDER_MST BO ON BO.ORDER_ID= ISNULL(UPC.ORDER_ID ,ORD.ORDER_ID )
  --LEFT  JOIN LM01106 LM ON LM.AC_CODE =BO.AC_CODE 
  --WHERE B.CANCELLED =0
  --AND  B.MEMO_DT BETWEEN  '''+CONVERT(VARCHAR,@DFM_DT,121)+''' AND '''+CONVERT(VARCHAR,@DTODT,121)+'''
  --AND ('''+RTRIM(LTRIM(STR(@NQTY_SKT)))+'''=0 OR  PMT.QUANTITY_IN_STOCK>0  ) 
  --AND ('''+RTRIM(LTRIM(@CAC_STATUS))+'''='''' OR BO.AC_CODE '+@CAC_CODE+')  '
  --PRINT @DTSQL
  --EXEC SP_EXECUTESQL @DTSQL
    
 -- WHERE  
 -- ---    
      
 -- SELECT A.ORDER_ID ,BO.AC_CODE,LM.AC_NAME ,    
 --        BO.ORDER_NO,BO.ORDER_DT , 
 --        ART.ARTICLE_NO ,   
 --        A.PARA1_CODE ,P1.PARA1_NAME ,    
 --        A.PARA2_CODE ,P2.PARA2_NAME ,    
 --        MST.MEMO_NO AS WO_NO,    
 --        MST.MEMO_DT AS WO_DT ,    
 --        B.PRODUCT_CODE,
 --        A.QUANTITY,
 --        CAST(PMT.QUANTITY_IN_STOCK AS NUMERIC(10,0)) AS QUANTITY_IN_STOCK
 --FROM #TMPTTT A    
 -- JOIN 
 -- (
	--  SELECT B.MEMO_ID,  B.REF_PRD_WORKORDER_MEMOID ,B.ARTICLE_CODE,B.PARA1_CODE,B.PARA2_CODE ,B.PRODUCT_CODE,
	--        SR=ROW_NUMBER () OVER (PARTITION BY  B.MEMO_ID,  B.REF_PRD_WORKORDER_MEMOID ,B.ARTICLE_CODE,B.PARA1_CODE,B.PARA2_CODE
	--        ORDER BY B.MEMO_ID,  B.REF_PRD_WORKORDER_MEMOID ,B.ARTICLE_CODE,B.PARA1_CODE,B.PARA2_CODE )
	--  FROM PRD_TRANSFER_MAIN_DET B
	 
 -- ) B   
 --  ON A.MEMO_ID =B.MEMO_ID AND A.WO_ID =B.REF_PRD_WORKORDER_MEMOID     
 -- AND A.ARTICLE_CODE =B.ARTICLE_CODE AND A.PARA1_CODE =B.PARA1_CODE AND A.PARA2_CODE =B.PARA2_CODE 
 -- AND A.QTYSR =B.SR 
 -- JOIN PMT01106 PMT ON PMT.PRODUCT_CODE =B.PRODUCT_CODE     
 -- JOIN BUYER_ORDER_MST BO ON BO.ORDER_ID=A.ORDER_ID     
 -- JOIN PRD_WO_MST MST ON MST.MEMO_ID=A.WO_ID     
 -- JOIN PARA1 P1 ON P1.PARA1_CODE=A.PARA1_CODE     
 -- JOIN PARA2 P2 ON P2.PARA2_CODE =A.PARA2_CODE     
 -- JOIN ARTICLE ART ON ART.ARTICLE_CODE=A.ARTICLE_CODE    
 -- JOIN LM01106 LM ON LM.AC_CODE =BO.AC_CODE 
 -- WHERE (@@NQTY_SKT=0 OR  PMT.QUANTITY_IN_STOCK>0  )   
 ---- WHERE PMT.QUANTITY_IN_STOCK>0    
  
END
