CREATE PROCEDURE SP3S_CUST_ATTRIBUTES
(
	@nQueryID		INT,
	@nAttr_No		VARCHAR(50),
	@cWhere			NVARCHAR(MAX)=''
)
AS
BEGIN
	IF @nQueryID=1
	BEGIN
		SELECT UPPER(TABLE_NAME) AS TABLE_NAME,
		UPPER((CASE WHEN ISNULL(TABLE_CAPTION,'')<>'' THEN ISNULL(TABLE_CAPTION,'') ELSE REPLACE(TABLE_NAME,'_MST','') END)) AS TABLE_CAPTION 
		,OPEN_KEY
		FROM CONFIG_CUST_ATTR (NOLOCK)
		WHERE ISNULL(TABLE_CAPTION,'')<>''
		ORDER BY CAST(REPLACE(REPLACE(TABLE_NAME,'CUST_ATTR',''),'_MST','') AS INT) 
	END
	ELSE IF @nQueryID=2
	BEGIN
		SELECT 'CUST_ATTR1_MST'AS TABLE_NAME,CUST_ATTR1_key_name AS KEY_NAME,CUST_ATTR1_key_code AS KEY_CODE ,CUST_ATTR1_alias AS KEY_ALIAS,ISNULL(CUST_ATTR1_inactive,0) AS INACTIVE  
		FROM CUST_ATTR1_MST (NOLOCK) WHERE ISNULL(CUST_ATTR1_KEY_NAME,'')<>'' AND 'CUST_ATTR1_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR2_MST'AS TABLE_NAME,CUST_ATTR2_key_name AS KEY_NAME,CUST_ATTR2_key_code AS KEY_CODE  ,CUST_ATTR2_alias AS KEY_ALIAS,CUST_ATTR2_inactive AS INACTIVE  
		FROM CUST_ATTR2_MST (NOLOCK) WHERE ISNULL(CUST_ATTR2_KEY_NAME,'')<>'' AND  'CUST_ATTR2_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR3_MST'AS TABLE_NAME,CUST_ATTR3_key_name AS KEY_NAME,CUST_ATTR3_key_code AS KEY_CODE  ,CUST_ATTR3_alias AS KEY_ALIAS,CUST_ATTR3_inactive AS INACTIVE  
		FROM CUST_ATTR3_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR3_KEY_NAME,'')<>'' AND  'CUST_ATTR3_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR4_MST'AS TABLE_NAME,CUST_ATTR4_key_name AS KEY_NAME,CUST_ATTR4_key_code AS KEY_CODE  ,CUST_ATTR4_alias AS KEY_ALIAS,CUST_ATTR4_inactive AS INACTIVE  
		FROM CUST_ATTR4_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR4_KEY_NAME,'')<>'' AND  'CUST_ATTR4_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR5_MST'AS TABLE_NAME,CUST_ATTR5_key_name AS KEY_NAME,CUST_ATTR5_key_code AS KEY_CODE  ,CUST_ATTR5_alias AS KEY_ALIAS,CUST_ATTR5_inactive AS INACTIVE  
		FROM CUST_ATTR5_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR5_KEY_NAME,'')<>'' AND  'CUST_ATTR5_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR6_MST'AS TABLE_NAME,CUST_ATTR6_key_name AS KEY_NAME,CUST_ATTR6_key_code AS KEY_CODE  ,CUST_ATTR6_alias AS KEY_ALIAS,CUST_ATTR6_inactive AS INACTIVE  
		FROM CUST_ATTR6_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR6_KEY_NAME,'')<>'' AND  'CUST_ATTR6_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR7_MST'AS TABLE_NAME,CUST_ATTR7_key_name AS KEY_NAME,CUST_ATTR7_key_code AS KEY_CODE  ,CUST_ATTR7_alias AS KEY_ALIAS,CUST_ATTR7_inactive AS INACTIVE  
		FROM CUST_ATTR7_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR7_KEY_NAME,'')<>'' AND  'CUST_ATTR7_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR8_MST'AS TABLE_NAME,CUST_ATTR8_key_name AS KEY_NAME,CUST_ATTR8_key_code AS KEY_CODE  ,CUST_ATTR8_alias AS KEY_ALIAS,CUST_ATTR8_inactive AS INACTIVE  
		FROM CUST_ATTR8_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR8_KEY_NAME,'')<>'' AND  'CUST_ATTR8_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR9_MST'AS TABLE_NAME,CUST_ATTR9_key_name AS KEY_NAME,CUST_ATTR9_key_code AS KEY_CODE  ,CUST_ATTR9_alias AS KEY_ALIAS,CUST_ATTR9_inactive AS INACTIVE  
		FROM CUST_ATTR9_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR9_KEY_NAME,'')<>'' AND  'CUST_ATTR9_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR10_MST'AS TABLE_NAME,CUST_ATTR10_key_name AS KEY_NAME,CUST_ATTR10_key_code AS KEY_CODE  ,CUST_ATTR10_alias AS KEY_ALIAS,CUST_ATTR10_inactive AS INACTIVE  
		FROM CUST_ATTR10_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR10_KEY_NAME,'')<>'' AND  'CUST_ATTR10_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR11_MST'AS TABLE_NAME,CUST_ATTR11_key_name AS KEY_NAME,CUST_ATTR11_key_code AS KEY_CODE  ,CUST_ATTR11_alias AS KEY_ALIAS,CUST_ATTR11_inactive AS INACTIVE  
		FROM CUST_ATTR11_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR11_KEY_NAME,'')<>'' AND  'CUST_ATTR11_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR12_MST'AS TABLE_NAME,CUST_ATTR12_key_name AS KEY_NAME,CUST_ATTR12_key_code AS KEY_CODE  ,CUST_ATTR12_alias AS KEY_ALIAS,CUST_ATTR12_inactive AS INACTIVE 
		FROM CUST_ATTR12_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR12_KEY_NAME,'')<>'' AND  'CUST_ATTR12_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR13_MST'AS TABLE_NAME,CUST_ATTR13_key_name AS KEY_NAME,CUST_ATTR13_key_code AS KEY_CODE  , CUST_ATTR13_alias AS KEY_ALIAS,CUST_ATTR13_inactive AS INACTIVE  
		FROM CUST_ATTR13_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR13_KEY_NAME,'')<>'' AND  'CUST_ATTR13_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR14_MST'AS TABLE_NAME,CUST_ATTR14_key_name AS KEY_NAME,CUST_ATTR14_key_code AS KEY_CODE  ,CUST_ATTR14_alias AS KEY_ALIAS,CUST_ATTR14_inactive AS INACTIVE  
		FROM CUST_ATTR14_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR14_KEY_NAME,'')<>'' AND  'CUST_ATTR14_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR15_MST'AS TABLE_NAME,CUST_ATTR15_key_name AS KEY_NAME,CUST_ATTR15_key_code AS KEY_CODE  ,CUST_ATTR15_alias AS KEY_ALIAS,CUST_ATTR15_inactive AS INACTIVE  
		FROM CUST_ATTR15_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR15_KEY_NAME,'')<>'' AND  'CUST_ATTR15_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR16_MST'AS TABLE_NAME,CUST_ATTR16_key_name AS KEY_NAME,CUST_ATTR16_key_code AS KEY_CODE  ,  CUST_ATTR16_alias AS KEY_ALIAS,CUST_ATTR16_inactive AS INACTIVE  
		FROM CUST_ATTR16_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR16_KEY_NAME,'')<>'' AND  'CUST_ATTR16_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR17_MST'AS TABLE_NAME,CUST_ATTR17_key_name AS KEY_NAME,CUST_ATTR17_key_code AS KEY_CODE  ,CUST_ATTR17_alias AS KEY_ALIAS,CUST_ATTR17_inactive AS INACTIVE
		FROM CUST_ATTR17_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR17_KEY_NAME,'')<>'' AND  'CUST_ATTR17_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR18_MST'AS TABLE_NAME,CUST_ATTR18_key_name AS KEY_NAME,CUST_ATTR18_key_code AS KEY_CODE  ,  CUST_ATTR18_alias AS KEY_ALIAS,CUST_ATTR18_inactive AS INACTIVE 
		FROM CUST_ATTR18_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR18_KEY_NAME,'')<>'' AND  'CUST_ATTR18_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR19_MST'AS TABLE_NAME,CUST_ATTR19_key_name AS KEY_NAME,CUST_ATTR19_key_code AS KEY_CODE  , CUST_ATTR19_alias AS KEY_ALIAS,CUST_ATTR19_inactive AS INACTIVE
		FROM CUST_ATTR19_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR19_KEY_NAME,'')<>'' AND  'CUST_ATTR19_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR20_MST'AS TABLE_NAME,CUST_ATTR20_key_name AS KEY_NAME,CUST_ATTR20_key_code AS KEY_CODE  ,  CUST_ATTR20_alias AS KEY_ALIAS,CUST_ATTR20_inactive AS INACTIVE  
		FROM CUST_ATTR20_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR20_KEY_NAME,'')<>'' AND  'CUST_ATTR20_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR21_MST'AS TABLE_NAME,CUST_ATTR21_key_name AS KEY_NAME,CUST_ATTR21_key_code AS KEY_CODE  ,CUST_ATTR21_alias AS KEY_ALIAS,CUST_ATTR21_inactive AS INACTIVE 
		FROM CUST_ATTR21_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR21_KEY_NAME,'')<>'' AND  'CUST_ATTR21_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR22_MST'AS TABLE_NAME,CUST_ATTR22_key_name AS KEY_NAME,CUST_ATTR22_key_code AS KEY_CODE , CUST_ATTR22_alias AS KEY_ALIAS,CUST_ATTR22_inactive AS INACTIVE 
		FROM CUST_ATTR22_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR22_KEY_NAME,'')<>'' AND  'CUST_ATTR22_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR23_MST'AS TABLE_NAME,CUST_ATTR23_key_name AS KEY_NAME,CUST_ATTR23_key_code AS KEY_CODE ,CUST_ATTR23_alias AS KEY_ALIAS,CUST_ATTR23_inactive AS INACTIVE  
		FROM CUST_ATTR23_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR23_KEY_NAME,'')<>'' AND  'CUST_ATTR23_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR24_MST'AS TABLE_NAME,CUST_ATTR24_key_name AS KEY_NAME,CUST_ATTR24_key_code AS KEY_CODE ,CUST_ATTR24_alias AS KEY_ALIAS,CUST_ATTR24_inactive AS INACTIVE  
		FROM CUST_ATTR24_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR24_KEY_NAME,'')<>'' AND  'CUST_ATTR24_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR25_MST'AS TABLE_NAME,CUST_ATTR25_key_name AS KEY_NAME,CUST_ATTR25_key_code AS KEY_CODE ,CUST_ATTR25_alias AS KEY_ALIAS,CUST_ATTR25_inactive AS INACTIVE  
		FROM CUST_ATTR25_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR25_KEY_NAME,'')<>'' AND  'CUST_ATTR25_MST'=@nAttr_No
	END
	ELSE IF @nQueryID=3
	BEGIN
		SELECT CAST((CASE WHEN ISNULL(TABLE_CAPTION,'')<>'' THEN 1 ELSE 0 END) AS BIT) AS CHK, UPPER(TABLE_NAME) AS CONFIG_OPTION,
		UPPER((CASE WHEN ISNULL(TABLE_CAPTION,'')<>'' THEN ISNULL(TABLE_CAPTION,'') ELSE '' END)) AS VALUE,NEWID() ROW_ID, 
		GETDATE() last_update,'' dept_id,'' REMARKS,'Attribute'+LTRIM(RTRIM(REPLACE(REPLACE(TABLE_NAME,'ATTR',''),'_MST',''))) AS Attr_Name
		FROM CONFIG_CUST_ATTR (NOLOCK)
		ORDER BY CAST(REPLACE(REPLACE(TABLE_NAME,'CUST_ATTR',''),'_MST','') AS INT) 
	END
	ELSE IF @nQueryID=4
	BEGIN  
		SELECT A.*
		,A1.CUST_ATTR1_KEY_NAME,A2.CUST_ATTR2_KEY_NAME,A3.CUST_ATTR3_KEY_NAME,A4.CUST_ATTR4_KEY_NAME,A5.CUST_ATTR5_KEY_NAME
		,A6.CUST_ATTR6_KEY_NAME,A7.CUST_ATTR7_KEY_NAME,A8.CUST_ATTR8_KEY_NAME,A9.CUST_ATTR9_KEY_NAME,A10.CUST_ATTR10_KEY_NAME
		,A11.CUST_ATTR11_KEY_NAME,A12.CUST_ATTR12_KEY_NAME,A13.CUST_ATTR13_KEY_NAME,A14.CUST_ATTR14_KEY_NAME,A15.CUST_ATTR15_KEY_NAME
		,A16.CUST_ATTR16_KEY_NAME,A17.CUST_ATTR17_KEY_NAME,A18.CUST_ATTR18_KEY_NAME,A19.CUST_ATTR19_KEY_NAME,A20.CUST_ATTR20_KEY_NAME
		,A21.CUST_ATTR21_KEY_NAME,A22.CUST_ATTR22_KEY_NAME,A23.CUST_ATTR23_KEY_NAME,A24.CUST_ATTR24_KEY_NAME,A25.CUST_ATTR25_KEY_NAME
		FROM CUSTOMER_FIX_ATTR A (NOLOCK)
		JOIN CUST_ATTR1_mst A1 (NOLOCK) ON A1.CUST_ATTR1_key_code=A.CUST_ATTR1_key_code
		JOIN CUST_ATTR2_mst A2 (NOLOCK) ON A2.CUST_ATTR2_key_code=A.CUST_ATTR2_key_code
		JOIN CUST_ATTR3_mst A3 (NOLOCK) ON A3.CUST_ATTR3_key_code=A.CUST_ATTR3_key_code
		JOIN CUST_ATTR4_mst A4 (NOLOCK) ON A4.CUST_ATTR4_key_code=A.CUST_ATTR4_key_code
		JOIN CUST_ATTR5_mst A5 (NOLOCK) ON A5.CUST_ATTR5_key_code=A.CUST_ATTR5_key_code
		JOIN CUST_ATTR6_mst A6 (NOLOCK) ON A6.CUST_ATTR6_key_code=A.CUST_ATTR6_key_code
		JOIN CUST_ATTR7_mst A7 (NOLOCK) ON A7.CUST_ATTR7_key_code=A.CUST_ATTR7_key_code
		JOIN CUST_ATTR8_mst A8 (NOLOCK) ON A8.CUST_ATTR8_key_code=A.CUST_ATTR8_key_code
		JOIN CUST_ATTR9_mst A9 (NOLOCK) ON A9.CUST_ATTR9_key_code=A.CUST_ATTR9_key_code
		JOIN CUST_ATTR10_mst A10 (NOLOCK) ON A10.CUST_ATTR10_key_code=A.CUST_ATTR10_key_code
		JOIN CUST_ATTR11_mst A11 (NOLOCK) ON A11.CUST_ATTR11_key_code=A.CUST_ATTR11_key_code
		JOIN CUST_ATTR12_mst A12 (NOLOCK) ON A12.CUST_ATTR12_key_code=A.CUST_ATTR12_key_code
		JOIN CUST_ATTR13_mst A13 (NOLOCK) ON A13.CUST_ATTR13_key_code=A.CUST_ATTR13_key_code
		JOIN CUST_ATTR14_mst A14 (NOLOCK) ON A14.CUST_ATTR14_key_code=A.CUST_ATTR14_key_code
		JOIN CUST_ATTR15_mst A15 (NOLOCK) ON A15.CUST_ATTR15_key_code=A.CUST_ATTR15_key_code
		JOIN CUST_ATTR16_mst A16 (NOLOCK) ON A16.CUST_ATTR16_key_code=A.CUST_ATTR16_key_code
		JOIN CUST_ATTR17_mst A17 (NOLOCK) ON A17.CUST_ATTR17_key_code=A.CUST_ATTR17_key_code
		JOIN CUST_ATTR18_mst A18 (NOLOCK) ON A18.CUST_ATTR18_key_code=A.CUST_ATTR18_key_code
		JOIN CUST_ATTR19_mst A19 (NOLOCK) ON A19.CUST_ATTR19_key_code=A.CUST_ATTR19_key_code
		JOIN CUST_ATTR20_mst A20 (NOLOCK) ON A20.CUST_ATTR20_key_code=A.CUST_ATTR20_key_code
		JOIN CUST_ATTR21_mst A21 (NOLOCK) ON A21.CUST_ATTR21_key_code=A.CUST_ATTR21_key_code
		JOIN CUST_ATTR22_mst A22 (NOLOCK) ON A22.CUST_ATTR22_key_code=A.CUST_ATTR22_key_code
		JOIN CUST_ATTR23_mst A23 (NOLOCK) ON A23.CUST_ATTR23_key_code=A.CUST_ATTR23_key_code
		JOIN CUST_ATTR24_mst A24 (NOLOCK) ON A24.CUST_ATTR24_key_code=A.CUST_ATTR24_key_code
		JOIN CUST_ATTR25_mst A25 (NOLOCK) ON A25.CUST_ATTR25_key_code=A.CUST_ATTR25_key_code  
		WHERE A.customer_code=@nAttr_No           
	END    
	--ELSE IF @nQueryID=5
	--BEGIN
	--	DECLARE @cCMD NVARCHAR(MAX)
	--	SET @cCMD=N'SELECT CAST(ISNULL('+@nAttr_No+',0) AS BIT) as [chk],B.SUB_SECTION_CODE,C.SECTION_CODE, c.section_name,b.sub_section_name,a.*
	--	FROM SECTIOND B(NOLOCK) 
	--	JOIN SECTIONM C(NOLOCK) ON B.SECTION_CODE=C.SECTION_CODE
	--	LEFT OUTER JOIN SD_ATTR_AVATAR A (NOLOCK) ON B.SUB_SECTION_CODE=A.SUB_SECTION_CODE
	--	WHERE B.SUB_SECTION_NAME<>''''
	--	ORDER BY ISNULL('+@nAttr_No+',0) DESC'
	--	PRINT @cCMD
	--	EXEC SP_EXECUTESQL @cCMD
	--END		
	ELSE IF @nQueryID=6
	BEGIN
		SELECT TOP 1 UPPER(TABLE_NAME) AS TABLE_NAME,
		UPPER((CASE WHEN ISNULL(TABLE_CAPTION,'')<>'' THEN ISNULL(TABLE_CAPTION,'') ELSE REPLACE(TABLE_NAME,'_MST','') END)) AS TABLE_CAPTION 
		FROM CONFIG_CUST_ATTR (NOLOCK)
		WHERE ISNULL(TABLE_CAPTION,'')=''
		ORDER BY CAST(REPLACE(REPLACE(TABLE_NAME,'CUST_ATTR',''),'_MST','') AS INT) 
	END
	ELSE IF @nQueryID=7
	BEGIN
		SELECT * FROM 
		( 
		SELECT 'CUST_ATTR1_MST'AS TABLE_NAME,CUST_ATTR1_key_name AS KEY_NAME,CUST_ATTR1_key_code AS KEY_CODE 
		FROM CUST_ATTR1_MST (NOLOCK) WHERE ISNULL(CUST_ATTR1_KEY_NAME,'')<>'' AND  'CUST_ATTR1_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR2_MST'AS TABLE_NAME,CUST_ATTR2_key_name AS KEY_NAME,CUST_ATTR2_key_code AS KEY_CODE 
		FROM CUST_ATTR2_MST (NOLOCK) WHERE ISNULL(CUST_ATTR2_KEY_NAME,'')<>'' AND  'CUST_ATTR2_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR3_MST'AS TABLE_NAME,CUST_ATTR3_key_name AS KEY_NAME,CUST_ATTR3_key_code AS KEY_CODE 
		FROM CUST_ATTR3_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR3_KEY_NAME,'')<>'' AND  'CUST_ATTR3_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR4_MST'AS TABLE_NAME,CUST_ATTR4_key_name AS KEY_NAME,CUST_ATTR4_key_code AS KEY_CODE 
		FROM CUST_ATTR4_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR4_KEY_NAME,'')<>'' AND  'CUST_ATTR4_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR5_MST'AS TABLE_NAME,CUST_ATTR5_key_name AS KEY_NAME,CUST_ATTR5_key_code AS KEY_CODE 
		FROM CUST_ATTR5_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR5_KEY_NAME,'')<>'' AND  'CUST_ATTR5_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR6_MST'AS TABLE_NAME,CUST_ATTR6_key_name AS KEY_NAME,CUST_ATTR6_key_code AS KEY_CODE 
		FROM CUST_ATTR6_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR6_KEY_NAME,'')<>'' AND  'CUST_ATTR6_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR7_MST'AS TABLE_NAME,CUST_ATTR7_key_name AS KEY_NAME,CUST_ATTR7_key_code AS KEY_CODE 
		FROM CUST_ATTR7_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR7_KEY_NAME,'')<>'' AND  'CUST_ATTR7_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR8_MST'AS TABLE_NAME,CUST_ATTR8_key_name AS KEY_NAME,CUST_ATTR8_key_code AS KEY_CODE 
		FROM CUST_ATTR8_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR8_KEY_NAME,'')<>'' AND  'CUST_ATTR8_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR9_MST'AS TABLE_NAME,CUST_ATTR9_key_name AS KEY_NAME,CUST_ATTR9_key_code AS KEY_CODE 
		FROM CUST_ATTR9_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR9_KEY_NAME,'')<>'' AND  'CUST_ATTR9_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR10_MST'AS TABLE_NAME,CUST_ATTR10_key_name AS KEY_NAME,CUST_ATTR10_key_code AS KEY_CODE 
		FROM CUST_ATTR10_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR10_KEY_NAME,'')<>'' AND  'CUST_ATTR10_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR11_MST'AS TABLE_NAME,CUST_ATTR11_key_name AS KEY_NAME,CUST_ATTR11_key_code AS KEY_CODE 
		FROM CUST_ATTR11_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR11_KEY_NAME,'')<>'' AND  'CUST_ATTR11_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR12_MST'AS TABLE_NAME,CUST_ATTR12_key_name AS KEY_NAME,CUST_ATTR12_key_code AS KEY_CODE 
		FROM CUST_ATTR12_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR12_KEY_NAME,'')<>'' AND  'CUST_ATTR12_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR13_MST'AS TABLE_NAME,CUST_ATTR13_key_name AS KEY_NAME,CUST_ATTR13_key_code AS KEY_CODE 
		FROM CUST_ATTR13_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR13_KEY_NAME,'')<>'' AND  'CUST_ATTR13_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR14_MST'AS TABLE_NAME,CUST_ATTR14_key_name AS KEY_NAME,CUST_ATTR14_key_code AS KEY_CODE 
		FROM CUST_ATTR14_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR14_KEY_NAME,'')<>'' AND  'CUST_ATTR14_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR15_MST'AS TABLE_NAME,CUST_ATTR15_key_name AS KEY_NAME,CUST_ATTR15_key_code AS KEY_CODE 
		FROM CUST_ATTR15_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR15_KEY_NAME,'')<>'' AND  'CUST_ATTR15_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR16_MST'AS TABLE_NAME,CUST_ATTR16_key_name AS KEY_NAME,CUST_ATTR16_key_code AS KEY_CODE 
		FROM CUST_ATTR16_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR16_KEY_NAME,'')<>'' AND  'CUST_ATTR16_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR17_MST'AS TABLE_NAME,CUST_ATTR17_key_name AS KEY_NAME,CUST_ATTR17_key_code AS KEY_CODE 
		FROM CUST_ATTR17_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR17_KEY_NAME,'')<>'' AND  'CUST_ATTR17_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR18_MST'AS TABLE_NAME,CUST_ATTR18_key_name AS KEY_NAME,CUST_ATTR18_key_code AS KEY_CODE 
		FROM CUST_ATTR18_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR18_KEY_NAME,'')<>'' AND  'CUST_ATTR18_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR19_MST'AS TABLE_NAME,CUST_ATTR19_key_name AS KEY_NAME,CUST_ATTR19_key_code AS KEY_CODE 
		FROM CUST_ATTR19_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR19_KEY_NAME,'')<>'' AND  'CUST_ATTR19_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR20_MST'AS TABLE_NAME,CUST_ATTR20_key_name AS KEY_NAME,CUST_ATTR20_key_code AS KEY_CODE 
		FROM CUST_ATTR20_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR20_KEY_NAME,'')<>'' AND  'CUST_ATTR20_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR21_MST'AS TABLE_NAME,CUST_ATTR21_key_name AS KEY_NAME,CUST_ATTR21_key_code AS KEY_CODE 
		FROM CUST_ATTR21_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR21_KEY_NAME,'')<>'' AND  'CUST_ATTR21_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR22_MST'AS TABLE_NAME,CUST_ATTR22_key_name AS KEY_NAME,CUST_ATTR22_key_code AS KEY_CODE 
		FROM CUST_ATTR22_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR22_KEY_NAME,'')<>'' AND  'CUST_ATTR22_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR23_MST'AS TABLE_NAME,CUST_ATTR23_key_name AS KEY_NAME,CUST_ATTR23_key_code AS KEY_CODE 
		FROM CUST_ATTR23_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR23_KEY_NAME,'')<>'' AND  'CUST_ATTR23_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR24_MST'AS TABLE_NAME,CUST_ATTR24_key_name AS KEY_NAME,CUST_ATTR24_key_code AS KEY_CODE 
		FROM CUST_ATTR24_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR24_KEY_NAME,'')<>'' AND  'CUST_ATTR24_MST'=@nAttr_No
		UNION
		SELECT 'CUST_ATTR25_MST'AS TABLE_NAME,CUST_ATTR25_key_name AS KEY_NAME,CUST_ATTR25_key_code AS KEY_CODE 
		FROM CUST_ATTR25_MST  (NOLOCK) WHERE ISNULL(CUST_ATTR25_KEY_NAME,'')<>'' AND  'CUST_ATTR25_MST'=@nAttr_No
		)X
		WHERE X.KEY_NAME LIKE @cWhere
	END
	--ELSE IF @nQueryID=8
	--BEGIN
	--	SELECT C.SECTION_CODE, c.section_name,b.sub_section_name,a.*
	--	FROM SECTIOND B(NOLOCK) 
	--	JOIN SECTIONM C(NOLOCK) ON B.SECTION_CODE=C.SECTION_CODE
	--	JOIN SD_ATTR_AVATAR A (NOLOCK) ON B.SUB_SECTION_CODE=A.SUB_SECTION_CODE
	--	WHERE B.SUB_SECTION_CODE=@cWhere
	--END		
END	

