CREATE PROC SP3S_UPLOAD_REPORTFILE
AS
BEGIN
SELECT  MODULE_NAME,REPORT_NAME,G_REPORT_FILE,MODIFY_DT FROM REPORTS (NOLOCK)
WHERE G_REPORT_FILE <> '' AND UDRF <> 1 
AND MODULE_NAME NOT IN  ('FIXREPORTS_BETA','FIXREPORTS')
AND (G_REPORT_FILE NOT LIKE '%.XML%' AND G_REPORT_FILE NOT LIKE '%.TXT%')
END
