CREATE PROCEDURE SP_MERGE_MIRROR_WPS_DATA
(
	@CMEMOID VARCHAR(50)
   ,@CLOCID VARCHAR(3)
   ,@CSOURCEDB VARCHAR(200)
   ,@CMERGEDB VARCHAR(200)
   ,@BMSTINSERTONLY BIT
   ,@CERRMSG VARCHAR(1000) OUTPUT
)
--WITH ENCRYPTION
AS
SET NOCOUNT ON
BEGIN
	/*
		SP_MERGE_MIRROR_WPS_DATA_208_2014_01_29 : THIS PROCEDURE WILL MERGE DATA FROM TEMPORARY TABLE TO ACTUAL TABLE.
												  TABLE NAMES AND ITS MERGING ORDER WILL BE FIXED AND WILL BE 
												  DEFINED HERE.	
						 
		NOTE : EMP_HEAD WILL BE MERGED TO EMPLOYEE				 
	*/
DECLARE @CSTEP VARCHAR(100),@DTSQL NVARCHAR(MAX),@NMERGE_ORDER NUMERIC(5)
	   ,@CTABLENAME VARCHAR(200),@CTABLE_SUFFIX VARCHAR(50),@CKEYFIELD VARCHAR(200),@CDEL_ID VARCHAR(50),@CTMP_TABLENAME VARCHAR(200),@LINSERTONLY VARCHAR(1)
	   ,@CFILTERCONDITION VARCHAR(200),@LUPDATEONLY VARCHAR(1),@BALWAYSUPDATE VARCHAR(1),@FDEL CHAR(1)
	   ,@CERRMSGOUT VARCHAR(1000),@CTABLESSTR VARCHAR(MAX),@CTEMPTABLE VARCHAR(100)
		
BEGIN TRY

	SET @CSTEP=10
	SET @CTABLE_SUFFIX=REPLACE(@CMEMOID,'-','_')
	
	BEGIN TRANSACTION 
	
	SET @CSTEP=20
	

	
	SET @CSTEP=50
	SET @CTABLENAME='WPS_DET'
	SET @CTMP_TABLENAME='TMP_WPS_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))
	SET @CTEMPTABLE=@CSOURCEDB+@CTMP_TABLENAME
	SET @CKEYFIELD='PS_ID'
	SET @CSTEP=60

	SET @DTSQL=N'IF OBJECT_ID('''+@CTEMPTABLE+''',''U'') IS NOT NULL
						DELETE A FROM '+@CMERGEDB+'['+@CTABLENAME+'] A WITH (ROWLOCK) LEFT OUTER JOIN
					'+@CTEMPTABLE+' B (NOLOCK) ON A.ROW_ID=B.ROW_ID  WHERE A.'+@CKEYFIELD+'='''+@CMEMOID+'''
				    AND B.ROW_ID IS NULL
				 ELSE
					DELETE FROM '+@CMERGEDB+'['+@CTABLENAME+'] WITH (ROWLOCK) WHERE '+@CKEYFIELD+'='''+@CMEMOID+''''   
				    
	PRINT @DTSQL
	EXEC SP_EXECUTESQL @DTSQL
	
	SET @CSTEP=70
	SET @CTABLENAME='STATE'
	SET @CTMP_TABLENAME='TMP_WPS_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))
	SET @CKEYFIELD='STATE_CODE'
	SET @CSTEP=80
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=@BMSTINSERTONLY,@CFILTERCONDITION='',@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1 
	SET @CSTEP=110 	
	SET @CTABLENAME='CITY'
	SET @CTMP_TABLENAME='TMP_WPS_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))
	SET @CKEYFIELD='CITY_CODE'
	SET @CSTEP=120
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=@BMSTINSERTONLY,@CFILTERCONDITION='',@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1 
	SET @CSTEP=130
	SET @CTABLENAME='AREA'
	SET @CTMP_TABLENAME='TMP_WPS_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))
	SET @CKEYFIELD='AREA_CODE'
	SET @CSTEP=140
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=@BMSTINSERTONLY,@CFILTERCONDITION='',@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1 
	SET @CSTEP=150
	SET @CTABLENAME='HD01106'
	SET @CTMP_TABLENAME='TMP_WPS_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))
	SET @CKEYFIELD='HEAD_CODE'
	SET @CSTEP=160
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=@BMSTINSERTONLY,@CFILTERCONDITION='',@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1 
	SET @CSTEP=170
	SET @CTABLENAME='LM01106'
	SET @CTMP_TABLENAME='TMP_WPS_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))
	SET @CKEYFIELD='AC_CODE'
	SET @CSTEP=180
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=@BMSTINSERTONLY,@CFILTERCONDITION='',@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1 
	SET @CSTEP=180
	SET @CTABLENAME='LMP01106'
	SET @CTMP_TABLENAME='TMP_WPS_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))
	SET @CKEYFIELD='AC_CODE'
	SET @CSTEP=190
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=@BMSTINSERTONLY,@CFILTERCONDITION='',@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1 
	SET @CSTEP=180
	SET @CTABLENAME='FORM'
	SET @CTMP_TABLENAME='TMP_WPS_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))
	SET @CKEYFIELD='FORM_ID'
	SET @CSTEP=190
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=@BMSTINSERTONLY,@CFILTERCONDITION='',@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1 
	
	SET @CSTEP=260
	SET @CTABLENAME='EMPLOYEE'
	SET @CTMP_TABLENAME='TMP_WPS_EMP_HEAD_'+LTRIM(RTRIM(@CTABLE_SUFFIX))
	SET @CKEYFIELD='EMP_CODE'
	SET @CSTEP=270
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=1,@CFILTERCONDITION='',@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1 
	SET @CSTEP=280
	SET @CTABLENAME='EMPLOYEE'
	SET @CTMP_TABLENAME='TMP_WPS_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))
	SET @CKEYFIELD='EMP_CODE'
	SET @CSTEP=290
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=1,@CFILTERCONDITION='',@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1 

	SET @CSTEP=290
	SET @CTABLENAME='SKU'
	SET @CTMP_TABLENAME='TMP_WPS_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))
	SET @CKEYFIELD='PRODUCT_CODE'
	SET @CSTEP=310
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=@BMSTINSERTONLY,@CFILTERCONDITION='',@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1
	
	SET @CSTEP=300
	SET @CTABLENAME='WPS_MST'
	SET @CTMP_TABLENAME='TMP_WPS_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))
	SET @CKEYFIELD='PS_ID'
	SET @CSTEP=310
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=0,@CFILTERCONDITION='',@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1
							   
	SET @CSTEP=320
	SET @CTABLENAME='WPS_DET'
	SET @CTMP_TABLENAME='TMP_WPS_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))
	SET @CKEYFIELD='ROW_ID'
	SET @CSTEP=330
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=0,@CFILTERCONDITION='',@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1 

	SET @CSTEP=440
	EXEC VALIDATEXN_MIRROR_WPS @CLOCID,@CMEMOID,@CMERGEDB,@CERRMSGOUT OUTPUT
	IF ISNULL(@CERRMSGOUT,'')<>''
	BEGIN
		SET @CERRMSG='P:SP_MERGE_MIRROR_WPS_DATA, STEP:'+@CSTEP+', MESSAGE:'+@CERRMSGOUT
	END	

	SET @CSTEP=450
	
	SET @CTABLESSTR='STATE,CITY,AREA,HD01106,LM01106,LMP01106,FORM,EMPLOYEE,WPS_MST,WPS_DET,SKU,XNSTABLELIST'

    EXEC SP3S_DROPTEMPTABLES_MIRRORDATA
    @CXNTYPE='WPS',
    @CTABLESUFFIX=@CTABLE_SUFFIX,
    @CTABLESSTR=@CTABLESSTR


END TRY
BEGIN CATCH
	SET @CERRMSG='P:SP_MERGE_MIRROR_WPS_DATA, STEP:'+@CSTEP+', MESSAGE:'+ERROR_MESSAGE()
END CATCH

EXIT_PROC:
	IF ISNULL(@CERRMSG,'')='' AND @@TRANCOUNT>0
	BEGIN
		COMMIT
	END
	ELSE IF ISNULL(@CERRMSG,'')<>'' AND @@TRANCOUNT>0
		ROLLBACK
END	
---END OF PROCEDURE - SP_MERGE_MIRROR_WPS_DATA
