CREATE PROCEDURE SP_BUYERSORDER_WSL_14
@CMEMOID VARCHAR(40),  
@CWHERE VARCHAR(500),  
@CFINYEAR VARCHAR(10),  
@NNAVMODE NUMERIC(2,0),
@CARTICLECODE CHAR(9)='',  
@CPARA2CODE CHAR(7)='',
@DTWHERE DATETIME ='',
@cLocId VARCHAR(5)=''
--WITH ENCRYPTION
 
AS    
BEGIN 

	SELECT TOP 1 A.PARA1_CODE, A.PARA2_CODE, A.PARA3_CODE, A.PARA4_CODE, A.PARA5_CODE,     
	A.PARA6_CODE, P1.PARA1_NAME, P2.PARA2_NAME, P3.PARA3_NAME, P4.PARA4_NAME,     
	P5.PARA5_NAME, P6.PARA6_NAME, ART.DT_CREATED AS [ART_DT_CREATED],     
	P3.DT_CREATED AS [PARA3_DT_CREATED],ISNULL(A.DT_CREATED,'''') AS [SKU_DT_CREATED],
	ART.ALIAS AS ARTICLE_ALIAS     
	FROM SKU A (NOLOCK)     
	JOIN ARTICLE ART (NOLOCK)  ON ART.ARTICLE_CODE= A.ARTICLE_CODE     
	JOIN PARA1 P1(NOLOCK)  ON A.PARA1_CODE = P1.PARA1_CODE     
	JOIN PARA2 P2(NOLOCK)  ON A.PARA2_CODE = P2.PARA2_CODE     
	JOIN PARA3 P3(NOLOCK)  ON A.PARA3_CODE = P3.PARA3_CODE     
	JOIN PARA4 P4(NOLOCK)  ON A.PARA4_CODE = P4.PARA4_CODE     
	JOIN PARA5 P5(NOLOCK)  ON A.PARA5_CODE = P5.PARA5_CODE     
	JOIN PARA6 P6(NOLOCK)  ON A.PARA6_CODE = P6.PARA6_CODE     
	WHERE A.ARTICLE_CODE = @CWHERE 
	 
END