  --  SP3SUPDATE_LOCWISEPMTXNS 1,'LY01119000000LY-000051','PUR'
CREATE PROCEDURE SP3SUPDATE_LOCWISEPMTXNS
@NUPDATEMODE INT,
@MEMOID VARCHAR(50),
@XNTYPE VARCHAR(10)
AS  
BEGIN
	
BEGIN TRY
	DECLARE @CCMD NVARCHAR(MAX),@CXNDT VARCHAR(MAX),@CPMTTABLENAMEXNDT VARCHAR(MAX),@CSTEP VARCHAR(5),
	@DXNDT DATETIME,@FLAG BIT,@CERRMSG NVARCHAR(MAX)
	
BEGIN TRAN 	
	
	
	SET @FLAG=(CASE WHEN @NUPDATEMODE=1 THEN 1 ELSE 0 END)	
	
	
	
	
            SET @CSTEP=10
			IF @XNTYPE='PUR'
					SELECT @DXNDT=RECEIPT_DT FROM PIM01106 WHERE MRR_ID=@MEMOID
			ELSE IF @XNTYPE='PRT'
					SELECT @DXNDT=RM_DT FROM RMM01106 WHERE RM_ID=@MEMOID
			ELSE IF @XNTYPE='PRD'
					SELECT @DXNDT=MEMO_DT FROM PRD_STK_TRANSFER_DTM_MST WHERE MEMO_ID=@MEMOID
			ELSE IF @XNTYPE = 'DCO'
					SELECT @DXNDT=MEMO_DT FROM FLOOR_ST_MST WHERE MEMO_ID=@MEMOID
			ELSE IF @XNTYPE='DCI'
					SELECT @DXNDT=RECEIPT_DT FROM FLOOR_ST_MST WHERE MEMO_ID=@MEMOID
			ELSE IF @XNTYPE='DNPS'
					SELECT @DXNDT=PS_DT FROM DNPS_MST WHERE PS_ID=@MEMOID
			ELSE IF @XNTYPE='SLS'
					SELECT @DXNDT=CM_DT FROM CMM01106 WHERE CM_ID=@MEMOID
			ELSE IF @XNTYPE='RPS'
					SELECT @DXNDT=CM_DT FROM RPS_MST WHERE CM_ID=@MEMOID
			ELSE IF @XNTYPE='APP'
					SELECT @DXNDT=MEMO_DT FROM APM01106 WHERE MEMO_ID=@MEMOID
			ELSE IF @XNTYPE='APR'
					SELECT @DXNDT=MEMO_DT FROM APPROVAL_RETURN_MST WHERE MEMO_ID=@MEMOID
			ELSE IF @XNTYPE='CNC'
					SELECT @DXNDT=CNC_MEMO_DT FROM ICM01106 WHERE CNC_MEMO_ID=@MEMOID
			ELSE IF @XNTYPE='WSL'
					SELECT @DXNDT=INV_DT FROM INM01106 WHERE INV_ID=@MEMOID
			ELSE IF @XNTYPE='WPS'
					SELECT @DXNDT=PS_DT FROM WPS_MST WHERE PS_ID=@MEMOID			
			ELSE IF @XNTYPE='WSR'
					SELECT @DXNDT=CN_DT FROM CNM01106 WHERE CN_ID=@MEMOID
			ELSE IF @XNTYPE='IRR'
					SELECT @DXNDT=IRM_MEMO_DT FROM IRM01106 WHERE IRM_MEMO_ID=@MEMOID
			ELSE IF @XNTYPE='SCM'
					SELECT @DXNDT=MEMO_DT FROM SCM01106 WHERE MEMO_ID=@MEMOID
			ELSE IF @XNTYPE='CIP'
					SELECT @DXNDT=MEMO_DT FROM SCM01106 WHERE MEMO_ID=@MEMOID
			ELSE IF @XNTYPE='JWI'
					SELECT @DXNDT=ISSUE_DT FROM JOBWORK_ISSUE_MST WHERE ISSUE_ID=@MEMOID
			ELSE IF @XNTYPE='JWR'
					SELECT @DXNDT=RECEIPT_DT FROM JOBWORK_RECEIPT_MST WHERE RECEIPT_ID=@MEMOID
			ELSE IF @XNTYPE='BOC'
					SELECT @DXNDT=ORDER_DT FROM WSL_ORDER_MST WHERE ORDER_ID=@MEMOID
			ELSE IF @XNTYPE='SCF'
					SELECT @DXNDT=RECEIPT_DT FROM SNC_MST WHERE MEMO_ID=@MEMOID
			ELSE IF @XNTYPE='SNC'
					SELECT @DXNDT=RECEIPT_DT FROM SNC_MST WHERE MEMO_ID=@MEMOID
			ELSE IF @XNTYPE='GRNPSIN'
					SELECT @DXNDT=MEMO_DT FROM GRN_PS_MST WHERE MEMO_ID=@MEMOID
																							
 
 
	
	SET @CSTEP='10'	
	SET @CPMTTABLENAMEXNDT=DB_NAME()+'_PMT..PMTLOCS_'+CONVERT(VARCHAR,@DXNDT,112)
	
	
	
	IF OBJECT_ID ('TEMPDB..#TMPPMT','U') IS NOT NULL
	DROP TABLE #TMPPMT
	
	SELECT PRODUCT_CODE,DEPT_ID,QUANTITY_IN_STOCK AS QUANTITY,BIN_ID
			INTO #TMPPMT FROM PMT01106 WHERE 1=2 
	
	
	SET @CSTEP=20
	IF @NUPDATEMODE = 2
		BEGIN
		
		     INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
		     SELECT PRODUCT_CODE,DEPT_ID,Quantity_In_Stock,BIN_ID
		     FROM  LOCWISEPMTXNS WHERE MEMO_ID=@MEMOID
		
		   
			SET @CCMD= 'UPDATE A SET  CBS_QTY=CBS_QTY-B.QUANTITY
			FROM '+@CPMTTABLENAMEXNDT+' A
			JOIN #TMPPMT B ON A.PRODUCT_CODE=B.PRODUCT_CODE AND A.BIN_ID=B.BIN_ID AND A.DEPT_ID=B.DEPT_ID'
			
			 PRINT @CCMD
		    EXEC SP_EXECUTESQL  @CCMD
		    
		    TRUNCATE TABLE #TMPPMT
		    
		    
		    SET @FLAG=0
			
		END
		

		
		--SET @CSTEP=30
		--IF @NUPDATEMODE=3 
		--BEGIN
		
		--     INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
		--     SELECT PRODUCT_CODE,DEPT_ID,Quantity_In_Stock,BIN_ID
		--     FROM  LOCWISEPMTXNS WHERE MEMO_ID=@MEMOID
		
		   
		--	SET @CCMD= 'UPDATE A SET  CBS_QTY=CBS_QTY-B.XN_QTY
		--	FROM '+@CPMTTABLENAMEXNDT+' A
		--	JOIN #TMPPMT B ON A.PRODUCT_CODE=B.PRODUCT_CODE AND A.BIN_ID=B.BIN_ID AND A.DEPT_ID=B.DEPT_ID'
			
		--	PRINT @CCMD
		--    EXEC SP_EXECUTESQL  @CCMD
		    
		--    GOTO END_PROC
			
		--END
		

	    SET @CSTEP=40
	
		IF @XNTYPE='PRD'
		BEGIN
			INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT A.PRODUCT_CODE,DEPT_ID,SUM(A.QUANTITY) AS XN_QTY,'000'  AS [BIN_ID]   
			FROM PRD_STK_TRANSFER_DTM_DET  A WITH (NOLOCK)    
			JOIN PRD_STK_TRANSFER_DTM_MST B WITH (NOLOCK)   ON A.MEMO_ID = B.MEMO_ID   
			WHERE B.MEMO_ID=@MEMOID AND B.CANCELLED=0  
			GROUP BY A.PRODUCT_CODE,DEPT_ID
		END

         SET @CSTEP=50 
		IF @XNTYPE='DCO'
		BEGIN
			INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT A.PRODUCT_CODE,LEFT(A.MEMO_ID,2),SUM(A.QUANTITY)*-1 AS XN_QTY,A.SOURCE_BIN_ID  AS [BIN_ID]   
			FROM FLOOR_ST_DET  A (NOLOCK)  
			JOIN FLOOR_ST_MST B (NOLOCK) ON A.MEMO_ID  = B.MEMO_ID    
			WHERE B.MEMO_ID=@MEMOID  AND  B.CANCELLED = 0 
			GROUP BY A.PRODUCT_CODE,A.SOURCE_BIN_ID,LEFT(A.MEMO_ID,2)
		END
		 
        SET @CSTEP=60
		IF @XNTYPE='DCI'
		BEGIN
		   INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT A.PRODUCT_CODE, LEFT(B.MEMO_ID,2),SUM(A.QUANTITY) AS XN_QTY,A.ITEM_TARGET_BIN_ID  AS [BIN_ID]   
			FROM FLOOR_ST_DET  A (NOLOCK)  
			JOIN FLOOR_ST_MST B (NOLOCK) ON A.MEMO_ID  = B.MEMO_ID    
			WHERE B.MEMO_ID=@MEMOID   AND ISNULL(B.RECEIPT_DT,'''')<>'''' AND  B.CANCELLED = 0
			GROUP BY A.PRODUCT_CODE,B.TARGET_BIN_ID,A.ITEM_TARGET_BIN_ID,LEFT(B.MEMO_ID,2)
		END   
        
        SET @CSTEP=70
		IF @XNTYPE='PUR'
		BEGIN
			INSERT #TMPPMT (PRODUCT_CODE,BIN_ID,DEPT_ID,QUANTITY)
			SELECT A.PRODUCT_CODE, B.BIN_ID  AS [BIN_ID],B.DEPT_ID,SUM(A.QUANTITY) AS QUANTITY  
			FROM PID01106 A (NOLOCK)  
			JOIN PIM01106 B (NOLOCK) ON A.MRR_ID = B.MRR_ID  
			LEFT OUTER JOIN PIM01106 PIM_REF (NOLOCK) ON PIM_REF.REF_CONVERTED_MRNTOBILL_MRRID=B.MRR_ID
			WHERE B.MRR_ID=@MEMOID  AND B.CANCELLED = 0  
			AND PIM_REF.MRR_ID IS NULL
			AND (B.INV_MODE<>2 OR B.RECEIPT_DT<>'') 
			GROUP BY A.PRODUCT_CODE,B.BIN_ID,B.DEPT_ID,B.RECEIPT_DT 
		END
		
		SET @CSTEP=80
		IF @XNTYPE='PRT'
		BEGIN
		INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT A.PRODUCT_CODE,  LEFT(B.RM_ID,2),SUM(A.QUANTITY)*-1 AS XN_QTY,A.BIN_ID  AS [BIN_ID] 
			FROM RMD01106 A (NOLOCK)  
			JOIN RMM01106 B (NOLOCK) ON A.RM_ID = B.RM_ID  
			WHERE B.RM_ID=@MEMOID  AND B.CANCELLED = 0 AND B.DN_TYPE IN (0,1) 
			AND B.ENTRY_MODE<>2
			GROUP BY A.PRODUCT_CODE,A.BIN_ID,LEFT(B.RM_ID,2)
		END

        SET @CSTEP=90
		IF @XNTYPE='DNPS'
		BEGIN
			INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT A.PRODUCT_CODE,LEFT(B.PS_ID,2),SUM(A.QUANTITY)*-1 AS XN_QTY,A.BIN_ID 
			FROM DNPS_DET A (NOLOCK)
			JOIN DNPS_MST B (NOLOCK) ON A.PS_ID = B.PS_ID
			WHERE B.PS_ID=@MEMOID AND B.CANCELLED = 0 
			GROUP BY A.PRODUCT_CODE,A.BIN_ID,LEFT(B.PS_ID,2)
		END	 

		SET @CSTEP=100
		IF @XNTYPE='SLS'
		BEGIN
		   INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT A.PRODUCT_CODE,  LEFT(B.CM_ID,2),SUM(A.QUANTITY)*-1 AS XN_QTY,A.BIN_ID  AS [BIN_ID] 
			FROM CMD01106 A (NOLOCK)  
			JOIN CMM01106 B (NOLOCK) ON A.CM_ID = B.CM_ID  
			JOIN LOCATION C (NOLOCK) ON C.DEPT_ID=LEFT(B.CM_NO,2)
			WHERE B.CM_ID=@MEMOID  AND B.CANCELLED = 0   
			GROUP BY A.PRODUCT_CODE,A.BIN_ID,LEFT(B.CM_ID,2)
		END

		SET @CSTEP=110
		IF @XNTYPE='RPS'
		BEGIN
			INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT A.PRODUCT_CODE,LEFT(B.CM_ID,2),  SUM(A.QUANTITY)*-1 AS XN_QTY,A.BIN_ID  AS [BIN_ID] 
			FROM RPS_DET A (NOLOCK)  
			JOIN RPS_MST B (NOLOCK) ON A.CM_ID = B.CM_ID
			WHERE B.CM_ID=@MEMOID  AND B.CANCELLED = 0  
			AND ISNULL(B.REF_CM_ID,'')=''
			GROUP BY A.PRODUCT_CODE,A.BIN_ID,LEFT(B.CM_ID,2)
		END	

		SET @CSTEP=120
		IF @XNTYPE='APP'
		BEGIN
			INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT A.PRODUCT_CODE,LEFT(B.MEMO_ID,2),  SUM(A.QUANTITY)*-1 AS XN_QTY,A.BIN_ID  AS [BIN_ID] 
			FROM APD01106 A   
			JOIN APM01106 B (NOLOCK) ON A.MEMO_ID = B.MEMO_ID  
			WHERE B.MEMO_ID=@MEMOID   AND B.CANCELLED = 0 
			GROUP BY A.PRODUCT_CODE,A.BIN_ID,LEFT(B.MEMO_ID,2)
		END
		
		SET @CSTEP=130
		IF @XNTYPE='APR'
		BEGIN
			INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT B.PRODUCT_CODE,LEFT(C.MEMO_ID,2),SUM(A.QUANTITY) AS XN_QTY,A.BIN_ID  AS [BIN_ID]  
			FROM APPROVAL_RETURN_DET A   
			JOIN APD01106 B (NOLOCK)ON A.APD_ROW_ID = B.ROW_ID  
			JOIN APPROVAL_RETURN_MST C (NOLOCK) ON C.MEMO_ID = A.MEMO_ID  
			WHERE C.MEMO_ID=@MEMOID   AND C.CANCELLED = 0  
			GROUP BY B.PRODUCT_CODE,A.BIN_ID,LEFT(C.MEMO_ID,2)
		END	

		SET @CSTEP=140
		IF @XNTYPE='CNC'
		BEGIN
			INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT A.PRODUCT_CODE,LEFT(B.CNC_MEMO_ID,2),SUM((CASE WHEN CNC_TYPE=1 THEN -1 ELSE 1 END)*A.QUANTITY) AS XN_QTY,
			A.BIN_ID  AS [BIN_ID]  
			FROM ICD01106 A WITH (NOLOCK)    
			JOIN ICM01106 B WITH (NOLOCK)   ON B.CNC_MEMO_ID = A.CNC_MEMO_ID  
			WHERE B.CNC_MEMO_ID=@MEMOID   AND B.CANCELLED = 0  AND STOCK_ADJ_NOTE=0
			GROUP BY A.PRODUCT_CODE,A.BIN_ID,LEFT(B.CNC_MEMO_ID,2)
		END	

		SET @CSTEP=150
		IF @XNTYPE='WSL'
		BEGIN
			INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT A.PRODUCT_CODE,LEFT(B.INV_ID,2),SUM(A.QUANTITY)*-1 AS XN_QTY,A.BIN_ID  AS [BIN_ID]  
			FROM IND01106 A (NOLOCK)  
			JOIN INM01106 B (NOLOCK) ON A.INV_ID = B.INV_ID  
			WHERE B.INV_ID=@MEMOID   AND  B.CANCELLED = 0 AND B.ENTRY_MODE<>2
			GROUP BY A.PRODUCT_CODE,A.BIN_ID,LEFT(B.INV_ID,2)
		END	 

		SET @CSTEP=160
		IF @XNTYPE='WPS'
		BEGIN
			INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT A.PRODUCT_CODE,LEFT(B.PS_ID,2),SUM(A.QUANTITY)*-1 AS XN_QTY,A.BIN_ID  AS [BIN_ID]  
			FROM WPS_DET A (NOLOCK)  
			JOIN WPS_MST B (NOLOCK) ON A.PS_ID = B.PS_ID  
			WHERE B.PS_ID=@MEMOID AND B.CANCELLED = 0  
			GROUP BY A.PRODUCT_CODE,A.BIN_ID,LEFT(B.PS_ID,2)
		END	 

		SET @CSTEP=170
		IF @XNTYPE='WSR'
		BEGIN
			INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT A.PRODUCT_CODE,BILLED_FROM_DEPT_ID,SUM(A.QUANTITY) AS XN_QTY,A.BIN_ID  AS [BIN_ID] 
			FROM CND01106 A (NOLOCK)  
			JOIN CNM01106 B (NOLOCK) ON A.CN_ID = B.CN_ID  
			WHERE A.CN_ID=@MEMOID
			AND  B.CANCELLED = 0 AND B.CN_TYPE<>2  
			GROUP BY A.PRODUCT_CODE,A.BIN_ID,BILLED_FROM_DEPT_ID
		END	 

		SET @CSTEP=180
		IF @XNTYPE='IRR'
		BEGIN
			INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT A.NEW_PRODUCT_CODE, LEFT(B.IRM_MEMO_ID,2),ABS(SUM(A.QUANTITY)) AS XN_QTY,B.BIN_ID  AS [BIN_ID] 
			FROM IRD01106 A (NOLOCK)  
			JOIN IRM01106 B (NOLOCK) ON A.IRM_MEMO_ID = B.IRM_MEMO_ID  
			WHERE B.IRM_MEMO_ID=@MEMOID  AND A.NEW_PRODUCT_CODE<>''''  
			GROUP BY A.NEW_PRODUCT_CODE,B.BIN_ID,LEFT(B.IRM_MEMO_ID,2)

		UNION ALL

			SELECT A.PRODUCT_CODE,LEFT(B.IRM_MEMO_ID,2),(ABS(SUM(A.QUANTITY))*-1) AS XN_QTY,A.BIN_ID  AS [BIN_ID]     
			FROM IRD01106 A (NOLOCK)  
			JOIN IRM01106 B (NOLOCK) ON A.IRM_MEMO_ID = B.IRM_MEMO_ID  
			WHERE B.IRM_MEMO_ID=@MEMOID  AND A.NEW_PRODUCT_CODE<>''''  
			GROUP BY A.PRODUCT_CODE,A.BIN_ID,LEFT(B.IRM_MEMO_ID,2)
		END	

		SET @CSTEP=190
		IF @XNTYPE='SCM'
		BEGIN
			INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT A.PRODUCT_CODE,LEFT(B.MEMO_ID,2),ABS(SUM(A.QUANTITY)) AS XN_QTY,'000'  AS [BIN_ID] 
			FROM SCF01106 A (NOLOCK)  
			JOIN SCM01106 B (NOLOCK) ON A.MEMO_ID = B.MEMO_ID  
			WHERE B.MEMO_ID=@MEMOID   AND B.CANCELLED=0 AND A.PRODUCT_CODE<>''''  
			GROUP BY A.PRODUCT_CODE,LEFT(B.MEMO_ID,2)
		END	

		SET @CSTEP=200
		IF @XNTYPE='CIP'
		BEGIN
			INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT A.PRODUCT_CODE,LEFT(B.MEMO_ID,2),ABS(SUM(A.QUANTITY+ADJ_QUANTITY))*-1 AS XN_QTY,  
			'000'  AS [BIN_ID]   
			FROM SCC01106 A (NOLOCK)  
			JOIN SCM01106 B (NOLOCK) ON A.MEMO_ID = B.MEMO_ID  
			WHERE B.MEMO_ID=@MEMOID    AND  B.CANCELLED=0 AND A.PRODUCT_CODE<>''''   
			GROUP BY A.PRODUCT_CODE,LEFT(B.MEMO_ID,2)
		END	

		SET @CSTEP=210
		IF @XNTYPE='JWI'
		BEGIN
			INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT 
			A.PRODUCT_CODE,LEFT(B.ISSUE_ID,2),  
			ABS(SUM(A.QUANTITY))*-1 AS XN_QTY,  
			A.BIN_ID  AS [BIN_ID]      
			FROM JOBWORK_ISSUE_DET A (NOLOCK)  
			JOIN JOBWORK_ISSUE_MST B (NOLOCK) ON A.ISSUE_ID = B.ISSUE_ID  
			WHERE B.ISSUE_ID=@MEMOID   AND  B.CANCELLED=0 
			AND ISNULL(B.ISSUE_MODE,0)=0 AND ISNULL(B.WIP,0)=0 AND ISNULL(B.ISSUE_TYPE,0)=1
			GROUP BY A.PRODUCT_CODE,A.BIN_ID,LEFT(B.ISSUE_ID,2)
		END	

		SET @CSTEP=220
		IF @XNTYPE='JWR'
		BEGIN
			INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT A.PRODUCT_CODE,LEFT(B.RECEIPT_ID,2),  ABS(SUM(A.QUANTITY)) AS XN_QTY,A.BIN_ID  AS [BIN_ID]     
			FROM JOBWORK_RECEIPT_DET A (NOLOCK)  
			JOIN JOBWORK_RECEIPT_MST B (NOLOCK) ON A.RECEIPT_ID = B.RECEIPT_ID  
			JOIN JOBWORK_ISSUE_DET D (NOLOCK) ON D.ROW_ID=A.REF_ROW_ID  
			JOIN JOBWORK_ISSUE_MST E (NOLOCK) ON E.ISSUE_ID = D.ISSUE_ID  
			WHERE B.RECEIPT_ID=@MEMOID   AND  B.CANCELLED=0 
			AND ISNULL(B.RECEIVE_MODE,0)=0 AND ISNULL(B.WIP,0)=0 AND ISNULL(E.ISSUE_TYPE,0)=1
			GROUP BY A.PRODUCT_CODE,A.BIN_ID,LEFT(B.RECEIPT_ID,2)
		END	

		SET @CSTEP=230
		IF @XNTYPE='BOC'
		BEGIN
			INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT E.PRODUCT_CODE,LEFT(D.ORDER_ID,2),SUM((E.CONS_QTY_PER_PICE*P.QUANTITY))*-1 AS XN_QTY,     
			'000'  AS [BIN_ID]              
			FROM WSL_ORDER_BOM E(NOLOCK)   
			LEFT OUTER JOIN WSL_ORDER_DET C (NOLOCK) ON E.REF_ROW_ID=C.ROW_ID  
			LEFT OUTER JOIN WSL_ORDER_MST D (NOLOCK) ON C.ORDER_ID=D.ORDER_ID  
			JOIN POD01106 P WITH (NOLOCK)  ON C.ROW_ID = P.WOD_ROW_ID   
			JOIN POM01106 PM WITH (NOLOCK)  ON P.PO_ID = PM.PO_ID    
			WHERE D.ORDER_ID=@MEMOID AND PM.CANCELLED = 0  
			GROUP BY E.PRODUCT_CODE,LEFT(D.ORDER_ID,2)
		END	

		
		SET @CSTEP=240
		IF @XNTYPE='SCF'
		BEGIN
			INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT B2.PRODUCT_CODE, LEFT(B.MEMO_ID,2), 
			SUM((CASE WHEN B2.BARCODE_CODING_SCHEME=3 THEN B2.TOTAL_QTY ELSE A.QUANTITY END)) AS XN_QTY,  
			A.BIN_ID  AS [BIN_ID]     
			FROM SNC_DET A (NOLOCK)  
			JOIN SNC_MST B (NOLOCK) ON A.MEMO_ID = B.MEMO_ID  
			JOIN
			(
			SELECT REFROW_ID AS [ROW_ID],A.PRODUCT_CODE,
			SKU.BARCODE_CODING_SCHEME,COUNT(*) AS [TOTAL_QTY]
			FROM SNC_BARCODE_DET A (NOLOCK)
			JOIN SKU (NOLOCK) ON SKU.PRODUCT_CODE=A.PRODUCT_CODE
			GROUP BY REFROW_ID,A.PRODUCT_CODE,SKU.BARCODE_CODING_SCHEME
			)B2 ON A.ROW_ID = B2.ROW_ID
			JOIN ARTICLE A1 ON A1.ARTICLE_CODE=A.ARTICLE_CODE
			WHERE B.MEMO_ID=@MEMOID   AND B.CANCELLED=0 AND B2.PRODUCT_CODE<>''''  
			GROUP BY B2.PRODUCT_CODE,A.BIN_ID,LEFT(B.MEMO_ID,2)
		END

		SET @CSTEP=250
		IF @XNTYPE='SNC'
		BEGIN
			INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT A.PRODUCT_CODE,LEFT(B.MEMO_ID,2),  
			ABS(SUM(A.QUANTITY))*-1 AS XN_QTY,  
			ISNULL(A.BIN_ID,'000')  AS [BIN_ID]   
			FROM SNC_CONSUMABLE_DET A (NOLOCK)  
			JOIN SNC_MST B (NOLOCK) ON A.MEMO_ID = B.MEMO_ID  
			WHERE B.MEMO_ID=@MEMOID   AND B.CANCELLED=0 AND A.PRODUCT_CODE<>''''   
			GROUP BY A.PRODUCT_CODE,ISNULL(A.BIN_ID,'000'),LEFT(B.MEMO_ID,2)
		END	

		SET @CSTEP=260
		IF @XNTYPE='GRNPSIN'
		BEGIN
			INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT A.PRODUCT_CODE,LEFT(B.MEMO_ID,2),SUM(A.QUANTITY) AS XN_QTY,B.BIN_ID  AS [BIN_ID]      
			FROM GRN_PS_DET A (NOLOCK)  
			JOIN GRN_PS_MST B (NOLOCK) ON A.MEMO_ID = B.MEMO_ID  
			WHERE B.MEMO_ID=@MEMOID   AND  B.CANCELLED = 0 
			AND ISNULL(B.REF_CONVERTED_MRR_ID,'''')='''' 
			GROUP BY A.PRODUCT_CODE,B.BIN_ID,LEFT(B.MEMO_ID,2)
		END	

		SET @CSTEP=270
		IF @XNTYPE='TTM'
		BEGIN
			INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT A.PRODUCT_CODE,LEFT(B.MEMO_ID,2),SUM(A.QTY)*1 AS XN_QTY,'000'  AS [BIN_ID] 
			FROM PRD_TRANSFER_MAIN_DET A (NOLOCK)  
			JOIN PRD_TRANSFER_MAIN_MST B (NOLOCK) ON A.MEMO_ID = B.MEMO_ID  
			WHERE B.MEMO_ID=@MEMOID  
			AND B.CANCELLED = 0 
			GROUP BY A.PRODUCT_CODE,LEFT(B.MEMO_ID,2)
		END	

		SET @CSTEP=280
		IF @XNTYPE='TTM'
		BEGIN
			INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT   A.PRODUCT_CODE, LEFT(B.MEMO_ID,2),SUM(A.QUANTITY) AS XN_QTY,A.BIN_ID  AS [BIN_ID]      
			FROM TRANSFER_TO_TRADING_MST B (NOLOCK)    
			JOIN TRANSFER_TO_TRADING_DET A (NOLOCK)ON A.MEMO_ID = B.MEMO_ID  
			WHERE B.MEMO_ID=@MEMOID  AND  B.CANCELLED = 0  
			GROUP BY A.PRODUCT_CODE,A.BIN_ID,LEFT(B.MEMO_ID,2)
		END	

		SET @CSTEP=290
		IF @XNTYPE='MIS'
		BEGIN
			INSERT #TMPPMT (PRODUCT_CODE,DEPT_ID,QUANTITY,BIN_ID)
			SELECT A.PRODUCT_CODE,LEFT(B.ISSUE_ID,2),   
			SUM(CASE WHEN ISNULL(B.ISSUE_TYPE,0)=0 THEN -1 ELSE 1 END* ISNULL(A.STOCK_QTY,0))  AS XN_QTY,  
			A.BIN_ID  AS [BIN_ID]      
			FROM BOM_ISSUE_MST B (NOLOCK)    
			JOIN BOM_ISSUE_DET A (NOLOCK)ON A.ISSUE_ID = B.ISSUE_ID  
			WHERE B.ISSUE_ID=@MEMOID   AND  B.CANCELLED = 0  
			GROUP BY A.PRODUCT_CODE,A.BIN_ID,LEFT(B.ISSUE_ID,2)
		END	

   
	 
	    SET @CSTEP=300
		SET @CCMD=N'INSERT '+@CPMTTABLENAMEXNDT+' (PRODUCT_CODE,BIN_ID,DEPT_ID,CBS_QTY)
		SELECT A.PRODUCT_CODE,A.BIN_ID,A.DEPT_ID,0 AS XN_QTY
		FROM #TMPPMT A
		LEFT JOIN '+@CPMTTABLENAMEXNDT+' B ON A.PRODUCT_CODE=B.PRODUCT_CODE
		WHERE B.PRODUCT_CODE IS NULL'
		PRINT @CCMD
		EXEC SP_EXECUTESQL 	@CCMD 
		
		
		SET @CSTEP=310
		IF @FLAG=1
		BEGIN
			SET @CCMD= 'UPDATE A SET  CBS_QTY=CBS_QTY+B.QUANTITY
			FROM '+@CPMTTABLENAMEXNDT+' A
			JOIN #TMPPMT B ON A.PRODUCT_CODE=B.PRODUCT_CODE AND A.BIN_ID=B.BIN_ID AND A.DEPT_ID=B.DEPT_ID'
		END
		
		SET @CSTEP=320
		IF @FLAG=0
		BEGIN
			SET @CCMD= 'UPDATE A SET  CBS_QTY=CBS_QTY-B.QUANTITY
			FROM '+@CPMTTABLENAMEXNDT+' A
			JOIN #TMPPMT B ON A.PRODUCT_CODE=B.PRODUCT_CODE AND A.BIN_ID=B.BIN_ID AND A.DEPT_ID=B.DEPT_ID'
		END
		
		PRINT @CCMD
		EXEC SP_EXECUTESQL  @CCMD	
	 
	
END TRY

BEGIN CATCH

  SET @CERRMSG=N'ERROR IN SP3SUPDATE_LOCWISEPMTXNS STEP:'+LTRIM(STR(@cSTEP))++ ' SQL ERROR: #' + LTRIM(STR(ERROR_NUMBER())) + ' ' + ERROR_MESSAGE()  
  GOTO END_PROC

	
END CATCH


END_PROC:

 IF ISNULL(@CERRMSG,'')=''
 COMMIT
 ELSE
 ROLLBACK
 
 SELECT ISNULL(@CERRMSG,'') AS ERRMSG
 
 
	
END		



/*
EXEC SP3SBUILDLOCWISEPMTXNS '2019-03-31'

SELECT * FROM JMHO_RFOPT..PMTLOCS_20190301 WHERE PRODUCT_CODE
NOT IN (SELECT PRODUCT_CODE FROM JMHO_RFOPT..PMTLOCS_20190331)

*/