CREATE PROCEDURE SP_CONSUMPTION_CON 

@NQUERYID		NUMERIC (2,0),    
@CMEMOID		VARCHAR(40),    
@CWHERE			VARCHAR(500),    
@CPRODUCTCODE	VARCHAR(50),    
@CFINYEAR		VARCHAR(5),    
@NNAVMODE		NUMERIC(2,0)
--WITH ENCRYPTION    
AS    
BEGIN    
DECLARE @CCMD NVARCHAR(MAX)    
    
IF     
@NQUERYID = 1    
GOTO LBLNAVIGATE    
    
ELSE IF     
@NQUERYID = 2    
GOTO LBLGETMASTERS    
    
ELSE IF     
@NQUERYID = 3    
GOTO LBLGETDETAILS    

ELSE IF    
@NQUERYID = 5    
GOTO LBLGETPRODUCTLIST    
    
LBLNAVIGATE:    
 EXECUTE SP_NAVIGATE 'CON_CONSUMPTION_MST',@NNAVMODE,@CMEMOID,@CFINYEAR,'MEMO_NO','MEMO_DT','MEMO_ID',@CWHERE    
GOTO LAST    
    
LBLGETMASTERS:    
	 SELECT T1.*,USR.USERNAME 
	 FROM CON_CONSUMPTION_MST T1
	 JOIN USERS USR ON T1.USER_CODE = USR.USER_CODE
	 WHERE T1.MEMO_ID = @CMEMOID    
     
GOTO LAST    
    
LBLGETDETAILS:    
	     
	 SELECT D.*,ART.ARTICLE_NAME AS ITEM_NAME,ART.ARTICLE_DESC AS ITEM_DESC,    
	 0 AS QUANTITY_IN_STOCK,M.DEPT_ID,UOM.UOM_NAME 
	 ,P1.PARA1_NAME ,P2.PARA2_NAME,P3.PARA3_NAME
	 FROM CON_CONSUMPTION_DET D    
	 JOIN CON_CONSUMPTION_MST M ON D.MEMO_ID = M.MEMO_ID     
	 JOIN SKU S ON D.PRODUCT_CODE = S.PRODUCT_CODE     
	 JOIN PARA1 P1 ON S.PARA1_CODE = P1.PARA1_CODE     
	 JOIN PARA2 P2 ON S.PARA2_CODE = P2.PARA2_CODE   
	 JOIN PARA3 P3 ON S.PARA3_CODE = P3.PARA3_CODE     
	 JOIN ARTICLE ART ON ART.ARTICLE_CODE=S.ARTICLE_CODE
	 JOIN UOM ON UOM.UOM_CODE = ART.UOM_CODE     
	 WHERE M.MEMO_ID = @CMEMOID    
	 ORDER BY D.TS DESC    
	     
 GOTO LAST    
    
LBLGETPRODUCTLIST:    
	 SELECT S.PRODUCT_CODE, A.ARTICLE_NAME AS ITEM_NAME,A.ARTICLE_DESC AS ITEM_DESC,
	 P1.PARA1_NAME ,P2.PARA2_NAME ,UOM.UOM_NAME      
	 FROM SKU S
	 JOIN PMT01106 P ON P.PRODUCT_CODE=S.PRODUCT_CODE
	 JOIN ARTICLE A ON S.ARTICLE_CODE = A.ARTICLE_CODE
	 JOIN PARA1 P1 ON S.PARA1_CODE = P1.PARA1_CODE     
	 JOIN PARA2 P2 ON S.PARA2_CODE = P2.PARA2_CODE     
	 JOIN SECTIOND SD ON SD.SUB_SECTION_CODE=A.SUB_SECTION_CODE
	 JOIN SECTIONM SM ON SM.SECTION_CODE=SD.SECTION_CODE
	 JOIN UOM ON UOM.UOM_CODE = A.UOM_CODE     
	 WHERE  SM.ITEM_TYPE=2 AND P.QUANTITY_IN_STOCK>0
	    
GOTO LAST    

    
LAST:    
END
