CREATE PROCEDURE SP_PPC_PRODCUT_CODE_LIST
(
  @NQUERYID INT=1,
  @CPRODUCT_CODE VARCHAR(100)=''
)
AS
BEGIN
   IF @NQUERYID=1
      GOTO  LBLBARCODELIS
   ELSE
   GOTO END_PROC
   
   LBLBARCODELIS:
        
        SELECT DISTINCT SKU.PRODUCT_CODE,ART.ARTICLE_NO,ART.ARTICLE_CODE ,QUANTITY_IN_STOCK 
        FROM PPC_SKU SKU
        JOIN PPC_PMT PMT ON SKU.PRODUCT_CODE=PMT.PRODUCT_CODE 
        JOIN ARTICLE ART ON SKU.ARTICLE_CODE =ART.ARTICLE_CODE 
        WHERE (@CPRODUCT_CODE='' OR SKU.PRODUCT_CODE LIKE ''+@CPRODUCT_CODE+'%')
   
   GOTO END_PROC

END_PROC:
END
