CREATE PROCEDURE SP_SEND_MIRROR_GRNPS_DATA_NEW  
(  
  @CUPLOADEDXNID VARCHAR(50)  
 ,@CCURLOCID VARCHAR(5)  
 ,@BACKNOWLEDGE BIT=0  
 ,@CERRMSG VARCHAR(1000) OUTPUT  
)  
--WITH ENCRYPTION  
AS  
BEGIN  
 DECLARE @CMEMOID VARCHAR(50),@CSTEP VARCHAR(5)  
BEGIN TRY   
 SET @CSTEP=00  
   
 DECLARE @CTEMPDBNAME1 VARCHAR(40),@CTEMPDBNAME VARCHAR(40)  
   
   
   
 SET @CSTEP=10      
   
  SET @CMEMOID=@CUPLOADEDXNID  
 ---- IF NO MEMO FOUND , JUST END THE PROCESS  
 IF ISNULL(@CMEMOID,'')=''  
  GOTO END_PROC  
  
LBLTABLEINFO:  
 SET @CSTEP=50  
  
 IF @BACKNOWLEDGE=1  
  GOTO END_PROC  
    
 SET @CSTEP=55  
 SELECT DISTINCT 'GRNPS_GRN_PS_MST_MIRROR' AS TARGET_TABLENAME,A.* ,@CMEMOID AS XN_ID FROM GRN_PS_MST(NOLOCK) A WHERE A.MEMO_ID=@CMEMOID  
   
 SET @CSTEP=60  
 SELECT DISTINCT 'GRNPS_GRN_PS_DET_MIRROR' AS TARGET_TABLENAME,A.* FROM GRN_PS_DET(NOLOCK) A WHERE A.MEMO_ID=@CMEMOID  
   
 SET @CSTEP=70  
 SELECT DISTINCT 'GRNPS_SKU_MIRROR' AS TARGET_TABLENAME,B.*, @CMEMOID AS GRN_MEMO_ID    
 FROM GRN_PS_DET(NOLOCK) A  
 JOIN SKU (NOLOCK) B ON A.PRODUCT_CODE  =B.PRODUCT_CODE  
 WHERE A.MEMO_ID=@CMEMOID  
   
 SET @CSTEP=71  
 SELECT DISTINCT 'GRNPS_PMT01106_MIRROR' AS TARGET_TABLENAME,@CMEMOID AS GRNPS_MEMO_ID,A.DEPT_ID,A.product_code,A.BIN_ID,A.quantity_in_stock  FROM PMT01106(NOLOCK) A  
 JOIN GRN_PS_DET (NOLOCK) B ON B.PRODUCT_CODE  =A.PRODUCT_CODE  
 WHERE B.MEMO_ID=@CMEMOID 
   
   
      
LBLCHECKDATA:  
  
END TRY  
BEGIN CATCH  
 SET @CERRMSG='P: SP_SEND_MIRROR_GRNPS_DATA_NEW, STEP:'+@CSTEP+', MESSAGE:'+ERROR_MESSAGE()  
 GOTO END_PROC  
END CATCH   
   
END_PROC:  
  
END   
---END OF PROCEDURE - SP_SEND_MIRROR_GRNPS_DATA_NEW  