
/*
EXEC SP_BUYERORDER_DETAILS 2,'2016-11-01','2017-12-01'
*/
CREATE PROCEDURE DBO.SP_RPT_BUYERORDER_DETAILS
(
  @NMODE INT = 1 /*@NMODE: 1 FOR ALL,2 FOR PENDING AND 3 FOR DELEIVERED*/  
 ,@FMDATE VARCHAR(10)=''
 ,@TODATE VARCHAR(10)=''
)
AS
  BEGIN
     IF OBJECT_ID('TEMPDB..#BUYERORDER') IS NOT NULL
        DROP TABLE #BUYERORDER
      CREATE TABLE #BUYERORDER
       (
         ID INT IDENTITY(1,1)
        ,LOCATIONAME VARCHAR(200)
        ,ORDER_DATE DATETIME
        ,ORDER_NO VARCHAR(200)
        ,PRODUCT_CODE VARCHAR(200)
        ,QTY INT
        ,ARTICLE_NAME VARCHAR(200)
        ,AMOUNT DECIMAL(9,2)
        ,SALEPERSON VARCHAR(200)
        ,DELIVER_DT DATETIME
        ,CUSTOMER_NAME VARCHAR(200)
        ,PO_NO VARCHAR(100)
        ,PO_DT DATETIME
        ,MRR_NO VARCHAR(200)
        ,MRR_DT DATETIME
        ,CM_NO VARCHAR(100)
        ,CM_DT DATETIME
        ,PENDING_QTY INT DEFAULT(1)
       )
       INSERT INTO #BUYERORDER(CUSTOMER_NAME,ORDER_NO,ORDER_DATE,DELIVER_DT,PRODUCT_CODE
                   ,QTY,ARTICLE_NAME,SALEPERSON,AMOUNT,LOCATIONAME)
       SELECT ISNULL(USER_CUSTOMER_CODE,'') + ' - '+ CU.CUSTOMER_FNAME,M.ORDER_NO
       ,M.ORDER_DT,M.DELIVERY_DT 
       ,D.PRODUCT_CODE,D.QUANTITY AS QUANTITY,ART.ARTICLE_NAME
       ,EM.EMP_NAME AS [SALEPERSON],D.GROSS_WSP AS  [AMOUNT],LO.DEPT_NAME
       FROM DBO.WSL_ORDER_MST M
       JOIN DBO.WSL_ORDER_DET D ON M.ORDER_ID=D.ORDER_ID
       JOIN DBO.ARTICLE ART ON D.ARTICLE_CODE=ART.ARTICLE_CODE
       JOIN DBO.CUSTDYM CU ON M.CUSTOMER_CODE=CU.CUSTOMER_CODE
       JOIN DBO.EMPLOYEE EM ON M.SALE_EMP_CODE=EM.EMP_CODE
       JOIN DBO.LOCATION LO ON LO.DEPT_ID=M.DEPT_ID
       WHERE (@FMDATE ='' OR CAST(ORDER_DT AS DATE) BETWEEN @FMDATE AND @TODATE)
       
       
      DECLARE @POMRR_DETAILS TABLE (PRODUCT_CODE VARCHAR(200),ORDER_NO VARCHAR(200)
                                    ,PO_NO VARCHAR(100),PO_DATE DATETIME
                                    ,MRR_NO VARCHAR(100),MRR_DATE DATETIME,CM_NO VARCHAR(100)
                                    ,CM_DT DATETIME)
       INSERT INTO @POMRR_DETAILS(PRODUCT_CODE,ORDER_NO,PO_NO,PO_DATE,MRR_NO,MRR_DATE,CM_NO,CM_DT)
       
       SELECT BO.PRODUCT_CODE,BO.ORDER_NO,PO.PO_ID,PO.LAST_UPDATE AS [PO_DT]
         ,PID.MRR_ID,PID.LAST_UPDATE AS [MRR_DT],CMM.CM_ID AS [CM_NO],CMM.CM_DT 
       FROM #BUYERORDER BO
       LEFT JOIN POD01106 PO WITH(NOLOCK) ON BO.PRODUCT_CODE=PO.PRODUCT_CODE
       LEFT JOIN PID01106 PID WITH(NOLOCK) ON BO.PRODUCT_CODE=PID.PRODUCT_CODE
       LEFT JOIN CMD01106 CMD WITH(NOLOCK) ON BO.PRODUCT_CODE=CMD.PRODUCT_CODE
       JOIN CMM01106 CMM WITH(NOLOCK) ON CMD.CM_ID=CMM.CM_ID
       
       
       
       UPDATE BU SET BU.PO_NO=POMM.PO_NO
                    ,BU.PO_DT=POMM.PO_DATE
                    ,BU.MRR_NO=POMM.MRR_NO
                    ,BU.MRR_DT=POMM.MRR_DATE
                    ,BU.CM_NO=POMM.CM_NO
                    ,BU.CM_DT=POMM.CM_DT
       FROM #BUYERORDER BU
       JOIN @POMRR_DETAILS POMM ON BU.PRODUCT_CODE=POMM.PRODUCT_CODE
       AND BU.ORDER_NO = POMM.ORDER_NO
       
       
       
       UPDATE BU SET PENDING_QTY=0
       FROM #BUYERORDER BU
       JOIN (
		     SELECT BO.ORDER_NO,BO.PRODUCT_CODE FROM #BUYERORDER BO
		     LEFT JOIN CMD01106 CMD ON BO.PRODUCT_CODE=CMD.PRODUCT_CODE
		     WHERE CMD.PRODUCT_CODE IS NULL
		    ) T ON BU.PRODUCT_CODE=T.PRODUCT_CODE AND BU.ORDER_NO=T.ORDER_NO
      
      IF @NMODE=1
         SELECT LOCATIONAME,ORDER_DATE ,ORDER_NO,PRODUCT_CODE,QTY AS CAL_QTY ,ARTICLE_NAME,AMOUNT AS CAL_AMOUNT
        ,SALEPERSON,DELIVER_DT,CUSTOMER_NAME,PO_NO,PO_DT,MRR_NO,MRR_DT,CM_NO,CM_DT,PENDING_QTY AS CAL_PENDING_QTY
        FROM #BUYERORDER 
     IF @NMODE=2
        SELECT LOCATIONAME,ORDER_DATE ,ORDER_NO,PRODUCT_CODE,QTY AS CAL_QTY ,ARTICLE_NAME,AMOUNT AS CAL_AMOUNT
    ,   SALEPERSON,DELIVER_DT,CUSTOMER_NAME,PO_NO,PO_DT,MRR_NO,MRR_DT,CM_NO,CM_DT,PENDING_QTY AS CAL_PENDING_QTY
        FROM #BUYERORDER WHERE PENDING_QTY=0
     IF @NMODE=3
        SELECT LOCATIONAME,ORDER_DATE ,ORDER_NO,PRODUCT_CODE,QTY AS CAL_QTY ,ARTICLE_NAME,AMOUNT AS CAL_AMOUNT
    ,   SALEPERSON,DELIVER_DT,CUSTOMER_NAME,PO_NO,PO_DT,MRR_NO,MRR_DT,CM_NO,CM_DT,PENDING_QTY AS CAL_PENDING_QTY
        FROM #BUYERORDER WHERE PENDING_QTY=1
      
      
  END
  
