CREATE PROCEDURE SP3S_WSLGATEPASS
(
@CINV_ID VARCHAR(22)
)
AS
BEGIN

     DECLARE @CERRORMSG VARCHAR(MAX)
 
	SELECT INV_NO,INV_DT,NET_AMOUNT,LM.AC_NAME,A.ANGADIA_NAME,PM1.*,PD1.* FROM INM01106 T1
		JOIN parcel_det  PB ON PB.REF_MEMO_ID=T1.INV_ID 
		JOIN
		(
		 SELECT BOX_NO,PARCEL_MEMO_ID,SUM(QUANTITY) AS TOTALQUANTITY FROM PARCEL_DET (NOLOCK) 
		 GROUP BY PARCEL_MEMO_ID,BOX_NO
		)PD1 ON PD1.PARCEL_MEMO_ID=PB.PARCEL_MEMO_ID
		 JOIN PARCEL_MST PM1 ON  PM1.PARCEL_MEMO_ID=PB.PARCEL_MEMO_ID 
		 JOIN LM01106 LM ON LM.AC_CODE=T1.AC_CODE
		 JOIN ANGM A ON A.ANGADIA_CODE=PM1.ANGADIA_CODE
					WHERE INV_ID=@CINV_ID
    
END_PROC:

     SELECT ISNULL(@CERRORMSG,'') AS ERRMSG
    --SET @CERRORMSG = 'PROCEDURE SP3S_WSLGATEPASS: STEP- ' + LTRIM(STR(@NSTEP)) + ' SQL ERROR: #' + LTRIM(STR(ERROR_NUMBER())) + ' ' + ERROR_MESSAGE()
    

END	
  ----------------------------------------------------- END OF PROCEDURE SP3S_WSLGATEPASS
