CREATE PROCEDURE SPPPC_PO_SIZE_FILTER    
(    
	@VNAME VARCHAR(500),
	@ARTICLECODE VARCHAR(500) 
)    
AS        
BEGIN     
	SELECT C.PARA2_CODE,C.PARA2_NAME FROM ART_DET AS A 
	JOIN PPC_SIZEGROUP_PARA2 AS B ON A.SIZEGROUP_CODE=B.SIZEGROUP_CODE
	JOIN  PARA2 AS C ON B.PARA2_CODE=C.PARA2_CODE 
	WHERE C.PARA2_NAME <> '' AND INACTIVE = 0   AND A.ARTICLE_CODE= @ARTICLECODE       
	AND C.PARA2_NAME LIKE '%'+ @VNAME +'%'   
	ORDER BY C.PARA2_ORDER, C.PARA2_NAME  
END
