CREATE PROCEDURE SP3S_WSL_BUYERORDER_QTY
(
  @FM_DATE DATETIME='',
  @TO_DATE DATETIME=''
)
AS
BEGIN
     
     --
     
     SELECT A.AC_CODE,LM.AC_NAME ,A.ORDER_DT,A.ORDER_NO ,
            SUM(B.QUANTITY) AS QUANTITY ,
            SUM(ISNULL(ADJ_QTY,0)) AS ADJ_QTY,
            SUM(B.QUANTITY)-SUM(ISNULL(ADJ_QTY,0)) AS NET_QTY
     FROM BUYER_ORDER_MST A
     JOIN BUYER_ORDER_DET B ON A.ORDER_ID =B.ORDER_ID 
     JOIN LM01106 LM  ON LM.AC_CODE=A.AC_CODE
     WHERE A.CANCELLED=0
     AND A.ORDER_DT BETWEEN @FM_DATE AND @TO_DATE
     GROUP BY A.AC_CODE,LM.AC_NAME ,A.ORDER_DT,A.ORDER_NO
     ORDER BY LM.AC_NAME


END
