CREATE PROCEDURE SP3S_PICKLIST_PRINTING    
(    
  @MEMO_ID VARCHAR(30)     
)    
AS    
BEGIN    
    
    Declare @cBatchLotNo varchar(50) ,@cAc_code varchar(15)  ,@LocID varchar(5)

	DECLARE  @TBLSTOCK TABLE (SRNO NUMERIC(5,0),bin_name varchar(max))
  
	SELECT @CBATCHLOTNO=BATCHLOTNO,@CAC_CODE=AC_CODE  ,@LocID=A.location_code  
	FROM PLM01106 A (NOLOCK) WHERE MEMO_ID=@MEMO_ID  
     
	 CREATE TABLE #tmpMemos (memo_id VARCHAR(50))


	 --- Done to handle Picklist generated from ARS of Wow wher3 batch lotno. is not generated(Sanjay : 09-07-2024)
     IF ISNULL(@CBATCHLOTNO,'')=''
	   INSERT INTO #tmpMemos (memo_id) 
	   select @memo_id
     else
	   INSERT INTO #tmpMemos (memo_id) 
	   select memo_id FROM plm01106 (NOLOCK) WHERE batchlotno=@CBATCHLOTNO AND AC_CODE=@CAC_CODE 
	   
             
    IF OBJECT_ID ('TEMPDB..#TMPPL','U') IS NOT NULL    
             DROP TABLE  #TMPPL    
    
    SELECT '' AS [ORDER_NO],'' AS [ORDER_DT],F.MEMO_NO AS [MEMO_NO],F.MEMO_DT AS [MEMO_DT],   D.AC_NAME AS [AC_NAME],    
    ART.ARTICLE_NO AS [ARTICLE_NO],P1.PARA1_NAME AS [PARA1_NAME],P2.PARA2_NAME AS [PARA2_NAME],P3.PARA3_NAME AS [PARA3_NAME],    
    AT1.ATTR1_KEY_NAME,AT2.ATTR2_KEY_NAME,AT3.ATTR3_KEY_NAME,AT4.ATTR4_KEY_NAME,AT5.ATTR5_KEY_NAME,AT6.ATTR6_KEY_NAME,    
    AT7.ATTR7_KEY_NAME,AT8.ATTR8_KEY_NAME,AT9.ATTR9_KEY_NAME,AT10.ATTR10_KEY_NAME,AT11.ATTR11_KEY_NAME,AT12.ATTR12_KEY_NAME,    
    AT13.ATTR13_KEY_NAME,AT14.ATTR14_KEY_NAME,AT15.ATTR15_KEY_NAME,AT16.ATTR16_KEY_NAME,AT17.ATTR17_KEY_NAME,AT18.ATTR18_KEY_NAME,    
    AT19.ATTR19_KEY_NAME,AT20.ATTR20_KEY_NAME,AT21.ATTR21_KEY_NAME,AT22.ATTR22_KEY_NAME,AT23.ATTR23_KEY_NAME,AT24.ATTR24_KEY_NAME,    
    AT25.ATTR25_KEY_NAME, SUM(A.QUANTITY) AS [QTY],    
    f.USER_CODE,    
    --bin.BIN_NAME  as STOCK_AVAILABLE_BIN ,    
    --bin1.BIN_NAME as Zonename,bin.bin_id ,    
    --LEFT(A.PLD_Product_code, ISNULL(NULLIF(CHARINDEX ('@',A.PLD_Product_code)-1,-1),LEN(A.PLD_Product_code ))) PLD_Product_code,    
    F.Remarks,F.CANCELLED,    
    SL.DEPT_NAME,SL.address1,SL.address2,SL.REGISTERED_ADD,SL.TIN_NO,SL.loc_gst_no,    
    LEFT(SL.loc_gst_no,2) AS loc_STATE_CODE,SLA.AREA_NAME,SLA.PINCODE AS Loc_PINCODE,SLA.PINCODE,    
    SLC.CITY,SLS.GST_STATE_NAME,SL.PHONE,sd.sub_section_name ,sm.section_name ,    
    SRNO=ROW_NUMBER() OVER(ORDER BY F.MEMO_NO)    
    into #TMPPL    
    FROM PLD01106 A    
    JOIN PLM01106 F ON F.MEMO_ID=A.MEMO_ID    
	JOIN #tmpMemos t on t.memo_id=a.memo_id
    JOIN LM01106 D ON D.AC_CODE=f.AC_CODE    
    JOIN ARTICLE ART ON ART.ARTICLE_CODE=a.ARTICLE_CODE    
    join sectiond sd (nolock) on sd.sub_section_code =art.sub_section_code     
    join sectionm sm (nolock) on sm.section_code =sd.section_code     
    JOIN PARA1 P1 ON P1.PARA1_CODE=a.PARA1_CODE    
    JOIN PARA2 P2 ON P2.PARA2_CODE=a.PARA2_CODE    
    JOIN PARA3 P3 ON P3.PARA3_CODE=a.PARA3_CODE    
    join bin (nolock) on a.BIN_ID =bin.BIN_ID     
    join bin bin1 (nolock) on bin.major_bin_id =bin1.BIN_ID     
    jOIN LOCATION SL (NOLOCK) ON SL.dept_id=@LocID     
    LEFT JOIN AREA SLA (NOLOCK) ON SL.AREA_CODE=SLA.AREA_CODE                      
    LEFT JOIN CITY SLC (NOLOCK) ON SLA.CITY_CODE=SLC.CITY_CODE                      
    LEFT JOIN GST_STATE_MST SLS (NOLOCK) ON SLS.GST_STATE_CODE=SL.GST_STATE_CODE    
    LEFT OUTER JOIN ARTICLE_FIX_ATTR ATTR  (NOLOCK) ON ART.ARTICLE_CODE = ATTR.ARTICLE_CODE     
    LEFT OUTER JOIN ATTR1_MST AT1 (NOLOCK) ON AT1.ATTR1_KEY_CODE=ATTR.ATTR1_KEY_CODE    
    LEFT OUTER JOIN ATTR2_MST AT2 (NOLOCK) ON AT2.ATTR2_KEY_CODE=ATTR.ATTR2_KEY_CODE    
    LEFT OUTER JOIN ATTR3_MST AT3 (NOLOCK) ON AT3.ATTR3_KEY_CODE=ATTR.ATTR3_KEY_CODE    
    LEFT OUTER JOIN ATTR4_MST AT4 (NOLOCK) ON AT4.ATTR4_KEY_CODE=ATTR.ATTR4_KEY_CODE    
    LEFT OUTER JOIN ATTR5_MST AT5 (NOLOCK) ON AT5.ATTR5_KEY_CODE=ATTR.ATTR5_KEY_CODE    
    LEFT OUTER JOIN ATTR6_MST AT6 (NOLOCK) ON AT6.ATTR6_KEY_CODE=ATTR.ATTR6_KEY_CODE    
    LEFT OUTER JOIN ATTR7_MST AT7 (NOLOCK) ON AT7.ATTR7_KEY_CODE=ATTR.ATTR7_KEY_CODE    
    LEFT OUTER JOIN ATTR8_MST AT8 (NOLOCK) ON AT8.ATTR8_KEY_CODE=ATTR.ATTR8_KEY_CODE    
    LEFT OUTER JOIN ATTR9_MST AT9 (NOLOCK) ON AT9.ATTR9_KEY_CODE=ATTR.ATTR9_KEY_CODE    
    LEFT OUTER JOIN ATTR10_MST AT10 (NOLOCK) ON AT10.ATTR10_KEY_CODE=ATTR.ATTR10_KEY_CODE    
    LEFT OUTER JOIN ATTR11_MST AT11 (NOLOCK) ON AT11.ATTR11_KEY_CODE=ATTR.ATTR11_KEY_CODE    
    LEFT OUTER JOIN ATTR12_MST AT12 (NOLOCK) ON AT12.ATTR12_KEY_CODE=ATTR.ATTR12_KEY_CODE    
    LEFT OUTER JOIN ATTR13_MST AT13 (NOLOCK) ON AT13.ATTR13_KEY_CODE=ATTR.ATTR13_KEY_CODE    
    LEFT OUTER JOIN ATTR14_MST AT14 (NOLOCK) ON AT14.ATTR14_KEY_CODE=ATTR.ATTR14_KEY_CODE    
    LEFT OUTER JOIN ATTR15_MST AT15 (NOLOCK) ON AT15.ATTR15_KEY_CODE=ATTR.ATTR15_KEY_CODE    
    LEFT OUTER JOIN ATTR16_MST AT16 (NOLOCK) ON AT16.ATTR16_KEY_CODE=ATTR.ATTR16_KEY_CODE    
    LEFT OUTER JOIN ATTR17_MST AT17 (NOLOCK) ON AT17.ATTR17_KEY_CODE=ATTR.ATTR17_KEY_CODE    
    LEFT OUTER JOIN ATTR18_MST AT18 (NOLOCK) ON AT18.ATTR18_KEY_CODE=ATTR.ATTR18_KEY_CODE    
    LEFT OUTER JOIN ATTR19_MST AT19 (NOLOCK) ON AT19.ATTR19_KEY_CODE=ATTR.ATTR19_KEY_CODE    
    LEFT OUTER JOIN ATTR20_MST AT20 (NOLOCK) ON AT20.ATTR20_KEY_CODE=ATTR.ATTR20_KEY_CODE    
    LEFT OUTER JOIN ATTR21_MST AT21 (NOLOCK) ON AT21.ATTR21_KEY_CODE=ATTR.ATTR21_KEY_CODE    
    LEFT OUTER JOIN ATTR22_MST AT22 (NOLOCK) ON AT22.ATTR22_KEY_CODE=ATTR.ATTR22_KEY_CODE    
    LEFT OUTER JOIN ATTR23_MST AT23 (NOLOCK) ON AT23.ATTR23_KEY_CODE=ATTR.ATTR23_KEY_CODE    
    LEFT OUTER JOIN ATTR24_MST AT24 (NOLOCK) ON AT24.ATTR24_KEY_CODE=ATTR.ATTR24_KEY_CODE    
    LEFT OUTER JOIN ATTR25_MST AT25(NOLOCK) ON AT25.ATTR25_KEY_CODE=ATTR.ATTR25_KEY_CODE          
    GROUP BY F.MEMO_NO,F.MEMO_DT, D.AC_NAME,ART.ARTICLE_NO,P1.PARA1_NAME,P2.PARA2_NAME,P3.PARA3_NAME,    
    AT1.ATTR1_KEY_NAME,AT2.ATTR2_KEY_NAME,AT3.ATTR3_KEY_NAME,AT4.ATTR4_KEY_NAME,AT5.ATTR5_KEY_NAME,AT6.ATTR6_KEY_NAME,    
     AT7.ATTR7_KEY_NAME,AT8.ATTR8_KEY_NAME,AT9.ATTR9_KEY_NAME,AT10.ATTR10_KEY_NAME,AT11.ATTR11_KEY_NAME,AT12.ATTR12_KEY_NAME,    
     AT13.ATTR13_KEY_NAME,AT14.ATTR14_KEY_NAME,AT15.ATTR15_KEY_NAME,AT16.ATTR16_KEY_NAME,AT17.ATTR17_KEY_NAME,AT18.ATTR18_KEY_NAME,    
     AT19.ATTR19_KEY_NAME,AT20.ATTR20_KEY_NAME,AT21.ATTR21_KEY_NAME,AT22.ATTR22_KEY_NAME,AT23.ATTR23_KEY_NAME,AT24.ATTR24_KEY_NAME,    
     AT25.ATTR25_KEY_NAME,f.USER_CODE,F.Remarks,F.CANCELLED,    
     SL.DEPT_NAME,SL.address1,SL.address2,SL.REGISTERED_ADD,SL.TIN_NO,SL.loc_gst_no,    
    LEFT(SL.loc_gst_no,2) ,SLA.AREA_NAME,SLA.PINCODE ,SLA.PINCODE,SLA.PINCODE,    
    SLC.CITY,SLS.GST_STATE_NAME,SL.PHONE,sd.sub_section_name ,sm.section_name     
  
  
 ;with CTE_STOCK as  
 (  
 select  a.srNo,bin_name    
    FROM #TMPPL A    
    join sku_names b (nolock) on a.ARTICLE_NO =b.article_no and a.PARA1_NAME =b.para1_name and a.PARA2_NAME =b.para2_name and a.PARA3_NAME =b.para3_name     
    join pmt01106 c (nolock) on b.product_Code =c.product_Code    
    join bin  (nolock) on c.BIN_ID =bin.bin_id     
    where c.quantity_in_stock >0 and c.DEPT_ID =@LocID  
    and c.BIN_ID <>'999'    
    group by a.srNo ,[bin_name]    
 )  
 
 insert into @TBLSTOCK(srNo,bin_name)
 select srNo,bin_name from CTE_STOCK


 SELECT A.SRNO ,  
           (SELECT   BIN_NAME+',' FROM @TBLSTOCK B WHERE A.SRNO=B.SRNO FOR XML PATH('')) AS STOCK_AVAILABLE_BIN  
     into #tmpstock  
 FROM @TBLSTOCK A  
 GROUP BY A.SRNO  
 Update #tmpstock set STOCK_AVAILABLE_BIN=substring(STOCK_AVAILABLE_BIN,1,len(STOCK_AVAILABLE_BIN)-1) where isnull(STOCK_AVAILABLE_BIN,'')<>''  
   
  
  
    
      
      SELECT a.*,b.STOCK_AVAILABLE_BIN  FROM #TMPPL a    
      left join #tmpstock b on a.srno =b.srno     
      ORDER BY ARTICLE_NO     
    
    
 --IF EXISTS(SELECT 'U' FROM SYS.TABLES WHERE NAME ='PICKLIST_PRINTING' AND DATEDIFF(d,create_date,getdate())<>0)    
 --   DROP TABLE PICKLIST_PRINTING    
    
 --IF  OBJECT_ID('PICKLIST_PRINTING','U') IS NULL     
 --BEGIN    
 -- SELECT *     
 -- INTO PICKLIST_PRINTING    
 -- FROM #TMPPL    
 -- WHERE 1=2    
 --  END    
END    
    
    
    