create PROCEDURE SP_MERGE_MIRROR_MSTEOSS_INC
(  
 @NMODE INT		----  0. CLEAR THE TEMP TABLES DATA
				----  1. UPDATE THE INFORMATION FOR ALL SCHEME SETUP MEMOS ONLY RELATED TO TARGET LOCATION
				----  2. UPDATE THE INFORMATION FOR ALL ACTIVE SCHEME SETUP TITLES ONLY RELATED TO TARGET LOCATION
				----  3. UPDATE THE DATA RELATED TO A GIVEN TITLE AT TARGET LOCATION	
)  
----WITH ENCRYPTION
AS  
BEGIN  
   
  --(dinkar) Replace  left(memoid,2) to Location_code  
 BEGIN TRY  
	
  DECLARE @CERRORMSG VARCHAR(1000),@CCURDEPTID varCHAR(5),@CHODEPTID varCHAR(5),@CCMD NVARCHAR(MAX),  
    @CXNMASTERTABLENAME VARCHAR(100),@BPROCEED BIT,@CTABLENAME VARCHAR(100),@CMASTERKEYFIELD VARCHAR(100),  
    @CKEYFIELD VARCHAR(100),@CPARENTTABLENAME VARCHAR(100),@CPARENTPARANAME VARCHAR(100),@CCHILDPARANAME VARCHAR(100),  
    @CWHERECLAUSE VARCHAR(100),@CJOINSTR VARCHAR(1000),@CMEMOID VARCHAR(100),@CFINYEAR VARCHAR(100),  
    @NGRPCHARS INT,@NSERIESCHARS INT,@BSERIESBROKEN BIT,@CPREVMEMOID VARCHAR(40),@CMERGETABLENAME VARCHAR(50),  
    @CFIRSTMEMOID VARCHAR(40),@NPREVMEMOID INT,@NMEMONOLEN INT,@CRETCMD NVARCHAR(MAX),  
    @CDELCHILDTABLENAME VARCHAR(100),@CDELCHILDPARANAME VARCHAR(100),@CDELPARENTPARANAME VARCHAR(100),  
    @CORIGINALTABLENAME VARCHAR(100),@NLOCTYPE INT,@BDONOTMERGE BIT,@CRFXNTYPE VARCHAR(10),  
    @BINSERTONLY BIT,@BLINKEDMASTER BIT,@BPURLOC BIT,@CSOURCELOCID CHAR(2),@BSOURCEPURLOC BIT,  
    @CMISSINGMEMOID VARCHAR(40),@CGRPCODE VARCHAR(20),@BRETVAL BIT,@NPREVNO INT,@CPREVNO VARCHAR(20),  
    @BEMPHEADSUPDATED BIT,@CFILTERCONDITION VARCHAR(100),@CTABLEPREFIX VARCHAR(100),@CXNTYPE VARCHAR(10),  
    @NXNSMERGINGORDER INT,@NSTEP INT,@CBUNDLEMTABLENAME VARCHAR(100),@CBUNDLEDTABLENAME VARCHAR(100),  
    @CSLSMSTTABLENAME VARCHAR(100),@CSLSDETTABLENAME VARCHAR(100),@CLOCSLSSETTABLENAME VARCHAR(100),  
    @CSCHEMEDETTABLENAME VARCHAR(100),@CSCHEMEHHTABLENAME VARCHAR(100),@CSLSBCTABLENAME VARCHAR(100),  
    @CSLSARTTABLENAME VARCHAR(100),@NXNSSENDINGORDER INT,@CSLSMEMONO VARCHAR(20),@BRESTOREMODE BIT
    
   DECLARE @CTEMPMASTERTABLENAME VARCHAR(100), @CTEMPDETAILTABLENAME VARCHAR(100),@CTEMPLOCTABLENAME VARCHAR(100),@cSchemRowIdMerge varchar(50),
			@CTEMPSLSBCTABLENAME VARCHAR(100), @CTEMPSLSARTTABLENAME VARCHAR(100),@CTEMPSLSPARATABLENAME VARCHAR(100),
			@CTEMHAPPYHOURSTABLENAME VARCHAR(100),@CSCH2 VARCHAR(100),@CSCH7 VARCHAR(100),@CSCH6 VARCHAR(100),
			@CSCH14 VARCHAR(100),@CSCH_B1 VARCHAR(100),@CSCH_B2 VARCHAR(100),@CTEMPCONFIGTABLENAME VARCHAR(100),
			@CTEMPSLSBCGETTABLENAME VARCHAR(100), @CTEMPSLSARTGETTABLENAME VARCHAR(100),@CTEMPSLSPARAGETTABLENAME VARCHAR(100),@BRECFOUND BIT
		   ,@CTEMPALLMASTERTABLENAME  VARCHAR(500),@CTEMPALLMASTERCONFIGTABLENAME VARCHAR(500),@CTEMPSCHEMEOPTPARATABLENAME VARCHAR(500)
    
  SET @NSTEP=10  
    
  DECLARE @TRETMSG TABLE  (MEMO_ID VARCHAR(40),ERRMSG VARCHAR(MAX))  
     
  SELECT @CERRORMSG='',@BPROCEED=1,@NMEMONOLEN=10,@CRETCMD='',@CMEMOID='',@CXNTYPE='MSTEOSS',@BEMPHEADSUPDATED=0  
   
  
    
  SET @NSTEP=30  
    
  SET @CFILTERCONDITION=''  
     
  SELECT TOP 1 @CCURDEPTID = VALUE FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION='LOCATION_ID'  
  SELECT TOP 1 @CHODEPTID = VALUE FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION='HO_LOCATION_ID'  

  IF @CCURDEPTID=@CHODEPTID
  BEGIN
	  SET @CERRORMSG='P:SP_MERGE_MIRROR_MSTEOSS_INC, CANNOT CALL MERGING PROC AT HEAD OFFICE'
	  GOTO END_PROC
  END					
      
  SELECT @NLOCTYPE=LOC_TYPE,@BPURLOC=PUR_LOC FROM LOCATION (NOLOCK) WHERE DEPT_ID=@CCURDEPTID  
    


		
  IF @NMODE=0
	GOTO END_PROC

  BEGIN TRANSACTION
      
  SET @CMEMOID='MSTEOSS'  
    
LBLMERGEBEFORE:  
	
	SET @NSTEP=40  

	IF OBJECT_ID('TEMPDB..#TMPFILTERCHANGE','U') IS NOT NULL
		DROP TABLE #TMPFILTERCHANGE	  
	
	SELECT ROW_ID INTO #TMPFILTERCHANGE FROM SCHEME_SETUP_DET WHERE 1=2
	     
	SELECT	   @CTEMPMASTERTABLENAME='MSTEOSS_SCHEME_SETUP_MST_MIRROR',  
			   @CTEMPDETAILTABLENAME='MSTEOSS_SCHEME_SETUP_DET_MIRROR',  
			   @CTEMPLOCTABLENAME='MSTEOSS_SCHEME_SETUP_LOC_MIRROR',  
			   @CTEMPSLSBCTABLENAME='MSTEOSS_SCHEME_SETUP_SLSBC_MIRROR',  
			   @CTEMPSLSBCGETTABLENAME='MSTEOSS_SCHEME_SETUP_SLSBC_GET_MIRROR',  
			   @CTEMPSLSARTTABLENAME='MSTEOSS_SCHEME_SETUP_SLSART_MIRROR',  
			   @CTEMPSLSARTGETTABLENAME='MSTEOSS_SCHEME_SETUP_SLSART_GET_MIRROR',  
			   @CTEMPSLSPARATABLENAME='MSTEOSS_SCHEME_SETUP_SLSPARA_MIRROR',  
			   @CTEMPSLSPARAGETTABLENAME='MSTEOSS_SCHEME_SETUP_SLSPARA_GET_MIRROR',  
			   @CTEMHAPPYHOURSTABLENAME='MSTEOSS_SCHEME_SETUP_HAPPYHOURS_MIRROR',
			   @CSCH2='MSTEOSS_SCHEME_SETUP_SCH0002_1_MIRROR', 
			   @CSCH7='MSTEOSS_SCHEME_SETUP_SCH0007_1_MIRROR', 
			   @CSCH6='MSTEOSS_SCHEME_SETUP_SCH0006_1_MIRROR', 
			   @CSCH14='MSTEOSS_SCHEME_SETUP_SCH0014_1_MIRROR', 
			   @CSCH_B1='MSTEOSS_SCHEME_SETUP_SCHB001_1_MIRROR', 
			   @CSCH_B2='MSTEOSS_SCHEME_SETUP_SCHB002_1_MIRROR', 
			   @CTEMPCONFIGTABLENAME = 'MSTEOSS_CONFIG_MIRROR' ,
			   @CTEMPALLMASTERTABLENAME='MSTEOSS_SCHEME_SETUP_ALLMASTERS_MIRROR' ,
			   @CTEMPALLMASTERCONFIGTABLENAME='MSTEOSS_SCHEME_SETUP_ALLMASTERS_CONFIG_MIRROR',
			   @CTEMPSCHEMEOPTPARATABLENAME='MSTEOSS_SCHEME_SETUP_OPTIMIZED_PARA_MIRROR'  
	     	   
LBLDELETE:  
        
	IF @NMODE IN (1,2,3)
	BEGIN
		SET @NSTEP=50
		IF OBJECT_ID('TEMPDB..#TMPDELSCHEMES','U') IS NOT NULL
			DROP TABLE #TMPDELSCHEMES
		
		SELECT ROW_ID AS SCHEME_SETUP_DET_ROW_ID INTO #TMPDELSCHEMES FROM SCHEME_SETUP_DET (NOLOCK) WHERE 1=2
		
		IF @NMODE=1
			INSERT #TMPDELSCHEMES	( SCHEME_SETUP_DET_ROW_ID )   
			SELECT ROW_ID AS SCHEME_SETUP_DET_ROW_ID
			FROM SCHEME_SETUP_DET A (NOLOCK) 
			LEFT OUTER JOIN MSTEOSS_SCHEME_SETUP_MST_MIRROR B (NOLOCK) ON A.MEMO_NO=B.MEMO_NO 
			WHERE B.MEMO_NO IS NULL  OR B.INACTIVE=1
		ELSE
		IF @NMODE=2
			INSERT #TMPDELSCHEMES	( SCHEME_SETUP_DET_ROW_ID )  
			SELECT A.ROW_ID AS SCHEME_SETUP_DET_ROW_ID
			FROM SCHEME_SETUP_DET A (NOLOCK) 
			LEFT OUTER JOIN MSTEOSS_SCHEMESINFO_MIRROR B (NOLOCK) ON A.ROW_ID=B.SCHEME_SETUP_DET_ROW_ID
			WHERE B.SCHEME_SETUP_DET_ROW_ID IS NULL
		ELSE
		IF @NMODE=3
			INSERT #TMPDELSCHEMES	( SCHEME_SETUP_DET_ROW_ID )  
			SELECT ROW_ID FROM MSTEOSS_SCHEME_SETUP_DET_MIRROR
		
		IF EXISTS (SELECT TOP 1 * FROM #TMPDELSCHEMES)
		BEGIN
			SET @NSTEP=60				
			DELETE A FROM SCHEME_SETUP_ALLMASTERS A JOIN #TMPDELSCHEMES B ON A.SCHEME_SETUP_DET_ROW_ID=B.SCHEME_SETUP_DET_ROW_ID
			DELETE A FROM SCHEME_SETUP_ALLMASTERS_CONFIG A JOIN #TMPDELSCHEMES B ON A.SCHEME_SETUP_DET_ROW_ID=B.SCHEME_SETUP_DET_ROW_ID
			DELETE A FROM  SCHEME_SETUP_SCH0002_1 A JOIN #TMPDELSCHEMES B ON A.SCHEME_SETUP_DET_ROW_ID=B.SCHEME_SETUP_DET_ROW_ID
			DELETE A FROM  SCHEME_SETUP_SCH0006_1 A JOIN #TMPDELSCHEMES B ON A.SCHEME_SETUP_DET_ROW_ID=B.SCHEME_SETUP_DET_ROW_ID
			DELETE A FROM  SCHEME_SETUP_SCH0007_1 A JOIN #TMPDELSCHEMES B ON A.SCHEME_SETUP_DET_ROW_ID=B.SCHEME_SETUP_DET_ROW_ID
			DELETE A FROM  SCHEME_SETUP_SCHB001_1 A  JOIN #TMPDELSCHEMES B ON A.SCHEME_SETUP_DET_ROW_ID=B.SCHEME_SETUP_DET_ROW_ID
			DELETE A FROM  SCHEME_SETUP_SCHB002_1 A  JOIN #TMPDELSCHEMES B ON A.SCHEME_SETUP_DET_ROW_ID=B.SCHEME_SETUP_DET_ROW_ID
			DELETE A FROM  SCHEME_SETUP_SCH0014_1 A JOIN #TMPDELSCHEMES B ON A.SCHEME_SETUP_DET_ROW_ID=B.SCHEME_SETUP_DET_ROW_ID
			DELETE A FROM  SCHEME_SETUP_SLSPARA A  JOIN #TMPDELSCHEMES B ON A.SCHEME_SETUP_DET_ROW_ID=B.SCHEME_SETUP_DET_ROW_ID
			DELETE A FROM  SCHEME_SETUP_SLSPARA_GET A JOIN #TMPDELSCHEMES B ON A.SCHEME_SETUP_DET_ROW_ID=B.SCHEME_SETUP_DET_ROW_ID 
			DELETE A FROM  SCHEME_SETUP_SLSART A JOIN #TMPDELSCHEMES B ON A.SCHEME_SETUP_DET_ROW_ID=B.SCHEME_SETUP_DET_ROW_ID 
			DELETE A FROM  SCHEME_SETUP_SLSART_GET A JOIN #TMPDELSCHEMES B ON A.SCHEME_SETUP_DET_ROW_ID=B.SCHEME_SETUP_DET_ROW_ID 
			DELETE A FROM  SCHEME_SETUP_SLSBC A JOIN #TMPDELSCHEMES B ON A.SCHEME_SETUP_DET_ROW_ID=B.SCHEME_SETUP_DET_ROW_ID
			JOIN SCHEME_SETUP_DET C ON C.ROW_ID=B.SCHEME_SETUP_DET_ROW_ID

		    
			SET @NSTEP=70
			DELETE A FROM  SCHEME_SETUP_SCH0012 A JOIN #TMPDELSCHEMES B ON A.SCHEME_SETUP_DET_ROW_ID=B.SCHEME_SETUP_DET_ROW_ID
		    
			SET @NSTEP=80
			DELETE A FROM  SCHEME_SETUP_SLSBC_GET A JOIN #TMPDELSCHEMES B ON A.SCHEME_SETUP_DET_ROW_ID=B.SCHEME_SETUP_DET_ROW_ID 
		    
		    IF @NMODE IN (1,2)
		    BEGIN	
				SET @NSTEP=90
				DELETE A FROM SCHEME_SETUP_DET A JOIN #TMPDELSCHEMES B ON B.SCHEME_SETUP_DET_ROW_ID=A.ROW_ID
				
				IF @NMODE=1
					DELETE A FROM SCHEME_SETUP_MST A LEFT OUTER JOIN SCHEME_SETUP_DET B ON A.MEMO_NO=B.MEMO_NO
					WHERE B.MEMO_NO IS NULL
			END
		END
				
		IF @NMODE=1 ----- UPDATE THE INFORMATION FOR ALL SCHEME SETUP MEMOS ONLY RELATED TO TARGET LOCATION
		BEGIN
			SET @NSTEP=100
			DELETE FROM MSTEOSS_SCHEME_SETUP_MST_MIRROR WHERE INACTIVE=1 
			
			DELETE A FROM MSTEOSS_SCHEME_SETUP_HAPPYHOURS_MIRROR A LEFT OUTER JOIN 
			MSTEOSS_SCHEME_SETUP_MST_MIRROR B (NOLOCK) ON A.MEMO_NO=B.MEMO_NO
			WHERE B.MEMO_NO IS NULL
			
			SET @NSTEP=110
			DELETE A FROM SCHEME_SETUP_HAPPYHOURS A LEFT OUTER JOIN 
			MSTEOSS_SCHEME_SETUP_MST_MIRROR B (NOLOCK) ON A.MEMO_NO=B.MEMO_NO
			WHERE B.MEMO_NO IS NULL
			
			UPDATE MSTEOSS_SCHEME_SETUP_MST_MIRROR SET LOC_APPLICABLE_MODE=1
			
			SET @NSTEP=120
			EXEC UPDATEMASTERXN_MIRROR 
			@CSOURCEDB='',
			@CSOURCETABLE=@CTEMPMASTERTABLENAME,
			@CDESTDB='',
			@CDESTTABLE='SCHEME_SETUP_MST',
			@CKEYFIELD1='MEMO_NO',
			@CKEYFIELD2='',
			@CKEYFIELD3='',
			@LINSERTONLY=0,
			@CFILTERCONDITION='',
			@LUPDATEONLY=0,
			@BALWAYSUPDATE=1			

							
			SET @NSTEP=130
			EXEC UPDATEMASTERXN_MIRROR 
			@CSOURCEDB='',
			@CSOURCETABLE=@CTEMHAPPYHOURSTABLENAME,
			@CDESTDB='',
			@CDESTTABLE='SCHEME_SETUP_HAPPYHOURS',
			@CKEYFIELD1='ROW_ID',
			@CKEYFIELD2='',
			@CKEYFIELD3='',
			@LINSERTONLY=0,
			@CFILTERCONDITION='',
			@LUPDATEONLY=0,
			@BALWAYSUPDATE=1

			SET @NSTEP=140	
			EXEC UPDATEMASTERXN_MIRROR 
			@CSOURCEDB='',
			@CSOURCETABLE=@CTEMPCONFIGTABLENAME,
			@CDESTDB='',
			@CDESTTABLE='CONFIG',
			@CKEYFIELD1='CONFIG_OPTION',
			@CKEYFIELD3='',
			@LINSERTONLY=0,
			@CFILTERCONDITION='',
			@LUPDATEONLY=0,
			@BALWAYSUPDATE=1
			
		END	
		ELSE
		IF @NMODE=2
		BEGIN   ---- AFTER DELETING TITLES AT LOCATION (WHICH ARE NOT FOUND AT HO OR INACTIVE) 
				---- RETURN THE LIST OF TITLES WHICH ARE NOT FOUND OR MODIFIED
				---- TO BE SYNCH FROM HO ONE BY ONE
			SET @NSTEP=150	
			SELECT A.SCHEME_SETUP_DET_ROW_ID,A.SCHEME_NAME,'' AS ERRMSG FROM MSTEOSS_SCHEMESINFO_MIRROR A
			LEFT OUTER JOIN SCHEME_SETUP_DET B ON A.SCHEME_SETUP_DET_ROW_ID=B.ROW_ID
			WHERE A.LAST_UPDATE<>ISNULL(B.LAST_UPDATE,'')
			
		END
		ELSE
		IF @NMODE=3	----- SYNCH THE SCHEME DETAILS FOR A GIVEN TITLE
		BEGIN
			SET @NSTEP=160
			
			INSERT #TMPFILTERCHANGE (ROW_ID)
			SELECT A.ROW_ID FROM MSTEOSS_SCHEME_SETUP_DET_MIRROR A 

			---- Had to comment this code Because at Da milano frequent problem of Sku_active_titles
			---- not getting populated on Scheme merging (Date :14-03-2023)

			--LEFT OUTER JOIN SCHEME_SETUP_DET B ON A.ROW_ID=B.ROW_ID
			--WHERE ISNULL(A.FILTER_CHANGE_LAST_UPDATE,'')<>ISNULL(B.FILTER_CHANGE_LAST_UPDATE,'')
			--AND  A.FILTER_MODE<=1 AND ISNULL(A.GET_FILTER_MODE,0)<=1
			--UNION
			--SELECT A.ROW_ID FROM MSTEOSS_SCHEME_SETUP_DET_MIRROR A 
			--WHERE A.FILTER_MODE>1 OR ISNULL(A.GET_FILTER_MODE,0)>1
		END				
		
		IF @NMODE IN(1,2)
			GOTO END_PROC
		
	END	
	
LBLMERGE:  
	
    PRINT 'SCHEME_SETUP_MST'
LBLMERGETABLES:
     
	SET @nStep=162
	EXEC SP3S_VALIDATE_EOSSDATA
	@cErrormsg=@CERRORMSG OUTPUT

	--select @CERRORMSG errmsg_temp
	IF ISNULL(@CERRORMSG,'')<>''
		GOTO END_PROC

	SET @NSTEP=165

	SET @cSchemRowIdMerge=''
	IF @nMode=3
	BEGIN
		SELECT TOP 1 @cSchemRowIdMerge=row_id FROM  MSTEOSS_SCHEME_SETUP_DET_MIRROR
		IF ISNULL(@cSchemRowIdMerge,'')=''
			SELECT TOP 1 @cSchemRowIdMerge=row_id FROM  MSTEOSS_SCHEME_SETUP_SLSBC_MIRROR

	END

	EXEC UPDATEMASTERXN_MIRROR 
	@CSOURCEDB='',
	@CSOURCETABLE=@CTEMPDETAILTABLENAME,
	@CDESTDB='',
	@CDESTTABLE='SCHEME_SETUP_DET',
	@CKEYFIELD1='ROW_ID',
	@CKEYFIELD2='',
	@CKEYFIELD3='',
	@LINSERTONLY=0,
	@CFILTERCONDITION='',
	@LUPDATEONLY=0,
	@BALWAYSUPDATE=1

	SET @NSTEP=180
	EXEC UPDATEMASTERXN_MIRROR 
	@CSOURCEDB='',
	@CSOURCETABLE=@CTEMPSLSBCTABLENAME,
	@CDESTDB='',
	@CDESTTABLE='SCHEME_SETUP_SLSBC',
	@CKEYFIELD1='ROW_ID',
	@CKEYFIELD2='',
	@CKEYFIELD3='',
	@LINSERTONLY=0,
	@CFILTERCONDITION='',
	@LUPDATEONLY=0,
	@BALWAYSUPDATE=1

				
	SET @NSTEP=190
	EXEC UPDATEMASTERXN_MIRROR 
	@CSOURCEDB='',
	@CSOURCETABLE=@CTEMPSLSBCGETTABLENAME,
	@CDESTDB='',
	@CDESTTABLE='SCHEME_SETUP_SLSBC_GET',
	@CKEYFIELD1='ROW_ID',
	@CKEYFIELD2='',
	@CKEYFIELD3='',
	@LINSERTONLY=0,
	@CFILTERCONDITION='',
	@LUPDATEONLY=0,
	@BALWAYSUPDATE=1
	
	

	SET @NSTEP=200
	EXEC UPDATEMASTERXN_MIRROR 
	@CSOURCEDB='',
	@CSOURCETABLE=@CTEMPSLSARTTABLENAME,
	@CDESTDB='',
	@CDESTTABLE='SCHEME_SETUP_SLSART',
	@CKEYFIELD1='ROW_ID',
	@CKEYFIELD2='',
	@CKEYFIELD3='',
	@LINSERTONLY=0,
	@CFILTERCONDITION='',
	@LUPDATEONLY=0,
	@BALWAYSUPDATE=1
		
	SET @NSTEP=210
	EXEC UPDATEMASTERXN_MIRROR 
	@CSOURCEDB='',
	@CSOURCETABLE=@CTEMPSLSARTGETTABLENAME,
	@CDESTDB='',
	@CDESTTABLE='SCHEME_SETUP_SLSART_GET',
	@CKEYFIELD1='ROW_ID',
	@CKEYFIELD2='',
	@CKEYFIELD3='',
	@LINSERTONLY=0,
	@CFILTERCONDITION='',
	@LUPDATEONLY=0,
	@BALWAYSUPDATE=1
		
	SET @NSTEP=220	
	EXEC UPDATEMASTERXN_MIRROR 
	@CSOURCEDB='',
	@CSOURCETABLE=@CTEMPSLSPARATABLENAME,
	@CDESTDB='',
	@CDESTTABLE='SCHEME_SETUP_SLSPARA',
	@CKEYFIELD1='ROW_ID',
	@CKEYFIELD2='',
	@CKEYFIELD3='',
	@LINSERTONLY=0,
	@CFILTERCONDITION='',
	@LUPDATEONLY=0,
	@BALWAYSUPDATE=1

		
	SET @NSTEP=230
	EXEC UPDATEMASTERXN_MIRROR 
	@CSOURCEDB='',
	@CSOURCETABLE=@CTEMPSLSPARAGETTABLENAME,
	@CDESTDB='',
	@CDESTTABLE='SCHEME_SETUP_SLSPARA_GET',
	@CKEYFIELD1='ROW_ID',
	@CKEYFIELD2='',
	@CKEYFIELD3='',
	@LINSERTONLY=0,
	@CFILTERCONDITION='',
	@LUPDATEONLY=0,
	@BALWAYSUPDATE=1

			
	SET @NSTEP=240
	EXEC UPDATEMASTERXN_MIRROR 
	@CSOURCEDB='',
	@CSOURCETABLE=@CSCH2,
	@CDESTDB='',
	@CDESTTABLE='SCHEME_SETUP_SCH0002_1',
	@CKEYFIELD1='ROW_ID',
	@CKEYFIELD2='',
	@CKEYFIELD3='',
	@LINSERTONLY=0,
	@CFILTERCONDITION='',
	@LUPDATEONLY=0,
	@BALWAYSUPDATE=1					

	SET @NSTEP=250
	EXEC UPDATEMASTERXN_MIRROR 
	@CSOURCEDB='',
	@CSOURCETABLE=@CSCH7,
	@CDESTDB='',
	@CDESTTABLE='SCHEME_SETUP_SCH0007_1',
	@CKEYFIELD1='ROW_ID',
	@CKEYFIELD2='',
	@CKEYFIELD3='',
	@LINSERTONLY=0,
	@CFILTERCONDITION='',
	@LUPDATEONLY=0,
	@BALWAYSUPDATE=1	

	SET @NSTEP=260
	EXEC UPDATEMASTERXN_MIRROR 
	@CSOURCEDB='',
	@CSOURCETABLE='MSTEOSS_SCHEME_SETUP_SCH0012_MIRROR',
	@CDESTDB='',
	@CDESTTABLE='SCHEME_SETUP_SCH0012',
	@CKEYFIELD1='ROW_ID',
	@CKEYFIELD2='',
	@CKEYFIELD3='',
	@LINSERTONLY=0,
	@CFILTERCONDITION='',
	@LUPDATEONLY=0,
	@BALWAYSUPDATE=1	
	
	SET @NSTEP=270
	EXEC UPDATEMASTERXN_MIRROR 
	@CSOURCEDB='',
	@CSOURCETABLE=@CSCH6,
	@CDESTDB='',
	@CDESTTABLE='SCHEME_SETUP_SCH0006_1',
	@CKEYFIELD1='ROW_ID',
	@CKEYFIELD2='',
	@CKEYFIELD3='',
	@LINSERTONLY=0,
	@CFILTERCONDITION='',
	@LUPDATEONLY=0,
	@BALWAYSUPDATE=1					

	SET @NSTEP=275
	EXEC UPDATEMASTERXN_MIRROR 
	@CSOURCEDB='',
	@CSOURCETABLE=@CSCH14,
	@CDESTDB='',
	@CDESTTABLE='SCHEME_SETUP_SCH0014_1',
	@CKEYFIELD1='SCHEME_SETUP_DET_ROW_ID',
	@CKEYFIELD2='',
	@CKEYFIELD3='',
	@LINSERTONLY=0,
	@CFILTERCONDITION='',
	@LUPDATEONLY=0,
	@BALWAYSUPDATE=1	

	SET @NSTEP=280
	EXEC UPDATEMASTERXN_MIRROR 
	@CSOURCEDB='',
	@CSOURCETABLE=@CSCH_B1,
	@CDESTDB='',
	@CDESTTABLE='SCHEME_SETUP_SCHB001_1',
	@CKEYFIELD1='ROW_ID',
	@CKEYFIELD2='',
	@CKEYFIELD3='',
	@LINSERTONLY=0,
	@CFILTERCONDITION='',
	@LUPDATEONLY=0,
	@BALWAYSUPDATE=1					

	SET @NSTEP=285
	EXEC UPDATEMASTERXN_MIRROR 
	@CSOURCEDB='',
	@CSOURCETABLE=@CSCH_B2,
	@CDESTDB='',
	@CDESTTABLE='SCHEME_SETUP_SCHB002_1',
	@CKEYFIELD1='ROW_ID',
	@CKEYFIELD2='',
	@CKEYFIELD3='',
	@LINSERTONLY=0,
	@CFILTERCONDITION='',
	@LUPDATEONLY=0,
	@BALWAYSUPDATE=1					
					
	SET @NSTEP=290
	EXEC UPDATEMASTERXN_MIRROR 
	@CSOURCEDB='',
	@CSOURCETABLE=@CTEMPLOCTABLENAME,
	@CDESTDB='',
	@CDESTTABLE='SCHEME_SETUP_LOC',
	@CKEYFIELD1='MEMO_NO',
	 @CKEYFIELD2='',
	@CKEYFIELD3='',
	@LINSERTONLY=0,
	@CFILTERCONDITION='',
	@LUPDATEONLY=0,
	@BALWAYSUPDATE=1
						
	
	
	SET @NSTEP=300
	EXEC UPDATEMASTERXN_MIRROR 
	@CSOURCEDB='',
	@CSOURCETABLE=@CTEMPALLMASTERTABLENAME,
	@CDESTDB='',
	@CDESTTABLE='SCHEME_SETUP_ALLMASTERS',
	@CKEYFIELD1='ROW_ID',
	@CKEYFIELD2='',
	@CKEYFIELD3='',
	@LINSERTONLY=0,
	@CFILTERCONDITION='',
	@LUPDATEONLY=0,
	@BALWAYSUPDATE=1
	
	SET @NSTEP=310
	
	EXEC UPDATEMASTERXN_MIRROR 
	@CSOURCEDB='',
	@CSOURCETABLE=@CTEMPALLMASTERCONFIGTABLENAME,
	@CDESTDB='',
	@CDESTTABLE='SCHEME_SETUP_ALLMASTERS_CONFIG',
	@CKEYFIELD1='SCHEME_SETUP_DET_ROW_ID',
	@CKEYFIELD2='',
	@CKEYFIELD3='',
	@LINSERTONLY=0,
	@CFILTERCONDITION='',
	@LUPDATEONLY=0,
	@BALWAYSUPDATE=1

	SET @NSTEP=320
	UPDATE MSTEOSS_REP_MST_MIRROR SET USER_CODE='0000000'
	
	SET @NSTEP=325
	EXEC UPDATEMASTERXN_MIRROR 
	@CSOURCEDB='',
	@CSOURCETABLE='MSTEOSS_REP_MST_MIRROR',
	@CDESTDB='',
	@CDESTTABLE='REP_MST',
	@CKEYFIELD1='REP_ID',
	@CKEYFIELD2='',
	@CKEYFIELD3='',
	@LINSERTONLY=1,
	@CFILTERCONDITION='',
	@LUPDATEONLY=0,
	@BALWAYSUPDATE=1
			
	SET @NSTEP=330
	EXEC UPDATEMASTERXN_MIRROR 
	@CSOURCEDB='',
	@CSOURCETABLE='MSTEOSS_REP_FILTER_MIRROR',
	@CDESTDB='',
	@CDESTTABLE='REP_FILTER',
	@CKEYFIELD1='REP_ID',
	@CKEYFIELD2='',
	@CKEYFIELD3='',
	@LINSERTONLY=1,
	@CFILTERCONDITION='',
	@LUPDATEONLY=0,
	@BALWAYSUPDATE=1

	SET @NSTEP=340
	EXEC UPDATEMASTERXN_MIRROR 
	@CSOURCEDB='',
	@CSOURCETABLE='MSTEOSS_REP_FILTER_DET_MIRROR',
	@CDESTDB='',
	@CDESTTABLE='REP_FILTER_DET',
	@CKEYFIELD1='REP_ID',
	@CKEYFIELD2='',
	@CKEYFIELD3='',
	@LINSERTONLY=0,
	@CFILTERCONDITION='',
	@LUPDATEONLY=1,
	@BALWAYSUPDATE=1

	SET @nStep=345
	EXEC SP3S_VALIDATE_EOSSDATA
	@bChkFinalData=1,
	@cErrormsg=@CERRORMSG OUTPUT

	IF ISNULL(@CERRORMSG,'')<>''
		GOTO END_PROC

	
	SET @NSTEP=350
	DECLARE @CENABLEOPTIMIZEDSCHEMES VARCHAR(2)
	SELECT TOP 1 @CENABLEOPTIMIZEDSCHEMES=VALUE FROM CONFIG WHERE CONFIG_OPTION='ENABLE_OPTIMIZED_EOSS_SCHEMES'		
			
	IF ISNULL(@CENABLEOPTIMIZEDSCHEMES,'')='1'
	BEGIN
		SET @NSTEP=360
		
		IF OBJECT_ID('TEMPDB..#TMPCMD','U') IS NOT NULL
			DROP TABLE #TMPCMD 
		
		SELECT TOP 1 PRODUCT_CODE INTO #TMPCMD FROM PMT01106 WHERE 1=2
		
		SET @NSTEP=370			
		EXEC SP3S_GETFILTERED_TITLES
		@NMODE=@NMODE,
		@CERRORMSG=@CERRORMSG OUTPUT
	END
	
	GOTO END_PROC
												
END TRY			

BEGIN CATCH
	SET @CERRORMSG ='ERROR IN PROCEDURE SP_MERGE_MIRROR_MSTEOSS_INC '+(CASE WHEN ISNULL(@cSchemRowIdMerge,'')<>'' THEN ' while merging SchemeRowId:'+@cSchemRowIdMerge ELSE '' END)+
	' AT STEP#'+STR(@NSTEP)+' || ' + ERROR_MESSAGE()
END CATCH
    
END_PROC:

	IF @@TRANCOUNT>0
	BEGIN
		IF ISNULL(@CERRORMSG,'')=''
			COMMIT TRANSACTION
		ELSE
			ROLLBACK 	
	END	

		DECLARE @bDonotDelete bit=0

		--IF EXISTS (SELECT TOP 1 row_id FROM msteoss_scheme_Setup_det_mirror where row_id='B411E41E-FFC9-43C6-A925-F03A63BF216D')
		--	SET @bDonotDelete=1
		
		IF @bDonotDelete=0
		BEGIN
			DELETE FROM MSTEOSS_SCHEME_SETUP_SCH0002_1_MIRROR
			DELETE FROM MSTEOSS_SCHEME_SETUP_SCH0006_1_MIRROR
			DELETE FROM MSTEOSS_SCHEME_SETUP_SCH0007_1_MIRROR
			DELETE FROM MSTEOSS_SCHEME_SETUP_SCH0014_1_MIRROR
			DELETE FROM MSTEOSS_SCHEME_SETUP_SCHB001_1_MIRROR
			DELETE FROM MSTEOSS_SCHEME_SETUP_SCHB002_1_MIRROR
			DELETE FROM MSTEOSS_SCHEME_SETUP_SCH0012_MIRROR 
			DELETE FROM MSTEOSS_SCHEME_SETUP_SLSPARA_MIRROR 
			DELETE FROM MSTEOSS_SCHEME_SETUP_SLSPARA_GET_MIRROR 
			DELETE FROM MSTEOSS_SCHEME_SETUP_SLSART_MIRROR 
			DELETE FROM MSTEOSS_SCHEME_SETUP_SLSART_GET_MIRROR 
			DELETE FROM MSTEOSS_SCHEME_SETUP_SLSBC_MIRROR
			DELETE FROM MSTEOSS_SCHEME_SETUP_SLSBC_GET_MIRROR
			DELETE FROM MSTEOSS_SCHEME_SETUP_HAPPYHOURS_MIRROR 			  		  
			DELETE FROM MSTEOSS_SCHEME_SETUP_LOC_MIRROR 
			DELETE FROM MSTEOSS_SCHEME_SETUP_DET_MIRROR
			DELETE FROM MSTEOSS_SCHEME_SETUP_MST_MIRROR
			DELETE FROM MSTEOSS_CONFIG_MIRROR
			DELETE FROM MSTEOSS_SCHEME_SETUP_ALLMASTERS_MIRROR
			DELETE FROM MSTEOSS_SCHEME_SETUP_ALLMASTERS_CONFIG_MIRROR
			DELETE FROM MSTEOSS_SCHEME_SETUP_OPTIMIZED_PARA_MIRROR
			DELETE FROM MSTEOSS_SCHEMESINFO_MIRROR
			DELETE FROM MSTEOSS_REP_MST_MIRROR
			DELETE FROM MSTEOSS_REP_FILTER_MIRROR
			DELETE FROM MSTEOSS_REP_FILTER_DET_MIRROR
		END
	
	IF @NMODE<>2  OR ISNULL(@CERRORMSG,'')<>''
		SELECT 'MSTEOSS' AS MEMO_ID,ISNULL(@CERRORMSG,'') AS ERRMSG    
    
END  
--- END OF CREATING PROCEDURE SP_MERGE_MIRROR_MSTEOSS_INC