CREATE PROCEDURE DBSALE_KPI_SALE_BY_MONTH_LAST_YEAR_COMPARISION(@MODE VARCHAR(1)='M',@LOC VARCHAR(MAX)='',@DT VARCHAR(10))
AS    
BEGIN    
   SET NOCOUNT ON
   SELECT DISTINCT PERIOD Month_Yr,FTD_CY CY,FTD_LY LY
   FROM DBSALE_KPI_DYNAMIC_DATA	
   WHERE REP_SCRIPT='DBSALE_KPI_SALE_BY_MONTH_LAST_YEAR_COMPARISION'
   AND DT=@DT
   AND (@LOC='' OR DEPT_ID IN (SELECT CODE FROM DBO.FN_SPLIT_VALUE(@LOC)))
   SET NOCOUNT OFF
END--PROCEDURE DBSALE_KPI_SALE_BY_MONTH_LAST_YEAR_COMPARISION
