CREATE PROCEDURE SP3S_UPDATE_CUS_GST_NO_CMM
AS
BEGIN
	IF NOT EXISTS (SELECT TOP 1 * FROM config_tempdataupd(NOLOCK) WHERE TEMPDATA_OPTION='UPDATE_CMM_PARTYGSTNO' )
	BEGIN
		UPDATE A SET Party_Gst_No =ISNULL(B.CUS_GST_NO ,'')
		FROM CMM01106 A (NOLOCK)
		JOIN CUSTDYM  B (NOLOCK) ON A.CUSTOMER_CODE  =B.CUSTOMER_CODE 
		WHERE A.CM_DT >='2017-07-01' AND ISNULL(A.Party_Gst_No,'')=''
		AND ISNULL(B.CUS_GST_NO ,'')<>''
	END

	INSERT config_tempdataupd	( TEMPDATA_OPTION, last_update )
	SELECT 'UPDATE_CMM_PARTYGSTNO'  config_option,GETDATE() AS LAST_UPDATE

END  
