CREATE PROCEDURE SP3S_CREATEINDEX_UPLOADTABLES
(
 @NMODE INT
)
AS
BEGIN
    
    IF EXISTS(SELECT TOP 1 'U' FROM CONFIG WHERE  CONFIG_OPTION ='INDEX_CREATE_UPLOAD_TABLES' AND VALUE=1)
    RETURN
    
    
    DECLARE @DTSQL NVARCHAR(MAX),@CTABLENAME VARCHAR(100),
    @CINDEXNAME VARCHAR(100)
    IF OBJECT_ID ('TEMPDB..#TMPTABLEINDEX','U') IS NOT NULL
       DROP TABLE #TMPTABLEINDEX
       
    SELECT CAST('' AS VARCHAR(100)) AS TABLENAME,
    INDEXNAME=CAST('' AS VARCHAR(100))
    INTO #TMPTABLEINDEX
    WHERE 1=2
    
    INSERT INTO #TMPTABLEINDEX(TABLENAME  )
    SELECT 'SLS_CMM01106_UPLOAD' UNION ALL
    SELECT 'SLS_CMD01106_UPLOAD' UNION ALL
    SELECT 'SLS_PAYMODE_XN_DET_UPLOAD' UNION ALL
   -- SELECT 'SLS_PACK_SLIP_R_UPLOAD' UNION ALL
    SELECT 'SLS_IMAGE_XN_DET_UPLOAD' UNION ALL
    SELECT 'SLS_CMM_FLIGHT_UPLOAD' UNION ALL
    SELECT 'SLS_COUPON_REDEMPTION_INFO_UPLOAD' UNION ALL
    SELECT 'SLS_GV_MST_REDEMPTION_UPLOAD' UNION ALL
    SELECT 'SLS_APM01106_REF_UPLOAD' UNION ALL
    SELECT 'RPS_RPS_MST_UPLOAD' UNION ALL
    SELECT 'RPS_RPS_DET_UPLOAD' 
 
    UPDATE #TMPTABLEINDEX SET INDEXNAME='IX_'+TABLENAME+'_SP_ID'
     
     IF OBJECT_ID ('TEMPDB..#TMPDROPINDEX','U') IS NOT NULL
         DROP TABLE #TMPDROPINDEX
         
	 SELECT I.NAME AS INDEXNAME,T.NAME AS TABLENAME
	 INTO #TMPDROPINDEX
	 FROM SYS.INDEXES I 
	 JOIN SYS.TABLES T ON I.OBJECT_ID=T.OBJECT_ID
	 JOIN SYS.COLUMNS S ON T.OBJECT_ID=S.OBJECT_ID    
	 AND CASE WHEN  IS_PRIMARY_KEY = 1 AND I.TYPE = 1 THEN 0 ELSE 1 END = 1   
	 AND IS_UNIQUE_CONSTRAINT = 0   AND IS_PRIMARY_KEY = 0 
	 JOIN #TMPTABLEINDEX TMP ON TMP.TABLENAME =T.NAME
	 WHERE I.NAME IS NOT NULL 
	 AND S.NAME ='SP_ID'
	 
	 
	 IF @NMODE=1
	 BEGIN
	 
		 WHILE EXISTS(SELECT TOP 1 'U' FROM #TMPDROPINDEX)
		 BEGIN
			 SELECT TOP 1 @CTABLENAME =TABLENAME  ,@CINDEXNAME= INDEXNAME FROM  #TMPDROPINDEX
			 
			SET @DTSQL=N'DROP INDEX '+@CINDEXNAME+' ON '+@CTABLENAME
			PRINT @DTSQL
			EXEC SP_EXECUTESQL @DTSQL
		    
			DELETE FROM #TMPDROPINDEX WHERE TABLENAME=@CTABLENAME AND INDEXNAME =@CINDEXNAME
		 END
		 
	 END
	 ELSE
	 BEGIN
	 SET @CTABLENAME=''
	 SET @CINDEXNAME=''
	 
	 WHILE EXISTS(SELECT TOP 1 'U' FROM #TMPTABLEINDEX)
	 BEGIN
	       SELECT TOP 1 @CTABLENAME =TABLENAME  ,@CINDEXNAME= INDEXNAME FROM  #TMPTABLEINDEX
	    
	    IF NOT EXISTS(SELECT TOP 1'U' FROM #TMPDROPINDEX WHERE TABLENAME =@CTABLENAME)
	    AND OBJECT_ID(@CTABLENAME,'U') IS NOT NULL
	    BEGIN
			SET @DTSQL=N'CREATE INDEX '+@CINDEXNAME+' ON '+@CTABLENAME+' (SP_ID)'
			PRINT @DTSQL
			EXEC SP_EXECUTESQL @DTSQL
	    END
	    
        DELETE FROM #TMPTABLEINDEX WHERE TABLENAME=@CTABLENAME AND INDEXNAME =@CINDEXNAME
	 END
	 
	  INSERT CONFIG	( CONFIG_OPTION, VALUE, ROW_ID, LAST_UPDATE,  ReMARKS )  
	  SELECT 	'INDEX_CREATE_UPLOAD_TABLES' AS  CONFIG_OPTION,1 AS VALUE, 
	  NEWID() AS ROW_ID,GETDATE() AS  LAST_UPDATE,'' AS REMARKS 
 
    END
	
   
END
