CREATE PROCEDURE SP3S_GET_JWI_BOM_ISSUED
(
	@CWHERE VARCHAR(MAX),
	@cLocID	VARCHAR(10)
)
AS
BEGIN
--DECLARE @CWHERE VARCHAR(MAX)='AK001'
;WITH BOM_ISSUE_SUMMARY
AS
(

	SELECT A.*,B.MEMO_ID AS ORD_PLAN_MEMO_ID,B.ROW_ID AS ORD_PLAN_DET_ROW_ID,
	CONVERT(NUMERIC(14,2),((A.AVG_QUANTITY+A.ADD_AVG_QUANTITY) * B.ISSUED_QTY)) AS JW_REQ_QTY
	,B.ISSUE_ID
	FROM ORD_PLAN_BOM_DET A (NOLOCK)
	JOIN
	(
		SELECT A.JOB_CODE, A1.ISSUE_ID,D.MEMO_ID,C.ROW_ID,C.ARTICLE_CODE,C.PARA1_CODE,C.PARA2_CODE,SUM(A.QUANTITY) AS ISSUED_QTY
		FROM JOBWORK_ISSUE_DET A (NOLOCK)
		JOIN JOBWORK_ISSUE_MST A1 (NOLOCK) ON A1.ISSUE_ID=A.ISSUE_ID 
		JOIN ORD_PLAN_BARCODE_DET B (NOLOCK) ON B.PRODUCT_CODE=A.PRODUCT_CODE
		JOIN ORD_PLAN_DET C (NOLOCK) ON C.ROW_ID=B.REFROW_ID
		JOIN ORD_PLAN_MST D (NOLOCK) ON D.MEMO_ID=C.MEMO_ID
		WHERE D.CANCELLED=0 AND A1.CANCELLED=0 AND A1.agency_code=@CWHERE AND  A1.location_Code = @cLocID
		GROUP BY A.JOB_CODE,A1.ISSUE_ID,D.MEMO_ID,C.ROW_ID,C.ARTICLE_CODE,C.PARA1_CODE,C.PARA2_CODE
	)B ON B.ROW_ID=A.REF_ROW_ID and a.job_code=b.job_code
	JOIN JOBWORK_ISSUE_BOM C (NOLOCK) ON C.ISSUE_ID=B.ISSUE_ID
	AND C.ARTICLE_CODE=A.ARTICLE_CODE 
	AND C.PARA1_CODE=A.PARA1_CODE 
	AND C.PARA2_CODE=A.PARA2_CODE
)
--SELECT T.* ,K.SECTION_NAME, J.SUB_SECTION_NAME, C.PARA1_NAME,        
--	 D.PARA2_NAME,E.PARA3_NAME,F.PARA4_NAME,G.PARA5_NAME,H.PARA6_NAME,B.ARTICLE_NO,         
--	 B.ARTICLE_NAME,I.UOM_NAME,
--	 CONVERT(NUMERIC(14,2),(T.JW_REQ_QTY)-ISNULL(X.ISSUED_QTY,0)) AS REQ_QTY,
--	 ISNULL(X.ISSUED_QTY,0) AS ISSUED_QTY 
SELECT T.issue_id, T.ARTICLE_CODE,T.PARA1_CODE,T.PARA2_CODE ,C.PARA1_NAME,        
	 D.PARA2_NAME,B.ARTICLE_NO,B.ARTICLE_NAME,I.UOM_NAME,
	  SUM(QUANTITY) AS QUANTITY,ISNULL(SUM(ISSUED_QTY),0) AS ISSUED_QTY,CONVERT(NUMERIC(14,2),SUM((T.JW_REQ_QTY)-ISNULL(X.ISSUED_QTY,0))) AS REQ_QTY,
	  CAST(0 AS NUMERIC(14,2)) AS SCANNED_QTY
	  ,SUM(JW_REQ_QTY) AS JW_REQ_QTY
INTO #SP3S_GET_JWI_BOM_ISSUED	  
FROM BOM_ISSUE_SUMMARY T (NOLOCK)
JOIN ARTICLE B (NOLOCK) ON T.ARTICLE_CODE = B.ARTICLE_CODE         
JOIN PARA1 C (NOLOCK) ON T.PARA1_CODE = C.PARA1_CODE        
JOIN PARA2 D (NOLOCK) ON T.PARA2_CODE = D.PARA2_CODE        
JOIN PARA3 E (NOLOCK) ON T.PARA3_CODE = E.PARA3_CODE        
JOIN PARA4 F (NOLOCK) ON T.PARA4_CODE = F.PARA4_CODE        
JOIN PARA5 G (NOLOCK) ON T.PARA5_CODE = G.PARA5_CODE        
JOIN PARA6 H (NOLOCK) ON T.PARA6_CODE = H.PARA6_CODE        
JOIN UOM I (NOLOCK) ON B.UOM_CODE = I.UOM_CODE        
JOIN SECTIOND J (NOLOCK) ON B.SUB_SECTION_CODE = J.SUB_SECTION_CODE        
JOIN SECTIONM K (NOLOCK) ON J.SECTION_CODE = K.SECTION_CODE 
LEFT OUTER JOIN
(
	SELECT A5.JOBWORK_ISSUE_ID,A1.MEMO_ID, A1.REF_ROW_ID,A1.ARTICLE_CODE,A1.PARA1_CODE,A1.PARA2_CODE,SUM(A6.QUANTITY) AS ISSUED_QTY
	FROM BOM_ISSUE_DET A4 (NOLOCK) 
	JOIN BOM_ISSUE_MST A5  (NOLOCK) ON A5.ISSUE_ID=A4.ISSUE_ID
	JOIN BOM_ISSUE_REF A6  (NOLOCK) ON A5.ISSUE_ID=A6.BOM_ISSUE_ID AND A4.ROW_ID=A6.BOM_DET_ROW_ID
	JOIN ORD_PLAN_BOM_DET A1  (NOLOCK) ON A1.ROW_ID=A6.ORD_PLAN_BOM_DET_ROW_ID
	WHERE A5.CANCELLED=0 AND A5.location_Code=@cLocID--AND A1.MEMO_ID='AK0111900000AK00000061'
	GROUP BY A5.JOBWORK_ISSUE_ID,A1.MEMO_ID, A1.REF_ROW_ID,A1.ARTICLE_CODE,A1.PARA1_CODE,A1.PARA2_CODE--,A6.ORD_PLAN_BOM_DET_ROW_ID
)X ON X.REF_ROW_ID=T.ORD_PLAN_DET_ROW_ID	AND X.MEMO_ID=T.ORD_PLAN_MEMO_ID
AND X.ARTICLE_CODE=T.ARTICLE_CODE AND X.PARA1_CODE=T.PARA1_CODE AND X.PARA2_CODE=T.PARA2_CODE
AND X.JOBWORK_ISSUE_ID=T.issue_id
GROUP BY T.Issue_id, T.ARTICLE_CODE,T.PARA1_CODE,T.PARA2_CODE ,C.PARA1_NAME,        
	 D.PARA2_NAME,B.ARTICLE_NO,B.ARTICLE_NAME,I.UOM_NAME
HAVING SUM(JW_REQ_QTY)> ISNULL(SUM(ISSUED_QTY),0)

--(+,-) 5 percent margin durring material issue

--DELETE FROM #SP3S_GET_JWI_BOM_ISSUED WHERE 
--ISSUED_QTY  BETWEEN ROUND( QUANTITY-( QUANTITY *5/100),2)
--AND ROUND( QUANTITY+( QUANTITY *5/100),2)

--

SELECT ISSUE_ID FROM #SP3S_GET_JWI_BOM_ISSUED GROUP BY ISSUE_ID
END


