
CREATE PROCEDURE SPPPC_DQRQ_DETAILS    
(    
 @NQUERYID INT=0,    
 @CAC_CODE VARCHAR(10)='',    
 @CORDER_ID VARCHAR(50)='',    
 @CBOM_ARTICLE_CODE VARCHAR(100)='',    
 @CMEMO_ID VARCHAR(100)='',    
 @CBO_ROW_ID VARCHAR(100)='',    
 @CRQORDER_ID VARCHAR(100)='',  
 @CMEMO_TYPE INT =1 ,
 @CFIN_YEAR VARCHAR(5)=''   
)    
AS    
BEGIN    
--DROP TABLE TMP11
--    SELECT @NQUERYID AS A
--    INTO TMP11    
    
--    SELECT * FROM TMP11
     
      
     IF @NQUERYID IN (3,9)    
     BEGIN    
              
          IF OBJECT_ID ('TEMPDB..#TMPDQ','U') IS NOT NULL    
              DROP TABLE #TMPDQ    
              
    SELECT B.AC_CODE ,LM.AC_NAME ,    
    A.ORDER_ID ,B.ORDER_NO, B.ORDER_DT,    
    B.BILL_NO,PMT.BO_BOM_ROW_ID,    
    A.ARTICLE_CODE  ,ART.ARTICLE_NO ,    
    A.PARA1_CODE ,P1.PARA1_NAME ,    
    A.SIZEGROUP_CODE ,SG.SIZEGROUP_NAME ,    
    A.PARA3_CODE,P3.PARA3_NAME ,    
    C.BOM_ARTICLE_CODE ,ART1.ARTICLE_NO AS BOM_ARTICLE_NO,ART1.ARTICLE_NAME AS BOM_ARTICLE_NAME ,    
    CAST('' AS VARCHAR(40)) AS ROW_ID,    
    A.ROW_ID AS BO_ROW_ID,    
    A.QUANTITY AS BO_QTY,    
    C.ROW_ID AS REF_ROW_ID,    
    SUM(PMT.QUANTITY_IN_STOCK ) AS QUANTITY_IN_STOCK ,    
    SUM(PMT.QUANTITY_IN_STOCK ) AS QUANTITY    
    INTO #TMPDQ    
    FROM PPC_BUYER_ORDER_DET A    
    JOIN PPC_BUYER_ORDER_MST B ON A.ORDER_ID =B.ORDER_ID     
    JOIN PPC_BO_ART_BOM C ON C.REF_ROW_ID=A.ROW_ID     
    JOIN PPC_PMT PMT ON C.ROW_ID =PMT.BO_BOM_ROW_ID    
    JOIN PARA1 P1 ON P1.PARA1_CODE=A.PARA1_CODE    
    JOIN PPC_SIZEGROUP SG ON SG.SIZEGROUP_CODE=A.SIZEGROUP_CODE    
    JOIN PARA3 P3 ON P3.PARA3_CODE=A.PARA3_CODE    
    JOIN ARTICLE ART ON ART.ARTICLE_CODE=A.ARTICLE_CODE    
    JOIN ARTICLE ART1 ON ART1.ARTICLE_CODE=C.BOM_ARTICLE_CODE    
    JOIN LM01106 LM ON LM.AC_CODE =B.AC_CODE     
    WHERE B.CANCELLED =0     
    AND PMT.QUANTITY_IN_STOCK>0    
    AND (@CORDER_ID='' OR A.ORDER_ID =@CORDER_ID)    
    GROUP BY B.ORDER_NO,B.ORDER_DT,B.AC_CODE ,LM.AC_NAME,A.ORDER_ID ,    
    A.ARTICLE_CODE ,ART.ARTICLE_NO , B.BILL_NO,    
    A.PARA1_CODE ,P1.PARA1_NAME ,    
    A.SIZEGROUP_CODE ,SG.SIZEGROUP_NAME ,    
    A.PARA3_CODE,P3.PARA3_NAME ,BO_BOM_ROW_ID,    
    C.BOM_ARTICLE_CODE ,ART1.ARTICLE_NAME  ,ART1.ARTICLE_NO ,    
    C.ROW_ID , A.ROW_ID,A.QUANTITY    
          
         
     END    
     IF @NQUERYID IN (5,10,11)    
      BEGIN    
              
          IF OBJECT_ID ('TEMPDB..#TMPRQ','U') IS NOT NULL    
              DROP TABLE #TMPRQ    
                  
              
    SELECT B.AC_CODE ,LM.AC_NAME ,    
     A.ORDER_ID ,B.ORDER_NO, B.ORDER_DT,A.ROW_ID AS BO_ROW_ID,    
     B.BILL_NO,C.ROW_ID AS BO_BOM_ROW_ID,A.QUANTITY AS BO_QTY,    
     A.ARTICLE_CODE  ,ART.ARTICLE_NO+'-'+CAST(CAST(A.QUANTITY AS NUMERIC(10,0)) AS VARCHAR(10)) AS ARTICLE_NO,     
     A.PARA1_CODE ,P1.PARA1_NAME ,    
     A.SIZEGROUP_CODE ,SG.SIZEGROUP_NAME ,    
     A.PARA3_CODE,P3.PARA3_NAME ,    
     C.BOM_ARTICLE_CODE,ART1.ARTICLE_NO AS BOM_ARTICLE_NO ,ART1.ARTICLE_NAME AS BOM_ARTICLE_NAME ,    
     CAST('' AS VARCHAR(40)) AS REF_ROW_ID,    
     CAST(CASE WHEN UC.CONVERSION_VALUE=0 THEN  SUM(A.QUANTITY*C.AVG_QTY )     
     ELSE  SUM(A.QUANTITY*C.AVG_QTY )/UC.CONVERSION_VALUE END -ISNULL(SUM(PMT.QUANTITY_IN_STOCK),0) AS NUMERIC(18,3)) AS REQ_QTY ,    
     SUM(ISNULL(PMT.QUANTITY_IN_STOCK,0) ) AS QUANTITY_IN_STOCK,    
     --CAST(CASE WHEN UC.CONVERSION_VALUE=0 THEN  SUM(A.QUANTITY*C.AVG_QTY )     
     --ELSE  SUM(A.QUANTITY*C.AVG_QTY )/UC.CONVERSION_VALUE END AS NUMERIC(18,3)) -SUM(ISNULL(PMT.QUANTITY_IN_STOCK,0) ) AS REQ_QTY,    
     CAST(0 AS NUMERIC(10,3)) AS QUANTITY    
     INTO #TMPRQ    
     FROM PPC_BUYER_ORDER_DET A    
     JOIN PPC_BUYER_ORDER_MST B ON A.ORDER_ID =B.ORDER_ID     
     JOIN PPC_BO_ART_BOM C ON C.REF_ROW_ID=A.ROW_ID     
     LEFT JOIN     
     ( SELECT BO_BOM_ROW_ID,SUM(QUANTITY_IN_STOCK) AS QUANTITY_IN_STOCK FROM     
        PPC_PMT PMT     
        GROUP BY BO_BOM_ROW_ID    
      )PMT ON C.ROW_ID =PMT.BO_BOM_ROW_ID    
     JOIN PARA1 P1 ON P1.PARA1_CODE=A.PARA1_CODE    
     JOIN PPC_SIZEGROUP SG ON SG.SIZEGROUP_CODE=A.SIZEGROUP_CODE    
     JOIN PARA3 P3 ON P3.PARA3_CODE=A.PARA3_CODE    
     JOIN ARTICLE ART ON ART.ARTICLE_CODE=A.ARTICLE_CODE    
     JOIN ARTICLE ART1 ON ART1.ARTICLE_CODE=C.BOM_ARTICLE_CODE    
     JOIN LM01106 LM ON LM.AC_CODE =B.AC_CODE     
     JOIN UOM ON UOM.UOM_CODE=ART1.UOM_CODE    
     LEFT OUTER JOIN PPC_UOM_CONVERSION UC ON UC.UOM_CODE=UOM.UOM_CODE    
     LEFT OUTER JOIN PPC_BOM_UOM BU ON BU.CONVERSION_UOM_CODE=UC.CONVERSION_UOM_CODE    
     WHERE B.CANCELLED =0     
     AND (@CBOM_ARTICLE_CODE='' OR C.BOM_ARTICLE_CODE=@CBOM_ARTICLE_CODE)    
    -- AND (@CORDER_ID='' OR B.ORDER_ID<>@CORDER_ID)    
     GROUP BY B.AC_CODE ,LM.AC_NAME ,    
     A.ORDER_ID ,B.ORDER_NO, B.ORDER_DT,    
     B.BILL_NO,C.ROW_ID  ,A.QUANTITY,    
     A.ARTICLE_CODE  ,ART.ARTICLE_NO+'-'+CAST(CAST(A.QUANTITY AS NUMERIC(10,0)) AS VARCHAR(10)),    
     A.PARA1_CODE ,P1.PARA1_NAME ,    
     A.SIZEGROUP_CODE ,SG.SIZEGROUP_NAME ,    
     A.PARA3_CODE,P3.PARA3_NAME ,    
     C.BOM_ARTICLE_CODE ,ART1.ARTICLE_NAME  ,ART1.ARTICLE_NO,    
     C.ROW_ID ,UC.CONVERSION_VALUE,A.ROW_ID    
     HAVING CAST(CASE WHEN UC.CONVERSION_VALUE=0 THEN  SUM(A.QUANTITY*C.AVG_QTY )     
     ELSE  SUM(A.QUANTITY*C.AVG_QTY )/UC.CONVERSION_VALUE END AS NUMERIC(10,3)) -ISNULL(SUM(ISNULL(PMT.QUANTITY_IN_STOCK,0) ),0)>0    

--DROP TABLE TMPRQ
--SELECT @CORDER_ID AS A,@CBOM_ARTICLE_CODE AS B 
--INTO TMPRQ

             --DROP TABLE TMPRQ
             --SELECT  *   INTO TMPRQ FROM #TMPRQ  
             
             --SELECT * FROM TMPRQ
                  
      END    
          
      IF @NQUERYID IN (7,12)  AND @CMEMO_TYPE=1  
      BEGIN    
               
           IF OBJECT_ID ('TEMPDB..#TMPDQV','U') IS NOT NULL    
              DROP TABLE #TMPDQV    
                  
		 SELECT B.AC_CODE ,LM.AC_NAME ,    
		 A.ORDER_ID ,B.ORDER_NO, B.ORDER_DT,    
		 B.BILL_NO,PMT.BO_BOM_ROW_ID,A.ROW_ID AS BO_ROW_ID,A.QUANTITY AS BO_QTY,    
		 A.ARTICLE_CODE  ,ART.ARTICLE_NO,    
		 A.PARA1_CODE ,P1.PARA1_NAME ,    
		 A.SIZEGROUP_CODE ,SG.SIZEGROUP_NAME ,    
		 A.PARA3_CODE,P3.PARA3_NAME ,    
		 C.BOM_ARTICLE_CODE ,ART1.ARTICLE_NO AS BOM_ARTICLE_NO,ART1.ARTICLE_NAME AS BOM_ARTICLE_NAME ,    
		 MST.ROW_ID ,    
		 C.ROW_ID AS REF_ROW_ID,    
		 SUM(PMT.QUANTITY_IN_STOCK+MST.QUANTITY ) AS QUANTITY_IN_STOCK ,    
		 SUM(MST.QUANTITY ) AS QUANTITY    
		 INTO #TMPDQV    
		 FROM PPC_BUYER_ORDER_DET A    
		 JOIN PPC_BUYER_ORDER_MST B ON A.ORDER_ID =B.ORDER_ID     
		 JOIN PPC_BO_ART_BOM C ON C.REF_ROW_ID=A.ROW_ID     
		 JOIN     
		 (    
		  SELECT PRODUCT_UID , BO_BOM_ROW_ID,SUM(QUANTITY_IN_STOCK) AS QUANTITY_IN_STOCK FROM     
		  PPC_PMT PMT     
		  GROUP BY PRODUCT_UID ,BO_BOM_ROW_ID    
		  )PMT ON C.ROW_ID =PMT.BO_BOM_ROW_ID     
		 JOIN PARA1 P1 ON P1.PARA1_CODE=A.PARA1_CODE    
		 JOIN PPC_SIZEGROUP SG ON SG.SIZEGROUP_CODE=A.SIZEGROUP_CODE    
		 JOIN PARA3 P3 ON P3.PARA3_CODE=A.PARA3_CODE    
		 JOIN ARTICLE ART ON ART.ARTICLE_CODE=A.ARTICLE_CODE    
		 JOIN ARTICLE ART1 ON ART1.ARTICLE_CODE=C.BOM_ARTICLE_CODE    
		 JOIN LM01106 LM ON LM.AC_CODE =B.AC_CODE     
		 JOIN    
		 (    
		  SELECT B.ROW_ID , PRODUCT_UID,QUANTITY FROM PPC_DQRQ_MST A    
		  JOIN PPC_DQ_DET B ON A.MEMO_ID=B.MEMO_ID    
		  WHERE (@CMEMO_ID='' OR A.MEMO_ID=@CMEMO_ID)    
		 ) MST ON MST.PRODUCT_UID=PMT.PRODUCT_UID    
		 WHERE B.CANCELLED =0     
	     AND (@CORDER_ID='' OR A.ORDER_ID =@CORDER_ID)    
		 GROUP BY B.ORDER_NO,B.ORDER_DT,B.AC_CODE ,LM.AC_NAME,A.ORDER_ID ,    
		 A.ARTICLE_CODE ,ART.ARTICLE_NO , B.BILL_NO,    
		 A.PARA1_CODE ,P1.PARA1_NAME ,    
		 A.SIZEGROUP_CODE ,SG.SIZEGROUP_NAME ,    
		 A.PARA3_CODE,P3.PARA3_NAME ,BO_BOM_ROW_ID,    
		 C.BOM_ARTICLE_CODE ,ART1.ARTICLE_NAME  ,ART1.ARTICLE_NO ,    
		 MST.ROW_ID ,C.ROW_ID ,A.ROW_ID,A.QUANTITY    
       
           
      END    
         
IF @NQUERYID=1    
   GOTO LBLBUYER       
ELSE IF @NQUERYID=2    
   GOTO LBLORDER     
ELSE IF @NQUERYID=3    
   GOTO LBLDQDET    
ELSE IF @NQUERYID=4    
   GOTO LBLDQBARCODEDET    
ELSE IF @NQUERYID=5    
   GOTO LBLRQDET    
ELSE IF @NQUERYID=6    
   GOTO LBLMST    
ELSE IF @NQUERYID=7    
   GOTO LBLDQ_VIEW    
ELSE IF @NQUERYID=8    
   GOTO LBLRQ_VIEW    
ELSE IF @NQUERYID=9    
   GOTO LBLDQFG    
ELSE IF @NQUERYID=10    
   GOTO LBLRQBUYER    
ELSE IF @NQUERYID=11    
   GOTO LBLRQORDER    
ELSE IF @NQUERYID=12    
   GOTO LBLDQFG_VIEW    
ELSE     
   GOTO END_PROC    
       
       
   LBLRQBUYER:    
          
      SELECT A.AC_CODE,AC_NAME     
      FROM PPC_BUYER_ORDER_MST A    
      JOIN LM01106 B ON A.AC_CODE=B.AC_CODE    
      GROUP BY A.AC_CODE,AC_NAME     
       
   GOTO END_PROC    
       
   LBLRQORDER:    
           
       SELECT BILL_NO,ORDER_ID    
       FROM #TMPRQ A     
       WHERE (@CAC_CODE='' OR A.AC_CODE=@CAC_CODE)    
       GROUP BY BILL_NO,ORDER_ID    
       
       
   GOTO END_PROC    
       
   LBLDQFG:    
           
       SELECT  A.AC_CODE ,A.AC_NAME ,BO_ROW_ID,    
        A.ORDER_ID ,A.ORDER_NO, A.ORDER_DT,    
        A.BILL_NO,A.ARTICLE_CODE,A.ARTICLE_NO,BO_QTY    
    FROM #TMPDQ A    
    GROUP BY A.AC_CODE ,A.AC_NAME ,BO_ROW_ID,    
    A.ORDER_ID ,A.ORDER_NO, A.ORDER_DT,    
     A.BILL_NO,A.ARTICLE_CODE,A.ARTICLE_NO,BO_QTY    
       
   GOTO END_PROC    
       
       
       
   LBLBUYER:    
       
      SELECT A.AC_CODE,B.AC_NAME       
      FROM PPC_BUYER_ORDER_MST  A    
      JOIN LM01106 B ON A.AC_CODE=B.AC_CODE     
      WHERE A.CANCELLED =0    
      GROUP BY A.AC_CODE,B.AC_NAME    
          
   GOTO END_PROC    
       
   LBLORDER:    
       
      SELECT A.ORDER_DT ,A.ORDER_ID ,A.ORDER_NO,A.BILL_NO       
      FROM PPC_BUYER_ORDER_MST  A    
      WHERE A.CANCELLED =0    
      AND (@CAC_CODE='' OR A.AC_CODE =@CAC_CODE)    
          
   GOTO END_PROC    
       
       
       
   LBLDQDET:    
           
          SELECT A.AC_CODE ,A.AC_NAME ,    
    A.ORDER_ID ,A.ORDER_NO, A.ORDER_DT,    
    A.BILL_NO,A.BO_BOM_ROW_ID,    
    A.ARTICLE_CODE  ,A.ARTICLE_NO ,    
    A.PARA1_CODE ,A.PARA1_NAME ,    
    A.SIZEGROUP_CODE ,A.SIZEGROUP_NAME ,    
    A.PARA3_CODE,A.PARA3_NAME ,    
    A.BOM_ARTICLE_CODE ,A.BOM_ARTICLE_NO,A.BOM_ARTICLE_NAME ,    
    CAST('' AS VARCHAR(40)) AS ROW_ID,    
    A.BO_ROW_ID,    
    A.QUANTITY AS BO_QTY,    
    A.REF_ROW_ID,    
    A.QUANTITY_IN_STOCK ,    
    A.QUANTITY    
    FROM #TMPDQ A    
    WHERE (@CBO_ROW_ID='' OR  A.BO_ROW_ID =@CBO_ROW_ID)    
         
     -- SELECT * FROM PPC_BO_ART_BOM WHERE ROW_ID ='ECA5037A-7A13-48D1-BC07-CFED41E09EF3    '    
   GOTO END_PROC    
     
   LBLDQBARCODEDET:    
     
     
  SELECT B.AC_CODE ,LM.AC_NAME ,    
      A.ORDER_ID ,B.ORDER_NO, B.ORDER_DT,    
      B.BILL_NO,PMT.BO_BOM_ROW_ID,    
      A.ARTICLE_CODE  ,ART.ARTICLE_NO,    
      A.PARA1_CODE ,P1.PARA1_NAME ,    
      A.SIZEGROUP_CODE ,SG.SIZEGROUP_NAME ,    
      A.PARA3_CODE,P3.PARA3_NAME ,    
      C.BOM_ARTICLE_CODE ,ART1.ARTICLE_NAME AS BOM_ARTICLE_NAME ,    
      A.ROW_ID AS REF_ROW_ID,    
      CAST('LATER'+CAST(NEWID () AS VARCHAR(100))  AS VARCHAR(40)) AS ROW_ID,    
      PMT.PRODUCT_UID ,PMT.PRODUCT_CODE,    
      SUM(PMT.QUANTITY_IN_STOCK ) AS QUANTITY_IN_STOCK ,    
      SUM(PMT.QUANTITY_IN_STOCK ) AS QUANTITY,    
      CAST(0 AS NUMERIC(10,3)) AS REQ_QTY    
      FROM PPC_BUYER_ORDER_DET A    
      JOIN PPC_BUYER_ORDER_MST B ON A.ORDER_ID =B.ORDER_ID     
      JOIN PPC_BO_ART_BOM C ON C.REF_ROW_ID=A.ROW_ID     
      JOIN PPC_PMT PMT ON C.ROW_ID =PMT.BO_BOM_ROW_ID    
      JOIN PARA1 P1 ON P1.PARA1_CODE=A.PARA1_CODE    
      JOIN PPC_SIZEGROUP SG ON SG.SIZEGROUP_CODE=A.SIZEGROUP_CODE    
      JOIN PARA3 P3 ON P3.PARA3_CODE=A.PARA3_CODE    
      JOIN ARTICLE ART ON ART.ARTICLE_CODE=A.ARTICLE_CODE    
      JOIN ARTICLE ART1 ON ART1.ARTICLE_CODE=C.BOM_ARTICLE_CODE    
      JOIN LM01106 LM ON LM.AC_CODE =B.AC_CODE     
      WHERE B.CANCELLED =0     
      AND PMT.QUANTITY_IN_STOCK>0    
      AND (@CORDER_ID='' OR A.ORDER_ID =@CORDER_ID)    
      AND (@CBO_ROW_ID='' OR  A.ROW_ID =@CBO_ROW_ID)    
      AND (@CBOM_ARTICLE_CODE='' OR C.BOM_ARTICLE_CODE=@CBOM_ARTICLE_CODE)    
      GROUP BY B.ORDER_NO,B.ORDER_DT,B.AC_CODE ,LM.AC_NAME,A.ORDER_ID ,    
      A.ARTICLE_CODE ,ART.ARTICLE_NO , B.BILL_NO,    
      A.PARA1_CODE ,P1.PARA1_NAME ,    
      A.SIZEGROUP_CODE ,SG.SIZEGROUP_NAME ,    
      A.PARA3_CODE,P3.PARA3_NAME ,BO_BOM_ROW_ID,    
      C.BOM_ARTICLE_CODE ,ART1.ARTICLE_NAME  ,    
      C.ROW_ID ,PMT.PRODUCT_UID ,PMT.PRODUCT_CODE,A.ROW_ID    
          
    GOTO END_PROC    
       
   LBLRQDET:    
           
           
       SELECT * FROM #TMPRQ A    
       WHERE A.ORDER_ID =@CRQORDER_ID  
       AND REQ_QTY>0   
       ORDER BY A.BO_ROW_ID ,A.BOM_ARTICLE_NO     
           

   GOTO END_PROC    
       
   LBLMST:    
   
     IF @CMEMO_TYPE IN(1,'')
     BEGIN    
      SELECT A.MEMO_ID,A.MEMO_NO,A.MEMO_DT,FIN_YEAR,CANCELLED ,LM.AC_CODE,LM.AC_NAME ,B.ORDER_ID ,  
		  B.ORDER_DT ,B.BILL_NO ,1 AS APPROVED   
		  FROM PPC_DQRQ_MST A     
		  LEFT JOIN    
		  (    
			SELECT DISTINCT A.MEMO_ID, D.AC_CODE,D.BILL_NO ,D.ORDER_ID,D.ORDER_DT     
		    FROM PPC_DQ_DET A    
		    JOIN PPC_BO_ART_BOM B ON A.BO_BOM_ROW_ID=B.ROW_ID     
		    JOIN PPC_BUYER_ORDER_DET C ON C.ROW_ID =B.REF_ROW_ID     
			JOIN PPC_BUYER_ORDER_MST D ON C.ORDER_ID=D.ORDER_ID    
	       
		  ) B ON A.MEMO_ID=B.MEMO_ID    
		  LEFT JOIN LM01106 LM ON LM.AC_CODE =B.AC_CODE    
		  WHERE (@CMEMO_ID='' OR  A.MEMO_ID=@CMEMO_ID )   
		   AND (@CMEMO_TYPE='' OR ISNULL(A.MEMO_TYPE,0)=@CMEMO_TYPE  ) 
		   AND(@CAC_CODE='' OR LM.AC_CODE=@CAC_CODE)
		   AND (@CFIN_YEAR='' OR A.FIN_YEAR=@CFIN_YEAR)
		   ORDER BY A.MEMO_DT DESC, A.MEMO_ID DESC 
     -- AND (@CORDER_ID='' OR B.ORDER_ID=@CORDER_ID)    
      END
      ELSE
      BEGIN
          SELECT A.MEMO_ID,A.MEMO_NO,A.MEMO_DT,FIN_YEAR,CANCELLED ,
                  ARTICLE_NO=ISNULL((SELECT STUFF((
                     SELECT ', '+ ART.ARTICLE_NO   FROM 
                     PPC_DQ_DET DET
                     JOIN PPC_SKU B ON DET.PRODUCT_UID =B.PRODUCT_UID 
                     JOIN ARTICLE ART ON ART.ARTICLE_CODE =B.ARTICLE_CODE 
                    WHERE A.MEMO_ID =DET.MEMO_ID  FOR XML PATH('')),1,1,'')),''),
                   ARTICLE_CODE=ISNULL((SELECT STUFF((
                     SELECT ','+ ART.ARTICLE_CODE   FROM 
                     PPC_DQ_DET DET
                     JOIN PPC_SKU B ON DET.PRODUCT_UID =B.PRODUCT_UID 
                     JOIN ARTICLE ART ON ART.ARTICLE_CODE =B.ARTICLE_CODE 
                    WHERE A.MEMO_ID =DET.MEMO_ID  FOR XML PATH('')),1,1,'')),'')
                    ,1 AS APPROVED
		            FROM PPC_DQRQ_MST A 
          WHERE (@CMEMO_ID='' OR  A.MEMO_ID=@CMEMO_ID )   
		  AND (@CMEMO_TYPE='' OR ISNULL(A.MEMO_TYPE,0)=@CMEMO_TYPE  )
		  AND (@CFIN_YEAR='' OR A.FIN_YEAR=@CFIN_YEAR)
		  ORDER BY A.MEMO_DT DESC, A.MEMO_ID DESC 
         -- WHERE A.MEMO_ID ='01011180000001DA000006'
          
      END 
   GOTO END_PROC    
       
   LBLDQ_VIEW:    
           
           
      -- SELECT *  FROM #TMPDQV    
      IF @CMEMO_TYPE=1
      BEGIN    
       SELECT A.AC_CODE,A.AC_NAME,A.ORDER_ID,A.ORDER_NO,A.ORDER_DT,A.BILL_NO,    
              A.BO_BOM_ROW_ID,A.BO_ROW_ID,A.BO_QTY,A.ARTICLE_CODE,A.ARTICLE_NO,    
              A.PARA1_CODE,A.PARA1_NAME,A.SIZEGROUP_CODE,A.SIZEGROUP_NAME,    
              A.PARA3_CODE,A.PARA3_NAME,A.BOM_ARTICLE_CODE,A.BOM_ARTICLE_NO,    
              A.BOM_ARTICLE_NAME,'' AS ROW_ID,REF_ROW_ID,    
              SUM(QUANTITY_IN_STOCK) AS QUANTITY_IN_STOCK,    
              SUM(QUANTITY ) AS QUANTITY    
       FROM #TMPDQV A    
       WHERE A.ORDER_ID =@CORDER_ID    
       GROUP BY A.AC_CODE,A.AC_NAME,A.ORDER_ID,A.ORDER_NO,A.ORDER_DT,A.BILL_NO,    
              A.BO_BOM_ROW_ID,A.BO_ROW_ID,A.BO_QTY,A.ARTICLE_CODE,A.ARTICLE_NO,    
              A.PARA1_CODE,A.PARA1_NAME,A.SIZEGROUP_CODE,A.SIZEGROUP_NAME,    
              A.PARA3_CODE,A.PARA3_NAME,A.BOM_ARTICLE_CODE,A.BOM_ARTICLE_NO,    
              A.BOM_ARTICLE_NAME,REF_ROW_ID    
       
       END  
 
   GOTO END_PROC    
            
        
   LBLRQ_VIEW:    
      
       SELECT BO.AC_CODE ,LM.AC_NAME ,    
              BO.ORDER_ID ,BO.ORDER_NO, BO.ORDER_DT,    
              BO.BILL_NO,BOM.ROW_ID AS BO_BOM_ROW_ID,    
              BO.ARTICLE_CODE  ,ART.ARTICLE_NO+'-'+CAST(CAST(BO.QUANTITY AS NUMERIC(10,0)) AS VARCHAR(10)) AS ARTICLE_NO,    
              BO.PARA1_CODE ,P1.PARA1_NAME ,    
              BO.SIZEGROUP_CODE ,SG.SIZEGROUP_NAME ,    
              BO.PARA3_CODE,P3.PARA3_NAME ,    
              BOM.BOM_ARTICLE_CODE ,ART1.ARTICLE_NO AS BOM_ARTICLE_NO, ART1.ARTICLE_NAME AS BOM_ARTICLE_NAME ,    
              BOM.REF_ROW_ID AS REF_ROW_ID,    
              C.QUANTITY  AS QUANTITY_IN_STOCK    
              ,'' AS ROW_ID,'' AS PRODUCT_UID,'' AS BO_BOM_ROW_ID    
              ,SKU.PRODUCT_CODE    
              ,C.BO_BOM_ROW_ID, C.REF_ROW_ID, C.PRODUCT_UID,C.QUANTITY,
              C.REQ_QTY 
       FROM PPC_DQRQ_MST A    
       JOIN PPC_DQ_DET B ON A.MEMO_ID=B.MEMO_ID    
       JOIN PPC_RQ_DET C ON B.ROW_ID=C.REF_ROW_ID   
       JOIN PPC_BO_ART_BOM BOM ON BOM.ROW_ID=C.BO_BOM_ROW_ID
       JOIN
       (
        SELECT B.AC_CODE, A.ORDER_ID ,B.ORDER_NO, B.ORDER_DT, 
        A.ROW_ID,B.BILL_NO ,A.ARTICLE_CODE,A.SIZEGROUP_CODE,A.PARA3_CODE,A.QUANTITY,
        A.PARA1_CODE
        FROM PPC_BUYER_ORDER_DET A
        JOIN PPC_BUYER_ORDER_MST B ON A.ORDER_ID=B.ORDER_ID
        WHERE B.CANCELLED=0
       ) BO ON BO.ROW_ID=BOM.REF_ROW_ID
       JOIN LM01106 LM ON LM.AC_CODE =BO.AC_CODE 
       JOIN ARTICLE ART ON ART.ARTICLE_CODE=BO.ARTICLE_CODE
       JOIN PARA1 P1 ON P1.PARA1_CODE=BO.PARA1_CODE
       JOIN PARA3 P3 ON P3.PARA3_CODE=BO.PARA3_CODE
       JOIN PPC_SIZEGROUP SG ON SG.SIZEGROUP_CODE=BO.SIZEGROUP_CODE
       JOIN ARTICLE ART1 ON ART1.ARTICLE_CODE=BOM.BOM_ARTICLE_CODE
       JOIN PPC_SKU SKU ON SKU.PRODUCT_UID=C.PRODUCT_UID
       WHERE A.MEMO_ID=@CMEMO_ID AND BOM.BOM_ARTICLE_CODE=@CBOM_ARTICLE_CODE    
       --GROUP BY BO.AC_CODE ,LM.AC_NAME ,    
       --       BO.ORDER_ID ,BO.ORDER_NO, BO.ORDER_DT,    
       --       BO.BILL_NO,BOM.ROW_ID ,    
       --       BO.ARTICLE_CODE  ,ART.ARTICLE_NO+'-'+CAST(CAST(BO.QUANTITY AS NUMERIC(10,0)) AS VARCHAR(10)) ,    
       --       BO.PARA1_CODE ,P1.PARA1_NAME ,    
       --       BO.SIZEGROUP_CODE ,SG.SIZEGROUP_NAME ,    
       --       BO.PARA3_CODE,P3.PARA3_NAME ,    
       --       BOM.BOM_ARTICLE_CODE ,ART1.ARTICLE_NO , ART1.ARTICLE_NAME  ,    
       --       BOM.REF_ROW_ID ,SKU.PRODUCT_CODE
      
      --END 
   GOTO END_PROC    
       
   LBLDQFG_VIEW:    
    
    IF @CMEMO_TYPE=1
    BEGIN         
		SELECT  A.AC_CODE ,A.AC_NAME ,BO_ROW_ID,    
			A.ORDER_ID ,A.ORDER_NO, A.ORDER_DT,    
			A.BILL_NO,A.ARTICLE_CODE,A.ARTICLE_NO,BO_QTY    
		FROM #TMPDQV A    
		GROUP BY A.AC_CODE ,A.AC_NAME ,BO_ROW_ID,    
		A.ORDER_ID ,A.ORDER_NO, A.ORDER_DT,    
		 A.BILL_NO,A.ARTICLE_CODE,A.ARTICLE_NO,BO_QTY  
     END
     ELSE
     BEGIN
       
        SELECT '' AS AC_CODE,'' AS AC_NAME,'' AS ORDER_ID,'' AS ORDER_NO,'' AS ORDER_DT,'' AS BILL_NO,    
              '' AS BO_BOM_ROW_ID,'' AS BO_ROW_ID,0 AS BO_QTY,
              '' AS ARTICLE_CODE,'' AS ARTICLE_NO,    
              '' AS PARA1_CODE,'' AS PARA1_NAME,'' AS SIZEGROUP_CODE,'' AS SIZEGROUP_NAME,    
              '' AS PARA3_CODE,'' AS PARA3_NAME,SKU.ARTICLE_CODE AS BOM_ARTICLE_CODE,ART.ARTICLE_NO AS BOM_ARTICLE_NO,    
              ART.ARTICLE_NAME AS BOM_ARTICLE_NAME,'' AS ROW_ID,'' AS REF_ROW_ID,    
              SUM(QUANTITY_IN_STOCK) AS QUANTITY_IN_STOCK,    
              SUM(QUANTITY ) AS QUANTITY 
			  FROM PPC_DQRQ_MST A    
			  JOIN PPC_DQ_DET B ON A.MEMO_ID=B.MEMO_ID  
			  JOIN PPC_SKU SKU ON SKU.PRODUCT_UID=B.PRODUCT_UID
			  JOIN PPC_PMT PMT ON PMT.PRODUCT_UID=SKU.PRODUCT_UID
			  JOIN ARTICLE ART ON ART.ARTICLE_CODE=SKU.ARTICLE_CODE  
			  WHERE (@CMEMO_ID='' OR A.MEMO_ID=@CMEMO_ID)  
              GROUP BY SKU.ARTICLE_CODE ,ART.ARTICLE_NO ,    
              ART.ARTICLE_NAME 
       END    
      
   GOTO END_PROC    
       
END_PROC:    
    
END 
