CREATE PROCEDURE SP3S_DROP_UNWANTED_MIRRORCONST
AS
BEGIN
	IF OBJECT_ID('TEMPDB..#TMPDROPCONST','U') IS NOT NULL
		DROP TABLE #TMPDROPCONST
	
	DECLARE @CCMD NVARCHAR(MAX),@BLOOP BIT
		
	SELECT 'ALTER TABLE '+C.NAME+' DROP CONSTRAINT '+ B.NAME AS CMD INTO #TMPDROPCONST
    FROM SYSCONSTRAINTS A
    JOIN SYSOBJECTS B ON A.CONSTID = B.ID
    JOIN SYSOBJECTS C ON A.ID = C.ID 
    JOIN SYSCOMMENTS D ON A.CONSTID = D.ID
    LEFT OUTER JOIN SYSCOLUMNS E ON E.COLID = A.COLID AND E.ID=A.ID
    LEFT OUTER JOIN STRUCOMP_SQLEXPR H (NOLOCK) ON H.TABLENAME=C.NAME AND H.COLNAME=E.NAME
    WHERE B.XTYPE IN ('D','C') AND RIGHT(C.NAME,7) IN ('_UPLOAD','_MIRROR')
    AND C.NAME NOT IN ('ART_ARTICLE_UPLOAD')  AND RIGHT(B.NAME,19)<>'VERSION_LAST_UPDATE'
    
    SET @BLOOP=0
    WHILE @BLOOP=0
    BEGIN
		SET @CCMD=''
		SELECT TOP 1  @CCMD=CMD FROM #TMPDROPCONST
		
		IF ISNULL(@CCMD,'')<>''
			EXEC SP_EXECUTESQL @CCMD
		ELSE
			BREAK	
			
		DELETE FROM #TMPDROPCONST WHERE CMD=@CCMD	
    END
END
