CREATE PROCEDURE SP3S_GET_FORM_FKEYDATA
@CSOURCEDB VARCHAR(200),
@CSOURCETABLE VARCHAR(200),
@CSOURCEKEYFIELD VARCHAR(200),
@CXNTYPE VARCHAR(10),
@CTABLESUFFIX VARCHAR(40),
@CLOCID VARCHAR(5),
@CERRORMSG VARCHAR(MAX) OUTPUT
--WITH ENCRYPTION
AS
BEGIN
	BEGIN TRY
		DECLARE @CCMD NVARCHAR(MAX),@CTEMPTABLE VARCHAR(1000),@CTEMPTABLE1 VARCHAR(1000),@CTEMPTABLE2 VARCHAR(1000),
				@CTEMPTABLE3 VARCHAR(1000),@CTEMPTABLE4 VARCHAR(1000),@CTEMPTABLE5 VARCHAR(1000),
				@CKEYFIELDVAL VARCHAR(40),@CDESTDB VARCHAR(200),@CFILTERCONDITION VARCHAR(MAX),@NSTEP INT
		
		SET @CDESTDB='WIZAPP3S_MIRROR_'+@CLOCID+'.DBO.'
		
		SET @NSTEP=10		

		IF @CSOURCETABLE<>'#TMPMISSINGFORMDATA'
		BEGIN
			IF OBJECT_ID('TEMPDB..#TMPMISSINGFORMDATA','U') IS NOT NULL
				DROP TABLE #TMPMISSINGFORMDATA
			
			SELECT FORM_ID INTO #TMPMISSINGFORMDATA FROM FORM WHERE 1=2
		END
		
		IF OBJECT_ID('TEMPDB..#TMPMISSINGLMDATA','U') IS NOT NULL
			DROP TABLE #TMPMISSINGLMDATA

		SELECT AC_CODE INTO #TMPMISSINGLMDATA FROM LM01106 WHERE 1=2
		
		SET @NSTEP=20											
		SET @CTEMPTABLE=(CASE WHEN LEFT(@CSOURCETABLE,1)='#' THEN @CSOURCETABLE ELSE @CSOURCEDB+'TMP_'+@CXNTYPE+'_'+@CSOURCETABLE+'_'+@CTABLESUFFIX END)
		
		IF @CSOURCETABLE<>'#TMPMISSINGFORMDATA'
		BEGIN
			SET @CCMD=N'SELECT DISTINCT A.'+@CSOURCEKEYFIELD+' FROM '+@CTEMPTABLE+'  A
						LEFT OUTER JOIN WIZAPP3S_MIRROR_'+@CLOCID+'.DBO.FORM B ON B.FORM_ID=A.'+@CSOURCEKEYFIELD+'
						WHERE B.FORM_ID IS NULL AND A.'+@CSOURCEKEYFIELD+' IS NOT NULL'

				
			INSERT #TMPMISSINGFORMDATA
			EXEC SP_EXECUTESQL @CCMD
		END
				
		SET @NSTEP=30
		SET @CCMD=N'SELECT DISTINCT B.PUR_RETURN_AC_CODE
					FROM '+@CTEMPTABLE+'  A
					JOIN FORM B ON B.FORM_ID=A.'+@CSOURCEKEYFIELD+'
					LEFT OUTER JOIN WIZAPP3S_MIRROR_'+@CLOCID+'.DBO.LM01106 C ON C.AC_CODE=B.PUR_RETURN_AC_CODE
					WHERE C.AC_CODE IS NULL
					UNION
					SELECT DISTINCT B.SALE_RETURN_AC_CODE
					FROM '+@CTEMPTABLE+'  A
					JOIN FORM B ON B.FORM_ID=A.'+@CSOURCEKEYFIELD+'
					LEFT OUTER JOIN WIZAPP3S_MIRROR_'+@CLOCID+'.DBO.LM01106 C ON C.AC_CODE=B.SALE_RETURN_AC_CODE
					WHERE C.AC_CODE IS NULL
					UNION
					SELECT DISTINCT B.EXCISE_EDU_CESS_AC_CODE
					FROM '+@CTEMPTABLE+'  A
					JOIN FORM B ON B.FORM_ID=A.'+@CSOURCEKEYFIELD+'
					LEFT OUTER JOIN WIZAPP3S_MIRROR_'+@CLOCID+'.DBO.LM01106 C ON C.AC_CODE=B.EXCISE_EDU_CESS_AC_CODE
					WHERE C.AC_CODE IS NULL
					UNION
					SELECT DISTINCT B.EXCISE_HEDU_CESS_AC_CODE
					FROM '+@CTEMPTABLE+'  A
					JOIN FORM B ON B.FORM_ID=A.'+@CSOURCEKEYFIELD+'
					LEFT OUTER JOIN WIZAPP3S_MIRROR_'+@CLOCID+'.DBO.LM01106 C ON C.AC_CODE=B.EXCISE_HEDU_CESS_AC_CODE
					WHERE C.AC_CODE IS NULL
					UNION
					SELECT DISTINCT B.EXCISE_DUTY_AC_CODE
					FROM '+@CTEMPTABLE+'  A
					JOIN FORM B ON B.FORM_ID=A.'+@CSOURCEKEYFIELD+'
					LEFT OUTER JOIN WIZAPP3S_MIRROR_'+@CLOCID+'.DBO.LM01106 C ON C.AC_CODE=B.EXCISE_DUTY_AC_CODE
					WHERE C.AC_CODE IS NULL
					UNION
					SELECT DISTINCT B.PURCHASE_AC_CODE
					FROM '+@CTEMPTABLE+'  A
					JOIN FORM B ON B.FORM_ID=A.'+@CSOURCEKEYFIELD+'
					LEFT OUTER JOIN WIZAPP3S_MIRROR_'+@CLOCID+'.DBO.LM01106 C ON C.AC_CODE=B.PURCHASE_AC_CODE
					WHERE C.AC_CODE IS NULL
					UNION
					SELECT DISTINCT B.SALE_AC_CODE
					FROM '+@CTEMPTABLE+'  A
					JOIN FORM B ON B.FORM_ID=A.'+@CSOURCEKEYFIELD+'
					LEFT OUTER JOIN WIZAPP3S_MIRROR_'+@CLOCID+'.DBO.LM01106 C ON C.AC_CODE=B.SALE_AC_CODE
					WHERE C.AC_CODE IS NULL
					UNION
					SELECT DISTINCT B.TAX_AC_CODE
					FROM '+@CTEMPTABLE+'  A
					JOIN FORM B ON B.FORM_ID=A.'+@CSOURCEKEYFIELD+'
					LEFT OUTER JOIN WIZAPP3S_MIRROR_'+@CLOCID+'.DBO.LM01106 C ON C.AC_CODE=B.TAX_AC_CODE
					WHERE C.AC_CODE IS NULL'
		
		PRINT @CCMD
			
		INSERT #TMPMISSINGLMDATA
		EXEC SP_EXECUTESQL @CCMD		
		
		
		IF EXISTS (SELECT TOP 1 AC_CODE FROM #TMPMISSINGLMDATA)
		BEGIN
			PRINT 'CHECK FKEY FOR LM AGAINST FORM'
			
			SET @NSTEP=40
			EXEC SP3S_GET_LM01106_FKEYDATA
			@CSOURCEDB='',
			@CSOURCETABLE='#TMPMISSINGLMDATA',
			@CSOURCEKEYFIELD='AC_CODE',
			@CXNTYPE=@CXNTYPE,
			@CTABLESUFFIX=@CTABLESUFFIX,
			@CLOCID=@CLOCID,
			@CERRORMSG=@CERRORMSG OUTPUT
		END	

		
		IF EXISTS (SELECT TOP 1 FORM_ID FROM #TMPMISSINGFORMDATA)
		BEGIN

			SET @NSTEP=50
			SET @CFILTERCONDITION= 'B.FORM_ID IN (SELECT FORM_ID FROM #TMPMISSINGFORMDATA)'
			
			EXEC UPDATEMASTERXN_MIRROR
			@CSOURCEDB='',
			@CSOURCETABLE='FORM',
			@CDESTDB=@CDESTDB,
			@CDESTTABLE='FORM',
			@CKEYFIELD1='FORM_ID',
			@LINSERTONLY=0,
			@CFILTERCONDITION=@CFILTERCONDITION,
			
			
			@LUPDATEONLY=0,
			@BALWAYSUPDATE=1
		END
							
		GOTO END_PROC									
	END TRY
	
	BEGIN CATCH
		SELECT @CERRORMSG='PROCEDURE SP3S_GET_FORM_FKEYDATA : '+ISNULL(ERROR_PROCEDURE(),'NULL P')+'STEP :'+STR(ISNULL(@NSTEP,0))+ ' LINE NO. :'+
		ISNULL(LTRIM(RTRIM(STR(ERROR_LINE()))),'NULL LINE')+'MSG :'+ISNULL(ERROR_MESSAGE(),'NULL MSG')
		
		GOTO END_PROC
	END CATCH
	
END_PROC:
		
END
----'END OF PROCEDURE SP3S_GET_FORM_FKEYDATA'
