CREATE PROCEDURE SP_BUYERSORDER_WSL_15
@CMEMOID VARCHAR(40),  
@CWHERE VARCHAR(500),  
@CFINYEAR VARCHAR(10),  
@NNAVMODE NUMERIC(2,0),
@CARTICLECODE CHAR(9)='',  
@CPARA2CODE CHAR(7)='',
@DTWHERE DATETIME ='',
@cLocId VARCHAR(5)=''
--WITH ENCRYPTION
 
AS    
BEGIN 
  SELECT DISTINCT A.ARTICLE_CODE, A.PARA2_CODE, B.PARA2_NAME,B.PARA2_ORDER ,A.MRP,A.WS_PRICE 
  FROM ART_DET A (NOLOCK)     
  JOIN PARA2 B (NOLOCK)  ON A.PARA2_CODE = B.PARA2_CODE    
  WHERE A.ARTICLE_CODE = @CWHERE     
  ORDER BY B.PARA2_ORDER    
END