CREATE PROCEDURE SP_MERGE_MIRROR_XNSLM_DATA
(
	@CMEMOID VARCHAR(50),  
    @CLOCID VARCHAR(2), 
    @CSOURCEDB VARCHAR(100),
	@CMERGEDB VARCHAR(100),
	@BMSTINSERTONLY BIT, 
    @CERRMSG VARCHAR(MAX) OUTPUT  
)
AS
BEGIN
	DECLARE @CCMD NVARCHAR(MAX),@CSTEP VARCHAR(10),@CTABLE_SUFFIX VARCHAR(100),
	@CTABLENAME VARCHAR(100),@CTMP_TABLENAME VARCHAR(100),@CKEYFIELD VARCHAR(100),
	@CTABLESSTR VARCHAR(MAX)
	
	DECLARE @TXNSSENDINFO TABLE (ORG_TABLENAME VARCHAR(50),TMP_TABLENAME VARCHAR(50),XN_ID VARCHAR(40))
	BEGIN TRY 
			
			SET @CTABLE_SUFFIX = REPLACE(@CMEMOID,'-','_') 
			
			INSERT @TXNSSENDINFO (ORG_TABLENAME) VALUES ('REGIONM')
			INSERT @TXNSSENDINFO (ORG_TABLENAME) VALUES ('STATE')
			INSERT @TXNSSENDINFO (ORG_TABLENAME) VALUES ('CITY') 
			INSERT @TXNSSENDINFO (ORG_TABLENAME) VALUES ('AREA')   
			INSERT @TXNSSENDINFO (ORG_TABLENAME) VALUES ('LMP01106') 
			INSERT @TXNSSENDINFO (ORG_TABLENAME) VALUES ('LM01106') 

			SET @CSTEP = 20 
			SET @CTABLENAME='REGIONM'  
			SET @CTMP_TABLENAME='TMP_XNSLM_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))  
			SET @CKEYFIELD='REGION_CODE'  
			EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB  
				 ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''  
				 ,@LINSERTONLY=1,@CJOINSTR='',@LUPDATEONLY=0  
				 ,@BALWAYSUPDATE=1 
				 
			SET @CSTEP = 30 
			SET @CTABLENAME='STATE'  
			SET @CTMP_TABLENAME='TMP_XNSLM_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))  
			SET @CKEYFIELD='STATE_CODE'  
			SET @CSTEP=40 
			EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB  
				 ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''  
				 ,@LINSERTONLY=1,@CJOINSTR='',@LUPDATEONLY=0  
				 ,@BALWAYSUPDATE=1 
		   
			SET @CSTEP = 60
			SET @CTABLENAME='CITY'  
			SET @CTMP_TABLENAME='TMP_XNSLM_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))  
			SET @CKEYFIELD='CITY_CODE'  
			SET @CSTEP=80 
			EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB  
				 ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''  
				 ,@LINSERTONLY=1,@CJOINSTR='',@LUPDATEONLY=0  
				 ,@BALWAYSUPDATE=1 
		    
			SET @CSTEP = 100
			SET @CTABLENAME='AREA'  
			SET @CTMP_TABLENAME='TMP_XNSLM_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))  
			SET @CKEYFIELD='AREA_CODE'  
			SET @CSTEP= 120 
			EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB  
				 ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''  
				 ,@LINSERTONLY=1,@CJOINSTR='',@LUPDATEONLY=0  
				 ,@BALWAYSUPDATE=1
		    
			SET @CSTEP= 130 
			SET @cCmd=N'UPDATE a SET ac_name=a.ac_name+''_''+a.ac_code from '+@CTMP_TABLENAME+' A
						JOIN lm01106 b ON a.ac_name=b.ac_name
						WHERE a.ac_code<>b.ac_code'
			EXEC SP_EXECUTESQL @cCmd

			SET @CSTEP = 140
			SET @CTABLENAME='LM01106'  
			SET @CTMP_TABLENAME='TMP_XNSLM_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))  
			SET @CKEYFIELD='AC_CODE'  
			SET @CSTEP= 160
			
			EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB  
				 ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''  
				 ,@LINSERTONLY=1,@CJOINSTR='',@LUPDATEONLY=0  
				 ,@BALWAYSUPDATE=1                    

			SET @CSTEP = 170
			SET @CTABLENAME='LMP01106'  
			SET @CTMP_TABLENAME='TMP_XNSLM_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))  
			SET @CKEYFIELD='AC_CODE'  
			
			EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB  
				 ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''  
				 ,@LINSERTONLY=1,@CJOINSTR='',@LUPDATEONLY=0  
				 ,@BALWAYSUPDATE=1                    
				         
	END TRY
    
	BEGIN CATCH
	 SET @CERRMSG='P:SP_MERGE_MIRROR_XNSLM_DATA, STEP:'+LTRIM(RTRIM(STR(@CSTEP)))+', MESSAGE:'+ERROR_MESSAGE()
	END CATCH

EXIT_PROC:
	IF ISNULL(@CERRMSG,'')='' AND @@TRANCOUNT>0  
		COMMIT  
	ELSE
	IF ISNULL(@CERRMSG,'')<>'' AND @@TRANCOUNT>0  
		ROLLBACK  

   SET @CTABLESSTR='STATE,CITY,AREA,LM01106,LMP01106,XNSTABLELIST'
   IF ISNULL(@CERRMSG,'')=''	
	   EXEC SP3S_DROPTEMPTABLES_MIRRORDATA
		@CXNTYPE='XNSLM',
		@CTABLESUFFIX=@CTABLE_SUFFIX,
		@CTABLESSTR=@CTABLESSTR
		
END
--END OF THE PROCEDURES SP_MERGE_MIRROR_XNSLM_DATA
