CREATE PROCEDURE SPSIS_UPDATE_LOCATION_MAX_CM_DT
AS
BEGIN
	;WITH CMM
	AS
	(
		/*Rohit 30-10-2024
		SELECT LEFT(CM_ID,2) AS DEPT_ID,MAX(CM_DT) AS CM_DT
		FROM CMM01106 (NOLOCK)
		WHERE CANCELLED=0
		GROUP BY LEFT(CM_ID,2)
		*/
		SELECT LOCATION_CODE AS DEPT_ID,MAX(CM_DT) AS CM_DT
		FROM CMM01106 (NOLOCK)
		WHERE CANCELLED=0
		GROUP BY LOCATION_CODE
	)
	UPDATE A SET A.max_cm_dt=CMM.CM_DT
	FROM LOCATION A
	JOIN CMM ON CMM.DEPT_ID=A.dept_id
END