CREATE PROCEDURE SP_PRD_SPLIT_N_COMBINE  
(      
 @NQUERYID INT,  
 @CMEMOID VARCHAR(25),  
 @CWHERE  VARCHAR(500) = ''    
)  
--WITH ENCRYPTION

AS  
BEGIN
 
IF @NQUERYID = 1    
	GOTO LBLGETMASTER    
ELSE IF @NQUERYID = 2    
	GOTO LBLGETDETAIL    
ELSE IF @NQUERYID = 3    
	GOTO LBLGETSUBDETAIL      
ELSE IF @NQUERYID = 4    
	GOTO LBLGETBARCODEDETAIL 
ELSE IF	@NQUERYID = 5    
	GOTO LBLGETALLBARCODEDETAIL 
ELSE    
  GOTO LAST     
    
LBLGETMASTER:    
   
	 SELECT D.USERNAME AS 'CREATED_USERNAME', E.USERNAME AS 'MODIFIED_USERNAME',       
	  C.AC_NAME AS SUPP_NAME,C.ADDRESS0+' '+ C.ADDRESS1 + ' ' + C.ADDRESS2 + ', ' + C.AREA_NAME +       
	  ' ' + C.CITY + ' ' + C.STATE AS 'SUPP_ADDRESS',  A.* ,C.MRP_CALC_MODE , C.ALIAS,    
		 '' AS  FORM_NAME, '' AS FORM_ID,BIN.BIN_NAME,C.MP_PERCENTAGE   
	 FROM PRD_SNC_MST A  (NOLOCK)    
	 JOIN LMV01106 C (NOLOCK) ON A.AC_CODE = C.AC_CODE      
	 JOIN USERS D (NOLOCK) ON A.USER_CODE = D.USER_CODE      
	 JOIN USERS E (NOLOCK) ON A.EDT_USER_CODE = E.USER_CODE     
	 JOIN BIN (NOLOCK) ON BIN.BIN_ID = A.BIN_ID             
	 WHERE A.MEMO_ID = @CMEMOID      
	   
	 GOTO LAST   
    
LBLGETDETAIL:  
    
	 SELECT K.SECTION_NAME, J.SUB_SECTION_NAME, I.*, C.PARA1_NAME,CONVERT(VARCHAR(40),'') AS PRODUCT_CODE,        
	 D.PARA2_NAME,E.PARA3_NAME,F.PARA4_NAME,G.PARA5_NAME,H.PARA6_NAME,B.ARTICLE_NO,         
	 B.ARTICLE_NAME, B.CODING_SCHEME, A.*,A.PURCHASE_PRICE * A.QUANTITY AS 'AMOUNT'  ,      
	 ISNULL(B.DT_CREATED,'') AS [ART_DT_CREATED],ISNULL(E.DT_CREATED,'') AS [PARA3_DT_CREATED],      
	 '' AS [SKU_DT_CREATED],B.GEN_EAN_CODES,         
	 '' AS OTHER_XN_PRODUCT_CODE,D.PARA2_ORDER, B.SIZE_RATE_DIFF ,B.SIZE_CENTER_POINT,     
	 A.QUANTITY AS [ORG_QUANTITY],CAST(0 AS NUMERIC(10,2)) AS [STK_QUANTITY],B.STOCK_NA,    
	 FORM.FORM_NAME,B.FIX_MRP, '' AS PRODUCT_NAME,B.FIX_PRICE_ARTICLE,CONVERT(NUMERIC(2),0) AS  MODE,    
	 B.ALIAS AS ARTICLE_ALIAS  ,'' AS PRODUCT_UID  
	 FROM PRD_SNC_DET A (NOLOCK)       
	 JOIN ARTICLE B (NOLOCK) ON A.ARTICLE_CODE = B.ARTICLE_CODE         
	 JOIN PARA1 C (NOLOCK) ON A.PARA1_CODE = C.PARA1_CODE        
	 JOIN PARA2 D (NOLOCK) ON A.PARA2_CODE = D.PARA2_CODE        
	 JOIN PARA3 E (NOLOCK) ON A.PARA3_CODE = E.PARA3_CODE        
	 JOIN PARA4 F (NOLOCK) ON A.PARA4_CODE = F.PARA4_CODE        
	 JOIN PARA5 G (NOLOCK) ON A.PARA5_CODE = G.PARA5_CODE        
	 JOIN PARA6 H (NOLOCK) ON A.PARA6_CODE = H.PARA6_CODE        
	 JOIN UOM I (NOLOCK) ON B.UOM_CODE = I.UOM_CODE        
	 JOIN SECTIOND J (NOLOCK) ON B.SUB_SECTION_CODE = J.SUB_SECTION_CODE        
	 JOIN SECTIONM K (NOLOCK) ON J.SECTION_CODE = K.SECTION_CODE     
	 JOIN FORM (NOLOCK) ON FORM.FORM_ID=A.FORM_ID     
	 WHERE A.MEMO_ID = @CMEMOID  
	 ORDER BY A.SRNO        

	 GOTO LAST   
    
LBLGETSUBDETAIL:  
   
	 SELECT DISTINCT  K.SECTION_NAME, J.SUB_SECTION_NAME, I.*, C.PARA1_NAME,((T.QUANTITY+T.WASTAGE_QUANTITY)*T.PURCHASE_PRICE) AS AMOUNT,        
	 D.PARA2_NAME,E.PARA3_NAME,F.PARA4_NAME,G.PARA5_NAME,H.PARA6_NAME,B.ARTICLE_NO,         
	 B.ARTICLE_NAME, B.CODING_SCHEME, T.*,ISNULL(B.DT_CREATED,'') AS [ART_DT_CREATED],  
	 ISNULL(E.DT_CREATED,'') AS [PARA3_DT_CREATED], '' AS [SKU_DT_CREATED],  
	 B.GEN_EAN_CODES,  '' AS OTHER_XN_PRODUCT_CODE,D.PARA2_ORDER, B.SIZE_RATE_DIFF ,B.SIZE_CENTER_POINT,     
	 CAST(0 AS NUMERIC(10,2)) AS [STK_QUANTITY],B.STOCK_NA,    
	 FORM.FORM_NAME,B.FIX_MRP,  '' AS PRODUCT_NAME,B.FIX_PRICE_ARTICLE,CONVERT(NUMERIC(2),0) AS  MODE,    
	 B.ALIAS AS ARTICLE_ALIAS,B1.BIN_NAME  ,T.PRODUCT_UID   
	 FROM PRD_SNC_CONSUMABLE_DET T (NOLOCK)    
	 JOIN SKU ON SKU.PRODUCT_CODE=T.PRODUCT_CODE
	 JOIN PRD_SNC_DET T1 (NOLOCK) ON  T.MEMO_ID=T1.MEMO_ID  
	 JOIN PRD_SNC_MST T2 (NOLOCK) ON  T1.MEMO_ID=T2.MEMO_ID  
	 JOIN ARTICLE B (NOLOCK) ON SKU.ARTICLE_CODE = B.ARTICLE_CODE         
	 JOIN PARA1 C (NOLOCK) ON SKU.PARA1_CODE = C.PARA1_CODE        
	 JOIN PARA2 D (NOLOCK) ON SKU.PARA2_CODE = D.PARA2_CODE        
	 JOIN PARA3 E (NOLOCK) ON SKU.PARA3_CODE = E.PARA3_CODE        
	 JOIN PARA4 F (NOLOCK) ON SKU.PARA4_CODE = F.PARA4_CODE        
	 JOIN PARA5 G (NOLOCK) ON SKU.PARA5_CODE = G.PARA5_CODE        
	 JOIN PARA6 H (NOLOCK) ON SKU.PARA6_CODE = H.PARA6_CODE        
	 JOIN UOM I (NOLOCK) ON B.UOM_CODE = I.UOM_CODE        
	 JOIN SECTIOND J (NOLOCK) ON B.SUB_SECTION_CODE = J.SUB_SECTION_CODE        
	 JOIN SECTIONM K (NOLOCK) ON J.SECTION_CODE = K.SECTION_CODE     
	 JOIN FORM (NOLOCK) ON FORM.FORM_ID=SKU.FORM_ID   
	 JOIN BIN B1 ON B1.BIN_ID=ISNULL(T.BIN_ID,'000')       
	 WHERE T2.MEMO_ID = @CMEMOID  AND ISNULL(T.REF_ROW_ID,'')= (CASE WHEN T2.SNC_MST_MODE=1 THEN ISNULL(T.REF_ROW_ID,'') ELSE T1.ROW_ID END)     
	 ORDER BY T.AUTO_SRNO    
    
	 GOTO LAST
	 
   

LBLGETBARCODEDETAIL:
	    
     SELECT REFROW_ID,PRODUCT_CODE FROM PRD_SNC_BARCODE_DET WHERE REFROW_ID=@CWHERE
     GOTO LAST
LBLGETALLBARCODEDETAIL:     
     SELECT A.PRODUCT_CODE ,(CASE WHEN D.BARCODE_CODING_SCHEME=3 THEN 1 ELSE B.QUANTITY END ) AS [QUANTITY]
     FROM PRD_SNC_BARCODE_DET A
     JOIN PRD_SNC_DET B ON B.ROW_ID=A.REFROW_ID
     JOIN PRD_SNC_MST C ON C.MEMO_ID=B.MEMO_ID
     JOIN SKU D ON D.PRODUCT_CODE=A.PRODUCT_CODE
     WHERE C.MEMO_ID=@CWHERE
     GOTO LAST

LAST:    


END
