create PROCEDURE [DBO].[SP3S_INV_JOBCARD_ISSUE]          
(          
  @IMODE INT ,          
  @CWHERE VARCHAR(MAX)='',      
  @CAGENCYCODE VARCHAR(20)='',      
  @FINYEAR VARCHAR(10)=''  ,    
  @DEPTID VARCHAR(10)='' ,
  @NRETURNMODE INT=0,
  @CJOB_CODE VARCHAR(10)='',
  @CPRODUCT_CODE VARCHAR(50)='',
  @bitemReturn bit=0
          
)      
AS                   
BEGIN          
    IF @IMODE =1         
		EXEC SP3S_INV_JOBCARD_ISSUE_1 @IMODE=@IMODE,@CWHERE =@CWHERE,@CAGENCYCODE =@CAGENCYCODE,@FINYEAR =@FINYEAR,@DEPTID =@DEPTID,@NRETURNMODE =@NRETURNMODE
    ELSE IF @IMODE =2    
		EXEC SP3S_INV_JOBCARD_ISSUE_2 @IMODE=@IMODE,@CWHERE =@CWHERE,@CAGENCYCODE =@CAGENCYCODE,@FINYEAR =@FINYEAR,@DEPTID =@DEPTID,@NRETURNMODE =@NRETURNMODE
	ELSE IF @IMODE =3	 
		EXEC SP3S_INV_JOBCARD_ISSUE_3 @IMODE=@IMODE,@CWHERE =@CWHERE,@CAGENCYCODE =@CAGENCYCODE,@FINYEAR =@FINYEAR,@DEPTID =@DEPTID,@NRETURNMODE =@NRETURNMODE
	ELSE IF @IMODE =4	 
		EXEC SP3S_INV_JOBCARD_ISSUE_4 @IMODE=@IMODE,@CWHERE =@CWHERE,@CAGENCYCODE =@CAGENCYCODE,@FINYEAR =@FINYEAR,@DEPTID =@DEPTID,@NRETURNMODE =@NRETURNMODE
	ELSE IF @IMODE =5    
		EXEC SP3S_INV_JOBCARD_ISSUE_5 @IMODE=@IMODE,@CWHERE =@CWHERE,@CAGENCYCODE =@CAGENCYCODE,@FINYEAR =@FINYEAR,@DEPTID =@DEPTID,@NRETURNMODE =@NRETURNMODE
	ELSE IF @IMODE =6    
		EXEC SP3S_INV_JOBCARD_ISSUE_6 @IMODE=@IMODE,@CWHERE =@CWHERE,@CAGENCYCODE =@CAGENCYCODE,@FINYEAR =@FINYEAR,@DEPTID =@DEPTID,@NRETURNMODE =@NRETURNMODE
	ELSE IF @IMODE =7    
		EXEC SP3S_INV_JOBCARD_ISSUE_7 @IMODE=@IMODE,@CWHERE =@CWHERE,@CAGENCYCODE =@CAGENCYCODE,@FINYEAR =@FINYEAR,@DEPTID =@DEPTID,@NRETURNMODE =@NRETURNMODE        
	ELSE IF @IMODE =8	 
		EXEC SP3S_INV_JOBCARD_ISSUE_8 @IMODE=@IMODE,@CWHERE =@CWHERE,@CAGENCYCODE =@CAGENCYCODE,@FINYEAR =@FINYEAR,@DEPTID =@DEPTID,@NRETURNMODE =@NRETURNMODE
	ELSE IF @IMODE =9	 
		EXEC SP3S_INV_JOBCARD_ISSUE_9 @IMODE=@IMODE,@CWHERE =@CWHERE,@CAGENCYCODE =@CAGENCYCODE,@FINYEAR =@FINYEAR,@DEPTID =@DEPTID,@NRETURNMODE =@NRETURNMODE
	ELSE IF @IMODE =10	 
		EXEC SP3S_INV_JOBCARD_ISSUE_10 @IMODE=@IMODE,@CWHERE =@CWHERE,@CAGENCYCODE =@CAGENCYCODE,@FINYEAR =@FINYEAR,@DEPTID =@DEPTID,@NRETURNMODE =@NRETURNMODE
	ELSE IF @IMODE =11   
		EXEC SP3S_INV_JOBCARD_ISSUE_11 @IMODE=@IMODE,@CWHERE =@CWHERE,@CAGENCYCODE =@CAGENCYCODE,@FINYEAR =@FINYEAR,@DEPTID =@DEPTID,@NRETURNMODE =@NRETURNMODE
	ELSE IF @IMODE =12   
		EXEC SP3S_INV_JOBCARD_ISSUE_12 @IMODE=@IMODE,@CWHERE =@CWHERE,@CAGENCYCODE =@CAGENCYCODE,@FINYEAR =@FINYEAR,@DEPTID =@DEPTID,@NRETURNMODE =@NRETURNMODE,@CPRODUCT_CODE=@CPRODUCT_CODE,@bitemReturn=@bitemReturn
	ELSE IF @IMODE =13   
		EXEC SP3S_INV_JOBCARD_ISSUE_13 @IMODE=@IMODE,@CWHERE =@CWHERE,@CAGENCYCODE =@CAGENCYCODE,@FINYEAR =@FINYEAR,@DEPTID =@DEPTID,@NRETURNMODE =@NRETURNMODE,@CJOB_CODE=@CJOB_CODE
	ELSE IF @IMODE =14	 
		EXEC SP3S_INV_JOBCARD_ISSUE_14 @IMODE=@IMODE,@CWHERE =@CWHERE,@CAGENCYCODE =@CAGENCYCODE,@FINYEAR =@FINYEAR,@DEPTID =@DEPTID,@NRETURNMODE =@NRETURNMODE
	ELSE IF @IMODE =15	 
		EXEC SP3S_INV_JOBCARD_ISSUE_15 @IMODE=@IMODE,@CWHERE =@CWHERE,@CAGENCYCODE =@CAGENCYCODE,@FINYEAR =@FINYEAR,@DEPTID =@DEPTID,@NRETURNMODE =@NRETURNMODE
	ELSE IF @IMODE =16	 
		EXEC SP3S_INV_JOBCARD_ISSUE_16 @IMODE=@IMODE,@CWHERE =@CWHERE,@CAGENCYCODE =@CAGENCYCODE,@FINYEAR =@FINYEAR,@DEPTID =@DEPTID,@NRETURNMODE =@NRETURNMODE
	ELSE IF @IMODE =17	 
		EXEC SP3S_INV_JOBCARD_ISSUE_17 @IMODE=@IMODE,@CWHERE =@CWHERE,@CAGENCYCODE =@CAGENCYCODE,@FINYEAR =@FINYEAR,@DEPTID =@DEPTID,@NRETURNMODE =@NRETURNMODE
	ELSE IF @IMODE =18	 
		EXEC SP3S_INV_JOBCARD_ISSUE_18 @IMODE=@IMODE,@CWHERE =@CWHERE,@CAGENCYCODE =@CAGENCYCODE,@FINYEAR =@FINYEAR,@DEPTID =@DEPTID,@NRETURNMODE =@NRETURNMODE
	ELSE IF @IMODE =19	 
		EXEC SP3S_INV_JOBCARD_ISSUE_19 @IMODE=@IMODE,@CWHERE =@CWHERE,@CAGENCYCODE =@CAGENCYCODE,@FINYEAR =@FINYEAR,@DEPTID =@DEPTID,@NRETURNMODE =@NRETURNMODE
	ELSE IF @IMODE =20	 
		EXEC SP3S_INV_JOBCARD_ISSUE_20 @IMODE=@IMODE,@CWHERE =@CWHERE,@CAGENCYCODE =@CAGENCYCODE,@FINYEAR =@FINYEAR,@DEPTID =@DEPTID,@NRETURNMODE =@NRETURNMODE
	ELSE IF @IMODE =21	 
		EXEC SP3S_INV_JOBCARD_ISSUE_21 @IMODE=@IMODE,@CWHERE =@CWHERE,@CAGENCYCODE =@CAGENCYCODE,@FINYEAR =@FINYEAR,@DEPTID =@DEPTID,@NRETURNMODE =@NRETURNMODE              
END
