CREATE PROCEDURE SPWOW_GST_CALC_QUERIES
@nQueryId INT,
@dMemoDt DATETIME='',
@cLocationId VARCHAR(4)=''
AS
BEGIN

	IF @nQueryId=1
		select top 1 row_id,hsn_code,mrp,quantity,xn_value_without_gst,xn_value_with_gst,
		NET_VALUE_WOTAX,net_value,cgst_amount,sgst_amount,igst_amount,gst_percentage,gst_percentage tax_percentage,
		gst_percentage RATE_CUTOFF_TAX_PERCENTAGE,Gst_Cess_Percentage,Gst_Cess_Percentage Rate_CutOff_Gst_Cess_Percentage,
		Gst_Cess_Percentage Cess_Percentage,gst_percentage RATE_CUTOFF,
		cess_amount,XN_VALUE_WITH_GST,CESS_AMOUNT Gst_Cess_Amount,CONVERT(INT,0) GST_CAL_BASIS,convert(int,0) tax_method
		from GST_TAXINFO_CALC (NOLOCK)
		--for json path
		WHERE 1=2
		
	ELSE
	IF @nQueryId=2 -- This Query id to be called on Hsn master merging or Memo date change in the Bill
	BEGIN

		DECLARE @CFC_CODE VARCHAR(7),@CALL_XN_IGST VARCHAR(5),@CALWAYS_PICK_GST_MODE_IN_RETAIL VARCHAR(10),
		@OTHER_CHARGES_HSN_CODE VARCHAR(20),@nOHGstPercentage NUMERIC(6,2)
		SELECT @CFC_CODE=fc_code  FROM location (NOLOCK) WHERE DEPT_ID=@cLocationId

       
       SELECT TOP 1 @CALL_XN_IGST=VALUE  FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION ='ALL_XN_IGST' 
       
       IF ISNULL(@CFC_CODE,'') NOT IN('','0000000')
	       	SET @CALL_XN_IGST='1'
		
       DECLARE @CREUPDATENETEXCL VARCHAR(5),@CREUPDATENETINCL VARCHAR(5),@CEXCLRANGEFROM VARCHAR(15),@CEXCLRANGETO VARCHAR(15),
	   @CEXCLRANGENET VARCHAR(15),@CINCLRANGEFROM VARCHAR(15),@CINCLRANGETO VARCHAR(15),@CINCLRANGENET VARCHAR(15)

		SELECT TOP 1 @CREUPDATENETEXCL=VALUE FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION='REUPDATE_NET_FOR_RANGE_EXCLUSIVE'
		SELECT TOP 1 @CREUPDATENETINCL=VALUE FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION='REUPDATE_NET_FOR_RANGE_INCLUSIVE'

	   SELECT TOP 1 @CEXCLRANGEFROM=VALUE FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION='FROM_NET_RANGE_EXCLUSIVE'
	   SELECT TOP 1 @CEXCLRANGETO=VALUE FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION='TO_NET_RANGE_EXCLUSIVE'
	   SELECT TOP 1 @CEXCLRANGENET=VALUE FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION='RANGE_EXCLUSIVE_CONVERT_NET'
	   SELECT TOP 1 @CINCLRANGEFROM=VALUE FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION='FROM_NET_RANGE_INCLUSIVE'
	   SELECT TOP 1 @CINCLRANGETO=VALUE FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION='TO_NET_RANGE_INCLUSIVE'
	   SELECT TOP 1 @CINCLRANGENET=VALUE FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION='RANGE_INCLUSIVE_CONVERT_NET'

	   SELECT @CALWAYS_PICK_GST_MODE_IN_RETAIL=value  FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION='ALWAYS_PICK_GST_MODE_IN_RETAIL_SALE_FROM_HSN_MASTER'

	   IF EXISTS (SELECT TOP 1 HSN_CODE FROM GST_OH_CONFIG (NOLOCK) WHERE OH_NAME='OC' AND XN_TYPE='SLS')
		   SELECT TOP 1 @OTHER_CHARGES_HSN_CODE=HSN_CODE,@nOHGstPercentage=GST_PERCENTAGE FROM GST_OH_CONFIG (NOLOCK) WHERE OH_NAME='OC' 
		   AND XN_TYPE='SLS'
	   ELSE
	   	   SELECT TOP 1 @OTHER_CHARGES_HSN_CODE=HSN_CODE,@nOHGstPercentage=GST_PERCENTAGE FROM GST_OH_CONFIG (NOLOCK) WHERE OH_NAME='OC' 

	   SELECT TOP 1 ISNULL(a.GST_STATE_CODE,'') CURSTATE_CODE,LOC_GST_NO,ISNULL(REGISTERED_GST,0) REGISTERED_DEALER,
	   ISNULL(CESS_APPLICABLE,0) CESS_APPLICABLE,ISNULL(b.CESS_PERCENTAGE,0) CESS_PERCENTAGE,ISNULL(@CALL_XN_IGST,'') ALL_XN_IGST,
	   ISNULL(@CALWAYS_PICK_GST_MODE_IN_RETAIL,'') ALWAYS_PICK_GST_MODE_IN_RETAIL_SALE_FROM_HSN_MASTER,
	   CONVERT(VARCHAR(20),'') party_gst_no,CONVERT(VARCHAR(20),'') party_state_code,
	   CONVERT(BIT,0) custdym_export_gst_percentage_Applicable,convert(numeric(7,2),0) custdym_export_gst_percentage,
	   ISNULL(@OTHER_CHARGES_HSN_CODE,'') OTHER_CHARGES_HSN_CODE,ISNULL(@nOHGstPercentage,0) OTHER_CHARGES_Gst_Percentage,
	   @dMemoDt memo_dt,@CREUPDATENETEXCL REUPDATE_NET_FOR_RANGE_EXCLUSIVE,@CREUPDATENETINCL REUPDATE_NET_FOR_RANGE_INCLUSIVE,@CEXCLRANGEFROM  FROM_NET_RANGE_EXCLUSIVE,
	   @CEXCLRANGETO TO_NET_RANGE_EXCLUSIVE,@CEXCLRANGENET RANGE_EXCLUSIVE_CONVERT_NET,@CINCLRANGEFROM FROM_NET_RANGE_INCLUSIVE,@CINCLRANGETO TO_NET_RANGE_INCLUSIVE,
	   @CINCLRANGENET  RANGE_INCLUSIVE_CONVERT_NET

	   FROM LOCATION A (NOLOCK)
	   LEFT JOIN GST_STATE_DET b (NOLOCK) ON a.gst_state_code=b.GST_STATE_CODE
	   AND @dMemoDt BETWEEN B.FM_DT AND B.TO_DT
	   WHERE A.DEPT_ID =@cLocationId 
	   --FOR JSON Path
       
       IF ISNULL(@CFC_CODE,'') NOT IN('','0000000')
       		SET @CALL_XN_IGST='1'
	
		SELECT hsn_code,RETAILSALE_TAX_METHOD FROM hsn_mst (NOLOCK)
		--FOR JSON Path

		;WITH CTE AS
			(
			SELECT a.HSN_CODE,ISNULL(C.TAX_PERCENTAGE,0) AS TAX_PERCENTAGE,ISNULL(C.RATE_CUTOFF,0) AS RATE_CUTOFF,
					ISNULL(C.RATE_CUTOFF_TAX_PERCENTAGE,0) AS RATE_CUTOFF_TAX_PERCENTAGE,
					ISNULL(C.WEF,'') AS WEF,
					SR=ROW_NUMBER() OVER (PARTITION BY A.hsn_code ORDER BY C.WEF DESC),
					ISNULL(C.GST_CAL_BASIS,1) AS GST_CAL_BASIS,
					isnull(c.Rate_CutOff_Gst_Cess_Percentage,0) as Rate_CutOff_Gst_Cess_Percentage,
					isnull(c.Gst_Cess_Percentage,0) as Gst_Cess_Percentage
			FROM hsn_mst A (NOLOCK)
			LEFT JOIN HSN_DET C (NOLOCK) ON a.HSN_CODE =C.HSN_CODE AND C.WEF  <=@dMemoDt AND ISNULL(C.DEPT_ID,'')=
			(CASE WHEN ISNULL(@CFC_CODE,'')IN('','0000000') THEN  '' ELSE @cLocationId END)
			)
			SELECT *
			FROM CTE WHERE SR=1
			--FOR JSON Path
	END
END
