CREATE procEDURE SP_WSLINV_4--(LocId 3 digit change only increased the parameter width by Sanjay:04-11-2024)
	@CMEMOID	VARCHAR(40) = '',
	@CWHERE1	VARCHAR(500) = '',
	@NNAVMODE	NUMERIC(1,0) = 0,
	@CWHERE2	NVARCHAR(MAX)='',
	@DMEMODT DATETIME='',
	@CLOCID		VARCHAR(4)=''
----WITH ENCRYPTION
AS
BEGIN
	
	IF(@CWHERE1 = '1')
		SELECT * FROM FORM (NOLOCK) WHERE FORM_ID <> '0000000' AND EXCISE_ACCESSIBLE_PERCENTAGE > 0	AND INACTIVE=0
	ELSE
		SELECT * FROM FORM (NOLOCK) WHERE FORM_ID <> '0000000' AND EXCISE_ACCESSIBLE_PERCENTAGE = 0 AND INACTIVE=0

END