CREATE PROCEDURE SP_STOCKRECON_COLLIST
(
	@NMODE NUMERIC(1),
	@USERCODE VARCHAR(10),
	@REPID VARCHAR(10)
)
AS
BEGIN

DECLARE @CPARA1 VARCHAR(100) DECLARE @CPARA2 VARCHAR(100) DECLARE @CPARA3 VARCHAR(100)
DECLARE @CPARA4 VARCHAR(100) DECLARE @CPARA5 VARCHAR(100) DECLARE @CPARA6 VARCHAR(100)

SELECT @CPARA1= VALUE FROM CONFIG WHERE  CONFIG_OPTION= 'PARA1_caption'
SELECT @CPARA2= VALUE FROM CONFIG WHERE  CONFIG_OPTION= 'PARA2_caption'
SELECT @CPARA3= VALUE FROM CONFIG WHERE CONFIG_OPTION= 'PARA3_caption'
SELECT @CPARA4= VALUE FROM CONFIG WHERE  CONFIG_OPTION= 'PARA4_caption'
SELECT @CPARA5= VALUE FROM CONFIG WHERE CONFIG_OPTION= 'PARA5_caption'
SELECT @CPARA6= VALUE FROM CONFIG WHERE CONFIG_OPTION= 'PARA6_caption'

DECLARE @ALLCOLSLIST TABLE(CHK BIT,COLNAME VARCHAR(100),COLEXP VARCHAR(100),WIDTH VARCHAR(10),GRP BIT,COLORDER NUMERIC(3))	
SET @NMODE =1

INSERT @ALLCOLSLIST(CHK,COLNAME,COLEXP,WIDTH,GRP,COLORDER)	


SELECT CAST (0 AS BIT) AS CHK,'Recon Id' AS COLNAME,'stm.Memo_Id' AS COLEXP, 25 AS WIDTH,CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,'Title' AS COLNAME,'stm_title' AS COLEXP, 50 AS WIDTH,CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,'Start Date' AS COLNAME,'stm_start_dt' AS COLEXP, 50 AS WIDTH,CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,'End Date' AS COLNAME,'stm_end_dt' AS COLEXP, 50 AS WIDTH,CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,'SECTION NAME' AS COLNAME, 'SECTION_NAME' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER 
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,'SUB SECTION NAME' AS COLNAME, 'SUB_SECTION_NAME' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,'ARTICLE NO' AS COLNAME, 'ARTICLE_NO' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
select CAST (0 AS BIT) AS CHK,table_caption  as COLNAME,column_name as COLEXP ,15 AS WIDTH,CAST (0 AS BIT) AS GRP,  0 AS COLORDER  from  config_attr where  table_caption <> ''
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,'PRODUCT CODE' AS COLNAME, 'PRODUCT_CODE' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER 
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,@CPARA1 AS COLNAME, 'PARA1_NAME' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,@CPARA2 AS COLNAME, 'PARA2_NAME' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,@CPARA3 AS COLNAME, 'PARA3_NAME' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,@CPARA4 AS COLNAME, 'PARA4_NAME' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,@CPARA5 AS COLNAME, 'PARA5_NAME' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,@CPARA6 AS COLNAME, 'PARA6_NAME' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,'UOM' AS COLNAME, 'UOM_NAME' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,'SUPPLIER' AS COLNAME, 'AC_NAME' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,'PUR RECEIPT DT' AS COLNAME, 'RECEIPT_DT' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,'PUR INV DT' AS COLNAME, 'INV_DT' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,'PUR INV NO' AS COLNAME, 'INV_NO' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,'MRP' AS COLNAME, 'MRP' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,'PURCHASE PRICE' AS COLNAME, 'PURCHASE_PRICE' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,'WS PRICE' AS COLNAME, 'WS_PRICE' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,'IMAGE' AS COLNAME, 'IMAGE' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,'USER NAME' AS COLNAME, 'USERNAME' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER 

UNION ALL
SELECT CAST (0 AS BIT) AS CHK,'BIN ID' AS COLNAME, 'BIN_ID' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER 
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,'LOT REMARKS' AS COLNAME,'lot_remarks' AS COLEXP, 15 AS WIDTH,CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,'SCANNED QTY' AS COLNAME, 'SCAN_QTY' AS COLEXP, 15 AS WIDTH,CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,'SCANNED VALUE AT PP' AS COLNAME,'SCAN_VALUE_AT_PP' AS COLEXP, 15 AS WIDTH,CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,'SCANNED VALUE AT MRP' AS COLNAME,'SCAN_VALUE_AT_MRP' AS COLEXP, 15 AS WIDTH,CAST (0 AS BIT) AS GRP,  0 AS COLORDER
UNION ALL
SELECT CAST (0 AS BIT) AS CHK,'SCANNED VALUE AT WSP' AS COLNAME,'SCAN_VALUE_AT_WSP' AS COLEXP, 15 AS WIDTH,CAST (0 AS BIT) AS GRP,  0 AS COLORDER


IF @NMODE=1
BEGIN
	INSERT @ALLCOLSLIST(CHK,COLNAME,COLEXP,WIDTH,GRP,COLORDER)	
	SELECT CAST (0 AS BIT) AS CHK,'STOCK QTY' AS COLNAME, 'COMPUTER_QTY' AS COLEXP, 15 AS WIDTH,CAST (0 AS BIT) AS GRP,  0 AS COLORDER
	UNION ALL
	SELECT CAST (0 AS BIT) AS CHK,'STOCK VALUE AT PP' AS COLNAME, 'COMPUTER_VALUE_AT_PP' AS COLEXP, 15 AS WIDTH,CAST (0 AS BIT) AS GRP,  0 AS COLORDER
	UNION ALL
	SELECT CAST (0 AS BIT) AS CHK,'STOCK VALUE AT MRP' AS COLNAME, 'COMPUTER_VALUE_AT_MRP' AS COLEXP, 15 AS WIDTH,CAST (0 AS BIT) AS GRP,  0 AS COLORDER
	UNION ALL
	SELECT CAST (0 AS BIT) AS CHK,'STOCK VALUE AT WSP' AS COLNAME, 'COMPUTER_VALUE_AT_WSP' AS COLEXP, 15 AS WIDTH,CAST (0 AS BIT) AS GRP,  0 AS COLORDER
	UNION ALL
	SELECT CAST (0 AS BIT) AS CHK,'SHORTAGE QTY' AS COLNAME, 'SHORTAGE_QTY' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
	UNION ALL
	SELECT CAST (0 AS BIT) AS CHK,'SHORTAGE VALUE AT PP' AS COLNAME, 'SHORTAGE_VALUE_AT_PP' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
	UNION ALL
	SELECT CAST (0 AS BIT) AS CHK,'SHORTAGE VALUE AT MRP' AS COLNAME, 'SHORTAGE_VALUE_AT_MRP' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
	UNION ALL
	SELECT CAST (0 AS BIT) AS CHK,'SHORTAGE VALUE AT WSP' AS COLNAME, 'SHORTAGE_VALUE_AT_WSP' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
	UNION ALL
	SELECT CAST (0 AS BIT) AS CHK,'EXCESS QTY' AS COLNAME, 'EXCESS_QTY' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
	UNION ALL
	SELECT CAST (0 AS BIT) AS CHK,'EXCESS VALUE AT PP' AS COLNAME, 'EXCESS_VALUE_AT_PP' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
	UNION ALL
	SELECT CAST (0 AS BIT) AS CHK,'EXCESS VALUE AT MRP' AS COLNAME, 'EXCESS_VALUE_AT_MRP' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
	UNION ALL
	SELECT CAST (0 AS BIT) AS CHK,'EXCESS VALUE AT WSP' AS COLNAME, 'EXCESS_VALUE_AT_WSP' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER
	--UNION ALL
	--SELECT CAST (0 AS BIT) AS CHK,'EXCESS QTY REALIZED' AS COLNAME, 'EXCESS_QTY_REALIZED' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER		
	--UNION ALL
	--SELECT CAST (0 AS BIT) AS CHK,'EXCESS REALIZED VALUE AT PP' AS COLNAME, 'EXCESS_REALIZED_VALUE_AT_PP' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER		
	--UNION ALL
	--SELECT CAST (0 AS BIT) AS CHK,'EXCESS REALIZED VALUE AT MRP' AS COLNAME, 'EXCESS_REALIZED_VALUE_AT_MRP' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER		
	--UNION ALL
	--SELECT CAST (0 AS BIT) AS CHK,'EXCESS REALIZED VALUE AT WSP' AS COLNAME, 'EXCESS_REALIZED_VALUE_AT_WSP' AS COLEXP, 15 AS WIDTH, CAST (0 AS BIT) AS GRP,  0 AS COLORDER		
END

SELECT ISNULL(B.CHK,0) AS CHK,A.COLNAME, A.COLEXP,ISNULL(B.WIDTH,15) AS WIDTH ,ISNULL(B.GRP,0) AS GRP, 
       ISNULL(B.COLORDER,0) AS COLORDER
FROM @ALLCOLSLIST A
LEFT OUTER JOIN STKRECON_COLLIST B ON A.COLNAME= B.COLNAME AND B.USER_CODE= @USERCODE AND B.REP_ID= @REPID

END
