CREATE PROCEDURE SP_SEND_MIRROR_DOCASN_OPT_DATA_NEW --(LocId 3 digit change by Sanjay:30-10-2024)
	 @CREQXNID VARCHAR(50)
	,@CTARGETLOCID VARCHAR(5)
	,@CREQCHALLANNO VARCHAR(20)=''
	,@CREQCHALLANFINYEAR VARCHAR(20)=''
	,@BACKNOWLEDGE BIT=0
	,@CERRMSG VARCHAR(1000) OUTPUT
AS
/*

	SP_SEND_MIRROR_DOCPO_OPT_DATA_NEW : THIS PROCEDURE USE TO SEND DOCPO DATA
*/
BEGIN
	DECLARE @DTSQL NVARCHAR(MAX),@CTEMPTABLE VARCHAR(500),@CMEMOID VARCHAR(50),
	@CTEMPEMPLOYEETABLE VARCHAR(200),@DMEMOLASTUPDATE DATETIME,@CTABLENAME VARCHAR(100),
	@BRECFOUND BIT,@CSTEP VARCHAR(5),@CFILTERCONDITION VARCHAR(MAX),@CCUTOFFDATE VARCHAR(20),
	@CTEMPMASTERTABLE VARCHAR(200),@CTEMPDETAILTABLE VARCHAR(200),@CTEMPLMTABLE VARCHAR(200),
	@CTEMPLMPTABLE VARCHAR(200),@CTEMPAREATABLE VARCHAR(200),@CTEMPCITYTABLE VARCHAR(200),
	@CTEMPPMODEXNTABLE VARCHAR(200),@CTEMPPMODETABLE VARCHAR(200),@CSTNAPPROVAL BIT,
	@CCLOCID VARCHAR(10),@CHOLOCID VARCHAR(10),@BSENDPURINFOLOC BIT,@CCURDEPTID VARCHAR(4),@CHODEPTID VARCHAR(4),
	@CTEMPSKUTABLE VARCHAR(500),@CTEMPSKUOHTABLE VARCHAR(500),
	@NTARGETLOCTYPE INT,@BTARGETPURLOC BIT,@CTEMPSLSBCTABLE VARCHAR(500),@CTEMPSLSDETTABLE VARCHAR(500), 
	@BGETCHALLANTHRUMIRROR BIT,@CPARTYDEPTID VARCHAR(5),@NMODE INT,
	@BCOMPLETED BIT,@BEXPORTED BIT,@CDISPATCHDETAILS VARCHAR(500),@CDONOTSENDCHALLANWODISPATCHDETAILS VARCHAR(2),
	@CJOINSTR VARCHAR(1000),@BTEMPDATADELETED BIT,@NSPID INT,@BDONOTSENDCHALLANWITHOUTDISPATCH BIT
	
	SET @NSPID = @@SPID
	
LBLSTART:
	
	PRINT 'ENTER SP_SEND_MIRROR_DOCASN_OPT_DATA_NEW'
	 	
	DECLARE @TXNSSENDINFO TABLE (ORG_TABLENAME VARCHAR(500),TMP_TABLENAME VARCHAR(500),XN_ID VARCHAR(40))  

	SELECT TOP 1 @CCURDEPTID = [VALUE] FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION='LOCATION_ID'
	SELECT TOP 1 @CHODEPTID = [VALUE] FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION='HO_LOCATION_ID'
		


BEGIN TRY 	
			
	SET @CSTEP=10	
	SET @CFILTERCONDITION=''
	
	
	IF @BACKNOWLEDGE=1
		GOTO LBLTABLEINFO
 
LBLTABLEINFO:
	
	SET @CMEMOID = @CREQXNID

	IF @BACKNOWLEDGE=1
		GOTO END_PROC
		
	SET @CSTEP=50
	---- POPULATE LIST OF TABLES 
		
	
	SET @CFILTERCONDITION=' B.MEMO_ID='''+@CMEMOID+''''
	
	---- SEND THE PURCHASE ORDER MEMO MASTER TABLE
	
	SELECT 	@CMEMOID AS XN_ID,'DOCASN_ASN_MST_MIRROR' AS TARGET_TABLENAME,* FROM ASN_MST (NOLOCK) WHERE MEMO_ID=@CMEMOID
	SELECT 	@CMEMOID AS XN_ID,'DOCASN_ASN_DET_MIRROR' AS TARGET_TABLENAME,* FROM ASN_DET (NOLOCK) WHERE MEMO_ID=@CMEMOID
	
	GOTO END_PROC
	
END TRY
BEGIN CATCH
	SET @CERRMSG='P: SP_SEND_MIRROR_DOCASN_OPT_DATA_NEW, STEP:'+@CSTEP+', MESSAGE:'+ERROR_MESSAGE()
	GOTO END_PROC
END CATCH 		

END_PROC:
		
END
---END OF PROCEDURE - SP_SEND_MIRROR_DOCPO_OPT_DATA_NEW
