CREATE PROCEDURE  SP3S_VCH_FILTER_DET
(
	@cMemoID	VARCHAR(50)=''
)
AS
BEGIN
	SELECT D.X_TYPE,D.cost_center_dept_id AS DEPT_ID,AC.AC_NAME PARTICULAR,
	(CASE WHEN D.DEBIT_AMOUNT=0 THEN NULL ELSE D.DEBIT_AMOUNT END) DEBIT_AMOUNT,
	(CASE WHEN D.CREDIT_AMOUNT=0 THEN NULL ELSE D.CREDIT_AMOUNT END) CREDIT_AMOUNT,D.NARRATION,D.VM_ID AS MEMO_ID
	FROM VM01106 M(NOLOCK) 
	JOIN VD01106 D(NOLOCK) ON M.VM_ID=D.VM_ID  
	JOIN VCHTYPE VTYP (NOLOCK) ON VTYP.VOUCHER_CODE=M.VOUCHER_CODE  
	JOIN LMV01106 AC(NOLOCK) ON AC.AC_CODE=D.AC_CODE
	WHERE M.vm_id=@cMemoID
END