CREATE PROCEDURE SP_CNPS    

@NQUERYID NUMERIC(2,0),    
@CFROMDATE NVARCHAR(50),    
@CTODATE NVARCHAR(50),    
@CWHERE  NVARCHAR(MAX),    
@CWHERE1 VARCHAR(100)='',
@CMODE INT=1,
@CLOCATION VARCHAR(5)='',
@NESTIMATEMODE INT=1
     
AS    
BEGIN   
 --(dinkar) Replace  left(memoid,2) to Location_code 

DECLARE @CCMD NVARCHAR(MAX)    

IF @NQUERYID = 1    
GOTO LBLSUPPLIERSLOV    

ELSE IF @NQUERYID = 2    
GOTO LBLGETMST    

ELSE IF @NQUERYID = 3    
GOTO LBLGETDETAILS   

       
ELSE IF @NQUERYID = 4    
GOTO LBLPSMST   

ELSE IF @NQUERYID = 5    
GOTO LBLPSDET   

ELSE    
GOTO LAST    


LBLSUPPLIERSLOV:    
DECLARE @CHEADCODE VARCHAR(MAX),@CHEADCODE1 VARCHAR(MAX),@CHEADCODE2 VARCHAR(4000),@CHEADCODE3 VARCHAR(4000) 
SET @CHEADCODE=DBO.FN_ACT_TRAVTREE(@CWHERE)
SELECT  A.AC_CODE, A.AC_NAME, ISNULL(A.CREDIT_DAYS, 0) AS CREDIT_DAYS,       
ISNULL(A.DISCOUNT_PERCENTAGE, 0) AS DISCOUNT_PERCENTAGE,      
A.ADDRESS1 + ' ' + A.ADDRESS2 + ', ' + A.AREA_NAME + ' ' + A.CITY + ' ' +       
A.STATE AS 'SUPP_ADDRESS', AC_NAME AS REPCOLNAME ,  A.FORM_ID    ,ISNULL(A.ON_HOLD,0) AS ON_HOLD    
FROM LMV01106 A       
WHERE ( CHARINDEX ( HEAD_CODE,@CHEADCODE ) > 0  OR ALLOW_CREDITOR_DEBTOR = 1 )       
AND INACTIVE = 0 AND A.AC_NAME <> ''     
UNION ALL      
SELECT A.AC_CODE, ALIAS, ISNULL(A.CREDIT_DAYS, 0) AS CREDIT_DAYS,       
ISNULL(A.DISCOUNT_PERCENTAGE, 0) AS DISCOUNT_PERCENTAGE,       
A.ADDRESS1 + ' ' + A.ADDRESS2 + ', ' + A.AREA_NAME + ' ' + A.CITY + ' ' +       
A.STATE AS 'SUPP_ADDRESS', AC_NAME AS REPCOLNAME ,  A.FORM_ID  ,ISNULL(A.ON_HOLD,0) AS ON_HOLD       
FROM LMV01106 A       
WHERE ( CHARINDEX ( HEAD_CODE, @CHEADCODE ) > 0  OR ALLOW_CREDITOR_DEBTOR = 1 )       
AND INACTIVE = 0 AND A.ALIAS <> ''     
ORDER BY A.AC_NAME       

GOTO LAST    

LBLGETMST:   


SELECT  USERS.USERNAME,  C.AC_NAME AS SUPP_NAME,     
C.ADDRESS1 + ' ' + C.ADDRESS2 + ', ' + C.AREA_NAME + ' ' + C.CITY + ' ' + C.STATE AS 'SUPP_ADDRESS',    
MST.*, CONVERT(CHAR(10),CASE WHEN PS_DT='' THEN NULL ELSE PS_DT END ,105)  AS RM_DT1 ,
LOCATION.DEPT_NAME 
FROM CNPS_MST MST (NOLOCK)        
JOIN USERS (NOLOCK)  ON MST.USER_CODE = USERS.USER_CODE     
JOIN LMV01106 C ON MST.AC_CODE = C.AC_CODE   
LEFT OUTER JOIN LOCATION (NOLOCK)  ON MST.PARTY_DEPT_ID = LOCATION.DEPT_ID 
WHERE MST.PS_ID =@CWHERE    

GOTO LAST    

LBLGETDETAILS:    

SELECT  A.PRODUCT_CODE,A.QUANTITY, 
A.ROW_ID,A.LAST_UPDATE,A.DEPT_ID,A.PS_ID, B.UOM_CODE,       
RMM.CANCELLED,B.DISCON,E.UOM_TYPE,  B.ARTICLE_CODE,       
B.ARTICLE_NO, B.ARTICLE_NAME, B.ARTICLE_DESC, C.PARA1_CODE,       
C.PARA1_NAME, D.PARA2_CODE, D.PARA2_ORDER, D.PARA2_NAME, E.UOM_NAME, I.AC_CODE,        
CONVERT(VARCHAR, S.INV_DT, 105) AS 'INV_DT', S.RECEIPT_DT,   
S.INV_NO AS BILL_NO, S.CHALLAN_NO , E.UOM_TYPE,  
G.SUB_SECTION_NAME, H.PARA3_CODE,S.PURCHASE_PRICE,     
H.PARA3_NAME, I.AC_NAME, J.SECTION_NAME, S.MRP,S.WS_PRICE AS WSP, B.CODING_SCHEME, '' AS BRAND_NAME,     
X.PARA4_NAME, X.PARA4_CODE, Y.PARA5_NAME, Y.PARA5_CODE,     
Z.PARA6_NAME, Z.PARA6_CODE, A.QUANTITY ,
ISNULL(B.DT_CREATED,'') AS [ART_DT_CREATED],ISNULL(H.DT_CREATED,'') AS [PARA3_DT_CREATED],    
ISNULL(S.DT_CREATED,'') AS [SKU_DT_CREATED],I.CITY  ,S.PRODUCT_NAME,S.FIX_MRP,  
S.ER_FLAG,S.MRP,S.WS_PRICE , A.BIN_ID,BIN.BIN_NAME ,B.STOCK_NA,B.ALIAS AS ARTICLE_ALIAS
,ISNULL(A.BOX_ID,'') AS BOX_ID,CAST(0 as NUMERIC(14,2)) AS QUANTITY_IN_STOCK
FROM CNPS_DET A (NOLOCK)        
JOIN CNPS_MST RMM (NOLOCK) ON A.PS_ID = RMM.PS_ID        
JOIN SKU S (NOLOCK)  ON A.PRODUCT_CODE = S.PRODUCT_CODE      
LEFT OUTER JOIN SKU_OH F ON S.PRODUCT_CODE = F.PRODUCT_CODE      
JOIN ARTICLE B (NOLOCK)  ON S.ARTICLE_CODE = B.ARTICLE_CODE        
JOIN PARA1 C (NOLOCK) ON S.PARA1_CODE = C.PARA1_CODE        
JOIN PARA2 D (NOLOCK)  ON S.PARA2_CODE = D.PARA2_CODE       
JOIN PARA3 H (NOLOCK)  ON S.PARA3_CODE = H.PARA3_CODE        
JOIN PARA4 X (NOLOCK)  ON S.PARA4_CODE = X.PARA4_CODE        
JOIN PARA5 Y (NOLOCK)  ON S.PARA5_CODE = Y.PARA5_CODE        
JOIN PARA6 Z (NOLOCK)  ON S.PARA6_CODE = Z.PARA6_CODE       
JOIN UOM E  (NOLOCK)  ON B.UOM_CODE = E.UOM_CODE       
JOIN SECTIOND G (NOLOCK)  ON B.SUB_SECTION_CODE = G.SUB_SECTION_CODE        
JOIN LMV01106 I (NOLOCK)  ON S.AC_CODE = I.AC_CODE    
JOIN SECTIONM J (NOLOCK) ON G.SECTION_CODE = J.SECTION_CODE  
LEFT OUTER JOIN BIN (NOLOCK) ON BIN.BIN_ID=A.BIN_ID            
WHERE A.PS_ID =@CWHERE          
GOTO LAST 



  
LBLPSMST:    
     
    IF OBJECT_ID('TEMPDB..#TMPWPS','U') IS NOT NULL    
    DROP TABLE #TMPWPS    
      
    SELECT DISTINCT ISNULL(A.PS_ID,'') AS PS_ID 
	INTO #TMPWPS 
	FROM CND01106 A (NOLOCK) 
    JOIN CNM01106 B (NOLOCK) ON A.CN_ID=B.CN_ID      
    WHERE (B.AC_CODE=@CWHERE OR @CWHERE='' ) AND (B.PARTY_DEPT_ID=@CWHERE1 OR @CWHERE1='' )  
    AND B.MODE=@CMODE AND CANCELLED=0  
      
    SELECT CAST(0 AS BIT) AS BILLCHECK, B.PS_ID,B.PS_NO,B.PS_DT,   
    SUM(QUANTITY) AS TOTAL_QTY,      
    CAST('' AS NVARCHAR(10)) AS SRNO ,B.REMARKS    
    FROM CNPS_DET A (NOLOCK)      
    JOIN CNPS_MST B (NOLOCK) ON A.PS_ID= B.PS_ID       
    LEFT OUTER JOIN #TMPWPS C (NOLOCK) ON C.PS_ID=B.PS_ID    
    WHERE (B.AC_CODE=@CWHERE OR @CWHERE='' ) AND (B.PARTY_DEPT_ID=@CWHERE1 OR @CWHERE1='' )  
    AND B.PS_MODE=@CMODE    AND B.location_Code = @CLOCATION
	AND ISNULL(B.memo_type,1)=@NESTIMATEMODE
    AND CANCELLED=0 AND C.PS_ID IS NULL    
    GROUP BY  B.PS_ID,B.PS_NO,B.PS_DT ,B.REMARKS         
    ORDER BY PS_ID     
    
 GOTO LAST    
     
LBLPSDET:    
    
   DECLARE @CQRY1 NVARCHAR(MAX)          
   SET @CQRY1=N' SELECT        
   CAST(0 AS BIT) AS BILLCHECK      
  ,W1.PS_ID      
  ,W2.PS_NO      
  ,W2.PS_DT      
  ,W1.PRODUCT_CODE      
  ,W1.QUANTITY   ,
  W1.BIN_ID,B.bin_name
   FROM CNPS_DET  W1 (NOLOCK)       
   JOIN CNPS_MST W2 (NOLOCK) ON W1.PS_ID= W2.PS_ID      
   Join bin b on W1.bin_id= b.bin_id
   WHERE W2.PS_ID IN ('+@CWHERE1+')  
   ORDER BY W2.PS_NO '    
     
       
   PRINT @CQRY1      
   EXEC SP_EXECUTESQL @CQRY1        
     
   GOTO LAST  
        
  


LAST:    
END
