CREATE PROCEDURE SP_BUYERSORDER_WSL_6
@CMEMOID VARCHAR(40),  
@CWHERE VARCHAR(500),  
@CFINYEAR VARCHAR(10),  
@NNAVMODE NUMERIC(2,0),
@CARTICLECODE CHAR(9)='',  
@CPARA2CODE CHAR(7)='',
@DTWHERE DATETIME ='',
@cLocId VARCHAR(5)=''
--WITH ENCRYPTION
 
AS    
BEGIN 
	SELECT A.PARA3_CODE, A.PARA3_NAME FROM PARA3 A   
	WHERE A.PARA3_NAME <> '' AND INACTIVE = 0    
	ORDER BY A.PARA3_NAME 
END