CREATE PROCEDURE UPDATECAMPAIGNCITY
@CERRORMSG VARCHAR(MAX) OUTPUT
--WITH ENCRYPTION
AS
BEGIN
	
		
	DECLARE @CSTATE VARCHAR(100),@CCITY VARCHAR(100),@CCITYCODE VARCHAR(100),@CAREACODE VARCHAR(50),
	@CAREA VARCHAR(100),@CDATABASE VARCHAR(50),@CCMD NVARCHAR(MAX),@CTEMPTABLE VARCHAR(100),
	@NSTEP INT
	
	SELECT @CDATABASE='',@CERRORMSG=''
	
	BEGIN TRY
	
		SET @NSTEP=10
		DECLARE @NSPID INT
		
		SET @NSPID = @@SPID
		
		SET @NSTEP=20
		
		
		SET @CTEMPTABLE='TMP_CAMPAIGN_CITY_'+LTRIM(RTRIM(STR(@NSPID)))
		
		SET @CCMD=N'SELECT  @CSTATEOUT= ISNULL(STATE,'''') FROM '+@CTEMPTABLE
		EXEC SP_EXECUTESQL @CCMD,N'@CSTATEOUT VARCHAR(50) OUTPUT',@CSTATEOUT=@CSTATE OUTPUT
		
		SET @NSTEP=30
		
		SET @CCMD=N'SELECT  @CCITYOUT= ISNULL(CITY,'''') FROM '+@CTEMPTABLE
		EXEC SP_EXECUTESQL @CCMD,N'@CCITYOUT VARCHAR(50) OUTPUT',@CCITYOUT=@CCITY OUTPUT
		
		SET @NSTEP=40
		SET @CCMD=N'SELECT  @CCITYCODEOUT= ISNULL(CITY_CODE,''0000000'') FROM '+@CTEMPTABLE
		EXEC SP_EXECUTESQL @CCMD,N'@CCITYCODEOUT CHAR(7) OUTPUT',@CCITYCODEOUT=@CCITYCODE OUTPUT
		
		SET @NSTEP=50

		SET @CCMD=N'UPDATE '+@CTEMPTABLE+' SET COMPANY_CODE=''01'',DISTT_CODE=''0000000''' 
		EXEC SP_EXECUTESQL @CCMD
		
		IF ISNULL(@CSTATE,'') <>''
		BEGIN
			SET @NSTEP=60					  

			EXEC UPDATEMASTERXN   @CDATABASE , @CTEMPTABLE ,@CDATABASE ,'REGIONM' , 'REGION_CODE',
								  '','',0,'',0,'',0,'',1  
								  			
			EXEC UPDATEMASTERXN   @CDATABASE , @CTEMPTABLE ,@CDATABASE ,'STATE' , 'STATE_CODE',
								  '','',0,'',0,'',0,'',1  
		END
		
		IF ISNULL(@CCITY,'') <>''
		BEGIN
			SET @NSTEP=70					  
			EXEC UPDATEMASTERXN   @CDATABASE , @CTEMPTABLE ,@CDATABASE ,'CITY' ,  'CITY_CODE',
							  '','',0,'',0,'',0,'',1  
			
			SET @NSTEP=80
			
			SET @CCMD=N'UPDATE '+@CTEMPTABLE+' SET AREA_CODE= CITY_CODE,AREA_NAME= CITY'
			EXEC SP_EXECUTESQL @CCMD
			
			SET @NSTEP=90
			
			EXEC UPDATEMASTERXN   @CDATABASE , @CTEMPTABLE ,@CDATABASE ,'AREA' ,  'AREA_CODE',
							  '','',0,'',0,'',0,'',1 
		END
		ELSE
		BEGIN
			SET @NSTEP=95
			
			SET @CCMD=N'UPDATE '+@CTEMPTABLE+' SET AREA_CODE=''0000000'',AREA_NAME='''''
			EXEC SP_EXECUTESQL @CCMD
		END
		
	END TRY
	
	BEGIN CATCH 
	
		SET @CERRORMSG='PROCEDURE : UPDATECAMPAIGNCUSTDYM STEP  '+ISNULL(LTRIM(RTRIM(STR(@NSTEP))),'0')+ERROR_MESSAGE()
	
	END CATCH
	
END
