CREATE PROCEDURE SP3SPRINTFORMAT
(
	@NMODE INT=1,
	@CDEPTID VARCHAR(10)='',
	@CPRINTID VARCHAR(50)=''
)
AS
BEGIN
	BEGIN
	--SELECT * FROM PRINTLOCATION
	--SELECT * FROM PRINTMASTER
	  --DECLARE @CERRORMSG VARCHAR(MAX)
		IF @NMODE=1
			GOTO LBLSECTION1
		IF @NMODE=2
			GOTO LBLSECTION2
		IF @NMODE=3
			GOTO LBLSECTION3
	END

LBLSECTION1:
	BEGIN
		SELECT PRINTID,XNTYPE,(CASE WHEN XNTYPE='SLS' THEN 'RETAIL SALE' WHEN XNTYPE='WSL' THEN 'WHOLE SALE' END) MEMOTYPE,REPORTNAME,
			   PRINTERNAME ,PAPERSIZE,ORIENTATION  
		FROM PRINTMASTER WHERE ISDEFAULTFORMAT<>1
		
		GOTO END_PROC
	END

LBLSECTION2:
BEGIN
	SELECT P.* 
	FROM PRINTMASTER P 
	LEFT JOIN PRINTLOCATION PL ON P.PRINTID=PL.PRINTID
	WHERE DEPTID=@CDEPTID 
	GOTO END_PROC
END

LBLSECTION3:
	BEGIN
	
	IF EXISTS(SELECT TOP 1 'U' FROM PRINTMASTER WHERE PRINTID=@CPRINTID)
	BEGIN
	
		SELECT @CPRINTID AS PRINTID,L.DEPT_ID AS DEPTID,L.DEPT_NAME,(CASE WHEN PL.DEPTID IS NULL THEN 0 ELSE 1 END) AS CHK
		FROM LOCATION L
		LEFT JOIN PRINTLOCATION PL ON PL.DEPTID=L.DEPT_ID AND PL.PRINTID=@CPRINTID
	
	END
	
	
	
	IF NOT EXISTS (SELECT TOP 1 'U'  FROM PRINTMASTER WHERE PRINTID=@CPRINTID)
	BEGIN
		PRINT 'INVALID PRINTID...'
	END
	
		--LEFT JOIN PRINTMASTER PM ON PM.PRINTID=PL.PRINTID
		--WHERE PM.PRINTID=@CPRINTID
		
		--UNION ALL 
		--SELECT (CASE WHEN DEPTID=DEPT_ID THEN 1 ELSE 0 END) 'CHK',L.DEPT_ID,L.DEPT_NAME 
		--FROM LOCATION L 
		--LEFT JOIN PRINTLOCATION PL ON L.DEPT_ID=PL.DEPTID
		--LEFT JOIN PRINTMASTER PM ON PM.PRINTID=PL.PRINTID
		--WHERE PM.PRINTID=@CPRINTID
		 
		GOTO END_PROC
    END
    


END_PROC:  
END
--END OF PROCEDURE - SP3SPRINTFORMAT
