CREATE PROCEDURE SPACT_LOC_FILTER
(
	@nMode	INT=1,
	@SPID	VARCHAR(50),
	@USERCODE	VARCHAR(10),
	@cDeptID	VARCHAR(5)
)
AS
BEGIN
	DECLARE @DTUSERLOC TABLE(DEPT_ID VARCHAR(10))
	DECLARE @DTLOC TABLE(DEPT_ID VARCHAR(10),DEPT_NAME VARCHAR(MAX),AREA_CODE VARCHAR(20),ADDRESS VARCHAR(MAX),LOC_GST_NO VARCHAR(20),LOC_TYPE INT)
	DECLARE @bAllLocation BIT=1
	DECLARE @bHO BIT=0

	IF EXISTS(SELECT VALUE FROM CONFIG WHERE config_option='HO_LOCATION_ID' AND value=@cDeptID)
		SET @bHO=1

	INSERT INTO @DTUSERLOC (DEPT_ID)
	SELECT DEPT_ID FROM LOCUSERS (NOLOCK)
	WHERE user_code=@USERCODE

	INSERT INTO @DTLOC(DEPT_ID ,DEPT_NAME ,AREA_CODE ,ADDRESS,LOC_GST_NO,LOC_TYPE)
	SELECT DEPT_ID,DEPT_NAME,AREA_CODE,ISNULL(ADDRESS1,'')+ISNULL(ADDRESS1,'') AS ADDRESS,SUBSTRING(LOC_GST_NO,3,10) AS LOC_GST_NO,loc_type
	FROM LOCATION  (NOLOCK)
	WHERE  (((DEPT_ID=MAJOR_DEPT_ID AND loc_type=1) OR (Account_posting_at_ho=1)) )
	AND  @nMode<>99
	AND ISNULL(LOC_GST_NO,'')<>'' 
	UNION 
	SELECT DEPT_ID,DEPT_NAME,AREA_CODE,ISNULL(ADDRESS1,'')+ISNULL(ADDRESS1,'') AS ADDRESS,PAN_NO AS LOC_GST_NO,loc_type
	FROM LOCATION  (NOLOCK)
	WHERE  (((DEPT_ID=MAJOR_DEPT_ID AND loc_type=1) OR (Account_posting_at_ho=1)) ) AND @nMode<>99
	AND ISNULL(PAN_NO,'')<>'' AND ISNULL(LOC_GST_NO,'')='' 
	UNION
	SELECT DEPT_ID,DEPT_NAME,AREA_CODE,ISNULL(ADDRESS1,'')+ISNULL(ADDRESS1,'') AS ADDRESS, LOC_GST_NO,loc_type
	FROM LOCATION  (NOLOCK)
	WHERE  (((DEPT_ID=MAJOR_DEPT_ID AND loc_type=1) OR (Account_posting_at_ho=1)) )
	AND  @nMode=99
	AND ISNULL(LOC_GST_NO,'')<>'' 

	
	--select * from @DTUSERLOC
	--select * from @DTLOC

	SELECT @bAllLocation=0
	FROM @DTLOC a
	LEFT OUTER JOIN @DTUSERLOC b ON b.DEPT_ID=A.DEPT_ID
	where b.DEPT_ID is null

	IF @nMode=1
	BEGIN
		;WITH ACT
		AS
		(
			SELECT * FROM act_filter_loc WHERE sp_id=@SPID
		)
		,ALL_LOC
		AS
		(
			SELECT A.DEPT_ID,DEPT_NAME,AREA_CODE,A.ADDRESS,A.LOC_GST_NO
			,(CASE WHEN A.loc_type=2 THEN 'Franchisee' ELSE 'Company Owned' END ) AS [Loc_Type]
			FROM @DTLOC  A 
			--JOIN @DTUSERLOC B ON A.DEPT_ID= B.DEPT_ID
			WHERE (@bHO=1 OR a.DEPT_ID=@cDeptID)
			--UNION
			--SELECT '' AS DEPT_ID, 'ALL LOCATIONS' AS DEPT_NAME,'' AREA_CODE,'' AS ADDRESS,'ALL LOCATIONS' AS LOC_GST_NO,'' AS LOC_TYPE
			--WHERE (@bAllLocation=1 OR '0000000'=@USERCODE) AND @bHO=1
		)
		,GROUP_COMPANY
		AS
		(
			SELECT ROW_NUMBER() OVER (PARTITION BY PAN_NO ORDER BY PAN_NO) AS SRNO,X.PAN_NO, LOC_GST_NO, DEPT_NAME
			FROM 
			(
				SELECT LOC_GST_NO AS PAN_NO, LOC_GST_NO, DEPT_NAME
				FROM @DTLOC 
				WHERE ISNULL(LOC_GST_NO,'')<>''
				--UNION
				--SELECT 'L LOCATION' AS PAN_NO,'' AS LOC_GST_NO, 'ALL LOCATIONS' AS DEPT_NAME
				--WHERE (@bAllLocation=1 OR '0000000'=@USERCODE) AND @bHO=1
			)X
		)
		SELECT CAST((CASE WHEN ACT.dept_id IS NULL THEN 0 ELSE 1 END)AS BIT) AS CHK, upper(A.DEPT_ID)AS DEPT_ID,upper(A.DEPT_NAME) AS DEPT_NAME
		,UPPER(b.area_name)as [Area], UPPER(c.city)as City, upper(d.state) as [State], upper(e.region_name)as [Region]
		,A.ADDRESS AS [Address],ISNULL(GP.dept_name,'') AS GROUP_NAME,A.Loc_Type AS [Loc Type],A.LOC_GST_NO

		--SELECT CAST((CASE WHEN F.dept_id IS NULL THEN 0 ELSE 1 END) AS BIT) AS CHK, upper(A.DEPT_ID)AS DEPT_ID,
		--upper(A.DEPT_NAME) AS DEPT_NAME,UPPER(b.area_name)as [Area], UPPER(c.city)as City, 
		--upper(d.state)as [State], upper(e.region_name)as [Region] ,A.ADDRESS AS [Address],
		--ISNULL(GP.dept_name,'') AS [Group_Name],A.Loc_Type AS [Loc Type],A.LOC_GST_NO


		FROM ALL_LOC A
		LEFT OUTER JOIN AREA B (NOLOCK) ON A.AREA_CODE=B.AREA_CODE 
		LEFT OUTER JOIN CITY C  (NOLOCK) ON B.CITY_CODE=C.CITY_CODE 
		LEFT OUTER JOIN STATE D (NOLOCK) ON C.STATE_CODE=D.STATE_CODE 
		LEFT OUTER JOIN REGIONM E (NOLOCK) ON D.REGION_CODE=E.REGION_CODE 
		LEFT OUTER JOIN ACT ON ACT.dept_id=A.dept_id 
		LEFT OUTER JOIN 
		(
			SELECT * FROM GROUP_COMPANY WHERE SRNO=1
		)GP ON GP.PAN_NO=A.LOC_GST_NO
	END
	ELSE IF @nMode=2
	BEGIN
		
		;WITH ALL_LOC
		AS
		(
			
			SELECT A.DEPT_ID,DEPT_NAME,AREA_CODE,A.ADDRESS,A.LOC_GST_NO
			,(CASE WHEN A.loc_type=2 THEN 'Franchisee' ELSE 'Company Owned' END ) AS [Loc_Type]
			FROM @DTLOC  A 
			--JOIN @DTUSERLOC B ON A.DEPT_ID= B.DEPT_ID
			UNION
			SELECT '' AS DEPT_ID, 'ALL LOCATIONS' AS DEPT_NAME,'' AREA_CODE,'' AS ADDRESS,'ALL LOCATIONS' AS LOC_GST_NO,'' AS LOC_TYPE
			WHERE (@bAllLocation=1 OR '0000000'=@USERCODE) AND @bHO=1
		)
		,GROUP_COMPANY
		AS
		(
			SELECT ROW_NUMBER() OVER (PARTITION BY PAN_NO ORDER BY PAN_NO) AS SRNO,X.PAN_NO, LOC_GST_NO, DEPT_NAME
			FROM 
			(
				SELECT LOC_GST_NO AS PAN_NO, LOC_GST_NO, DEPT_NAME
				FROM @DTLOC 
				WHERE ISNULL(LOC_GST_NO,'')<>''
				UNION
				SELECT 'L LOCATION' AS PAN_NO,'' AS LOC_GST_NO, 'ALL LOCATIONS' AS DEPT_NAME
				WHERE (@bAllLocation=1 OR '0000000'=@USERCODE) AND @bHO=1
			)X
		)
		--SELECT CAST(1 AS BIT) AS CHK, upper(A.DEPT_ID)AS DEPT_ID,upper(A.DEPT_NAME) AS DEPT_NAME
		--,UPPER(b.area_name)as area_name, UPPER(c.city)as city, upper(d.state)as state, upper(e.region_name)as region_name 
		--,A.ADDRESS,ISNULL(GP.dept_name,'') AS GROUP_NAME
		SELECT CAST(1 AS BIT) AS CHK, upper(A.DEPT_ID)AS DEPT_ID,upper(A.DEPT_NAME) AS DEPT_NAME
		,UPPER(b.area_name)as [Area], UPPER(c.city)as City, upper(d.state) as [State], upper(e.region_name)as [Region]
		,A.ADDRESS AS [Address],ISNULL(GP.dept_name,'') AS GROUP_NAME,A.Loc_Type AS [Loc Type],A.LOC_GST_NO
		FROM ALL_LOC A
		JOIN act_filter_loc ACT (NOLOCK) ON ACT.dept_id=A.dept_id AND ACT.sp_id=@SPID
		LEFT OUTER JOIN AREA B (NOLOCK) ON A.AREA_CODE=B.AREA_CODE 
		LEFT OUTER JOIN CITY C  (NOLOCK) ON B.CITY_CODE=C.CITY_CODE 
		LEFT OUTER JOIN STATE D (NOLOCK) ON C.STATE_CODE=D.STATE_CODE 
		LEFT OUTER JOIN REGIONM E (NOLOCK) ON D.REGION_CODE=E.REGION_CODE
		LEFT OUTER JOIN 
		(
			SELECT * FROM GROUP_COMPANY WHERE SRNO=1
		)GP ON GP.PAN_NO=A.LOC_GST_NO
		WHERE ACT.sp_id=@SPID
		
	END
	ELSE IF @nMode=99
	BEGIN
		;WITH ALL_LOC
		AS
		(
			SELECT A.DEPT_ID,DEPT_NAME,AREA_CODE,ISNULL(ADDRESS1,'')+ISNULL(ADDRESS1,'') AS ADDRESS,A.LOC_GST_NO AS LOC_GST_NO
			,(CASE WHEN A.loc_type=2 THEN 'Franchisee' ELSE 'Company Owned' END ) AS [Loc_Type]
			FROM LOCATION  A (NOLOCK)
			WHERE --(@bHO=1 OR a.DEPT_ID=@cDeptID) AND 
			DEPT_ID=MAJOR_DEPT_ID AND ISNULL(LOC_GST_NO,'')<>''
			--UNION 
			--SELECT DEPT_ID,DEPT_NAME,AREA_CODE,ISNULL(ADDRESS1,'')+ISNULL(ADDRESS1,'') AS ADDRESS,PAN_NO AS LOC_GST_NO
			--,(CASE WHEN loc_type=2 THEN 'Franchisee' ELSE 'Company Owned' END ) AS [Loc_Type]
			--FROM LOCATION  (NOLOCK)
			--WHERE  DEPT_ID=MAJOR_DEPT_ID AND ISNULL(PAN_NO,'')<>'' AND ISNULL(LOC_GST_NO,'')=''
			--UNION
			--SELECT '' AS DEPT_ID, 'ALL LOCATIONS' AS DEPT_NAME,'' AREA_CODE,'' AS ADDRESS,'ALL COMPANY' AS LOC_GST_NO ,''
			--WHERE (@bAllLocation=1 OR '0000000'=@USERCODE) AND @bHO=1
		)
		,GROUP_COMPANY
		AS
		(
			SELECT ROW_NUMBER() OVER (PARTITION BY PAN_NO ORDER BY PAN_NO) AS SRNO,X.PAN_NO, LOC_GST_NO, DEPT_NAME
			FROM 
			(
				SELECT SUBSTRING(LOC_GST_NO,3,10) AS PAN_NO, LOC_GST_NO, DEPT_NAME
				FROM @DTLOC 
				WHERE ISNULL(LOC_GST_NO,'')<>''
				AND DEPT_ID=(CASE WHEN @bHO=1 THEN @cDeptID ELSE DEPT_ID END)
				--UNION
				--SELECT 'ALL COMPANY' AS PAN_NO,'ALL COMPANY' AS LOC_GST_NO, 'ALL LOCATIONS' AS DEPT_NAME
				--WHERE (@bAllLocation=1 OR '0000000'=@USERCODE) AND @bHO=1
			)X
		)
		--SELECT * FROM GROUP_COMPANY,ALL_LOC
		SELECT CAST( 1 AS BIT) AS CHK, upper(A.DEPT_ID)AS DEPT_ID,
		upper(A.DEPT_NAME) AS DEPT_NAME,UPPER(b.area_name)as [Area], UPPER(c.city)as City, 
		upper(d.state)as [State], upper(e.region_name)as [Region] ,A.ADDRESS AS [Address],
		ISNULL(GP.dept_name,'') AS [Group_Name],A.Loc_Type AS [Loc Type],A.LOC_GST_NO
		FROM ALL_LOC A
		LEFT OUTER JOIN AREA B (NOLOCK) ON A.AREA_CODE=B.AREA_CODE 
		LEFT OUTER JOIN CITY C  (NOLOCK) ON B.CITY_CODE=C.CITY_CODE 
		LEFT OUTER JOIN STATE D (NOLOCK) ON C.STATE_CODE=D.STATE_CODE 
		LEFT OUTER JOIN REGIONM E (NOLOCK) ON D.REGION_CODE=E.REGION_CODE
		--LEFT OUTER JOIN act_filter_loc F (NOLOCK) ON F.dept_id=A.dept_id AND F.sp_id=@SPID
		LEFT OUTER JOIN 
		(
			SELECT * FROM GROUP_COMPANY WHERE SRNO=1
		)GP ON GP.PAN_NO=SUBSTRING(A.LOC_GST_NO,3,10)
	END
END
/*
CREATE PROCEDURE SPACT_LOC_FILTER
(
	@nMode	INT=1,
	@SPID	NUMERIC(5),
	@USERCODE	VARCHAR(10),
	@cDeptID	VARCHAR(5)
)
AS
BEGIN
	DECLARE @DTUSERLOC TABLE(DEPT_ID VARCHAR(10))
	DECLARE @DTLOC TABLE(DEPT_ID VARCHAR(10),DEPT_NAME VARCHAR(MAX),AREA_CODE VARCHAR(20),ADDRESS VARCHAR(MAX),LOC_GST_NO VARCHAR(20))
	DECLARE @bAllLocation BIT=1
	DECLARE @bHO BIT=0

	IF EXISTS(SELECT VALUE FROM CONFIG WHERE config_option='HO_LOCATION_ID' AND value=@cDeptID)
		SET @bHO=1

	INSERT INTO @DTUSERLOC (DEPT_ID)
	SELECT DEPT_ID FROM LOCUSERS (NOLOCK)
	WHERE user_code=@USERCODE

	INSERT INTO @DTLOC(DEPT_ID ,DEPT_NAME ,AREA_CODE ,ADDRESS,LOC_GST_NO)
	SELECT DEPT_ID,DEPT_NAME,AREA_CODE,ISNULL(ADDRESS1,'')+ISNULL(ADDRESS1,'') AS ADDRESS,LOC_GST_NO
	FROM LOCATION  (NOLOCK)
	WHERE  ((DEPT_ID=MAJOR_DEPT_ID AND loc_type=1) OR (Account_posting_at_ho=1))  OR(DEPT_ID=MAJOR_DEPT_ID AND @nMode=99)

	--select * from @DTUSERLOC
	--select * from @DTLOC

	SELECT @bAllLocation=0
	FROM @DTLOC a
	LEFT OUTER JOIN @DTUSERLOC b ON b.DEPT_ID=A.DEPT_ID
	where b.DEPT_ID is null

	IF @nMode=1
	BEGIN
		;WITH ACT
		AS
		(
			SELECT * FROM act_filter_loc WHERE sp_id=@SPID
		)
		,ALL_LOC
		AS
		(
			
			SELECT A.DEPT_ID,DEPT_NAME,AREA_CODE,A.ADDRESS,A.LOC_GST_NO
			FROM @DTLOC  A 
			--JOIN @DTUSERLOC B ON A.DEPT_ID= B.DEPT_ID
			WHERE (@bHO=1 OR a.DEPT_ID=@cDeptID)
			UNION
			SELECT '' AS DEPT_ID, 'ALL LOCATIONS' AS DEPT_NAME,'' AREA_CODE,'' AS ADDRESS,'ALL LOCATIONS' AS LOC_GST_NO
			WHERE (@bAllLocation=1 OR '0000000'=@USERCODE) AND @bHO=1
		)
		,GROUP_COMPANY
		AS
		(
			SELECT ROW_NUMBER() OVER (PARTITION BY PAN_NO ORDER BY PAN_NO) AS SRNO,X.PAN_NO, LOC_GST_NO, DEPT_NAME
			FROM 
			(
				SELECT SUBSTRING(LOC_GST_NO,3,10) AS PAN_NO, LOC_GST_NO, DEPT_NAME
				FROM @DTLOC 
				WHERE ISNULL(LOC_GST_NO,'')<>''
				UNION
				SELECT 'L LOCATION' AS PAN_NO,'' AS LOC_GST_NO, 'ALL LOCATIONS' AS DEPT_NAME
				WHERE (@bAllLocation=1 OR '0000000'=@USERCODE) AND @bHO=1
			)X
		)
		SELECT CAST((CASE WHEN ACT.dept_id IS NULL THEN 0 ELSE 1 END)AS BIT) AS CHK, upper(A.DEPT_ID)AS DEPT_ID,upper(A.DEPT_NAME) AS DEPT_NAME
		,UPPER(b.area_name)as [Area], UPPER(c.city)as City, upper(d.state) as [State], upper(e.region_name)as [Region]
		,A.ADDRESS AS [Address],ISNULL(GP.dept_name,'') AS GROUP_NAME
		FROM ALL_LOC A
		LEFT OUTER JOIN AREA B (NOLOCK) ON A.AREA_CODE=B.AREA_CODE 
		LEFT OUTER JOIN CITY C  (NOLOCK) ON B.CITY_CODE=C.CITY_CODE 
		LEFT OUTER JOIN STATE D (NOLOCK) ON C.STATE_CODE=D.STATE_CODE 
		LEFT OUTER JOIN REGIONM E (NOLOCK) ON D.REGION_CODE=E.REGION_CODE 
		LEFT OUTER JOIN ACT ON ACT.dept_id=A.dept_id
		LEFT OUTER JOIN 
		(
			SELECT * FROM GROUP_COMPANY WHERE SRNO=1
		)GP ON GP.PAN_NO=SUBSTRING(A.LOC_GST_NO,3,10) 
	END
	ELSE IF @nMode=2
	BEGIN
		
		;WITH ALL_LOC
		AS
		(
			
			SELECT A.DEPT_ID,DEPT_NAME,AREA_CODE,A.ADDRESS,A.LOC_GST_NO
			FROM @DTLOC  A 
			--JOIN @DTUSERLOC B ON A.DEPT_ID= B.DEPT_ID
			UNION
			SELECT '' AS DEPT_ID, 'ALL LOCATIONS' AS DEPT_NAME,'' AREA_CODE,'' AS ADDRESS,'ALL LOCATIONS' AS LOC_GST_NO
			WHERE (@bAllLocation=1 OR '0000000'=@USERCODE) AND @bHO=1
		)
		,GROUP_COMPANY
		AS
		(
			SELECT ROW_NUMBER() OVER (PARTITION BY PAN_NO ORDER BY PAN_NO) AS SRNO,X.PAN_NO, LOC_GST_NO, DEPT_NAME
			FROM 
			(
				SELECT SUBSTRING(LOC_GST_NO,3,10) AS PAN_NO, LOC_GST_NO, DEPT_NAME
				FROM @DTLOC 
				WHERE ISNULL(LOC_GST_NO,'')<>''
				UNION
				SELECT 'L LOCATION' AS PAN_NO,'' AS LOC_GST_NO, 'ALL LOCATIONS' AS DEPT_NAME
				WHERE (@bAllLocation=1 OR '0000000'=@USERCODE) AND @bHO=1
			)X
		)
		--SELECT CAST(1 AS BIT) AS CHK, upper(A.DEPT_ID)AS DEPT_ID,upper(A.DEPT_NAME) AS DEPT_NAME
		--,UPPER(b.area_name)as area_name, UPPER(c.city)as city, upper(d.state)as state, upper(e.region_name)as region_name 
		--,A.ADDRESS,ISNULL(GP.dept_name,'') AS GROUP_NAME
		SELECT CAST(1 AS BIT) AS CHK, upper(A.DEPT_ID)AS DEPT_ID,upper(A.DEPT_NAME) AS DEPT_NAME
		,UPPER(b.area_name)as [Area], UPPER(c.city)as City, upper(d.state) as [State], upper(e.region_name)as [Region]
		,A.ADDRESS AS [Address],ISNULL(GP.dept_name,'') AS GROUP_NAME
		FROM ALL_LOC A
		JOIN act_filter_loc ACT (NOLOCK) ON ACT.dept_id=A.dept_id
		LEFT OUTER JOIN AREA B (NOLOCK) ON A.AREA_CODE=B.AREA_CODE 
		LEFT OUTER JOIN CITY C  (NOLOCK) ON B.CITY_CODE=C.CITY_CODE 
		LEFT OUTER JOIN STATE D (NOLOCK) ON C.STATE_CODE=D.STATE_CODE 
		LEFT OUTER JOIN REGIONM E (NOLOCK) ON D.REGION_CODE=E.REGION_CODE
		LEFT OUTER JOIN 
		(
			SELECT * FROM GROUP_COMPANY WHERE SRNO=1
		)GP ON GP.PAN_NO=SUBSTRING(A.LOC_GST_NO,3,10) 
		WHERE ACT.sp_id=@SPID
		
	END
	ELSE IF @nMode=99
	BEGIN
		;WITH ALL_LOC
		AS
		(
			SELECT A.DEPT_ID,DEPT_NAME,AREA_CODE,ISNULL(ADDRESS1,'')+ISNULL(ADDRESS1,'') AS ADDRESS,A.LOC_GST_NO
			,(CASE WHEN A.loc_type=2 THEN 'Franchisee' ELSE 'Company Owned' END ) AS [Loc_Type]
			FROM LOCATION  A 
			WHERE --(@bHO=1 OR a.DEPT_ID=@cDeptID) AND 
			DEPT_ID=MAJOR_DEPT_ID AND ISNULL(LOC_GST_NO,'')<>''
			--UNION
			--SELECT '' AS DEPT_ID, 'ALL LOCATIONS' AS DEPT_NAME,'' AREA_CODE,'' AS ADDRESS,'ALL COMPANY' AS LOC_GST_NO ,''
			--WHERE (@bAllLocation=1 OR '0000000'=@USERCODE) AND @bHO=1
		)
		,GROUP_COMPANY
		AS
		(
			SELECT ROW_NUMBER() OVER (PARTITION BY PAN_NO ORDER BY PAN_NO) AS SRNO,X.PAN_NO, LOC_GST_NO, DEPT_NAME
			FROM 
			(
				SELECT SUBSTRING(LOC_GST_NO,3,10) AS PAN_NO, LOC_GST_NO, DEPT_NAME
				FROM @DTLOC 
				WHERE ISNULL(LOC_GST_NO,'')<>''
				--UNION
				--SELECT 'ALL COMPANY' AS PAN_NO,'ALL COMPANY' AS LOC_GST_NO, 'ALL LOCATIONS' AS DEPT_NAME
				--WHERE (@bAllLocation=1 OR '0000000'=@USERCODE) AND @bHO=1
			)X
		)
		SELECT CAST(1 AS BIT) AS CHK, upper(A.DEPT_ID)AS DEPT_ID,upper(A.DEPT_NAME) AS DEPT_NAME
		,UPPER(b.area_name)as [Area], UPPER(c.city)as City, upper(d.state)as [State], upper(e.region_name)as [Region] 
		,A.ADDRESS AS [Address],ISNULL(GP.dept_name,'') AS [Group_Name],A.Loc_Type AS [Loc Type],A.LOC_GST_NO
		FROM ALL_LOC A
		LEFT OUTER JOIN AREA B (NOLOCK) ON A.AREA_CODE=B.AREA_CODE 
		LEFT OUTER JOIN CITY C  (NOLOCK) ON B.CITY_CODE=C.CITY_CODE 
		LEFT OUTER JOIN STATE D (NOLOCK) ON C.STATE_CODE=D.STATE_CODE 
		LEFT OUTER JOIN REGIONM E (NOLOCK) ON D.REGION_CODE=E.REGION_CODE 
		LEFT OUTER JOIN 
		(
			SELECT * FROM GROUP_COMPANY WHERE SRNO=1
		)GP ON GP.PAN_NO=SUBSTRING(A.LOC_GST_NO,3,10) 
	END
END
*/