CREATE PROCEDURE SP3S_GETSTOCK_ONLINEBARCODE
(
@CPRODUCT_CODE VARCHAR(100)
)
AS
BEGIN
   DECLARE @DBNAME VARCHAR(50),@CCMD NVARCHAR(MAX)
   SELECT @DBNAME=DB_NAME()+'_RFOPT'+'.DBO.RF_OPT'

   SET @CCMD=N'SELECT PRODUCT_CODE,[DEPT_NAME],SUM(ISNULL(CBS , 0)) AS CBS
		FROM 
		(
				SELECT A.PRODUCT_CODE AS PRODUCT_CODE,LOCATION.[DEPT_NAME]
					  ,CAST(SUM( (CASE WHEN A.XN_TYPE=''OPS'' OR (A.XN_TYPE IN (''API'',''SCF'',''OPS'',''PRD'', ''PUR'', 
					  ''CHI'', ''SLR'',''UNC'',''APR'', ''WSR'', ''PFI'', ''PFG'', ''BCG'',''MRP'',''DCI'',''PSB'',''JWR'') 
					   AND ARTICLE.STOCK_NA=0 ) THEN 1 WHEN A.XN_TYPE IN 
					  (''APO'',''SCC'',''BOC'',''PRT'',''CHO'',''SLS'',''CNC'',''APP'',''WSL'',''CIP'', ''CRM'', ''DCO'',''MIP'',
					  ''CSB'',''JWI'',''DLM'')  AND ARTICLE.STOCK_NA=0 THEN -1 ELSE 0 END) 
					  * (XN_QTY)) AS NUMERIC(14,2)) AS CBS
				FROM '+ @DBNAME +'  A  (NOLOCK) 
				JOIN SKU (NOLOCK) ON A.PRODUCT_CODE = SKU.PRODUCT_CODE 
				JOIN ARTICLE (NOLOCK) ON SKU.ARTICLE_CODE = ARTICLE.ARTICLE_CODE 
				 JOIN LOCATION  (NOLOCK) ON A.DEPT_ID = LOCATION.DEPT_ID
				WHERE ( LOCATION.INACTIVE IN (0)) AND  SKU.ER_FLAG IN (''0'' , ''1'' )
				AND SKU.ONLINE_PRODUCT_CODE='''+ @CPRODUCT_CODE +'''
				GROUP BY A.PRODUCT_CODE,LOCATION.[DEPT_NAME]


		 ) B 
		 GROUP BY PRODUCT_CODE,[DEPT_NAME]
		 HAVING NOT (SUM(ISNULL(CBS,0))= 0 )
		 ORDER BY [DEPT_NAME],PRODUCT_CODE'
		 
PRINT @CCMD
EXEC SP_EXECUTESQL @CCMD		 
  
END
-- **********************  END OF PROCEDURE SP3S_GETSTOCK_ONLINEBARCODE
