create PROC VALIDATEXN_XNSPOM_BEFORE_EDIT 
@CMEMOID VARCHAR(30),
@BCANCELXN BIT,
@CERRORMSG VARCHAR(200) OUTPUT,
@CEXPRERRORMSG VARCHAR(200) OUTPUT
--WITH ENCRYPTION
AS
BEGIN
	
	
	
	
	DECLARE @CTEXT VARCHAR(10)
	
	SET @CTEXT=(CASE WHEN @BCANCELXN=1 THEN 'CANCEL' ELSE 'EDIT' END)


	IF EXISTS (SELECT TOP 1 'U' FROM POD01106 a (nolock) 
	           join PurchaseOrderProcessingNew b (nolock)  on a.row_id =b.RefRowId 
	          WHERE  PO_ID=@CMEMOID and b.XnType <>'PurchaseOrder' and Qty<>0 ) AND @BCANCELXN=1
	   BEGIN
		     SET @CERRORMSG='PI HAS BEEN GENERATED YOU CAN NOT CANCELLED IT '
		     RETURN
       END

	   IF EXISTS (SELECT TOP 1 'U' FROM POm01106 WHERE  PO_ID=@CMEMOID and isnull(ApprovedLevelNo,0)=99 ) 
	   BEGIN
		    SET @CERRORMSG='PO HAS BEEN APPROVED BY USER.....CAN NOT '+@CTEXT
	        RETURN
       END

end
		