CREATE PROCEDURE SP_PPC_TODAY_DELIVERY_PO
(
 @DTODAY DATETIME=''
)   
AS
BEGIN 
     
     
     SELECT A.PO_NO,
     REPLACE (CONVERT(VARCHAR, A.PO_DT, 106),' ','/')  AS PO_DT,
     REPLACE (CONVERT(VARCHAR, B.DELIVERY_DT, 106),' ','/')  AS DELIVERY_DT,
     LM.AC_NAME ,ART.ARTICLE_NO  ,P1.PARA1_NAME ,B.QUANTITY ,
     ISNULL(ORDER_NO,'') AS BO_NO
     FROM PPC_POM01106 A (NOLOCK)
     JOIN PPC_POD01106 B (NOLOCK) ON A.PO_ID =B.PO_ID 
     JOIN ARTICLE ART (NOLOCK) ON ART.ARTICLE_CODE =B.ARTICLE_CODE 
     JOIN PARA1 P1 (NOLOCK) ON P1.PARA1_CODE =B.PARA1_CODE
     JOIN LM01106 LM (NOLOCK) ON LM.AC_CODE=A.AC_CODE 
     LEFT OUTER JOIN
     (
      SELECT A.PO_ROW_ID ,SUM(A.QUANTITY) AS PUR_QTY 
      FROM PPC_PID01106 A (NOLOCK)
      JOIN PPC_PIM01106 B (NOLOCK) ON A.MRR_ID =B.MRR_ID 
      WHERE  B.CANCELLED=0
      GROUP BY A.PO_ROW_ID
     ) PID ON PID .PO_ROW_ID= B.ROW_ID
     LEFT OUTER JOIN
     ( 
     
     SELECT C.BILL_NO AS ORDER_NO,A.ROW_ID  
     FROM PPC_BO_ART_BOM A
     JOIN PPC_BUYER_ORDER_DET B ON B.ROW_ID =A.REF_ROW_ID 
     JOIN PPC_BUYER_ORDER_MST C ON B.ORDER_ID =C.ORDER_ID 
     WHERE C.CANCELLED =0
     GROUP BY C.BILL_NO,A.ROW_ID
     ) BO ON BO.ROW_ID =B.BO_BOM_ROW_ID 
     WHERE A.CANCELLED =0
     AND B.QUANTITY >ISNULL(PUR_QTY,0)
     ORDER BY B.DELIVERY_DT
     --AND B.DELIVERY_DT =@DTODAY
     
END
