create PROCEDURE SP3S_SYNCH_UPLOADDATA_GVXFR_OPT
(
    @nSpId VARCHAR(50)
   ,@CERRMSG VARCHAR(1000) OUTPUT
)
--WITH ENCRYPTION
AS
SET NOCOUNT ON
BEGIN
	

DECLARE @CSTEP VARCHAR(100),@CMEMO_ID VARCHAR(100),@CFILTERCONDITION VARCHAR(1000),
        @CTABLENAME VARCHAR(100),@CTMP_TABLENAME VARCHAR(100),
		@CKEYFIELD VARCHAR(50),@CSOURCEDB VARCHAR(10),@CMERGEDB VARCHAR(10),@CTABLE_SUFFIX varchar(10),
		@CCMD nvarchar(max),@BCHALLANRECEIVEDPREV BIT,@CCMDOUTPUT VARCHAR(MAX),@HODEPT_ID VARCHAR(4)
	


BEGIN TRY
	BEGIN TRANSACTION	

	SELECT @CMEMO_ID=MEMO_ID FROM GVXFR_GV_STKXFER_MST_UPLOAD WHERE SP_ID=@nSpId
	SELECT @HODEPT_ID=value FROM CONFIG WHERE CONFIG_OPTION ='HO_LOCATION_ID'
	IF ISNULL(@CMEMO_ID,'')=''
	   GOTO EXIT_PROC

    SET @CTABLE_SUFFIX='upload'
	
	select @CSOURCEDB ='',@cMergedb=''                                           
										    
   
    SET @CSTEP = 50       
   
	UPDATE GVXFR_GV_STKXFER_MST_UPLOAD SET  USER_CODE='0000000' where sp_id=@nSpId

    SET @CTABLENAME='GV_STKXFER_MST'        
    SET @CTMP_TABLENAME='GVXFR_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))
    			

	SET @CSTEP = 60       
    SET @CCMD=N'UPDATE B SET RECEIPT_DT=A.RECEIPT_DT FROM '+@CTMP_TABLENAME+' A  WITH (ROWLOCK) 
				JOIN GV_STKXFER_MST B (NOLOCK) ON A.MEMO_ID=B.MEMO_ID
				where a.sp_id ='''+@nSpId+''' AND B.target_dept_id<>'''+ @HODEPT_ID+''''
	EXEC SP_EXECUTESQL @CCMD


	 
   IF EXISTS (SELECT MEMO_ID FROM GVXFR_GV_STKXFER_MST_UPLOAD (NOLOCK) WHERE sp_id=@nSpId AND TARGET_DEPT_ID=@HODEPT_ID)
    BEGIN

	  SET @CCMD=N'UPDATE A SET RECEIPT_DT=B.RECEIPT_DT FROM '+@CTMP_TABLENAME+' A  WITH (ROWLOCK) 
				JOIN GV_STKXFER_MST B (NOLOCK) ON A.MEMO_ID=B.MEMO_ID
				where a.sp_id ='''+@nSpId+''' AND B.target_dept_id='''+ @HODEPT_ID+''' '
	  EXEC SP_EXECUTESQL @CCMD

	

	SET @CKEYFIELD='MEMO_ID'        
    SET @CSTEP= 70   
    EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
         ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''        
         ,@LINSERTONLY=0,@LUPDATEONLY=0,@BALWAYSUPDATE=1 


   
			DELETE FROM GV_STKXFER_DET WITH (ROWLOCK) WHERE MEMO_ID = @CMEMO_ID
  
			SET @CSTEP = 80      
			SET @CTABLENAME='GV_STKXFER_DET'        
			SET @CTMP_TABLENAME='GVXFR_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))
			SET @CKEYFIELD='MEMO_ID'        
			SET @CSTEP= 90
			EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB        
			,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''        
			,@LINSERTONLY=1,@LUPDATEONLY=0,@BALWAYSUPDATE=0 

	END
	
   
   

END TRY
BEGIN CATCH
	SET @CERRMSG='P:SP3S_SYNCH_UPLOADDATA_GVXFR_OPT for MemoId: STEP:'+@CSTEP+', MESSAGE:'+ERROR_MESSAGE()
	GOTO EXIT_PROC
END CATCH

EXIT_PROC:


	IF @@TRANCOUNT>0
	BEGIN
		IF ISNULL(@CERRMSG,'')=''
			COMMIT
		ELSE
			ROLLBACK
    END
	
	DELETE FROM GVXFR_GV_STKXFER_MST_UPLOAD WHERE memo_id=@CMEMO_ID
	DELETE FROM GVXFR_GV_STKXFER_DET_UPLOAD WHERE memo_id=@CMEMO_ID		
	
END	
