CREATE PROCEDURE SP_CUSTOMDVAT30_SUMMARY
	@DFROMDT DATETIME,
	@DTODT DATETIME,
	@CCURRENTSTATE VARCHAR(10) = '',
	@NMODE INT=1
--WITH ENCRYPTION	
AS
BEGIN
	---POST_TAX_SEPARATELY - 0 : INTERSTATE PURCHASE
	---POST_TAX_SEPARATELY - 1 : LOCAL PURCHASE
	DECLARE @CDEPTID VARCHAR(2), @CHODEPTID VARCHAR(2)  

	SELECT TOP 1 @CDEPTID = [VALUE] FROM CONFIG WHERE CONFIG_OPTION = 'LOCATION_ID'

	SELECT TOP 1 @CHODEPTID = [VALUE] FROM CONFIG WHERE CONFIG_OPTION = 'HO_LOCATION_ID'

	IF ISNULL(@CCURRENTSTATE,'')=''
		SELECT @CCURRENTSTATE = STATE_CODE FROM LOC_VIEW WHERE DEPT_ID = @CDEPTID

	DECLARE @LOCLIST TABLE ( DEPT_ID VARCHAR(2) )

	IF @CDEPTID = @CHODEPTID 
		INSERT @LOCLIST
		SELECT DEPT_ID FROM LOC_VIEW
		WHERE STATE_CODE = @CCURRENTSTATE
		AND   LOC_TYPE = 1
		AND   PUR_LOC = 1
	ELSE
		INSERT @LOCLIST
		SELECT @CDEPTID AS DEPT_ID
	
	IF @NMODE=1
	
		SELECT	 MONTHYEAR, SUPPLIER	, ST_NO  ,SUM(IST_PUR_AMT) AS IST_PUR_AMT, SUM(TF_PUR_AMT ) AS TF_PUR_AMT  ,SUM(LOCAL_PUR_AMT) AS LOCAL_PUR_AMT
				,TAX_PERCENTAGE, SUM(TAX_AMOUNT	) AS TAX_AMOUNT	, SUM(TOTAL_AMOUNT ) AS TOTAL_AMOUNT 				
				,FORM_NAME
	FROM(
		SELECT	 
				  LTRIM(RTRIM(STR(MONTH(A.INV_DT))))+ '/' + RTRIM(LTRIM(STR(YEAR(A.INV_DT)))) AS MONTHYEAR
				, B.AC_NAME AS SUPPLIER
				, ( CASE WHEN F.POST_TAX_SEPARATELY=0  
						THEN B.CST_NO ELSE B.TIN_NO END ) AS ST_NO  
				, SUM( CASE WHEN (F.POST_TAX_SEPARATELY=0 AND PID.TAX_AMOUNT<>0)
 
						THEN PID.RFNET ELSE 0 END ) AS IST_PUR_AMT
				, SUM( CASE WHEN PID.TAX_AMOUNT=0 THEN  PID.RFNET  ELSE 0 END ) AS TF_PUR_AMT
				, SUM( CASE WHEN (F.POST_TAX_SEPARATELY=0 OR PID.TAX_AMOUNT=0) 
						THEN 0 ELSE PID.RFNET-PID.TAX_AMOUNT END ) AS LOCAL_PUR_AMT
				,PID.TAX_PERCENTAGE AS TAX_PERCENTAGE
				, SUM( CASE WHEN (F.POST_TAX_SEPARATELY=0 OR PID.TAX_AMOUNT=0) 
					THEN 0  ELSE PID.TAX_AMOUNT END ) AS TAX_AMOUNT
				, SUM( CASE WHEN (F.POST_TAX_SEPARATELY=0 OR PID.TAX_AMOUNT=0) THEN 0
				ELSE  PID.RFNET  END ) AS TOTAL_AMOUNT 	
				,F.FORM_NAME	
		FROM PIM01106 A  
		JOIN PID01106 PID ON A.MRR_ID=PID.MRR_ID
		JOIN FORM F ON PID.FORM_ID=F.FORM_ID
		JOIN LMV01106 B ON A.AC_CODE = B.AC_CODE  
		JOIN @LOCLIST LOC ON LEFT(A.MRR_ID,2) = LOC.DEPT_ID
		WHERE A.INV_DT BETWEEN @DFROMDT AND @DTODT 
		AND A.MEMO_TYPE = 1  
		AND A.BILL_NO <> ''  
		AND A.CANCELLED=0  
		AND  ROUND(A.SUBTOTAL,0) <>0  
		GROUP BY B.AC_NAME,PID.TAX_PERCENTAGE, ( CASE WHEN F.POST_TAX_SEPARATELY=0  
						THEN B.CST_NO ELSE B.TIN_NO END )
						

	   ,LTRIM(RTRIM(STR(MONTH(A.INV_DT))))+ '/' + RTRIM(LTRIM(STR(YEAR(A.INV_DT)))) 					
		,F.FORM_NAME
		UNION ALL
		
		SELECT	 
				LTRIM(RTRIM(STR(MONTH(A.INV_DT))))+ '/' + RTRIM(LTRIM(STR(YEAR(A.INV_DT)))) AS MONTHYEAR
				,  B.AC_NAME AS SUPPLIER
				, ( CASE WHEN F.POST_TAX_SEPARATELY=0  
						THEN B.CST_NO ELSE B.TIN_NO END ) AS ST_NO  
				, SUM( CASE WHEN (F.POST_TAX_SEPARATELY=0 AND PID.TAX_AMOUNT<>0) 
						THEN PID.RFNET ELSE 0 END ) AS IST_PUR_AMT
				, SUM( CASE WHEN PID.TAX_AMOUNT=0 THEN  PID.RFNET  ELSE 0 END ) AS TF_PUR_AMT
				, SUM( CASE WHEN (F.POST_TAX_SEPARATELY=0 OR PID.TAX_AMOUNT=0) 
						THEN 0 ELSE PID.RFNET-PID.TAX_AMOUNT END ) AS LOCAL_PUR_AMT
				,PID.TAX_PERCENTAGE AS TAX_PERCENTAGE
				, SUM( CASE WHEN (F.POST_TAX_SEPARATELY=0 OR PID.TAX_AMOUNT=0) 
					THEN 0  ELSE PID.TAX_AMOUNT END ) AS TAX_AMOUNT
				, SUM( CASE WHEN (F.POST_TAX_SEPARATELY=0 OR PID.TAX_AMOUNT=0) THEN 0
						ELSE  PID.RFNET  END ) AS TOTAL_AMOUNT 		
				,F.FORM_NAME						
		FROM PRD_PIM01106 A  
		JOIN PRD_PID01106 PID ON A.MRR_ID=PID.MRR_ID
		JOIN FORM F ON PID.FORM_ID=F.FORM_ID
		JOIN LMV01106 B ON A.AC_CODE = B.AC_CODE  
		JOIN @LOCLIST LOC ON LEFT(A.MRR_ID,2) = LOC.DEPT_ID
		WHERE A.INV_DT BETWEEN @DFROMDT AND @DTODT 
		AND A.BILL_NO <> ''  
		AND A.CANCELLED=0  
		AND  ROUND(A.SUBTOTAL,0) <>0  
		GROUP BY B.AC_NAME,PID.TAX_PERCENTAGE, ( 
						CASE WHEN F.POST_TAX_SEPARATELY=0  
						THEN B.CST_NO ELSE B.TIN_NO END )
		,LTRIM(RTRIM(STR(MONTH(A.INV_DT))))+ '/' + RTRIM(LTRIM(STR(YEAR(A.INV_DT))))				
		,F.FORM_NAME
		) A
		GROUP BY MONTHYEAR, SUPPLIER	, ST_NO  ,TAX_PERCENTAGE ,FORM_NAME
		ORDER BY MONTHYEAR
	ELSE
	 
		SELECT	 MONTHYEAR, SUPPLIER	, ST_NO  ,SUM(IST_PUR_AMT) AS IST_PUR_AMT, SUM(TF_PUR_AMT ) AS TF_PUR_AMT  ,SUM(LOCAL_PUR_AMT) AS LOCAL_PUR_AMT
				,TAX_PERCENTAGE, SUM(TAX_AMOUNT	) AS TAX_AMOUNT	, SUM(TOTAL_AMOUNT ) AS TOTAL_AMOUNT 				
				,FORM_NAME
	FROM(
		SELECT	
				LTRIM(RTRIM(STR(MONTH(A.RM_DT))))+ '/' + RTRIM(LTRIM(STR(YEAR(A.RM_DT)))) AS MONTHYEAR
				, B.AC_NAME AS SUPPLIER
				, ( CASE WHEN F.POST_TAX_SEPARATELY=0 THEN B.CST_NO ELSE B.TIN_NO END ) AS ST_NO
				,SUM( CASE WHEN ((F.POST_TAX_SEPARATELY=0 AND C.ITEM_TAX_AMOUNT<>0)) 
					THEN  C.RFNET  ELSE 0 END ) AS IST_PUR_AMT
				,SUM( CASE WHEN C.ITEM_TAX_AMOUNT=0 THEN  C.RFNET ELSE 0 END ) AS TF_PUR_AMT
				,SUM( CASE WHEN (F.POST_TAX_SEPARATELY=0 OR C.ITEM_TAX_AMOUNT=0) 
					THEN 0 ELSE  (C.RFNET-C.ITEM_TAX_AMOUNT)  END ) AS LOCAL_PUR_AMT
				,C.ITEM_TAX_PERCENTAGE AS TAX_PERCENTAGE
				,SUM( CASE WHEN (F.POST_TAX_SEPARATELY=0 OR C.ITEM_TAX_AMOUNT=0) 
					THEN 0 ELSE C.ITEM_TAX_AMOUNT END ) AS TAX_AMOUNT
				,SUM( CASE WHEN (F.POST_TAX_SEPARATELY=0 OR C.ITEM_TAX_AMOUNT=0) 
					THEN 0 ELSE  C.RFNET  END ) AS TOTAL_AMOUNT	
				,F.FORM_NAME	
		FROM RMM01106 A  
		JOIN LMV01106 B ON A.AC_CODE = B.AC_CODE  
		JOIN RMD01106 C ON A.RM_ID = C.RM_ID  
		JOIN FORM F ON C.ITEM_FORM_ID=F.FORM_ID
		JOIN @LOCLIST LOC ON LEFT(A.RM_ID,2) = LOC.DEPT_ID
		WHERE A.RM_DT BETWEEN @DFROMDT AND @DTODT AND  ROUND(A.SUBTOTAL,2) <>0 AND A.CANCELLED=0 AND A.MEMO_TYPE=1
 		GROUP BY B.AC_NAME,C.ITEM_TAX_PERCENTAGE,( CASE WHEN F.POST_TAX_SEPARATELY=0 THEN B.CST_NO ELSE B.TIN_NO END )
 		,LTRIM(RTRIM(STR(MONTH(A.RM_DT))))+ '/' + RTRIM(LTRIM(STR(YEAR(A.RM_DT))))
	 	,F.FORM_NAME
 		UNION ALL
	 	
 		SELECT	
 				LTRIM(RTRIM(STR(MONTH(A.RM_DT))))+ '/' + RTRIM(LTRIM(STR(YEAR(A.RM_DT)))) AS MONTHYEAR
 				, B.AC_NAME AS SUPPLIER
 				, ( CASE WHEN F.POST_TAX_SEPARATELY=0 THEN B.CST_NO ELSE B.TIN_NO END ) AS ST_NO
				,SUM( CASE WHEN ((F.POST_TAX_SEPARATELY=0 AND C.ITEM_TAX_AMOUNT<>0)) 
				 THEN  C.RFNET  ELSE 0 END ) AS IST_PUR_AMT
				,SUM( CASE WHEN C.ITEM_TAX_AMOUNT=0 THEN  C.RFNET ELSE 0 END ) AS TF_PUR_AMT
				,SUM( CASE WHEN (F.POST_TAX_SEPARATELY=0 OR C.ITEM_TAX_AMOUNT=0) 
					THEN 0 ELSE  (C.RFNET-C.ITEM_TAX_AMOUNT)  END ) AS LOCAL_PUR_AMT
				,C.ITEM_TAX_PERCENTAGE AS TAX_PERCENTAGE
				,SUM( CASE WHEN (F.POST_TAX_SEPARATELY=0 OR C.ITEM_TAX_AMOUNT=0) 
					THEN 0 ELSE C.ITEM_TAX_AMOUNT END ) AS TAX_AMOUNT
				,SUM( CASE WHEN (F.POST_TAX_SEPARATELY=0 OR C.ITEM_TAX_AMOUNT=0) 
					THEN 0 ELSE  C.RFNET  END ) AS TOTAL_AMOUNT	
				,F.FORM_NAME
		FROM PRD_RMM01106 A  
		JOIN LMV01106 B ON A.AC_CODE = B.AC_CODE  
		JOIN PRD_RMD01106 C ON A.RM_ID = C.RM_ID  
		JOIN FORM F ON C.ITEM_FORM_ID=F.FORM_ID
		JOIN @LOCLIST LOC ON LEFT(A.RM_ID,2) = LOC.DEPT_ID
		WHERE A.RM_DT BETWEEN @DFROMDT AND @DTODT AND  ROUND(A.SUBTOTAL,2) <>0 AND A.CANCELLED=0
 		GROUP BY B.AC_NAME,C.ITEM_TAX_PERCENTAGE,( CASE WHEN F.POST_TAX_SEPARATELY=0 THEN B.CST_NO ELSE B.TIN_NO END )
 		,LTRIM(RTRIM(STR(MONTH(A.RM_DT))))+ '/' + RTRIM(LTRIM(STR(YEAR(A.RM_DT))))
 		,F.FORM_NAME
) A
		GROUP BY MONTHYEAR, SUPPLIER	, ST_NO  ,TAX_PERCENTAGE ,FORM_NAME
		ORDER BY MONTHYEAR
END
