CREATE  PROCEDURE SP_GETIMAGE_BY_IMG_ID_2021    
(    
   @IMG_ID VARCHAR(100)=''
)    
AS    
BEGIN 
	--INSERT INTO IMAGE_TEST(LOC_ID , DT_DR ,LAST_UPDATE ) SELECT @IMG_ID,GETDATE(),GETDATE()
	DECLARE @DTSQL NVARCHAR(MAX)
	DECLARE @cDB_NAME NVARCHAR(MAX)
	SET @cDB_NAME=DB_NAME()+'_IMAGE'
	SET @DTSQL=N'IF EXISTS(SELECT IMG_ID FROM '+@cDB_NAME+'..IMAGE_INFO  IMAGE_INFO  (NOLOCK) WHERE IMG_ID='''+@IMG_ID+''')
					SELECT *,'''' AS ERRORMSG FROM '+@cDB_NAME+'..IMAGE_INFO  IMAGE_INFO  (NOLOCK) WHERE IMG_ID='''+@IMG_ID+'''
				ELSE
					SELECT ''Image Not Found in Database'' AS ERRORMSG'

	PRINT @DTSQL 
	EXEC SP_EXECUTESQL @DTSQL 
END