
CREATE PROCEDURE SP3S_UPDATE_LOCATION_CM_DT
AS
BEGIN
    
	DECLARE @CLOCID VARCHAR(5),@CHOLOC_ID VARCHAR(5)

	SELECT @CLOCID=VALUE  FROM CONFIG WHERE CONFIG_OPTION ='LOCATION_ID'
	SELECT @CHOLOC_ID=VALUE  FROM CONFIG WHERE CONFIG_OPTION ='HO_LOCATION_ID'

	IF @CLOCID<>@CHOLOC_ID
	RETURN

    IF OBJECT_ID('TEMPDB..#TMPCMM','U') IS NOT NULL
	   DROP TABLE #TMPCMM

    SELECT B.location_Code  AS DEPT_ID,MAX(CM_DT) AS MAX_CM_DT,
	MIN(CM_DT) AS MIN_CM_DT
	INTO #TMPCMM
	FROM  CMM01106 B (NOLOCK) 
	WHERE B.CANCELLED=0
	GROUP BY B.location_Code 

	UPDATE A SET MAX_CM_DT=B.MAX_CM_DT FROM LOCATION  A (NOLOCK)
	JOIN #TMPCMM  B ON A.DEPT_ID=B.DEPT_ID

	IF EXISTS (SELECT TOP 1 'U' FROM LOCATION (NOLOCK) WHERE ISNULL(MIN_CM_DT,'')='')
	BEGIN

	
	    UPDATE A SET MIN_CM_DT=B.MIN_CM_DT 
		FROM LOCATION  A (NOLOCK)
	    JOIN #TMPCMM  B ON A.DEPT_ID=B.DEPT_ID
		WHERE ISNULL(A.MIN_CM_DT,'')=''

	END


END

