CREATE PROCEDURE SP_WSLPACKSLIP_7--(LocId 3 digit change only increased the parameter width by Sanjay:04-11-2024)
 @CMEMOID VARCHAR(40) = '',  
 @CWHERE  VARCHAR(500) = '',
 @NNAVMODE NUMERIC(1,0) = 0,  
 @CFINYEAR VARCHAR(5)='',
 @CLOCID varchar(4)=''
--WITH ENCRYPTION
AS  
BEGIN  

    SELECT EMP_CODE, EMP_NAME, EMP_NAME AS EMP_NAME_ORG,0 AS ALIASENTRY   
    FROM EMPLOYEE   
    WHERE INACTIVE = 0   
    UNION   
    SELECT EMP_CODE, EMP_ALIAS AS EMP_NAME, EMP_NAME AS EMP_NAME_ORG,1 AS ALIASENTRY    
    FROM EMPLOYEE   
    WHERE INACTIVE = 0 AND EMP_ALIAS <>''  
    ORDER BY EMP_NAME   
  
end