---Discarded this Procedure as it iwas sending Config_loc tablel from Ho and 
-- it was overwriting the Login Date information at POS
-- Now application will call new API for sending Location master without this Table