CREATE PROC VALIDATEXN_PUR_BEFORE_EDIT 
@CMEMOID VARCHAR(30),
@BCANCELXN BIT,
@CERRORMSG VARCHAR(200) OUTPUT,
@CEXPRERRORMSG VARCHAR(200) OUTPUT
--WITH ENCRYPTION
AS
BEGIN
	
	DECLARE @CTEXT VARCHAR(10),@CPRODUCTCODE VARCHAR(50)
	
	SELECT @CPRODUCTCODE=''
	
	SET @CTEXT=(CASE WHEN @BCANCELXN=1 THEN 'CANCEL' ELSE 'EDIT' END)
	
	--IF EXISTS (SELECT TOP 1 MRR_ID FROM PIM01106 A JOIN VM01106 B ON A.BILL_NO=B.BILL_ID AND A.INV_DT=B.BILL_DT
	--		   AND A.AC_CODE=B.BILL_AC_CODE WHERE A.MRR_ID=@CMEMOID AND B.BILL_TYPE='PUR' AND  B.CANCELLED=0)
	--BEGIN	
	--	SET @CERRORMSG='THIS BILL HAS BEEN POSTED INTO ACCOUNTS.........CAN NOT '+@CTEXT
	--	RETURN
	--END
	/*
	* ROHIT 08-01-2022 : Against Ticket No 12-0411 of SUVIDHA
	*
	DECLARE  @TOTAL_AMOUNT NUMERIC(12,2)
	SELECT TOP 1 @TOTAL_AMOUNT=TOTAL_AMOUNT FROM PIM01106_AUDIT (NOLOCK) 
	WHERE MRR_ID =@CMEMOID
	ORDER BY LAST_UPDATE DESC
   

	IF EXISTS (SELECT TOP 1  A.MRR_ID FROM PIM01106  A (NOLOCK)
	JOIN PID01106 B ON A.MRR_ID =B.MRR_ID 
	JOIN RMM01106 (NOLOCK) C ON A.MRR_ID=C.REFMEMOID  
	WHERE C.CANCELLED=0 AND A.CANCELLED=0 AND  A.MRR_ID=@CMEMOID AND  B.PRTAMOUNT<>0  AND A.TOTAL_AMOUNT<>@TOTAL_AMOUNT)
    BEGIN	
		SET @CERRORMSG='DEBIT NOTE ALREADY CREATED FOR THIS .........CAN NOT '+@CTEXT
		RETURN
	END
	
	
	IF EXISTS (SELECT TOP 1  A.MRR_ID FROM PIM01106  A (NOLOCK)
	JOIN RMM01106 C (NOLOCK)  ON A.MRR_ID=C.REFMEMOID  
	WHERE C.CANCELLED=0 AND A.CANCELLED=0 AND  A.MRR_ID=@CMEMOID AND  isnull(A.PIM_MODE,0) =6 )
    BEGIN	
		SET @CERRORMSG='DEBIT NOTE ALREADY CREATED FOR THIS .........CAN NOT '+@CTEXT
		RETURN
	END
	
	DECLARE @CHECK_SUPPLIER_DN BIT
	select @CHECK_SUPPLIER_DN =CONVERT(BIT ,VALUE) from config where config_option ='CHECK_SUPPLIER_DN'

	IF EXISTS (SELECT PID_ROW_ID
	from RMD01106 A (NOLOCK)
	JOIN RMM01106 B (NOLOCK) ON A.rm_id=B.rm_id
	JOIN PID01106 C (NOLOCK) ON C.row_id=A.PID_ROW_ID
	JOIN PIM01106 D (NOLOCK) ON D.mrr_id=C.mrr_id
	WHERE D.CANCELLED=0 AND B.CANCELLED=0 
	AND D.mrr_id=@CMEMOID) AND @CHECK_SUPPLIER_DN=1
	BEGIN	
		SET @CERRORMSG='DEBIT NOTE ALREADY CREATED FOR THIS .........CAN NOT '+@CTEXT
		RETURN
	END
	*/	
END
