CREATE PROC SP_ERP_ARTICLEINFOMRP  
(  
 @CARTICLECODE CHAR(9),  
 @CPARA2CODE CHAR(7)  
)  
--WITH ENCRYPTION
AS  
BEGIN  
   
 DECLARE @TABLE TABLE ( PURPRICE NUMERIC, MRP NUMERIC, WSPRICE NUMERIC )  
 DECLARE @NCOUNT INT   
 SET @NCOUNT = 0    
 SELECT @NCOUNT = COUNT(*) FROM ART_DET A   
 WHERE A.ARTICLE_CODE = @CARTICLECODE AND A.PARA2_CODE = @CPARA2CODE  
     
 PRINT @NCOUNT  
     
 IF ( @NCOUNT > 0 )   
 BEGIN    
  PRINT 'ART_DET'  
  INSERT INTO @TABLE  
  SELECT A.PURCHASE_PRICE, A.MRP, A.WS_PRICE FROM ART_DET A   
  WHERE A.ARTICLE_CODE = @CARTICLECODE AND A.PARA2_CODE = @CPARA2CODE  
 END  
 ELSE  
 BEGIN  
  PRINT 'ARTICLE'  
  INSERT INTO @TABLE  
  SELECT A.PURCHASE_PRICE, A.MRP, A.WHOLESALE_PRICE FROM ARTICLE A   
  WHERE A.ARTICLE_CODE = @CARTICLECODE  
 END  
  
 SELECT * FROM @TABLE  
    
END  

--------------------------------------------------------------------------------
