CREATE PROCEDURE SP3S_GET_EMPLOYEE_FKEYDATA
@CSOURCEDB VARCHAR(200),
@CSOURCETABLE VARCHAR(200),
@CSOURCEKEYFIELD VARCHAR(200),
@CXNTYPE VARCHAR(10),
@CTABLESUFFIX VARCHAR(40),
@CLOCID VARCHAR(5),
@CERRORMSG VARCHAR(MAX) OUTPUT
--WITH ENCRYPTION
AS
BEGIN
	BEGIN TRY
		DECLARE @CCMD NVARCHAR(MAX),@CTEMPTABLE VARCHAR(1000),@CTEMPTABLE1 VARCHAR(1000),@CTEMPTABLE2 VARCHAR(1000),
				@CTEMPTABLE3 VARCHAR(1000),@CTEMPTABLE4 VARCHAR(1000),@CTEMPTABLE5 VARCHAR(1000),
				@CKEYFIELDVAL VARCHAR(40),@CDESTDB VARCHAR(200),@CFILTERCONDITION VARCHAR(MAX),@NSTEP INT
		
		SET @CDESTDB='WIZAPP3S_MIRROR_'+@CLOCID+'.DBO.'
		
		SET @NSTEP=10		
		IF @CSOURCETABLE<>'#TMPMISSINGEMPDATA'
		BEGIN
			IF OBJECT_ID('TEMPDB..#TMPMISSINGEMPDATA','U') IS NOT NULL
				DROP TABLE #TMPMISSINGEMPDATA
			
			SELECT EMP_CODE INTO #TMPMISSINGEMPDATA FROM EMPLOYEE WHERE 1=2
		END
		
		SET @NSTEP=20											
		SET @CTEMPTABLE=(CASE WHEN LEFT(@CSOURCETABLE,1)='#' THEN @CSOURCETABLE ELSE @CSOURCEDB+'TMP_'+@CXNTYPE+'_'+@CSOURCETABLE+'_'+@CTABLESUFFIX END)
		
		IF @CSOURCETABLE<>'#TMPMISSINGEMPDATA'
		BEGIN
			SET @CCMD=N'SELECT DISTINCT A.'+@CSOURCEKEYFIELD+' FROM '+@CTEMPTABLE+'  A
						LEFT OUTER JOIN WIZAPP3S_MIRROR_'+@CLOCID+'.DBO.EMPLOYEE B ON B.EMP_CODE=A.'+@CSOURCEKEYFIELD+'
						WHERE B.EMP_CODE IS NULL AND A.'+@CSOURCEKEYFIELD+' IS NOT NULL'

			PRINT @CCMD	
			INSERT #TMPMISSINGEMPDATA
			EXEC SP_EXECUTESQL @CCMD
		END
				
		IF EXISTS (SELECT TOP 1 EMP_CODE FROM #TMPMISSINGEMPDATA)
		BEGIN
			SET @NSTEP=80

			SET @CFILTERCONDITION= 'B.EMP_CODE IN (SELECT DISTINCT EMP_HEAD FROM #TMPMISSINGEMPDATA A
									JOIN EMPLOYEE B ON A.EMP_CODE=B.EMP_CODE)'
			
			EXEC UPDATEMASTERXN_MIRROR
			@CSOURCEDB='',
			@CSOURCETABLE='EMPLOYEE',
			@CDESTDB=@CDESTDB,
			@CDESTTABLE='EMPLOYEE',
			@CKEYFIELD1='EMP_CODE',
			@LINSERTONLY=0,
			@CFILTERCONDITION=@CFILTERCONDITION,
			
			
			@LUPDATEONLY=0,
			@BALWAYSUPDATE=1
			
			SET @NSTEP=90			
			SET @CFILTERCONDITION= 'B.EMP_CODE IN (SELECT EMP_CODE FROM #TMPMISSINGEMPDATA)'
			
			EXEC UPDATEMASTERXN_MIRROR
			@CSOURCEDB='',
			@CSOURCETABLE='EMPLOYEE',
			@CDESTDB=@CDESTDB,
			@CDESTTABLE='EMPLOYEE',
			@CKEYFIELD1='EMP_CODE',
			@LINSERTONLY=0,
			@CFILTERCONDITION=@CFILTERCONDITION,
			
			
			@LUPDATEONLY=0,
			@BALWAYSUPDATE=1
		END
							
		GOTO END_PROC									
	END TRY
	
	BEGIN CATCH
		SELECT @CERRORMSG='PROCEDURE SP3S_GET_EMPLOYEE_FKEYDATA : '+ISNULL(ERROR_PROCEDURE(),'NULL P')+'STEP :'+STR(ISNULL(@NSTEP,0))+ ' LINE NO. :'+
		ISNULL(LTRIM(RTRIM(STR(ERROR_LINE()))),'NULL LINE')+'MSG :'+ISNULL(ERROR_MESSAGE(),'NULL MSG')
		
		GOTO END_PROC
	END CATCH
	
END_PROC:
		
END
----'END OF PROCEDURE SP3S_GET_EMPLOYEE_FKEYDATA'
