CREATE PROCEDURE SP_NAVIGATE_ALL 
@CTABLENAME VARCHAR(100),
@NNAVMODE INT,
@CFINYEARPARA VARCHAR(10),
@CMEMONO VARCHAR(50),
@CMEMONOCOL VARCHAR(100)='MEMO_NO',
@CMEMODTCOL VARCHAR(100)='MEMO_DT',
@CMEMOIDCOL VARCHAR(100)='MEMO_ID',
@CWHERECLAUSE VARCHAR(500)='',
@BINCLUDEESTIMATE BIT=1
--WITH ENCRYPTION
AS
BEGIN
	PRINT 'ENTER NAVIGATE ALL'
	DECLARE @DMEMODT DATETIME,@CCMD NVARCHAR(MAX),@CFINYEAR VARCHAR(10)
	
	DECLARE @TNAVIGATE TABLE (MEMO_NO VARCHAR(20),MEMO_ID VARCHAR(40),FIN_YEAR VARCHAR(10))
		
	SET @CCMD=N'SELECT @DMEMODTOUT='+@CMEMODTCOL+',@CFINYEAROUT=FIN_YEAR FROM '+@CTABLENAME+' WHERE '+@CMEMONOCOL+'='''+@CMEMONO+'''
				AND FIN_YEAR='''+@CFINYEARPARA+''''
	PRINT ISNULL(@CCMD,'NULAPP-1')
	EXEC SP_EXECUTESQL @CCMD,N'@DMEMODTOUT DATETIME OUTPUT,@CFINYEAROUT VARCHAR(10) OUTPUT',
	@DMEMODTOUT=@DMEMODT OUTPUT,@CFINYEAROUT=@CFINYEAR OUTPUT
	
	SET @CCMD = N'SELECT TOP 1 '+@CMEMONOCOL+','+@CMEMOIDCOL+',FIN_YEAR FROM '+@CTABLENAME+' WHERE 1=1 '+
	(CASE WHEN @BINCLUDEESTIMATE=1 THEN '' ELSE ' AND MEMO_TYPE<>2 ' END)+
				   (CASE WHEN @CWHERECLAUSE<>'' THEN ' AND '+@CWHERECLAUSE ELSE '' END)+
				   (CASE WHEN @NNAVMODE IN(0,2,3) THEN ' AND '+@CMEMODTCOL+'='''+CONVERT(VARCHAR,@DMEMODT,110)+'''
				  AND '+@CMEMONOCOL+(CASE WHEN @NNAVMODE=2 THEN '<' WHEN @NNAVMODE=3 THEN '>' ELSE '=' END)+''''+@CMEMONO+'''' ELSE '' END)+
				 ' ORDER BY '+@CMEMODTCOL+(CASE WHEN @NNAVMODE IN (1,3) THEN ' ASC ' ELSE ' DESC ' END)+
				 ' ,'+@CMEMONOCOL+(CASE WHEN @NNAVMODE IN (1,3) THEN ' ASC ' ELSE ' DESC ' END)
				 
	PRINT ISNULL(@CCMD,'NULAPP-2')
	
	INSERT @TNAVIGATE			 
	EXEC SP_EXECUTESQL @CCMD                           
	
	IF NOT EXISTS (SELECT TOP 1 MEMO_NO FROM @TNAVIGATE)
	BEGIN
		SET @CCMD = N'SELECT TOP 1 '+@CMEMONOCOL+','+@CMEMOIDCOL+',FIN_YEAR FROM '+@CTABLENAME+' WHERE 1=1 '+
						(CASE WHEN @BINCLUDEESTIMATE=1 THEN '' ELSE ' AND MEMO_TYPE<>2 ' END)+
					  (CASE WHEN @CWHERECLAUSE<>'' THEN ' AND '+@CWHERECLAUSE ELSE '' END)+
					  (CASE WHEN @NNAVMODE IN(0,2,3) THEN ' AND '+@CMEMODTCOL+ 
					  (CASE WHEN @NNAVMODE=2 THEN '<' WHEN @NNAVMODE=3 THEN '>' ELSE '=' END)+
					  ''''+CONVERT(VARCHAR,@DMEMODT,110)+''' AND '+@CMEMONOCOL+'<>'''+@CMEMONO+'''' ELSE '' END)+
					  'ORDER BY '+@CMEMODTCOL+(CASE WHEN @NNAVMODE IN (1,3) THEN ' ASC ' ELSE ' DESC ' END)+
					 ' ,'+@CMEMONOCOL+(CASE WHEN @NNAVMODE IN (1,3) THEN ' ASC ' ELSE ' DESC ' END)
		PRINT ISNULL(@CCMD,'NULAPP-3')
		INSERT @TNAVIGATE				 
		EXEC SP_EXECUTESQL @CCMD	
	END
	
	IF NOT EXISTS (SELECT TOP 1 MEMO_NO FROM @TNAVIGATE)
	BEGIN
		SET @CCMD=N'SELECT '+@CMEMONOCOL+','+@CMEMOIDCOL+',FIN_YEAR FROM '+@CTABLENAME+' WHERE '+@CMEMONOCOL+'='''+@CMEMONO+''''
		PRINT ISNULL(@CCMD,'NULAPP-4')
		
		INSERT @TNAVIGATE				 
		EXEC SP_EXECUTESQL @CCMD	
	END
	
	IF OBJECT_ID('TEMPDB..#TMPNAV','U') IS NOT NULL
		DROP TABLE #TMPNAV
	
	SELECT MEMO_NO,MEMO_ID,FIN_YEAR INTO #TMPNAV FROM @TNAVIGATE
	
	SET @CCMD=N'SELECT MEMO_NO AS '+@CMEMONOCOL+',MEMO_ID AS '+@CMEMOIDCOL+',FIN_YEAR FROM #TMPNAV'
	PRINT ISNULL(@CCMD,'NULAPP-5')
	EXEC SP_EXECUTESQL @CCMD	
	
END
