CREATE PROCEDURE SP_MERGE_MIRROR_LOCSST
(
	@NMODE INT
)
----WITH ENCRYPTION
AS


SET NOCOUNT ON
BEGIN

DECLARE @CSTEP VARCHAR(100),@DTSQL NVARCHAR(MAX),@NMERGE_ORDER NUMERIC(5)
	   ,@CTABLENAME VARCHAR(200),@CTABLE_SUFFIX VARCHAR(50),@CKEYFIELD VARCHAR(200),@CDEL_ID VARCHAR(50),@CTMP_TABLENAME VARCHAR(200),@LINSERTONLY VARCHAR(1)
	   ,@CFILTERCONDITION VARCHAR(200),@LUPDATEONLY VARCHAR(1),@BALWAYSUPDATE VARCHAR(1),@FDEL CHAR(1)
	   ,@CERRMSG VARCHAR(1000),@CTABLESSTR VARCHAR(MAX),@CMRRIDSEARCH VARCHAR(100),@CERRORUPDPMT VARCHAR(MAX)
	    ,@EDITPUR BIT,@CMERGEDB VARCHAR(50),@CSOURCEDB VARCHAR(50)
BEGIN TRY

	IF @NMODE=1
		GOTO EXIT_PROC
		
BEGIN TRANSACTION 

	
    SELECT @CMERGEDB='',@CSOURCEDB=''
    
    SET @CSTEP=10
    DELETE FROM LOCSSTADD
    DELETE FROM LOCSST
    DELETE FROM LOCSST_MST
    
	SET @CSTEP=40
	SET @CTMP_TABLENAME='MSTLST_LOCSST_UPLOAD'
	SET @CKEYFIELD='ROW_ID'
	SET @CSTEP=50
	SET @DTSQL=N'DELETE  A FROM MSTLST_LOCSST_UPLOAD A LEFT JOIN SECTIOND B ON A.SUB_SECTION_CODE=B.SUB_SECTION_CODE
	              WHERE B.SUB_SECTION_CODE IS NULL'
	PRINT @DTSQL
	EXEC SP_EXECUTESQL @DTSQL
	
	SET @CSTEP=60
	SET @CTMP_TABLENAME='MSTLST_LOCSSTADD_UPLOAD'
	SET @CKEYFIELD='ROW_ID'
	SET @CSTEP=70
	SET @DTSQL=N'DELETE  A FROM MSTLST_LOCSSTADD_UPLOAD A LEFT JOIN MSTLST_LOCSST_UPLOAD B ON A.LOCSST_ROW_ID=B.ROW_ID
	             WHERE B.ROW_ID IS NULL'
	PRINT @DTSQL
	EXEC SP_EXECUTESQL @DTSQL
	
	
	---ADD BELOW TABLE DETAILS BY JAI RAM STARTED
	SET @CSTEP=71
	SET @CTABLENAME='REGIONM'
	SET @CTMP_TABLENAME='MSTLST_REGIONM_UPLOAD'
	SET @CKEYFIELD='REGION_CODE'
	SET @CSTEP=90
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=0,@CFILTERCONDITION='',@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1 
    SET @CSTEP=75
	SET @CTABLENAME='STATE'
	SET @CTMP_TABLENAME='MSTLST_STATE_UPLOAD'
	SET @CKEYFIELD='STATE_CODE'
	SET @CSTEP=90
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=0,@CFILTERCONDITION='',@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1 
							  
	---END
	
	SET @CSTEP=101
	SET @CTABLENAME='FORM'
	SET @CTMP_TABLENAME='MSTLST_FORM_UPLOAD'
	SET @CKEYFIELD='FORM_ID'
	SET @CSTEP=110
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=1,@CFILTERCONDITION='',@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1 
	
	
	
	SET @CSTEP=80
	SET @CTABLENAME='LOCSST_MST'
	SET @CTMP_TABLENAME='MSTLST_LOCSST_MST_UPLOAD'
	SET @CKEYFIELD='MEMO_ID'
	SET @CSTEP=90
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=0,@CFILTERCONDITION='',@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1 
    SET @CSTEP=100
	SET @CTABLENAME='LOCSST'
	SET @CTMP_TABLENAME='MSTLST_LOCSST_UPLOAD'
	SET @CKEYFIELD='ROW_ID'
	SET @CSTEP=120
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=0,@CFILTERCONDITION='',@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1 
    SET @CSTEP=130
	SET @CTABLENAME='LOCSSTADD'
	SET @CTMP_TABLENAME='MSTLST_LOCSSTADD_UPLOAD'
	SET @CKEYFIELD='ROW_ID'
	SET @CSTEP=140
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=0,@CFILTERCONDITION='',@LUPDATEONLY=0
	
	
END TRY
BEGIN CATCH
	SET @CERRMSG='P:SP_MERGE_MIRROR_LOCSST, STEP:'+@CSTEP+', MESSAGE:'+ERROR_MESSAGE()
END CATCH

EXIT_PROC:
	IF ISNULL(@CERRMSG,'')='' AND @@TRANCOUNT>0
	BEGIN
		COMMIT
	END
	ELSE IF ISNULL(@CERRMSG,'')<>'' AND @@TRANCOUNT>0
		ROLLBACK

   IF ISNULL(@CERRMSG,'')=''
   BEGIN		
	   DELETE FROM MSTLST_LOCSST_MST_UPLOAD 
	   DELETE FROM MSTLST_LOCSST_UPLOAD 
	   DELETE FROM MSTLST_LOCSSTADD_UPLOAD 
	   DELETE FROM MSTLST_STATE_UPLOAD
	   DELETE FROM MSTLST_REGIONM_UPLOAD
	   DELETE FROM MSTLST_FORM_UPLOAD
   END	
   
   SELECT 'MSTLST' AS MEMO_ID,ISNULL(@CERRMSG,'') AS ERRMSG   	  		
   
END	
---END OF PROCEDURE - SP_MERGE_MIRROR_LOCSST
