create PROCEDURE SP_BUYERSORDER_WSL_12
@CMEMOID VARCHAR(40),  
@CWHERE VARCHAR(500),  
@CFINYEAR VARCHAR(10),  
@NNAVMODE NUMERIC(2,0),
@CARTICLECODE CHAR(9)='',  
@CPARA2CODE CHAR(7)='',
@DTWHERE DATETIME ='',
@cLocId VARCHAR(5)=''
--WITH ENCRYPTION
 
AS    
BEGIN 
	DECLARE @nWsPrice NUMERIC(10,2)    


	SELECT TOP 1 @nWsPrice=sfp.fc_rate 
	FROM sku_fc_prices sfp (NOLOCK)
	JOIN location loc (NOLOCK) ON 1=1
	JOIN sku (NOLOCK) ON sku.product_code=sfp.product_code
	WHERE article_CODE=@CWHERE and loc.dept_id= @CLOCID AND sfp.fc_code=loc.fc_code      
	ORDER BY sfp.last_update DESC
						  
	SELECT A.ARTICLE_CODE, A.ARTICLE_DESC, A.ARTICLE_NAME,   
		 A.ARTICLE_NO, A.CODING_SCHEME,    
	     A.PURCHASE_PRICE, (CASE WHEN ISNULL(@nWsPrice,0)<>0 THEN @nWsPrice ELSE A.MRP END) AS MRP,(CASE WHEN ISNULL(@nWsPrice,0)<>0 THEN @nWsPrice ELSE A.WHOLESALE_PRICE END) AS WS_PRICE, A.CREATED_ON,   
		 A.PARA1_SET, A.PARA2_SET, B.UOM_CODE,B.UOM_NAME, B.UOM_TYPE,A.DT_CREATED,
		 A.ALIAS AS ARTICLE_ALIAS   ,A.HSN_CODE 
		 ,sd.sub_section_name,sm.section_name,sd.sub_section_code,sm.section_code 

		,ISNULL(A1.ATTR1_KEY_NAME,'') as ATTR1_KEY_NAME   ,ISNULL(A2.ATTR2_KEY_NAME,'')  as ATTR2_KEY_NAME
		,ISNULL(A3.ATTR3_KEY_NAME,'') as ATTR3_KEY_NAME  ,ISNULL(A4.ATTR4_KEY_NAME,'') as ATTR4_KEY_NAME
		,ISNULL(A5.ATTR5_KEY_NAME,'') as ATTR5_KEY_NAME,ISNULL(A6.ATTR6_KEY_NAME,'') as ATTR6_KEY_NAME
		,ISNULL(A7.ATTR7_KEY_NAME,'')  ATTR7_KEY_NAME ,ISNULL(A8.ATTR8_KEY_NAME,'')  ATTR8_KEY_NAME
		,ISNULL(A9.ATTR9_KEY_NAME,'')  ATTR9_KEY_NAME ,ISNULL(A10.ATTR10_KEY_NAME,'') ATTR10_KEY_NAME
		,ISNULL(A11.ATTR11_KEY_NAME,'') ATTR11_KEY_NAME,ISNULL(A12.ATTR12_KEY_NAME,'') ATTR12_KEY_NAME
		,ISNULL(A13.ATTR13_KEY_NAME,'') ATTR13_KEY_NAME ,ISNULL(A14.ATTR14_KEY_NAME,'') ATTR14_KEY_NAME
		,ISNULL(A15.ATTR15_KEY_NAME,'') ATTR15_KEY_NAME     
		,ISNULL(A16.ATTR16_KEY_NAME,'') ATTR16_KEY_NAME,ISNULL(A17.ATTR17_KEY_NAME,'') ATTR17_KEY_NAME
		,ISNULL(A18.ATTR18_KEY_NAME,'') ATTR18_KEY_NAME,ISNULL(A19.ATTR19_KEY_NAME,'') ATTR19_KEY_NAME
		,ISNULL(A20.ATTR20_KEY_NAME,'')  ATTR20_KEY_NAME  ,ISNULL(A21.ATTR21_KEY_NAME,'') ATTR21_KEY_NAME
		 ,ISNULL(A22.ATTR22_KEY_NAME,'') as ATTR22_KEY_NAME,ISNULL(A23.ATTR23_KEY_NAME,'') as ATTR23_KEY_NAME
		 ,ISNULL(A24.ATTR24_KEY_NAME,'') ATTR24_KEY_NAME,ISNULL(A25.ATTR25_KEY_NAME,'')  ATTR25_KEY_NAME     	  

	FROM ARTICLE A (NOLOCK)     
	JOIN UOM B (NOLOCK)  ON A.UOM_CODE = B.UOM_CODE   
	join sectiond sd on sd.sub_section_code=a.sub_section_code
	join sectionm sm on sd.section_code=sm.section_code

	LEFT JOIN ARTICLE_FIX_ATTR  AF (NOLOCK) ON AF.ARTICLE_CODE=A.ARTICLE_CODE
	LEFT JOIN ATTR1_MST A1 (NOLOCK) ON A1.ATTR1_KEY_CODE=af.attr1_KEY_CODE      
	LEFT JOIN ATTR2_MST A2 (NOLOCK) ON A2.ATTR2_KEY_CODE=af.attr2_KEY_CODE      
	LEFT JOIN ATTR3_MST A3 (NOLOCK) ON A3.ATTR3_KEY_CODE=af.attr3_KEY_CODE      
	LEFT JOIN ATTR4_MST A4 (NOLOCK) ON A4.ATTR4_KEY_CODE=af.attr4_KEY_CODE      
	LEFT JOIN ATTR5_MST A5 (NOLOCK) ON A5.ATTR5_KEY_CODE=af.attr5_KEY_CODE      
	LEFT JOIN ATTR6_MST A6 (NOLOCK) ON A6.ATTR6_KEY_CODE=af.attr6_KEY_CODE      
	LEFT JOIN ATTR7_MST A7 (NOLOCK) ON A7.ATTR7_KEY_CODE=af.attr7_KEY_CODE      
	LEFT JOIN ATTR8_MST A8 (NOLOCK) ON A8.ATTR8_KEY_CODE=af.attr8_KEY_CODE      
	LEFT JOIN ATTR9_MST A9 (NOLOCK) ON A9.ATTR9_KEY_CODE=af.attr9_KEY_CODE      
	LEFT JOIN ATTR10_MST A10 (NOLOCK) ON A10.ATTR10_KEY_CODE=af.attr10_KEY_CODE      
	LEFT JOIN ATTR11_MST A11 (NOLOCK) ON A11.ATTR11_KEY_CODE=af.attr11_KEY_CODE      
	LEFT JOIN ATTR12_MST A12 (NOLOCK) ON A12.ATTR12_KEY_CODE=af.attr12_KEY_CODE      
	LEFT JOIN ATTR13_MST A13 (NOLOCK) ON A13.ATTR13_KEY_CODE=af.attr13_KEY_CODE      
	LEFT JOIN ATTR14_MST A14 (NOLOCK) ON A14.ATTR14_KEY_CODE=af.attr14_KEY_CODE      
	LEFT JOIN ATTR15_MST A15 (NOLOCK) ON A15.ATTR15_KEY_CODE=af.attr15_KEY_CODE      
	LEFT JOIN ATTR16_MST A16 (NOLOCK) ON A16.ATTR16_KEY_CODE=af.attr16_KEY_CODE      
	LEFT JOIN ATTR17_MST A17 (NOLOCK) ON A17.ATTR17_KEY_CODE=af.attr17_KEY_CODE      
	LEFT JOIN ATTR18_MST A18 (NOLOCK) ON A18.ATTR18_KEY_CODE=af.attr18_KEY_CODE      
	LEFT JOIN ATTR19_MST A19 (NOLOCK) ON A19.ATTR19_KEY_CODE=af.attr19_KEY_CODE      
	LEFT JOIN ATTR20_MST A20 (NOLOCK) ON A20.ATTR20_KEY_CODE=af.attr20_KEY_CODE      
	LEFT JOIN ATTR21_MST A21 (NOLOCK) ON A21.ATTR21_KEY_CODE=af.attr21_KEY_CODE      
	LEFT JOIN ATTR22_MST A22 (NOLOCK) ON A22.ATTR22_KEY_CODE=af.attr22_KEY_CODE      
	LEFT JOIN ATTR23_MST A23 (NOLOCK) ON A23.ATTR23_KEY_CODE=af.attr23_KEY_CODE      
	LEFT JOIN ATTR24_MST A24 (NOLOCK) ON A24.ATTR24_KEY_CODE=af.attr24_KEY_CODE      
	LEFT JOIN ATTR25_MST A25 (NOLOCK) ON A25.ATTR25_KEY_CODE=Af.ATTR25_KEY_CODE 

	WHERE A.ARTICLE_TYPE =1 AND ARTICLE_PRD_MODE <> 3 
	AND  A.ARTICLE_CODE = @CWHERE  AND  A.INACTIVE =0   

END