CREATE PROCEDURE SP_QUOTATION_ALL 
(  
 @CQUERYID  NUMERIC(2),  
 @CWHERE   NVARCHAR(MAX)='',  
 @CFINYEAR  VARCHAR(5)='',  
 @CDEPTID  VARCHAR(4)='',  
 @NNAVMODE  NUMERIC(2)=1,  
 @CWHERECLAUSE VARCHAR(500)='' ,
 @DPODT DATETIME='' 
   
)
--WITH ENCRYPTION 
AS  
BEGIN  
DECLARE @CCMD NVARCHAR(MAX),@cHEAD_CODE VARCHAR(MAX) 
SET @CCMD=''  
    IF @CQUERYID=1  
  GOTO LBLPOLU  
 ELSE IF @CQUERYID=2  
  GOTO LBLMST  
 ELSE IF @CQUERYID=3  
  GOTO LBLDET  
 ELSE IF @CQUERYID=4  
  GOTO LBLPARA1  
 ELSE IF @CQUERYID=5  
  GOTO LBLPARA2  
 ELSE IF @CQUERYID=6  
  GOTO LBLPARA3  
 ELSE IF @CQUERYID=7  
  GOTO LBLPARA4  
 ELSE IF @CQUERYID=8  
  GOTO LBLPARA5  
 ELSE IF @CQUERYID=9  
  GOTO LBLPARA6  
 ELSE IF @CQUERYID=10  
  GOTO LBLSUPPLIERS  
 ELSE IF @CQUERYID=11  
  GOTO LBLARTICLELIST  
 ELSE IF @CQUERYID=12  
  GOTO LBLARTICLEINFO  
 ELSE IF @CQUERYID=13  
  GOTO LBLFORMS  
 ELSE IF @CQUERYID=14  
  GOTO LBLARTICLESKUINFO  
 ELSE IF @CQUERYID=15  
  GOTO LBLARTPARA2LIST  
 ELSE IF @CQUERYID=16  
  GOTO LBLARTPARA1LIST  
 ELSE IF @CQUERYID=17  
  GOTO LBLQBF  
 ELSE IF @CQUERYID=18  
  GOTO LBLLOCLIST  
    ELSE IF @CQUERYID=19    
        GOTO LBL19    
    ELSE IF @CQUERYID=20      
  GOTO LBL20   
 ELSE IF @CQUERYID=21      
  GOTO LBL21   
 ELSE IF @CQUERYID=22      
  GOTO LBL22
 ELSE IF @CQUERYID=23
	GOTO LBL23
 ELSE IF @CQUERYID=24
	GOTO LBL24 	    
 ELSE IF @CQUERYID=25
	GOTO LBL25 	    
 ELSE IF @CQUERYID=26
	GOTO LBL26 
 ELSE IF @CQUERYID=28
	GOTO LBL28		    		
 ELSE IF @CQUERYID=29
	GOTO LBL29		    		
ELSE
 GOTO LAST  
 
 LBL29:
 	select TERM_NAME,MEMO_ID from PPC_TERM_CONDITION_MST WHERE XN_TYPE='PO' ORDER BY TERM_NAME
	GOTO LAST

 LBL28:
 	SELECT a.*,b.username ,CONVERT(VARCHAR(50),a.BLOCK_TIME,113) AS BLOCK_TIME_STR
	FROM POM_BLOCK_DETAILS a (NOLOCK)
	JOIN  USERS b (NOLOCK) ON b.user_code =a.BLOCK_USER_CODE
	WHERE PO_ID=@CWHERE
	GOTO LAST
 
  LBL23:
		SELECT CONVERT(BIT,0) AS CHK,A.ORDER_ID,C.AC_NAME AS CUSTOMER_NAME,D.TOTAL_QTY,TOTAL_AMOUNT,
		ORDER_DT,ORDER_NO,( CASE WHEN MEMO_TYPE = 1 THEN 'DIRECT' WHEN MEMO_TYPE = 2 THEN 'PICK LIST' END) AS MEMO_TYPE,REF_NO FROM BUYER_ORDER_MST A(NOLOCK) 
		LEFT OUTER JOIN (SELECT DISTINCT ORDER_ID FROM BUYER_ORDER_DET A(NOLOCK) JOIN 
					(SELECT WOD_ROW_ID,SUM(QUANTITY) AS QUANTITY 
					FROM POD01106(NOLOCK) WHERE ISNULL(WOD_ROW_ID,'') <> '' GROUP BY WOD_ROW_ID  ) B ON A.ROW_ID = B.WOD_ROW_ID
			        JOIN POD01106 D(NOLOCK) ON D.WOD_ROW_ID = B.WOD_ROW_ID
			        JOIN POM01106 C(NOLOCK) ON D.PO_ID = C.PO_ID
			  WHERE A.QUANTITY <= B.QUANTITY AND C.CANCELLED = 0 AND C.MODE = 4 ) B ON A.ORDER_ID = B.ORDER_ID
		JOIN LMV01106 C(NOLOCK) ON A.AC_CODE = C.AC_CODE
		JOIN (SELECT ORDER_ID,SUM(QUANTITY) AS TOTAL_QTY FROM BUYER_ORDER_DET GROUP BY ORDER_ID) D ON A.ORDER_ID = D.ORDER_ID
		WHERE B.ORDER_ID IS NULL AND A.CANCELLED = 0	
		ORDER BY ORDER_NO,ORDER_DT  
	GOTO LAST

LBL24:
		 SELECT CONVERT(BIT,0) AS BCHK,ARTICLE_NO,ARTICLE_NAME,A.ARTICLE_CODE,A.PARA1_CODE,A.PARA2_CODE,AT.ALIAS,AT.MRP,AT.PURCHASE_PRICE,AT.WHOLESALE_PRICE,AT.FIX_MRP,SM.SECTION_NAME,SD.SUB_SECTION_NAME,UM.UOM_TYPE,UM.UOM_NAME,
		 P1.PARA1_NAME,
		 P2.PARA2_NAME,
		 P3.PARA3_NAME,
		 P4.PARA4_NAME,
		 P5.PARA5_NAME,
		 P6.PARA6_NAME,
		 A.QUANTITY-ISNULL(B.QUANTITY,0) AS QUANTITY,A.DISCOUNT_AMOUNT AS ITEM_DISCOUNT_AMOUNT,A.WS_PRICE AS RATE,A.ORDER_ID,A.ROW_ID,GROSS_WSP,A.DISCOUNT_PERCENTAGE,A.REMARKS,A.MANUAL_DISCOUNT 
		 FROM BUYER_ORDER_DET A(NOLOCK)
		 
		 LEFT OUTER JOIN
		 (SELECT WOD_ROW_ID,SUM(QUANTITY) AS QUANTITY FROM POD01106(NOLOCK)  JOIN POM01106(NOLOCK) ON POD01106.PO_ID = POM01106.PO_ID
		  WHERE POM01106.CANCELLED = 0  AND ISNULL(WOD_ROW_ID,'') <> '' GROUP BY WOD_ROW_ID) B ON A.ROW_ID = B.WOD_ROW_ID
		 JOIN BUYER_ORDER_MST C(NOLOCK) ON A.ORDER_ID = C.ORDER_ID
		 JOIN ARTICLE AT(NOLOCK) ON AT.ARTICLE_CODE = A.ARTICLE_CODE
		 JOIN PARA1 P1(NOLOCK) ON P1.PARA1_CODE = A.PARA1_CODE
		 JOIN PARA2 P2(NOLOCK) ON P2.PARA2_CODE = A.PARA2_CODE
		 JOIN PARA3 P3(NOLOCK) ON P3.PARA3_CODE = AT.PARA3_CODE
		 JOIN PARA4 P4(NOLOCK) ON P4.PARA4_CODE = AT.PARA4_CODE
		 JOIN PARA5 P5(NOLOCK) ON P5.PARA5_CODE	= AT.PARA5_CODE
		 JOIN PARA6 P6(NOLOCK) ON P6.PARA6_CODE = AT.PARA6_CODE
		 JOIN SECTIOND SD(NOLOCK) ON SD.SUB_SECTION_CODE = AT.SUB_SECTION_CODE
		 JOIN SECTIONM SM(NOLOCK) ON SM.SECTION_CODE = SD.SECTION_CODE
		 JOIN UOM UM(NOLOCK) ON UM.UOM_CODE = AT.UOM_CODE
		 WHERE (A.QUANTITY-ISNULL(B.QUANTITY,0) > 0 OR  B.WOD_ROW_ID IS NULL) AND C.CANCELLED = 0
		 ORDER BY A.ORDER_ID
GOTO LAST
    
LBLPOLU:  
 EXECUTE SP_NAVIGATE 'quotation_mst',@NNAVMODE,@CWHERE,@CFINYEAR,'PQ_NO','PQ_DT','PQ_ID',@CWHERECLAUSE  
 
 GOTO LAST  
   
LBLMST:  
  
   SELECT  A.*, 0.00 AS TOTAL_QTY, a.terms terms_name,CONVERT(VARCHAR(400),'') TERMS_REMARKS, 
   D.AC_NAME, C.DEPT_NAME,C.DEPT_ID , ISNULL(B.ADDRESS0,'') AS ADDRESS0,    
   ISNULL(B.ADDRESS1,'') AS ADDRESS1, ISNULL(B.ADDRESS2,'') AS ADDRESS2, 
   ISNULL(AREA.AREA_NAME,'') AS AREA_NAME, ISNULL(CITY.CITY,'') AS CITY, ISNULL(area.PINCODE,'') AS PINCODE, 
   ISNULL(state.STATE,'') AS STATE, ISNULL(B.SST_NO,'') AS SST_NO,    
   ISNULL(B.SST_DT,'') AS SST_DT, ISNULL(B.TIN_NO,'') AS TIN_NO, ISNULL(B.TIN_DT,'') AS TIN_DT,
   U.USERNAME,E.USERNAME AS EDT_USERNAME ,  
   (C.ADDRESS1 +' '+ C.ADDRESS2) AS STORE_ADDRESS ,'' AS FORM_NAME,D.ALIAS,
    ISNULL(B.ADDRESS0,'') + ' ' + ISNULL(B.ADDRESS1,'') + ' ' + ISNULL(B.ADDRESS2,'') + ' ' + ISNULL(area.AREA_NAME,'') + ' ' + ISNULL(city.CITY,'') + ' ' + ISNULL(state.STATE,'') AS SUPP_ADDRESS,  
    XN.*  ,B.MP_PERCENTAGE,B.WP_PERCENTAGE,OEM_MST.OEM_NAME,'' AS PQ_FOR_DEPT_NAME,
     0 AS  FREIGHT_GST_AMT,
     0 AS FREIGHT_TOTAL,
     0 AS  OTHER_CHARGES_GST_AMT,
     0 OTHER_CHARGES_TOTAL,'' PO_TYPE,ISNULL(TNC.TERM_NAME,'') AS TERM_NAME
	 ,'' AS SHIPPING_FROM_AC_NAME,'' AS 'SHIPPING_FROM_ADDRESS','' AS SHIPPING_GST_NO,'' AS SHIPPING_FROM_AC_CODE
   FROM quotation_mst  A(NOLOCK)     
   JOIN LM01106 D          (NOLOCK) ON A.AC_CODE = D.AC_CODE  
   	LEFT OUTER JOIN PPC_TERM_CONDITION_MST TNC(NOLOCK) ON TNC.MEMO_ID=A.TERMS_MEMO_ID
   LEFT JOIN LMP01106 B      (NOLOCK) ON A.AC_CODE=B.AC_CODE
   LEFT JOIN AREA           (NOLOCK) ON AREA.AREA_CODE=B.AREA_CODE
   LEFT JOIN CITY          (NOLOCK) ON CITY.CITY_CODE=AREA.CITY_CODE
   LEFT JOIN STATE         (NOLOCK) ON STATE.STATE_CODE=CITY.STATE_CODE
   LEFT JOIN OEM_MST       (NOLOCK) ON A.OEM_CODE=OEM_MST.OEM_CODE
   LEFT OUTER JOIN USERS U(NOLOCK) ON A.USER_CODE = U.USER_CODE     
   LEFT OUTER JOIN USERS E(NOLOCK) ON A.EDT_USER_CODE = E.USER_CODE     
   JOIN LOCATION C(NOLOCK) ON A.location_code = C.DEPT_ID 
   --JOIN LOCATION C1(NOLOCK) ON A.pq_for_dept_id = C1.DEPT_ID 
   LEFT OUTER JOIN XN_APPROVAL_DET XN(NOLOCK) ON XN.XN_ID=A.PQ_ID AND XN.XN_TYPE='XNSPQ'  
   --LEFT OUTER JOIN LMV01106 SHIP (NOLOCK) ON SHIP.AC_CODE = A.SHIPPING_FROM_AC_CODE
   WHERE A.PQ_ID = @CWHERE  
  
    --SELECT * FROM PO_TYPE_MST
    GOTO LAST  
      
LBLDET:  
	
	EXEC SP_QUOTATION_3  @CWHERE   =@CWHERE,  @CFINYEAR  =@CFINYEAR,  @CDEPTID  =@CDEPTID,  
	@NNAVMODE  =@NNAVMODE,  @CWHERECLAUSE =@CWHERECLAUSE,@DPODT =@DPODT
    GOTO LAST    

    GOTO LAST  
      
LBLPARA1:  
 SELECT A.PARA1_CODE, A.PARA1_NAME FROM PARA1 A (NOLOCK)  
 WHERE PARA1_NAME <> '' AND A.INACTIVE = 0 ORDER BY A.PARA1_NAME    
      
    GOTO LAST  
  
LBLPARA2:  
 SELECT A.PARA2_CODE, A.PARA2_NAME, A.PARA2_ORDER,0 AS PURCHASE_PRICE,0 AS WS_PRICE,0 AS MRP FROM PARA2 A(NOLOCK)   
    WHERE A.PARA2_NAME <> '' AND A.INACTIVE = 0 ORDER BY A.PARA2_ORDER  
      
    GOTO LAST  
      
LBLPARA3:  
    
 SELECT A.PARA3_CODE, A.PARA3_NAME FROM PARA3 A(NOLOCK)   
    WHERE A.PARA3_NAME <> '' AND A.INACTIVE = 0 ORDER BY A.PARA3_NAME  
      
    GOTO LAST  
  
LBLPARA4:  
    
 SELECT A.PARA4_CODE, A.PARA4_NAME FROM PARA4 A(NOLOCK)   
    WHERE A.PARA4_NAME <> '' AND A.INACTIVE = 0 ORDER BY A.PARA4_NAME  
      
    GOTO LAST  
  
LBLPARA5:  
    
 SELECT A.PARA5_CODE, A.PARA5_NAME FROM PARA5 A(NOLOCK)   
    WHERE A.PARA5_NAME <> '' AND A.INACTIVE = 0 ORDER BY A.PARA5_NAME  
      
    GOTO LAST  
  
LBLPARA6:  
    
 SELECT A.PARA6_CODE, A.PARA6_NAME FROM PARA6 A(NOLOCK)   
    WHERE A.PARA6_NAME <> '' AND A.INACTIVE = 0 ORDER BY A.PARA6_NAME  
      
    GOTO LAST  
      
LBLSUPPLIERS: 

	SET  @cHEAD_CODE =  DBO.FN_ACT_TRAVTREE (@CWHERE ) ----ADD VARIABLE BY GAURI ON 17/4/2019
    
 SET @CCMD = N'SELECT  A.ALIAS,A.AC_CODE, A.AC_NAME, ISNULL(A.CREDIT_DAYS, 0) AS CREDIT_DAYS,         
    ISNULL(A.DISCOUNT_PERCENTAGE, 0) AS DISCOUNT_PERCENTAGE,A.CITY,A.AREA_NAME,A.STATE,A.PINCODE,  
    A.ADDRESS0,A.ADDRESS1,A.ADDRESS2, A.ADDRESS0 + '' '' +   
    A.ADDRESS1 + '' '' + A.ADDRESS2 + '' '' + A.AREA_NAME + '' '' + A.CITY + '' '' +         
    A.STATE AS SUPP_ADDRESS, AC_NAME AS REPCOLNAME         
    FROM LMV01106 A(NOLOCK)         
    WHERE (  HEAD_CODE IN ('+@cHEAD_CODE+')    ----REPLACE VARIABLE FROM FUNCTION BY GAURI ON 17/4/2019 
    OR ALLOW_CREDITOR_DEBTOR = 1 )         
    AND INACTIVE = 0 AND A.AC_NAME <> ''''       
  
    UNION ALL        
  
    SELECT A.ALIAS,A.AC_CODE, ALIAS, ISNULL(A.CREDIT_DAYS, 0) AS CREDIT_DAYS,         
    ISNULL(A.DISCOUNT_PERCENTAGE, 0) AS DISCOUNT_PERCENTAGE, A.CITY,A.AREA_NAME,A.STATE,  
    A.PINCODE,A.ADDRESS0,A.ADDRESS1,A.ADDRESS2, A.ADDRESS0 + '' '' +         
    A.ADDRESS1 + '' '' + A.ADDRESS2 + '' '' + A.AREA_NAME + '' '' + A.CITY + '' '' +   
    A.STATE AS SUPP_ADDRESS, AC_NAME AS REPCOLNAME          
    FROM LMV01106 A(NOLOCK)         
    WHERE ( HEAD_CODE IN ('+@cHEAD_CODE+')    ----REPLACE VARIABLE FROM FUNCTION BY GAURI ON 17/4/2019 
    OR ALLOW_CREDITOR_DEBTOR = 1 )         
    AND INACTIVE = 0 AND A.ALIAS <> ''''        
    ORDER BY A.AC_NAME '  
    --AND A.HEAD_CODE = ''' + @CWHERE + '''    
      
    EXEC SP_EXECUTESQL @CCMD  
          
    GOTO LAST  
      
LBLARTICLELIST:  
  
 SELECT A.ARTICLE_CODE, A.ARTICLE_NAME, A.ARTICLE_NO,     
    B.SUB_SECTION_NAME, C.SECTION_NAME,A.ALIAS AS ARTICLE_ALIAS FROM ARTICLE A (NOLOCK)    
    JOIN SECTIOND B(NOLOCK) ON A.SUB_SECTION_CODE = B.SUB_SECTION_CODE    
    JOIN SECTIONM C(NOLOCK) ON B.SECTION_CODE = C.SECTION_CODE    
    WHERE A.ARTICLE_NO <> ''  AND A.INACTIVE = 0 AND A.CODING_SCHEME <> 1  
   
 UNION ALL   
  
 SELECT A.ARTICLE_CODE, A.ARTICLE_NAME, A1.PRODUCT_CODE AS [ARTICLE_NO],     
 B.SUB_SECTION_NAME, C.SECTION_NAME,A.ALIAS AS ARTICLE_ALIAS   
 FROM SKU A1(NOLOCK)     
 JOIN ARTICLE A(NOLOCK)   ON A.ARTICLE_CODE=A1.ARTICLE_CODE  
 JOIN SECTIOND B(NOLOCK) ON A.SUB_SECTION_CODE = B.SUB_SECTION_CODE    
 JOIN SECTIONM C(NOLOCK) ON B.SECTION_CODE = C.SECTION_CODE    
 WHERE A.ARTICLE_NO <> '' AND A.INACTIVE=0 AND A1.BARCODE_CODING_SCHEME = 1  
  
  UNION ALL     
     
  SELECT A.ARTICLE_CODE, A.ARTICLE_NAME, EAN.EAN AS [ARTICLE_NO],       
  B.SUB_SECTION_NAME, C.SECTION_NAME,A.ALIAS AS ARTICLE_ALIAS     
  FROM EAN_SYNC EAN   
  JOIN SKU A1(NOLOCK)     ON EAN.PRODUCT_CODE=A1.PRODUCT_CODE  
  JOIN ARTICLE A (NOLOCK)  ON A.ARTICLE_CODE=A1.ARTICLE_CODE    
  JOIN SECTIOND B(NOLOCK) ON A.SUB_SECTION_CODE = B.SUB_SECTION_CODE      
  JOIN SECTIONM C(NOLOCK) ON B.SECTION_CODE = C.SECTION_CODE      
  WHERE A.ARTICLE_NO <> '' AND A.INACTIVE=0 AND A1.BARCODE_CODING_SCHEME = 1  
   
 ORDER BY A.ARTICLE_NO  
          
    GOTO LAST  
      
LBLARTICLEINFO:  
 SELECT A.ARTICLE_CODE, A.ARTICLE_DESC, A.ARTICLE_NAME, A.ARTICLE_NO, A.CODING_SCHEME,  
 A.PURCHASE_PRICE, A.MRP, A.WHOLESALE_PRICE,A.WSP_PERCENTAGE , A.CREATED_ON, A.PARA1_SET, A.PARA2_SET, B.UOM_CODE,   
 B.UOM_NAME, B.UOM_TYPE, A.MP_PERCENTAGE ,A.FIX_MRP,'' AS PRODUCT_NAME,  
 ISNULL(A.DT_CREATED,'') AS [ART_DT_CREATED],'' AS [PARA3_DT_CREATED], '' AS [SKU_DT_CREATED],
 A.ALIAS AS ARTICLE_ALIAS    
 FROM ARTICLE A(NOLOCK)   
 JOIN UOM B(NOLOCK) ON A.UOM_CODE = B.UOM_CODE   
 WHERE A.ARTICLE_CODE=@CWHERE  
   
    GOTO LAST  
  
LBLFORMS:  
  
 SELECT FORM_ID, FORM_NAME, TAX_PERCENTAGE FROM FORM(NOLOCK)   
 WHERE FORM_NAME <> '' AND INACTIVE = 0  ORDER BY FORM_NAME  
   
 GOTO LAST  
  
LBLARTICLESKUINFO:  
  
 SELECT TOP 1 A.PARA1_CODE, A.PARA2_CODE, A.PARA3_CODE, A.PARA4_CODE, A.PARA5_CODE,   
    A.PARA6_CODE, P1.PARA1_NAME, P2.PARA2_NAME, P3.PARA3_NAME, P4.PARA4_NAME,   
    P5.PARA5_NAME, P6.PARA6_NAME, ART.DT_CREATED AS [ART_DT_CREATED],   
    P3.DT_CREATED AS [PARA3_DT_CREATED],ISNULL(A.DT_CREATED,'') AS [SKU_DT_CREATED],A.FIX_MRP,A.PRODUCT_NAME,
    ART.ALIAS AS ARTICLE_ALIAS  
    FROM SKU A (NOLOCK)  
    JOIN ARTICLE (NOLOCK) ART ON ART.ARTICLE_CODE= A.ARTICLE_CODE   
    JOIN PARA1 (NOLOCK) P1 ON A.PARA1_CODE = P1.PARA1_CODE   
    JOIN PARA2 (NOLOCK) P2 ON A.PARA2_CODE = P2.PARA2_CODE   
    JOIN PARA3 (NOLOCK) P3 ON A.PARA3_CODE = P3.PARA3_CODE   
    JOIN PARA4 (NOLOCK) P4 ON A.PARA4_CODE = P4.PARA4_CODE   
    JOIN PARA5 (NOLOCK) P5 ON A.PARA5_CODE = P5.PARA5_CODE   
    JOIN PARA6 (NOLOCK) P6 ON A.PARA6_CODE = P6.PARA6_CODE   
    WHERE A.ARTICLE_CODE = @CWHERE  
      
    GOTO LAST  
     
LBLARTPARA2LIST:  
 DECLARE @PARA NUMERIC (18)  
   
 SELECT @PARA = COUNT(A.PARA2_CODE)  
 FROM PARA2 A(NOLOCK)    
 JOIN ART_DET (NOLOCK) B ON A.PARA2_CODE = B.PARA2_CODE    
 WHERE B.ARTICLE_CODE = @CWHERE    
   
 IF @PARA > 0   
 BEGIN      
  SELECT B.ARTICLE_CODE,A.PARA2_CODE, A.PARA2_NAME, A.PARA2_ORDER,B.PURCHASE_PRICE,B.WS_PRICE,B.MRP   
  ,B.CENTER_POINT    
  FROM PARA2 A(NOLOCK)    
  JOIN ART_DET (NOLOCK) B ON A.PARA2_CODE = B.PARA2_CODE    
  WHERE B.ARTICLE_CODE = @CWHERE  ORDER BY A.PARA2_ORDER  
 END  
 ELSE  
 BEGIN  
  SELECT @CWHERE AS ARTICLE_CODE, A.PARA2_CODE, A.PARA2_NAME, A.PARA2_ORDER,    
  ISNULL((SELECT PURCHASE_PRICE FROM ARTICLE (NOLOCK) WHERE ARTICLE_CODE = @CWHERE),0)  AS  PURCHASE_PRICE,  
  ISNULL((SELECT WHOLESALE_PRICE FROM ARTICLE (NOLOCK) WHERE ARTICLE_CODE = @CWHERE),0) AS WS_PRICE,  
  ISNULL((SELECT MRP FROM ARTICLE (NOLOCK) WHERE ARTICLE_CODE = @CWHERE),0) AS MRP    
  ,CONVERT(NUMERIC(14,3),0) AS RATE_DIFFERENCE,CONVERT(BIT,0) AS CENTER_POINT   
  FROM PARA2 A    
  WHERE A.PARA2_CODE = '0000000'   
  ORDER BY A.PARA2_ORDER  
    END  
      
 GOTO LAST  
  
LBLARTPARA1LIST:  
 SELECT A.ARTICLE_CODE, A.PARA1_CODE, B.PARA1_NAME FROM ART_PARA1 A(NOLOCK)   
    JOIN PARA1 B(NOLOCK) ON A.PARA1_CODE = B.PARA1_CODE  
    WHERE A.ARTICLE_CODE = @CWHERE  
    ORDER BY B.PARA1_NAME  
      
 GOTO LAST  
  
  
LBLQBF:  
  
 SET @CCMD=N'SELECT DISTINCT PO_ID,MST_PO_NO AS PO_NO,MST_XN_DT AS PO_DT,PO_ID AS XN_ID,MST_PO_NO AS XN_NO ,MST_XN_DT AS XN_DT   
    FROM VW_PO_QBF  '+@CWHERE  
 PRINT @CCMD  
 EXEC SP_EXECUTESQL @CCMD  
      
 GOTO LAST  
  
LBLLOCLIST:  
  
 SELECT * FROM LOCATION(NOLOCK) WHERE INACTIVE=0 AND LOC_TYPE = 1 AND DEPT_ID<>@CWHERE    
   
    GOTO LAST     
      
 LBL19:     
     
   --SELECT  TOP 1 ISNULL(B.MRR_ID,'') AS MRR_ID,A.ROW_ID,B.PO_ROW_ID FROM POD01106 A(NOLOCK)  
   --JOIN PID01106 B(NOLOCK) ON B.PO_ROW_ID=A.ROW_ID  
   --WHERE A.PO_ID=@CWHERE  
   
    SELECT  TOP 1 ISNULL(B.PO_ID,'') AS MRR_ID,A.ROW_ID,'' PO_ROW_ID FROM quotation_det A(NOLOCK)  
   JOIN POD01106  B(NOLOCK) ON 1=2--B.PQ_ROW_ID=A.ROW_ID  
   WHERE A.PQ_ID=@CWHERE  


   GOTO LAST       
     
LBL20:  
 SET @CCMD= N'SELECT DISTINCT A.PQ_NO,A.PQ_DT,
    F.SECTION_NAME,E.SUB_SECTION_NAME,D.ARTICLE_NO,D.ARTICLE_NAME,  
    P1.PARA1_NAME,P2.PARA2_NAME,P3.PARA3_NAME,  
    P4.PARA4_NAME,P5.PARA5_NAME,P6.PARA6_NAME,D.CODING_SCHEME,  
    B.QUANTITY,D.ALIAS AS ARTICLE_ALIAS,B.ROW_ID,
    SP2.SIZEINCHES,SP2.SIZECMS,SP2.REMARKS,
    LM.AC_NAME,
    REPLACE(ISNULL(LM.ADDRESS0,''''),'','','':'') +'' ''+REPLACE(ISNULL(LM.ADDRESS1,''''),'','','':'') +'' ''+
    REPLACE(ISNULL(LM.ADDRESS2,''''),'','','':'') AS ADDRESS,
    REPLACE(LM.AREA_NAME,'','','':'') AS AREA_NAME,
    REPLACE(LM.CITY,'','','':'') AS CITY,
    REPLACE(LM.STATE,'','','':'') AS STATE,
    REPLACE(LM.PINCODE,'','','':'') AS PINCODE
    ,AT1.attr1_key_name,AT2.attr2_key_name,AT3.attr3_key_name,AT4.attr4_key_name,AT5.attr5_key_name,AT6.attr6_key_name,    
	AT7.attr7_key_name,AT8.attr8_key_name,AT9.attr9_key_name,AT10.attr10_key_name,AT11.attr11_key_name,AT12.attr12_key_name,    
	AT13.attr13_key_name,AT14.attr14_key_name,AT15.attr15_key_name,AT16.attr16_key_name,AT17.attr17_key_name,AT18.attr18_key_name,    
	AT19.attr19_key_name,AT20.attr20_key_name,AT21.attr21_key_name,AT22.attr22_key_name,AT23.attr23_key_name,AT24.attr24_key_name,    
	AT25.attr25_key_name 
    FROM QUOTATION_MST  A(NOLOCK)  
    JOIN QUOTATION_DET  B(NOLOCK) ON B.PQ_ID=A.PQ_ID   
    JOIN ARTICLE D(NOLOCK) ON D.ARTICLE_CODE=B.ARTICLE_CODE   
    JOIN SECTIOND E(NOLOCK) ON E.SUB_SECTION_CODE=D.SUB_SECTION_CODE   
    JOIN SECTIONM F(NOLOCK) ON F.SECTION_CODE=E.SECTION_CODE   
    JOIN LMV01106 LM(NOLOCK) ON LM.AC_CODE=A.AC_CODE
    LEFT OUTER JOIN PARA1 P1(NOLOCK) ON P1.PARA1_CODE=B.PARA1_CODE   
    LEFT OUTER JOIN PARA2 P2(NOLOCK) ON P2.PARA2_CODE=B.PARA2_CODE   
    LEFT OUTER JOIN PARA3 P3(NOLOCK) ON P3.PARA3_CODE=B.PARA3_CODE   
    LEFT OUTER JOIN PARA4 P4(NOLOCK) ON P4.PARA4_CODE=B.PARA4_CODE   
    LEFT OUTER JOIN PARA5 P5(NOLOCK) ON P5.PARA5_CODE=B.PARA5_CODE   
    LEFT OUTER JOIN PARA6 P6(NOLOCK) ON P6.PARA6_CODE=B.PARA6_CODE   
    LEFT OUTER JOIN article_fix_attr ATTR  (NOLOCK) ON D.article_code = ATTR.ARTICLE_CODE     
	LEFT OUTER JOIN attr1_mst at1 (NOLOCK) ON at1.attr1_key_code=ATTR.attr1_key_code    
	LEFT OUTER JOIN attr2_mst at2 (NOLOCK) ON at2.attr2_key_code=ATTR.attr2_key_code    
	LEFT OUTER JOIN attr3_mst at3 (NOLOCK) ON at3.attr3_key_code=ATTR.attr3_key_code    
	LEFT OUTER JOIN attr4_mst at4 (NOLOCK) ON at4.attr4_key_code=ATTR.attr4_key_code    
	LEFT OUTER JOIN attr5_mst at5 (NOLOCK) ON at5.attr5_key_code=ATTR.attr5_key_code    
	LEFT OUTER JOIN attr6_mst at6 (NOLOCK) ON at6.attr6_key_code=ATTR.attr6_key_code    
	LEFT OUTER JOIN attr7_mst at7 (NOLOCK) ON at7.attr7_key_code=ATTR.attr7_key_code    
	LEFT OUTER JOIN attr8_mst at8 (NOLOCK) ON at8.attr8_key_code=ATTR.attr8_key_code    
	LEFT OUTER JOIN attr9_mst at9 (NOLOCK) ON at9.attr9_key_code=ATTR.attr9_key_code    
	LEFT OUTER JOIN attr10_mst at10 (NOLOCK) ON at10.attr10_key_code=ATTR.attr10_key_code    
	LEFT OUTER JOIN attr11_mst at11 (NOLOCK) ON at11.attr11_key_code=ATTR.attr11_key_code    
	LEFT OUTER JOIN attr12_mst at12 (NOLOCK) ON at12.attr12_key_code=ATTR.attr12_key_code    
	LEFT OUTER JOIN attr13_mst at13 (NOLOCK) ON at13.attr13_key_code=ATTR.attr13_key_code    
	LEFT OUTER JOIN attr14_mst at14 (NOLOCK) ON at14.attr14_key_code=ATTR.attr14_key_code    
	LEFT OUTER JOIN attr15_mst at15 (NOLOCK) ON at15.attr15_key_code=ATTR.attr15_key_code    
	LEFT OUTER JOIN attr16_mst at16 (NOLOCK) ON at16.attr16_key_code=ATTR.attr16_key_code    
	LEFT OUTER JOIN attr17_mst at17 (NOLOCK) ON at17.attr17_key_code=ATTR.attr17_key_code    
	LEFT OUTER JOIN attr18_mst at18 (NOLOCK) ON at18.attr18_key_code=ATTR.attr18_key_code    
	LEFT OUTER JOIN attr19_mst at19 (NOLOCK) ON at19.attr19_key_code=ATTR.attr19_key_code    
	LEFT OUTER JOIN attr20_mst at20 (NOLOCK) ON at20.attr20_key_code=ATTR.attr20_key_code    
	LEFT OUTER JOIN attr21_mst at21 (NOLOCK) ON at21.attr21_key_code=ATTR.attr21_key_code    
	LEFT OUTER JOIN attr22_mst at22 (NOLOCK) ON at22.attr22_key_code=ATTR.attr22_key_code    
	LEFT OUTER JOIN attr23_mst at23 (NOLOCK) ON at23.attr23_key_code=ATTR.attr23_key_code    
	LEFT OUTER JOIN attr24_mst at24 (NOLOCK) ON at24.attr24_key_code=ATTR.attr24_key_code    
	LEFT OUTER JOIN attr25_mst at25(NOLOCK) ON at25.attr25_key_code=ATTR.attr25_key_code
    LEFT OUTER JOIN SECTIONDPARA2 SP2(NOLOCK) ON SP2.SUB_SECTION_CODE=E.SUB_SECTION_CODE AND B.PARA2_CODE=SP2.PARA2_CODE
    WHERE B.PQ_ID = ''' + @CWHERE + ''''    
 PRINT @CCMD  
 EXEC SP_EXECUTESQL @CCMD  
 GOTO LAST     
   
LBL21:  
 IF @CWHERECLAUSE <> ''  
 BEGIN    
  SELECT CAST(1 AS BIT) AS CHK,M.ORDER_ID ,M.ORDER_NO,M.REF_NO,  
  M.ORDER_DT ,M.TOTAL_AMOUNT,SUM(D.QUANTITY) AS TOTAL_QTY  
  ,(CASE WHEN B.AC_NAME = '' THEN (CUST.CUSTOMER_FNAME +' '+ CUST.CUSTOMER_LNAME) ELSE B.AC_NAME END) AS CUSTOMER_NAME  
 
  ,M.DISCOUNT_AMOUNT  
  ,M.DISCOUNT_PERCENTAGE   ,ISNULL(M.URGENT,0) AS URGENT
  FROM WSL_ORDER_MST M  (NOLOCK)   
  JOIN WSL_ORDER_DET D  (NOLOCK) ON M.ORDER_ID = D.ORDER_ID   
  JOIN LMV01106 B (NOLOCK)  ON M.AC_CODE = B.AC_CODE  
  JOIN custdym CUST (NOLOCK) ON M.CUSTOMER_CODE = CUST.CUSTOMER_CODE  
  JOIN POD01106 BO (NOLOCK) ON D.PRODUCT_CODE = BO.PRODUCT_CODE 
  JOIN POM01106 POM (NOLOCK) ON BO.PO_ID = POM.PO_ID   
  WHERE POM.CANCELLED= 0 AND M.CANCELLED = 0 AND ISNULL(D.CANCELLED,0)=0 AND M.APPROVED=1 
  AND D.ORDER_TYPE <> 1 AND BO.PO_ID = @CWHERE   
  GROUP BY M.ORDER_ID,M.ORDER_NO,M.REF_NO,M.ORDER_DT  
  ,M.TOTAL_AMOUNT,B.AC_NAME,CUST.CUSTOMER_FNAME,CUST.CUSTOMER_LNAME  
  ,M.DISCOUNT_PERCENTAGE,M.DISCOUNT_AMOUNT  ,ISNULL(M.URGENT,0)
    
 END  
 ELSE  
 BEGIN  
 IF @NNAVMODE = 2  
 BEGIN  
  SELECT CAST(1 AS BIT) AS CHK,M.ORDER_ID ,M.ORDER_NO,M.REF_NO,  
  M.ORDER_DT ,M.TOTAL_AMOUNT,SUM(D.QUANTITY) AS TOTAL_QTY  
  ,(CASE WHEN B.AC_NAME = '' THEN (CUST.CUSTOMER_FNAME +' '+ CUST.CUSTOMER_LNAME) ELSE B.AC_NAME END) AS CUSTOMER_NAME  

  ,M.DISCOUNT_AMOUNT  
  ,M.DISCOUNT_PERCENTAGE    ,ISNULL(M.URGENT,0) AS URGENT
  FROM WSL_ORDER_MST M  (NOLOCK)   
  JOIN WSL_ORDER_DET D  (NOLOCK) ON M.ORDER_ID = D.ORDER_ID   
  JOIN LMV01106 B (NOLOCK)  ON M.AC_CODE = B.AC_CODE  
  JOIN custdym CUST (NOLOCK) ON M.CUSTOMER_CODE = CUST.CUSTOMER_CODE  
  JOIN POD01106 BO (NOLOCK) ON D.PRODUCT_CODE = BO.PRODUCT_CODE
  JOIN POM01106 POM (NOLOCK) ON BO.PO_ID = POM.PO_ID  
  WHERE POM.CANCELLED=0 AND M.CANCELLED = 0 AND ISNULL(D.CANCELLED,0)=0 AND M.APPROVED=1 AND D.ORDER_TYPE <> 1 AND BO.PO_ID = @CWHERE   
  GROUP BY M.ORDER_ID,M.ORDER_NO,M.REF_NO,M.ORDER_DT  
  ,M.TOTAL_AMOUNT,B.AC_NAME,CUST.CUSTOMER_FNAME,CUST.CUSTOMER_LNAME  
  ,M.DISCOUNT_PERCENTAGE,M.DISCOUNT_AMOUNT  ,ISNULL(M.URGENT,0)
    
  UNION ALL  
    
  SELECT CAST((CASE WHEN ISNULL(BO.PO_ID,'') = '' THEN 0 ELSE 1 END) AS BIT) AS CHK,M.ORDER_ID ,M.ORDER_NO,M.REF_NO,  
  M.ORDER_DT ,M.TOTAL_AMOUNT,SUM(D.QUANTITY) AS TOTAL_QTY  
  ,(CASE WHEN B.AC_NAME = '' THEN (CUST.CUSTOMER_FNAME +' '+ CUST.CUSTOMER_LNAME) ELSE B.AC_NAME END) AS CUSTOMER_NAME   
 
  ,M.DISCOUNT_AMOUNT  
  ,M.DISCOUNT_PERCENTAGE   ,ISNULL(M.URGENT,0) AS URGENT 
  FROM WSL_ORDER_MST M  (NOLOCK)   
  JOIN WSL_ORDER_DET D  (NOLOCK) ON M.ORDER_ID = D.ORDER_ID   
  JOIN LMV01106 B (NOLOCK)  ON M.AC_CODE = B.AC_CODE  
  JOIN custdym CUST (NOLOCK) ON M.CUSTOMER_CODE = CUST.CUSTOMER_CODE  
 -- LEFT OUTER JOIN POD01106 BO (NOLOCK) ON D.ROW_ID = BO.WOD_ROW_ID 
  --LEFT OUTER JOIN POM01106 POM (NOLOCK) ON BO.PO_ID = POM.PO_ID   AND POM.CANCELLED=0 
  
   LEFT OUTER JOIN 
  (
	   SELECT PRODUCT_CODE,BO.PO_ID FROM  POD01106 BO (NOLOCK)   
	   LEFT OUTER JOIN POM01106 POM (NOLOCK) ON BO.PO_ID = POM.PO_ID WHERE
	   POM.CANCELLED= 0
  )  BO  ON ISNULL(D.PRODUCT_CODE,'') = ISNULL(BO.PRODUCT_CODE,'') 
    
  WHERE   M.CANCELLED = 0 AND ISNULL(D.CANCELLED,0)=0 AND  M.APPROVED=1 AND D.ORDER_TYPE <> 1 AND BO.PRODUCT_CODE IS NULL
		  AND ISNULL(D.PRODUCT_CODE,'')<>''
  GROUP BY M.ORDER_ID,M.ORDER_NO,M.REF_NO,M.ORDER_DT  
  ,M.TOTAL_AMOUNT,B.AC_NAME,CUST.CUSTOMER_FNAME,CUST.CUSTOMER_LNAME,BO.PO_ID  
  ,M.DISCOUNT_PERCENTAGE,M.DISCOUNT_AMOUNT   ,ISNULL(M.URGENT,0)
 END  
 ELSE  
 BEGIN  
  SELECT CAST(0 AS BIT) AS CHK,M.ORDER_ID ,M.ORDER_NO,M.REF_NO,  
  M.ORDER_DT ,M.TOTAL_AMOUNT,SUM(D.QUANTITY) AS TOTAL_QTY  
  ,(CASE WHEN B.AC_NAME = '' THEN (CUST.CUSTOMER_FNAME +' '+ CUST.CUSTOMER_LNAME) ELSE B.AC_NAME END) AS CUSTOMER_NAME  
  --CHANGE NEW..  
  ,M.DISCOUNT_AMOUNT  
  ,M.DISCOUNT_PERCENTAGE  ,ISNULL(M.URGENT,0) AS URGENT  
  FROM WSL_ORDER_MST M  (NOLOCK)   
  JOIN WSL_ORDER_DET D  (NOLOCK) ON M.ORDER_ID = D.ORDER_ID   
  JOIN LMV01106 B (NOLOCK)  ON M.AC_CODE = B.AC_CODE  
  JOIN custdym CUST (NOLOCK) ON M.CUSTOMER_CODE = CUST.CUSTOMER_CODE  
 -- LEFT OUTER JOIN POD01106 BO (NOLOCK) ON D.ROW_ID = BO.WOD_ROW_ID 
 --  LEFT OUTER JOIN POM01106 POM (NOLOCK) ON BO.PO_ID = POM.PO_ID AND POM.CANCELLED=0
 
  LEFT OUTER JOIN 
  (
   SELECT PRODUCT_CODE FROM  POD01106 BO (NOLOCK)   
   LEFT OUTER JOIN POM01106 POM (NOLOCK) ON BO.PO_ID = POM.PO_ID WHERE
   POM.CANCELLED= 0
  )  BO  ON ISNULL(D.PRODUCT_CODE,'') = ISNULL(BO.PRODUCT_CODE,'') 
  WHERE  M.CANCELLED = 0 AND M.APPROVED=1 AND ISNULL(D.CANCELLED,0)=0 AND ISNULL(D.PRODUCT_CODE,'')<>'' AND D.ORDER_TYPE <> 1 AND BO.PRODUCT_CODE IS NULL  
  GROUP BY M.ORDER_ID,M.ORDER_NO,M.REF_NO,M.ORDER_DT  
  ,M.TOTAL_AMOUNT,B.AC_NAME,CUST.CUSTOMER_FNAME,CUST.CUSTOMER_LNAME  
  ,M.DISCOUNT_PERCENTAGE,M.DISCOUNT_AMOUNT   ,ISNULL(M.URGENT,0) 
 END  
 END  
    
     
GOTO LAST  

  
LBL22:  
IF @CWHERECLAUSE <> ''  
BEGIN  
	 SELECT B.ARTICLE_NAME,A.*,B.PURCHASE_PRICE  
	 ,(A.GROSS_WSP) AS MRP,(A.RFNET/A.QUANTITY) AS RATE,  
	  B.ARTICLE_NO,C.PARA1_NAME,D.PARA2_NAME,E.PARA3_NAME, F.PARA4_NAME, G.PARA5_NAME, H.PARA6_NAME,      
	  '' AS JRD_ROW_ID, '' AS JID_ROW_ID, '' AS JOD_ROW_ID,D.PARA2_ORDER,C.PARA1_ORDER ,    
	  A.RFNET AS AMOUNT,B.UOM_CODE,I.UOM_NAME,I.UOM_TYPE,B.DT_CREATED    
	  ,B.CODING_SCHEME,B.PARA1_SET,B.PARA2_SET,  
	  '0000000' AS FORM_ID,  
	  CONVERT(NUMERIC(14,2), 0) AS ITEM_TAX_PERCENTAGE,  
	  CONVERT(NUMERIC(14,2), 0) AS ITEM_TAX_AMOUNT,  
	  --(A.DISCOUNT_AMOUNT/A.QUANTITY) AS ITEM_DISCOUNT_AMOUNT,    
	  A.DISCOUNT_PERCENTAGE AS ITEM_DISCOUNT_PERCENTAGE,  
	  CONVERT(NUMERIC(14,2), 0) AS ITEM_DISCOUNT_AMOUNT,  
	  --CONVERT(NUMERIC(14,2), 0) AS ITEM_DISCOUNT_PERCENTAGE,  
	  B.WHOLESALE_PRICE, 
	  B.PURCHASE_PRICE, 
	  B.GROSS_PURCHASE_PRICE, 
	  B.DISCOUNT_PERCENTAGE AS ART_DISCOUNT_PERCENTAGE,
	  B.DISCOUNT_AMOUNT AS ART_DISCOUNT_AMOUNT,
	  CAST(0 AS BIT) AS MANUAL_MRP,  
	  CAST(0 AS BIT) AS MANUAL_DISCOUNT,  
	  CAST(0 AS BIT) AS MANUAL_WSP,  
	  A.QUANTITY AS INVOICE_QUANTITY,  
	  CONVERT(NUMERIC(14,2), 0) AS SCHEME_QUANTITY,
	  B.ALIAS AS ARTICLE_ALIAS       
		FROM WSL_ORDER_DET A  (NOLOCK)        
		JOIN ARTICLE B (NOLOCK)  ON A.ARTICLE_CODE = B.ARTICLE_CODE        
		JOIN PARA1 C (NOLOCK)  ON A.PARA1_CODE = C.PARA1_CODE        
		JOIN PARA2 D (NOLOCK)  ON A.PARA2_CODE = D.PARA2_CODE         
		JOIN PARA3 E (NOLOCK)  ON A.PARA3_CODE = E.PARA3_CODE         
		JOIN PARA4 F (NOLOCK)  ON A.PARA4_CODE = F.PARA4_CODE         
		JOIN PARA5 G (NOLOCK)  ON A.PARA5_CODE = G.PARA5_CODE         
		JOIN PARA6 H (NOLOCK) ON A.PARA6_CODE = H.PARA6_CODE        
		JOIN WSL_ORDER_MST R ON R.ORDER_ID= A.ORDER_ID   
	   JOIN UOM I       (NOLOCK) ON B.UOM_CODE = I.UOM_CODE     
	   JOIN SECTIOND M  (NOLOCK) ON B.SUB_SECTION_CODE = M.SUB_SECTION_CODE   
	   JOIN SECTIONM N  (NOLOCK) ON M.SECTION_CODE = N.SECTION_CODE   
	   JOIN POD01106 BO (NOLOCK) ON A.PRODUCT_CODE = BO.PRODUCT_CODE
	   JOIN POM01106 POM (NOLOCK) ON BO.PO_ID = POM.PO_ID 
	   WHERE POM.CANCELLED=0 AND ISNULL(A.CANCELLED,0)=0 AND BO.PO_ID = @CWHERE  
	   ORDER BY A.PRODUCT_CODE,C.PARA1_NAME, D.PARA2_ORDER , B.ARTICLE_NO,  D.PARA2_NAME    
 END  
 ELSE  
 BEGIN  
	  IF @NNAVMODE = 2  
	  BEGIN  
		   SELECT  B.ARTICLE_NAME,A.*,0 AS PURCHASE_PRICE  
		   ,A.GROSS_WSP AS MRP,(A.RFNET/A.QUANTITY) AS RATE,  
		   B.ARTICLE_NO,C.PARA1_NAME,D.PARA2_NAME,E.PARA3_NAME  
		   , F.PARA4_NAME, G.PARA5_NAME, H.PARA6_NAME,      
		   '' AS JRD_ROW_ID, '' AS JID_ROW_ID, '' AS JOD_ROW_ID  
		   ,D.PARA2_ORDER,C.PARA1_ORDER ,    
		   A.RFNET AS AMOUNT,B.UOM_CODE,I.UOM_NAME,I.UOM_TYPE,B.DT_CREATED    
		   ,B.CODING_SCHEME,B.PARA1_SET,B.PARA2_SET,  
		   '0000000' AS FORM_ID,  
		   CONVERT(NUMERIC(14,2), 0) AS ITEM_TAX_PERCENTAGE,  
		   CONVERT(NUMERIC(14,2), 0) AS ITEM_TAX_AMOUNT,  
		     
		     
		     
		   --(A.DISCOUNT_AMOUNT/A.QUANTITY) AS ITEM_DISCOUNT_AMOUNT,    
			 A.DISCOUNT_PERCENTAGE AS ITEM_DISCOUNT_PERCENTAGE,  
			   CONVERT(NUMERIC(14,2), 0) AS ITEM_DISCOUNT_AMOUNT,  
			  --CONVERT(NUMERIC(14,2), 0) AS ITEM_DISCOUNT_PERCENTAGE,  
		  B.WHOLESALE_PRICE, 
		  B.PURCHASE_PRICE, 
		  B.GROSS_PURCHASE_PRICE, 
		  B.DISCOUNT_PERCENTAGE AS ART_DISCOUNT_PERCENTAGE,
		  B.DISCOUNT_AMOUNT AS ART_DISCOUNT_AMOUNT,
		   CAST(0 AS BIT) AS MANUAL_MRP,  
		   CAST(0 AS BIT) AS MANUAL_DISCOUNT,  
		   CAST(0 AS BIT) AS MANUAL_WSP,  
		   A.QUANTITY AS INVOICE_QUANTITY,  
		   CONVERT(NUMERIC(14,2), 0) AS SCHEME_QUANTITY,
		   B.ALIAS AS ARTICLE_ALIAS       
		   FROM WSL_ORDER_DET A  (NOLOCK)        
		   JOIN ARTICLE B (NOLOCK)  ON A.ARTICLE_CODE = B.ARTICLE_CODE        
		   JOIN PARA1 C (NOLOCK)  ON A.PARA1_CODE = C.PARA1_CODE        
		   JOIN PARA2 D (NOLOCK)  ON A.PARA2_CODE = D.PARA2_CODE         
		   JOIN PARA3 E (NOLOCK)  ON A.PARA3_CODE = E.PARA3_CODE         
		   JOIN PARA4 F (NOLOCK)  ON A.PARA4_CODE = F.PARA4_CODE         
		   JOIN PARA5 G (NOLOCK)  ON A.PARA5_CODE = G.PARA5_CODE         
		   JOIN PARA6 H (NOLOCK) ON A.PARA6_CODE = H.PARA6_CODE        
		   JOIN WSL_ORDER_MST R ON R.ORDER_ID= A.ORDER_ID   
		   JOIN UOM I       (NOLOCK) ON B.UOM_CODE = I.UOM_CODE     
		   JOIN SECTIOND M  (NOLOCK) ON B.SUB_SECTION_CODE = M.SUB_SECTION_CODE   
		   JOIN SECTIONM N  (NOLOCK) ON M.SECTION_CODE = N.SECTION_CODE   
		   JOIN POD01106 BO (NOLOCK) ON A.PRODUCT_CODE = BO.PRODUCT_CODE
		   JOIN POM01106 POM (NOLOCK) ON BO.PO_ID = POM.PO_ID 
		   WHERE POM.CANCELLED=0 AND ISNULL(A.CANCELLED,0)=0 AND BO.PO_ID = @CWHERE  
		     
		   UNION ALL  
		     
		   SELECT  B.ARTICLE_NAME,A.*,0 AS PURCHASE_PRICE  
		   ,(A.GROSS_WSP) AS MRP,(A.RFNET/A.QUANTITY) AS RATE,  
		  B.ARTICLE_NO,C.PARA1_NAME,D.PARA2_NAME,E.PARA3_NAME, F.PARA4_NAME, G.PARA5_NAME, H.PARA6_NAME,      
		  '' AS JRD_ROW_ID, '' AS JID_ROW_ID, '' AS JOD_ROW_ID,D.PARA2_ORDER,C.PARA1_ORDER ,    
		  A.RFNET AS AMOUNT,B.UOM_CODE,I.UOM_NAME,I.UOM_TYPE,B.DT_CREATED    
		  ,B.CODING_SCHEME,B.PARA1_SET,B.PARA2_SET,  
		  '0000000' AS FORM_ID,  
		  CONVERT(NUMERIC(14,2), 0) AS ITEM_TAX_PERCENTAGE,  
		  CONVERT(NUMERIC(14,2), 0) AS ITEM_TAX_AMOUNT,  
		  --(A.DISCOUNT_AMOUNT/A.QUANTITY) AS ITEM_DISCOUNT_AMOUNT,    
		  A.DISCOUNT_PERCENTAGE AS ITEM_DISCOUNT_PERCENTAGE,  
		  CONVERT(NUMERIC(14,2), 0) AS ITEM_DISCOUNT_AMOUNT,  
		  --CONVERT(NUMERIC(14,2), 0) AS ITEM_DISCOUNT_PERCENTAGE, 
		  B.WHOLESALE_PRICE, 
		  B.PURCHASE_PRICE, 
		  B.GROSS_PURCHASE_PRICE, 
		  B.DISCOUNT_PERCENTAGE AS ART_DISCOUNT_PERCENTAGE,
		  B.DISCOUNT_AMOUNT AS ART_DISCOUNT_AMOUNT,
		  CAST(0 AS BIT) AS MANUAL_MRP,  
		  CAST(0 AS BIT) AS MANUAL_DISCOUNT,  
		  CAST(0 AS BIT) AS MANUAL_WSP,  
		  A.QUANTITY AS INVOICE_QUANTITY,  
		  CONVERT(NUMERIC(14,2), 0) AS SCHEME_QUANTITY,
		  B.ALIAS AS ARTICLE_ALIAS  
		  FROM WSL_ORDER_DET A  (NOLOCK)        
		  JOIN ARTICLE B (NOLOCK)  ON A.ARTICLE_CODE = B.ARTICLE_CODE        
		  JOIN PARA1 C (NOLOCK)  ON A.PARA1_CODE = C.PARA1_CODE        
		  JOIN PARA2 D (NOLOCK)  ON A.PARA2_CODE = D.PARA2_CODE         
		  JOIN PARA3 E (NOLOCK)  ON A.PARA3_CODE = E.PARA3_CODE         
		  JOIN PARA4 F (NOLOCK)  ON A.PARA4_CODE = F.PARA4_CODE         
		  JOIN PARA5 G (NOLOCK)  ON A.PARA5_CODE = G.PARA5_CODE         
		  JOIN PARA6 H (NOLOCK) ON A.PARA6_CODE = H.PARA6_CODE        
		  JOIN WSL_ORDER_MST R ON R.ORDER_ID= A.ORDER_ID   
		  LEFT OUTER JOIN UOM I       (NOLOCK) ON B.UOM_CODE = I.UOM_CODE     
		  LEFT OUTER JOIN SECTIOND M  (NOLOCK) ON B.SUB_SECTION_CODE = M.SUB_SECTION_CODE   
		  LEFT OUTER JOIN SECTIONM N  (NOLOCK) ON M.SECTION_CODE = N.SECTION_CODE   
		  --LEFT OUTER JOIN POD01106 BO (NOLOCK) ON A.ROW_ID = BO.WOD_ROW_ID 
		  --LEFT OUTER JOIN POM01106 POM (NOLOCK) ON BO.PO_ID = POM.PO_ID AND POM.CANCELLED=0
		   LEFT OUTER JOIN 
		  (
		   SELECT PRODUCT_CODE FROM  POD01106 BO (NOLOCK)   
		   LEFT OUTER JOIN POM01106 POM (NOLOCK) ON BO.PO_ID = POM.PO_ID WHERE
		   POM.CANCELLED= 0
		  )  BO  ON ISNULL(A.PRODUCT_CODE,'') = ISNULL(BO.PRODUCT_CODE,'') 
		  WHERE   R.CANCELLED = 0 AND ISNULL(A.CANCELLED,0)=0 AND R.APPROVED=1 AND ISNULL(A.PRODUCT_CODE,'')<>'' AND A.ORDER_TYPE <> 1 AND BO.PRODUCT_CODE IS NULL  
		  ORDER BY A.PRODUCT_CODE,C.PARA1_NAME, D.PARA2_ORDER , B.ARTICLE_NO,  D.PARA2_NAME  
	  END  
	 ELSE  
	 BEGIN  
		  SELECT  CAST(0 AS BIT) AS BCHK,B.ARTICLE_NAME,A.*,0 AS PURCHASE_PRICE  
		  ,(A.GROSS_WSP) AS MRP,(A.RFNET/A.QUANTITY) AS RATE,  
		  B.ARTICLE_NO,C.PARA1_NAME,D.PARA2_NAME,E.PARA3_NAME, F.PARA4_NAME, G.PARA5_NAME, H.PARA6_NAME,      
		  '' AS JRD_ROW_ID, '' AS JID_ROW_ID, '' AS JOD_ROW_ID,D.PARA2_ORDER,C.PARA1_ORDER ,    
		  A.RFNET AS AMOUNT,B.UOM_CODE,I.UOM_NAME,I.UOM_TYPE,B.DT_CREATED    
		  ,B.CODING_SCHEME,B.PARA1_SET,B.PARA2_SET,  
		  '0000000' AS FORM_ID,  
		  CONVERT(NUMERIC(14,2), 0) AS ITEM_TAX_PERCENTAGE,  
		  CONVERT(NUMERIC(14,2), 0) AS ITEM_TAX_AMOUNT,  
		    
			 --(A.DISCOUNT_AMOUNT/A.QUANTITY) AS ITEM_DISCOUNT_AMOUNT,    
		  A.DISCOUNT_PERCENTAGE AS ITEM_DISCOUNT_PERCENTAGE,  
		  CONVERT(NUMERIC(14,2), 0) AS ITEM_DISCOUNT_AMOUNT,  
		  --CONVERT(NUMERIC(14,2), 0) AS ITEM_DISCOUNT_PERCENTAGE,  
		  B.WHOLESALE_PRICE, 
		  B.PURCHASE_PRICE, 
		  B.GROSS_PURCHASE_PRICE, 
		  B.DISCOUNT_PERCENTAGE AS ART_DISCOUNT_PERCENTAGE,
		  B.DISCOUNT_AMOUNT AS ART_DISCOUNT_AMOUNT, 
		  CAST(0 AS BIT) AS MANUAL_MRP,  
		  CAST(0 AS BIT) AS MANUAL_DISCOUNT,  
		  CAST(0 AS BIT) AS MANUAL_WSP,  
		  A.QUANTITY AS INVOICE_QUANTITY,  
		  CONVERT(NUMERIC(14,2), 0) AS SCHEME_QUANTITY,
		  B.ALIAS AS ARTICLE_ALIAS  
		  FROM WSL_ORDER_DET A  (NOLOCK)        
		  JOIN ARTICLE B (NOLOCK)  ON A.ARTICLE_CODE = B.ARTICLE_CODE        
		  JOIN PARA1 C (NOLOCK)  ON A.PARA1_CODE = C.PARA1_CODE        
		  JOIN PARA2 D (NOLOCK)  ON A.PARA2_CODE = D.PARA2_CODE         
		  JOIN PARA3 E (NOLOCK)  ON A.PARA3_CODE = E.PARA3_CODE         
		  JOIN PARA4 F (NOLOCK)  ON A.PARA4_CODE = F.PARA4_CODE         
		  JOIN PARA5 G (NOLOCK)  ON A.PARA5_CODE = G.PARA5_CODE         
		  JOIN PARA6 H (NOLOCK) ON A.PARA6_CODE = H.PARA6_CODE        
		  JOIN WSL_ORDER_MST R ON R.ORDER_ID= A.ORDER_ID   
		  LEFT OUTER JOIN UOM I       (NOLOCK) ON B.UOM_CODE = I.UOM_CODE     
		  LEFT OUTER JOIN SECTIOND M  (NOLOCK) ON B.SUB_SECTION_CODE = M.SUB_SECTION_CODE   
		  LEFT OUTER JOIN SECTIONM N  (NOLOCK) ON M.SECTION_CODE = N.SECTION_CODE   
		  --LEFT OUTER JOIN POD01106 BO (NOLOCK) ON A.ROW_ID = BO.WOD_ROW_ID  
		  --LEFT OUTER JOIN POM01106 POM (NOLOCK) ON BO.PO_ID = POM.PO_ID AND POM.CANCELLED= 0
		  LEFT OUTER JOIN 
		  (
			   SELECT PRODUCT_CODE FROM  POD01106 BO (NOLOCK)   
			   LEFT OUTER JOIN POM01106 POM (NOLOCK) ON BO.PO_ID = POM.PO_ID WHERE
			   POM.CANCELLED= 0
		  )  BO  ON ISNULL(A.PRODUCT_CODE,'') = ISNULL(BO.PRODUCT_CODE,'') 
		    
		  WHERE  R.CANCELLED = 0 AND R.APPROVED=1 AND ISNULL(A.CANCELLED,0)=0 AND ISNULL(A.PRODUCT_CODE,'')<>'' AND A.ORDER_TYPE <> 1 AND BO.PRODUCT_CODE IS NULL  
		  ORDER BY A.PRODUCT_CODE,C.PARA1_NAME, D.PARA2_ORDER , B.ARTICLE_NO,  D.PARA2_NAME  
	 END  
 END  
 
 GOTO LAST     

LBL25:
		SELECT CONVERT(BIT,0) AS CHK,D.TOTAL_QTY,TOTAL_AMOUNT,A.MEMO_DT AS ORDER_DT,A.MEMO_NO AS ORDER_NO,BUY_PLAN_NAME,BPM.BUDGET_PLAN_NAME,
		A.MEMO_NO AS ORDER_ID
		FROM BUY_PLAN_MST A(NOLOCK) 
		JOIN BUDGET_PLAN_MST BPM(NOLOCK) ON BPM.MEMO_NO=A.BUDGET_PLAN_MEMO_NO
		JOIN 
		(SELECT DISTINCT MEMO_NO FROM BUY_PLAN_DET A(NOLOCK) 
		 LEFT OUTER JOIN 
			(SELECT BUY_PLAN_ROW_ID,SUM(QUANTITY) AS QUANTITY FROM POD01106 A(NOLOCK)
			 JOIN POM01106 B(NOLOCK) ON A.PO_ID=B.PO_ID
			 WHERE B.CANCELLED=0 AND ENTRY_MODE = 4 AND ISNULL(BUY_PLAN_ROW_ID,'') <> '' 
				GROUP BY BUY_PLAN_ROW_ID) B ON A.ROW_ID = B.BUY_PLAN_ROW_ID
		 WHERE (A.QUANTITY- ISNULL(B.QUANTITY,0))>0) B ON A.MEMO_NO = B.MEMO_NO
		 JOIN (SELECT MEMO_NO,SUM(QUANTITY) AS TOTAL_QTY,SUM(QUANTITY*PURCHASE_PRICE) AS TOTAL_AMOUNT
		       FROM BUY_PLAN_DET(NOLOCK) GROUP BY MEMO_NO) D ON A.MEMO_NO = D.MEMO_NO
		WHERE A.APPROVEDLEVELNO=99 AND A.CANCELLED = 0 AND BPM.EXPIRY_DT>@DPODT
		ORDER BY A.MEMO_NO,A.MEMO_DT  
	    
	    GOTO LAST

LBL26:
		 SELECT CONVERT(BIT,0) AS BCHK,ARTICLE_NO,ARTICLE_NAME,A.ARTICLE_CODE,A.PARA1_CODE,A.PARA2_CODE,AT.ALIAS,
		 CASE WHEN isnull(AT.MRP,0)=0 THEN a.MRP ELSE AT.MRP END AS MRP,
		 CASE WHEN isnull(A.PURCHASE_PRICE,0)<>0 THEN a.PURCHASE_PRICE ELSE AT.PURCHASE_PRICE END AS PURCHASE_PRICE,
		 CASE WHEN isnull(AT.WHOLESALE_PRICE,0)=0 THEN at.wholesale_price ELSE AT.WHOLESALE_PRICE END AS WHOLESALE_PRICE,
		 CASE WHEN isnull(AT.FIX_MRP,0)=0 THEN at.FIX_MRP ELSE AT.FIX_MRP END AS FIX_MRP,


		 --AT.MRP,AT.PURCHASE_PRICE,AT.WHOLESALE_PRICE,AT.FIX_MRP,
		 
		 SM.SECTION_NAME,SD.SUB_SECTION_NAME,UM.UOM_TYPE,UM.UOM_NAME,
		 P1.PARA1_NAME,
		 P2.PARA2_NAME,
		 P3.PARA3_NAME,P3.PARA3_CODE ,
		 P4.PARA4_NAME,P4.PARA4_CODE ,
		 P5.PARA5_NAME,P5.PARA5_CODE ,
		 P6.PARA6_NAME,P6.PARA6_CODE ,
		 CODING_SCHEME,AT.UOM_CODE,
		 (A.QUANTITY-ISNULL(B.QUANTITY,0)) AS QUANTITY,A.PURCHASE_PRICE AS RATE,A.MEMO_NO AS ORDER_NO,A.MEMO_NO AS ORDER_ID,A.ROW_ID,
		 (A.QUANTITY-ISNULL(B.QUANTITY,0)) AS PENDING_QUANTITY,CONVERT(DATETIME,'') AS DELIVERY_DT,AT.HSN_CODE
		 ,AT1.attr1_key_name,AT2.attr2_key_name,AT3.attr3_key_name,AT4.attr4_key_name,AT5.attr5_key_name,AT6.attr6_key_name,
		   AT7.attr7_key_name,AT8.attr8_key_name,AT9.attr9_key_name,AT10.attr10_key_name,AT11.attr11_key_name,AT12.attr12_key_name,
		   AT13.attr13_key_name,AT14.attr14_key_name,AT15.attr15_key_name,AT16.attr16_key_name,AT17.attr17_key_name,AT18.attr18_key_name,
		   AT19.attr19_key_name,AT20.attr20_key_name,AT21.attr21_key_name,AT22.attr22_key_name,AT23.attr23_key_name,AT24.attr24_key_name,
			AT25.attr25_key_name
		 FROM BUY_PLAN_DET A(NOLOCK)
		 JOIN BUY_PLAN_MST D(NOLOCK) ON A.MEMO_NO=D.MEMO_NO
		 JOIN BUDGET_PLAN_MST BPM(NOLOCK) ON BPM.MEMO_NO=D.BUDGET_PLAN_MEMO_NO
		 LEFT OUTER JOIN
		 (SELECT BUY_PLAN_ROW_ID,SUM(QUANTITY) AS QUANTITY FROM POD01106(NOLOCK)  JOIN POM01106(NOLOCK) ON POD01106.PO_ID = POM01106.PO_ID
		  WHERE POM01106.CANCELLED = 0  AND ISNULL(BUY_PLAN_ROW_ID,'') <> '' GROUP BY BUY_PLAN_ROW_ID) B ON A.ROW_ID = B.BUY_PLAN_ROW_ID
		 JOIN BUY_PLAN_MST C(NOLOCK) ON A.MEMO_NO = C.MEMO_NO
		 JOIN ARTICLE AT(NOLOCK) ON AT.ARTICLE_CODE = A.ARTICLE_CODE
		 JOIN PARA1 P1(NOLOCK) ON P1.PARA1_CODE = A.PARA1_CODE
		 JOIN PARA2 P2(NOLOCK) ON P2.PARA2_CODE = A.PARA2_CODE
		 JOIN PARA3 P3(NOLOCK) ON P3.PARA3_CODE = a.PARA3_CODE
		 JOIN PARA4 P4(NOLOCK) ON P4.PARA4_CODE = a.PARA4_CODE
		 JOIN PARA5 P5(NOLOCK) ON P5.PARA5_CODE	= a.PARA5_CODE
		 JOIN PARA6 P6(NOLOCK) ON P6.PARA6_CODE = a.PARA6_CODE
		 JOIN SECTIOND SD(NOLOCK) ON SD.SUB_SECTION_CODE = AT.SUB_SECTION_CODE
		 JOIN SECTIONM SM(NOLOCK) ON SM.SECTION_CODE = SD.SECTION_CODE
		 JOIN UOM UM(NOLOCK) ON UM.UOM_CODE = AT.UOM_CODE
		 LEFT OUTER JOIN article_fix_attr ATTR  (NOLOCK) ON AT.article_code = ATTR.ARTICLE_CODE 
		LEFT OUTER JOIN attr1_mst at1 (NOLOCK) ON at1.attr1_key_code=ATTR.attr1_key_code
		LEFT OUTER JOIN attr2_mst at2 (NOLOCK) ON at2.attr2_key_code=ATTR.attr2_key_code
		LEFT OUTER JOIN attr3_mst at3 (NOLOCK) ON at3.attr3_key_code=ATTR.attr3_key_code
		LEFT OUTER JOIN attr4_mst at4 (NOLOCK) ON at4.attr4_key_code=ATTR.attr4_key_code
		LEFT OUTER JOIN attr5_mst at5 (NOLOCK) ON at5.attr5_key_code=ATTR.attr5_key_code
		LEFT OUTER JOIN attr6_mst at6 (NOLOCK) ON at6.attr6_key_code=ATTR.attr6_key_code
		LEFT OUTER JOIN attr7_mst at7 (NOLOCK) ON at7.attr7_key_code=ATTR.attr7_key_code
		LEFT OUTER JOIN attr8_mst at8 (NOLOCK) ON at8.attr8_key_code=ATTR.attr8_key_code
		LEFT OUTER JOIN attr9_mst at9 (NOLOCK) ON at9.attr9_key_code=ATTR.attr9_key_code
		LEFT OUTER JOIN attr10_mst at10 (NOLOCK) ON at10.attr10_key_code=ATTR.attr10_key_code
		LEFT OUTER JOIN attr11_mst at11 (NOLOCK) ON at11.attr11_key_code=ATTR.attr11_key_code
		LEFT OUTER JOIN attr12_mst at12 (NOLOCK) ON at12.attr12_key_code=ATTR.attr12_key_code
		LEFT OUTER JOIN attr13_mst at13 (NOLOCK) ON at13.attr13_key_code=ATTR.attr13_key_code
		LEFT OUTER JOIN attr14_mst at14 (NOLOCK) ON at14.attr14_key_code=ATTR.attr14_key_code
		LEFT OUTER JOIN attr15_mst at15 (NOLOCK) ON at15.attr15_key_code=ATTR.attr15_key_code
		LEFT OUTER JOIN attr16_mst at16 (NOLOCK) ON at16.attr16_key_code=ATTR.attr16_key_code
		LEFT OUTER JOIN attr17_mst at17 (NOLOCK) ON at17.attr17_key_code=ATTR.attr17_key_code
		LEFT OUTER JOIN attr18_mst at18 (NOLOCK) ON at18.attr18_key_code=ATTR.attr18_key_code
		LEFT OUTER JOIN attr19_mst at19 (NOLOCK) ON at19.attr19_key_code=ATTR.attr19_key_code
		LEFT OUTER JOIN attr20_mst at20 (NOLOCK) ON at20.attr20_key_code=ATTR.attr20_key_code
		LEFT OUTER JOIN attr21_mst at21 (NOLOCK) ON at21.attr21_key_code=ATTR.attr21_key_code
		LEFT OUTER JOIN attr22_mst at22 (NOLOCK) ON at22.attr22_key_code=ATTR.attr22_key_code
		LEFT OUTER JOIN attr23_mst at23 (NOLOCK) ON at23.attr23_key_code=ATTR.attr23_key_code
		LEFT OUTER JOIN attr24_mst at24 (NOLOCK) ON at24.attr24_key_code=ATTR.attr24_key_code
		LEFT OUTER JOIN attr25_mst at25(NOLOCK) ON at25.attr25_key_code=ATTR.attr25_key_code
		 WHERE D.APPROVEDLEVELNO=99 AND  (A.QUANTITY-ISNULL(B.QUANTITY,0) > 0 OR  B.BUY_PLAN_ROW_ID IS NULL) AND C.CANCELLED = 0
		 AND BPM.EXPIRY_DT>@DPODT
		 ORDER BY A.MEMO_NO
		 
		 GOTO LAST
  
LAST:  
  
END