CREATE PROCEDURE SP_SEND_MIRROR_DOCGV_DATA_OPT --(LocId 3 digit change by Sanjay:30-10-2024)
	 @CREQXNID VARCHAR(50)
	,@CTARGETLOCID VARCHAR(4)
	,@CERRMSG VARCHAR(1000) OUTPUT
AS
/*
	SP_SEND_MIRROR_DOCGV_DATA : THIS PROCEDURE USE TO SEND DOCGV DATA
*/
BEGIN
	DECLARE @DTSQL NVARCHAR(MAX),@NSPID INT,@CTEMPTABLE VARCHAR(500),@CMEMOID VARCHAR(50),
	@CTEMPEMPLOYEETABLE VARCHAR(200),@DMEMOLASTUPDATE DATETIME,@CTABLENAME VARCHAR(100),
	@BRECFOUND BIT,@CSTEP VARCHAR(5),@CFILTERCONDITION VARCHAR(MAX),@CCUTOFFDATE VARCHAR(20),
	@CTEMPMASTERTABLE VARCHAR(200),@CTEMPDETAILTABLE VARCHAR(200),@CTEMPLMTABLE VARCHAR(200),
	@CTEMPLMPTABLE VARCHAR(200),@CTEMPAREATABLE VARCHAR(200),@CTEMPCITYTABLE VARCHAR(200),
	@CTEMPPMODEXNTABLE VARCHAR(200),@CTEMPPMODETABLE VARCHAR(200),@CSTNAPPROVAL BIT,
	@CCLOCID VARCHAR(10),@CHOLOCID VARCHAR(10),@BSENDPURINFOLOC BIT,
	@BPURLOC BIT,@BHOWH BIT,@CTEMPSKUGVTABLE VARCHAR(500),@CTEMPSKUOHTABLE VARCHAR(500),
	@NTARGETLOCTYPE INT,@BTARGETPURLOC BIT,@CTEMPSLSBCTABLE VARCHAR(500),@CTEMPSLSDETTABLE VARCHAR(500)
	
	DECLARE @TXNSSENDINFO TABLE (ORG_TABLENAME VARCHAR(50),TMP_TABLENAME VARCHAR(50),XN_ID VARCHAR(40))  
	

BEGIN TRY 	


	
	SET @CSTEP=10
	---- IF NO MEMO FOUND , JUST END THE PROCESS
	SET @CMEMOID=@CREQXNID

LBLTABLEINFO:
	SET @CSTEP=50
	---- POPULATE LIST OF TABLES 

	SELECT 	@CREQXNID AS XN_ID,'DOCGV_GV_STKXFER_MST_UPLOAD' AS TARGET_TABLENAME,* FROM GV_STKXFER_MST (NOLOCK) 
	WHERE memo_id=@CREQXNID

	SELECT 	@CREQXNID AS XN_ID,'DOCGV_GV_STKXFER_DET_UPLOAD' AS TARGET_TABLENAME,* FROM GV_STKXFER_DET (NOLOCK) 
	WHERE memo_id=@CREQXNID

	SELECT 	@CREQXNID AS XN_ID,'DOCGV_SKU_GV_MST_UPLOAD' AS TARGET_TABLENAME,* FROM SKU_GV_MST a (NOLOCK) 
	JOIN GV_STKXFER_DET b (NOLOCK) ON a.gv_srno=b.gv_srno
	WHERE memo_id=@CREQXNID

	SELECT 	@CREQXNID AS XN_ID,'DOCGV_GV_MST_INFO_UPLOAD' AS TARGET_TABLENAME,* FROM GV_MST_INFO a (NOLOCK) 
	JOIN GV_STKXFER_DET b (NOLOCK) ON a.gv_srno=b.gv_srno
	WHERE memo_id=@CREQXNID

	SELECT 	@CREQXNID AS XN_ID,'DOCGV_GV_GEN_DET_UPLOAD' AS TARGET_TABLENAME,a.* FROM GV_GEN_DET a (NOLOCK) 
	JOIN GV_STKXFER_DET b (NOLOCK) ON a.gv_srno=b.gv_srno
	WHERE b.memo_id=@CREQXNID
		
	SELECT 	DISTINCT @CREQXNID AS XN_ID,'DOCGV_GV_GEN_MST_UPLOAD' AS TARGET_TABLENAME,a.* 
	FROM GV_GEN_MST a (NOLOCK) 
	JOIN GV_GEN_DET c (NOLOCK) ON c.memo_id=a.memo_id
	JOIN GV_STKXFER_DET b (NOLOCK) ON c.gv_srno=b.gv_srno
	WHERE b.memo_id=@CREQXNID

	GOTO END_PROC
	
END TRY

BEGIN CATCH
	SET @CERRMSG='P: SP_SEND_MIRROR_DOCGV_DATA_OPT, STEP:'+@CSTEP+', MESSAGE:'+ERROR_MESSAGE()
	GOTO END_PROC
END CATCH 		

END_PROC:
		
END
---END OF PROCEDURE - SP_SEND_MIRROR_DOCGV_DATA_OPT