CREATE PROCEDURE SP_Recalculate_Goods_Tds
(
  @DFMDT DATETIME ,
  @DTODT DATETIME,
  @CDEPT_ID varchar(4)='',
  @NPARTY_AMOUNT_FORTCS numeric(18,2)=0
)
as
BEGIN
     DECLARE @CSTEP VARCHAR(10),@CERRORMSG varchar(1000),@DMEMO_DT DATETIME,
             @NTAXABLEVALUE numeric(18,2),@nxnitemtype int,@CsourceGstNo varchar(20),
             @CtargetGstNo varchar(20),@cfinyear varchar(10),@DINVDT Datetime,@cac_code Varchar(10),
             @CMRR_ID varchar(50),@ninv_mode int

     BEGIN TRANSACTION
	 BEGIN TRY
	 
	 IF ISNULL(@CDEPT_ID,'')=''
	 BEGIN
	     SET @CERRORMSG='LOCATION ID CAN NOT BE BLANK'
		  GOTO END_PROC
	 END

	 IF @DFMDT<'2021-07-01'
	   GOTO END_PROC
	
	  IF NOT EXISTS (SELECT TOP 1 'U' FROM LOCATION WHERE DEPT_ID =@CDEPT_ID AND ISNULL(ENABLE_TCS,0)=1)
	  begin

	  
               update b set  GOODS_TDS_BASEAMOUNT=0,
			                GOODS_TDS_PERCENTAGE=0,
							GOODS_TDS_AMOUNT=0
			  FROM  PIM01106 B where dept_id=@CDEPT_ID and isnull(GOODS_TDS_PERCENTAGE,0)<>0

	   GOTO END_PROC

	  end

	 SET @CSTEP=10

	 
	 DECLARE @tBal TABLE (TCS_BASEAMOUNT NUMERIC(18,2))

	CREATE  TABLE  #TMSTTABLEDATA  (dept_id varchar(4),mrr_id varchar(50),GOODS_TDS_BASEAMOUNT numeric(18,2),GOODS_TDS_PERCENTAGE numeric(10,3),GOODS_TDS_AMOUNT numeric(12,2),
	                          TOTAL_AMOUNT numeric(18,2),xn_item_type int,sourceGstNo varchar(20),
							  targetGstNo varchar(20),FIN_YEAR varchar(10),RECEIPT_DT Datetime,
							  ac_code Varchar(20),inv_mode int )	 

  
  
   INSERT INTO #TMSTTABLEDATA (DEPT_ID ,MRR_ID ,GOODS_TDS_BASEAMOUNT ,GOODS_TDS_PERCENTAGE ,GOODS_TDS_AMOUNT,TOTAL_AMOUNT,XN_ITEM_TYPE,SOURCEGSTNO,TARGETGSTNO ,FIN_YEAR ,RECEIPT_DT ,AC_CODE,inv_mode  )

	SELECT A.DEPT_ID ,MRR_ID ,0 as GOODS_TDS_BASEAMOUNT ,0 as GOODS_TDS_PERCENTAGE ,0 GOODS_TDS_AMOUNT  ,TOTAL_AMOUNT ,XN_ITEM_TYPE , L.LOC_GST_NO SOURCEGSTNO,LMP.Ac_gst_no  TARGETGSTNO ,A.FIN_YEAR ,RECEIPT_DT  INVDT ,A.AC_CODE ,a.inv_mode
	FROM PIM01106 A (NOLOCK) 
	JOIN LOCATION L (NOLOCK) ON L.dept_id =a.location_Code
	JOIN LMP01106 LMP (NOLOCK) ON A.ac_code =LMP.AC_CODE
	WHERE A.CANCELLED =0 AND A.RECEIPT_DT BETWEEN @DFMDT AND @DTODT
	AND ISNULL(A.BILL_CHALLAN_MODE,0)=0 and a.XN_ITEM_TYPE=1
	and a.dept_id=@CDEPT_ID
	--and a.mrr_id='0001122000000HO-001848'

	SELECT * INTO #TMSTTABLE FROM  #TMSTTABLEDATA WHERE 1=2

	WHILE EXISTS (SELECT TOP 1 'U' FROM #TMSTTABLEDATA)
	BEGIN
	      
         SET @CSTEP=20

		  INSERT INTO #TMSTTABLE (DEPT_ID ,MRR_ID ,GOODS_TDS_BASEAMOUNT ,GOODS_TDS_PERCENTAGE ,GOODS_TDS_AMOUNT,TOTAL_AMOUNT,XN_ITEM_TYPE,SOURCEGSTNO,TARGETGSTNO ,FIN_YEAR ,RECEIPT_DT ,AC_CODE,inv_mode   )
		  select top 1 DEPT_ID ,MRR_ID ,GOODS_TDS_BASEAMOUNT ,GOODS_TDS_PERCENTAGE ,GOODS_TDS_AMOUNT,TOTAL_AMOUNT,XN_ITEM_TYPE,SOURCEGSTNO,TARGETGSTNO ,FIN_YEAR ,RECEIPT_DT ,AC_CODE ,inv_mode 
		  from #TMSTTABLEDATA
		  ORDER BY MRR_ID 
		

		 SELECT @NXNITEMTYPE=0,@NTAXABLEVALUE= 0,@CSOURCEGSTNO='',@CTARGETGSTNO='',@CFINYEAR='',  
		       @DINVDT='',@CAC_CODE='',@CMRR_ID='',@ninv_mode=1
		 
		 SET @CSTEP=25
		 SELECT TOP 1 @NXNITEMTYPE=XN_ITEM_TYPE,@NTAXABLEVALUE= TOTAL_AMOUNT,@CSOURCEGSTNO=SOURCEGSTNO,@CTARGETGSTNO=TARGETGSTNO,@CFINYEAR=FIN_YEAR,  
		       @DINVDT=RECEIPT_DT,@CAC_CODE=AC_CODE,@CMRR_ID=mrr_id,@ninv_mode=a.inv_mode
		 FROM #TMSTTABLE  A
		 

		 SET @CSTEP=26
		 
		   INSERT INTO @TBAL
		   EXEC SP3S_GET_PURCHASE_TCS_BASEAMOUNT
		        @CSOURCEGSTNO=@CSOURCEGSTNO,
				@CTARGETGSTNO=@CTARGETGSTNO,
				@CFINYEAR=@CFINYEAR,
				@DINVDT=@DINVDT,
				@BCALLEDFROMVCHENTRY=0,
				@CAC_CODE=@CAC_CODE,
				@CMRR_ID=@CMRR_ID

				SET @CSTEP=28
		  select @NPARTY_AMOUNT_FORTCS=TCS_BASEAMOUNT from @tBal
		  set @NPARTY_AMOUNT_FORTCS=isnull(@NPARTY_AMOUNT_FORTCS,0)

	
		  SET @CSTEP=30
		 IF  EXISTS (SELECT TOP 1 'U' FROM TCS_MST WHERE WEF <=@DINVDT AND ISNULL(TCS_TYPE,0)=1 ) AND ISNULL(@NXNITEMTYPE,0)=1
		   BEGIN
	        

			  EXEC SP3S_TCSCAL_PUR 
			  @CXNTYPE='PUR',
			  @CLOCID=@CDEPT_ID,
			  @NTAXABLEVALUE=@NTAXABLEVALUE,
			  @NPARTY_AMOUNT_FORTCS=@NPARTY_AMOUNT_FORTCS,
			  @CERRORMSG=@CERRORMSG OUTPUT,
			  @ninvmode=@ninv_mode

			  IF ISNULL(@CERRORMSG,'')<>''
			   GOTO END_PROC

			

			  update b set  GOODS_TDS_BASEAMOUNT=a.GOODS_TDS_BASEAMOUNT,
			                GOODS_TDS_PERCENTAGE=a.GOODS_TDS_PERCENTAGE,
							GOODS_TDS_AMOUNT=a.GOODS_TDS_AMOUNT
			  FROM #TMSTTABLE A
			  JOIN PIM01106 B ON A.MRR_ID=B.MRR_ID 


		   END

		  DELETE FROM @TBAL
		  DELETE FROM #TMSTTABLEDATA WHERE MRR_ID=@CMRR_ID
		  delete from #TMSTTABLE WHERE MRR_ID=@CMRR_ID

	         
   END


	 END TRY

	BEGIN CATCH
		SET @CERRORMSG='Error in Procedure SP3S_FETCH_BATCHWISEBC AT Step#'+@cStep+' '+ERROR_MESSAGE()
		GOTO END_PROC
	END CATCH

END_PROC:

	IF @@TRANCOUNT>0
	BEGIN
		IF ISNULL(@CERRORMSG,'')='' 
			BEGIN
			commit TRANSACTION
		END
		ELSE
			ROLLBACK
	END

select  @CERRORMSG aS ERRMSG

end
