CREATE PROCEDURE SP_PAY_HOLD
(  
 @CMEMOID VARCHAR(50),  
 @CXNTYPE VARCHAR(50),  
 @CTABLE VARCHAR(50)  
)  
--WITH ENCRYPTION

AS  
BEGIN  
 DECLARE @CCOL VARCHAR(40),   
   @CCMD NVARCHAR(MAX),  
   @CRETCOLSTR NVARCHAR(MAX)  
    
     
 SET @CRETCOLSTR = N''  
   
  
 DECLARE CUR_CT CURSOR FOR  
    
 SELECT B.PAYMODE_NAME   
 FROM PAYMODE_XN_DET_HOLD A (NOLOCK)  
 JOIN PAYMODE_MST B (NOLOCK) ON A.PAYMODE_CODE = B.PAYMODE_CODE  
 JOIN PAYMODE_GRP_MST C (NOLOCK) ON B.PAYMODE_GRP_CODE = C.PAYMODE_GRP_CODE  
 WHERE  A.HOLD_ID=@CMEMOID AND A.XN_TYPE= @CXNTYPE  
 ORDER BY B.PAYMODE_NAME  
  
   
  
 OPEN CUR_CT  
  
 FETCH NEXT FROM CUR_CT INTO @CCOL  
 WHILE @@FETCH_STATUS = 0  
 BEGIN  
  SET @CRETCOLSTR = @CRETCOLSTR + ( CASE WHEN @CRETCOLSTR<>'' THEN N', ' ELSE '' END ) + N'  
        SUM(CASE WHEN B.PAYMODE_NAME = ''' + @CCOL + ''' THEN A.AMOUNT ELSE 0 END) AS [' + @CCOL + '] '  
  
    
  FETCH NEXT FROM CUR_CT INTO @CCOL  
 END  
 CLOSE CUR_CT  
 DEALLOCATE CUR_CT 
  
   
 SET @CCMD =N'IF OBJECT_ID('''+@CTABLE+''', ''U'' ) IS NOT NULL  
           DROP TABLE '+@CTABLE  
             
 EXEC SP_EXECUTESQL @CCMD  
  
 SET @CCMD = N' SELECT A.HOLD_ID AS [MEMO_ID]' + (CASE WHEN @CRETCOLSTR<>'' THEN ', ' ELSE '' END) + @CRETCOLSTR +   
    N' INTO '+@CTABLE+ '   
    FROM PAYMODE_XN_DET_HOLD A (NOLOCK)  
    JOIN PAYMODE_MST B (NOLOCK) ON A.PAYMODE_CODE = B.PAYMODE_CODE  
    JOIN PAYMODE_GRP_MST C (NOLOCK) ON B.PAYMODE_GRP_CODE = C.PAYMODE_GRP_CODE  
    WHERE   A.XN_TYPE= '''+@CXNTYPE+''' AND  A.HOLD_ID='''+@CMEMOID+''' GROUP BY A.HOLD_ID'  
       
       
       
 --PRINT @CCMD  
 EXEC SP_EXECUTESQL @CCMD  
  
  
END
