CREATE PROCEDURE SP_SEND_MIRROR_CNC_DATA_NEW
(	
	 @CUPLOADEDXNID VARCHAR(50)
	,@CCURLOCID VARCHAR(5)	
	,@BACKNOWLEDGE BIT=0
	,@CERRMSG VARCHAR(1000) OUTPUT
)
--WITH ENCRYPTION
AS
BEGIN
     DECLARE @DTSQL NVARCHAR(MAX),@CSTEP VARCHAR(10),@CFILTERCONDITION VARCHAR(MAX),
             @CMEMOID VARCHAR(50),@DMEMOLASTUPDATE DATETIME,
             @CTABLENAME VARCHAR(100),@CTEMPTABLE VARCHAR(100),@CTEMPMASTERTABLE VARCHAR(100),
             @CTEMPDETAILTABLE VARCHAR(100),@BRECFOUND BIT
     
     
BEGIN TRY
     DECLARE @CTEMPDBNAME VARCHAR(100)
	 
	 SET @CTEMPDBNAME=''
	
	SET @CSTEP=10
	SET @CFILTERCONDITION=''	
		 
	--CHNAGE BY BAIJNATH
	SET @CMEMOID=@CUPLOADEDXNID
    SET @CSTEP=40
	---- IF NO MEMO FOUND , JUST END THE PROCESS
	IF ISNULL(@CMEMOID,'')=''
		GOTO END_PROC
	
	
	
	SET @CSTEP=220
	---- SEND THE ICM01106 MEMO MASTER TABLE
	SELECT DISTINCT  A.*,'CNC_ICM01106_UPLOAD' AS TARGET_TABLENAME FROM ICM01106 A (NOLOCK) WHERE   A.CNC_MEMO_ID=@CMEMOID
	
	SET @CSTEP=250
	---- SEND THE ICD01106 MEMO DETAIL TABLE
	SELECT DISTINCT  A.*,'CNC_ICD01106_UPLOAD' AS TARGET_TABLENAME FROM ICD01106 A (NOLOCK) WHERE   A.CNC_MEMO_ID=@CMEMOID
		
	
	SET @CSTEP=251
	---- SEND THE pmt01106 TABLE
	SELECT DISTINCT 'CNC_PMT01106_UPLOAD' AS TARGET_TABLENAME, @CMEMOID AS CNC_MEMO_ID ,A.DEPT_ID,A.product_code,A.BIN_ID,A.quantity_in_stock  
	  FROM PMT01106 A (NOLOCK)  
	  JOIN ICD01106 B (NOLOCK) ON B.product_code=A.product_code
	  WHERE B.CNC_MEMO_ID=@CMEMOID 


	GOTO END_PROC
	
	END TRY
BEGIN CATCH
	SET @CERRMSG='P: SP_SEND_MIRROR_CNC_DATA_NEW, STEP:'+@CSTEP+', MESSAGE:'+ERROR_MESSAGE()
	GOTO END_PROC
END CATCH 	
	
END_PROC:
	
	
END
