CREATE PROCEDURE SP3S_SYNCH_UPLOADDATA_PRCL_OPT
(
    @CSPID VARCHAR(50)
   ,@CERRMSG VARCHAR(1000) OUTPUT
)
--WITH ENCRYPTION
AS
BEGIN
    DECLARE @CSTEP VARCHAR(100),@DTSQL NVARCHAR(MAX),@NMERGE_ORDER NUMERIC(5)
	   ,@CTABLENAME VARCHAR(200),@CTABLE_SUFFIX VARCHAR(50),@CKEYFIELD VARCHAR(200),@CDEL_ID VARCHAR(50),@CTMP_TABLENAME VARCHAR(200),@LINSERTONLY VARCHAR(1)
	   ,@CFILTERCONDITION VARCHAR(200),@LUPDATEONLY VARCHAR(1),@BALWAYSUPDATE VARCHAR(1),@FDEL CHAR(1)
	   ,@CERRMSGOUT VARCHAR(1000),@CTABLESSTR VARCHAR(MAX),@CTABLESUFFIX VARCHAR(100)
	   ,@CXNTYPE VARCHAR(10),@CPARTYDEPTID VARCHAR(5),@CMIRRORDOCXNID VARCHAR(40),@LAST_UPDATE_INSERTED DATETIME
	   ,@CCURLOCID VARCHAR(5),@CREFMEMOID VARCHAR(40),@CMEMOID VARCHAR(50),@CLOCID VARCHAR(5),@CSOURCEDB VARCHAR(200)
       ,@CMERGEDB VARCHAR(200),@BMSTINSERTONLY BIT
	   
     
      BEGIN TRY
		SELECT TOP 1 @CCURLOCID=VALUE FROM CONFIG WHERE CONFIG_OPTION='LOCATION_ID'
		
		SET @CSTEP=20
		SET @CTABLE_SUFFIX='UPLOAD'
		BEGIN TRANSACTION
		SET @CTABLESUFFIX=@CTABLE_SUFFIX
		    
			SELECT @CSOURCEDB='',@CMERGEDB=''

		  SELECT TOP 1 @CMEMOID = B.PARCEL_MEMO_ID  
	  	  FROM PRCL_PARCEL_MST_UPLOAD B (NOLOCK)
		  WHERE SP_ID=@CSPID
	   

		IF ISNULL(@CMEMOID,'')=''
			GOTO EXIT_PROC
        
     

	       SET @CFILTERCONDITION = '  B.SP_ID='''+LTRIM(RTRIM((@CSPID)))+''''
		    
		    SET @CSTEP=30
			SET @CTABLENAME='ANGM'
			SET @CTMP_TABLENAME='PRCL_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))
			SET @CKEYFIELD='ANGADIA_CODE'
			SET @CSTEP=40
			EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=1,@CFILTERCONDITION=@CFILTERCONDITION,@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=0 


			SET @CFILTERCONDITION = ' B.SP_ID='''+LTRIM(RTRIM((@CSPID)))+''''
			SET @CSTEP=60
			SET @CTABLENAME='PARCEL_MST'
			SET @CTMP_TABLENAME='PRCL_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))
			SET @CKEYFIELD='PARCEL_MEMO_ID'
			SET @CSTEP=80
			EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
									  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=0,@CFILTERCONDITION=@CFILTERCONDITION,@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1
			
			SET @CSTEP=90
			SET @DTSQL = N'DELETE A FROM PARCEL_DET A 
			               LEFT JOIN '+@CSOURCEDB+'PRCL_PARCEL_DET_'+@CTABLESUFFIX+' B ON A.ROW_ID=B.ROW_ID
			               WHERE A.'+@CKEYFIELD+' = '''+@CMEMOID+''' AND B.ROW_ID IS NULL'
			PRINT @DTSQL
			EXEC SP_EXECUTESQL @DTSQL
			
					
			SET @CSTEP=100
			SET @CTABLENAME='PARCEL_DET'
			SET @CTMP_TABLENAME='PRCL_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))
			SET @CKEYFIELD='PARCEL_MEMO_ID'
			SET @CSTEP=130
			EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='ROW_ID',@CKEYFIELD3=''
							  ,@LINSERTONLY=0,@CFILTERCONDITION=@CFILTERCONDITION,@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1 
							  
		    SET @CSTEP=90
			
	   
			SET @CSTEP=120
			SELECT @CXNTYPE=XN_TYPE,@LAST_UPDATE_INSERTED=LAST_UPDATE FROM PARCEL_MST 
			WHERE PARCEL_MEMO_ID=@CMEMOID
			
			IF @CXNTYPE='WSL'
				SELECT TOP 1 @CPARTYDEPTID = PARTY_DEPT_ID,@CREFMEMOID=A.REF_MEMO_ID
				FROM PARCEL_DET A 
				JOIN INM01106 B ON A.REF_MEMO_ID=B.INV_ID
				WHERE PARCEL_MEMO_ID=@CMEMOID AND B.INV_MODE=2
			ELSE
			IF @CXNTYPE='PRT'
				SELECT TOP 1 @CPARTYDEPTID = PARTY_DEPT_ID,@CREFMEMOID=A.REF_MEMO_ID
				FROM PARCEL_DET A 
				JOIN RMM01106 B ON A.REF_MEMO_ID=B.RM_ID
				WHERE PARCEL_MEMO_ID=@CMEMOID AND MODE=2				
				
			IF ISNULL(@CPARTYDEPTID,'')<>'' AND @CPARTYDEPTID<>@CCURLOCID
			BEGIN		
				  
			 SET @CSTEP=150
			IF @CXNTYPE='WSL'
				UPDATE INM01106  WITH (ROWLOCK)  SET LAST_UPDATE=LAST_UPDATE WHERE INV_ID=@CREFMEMOID
			ELSE
			IF @CXNTYPE='PRT'
				UPDATE RMM01106 WITH (ROWLOCK) SET LAST_UPDATE=LAST_UPDATE WHERE RM_ID=@CREFMEMOID
				  
		    END	  
		 
	END TRY
	BEGIN CATCH
		SET @CERRMSG='P:SP3S_SYNCH_UPLOADDATA_PRCL_OPT, STEP:'+@CSTEP+', MESSAGE:'+ERROR_MESSAGE()
	END CATCH
	EXIT_PROC:
	IF ISNULL(@CERRMSG,'')='' AND @@TRANCOUNT>0
	BEGIN
		COMMIT
		
	END
	ELSE IF ISNULL(@CERRMSG,'')<>'' AND @@TRANCOUNT>0
		ROLLBACK   
	   
	   delete from PRCL_PARCEL_MST_UPLOAD where sp_id=@CSPID
	   
	   delete from PRCL_PARCEL_det_UPLOAD where sp_id=@CSPID
	   
	   delete from PRCL_angm_UPLOAD where sp_id=@CSPID

END
----'END OF CREATING PROCEDURE - SP_MERGE_MIRROR_PRCL_DATA'
