CREATE PROCEDURE SP_SC_PRODUCT_CODE  
@CWHERE VARCHAR(MAX)  
--WITH ENCRYPTION

AS  
BEGIN  
	SELECT TOP 50 A.ARTICLE_CODE, A.ARTICLE_NAME, A.ARTICLE_NO,       
	B.SUB_SECTION_NAME, C.SECTION_NAME,'' AS PRODUCT_CODE,  
	PARA1.PARA1_NAME,PARA2.PARA2_NAME,    
	PARA3.PARA3_NAME,PARA4.PARA4_NAME,PARA5.PARA5_NAME,PARA6.PARA6_NAME,  
	PARA1.PARA1_CODE,PARA2.PARA2_CODE,    
	PARA3.PARA3_CODE,PARA4.PARA4_CODE,PARA5.PARA5_CODE,PARA6.PARA6_CODE,  
	A.PURCHASE_PRICE,A.MRP,A.WHOLESALE_PRICE AS WS_PRICE,UOM.UOM_NAME,A.CODING_SCHEME,  
	ISNULL(A.DT_CREATED,'') AS [ART_DT_CREATED],ISNULL(PARA3.DT_CREATED,'') AS [PARA3_DT_CREATED],        
	'' AS [SKU_DT_CREATED],A.ALIAS AS ARTICLE_ALIAS         
	FROM ARTICLE A       
	JOIN SECTIOND B ON A.SUB_SECTION_CODE = B.SUB_SECTION_CODE      
	JOIN SECTIONM C ON B.SECTION_CODE = C.SECTION_CODE  
	JOIN PARA1  (NOLOCK) ON A.PARA1_CODE= PARA1.PARA1_CODE       
	JOIN PARA2  (NOLOCK) ON A.PARA2_CODE= PARA2.PARA2_CODE     
	JOIN PARA3  (NOLOCK) ON A.PARA3_CODE= PARA3.PARA3_CODE       
	JOIN PARA4  (NOLOCK) ON A.PARA4_CODE= PARA4.PARA4_CODE     
	JOIN PARA5  (NOLOCK) ON A.PARA5_CODE= PARA5.PARA5_CODE       
	JOIN PARA6  (NOLOCK) ON A.PARA6_CODE= PARA6.PARA6_CODE   
	JOIN UOM  (NOLOCK) ON A.UOM_CODE= UOM.UOM_CODE         
	WHERE A.ARTICLE_NO <> '' AND A.INACTIVE=0 AND A.CODING_SCHEME <> 1   
	AND A.ARTICLE_NO LIKE @CWHERE  
	  
	UNION ALL    
	SELECT  TOP 50    A.ARTICLE_CODE, A.ARTICLE_NAME, A1.PRODUCT_CODE AS [ARTICLE_NO],       
	B.SUB_SECTION_NAME, C.SECTION_NAME ,A1.PRODUCT_CODE ,  
	PARA1.PARA1_NAME,PARA2.PARA2_NAME,    
	PARA3.PARA3_NAME,PARA4.PARA4_NAME,PARA5.PARA5_NAME,PARA6.PARA6_NAME,  
	PARA1.PARA1_CODE,PARA2.PARA2_CODE,    
	PARA3.PARA3_CODE,PARA4.PARA4_CODE,PARA5.PARA5_CODE,PARA6.PARA6_CODE,  
	A.PURCHASE_PRICE,A.MRP,A.WHOLESALE_PRICE AS WS_PRICE,UOM.UOM_NAME,A1.BARCODE_CODING_SCHEME AS CODING_SCHEME,  
	ISNULL(A.DT_CREATED,'') AS [ART_DT_CREATED],ISNULL(PARA3.DT_CREATED,'') AS [PARA3_DT_CREATED],        
	ISNULL(A1.DT_CREATED,'') AS [SKU_DT_CREATED],A.ALIAS AS ARTICLE_ALIAS        
	FROM SKU A1       
	JOIN ARTICLE A   ON A.ARTICLE_CODE=A1.ARTICLE_CODE    
	JOIN SECTIOND B ON A.SUB_SECTION_CODE = B.SUB_SECTION_CODE      
	JOIN SECTIONM C ON B.SECTION_CODE = C.SECTION_CODE   
	JOIN PARA1  (NOLOCK) ON A1.PARA1_CODE= PARA1.PARA1_CODE       
	JOIN PARA2  (NOLOCK) ON A1.PARA2_CODE= PARA2.PARA2_CODE     
	JOIN PARA3  (NOLOCK) ON A1.PARA3_CODE= PARA3.PARA3_CODE       
	JOIN PARA4  (NOLOCK) ON A1.PARA4_CODE= PARA4.PARA4_CODE     
	JOIN PARA5  (NOLOCK) ON A1.PARA5_CODE= PARA5.PARA5_CODE       
	JOIN PARA6  (NOLOCK) ON A1.PARA6_CODE= PARA6.PARA6_CODE   
	JOIN UOM  (NOLOCK) ON A.UOM_CODE= UOM.UOM_CODE        
	LEFT OUTER JOIN EAN_SYNC EAN ON EAN.PRODUCT_CODE=A1.PRODUCT_CODE  
	WHERE A.ARTICLE_NO <> '' AND A.INACTIVE=0 AND A1.BARCODE_CODING_SCHEME = 1      
	AND EAN.PRODUCT_CODE IS NULL AND A1.PRODUCT_CODE LIKE @CWHERE 
	  
	  
	UNION ALL    
	  
	SELECT   TOP 50 A.ARTICLE_CODE, A.ARTICLE_NAME, A1.PRODUCT_CODE AS [ARTICLE_NO],       
	B.SUB_SECTION_NAME, C.SECTION_NAME ,A1.PRODUCT_CODE ,  
	PARA1.PARA1_NAME,PARA2.PARA2_NAME,    
	PARA3.PARA3_NAME,PARA4.PARA4_NAME,PARA5.PARA5_NAME,PARA6.PARA6_NAME,  
	PARA1.PARA1_CODE,PARA2.PARA2_CODE,    
	PARA3.PARA3_CODE,PARA4.PARA4_CODE,PARA5.PARA5_CODE,PARA6.PARA6_CODE,  
	A.PURCHASE_PRICE,A.MRP,A.WHOLESALE_PRICE AS WS_PRICE,UOM.UOM_NAME,A1.BARCODE_CODING_SCHEME AS CODING_SCHEME,  
	ISNULL(A.DT_CREATED,'') AS [ART_DT_CREATED],ISNULL(PARA3.DT_CREATED,'') AS [PARA3_DT_CREATED],        
	ISNULL(A1.DT_CREATED,'') AS [SKU_DT_CREATED],A.ALIAS AS ARTICLE_ALIAS       
	FROM SKU A1       
	JOIN ARTICLE A   ON A.ARTICLE_CODE=A1.ARTICLE_CODE    
	JOIN SECTIOND B ON A.SUB_SECTION_CODE = B.SUB_SECTION_CODE      
	JOIN SECTIONM C ON B.SECTION_CODE = C.SECTION_CODE   
	JOIN PARA1  (NOLOCK) ON A1.PARA1_CODE= PARA1.PARA1_CODE       
	JOIN PARA2  (NOLOCK) ON A1.PARA2_CODE= PARA2.PARA2_CODE     
	JOIN PARA3  (NOLOCK) ON A1.PARA3_CODE= PARA3.PARA3_CODE       
	JOIN PARA4  (NOLOCK) ON A1.PARA4_CODE= PARA4.PARA4_CODE     
	JOIN PARA5  (NOLOCK) ON A1.PARA5_CODE= PARA5.PARA5_CODE       
	JOIN PARA6  (NOLOCK) ON A1.PARA6_CODE= PARA6.PARA6_CODE   
	JOIN UOM  (NOLOCK) ON A.UOM_CODE= UOM.UOM_CODE        
	LEFT OUTER JOIN EAN_SYNC EAN ON EAN.PRODUCT_CODE=A1.PRODUCT_CODE  
	WHERE A.ARTICLE_NO <> '' AND A.INACTIVE=0 AND A1.BARCODE_CODING_SCHEME <> 1      
	AND EAN.PRODUCT_CODE IS NULL AND A1.PRODUCT_CODE LIKE @CWHERE  
END
