CREATE procEDURE SP_WSLINV_7--(LocId 3 digit change only increased the parameter width by Sanjay:04-11-2024)
	@CMEMOID	VARCHAR(40) = '',
	@CWHERE1	VARCHAR(500) = '',
	@NNAVMODE	NUMERIC(1,0) = 0,
	@CWHERE2	NVARCHAR(MAX)='',
	@DMEMODT DATETIME='',
	@CLOCID		VARCHAR(4)=''
----WITH ENCRYPTION
AS
BEGIN

	SELECT EMP_CODE, EMP_NAME, EMP_NAME AS EMP_NAME_ORG,0 AS ALIASENTRY   
    FROM EMPLOYEE  (NOLOCK)  
    WHERE INACTIVE = 0  AND EMP_TYPE IN (1,3)
    UNION   
    SELECT EMP_CODE, EMP_ALIAS AS EMP_NAME, EMP_NAME AS EMP_NAME_ORG,1 AS ALIASENTRY    
    FROM EMPLOYEE  (NOLOCK)  
    WHERE INACTIVE = 0  AND EMP_TYPE IN (1,3) AND EMP_ALIAS <>''  
    ORDER BY EMP_NAME   

END