CREATE PROCEDURE SAVETRAN_PO_UPDSKU
(
	@nUpdateMode NUMERIC(2,0),
	@nSpId VARCHAR(40)
)
--WITH ENCRYPTION
AS
BEGIN
	IF @nUpdateMode=1
		RETURN
	
	DECLARE @cStep VARCHAR(10)

	SET @cSTEP = 195.2
	EXEC SP_CHKXNSAVELOG 'PO',@cSTEP,0,@NSPID,'',1
	-- UPDATING OVERHEADS IN SKU_OH TABLE
	UPDATE SKU_OH SET  	
		DISCOUNT_AMOUNT	= ( CASE WHEN GTOT.GROSS_TOTAL<>0 THEN ( ( C.DISCOUNT_AMOUNT + (GTOT.GROSS_TOTAL - C.SUBTOTAL) ) /GTOT.GROSS_TOTAL)*B.PURCHASE_PRICE ELSE 0 END ),  	
		TAX_AMOUNT 		= B.TAX_AMOUNT,  	
		FREIGHT			= ( CASE WHEN GTOT.GROSS_TOTAL<>0 THEN (C.FREIGHT/GTOT.GROSS_TOTAL)*B.PURCHASE_PRICE ELSE 0 END ),  	
		OTHER_CHARGES 	= ( CASE WHEN GTOT.GROSS_TOTAL<>0 THEN (C.OTHER_CHARGES/GTOT.GROSS_TOTAL)*B.PURCHASE_PRICE ELSE 0 END ),  	
		ROUND_OFF		= ( CASE WHEN GTOT.GROSS_TOTAL<>0 THEN (C.ROUND_OFF/GTOT.GROSS_TOTAL)*B.PURCHASE_PRICE ELSE 0 END ),
		EXCISE_DUTY_AMOUNT=	0
	FROM PO_POD01106_UPLOAD B (NOLOCK)  
	JOIN PO_POM01106_UPLOAD C (NOLOCK)  ON B.SP_ID = C.SP_ID  
	JOIN 
	( 	
		SELECT 	SP_ID, SUM(QUANTITY*PURCHASE_PRICE) AS GROSS_TOTAL 	
		FROM PO_POD01106_UPLOAD (NOLOCK) 
		WHERE SP_ID = @nSpId	
		GROUP BY SP_ID  
	) GTOT 
	ON B.SP_ID = GTOT.SP_ID  
	WHERE B.SP_ID  = @nSpId
	AND B.PRODUCT_CODE = SKU_OH.PRODUCT_CODE 

	SET @cSTEP = 195.4
	EXEC SP_CHKXNSAVELOG 'PO',@cSTEP,0,@NSPID,'',1

	-- UPDATING MASTER INFORMATION AND OTHER DETAILS IN SKU TABLE
	UPDATE A SET  	
		ARTICLE_CODE = B.ARTICLE_CODE,  	
		PARA1_CODE = B.PARA1_CODE,  	
		PARA2_CODE = B.PARA2_CODE,  	
		PARA3_CODE = B.PARA3_CODE,  	
		PARA4_CODE = B.PARA4_CODE,  	
		PARA5_CODE = B.PARA5_CODE,  	
		PARA6_CODE = B.PARA6_CODE,  	
		AC_CODE		= C.AC_CODE, 	
		FORM_ID		= B.FORM_ID, 	
		INV_NO		= C.PO_NO, 
		INV_DT		= C.PO_DT,  	
		RECEIPT_DT	= C.PO_DT, 
		PURCHASE_PRICE = B.PURCHASE_PRICE,
		hsn_code =B.hsn_code ,
		alternate_uom_code=b.alternate_uom_code,
		alt_uom_conversion_factor=b.alt_uom_conversion_factor
	FROM SKU A (NOLOCK)
	JOIN PO_POD01106_UPLOAD B (NOLOCK) ON A.PRODUCT_CODE = B.PRODUCT_CODE
	JOIN PO_POM01106_UPLOAD C (NOLOCK) ON B.SP_ID  = C.SP_ID  
	LEFT OUTER JOIN SKU_OH D (NOLOCK) ON A.PRODUCT_CODE = D.PRODUCT_CODE
	WHERE B.SP_ID  = @nSpId
	 
	---UPDATING MRP IN SKU TABLE 
	SET @cSTEP = 195.6
	EXEC SP_CHKXNSAVELOG 'PO',@cSTEP,0,@NSPID,'',1

	UPDATE  A SET A.MRP = B.MRP ,A.WS_PRICE = B.WHOLESALE_PRICE
	FROM SKU A  WITH (ROWLOCK)
	JOIN PO_POD01106_UPLOAD B (NOLOCK) ON A.PRODUCT_CODE=B.PRODUCT_CODE
	JOIN ARTICLE C (NOLOCK) ON B.ARTICLE_CODE=C.ARTICLE_CODE 
	LEFT OUTER JOIN 
	( SELECT DISTINCT a.PRODUCT_CODE FROM IRD01106 a (NOLOCK)
		JOIN irm01106 b (NOLOCK) ON b.irm_memo_id=b.irm_memo_id
		JOIN PO_POD01106_UPLOAD c (NOLOCK) ON A.PRODUCT_CODE = c.PRODUCT_CODE
		WHERE sp_id=@nSpId
	) IRD ON B.PRODUCT_CODE = IRD.PRODUCT_CODE
	WHERE B.SP_ID  = @nSpId
	AND   C.CODING_SCHEME<>1 
	AND   IRD.PRODUCT_CODE IS NULL


END