CREATE PROCEDURE SP_RETAILSALE_6 -- (LocId 3 digit change by Sanjay:30-10-2024)
(  
	 @CQUERYID			NUMERIC(2),  
	 @CWHERE			VARCHAR(MAX)='',  
	 @CFINYEAR			VARCHAR(5)='',  
	 @CDEPTID			VARCHAR(4)='',  
	 @NNAVMODE			NUMERIC(2)=1,  
	 @CWIZAPPUSERCODE	VARCHAR(10)='',  
	 @CREFMEMOID		VARCHAR(40)='',  
	 @CREFMEMODT		DATETIME='',  
	 @BINCLUDEESTIMATE	BIT=1,  
	 @CFROMDT			DATETIME='',  
	 @CTODT				VARCHAR(50)='',
	 @bCardDiscount		BIT=0,
	 @cCustCode			VARCHAR(15)=''
) 
AS  
BEGIN  
		SELECT A.EMP_CODE, EMP_NAME, EMP_NAME AS EMP_NAME_ORG,0 AS ALIASENTRY   
       FROM EMPLOYEE  A(NOLOCK) 
        JOIN EMP_GRP_LINK B (NOLOCK) ON A.emp_code=B.EMP_CODE 
        Join EMPLOYEE_GRP C on B.EMP_GRP_CODE = C.EMP_GRP_CODE 
        WHERE A.INACTIVE = 0    AND EMP_TYPE in (1,3) AND C.dept_id = @CWHERE 
        UNION   
        SELECT A.EMP_CODE, EMP_ALIAS AS EMP_NAME, EMP_NAME AS EMP_NAME_ORG,1 AS ALIASENTRY    
        FROM EMPLOYEE  A(NOLOCK) 
        JOIN EMP_GRP_LINK B (NOLOCK) ON A.emp_code=B.EMP_CODE  
        Join EMPLOYEE_GRP C on B.EMP_GRP_CODE = C.EMP_GRP_CODE 
        WHERE A.INACTIVE = 0 AND EMP_TYPE in (1,3) AND EMP_ALIAS <>''   AND C.dept_id = @CWHERE 
        ORDER BY EMP_NAME   
	
end
