CREATE PROCEDURE SP_BUYERSORDER_WSL_24
@CMEMOID VARCHAR(40),  
@CWHERE VARCHAR(500),  
@CFINYEAR VARCHAR(10),  
@NNAVMODE NUMERIC(2,0),
@CARTICLECODE CHAR(9)='',  
@CPARA2CODE CHAR(7)='',
@DTWHERE DATETIME ='',
@cLocId VARCHAR(5)=''
--WITH ENCRYPTION
 
AS    
BEGIN 

SELECT CONVERT(BIT,0) AS CHK, A.ORDER_ID,B.ADV_REC_ID,C.AMOUNT,A.ORDER_NO,C.ADV_REC_NO ,A.CUSTOMER_CODE,A.AC_CODE 
	FROM BUYER_ORDER_MST A (NOLOCK)
	JOIN WSL_ORDER_ADV_RECEIPT B (NOLOCK) ON A.ORDER_ID = B.ORDER_ID 
	JOIN ARC01106 C (NOLOCK) ON B.ADV_REC_ID = C.ADV_REC_ID 
	WHERE A.CANCELLED = 1 AND (A.CUSTOMER_CODE = @CWHERE OR A.AC_CODE = @CWHERE )

	UNION ALL

	SELECT CONVERT(BIT,0) AS CHK,'' AS ORDER_ID,C.ADV_REC_ID,C.AMOUNT,'' AS ORDER_NO,C.ADV_REC_NO ,C.CUSTOMER_CODE,C.AC_CODE 
	FROM ARC01106 C (NOLOCK)
	LEFT OUTER JOIN WSL_ORDER_ADV_RECEIPT B (NOLOCK) ON C.ADV_REC_ID = B.ADV_REC_ID
	WHERE C.ARCT<> 1 AND C.CANCELLED = 0 AND  ISNULL(B.ADV_REC_ID,'') = '' AND (C.CUSTOMER_CODE = @CWHERE OR C.AC_CODE = @CWHERE )
END