CREATE PROCEDURE SP3S_CAPTURE_AUDIT_TRIAL  
(  
 @XN_TYPE VARCHAR(10)  
,@XN_ID VARCHAR(1000)  
,@XN_HDR_TEMP_TABLE VARCHAR(1000)  
,@XN_DTL_TEMP_TABLE VARCHAR(1000)  
,@XN_SP_ID INT=0  
,@COMPUTER_NAME VARCHAR(1000)  
,@WINUSERNAME VARCHAR(1000)  
,@CWIZUSERCODE VARCHAR(1000)  
,@CANCEL INT=0   
,@XN_CM_DT DATETIME='1900-01-01'  
,@EDIT_CLICKED BIT=0  
)  
AS  
BEGIN  
  SET NOCOUNT ON  
  DECLARE @CWIZUSERNAME VARCHAR(1000)  
    
  IF @XN_TYPE NOT IN ('SLS','PUR','WSL','PRT')  
     RETURN   
    
  DECLARE @SQL VARCHAR(MAX)  
  ,@HDR_TABLE VARCHAR(5000),@DTL_TABLE VARCHAR(5000)  
  ,@HDR_KEY VARCHAR(5000),@DTL_KEY VARCHAR(5000)  
  ,@ROWID VARCHAR(1000),@MODE VARCHAR(100),@CNT_NEW INT,@CNT_OLD INT  
  ,@JOIN_ON VARCHAR(MAX),@FIELDS VARCHAR(1000),@KEY_ID VARCHAR(1000)  
  ,@INS_TABLE VARCHAR(1000),@DEL_TABLE VARCHAR(1000),@TABLE VARCHAR(1000)    
  ,@FIELD VARCHAR(500),@DATA VARCHAR(500),@FIELD_LIST VARCHAR(MAX)  
  ,@PROCESS_HDR BIT,@UPDATED_ON DATETIME  
  ,@TAB VARCHAR(500),@AGE VARCHAR(500),@EDITED BIT  
    
  SET @EDITED=0  
    
  IF @XN_TYPE='SLS'  
     SELECT @HDR_TABLE='CMM01106',@DTL_TABLE='CMD01106'  
  ELSE IF @XN_TYPE='PUR'  
     SELECT @HDR_TABLE='PIM01106',@DTL_TABLE='PID01106'    
  ELSE IF @XN_TYPE='WSL'  
     SELECT @HDR_TABLE='INM01106',@DTL_TABLE='IND01106'    
  ELSE IF @XN_TYPE='PRT'  
     SELECT @HDR_TABLE='RMM01106',@DTL_TABLE='RMD01106'    
    
    
  --SET ROWID   
  --IF NOT EXISTS(SELECT KEY_VALUE FROM AUDIT_XN_MST (NOLOCK) WHERE XN_TYPE=@XN_TYPE)   
  --   INSERT AUDIT_XN_MST SELECT @XN_TYPE,0  
  --UPDATE AUDIT_XN_MST SET KEY_VALUE+=1 WHERE XN_TYPE=@XN_TYPE  
  --SELECT @ROWID='AUDIT-'+UPPER(@XN_TYPE)+'-'+CAST(KEY_VALUE AS VARCHAR)   
  --FROM AUDIT_XN_MST (NOLOCK) WHERE XN_TYPE=@XN_TYPE  
  SET @ROWID=LEFT(NEWID(),40)  
    
  SELECT @CWIZUSERNAME=ISNULL(U.USERNAME,'') FROM USERS U WHERE U.USER_CODE=@CWIZUSERCODE  
    
  IF @CANCEL=1  
     BEGIN  
        SET @UPDATED_ON=GETDATE()  
        INSERT XN_AUDIT_TRIAL_DET WITH (ROWLOCK) (XN_TYPE, TABLE_NAME, KEY_VALUE, FIELD_NAME, DATA_TYPE, TXN_MODE, ID, OLDVAL, NEWVAL, AUDITED_ON, COMPUTER_NAME ,WINUSERNAME ,CWIZUSERCODE,CWIZUSERNAME)  
        SELECT TOP 1 @XN_TYPE,@HDR_TABLE,@XN_ID,'CANCELLED','BIT','CANCEL',@ROWID,'NO','YES',CONVERT(VARCHAR,@UPDATED_ON,113),@COMPUTER_NAME,@WINUSERNAME,@CWIZUSERCODE,@CWIZUSERNAME   
        RETURN  
     END  
       
  IF @CANCEL=4  
     BEGIN   
  INSERT XN_AUDIT_TRIAL_DET WITH (ROWLOCK) (XN_TYPE, TABLE_NAME, KEY_VALUE, FIELD_NAME, DATA_TYPE, TXN_MODE, ID, OLDVAL, NEWVAL, AUDITED_ON, COMPUTER_NAME ,WINUSERNAME ,CWIZUSERCODE,CWIZUSERNAME)  
        SELECT @XN_TYPE,@HDR_TABLE,@XN_ID,'CM_DT','DATETIME','UPDATE',@ROWID  
        ,(SELECT TOP 1 REPLACE(CONVERT(VARCHAR,CM_DT,102),'.','-') FROM CMM01106 (NOLOCK) WHERE CM_ID=@XN_ID)  
        ,REPLACE(CONVERT(VARCHAR,@XN_CM_DT,102),'.','-')  
        ,CONVERT(VARCHAR,GETDATE(),113),@COMPUTER_NAME,@WINUSERNAME,@CWIZUSERCODE,@CWIZUSERNAME  
        RETURN  
     END  
    
  IF ISNULL(@EDIT_CLICKED,0)=0  
     RETURN  
    
  IF @XN_TYPE='WSL'     
     SELECT @XN_HDR_TEMP_TABLE='[##INM_'+CAST(@XN_SP_ID AS VARCHAR)+'_'+@XN_ID+']'  
     ,@XN_DTL_TEMP_TABLE='[##IND_'+CAST(@XN_SP_ID AS VARCHAR)+'_'+@XN_ID+']'  
  
  IF @XN_TYPE='PUR'  
     SELECT @XN_HDR_TEMP_TABLE='[##PIM_'+CAST(@XN_SP_ID AS VARCHAR)+'_'+@XN_ID+']'  
     ,@XN_DTL_TEMP_TABLE='[##PID_'+CAST(@XN_SP_ID AS VARCHAR)+'_'+@XN_ID+']'  
       
  IF @XN_TYPE='PRT'  
     SELECT @XN_HDR_TEMP_TABLE='[##RMM_'+CAST(@XN_SP_ID AS VARCHAR)+'_'+@XN_ID+']'  
     ,@XN_DTL_TEMP_TABLE='[##RMD_'+CAST(@XN_SP_ID AS VARCHAR)+'_'+@XN_ID+']'  
       
  SELECT TOP 1 @HDR_KEY=LEFT(KEY_FIELDS,LEN(KEY_FIELDS)-1) FROM XN_AUDIT_TRIAL_MST (NOLOCK) WHERE XN_TYPE=@XN_TYPE AND TRIG='UPDATE' AND TABLE_NAME=@HDR_TABLE  
  SELECT TOP 1 @DTL_KEY=LEFT(KEY_FIELDS,LEN(KEY_FIELDS)-1) FROM XN_AUDIT_TRIAL_MST (NOLOCK) WHERE XN_TYPE=@XN_TYPE AND TRIG='UPDATE' AND TABLE_NAME=@DTL_TABLE  
    
  SET @SQL='DELETE AUDIT_XN_ID WHERE XN_TYPE='''+@XN_TYPE+''';INSERT AUDIT_XN_ID SELECT TOP 1 '''+@XN_TYPE+''','''+@XN_ID+''''  
  EXEC(@SQL)  
    
  SELECT @HDR_TABLE TAB INTO #TAB   
  UNION   
  SELECT @DTL_TABLE   
  SELECT '_NEW_'AGE INTO #AGE   
  UNION   
  SELECT '_OLD_'  
    
  SET @MODE=''  
   
  IF CURSOR_STATUS('GLOBAL','TTAB') IN (0,1)  
 BEGIN  
   CLOSE TTAB  
   DEALLOCATE TTAB  
 END  
   
  DECLARE TTAB CURSOR FOR   
  SELECT T.TAB,A.AGE FROM #TAB T,#AGE A  
  OPEN TTAB  
  FETCH NEXT FROM TTAB INTO @TAB,@AGE  
  WHILE @@FETCH_STATUS=0  
    BEGIN  
        SET @MODE=''  
        SET @SQL='IF OBJECT_ID(''['+@TAB+@AGE+@XN_ID+']'',''U'') IS NOT NULL'+CHAR(13)+'DROP TABLE ['+@TAB+@AGE+@XN_ID+'];'  
  EXEC(@SQL)  
    
    
  SET @SQL=''  
  /*  
  SELECT @SQL=COALESCE(@SQL,'')+COLUMN_NAME+','  
  FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=@TAB  
    AND DATA_TYPE NOT LIKE 'TIMESTAMP'  
    AND COLUMN_NAME NOT IN ('TS','ROW_SNO')  
  SET @SQL=LEFT(@SQL,LEN(@SQL)-1)  
  SET @SQL='SELECT '+@SQL+' INTO ['+@TAB+@AGE+@XN_ID+'] FROM '  
  +CASE @AGE WHEN '_OLD_' THEN @TAB+' (NOLOCK) '   
     ELSE CASE WHEN @TAB LIKE '%M01106' THEN @XN_HDR_TEMP_TABLE ELSE @XN_DTL_TEMP_TABLE END   
   END  
  +''  
  +' WHERE '+@HDR_KEY+'='''+@XN_ID+''''  
  +CASE @AGE WHEN '_NEW_' THEN CASE WHEN @XN_TYPE IN ('SLS') THEN ' AND SP_ID='+CAST(@XN_SP_ID AS VARCHAR) ELSE '' END ELSE '' END  
  */  
  SET @SQL=''  
  IF @TAB LIKE 'IN%01106'  
     SET @SQL='INV_ID,'  
  IF @TAB LIKE 'PIM01106'  
     SET @SQL='MRR_ID,'  
  IF @TAB LIKE 'PID01106'  
     SET @SQL='MRR_ID,ARTICLE_CODE,ROW_ID,SRNO,'  
  IF @TAB LIKE 'RM%01106'  
     SET @SQL='RM_ID,'  
    
  IF @TAB IN ('CMM01106','CMD01106')    
   SELECT @SQL=COALESCE(@SQL,'')+COLUMN_NAME+','  
   FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=@TAB  
   AND DATA_TYPE NOT LIKE 'TIMESTAMP'  
   AND COLUMN_NAME NOT IN ('TS','ROW_SNO')  
     ELSE  
   SELECT @SQL=COALESCE(@SQL,'')+FIELD_NAME+',' FROM XN_AUDIT_TRIAL_MST (NOLOCK) WHERE TABLE_NAME=@TAB AND TRIG='UPDATE' ORDER BY ORDER_ID     
    
  SET @SQL=LEFT(@SQL,LEN(@SQL)-1)  
  SET @SQL='SELECT '+@SQL+' INTO ['+@TAB+@AGE+@XN_ID+'] FROM '  
  +CASE @AGE WHEN '_OLD_' THEN @TAB+' (NOLOCK) '   
     ELSE CASE WHEN @TAB LIKE '%M01106' THEN @XN_HDR_TEMP_TABLE ELSE @XN_DTL_TEMP_TABLE END   
   END  
  +''  
  +CASE WHEN @TAB IN ('CMM01106','CMD01106') OR @AGE='_OLD_' THEN ' WHERE '+@HDR_KEY+'='''+@XN_ID+'''' ELSE '' END  
  +CASE @AGE WHEN '_NEW_' THEN CASE WHEN @XN_TYPE IN ('SLS') THEN ' AND SP_ID='+CAST(@XN_SP_ID AS VARCHAR) ELSE '' END ELSE '' END  
  PRINT @SQL  
  EXEC(@SQL)  
  --    
        FETCH NEXT FROM TTAB INTO @TAB,@AGE  
    END  
  CLOSE TTAB  
  DEALLOCATE TTAB  
    
  --SET MODE    
  SELECT @CNT_NEW=0,@CNT_OLD=0         
  SELECT TOP 1 @CNT_OLD=I.ROWCNT FROM SYSOBJECTS O JOIN SYSINDEXES I ON O.ID=I.ID AND I.INDID<2 AND O.XTYPE='U' AND O.NAME=''+@DTL_TABLE+'_OLD_'+@XN_ID+''  
  SELECT TOP 1 @CNT_NEW=I.ROWCNT FROM SYSOBJECTS O JOIN SYSINDEXES I ON O.ID=I.ID AND I.INDID<2 AND O.XTYPE='U' AND O.NAME=''+@DTL_TABLE+'_NEW_'+@XN_ID+''  
  IF @MODE=''  
     SET @MODE=CASE WHEN @CNT_NEW<@CNT_OLD THEN 'DELETE' ELSE 'UPDATE' END    
    
  SET @PROCESS_HDR=1   
  --HDR TABLE AUDIT LOG     
  LOG_AUDIT:  
  IF @PROCESS_HDR=1   
     SET @TABLE=@DTL_TABLE  
  ELSE  
     SET @TABLE=@HDR_TABLE  
    
  IF @XN_TYPE IN ('SLS')  
     SELECT @INS_TABLE='['+@TABLE+'_NEW_'+@XN_ID+']'  
           ,@DEL_TABLE='['+@TABLE+'_OLD_'+@XN_ID+']'  
           ,@SQL=''  
  
  IF @XN_TYPE IN ('WSL','PUR','PRT')  
     SELECT @INS_TABLE='['+@TABLE+'_OLD_'+@XN_ID+']'  
           ,@DEL_TABLE='['+@TABLE+'_NEW_'+@XN_ID+']'  
           ,@SQL=''  
  
  SELECT TOP 1 @JOIN_ON=KEY_FIELDS,@FIELDS='',@KEY_ID=KEY_FIELDS  
  FROM XN_AUDIT_TRIAL_MST (NOLOCK)  
  WHERE XN_TYPE=@XN_TYPE AND TABLE_NAME=@TABLE AND TRIG='UPDATE'  
    
    
  SET @KEY_ID=LEFT(@KEY_ID,LEN(@KEY_ID)-1)  
  SET @KEY_ID='I.'+REPLACE(@KEY_ID,'+','+I.')  
    
  WHILE CHARINDEX('+',@JOIN_ON)>0  
    BEGIN  
      SET @FIELDS+='I.'+LEFT(@JOIN_ON,CHARINDEX('+',@JOIN_ON)-1)+'=D.'+LEFT(@JOIN_ON,CHARINDEX('+',@JOIN_ON)-1)+'+'   
      SET @JOIN_ON=SUBSTRING(@JOIN_ON,CHARINDEX('+',@JOIN_ON)+1,1000)  
    END  
  SET @FIELDS=REPLACE(SUBSTRING(@FIELDS,1,LEN(@FIELDS)-1),'+',' AND ')   
  SET @JOIN_ON=@FIELDS  
  SET @UPDATED_ON=GETDATE()  
      
  --CHECK FILEDS ALTERED  
  SET @SQL=''  
  IF CURSOR_STATUS('GLOBAL','FIELD') IN (0,1)  
  BEGIN  
  CLOSE FIELD  
  DEALLOCATE FIELD  
 END  
  DECLARE FIELD CURSOR FOR  
  SELECT FIELD_NAME,DATA_TYPE   
  FROM XN_AUDIT_TRIAL_MST (NOLOCK)  
  WHERE XN_TYPE=@XN_TYPE AND TABLE_NAME=@TABLE AND TRIG='UPDATE'  
  OPEN FIELD  
  FETCH NEXT FROM FIELD INTO @FIELD,@DATA  
  --CREATE TABLE VI_SQL(RTIME DATETIME,SRPT VARCHAR(MAX))  
    
  WHILE @@FETCH_STATUS=0  
    BEGIN  
        
      SET @SQL=CASE @DATA  
                    WHEN 'BIT'     THEN 'ISNULL(I.'+@FIELD+',0)=ISNULL(D.'+@FIELD+',0)'  
                    WHEN 'NUMERIC'  THEN 'ISNULL(I.'+@FIELD+',0)=ISNULL(D.'+@FIELD+',0)'  
                    WHEN 'INT'      THEN 'ISNULL(I.'+@FIELD+',0)=ISNULL(D.'+@FIELD+',0)'  
                    WHEN 'BIGINT'   THEN 'ISNULL(I.'+@FIELD+',0)=ISNULL(D.'+@FIELD+',0)'  
                    WHEN 'CHAR'     THEN 'ISNULL(I.'+@FIELD+','''')=ISNULL(D.'+@FIELD+','''')'  
                    WHEN 'VARCHAR'  THEN 'ISNULL(I.'+@FIELD+','''')=ISNULL(D.'+@FIELD+','''')'  
                    WHEN 'DATETIME' THEN 'ISNULL(I.'+@FIELD+',''1900-01-01'')=ISNULL(D.'+@FIELD+',''1900-01-01'')'  
                    ELSE        'I.'+@FIELD+'=D.'+@FIELD  
               END  
      SET @FIELD_LIST=@SQL                
        
      --UPDATE HDR/DTL  
      SET @SQL='IF EXISTS(SELECT * FROM '+@INS_TABLE+' I JOIN '+@DEL_TABLE+' D ON '+@JOIN_ON+' WHERE NOT '+@FIELD_LIST+')  
             INSERT XN_AUDIT_TRIAL_DET (XN_TYPE, TABLE_NAME, KEY_VALUE, FIELD_NAME, DATA_TYPE, TXN_MODE, ID, OLDVAL, NEWVAL, AUDITED_ON, COMPUTER_NAME ,WINUSERNAME ,CWIZUSERCODE,CWIZUSERNAME)  
             SELECT '''+@XN_TYPE+''','''+@TABLE+''','+CASE @TABLE   
                  WHEN 'PID01106' THEN 'I.MRR_ID+CASE LEN(ISNULL(I.PRODUCT_CODE,'''')) WHEN 0 THEN I.ARTICLE_CODE+I.ROW_ID ELSE I.PRODUCT_CODE END'--REPLACE(REPLACE(@KEY_ID,'+I.ROW_ID',''),'I.PRODUCT_CODE','CASE LEN(ISNULL(I.PRODUCT_CODE,'''')) WHEN 0 THEN I.ARTICLE_CODE+I.ROW_ID ELSE I.PRODUCT_CODE END')  
                  WHEN 'RMD01106' THEN 'I.RM_ID+I.PRODUCT_CODE'/*REPLACE(@KEY_ID,'ROW_ID','RM_ID')*/  
                  WHEN 'IND01106' THEN 'I.INV_ID+I.PRODUCT_CODE'  
                  ELSE @KEY_ID   
                    
               END+','''+@FIELD+''','''+@DATA+''','''+@MODE+''','''+@ROWID+''', D.'+@FIELD+', I.'+@FIELD+','''+CONVERT(VARCHAR,@UPDATED_ON,113)+''','''+@COMPUTER_NAME+''','''+@WINUSERNAME+''','''+@CWIZUSERCODE+''','''+@CWIZUSERNAME+'''   
                FROM '+@INS_TABLE+' I JOIN '+@DEL_TABLE+' D ON '+@JOIN_ON+' WHERE NOT ('+@FIELD_LIST+')'  
      EXEC (@SQL)                  
        
      IF @@ROWCOUNT>0  
      SET @EDITED=1  
     
      SET @SQL='IF NOT EXISTS(SELECT * FROM XN_AUDIT_TRIAL_DET (NOLOCK) WHERE XN_TYPE='''+@XN_TYPE+''' AND ID='''+@ROWID+''' AND FIELD_NAME IN (''TOTAL_AMOUNT''))  
             INSERT XN_AUDIT_TRIAL_DET (XN_TYPE, TABLE_NAME, KEY_VALUE, FIELD_NAME, DATA_TYPE, TXN_MODE, ID, OLDVAL, NEWVAL, AUDITED_ON, COMPUTER_NAME ,WINUSERNAME ,CWIZUSERCODE,CWIZUSERNAME)  
             SELECT TOP 1 '''+@XN_TYPE+''','''+@TABLE+''','+@KEY_ID+','''+@FIELD+''','''+@DATA+''','''+@MODE+''','''+@ROWID+''', D.'+@FIELD+', ''0'','''+CONVERT(VARCHAR,@UPDATED_ON,113)+''','''+@COMPUTER_NAME+''','''+@WINUSERNAME+''','''+@CWIZUSERCODE+'''
,'''+@CWIZUSERNAME+'''   
                FROM '+@DEL_TABLE+' I'  
      SET @SQL=REPLACE(@SQL,'D.','I.')                
      IF @FIELD IN ('TOTAL_AMOUNT') AND @DEL_TABLE LIKE '%M01106%'                                       
      EXEC (@SQL)  
     
   IF @@ROWCOUNT>0  
      SET @EDITED=1  
        
      SET @SQL='IF NOT EXISTS(SELECT * FROM XN_AUDIT_TRIAL_DET (NOLOCK) WHERE XN_TYPE='''+@XN_TYPE+''' AND ID='''+@ROWID+''' AND FIELD_NAME IN (''NET_AMOUNT''))  
             INSERT XN_AUDIT_TRIAL_DET (XN_TYPE, TABLE_NAME, KEY_VALUE, FIELD_NAME, DATA_TYPE, TXN_MODE, ID, OLDVAL, NEWVAL, AUDITED_ON, COMPUTER_NAME ,WINUSERNAME ,CWIZUSERCODE,CWIZUSERNAME)  
             SELECT TOP 1 '''+@XN_TYPE+''','''+@TABLE+''','+@KEY_ID+','''+@FIELD+''','''+@DATA+''','''+@MODE+''','''+@ROWID+''', D.'+@FIELD+', ''0'','''+CONVERT(VARCHAR,@UPDATED_ON,113)+''','''+@COMPUTER_NAME+''','''+@WINUSERNAME+''','''+@CWIZUSERCODE+'''
,'''+@CWIZUSERNAME+'''   
                FROM '+@DEL_TABLE+' I'  
      SET @SQL=REPLACE(@SQL,'D.','I.')                
      IF @FIELD IN ('NET_AMOUNT') AND @DEL_TABLE LIKE '%M01106%'                                       
      EXEC (@SQL)  
     
   IF @@ROWCOUNT>0  
      SET @EDITED=1  
  
      SET @SQL='IF NOT EXISTS(SELECT * FROM XN_AUDIT_TRIAL_DET (NOLOCK) WHERE XN_TYPE='''+@XN_TYPE+''' AND ID='''+@ROWID+''' AND LTRIM(RTRIM(FIELD_NAME)) IN (''DISCOUNT_AMOUNT'') AND TABLE_NAME LIKE ''%M01106%'')  
             INSERT XN_AUDIT_TRIAL_DET (XN_TYPE, TABLE_NAME, KEY_VALUE, FIELD_NAME, DATA_TYPE, TXN_MODE, ID, OLDVAL, NEWVAL, AUDITED_ON, COMPUTER_NAME ,WINUSERNAME ,CWIZUSERCODE,CWIZUSERNAME)  
               SELECT TOP 1 '''+@XN_TYPE+''','''+@TABLE+''','+@KEY_ID+','''+@FIELD+''','''+@DATA+''','''+@MODE+''','''+@ROWID+''', D.'+@FIELD+', ''0'','''+CONVERT(VARCHAR,@UPDATED_ON,113)+''','''+@COMPUTER_NAME+''','''+@WINUSERNAME+''','''+@CWIZUSERCODE+'
'','''+@CWIZUSERNAME+'''   
                FROM '+@DEL_TABLE+' I'  
      SET @SQL=REPLACE(@SQL,'D.','I.')                
      IF @FIELD IN ('DISCOUNT_AMOUNT') AND @DEL_TABLE LIKE '%M01106%' AND 1=2                                       
      EXEC (@SQL)  
     
   IF @@ROWCOUNT>0  
      SET @EDITED=1  
  
   --DELETE FROM DTL  
      SET @SQL='INSERT XN_AUDIT_TRIAL_DET (XN_TYPE, TABLE_NAME, KEY_VALUE, FIELD_NAME, DATA_TYPE, TXN_MODE, ID, OLDVAL, NEWVAL, AUDITED_ON, COMPUTER_NAME ,WINUSERNAME ,CWIZUSERCODE,CWIZUSERNAME)  
    SELECT '''+@XN_TYPE+''','''+@TABLE+''','+CASE @TABLE WHEN 'PID01106' THEN REPLACE(REPLACE(@KEY_ID,'+I.ROW_ID',''),'I.PRODUCT_CODE','CASE LEN(ISNULL(I.PRODUCT_CODE,'''')) WHEN 0 THEN I.ARTICLE_CODE+I.ROW_ID ELSE I.PRODUCT_CODE END')  
                  WHEN 'RMD01106' THEN 'I.RM_ID+I.PRODUCT_CODE'  
                  WHEN 'CMD01106' THEN 'I.CM_ID+I.PRODUCT_CODE'  
                  WHEN 'IND01106' THEN 'I.INV_ID+I.PRODUCT_CODE'  
                  ELSE @KEY_ID   
                  END+','''+@FIELD+''','''+@DATA+''','''+'DELETE'+''','''+@ROWID+''', I.'+@FIELD+', ''DELETED'','''+CONVERT(VARCHAR,@UPDATED_ON,113)+''','''+@COMPUTER_NAME+''','''+@WINUSERNAME+''','''+@CWIZUSERCODE+''','''+@CWIZUSERNAME+''' '  
      SET @SQL+='FROM '+@DEL_TABLE+' I LEFT JOIN '+@INS_TABLE+' D ON '+@JOIN_ON  
      SET @SQL+=CHAR(13)+'WHERE D.'+@FIELD+' IS NULL AND '''+@TABLE+'''='''+@DTL_TABLE+''''  
      EXEC(@SQL)  
        
      IF @@ROWCOUNT>0  
      SET @EDITED=1  
     
   --INSERT FROM DTL  
   SET @KEY_ID=REPLACE(@KEY_ID,'I.','D.')  
      SET @SQL='INSERT XN_AUDIT_TRIAL_DET (XN_TYPE, TABLE_NAME, KEY_VALUE, FIELD_NAME, DATA_TYPE, TXN_MODE, ID, OLDVAL, NEWVAL, AUDITED_ON, COMPUTER_NAME ,WINUSERNAME ,CWIZUSERCODE,CWIZUSERNAME)  
				SELECT '''+@XN_TYPE+''','''+@TABLE+''','+CASE @TABLE WHEN 'PID01106' THEN REPLACE(REPLACE(@KEY_ID,'+I.ROW_ID',''),'I.PRODUCT_CODE','CASE LEN(ISNULL(I.PRODUCT_CODE,'''')) WHEN 0 THEN I.ARTICLE_CODE+I.ROW_ID ELSE I.PRODUCT_CODE END')  
                  WHEN 'RMD01106' THEN REPLACE(@KEY_ID,'D.ROW_ID','D.RM_ID')+'+D.PRODUCT_CODE'   
                  WHEN 'IND01106' THEN 'I.INV_ID+I.PRODUCT_CODE'  
                  ELSE @KEY_ID   
                  END+','''+@FIELD+''','''+@DATA+''','''+@MODE+''','''+@ROWID+''', I.'+@FIELD+', D.'+@FIELD+','''+CONVERT(VARCHAR,@UPDATED_ON,113)+''','''+@COMPUTER_NAME+''','''+@WINUSERNAME+''','''+@CWIZUSERCODE+''','''+@CWIZUSERNAME+''' '  
                  --END+','''+@FIELD+''','''+@DATA+''','''+@MODE+''','''+@ROWID+''', I.'+@FIELD+', ''UPDATED'','''+CONVERT(VARCHAR,@UPDATED_ON,113)+''','''+@COMPUTER_NAME+''','''+@WINUSERNAME+''','''+@CWIZUSERCODE+''','''+@CWIZUSERNAME+''' '  
      SET @SQL+='FROM '+@DEL_TABLE+' I RIGHT JOIN '+@INS_TABLE+' D ON '+@JOIN_ON  
      SET @SQL+=CHAR(13)+'WHERE I.'+@FIELD+' IS NULL AND '''+@TABLE+'''='''+@DTL_TABLE+''''  
      EXEC(@SQL)  
        
      IF @@ROWCOUNT>0  
      SET @EDITED=1  
     
   SET @SQL='UPDATE XN_AUDIT_TRIAL_DET SET OLDVAL=(SELECT TOP 1'+@FIELD+' FROM '+@DEL_TABLE+') WHERE XN_TYPE='''+@XN_TYPE+''' AND ID='''+@ROWID+''' AND TABLE_NAME='''+@TABLE+''' AND FIELD_NAME='''+@FIELD+''''  
   IF @FIELD IN ('NET_AMOUNT','TOTAL_AMOUNT','DISCOUNT_AMOUNT') AND @TABLE LIKE '%M01106'  
          EXEC(@SQL)  
        
      SET @SQL='IF EXISTS(SELECT TOP 1 * FROM ['+@TABLE+'_NEW_'+@XN_ID+'] WHERE ROW_ID LIKE ''LATER%'')  
                   BEGIN  
          DELETE XN_AUDIT_TRIAL_DET WHERE XN_TYPE=''PUR'' AND TABLE_NAME=''PID01106'' AND ID='''+@ROWID+'''  
            
          INSERT XN_AUDIT_TRIAL_DET (XN_TYPE, TABLE_NAME, KEY_VALUE, FIELD_NAME, DATA_TYPE, TXN_MODE, ID, OLDVAL, NEWVAL, AUDITED_ON, COMPUTER_NAME ,WINUSERNAME ,CWIZUSERCODE,CWIZUSERNAME,SRNO)  
          SELECT ''PUR'',''PID01106''  
          ,N.MRR_ID+CASE WHEN LEN(ISNULL(N.PRODUCT_CODE,''''))=0 THEN N.ARTICLE_CODE+CASE WHEN N.ROW_ID LIKE ''%LATER%'' THEN '''' ELSE N.ROW_ID END ELSE N.PRODUCT_CODE END  
       ,'''+@FIELD+''','''+@DATA+''','''+@MODE+''','''+@ROWID+''',''INSERTED'',CAST(CASE WHEN LEN(ISNULL(N.PRODUCT_CODE,''''))=0 THEN N.ARTICLE_CODE+CASE WHEN N.ROW_ID LIKE ''%LATER%'' THEN '''' ELSE N.ROW_ID END ELSE N.PRODUCT_CODE END AS VARCHAR),'''+CONVERT(VARCHAR,@UPDATED_ON,113)+''','''+@COMPUTER_NAME+''','''+@WINUSERNAME+''','''+@CWIZUSERCODE+''','''+@CWIZUSERNAME+''',CAST(N.SRNO AS VARCHAR)  
       FROM (SELECT DISTINCT MRR_ID,ARTICLE_CODE,MRP,PRODUCT_CODE,ROW_ID,SRNO FROM '+@INS_TABLE+')N              
       LEFT JOIN (SELECT DISTINCT MRR_ID,ARTICLE_CODE,MRP,PRODUCT_CODE,ROW_ID,SRNO FROM '+@DEL_TABLE+')O              
       ON N.PRODUCT_CODE=O.PRODUCT_CODE              
       WHERE O.PRODUCT_CODE IS NULL  
         
          INSERT XN_AUDIT_TRIAL_DET (XN_TYPE, TABLE_NAME, KEY_VALUE, FIELD_NAME, DATA_TYPE, TXN_MODE, ID, OLDVAL, NEWVAL, AUDITED_ON, COMPUTER_NAME ,WINUSERNAME ,CWIZUSERCODE,CWIZUSERNAME,SRNO)  
          SELECT ''PUR'',''PID01106''  
          ,N.MRR_ID+CASE WHEN LEN(ISNULL(N.PRODUCT_CODE,''''))=0 THEN N.ARTICLE_CODE+CASE WHEN N.ROW_ID LIKE ''%LATER%'' THEN '''' ELSE N.ROW_ID END ELSE N.PRODUCT_CODE END  
       ,'''+'QUANTITY'+''','''+'NUMERIC1'+''','''+@MODE+''','''+@ROWID+''',''INSERTED'',CAST(N.QUANTITY AS VARCHAR),'''+CONVERT(VARCHAR,@UPDATED_ON,113)+''','''+@COMPUTER_NAME+''','''+@WINUSERNAME+''','''+@CWIZUSERCODE+''','''+@CWIZUSERNAME+''',CAST(N.SRNO AS VARCHAR)  
       FROM (SELECT DISTINCT MRR_ID,ARTICLE_CODE,MRP,PRODUCT_CODE,ROW_ID,SRNO,QUANTITY FROM '+@INS_TABLE+')N              
       LEFT JOIN (SELECT DISTINCT MRR_ID,ARTICLE_CODE,MRP,PRODUCT_CODE,ROW_ID,SRNO,QUANTITY FROM '+@DEL_TABLE+')O              
       ON N.PRODUCT_CODE=O.PRODUCT_CODE              
       WHERE O.PRODUCT_CODE IS NULL  
         
       DELETE XN_AUDIT_TRIAL_DET WITH (ROWLOCK) WHERE XN_TYPE=''PUR'' AND TABLE_NAME=''PID01106'' AND FIELD_NAME NOT IN (''PRODUCT_CODE'',''QUANTITY'') AND ID='''+@ROWID+'''  
       END'         
      IF @TABLE='PID01106' AND @FIELD='PRODUCT_CODE'  
         EXEC(@SQL)  
        
      FETCH NEXT FROM FIELD INTO @FIELD,@DATA  
   END  
  CLOSE FIELD  
  DEALLOCATE FIELD  
  
  IF @XN_TYPE IN ('SLS','PUR','WSL','PRT') AND 1=1  
     BEGIN  
       SET @SQL='DROP TABLE '+@INS_TABLE  
       EXEC(@SQL)    
       SET @SQL='DROP TABLE '+@DEL_TABLE  
       EXEC(@SQL)  
    END  
      
 IF @TABLE=@HDR_TABLE  
    GOTO EXIT_PROC  
 ELSE     
    BEGIN  
      SET @PROCESS_HDR=0  
      GOTO LOG_AUDIT  
    END      
  
 EXIT_PROC:  
 --UPDATE AUDIT_XN_MST WITH (ROWLOCK) SET KEY_VALUE-=1 WHERE XN_TYPE=@XN_TYPE AND @EDITED=0  
 --  
 /*  
 UPDATE X1 SET X1.NEWVAL=CAST(I.DISCOUNT_AMOUNT AS VARCHAR)  
 FROM XN_AUDIT_TRIAL_DET X1 JOIN PIM01106 I(NOLOCK) ON I.MRR_ID=X1.KEY_VALUE  
 WHERE X1.XN_TYPE='PUR'  
 AND X1.ID=(SELECT TOP 1 X2.ID FROM XN_AUDIT_TRIAL_DET X2 WHERE X2.XN_TYPE='PUR' ORDER BY CAST(SUBSTRING(X2.ID,11,5) AS INT) DESC)  
 AND X1.FIELD_NAME='DISCOUNT_AMOUNT'  
 AND LEFT(LTRIM(RTRIM(X1.KEY_VALUE)),LEN(LTRIM(RTRIM(@CMEMOID))))=LTRIM(RTRIM(@CMEMOID))  
 */                 
   
 DELETE XN_AUDIT_TRIAL_DET   
 WHERE XN_TYPE=@XN_TYPE AND ID=@ROWID AND DATA_TYPE='NUMERIC'   
 AND @EDITED=1 AND TABLE_NAME LIKE '%D01106' AND NEWVAL NOT LIKE 'DELETE%'  
 AND LEFT(OLDVAL,1) LIKE '[0-9]%' AND LEFT(NEWVAL,1) LIKE '[0-9]%'  
 AND CAST(ABS(CAST(OLDVAL AS FLOAT)-CAST(NEWVAL AS FLOAT)) AS DECIMAL(14,2))<=0.01   
   
  
 --NEW BARCODE INSERTED IN EDIT  
 DELETE XN_AUDIT_TRIAL_DET   
 WHERE XN_TYPE=@XN_TYPE AND ID=@ROWID  
 AND OLDVAL IS NULL AND FIELD_NAME NOT IN ('PRODUCT_CODE') AND @EDITED=1 AND @XN_TYPE IN ('SLS','PRT','WSL','PRT')  
 AND TABLE_NAME LIKE '%D01106'  
   
 --BARCODE DELETED IN EDIT  
 DELETE XN_AUDIT_TRIAL_DET   
 WHERE XN_TYPE=@XN_TYPE   
 AND ID=@ROWID  
 AND NEWVAL LIKE 'DELETE%'  
 AND FIELD_NAME NOT IN ('PRODUCT_CODE') AND @EDITED=1 AND @XN_TYPE IN ('SLS','PRT','WSL','PRT')  
 AND TABLE_NAME LIKE '%D01106'  
   
 --NEW BARCODE INSERTED IN EDIT  
 UPDATE XN_AUDIT_TRIAL_DET SET OLDVAL='INSERTED'   
 WHERE XN_TYPE=@XN_TYPE AND ID=@ROWID  
 AND OLDVAL IS NULL AND FIELD_NAME IN ('PRODUCT_CODE','QUANTITY') AND @EDITED=1 AND @XN_TYPE IN ('SLS','PRT','WSL','PRT')  
 AND TABLE_NAME LIKE '%D01106'  
   
 --  
 UPDATE X   
 SET X.KEY_VALUE=P.MRR_ID+P.PRODUCT_CODE  
 FROM XN_AUDIT_TRIAL_DET X JOIN PID01106 P (NOLOCK) ON P.MRR_ID+P.PRODUCT_CODE+P.ROW_ID=X.KEY_VALUE  
 WHERE XN_TYPE='PUR' AND ID=@ROWID AND TABLE_NAME='PID01106'  
   
 --@XN_HDR_TEMP_TABLE  
 --  
 SET @CNT_OLD=0  
 SELECT @CNT_OLD=COUNT(*) FROM XN_AUDIT_TRIAL_DET (NOLOCK) WHERE XN_TYPE=@XN_TYPE AND ID=@ROWID AND FIELD_NAME='BILL_LEVEL_TAX_METHOD'  
 IF @CNT_OLD>1  
    BEGIN  
       SET @CNT_OLD-=1  
       SET ROWCOUNT @CNT_OLD  
       DELETE FROM XN_AUDIT_TRIAL_DET WHERE XN_TYPE=@XN_TYPE AND ID=@ROWID AND FIELD_NAME='BILL_LEVEL_TAX_METHOD' AND 1=1  
       SET ROWCOUNT 0  
    END  
   
 UPDATE XN_AUDIT_TRIAL_DET  
 SET KEY_VALUE=@XN_ID  
 ,OLDVAL=REPLACE(REPLACE(OLDVAL,'1','EXCLUSIVE'),'2','INCLUSIVE')  
 ,NEWVAL=REPLACE(REPLACE(NEWVAL,'1','EXCLUSIVE'),'2','INCLUSIVE')   
 WHERE XN_TYPE=@XN_TYPE AND ID=@ROWID AND FIELD_NAME IN ('BILL_LEVEL_TAX_METHOD','OH_TAX_METHOD')  
   
 UPDATE XN_AUDIT_TRIAL_DET  
 SET KEY_VALUE=@XN_ID  
 ,OLDVAL=REPLACE(REPLACE(OLDVAL,'1','BILL LEVEL'),'2','ITEM LEVEL')  
 ,NEWVAL=REPLACE(REPLACE(NEWVAL,'1','BILL LEVEL'),'2','ITEM LEVEL')   
 WHERE XN_TYPE=@XN_TYPE AND ID=@ROWID AND FIELD_NAME IN ('TAXFORM_STORAGE_MODE')  
   
   
 IF EXISTS(SELECT * FROM XN_AUDIT_TRIAL_DET (NOLOCK) WHERE XN_TYPE=@XN_TYPE AND ID=@ROWID AND FIELD_NAME='TOTAL_AMOUNT' AND CAST(OLDVAL AS FLOAT)=CAST(NEWVAL AS FLOAT) AND LEFT(OLDVAL,1) LIKE '[0-9]' AND LEFT(NEWVAL,1) LIKE '[0-9]')  
    IF (SELECT COUNT(*) FROM XN_AUDIT_TRIAL_DET (NOLOCK) WHERE XN_TYPE=@XN_TYPE AND ID=@ROWID)=1 AND 1=1  
       BEGIN  
         DELETE XN_AUDIT_TRIAL_DET WHERE XN_TYPE=@XN_TYPE AND ID=@ROWID  
         UPDATE AUDIT_XN_MST SET KEY_VALUE-=1 WHERE XN_TYPE=@XN_TYPE AND @EDITED=1  
       END  
    ELSE  
       DELETE XN_AUDIT_TRIAL_DET WHERE XN_TYPE=@XN_TYPE AND ID=@ROWID AND FIELD_NAME='TOTAL_AMOUNT' AND 1=1  
   
 UPDATE XN_AUDIT_TRIAL_DET SET NEWVAL=REPLACE(NEWVAL,'.0000','.00'),OLDVAL=REPLACE(OLDVAL,'.0000','.00')  WHERE XN_TYPE=@XN_TYPE AND ID=@ROWID  
 UPDATE XN_AUDIT_TRIAL_DET SET KEY_VALUE=@XN_ID+NEWVAL WHERE XN_TYPE=@XN_TYPE AND ID=@ROWID AND OLDVAL='INSERTED' AND KEY_VALUE IS NULL--INM INSERTION CASE  
 DELETE XN_AUDIT_TRIAL_DET WHERE XN_TYPE=@XN_TYPE AND ID=@ROWID AND NEWVAL LIKE 'DELETE%' AND KEY_VALUE IS NULL AND TABLE_NAME LIKE '%D01106'  
 DELETE XN_AUDIT_TRIAL_DET WHERE XN_TYPE=@XN_TYPE AND ID=@ROWID AND OLDVAL IS NULL AND TABLE_NAME LIKE '%D01106' AND KEY_VALUE LIKE '%LATER%'  
 UPDATE XN_AUDIT_TRIAL_DET SET DATA_TYPE='NUMERIC' WHERE XN_TYPE=@XN_TYPE AND DATA_TYPE='NUMERIC1'  
 SET NOCOUNT OFF  
END
