CREATE PROCEDURE SP_NEVIGATE_ITEM     
@CPRODUCTCODE VARCHAR(50),          
@NNAVMODE  NUMERIC(2,0)  
-- WITH ENCRYPTION
     
AS      
BEGIN  
IF(@NNAVMODE=1)
	BEGIN
	 SELECT TOP 1 PRODUCT_CODE FROM SKU 
	 ORDER BY PRODUCT_CODE ASC
	END
 
ELSE IF(@NNAVMODE=3)
	BEGIN
		IF NOT EXISTS( SELECT TOP 1 PRODUCT_CODE FROM SKU 
		WHERE PRODUCT_CODE>=(SELECT PRODUCT_CODE FROM SKU WHERE PRODUCT_CODE=@CPRODUCTCODE)
		AND PRODUCT_CODE<>@CPRODUCTCODE
		ORDER BY PRODUCT_CODE ASC)
		   SELECT @CPRODUCTCODE AS PRODUCT_CODE
		ELSE
		  SELECT TOP 1 PRODUCT_CODE FROM SKU 
		  WHERE PRODUCT_CODE>=(SELECT PRODUCT_CODE FROM SKU WHERE PRODUCT_CODE=@CPRODUCTCODE)
		  AND PRODUCT_CODE<>@CPRODUCTCODE
		  ORDER BY PRODUCT_CODE ASC
		 
	END

ELSE IF(@NNAVMODE=2)
	BEGIN
		IF NOT EXISTS(SELECT TOP 1 PRODUCT_CODE FROM SKU
		WHERE PRODUCT_CODE<=(SELECT PRODUCT_CODE FROM SKU WHERE PRODUCT_CODE=@CPRODUCTCODE)
		AND PRODUCT_CODE<>@CPRODUCTCODE
		ORDER BY PRODUCT_CODE DESC)
		   SELECT @CPRODUCTCODE AS PRODUCT_CODE
		ELSE 
		SELECT TOP 1 PRODUCT_CODE FROM SKU
		WHERE PRODUCT_CODE<=(SELECT PRODUCT_CODE FROM SKU WHERE PRODUCT_CODE=@CPRODUCTCODE)
		AND PRODUCT_CODE<>@CPRODUCTCODE
		ORDER BY PRODUCT_CODE DESC
	END
	
ELSE IF(@NNAVMODE=4)
	 BEGIN
		 SELECT TOP 1 PRODUCT_CODE FROM SKU ORDER BY PRODUCT_CODE DESC
	 END
 

END
