CREATE PROCEDURE SP_APPROVAL_SETUP    
(    
 @NQUERYID   NUMERIC(5),    
 @CXN_TYPE   VARCHAR(10),    
 @CWHERE    VARCHAR(MAX),
 @DFROMDT DATETIME=''   
)    
AS    
BEGIN    
IF @NQUERYID=1    
 GOTO REPORTS    
ELSE IF @NQUERYID=101    
 GOTO LEVELMST    
ELSE IF @NQUERYID=102    
 GOTO CHECKLISTMST    
ELSE IF @NQUERYID=103    
 GOTO LOCATIONMST     
ELSE IF @NQUERYID=104    
 GOTO USERMST     
ELSE IF @NQUERYID=105    
 GOTO USERLEVEL     
ELSE IF @NQUERYID=106    
 GOTO CHECKLISTLEVELMST     
ELSE IF @NQUERYID=110    
 GOTO APPROVAL_XNTYPE     


APPROVAL_XNTYPE:
	  
		  SELECT XN_TYPE,DISPLAY_NAME,'FRMXNAPPROVAL_'+XN_TYPE AS FORM_NAME
		  FROM
		  (
			  SELECT CAST('PUR' AS VARCHAR(10)) AS XN_TYPE,CAST('PURCHASE INVOICE' AS VARCHAR(50)) AS DISPLAY_NAME UNION 
			  SELECT 'PRT' AS XN_TYPE,'DEBIT NOTE' AS DISPLAY_NAME UNION 
			  SELECT 'PTC' AS XN_TYPE,'PETTY CASH' AS DISPLAY_NAME UNION 
			  SELECT 'SLSCRI' AS XN_TYPE,'CREDIT BILLS' AS DISPLAY_NAME UNION 
			  SELECT 'CRDISS' AS XN_TYPE,'CARD ISSUE' AS DISPLAY_NAME UNION
			  SELECT 'SFT' AS XN_TYPE,'SHIFT' AS DISPLAY_NAME UNION
			  SELECT 'WSL' AS XN_TYPE,'WHOLESALE' AS DISPLAY_NAME UNION
			  SELECT 'GRPWSL' AS XN_TYPE,'WHOLESALE GROUP' AS DISPLAY_NAME UNION
			  SELECT 'EDS' AS XN_TYPE,'EOSS DISCOUNT SHARING APPROVAL' AS DISPLAY_NAME UNION
			  SELECT 'SLSEDT' AS XN_TYPE,'MODIFIED BILL APPROVAL' AS DISPLAY_NAME UNION
			  SELECT 'EOSSDSLS' AS XN_TYPE,'EOSS DISABLED BILLS' AS DISPLAY_NAME UNION
			  SELECT 'VCH' AS XN_TYPE,'VOUCHER ENTRY' AS DISPLAY_NAME UNION
			  SELECT 'PO' AS XN_TYPE,'PURCHASE ORDER APPROVAL' AS DISPLAY_NAME UNION
			  SELECT 'BDGPL' AS XN_TYPE,'BUDGET PLAN' AS DISPLAY_NAME UNION
			  SELECT 'BUYPL' AS XN_TYPE,'BUY PLAN' AS DISPLAY_NAME UNION
			  SELECT 'WSLORD' AS XN_TYPE,'WSL BUYER ORDER' AS DISPLAY_NAME UNION
			  SELECT 'WSR' AS XN_TYPE,'WHOLESALE RETURN' AS DISPLAY_NAME UNION
			  SELECT 'JWI' AS XN_TYPE,'JOB WORK ISSUE' AS DISPLAY_NAME UNION
			  SELECT 'JWR' AS XN_TYPE,'JOB WORK RETURN' AS DISPLAY_NAME UNION
			  SELECT 'EDT' AS XN_TYPE,'SOR TERMS' AS DISPLAY_NAME union
			  SELECT 'ARO' AS XN_TYPE,'Auto Reorder' AS DISPLAY_NAME  UNION
			  SELECT 'EOSSSOR' AS XN_TYPE,'SOR PAYMENT ADVICE' AS DISPLAY_NAME   UNION
			  SELECT 'JC' AS XN_TYPE,'JOB CARD' AS DISPLAY_NAME   UNION
			   SELECT 'WPS' AS XN_TYPE,'WHOLESALE PACKSLIP' AS DISPLAY_NAME 


		  )X
		  ORDER BY DISPLAY_NAME
	GOTO ENDPROC  
REPORTS:    
	SELECT @CXN_TYPE AS [XN_TYPE],A.USER_CODE,A.LEVEL_NO,A.DEPT_ID+'-'+D.DEPT_NAME AS [DEPT_ID],  
	A.LEVEL_CODE,DBO.FN3S_GETLEVELUSERS(C.LEVEL_CODE,@CXN_TYPE,A.DEPT_ID) AS [USERNAME],C.LEVEL_DESC  
	FROM XN_APPROVAL_CHECKLIST_LEVELS C  
	LEFT OUTER JOIN XN_APPROVAL_CHECKLIST_LEVEL_USERS A ON C.LEVEL_CODE=A.LEVEL_CODE  
	LEFT OUTER JOIN USERS B ON B.USER_CODE=A.USER_CODE  
	LEFT OUTER JOIN LOCATION D ON D.DEPT_ID=A.DEPT_ID  
	WHERE ISNULL(C.XN_TYPE,@CXN_TYPE)=@CXN_TYPE   
    
  GOTO ENDPROC    
LEVELMST:    
 SELECT A.*,CONVERT(BIT,(CASE WHEN B.LEVEL_CODE IS  NULL   THEN 0 ELSE 1 END)) AS [LEVEL_USED],CONVERT(BIT,0 ) AS [DELETE1]  
 FROM XN_APPROVAL_CHECKLIST_LEVELS A   
 LEFT OUTER JOIN  
 (  
 SELECT DISTINCT LEVEL_CODE FROM XN_APPROVAL_DONE_MST  WHERE XN_TYPE=@CXN_TYPE  
 )B ON B.LEVEL_CODE=A.LEVEL_CODE   
 WHERE XN_TYPE=@CXN_TYPE    
     
 GOTO ENDPROC    
CHECKLISTMST:    
 SELECT A.*,CONVERT(BIT,(CASE WHEN B.CHECKLIST_CODE IS  NULL   THEN 0 ELSE 1 END)) AS [CHECKLIST_USED],CONVERT(BIT,0 ) AS [DELETE1]  
 FROM XN_APPROVAL_CHECKLIST_MST A   
 LEFT OUTER JOIN  
 (  
 SELECT DISTINCT  CHECKLIST_CODE FROM XN_APPROVAL_CHECKLIST_LEVEL_DETAILS WHERE XN_TYPE=@CXN_TYPE  
 )B ON B.CHECKLIST_CODE=A.CHECKLIST_CODE   
 WHERE A.XN_TYPE=@CXN_TYPE  ORDER BY  A.CHECKLIST_ORDER 
     
 GOTO ENDPROC    
 
CHECKLISTLEVELMST:    
  
SELECT UPPER(@CXN_TYPE) AS [XN_TYPE], X.CHECKLIST_CODE,X.CHECKLIST_DESC,X.LEVEL_CODE,X.LEVEL_DESC,X.LEVEL_NO, X.CHECKLIST_ORDER,   
CAST((CASE WHEN X1.CHECKLIST_CODE IS NULL THEN 0 ELSE 1 END) AS BIT) AS [CHK]  
FROM  
(  
 SELECT  B.CHECKLIST_CODE,B.CHECKLIST_DESC,C.LEVEL_CODE,C.LEVEL_DESC,C.LEVEL_NO,B.CHECKLIST_ORDER   
 FROM XN_APPROVAL_CHECKLIST_MST B , XN_APPROVAL_CHECKLIST_LEVELS C   
 WHERE B.XN_TYPE=@CXN_TYPE AND C.XN_TYPE=@CXN_TYPE   
)X   
LEFT OUTER JOIN  
(  
 SELECT A.CHECKLIST_CODE,A.LEVEL_CODE,B.CHECKLIST_DESC,C.LEVEL_DESC,B.CHECKLIST_ORDER     
 FROM XN_APPROVAL_CHECKLIST_LEVEL_DETAILS A     
 JOIN XN_APPROVAL_CHECKLIST_MST B ON B.CHECKLIST_CODE =A.CHECKLIST_CODE     
 JOIN XN_APPROVAL_CHECKLIST_LEVELS C ON C.LEVEL_CODE =A.LEVEL_CODE  
 WHERE A.XN_TYPE=@CXN_TYPE    
)X1 ON X1.CHECKLIST_CODE=X.CHECKLIST_CODE AND X1.LEVEL_CODE=X.LEVEL_CODE  
ORDER BY  X.CHECKLIST_ORDER  
GOTO ENDPROC    
    
LOCATIONMST:    
 SELECT CONVERT(BIT,CASE WHEN ISNULL(X1.DEPT_ID,'')='' THEN 0 ELSE 1 END) AS [CHK],
(CASE WHEN ISNULL(X1.CUTOFFDATE,'')='' THEN @DFROMDT ELSE X1.CUTOFFDATE END) AS CUTOFFDATE,
ISNULL(X1.ALLOWAUTOPOSTEDENTRY,0) AS ALLOWAUTOPOSTEDENTRY,
 X.DEPT_ID,X.DEPT_NAME,  
 UPPER(@CXN_TYPE) AS [XN_TYPE],  
 (CASE WHEN UPPER(@CXN_TYPE)='PUR' THEN 'PURCHASE'   
    WHEN UPPER(@CXN_TYPE)='PTC' THEN 'PETTY CASH'   
    WHEN UPPER(@CXN_TYPE)='PRT' THEN 'PURCHASE RETURN'   
    WHEN UPPER(@CXN_TYPE)='VCH' THEN 'VOUCHER'   
    WHEN UPPER(@CXN_TYPE)='SLSCRI' THEN 'CREDIT BILLS'   
    WHEN UPPER(@CXN_TYPE)='SLSEDT' THEN 'MODIFIED BILLS'   
    WHEN UPPER(@CXN_TYPE)='CRDISS' THEN 'CARD ISSUE DIFF.'
    WHEN UPPER(@CXN_TYPE)='WBO' THEN 'WHOLE SALE BUYER ORDER' 
	WHEN UPPER(@CXN_TYPE)='JC' THEN 'JOB CARD'   
    ELSE '' END)   AS [MODULE_NAME]  
 FROM    
 (    
  SELECT DEPT_ID,DEPT_NAME     
  FROM LOCATION WHERE INACTIVE=0    
 )X    
 LEFT OUTER JOIN     
 (    
  SELECT A.DEPT_ID ,A.CUTOFFDATE,A.ALLOWAUTOPOSTEDENTRY
  FROM LOC_XNSAPPROVAL A     
  JOIN LOCATION B ON B.DEPT_ID=A.DEPT_ID     
  WHERE A.XN_TYPE=@CXN_TYPE    
 )X1 ON X1.DEPT_ID=X.DEPT_ID    
 ORDER BY DEPT_ID    
     
 GOTO ENDPROC    
USERMST:    
  SELECT B.XN_TYPE, A.DEPT_ID,A.USER_CODE,C.USERNAME     
 FROM LOCUSERS A    
 JOIN LOC_XNSAPPROVAL B ON B.DEPT_ID=A.DEPT_ID   
 JOIN USERS C ON C.USER_CODE=A.USER_CODE   
 WHERE B.XN_TYPE= @CXN_TYPE  
 order by C.USERNAME
 GOTO ENDPROC     
USERLEVEL:    
   
 SELECT X.XN_TYPE,X.DEPT_ID,X.LEVEL_CODE,X.LEVEL_NO,X.LEVEL_DESC,X.USER_CODE ,X.USERNAME ,  
 (CASE WHEN X1.LEVEL_CODE IS NULL THEN 0 ELSE 1 END) AS [CHK_LEVEL],  
 (CASE WHEN X1.USER_CODE IS NULL THEN 0 ELSE 1 END) AS [CHK_USER]  
 FROM   
 (  
  SELECT A.XN_TYPE,A.DEPT_ID,B.LEVEL_CODE,B.LEVEL_NO,B.LEVEL_DESC,C.USER_CODE ,D.USERNAME  
  FROM LOC_XNSAPPROVAL A  
  JOIN XN_APPROVAL_CHECKLIST_LEVELS B ON 1=1 AND B.XN_TYPE=@CXN_TYPE  
  JOIN LOCUSERS C ON C.DEPT_ID=A.DEPT_ID  
  JOIN USERS D ON D.USER_CODE=C.USER_CODE  
  WHERE A.XN_TYPE=@CXN_TYPE  
 )X  
 LEFT OUTER JOIN   
 (  
  SELECT A.XN_TYPE,A.DEPT_ID,B.LEVEL_CODE,B.LEVEL_NO,B.LEVEL_DESC,A.USER_CODE ,D.USERNAME  
  FROM XN_APPROVAL_CHECKLIST_LEVEL_USERS A  
  JOIN XN_APPROVAL_CHECKLIST_LEVELS B ON A.LEVEL_NO=B.LEVEL_NO AND  B.XN_TYPE=@CXN_TYPE  
  JOIN USERS D ON D.USER_CODE=A.USER_CODE  
  WHERE A.XN_TYPE=@CXN_TYPE  
 )X1 ON X1.LEVEL_CODE=X.LEVEL_CODE AND X1.DEPT_ID = X.DEPT_ID AND X1.USER_CODE=X.USER_CODE  
 
 GOTO ENDPROC     
    
ENDPROC:    
     
END
