CREATE PROCEDURE SPPPC_VALIDATE_ORDER
(
  @CBILL_NO VARCHAR(100)=''
)
AS
BEGIN
   
   DECLARE @CERRMSG VARCHAR(1000)
   SET @CERRMSG=''
   IF EXISTS (SELECT TOP 1 'U' FROM PPC_BUYER_ORDER_MST WHERE BILL_NO=@CBILL_NO)
   BEGIN
        SET @CERRMSG='ORDER NO ALREDY EXISTS PLEASE CHECK'
   END
   
   SELECT @CERRMSG ERRMSG
END
