CREATE PROCEDURE SP_STOCKNAPRODUCTCODESETTLEMENT--(LocId 3 digit change by Sanjay:30-10-2024)
(      
	@NQUERYID NUMERIC(2,0),       
	@CWHERE  NVARCHAR(MAX),  
	@CFROMDT  DATETIME='',     
	@CTODT  DATETIME='' ,
	@CLOCID VARCHAR(4)=''          
)  
AS      
BEGIN      
DECLARE @CCMD NVARCHAR(MAX),@CDEPT_ID VARCHAR(4)      
      
IF @NQUERYID = 1      
	GOTO LBLMST     
      
ELSE IF @NQUERYID = 2      
	GOTO LBLDET      
      
ELSE IF @NQUERYID = 3      
	GOTO LBLCMMDET      
  
ELSE      
	GOTO LAST      
         
LBLMST:      
      
SELECT A.*,U1.USERNAME AS CREATEDBY,U2.USERNAME AS MODIFIEDBY  
FROM SLS_STOCK_NA_REP_MST A (NOLOCK)  
JOIN USERS U1 (NOLOCK) ON U1.USER_CODE=A.USER_CODE  
LEFT OUTER JOIN USERS U2  (NOLOCK) ON U2.USER_CODE=A.EDT_USER_CODE  
WHERE MEMO_ID=@CWHERE  
       
GOTO LAST      
       
LBLDET:      
    SELECT DET.*,CAST(0 AS INT) AS SRNO,   
    EMP.EMP_NAME, B.ARTICLE_CODE, B.ARTICLE_NO, B.ARTICLE_NAME, C.PARA1_CODE,      
    C.PARA1_NAME, D.PARA2_CODE, D.PARA2_NAME, F.PARA3_CODE, F.PARA3_NAME, E.UOM_NAME,         
    A.DEPT_ID, B.CODING_SCHEME,  B.INACTIVE,ISNULL(P.QUANTITY_IN_STOCK,0) AS QUANTITY_IN_STOCK ,     
    SKU.PURCHASE_PRICE,  SKU.MRP,SKU.WS_PRICE,   SM.SECTION_NAME, SD.SUB_SECTION_NAME,      
    G.PARA4_CODE,H.PARA5_CODE,I.PARA6_CODE,CMM.CM_NO,CMM.DISCOUNT_PERCENTAGE AS MST_DISCOUNT_PERCENTAGE,CMM.DISCOUNT_AMOUNT AS MST_DISCOUNT_AMOUNT,           
    PARA4_NAME,PARA5_NAME,PARA6_NAME,E.UOM_CODE,ISNULL(E.UOM_TYPE,0) AS [UOM_TYPE],      
    B.DT_CREATED AS [ART_DT_CREATED],F.DT_CREATED AS [PARA3_DT_CREATED],SKU.DT_CREATED AS [SKU_DT_CREATED],      
    B.STOCK_NA,     
  CONVERT (BIT,(CASE WHEN A.QUANTITY <0 THEN 1 ELSE 0 END)) AS SALERETURN ,CAST(0 AS BIT) AS CREDIT_REFUND,    
  '' AS HOLD_ID,'' AS CMD_HOLD_ROW_ID, A.MRP AS [LOCSKU_MRP],SKU.PRODUCT_NAME,    
   EMP1.EMP_NAME AS EMP_NAME1 ,EMP2.EMP_NAME AS EMP_NAME2  ,(CASE WHEN ISNULL(SKU.FIX_MRP,0)=0 THEN SKU.MRP ELSE SKU.FIX_MRP END) AS [FIX_MRP],  
   (CASE WHEN ISNULL(A.HOLD_FOR_ALTER,0)=0 THEN 'N' ELSE 'Y' END) AS [HOLD_FOR_ALTER_TXT],  
   (CASE WHEN ISNULL(A.PACK_SLIP_ID,'')='' THEN '' ELSE RIGHT(A.PACK_SLIP_ID,10 ) END) AS [PACK_SLIP_NO]  
   ,ISNULL(BIN.BIN_NAME,'') AS [BIN_NAME],B.ALIAS AS ARTICLE_ALIAS ,SD.SUB_SECTION_CODE,SM.SECTION_CODE,  
   CONVERT(BIT,0 ) AS [BRANDWISE_DISC],DBO.FN_GETSLSTITLE(1,A.ROW_ID) AS SLS_TITLE,ISNULL(N.NARRATION,'') AS [NARRATION]   ,
   CMM.REMARKS,A.item_desc 
   FROM SLS_STOCK_NA_REP_DET DET (NOLOCK)  
   JOIN sls_stock_na_rep_mst MST (NOLOCK) ON MST.memo_id=DET.memo_id
  JOIN CMD01106  A  (NOLOCK) ON DET.CMD_ROW_ID=A.ROW_ID  
  JOIN CMM01106 CMM (NOLOCK) ON CMM.CM_ID=A.CM_ID  
  JOIN SKU  (NOLOCK) ON SKU.PRODUCT_CODE=A.PRODUCT_CODE    
  LEFT OUTER JOIN PMT01106 P  (NOLOCK) ON P.PRODUCT_CODE=A.PRODUCT_CODE AND P.BIN_ID=A.BIN_ID  And mst.location_code=p.dept_id
  LEFT OUTER JOIN BIN (NOLOCK) ON BIN.BIN_ID=A.BIN_ID    
  JOIN ARTICLE B  (NOLOCK) ON SKU.ARTICLE_CODE = B.ARTICLE_CODE        
  JOIN SECTIOND SD  (NOLOCK) ON B.SUB_SECTION_CODE = SD.SUB_SECTION_CODE      
  JOIN SECTIONM SM  (NOLOCK) ON SD.SECTION_CODE = SM.SECTION_CODE      
  JOIN PARA1 C  (NOLOCK) ON SKU.PARA1_CODE = C.PARA1_CODE        
  JOIN PARA2 D  (NOLOCK) ON SKU.PARA2_CODE = D.PARA2_CODE        
  JOIN PARA3 F  (NOLOCK) ON SKU.PARA3_CODE = F.PARA3_CODE        
  JOIN PARA4 G  (NOLOCK) ON SKU.PARA4_CODE = G.PARA4_CODE        
  JOIN PARA5 H  (NOLOCK) ON SKU.PARA5_CODE = H.PARA5_CODE        
  JOIN PARA6 I  (NOLOCK) ON SKU.PARA6_CODE = I.PARA6_CODE        
  JOIN UOM E  (NOLOCK) ON B.UOM_CODE = E.UOM_CODE   
  LEFT OUTER JOIN NRM N (NOLOCK) ON N.NRM_ID=ISNULL(A.NRM_ID  ,'0000000')  
  LEFT OUTER JOIN EMPLOYEE EMP  (NOLOCK) ON A.EMP_CODE = EMP.EMP_CODE     
  LEFT OUTER JOIN EMPLOYEE EMP1  (NOLOCK) ON A.EMP_CODE1 = EMP1.EMP_CODE       
  LEFT OUTER JOIN EMPLOYEE EMP2  (NOLOCK) ON A.EMP_CODE2 = EMP2.EMP_CODE   
  WHERE DET.MEMO_ID=@CWHERE  
  
 GOTO LAST      
      
LBLCMMDET:    
    SELECT TOP 1 @CFROMDT=VALUE FROM CONFIG WHERE CONFIG_OPTION='STOCK_NA_CUT_OFF_DATE' 
    
    IF @CLOCID=''
       SELECT TOP 1 @CDEPT_ID=DEPT_ID FROM NEW_APP_LOGIN_INFO (nolock) WHERE SPID=@@SPID 
    ELSE
       SET @CDEPT_ID=@CLOCID
    
    IF OBJECT_ID('tempdb..#tmpPending','U') IS NOT NULL
		DROP TABLE  #tmpPending   
    
    SELECT a.row_id INTO #tmpPending FROM cmd01106 a (NOLOCK)
    LEFT JOIN SLS_STOCK_NA_REP_DET SSN(NOLOCK) ON A.ROW_ID=SSN.CMD_ROW_ID  
	join sku (nolock) on a.PRODUCT_CODE =sku.product_code 
	join article art (nolock) on art.article_code =sku.article_code
    --JOIN SKU_NAMES SKU (NOLOCK) ON SKU.PRODUCT_CODE=A.PRODUCT_CODE    
    JOIN cmm01106 cmm (NOLOCK) ON cmm.cm_id=a.cm_id
    WHERE isnull(art.STOCK_NA,0)=1 
	      and isnull(art.Consider_For_Post_Estimate ,0)=0
	AND SSN.CMD_ROW_ID IS NULL AND CMM.CANCELLED=0 AND CMM.CM_DT BETWEEN @CFROMDT AND @CTODT 
    AND cmm.location_Code=@CDEPT_ID  --AND  A.QUANTITY>0 /* ROHIT 29-04-2022   AGAINST TICKET NO : 04-2050 CLIENT INDRAPRASHTHA */
  
    SELECT  A.*,A.SR_NO AS SRNO, '' AS NEW_PRODUCT_CODE,A.ROW_ID AS CMD_ROW_ID,   
    EMP.EMP_NAME, A.PRODUCT_CODE AS OLD_PRODUCT_CODE, '' as ARTICLE_CODE, ARTICLE_NO, ARTICLE_NAME, '' as PARA1_CODE,      
    PARA1_NAME, '' as PARA2_CODE, PARA2_NAME, '' as PARA3_CODE, PARA3_NAME, '' as UOM_NAME,         
    A.DEPT_ID, 0 as CODING_SCHEME,  0 as INACTIVE,ISNULL(P.QUANTITY_IN_STOCK,0) AS QUANTITY_IN_STOCK ,     
    SKU.pp as PURCHASE_PRICE, SKU.MRP,SKU.WS_PRICE, SECTION_NAME, SUB_SECTION_NAME,      
    '' as PARA4_CODE,'' as PARA5_CODE,'' as PARA6_CODE,CMM.CM_NO,CMM.CM_DT, CMM.DISCOUNT_PERCENTAGE AS MST_DISCOUNT_PERCENTAGE,CMM.DISCOUNT_AMOUNT AS MST_DISCOUNT_AMOUNT,     
    PARA4_NAME,PARA5_NAME,PARA6_NAME,'' as UOM_CODE,0 as  [UOM_TYPE],      
    '' as  [ART_DT_CREATED],'' as  [PARA3_DT_CREATED],'' as  [SKU_DT_CREATED],      
    STOCK_NA,     
  CONVERT (BIT,(CASE WHEN A.QUANTITY <0 THEN 1 ELSE 0 END)) AS SALERETURN ,CAST(0 AS BIT) AS CREDIT_REFUND,    
  '' AS HOLD_ID,'' AS CMD_HOLD_ROW_ID, A.MRP AS [LOCSKU_MRP],sub_section_name as PRODUCT_NAME,    
   EMP1.EMP_NAME AS EMP_NAME1 ,EMP2.EMP_NAME AS EMP_NAME2  ,
   SKU.MRP AS [FIX_MRP],  
   (CASE WHEN ISNULL(A.HOLD_FOR_ALTER,0)=0 THEN 'N' ELSE 'Y' END) AS [HOLD_FOR_ALTER_TXT],  
   (CASE WHEN ISNULL(A.PACK_SLIP_ID,'')='' THEN '' ELSE RIGHT(A.PACK_SLIP_ID,10 ) END) AS [PACK_SLIP_NO]  
   ,ISNULL(BIN.BIN_NAME,'') AS [BIN_NAME],'' AS ARTICLE_ALIAS ,'' as SUB_SECTION_CODE,'' as SECTION_CODE,  
   CONVERT(BIT,0 ) AS [BRANDWISE_DISC],DBO.FN_GETSLSTITLE(1,A.ROW_ID) AS SLS_TITLE,ISNULL(N.NARRATION,'') AS [NARRATION]  ,
  CMM.REMARKS,A.item_desc 
  FROM CMD01106  A  (NOLOCK)   
  JOIN CMM01106 CMM (NOLOCK) ON CMM.CM_ID=A.CM_ID  
  JOIN #tmpPending pn (NOLOCK) ON pn.ROW_ID=a.ROW_ID
  JOIN SKU_NAMES SKU  (NOLOCK) ON SKU.PRODUCT_CODE=A.PRODUCT_CODE    
  LEFT OUTER JOIN PMT01106 P  (NOLOCK) ON P.PRODUCT_CODE=A.PRODUCT_CODE AND P.BIN_ID=A.BIN_ID AND P.DEPT_ID=cmm.location_code  
  LEFT OUTER JOIN BIN (NOLOCK) ON BIN.BIN_ID=A.BIN_ID    
  LEFT OUTER JOIN NRM N (NOLOCK) ON N.NRM_ID=ISNULL(A.NRM_ID  ,'0000000')  
  LEFT OUTER JOIN EMPLOYEE EMP  (NOLOCK) ON A.EMP_CODE = EMP.EMP_CODE     
  LEFT OUTER JOIN EMPLOYEE EMP1  (NOLOCK) ON A.EMP_CODE1 = EMP1.EMP_CODE       
  LEFT OUTER JOIN EMPLOYEE EMP2  (NOLOCK) ON A.EMP_CODE2 = EMP2.EMP_CODE      
  ORDER BY  CMM.CM_DT,CMM.CM_NO,A.SR_NO  
GOTO LAST    
          
LAST:      
    
END      
--END OF PROCEDURE - SP_STOCKNAPRODUCTCODESETTLEMENT
/*
EXEC SP_STOCKNAPRODUCTCODESETTLEMENT_chk 3,'','2018-04-01','2019-08-29','02'

select * into #tmpslsna from SLS_STOCK_NA_REP_DET where cmd_row_id='021E979EEC-324D-4F2E-972E-2A47B3E0935B'

delete from SLS_STOCK_NA_REP_DET where cmd_row_id='021E979EEC-324D-4F2E-972E-2A47B3E0935B'


INSERT SLS_STOCK_NA_REP_DET	( bin_id, cm_dt, cmd_row_id, memo_id, mrp, new_product_code, old_product_code, quantity,
 row_id, tax_percentage )  
 SELECT bin_id, cm_dt, cmd_row_id, memo_id, mrp, new_product_code, old_product_code, quantity, row_id, tax_percentage 
 FROM #tmpslsna

select * from #tmpslsna
update cmd01106 set product_code='8907842363350' where row_id='021E979EEC-324D-4F2E-972E-2A47B3E0935B'

select a.* from SLS_STOCK_NA_REP_DET a
join cmd01106 b on a.cmd_row_id=b.row_id
join sku_names c on c.product_Code=b.product_code
where stock_na=1

select a.cm_id, stock_na, cm_dt,a.* from cmd01106 a join cmm01106 b on a.cm_id=b.cm_id 
join sku_names c on c.product_Code=a.product_code where row_id='021E979EEC-324D-4F2E-972E-2A47B3E0935B'
and cancelled=0 


select * from sku_names where stock_na=1
*/
