CREATE PROCEDURE SP_JOB_CARD_BARCODE_PRINT(@MEMO_ID VARCHAR(40))
AS
BEGIN
SET NOCOUNT ON
SELECT DISTINCT OPM.MEMO_ID,OPM.MEMO_NO,OPM.MEMO_DT,LMV01106.AC_NAME,LOC.DEPT_NAME,BIN.BIN_NAME,OPM.ORD_PLAN_MODE,OPD.WOD_ROW_ID,
SECTIONM.SECTION_NAME,SECTIOND.SUB_SECTION_NAME,PARA1.PARA1_NAME COLOR,PARA2.PARA2_NAME SIZE,PARA3.PARA3_NAME STYLE,
ARTICLE.ARTICLE_NAME,OPD.QUANTITY
FROM ORD_PLAN_MST OPM (NOLOCK)
JOIN ORD_PLAN_DET OPD (NOLOCK) ON OPM.MEMO_ID=OPD.MEMO_ID
JOIN ORD_PLAN_BARCODE_DET OBAR (NOLOCK) ON OBAR.REFROW_ID=OPD.ROW_ID
JOIN LOCATION LOC (NOLOCK) ON LOC.DEPT_ID=OPM.DEPT_ID
LEFT JOIN LMV01106 (NOLOCK) ON LMV01106.AC_CODE=OPM.AC_CODE
JOIN JOBWORK_PMT PMT ON PMT.PRODUCT_CODE=OBAR.PRODUCT_CODE AND OPD.BIN_ID=PMT.BIN_ID AND OPM.DEPT_ID=PMT.DEPT_ID
JOIN SKU ON SKU.PRODUCT_CODE=PMT.PRODUCT_CODE
JOIN ARTICLE (NOLOCK) ON SKU.ARTICLE_CODE = ARTICLE.ARTICLE_CODE         
JOIN PARA1 (NOLOCK) ON SKU.PARA1_CODE = PARA1.PARA1_CODE        
JOIN PARA2 (NOLOCK) ON SKU.PARA2_CODE = PARA2.PARA2_CODE        
JOIN PARA3 (NOLOCK) ON SKU.PARA3_CODE = PARA3.PARA3_CODE        
JOIN PARA4 (NOLOCK) ON SKU.PARA4_CODE = PARA4.PARA4_CODE        
JOIN PARA5 (NOLOCK) ON SKU.PARA5_CODE = PARA5.PARA5_CODE        
JOIN PARA6 (NOLOCK) ON SKU.PARA6_CODE = PARA6.PARA6_CODE        
JOIN UOM   (NOLOCK) ON ARTICLE.UOM_CODE = UOM.UOM_CODE        
JOIN SECTIOND (NOLOCK) ON ARTICLE.SUB_SECTION_CODE = SECTIOND.SUB_SECTION_CODE        
JOIN SECTIONM (NOLOCK) ON SECTIOND.SECTION_CODE = SECTIONM.SECTION_CODE     
JOIN BIN  (NOLOCK) ON BIN.BIN_ID=ISNULL(PMT.BIN_ID,'000') 
WHERE OPM.MEMO_ID=@MEMO_ID
SET NOCOUNT OFF
END
