CREATE PROCEDURE SP_SEND_MIRROR_MSTEAN_NEW
@CTARGETLOCID VARCHAR(5)
----WITH ENCRYPTION
AS
BEGIN

    DECLARE @DTSQL NVARCHAR(MAX),@CSTEP VARCHAR(10),@CFILTERCONDITION NVARCHAR(MAX),@DMEMOLASTUPDATE DATETIME
           ,@CXNTYPE VARCHAR(10),@CMEMOID VARCHAR(100),@CTABLENAME VARCHAR(100),@CTEMPTABLE VARCHAR(100)
           ,@BRECFOUND BIT,@CTEMPSKUTABLE VARCHAR(100),@CTEMPLMTABLE VARCHAR(100),@TMP_AREA VARCHAR(100)
           ,@CTEMPLMPTABLE VARCHAR(100),@CTEMPDBNAME VARCHAR(200),@CLOCMSTLUPD VARCHAR(20),@CCURDEPTID VARCHAR(5)
           ,@CHODEPTID VARCHAR(5),@NRECCOUNT INT,@CERRORMSG VARCHAR(MAX),@CREPLOCTABLE VARCHAR(500),@NLOCTYPE INT
           ,@CLOCMERGINGTHRUWIZCOM VARCHAR(2),@CPRINTMSTTEMPTABLE VARCHAR(400),@CTILLLOCSTEMPTABLE VARCHAR(200) 
           ,@CPARTYRATEMSTTEMPTABLE VARCHAR(500)
           ,@CEMP_GRP_LINKTEMPTABLE VARCHAR(400),@CEMPLOYEE_GRPTEMPTABLE VARCHAR(400),
           @CEMPLOYEETEMPTABLE VARCHAR(400),@CEMPCATEGORYTEMPTABLE VARCHAR(400),@CEMP_GRP_LINKTEMPTABLE1 VARCHAR(400)
     
    DECLARE @TXNSSENDINFO TABLE (ORG_TABLENAME VARCHAR(100),TMP_TABLENAME VARCHAR(100),ERRMSG VARCHAR(MAX)) 
    
    BEGIN TRY
    
	SET @CSTEP=0

	SET @CTEMPDBNAME = ''
	SET @CSTEP=10
	
	PRINT @CSTEP+':'+CONVERT(VARCHAR,GETDATE(),113)
	SET @CFILTERCONDITION=''
	SET @CSTEP=20

	SELECT @CCURDEPTID = VALUE FROM CONFIG WHERE CONFIG_OPTION='LOCATION_ID'
	SELECT @CHODEPTID = VALUE FROM CONFIG WHERE CONFIG_OPTION='HO_LOCATION_ID'		
	
	SELECT @NLOCTYPE=LOC_TYPE FROM LOCATION WHERE DEPT_ID=@CTARGETLOCID
	
	PRINT @CSTEP+':'+CONVERT(VARCHAR,GETDATE(),113)
	
	IF @CCURDEPTID<>@CHODEPTID
	BEGIN
		SELECT '' AS LAST_UPDATE,'' AS ERRMSG
		GOTO END_PROC
	END		
	
	SET @CSTEP =60
	SET @CTABLENAME ='EAN_SYNC'

	SELECT DISTINCT  'MSTEAN_EAN_SYNC_MIRROR' AS TARGET_TABLENAME,EAN_SYNC.*,1 AS PICK_FROM_CURRENT_DB FROM EAN_SYNC (NOLOCK)


	GOTO END_PROC
     
END TRY

BEGIN CATCH
	SET @CERRORMSG='P: SP_SEND_MIRROR_MSTEAN, STEP:'+@CSTEP+', MESSAGE:'+ERROR_MESSAGE()
	GOTO END_PROC
END CATCH 	
	
END_PROC:

	SELECT ISNULL(@CERRORMSG,'') AS ERRMSG
 END

------------- END OF PROCEDURE SP_SEND_MIRROR_MSTEMP
