CREATE PROCEDURE SP3S_PRD_WO_DETAILS
(
 @CFM_DT DATETIME ='',
 @CTODT DATETIME='',
 @AC_CODE VARCHAR(100)='',
 @CORDER_ID VARCHAR(100)=''
)
AS
BEGIN
    
    
  IF OBJECT_ID ('TEMPDB..#TMPORDER','U') IS NOT NULL
   DROP TABLE #TMPORDER
   
  SELECT A.MEMO_ID AS ORDER_ID,A.MEMO_NO AS ORDER_NO ,A.MEMO_DT AS ORDER_DT
  INTO #TMPORDER
  FROM PRD_WO_MST A (NOLOCK) 
  WHERE A.CANCELLED =0
  AND (@CORDER_ID='' OR A.MEMO_ID =@CORDER_ID)
  
  IF OBJECT_ID ('TEMPDB..#TMPOPS','U') IS NOT NULL
     DROP TABLE #TMPOPS
  
  SELECT T1.REF_PRD_WORKORDER_MEMOID AS ORDER_ID,
  ISNULL(SUM(CASE WHEN UOM.UOM_NAME='PCS' THEN (T1.QUANTITY) ELSE 0 END),0)-ISNULL(SUM(CASE WHEN UOM.UOM_NAME='PCS' THEN (T4.REC_QTY) ELSE 0 END),0)  AS OPS_PCS_QTY,
  ISNULL(SUM(CASE WHEN UOM.UOM_NAME='MTR' THEN (T1.QUANTITY) ELSE 0 END),0)-ISNULL(SUM(CASE WHEN UOM.UOM_NAME='MTR' THEN (T4.REC_QTY) ELSE 0 END) ,0)  AS OPS_MTR_QTY
  INTO #TMPOPS
  FROM PRD_AGENCY_ISSUE_MATERIAL_DET (NOLOCK) T1                 
  JOIN ARTICLE (NOLOCK) T2 ON T1.ARTICLE_CODE = T2.ARTICLE_CODE                
  JOIN UOM  (NOLOCK) ON T2.UOM_CODE = UOM.UOM_CODE                             
  JOIN PRD_AGENCY_ISSUE_MATERIAL_MST (NOLOCK) T5 ON T5.MEMO_ID=T1.MEMO_ID          
  LEFT OUTER JOIN           
  (           
   SELECT DT.XN_PRODUCT_UID,DT.REF_ROW_ID,SUM(ISNULL(DT.QUANTITY,0)) AS REC_QTY            
   FROM PRD_AGENCY_MATERIAL_RECEIPT_DET (NOLOCK) DT          
   JOIN PRD_AGENCY_MATERIAL_RECEIPT_MST (NOLOCK) MT ON   MT.MEMO_ID=DT.MEMO_ID          
   LEFT OUTER JOIN PRD_AGENCY_ISSUE_MATERIAL_DET (NOLOCK) T11 ON DT.REF_ROW_ID=T11.ROW_ID             
   WHERE MT.CANCELLED=0   
   AND MT.MEMO_DT < @CTODT
   GROUP BY DT.XN_PRODUCT_UID,DT.REF_ROW_ID
  ) T4 ON T4.REF_ROW_ID=T1.ROW_ID 
  JOIN PRD_AGENCY_MST (NOLOCK) AG ON AG.AGENCY_CODE =T5.REF_AGENCY_CODE      
  WHERE T5.MEMO_DT< @CFM_DT
  AND (@AC_CODE='' OR AG.AC_CODE =@AC_CODE)
  AND (@CORDER_ID='' OR T1.REF_PRD_WORKORDER_MEMOID =@CORDER_ID)
  GROUP BY T1.REF_PRD_WORKORDER_MEMOID
  
 
  
  IF OBJECT_ID ('TEMPDB..#TMPISSUE','U') IS NOT NULL
     DROP TABLE #TMPISSUE
  
  SELECT AG.AGENCY_CODE,AG.AGENCY_NAME,JOBS.JOB_NAME, T1.REF_PRD_WORKORDER_MEMOID AS ORDER_ID,T5.MEMO_ID AS ISSUE_ID,T5.MEMO_NO AS ISSUE_NO,T5.MEMO_DT AS ISSUE_DT,
  SUM(CASE WHEN UOM.UOM_NAME='PCS' THEN (T1.QUANTITY) ELSE 0 END)  AS ISSUE_PCS_QTY,
  SUM(CASE WHEN UOM.UOM_NAME='MTR' THEN (T1.QUANTITY) ELSE 0 END)  AS ISSUE_MTR_QTY,
  SD.SUB_SECTION_NAME 
  INTO #TMPISSUE
  FROM PRD_AGENCY_ISSUE_MATERIAL_DET (NOLOCK) T1                 
  JOIN ARTICLE T2 (NOLOCK) ON T1.ARTICLE_CODE = T2.ARTICLE_CODE 
  JOIN ARTICLE T3 (NOLOCK) ON T3.ARTICLE_CODE =T1.REF_COMPONENT_ARTICLE_CODE
  JOIN SECTIOND SD (NOLOCK) ON SD.SUB_SECTION_CODE =T3.SUB_SECTION_CODE              
  JOIN UOM (NOLOCK) ON T2.UOM_CODE = UOM.UOM_CODE                               
  JOIN PRD_AGENCY_ISSUE_MATERIAL_MST (NOLOCK) T5 ON T5.MEMO_ID=T1.MEMO_ID           
  JOIN JOBS (NOLOCK) ON JOBS.JOB_CODE =T1 .JOB_CODE    
  JOIN PRD_AGENCY_MST (NOLOCK) AG ON AG.AGENCY_CODE =T5.REF_AGENCY_CODE  
  WHERE T5.MEMO_DT BETWEEN @CFM_DT AND @CTODT
   AND (@AC_CODE='' OR AG.AC_CODE =@AC_CODE)
  AND (@CORDER_ID='' OR T1.REF_PRD_WORKORDER_MEMOID =@CORDER_ID)
  GROUP BY AG.AGENCY_CODE,T1.REF_PRD_WORKORDER_MEMOID,T5.MEMO_ID ,T5.MEMO_NO ,T5.MEMO_DT 
  ,AG.AGENCY_NAME,JOBS.JOB_NAME,SD.SUB_SECTION_NAME  
 
  
  --EXEC SP3S_PRD_WO_DETAILS '2016-04-01','2017-03-31','',''
  
  SELECT AGENCY_CODE,AGENCY_NAME,JOB_NAME,ORDER_ID,
  ISSUE_ID,ISSUE_NO,ISSUE_DT,ISSUE_PCS_QTY,ISSUE_MTR_QTY,
  REC_NO,REC_DT,REC_ID,
  REC_PCS_QTY  AS REC_PCS_QTY,
  REC_MTR_QTY  AS REC_MTR_QTY,
  ISSUE_SR=ROW_NUMBER() OVER (PARTITION BY A.ISSUE_ID ORDER BY A.ISSUE_ID),
   SUB_SECTION_NAME
  INTO #TMPISSUEREC
  FROM #TMPISSUE A
  LEFT OUTER JOIN
  (
   SELECT A.MEMO_ID,  MT.MEMO_ID AS REC_ID, MT.MEMO_NO AS REC_NO,MT.MEMO_DT AS REC_DT,
   SUM(CASE WHEN UOM.UOM_NAME='PCS' THEN (DT.QUANTITY) ELSE 0 END)  AS REC_PCS_QTY,
   SUM(CASE WHEN UOM.UOM_NAME='MTR' THEN (DT.QUANTITY) ELSE 0 END)  AS REC_MTR_QTY
   FROM PRD_AGENCY_ISSUE_MATERIAL_DET A
   JOIN ARTICLE T2 (NOLOCK) ON A.ARTICLE_CODE = T2.ARTICLE_CODE
   JOIN UOM (NOLOCK) ON T2.UOM_CODE = UOM.UOM_CODE 
   JOIN PRD_AGENCY_MATERIAL_RECEIPT_DET DT ON A.ROW_ID=DT.REF_ROW_ID
   JOIN PRD_AGENCY_MATERIAL_RECEIPT_MST MT (NOLOCK) ON   MT.MEMO_ID=DT.MEMO_ID 
   WHERE MT.CANCELLED=0   
   AND MT.MEMO_DT BETWEEN @CFM_DT AND  @CTODT    
   GROUP BY A.MEMO_ID,MT.MEMO_ID, MT.MEMO_NO,MT.MEMO_DT
  ) B ON A.ISSUE_ID=B.MEMO_ID 
  GROUP BY AGENCY_CODE,AGENCY_NAME,JOB_NAME,ORDER_ID,
  ISSUE_ID,ISSUE_NO,ISSUE_DT,ISSUE_PCS_QTY,ISSUE_MTR_QTY,
   REC_NO,REC_DT,REC_ID,REC_PCS_QTY,REC_MTR_QTY,SUB_SECTION_NAME
   
  
  
  IF OBJECT_ID ('TEMPDB..#TMPISSUE_CUM_SUM','U') IS NOT NULL
     DROP TABLE #TMPISSUE_CUM_SUM
     
  SELECT A.AGENCY_NAME,A.JOB_NAME , A.ORDER_ID , A.ISSUE_ID , A.ISSUE_NO ,A.ISSUE_DT ,
         ISNULL(A.ISSUE_PCS_QTY,0) AS ISSUE_PCS_QTY, 
         ISNULL(A.ISSUE_MTR_QTY,0) AS ISSUE_MTR_QTY,
         A.REC_ID,A.REC_NO ,A.REC_DT ,
         ISNULL(A.REC_PCS_QTY,0) AS REC_PCS_QTY ,
         ISNULL(A.REC_MTR_QTY,0) AS  REC_MTR_QTY,
         A.ISSUE_SR ,
         SUM(B.REC_PCS_QTY) AS REC_PCS_QTY_CUMM,
         SUM(B.REC_MTR_QTY) AS REC_MTR_QTY_CUMM,
         A.SUB_SECTION_NAME
  INTO #TMPISSUE_CUM_SUM
  FROM #TMPISSUEREC A
  JOIN #TMPISSUEREC B ON A.ISSUE_ID=B.ISSUE_ID AND B.ISSUE_SR <=A.ISSUE_SR 
  GROUP BY A.ORDER_ID ,A.ISSUE_ID ,A.ISSUE_NO ,A.ISSUE_DT ,A.ISSUE_PCS_QTY, A.ISSUE_MTR_QTY,
          A.REC_ID,A.REC_NO ,A.REC_DT ,A.REC_PCS_QTY ,A.REC_MTR_QTY ,A.ISSUE_SR,
          A.AGENCY_NAME,A.JOB_NAME,A.SUB_SECTION_NAME
  ORDER BY A.ORDER_ID ,A.ISSUE_ID,A.ISSUE_SR
  
 
  
  
 
  SELECT B.AGENCY_NAME ,B.JOB_NAME, A.ORDER_NO ,A.ORDER_DT,ISNULL(OPS_PCS_QTY,0) AS OPS_PCS_QTY,ISNULL(OPS_MTR_QTY,0) AS OPS_MTR_QTY,
  B.ISSUE_NO AS ISSUE_NO,
  B.ISSUE_DT ,
  CASE WHEN ISSUE_SR=1 THEN B.ISSUE_PCS_QTY ELSE 0 END AS ISSUE_PCS_QTY,
  CASE WHEN ISSUE_SR=1 THEN B.ISSUE_MTR_QTY ELSE 0 END AS ISSUE_MTR_QTY,
  B.REC_NO ,B.REC_DT ,B.REC_PCS_QTY ,B.REC_MTR_QTY 
  ,CLOSING_PCS_QTY=(ISNULL(OPS_PCS_QTY,0)+ISNULL(B.ISSUE_PCS_QTY,0))-(ISNULL(B.REC_PCS_QTY_CUMM,0)),
  CLOSING_MTR_QTY=(ISNULL(OPS_MTR_QTY,0)+ISNULL(B.ISSUE_MTR_QTY,0))-(ISNULL(B.REC_MTR_QTY_CUMM,0)),
  B.SUB_SECTION_NAME
  FROM #TMPORDER A
  JOIN #TMPISSUE_CUM_SUM B ON A.ORDER_ID =B.ORDER_ID 
  LEFT OUTER JOIN #TMPOPS OPS ON A.ORDER_ID =OPS.ORDER_ID 
  ORDER BY B.AGENCY_NAME,A.ORDER_NO ,B.JOB_NAME,B.ISSUE_NO,B.ISSUE_DT,ISSUE_SR 
  


END
