CREATE PROCEDURE SP_VALIDATEDATASENTINFO
@CXNTYPE VARCHAR(20),
@CTABLEPREFIX VARCHAR(100),
@CTABLESUFFIX VARCHAR(100),
@CERRORMSG VARCHAR(MAX) OUTPUT
--WITH ENCRYPTION
AS
BEGIN
	PRINT 'ENTER SP_VALIDATEDATASENTINFO-1' 
	DECLARE @CCMD NVARCHAR(MAX),@CTEMPDATASENTINFONAME VARCHAR(100),@CTABLENAME VARCHAR(100),
			@CSENDTABLENAME VARCHAR(100),@NSTEP INT,@BPROCEED BIT,@NSOURCETABLERECCOUNT INT,@NRECCOUNT INT
	
	SET @CERRORMSG=''
	
BEGIN TRY

	SET @NSTEP=10
	IF CURSOR_STATUS('GLOBAL','XNSTABLELISTCUR') IN (0,1)  
	BEGIN
		CLOSE XNSTABLELISTCUR
		DEALLOCATE XNSTABLELISTCUR
	END	
	
	SET @NSTEP=70
	SET @CTEMPDATASENTINFONAME=@CTABLEPREFIX+'_DATASENTINFO_'+@CTABLESUFFIX
		
	IF OBJECT_ID(@CTEMPDATASENTINFONAME,'U') IS NULL
		GOTO END_PROC
	
	SET @NSTEP=80
	DECLARE @TTABLELIST TABLE (TABLENAME VARCHAR(200),RECCOUNT INT)
	
	SET @NSTEP=90
	SET @CCMD=N'SELECT TABLENAME,RECCOUNT FROM '+@CTEMPDATASENTINFONAME
	
	INSERT @TTABLELIST
	EXEC SP_EXECUTESQL @CCMD

	DECLARE XNSTABLELISTCUR CURSOR FOR SELECT TABLENAME,RECCOUNT FROM @TTABLELIST
	OPEN XNSTABLELISTCUR
	
	FETCH NEXT FROM XNSTABLELISTCUR INTO @CTABLENAME,@NRECCOUNT
	WHILE @@FETCH_STATUS=0
	BEGIN
		SET @NSTEP=105
		SET @CSENDTABLENAME=@CTABLEPREFIX+'_'+@CTABLENAME+'_'+@CTABLESUFFIX
		
		PRINT 'CHECK SEND TABLE:'+@CSENDTABLENAME
		IF OBJECT_ID(@CSENDTABLENAME,'U') IS NOT NULL
			SET @BPROCEED=1
		ELSE
			SET @BPROCEED=0
		
		IF @BPROCEED=1
		BEGIN
			SET @NSTEP=115
			SET @CCMD=N'SELECT @NSOURCETABLERECCOUNT=COUNT(*) FROM '+@CSENDTABLENAME
			PRINT @CCMD
			EXEC SP_EXECUTESQL @CCMD,N'@NSOURCETABLERECCOUNT INT OUTPUT',@NSOURCETABLERECCOUNT=@NSOURCETABLERECCOUNT OUTPUT
			
				
			IF @NSOURCETABLERECCOUNT<>@NRECCOUNT
			BEGIN
				SET @NSTEP=120
				SET @BPROCEED=0
				SET @CERRORMSG='EXTRACTED NO. OF RECORDS  ('+LTRIM(RTRIM(STR(@NSOURCETABLERECCOUNT)))+')
								FOR THE TABLE :'+@CTABLENAME+' IS NOT EQUAL TO NO. OF SENT RECORDS ('+
							    LTRIM(RTRIM(STR(@NRECCOUNT)))+')....PLEASE GET DATA RESENT'
				GOTO END_PROC			    
			END
		END
		ELSE
		BEGIN
			SET @NSTEP=130
			SET @CERRORMSG='SOURCE DATA NOT FOUND FOR TABLE :'+@CTABLENAME+'...PLEASE GET DATA RESENT'
			GOTO END_PROC
		END
		
		FETCH NEXT FROM XNSTABLELISTCUR INTO @CTABLENAME,@NRECCOUNT					
	END

	CLOSE XNSTABLELISTCUR
	DEALLOCATE XNSTABLELISTCUR
	
END TRY

BEGIN CATCH
	SELECT @CERRORMSG='PROCEDURE SP_VALIDATEDATASENTINFO STEP: '+STR(@NSTEP)+' LINE NO. :'+
	ISNULL(LTRIM(RTRIM(STR(ERROR_LINE()))),'NULL LINE')+'MSG :'+ISNULL(ERROR_MESSAGE(),'NULL MSG')
END CATCH


END_PROC:		

END
--- 'END OF CREATING PROCEDURE SP_VALIDATEDATASENTINFO'
