CREATE PROCEDURE SP_GETLEVELCHECKLIST
AS
BEGIN
	 
	SELECT A.XN_TYPE ,A.LEVEL_DESC ,A.LEVEL_CODE ,A.LEVEL_NO ,B.CHECKLIST_CODE,B.CHECKLIST_DESC,
	 CASE WHEN C.LEVEL_CODE IS NULL THEN 0 ELSE 1 END AS CHK
	FROM
	(
		SELECT SR=1, A.XN_TYPE ,A.LEVEL_DESC ,A.LEVEL_CODE ,A.LEVEL_NO 
		 FROM XN_APPROVAL_CHECKLIST_LEVELS A
	 ) A
	JOIN 
	(
	 SELECT SR=1, B.CHECKLIST_CODE,B.CHECKLIST_DESC
	  FROM XN_APPROVAL_CHECKLIST_MST B WHERE INACTIVE =0

	) B ON A.SR =B.SR 
	LEFT JOIN
	(
	 SELECT * FROM XN_APPROVAL_CHECKLIST_LEVEL_DETAILS
	) C ON C.XN_TYPE =A.XN_TYPE AND C.CHECKLIST_CODE =B.CHECKLIST_CODE  AND C.LEVEL_CODE =A.LEVEL_CODE 
	ORDER BY A.LEVEL_CODE ,B.CHECKLIST_CODE 

END
