CREATE PROCEDURE SP_SYNCH_MIRRORDATA_CUS_SINGLE
(
  @CERRMSG VARCHAR(1000) OUTPUT
)
--WITH ENCRYPTION
AS
SET NOCOUNT ON
BEGIN
	/*
		208_2014_01_13 : THIS PROCEDURE WILL MERGE DATA FROM TEMPORARY TABLE TO ACTUAL TABLE.
						 TABLE NAMES AND ITS MERGING ORDER WILL BE FIXED AND WILL BE DEFINED HERE.	
						 
	*/

DECLARE @CSTEP VARCHAR(100),@DTSQL NVARCHAR(MAX),@NMERGE_ORDER NUMERIC(5)
	   ,@CTABLENAME VARCHAR(200),@CTABLE_SUFFIX VARCHAR(50),@CKEYFIELD VARCHAR(200),@CDEL_ID VARCHAR(50),@CTMP_TABLENAME VARCHAR(200),@LINSERTONLY VARCHAR(1)
	   ,@CFILTERCONDITION VARCHAR(200),@CFILTERCONDITION2 VARCHAR(500),@LUPDATEONLY VARCHAR(1),@BALWAYSUPDATE VARCHAR(1),@FDEL CHAR(1)
	   ,@CERRMSGOUT VARCHAR(1000),@CTABLESSTR VARCHAR(MAX),@CMIRRORINGENABLED VARCHAR(5)
	   ,@CCURDEPTID VARCHAR(5),@CTEMPMASTERTABLE VARCHAR(200),@CTEMPMASTERTABLE1 VARCHAR(200)
	   ,@CTEMPMASTERTABLE2 VARCHAR(200),@CTEMPMASTERTABLE3 VARCHAR(200)
	   ,@CTEMPPAYMODETABLE VARCHAR(200),@CTEMPTABLE VARCHAR(100),@CDONOTRESETPOSTEDINAC VARCHAR(1)
	   ,@BADDMODE BIT,@CCUTOFFDATE VARCHAR(20),@CWHERECLAUSE VARCHAR(2000),@CMEMONOLEN VARCHAR(5),@NMEMONOLEN INT
	   ,@DMINMEMODT DATETIME,@DMAXMEMODT DATETIME,@CFINYEAR VARCHAR(5),@CMEMOPREFIX VARCHAR(10)
	   ,@CMINMEMONO VARCHAR(20),@CMAXMEMONO VARCHAR(20),@CSOURCEDB VARCHAR(200),@CMERGEDB VARCHAR(200)
	   ,@BMSTINSERTONLY BIT,@BSERIESMISMATCHFOUND BIT,@CMEMOID VARCHAR(40),@CPREVMEMONO VARCHAR(20)
	   ,@NPREVMEMONO NUMERIC(5,0),@NLENVALUE INT,@CPREVMEMONOSEARCH VARCHAR(20),@CMEMOIDSEARCH VARCHAR(40)
	   ,@CRETPRODUCTCODE VARCHAR(50),@NVERSIONNO INT,@CJOINSTR VARCHAR(MAX),@CSTATECODE CHAR(7)
	   ,@CCITYCODE VARCHAR(10),@CAREACODE CHAR(7)
	
	
BEGIN TRY
	
	
	SET @CSTEP=10

	SELECT @CSOURCEDB='',@CMERGEDB='',@BMSTINSERTONLY=1,@BSERIESMISMATCHFOUND=0
	
	SET @CSTEP=15
    	
    SELECT TOP 1 @CCURDEPTID=VALUE FROM CONFIG WHERE CONFIG_OPTION='LOCATION_ID'
    
	SET @CSTEP=20


	SELECT @CTEMPMASTERTABLE=@CSOURCEDB+'CUS_CUSTDYM_MIRROR',
		   @CTEMPMASTERTABLE1=@CSOURCEDB+'CUS_STATE_MIRROR',
		   @CTEMPMASTERTABLE2=@CSOURCEDB+'CUS_CITY_MIRROR',
		   @CTEMPMASTERTABLE3=@CSOURCEDB+'CUS_AREA_MIRROR'
	

	

LBLSTART:
    
    BEGIN TRANSACTION 	     
    
    SELECT @CMEMOID='',@NVERSIONNO=0

    SELECT TOP 1 @CMEMOID = B.CUSTOMER_CODE ,@NVERSIONNO=VERSION_NO
    FROM CUS_CUSTDYM_MIRROR B (NOLOCK)
    LEFT OUTER JOIN MIRROR_SYNCH_LOG C (NOLOCK) ON C.MEMO_ID=B.CUSTOMER_CODE AND C.XN_TYPE='CUS'
    WHERE DATEDIFF(SS,B.VERSION_LAST_UPDATE,GETDATE())>60 AND C.MEMO_ID IS NULL
    ORDER BY B.CUSTOMER_CODE,VERSION_NO DESC
        
    IF ISNULL(@CMEMOID,'')=''
		GOTO EXIT_PROC
		
    
	SET @CSTEP=30
	
LBLMERGE:
	---DELETING EXISTING RECORD IF BILL COMES AGAIN FOR MERGING
	
	SELECT TOP 1 @CSTATECODE=A.STATE_CODE,@CCITYCODE=B.CITY_CODE,@CAREACODE=C.AREA_CODE
	FROM CUS_STATE_MIRROR A JOIN CUS_CITY_MIRROR B ON A.STATE_CODE=B.STATE_CODE
	JOIN CUS_AREA_MIRROR C ON C.CITY_CODE=B.CITY_CODE
	WHERE A.VERSION_NO=@NVERSIONNO AND B.VERSION_NO=@NVERSIONNO AND C.VERSION_NO=@NVERSIONNO 
								  
	SET @CTABLENAME='STATE'
	SET @CTMP_TABLENAME='CUS_STATE_MIRROR'
	SET @CKEYFIELD='STATE_CODE'
	
	SET @CFILTERCONDITION = 'B.STATE_CODE='''+@CSTATECODE+''' AND B.VERSION_NO='+LTRIM(RTRIM(STR(@NVERSIONNO)))
	 
	SET @CSTEP=40
	
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=1,@CFILTERCONDITION=@CFILTERCONDITION,@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1,@BUPDATEXNS=0 


	SET @CSTEP=50
	SET @CTABLENAME='CITY'
	SET @CTMP_TABLENAME='CUS_CITY_MIRROR'
	SET @CKEYFIELD='CITY_CODE'
	
	SET @CFILTERCONDITION = 'B.CITY_CODE='''+@CCITYCODE+''' AND B.VERSION_NO='+LTRIM(RTRIM(STR(@NVERSIONNO)))
	
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=1,@CFILTERCONDITION='',@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=0,@BUPDATEXNS=0

	SET @CSTEP=60	
	SET @CTABLENAME='AREA'
	SET @CTMP_TABLENAME='CUS_AREA_MIRROR'
	SET @CKEYFIELD='AREA_CODE'
	
	SET @CFILTERCONDITION = 'B.AREA_CODE='''+@CAREACODE+''' AND B.VERSION_NO='+LTRIM(RTRIM(STR(@NVERSIONNO)))
	
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=1,@CFILTERCONDITION=@CFILTERCONDITION,@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1 					  
	
	SET @CFILTERCONDITION = 'B.CUSTOMER_CODE='''+@CMEMOID+''' AND B.VERSION_NO='+LTRIM(RTRIM(STR(@NVERSIONNO)))
	
	SET @CSTEP=70
	SET @CTABLENAME='CUSTDYM'
	SET @CTMP_TABLENAME='CUS_CUSTDYM_MIRROR'
	SET @CKEYFIELD='CUSTOMER_CODE'
	
	
	SET @CSTEP=80
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=1,@CFILTERCONDITION=@CFILTERCONDITION,@LUPDATEONLY=@LUPDATEONLY
							  ,@BALWAYSUPDATE=1,@BUPDATEXNS=0 

	SET @CSTEP=90
    SELECT TOP 1 @CERRMSG=ERRMSG FROM MIRROR_SYNCH_LOG (NOLOCK) WHERE XN_TYPE='CUS' AND MEMO_ID=@CMEMOID
    
    IF ISNULL(@CERRMSG,'')=''
    BEGIN 
		SET @CSTEP=340
	    		
		DELETE A FROM CUS_STATE_MIRROR A WHERE A.STATE_CODE=@CSTATECODE AND A.VERSION_NO<=@NVERSIONNO
		
		DELETE A FROM CUS_CITY_MIRROR A WHERE A.CITY_CODE=@CCITYCODE AND A.VERSION_NO<=@NVERSIONNO

		DELETE A FROM CUS_AREA_MIRROR A WHERE A.AREA_CODE=@CAREACODE AND A.VERSION_NO<=@NVERSIONNO

		DELETE A FROM CUS_CUSTDYM_MIRROR A WHERE A.CUSTOMER_CODE=@CMEMOID AND A.VERSION_NO<=@NVERSIONNO
				
	END    
	
	IF ISNULL(@CERRMSG,'')=''
		COMMIT
	ELSE
		GOTO EXIT_PROC	
	
	GOTO LBLSTART
	
END TRY
BEGIN CATCH
	SET @CERRMSG='P:SP_SYNCH_MIRRORDATA_CUS_SINGLE, STEP:'+@CSTEP+', MESSAGE:'+ERROR_MESSAGE()
	GOTO EXIT_PROC
END CATCH

EXIT_PROC:

	IF @@TRANCOUNT>0
	BEGIN
		IF ISNULL(@CERRMSG,'')='' 
			COMMIT
		ELSE
			ROLLBACK
    END
	
END	
---END OF PROCEDURE - SP_SYNCH_MIRRORDATA_CUS_SINGLE
