CREATE PROCEDURE DBKPI_Sorting
AS  
BEGIN  
SET NOCOUNT ON
SELECT 1 SortingID,'Sale'  SortingON UNION
SELECT 2 SortingID,'Profit'SortingON UNION
SELECT 3 SortingID,'GMROI' SortingON
SET NOCOUNT OFF
END