CREATE PROCEDURE SP3S_DROP_COLUMN(@TABLE VARCHAR(1000),@COL VARCHAR(1000))
AS
BEGIN
DECLARE @CCMD NVARCHAR(MAX)='',@DF VARCHAR(1000)
SELECT @DF=D.NAME FROM SYS.DEFAULT_CONSTRAINTS D 
JOIN SYSCOLUMNS C ON D.parent_column_id=C.colid AND D.parent_OBJECT_id=C.ID
WHERE OBJECT_NAME(D.parent_OBJECT_id)=@TABLE AND C.name=@COL
IF ISNULL(@DF,'')<>''
   SET @CCMD=N'ALTER TABLE ['+@TABLE+'] DROP CONSTRAINT ['+@DF+'];'
SET @CCMD+='ALTER TABLE ['+@TABLE+'] DROP COLUMN ['+@COL+'];'   
EXEC(@CCMD)
END
