
CREATE proc SPPC_PUR             
@NMODE INT,            
@PONUMBER CHAR(50),            
@CANCELLED BIT,
@CFIN_YEAR VARCHAR(5)='',
@CAC_CODE VARCHAR(10)='',
@CORDER_ID VARCHAR(50)='',
@CCHALLAN_NO VARCHAR(50)='' ,
@DREC_FM_DT DATETIME='',
@DREC_TO_DT DATETIME='',
@NDIRECT INT=0          
AS BEGIN          
 
 IF @NMODE=1
    GOTO LBLMRR
 ELSE IF @NMODE=2
    GOTO LBL_MRRDET
 ELSE IF @NMODE=3
    GOTO LBL_STATUS
 ELSE IF @NMODE=4
    GOTO LBL_DETVIEW
 ELSE IF @NMODE=5    
    GOTO LBLPARTY  
 ELSE IF @NMODE=6    
    GOTO LBLBILL
 ELSE IF @NMODE=7    
    GOTO LBLCHALLAN  
 ELSE
 GOTO END_PROC   
 
 
  LBLPARTY:
       
       SELECT A.AC_CODE ,B.AC_NAME
       FROM PPC_PIM01106 A
       JOIN LM01106 B ON A.AC_CODE=B.AC_CODE
       GROUP BY A.AC_CODE ,B.AC_NAME
   
   GOTO END_PROC 
   
   LBLBILL:
      
      
      SELECT DISTINCT A.BILL_NO AS ORDER_NO ,
             A.ORDER_ID
      FROM PPC_BUYER_ORDER_MST A
      JOIN PPC_BUYER_ORDER_DET B ON A.ORDER_ID=B.ORDER_ID
      JOIN PPC_BO_ART_BOM C ON B.ROW_ID=C.REF_ROW_ID
      JOIN PPC_POD01106 POD ON C.ROW_ID=POD.bo_bom_row_id
      JOIN PPC_PID01106 PID ON PID.PO_ROW_ID=POD.ROW_ID
      WHERE A.CANCELLED=0 
      AND (@CAC_CODE='' OR A.AC_CODE=@CAC_CODE)
      
   
   GOTO END_PROC 
   
   LBLCHALLAN:
      
      SELECT DISTINCT PIM.CHALLAN_NO
      FROM PPC_BUYER_ORDER_MST A
      JOIN PPC_BUYER_ORDER_DET B ON A.ORDER_ID=B.ORDER_ID
      JOIN PPC_BO_ART_BOM C ON B.ROW_ID=C.REF_ROW_ID
      JOIN PPC_POD01106 POD ON C.ROW_ID=POD.bo_bom_row_id
      JOIN PPC_PID01106 PID ON PID.PO_ROW_ID=POD.ROW_ID
      JOIN PPC_PIM01106 PIM ON PIM.MRR_ID=PID.MRR_ID
      WHERE A.CANCELLED=0 
      AND (@CAC_CODE='' OR A.AC_CODE=@CAC_CODE)
      AND (@CORDER_ID='' OR A.ORDER_ID=@CORDER_ID)
      
    GOTO END_PROC 
     
----1.BIND PONUMBER            
LBLMRR:            
   SELECT MRR_ID,MRR_NO  FROM ppc_piM01106            

GOTO END_PROC           
            
----2.BIND GRID            
LBL_MRRDET:           
	SELECT ppc_piM01106.*,LM01106.AC_CODE,LM01106.AC_NAME,Pid.PO_NO,PID.ORDER_NO  ,Pur_qty as pur_qty            
	FROM ppc_piM01106 
	JOIN
	(
	  SELECT mrr_id ,SUM(quantity) as Pur_qty 
	  FROM PPC_PID01106 
	  WHERE (@NDIRECT =1 OR ISNULL(PO_ROW_ID,'') <>'') --1 FOR DIRECT PURCHASE
	  AND (@NDIRECT =2 OR ISNULL(PO_ROW_ID,'') ='')--2 FOR AGAINST PO
	  GROUP BY mrr_id
	) POD ON POD.mrr_id=ppc_piM01106.MRR_ID
	JOIN 
		(
		 SELECT POD.ORDER_NO, A.MRR_ID,POD.PO_NO FROM PPC_PID01106 A
		 LEFT OUTER JOIN
		 (
		  SELECT E.BILL_NO AS ORDER_NO, B.PO_NO, A.ROW_ID FROM PPC_POD01106 A
		  JOIN PPC_POM01106 B ON A.PO_ID=B.PO_ID
		  JOIN PPC_BO_ART_BOM C ON C.ROW_ID =A.bo_bom_row_id
		  JOIN PPC_BUYER_ORDER_DET D ON D.ROW_ID =C.REF_ROW_ID 
		  JOIN PPC_BUYER_ORDER_MST E ON E.ORDER_ID  =D.ORDER_ID 
		  WHERE B.CANCELLED=0 AND E.CANCELLED =0
		  GROUP BY E.BILL_NO, B.PO_NO, A.ROW_ID
		 ) POD ON POD.ROW_ID =A.PO_ROW_ID
		 GROUP BY POD.ORDER_NO,A.MRR_ID,POD.PO_NO
		) PID ON PID.MRR_ID=PPC_PIM01106.MRR_ID
	JOIN LM01106 ON LM01106.AC_CODE=ppc_piM01106.ac_code            
	WHERE (@PONUMBER='' OR PPC_PIM01106.MRR_ID=@PONUMBER)       
	ORDER BY PPC_PIM01106.MRR_ID DESC          
	          
GOTO END_PROC             
            
----3.SEARCH BY PO NUMBER AND STATUS            
LBL_STATUS:
           
	SELECT PPC_PIM01106.*,LM01106.AC_CODE,LM01106.AC_NAME,Pid.PO_NO,PID.ORDER_NO            
	FROM PPC_PIM01106 
	JOIN 
	(
	 SELECT POD.ORDER_NO,A.MRR_ID,POD.PO_NO FROM PPC_PID01106 A
	 LEFT OUTER JOIN
	 (
	  SELECT E.BILL_NO AS ORDER_NO,B.PO_NO, A.ROW_ID FROM PPC_POD01106 A
	  JOIN PPC_POM01106 B ON A.PO_ID=B.PO_ID
	  JOIN PPC_BO_ART_BOM C ON C.ROW_ID =A.bo_bom_row_id
	  JOIN PPC_BUYER_ORDER_DET D ON D.ROW_ID =C.REF_ROW_ID 
	  JOIN PPC_BUYER_ORDER_MST E ON E.ORDER_ID  =D.ORDER_ID 
	  WHERE B.CANCELLED=0 AND E.CANCELLED =0
	  GROUP BY E.BILL_NO, B.PO_NO, A.ROW_ID
	 ) POD ON POD.ROW_ID =A.PO_ROW_ID
	 GROUP BY POD.ORDER_NO,A.MRR_ID,POD.PO_NO
	) PID ON PID.MRR_ID=PPC_PIM01106.MRR_ID
	JOIN LM01106  ON LM01106.AC_CODE=ppc_piM01106.ac_code             
	WHERE (@PONUMBER='' OR PPC_PIM01106.MRR_ID=@PONUMBER)
	AND ppc_piM01106.CANCELLED=@CANCELLED  
	          
GOTO END_PROC
   
----3.SEARCH BY PO NUMBER OR STATUS            
LBL_DETVIEW:
	          
	       
	SELECT  PIM.user_code, PIM.mrr_id, PIM.fin_year, PIM.credit_days, PIM.cr_discount_percentage, PIM.EDT_USER_CODE, PIM.mrr_no
	 , PIM.bill_no, PIM.bill_dt, PIM.receipt_dt, PIM.ac_code, PIM.total_amount, PIM.subtotal, PIM.discount_percentage
	 , PIM.discount_amount, PIM.other_charges, PIM.freight, PIM.tax_percentage, PIM.tax_amount, PIM.round_off, PIM.last_update
	 ,CANCELLED=CASE WHEN PIM.CANCELLED=0 THEN 'NO' ELSE 'YES' END  , PIM.DEPT_ID, PIM.REMARKS, PIM.CHALLAN_NO, PIM.CHALLAN_DT 
	
	,LM01106.AC_CODE,LM01106.AC_NAME,Pid.PO_NO ,PID.ORDER_NO,pur_qty as pur_qty             
	FROM ppc_piM01106 PIM
	JOIN LM01106 ON LM01106.AC_CODE=PIM.ac_code
	JOIN 
		(
		 SELECT POD.ORDER_ID, POD.ORDER_NO, A.MRR_ID,POD.PO_NO,
		 SUM(a.quantity) as pur_qty 
		 FROM PPC_PID01106 A
		 LEFT OUTER JOIN
		 (
		  SELECT E.ORDER_ID, E.BILL_NO AS ORDER_NO,B.PO_NO, A.ROW_ID FROM PPC_POD01106 A
		  JOIN PPC_POM01106 B ON A.PO_ID=B.PO_ID
		  JOIN PPC_BO_ART_BOM C ON C.ROW_ID =A.bo_bom_row_id
		  JOIN PPC_BUYER_ORDER_DET D ON D.ROW_ID =C.REF_ROW_ID 
		  JOIN PPC_BUYER_ORDER_MST E ON E.ORDER_ID  =D.ORDER_ID 
		  WHERE B.CANCELLED=0 AND E.CANCELLED =0
		  GROUP BY E.ORDER_ID,E.BILL_NO, B.PO_NO, A.ROW_ID
		 ) POD ON POD.ROW_ID =A.PO_ROW_ID
		  WHERE (@NDIRECT =1 OR ISNULL(PO_ROW_ID,'') <>'') --1 FOR DIRECT PURCHASE
	      AND (@NDIRECT =2 OR ISNULL(PO_ROW_ID,'') ='')--2 FOR AGAINST PO
		 GROUP BY POD.ORDER_ID,POD.ORDER_NO,A.MRR_ID,POD.PO_NO
		) PID ON PID.MRR_ID=PIM.MRR_ID             
	--WHERE ppc_POM01106.PO_NO=@PONUMBER OR ppc_POM01106.CANCELLED=@CANCELLED        
	WHERE (@PONUMBER='' OR PIM.MRR_ID=@PONUMBER) --OR ppc_POM01106.CANCELLED=@CANCELLED 
	and (@CFIN_YEAR='' or PIM.fin_year=@CFIN_YEAR)    
    AND (@CAC_CODE='' OR PIM.ac_code =@CAC_CODE)     
    AND (@CCHALLAN_NO='' OR PIM .CHALLAN_NO =@CCHALLAN_NO)
    AND (@CORDER_ID='' OR PID.ORDER_ID =@CORDER_ID)
    AND (@DREC_FM_DT='' OR PIM.RECEIPT_DT BETWEEN  @DREC_FM_DT AND  @DREC_TO_DT)   
    order by PIM.mrr_id DESC,PIM.receipt_dt desc
      
GOTO END_PROC
 


END_PROC:       
            
END 
