create PROCEDURE SP_LOC_SHORTAGE_SALE_RATIO  
(  
	 @CDEPTID VARCHAR(2)=''
)  
----WITH ENCRYPTION
AS
BEGIN 
--(dinkar) Replace  left(memoid,2) to Location_code 
	SELECT a.DEPT_ID  AS DEPT_ID, 
    CONVERT(NUMERIC(18,2), SUM(SHORTAGE_QTY) / B.QUANTITY *100, 2) AS SHORTAGE_SALE_RATIO
	FROM STK_RECON_HIST_MST (NOLOCK) A
	JOIN
	(
		SELECT a.location_Code  AS DEPT_ID,SUM(QUANTITY) AS QUANTITY 
		FROM CMD01106 B  (NOLOCK)
		JOIN CMM01106 A  (NOLOCK) ON A.CM_ID=B.CM_ID 
		WHERE A.CANCELLED =0 
		GROUP BY a.location_Code 
	) B ON a.DEPT_ID =B.DEPT_ID 
	WHERE (@CDEPTID='' OR a.DEPT_ID =@CDEPTID)
	GROUP BY a.DEPT_ID ,B.QUANTITY

END
 --END OF PROCEDURE SP_LOC_SHORTAGE_SALE_RATIO
