CREATE PROCEDURE SP_PRD_BARCODELEVEL_STOCK_REPORT
(
 @DFM_DT DATETIME,
 @DTODT DATETIME
)
AS
BEGIN
    
    
    
    SELECT A.PRODUCT_CODE ,
           AR.ARTICLE_NO,SD.SUB_SECTION_NAME,
           SM.SECTION_NAME,
           SUM(QUANTITY) AS CUT_QUANTITY ,
           SUM(D.QUANTITY_IN_STOCK) AS STK_QTY
    FROM PRD_STK_TRANSFER_DET A (NOLOCK)
    JOIN PRD_STK_TRANSFER_MST B (NOLOCK) ON A.MEMO_ID=B.MEMO_ID 
    JOIN PRD_SKU C (NOLOCK) ON C.PRODUCT_UID=A.PRODUCT_UID
    JOIN PRD_PMT D (NOLOCK) ON C.PRODUCT_UID=D.PRODUCT_UID
    JOIN ARTICLE AR (NOLOCK) ON AR.ARTICLE_CODE =C.ARTICLE_CODE 
    JOIN SECTIOND  SD (NOLOCK) ON AR.SUB_SECTION_CODE =SD.SUB_SECTION_CODE
    JOIN SECTIONM  SM (NOLOCK) ON SD.SECTION_CODE =SM.SECTION_CODE 
    WHERE B.MEMO_DT BETWEEN @DFM_DT AND @DTODT
    GROUP BY A.PRODUCT_CODE ,AR.ARTICLE_NO,SD.SUB_SECTION_NAME,
           SM.SECTION_NAME
    
    


END
