CREATE PROCEDURE SP_MERGE_MIRROR_DOC_CONVERSION
(
	@CREQCHALLANID VARCHAR(40),
	@CREQXNTYPE VARCHAR(40)
)
AS
/**
	THIS PROCEDURE EXTRACT DATA FROM HEAD OFFICE FOR A PARTICULAR LOCATION AND INSERTS PENDING DOCS INTO LOCATION 
	DATABASE AFTER CONVERSION FROM W8 TO W3S
**/
BEGIN
	DECLARE  @CERRMSG VARCHAR(MAX),@CSOURCEDB VARCHAR(100),@CTMP_TABLENAME VARCHAR(500),@CSTEP VARCHAR(5),
			 @CPENDINGMEMOID VARCHAR(40)

BEGIN TRY
	
	SET @CSOURCEDB=DB_NAME()+'_TEMP.DBO.'

	BEGIN TRANSACTION			
	
	IF @CREQXNTYPE='PUR'
	BEGIN
		
		SET @CSTEP='10'
		DELETE FROM PID01106 WHERE MRR_ID=@CREQCHALLANID
		DELETE FROM PIM01106 WHERE MRR_ID=@CREQCHALLANID
		
		SET @CSTEP='20'
		SET @CTMP_TABLENAME='TMP_DOCW8_PIM01106_'+LTRIM(RTRIM(REPLACE(@CREQCHALLANID,'-','_')))
		
	    EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB='',
			 @CDESTTABLE='PIM01106',@CKEYFIELD1='MRR_ID',@LINSERTONLY=1
		
		SET @CSTEP='30'
		SET @CTMP_TABLENAME='TMP_DOCW8_PID01106_'+LTRIM(RTRIM(REPLACE(@CREQCHALLANID,'-','_')))
		
	    EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB='',
			 @CDESTTABLE='PID01106',@CKEYFIELD1='MRR_ID',@LINSERTONLY=1

		IF NOT EXISTS (SELECT TOP 1 XN_ID FROM MIRRORLOG WHERE XN_ID=@CREQCHALLANID AND XN_TYPE='PUR')
			INSERT MIRRORLOG  WITH (ROWLOCK) ( XN_TYPE, XN_ID, LAST_UPDATE )  
			SELECT 	'PUR' AS  XN_TYPE,MRR_ID AS XN_ID, LAST_UPDATE FROM PIM01106 WHERE MRR_ID=@CREQCHALLANID
		ELSE
			UPDATE MIRRORLOG  WITH (ROWLOCK) SET LAST_UPDATE=B.LAST_UPDATE FROM PIM01106 B (NOLOCK) WHERE B.MRR_ID=MIRRORLOG.XN_ID
			AND XN_TYPE='PUR'		
	END	
	ELSE
	IF @CREQXNTYPE='PRT'
	BEGIN
		SET @CSTEP='50'
		DELETE FROM RMD01106 WITH (ROWLOCK) WHERE RM_ID=@CREQCHALLANID
		DELETE FROM RMM01106 WITH (ROWLOCK) WHERE RM_ID=@CREQCHALLANID
		
		SET @CSTEP='60'
		SET @CTMP_TABLENAME='TMP_DOCW8_RMM01106_'+LTRIM(RTRIM(REPLACE(@CREQCHALLANID,'-','_')))
		
	    EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB='',
			 @CDESTTABLE='RMM01106',@CKEYFIELD1='RM_ID',@LINSERTONLY=1
			
		SET @CSTEP='62'	
		SET @CTMP_TABLENAME='TMP_DOCW8_RMD01106_'+LTRIM(RTRIM(REPLACE(@CREQCHALLANID,'-','_')))
		
	    EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB='',
			 @CDESTTABLE='RMD01106',@CKEYFIELD1='RM_ID',@LINSERTONLY=1
		
		IF NOT EXISTS (SELECT TOP 1 XN_ID FROM MIRRORLOG WHERE XN_ID=@CREQCHALLANID AND XN_TYPE='PRT')
			INSERT MIRRORLOG ( XN_TYPE, XN_ID, LAST_UPDATE )  
			SELECT 	'PRT' AS  XN_TYPE,RM_ID AS XN_ID, LAST_UPDATE FROM RMM01106 WHERE RM_ID=@CREQCHALLANID
		ELSE
			UPDATE MIRRORLOG  WITH (ROWLOCK) SET LAST_UPDATE=B.LAST_UPDATE FROM RMM01106 B (NOLOCK) WHERE B.RM_ID=MIRRORLOG.XN_ID
			AND XN_TYPE='PRT'	
			 
	END
	ELSE
	IF @CREQXNTYPE='WSL'
	BEGIN
		SET @CSTEP='64'
		DELETE FROM IND01106 WITH (ROWLOCK)  WHERE INV_ID=@CREQCHALLANID
		DELETE FROM INM01106 WITH (ROWLOCK)  WHERE INV_ID=@CREQCHALLANID
		
		SET @CSTEP='66'
		SET @CTMP_TABLENAME='TMP_DOCW8_INM01106_'+LTRIM(RTRIM(REPLACE(@CREQCHALLANID,'-','_')))
		
	    EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB='',
			 @CDESTTABLE='INM01106',@CKEYFIELD1='INV_ID',@LINSERTONLY=1
			
		SET @CSTEP='68'	
		SET @CTMP_TABLENAME='TMP_DOCW8_IND01106_'+LTRIM(RTRIM(REPLACE(@CREQCHALLANID,'-','_')))
		
	    EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB='',
			 @CDESTTABLE='IND01106',@CKEYFIELD1='INV_ID',@LINSERTONLY=1

		IF NOT EXISTS (SELECT TOP 1 XN_ID FROM MIRRORLOG WHERE XN_ID=@CREQCHALLANID AND XN_TYPE='WSL')
			INSERT MIRRORLOG WITH (ROWLOCK) ( XN_TYPE, XN_ID, LAST_UPDATE )  
			SELECT 	'WSL' AS  XN_TYPE,INV_ID AS XN_ID, LAST_UPDATE FROM INM01106 WHERE INV_ID=@CREQCHALLANID
		ELSE
			UPDATE MIRRORLOG WITH (ROWLOCK) SET LAST_UPDATE=B.LAST_UPDATE FROM INM01106 B (NOLOCK) WHERE B.INV_ID=MIRRORLOG.XN_ID
			AND XN_TYPE='WSL'			 
	END	
	ELSE
	IF @CREQXNTYPE='OPS'
	BEGIN
		DELETE FROM OPS01106
		
		SET @CSTEP='75'
		SET @CTMP_TABLENAME='TMP_DOCW8_OPS01106_'+LTRIM(RTRIM(REPLACE(@CREQCHALLANID,'-','_')))
		
	    EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB='',
			 @CDESTTABLE='OPS01106',@CKEYFIELD1='DEPT_ID',@LINSERTONLY=1
		
	END
	
	SET @CSTEP='80'
	UPDATE PENDING_DOCS_W8CONVERSION WITH (ROWLOCK) SET SYNCH=1 WHERE XN_TYPE=@CREQXNTYPE AND MEMO_ID=@CREQCHALLANID
	
	
	---- AFTER ALL PENDING DOCS GOT MERGED AT LOCATION, JUST REMOVE THE MARK TO SKIP THE ITEM RECONCILATION 
	---- THROUGH PROCEDURE
	SET @CSTEP='90'
	SELECT TOP 1 @CPENDINGMEMOID=MEMO_ID FROM PENDING_DOCS_W8CONVERSION WHERE ISNULL(SYNCH,0)=0
	
	IF ISNULL(@CPENDINGMEMOID,'')=''
		UPDATE CONFIG SET VALUE='' WHERE CONFIG_OPTION='SKIP_ITEMRECON_DUETO_W8CONVERSION'
		
	GOTO END_PROC	
				
END TRY
BEGIN CATCH
	SET @CERRMSG='PROCEDURE SP_MERGE_MIRROR_DOC_CONVERSION STEP #'+@CSTEP+' ERROR MESSAGE - '+ERROR_MESSAGE()
	GOTO END_PROC
END CATCH

END_PROC:

	IF @@TRANCOUNT>0
	BEGIN
		IF ISNULL(@CERRMSG,'')<>''	
			ROLLBACK
		ELSE
			COMMIT	
	END

	SELECT ISNULL(@CERRMSG,'') AS ERRMSG
	
END	
--END OF CREATING PROCEDURE - SP_MERGE_MIRROR_DOC_CONVERSION
