

IF EXISTS(SELECT TOP 1 'U' FROM REP_MST WHERE ISNULL(REF_REP_ID,'')<>'' GROUP BY USER_CODE,REF_REP_ID HAVING COUNT(*)>1 )
BEGIN
IF OBJECT_ID('TEMPDB..#DUPREPORTS','U') IS NOT NULL
	DROP TABLE #DUPREPORTS

	;WITH DUPREPORTS
	AS
	(
		SELECT REP_ID,ROW_NUMBER() OVER(PARTITION BY USER_CODE,REF_REP_ID ORDER BY REP_ID DESC) AS DUPCNT
		FROM REP_MST
		WHERE ISNULL(REF_REP_ID,'')<>''
	)
	SELECT * INTO #DUPREPORTS
	FROM DUPREPORTS
	WHERE DUPCNT<>1

	DELETE REP_FILTER_DET WHERE REP_ID IN 
	(SELECT REP_ID FROM #DUPREPORTS)

	DELETE REP_FILTER WHERE REP_ID IN 
	(SELECT REP_ID FROM #DUPREPORTS)

	DELETE REP_DET WHERE REP_ID IN 
	(SELECT REP_ID FROM #DUPREPORTS)

	DELETE REP_CRM WHERE REP_ID IN 
	(SELECT REP_ID FROM #DUPREPORTS)

	DELETE REP_SCH WHERE REP_ID IN 
	(SELECT REP_ID FROM #DUPREPORTS)

	DELETE REP_MST WHERE REP_ID IN 
	(SELECT REP_ID FROM #DUPREPORTS)
END	
