
 CREATE PROCEDURE SP_PRODUCT_STATUS_REPORT_7
(
 @nQueryID	INT=0,  
 @DFM_DT DATETIME='',  
 @DTO_DT DATETIME='',  
 @REF_NO VARCHAR(100)='',  
 @BUYER_NAME VARCHAR(100)='',  
 @CORDER_NO VARCHAR(100)='',  
 @JOBCARD_NO VARCHAR(100)=''  
   
)  
AS  
BEGIN  
      
	if isnull(@REF_NO,'')<>'' or isnull(@BUYER_NAME,'')<>'' or isnull(@CORDER_NO,'')<>'' or isnull(@JOBCARD_NO,'')<>''
	set @DFM_DT=''

      
      IF OBJECT_ID ('TEMPDB..#TMPJOBCARD','U') IS NOT NULL
         DROP TABLE #TMPJOBCARD
      
      SELECT A.MEMO_NO AS JOBCARD_NO,
             A.MEMO_DT AS JOBCARD_DT,
             A.MEMO_ID AS JOBCARD_ID,
             BM.ORDER_NO ,
             BM.ORDER_DT ,
             BM.REF_NO ,
             IM.ISSUE_ID ,
             IM.ISSUE_NO,
             IM.ISSUE_DT
      INTO #TMPJOBCARD
      FROM ORD_PLAN_MST  A (NOLOCK)
      JOIN ORD_PLAN_DET B (NOLOCK) ON A.MEMO_ID =B.MEMO_ID 
      JOIN ORD_PLAN_BARCODE_DET C (NOLOCK) ON B.ROW_ID =C.REFROW_ID 
      JOIN JOBWORK_ISSUE_DET id (NOLOCK) ON c.PRODUCT_CODE =id.PRODUCT_CODE 
      JOIN JOBWORK_ISSUE_MST im (NOLOCK) ON im.ISSUE_ID =id.ISSUE_ID 
      LEFT JOIN BUYER_ORDER_DET BD (NOLOCK) ON BD.ROW_ID =B.WOD_ROW_ID 
      LEFT JOIN BUYER_ORDER_MST BM  (NOLOCK) ON BD.ORDER_ID =BM.ORDER_ID 
      LEFT JOIN LM01106 LM (NOLOCK) ON LM.AC_CODE =BM.AC_CODE  
      WHERE A.CANCELLED =0 AND ISNULL(BM.CANCELLED,0)=0
      AND (@REF_NO='' OR ISNULL(BM.REF_NO,'')=@REF_NO)  
	  AND (@BUYER_NAME='' OR ISNULL(LM.AC_CODE ,'')=@BUYER_NAME)  
	  AND (@CORDER_NO='' OR ISNULL(BM.ORDER_ID,'')=@CORDER_NO)  
	  AND (@JOBCARD_NO='' OR ISNULL(a.MEMO_ID,'')=@JOBCARD_NO)  
	  AND (@DFM_DT='' or ISNULL(BM.ORDER_DT,ISNULL(a.MEMO_DT ,'')) BETWEEN @DFM_DT AND @DTO_DT  )
      GROUP BY  A.MEMO_NO ,A.MEMO_DT ,A.MEMO_ID ,BM.ORDER_NO ,BM.ORDER_DT ,IM.ISSUE_ID ,IM.ISSUE_NO,IM.ISSUE_DT,
      BM.REF_NO 
      
      --SELECT * FROM BOM_ISSUE_DET 
      
      
    ;WITH BOM_SUMMARY AS
    (  
     
     SELECT A.* ,SD.SUB_SECTION_NAME,SM.SECTION_NAME,
     B.ISSUE_NO AS BOM_ISSUE_ID,B.ISSUE_DT AS BOM_ISSUE_DT,
     ART.ARTICLE_NO,ART.ARTICLE_NAME ,C.STOCK_QTY  AS ISSUE_QTY,UOM_NAME
     FROM #TMPJOBCARD A
     JOIN BOM_ISSUE_MST B (NOLOCK ) ON A.ISSUE_ID=B.JOBWORK_ISSUE_ID
     JOIN BOM_ISSUE_DET C (NOLOCK) ON B.ISSUE_ID=C.ISSUE_ID 
     JOIN SKU (NOLOCK) ON SKU.PRODUCT_CODE=C.PRODUCT_CODE 
     JOIN ARTICLE ART (NOLOCK) ON ART.ARTICLE_CODE=SKU.ARTICLE_CODE 
     JOIN SECTIOND SD ON SD.SUB_SECTION_CODE =ART.SUB_SECTION_CODE 
     JOIN SECTIONM SM ON SM.SECTION_CODE =SD.SECTION_CODE 
     JOIN UOM (NOLOCK) ON UOM.UOM_CODE =ART.UOM_CODE 
     WHERE B.CANCELLED =0
    )  
    
 

 
    SELECT ISNULL(ORDER_NO,'') AS  [Buyer Order No],
           isnull(REF_NO,'') as [Buyer Ref No],
           JOBCARD_NO AS [Job Card No],
           ISSUE_NO AS [Issue No],
           ISSUE_DT AS [Issue Date],
           SUB_SECTION_NAME AS [Sub Section],
           SECTION_NAME as [Section],
           ARTICLE_NO [Item],
           ARTICLE_NAME [Item Name],
           SUM(ISSUE_QTY) AS [Issue Qty],
           UOM_NAME as [Uom Name]
           
    FROM BOM_SUMMARY
    GROUP BY ORDER_NO,JOBCARD_NO ,ISSUE_NO ,ISSUE_DT ,SUB_SECTION_NAME,
    SECTION_NAME,ARTICLE_NO ,ARTICLE_NAME,UOM_NAME,isnull(REF_NO,'')
    order by JOBCARD_NO,ISSUE_NO,ISSUE_DT,SUB_SECTION_NAME,
    SECTION_NAME,ARTICLE_NO 
	
END

