create PROCEDURE SP_DSR_BILLWISETAX  
(          --PARAMETERS  
 @DFROMDT DATETIME,    --REPORT FROM DT  
 @DTODT  DATETIME,    --REPORT TO DT  
 @CDEPTID CHAR(4)='',    --DEPT ID (IF BLANK THIS PARAMETER THEN RUN THIS REPORT FOR ALL LOCATION  
 @NMODE  INT,      --@NMODE=1- BILL NO WISE; 2- DATE WISE   
 @BESTIMATEENABLED BIT=0,
 @CUSERCODE VARCHAR(15)='',
 @CBINID VARCHAR(10)=''
)  
--WITH ENCRYPTION
AS  
BEGIN   
--(dinkar) Replace  left(memoid,2) to Location_code 
/*
MODIFICATION HISTORY:
MODIFIED BY			: BABAN
MODIFICATION DATE	: 15 SEP 2014
DESCRIPTION			: BASED ON CONFIG SETTING, CASH MEMOS COULD BE FILTERED(VALID CASH MEMO (VALIDATED BY CASHIER)
					  AND INVALID CASH MEMO).
*/  
	DECLARE @CMAJORDEPTID VARCHAR(5),@BDSM BIT
	SELECT TOP 1 @BDSM=VALUE FROM CONFIG WHERE CONFIG_OPTION='OPEN_CASHIER_FOR_CASHMEMOS'
	SET @BDSM=ISNULL(@BDSM,0)	
	
	SELECT @CMAJORDEPTID=MAJOR_DEPT_ID FROM LOCATION (NOLOCK) WHERE DEPT_ID=@CDEPTID
	 		 	
	SET @CMAJORDEPTID=ISNULL(@CMAJORDEPTID,'')

	 DECLARE @OUTPUTC TABLE ( CM_DT DATETIME, CM_NO VARCHAR(20),SUB_SECTION_NAME VARCHAR(200),SECTION_NAME VARCHAR(200),QUANTITY NUMERIC(14,2), TAX_PERCENTAGE NUMERIC(10,3),  
			SALE_AMT NUMERIC(12,2), TAX_AMT NUMERIC(12,2), NET_SALE_AMT NUMERIC(12,2) )  
	  
	 INSERT @OUTPUTC ( CM_DT, CM_NO,SUB_SECTION_NAME,SECTION_NAME,QUANTITY, TAX_PERCENTAGE, SALE_AMT, TAX_AMT, NET_SALE_AMT)  
	 SELECT B.CM_DT, B.CM_NO,F.SUB_SECTION_NAME,G.SECTION_NAME,A.QUANTITY, A.TAX_PERCENTAGE,   
	 RFNET-A.TAX_AMOUNT+(CASE WHEN UPDATE_AC=1 THEN CMM_DISCOUNT_AMOUNT ELSE 0 END) AS SALE_AMT,    
	 A.TAX_AMOUNT  AS TAX_AMT,    
	 RFNET AS NET_SALE_AMT  
	 FROM CMD01106 A    
	 JOIN CMM01106 B ON A.CM_ID = B.CM_ID   
	 JOIN DTM ON DTM.DT_CODE=B.DT_CODE 
	 JOIN LOCATION C ON  b.location_Code  = C.DEPT_ID
	 JOIN SKU D ON D.PRODUCT_CODE = A.PRODUCT_CODE
	 JOIN ARTICLE E ON E.ARTICLE_CODE = D.ARTICLE_CODE
	 JOIN SECTIOND F ON E.SUB_SECTION_CODE = F.SUB_SECTION_CODE
	 JOIN SECTIONM G ON G.SECTION_CODE = F.SECTION_CODE 
	 LEFT JOIN 
	(
		SELECT DISTINCT CM_ID FROM DSD01106 DSD(NOLOCK) JOIN DSM01106 DSM(NOLOCK) ON DSD.DS_ID=DSM.DS_ID
		WHERE DSM.CANCELLED=0
	)DSD ON A.CM_ID=DSD.CM_ID
	 WHERE B.CANCELLED = 0    
	 --AND B.CM_MODE = 1   --CHANGE
	 AND (B.MEMO_TYPE = 1 OR @BESTIMATEENABLED = 1)--CHANGE
	 AND B.CM_DT BETWEEN @DFROMDT AND @DTODT
	 AND b.location_Code  =(CASE WHEN @CMAJORDEPTID='' THEN b.location_Code  ELSE @CMAJORDEPTID END)    
 	 AND ISNULL(B.BIN_ID,'000') = (CASE WHEN @CBINID = '' THEN ISNULL(B.BIN_ID,'000') 
									    ELSE @CBINID END)  
	 AND B.USER_CODE=(CASE WHEN @CUSERCODE='' THEN B.USER_CODE ELSE @CUSERCODE END)
	 AND ((@BDSM=1 AND DSD.CM_ID IS NOT NULL) OR (@BDSM=0))	
	-- GROUP BY B.CM_DT, B.CM_NO, A.TAX_PERCENTAGE  
	 
	 
	 IF @NMODE = 1  
	 BEGIN
		 SELECT CM_DT,CM_NO,TAX_PERCENTAGE,SUM(SALE_AMT)AS SALE_AMT,SUM(TAX_AMT) AS TAX_AMT,SUM(NET_SALE_AMT) AS NET_SALE_AMT FROM @OUTPUTC GROUP BY CM_DT, CM_NO, TAX_PERCENTAGE  
		 ORDER BY CM_DT, CM_NO, TAX_PERCENTAGE  
	 END
	 ELSE
	 IF(@NMODE=3)
	 BEGIN
		SELECT CM_DT,CM_NO,SUB_SECTION_NAME,SECTION_NAME,TAX_PERCENTAGE,SUM(QUANTITY) AS QUANTITY, 
		SUM(SALE_AMT) AS SALE_AMT,SUM(TAX_AMT) AS TAX_AMT,SUM(NET_SALE_AMT) AS NET_SALE_AMT   FROM  @OUTPUTC
		GROUP BY CM_DT,CM_NO,SUB_SECTION_NAME,TAX_PERCENTAGE,SECTION_NAME
		ORDER BY CM_DT,CM_NO,TAX_PERCENTAGE,SUB_SECTION_NAME,SECTION_NAME
	 END
	 ELSE 
		 SELECT CM_DT, TAX_PERCENTAGE, SUM(SALE_AMT) AS SALE_AMT, SUM(TAX_AMT) AS TAX_AMT, SUM(NET_SALE_AMT) AS NET_SALE_AMT  
		 FROM @OUTPUTC  
		 GROUP BY CM_DT, TAX_PERCENTAGE  
		 ORDER BY CM_DT, TAX_PERCENTAGE  
END  
--************************************ END OF PROCEDURE SP_DSR_BILLWISETAX
