CREATE PROCEDURE SP3S_PRINTCREDITNOTE_GST
(  
 @CXN_TYPE VARCHAR(10)='',  
 @CXN_ID VARCHAR(100)=''  
)  
AS  
BEGIN  
DECLARE @DTSQL VARCHAR(MAX),@CCOLNAME VARCHAR(MAX),@CERRMSG VARCHAR(100),@NCALQTYSUM NUMERIC(10,3),  
        @NSTOREDQTY NUMERIC(10,3),@CSTEP VARCHAR(10),@RATE_FIELD VARCHAR(100),@MRP_TOTAL VARCHAR(1000)
        ,@BROKER_NAME VARCHAR(100),@LocId varchar(5)
SET @CXN_TYPE=LTRIM(RTRIM(@CXN_TYPE))
IF @CXN_TYPE!='WSR'
   RETURN       
   
SET NOCOUNT ON  
SET @RATE_FIELD='RATE'

SELECT @BROKER_NAME=CASE ISNULL(BN.AC_NAME,'') WHEN '' THEN '' ELSE 'BROKER NAME: '+BN.AC_NAME END,
@LocId= CN.location_Code 
FROM CNM01106 CN(NOLOCK)
LEFT OUTER JOIN LM01106 BN (NOLOCK) ON CN.BROKER_AC_CODE=BN.AC_CODE
WHERE CN_ID=@CXN_ID

SET @CERRMSG=''  
SET @CSTEP=100  
BEGIN TRY  
  SET @CSTEP=10             
  IF OBJECT_ID ('TEMPDB..#TRANSPORTER','U') IS NOT NULL  
     DROP TABLE #TRANSPORTER  
     
  IF OBJECT_ID('TEMPDB..#DATASET1') IS NOT NULL
	 DROP TABLE #DATASET1
  

  
  SELECT @MRP_TOTAL='GROSS AMT: '+CAST(CAST(SUM(RATE*QUANTITY) AS NUMERIC(18,2)) AS VARCHAR) FROM CND01106(NOLOCK) WHERE CN_ID=@CXN_ID		     
  
  SELECT l.Dept_Print_Name as COMPANY_NAME,l.ADDRESS1,l.ADDRESS2,lv.CITY  
        ,PHONES_FAX=CASE LEN(ISNULL(l.PHONE,'')) WHEN 0 THEN '' ELSE 'TEL: '+l.PHONE END  
        ,TIN_NO=CASE LEN(ISNULL(l.TIN_NO,'')) WHEN 0 THEN '' ELSE 'TIN: '+l.TIN_NO END  
        ,TAN_NO=CASE LEN(ISNULL(l.TAN_NO,'')) WHEN 0 THEN '' ELSE 'TAN: '+l.TAN_NO END   
        ,CIN=CASE LEN(ISNULL(CMP.CIN,'')) WHEN 0 THEN '' ELSE 'CIN: '+CMP.CIN END
        ,CMP.LOGO_PATH 
        ,LOC_GST_NO=CASE LEN(ISNULL(L.LOC_GST_NO,'')) WHEN 0 THEN '' ELSE 'GSTIN: '+L.LOC_GST_NO END
        ,CAST(0 AS NUMERIC(10,2)) AS REVERSE_CHARGES
        --,CASE WHEN MODE=2 THEN 'CHALLAN' ELSE (SELECT TOP 1 CAPTION FROM GST_XN_CAPTION WHERE XN_TYPE=@CXN_TYPE) END+' NO: '+CNM.CN_NO AS CN_NO
        --,CASE WHEN MODE=2 THEN 'CHALLAN' ELSE (SELECT TOP 1 CAPTION FROM GST_XN_CAPTION WHERE XN_TYPE=@CXN_TYPE) END+' DT: '+CONVERT(VARCHAR,CNM.CN_DT,105)AS CN_DT
        ,CASE WHEN L.REGISTERED_GST=1 AND L.LOC_GST_NO=PCOUNTRY.AC_GST_NO THEN 'CHALLAN'  
			  WHEN CNM.MODE=2 AND L.LOC_GST_NO=PCOUNTRY.AC_GST_NO THEN 'CHALLAN'  
			  ELSE (SELECT TOP 1 CAPTION FROM GST_XN_CAPTION WHERE LTRIM(RTRIM(XN_TYPE))=@CXN_TYPE) 
		 END+' NO: '+CNM.CN_NO AS CN_NO
        ,CASE WHEN L.REGISTERED_GST=1 AND L.LOC_GST_NO=PCOUNTRY.AC_GST_NO THEN 'CHALLAN'  
			  WHEN CNM.MODE=2 AND L.LOC_GST_NO=PCOUNTRY.AC_GST_NO THEN 'CHALLAN'  
			  ELSE (SELECT TOP 1 CAPTION FROM GST_XN_CAPTION WHERE LTRIM(RTRIM(XN_TYPE))=@CXN_TYPE) 
		 END+' DT: '+CONVERT(VARCHAR,CNM.CN_DT,105) AS CN_DT
		 ,ISNULL(LS.GST_STATE_NAME,'') AS  LOC_GST_STATE_NAME
        ,LS.GST_STATE_CODE AS LOC_GST_STATE_CODE
        ,'RECEIVER:- '+CASE WHEN MODE=1 THEN LM.AC_NAME ELSE TL.DEPT_NAME END 
         +CASE (SELECT TOP 1 ISNULL(IS_PARTY_ALIAS,0) FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE)
		   	   WHEN 0 THEN '' 
			   ELSE CASE WHEN MODE=1 THEN ISNULL('-'+LM.ALIAS,'') ELSE ISNULL('-'+TL.DEPT_ALIAS,'') END
		  END
		AS PARTY_NAME
        
        --05 AUG 2017
        --,CASE WHEN MODE=1   
        --      THEN RTRIM(LTRIM(LMP.ADDRESS0+' '+LMP.ADDRESS1+' '+LMP.ADDRESS2+' '+CUSAR.AREA_NAME +' '+CUSCT.CITY+' '+CUSAR.PINCODE ))   
        --      ELSE RTRIM(LTRIM(TL.ADDRESS1+' '+TL.ADDRESS2+' '+' '+TLAR.AREA_NAME+TLCT .CITY+' '+TLAR .PINCODE))    
        -- END   
        -- AS PARTY_ADDRESS
		,CASE WHEN MODE=1
		       THEN CASE LEN(ISNULL(LMP.ADDRESS0,'')) WHEN 0 THEN '' ELSE RTRIM(LTRIM(ISNULL(LMP.ADDRESS0,''))) END
			   ELSE CASE LEN(ISNULL(TL.ADDRESS1,'')) WHEN 0 THEN '' ELSE RTRIM(LTRIM(TL.ADDRESS1)) END
		 END
		 AS PARTY_ADDRESS1
				  
		 ,CASE WHEN MODE=1
		      THEN CASE LEN(ISNULL(LMP.ADDRESS1,'')) WHEN 0 THEN '' ELSE RTRIM(LTRIM(ISNULL(LMP.ADDRESS1,''))) END
		      ELSE CASE LEN(ISNULL(TL.ADDRESS2,'')) WHEN 0 THEN '' ELSE RTRIM(LTRIM(TL.ADDRESS2)) END
		 END
		 AS PARTY_ADDRESS2

		 ,CASE WHEN MODE=1
		       THEN CASE LEN(ISNULL(LMP.ADDRESS2,'')) WHEN 0 THEN '' ELSE RTRIM(LTRIM(ISNULL(LMP.ADDRESS2,''))) END
		       ELSE ''--CASE LEN(ISNULL(TL.ADDRESS1,'')) WHEN 0 THEN '' ELSE 'RECEIVER: '+RTRIM(LTRIM(TL.ADDRESS1))
		  END
		  AS PARTY_ADDRESS3
				        
		 ,CASE WHEN MODE=1
		       THEN RTRIM(LTRIM(CASE RIGHT(RTRIM(ISNULL(CUSAR.AREA_NAME,'')),1) WHEN ',' THEN LEFT(ISNULL(CUSAR.AREA_NAME,''),LEN(ISNULL(CUSAR.AREA_NAME,''))-1) ELSE ISNULL(CUSAR.AREA_NAME,'')END
		            +CASE LEN(ISNULL(CUSCT.CITY,'')) WHEN 0 THEN '' ELSE ', ' END+ISNULL(CUSCT.CITY,'')
		            +CASE LEN(ISNULL(CUSAR.PINCODE,'')) WHEN 0 THEN '' ELSE ', ' END+CUSAR.PINCODE))
		       ELSE RTRIM(LTRIM(ISNULL(TLAR.AREA_NAME,'')
		            +CASE LEN(ISNULL(TLCT.CITY,'')) WHEN 0 THEN '' ELSE ', ' END+ISNULL(TLCT.CITY,'')
		            +CASE LEN(ISNULL(TLAR.PINCODE,'')) WHEN 0 THEN '' ELSE ', ' END+TLAR.PINCODE))
		  END
		  +CASE ISNULL(' '+LMP.MOBILE,'') WHEN '' THEN '' ELSE ' PHONE- '+LMP.MOBILE END
		  AS PARTY_CITY
         --05 AUG 2017
         
        ,CASE WHEN MODE=1 THEN LMP.AC_GST_NO ELSE TL.LOC_GST_NO END AS PARTY_GST_NO
        ,ISNULL(CASE WHEN MODE=1 THEN CS.GST_STATE_NAME ELSE TS.GST_STATE_NAME END,'') AS PARTY_STATE_NAME
        ,ISNULL(CASE WHEN MODE=1 THEN CS.GST_STATE_CODE ELSE TS.GST_STATE_CODE END,'') AS PARTY_STATE_CODE
        ,CASE WHEN CNM.CANCELLED =1 THEN 'CANCELLED' ELSE '' END AS CANCELLED
        --,'CREDIT NOTE' AS INVOICE_TYPE--05 AUG 2017
        --,CASE WHEN MODE=2 THEN 'DELIVERY CHALLAN' ELSE (SELECT TOP 1 CAPTION FROM GST_XN_CAPTION WHERE LTRIM(RTRIM(XN_TYPE))=@CXN_TYPE) END AS INVOICE_TYPE--05 AUG 2017
        ,CASE WHEN L.REGISTERED_GST=1 AND L.LOC_GST_NO=PCOUNTRY.AC_GST_NO THEN 'DELIVERY CHALLAN'  
			  WHEN CNM.MODE=2 AND L.LOC_GST_NO=PCOUNTRY.AC_GST_NO THEN 'DELIVERY CHALLAN'  
			  ELSE (SELECT TOP 1 CAPTION FROM GST_XN_CAPTION WHERE LTRIM(RTRIM(XN_TYPE))=@CXN_TYPE) 
		 END AS INVOICE_TYPE
        ,ISNULL(LS.UT,0) AS UT
        ,(SELECT TOP 1 ISNULL(IS_ENABLED,0) FROM GST_TNC WHERE XN_TYPE=@CXN_TYPE)AS PRINT_TERM
        ,ISNULL(L.REGISTERED_ADD,'')REGISTERED_ADDRESS  
        ,ISNULL(CNM.REMARKS,'')REMARKS  
        --,BUYER_ORDER_NO=CASE ISNULL(BUYER_ORDER_NO,'') WHEN '' THEN '' ELSE 'P.O.NO: '+BUYER_ORDER_NO END  
        ,(SELECT TOP 1 LOGO FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE)LOGO  
        ,(SELECT TOP 1 NAME FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE)NAME
        ,(SELECT TOP 1 ADDRESS1 FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE)PRINT_ADDRESS1
        ,(SELECT TOP 1 TELEPHONE1 FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE)TELEPHONE1
        ,(SELECT TOP 1 CIN_NO FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE)CIN_NO
        ,(SELECT TOP 1 DATE_WITH_TIME FROM GST_COMPANY_CONFIG WHERE @CXN_TYPE=@CXN_TYPE)DATE_WITH_TIME
        ,ISNULL((SELECT SUM(XN_VALUE_WITHOUT_GST) FROM CND01106 (NOLOCK) WHERE CN_ID=@CXN_ID),0)
         +ISNULL(CNM.FREIGHT,0)
         +ISNULL(CNM.INSURANCE,0)
         +ISNULL(CNM.OTHER_CHARGES,0)
         AS [TAXABLEVALUE]  
        ,ISNULL((SELECT SUM(CGST_AMOUNT) FROM CND01106 (NOLOCK) WHERE CN_ID=@CXN_ID),0)
         +ISNULL(CNM.OTHER_CHARGES_CGST_AMOUNT,0)
         +ISNULL(CNM.FREIGHT_CGST_AMOUNT,0)
         +ISNULL(CNM.INSURANCE_CGST_AMOUNT,0)
        AS [CGSTAMOUNT]   
        ,ISNULL((SELECT SUM(SGST_AMOUNT) FROM CND01106 (NOLOCK) WHERE CN_ID=@CXN_ID),0)  
         +ISNULL(CNM.OTHER_CHARGES_SGST_AMOUNT,0)
         +ISNULL(CNM.FREIGHT_SGST_AMOUNT,0)
         +ISNULL(CNM.INSURANCE_SGST_AMOUNT,0)
        AS [SGSTAMOUNT]  
        ,ISNULL((SELECT SUM(IGST_AMOUNT) FROM CND01106 (NOLOCK) WHERE CN_ID=@CXN_ID),0)  
         +ISNULL(CNM.OTHER_CHARGES_IGST_AMOUNT,0)
         +ISNULL(CNM.FREIGHT_IGST_AMOUNT,0)
         +ISNULL(CNM.INSURANCE_IGST_AMOUNT,0)
        AS [IGSTAMOUNT]  
        ,ISNULL(CNM.FREIGHT,0) AS FREIGHT  
        ,ISNULL(CNM.INSURANCE,0) AS INSURANCE_AMOUNT  
        ,ISNULL(CNM.OTHER_CHARGES,0) AS OTHER_CHARGE  
        ,ISNULL(CNM.TOTAL_AMOUNT/*NET_AMOUNT*/,0) AS NETAMOUNT  
        ,ISNULL(CNM.ROUND_OFF,0) AS ROUND_OFF  
        ,ISNULL((SELECT SUM(CGST_AMOUNT+SGST_AMOUNT+IGST_AMOUNT) FROM CND01106(NOLOCK) WHERE CN_ID=@CXN_ID),0)
         +ISNULL(CNM.OTHER_CHARGES_CGST_AMOUNT,0)+ISNULL(CNM.FREIGHT_CGST_AMOUNT,0)+ISNULL(CNM.INSURANCE_CGST_AMOUNT,0)--+ISNULL(CNM.PACKING_CGST_AMOUNT,0)  
         +ISNULL(CNM.OTHER_CHARGES_SGST_AMOUNT,0)+ISNULL(CNM.FREIGHT_SGST_AMOUNT,0)+ISNULL(CNM.INSURANCE_SGST_AMOUNT,0)--+ISNULL(CNM.PACKING_SGST_AMOUNT,0)  
         +ISNULL(CNM.OTHER_CHARGES_IGST_AMOUNT,0)+ISNULL(CNM.FREIGHT_IGST_AMOUNT,0)+ISNULL(CNM.INSURANCE_IGST_AMOUNT,0)--+ISNULL(CNM.PACKING_IGST_AMOUNT,0)  
        AS [GSTCOLLECTION]  
        ,''BILL_NUMBER 
        ,CONVERT(VARCHAR,GETDATE(),105)AS BILL_DATE
        --22 AUG 2017
	    ,ISNULL((SELECT TOP 1 PRINT_REF_NO FROM GST_COMPANY_CONFIG WHERE XN_TYPE='WSR'),0) AS PRINT_REF_NO
	    ,CASE ISNULL(CNM.MANUAL_INV_NO,'') WHEN '' THEN '' ELSE 'REF NO: '+CNM.MANUAL_INV_NO END AS REF_NO        
		--03 FEB 2018
		,(SELECT TOP 1 ISNULL(PRINT_AUTHORIZED_SIGNATURE,0) FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE)PRINT_AUTHORIZED_SIGNATURE  
        --06 FEB 2018
		,ISNULL((SELECT TOP 1 TOP_MARGIN FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE),0.01)TOP_MARGIN
		,ISNULL((SELECT TOP 1 BOTTOM_MARGIN FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE),0.25)BOTTOM_MARGIN
		,ISNULL((SELECT TOP 1 LEFT_MARGIN FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE),0.30)LEFT_MARGIN
		,ISNULL((SELECT TOP 1 RIGHT_MARGIN FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE),0.25)RIGHT_MARGIN
		--08 FEB 2018
		,ISNULL((SELECT TOP 1 PRINT_COPIES FROM GST_SLS_CUSTOMER_CONFIG (NOLOCK) WHERE XN_TYPE=@CXN_TYPE),1)AS PRINT_COPIES
		--23 MAY 2018
		,ISNULL((SELECT TOP 1 PRINT_DISC_AMT_PUR FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE),0)PRINT_DISC_AMT_PUR
		,ISNULL((SELECT TOP 1 PRINT_DISC_PER_PUR FROM GST_COMPANY_CONFIG WHERE XN_TYPE=@CXN_TYPE),0)PRINT_DISC_PER_PUR
		,cnm.SHIPPING_ADDRESS
		,cnm.Total_Gst_Cess_Amount 
	    INTO #DATASET1
  FROM CNM01106 CNM (NOLOCK)    
  LEFT JOIN COMPANY CMP (NOLOCK) ON CMP.COMPANY_CODE='01'  
  LEFT OUTER JOIN LOCATION L (NOLOCK) ON L.DEPT_ID =CNM.location_Code 
  LEFT JOIN GST_STATE_MST LS (NOLOCK) ON LS.GST_STATE_CODE=L.GST_STATE_CODE  
  LEFT JOIN LMP01106 LMP (NOLOCK) ON LMP.AC_CODE=CNM.AC_CODE  
  LEFT JOIN GST_STATE_MST CS (NOLOCK) ON CS.GST_STATE_CODE=LMP.AC_GST_STATE_CODE  
  LEFT JOIN LM01106 LM (NOLOCK) ON LM.AC_CODE=LMP.AC_CODE  
  LEFT JOIN AREA CUSAR (NOLOCK) ON LMP.AREA_CODE=CUSAR.AREA_CODE  
  LEFT JOIN CITY CUSCT (NOLOCK) ON CUSAR.CITY_CODE=CUSCT.CITY_CODE  
  LEFT JOIN LMV01106 PCOUNTRY (NOLOCK) ON LM.AC_CODE=PCOUNTRY.AC_CODE--16 MAR 2018  
  LEFT OUTER JOIN LOCATION TL (NOLOCK) ON TL.DEPT_ID=CNM.PARTY_DEPT_ID  
  LEFT JOIN AREA TLAR (NOLOCK) ON TL.AREA_CODE=TLAR.AREA_CODE  
  LEFT JOIN CITY TLCT (NOLOCK) ON TLAR.CITY_CODE=TLCT.CITY_CODE  
  LEFT JOIN GST_STATE_MST TS (NOLOCK) ON TS.GST_STATE_CODE=TL.GST_STATE_CODE  
  left join LOC_VIEW lv (nolock) on lv.dept_id =L.dept_id 
  WHERE CNM.CN_ID=@CXN_ID
  
  UPDATE #DATASET1 SET ADDRESS1=REPLACE(ADDRESS1,'(WC)','')
  ,ADDRESS2=REPLACE(ADDRESS2,'(WC)','')
  ,CITY=REPLACE(CITY,'(WC)','')
  ,PARTY_ADDRESS1=REPLACE(PARTY_ADDRESS1,'(WC)','')
  ,PARTY_ADDRESS2=REPLACE(PARTY_ADDRESS2,'(WC)','')
  ,PARTY_ADDRESS3=REPLACE(PARTY_ADDRESS3,'(WC)','')
  ,PARTY_CITY=REPLACE(PARTY_CITY,'(WC)','')
  
		  
  --04 AUG 2017
  SELECT @CCOLNAME=ISNULL(@CCOLNAME+'+','  ')+'ISNULL('+SOURCENAME+'.'+QUOTENAME(COLUMNNAME) +','''')+'+''''+COLUMNSEPARATOR+''''+' '  
  FROM GST_XN_DETAIL  WHERE XN_TYPE =@CXN_TYPE AND ISVISIBLE=1  
  ORDER BY DISPLAYORDER  
  --SELECT @CCOLNAME=ISNULL(@CCOLNAME+'+','  ')+'LEFT('+SOURCENAME+'.'+QUOTENAME(COLUMNNAME)+','+CAST(COLUMNPRINTLENGTH AS VARCHAR)+')'+'+'+''''+COLUMNSEPARATOR+''''+' '  
  --FROM GST_XN_DETAIL  WHERE XN_TYPE =@CXN_TYPE AND ISVISIBLE=1  
  --ORDER BY DISPLAYORDER  
  --04 AUG 2017   
  
 
	DECLARE @BPRINTMRP BIT
	SELECT @BPRINTMRP=MRP FROM GST_COMPANY_CONFIG WHERE XN_TYPE ='WSR'
	SET @BPRINTMRP=ISNULL(@BPRINTMRP,0)
  
  IF RIGHT(@CCOLNAME,4)='+'''+(SELECT TOP 1 COLUMNSEPARATOR FROM GST_XN_DETAIL WHERE XN_TYPE =@CXN_TYPE AND ISVISIBLE=1)+''''  
     SET @CCOLNAME=LEFT(@CCOLNAME,LEN(@CCOLNAME)-4)  
  PRINT @CCOLNAME 
  
  SELECT ROW_NUMBER() OVER (ORDER BY AUTO_SRNO) AS SR_NO
         ,CAST('' AS VARCHAR(MAX)) AS PARTICULARS
         ,A.HSN_CODE
         ,UOM.UOM_NAME
         ,CAST(A.QUANTITY AS NUMERIC(10,2)) AS QUANTITY
         ,A.gross_rate   ,A.RATE
         ,CAST(A.QUANTITY*A.RATE AS NUMERIC(12,2)) AS AMOUNT
         ,CAST((A.QUANTITY*A.RATE )-ISNULL(XN_VALUE_WITHOUT_GST,0) AS NUMERIC(12,2)) 
          AS LESS_DISCOUNT
         ,A.IGST_AMOUNT AS DISCOUNT_PER 
         ,CAST(ISNULL(XN_VALUE_WITHOUT_GST,0) AS NUMERIC(12,2)) AS TAXABLE_VALUE
         ,CAST(CASE WHEN A.IGST_AMOUNT<>0 THEN A.GST_PERCENTAGE ELSE 0 END AS NUMERIC(12,0)) 
          AS IGST_RATE 
         ,A.IGST_AMOUNT
         ,CAST(CASE WHEN A.CGST_AMOUNT<>0 THEN (A.GST_PERCENTAGE)/2 ELSE 0 END AS NUMERIC(12,1)) AS CGST_RATE
         ,A.CGST_AMOUNT
         ,CAST(CASE WHEN A.SGST_AMOUNT<>0 THEN (A.GST_PERCENTAGE)/2 ELSE 0 END AS NUMERIC(12,1)) AS SGST_RATE
         ,A.SGST_AMOUNT
         ,A.XN_VALUE_WITH_GST AS TOTAL
         ,0/*B.NET_AMOUNT*/ AS NET_AMOUNT
         ,B.ROUND_OFF
         ,A.INV_NO AS BILL_NO   
         ,A.XN_VALUE_WITH_GST AS TOTAL_VALUE
         ,CAST('' AS VARCHAR(MAX)) AS [NRVN]
		 ,A.DISCOUNT_AMOUNT 
		 ,A.CNMDISCOUNTAMOUNT 
		 ,A.inm_discount_amount
		 ,A.IND_DISCOUNT_AMOUNT 
		 ,a.Gst_Cess_Amount 
		 ,a.INM_DISCOUNT_PERCENTAGE as INM_DISCOUNT_PERCENTAGE
		 ,a.ind_DISCOUNT_PERCENTAGE as IND_DISCOUNT_PERCENTAGE
		 ,SKU.MRP
  INTO #TMPDETAILS            
  FROM CND01106 A (NOLOCK)  
  JOIN CNM01106 B (NOLOCK) ON  A.CN_ID=B.CN_ID  
  LEFT JOIN SKU (NOLOCK) ON SKU.PRODUCT_CODE =A.PRODUCT_CODE     
  LEFT JOIN ARTICLE (NOLOCK) ON ARTICLE.ARTICLE_CODE =SKU.ARTICLE_CODE      
  LEFT JOIN UOM UOM (NOLOCK) ON UOM.UOM_CODE=ARTICLE.UOM_CODE  
  LEFT OUTER JOIN SECTIOND SD (NOLOCK) ON SD.SUB_SECTION_CODE=ARTICLE.SUB_SECTION_CODE  
  WHERE 1=2  
    
  SET @DTSQL=' INSERT INTO #TMPDETAILS(SR_NO,PARTICULARS,HSN_CODE,UOM_NAME,QUANTITY,gross_rate,RATE,AMOUNT,LESS_DISCOUNT,DISCOUNT_PER,TAXABLE_VALUE,IGST_RATE,IGST_AMOUNT,CGST_RATE,CGST_AMOUNT,SGST_RATE,SGST_AMOUNT,TOTAL,NET_AMOUNT,ROUND_OFF,BILL_NO,TOTAL_VALUE,[NRVN]
                 ,DISCOUNT_AMOUNT,CNMDISCOUNTAMOUNT,A.inm_discount_amount,A.IND_DISCOUNT_AMOUNT ,Gst_Cess_Amount,INM_DISCOUNT_PERCENTAGE,IND_DISCOUNT_PERCENTAGE ,MRP  )  
                SELECT ROW_NUMBER() OVER (ORDER BY '+ @CCOLNAME+' ) AS SR_NO
                , '+ @CCOLNAME+' AS PARTICULARS
                ,A.HSN_CODE
                ,UOM.UOM_NAME
                ,SUM(A.QUANTITY) AS QUANTITY
				,a.gross_rate
                ,A.RATE
                ,CAST(SUM(A.QUANTITY*A.RATE) AS NUMERIC(12,2)) AS AMOUNT  
                --,CAST((SUM(A.QUANTITY)*A.RATE)-SUM(ISNULL(XN_VALUE_WITHOUT_GST,0)) AS NUMERIC(12,2))
                ,CAST(SUM(A.DISCOUNT_AMOUNT+A.CNMDISCOUNTAMOUNT)
                      AS NUMERIC(12,2)) 
                AS LESS_DISCOUNT  
                ,0 DISCOUNT_PER  
                ,CAST(SUM(ISNULL(XN_VALUE_WITHOUT_GST,0)) AS NUMERIC(12,2)) AS TAXABLE_VALUE
                ,CAST(CASE WHEN SUM(A.IGST_AMOUNT)<>0 THEN  A.GST_PERCENTAGE ELSE 0 END AS NUMERIC(12,0)) AS IGST_RATE
                ,CAST(SUM(A.IGST_AMOUNT) AS NUMERIC(12,2)) AS IGST_AMOUNT
                ,CAST(CASE WHEN SUM(A.CGST_AMOUNT)<>0 THEN  (A.GST_PERCENTAGE)/2 ELSE 0 END AS NUMERIC(12,1)) AS CGST_RATE
                ,CAST(SUM(A.CGST_AMOUNT) AS NUMERIC(12,2)) AS CGST_AMOUNT
                ,CAST(CASE WHEN SUM(A.SGST_AMOUNT)<>0 THEN  (A.GST_PERCENTAGE)/2 ELSE 0 END AS NUMERIC(12,1)) AS SGST_RATE
                ,CAST(SUM(A.SGST_AMOUNT) AS NUMERIC(12,2)) AS SGST_AMOUNT
                ,CAST(SUM(A.XN_VALUE_WITH_GST) AS NUMERIC(12,2)) AS TOTAL
                ,B.TOTAL_AMOUNT AS NET_AMOUNT
                ,B.ROUND_OFF 
                --24 JUL 2017
                ,ISNULL(A.INV_NO,'''')+CASE YEAR(ISNULL(A.INV_DT,'''')) WHEN 1900 THEN '''' ELSE ''/''+CONVERT(VARCHAR,A.INV_DT,105) END INV_NO
                ,CAST(SUM(A.QUANTITY*A.RATE) AS NUMERIC(12,2)) AS AMOUNT  
                --31 JAN 2018
                ,RTRIM(LTRIM(B.CN_NO))+''/''+RTRIM(LTRIM(A.INV_NO))+''/''+REPLACE(CAST (A.GST_PERCENTAGE AS VARCHAR(10)),''.00'','''') AS [NRVN]
				,sum(a.DISCOUNT_AMOUNT) as DISCOUNT_AMOUNT
				,sum(a.CNMDISCOUNTAMOUNT) as CNMDISCOUNTAMOUNT
                ,sum(a.inm_discount_amount) as inm_discount_amount
				,sum(a.IND_DISCOUNT_AMOUNT) as IND_DISCOUNT_AMOUNT
				,sum(isnull(a.Gst_Cess_Amount,0)) as Gst_Cess_Amount
                ,a.INM_DISCOUNT_PERCENTAGE,a.IND_DISCOUNT_PERCENTAGE
				,CASE WHEN '+RTRIM(LTRIM(STR(@BPRINTMRP)))+'=1 THEN SKU.MRP ELSE 0 END
                FROM CND01106 A (NOLOCK)  
                JOIN CNM01106 B (NOLOCK) ON  A.CN_ID=B.CN_ID  
                LEFT JOIN SKU (NOLOCK) ON SKU.PRODUCT_CODE =A.PRODUCT_CODE     
                LEFT JOIN ARTICLE (NOLOCK) ON ARTICLE.ARTICLE_CODE =SKU.ARTICLE_CODE      
                LEFT JOIN UOM UOM (NOLOCK) ON UOM.UOM_CODE=ARTICLE.UOM_CODE  
                LEFT OUTER JOIN SECTIOND  (NOLOCK) ON SECTIOND.SUB_SECTION_CODE=ARTICLE.SUB_SECTION_CODE  
                LEFT OUTER JOIN SECTIONM  (NOLOCK) ON SECTIONM.SECTION_CODE=SECTIOND.SECTION_CODE  
                LEFT OUTER JOIN PARA1 ON PARA1.PARA1_CODE=SKU.PARA1_CODE  
                LEFT OUTER JOIN PARA2 ON PARA2.PARA2_CODE=SKU.PARA2_CODE  
                LEFT OUTER JOIN PARA3 ON PARA3.PARA3_CODE=SKU.PARA3_CODE  
                LEFT OUTER JOIN PARA4 ON PARA4.PARA4_CODE=SKU.PARA4_CODE  
                LEFT OUTER JOIN PARA5 ON PARA5.PARA5_CODE=SKU.PARA5_CODE  
                LEFT OUTER JOIN PARA6 ON PARA6.PARA6_CODE=SKU.PARA6_CODE  
                WHERE A.CN_ID='''+@CXN_ID+'''  
                GROUP BY '+ @CCOLNAME+',A.HSN_CODE,UOM.UOM_NAME,a.gross_rate,A.RATE,A.GST_PERCENTAGE ,B.TOTAL_AMOUNT ,B.ROUND_OFF
				,a.INM_DISCOUNT_PERCENTAGE,a.IND_DISCOUNT_PERCENTAGE
                --24 JUL 2017
                ,ISNULL(A.INV_NO,'''')+CASE YEAR(ISNULL(A.INV_DT,'''')) WHEN 1900 THEN '''' ELSE ''/''+CONVERT(VARCHAR,A.INV_DT,105) END
                --31 JAN 2018
                ,RTRIM(LTRIM(B.CN_NO))+''/''+RTRIM(LTRIM(A.INV_NO))+''/''+REPLACE(CAST (A.GST_PERCENTAGE AS VARCHAR(10)),''.00'','''')
				,CASE WHEN '+RTRIM(LTRIM(STR(@BPRINTMRP)))+'=1 THEN SKU.MRP ELSE 0 END
                ORDER BY '+ @CCOLNAME+''  
  PRINT @DTSQL  
  --EXEC SP_EXECUTESQL @DTSQL  
  EXEC(@DTSQL)
  
  --24 JUL 2017
  UPDATE #TMPDETAILS SET DISCOUNT_PER=ROUND(ISNULL(LESS_DISCOUNT,0)/CASE ISNULL(TOTAL_VALUE,0) WHEN 0 THEN 1 ELSE ISNULL(TOTAL_VALUE,0) END*100.0,2)
  --24 JUL 2017   

 
  SELECT *,@MRP_TOTAL AS MRP_TOTAL,@BROKER_NAME AS BROKER_NAME 
   ,V.DEPT_ID LOC_COMP_ID
   ,V.ADDRESS1 LOC_COMP_ADD1
   ,V.ADDRESS2 LOC_COMP_ADD2
   ,V.TAN_NO LOC_COMP_TANNO
   ,V.PAN_NO LOC_COMP_PANNO
   ,V.TIN_NO LOC_COMP_TINNO
   ,V.CITY LOC_COMP_CITY 
   ,V.PINCODE LOC_COMP_PINCODE
   ,V.[STATE] LOC_COMP_STATE
   ,V.PHONE LOC_COMP_PHONE
   ,V.dept_name LOC_COMP_NAME   
  FROM #DATASET1	
  JOIN (SELECT L.DEPT_ID,ADDRESS1,ADDRESS2,TAN_NO,PAN_NO,TIN_NO,C.CITY,A.PINCODE,S.STATE,L.PHONE,l.dept_name  
		FROM LOCATION L  
		LEFT JOIN AREA A ON A.AREA_CODE=L.AREA_CODE  
		LEFT JOIN CITY C ON A.CITY_CODE=C.CITY_CODE  
		LEFT JOIN STATE S ON S.STATE_CODE=C.STATE_CODE )V 
  ON @LocId =V.DEPT_ID		


  
  SELECT SR_NO,PARTICULARS,HSN_CODE,UOM_NAME,QUANTITY,gross_rate ,RATE,AMOUNT,LESS_DISCOUNT,DISCOUNT_PER,TAXABLE_VALUE,IGST_RATE,  
         IGST_AMOUNT,CGST_RATE,CGST_AMOUNT,SGST_RATE,SGST_AMOUNT,TOTAL ,NET_AMOUNT,ROUND_OFF,BILL_NO,[NRVN]  ,
		 DISCOUNT_AMOUNT,CNMDISCOUNTAMOUNT      ,inm_discount_amount
		 ,IND_DISCOUNT_AMOUNT ,
		 INM_DISCOUNT_PERCENTAGE as INM_DISCOUNT_PERCENTAGE,
		 IND_DISCOUNT_PERCENTAGE as IND_DISCOUNT_PERCENTAGE,
		 Gst_Cess_Amount ,MRP
  FROM #TMPDETAILS   
  ORDER BY SR_NO   
     
  SELECT TNC_1,TNC_2,TNC_3,TNC_4,TNC_5,TNC_6   
  FROM GST_TNC WHERE XN_TYPE=@CXN_TYPE  
    
  SELECT B.PAYMODE_NAME 
  FROM PAYMODE_XN_DET A
  JOIN PAYMODE_MST B ON A.PAYMODE_CODE=B.PAYMODE_CODE
  WHERE A.XN_TYPE =@CXN_TYPE AND A.MEMO_ID=@CXN_ID
  GROUP BY B.PAYMODE_NAME  
     
  --ADD NEW AS BLOCK FOR GST PERCENTAGE  
  SELECT *  
         ,[IGST_PER]=CASE ISNULL([IGST_AMOUNT],0) WHEN 0 THEN '0%' WHEN [GST_COLLECTION] THEN GST ELSE GST END  
         ,[CGST_PER]=CASE ISNULL([CGST_AMOUNT],0) WHEN 0 THEN '0%' ELSE DBO.CURR_GROUPING(ROUND(CAST(REPLACE([GST],'%','') AS DECIMAL(10,2))/2,2),'')+'%' END  
         ,[SGST_PER]=CASE ISNULL([SGST_AMOUNT],0) WHEN 0 THEN '0%' ELSE DBO.CURR_GROUPING(ROUND(CAST(REPLACE([GST],'%','') AS DECIMAL(10,2))/2,2),'')+'%' END  
  FROM  
  (  
    SELECT CAST(DBO.CURR_GROUPING(GST_PERCENTAGE,'') AS VARCHAR)+'%'[GST]  
   ,SUM(XN_VALUE_WITHOUT_GST)[TAXABLE_VALUES]  
   ,SUM(CGST_AMOUNT)[CGST_AMOUNT]   
   ,SUM(SGST_AMOUNT)[SGST_AMOUNT]   
   ,SUM(IGST_AMOUNT)[IGST_AMOUNT]  
   ,SUM(ISNULL(GST_CESS_AMOUNT,0)) [GST_CESS_AMOUNT]  
   ,SUM(CGST_AMOUNT+SGST_AMOUNT+IGST_AMOUNT)[GST_COLLECTION]  
   FROM CND01106 (NOLOCK) 
   WHERE CN_ID=@CXN_ID  
   GROUP BY CAST(DBO.CURR_GROUPING(GST_PERCENTAGE,'') AS VARCHAR)  
  )GST  
        
           
  SELECT *   
  FROM  
  (  
   SELECT CASE OH_NAME WHEN 'OC' THEN 'OTHER CHARGES' ELSE OH_NAME END AS OH_NAME  
   ,HSN_CODE AS HSNSAC_CODE  
   ,OH_GST_PER    =CASE OH_NAME WHEN 'FREIGHT' THEN FREIGHT_GST_PERCENTAGE 
                                WHEN 'OC' THEN OTHER_CHARGES_GST_PERCENTAGE  
                                WHEN 'INSURANCE' THEN INSURANCE_GST_PERCENTAGE 
                   END
   ,OH_SGST_AMOUNT=CASE OH_NAME WHEN 'OC' THEN ISNULL(OTHER_CHARGES_SGST_AMOUNT,0) 
                                WHEN 'FREIGHT' THEN ISNULL(FREIGHT_SGST_AMOUNT,0) 
                                WHEN 'INSURANCE' THEN ISNULL(INSURANCE_SGST_AMOUNT,0) 
                   END  
   ,OH_CGST_AMOUNT=CASE OH_NAME WHEN 'OC' THEN ISNULL(OTHER_CHARGES_CGST_AMOUNT,0) 
								WHEN 'FREIGHT' THEN ISNULL(FREIGHT_CGST_AMOUNT,0) 
								WHEN 'INSURANCE' THEN ISNULL(INSURANCE_CGST_AMOUNT,0)
			       END
   ,OH_IGST_AMOUNT=CASE OH_NAME WHEN 'OC' THEN ISNULL(OTHER_CHARGES_IGST_AMOUNT,0) 
								WHEN 'FREIGHT' THEN ISNULL(FREIGHT_IGST_AMOUNT,0) 
								WHEN 'INSURANCE' THEN ISNULL(INSURANCE_IGST_AMOUNT,0)
				   END
   ,OH_TAXABLE_VALUE=CASE OH_NAME WHEN 'OC' THEN ISNULL(OTHER_CHARGES_TAXABLE_VALUE,0) 
								WHEN 'FREIGHT' THEN ISNULL(FREIGHT_TAXABLE_VALUE,0) 
								WHEN 'INSURANCE' THEN ISNULL(INSURANCE_TAXABLE_VALUE,0)
				   END
   FROM GST_OH_CONFIG,CNM01106 (NOLOCK)  
   WHERE CN_ID=@CXN_ID AND OH_NAME<>'PACKING'
  )T  
  WHERE ISNULL(OH_GST_PER,0)<>0

  SELECT HSN_CODE HSNSACCODE,SUM(TAXABLE_VALUE)TAXABLEVALUE                      
   ,CAST(IGST_RATE AS DECIMAL(10,2))HSNIGSTPER,SUM(IGST_AMOUNT)HSNIGSTAMOUNT                      
   ,CAST(CGST_RATE AS DECIMAL(10,2))HSNCGSTPER,SUM(CGST_AMOUNT)HSNCGSTAMOUNT                      
   ,CAST(SGST_RATE AS DECIMAL(10,2))HSNSCGSTPER,SUM(SGST_AMOUNT)HSNSCGSTAMOUNT                      
   ,SUM(TOTAL)HSNTOTALAMOUNT  
   ,sum(GST_CESS_AMOUNT) as HSNCESSAMOUNT                      
   ,SUM(QUANTITY)HSNQUANTITY                        
   FROM #TMPDETAILS                      
   GROUP BY HSN_CODE,IGST_RATE,CGST_RATE,SGST_RATE  
   
  GOTO END_PROC  
END TRY    


BEGIN CATCH
  BEGIN
    SELECT @CERRMSG='ERROR MESSAGE IN PROCEDURE SP3S_PRINTCREDITNOTE_GST STEP#'+@CSTEP+' '+CAST(ERROR_MESSAGE() AS VARCHAR(MAX))+ '||'+ERROR_PROCEDURE()
    GOTO END_PROC
  END
END CATCH
     
END_PROC:
  SELECT @CERRMSG AS ERRMSG
SET NOCOUNT OFF  
END--END SP3S_PRINTCREDITNOTE_GST