CREATE PROCEDURE SP_EDIT_ATTENDANCE
(
 @NMONTH INT,@NYEAR INT,@NMODE INT, @NSPID INT,@CREF_ID CHAR(50),@CDEPARTMENT_ID CHAR(7),@CLOC_ID CHAR(7)=''
)
--WITH ENCRYPTION
AS
BEGIN
BEGIN TRY

  DECLARE @COLUMN DATETIME, @CCMD NVARCHAR(MAX),@TIMEIN DATETIME, @TIMEOUT DATETIME,
  @CSOURCEDB VARCHAR(200),@CDESTDB VARCHAR(200),@CTABLENAME VARCHAR(200),@CTMP_TABLENAME VARCHAR(200),
  @CKEYFIELD1 VARCHAR(200),@CKEYFIELD2 VARCHAR(200),@CERROR VARCHAR(1000),@CFILTER NVARCHAR(MAX),@CSTEP VARCHAR(10),
  @CERRMSG NVARCHAR(500),@TEMP_TABLE VARCHAR(100),@CVALUE VARCHAR(100)

 BEGIN TRANSACTION 
  IF (@NMODE = 1)
  BEGIN 
		  SET @CSTEP = '10'
		  IF OBJECT_ID('#TEMP1','U') IS NOT NULL
				DROP TABLE #TEMP1
		  IF OBJECT_ID('#TEMP2','U') IS NOT NULL
				DROP TABLE #TEMP2
		  IF OBJECT_ID('#TEMP3','U') IS NOT NULL
				DROP TABLE #TEMP3
		  IF OBJECT_ID('#TEMP4','U') IS NOT NULL
				DROP TABLE #TEMP4		
		  
		  SET @CSTEP = '20'
		  SELECT EMP_ID INTO #TEMP1 FROM EMP_ATTENDANCE
		  WHERE 1=2
		  SELECT EMP_ID INTO #TEMP2 FROM EMP_ATTENDANCE
		  WHERE 1=2
		  SELECT  ATTENDANCE_DT INTO #TEMP3 FROM EMP_ATTENDANCE
		  WHERE 1=2
		  CREATE TABLE #TEMP4 (ATTENDANCE_DT DATETIME,EMP_ID VARCHAR(100))
		  
		  SET @CSTEP = '30'
		  IF ISNULL(@CREF_ID,'') <> ''
		  BEGIN
			PRINT 'XNZ'+@CREF_ID
		   	SET @CFILTER = N' WHERE A.REF_ID = '''+RTRIM(LTRIM(@CREF_ID))+''' AND INACTIVE = 0 AND EMP_STATUS  <> 2 '+(CASE WHEN ISNULL(@CLOC_ID,'')='' THEN '' ELSE ' AND DEPT_ID = '''+@CLOC_ID+'''' END)
		  END
		  ELSE 
		  IF ISNULL(@CDEPARTMENT_ID,'') <> ''
		  BEGIN 	
		   	SET @CFILTER = N' WHERE A.DEPARTMENT_ID = '''+@CDEPARTMENT_ID+''' AND INACTIVE = 0 AND EMP_STATUS  <> 2 '+(CASE WHEN ISNULL(@CLOC_ID,'')='' THEN '' ELSE ' AND DEPT_ID = '''+@CLOC_ID+'''' END)	
		  END
		  ELSE
		  IF (@NMONTH = 0 OR @NYEAR = 0)
		  BEGIN
			SET @CFILTER = N' WHERE 1=2'
		  END
		  ELSE
		  BEGIN
		   	SET @CFILTER = ' WHERE INACTIVE = 0 AND EMP_STATUS  <> 2 '+(CASE WHEN ISNULL(@CLOC_ID,'')='' THEN '' ELSE ' AND DEPT_ID = '''+@CLOC_ID+'''' END)
		  END
		 PRINT @CFILTER
		 
		 SET @CSTEP = '40'  		
		 SET @CCMD = N'SELECT DISTINCT A.EMP_ID FROM EMP_MST A '+@CFILTER+' '
		 PRINT'ABC'
		 PRINT @CCMD
		 INSERT INTO #TEMP1
		 EXEC SP_EXECUTESQL @CCMD
		 INSERT INTO #TEMP2
		 EXEC SP_EXECUTESQL @CCMD
		 
		 SET @CSTEP = '50'
		 SET @CCMD = N'SELECT DISTINCT ATTENDANCE_DT FROM EMP_ATTENDANCE WHERE MONTH(ATTENDANCE_DT) = '+STR(@NMONTH)+' AND YEAR(ATTENDANCE_DT) = '+STR(@NYEAR)+' ORDER BY ATTENDANCE_DT'
         PRINT @CCMD
         INSERT INTO #TEMP3
         EXEC SP_EXECUTESQL @CCMD
         
         SET @CSTEP = '52'
         SET @CCMD = N'SELECT ATTENDANCE_DT,EMP_ID FROM #TEMP1 CROSS JOIN  #TEMP3'
         PRINT @CCMD
         INSERT INTO #TEMP4
         EXEC SP_EXECUTESQL @CCMD
           
		 SET @CSTEP = '60'
		 SET @CCMD = N'ALTER TABLE #TEMP1 ADD [DEPARTMENT_NAME] VARCHAR(100),[LOCATION_NAME] VARCHAR(100),MODE INT
					   ALTER TABLE #TEMP2 ADD [DEPARTMENT_NAME] VARCHAR(100),[LOCATION_NAME] VARCHAR(100),MODE INT'
		 PRINT @CCMD
		 EXEC SP_EXECUTESQL @CCMD
		   
		 WHILE (SELECT TOP 1 'U' FROM #TEMP3) = 'U'
		 BEGIN
				SET @CSTEP = '70'
				SET @COLUMN = (SELECT TOP 1 ATTENDANCE_DT FROM #TEMP3) 
				SET @CCMD = N'ALTER TABLE #TEMP1
							  ADD ['+CONVERT(VARCHAR,@COLUMN,105)+'] CHAR(5)'
				PRINT @CCMD 
				EXEC SP_EXECUTESQL @CCMD
				
				SET @CSTEP = '80'
				SET @CCMD = N'ALTER TABLE #TEMP2
							  ADD ['+CONVERT(VARCHAR,@COLUMN,105)+'] CHAR(5)'
				PRINT @CCMD 
				EXEC SP_EXECUTESQL @CCMD
				
				
				SET @CSTEP = '90'
				SET @CCMD = N'UPDATE A SET A.['+CONVERT(VARCHAR,@COLUMN,105)+'] = CONVERT(VARCHAR(5),B.TIME_IN,8)
							 FROM #TEMP1 A JOIN EMP_ATTENDANCE B
				ON A.EMP_ID = B.EMP_ID WHERE B.ATTENDANCE_DT = '''+CONVERT(VARCHAR,@COLUMN)+''''
				
				PRINT @CCMD
				EXEC SP_EXECUTESQL @CCMD
				
				SET @CCMD = N'UPDATE #TEMP1 SET ['+CONVERT(VARCHAR,@COLUMN,105)+'] = ''00:00'' WHERE ['+CONVERT(VARCHAR,@COLUMN,105)+'] IS NULL'
				PRINT @CCMD
				EXEC SP_EXECUTESQL @CCMD
				
				SET @CCMD = N'UPDATE #TEMP2 SET ['+CONVERT(VARCHAR,@COLUMN,105)+'] = ''00:00'' WHERE ['+CONVERT(VARCHAR,@COLUMN,105)+'] IS NULL'
				PRINT @CCMD
				EXEC SP_EXECUTESQL @CCMD

				SET @CSTEP = '100'
				SET @CCMD = N'UPDATE A SET A.['+CONVERT(VARCHAR,@COLUMN,105)+'] = CONVERT(VARCHAR(5),B.TIME_OUT,8)
							   FROM #TEMP2 A JOIN EMP_ATTENDANCE B
				ON A.EMP_ID = B.EMP_ID WHERE B.ATTENDANCE_DT = '''+CONVERT(VARCHAR,@COLUMN)+''''
				PRINT @CCMD
				EXEC SP_EXECUTESQL @CCMD
				
				DELETE FROM #TEMP3 WHERE ATTENDANCE_DT = @COLUMN
		 END

			SET @CSTEP = '110'
			SET @CCMD = N'UPDATE A SET MODE=1, A.[DEPARTMENT_NAME] = C.DEPARTMENT_NAME,A.[LOCATION_NAME] = D.DEPT_ID + ''-'' + D.DEPT_NAME FROM 
						#TEMP1 A JOIN EMP_MST B ON A.EMP_ID = B.EMP_ID JOIN EMP_DEPARTMENT C ON B.DEPARTMENT_ID = C.DEPARTMENT_ID 
						JOIN LOCATION D ON B.DEPT_ID = D.DEPT_ID
						  UPDATE A SET MODE=2, A.[DEPARTMENT_NAME] = C.DEPARTMENT_NAME,A.[LOCATION_NAME] = D.DEPT_ID + ''-'' + D.DEPT_NAME FROM 
						#TEMP2 A JOIN EMP_MST B ON A.EMP_ID = B.EMP_ID JOIN EMP_DEPARTMENT C ON B.DEPARTMENT_ID = C.DEPARTMENT_ID
						JOIN LOCATION D ON B.DEPT_ID = D.DEPT_ID'			  
			PRINT @CCMD
			
			EXEC SP_EXECUTESQL @CCMD
			
			SET @CSTEP = '115'
			SELECT A.REF_ID,(A.EMP_FNAME+' '+A.EMP_LNAME)AS NAME,B.*  FROM   
			(SELECT * FROM #TEMP1 UNION ALL SELECT * FROM #TEMP2) B 
			JOIN EMP_MST A ON A.EMP_ID = B.EMP_ID
			ORDER BY B.EMP_ID,B.MODE
		    
		    SET @CSTEP = '120'
		    SET @TEMP_TABLE = DB_NAME()+'_TEMP.DBO.TEMP_EMP_ATTENDANCE_'+LTRIM(RTRIM(@NSPID))
		    		     
		    SET @CCMD = N'IF OBJECT_ID('''+@TEMP_TABLE+''',''U'') IS NOT NULL
							DROP TABLE '+@TEMP_TABLE+''
			PRINT @CCMD
			EXEC SP_EXECUTESQL @CCMD
			
		    SELECT CONVERT(VARCHAR,A.ATTENDANCE_DT,105) AS ATTENDANCE_DT_APP,0 AS ISEDITED,ISNULL(B.ENTRY_MODE,1) AS ENTRY_MODE , A.*,ISNULL(B.TIME_IN,'1900-01-01 00:00:00.000') AS TIME_IN,ISNULL(B.TIME_OUT,'1900-01-01 00:00:00.000') AS TIME_OUT,
		    ISNULL(B.ROW_ID,NEWID()) AS  ROW_ID,ISNULL(B.LOG_ABSENT_STATUS,0) AS LOG_ABSENT_STATUS,C.DEPT_ID,C.SHIFT_ID
		    FROM #TEMP4 A
		    LEFT OUTER JOIN EMP_ATTENDANCE B ON A.EMP_ID = B.EMP_ID AND A.ATTENDANCE_DT = B.ATTENDANCE_DT 
		    JOIN EMP_MST C ON A.EMP_ID = C.EMP_ID
		    WHERE C.DEPT_ID = (CASE WHEN ISNULL(@CLOC_ID,'') = '' THEN C.DEPT_ID ELSE @CLOC_ID END)
		    ORDER BY EMP_ID,ATTENDANCE_DT		
	END	
	ELSE IF(@NMODE = 2)
	BEGIN
	    SET @CSTEP = '130'
	    
		
		SET @CDESTDB   = DB_NAME()+'.DBO.'
				
		SET @CSOURCEDB = @CDESTDB
			
		SET @CTABLENAME= 'EMP_ATTENDANCE'        
		SET @CTMP_TABLENAME=@CTABLENAME+'_'+LTRIM(RTRIM(@NSPID))        
		SET @CKEYFIELD1='ROW_ID' 
		 
		
		SET @TEMP_TABLE = @CSOURCEDB+@CTMP_TABLENAME
		PRINT  @TEMP_TABLE  
	    IF OBJECT_ID(''+@TEMP_TABLE+'','U') IS NULL
	    BEGIN
			SET @CERRMSG='P:SP_EDIT_ATTENDANCE, STEP:'''+@CSTEP+''', MESSAGE: TEMP TABLE NOT FOUND.'
			GOTO EXIT_PROC
		END
		
		SET @CSTEP = '140'
		EXEC UPDATEMASTERXN   
				@CSOURCEDB = @CSOURCEDB,  
				@CSOURCETABLE = @CTMP_TABLENAME,  
				@CDESTDB  = @CDESTDB,  
				@CDESTTABLE = @CTABLENAME,  
				@CKEYFIELD1 = @CKEYFIELD1, 
				@BALWAYSUPDATE = 1,
				@LUPDATEONLY = 1
		
		SET @CSTEP = '150'
		EXEC UPDATEMASTERXN   
				@CSOURCEDB = @CSOURCEDB,  
				@CSOURCETABLE = @CTMP_TABLENAME,  
				@CDESTDB  = @CDESTDB,  
				@CDESTTABLE = @CTABLENAME,  
				@CKEYFIELD1 = @CKEYFIELD1, 
				@LINSERTONLY = 1,
				@CFILTERCONDITION = '(B.TIME_IN <> '''' OR B.TIME_OUT <> '''')'
					
				SELECT '' AS ERRMSG
		GOTO EXIT_PROC		 
   END 
   
  
   ELSE IF(@NMODE = 3)
   BEGIN
			  
			DECLARE @RESULT TABLE (TYPE VARCHAR(20),MESSAGE VARCHAR(200), VALUE VARCHAR(1000))
			DECLARE @DT DATETIME
			SET @CSTEP = '200'
		    SET @TEMP_TABLE = DB_NAME()+'_TEMP.DBO.TEMP_EXCLEMPATT_'+LTRIM(RTRIM(@NSPID))
			
			SET @CSTEP = '230'
			SET @CCMD = N'IF OBJECT_ID('''+@TEMP_TABLE+''',''U'') IS NULL
							SET @CERRMSG = ''TEMP TABLE NOT FOUND.'''
			PRINT @CCMD
			EXEC SP_EXECUTESQL @CCMD,N'@CERRMSG VARCHAR(MAX) OUTPUT',@CERRMSG OUTPUT
			
			SET @CSTEP = '240'
			IF ISNULL(@CERRMSG,'') <> ''
			BEGIN
				GOTO EXIT_PROC
			END
			
			SET @CSTEP = '250'
			SET @CCMD = N'SELECT ''ALERT'' AS TYPE,''EMP_ID NOT FOUND.'' AS MESSAGE, A.REF_ID AS VALUE FROM '+@TEMP_TABLE+' A LEFT OUTER 
						  JOIN EMP_MST B ON A.REF_ID = B.REF_ID WHERE  B.REF_ID IS NULL'
			PRINT @CCMD	
			
			SET @CSTEP = '280'
			INSERT INTO @RESULT
			EXEC SP_EXECUTESQL @CCMD
			
			SET @CSTEP = '300'
			SET @CCMD = N' SELECT ''ALERT'' AS TYPE,''TIME IN OR TIME OUT IS WRONG.'' AS MESSAGE,
						''EMP_ID: ''+REF_ID+'' ''+CONVERT(VARCHAR,ATT_DATE,105)+''TIME IN: ''+ LEFT(CONVERT(VARCHAR,INTIME,14),5)+'' TIME OUT: ''+LEFT(CONVERT(VARCHAR,OUTTIME,14),5) AS VALUE FROM '+@TEMP_TABLE+' 
						WHERE (LEFT(CONVERT(VARCHAR,INTIME,14),5) <> ''00:00'' OR LEFT(CONVERT(VARCHAR,OUTTIME,14),5) <> ''00:00'') AND LOG_ABSENT_STATUS  IN (''1'',''2'',''3'',''4'')' 
			PRINT @CCMD
			INSERT INTO @RESULT
			EXEC SP_EXECUTESQL @CCMD
			
			IF EXISTS(SELECT TOP 1 * FROM @RESULT)
				GOTO EXIT_PROC
			
			SET @CSTEP = '320'
			IF OBJECT_ID('#FINAL_RESULT','U') IS NOT NULL
				DROP TABLE #FINAL_RESULT
			
			IF OBJECT_ID('#DIST_DATE','U') IS NOT NULL
				DROP TABLE #DIST_DATE
				
			CREATE TABLE #FINAL_RESULT(REF_ID VARCHAR(100),MODE NUMERIC(1,0))
			CREATE TABLE #DIST_DATE(ATT_DATE DATETIME)
			
			SET @CSTEP = '330'
			SET @CCMD = N'SELECT DISTINCT REF_ID,1 AS MODE FROM '+@TEMP_TABLE+''
			PRINT @CCMD
			INSERT INTO #FINAL_RESULT
			EXEC SP_EXECUTESQL @CCMD
			
			SET @CSTEP = '350'
			SET @CCMD = N'SELECT DISTINCT REF_ID,2 AS MODE FROM '+@TEMP_TABLE+''
			PRINT @CCMD
			INSERT INTO #FINAL_RESULT
			EXEC SP_EXECUTESQL @CCMD
			
			SET @CSTEP = '380'
			SET @CCMD = N'SELECT DISTINCT ATT_DATE FROM '+@TEMP_TABLE+' ORDER BY ATT_DATE'
			PRINT @CCMD
			INSERT INTO #DIST_DATE
			EXEC SP_EXECUTESQL @CCMD
			
			
			WHILE EXISTS (SELECT TOP 1 * FROM #DIST_DATE)
			BEGIN
				SELECT TOP 1 @DT = ATT_DATE FROM #DIST_DATE
				SET @CSTEP = '400'
				SET @CCMD = N'ALTER TABLE #FINAL_RESULT
							  ADD ['+CONVERT(VARCHAR,@DT,105)+'] CHAR(5)'
				PRINT @CCMD
				EXEC SP_EXECUTESQL @CCMD
			
				SET @CSTEP = '430'
				SET @CCMD = N'UPDATE A SET A.['+CONVERT(VARCHAR,@DT,105)+']= B.IN_STR FROM  #FINAL_RESULT A
							  JOIN '+@TEMP_TABLE+' B ON A.REF_ID = B.REF_ID AND  ATT_DATE = '''+LEFT(CONVERT(VARCHAR,@DT,120),10)+'''
							  WHERE  A.MODE = 1'
				
				PRINT 	@CCMD		
				EXEC SP_EXECUTESQL @CCMD
								
				SET @CSTEP = '450'
				SET @CCMD = N'UPDATE A SET A.['+CONVERT(VARCHAR,@DT,105)+']=B.OUT_STR FROM  #FINAL_RESULT A 
							JOIN '+@TEMP_TABLE+' B ON A.REF_ID = B.REF_ID AND ATT_DATE = '''+LEFT(CONVERT(VARCHAR,@DT,120),10)+'''
							WHERE  A.MODE = 2'
				
				PRINT 	@CCMD				
				EXEC SP_EXECUTESQL @CCMD
				
				DELETE TOP (1) FROM #DIST_DATE
				
			END
			SET @CSTEP = '480'
			SELECT B.EMP_ID,(B.EMP_FNAME+' '+B.EMP_LNAME) AS NAME,C.DEPARTMENT_NAME AS [DEPARTMENT_NAME],D.DEPT_NAME AS [LOCATION_NAME],A.* FROM #FINAL_RESULT A 
			JOIN EMP_MST B ON A.REF_ID = B.REF_ID
			JOIN EMP_DEPARTMENT C ON C.DEPARTMENT_ID = B.DEPARTMENT_ID
			JOIN LOCATION D ON D.DEPT_ID = B.DEPT_ID
			ORDER BY REF_ID,MODE
			
			SET @CSTEP = '510'
			SET @CCMD = N'SELECT CONVERT(VARCHAR,CONVERT(DATETIME,A.ATT_DATE),105) AS ATTENDANCE_DT_APP,1 AS ISEDITED,ISNULL(C.ENTRY_MODE,1) AS ENTRY_MODE,ATT_DATE AS ATTENDANCE_DT,
						B.EMP_ID,CONVERT(DATETIME,IN_STR) AS TIME_IN,CONVERT(DATETIME,OUT_STR) AS TIME_OUT,
						CONVERT (VARCHAR(MAX), (CASE WHEN ISNULL(C.ROW_ID,'''') = '''' THEN NEWID() ELSE C.ROW_ID END)) AS ROW_ID,
						CONVERT (INT,A.LOG_ABSENT_STATUS) AS LOG_ABSENT_STATUS,B.DEPT_ID,B.SHIFT_ID   FROM '+@TEMP_TABLE+' A
						JOIN EMP_MST B ON A.REF_ID = B.REF_ID
						LEFT OUTER JOIN EMP_ATTENDANCE C ON C.EMP_ID = B.EMP_ID AND C.ATTENDANCE_DT=A.ATT_DATE
						ORDER BY EMP_ID, ATT_DATE'
			PRINT @CCMD	
			EXEC SP_EXECUTESQL @CCMD
			GOTO EXIT_PROC
	END
 END TRY
BEGIN CATCH
	SET @CERRMSG='P:SP_EDIT_ATTENDANCE, STEP:'+@CSTEP+', MESSAGE:'+ERROR_MESSAGE()
END CATCH

EXIT_PROC:
	
	IF (@NMODE =3)
	BEGIN
		IF ISNULL(@CERRMSG,'') = ''
				INSERT INTO @RESULT SELECT 'SUCCESS' AS TYPE,'' AS MESSAGE,'' AS VALUE
			ELSE
				INSERT INTO @RESULT SELECT 'ERROR' AS TYPE,@CERRMSG AS MESSAGE,'' AS VALUE
				
		SELECT 	* FROM @RESULT	
			
	END

    IF ISNULL(@CERRMSG,'')='' AND @@TRANCOUNT>0  
	BEGIN	
		COMMIT
		IF(@NMODE IN (2,3))
		BEGIN
			SET @CCMD = N'IF OBJECT_ID('''+@TEMP_TABLE+''',''U'') IS NOT NULL
								DROP TABLE '+@TEMP_TABLE+''
			PRINT @CCMD
			EXEC SP_EXECUTESQL @CCMD
		END	
	END
	ELSE IF ISNULL(@CERRMSG,'')<>'' AND @@TRANCOUNT>0
	BEGIN	
		ROLLBACK
		IF @NMODE <> 3
		SELECT @CERRMSG AS ERRMSG
	END	
END
