CREATE PROCEDURE SP3S_PARCEL_DETAILS  
(  
 ----LIST OF INPUT PARAMETERS WITH DESCRIPTION  
 @CXNTYPE VARCHAR(10)='',  
 @DFROMDATE DATETIME ='',  
 @DTODATE DATETIME= '',  
 @CPAYTYPE INT=0,  
 @CACCODE VARCHAR(100)= '',  
 @CAUNGDIACODE VARCHAR(100)= '',  
 @CRECEIPTNO VARCHAR(100)= '',  
 @CBILTYNO VARCHAR(100)='',  
 @DRECFROMDATE DATETIME='',  
 @DRECTODATE DATETIME='',  
 @NCANCELLED NUMERIC(1) =2,  
 @NSTATUS NUMERIC(1) =0  ,
 @NMODE INT=-1,
 @NPARCEL_TYPE INT=0,
 @NTRANSPORTER_BILL_STATUS  NUMERIC(1) =0 ,
 @COEMACCODE VARCHAR(100)= '',
 @CCITY_CODE VARCHAR(10)='',
 @CDEPTID VARCHAR(5)=''
)  
--WITH ENCRYPTION  
AS  
/*  
AUTHOR    : BABAN  
CREATION DATE : 18 OCTOBER 2014  
DESCRIPTION   : RETRUNS PARCEL DETAILS FOR A MEMO   
TEST DATA   
  :  
SP3S_PARCEL_DETAILS '0001115000000000000001'  
  
MODIFICATION HISTORY  
MODIFIED BY   :  
MODIFIED DATE :  
DESCRIPTION   :  
  
MODIFIED BY   :  
MODIFIED DATE :  
DESCRIPTION   :  
*/  
BEGIN  
---DECLARE PROC VARIABLES  
DECLARE @CERRMSG VARCHAR(500),@CSTEP VARCHAR(5)  
BEGIN TRY  
  
  
   IF @CXNTYPE <> 'VCH'  
   BEGIN  

	IF OBJECT_ID('TEMPDB..#TransporterBillStatus','U') IS NOT NULL
		DROP TABLE #TransporterBillStatus

		SELECT parcel_memo_id INTO #TransporterBillStatus FROM  parcel_mst (NOLOCK) WHERE 1=2
		SELECT parcel_memo_id,CONVERT(varchar(10),'') parcel_status,
		       TOT_QUANTITY=convert(numeric(14,2),0) ,TOT_QTY=convert(numeric(14,2),0),TOT_BOXES=convert(numeric(14,2),0)
		--,CONVERT(VARCHAR(50),'') as ref_memo_id 
		      
		INTO #OpenStatus 
		FROM  parcel_mst (NOLOCK) WHERE 1=2


	
		IF @NTRANSPORTER_BILL_STATUS=1
		BEGIN
			INSERT INTO #TransporterBillStatus(parcel_memo_id)
			SELECT parcel_memo_id FROM  parcel_mst (NOLOCK)
			WHERE ISNULL(ref_converted_transport_bill_memoid,'')=''
			AND (parcel_memo_dt BETWEEN @DFROMDATE AND @DTODATE)
		END
		ELSE IF @NTRANSPORTER_BILL_STATUS=2
		BEGIN
			INSERT INTO #TransporterBillStatus(parcel_memo_id)
			SELECT parcel_memo_id FROM  parcel_mst (NOLOCK)
			WHERE ISNULL(ref_converted_transport_bill_memoid,'')<>''
			AND (parcel_memo_dt BETWEEN @DFROMDATE AND @DTODATE)
		END
	
		-- as Discuss with Panka ji and Sanjiv sir parcel will be Repeated if single memo will be opend and upopened both (nagarmal 15092023)
		INSERT INTO #OpenStatus(parcel_memo_id,parcel_status,TOT_QUANTITY ,TOT_QTY ,TOT_BOXES )
		SELECT A.parcel_memo_id,
		       (case when ISNULL(REF_MEMO_ID,'')<>'' then 'Opened' else 'Unopened' end)   parcel_status ,
			   sum(b.QUANTITY) as TOT_QUANTITY,
			   sum(b.qty) as TOT_QTY,
			   sum(b.BOX_NO) as TOT_BOXES
		FROM  parcel_mst A (NOLOCK)
		JOIN parcel_DET b ON b.parcel_memo_id=a.parcel_memo_id
		WHERE parcel_memo_dt BETWEEN @DFROMDATE AND @DTODATE
		group by A.parcel_memo_id,(case when ISNULL(REF_MEMO_ID,'')<>'' then 'Opened' else 'Unopened' end) 

		--UPDATE a SET parcel_status=(CASE WHEN b.parcel_memo_id IS NOT NULL THEN 'Opened' ELSE 'Unopened' END)
		--FROM #OpenStatus a
		--LEFT JOIN (SELECT parcel_memo_id FROM #OpenStatus WHERE ref_memo_id<>'') b ON a.parcel_memo_id=b.parcel_memo_id
		
	 SELECT   PM.PARCEL_MEMO_NO,PM.PARCEL_MEMO_ID AS MEMO_ID,CHAR(9)+ CONVERT(VARCHAR,PM.PARCEL_MEMO_DT,105) AS PARCEL_MEMO_DT,  
			CHAR(9)+ CONVERT(VARCHAR,PM.RECEIPT_DT,105) AS BILTY_DT,  
			--,LM.AC_NAME,  
			CANCELLED=CASE WHEN PM.CANCELLED <>0 THEN 'CANCELLED' ELSE '' END,  
		PM.DEPT_ID
		,PM.CASH_RECEIPT_NO,PM.BILTY_NO,PM.REMARKS AS MST_REMARKS  
		,XN.XN_DESC AS  XN_TYPE
		,AM.ANGADIA_NAME AS TRANSPORTER   
		,'' as REF_MEMO_NO   , ISNULL(cash_amount,0) cash_amount
		,OpenStatus.TOT_BOXES as TOTAL_BOXES  
		,(CASE WHEN PM.CANCELLED=0 THEN OpenStatus.TOT_QUANTITY ELSE 0 END) AS QUANTITY   
		,(CASE WHEN PM.CANCELLED=0 THEN OpenStatus.TOT_QTY ELSE 0 END) AS WEIGHT   
		 ,(CASE WHEN PM.CANCELLED=0 THEN  PM.TOTAL_AMOUNT ELSE 0 END) AS FREIGHT_AMOUNT  
		 ,lm.ac_name 
		 ,US.username as USERNAME 
		 ,EU.username as EDT_USERNAME  
		 ,(CASE WHEN ISNULL( PM.Parcel_Type,0) = 1 THEN 'Linked' WHEN ISNULL( PM.Parcel_Type,0) = 2 THEN 'Open' ELSE '' END) AS Parcel_Type
		 ,(CASE WHEN ISNULL( PM.PAY_TYPE,0) = 1 THEN 'Paid by Company' ELSE 'Paid by Supplier/Customer' END) AS paymode
		 ,handled_by,Driver_name,vehicle_no
		 ,(CASE WHEN PM.CANCELLED=0 and OpenStatus.parcel_status<>'Unopened' THEN   PM.XN_NO_LIST ELSE '' END) AS XN_NO_LIST
		 ,OpenStatus.parcel_status
		 ,ISNULL(OEM.AC_NAME,'') AS OEM_AC_NAME
		 ,PM.route_form1,PM.route_form2,S.SHIPPING_NAME,OpenStatus.TOT_BOXES
		 ,CITY.CITY,lmp.MOBILE
	 FROM PARCEL_MST PM (NOLOCK)  
	 LEFT OUTER JOIN
	 (
		SELECT 'Purchase Invoice' AS XN_DESC,'PUR' AS XN_TYPE 
		UNION 
		SELECT 'Wholesale Credit Note' AS XN_DESC,'WSR' AS XN_TYPE 
		UNION 
		SELECT 'GRN' AS XN_DESC,'GRN' AS XN_TYPE 
		UNION
		SELECT 'Purchase Return' AS XN_DESC,'PRT' AS XN_TYPE 
		UNION 
		SELECT 'Wholesale Invoice' AS XN_DESC,'WSL' AS XN_TYPE 
		UNION 
		SELECT 'Material Issue' AS XN_DESC,'MIS' AS XN_TYPE 
		UNION 
		SELECT 'Jobwork Issue' AS XN_DESC,'JWI' AS XN_TYPE 
		UNION 
		SELECT 'Jobwork Receipt' AS XN_DESC,'JWR' AS XN_TYPE 
	 )XN ON XN.XN_TYPE=PM.xn_type
	 JOIN LM01106 LM (NOLOCK) ON PM.PARCEL_AC_CODE=LM.AC_CODE  
	 LEFT OUTER JOIN LMP01106  LMP (nolock) ON LM.AC_CODE = LMP.AC_CODE   
	 LEFT OUTER JOIN AREA (nolock) ON  LMP.AREA_CODE = AREA.AREA_CODE   
     LEFT OUTER JOIN CITY (nolock) ON  AREA.CITY_CODE = CITY.CITY_CODE  
	 LEFT OUTER JOIN LM01106 OEM (NOLOCK) ON PM.OEM_AC_CODE=OEM.AC_CODE  
	 JOIN ANGM AM (NOLOCK) ON PM.ANGADIA_CODE=AM.ANGADIA_CODE  
	 JOIN LOCATION LN (NOLOCK) ON LN.DEPT_ID=PM.DEPT_ID  
	 JOIN USERS US (NOLOCK) ON PM.USER_CODE=US.USER_CODE  
	 JOIN USERS EU (NOLOCK) ON PM.EDT_USER_CODE=EU.USER_CODE  
	 LEFT OUTER JOIN #TransporterBillStatus BillStatus ON BillStatus.parcel_memo_id=PM.parcel_memo_id
	 LEFT OUTER JOIN  #OpenStatus OpenStatus ON OpenStatus.parcel_memo_id=PM.parcel_memo_id
	-- (SELECT DISTINCT parcel_memo_id,parcel_status FROM #OpenStatus) OpenStatus ON OpenStatus.parcel_memo_id=PM.parcel_memo_id
	 LEFT OUTER JOIN SHIPPING_MODE S(NOLOCK) ON  PM.SHIPPING_CODE= S.SHIPPING_CODE  
	 WHERE (@CXNTYPE='' OR PM.XN_TYPE=@CXNTYPE)  
	 AND (@DFROMDATE='' OR PM.PARCEL_MEMO_DT BETWEEN @DFROMDATE AND @DTODATE)  
	 AND (@CPAYTYPE=0 OR PM.PAY_TYPE=@CPAYTYPE)  
	 AND (@CACCODE='' OR PM.PARCEL_AC_CODE =@CACCODE)  
	 AND (@CAUNGDIACODE='' OR PM.ANGADIA_CODE=@CAUNGDIACODE)  
	 AND (@CRECEIPTNO='' OR PM.CASH_RECEIPT_NO =@CRECEIPTNO)  
	 AND (@CBILTYNO='' OR PM.BILTY_NO=@CBILTYNO)  
	 AND (@DRECFROMDATE='' OR PM.RECEIPT_DT BETWEEN @DRECFROMDATE AND @DRECTODATE)  
	 AND (@NCANCELLED=2 OR PM.CANCELLED=@NCANCELLED)   
	 AND (@NMODE NOT IN (0,1) OR  PM.MODE=@NMODE) 
	 AND (@NPARCEL_TYPE =0 OR PM.parcel_type=@NPARCEL_TYPE) 
	 AND (@NSTATUS=0 OR OpenStatus.parcel_status=(CASE WHEN @NSTATUS=1 THEN 'Opened' ELSE 'Unopened' END) )
	 AND (@NTRANSPORTER_BILL_STATUS=0 OR BillStatus.parcel_memo_id IS NOT NULL)
	 AND (@COEMACCODE='' OR PM.OEM_AC_CODE =@COEMACCODE)  
	 AND (@CCITY_CODE='' OR CITY.CITY_code =@CCITY_CODE)  
	 AND (@CDEPTID='' OR PM.location_code =@CDEPTID)  
 END  
   
   
  IF @CXNTYPE = 'VCH'  
   BEGIN  
  
       
 SELECT   PM.VOUCHER_NO AS PARCEL_MEMO_NO,PM.VM_ID AS MEMO_ID,  
 CONVERT(VARCHAR,PM.VOUCHER_DT,105) AS PARCEL_MEMO_DT,  
 '' AS RECEIPT_DT  
 ,LM.AC_NAME,  
 CANCELLED=CASE WHEN PM.CANCELLED <>0 THEN 'CANCELLED' ELSE '' END,  
 US.USERNAME,EU.USERNAME AS EDIT_USERNAME  
 ,PM.LR_NO AS BILTY_NO,V.VOUCHER_TYPE AS XN_TYPE,AM.ANGADIA_NAME AS TRANSPORTER    
 ,(CASE WHEN PM.CANCELLED=0 THEN  PM.DRTOTAL  ELSE 0 END) AS TOTAL_AMOUNT   
 FROM VM01106 PM (NOLOCK)  
 JOIN VD01106 PD (NOLOCK) ON PM.VM_ID=PD.VM_ID AND X_TYPE= 'DR'  
 JOIN VCHTYPE V ON PM.VOUCHER_CODE = V.VOUCHER_CODE   
 JOIN LM01106 LM ON PD.AC_CODE= LM.AC_CODE   
 LEFT OUTER JOIN LMP01106  LMP (nolock) ON LM.AC_CODE = LMP.AC_CODE   
 LEFT OUTER JOIN AREA (nolock) ON  LMP.AREA_CODE = AREA.AREA_CODE   
 LEFT OUTER JOIN CITY (nolock) ON  AREA.CITY_CODE = CITY.CITY_CODE  
 JOIN ANGM AM (NOLOCK) ON PM.ANGADIA_CODE=AM.ANGADIA_CODE  
 JOIN LOCATION LN (NOLOCK) ON LN.DEPT_ID=PM.DEPT_ID  
 LEFT OUTER JOIN USERS US (NOLOCK) ON PM.USER_CODE=US.USER_CODE  
 LEFT OUTER JOIN USERS EU (NOLOCK) ON PM.EDT_USER_CODE=EU.USER_CODE   
 WHERE  (@DFROMDATE='' OR PM.VOUCHER_DT  BETWEEN @DFROMDATE AND @DTODATE)   
 AND (@CACCODE='' OR PD.AC_CODE =@CACCODE)  
 AND (@CAUNGDIACODE='' OR PM.ANGADIA_CODE=@CAUNGDIACODE)   
 AND (@NCANCELLED=2 OR PM.CANCELLED=@NCANCELLED)   
  AND (@CCITY_CODE='' OR CITY.CITY_code =@CCITY_CODE)  
      
      
 END  
  
END TRY  
BEGIN CATCH  
 SET @CERRMSG='PROCEDURE - SP3S_PARCEL_DETAILS, STEP - '+@CSTEP+', MESSAGE - '+ERROR_MESSAGE()  
END CATCH  
 IF ISNULL(@CERRMSG,'')<>''  
  SELECT @CERRMSG AS ERRORMESSAGE   
END  
--END OF PROCEDURE - SP3S_PARCEL_DETAILS  