CREATE PROCEDURE SP3S_EOSS_UPDATESCHEME_WTDDISC --(LocId 3 digit change by Sanjay:05-11-2024)
@CSCHEMESETROWID VARCHAR(40)='',
@CERRORMSG VARCHAR(1000) OUTPUT,
@CLOCID VARCHAR(4)=''
WITH RECOMPILE
AS
BEGIN
	
	--SELECT 'BEFORE APPLY WEIGHTED',SCHEME_SETUP_DET_ROW_ID,* FROM #TMPCMD WHERE BNGN_QTY<>0
BEGIN TRY
	
	DECLARE  @CSTEP VARCHAR(4),@CPRODUCTCODE VARCHAR(50),@BSISLOC BIT
	
	SET @CSTEP='10'
	SET @CERRORMSG=''
	
	--IF @@SPID=101
	--	SELECT 'CHECK TMPCMD', * FROM #TMPCMD WHERE DISCOUNT_PERCENTAGE>100


	SET @CSTEP='20'
	PRINT 'WTD-1'
	DECLARE @BPROCESSSLRENTRY BIT
	
	SET @BPROCESSSLRENTRY=0
	
	DECLARE @CPICKDISCSLRMODE VARCHAR(4),@CLOCATIONID VARCHAR(4)

	SET @CSTEP='30'

	IF @CLOCID=''
		SELECT @CLOCATIONID=DEPT_ID FROM NEW_APP_LOGIN_INFO (NOLOCK) WHERE SPID=@@SPID 
	ELSE
		SET @CLOCATIONID=@CLOCID

		
	SELECT @BSISLOC=ISNULL(SIS_LOC,0) FROM LOCATION WHERE DEPT_ID=@CLOCATIONID
	
	PRINT 'WTD-2'
LBLSTART:
		
	DECLARE @NGROSSSALE NUMERIC(10,2),@NNETSALE NUMERIC(10,2),@CSLSDETROWID VARCHAR(40),
	@BSLSDISCOUNTDISABLED BIT,@NNETAMOUNT NUMERIC(10,2),@CROWID VARCHAR(40),@NDISCAMT NUMERIC(10,2),
	@NTOTWTDDISC NUMERIC(10,2),@NDISCPCT NUMERIC(7,3),@CPROCESSSLRENTRY CHAR(1)
	
	SET @CSTEP='40'
	PRINT 'WTD-3'
	IF NOT EXISTS (SELECT TOP 1 CMD_ROW_ID FROM #TMPCMD WHERE ISNULL(BNGN_ROW_ID,'')<>'' 
		AND ((@BPROCESSSLRENTRY=0 AND QUANTITY>0) OR (@BPROCESSSLRENTRY=1 AND QUANTITY<0))
		AND (SCHEME_SETUP_DET_ROW_ID=@CSCHEMESETROWID OR @CSCHEMESETROWID=''))
		GOTO END_PROC
	
	

	SET @CSTEP='42'
	SELECT TOP 1 @CROWID=CMD_ROW_ID FROM #TMPCMD WHERE ISNULL(BNGN_ROW_ID,'')<>'' 
	AND ((@BPROCESSSLRENTRY=0 AND QUANTITY>0) OR (@BPROCESSSLRENTRY=1 AND QUANTITY<0))
	AND DISCOUNT_AMOUNT<>0 AND (SCHEME_SETUP_DET_ROW_ID=@CSCHEMESETROWID OR @CSCHEMESETROWID='')
	

	--IF @@SPID=404 AND @CSCHEMESETROWID='BC69BB64-0D73-469B-A241-0014D3E3F2A1' 
	--	SELECT 'CHECK TMPCMD BEFORE BNGN FIX MRP',BNGN_ROW_ID,DISCOUNT_PERCENTAGE,DISCOUNT_AMOUNT, * FROM #TMPCMD

	SET @CSTEP='45'
	UPDATE #TMPCMD SET NET=(CASE WHEN DISCOUNT_AMOUNT=0 THEN CMD_MRP*QUANTITY 
	ELSE (CMD_MRP*QUANTITY)-((CMD_MRP*QUANTITY)-((MRP*QUANTITY)-DISCOUNT_AMOUNT)) END)
	WHERE FIX_MRP_ITEM=1 AND ISNULL(BNGN_ROW_ID,'')<>'' 
	AND ((@BPROCESSSLRENTRY=0 AND QUANTITY>0) OR (@BPROCESSSLRENTRY=1 AND QUANTITY<0))
	AND (SCHEME_SETUP_DET_ROW_ID=@CSCHEMESETROWID OR @CSCHEMESETROWID='')

	UPDATE #TMPCMD SET MRP=CMD_MRP
	WHERE FIX_MRP_ITEM=1 AND ISNULL(BNGN_ROW_ID,'')<>'' 
	AND ((@BPROCESSSLRENTRY=0 AND QUANTITY>0) OR (@BPROCESSSLRENTRY=1 AND QUANTITY<0))
	AND (SCHEME_SETUP_DET_ROW_ID=@CSCHEMESETROWID OR @CSCHEMESETROWID='')

	UPDATE #TMPCMD SET DISCOUNT_AMOUNT=ROUND(CMD_MRP-(NET/QUANTITY),0)
	WHERE FIX_MRP_ITEM=1 AND ISNULL(BNGN_ROW_ID,'')<>'' 
	AND ((@BPROCESSSLRENTRY=0 AND QUANTITY>0) OR (@BPROCESSSLRENTRY=1 AND QUANTITY<0))
	AND (SCHEME_SETUP_DET_ROW_ID=@CSCHEMESETROWID OR @CSCHEMESETROWID='')
	AND DISCOUNT_AMOUNT<>0

	PRINT 'WTD-4'
	SELECT @NDISCAMT=SUM(DISCOUNT_AMOUNT) FROM #TMPCMD WHERE ISNULL(BNGN_ROW_ID,'')<>'' 
	AND ((@BPROCESSSLRENTRY=0 AND QUANTITY>0) OR (@BPROCESSSLRENTRY=1 AND QUANTITY<0))
	AND (SCHEME_SETUP_DET_ROW_ID=@CSCHEMESETROWID OR @CSCHEMESETROWID='')

	UPDATE #TMPCMD SET  DISCOUNT_PERCENTAGE=ROUND((DISCOUNT_AMOUNT/(CMD_MRP*QUANTITY)*100),3)
	WHERE FIX_MRP_ITEM=1 AND ISNULL(BNGN_ROW_ID,'')<>'' 
	AND ((@BPROCESSSLRENTRY=0 AND QUANTITY>0) OR (@BPROCESSSLRENTRY=1 AND QUANTITY<0))
	AND (SCHEME_SETUP_DET_ROW_ID=@CSCHEMESETROWID OR @CSCHEMESETROWID='')
	AND DISCOUNT_AMOUNT<>0

	--IF @@SPID=404 AND @CSCHEMESETROWID='BC69BB64-0D73-469B-A241-0014D3E3F2A1' 
	--	SELECT 'CHECK TMPCMD AFTER BNGN FIX MRP',BNGN_ROW_ID,DISCOUNT_PERCENTAGE,DISCOUNT_AMOUNT,WEIGHTED_AVG_DISC_AMT,
	--	WEIGHTED_AVG_DISC_PCT,* FROM #TMPCMD
	 
	SET @CPROCESSSLRENTRY=(CASE WHEN @BPROCESSSLRENTRY=1 THEN '1' ELSE '0' END)
	
	SET @CSTEP='50'
	PRINT 'WTD-5'
	--IF @@SPID=223
	--	SELECT 'CHECK WEIGHTED_AVG_DISC_AMT-0',BNGN_ROW_ID,MRP,NET,DISCOUNT_AMOUNT,WEIGHTED_AVG_DISC_AMT,* FROM #TMPCMD
			
	PRINT 'FINALLY UPDATE WEIGHTED_AVG_DISC_AMT '+@CPROCESSSLRENTRY
	UPDATE A SET WEIGHTED_AVG_DISC_AMT=(MRP*QUANTITY*((B.GROSS_SALE-B.NET_SALE)/B.GROSS_SALE))
	FROM #TMPCMD A JOIN 
	(SELECT BNGN_ROW_ID,SUM(MRP*QUANTITY) AS GROSS_SALE,SUM((MRP*QUANTITY)-DISCOUNT_AMOUNT) AS NET_SALE
	 FROM #TMPCMD WHERE ((@BPROCESSSLRENTRY=0 AND QUANTITY>0) OR (@BPROCESSSLRENTRY=1 AND QUANTITY<0))
	 AND BNGN_ROW_ID<>'' AND (SCHEME_SETUP_DET_ROW_ID=@CSCHEMESETROWID OR @CSCHEMESETROWID='')
	  GROUP BY BNGN_ROW_ID) B ON A.BNGN_ROW_ID=B.BNGN_ROW_ID
	WHERE ISNULL(A.BNGN_ROW_ID,'')<>'' AND (A.SCHEME_SETUP_DET_ROW_ID=@CSCHEMESETROWID OR @CSCHEMESETROWID='')
	
	--IF @@SPID=223
	--	SELECT 'CHECK WEIGHTED_AVG_DISC_AMT-1',WEIGHTED_AVG_DISC_AMT,* FROM #TMPCMD
	
	SET @CSTEP='60'
	PRINT 'WTD-6'	 	
	SELECT @NTOTWTDDISC=SUM(WEIGHTED_AVG_DISC_AMT) FROM #TMPCMD WHERE ISNULL(BNGN_ROW_ID,'')<>'' AND 
	((@BPROCESSSLRENTRY=0 AND QUANTITY>0) OR (@BPROCESSSLRENTRY=1 AND QUANTITY<0))
	AND (SCHEME_SETUP_DET_ROW_ID=@CSCHEMESETROWID OR @CSCHEMESETROWID='')
	
	IF ABS(@NTOTWTDDISC-@NDISCAMT)>0
	BEGIN
		PRINT 'DIF FOUND'
		UPDATE #TMPCMD SET WEIGHTED_AVG_DISC_AMT=WEIGHTED_AVG_DISC_AMT+(@NDISCAMT-@NTOTWTDDISC)
		WHERE CMD_ROW_ID=@CROWID
	END	

	--IF @@SPID=223
	--	SELECT 'CHECK WEIGHTED_AVG_DISC_AMT-2',WEIGHTED_AVG_DISC_AMT,* FROM #TMPCMD
			
	--IF @@SPID=223	
	--	SELECT 'BEFORE DISTRIBUTING',* FROM #TMPCMD
	
	SET @CSTEP='70'
	PRINT 'BEFORE DISTRIBUTING'
	
	--SELECT 'BEFORE DISTRIBUTING',* FROM #TMPCMD
	
	UPDATE A SET APPLY_EXCLUSIVE_TAX=0 FROM #TMPCMD A 
	JOIN SCHEME_SETUP_DET B ON A.SCHEME_SETUP_DET_ROW_ID=B.ROW_ID
	WHERE ISNULL(BNGN_ROW_ID,'')<>'' AND ((@BPROCESSSLRENTRY=0 AND QUANTITY>0) OR (@BPROCESSSLRENTRY=1 AND QUANTITY<0))
	AND B.APPLY_EXCLUSIVE_TAX=1 AND ROUND((WEIGHTED_AVG_DISC_AMT/(MRP*QUANTITY))*100,2)<B.EXCLUSIVE_VAT_TO_DISC
	AND (SCHEME_SETUP_DET_ROW_ID=@CSCHEMESETROWID OR @CSCHEMESETROWID='')
		
	UPDATE A SET WEIGHTED_AVG_DISC_PCT=ROUND((A.WEIGHTED_AVG_DISC_AMT/(MRP*QUANTITY))*100,3)
	FROM #TMPCMD A JOIN SCHEME_SETUP_DET B ON A.SCHEME_SETUP_DET_ROW_ID=B.ROW_ID
	WHERE ISNULL(BNGN_ROW_ID,'')<>'' AND ((@BPROCESSSLRENTRY=0 AND QUANTITY>0) OR (@BPROCESSSLRENTRY=1 AND QUANTITY<0))
	AND (SCHEME_SETUP_DET_ROW_ID=@CSCHEMESETROWID OR @CSCHEMESETROWID='')

	----NEED TO RECALCULATE THIS AGAIN BECAUSE OF DISCOUNT AMOUNT VALIDATION BEING FAILED 
	---- ON FINAL SAVE (CANTABIL TICKET#11-0051 DATED: 01-112022 BILL#3A2223-01806)
	UPDATE  #TMPCMD SET WEIGHTED_AVG_DISC_AMT=ROUND(MRP*QUANTITY*WEIGHTED_AVG_DISC_PCT/100,2)

	SET @CSTEP='80'
	--IF @@SPID=223
	--	SELECT 'CHECK WEIGHTED_AVG_DISC_AMT-3',WEIGHTED_AVG_DISC_AMT,* FROM #TMPCMD
			
	PRINT 'NOW UPDATE DISCOUNT BASED UPON WEIGHTED AVG'
	--COMMENTED THIS CODE ON 09-07-2019 AS PER PROBLEM COMING AT DONEAR
	-- IN THE SCHEME OF BUY 2 GET 3 
	---,WEIGHTED_AVG_DISC_AMT=A.DISCOUNT_AMOUNT

	UPDATE A SET SCHEME_DISCOUNT=A.DISCOUNT_AMOUNT
	FROM #TMPCMD A 
	JOIN SCHEME_SETUP_DET B ON A.SCHEME_SETUP_DET_ROW_ID=B.ROW_ID

	UPDATE A SET DISCOUNT_AMOUNT=WEIGHTED_AVG_DISC_AMT ,scheme_applied_amount=scheme_applied_amount+WEIGHTED_AVG_DISC_AMT
	FROM #TMPCMD A 
	JOIN SCHEME_SETUP_DET B ON A.SCHEME_SETUP_DET_ROW_ID=B.ROW_ID
	WHERE ISNULL(BNGN_ROW_ID,'')<>'' AND ((@BPROCESSSLRENTRY=0 AND QUANTITY>0) OR 
	(@BPROCESSSLRENTRY=1 AND QUANTITY<0))
	AND (SCHEME_SETUP_DET_ROW_ID=@CSCHEMESETROWID OR @CSCHEMESETROWID='')		
	AND ISNULL(DONOT_DISTRIBUTE_WEIGHTED_AVG_DISC,0)=0

	--- CHANGED THIS CONDITION TO ABOVE ONE AFTER PROBLEM REPORTED BY JAYSHOES (TICKET#11-1901) (DATE:23-11-2022)
	--- THEY WERE WANTING SCHEME NOT TO BE DISTRIBUTED IN CASE OF SALE IMPORT FROM SIS LOCATION
	--AND (ISNULL(DONOT_DISTRIBUTE_WEIGHTED_AVG_DISC,0)=0 OR @BSISLOC=1)
	
	--IF @@SPID=223
	--	SELECT 'CHECK WEIGHTED_AVG_DISC_AMT-4',WEIGHTED_AVG_DISC_AMT,* FROM #TMPCMD
	
	SET @CSTEP='90'		
	UPDATE A SET DISCOUNT_PERCENTAGE=ROUND((A.DISCOUNT_AMOUNT/(MRP*QUANTITY))*100,3),
	NET=(A.MRP*A.QUANTITY)-A.DISCOUNT_AMOUNT
	FROM #TMPCMD A JOIN SCHEME_SETUP_DET B ON A.SCHEME_SETUP_DET_ROW_ID=B.ROW_ID
	WHERE ISNULL(BNGN_ROW_ID,'')<>'' AND ((@BPROCESSSLRENTRY=0 AND QUANTITY>0) OR (@BPROCESSSLRENTRY=1 AND QUANTITY<0))
	AND (SCHEME_SETUP_DET_ROW_ID=@CSCHEMESETROWID OR @CSCHEMESETROWID='')


	IF EXISTS (SELECT TOP 1 * FROM #TMPCMD WHERE ROUND(DISCOUNT_PERCENTAGE,0)>100)
	BEGIN
		SELECT TOP 1 @CPRODUCTCODE=PRODUCT_CODE FROM #TMPCMD WHERE DISCOUNT_PERCENTAGE>100
		SET @CERRORMSG='ITEM CODE :'+@CPRODUCTCODE+' IS HAVING SCHEME : DISCOUNT MORE THAN 100%....CANNOT SAVE'
		GOTO EXIT_PROC
		--('+SLS_TITLE+')
	END

END_PROC:	
	IF @BPROCESSSLRENTRY=0
	BEGIN
		SET @BPROCESSSLRENTRY=1
		GOTO LBLSTART
	END

END TRY

BEGIN CATCH
	SET @CERRORMSG='ERROR IN PROCEDURE SP3S_EOSS_UPDATESCHEME_WTDDISC AT STEP#'+@CSTEP+' '+ERROR_MESSAGE()
	GOTO EXIT_PROC
END CATCH

EXIT_PROC:
			
	
END
---- 'END OF CREATING PROCEDURE SP3S_EOSS_UPDATESCHEME_WTDDISC'
