CREATE PROCEDURE SAVETRAN_APPROVE_MANUALBILL
@CCMID VARCHAR(40),
@NSPID VARCHAR(50)
AS
BEGIN
	
BEGIN TRY	
	
	DECLARE @CCMD NVARCHAR(MAX),@CTEMPTABLE VARCHAR(500),@CSTEP VARCHAR(5),@CERRMSG VARCHAR(MAX)
	
	BEGIN TRAN
	
	SET @CSTEP=10
	SET @CTEMPTABLE='SLS_cmd_manualbill_errors_UPLOAD'
	
	
	
	
	
	SET @CCMD=N'UPDATE A SET APPROVED=B.APPROVED,USER_CODE=B.USER_CODE,REMARKS=B.REMARKS,APPROVED_ON=GETDATE() 
				FROM CMD_MANUALBILL_ERRORS A 
				JOIN '+@CTEMPTABLE+' B ON A.CMD_ROW_ID=B.CMD_ROW_ID
			    WHERE A.APPROVED=0 AND SP_ID ='''+@NSPID+''' '
	PRINT @CCMD
	EXEC SP_EXECUTESQL @CCMD
	
	
	SET @CCMD=N'UPDATE C SET C.MANUAL_BILL=0 
				FROM CMD01106 A 
				JOIN '+@CTEMPTABLE+' B ON A.ROW_ID=B.CMD_ROW_ID
				JOIN CMM01106 C ON A.CM_ID= C.CM_ID 
				WHERE  SP_ID ='''+@NSPID+''' '
			    
	PRINT @CCMD
	EXEC SP_EXECUTESQL @CCMD
		
	SET @CSTEP=20
	SET @CCMD=N'DELETE FROM MIRRORLOG WHERE XN_ID='''+@CCMID+''' AND XN_TYPE=''DOCMBAPP'''
	EXEC SP_EXECUTESQL @CCMD
	
	GOTO END_PROC
END TRY

BEGIN CATCH
	SET @CERRMSG='P:SAVETRAN_APPROVE_MANUALBILL, STEP:'+@CSTEP+', MESSAGE:'+ERROR_MESSAGE()
	GOTO END_PROC
END CATCH

END_PROC:
	IF @@TRANCOUNT>0
	BEGIN
		IF ISNULL(@CERRMSG,'')=''
			COMMIT
		ELSE
			ROLLBACK	
	END	
	

	DELETE A FROM SLS_cmd_manualbill_errors_UPLOAD A (NOLOCK) WHERE SP_ID=@NSPID 
	
	SELECT @CCMID AS MEMO_ID,ISNULL(@CERRMSG,'') AS ERRMSG					
END
---- END OF PROCEDURE SAVETRAN_APPROVE_MANUALBILL
