CREATE PROCEDURE SP_MERGE_MIRROR_DOCASN_DATA        
(        
	 @CMEMOID VARCHAR(50),        
	 @CLOCID VARCHAR(2),        
	 @CERRMSG VARCHAR(MAX) OUTPUT        
)        
AS        
BEGIN 
 
 SET NOCOUNT ON        
 
 DECLARE @DTSQL NVARCHAR(MAX),@CSOURCEDB VARCHAR(200),@CTMP_TABLENAME VARCHAR(200),        
   @CJOINSTR VARCHAR(MAX),@CERRORMSG VARCHAR(MAX),@CTABLESUFFIX VARCHAR(100),        
   @CTABLENAME VARCHAR(200),@CERRMSGOUT VARCHAR(MAX),@CSTEP VARCHAR(20),@CKEYFIELD VARCHAR(100)        
   ,@CKEYFIELD1 VARCHAR(100),@CMERGEDB VARCHAR(50)
   ,@INV_MODE INT,@CFINYEAR VARCHAR(10),@MRR_NO VARCHAR(50),@INV_ID VARCHAR(50)      
   ,@TEMP_TABLE1 VARCHAR(20),@CCMD NVARCHAR(MAX), @CCURDEPTID CHAR(2),@CHODEPTID CHAR(2),
   @BSOURCEPURLOC BIT,@BTARGETPURLOC BIT,@BGENERATEAUTOSERIES BIT,@CSOURCELOCID CHAR(2), @BHOLOC BIT,@BSKU_OH BIT,
   @NTARGETLOCTYPE INT,@BMSTINSERTONLY BIT,@CMEMONOPREFIX VARCHAR(100),@CPARTYDEPTID VARCHAR(5),
   @BCHALLANRECEIVEDPREV BIT,@CTABLESSTR VARCHAR(MAX),@BGETCHALLANTHRUMIRROR BIT,@CSOURCETEMPTABLE VARCHAR(500),
   @CTMPINDTABLE VARCHAR(500),@NVERSIONNO INT,@NINVMODE INT,@CFILTERCONDITION VARCHAR(MAX),@CCMDOUTPUT VARCHAR(MAX),@CFILTERCONDITION1 VARCHAR(MAX),
   @BSENDPURINFOLOC BIT
  
 
 BEGIN TRY        
  
  SET @CSTEP=2
    	 
  SELECT @CCURDEPTID = VALUE FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION='LOCATION_ID'
  SELECT @CHODEPTID = VALUE FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION='HO_LOCATION_ID'
  
  SET @CSTEP=5	
  SET @CSOURCEDB=DB_NAME()+'.DBO.'
          
  SET @CTABLESUFFIX=REPLACE(@CMEMOID,'-','_') 
  SET @CFILTERCONDITION=''
  SET @CTMP_TABLENAME=@CSOURCEDB+'DOCASN_ASN_MST_MIRROR'
  
  SELECT TOP 1 @NVERSIONNO=MAX(VERSION_NO) FROM DOCPO_POM01106_MIRROR WHERE PO_ID=@CMEMOID
    
  SELECT @CFILTERCONDITION=' A.MEMO_ID='''+@CMEMOID+''' AND A.VERSION_NO='+LTRIM(RTRIM(STR(@NVERSIONNO))) 	
		 
     
  SET @CCMD=N'SELECT @CPARTYDEPTID=
  B.DEPT_ID FROM '+@CTMP_TABLENAME+' A JOIN POM01106 B ON A.PO_ID=B.PO_ID WHERE '+@CFILTERCONDITION
  
  PRINT @CCMD
  EXEC SP_EXECUTESQL @CCMD,N'@CPARTYDEPTID VARCHAR(5) OUTPUT',@CPARTYDEPTID OUTPUT
  
    
  IF ISNULL(@CMEMOID,'')=''
	GOTO EXIT_PROC     
  
  IF @CPARTYDEPTID<>@CCURDEPTID
  BEGIN
	SET @CERRMSG = 'THE CHALLAN NO.:'+RIGHT(@CMEMOID,10)+' BELONGS TO LOCATION ID :'+@CPARTYDEPTID+' OTHER THAN CURRENT LOCATION ID:'+@CCURDEPTID		
	GOTO EXIT_PROC
  END
  
  SELECT TOP 1 @CSOURCELOCID=DEPT_ID,@BSOURCEPURLOC=PUR_LOC FROM LOCATION (NOLOCK) WHERE DEPT_ID=LEFT(@CMEMOID,2)	
  SELECT TOP 1 @BTARGETPURLOC=PUR_LOC,@NTARGETLOCTYPE=LOC_TYPE,@BSENDPURINFOLOC=UPD_PURINFO
  FROM LOCATION (NOLOCK) WHERE DEPT_ID=@CCURDEPTID
  
  SET @BHOLOC=0
  IF @CCURDEPTID=@CHODEPTID
	  SET @BHOLOC=1
  
  SET @CSTEP = 10        
  SET @CMERGEDB=DB_NAME()+'.DBO.'      
  SET @CERRORMSG=''        
 
  IF @BHOLOC=1
	SET @BMSTINSERTONLY = 1
  ELSE
	SET @BMSTINSERTONLY = 0
	
  IF @BHOLOC=0
	BEGIN TRANSACTION        
	

 UPDATE DOCASN_ASN_MST_MIRROR SET USER_CODE='0000000'
    
  SELECT @CFILTERCONDITION=' A.MEMO_ID='''+@CMEMOID+''' AND A.VERSION_NO='+LTRIM(RTRIM(STR(@NVERSIONNO))) 
  	
       SET @CSTEP=360
	SET @CTABLENAME='ASN_MST'
	SET @CTMP_TABLENAME='DOCASN_'+@CTABLENAME+'_MIRROR'
	SET @CKEYFIELD='MEMO_ID'
	SET @CSTEP=110
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=0,@CFILTERCONDITION='',@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1 
							 
   DELETE FROM POD01106 WHERE PO_ID=@CMEMOID							  
							  
	
	SET @CSTEP=370
	SET @CTABLENAME='ASN_DET'
	SET @CTMP_TABLENAME='DOCASN_'+@CTABLENAME+'_MIRROR'
	SET @CKEYFIELD='ROW_ID'
	SET @CSTEP=110
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=1,@CFILTERCONDITION='',@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1 
							  
					
	
	
	 
    					
 END TRY        
 BEGIN CATCH
  PRINT 'CATCH START'       
  SET @CERRMSG='P:SP_MERGE_MIRROR_DOCASN_DATA, STEP:'+LTRIM(RTRIM(STR(@CSTEP)))+', MESSAGE:'+ERROR_MESSAGE()        
  GOTO EXIT_PROC
 END CATCH        
        
EXIT_PROC:   
 
     
 IF ISNULL(@CERRMSG,'')='' AND @@TRANCOUNT>0        
 BEGIN 
	 IF @BHOLOC=0       
	 BEGIN
		COMMIT TRANSACTION
	END	
		
 END        
 ELSE IF ISNULL(@CERRMSG,'')<>'' AND @@TRANCOUNT>0 
 BEGIN 
	 IF @BHOLOC=0
		ROLLBACK        
 END
   
   
		DELETE A FROM DOCASN_ASN_MST_MIRROR A WITH (ROWLOCK) WHERE A.MEMO_ID =@CMEMOID AND A.VERSION_NO<=@NVERSIONNO
		DELETE A FROM DOCASN_ASN_DET_MIRROR A	WITH (ROWLOCK) WHERE A.MEMO_ID  =@CMEMOID AND A.VERSION_NO<=@NVERSIONNO
		

END 
------ END OF CREATING PROCEDURE - SP_MERGE_MIRROR_DOCASN_DATA
