CREATE PROCEDURE SP_WSLINV_11--(LocId 3 digit change only increased the parameter width by Sanjay:04-11-2024)
	@CMEMOID	VARCHAR(40) = '',
	@CWHERE1	VARCHAR(500) = '',
	@NNAVMODE	NUMERIC(1,0) = 0,
	@CWHERE2	NVARCHAR(MAX)='',
	@DMEMODT DATETIME='',
	@CLOCID		VARCHAR(4)=''
----WITH ENCRYPTION
AS
BEGIN
	
	DECLARE @CSENDPARA6 VARCHAR(10)
	SELECT @CSENDPARA6 = VALUE FROM CONFIG WHERE CONFIG_OPTION = 'SENT_SUPPLIER_NAME_PARA6'
	SELECT @CSENDPARA6=ISNULL(@CSENDPARA6,'')

	DECLARE @cpara1Name varchar(10),@cpara2Name varchar(10),@cpara3Name varchar(10),@cpara4Name varchar(10),@cpara5Name varchar(10),@cpara6Name varchar(10),
	        @DTSQL NVARCHAR(MAX),@CPARANAME VARCHAR(5000)

	SELECT @cpara1Name=CASE WHEN ISNULL(VALUE,'')='' THEN 'PARA1_NAME' ELSE VALUE END  FROM CONFIG WHERE CONFIG_OPTION ='PARA1_CAPTION'
	SELECT @cpara2Name=CASE WHEN ISNULL(VALUE,'')='' THEN 'PARA2_NAME' ELSE VALUE END  FROM CONFIG WHERE CONFIG_OPTION ='PARA2_CAPTION'
	SELECT @cpara3Name=CASE WHEN ISNULL(VALUE,'')='' THEN 'PARA3_NAME' ELSE VALUE END  FROM CONFIG WHERE CONFIG_OPTION ='PARA3_CAPTION'
	SELECT @cpara4Name=CASE WHEN ISNULL(VALUE,'')='' THEN 'PARA4_NAME' ELSE VALUE END  FROM CONFIG WHERE CONFIG_OPTION ='PARA4_CAPTION'
	SELECT @cpara5Name=CASE WHEN ISNULL(VALUE,'')='' THEN 'PARA5_NAME' ELSE VALUE END  FROM CONFIG WHERE CONFIG_OPTION ='PARA5_CAPTION'
	SELECT @cpara6Name=CASE WHEN ISNULL(VALUE,'')='' THEN 'PARA6_NAME' ELSE VALUE END  FROM CONFIG WHERE CONFIG_OPTION ='PARA6_CAPTION'


	SET @CPARANAME='SN.PARA1_NAME AS '+QUOTENAME(@cpara1Name)+','
	SET @CPARANAME=@CPARANAME+' SN.PARA2_NAME AS '+QUOTENAME(@cpara2Name)+','
	SET @CPARANAME=@CPARANAME+' SN.PARA3_NAME AS '+QUOTENAME(@cpara3Name)+','
	SET @CPARANAME=@CPARANAME+' SN.PARA4_NAME AS '+QUOTENAME(@cpara4Name)+','
	SET @CPARANAME=@CPARANAME+' SN.PARA5_NAME AS '+QUOTENAME(@cpara5Name)+','
	SET @CPARANAME=@CPARANAME+'(CASE WHEN '''+@CSENDPARA6+'''= ''1'' THEN L.AC_NAME ELSE SN.PARA6_NAME END) AS  '+QUOTENAME(@cpara6Name)+''

	declare @CATTRNAME VARCHAR(MAX)
	select  @CATTRNAME =isnull(@CATTRNAME+',','')+'SN.'+column_name +' AS '+QUOTENAME (case when isnull(table_caption,'')<>'' 
	        then table_caption else  column_name end)
	from config_attr 

	

	--IF OBJECT_ID ('TEMPWSLEXPORT','U' ) IS NOT NULL
	--   drop table TEMPWSLEXPORT
	
	SET @DTSQL=N'SELECT  LEFT( S1.PRODUCT_CODE, ISNULL(NULLIF(CHARINDEX (''@'', S1.PRODUCT_CODE)-1,-1),LEN( S1.PRODUCT_CODE ))) PRODUCT_CODE,
	T1.RATE AS PURCHASE_PRICE,SN.ARTICLE_NO,SN.ARTICLE_NAME
	,S1.BARCODE_CODING_SCHEME AS CODING_SCHEME,SN.SECTION_NAME,SN.SUB_SECTION_NAME,SN.SECTION_NAME,
	'+@CPARANAME+'
    ,SN.sn_article_desc as ARTICLE_DESC,B.INV_NO,B.INV_DT,FR.FORM_NAME,
	sn. uom as  UOM_NAME,U.GST_UOM_NAME, SP.SIZEINCHES,SP.SIZECMS,    T1.QUANTITY,S1.MRP,T1.RATE AS 
	WS_PRICE,T1.DISCOUNT_PERCENTAGE,T1.DISCOUNT_AMOUNT,T1.NET_RATE,
	sn.article_alias AS ARTICLE_ALIAS,S1.ONLINE_PRODUCT_CODE,S1.VENDOR_EAN_NO	,
	T1.HSN_CODE,(CASE WHEN CHARINDEX(''@'',S1.PRODUCT_CODE)>1 THEN LEFT(S1.PRODUCT_CODE,CHARINDEX(''@'',S1.PRODUCT_CODE)-1) ELSE S1.PRODUCT_CODE END) AS PRODUCT_CODE1 ,
	
	'+@CATTRNAME+'
	,S1.FIX_MRP,
	b.manual_inv_no as Ref_no,T1.GST_PERCENTAGE,
	(T1.IGST_AMOUNT+T1.CGST_AMOUNT+T1.SGST_AMOUNT) AS GST_AMOUNT,
	T1.XN_VALUE_WITHOUT_GST AS TAXABLE_VALUE,B.Remarks,L.AC_NAME,
	cast(T1.NET_RATE*quantity as numeric(14,2)) as Amount,
	(T1.discount_amount+T1.INMDISCOUNTAMOUNT) as TOTAL_DISCOUNT,
	T1.inmdiscountamount
	--into TEMPWSLEXPORT
	FROM IND01106 T1 (NOLOCK)
	JOIN INM01106 B (NOLOCK)  ON B.INV_ID=T1.INV_ID	
	JOIN SKU S1 (NOLOCK) ON S1.PRODUCT_CODE=T1.PRODUCT_CODE   
	JOIN SKU_NAMES SN (NOLOCK) ON SN.PRODUCT_CODE =S1.PRODUCT_CODE 
	left outer  JOIN  ARTICLE ART ON S1.ARTICLE_CODE= ART.ARTICLE_CODE
	LEFT OUTER JOIN SECTIOND SD ON ART.SUB_SECTION_CODE= SD.SUB_SECTION_CODE
	LEFT OUTER JOIN  SECTIONDPARA2 SP ON SD.SUB_SECTION_CODE= SP.SUB_SECTION_CODE  AND ISNULL( S1.PARA2_CODE,'''')= ISNULL(SP.PARA2_CODE,'''')
	LEFT OUTER JOIN UOM U ON ART.UOM_CODE= U.UOM_CODE
	LEFT JOIN FORM FR (NOLOCK)ON T1.ITEM_FORM_ID= FR.FORM_ID 
	left outer JOIN LM01106 L (NOLOCK) ON L.AC_CODE = B.AC_CODE 
	WHERE T1.INV_ID = '''+ @CMEMOID+''' '
	PRINT @DTSQL
	EXEC SP_EXECUTESQL @DTSQL

	--SELECT * FROM TEMPWSLEXPORT




END

