CREATE PROCEDURE SP_VALIDATE_MEMODATE--(LocId 3 digit change by Sanjay:06-11-2024)
@CXNTYPE VARCHAR(10),
@CXNID VARCHAR(40),
@DOLDMEMODATE DATETIME='',
@CERRORMSG VARCHAR(MAX) OUTPUT
--WITH ENCRYPTION
AS
BEGIN
	DECLARE @CMASTERTABLENAME VARCHAR(200),@CMAXMEMONO VARCHAR(50),@DMAXMEMODATE DATETIME,@CMINMEMONO VARCHAR(50),@DMINMEMODATE DATETIME,@CCURMEMONO VARCHAR(50)
				   ,@CCMD NVARCHAR(MAX),@CKEYFIELDCOL VARCHAR(100),@CKEYFIELDCOL2 VARCHAR(100),@CKEYDATECOL VARCHAR(50)
				   ,@DMEMODT DATETIME,@NMEMOPREFIXLEN INT,@CMINCMNO VARCHAR(15),@CMAXCMNO VARCHAR(15),
					 @CFINYEAR VARCHAR(10),@NCURRENTCMNO NUMERIC(5,0),@NMAXCMNO NUMERIC(5,0),@NCURCMNO NUMERIC(5,0),
					 @NMINCMNO INT,@CDEPTID VARCHAR(4),@CWHERECLAUSE VARCHAR(MAX),@CMEMOPREFIX VARCHAR(10),@cMemoNo varchar(50)
					 
	 SET @CWHERECLAUSE=''					 
	 
	 IF @CXNTYPE<>'SLS'
		GOTO END_PROC
		
	IF @CXNTYPE='PUR'
	BEGIN
		SELECT  @CMASTERTABLENAME='PIM01106'
			   ,@CKEYFIELDCOL='MRR_ID'
			   ,@CKEYDATECOL='RECEIPT_DT'
			   ,@CKEYFIELDCOL2='MRR_NO'
	END
	ELSE IF @CXNTYPE='WSL'
	BEGIN
		SELECT  @CMASTERTABLENAME='INM01106'
			   ,@CKEYFIELDCOL='INV_ID'
			   ,@CKEYDATECOL='INV_DT'
			   ,@CKEYFIELDCOL2='INV_NO'
	END
	ELSE IF @CXNTYPE='SLS'
	BEGIN
		SELECT  @CMASTERTABLENAME='CMM01106'
			   ,@CKEYFIELDCOL='CM_ID'
			   ,@CKEYDATECOL='CM_DT'
			   ,@CKEYFIELDCOL2='CM_NO'
	END
	ELSE IF @CXNTYPE='PRT'
	BEGIN
		SELECT  @CMASTERTABLENAME='RMM01106'
			   ,@CKEYFIELDCOL='RM_ID'
			   ,@CKEYDATECOL='RM_DT'
			   ,@CKEYFIELDCOL2='RM_NO'
	END
	ELSE IF @CXNTYPE='WSR'
	BEGIN
		SELECT  @CMASTERTABLENAME='CNM01106'
			   ,@CKEYFIELDCOL='CN_ID'
			   ,@CKEYDATECOL='CN_DT'
			   ,@CKEYFIELDCOL2='CN_NO'
	
	END
	ELSE IF @CXNTYPE='PO'
	BEGIN
		SELECT  @CMASTERTABLENAME='POM01106'
			   ,@CKEYFIELDCOL='PO_ID'
			   ,@CKEYDATECOL='PO_DT'
			   ,@CKEYFIELDCOL2='PO_NO'
	END
		---GET THE MEMO PREFIX LENGTH 
		IF @CXNTYPE NOT IN ('SLS')
		BEGIN
			SET @CCMD=N'SELECT @NMEMOPREFIXLEN=LEN(LTRIM(RTRIM(DBO.FN_GETMEMOPREFIX('+@CKEYFIELDCOL+',MEMO_PREFIX)))),
						@CMEMOPREFIX=DBO.FN_GETMEMOPREFIX('+@CKEYFIELDCOL+',MEMO_PREFIX) 
						FROM '+@CMASTERTABLENAME+' WHERE '+@CKEYFIELDCOL+'='''+@CXNID+''''
						
			EXEC SP_EXECUTESQL @CCMD,N'@NMEMOPREFIXLEN INT OUTPUT,@CMEMOPREFIX VARCHAR(10) OUTPUT',
			@NMEMOPREFIXLEN OUTPUT,@CMEMOPREFIX OUTPUT			
		END 
		ELSE IF @CXNTYPE='SLS'
		BEGIN
			select @cMemoNo=ltrim(rtrim(cm_no)) from cmm01106 (NOLOCK) WHERE cm_id=@cXnId
			SELECT @NMEMOPREFIXLEN=(CASE WHEN SUBSTRING(@cMemoNo,5,1) IN ('N','E','R') THEN 6 ELSE 5 END)
			SET @CCMD=N'SELECT @CMEMOPREFIX=LEFT(CM_NO,'+LTRIM(RTRIM(STR(@NMEMOPREFIXLEN)))+')
						FROM '+@CMASTERTABLENAME+' WHERE '+@CKEYFIELDCOL+'='''+@CXNID+''''
			EXEC SP_EXECUTESQL @CCMD,N'@CMEMOPREFIX VARCHAR(10) OUTPUT',@CMEMOPREFIX OUTPUT			
		END	
		
		--GET THE FINYEAR FOR THE MEMO_ID
		SET @CCMD=N'SELECT @CFINYEAR=FIN_YEAR,@CCURMEMONO=LTRIM(RTRIM('+@CKEYFIELDCOL2+')),@DMEMODT='+@CKEYDATECOL+' FROM '+@CMASTERTABLENAME+' WHERE '+@CKEYFIELDCOL+'='''+@CXNID+''''
		PRINT @CCMD
		EXEC SP_EXECUTESQL @CCMD,N'@CFINYEAR VARCHAR(10) OUTPUT,@CCURMEMONO VARCHAR(50) OUTPUT,@DMEMODT DATETIME OUTPUT',@CFINYEAR OUTPUT,@CCURMEMONO OUTPUT,@DMEMODT OUTPUT
		
		DECLARE @cCurMemoExpr varchar(200),@cKeyfieldCol2Expr VARCHAR(200)
		SELECT @cKeyfieldCol2Expr = (CASE WHEN @cXntype='SLS' THEN 'convert(numeric(7,0),substring('+@CKEYFIELDCOL2+','+str(@NMEMOPREFIXLEN+1)+',len('+@CKEYFIELDCOL2+')))'
									   ELSE @CKEYFIELDCOL2 END),
			   @cCurMemoExpr = (CASE WHEN @cXntype='SLS' THEN 'convert(numeric(7,0),substring('''+@CCURMEMONO+''','+str(@NMEMOPREFIXLEN+1)+',len('+@CKEYFIELDCOL2+')))'
									   ELSE @CCURMEMONO END)
		--GET THE MAX MEMO_NO BELOW THE PASSED MEMO_ID
		SET @CCMD=N'SELECT @CMAXMEMONO=LTRIM(RTRIM(MAX('+@CKEYFIELDCOL2+'))) 
					FROM '+@CMASTERTABLENAME+' WHERE CANCELLED=0 AND  FIN_YEAR='''+@CFINYEAR+'''
					AND LEFT('+@CKEYFIELDCOL2+','+CONVERT(VARCHAR(4),@NMEMOPREFIXLEN)+')=LEFT('''+@CCURMEMONO+''','+CONVERT(VARCHAR,@NMEMOPREFIXLEN)+')
					AND '+@cKeyfieldCol2Expr+'<'+@cCurMemoExpr+''+
					(CASE WHEN @CXNTYPE<>'SLS' THEN  ' AND DBO.FN_GETMEMOPREFIX('+@CKEYFIELDCOL+',MEMO_PREFIX)='''+@CMEMOPREFIX+'''' ELSE '' END)
		PRINT @CCMD	
		EXEC SP_EXECUTESQL @CCMD,N'@CMAXMEMONO VARCHAR(50) OUTPUT',@CMAXMEMONO OUTPUT
		
		IF ISNULL(@CMAXMEMONO,'')<>''
		BEGIN
			SET @CCMD=N'SELECT @DMAXMEMODATE='+@CKEYDATECOL+' FROM '+@CMASTERTABLENAME+' 
			WHERE '+@CKEYFIELDCOL2+'='''+@CMAXMEMONO+''' AND FIN_YEAR='''+@CFINYEAR+''' AND cancelled=0'
			PRINT @CCMD
			EXEC SP_EXECUTESQL @CCMD,N'@DMAXMEMODATE DATETIME OUTPUT',@DMAXMEMODATE OUTPUT
			
			IF @DMEMODT<@DMAXMEMODATE
			SET @CERRORMSG='CURRENT MEMO DATE CANNOT BE LESS THAN - '+CONVERT(VARCHAR,@DMAXMEMODATE,105)
		END
		
		--GET THE MIN MEMO_NO ABOVE THE PASSED MEMO_ID
		SET @CCMD=N'SELECT @CMINMEMONO=LTRIM(RTRIM(MIN('+@CKEYFIELDCOL2+'))) 
					FROM '+@CMASTERTABLENAME+' WHERE CANCELLED=0 AND  FIN_YEAR='''+@CFINYEAR+'''
					AND cancelled=0 AND LEFT('+@CKEYFIELDCOL2+','+CONVERT(VARCHAR(4),@NMEMOPREFIXLEN)+')=LEFT('''+@CCURMEMONO+''','+CONVERT(VARCHAR,@NMEMOPREFIXLEN)+')
					AND '+@cKeyfieldCol2Expr+'>'+@CCURMEMOExpr+''+
					(CASE WHEN @CXNTYPE<>'SLS' THEN  ' AND DBO.FN_GETMEMOPREFIX('+@CKEYFIELDCOL+',MEMO_PREFIX)='''+@CMEMOPREFIX+'''' ELSE '' END)
		PRINT @CCMD	
		EXEC SP_EXECUTESQL @CCMD,N'@CMINMEMONO VARCHAR(50) OUTPUT',@CMINMEMONO OUTPUT
		
		IF ISNULL(@CMINMEMONO,'')<>''
		BEGIN
			SET @CCMD=N'SELECT @DMINMEMODATE='+@CKEYDATECOL+' FROM '+@CMASTERTABLENAME+' 
			WHERE '+@CKEYFIELDCOL2+'='''+@CMINMEMONO+''' AND FIN_YEAR='''+@CFINYEAR+''''
			PRINT @CCMD
			EXEC SP_EXECUTESQL @CCMD,N'@DMINMEMODATE DATETIME OUTPUT',@DMINMEMODATE OUTPUT
			
			IF @DMEMODT>@DMINMEMODATE
			SET @CERRORMSG='CURRENT MEMO DATE CANNOT BE GREATER THAN - '+CONVERT(VARCHAR,@DMINMEMODATE,105)
			
		END
	
END_PROC:
END

-----END OF PROCEDURE SP_VALIDATE_MEMODATE
