CREATE PROCEDURE SP_DAYBOOK
(
 @CDEPTID CHAR(4),	
 @DFROMDT DATETIME,
 @DTODT DATETIME,
 @CUSERCODE	VARCHAR(15)=''
)
--WITH ENCRYPTION
AS
BEGIN
--(dinkar) Replace  left(memoid,2) to Location_code 

DECLARE @DCLOSINGDT DATETIME
DECLARE @TOPBAL TABLE (OP_BAL NUMERIC(18,2))

DECLARE @TCASHXN TABLE ( XN_DT DATETIME, XN_NO VARCHAR(40), XN_ID VARCHAR(40),
						 XN_TYPE VARCHAR(10), DR_AMOUNT NUMERIC(18,2), CR_AMOUNT NUMERIC(18,2),
						 AC_NAME VARCHAR(500), NARRATION VARCHAR(MAX),
						 OP_BAL NUMERIC(18,2), CL_BAL NUMERIC(18,2) )

DECLARE @TDAYBOOK TABLE (AC_NAME VARCHAR(500),NARRATION VARCHAR(MAX),XN_NO VARCHAR(40),XN_DT DATETIME,
						 OP NUMERIC(18,2),DR_AMOUNT NUMERIC(18,2),CR_AMOUNT NUMERIC(18,2),
						 XN_TYPE VARCHAR(5),S_NO INT,DONOT_CALC INT)

DECLARE @TCLBAL TABLE (CL_BAL NUMERIC(18,2))

PRINT 'DAYBOOK-1'
SET @DCLOSINGDT=@DFROMDT-1

PRINT 'DAYBOOK-2'
INSERT @TOPBAL
EXEC SP_CASHXN @CDEPTID,'',@DCLOSINGDT,0,0,0,@CUSERCODE

PRINT 'DAYBOOK-3'
INSERT @TCLBAL
EXEC SP_CASHXN @CDEPTID,'',@DTODT,0,0,0,@CUSERCODE

PRINT 'DAYBOOK-4'
INSERT @TCASHXN
EXEC SP_CASHXN @CDEPTID,@DFROMDT,@DTODT,0,1,0,@CUSERCODE

PRINT 'DAYBOOK-5'
INSERT @TDAYBOOK
SELECT 'OPENING BALANCE' AS AC_NAME,'' AS NARRATION,'' AS XN_NO,@DFROMDT AS XN_DT,0 AS OP,(CASE WHEN OP_BAL>0 THEN OP_BAL ELSE 0 END) AS DR_AMOUNT,
(CASE WHEN OP_BAL<0 THEN ABS(OP_BAL) ELSE 0 END) AS CR_AMOUNT,'OPS' AS XN_TYPE,1 AS S_NO,0 AS DONOT_CALC 
FROM @TOPBAL
 
INSERT @TDAYBOOK
SELECT AC_NAME,NARRATION,XN_NO,XN_DT,OP_BAL AS OP,DR_AMOUNT,CR_AMOUNT,XN_TYPE,2 AS S_NO,0 AS DONOT_CALC 
FROM @TCASHXN

PRINT 'DAYBOOK-6'
INSERT @TDAYBOOK
SELECT C.CUSTOMER_TITLE + ' ' + C.CUSTOMER_FNAME + ' ' + C.CUSTOMER_LNAME AS AC_NAME,A.REMARKS AS NARRATION,
CM_NO,CM_DT,0 AS OP,0 AS DR_AMOUNT,A.NET_AMOUNT-ISNULL(D.CASH_AMOUNT,0) AS CR_AMOUNT,'SLS' AS XN_TYPE,3 AS S_NO,0 AS DONOT_CALC
FROM CMM01106 A
JOIN CUSTDYM C ON A.CUSTOMER_CODE = C.CUSTOMER_CODE
LEFT OUTER JOIN VW_BILL_PAYMODE D ON A.CM_ID = D.MEMO_ID AND D.XN_TYPE = 'SLS'
WHERE A.CM_DT BETWEEN @DFROMDT AND @DTODT
AND A.CANCELLED = 0
AND  A.location_Code  = @CDEPTID 
AND  A.NET_AMOUNT<>ISNULL(D.CASH_AMOUNT,0)
AND A.USER_CODE=(CASE WHEN @CUSERCODE='' THEN A.USER_CODE ELSE @CUSERCODE END)

INSERT @TDAYBOOK
SELECT 'SALE' AS AC_NAME,'' AS NARRATION,
'' AS XN_NO,'' AS XN_DT,0 AS OP,SUM(NET_AMOUNT) AS DR_AMOUNT,0 AS CR_AMOUNT,'SLS' AS XN_TYPE,3 AS S_NO,1 AS DONOT_CALC
FROM CMM01106 A
WHERE A.CM_DT BETWEEN @DFROMDT AND @DTODT
AND A.CANCELLED = 0
AND  A.location_Code  = @CDEPTID 
AND A.USER_CODE=(CASE WHEN @CUSERCODE='' THEN A.USER_CODE ELSE @CUSERCODE END)


INSERT @TDAYBOOK
SELECT 'CASH' AS AC_NAME,'' AS NARRATION,
'' AS XN_NO,'' AS XN_DT,0 AS OP,SUM(D.CASH_AMOUNT) AS DR_AMOUNT,0 AS CR_AMOUNT,'SLS' AS XN_TYPE,3 AS S_NO,0 AS DONOT_CALC
FROM CMM01106 A
LEFT OUTER JOIN VW_BILL_PAYMODE D ON A.CM_ID = D.MEMO_ID AND D.XN_TYPE = 'SLS'
WHERE A.CM_DT BETWEEN @DFROMDT AND @DTODT
AND A.CANCELLED = 0
AND  A.location_Code  = @CDEPTID 
AND   ISNULL(D.CASH_AMOUNT,0) <> 0
AND A.USER_CODE=(CASE WHEN @CUSERCODE='' THEN A.USER_CODE ELSE @CUSERCODE END)

INSERT @TDAYBOOK
SELECT 'OTHERS' AS AC_NAME,'' AS NARRATION,
'' AS XN_NO,'' AS XN_DT,0 AS OP,SUM(A.NET_AMOUNT-D.CASH_AMOUNT) AS DR_AMOUNT,0 AS CR_AMOUNT,'SLS' AS XN_TYPE,3 AS S_NO,0 AS DONOT_CALC
FROM CMM01106 A
JOIN VW_BILL_PAYMODE D ON A.CM_ID = D.MEMO_ID AND D.XN_TYPE = 'SLS'
WHERE A.CM_DT BETWEEN @DFROMDT AND @DTODT
AND A.CANCELLED = 0
AND A.location_Code  = @CDEPTID 
AND A.USER_CODE=(CASE WHEN @CUSERCODE='' THEN A.USER_CODE ELSE @CUSERCODE END)



INSERT @TDAYBOOK
SELECT 'CASH IN HAND' AS AC_NAME,'' AS NARRATION,'' AS XN_NO,@DFROMDT AS XN_DT,0 AS OP,(CASE WHEN CL_BAL<0 THEN ABS(CL_BAL) ELSE 0 END) AS DR_AMOUNT,
(CASE WHEN CL_BAL>0 THEN CL_BAL ELSE 0 END) AS CR_AMOUNT,'CBS' AS XN_TYPE,4 AS S_NO,0 AS DONOT_CALC FROM @TCLBAL

SELECT * FROM @TDAYBOOK ORDER BY S_NO

SELECT DENOMINATION,QUANTITY 
FROM PECD01106  WHERE  PEM_MEMO_DT=@DTODT

END
------- END OF PROCEDURE SP_DAYBOOK
