CREATE PROCEDURE SP_PRD_DEPTOUTPUT 
@NQUERYID NUMERIC (2,0),    
@CMEMOID VARCHAR(40),    
@CWHERE VARCHAR(500),    
@CARTICLECODE VARCHAR(50),    
@CFINYEAR VARCHAR(5),    
@NNAVMODE NUMERIC(2,0)    
-- WITH ENCRYPTION   
AS    
    
BEGIN      
      
DECLARE @CCMD NVARCHAR(4000)      
       
IF       
@NQUERYID = 1      
GOTO LBLNAVIGATE      
      
ELSE IF       
@NQUERYID = 2      
GOTO LBLGETMASTERS      
      
ELSE IF       
@NQUERYID = 3      
GOTO LBLGETDETAILS      
      
ELSE IF       
@NQUERYID = 4      
GOTO LBLGETSEGMENTS      
      
ELSE IF       
@NQUERYID = 5      
GOTO LBLARTICLELIST      
      
ELSE IF       
@NQUERYID = 6      
GOTO LBLARTICLEPARA1      
      
ELSE IF       
@NQUERYID = 7      
GOTO LBLARTICLEPARA2      
      
ELSE IF       
@NQUERYID = 8      
GOTO LBLARTICLEBOM      
      
ELSE IF       
@NQUERYID = 9      
GOTO LBLGETCONSUMPTION      
      
ELSE IF       
@NQUERYID = 10      
GOTO LBLGETLEDGERS      
      
ELSE IF       
@NQUERYID = 11      
GOTO LBLGETWORKORDERS      
      
ELSE IF       
@NQUERYID = 12      
GOTO LBLREPORT      
    
ELSE IF       
@NQUERYID = 13      
GOTO LBLCONVARTICLELIST     
    
ELSE IF       
@NQUERYID = 14      
GOTO LBLJOBLIST    
    
ELSE      
     
GOTO LAST      
       
LBLNAVIGATE:      
      
 EXECUTE SP_NAVIGATE 'PRD_DEPARTMENT_OUTPUT_MST',@NNAVMODE,@CMEMOID,@CFINYEAR,'MEMO_NO','MEMO_DT','MEMO_ID',@CWHERE      
      
GOTO LAST      
      
LBLGETMASTERS:      
      
    SELECT T1.*,T2.DEPARTMENT_NAME,T3.USERNAME,''AS AC_NAME,      
    ISNULL(T6.REF_NO,'') AS WORKORDERNO,    
    ISNULL(T6.MEMO_NO,'') AS WORKORDERMEMONO    
    FROM PRD_DEPARTMENT_OUTPUT_MST T1      
    JOIN PRD_DEPARTMENT_MST T2 ON T1.DEPARTMENT_ID = T2.DEPARTMENT_ID      
    JOIN USERS T3 ON T3.USER_CODE = T1.USER_CODE      
    LEFT OUTER JOIN PRD_WO_MST T6 ON T6.MEMO_ID = T1.REF_PRD_WORKORDER_MEMOID      
    WHERE T1.MEMO_ID = @CMEMOID      
      
GOTO LAST      
      
LBLGETDETAILS:      
 IF @NNAVMODE = 1    
 BEGIN    
    SELECT A.ARTICLE_CODE ,A.PARA1_CODE ,A.PARA2_CODE ,    
    (A.TOTAL_QTY - ISNULL(B.TOTAL_OUTPUT_QTY,0)) AS QUANTITY,A.TOTAL_QTY,    
    (A.TOTAL_QTY - ISNULL(B.TOTAL_OUTPUT_QTY,0)) AS BALANCE_QTY,    
    ISNULL(B.TOTAL_OUTPUT_QTY,0) AS TOTAL_OUTPUT_QTY,    
    PARA1.PARA1_NAME,PARA2.PARA2_NAME,T3.ARTICLE_NO,T3.ARTICLE_NAME,UOM.UOM_NAME,T3.DT_CREATED  
     ,CAST(0 AS NUMERIC) AS TOTAL_PRICE   
    FROM     
    (    
     SELECT A.ARTICLE_CODE,SUM(C.QUANTITY) AS TOTAL_QTY,C.PARA1_CODE,C.PARA2_CODE     
     FROM PRD_WO_DET A     
     JOIN PRD_WO_SUB_DET C ON A.ROW_ID = C.REF_ROW_ID      
     WHERE A.MEMO_ID = @CMEMOID     
     AND A.ARTICLE_CODE = @CARTICLECODE     
     GROUP BY A.ARTICLE_CODE,C.PARA1_CODE,C.PARA2_CODE    
    ) A     
    JOIN PARA1 ON PARA1.PARA1_CODE = A.PARA1_CODE      
    JOIN PARA2 ON PARA2.PARA2_CODE = A.PARA2_CODE      
    JOIN ARTICLE T3 ON T3.ARTICLE_CODE = A.ARTICLE_CODE      
    JOIN UOM ON T3.UOM_CODE = UOM.UOM_CODE     
    LEFT OUTER JOIN     
    (    
     SELECT T1.ARTICLE_CODE,SUM(T1.QUANTITY) AS TOTAL_OUTPUT_QTY,T1.PARA1_CODE,T1.PARA2_CODE     
     FROM PRD_DEPARTMENT_OUTPUT_DET T1      
     JOIN PRD_DEPARTMENT_OUTPUT_MST M ON M.MEMO_ID = T1.MEMO_ID      
     WHERE M.REF_PRD_WORKORDER_MEMOID = @CMEMOID     
     AND T1.ARTICLE_CODE = @CARTICLECODE     
     AND M.CANCELLED = 0     
     GROUP BY T1.ARTICLE_CODE,T1.PARA1_CODE,T1.PARA2_CODE    
    ) B     
    ON A.ARTICLE_CODE = B.ARTICLE_CODE     
    AND A.PARA1_CODE = B.PARA1_CODE     
    AND A.PARA2_CODE = B.PARA2_CODE     
 END    
 ELSE    
 BEGIN    
     
  DECLARE @CREFWORKORDERMEMOID VARCHAR(MAX),@CCOMPARTICLECODE VARCHAR(MAX)     
  IF @CMEMOID <> ''    
  BEGIN    
   SELECT TOP 1 @CREFWORKORDERMEMOID=REF_PRD_WORKORDER_MEMOID FROM PRD_DEPARTMENT_OUTPUT_MST WHERE MEMO_ID = @CMEMOID    
   SELECT TOP 1 @CCOMPARTICLECODE = ARTICLE_CODE FROM PRD_DEPARTMENT_OUTPUT_DET WHERE MEMO_ID = @CMEMOID    
  END    
  ELSE    
   SELECT @CREFWORKORDERMEMOID = '',@CCOMPARTICLECODE = ''    
       
   SELECT T1.*,T2.SEGMENT_NAME,PARA1.PARA1_NAME,PARA2.PARA2_NAME,T3.ARTICLE_NO,    
   T3.ARTICLE_NAME,T3.ARTICLE_DESC,UOM.UOM_NAME,T3.DT_CREATED      
   ,ISNULL(P.BALANCE_QTY,0) AS BALANCE_QTY    
   ,ISNULL(P.TOTAL_QTY,0) AS TOTAL_QTY    
   ,ISNULL(P.TOTAL_OUTPUT_QTY,0) AS TOTAL_OUTPUT_QTY  
   ,T1.QUANTITY*T1.PURCHASE_PRICE AS TOTAL_PRICE   
   FROM PRD_DEPARTMENT_OUTPUT_DET T1      
   JOIN PRD_SEGMENT_MST T2 ON T1.SEGMENT_ID = T2.SEGMENT_ID      
   JOIN PARA1 ON PARA1.PARA1_CODE = T1.PARA1_CODE      
   JOIN PARA2 ON PARA2.PARA2_CODE = T1.PARA2_CODE      
   JOIN ARTICLE T3 ON T3.ARTICLE_CODE = T1.ARTICLE_CODE      
   JOIN UOM ON T3.UOM_CODE = UOM.UOM_CODE      
   LEFT OUTER JOIN    
   (    
    SELECT A.ARTICLE_CODE ,A.PARA1_CODE ,A.PARA2_CODE ,     
    A.TOTAL_QTY,(A.TOTAL_QTY - ISNULL(B.TOTAL_OUTPUT_QTY,0)) AS BALANCE_QTY,    
    ISNULL(B.TOTAL_OUTPUT_QTY,0) AS TOTAL_OUTPUT_QTY    
    FROM     
    (    
     SELECT A.ARTICLE_CODE,SUM(C.QUANTITY) AS TOTAL_QTY,C.PARA1_CODE,C.PARA2_CODE     
     FROM PRD_WO_DET A     
     JOIN PRD_WO_SUB_DET C ON A.ROW_ID = C.REF_ROW_ID      
     WHERE A.MEMO_ID = @CREFWORKORDERMEMOID AND A.ARTICLE_CODE = @CCOMPARTICLECODE     
     GROUP BY A.ARTICLE_CODE,C.PARA1_CODE,C.PARA2_CODE    
    ) A     
    LEFT OUTER JOIN     
    (    
     SELECT T1.ARTICLE_CODE,SUM(T1.QUANTITY) AS TOTAL_OUTPUT_QTY,T1.PARA1_CODE,T1.PARA2_CODE     
     FROM PRD_DEPARTMENT_OUTPUT_DET T1      
     JOIN PRD_DEPARTMENT_OUTPUT_MST M ON M.MEMO_ID = T1.MEMO_ID      
     WHERE     
     M.REF_PRD_WORKORDER_MEMOID = @CREFWORKORDERMEMOID    
     AND T1.ARTICLE_CODE = @CCOMPARTICLECODE AND M.CANCELLED = 0     
     GROUP BY T1.ARTICLE_CODE,T1.PARA1_CODE,T1.PARA2_CODE    
    ) B     
    ON A.ARTICLE_CODE = B.ARTICLE_CODE AND A.PARA1_CODE = B.PARA1_CODE AND A.PARA2_CODE = B.PARA2_CODE    
   )    
   P ON P.ARTICLE_CODE = T1.ARTICLE_CODE AND P.PARA1_CODE = T1.PARA1_CODE AND P.PARA2_CODE = T1.PARA2_CODE    
   WHERE T1.MEMO_ID = @CMEMOID      
 END    
GOTO LAST      
      
LBLGETSEGMENTS:      
      
   SELECT  T1.* FROM PRD_SEGMENT_MST T1  JOIN PRD_FLOOR_MST T3 ON T3.FLOOR_ID=T1.FLOOR_ID       
   WHERE T3.DEPARTMENT_ID = @CWHERE AND T1.SEGMENT_ID <> '0000000'      
      
GOTO LAST      
      
LBLARTICLELIST:      
     
 IF(@CMEMOID <> '')      
 BEGIN    
      
   SET @CCMD =  'SELECT DISTINCT T3.MEMO_ID,T1.ARTICLE_NO,T1.ARTICLE_CODE    
       ,T1.ARTICLE_DESC,T1.ARTICLE_NAME,UOM.UOM_NAME,T1.DT_CREATED      
       ,T1.PURCHASE_PRICE ,T1.MRP ,T1.WHOLESALE_PRICE AS WS_PRICE    
       FROM ARTICLE T1      
       JOIN UOM ON UOM.UOM_CODE = T1.UOM_CODE      
       JOIN PRD_WO_DET  T3 ON T3.ARTICLE_CODE = T1.ARTICLE_CODE      
       WHERE T3.MEMO_ID = '''+@CMEMOID+'''     
       AND T3.ARTICLE_CODE IN     
       (    
      SELECT K.REF_COMPONENT_ARTICLE_CODE     
      FROM PRD_MATERIAL_RECEIPT_MST R    
      JOIN PRD_ISSUE_MATERIAL_MST I ON R.REF_PRD_MATERIAL_ISSUE_MEMOID = I.MEMO_ID     
      JOIN PRD_ISSUE_MATERIAL_DET K ON I.MEMO_ID = K.MEMO_ID     
      WHERE K.REF_PRD_WORKORDER_MEMOID = '''+@CMEMOID+'''     
      AND R.DEPARTMENT_ID = '''+ @CWHERE +'''    
       )'    
          
   PRINT @CCMD      
   EXECUTE SP_EXECUTESQL @CCMD     
 END    
 ELSE      
 BEGIN    
   SELECT DISTINCT T1.ARTICLE_NO,T1.ARTICLE_CODE,T1.ARTICLE_DESC,T1.ARTICLE_NAME,UOM.UOM_NAME,T1.DT_CREATED    
   ,T2.PURCHASE_PRICE ,T2.MRP ,T2.WS_PRICE    
   FROM ARTICLE T1      
   JOIN PRD_DEPARTMENT_OUTPUT_DET T2 ON T1.ARTICLE_CODE = T2.ARTICLE_CODE      
   JOIN UOM ON UOM.UOM_CODE = T1.UOM_CODE      
 END    
      
GOTO LAST      
      
LBLARTICLEPARA1:      
      
  IF(ISNULL(@CMEMOID,'') <> '')      
   SELECT DISTINCT A.ARTICLE_CODE, D.PARA1_CODE, B.PARA1_NAME       
   FROM PRD_WO_DET A (NOLOCK)       
   JOIN PRD_WO_SUB_DET D (NOLOCK) ON D.REF_ROW_ID = A.ROW_ID     
   JOIN PARA1 B (NOLOCK)  ON D.PARA1_CODE = B.PARA1_CODE      
   WHERE A.MEMO_ID =@CMEMOID AND A.ARTICLE_CODE = @CARTICLECODE     
   ORDER BY B.PARA1_NAME      
  ELSE      
      
   SELECT A.ARTICLE_CODE, A.PARA1_CODE, B.PARA1_NAME       
   FROM ART_PARA1 A (NOLOCK)       
   JOIN PARA1 B (NOLOCK)  ON A.PARA1_CODE = B.PARA1_CODE      
   WHERE A.ARTICLE_CODE = @CARTICLECODE       
   ORDER BY B.PARA1_NAME      
      
GOTO LAST      
      
LBLARTICLEPARA2:      
 IF(ISNULL(@CMEMOID,'') <> '')      
    SELECT DISTINCT A.ARTICLE_CODE, D.PARA2_CODE, B.PARA2_NAME,B.PARA2_ORDER      
    FROM PRD_WO_DET A (NOLOCK)       
    JOIN PRD_WO_SUB_DET D (NOLOCK) ON D.REF_ROW_ID = A.ROW_ID     
    JOIN PARA2 B (NOLOCK)  ON D.PARA2_CODE = B.PARA2_CODE      
    WHERE A.MEMO_ID =@CMEMOID AND A.ARTICLE_CODE = @CARTICLECODE     
    ORDER BY B.PARA2_NAME     
 ELSE      
    SELECT A.ARTICLE_CODE, A.PARA2_CODE, B.PARA2_NAME,B.PARA2_ORDER      
    FROM ART_DET A (NOLOCK)       
    JOIN PARA2 B (NOLOCK)  ON A.PARA2_CODE = B.PARA2_CODE      
    WHERE A.ARTICLE_CODE = @CARTICLECODE       
    ORDER BY B.PARA2_ORDER      
      
GOTO LAST      
      
LBLARTICLEBOM:      
  IF(@NNAVMODE = 0)      
  BEGIN    
  SET @CCMD = N'SELECT T3.MRP,T3.PURCHASE_PRICE,T3.WS_PRICE,T3.PRODUCT_UID     
  ,PARA1.PARA1_CODE,PARA1.PARA1_NAME,PARA2.PARA2_CODE,PARA2.PARA2_NAME,    
   T2.CODING_SCHEME,T2.UOM_CODE,T2.ALIAS,T2.MP_PERCENTAGE,T2.PURCHASE_PRICE,T2.MRP,T2.PARA1_SET
   ,T2.STOCK_NA,T2.PARA2_SET,T2.INACTIVE,T2.SKU_CODE,T2.ARTICLE_CODE,T2.ARTICLE_DESC,T2.ARTICLE_GROUP_CODE
   ,T2.ARTICLE_NAME,T2.ARTICLE_NO,ARTICLE_PRD_MODE,T2.ARTICLE_SET_CODE,
   SUM(T1.AVG_QTY) AS AVG_QTY,D.ARTICLE_CODE AS REF_FINISHED_ARTICLE_CODE,0 AS TOTALQTY,      
   ISNULL(T3.QUANTITY_IN_STOCK,0) AS QUANTITY_IN_STOCK,UOM.UOM_NAME
   ,T3.PRODUCT_CODE    
   FROM PRD_WO_ART_BOM T1    
   JOIN PRD_WO_DET D ON D.ROW_ID = T1.REF_ROW_ID      
   JOIN PARA1 ON PARA1.PARA1_CODE =  T1.PARA1_CODE     
   JOIN ARTICLE T2 ON T2.ARTICLE_CODE = T1.BOM_ARTICLE_CODE      
   JOIN PARA2 ON PARA2.PARA2_CODE =  T1.PARA2_CODE     
   JOIN UOM ON UOM.UOM_CODE = T2.UOM_CODE     
   JOIN     
   (    
    SELECT SKU.ARTICLE_CODE,SKU.PARA1_CODE,SKU.PARA2_CODE,SKU.PRODUCT_UID,PMT.QUANTITY_IN_STOCK,PMT.WIP    
   ,SKU.MRP,SKU.PURCHASE_PRICE,SKU.WS_PRICE ,SKU.COMPONENT_CODE
   ,SKU.PRODUCT_CODE       
   FROM PRD_SKU SKU JOIN PRD_PMT PMT ON SKU.PRODUCT_UID = PMT.PRODUCT_UID     
   WHERE PMT.DEPARTMENT_ID = '''+ @CWHERE +''' AND SKU.WORK_ORDER_ID = '''+ @CMEMOID +'''    
   )  T3 ON T1.BOM_ARTICLE_CODE = T3.ARTICLE_CODE  
   --AND T1.PARA1_CODE = T3.PARA1_CODE 
   --AND T1.PARA2_CODE = T3.PARA2_CODE    AND T3.COMPONENT_CODE=D.ARTICLE_CODE
   WHERE D.ARTICLE_CODE = '''+@CARTICLECODE+''' AND D.MEMO_ID = '''+ @CMEMOID +'''
   GROUP BY 
   T3.MRP,T3.PURCHASE_PRICE,T3.WS_PRICE,T3.PRODUCT_UID     
  ,PARA1.PARA1_CODE,PARA1.PARA1_NAME,PARA2.PARA2_CODE,PARA2.PARA2_NAME,    
   T2.CODING_SCHEME,T2.UOM_CODE,T2.ALIAS,T2.MP_PERCENTAGE,T2.PURCHASE_PRICE,T2.MRP,T2.PARA1_SET
   ,T2.PARA2_SET,T2.INACTIVE,T2.SKU_CODE,T2.ARTICLE_CODE,T2.ARTICLE_DESC,T2.ARTICLE_GROUP_CODE
   ,T2.ARTICLE_NAME,T2.ARTICLE_NO,ARTICLE_PRD_MODE,T2.ARTICLE_SET_CODE,D.ARTICLE_CODE ,
   ISNULL(T3.QUANTITY_IN_STOCK,0) ,UOM.UOM_NAME,T2.STOCK_NA
   ,T3.PRODUCT_CODE'       
   PRINT @CCMD      
   EXECUTE SP_EXECUTESQL @CCMD      
  END    
  ELSE     
 BEGIN    
  SET @CCMD = N' SELECT T2.*,CAST(1 AS NUMERIC(10,2)) AS AVG_QTY,'''+@CARTICLECODE+''' AS REF_FINISHED_ARTICLE_CODE    
      ,0 AS TOTALQTY, T3.QUANTITY_IN_STOCK,UOM.UOM_NAME ,T3.MRP,T3.PURCHASE_PRICE,T3.WS_PRICE,T3.PRODUCT_UID     
      ,T3.MRP,T3.PURCHASE_PRICE,T3.WS_PRICE 
      ,T3.PRODUCT_CODE    
      FROM ARTICLE T2       
      JOIN     
      (    
      SELECT SKU.ARTICLE_CODE,SKU.PARA1_CODE,SKU.PARA2_CODE,SKU.PRODUCT_UID,PMT.QUANTITY_IN_STOCK,PMT.WIP    
      ,SKU.MRP,SKU.PURCHASE_PRICE,SKU.WS_PRICE ,SKU.COMPONENT_CODE
      ,SKU.PRODUCT_CODE       
      FROM PRD_SKU SKU     
      JOIN PRD_PMT PMT ON SKU.PRODUCT_UID = PMT.PRODUCT_UID     
      WHERE PMT.DEPARTMENT_ID = '''+ @CWHERE +''' AND SKU.WORK_ORDER_ID = '''+ @CMEMOID +'''    
      )  T3 ON T2.ARTICLE_CODE = T3.ARTICLE_CODE      
      JOIN UOM ON UOM.UOM_CODE = T2.UOM_CODE WHERE  T3.QUANTITY_IN_STOCK > 0'      
   PRINT @CCMD      
   EXECUTE SP_EXECUTESQL @CCMD      
 END     
GOTO LAST      
      
LBLGETCONSUMPTION:      
      
 SET @CCMD = N'SELECT DISTINCT T3.*,T2.ARTICLE_NO,T2.ARTICLE_NAME,T2.ARTICLE_DESC,    
    ISNULL(T4.QUANTITY_IN_STOCK,0) AS QUANTITY_IN_STOCK,      
    UOM.UOM_NAME,T5.ARTICLE_NO AS REF_ARTICLE_NO,T5.ARTICLE_NAME AS REF_ARTICLE_NAME,      
    T5.ARTICLE_DESC AS REF_ARTICLE_DESC,T6.SEGMENT_NAME,CAST(1 AS BIT) AS CHK,    
    PARA1.PARA1_NAME,PARA2.PARA2_NAME ,CAST(0  AS NUMERIC(10,2)) AS REQ_QUANTITY   
    ,ISNULL(T3.QUANTITY,0)* ISNULL(T3.PURCHASE_PRICE,0) AS AMOUNT    
    ,T4.PRODUCT_CODE  
    FROM PRD_DEPARTMENT_RMCONSUMPTION_DET T3      
    JOIN PRD_DEPARTMENT_OUTPUT_MST M ON T3.MEMO_ID = M.MEMO_ID    
    JOIN  PRD_WO_ART_BOM T1 ON T3.ARTICLE_CODE = T1.BOM_ARTICLE_CODE     
    JOIN PRD_WO_DET D ON D.ROW_ID = T1.REF_ROW_ID     
    AND T3.REF_FINISHED_ARTICLE_CODE = D.ARTICLE_CODE    
    --AND T3.PARA1_CODE = T1.PARA1_CODE AND T3.PARA2_CODE = T1.PARA2_CODE --AND T3.AVG_QTY = T1.AVG_QTY     
    JOIN ARTICLE T2 ON T3.ARTICLE_CODE = T2.ARTICLE_CODE      
    JOIN     
    (    
  SELECT SKU.ARTICLE_CODE,SKU.PARA1_CODE,SKU.PARA2_CODE,SKU.PRODUCT_UID    
  ,PMT.QUANTITY_IN_STOCK,PMT.WIP,SKU.WORK_ORDER_ID,    
  SKU.MRP,SKU.PURCHASE_PRICE,SKU.WS_PRICE , SKU.PRODUCT_CODE         
  FROM PRD_SKU SKU     
  JOIN PRD_PMT PMT ON SKU.PRODUCT_UID = PMT.PRODUCT_UID     
  WHERE PMT.DEPARTMENT_ID = '''+ @CWHERE +'''     
    ) T4 ON T3.PRODUCT_UID = T4.PRODUCT_UID     
    JOIN UOM ON UOM.UOM_CODE = T2.UOM_CODE      
    JOIN ARTICLE T5 ON T5.ARTICLE_CODE = T3.REF_FINISHED_ARTICLE_CODE      
    JOIN PRD_SEGMENT_MST T6 ON T6.SEGMENT_ID = T3.SEGMENT_ID      
    JOIN PARA1 ON PARA1.PARA1_CODE = T3.PARA1_CODE    
    JOIN PARA2 ON PARA2.PARA2_CODE = T3.PARA2_CODE    
    WHERE T3.MEMO_ID = '''+@CMEMOID+'''    
    AND D.MEMO_ID = M.REF_PRD_WORKORDER_MEMOID '    
     
       
 PRINT @CCMD      
 EXECUTE SP_EXECUTESQL @CCMD      
      
 GOTO LAST      
      
      
LBLGETWORKORDERS:      
 SELECT DISTINCT T1.* FROM PRD_WO_MST T1  WHERE T1.CANCELLED = 0    AND T1.MARK_AS_COMPLETED=1      
 AND T1.MEMO_ID IN     
 (SELECT DISTINCT I.REF_PRD_WORKORDER_MEMOID FROM PRD_MATERIAL_RECEIPT_MST R    
 JOIN PRD_ISSUE_MATERIAL_DET  I ON R.REF_PRD_MATERIAL_ISSUE_MEMOID = I.MEMO_ID     
 WHERE R.DEPARTMENT_ID = @CWHERE )      
 GOTO LAST      
      
LBLGETLEDGERS:      
 SELECT T1.* FROM LMV01106 T1 JOIN PRD_AGENCY_MST T2 ON T1.AC_CODE = T2.AC_CODE      
 GOTO LAST      
      
LBLREPORT:      
 SELECT * FROM VW_REP_OUTPUT WHERE MEMO_ID = @CMEMOID ORDER BY SEGMENT_NAME      
 GOTO LAST       
     
    
LBLCONVARTICLELIST:    
    
 SELECT DISTINCT T1.ARTICLE_NO,T1.ARTICLE_CODE,T1.ARTICLE_DESC    
 ,T1.ARTICLE_NAME,UOM.UOM_NAME,T1.DT_CREATED,PARA1.PARA1_NAME ,PARA2.PARA2_NAME    
 ,T1.PARA1_CODE,T1.PARA2_CODE     
 FROM ARTICLE T1      
 JOIN UOM ON UOM.UOM_CODE = T1.UOM_CODE      
 JOIN PARA1 ON PARA1.PARA1_CODE = T1.PARA1_CODE     
 JOIN PARA2 ON PARA2.PARA2_CODE = T1.PARA2_CODE     
 WHERE ARTICLE_CODE <> '00000000'    
    
   GOTO LAST      
    
LBLJOBLIST:    
    
 SELECT JOB_NAME,JOB_CODE FROM JOBS WHERE INACTIVE = 0    
 GOTO LAST      
     
LAST:     
    
END
