CREATE PROCEDURE  SP3S_SYNCH_UPLOADDATA_SLRRECON_OPT
(
    @nSpId VARCHAR(50)
   ,@CERRMSG VARCHAR(1000) OUTPUT
)
AS
SET NOCOUNT ON
BEGIN


DECLARE @CSTEP VARCHAR(100),@DTSQL NVARCHAR(MAX)
	   ,@CTABLENAME VARCHAR(200),@CKEYFIELD VARCHAR(200),@CTMP_TABLENAME VARCHAR(200),@LINSERTONLY VARCHAR(1)
	   ,@CFILTERCONDITION VARCHAR(200),@LUPDATEONLY VARCHAR(1),@BALWAYSUPDATE VARCHAR(1)
	   ,@CCURDEPTID VARCHAR(5),@CTEMPMASTERTABLE VARCHAR(200),@CTEMPDETAILTABLE1 VARCHAR(200)
	   ,@BADDMODE BIT,@CSOURCEDB VARCHAR(200),@CMERGEDB VARCHAR(200)
	   ,@BMSTINSERTONLY BIT,@BSERIESMISMATCHFOUND BIT,@CMEMOID VARCHAR(40),@CMEMOIDSEARCH VARCHAR(40)
	   ,@CRETPRODUCTCODE VARCHAR(50),@NVERSIONNO INT, @CCMD NVARCHAR(MAX),@CTEMPDETAILTABLE3 VARCHAR(200)
	   ,@bcancelled bit
	

BEGIN TRY
	
	
	SET @CSTEP=10

	SELECT @CSOURCEDB='',@CMERGEDB='',@BMSTINSERTONLY=1,@BSERIESMISMATCHFOUND=0
	
	SET @CSTEP=15
    	
    SELECT TOP 1 @CCURDEPTID=VALUE FROM CONFIG WHERE CONFIG_OPTION='LOCATION_ID'

	SELECT @CTEMPMASTERTABLE=@CSOURCEDB+'SLRRECON_SLR_RECON_MST_UPLOAD',
		   @CTEMPDETAILTABLE1=@CSOURCEDB+'SLRRECON_SLR_RECON_DET_UPLOAD'
		   

LBLSTART:
    
    BEGIN TRANSACTION
    
    SELECT @CMEMOID='',@NVERSIONNO=0
		


    SELECT TOP 1 @CMEMOID = B.MEMO_ID ,@bcancelled=cancelled 
    FROM SLRRECON_SLR_RECON_MST_UPLOAD B (NOLOCK) where sp_id=@nSpId
  
    
    IF ISNULL(@CMEMOID,'')=''
		GOTO EXIT_PROC
		
    
    SET @CFILTERCONDITION = 'B.SP_ID='''+@nSpId+''''

	SET @CSTEP=20
	SET @CMEMOIDSEARCH=''
	SELECT TOP 1 @CMEMOIDSEARCH=A.MEMO_ID FROM SLR_RECON_MST A (NOLOCK) WHERE A.MEMO_ID=@CMEMOID
	
	IF ISNULL(@CMEMOIDSEARCH,'')<>''
		SET @BADDMODE=0
	ELSE
		SET @BADDMODE=1


	IF @BADDMODE=0
	BEGIN	
		SET @CSTEP=25

		IF @bCancelled=1 
		BEGIN
			UPDATE SLR_RECON_mst WITH (ROWLOCK) SET cancelled=1 WHERE MEMO_ID=@cMemoid
			GOTO lblUpdatePmt
		END

		SET @DTSQL=N'DELETE A FROM SLR_RECON_DET A JOIN '+@CTEMPMASTERTABLE+' B (NOLOCK) ON A.MEMO_ID=B.MEMO_ID
					 LEFT OUTER JOIN 
					 (SELECT ROW_ID FROM '+@CTEMPDETAILTABLE1+' B WHERE '+@CFILTERCONDITION+') C 
					 ON A.ROW_ID = C.ROW_ID 
					 WHERE a.MEMO_ID='''+@CMEMOID+''' and  C.ROW_ID IS NULL AND '+@CFILTERCONDITION

		PRINT @DTSQL
		EXEC SP_EXECUTESQL @DTSQL
		
	END
	
LBLMERGE:

							  
	SET @CFILTERCONDITION = 'B.MEMO_ID='''+@CMEMOID+''' AND B.sp_id='''+@nSpId+''''


	SET @CTABLENAME='SLR_RECON_MST'
	SET @CTMP_TABLENAME='SLRRECON_SLR_RECON_MST_UPLOAD'
	SET @CKEYFIELD='MEMO_ID'

	
	SET @CSTEP=70
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=1,@CFILTERCONDITION=@CFILTERCONDITION,@LUPDATEONLY=@LUPDATEONLY
							  ,@BALWAYSUPDATE=1 

	SET @CTABLENAME='SLR_RECON_DET'
	SET @CTMP_TABLENAME='SLRRECON_SLR_RECON_DET_UPLOAD'
	SET @CKEYFIELD='ROW_ID'

	
	SET @CSTEP=210	 
	
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=@BADDMODE,@CFILTERCONDITION=@CFILTERCONDITION,@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1,@BUPDATEXNS=1 

	
 
 	
 	SET @CFILTERCONDITION = ' B.sp_id='''+@nSpId+''''
   
   SET @CTABLENAME='POSGRRecos'
   SET @CTMP_TABLENAME='SLRRECON_POSGRRecos_UPLOAD'
   SET @CKEYFIELD='cm_id'

	SET @CSTEP=215	 
	
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='CMDRowId',@CKEYFIELD3=''
							  ,@LINSERTONLY=0,@CFILTERCONDITION=@CFILTERCONDITION,@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1,@BUPDATEXNS=1 


   
	SET @CSTEP=220 

	lblUpdatePmt:

	EXEC SP3S_MERGE_LOCPMT  
	@cTempTable='SLRRECON_PMT01106_UPLOAD',  
	@cMemoIdCol='sp_id',  
	@cMemoId =@nSpId

	SET @CSTEP=230    		
	
	


END TRY
BEGIN CATCH
	SET @CERRMSG='P:SP3S_SYNCH_UPLOADDATA_SLRRECON_OPT, MEMO ID :'+@CMEMOID+' STEP:'+@CSTEP+', MESSAGE:'+ERROR_MESSAGE()
	GOTO EXIT_PROC
END CATCH

EXIT_PROC:

	
	IF @@TRANCOUNT>0
	BEGIN
		IF ISNULL(@CERRMSG,'')='' AND @BSERIESMISMATCHFOUND<>1
			COMMIT
		ELSE
			ROLLBACK
    END
    
    
	DELETE A FROM SLRRECON_SLR_RECON_MST_upload A WHERE A.sp_id=@nSpId
	DELETE A FROM SLRRECON_SLR_RECON_DET_upload A WHERE A.sp_id=@nSpId
	DELETE A FROM SLRRECON_PMT01106_upload A WHERE A.sp_id=@nSpId
	DELETE A FROM SLRRECON_POSGRRecos_UPLOAD A WHERE A.sp_id=@nSpId
	
	
END	
---END OF PROCEDURE - SP_SYNCH_MIRRORDATA_SLRRECON_SINGLE
