CREATE PROCEDURE [DBO].[SAVETRAN_WALLET]  
(  
  @NSPID INT  ,
  @nMODE INT=2
)  
  
AS  
BEGIN  
    DECLARE @CCMD_1 NVARCHAR(MAX),@CCMD_2 NVARCHAR(MAX),@CERRMSG AS VARCHAR(MAX)  
                       
  IF ISNULL(@NSPID,'') = ''                
    BEGIN                
     SET @CERRMSG = ' SPID REQUIRED .....CANNOT PROCEED'
     SELECT @CERRMSG AS ERRMSG           
--     GOTO END_PROC                    
    END  
       
  ELSE  
   BEGIN  
   IF @nMODE=2
   BEGIN


          SET @CCMD_1='UPDATE PYMTG_MST  
          SET 
              MERCHANT_ID = B.MERCHANT_ID,
              PYG_GRP_NAME = B.PYG_GRP_NAME,  
              API_KEY = B.API_KEY,  
              INACTIVE = B.INACTIVE,  
              CHK = B.CHK  
              FROM TEMP_PYMTG_MST_' +LTRIM(RTRIM(STR(@NSPID)))+' B  
              WHERE PYMTG_MST.PYG_GRP_CODE = B.PYG_GRP_CODE'  
                
                
            
          SET @CCMD_2='UPDATE PYMTG_DET  
          SET PYG_GRP_CODE = B.PYG_GRP_CODE,  
          PYG_NAME = B.PYG_NAME,  
          PYG_API_OTP = B.PYG_API_OTP,  
          PYG_API_DEBIT = B.PYG_API_DEBIT,  
          PYG_API_REFUND = B.PYG_API_REFUND,  
          CHK = B.CHK  
          FROM TEMP_PYMTG_DET_' +LTRIM(RTRIM(STR(@NSPID)))+' B  
          WHERE PYMTG_DET.PYG_CODE = B.PYG_CODE'  
                
 --         PRINT @CCMD_1  
 --         PRINT @CCMD_2  
            
            
          EXEC SP_EXECUTESQL @CCMD_1  
          EXEC SP_EXECUTESQL @CCMD_2
          
          
          --UPDATE PAYMODE_GRP_MST
          --SET
          --PAYMODE_GRP_NAME = B.PYG_GRP_NAME
          --FROM PYMTG_MST AS B WHERE PAYMODE_GRP_MST.PAYMODE_GRP_CODE = B.PYG_GRP_CODE
          --AND B.CHK =1
          
          --INSERT INTO PAYMODE_GRP_MST(PAYMODE_GRP_CODE,PAYMODE_GRP_NAME)
          --SELECT A.PYG_GRP_CODE,A.PYG_GRP_NAME FROM PYMTG_MST AS A
          --LEFT JOIN PAYMODE_GRP_MST AS B ON B.PAYMODE_GRP_CODE = A.PYG_GRP_CODE WHERE B.PAYMODE_GRP_CODE IS  NULL
          --AND A.CHK =1
    END 
	ELSE IF @nMODE=1
	BEGIN
          DECLARE @CNEWKEYVAL VARCHAR(200)
		  EXEC GETNEXTKEY @CTABLENAME ='PYMTG_MST',
		@CCOLNAME='PYG_GRP_CODE',
		@NWIDTH=7,@CPREFIX='PYTG',@NLZEROS=1,@CFINYEAR='',@NROWCOUNT=0,@CNEWKEYVAL=@CNEWKEYVAL OUTPUT

		SET @CCMD_1='INSERT PYMTG_MST	( API_KEY, CHK, INACTIVE, MERCHANT_ID, MERCHANT_KEY, OTP_REQ, PYG_GRP_CODE, PYG_GRP_NAME )  
		SELECT 	  API_KEY, CHK, INACTIVE, MERCHANT_ID, MERCHANT_KEY, OTP_REQ,'''+@CNEWKEYVAL+''' PYG_GRP_CODE, PYG_GRP_NAME 
		FROM TEMP_PYMTG_MST_' +LTRIM(RTRIM(STR(@NSPID)))

		SET @CCMD_2='INSERT PYMTG_DET	( CHK, PYG_API_DEBIT, PYG_API_OTP, PYG_API_REFUND, PYG_CODE, PYG_GRP_CODE, PYG_NAME )  
		SELECT 	  CHK, PYG_API_DEBIT, PYG_API_OTP, PYG_API_REFUND, PYG_CODE, '''+@CNEWKEYVAL+''' PYG_GRP_CODE, PYG_NAME 
		FROM TEMP_PYMTG_DET_' +LTRIM(RTRIM(STR(@NSPID)))
		
		PRINT @CCMD_1  
		PRINT @CCMD_2  

		EXEC SP_EXECUTESQL @CCMD_1  
        EXEC SP_EXECUTESQL @CCMD_2

          --UPDATE PAYMODE_MST
          --SET
          --PAYMODE_NAME = B.PYG_NAME,
          --PAYMODE_GRP_CODE = 'PYTGW01' ,
          --LAST_UPDATE = GETDATE()
          --FROM PYMTG_DET AS B WHERE PAYMODE_MST.PAYMODE_CODE = B.PYG_CODE
          --AND B.CHK =1
          
          --INSERT INTO PAYMODE_MST(PAYMODE_CODE,PAYMODE_NAME,PAYMODE_GRP_CODE,LAST_UPDATE,CREDIT_LIMIT,COMMISSION_PERCENTAGE,SERVICE_TAX_PERCENTAGE,INACTIVE,CURRENCY_CONVERSION_RATE,COMMISSION_PERCENTAGE_PAYABLE,COMMISSION_AC_CODE,AC_CODE)
          --SELECT A.PYG_CODE,A.PYG_NAME,'PYTGW01' AS PAYMODE_GRP_CODE ,GETDATE(),0,0,0,0,1,0,'0000000000','0000000000' FROM PYMTG_DET AS A
          --LEFT JOIN PAYMODE_MST AS B ON B.PAYMODE_CODE = A.PYG_CODE WHERE B.PAYMODE_CODE IS NULL
          --AND A.CHK =1
    END 
          SET @CERRMSG = ''
          SELECT @CERRMSG AS ERRMSG
            
END   
                   
    
END

--***************************************** END OF PROCEDURE SAVETRAN_WALLET
