CREATE PROCEDURE SP3S_PENDING_ALL_ORDER
(
  @CORDER_ID VARCHAR(100)='',
  @CARTICLE_CODE VARCHAR(10)='',
  @CPARA1_CODE VARCHAR(10)='',
  @CPARA2_CODE VARCHAR(10)='',
  @CLOCID varchar(5)=''
)
AS
BEGIN


        DECLARE @CONSIDER_COLOR_IN_PICKLIST VARCHAR(10),@CONSIDER_SIZE_IN_PICKLIST VARCHAR(10)
	     
	     
	     SELECT TOP 1 @CONSIDER_COLOR_IN_PICKLIST=value  FROM CONFIG WHERE config_option ='CONSIDER_COLOR_IN_PICKLIST'
	     SELECT TOP 1 @CONSIDER_SIZE_IN_PICKLIST=value  FROM CONFIG WHERE config_option ='CONSIDER_SIZE_IN_PICKLIST'
	     
	     IF @CONSIDER_COLOR_IN_PICKLIST IS NULL
	     SET @CONSIDER_COLOR_IN_PICKLIST=''
	     
	     IF @CONSIDER_SIZE_IN_PICKLIST IS NULL
	     SET @CONSIDER_SIZE_IN_PICKLIST=''
	     
                SELECT LM.AC_NAME,A.ORDER_NO ,CONVERT (VARCHAR, A.ORDER_DT,105) AS ORDER_DT,
                       A.ORD_QTY - ISNULL(B.TRF_QTY,0) AS OTHER_PEND_QTY
                      
                FROM
                (
                 SELECT B.AC_CODE , A.article_code ,B.ORDER_ID,B.ORDER_NO,B.ORDER_DT,
                 CASE WHEN @CONSIDER_COLOR_IN_PICKLIST='1' THEN A.PARA1_CODE ELSE '0000000' END AS PARA1_CODE,
		         CASE WHEN @CONSIDER_SIZE_IN_PICKLIST='1' THEN  A.PARA2_CODE ELSE '0000000' END AS PARA2_CODE, 
		         SUM(A.quantity ) AS ORD_QTY
                 FROM BUYER_ORDER_DET A (NOLOCK)
                 JOIN BUYER_ORDER_MST B (NOLOCK) ON A.order_id =B.order_id 
                 WHERE B.CANCELLED =0
                 AND (@CLOCID='' OR ISNULL(B.WBO_FOR_DEPT_ID,B.location_Code )=@CLOCID)
                 AND  A.ORDER_ID<>@CORDER_ID
                 AND A.ARTICLE_CODE= @CARTICLE_CODE
                 AND  CASE WHEN @CONSIDER_COLOR_IN_PICKLIST='1' THEN A.PARA1_CODE ELSE '0000000' END=@CPARA1_CODE
                 AND CASE WHEN @CONSIDER_SIZE_IN_PICKLIST='1' THEN  A.PARA2_CODE ELSE '0000000' END=@CPARA2_CODE
                 GROUP BY B.AC_CODE ,A.article_code,B.ORDER_ID,B.ORDER_NO,B.ORDER_DT,
                 CASE WHEN @CONSIDER_COLOR_IN_PICKLIST='1' THEN A.PARA1_CODE ELSE '0000000' END,
                 CASE WHEN @CONSIDER_SIZE_IN_PICKLIST='1' THEN  A.PARA2_CODE ELSE '0000000' END
                 ) A
                 LEFT JOIN
                 (
                   
                 SELECT B.ORDER_ID,
                 SKU.article_code ,
                 CASE WHEN @CONSIDER_COLOR_IN_PICKLIST='1' THEN SKU.PARA1_CODE ELSE '0000000' END AS PARA1_CODE,
		         CASE WHEN @CONSIDER_SIZE_IN_PICKLIST='1' THEN  SKU.PARA2_CODE ELSE '0000000' END AS PARA2_CODE, 
		         SUM(A.quantity ) AS TRF_QTY
                 FROM FLOOR_ST_DET  A (NOLOCK)
                 JOIN FLOOR_ST_MST B (NOLOCK) ON A.MEMO_ID  =B.MEMO_ID 
                 JOIN SKU (NOLOCK) ON A.PRODUCT_CODE =SKU.product_code 
                 WHERE B.CANCELLED =0
                 AND  B.ORDER_ID<>@CORDER_ID 
                 AND SKU.ARTICLE_CODE= @CARTICLE_CODE
                 AND  CASE WHEN @CONSIDER_COLOR_IN_PICKLIST='1' THEN SKU.PARA1_CODE ELSE '0000000' END=@CPARA1_CODE
                 AND CASE WHEN @CONSIDER_SIZE_IN_PICKLIST='1' THEN  SKU.PARA2_CODE ELSE '0000000' END=@CPARA2_CODE
                 AND ISNULL(B.ORDER_ID,'')<>''
                 GROUP BY B.ORDER_ID,SKU.article_code,
                 CASE WHEN @CONSIDER_COLOR_IN_PICKLIST='1' THEN SKU.PARA1_CODE ELSE '0000000' END,
                 CASE WHEN @CONSIDER_SIZE_IN_PICKLIST='1' THEN  SKU.PARA2_CODE ELSE '0000000' END
                 ) B  ON A.article_code =B.article_code AND A.PARA1_CODE =B.PARA1_CODE 
                 AND A.PARA2_CODE =B.PARA2_CODE AND A.order_id =B.ORDER_ID 
                 JOIN ARTICLE ART (NOLOCK) ON ART.article_code =A.article_code 
                 JOIN para1 P1 (NOLOCK) ON P1.para1_code =A.PARA1_CODE 
                 JOIN para2 P2 (NOLOCK) ON P2.para2_code =A.PARA2_CODE 
                 JOIN LM01106 LM (NOLOCK) ON LM.AC_CODE=A.AC_CODE
                 ORDER BY LM.AC_NAME,A.ORDER_DT,A.ORDER_NO 


END
