CREATE PROCEDURE SP_GETCUSTLOYALTY
@CCUSTCODE VARCHAR(50)
--WITH ENCRYPTION
AS
BEGIN
	DECLARE @VCHCMDATE VARCHAR(25)
	SELECT @VCHCMDATE = CONVERT(VARCHAR,A.CM_DT,103) FROM CMM01106 A JOIN CUSTDYM B ON A.CUSTOMER_CODE = B.CUSTOMER_CODE
	WHERE A.CUSTOMER_CODE = @CCUSTCODE
	
	SELECT @VCHCMDATE AS LAST_VISIT_ON,CONVERT(VARCHAR,A.DT_BIRTH,103) AS DT_BIRTH,
	CONVERT(VARCHAR,A.DT_ANNIVERSARY,103) AS DT_ANNIVERSARY,
	CONVERT(VARCHAR,A.WIZCLIP_LAST_UPDATE,103) AS LAST_SYNC_DT,B.TOTAL_POINTS,B.TOTAL_PURCHASES ,B.CARD_STATUS 
	FROM CUSTDYM A JOIN WIZCLIP_CUSTDYM_POINTS B ON A.CUSTOMER_CODE = B.CUSTOMER_CODE
	WHERE (A.CUSTOMER_CODE = @CCUSTCODE OR A.MOBILE =  @CCUSTCODE OR A.USER_CUSTOMER_CODE = @CCUSTCODE)
END
