CREATE PROCEDURE DBSALE_KPI_PAYMENT_BY_JOURNAL 
@USER_CODE VARCHAR(7)='',
@LOC VARCHAR(MAX)='',
@DT VARCHAR(10)=''
as
begin
	DECLARE @FILTER VARCHAR(MAX),@PAYTYPE VARCHAR(1000),@SELECT_PAYTYPE VARCHAR(MAX),@DFROMDATE DATETIME,
	@DLASTDATE datetime,@DTSQL NVARCHAR(MAX)
	
	CREATE TABLE #DBSALE_KPI_PAYMENT_BY_JOURNAL (Date varchar(1000),PAY_TYPE VARCHAR(MAX))
	set @DFROMDATE='2020-03-01'
	set @USER_CODE='0000000'

	CREATE TABLE #TempPayType(DEPT_ID VARCHAR(10),[Date] DATE,PAYTYPE VARCHAR(100),SALE BIGINT)
	CREATE TABLE #TmpPayMode(ID INT IDENTITY(1,1),PAYMODE_GRP_CODE CHAR(7), PAYMODE_GRP_NAME VARCHAR(30))  
	
	SET @FILTER=ISNULL(@FILTER,'')  
	
	DELETE #TmpPayMode

	INSERT INTO #TmpPayMode (PAYMODE_GRP_CODE, PAYMODE_GRP_NAME)  
	SELECT PAYMODE_GRP_CODE, PAYMODE_GRP_NAME FROM PAYMODE_GRP_MST ORDER BY LEFT(PAYMODE_GRP_NAME,2)  
	DELETE #TmpPayMode WHERE PAYMODE_GRP_CODE NOT IN ('0000001','0000002')   

	DELETE #TempPayType

	
		SET @DLASTDATE=CONVERT(DATE,DATEADD(DD,-1,DATEADD(MM,1,@DFROMDATE)))  
		SET @DTSQL=N'SELECT a.location_code,CM_DT,PM.PAYMODE_GRP_NAME+''_''+PM.COLOUR4+''_''+PM.COLOUR1 AS PAYMODE_GRP_CODE  
		,ROUND(SUM(P.AMOUNT),0)  
		FROM CMM01106 A (NOLOCK)   
		JOIN PAYMODE_XN_DET P (NOLOCK) ON A.CM_ID=P.MEMO_ID AND P.XN_TYPE=''SLS''  
		JOIN PAYMODE_MST M (NOLOCK) ON M.PAYMODE_CODE=P.PAYMODE_CODE  
		JOIN (SELECT T1.PAYMODE_GRP_CODE, T1.PAYMODE_GRP_NAME, C1.COLOUR1, C1.COLOUR4  
			  FROM #TmpPayMode T1   
			  JOIN COLOUR_PALLETE C1 ON T1.ID = C1.ID  
			 )PM ON M.PAYMODE_GRP_CODE = PM.PAYMODE_GRP_CODE  
		JOIN VW_LOC_ADDRESS LA ON LA.DEPT_ID=a.location_code 
		WHERE cm_dt between '''+convert(varchar,@DFROMDATE,110)+''' and '''+convert(varchar,@Dlastdate,110)+'''
		GROUP BY a.location_code,CM_DT,PM.PAYMODE_GRP_NAME,PM.COLOUR4,PM.COLOUR1'  
		PRINT @DTSQL  
		INSERT #TempPayType EXEC SP_EXECUTESQL @DTSQL  
	
	--PIVOT THE DATA  
	SET @PAYTYPE=''
	SELECT @PAYTYPE=COALESCE(@PAYTYPE,'')+' ALTER TABLE #DBSALE_KPI_PAYMENT_BY_JOURNAL ADD ['+PAYTYPE+'] FLOAT;'
	FROM (SELECT DISTINCT PAYTYPE FROM #TempPayType)P
	EXEC(@PAYTYPE)

	SET @PAYTYPE=''
	SELECT @PAYTYPE=COALESCE(@PAYTYPE,'')+'['+PAYTYPE+'],'   
	,@SELECT_PAYTYPE=COALESCE(@SELECT_PAYTYPE,'')+'CONVERT(VARCHAR,ISNULL(['+PAYTYPE+'],0))+''.00'' AS ['+PAYTYPE+'],'  
	FROM (SELECT DISTINCT PAYTYPE FROM #TempPayType)T  

	IF RIGHT(ISNULL(@PAYTYPE,''),1)=','  
		SET @PAYTYPE=LEFT(@PAYTYPE,LEN(@PAYTYPE)-1)  
	IF RIGHT(ISNULL(@SELECT_PAYTYPE,''),1)=','  
		SET @SELECT_PAYTYPE=LEFT(@SELECT_PAYTYPE,LEN(@SELECT_PAYTYPE)-1)  

	WHILE @DFROMDATE<=@DLASTDATE  
	BEGIN  
	  IF NOT EXISTS(SELECT * FROM #TempPayType WHERE CONVERT(DATE,[DATE])=CONVERT(DATE,@DFROMDATE))  
		 INSERT #TempPayType 
		 SELECT DISTINCT DEPT_ID,CONVERT(DATE,@DFROMDATE),PAYMODE_GRP_NAME,0 FROM #TmpPayMode,LOCATION
	  SET @DFROMDATE=DATEADD(DD,1,CONVERT(DATE,@DFROMDATE))  
	END  

	SET @DTSQL='INSERT #DBSALE_KPI_PAYMENT_BY_JOURNAL(Date,pay_type,'+@PAYTYPE+')
	SELECT date, '''+LEFT(@PAYTYPE,LEN(@PAYTYPE)-0)+''','+@SELECT_PAYTYPE+'   
	FROM (SELECT [Date],PAYTYPE,SALE FROM #TempPayType)SRC  
	PIVOT (SUM(SALE)FOR PAYTYPE IN ('+@PAYTYPE+'))PVT'  
	PRINT @DTSQL  
	EXEC SP_EXECUTESQL @DTSQL       

	SELECT  * from #DBSALE_KPI_PAYMENT_BY_JOURNAL
END
