create PROCEDURE SP3S_CAPTURE_AUDIT_TRAIL_HSN
(
 @XN_TYPE VARCHAR(10)
,@XN_ID VARCHAR(1000)
,@XN_HDR_TEMP_TABLE VARCHAR(1000)
,@XN_DTL_TEMP_TABLE VARCHAR(1000)
,@XN_SP_ID VARCHAR(40)=''
,@COMPUTER_NAME VARCHAR(1000)
,@WINUSERNAME VARCHAR(1000)
,@CWIZUSERCODE VARCHAR(1000)
,@CANCEL INT=0 
,@XN_CM_DT DATETIME='1900-01-01'
,@EDIT_CLICKED BIT=0
)
AS
BEGIN
  SET NOCOUNT ON

  DECLARE @CWIZUSERNAME VARCHAR(1000)
  
  IF @XN_TYPE NOT IN ('HSN')
     RETURN 
  

		   	  
     
  DECLARE @SQL VARCHAR(MAX),@SQL2 VARCHAR(MAX),@COL VARCHAR(MAX)
  ,@HDR_TABLE VARCHAR(5000),@DTL_TABLE VARCHAR(5000)
  ,@HDR_KEY VARCHAR(5000),@DTL_KEY VARCHAR(5000)
  ,@ROWID VARCHAR(1000),@MODE VARCHAR(100),@CNT_NEW INT,@CNT_OLD INT
  ,@JOIN_ON VARCHAR(MAX),@FIELDS VARCHAR(1000),@KEY_ID VARCHAR(1000)
  ,@INS_TABLE VARCHAR(1000),@DEL_TABLE VARCHAR(1000),@TABLE VARCHAR(1000)  
  ,@FIELD VARCHAR(500),@DATA VARCHAR(500),@FIELD_LIST VARCHAR(MAX)
  ,@PROCESS_HDR BIT,@UPDATED_ON DATETIME
  ,@TAB VARCHAR(500),@AGE VARCHAR(500),@EDITED BIT
  
  SET @EDITED=0
  
    IF @XN_TYPE='HSN'
     SELECT @HDR_TABLE='HSN_MST' ,@DTL_TABLE='HSN_DET' ,@XN_HDR_TEMP_TABLE='[##HSM_'+CAST(@XN_SP_ID AS VARCHAR(40))+'_'+@XN_ID+']',@XN_DTL_TEMP_TABLE='[##HSN_'+CAST(@XN_SP_ID AS VARCHAR(40))+'_'+@XN_ID+']',@JOIN_ON='HSN_CODE'
  
  SET @ROWID=LEFT(NEWID(),40)
  
  SELECT @CWIZUSERNAME=ISNULL(U.USERNAME,'') FROM USERS U WHERE U.USER_CODE=@CWIZUSERCODE
  set @CWIZUSERNAME=isnull(@CWIZUSERNAME,'')
  
  SET @UPDATED_ON=GETDATE()
  
 
  IF ISNULL(@EDIT_CLICKED,0)=0
     RETURN

  SET @SQL='UPDATE T SET '
  SELECT @SQL=COALESCE(@SQL,'')+'T.NEW_'+FIELD_NAME+' = I.'+FIELD_NAME+',' FROM XN_AUDIT_TRIAL_MST (NOLOCK) WHERE TABLE_NAME=@HDR_TABLE AND TRIG='UPDATE' ORDER BY ORDER_ID
  SET @SQL=LEFT(@SQL,LEN(@SQL)-1)+' FROM [##'+'HSM'+'_'+CAST(@XN_SP_ID AS VARCHAR(40))+'_'+@XN_ID+'] T JOIN '+@HDR_TABLE+' I (NOLOCK) ON I.'+@JOIN_ON+'='''+@XN_ID+''';'
  print @sql	
  EXEC(@SQL)


 

  SET @SQL=''
  --CAPTURE HDR
  SELECT @SQL=COALESCE(@SQL,'')+'INSERT XN_AUDIT_TRIAL_DET (XN_ID,XN_TYPE, TABLE_NAME, KEY_VALUE, FIELD_NAME, DATA_TYPE, TXN_MODE, ID, OLDVAL, NEWVAL, AUDITED_ON, COMPUTER_NAME, WINUSERNAME, CWIZUSERCODE, CWIZUSERNAME, PRODUCT_CODE)
  SELECT '''+@XN_ID+''','''+@XN_TYPE+''', '''+@HDR_TABLE+''', OLD_'+LEFT(KEY_FIELDS,LEN(KEY_FIELDS)-1)+', '''+FIELD_NAME+''', '''+DATA_TYPE+''', '''+TRIG+''', '''+@ROWID+''', OLD_'+FIELD_NAME+' , NEW_'+FIELD_NAME+' , '''+CONVERT(VARCHAR,@UPDATED_ON,113)+''', '''+@COMPUTER_NAME+''', '''+@WINUSERNAME+''', '''+@CWIZUSERCODE+''', '''+@CWIZUSERNAME+''',''''
  FROM [##'+'HSM'+'_'+CAST(@XN_SP_ID AS VARCHAR(40))+'_'+@XN_ID+'] 
  WHERE NEW_'+FIELD_NAME+'<>OLD_'+FIELD_NAME+';'
  FROM XN_AUDIT_TRIAL_MST (NOLOCK) 
  WHERE TABLE_NAME=@HDR_TABLE AND TRIG='UPDATE'
  print @sql
  EXEC(@SQL)
 
 

  SET @SQL=''
  SET @SQL='UPDATE T SET '
  SELECT @SQL=COALESCE(@SQL,'')+'T.NEW_'+FIELD_NAME+' = ISNULL(I.'+FIELD_NAME+','+CASE WHEN DATA_TYPE in('DATETIME','varchar')  THEN '''''' WHEN DATA_TYPE in('bit','numeric') then '''0''' ELSE '''-999''' END+' ),' FROM XN_AUDIT_TRIAL_MST (NOLOCK) WHERE TABLE_NAME=@DTL_TABLE AND TRIG='UPDATE' ORDER BY ORDER_ID
  SET @SQL=LEFT(@SQL,LEN(@SQL)-1)+' FROM [##'+LEFT(@DTL_TABLE,3) +'_'+CAST(@XN_SP_ID AS VARCHAR(40))+'_'+@XN_ID+'] T LEFT JOIN '+@DTL_TABLE+' I (NOLOCK) ON I.'+@JOIN_ON+'='''+@XN_ID
  +''' AND I.ROW_ID=T.ROW_ID;'  

  print @sql
  EXEC(@SQL)
  
   
   SET @SQL2='' 

 
	 SELECT @SQL2=COALESCE(@SQL2,'')
	 +'INSERT XN_AUDIT_TRIAL_DET (XN_ID,XN_TYPE, TABLE_NAME, KEY_VALUE, FIELD_NAME, DATA_TYPE, TXN_MODE, ID, OLDVAL, NEWVAL, AUDITED_ON, COMPUTER_NAME, WINUSERNAME, CWIZUSERCODE, CWIZUSERNAME, PRODUCT_CODE)'+CHAR(13)
	 +'SELECT '''+@XN_ID+''','''+@XN_TYPE+''','''+@DTL_TABLE+''', OLD_'+REPLACE(LEFT(KEY_FIELDS,LEN(KEY_FIELDS)-1),'+','+OLD_')+', '''+FIELD_NAME+''', '''+DATA_TYPE+''', '''+TRIG+''', '''+@ROWID+''', OLD_'+FIELD_NAME+' , ISNULL(NEW_'+FIELD_NAME+',''DELETED'') , '''+CONVERT(VARCHAR,@UPDATED_ON,113)+''', '''+@COMPUTER_NAME+''', '''+@WINUSERNAME+''', '''+@CWIZUSERCODE+''', '''+@CWIZUSERNAME+''',OLD_HSN_CODE
	 FROM [##'+ LEFT(@DTL_TABLE,3) +'_'+CAST(@XN_SP_ID AS VARCHAR(40))+'_'+@XN_ID+']'
	 +' WHERE OLD_'+FIELD_NAME+'<>NEW_'+FIELD_NAME+' ;'
	 FROM XN_AUDIT_TRIAL_MST (NOLOCK) 
	 WHERE TABLE_NAME=@DTL_TABLE AND TRIG='UPDATE' and KEY_FIELDS <>''
	print @SQL2
    EXEC(@SQL2)

  
  SET NOCOUNT OFF
END

