
CREATE PROCEDURE SP3S_EXPOT_BOM
AS
BEGIN

     SELECT ART.ARTICLE_NO ,
            ISNULL(JOBS.JOB_NAME,'') AS JOB_NAME,
            ART1.ARTICLE_NO AS BOM_ARTICLE_NO,
            A.AVG_QTY,A.RATE,P1.PARA1_NAME AS BOM_PARA1_NAME,
            P2.PARA2_NAME AS BOM_PARA2_NAME,
            A.ADD_AVG_QTY,
          ISNULL(A.TOL_PER,0) AS TOL_PER,
          A.ARTICLE_CODE ,A.BOM_ARTICLE_CODE ,A.BOM_PARA1_CODE ,A.BOM_PARA2_CODE,
          ISNULL(A.JOB_CODE,'0000000') AS JOB_CODE,
          A.ROW_ID 
     FROM ARTICLE ART
     LEFT JOIN ART_BOM A (NOLOCK) ON A.ARTICLE_CODE =ART.ARTICLE_CODE 
     JOIN ARTICLE ART1 (NOLOCK) ON A.BOM_ARTICLE_CODE =ART1.ARTICLE_CODE 
     LEFT JOIN PARA1 P1 (NOLOCK) ON A.BOM_PARA1_CODE=P1.PARA1_CODE
     LEFT JOIN PARA2 P2 (NOLOCK) ON A.BOM_PARA2_CODE=P2.PARA2_CODE
     LEFT JOIN JOBS (NOLOCK) ON JOBS.JOB_CODE =A.JOB_CODE 
     ORDER BY ART.ARTICLE_NO ,ART1.ARTICLE_NO

END

