CREATE PROCEDURE SP_PRD_PYMTDETAILS      
(      
 @NQUERYID NUMERIC(1)=1,      
 @CXNTYPE VARCHAR(40)='',      
 @CMEMOID VARCHAR(50)='',  
 @CWHERE VARCHAR(1000)=''      
)
--WITH ENCRYPTION 
AS     
BEGIN      
 IF @NQUERYID=1       
  SELECT A.*,B.PAYMODE_NAME,C.* ,CAST(0 AS BIT ) AS DELETED,      
  (CASE WHEN A.CURRENCY_CONVERSION_RATE> 0 THEN     
  CAST(A.AMOUNT/A.CURRENCY_CONVERSION_RATE AS NUMERIC(10,2)) ELSE A.AMOUNT END ) AS BASIC_AMOUNT,
  ISNULL(S.CM_DT,ISNULL(R.ADV_REC_DT,'')) AS ADJ_MEMO_DT    
  FROM PRD_PAYMODE_XN_DET A  (NOLOCK)   
  JOIN PAYMODE_MST B (NOLOCK) ON B.PAYMODE_CODE=A.PAYMODE_CODE      
  JOIN PAYMODE_GRP_MST C (NOLOCK) ON C.PAYMODE_GRP_CODE=B.PAYMODE_GRP_CODE      
  LEFT OUTER JOIN CMM01106 S (NOLOCK) ON S.CM_ID=A.ADJ_MEMO_ID AND SUBSTRING(S.CM_NO,5,1)='N'
  LEFT OUTER JOIN ARC01106 R (NOLOCK) ON R.ADV_REC_ID=A.ADJ_MEMO_ID AND R.ARC_TYPE=2  
  WHERE A.XN_TYPE =@CXNTYPE AND A.MEMO_ID=@CMEMOID       
   
 ELSE IF @NQUERYID=2  
 BEGIN  
	IF @CWHERE=''  
	  SELECT A.PAYMODE_CODE,A.PAYMODE_NAME ,B.*,A.CURRENCY_CONVERSION_RATE      
	  FROM PAYMODE_MST A  (NOLOCK)    
	  JOIN PAYMODE_GRP_MST B (NOLOCK) ON B.PAYMODE_GRP_CODE=A.PAYMODE_GRP_CODE      
	  WHERE INACTIVE=0 AND PAYMODE_NAME<>'' AND ( @CXNTYPE='' OR PAYMODE_CODE <> 'GVC0001' )    
	  ORDER BY A.PAYMODE_GRP_CODE,A.PAYMODE_NAME
	ELSE
		BEGIN
			DECLARE @CCMD NVARCHAR(4000)
			SET @CCMD=N' SELECT A.PAYMODE_CODE,A.PAYMODE_NAME ,B.*,A.CURRENCY_CONVERSION_RATE      
			  FROM PAYMODE_MST A  (NOLOCK)    
			  JOIN PAYMODE_GRP_MST B (NOLOCK) ON B.PAYMODE_GRP_CODE=A.PAYMODE_GRP_CODE      
			  WHERE INACTIVE=0 AND PAYMODE_NAME<>''''   AND A.PAYMODE_GRP_CODE IN (' + @CWHERE +')    
			  ORDER BY A.PAYMODE_GRP_CODE,A.PAYMODE_NAME' 
			EXEC SP_EXECUTESQL @CCMD
		END
 END
 ELSE IF @NQUERYID=3      
  
    EXEC SP_WL_PENDINGCN @CXNTYPE,@CMEMOID   
 ELSE IF @NQUERYID=4      
	SELECT *,CONVERT(BIT,0) AS [GV_SOLD] FROM GV_GEN_DET A
	JOIN GV_GEN_MST B ON B.MEMO_ID=A.MEMO_ID
	WHERE 1=2
END
