CREATE PROCEDURE SP_PRD_JOBWORK_DYING_REPORT
(
 @DFM_DT DATETIME='',
 @DTO_DT DATETIME='',
 @CAGENCY_CODE VARCHAR(100)='',
 @NPENDING INT=0
)
AS
BEGIN
	DECLARE @SQLQUERY NVARCHAR(MAX)=''
	DECLARE @AC_CODE VARCHAR(100)  
	IF @CAGENCY_CODE=''  
     BEGIN  
		SET @AC_CODE=''  
		SET @CAGENCY_CODE='IN('''')'  
     END  
     ELSE   
     BEGIN  
		SET @AC_CODE='LATER'  
     END  
     
     IF OBJECT_ID ('TEMPDB..#TMPISSUE','U') IS NOT NULL
        DROP TABLE #TMPISSUE
        
     SELECT C.AGENCY_NAME,A.ISSUE_ID, A.ISSUE_NO ,A.ISSUE_DT,SUM(B.QUANTITY) AS ISSUE_QUANTITY
     INTO #TMPISSUE
     FROM PRD_JOBWORK_ISSUE_MST (NOLOCK) A
     JOIN PRD_JOBWORK_ISSUE_DET (NOLOCK) B ON A.ISSUE_ID =B.ISSUE_ID 
     JOIN PRD_AGENCY_MST (NOLOCK) C ON A.AGENCY_CODE =C.AGENCY_CODE
     WHERE (@CAGENCY_CODE='' OR C.AGENCY_CODE=@CAGENCY_CODE)
     AND A.ISSUE_DT BETWEEN @DFM_DT AND @DTO_DT
     AND A.CANCELLED =0
     AND 1=2
     GROUP BY A.ISSUE_ID,C.AGENCY_NAME,A.ISSUE_NO ,A.ISSUE_DT
     
     SET @SQLQUERY=N'SELECT C.AGENCY_NAME,A.ISSUE_ID, A.ISSUE_NO ,A.ISSUE_DT,SUM(B.QUANTITY) AS ISSUE_QUANTITY
     FROM PRD_JOBWORK_ISSUE_MST (NOLOCK) A
     JOIN PRD_JOBWORK_ISSUE_DET (NOLOCK) B ON A.ISSUE_ID =B.ISSUE_ID 
     JOIN PRD_AGENCY_MST (NOLOCK) C ON A.AGENCY_CODE =C.AGENCY_CODE
     WHERE ('''+@AC_CODE+'''='''' OR C.AGENCY_CODE '+@CAGENCY_CODE+' )  
     AND A.ISSUE_DT BETWEEN '''+CONVERT(VARCHAR(10),@DFM_DT,120)+''' AND '''+CONVERT(VARCHAR(10),@DTO_DT,120)+'''
     AND A.CANCELLED =0
     GROUP BY A.ISSUE_ID,C.AGENCY_NAME,A.ISSUE_NO ,A.ISSUE_DT'
	 
	 PRINT @SQLQUERY
	 INSERT INTO #TMPISSUE
     EXEC SP_EXECUTESQL @SQLQUERY
        -- 
      IF OBJECT_ID ('TEMPDB..#TMPREC','U') IS NOT NULL
        DROP TABLE #TMPREC
     SELECT A.ISSUE_ID,
     D.RECEIPT_NO,D.RECEIPT_DT,SUM(ISNULL(D.QUANTITY,0)) AS REC_QUANTITY,NET_AMOUNT
     INTO #TMPREC
     FROM PRD_JOBWORK_ISSUE_MST (NOLOCK) A
     JOIN PRD_JOBWORK_ISSUE_DET (NOLOCK) B ON A.ISSUE_ID =B.ISSUE_ID 
     JOIN
     (
      SELECT B.RECEIPT_NO,B.RECEIPT_DT, REF_ROW_ID ,NET_AMOUNT,SUM(QUANTITY) AS QUANTITY
      FROM PRD_JOBWORK_RECEIPT_DET A
      JOIN PRD_JOBWORK_RECEIPT_MST B ON A.RECEIPT_ID=B.RECEIPT_ID
      WHERE B.CANCELLED=0
      GROUP BY B.RECEIPT_NO,B.RECEIPT_DT,REF_ROW_ID,NET_AMOUNT
     ) D ON B.ROW_ID=D.REF_ROW_ID
     WHERE A.CANCELLED =0
     AND 1=2
     GROUP BY A.ISSUE_ID,D.RECEIPT_NO,D.RECEIPT_DT,NET_AMOUNT
    
    SET @SQLQUERY= N'SELECT A.ISSUE_ID,
     D.RECEIPT_NO,D.RECEIPT_DT,SUM(ISNULL(D.QUANTITY,0)) AS REC_QUANTITY,NET_AMOUNT
     FROM PRD_JOBWORK_ISSUE_MST (NOLOCK) A
     JOIN PRD_JOBWORK_ISSUE_DET (NOLOCK) B ON A.ISSUE_ID =B.ISSUE_ID 
     JOIN
     (
      SELECT B.RECEIPT_NO,B.RECEIPT_DT, REF_ROW_ID ,NET_AMOUNT,SUM(QUANTITY) AS QUANTITY
      ,B.AGENCY_CODE,B.AC_CODE
      FROM PRD_JOBWORK_RECEIPT_DET A
      JOIN PRD_JOBWORK_RECEIPT_MST B ON A.RECEIPT_ID=B.RECEIPT_ID
      WHERE B.CANCELLED=0
      GROUP BY B.RECEIPT_NO,B.RECEIPT_DT,REF_ROW_ID,NET_AMOUNT,B.AGENCY_CODE,B.AC_CODE
     ) D ON B.ROW_ID=D.REF_ROW_ID
     WHERE A.CANCELLED =0
     AND ('''+@AC_CODE+'''='''' OR D.AGENCY_CODE '+@CAGENCY_CODE+' )  
     GROUP BY A.ISSUE_ID,D.RECEIPT_NO,D.RECEIPT_DT,NET_AMOUNT'
     
     PRINT @SQLQUERY
     INSERT INTO #TMPREC
     EXEC SP_EXECUTESQL  @SQLQUERY
    ----ONLY
    
    
      IF OBJECT_ID ('TEMPDB..#TMPPENDING','U') IS NOT NULL
        DROP TABLE #TMPPENDING
    
     SELECT A.AGENCY_NAME,A.ISSUE_ID,A.ISSUE_NO,A.ISSUE_DT,
            A.ISSUE_QUANTITY
            ,B.RECEIPT_NO,
             B.RECEIPT_DT,
             B.REC_QUANTITY ,
             B.NET_AMOUNT
             ,SR=ROW_NUMBER() OVER (PARTITION BY A.ISSUE_ID ORDER BY A.ISSUE_ID)
             ,CAST(0 AS NUMERIC(12,2)) AS TOTAL_PENDING
     INTO #TMPPENDING
     FROM #TMPISSUE A
     LEFT OUTER JOIN #TMPREC B ON A.ISSUE_ID=B.ISSUE_ID 
    
    
   UPDATE A SET TOTAL_PENDING =A.ISSUE_QUANTITY-ISNULL(B.REC_QUANTITY,0)
    FROM #TMPPENDING A
    JOIN
    (
     SELECT ISSUE_ID,SUM(REC_QUANTITY) AS REC_QUANTITY
     FROM #TMPPENDING
     GROUP BY ISSUE_ID
    ) B ON A.ISSUE_ID=B.ISSUE_ID
    WHERE A.SR=1
    
    
    
    SELECT A.AGENCY_NAME,
           A.ISSUE_ID,
           A.ISSUE_NO,
           A.ISSUE_DT,
           CASE WHEN A.SR=1 THEN A.ISSUE_QUANTITY ELSE 0 END AS ISSUE_QTY,
           ISNULL(A.RECEIPT_NO,'') AS RECEIPT_NO ,
           ISNULL(A.RECEIPT_DT,'') AS RECEIPT_DT,
           ISNULL(A.REC_QUANTITY,0) AS REC_QTY,
           ISNULL(A.NET_AMOUNT,0) AS NET_AMOUNT,
           SUM(ISNULL(B.REC_QUANTITY,0)) AS TOTAL_REC_QTY,
           A.ISSUE_QUANTITY-SUM(ISNULL(B.REC_QUANTITY,0)) AS PENDING_QTY,
           A.TOTAL_PENDING
    FROM #TMPPENDING A
    JOIN #TMPPENDING B ON A.ISSUE_ID =B.ISSUE_ID AND B.SR <=A.SR
    WHERE (@NPENDING=0 OR A.TOTAL_PENDING>0) 
    GROUP BY A.SR,A.AGENCY_NAME,
           A.ISSUE_ID,
           A.ISSUE_NO,
           A.ISSUE_DT,
           A.ISSUE_QUANTITY,
           A.RECEIPT_NO ,
           A.RECEIPT_DT,
           A.REC_QUANTITY,
           A.NET_AMOUNT,
           A.TOTAL_PENDING
    ORDER BY AGENCY_NAME,A.ISSUE_DT,A.ISSUE_NO,SUM(B.REC_QUANTITY)
    
    
END
