CREATE PROCEDURE VALIDATEXN_MIRROR_PBG  
 @CLOCID VARCHAR(10),
 @CXNID VARCHAR(50),   
 @CMERGEDB VARCHAR(200),
 @CERRORMSG VARCHAR(MAX) OUTPUT  
-- WITH ENCRYPTION
AS  
BEGIN  
/* 
VALIDATEXN_MIRROR_PBG_V208_01_FEB_14 : THIS PROCEDURE WILL VALIDATE ALL THE MIRROR TRANSFERRED DATA FOR
PURCHASE ORDER.
*/
DECLARE	@NCALCDISCOUNTAMT NUMERIC(14,2),@NDISCOUNTAMT NUMERIC(14,2),@DTSQL NVARCHAR(MAX),@NSUBTOTAL NUMERIC(14,2)
		,@NSUMINDNET NUMERIC(14,2),@CSTEP VARCHAR(5),@CCHK_TABLE VARCHAR(50),@NPAYMODECRAMT NUMERIC(10,2)
		,@NPAYMODETOTAMT NUMERIC(10,2),@NTOTAMOUNT NUMERIC(14,2)   
	 
	 SET @CSTEP=00
	 SET @CERRORMSG=''
	 
	 SET @CSTEP=10
	 IF OBJECT_ID('TEMPDB..#PBMTABLE','U') IS NOT NULL 
		DROP TABLE #PBMTABLE	 
	 
	 SET @CSTEP=20
	 IF OBJECT_ID('TEMPDB..#PBDTABLE','U') IS NOT NULL 
		DROP TABLE #PBDTABLE
	 
	 SET @CSTEP=40
	 
	 CREATE TABLE #PBMTABLE(MEMO_ID VARCHAR(22),DISCOUNT_PERCENTAGE NUMERIC (7,3),
			 DISCOUNT_AMOUNT NUMERIC (10,2),TOTAL_AMOUNT NUMERIC (10,2), ROUND_OFF NUMERIC (10,2), 
			 MEMO_NO CHAR(15),SUBTOTAL NUMERIC(18,4), FIN_YEAR VARCHAR(10),
			 BILL_DT DATETIME,USER_CODE CHAR(7),AC_CODE CHAR(10),MANUAL_DISCOUNT BIT )  
			 
	 SET @CSTEP=50		 
	 CREATE TABLE #PBDTABLE (MEMO_ID VARCHAR(22),PRODUCT_CODE VARCHAR(50),QUANTITY NUMERIC(10,3)
							,PURCHASE_PRICE NUMERIC (14,4),DISCOUNT_PERCENTAGE NUMERIC(6,2)
			  ,DISCOUNT_AMOUNT NUMERIC (14,4),TAX_PERCENTAGE NUMERIC(6,2),TAX_AMOUNT NUMERIC(12,4),MANUAL_DISCOUNT BIT )  
	 SET @CSTEP=60
	 
BEGIN TRY	 
	 SET @CSTEP=70	     
	 PRINT 'MASTER RECORDS...'
	 SET @DTSQL=N'SELECT MEMO_ID,DISCOUNT_PERCENTAGE,DISCOUNT_AMOUNT,TOTAL_AMOUNT,ROUND_OFF, 
				 MEMO_NO,SUBTOTAL,FIN_YEAR,BILL_DT,USER_CODE,AC_CODE,MANUAL_DISCOUNT 
				 FROM  '+@CMERGEDB+'PBM01106 (NOLOCK) WHERE MEMO_ID='''+@CXNID+'''' 
	 
	 SET @CSTEP=80	      
	 INSERT #PBMTABLE
	 EXEC SP_EXECUTESQL @DTSQL 
	 SET @CSTEP=90
	 PRINT 'DETAIL RECORDS...'
	 SET @DTSQL=N'SELECT MEMO_ID ,PRODUCT_CODE ,QUANTITY ,PURCHASE_PRICE 
				,DISCOUNT_PERCENTAGE ,DISCOUNT_AMOUNT,TAX_PERCENTAGE,TAX_AMOUNT, MANUAL_DISCOUNT 
				 FROM  '+@CMERGEDB+'PBD01106 (NOLOCK) WHERE MEMO_ID='''+@CXNID+''''  
	 
	 SET @CSTEP=100
	 INSERT #PBDTABLE
	 EXEC SP_EXECUTESQL @DTSQL 
	 
	 SET @CSTEP=130
	 IF ISNULL(@CERRORMSG,'')<>''
		RETURN
		
	 SET @CSTEP=140	
	 PRINT 'VALIDATING LEDGERS...'	
	 IF ISNULL(@CERRORMSG,'')=''
	 BEGIN
		 SET @CSTEP=150	
		 SET @DTSQL=N'IF EXISTS (SELECT TOP 1 ''U'' FROM  '+@CMERGEDB+'PBM01106 A
								LEFT OUTER JOIN  '+@CMERGEDB+'LM01106 B ON A.AC_CODE=B.AC_CODE
								WHERE A.MEMO_ID='''+@CXNID+''' AND B.AC_CODE IS NULL)
						SET @CERRORMSGOUT=''INVALID LEDGER DETAILS FOUND''
					 ELSE
						SET @CERRORMSGOUT='''''	
		 EXEC SP_EXECUTESQL @DTSQL,N'@CERRORMSGOUT VARCHAR(200) OUTPUT',@CERRORMSGOUT=@CERRORMSG OUTPUT
		 IF ISNULL(@CERRORMSG,'')<>''
			RETURN
	 END
	 
	 SET @CSTEP=160
	 SELECT @NSUBTOTAL=SUBTOTAL FROM #PBMTABLE  
	 
	 SET @CSTEP=170
	 SELECT @NSUMINDNET=SUM(PURCHASE_PRICE*QUANTITY) FROM #PBDTABLE
	 
	 SET @CSTEP=180
	 IF ABS(ISNULL(@NSUMINDNET,0)-ISNULL(@NSUBTOTAL,0))>1
	 BEGIN
		SET @CERRORMSG = 'MISMATCH BETWEEN ITEM LEVEL TOTAL AMOUNT & BILL LEVEL SUBTOTAL.....' -- CANNOT SAVE '
		RETURN
	 END	 
END TRY	
BEGIN CATCH
		SET @CERRORMSG = 'P:VALIDATEXN_MIRROR_PBG,STEP: '+@CSTEP+'MESSAGE: '+ERROR_MESSAGE()
		RETURN
END CATCH	
END_PROC:  
END  
--*************************************** END OF PROCEDURE VALIDATEXN_MIRROR_PBG
