

IF NOT EXISTS(SELECT CONFIG_OPTION FROM CONFIG WHERE CONFIG_OPTION='UPDATE_CMM_COPIES_PTD'
			  AND VALUE='1')
BEGIN
	PRINT 'UPDATE COPIES PRINTED MARK IN CASH MEMO TABLE'
	DELETE FROM CONFIG WHERE CONFIG_OPTION='UPDATE_CMM_COPIES_PTD'
	
	UPDATE CMM01106 SET COPIES_PTD=1 WHERE COPIES_PTD=0
	
    INSERT CONFIG (CONFIG_OPTION,VALUE,ROW_ID,LAST_UPDATE)
	VALUES ('UPDATE_CMM_COPIES_PTD','1','',GETDATE())	
END
