CREATE PROCEDURE SP_CONVERT_CMA_NEWAPR
@CCURLOCID VARCHAR(5)=''
--WITH ENCRYPTION
AS
BEGIN

	DECLARE @CUSERCODE CHAR(7),@CFINYEAR VARCHAR(10),@CMEMOID VARCHAR(40),@DAPRDT DATETIME,@NCNT INT,@CDEPTID CHAR(2),
			@CAPRMEMOID VARCHAR(40),@NSTEP INT,@CERRORMSG VARCHAR(MAX),@CMEMONOPREFIX VARCHAR(10),@CMEMONOVAL VARCHAR(10)
		
	
	BEGIN TRY
	
	BEGIN TRANSACTION
		
	DECLARE @TRETMSG TABLE  (ERRMSG VARCHAR(MAX))
	
	SET @NSTEP=10
	
	IF CURSOR_STATUS('GLOBAL','APRCUR') IN (0,1)
	BEGIN
		CLOSE APRCUR
		DEALLOCATE APRCUR
	END	
	
	SET @NCNT=1
	
	IF @CCURLOCID=''
		SELECT TOP 1 @CCURLOCID=DEPT_ID FROM NEW_APP_LOGIN_INFO (nolock) WHERE SPID=@@SPID 
	
	SET @NSTEP=20
	DECLARE APRCUR CURSOR FOR SELECT DISTINCT B.MEMO_ID,APR_DT FROM CMA01106 A 
	JOIN APD01106 B ON A.CMD_ROW_ID=B.ROW_ID
	JOIN APM01106 C ON C.MEMO_ID=B.MEMO_ID
	WHERE LEFT(B.MEMO_ID,2)=@CCURLOCID AND CANCELLED=0
	ORDER BY B.MEMO_ID,APR_DT
	
	OPEN APRCUR
	
	FETCH NEXT FROM APRCUR INTO @CMEMOID,@DAPRDT
	WHILE @@FETCH_STATUS=0
	BEGIN
		SET @NSTEP=30
		SELECT TOP 1 @CDEPTID=DEPT_ID FROM APD01106 WHERE MEMO_ID=@CMEMOID
		SELECT TOP 1 @CUSERCODE=USER_CODE FROM APM01106 WHERE MEMO_ID=@CMEMOID
		
		SET @CFINYEAR='01'+DBO.FN_GETFINYEAR(@DAPRDT)
		SET @CMEMONOPREFIX=LEFT(RIGHT(@CMEMOID,10),4)+'R-'
		
		
		SET @NSTEP=40

		EXEC GETNEXTKEY 'APPROVAL_RETURN_MST','MEMO_NO',10,@CMEMONOPREFIX,1,@CFINYEAR,0,@CMEMONOVAL OUTPUT   
		
		
		PRINT 'INSERTING NEW MEMO NO.:'+@CMEMONOVAL
		
		SET @CAPRMEMOID=LEFT(RIGHT(@CMEMOID,10),2)+@CFINYEAR+@CMEMONOVAL

		SET @NSTEP=50
		INSERT APPROVAL_RETURN_MST	( MEMO_ID, MEMO_NO, MEMO_DT, CUSTOMER_CODE, AC_CODE, MODE, SENT_FOR_RECON, 
		LAST_UPDATE, CANCELLED, USER_CODE, FIN_YEAR, REMARKS, DEPT_ID )  
		SELECT 	@CAPRMEMOID AS MEMO_ID,@CMEMONOVAL AS MEMO_NO,@DAPRDT AS MEMO_DT,CUSTOMER_CODE,AC_CODE,MEMO_TYPE AS MODE,
		0 AS SENT_FOR_RECON,GETDATE() AS LAST_UPDATE,0 AS CANCELLED,@CUSERCODE AS USER_CODE,@CFINYEAR AS FIN_YEAR,
		'CONVERTED ENTRY' AS REMARKS,LEFT(@CMEMONOPREFIX,2) AS DEPT_ID
		FROM APM01106 WHERE MEMO_ID=@CMEMOID
		
		INSERT APPROVAL_RETURN_DET	( MEMO_ID, QUANTITY, ROW_ID, EMP_CODE, REMARKS, APD_ROW_ID, AUTO_SRNO ) 
		SELECT 	@CAPRMEMOID AS MEMO_ID,A.QUANTITY,LEFT(A.ROW_ID,2)+CONVERT(VARCHAR(40),NEWID()) AS ROW_ID,'0000000' AS EMP_CODE,'' AS REMARKS,
		CMD_ROW_ID AS APD_ROW_ID,0 AS AUTO_SRNO FROM CMA01106 A JOIN APD01106 B ON A.CMD_ROW_ID=B.ROW_ID
		WHERE B.MEMO_ID=@CMEMOID AND APR_DT=@DAPRDT

		SET @NCNT=@NCNT+1
		
		FETCH NEXT FROM APRCUR INTO @CMEMOID,@DAPRDT
	END
	
	CLOSE APRCUR
	DEALLOCATE APRCUR
	
	SET @NSTEP=60
	
	END TRY
	
	BEGIN CATCH
		SET @CERRORMSG = 'STEP- ' + LTRIM(STR(@NSTEP)) + ' SQL ERROR: #' + LTRIM(STR(ERROR_NUMBER())) + ' ' + ERROR_MESSAGE()
			
		GOTO END_PROC
	END CATCH
	
END_PROC:
	

	IF @@TRANCOUNT>0  
	BEGIN
		IF ISNULL(@CERRORMSG,'')=''
			COMMIT TRANSACTION  
		 ELSE
			ROLLBACK
	END	
	 
 	INSERT @TRETMSG
	SELECT @CERRORMSG
			
	SELECT * FROM @TRETMSG

	
	
END		
--- 'END OF PROCEDURE SP_CONVERT_CMA_NEWAPR'
