CREATE PROCEDURE SP_CANCELLETION_FILTER
(
    @NINV_MODE INT ,
    @DFROMDATE VARCHAR(10),
    @DTODATE VARCHAR(10),
    @CLOC_ID VARCHAR(10)='',
    @LOC VARCHAR(4)=''
 
)
--WITH ENCRYPTION
AS
BEGIN

  --(dinkar) Replace  left(memoid,2) to Location_code     
      DECLARE @CCMD NVARCHAR(MAX),@CNC_TYPE VARCHAR(1000)
      IF @NINV_MODE=0
      SET @CNC_TYPE=2
       ELSE IF @NINV_MODE=1
      SET @CNC_TYPE='''0'',''1'''
       ELSE
      SET @CNC_TYPE=0
        
	SET @CCMD=N'SELECT ICM.CNC_MEMO_ID, ICM.CNC_MEMO_NO,CONVERT(VARCHAR,ICM.CNC_MEMO_DT,106) AS CNC_MEMO_DT,
		      SUM(ICD.QUANTITY) AS QUANTITY1,
		      ICM.TOTAL_QUANTITY_STR AS TOTAL_QUANTITY_STR
			  ,ICM.CANCELLED AS CANCELLED1
			  ,CASE WHEN ICM.CNC_TYPE=2 THEN ''UN-CANCELLED'' WHEN  ICM.CNC_TYPE=1 THEN ''CANCELLED'' ELSE ''CANCELLED'' END  AS CNC_TYPE
			   ,ICM.TOTAL_AMOUNT AS TOTAL_AMOUNT1
			   ,ICM.DEPT_ID,L.DEPT_NAME 
			   ,ICM.APPROVED
			   ,CONVERT(VARCHAR,ICM.CNC_DT,106) AS CNC_DT
			   ,ICM.BIN_ID,BIN_NAME,ICM.REMARKS
		FROM ICM01106 ICM(NOLOCK)
		JOIN ICD01106 ICD(NOLOCK) ON ICD.CNC_MEMO_ID=ICM.CNC_MEMO_ID
		JOIN SKU (NOLOCK) ON SKU.PRODUCT_CODE=ICD.PRODUCT_CODE
		JOIN ARTICLE ART (NOLOCK) ON ART.ARTICLE_CODE=SKU.ARTICLE_CODE
		JOIN PARA1 P1  (NOLOCK) ON P1.PARA1_CODE=SKU.PARA1_CODE
		JOIN PARA2 P2  (NOLOCK) ON P2.PARA2_CODE=SKU.PARA2_CODE
		JOIN BIN (NOLOCK) ON BIN.BIN_ID=ICD.BIN_ID
		JOIN LOCATION L(NOLOCK) ON L.DEPT_ID=ICM.LOCATION_CODE
		WHERE CONVERT(DATETIME,CONVERT(VARCHAR,CNC_MEMO_DT,105),103) BETWEEN '''+@DFROMDATE+''' AND '''+@DTODATE+'''
		AND ('''+RTRIM(LTRIM(STR(@NINV_MODE)))+'''=''2'' OR CNC_TYPE IN('+@CNC_TYPE+'))
		AND ('''+@CLOC_ID+'''='''' OR ICM.LOCATION_CODE='''+@CLOC_ID+''')
		AND ('''+@LOC+'''='''' OR ICM.LOCATION_CODE= ''' +@LOC +''')	
		AND ICM.CANCELLED=0
       GROUP BY ICM.CNC_MEMO_ID, ICM.CNC_MEMO_NO,ICM.CNC_MEMO_DT
			   ,ICM.CANCELLED
			   ,ICM.CNC_TYPE
			   ,ICM.TOTAL_AMOUNT
			   ,ICM.DEPT_ID
			   ,ICM.APPROVED
			   ,ICM.CNC_DT
			   ,ICM.BIN_ID,BIN_NAME,L.DEPT_NAME
			    ,ICM.TOTAL_QUANTITY_STR,ICM.REMARKS'
			   
	PRINT @CCMD
	EXEC SP_EXECUTESQL @CCMD
END
