CREATE PROCEDURE [DBO].[SPPPC_FILTER_LEDGER]   
(  
 @NMODE        INT, --  (1) - VIEW FILTER DATA  (2) - VIEW ID WISE  
 @AC_CODE        VARCHAR(10) = '',  
 @AC_NAME       VARCHAR(300)='',  
 @INACTIVE        VARCHAR(5)='',  
 @HEAD_CODE      VARCHAR(10) = '',  
 @CITY_CODE       VARCHAR(10) = '',  
 @ERRMSG_OUT      VARCHAR(MAX) OUT  
)  
AS  
BEGIN  
 DECLARE @CSTEP INT, @CCMD NVARCHAR(MAX)  
 BEGIN TRY  
  SET NOCOUNT ON;  
    
  SET @ERRMSG_OUT = ''  
    
  --  (1) - VIEW FILTER DATA   
  SET @CSTEP = 10    
  IF (@NMODE=1)    
  BEGIN    
   SET @CCMD=N'SELECT AC_CODE, AC_NAME, ALIAS, HEAD_CODE, HEAD_NAME, INACTIVE, PRINT_NAME, ADDRESS0, ADDRESS1,   
            ADDRESS2, AREA_CODE, CITY_CODE, TIN_NO, PAN_NO, PHONES_O, PHONES_R, PHONES_FAX, MOBILE, ENABLE_EMAIL, E_MAIL,   
            ALLOW_CREDITOR_DEBTOR, AREA_NAME, PINCODE, CITY, STATE_CODE, [STATE] FROM (  
          SELECT A1.AC_CODE, A1.AC_NAME, A1.ALIAS, A1.HEAD_CODE, A3.HEAD_NAME, CASE WHEN ISNULL(A1.INACTIVE, 0) = 0 THEN ''NO'' ELSE ''YES'' END AS INACTIVE,  
            ISNULL(A2.PRINT_NAME, '''') AS PRINT_NAME, ISNULL(A2.ADDRESS0, '''') AS ADDRESS0, ISNULL(A2.ADDRESS1, '''') AS ADDRESS1,   
            ISNULL(A2.ADDRESS2, '''') AS ADDRESS2, ISNULL(A2.AREA_CODE, '''') AS AREA_CODE, ISNULL(A2.CITY_CODE, '''') AS CITY_CODE, ISNULL(A2.TIN_NO, '''') AS TIN_NO,   
            ISNULL(A2.PAN_NO, '''') AS PAN_NO, ISNULL(A2.PHONES_O, '''') AS PHONES_O, ISNULL(A2.PHONES_R, '''') AS PHONES_R, ISNULL(A2.PHONES_FAX, '''') AS PHONES_FAX,   
            ISNULL(A2.MOBILE, '''') AS MOBILE, CASE WHEN ISNULL(A2.ENABLE_EMAIL, 0) = 0 THEN ''NO'' ELSE ''YES'' END AS ENABLE_EMAIL, ISNULL(A2.E_MAIL, '''') AS E_MAIL,  
            CASE WHEN ISNULL(A2.ALLOW_CREDITOR_DEBTOR, 0) = 0 THEN ''NO'' ELSE ''YES'' END AS ALLOW_CREDITOR_DEBTOR,  
            DBO.UDF_PROPERCASE(A4.AREA_NAME) AS AREA_NAME, ISNULL(A4.PINCODE, '''') AS PINCODE, DBO.UDF_PROPERCASE(A5.CITY) AS [CITY],   
            ISNULL(A6.STATE_CODE, '''') AS STATE_CODE, DBO.UDF_PROPERCASE(A6.[STATE]) AS [STATE]  
          FROM LM01106 A1 (NOLOCK)   
          JOIN HD01106 A3 (NOLOCK) ON (A1.HEAD_CODE = A3.HEAD_CODE)  
          LEFT JOIN LMP01106 A2 (NOLOCK) ON (A1.AC_CODE = A2.AC_CODE)  
          LEFT JOIN AREA A4 (NOLOCK) ON A2.AREA_CODE = A4.AREA_CODE  
          LEFT JOIN CITY A5 (NOLOCK) ON A2.CITY_CODE=A5.CITY_CODE   
          LEFT JOIN [STATE] A6 (NOLOCK) ON A6.STATE_CODE=A5.STATE_CODE) AS LC  
         WHERE AC_NAME LIKE ''%' + @AC_NAME + '%''  
         AND HEAD_CODE LIKE ''%' + @HEAD_CODE + '%''   
         AND CITY_CODE LIKE ''%' + @CITY_CODE + '%''   
         AND INACTIVE LIKE ''%' + @INACTIVE + '%''   
         ORDER BY AC_NAME '  
   PRINT @CCMD    
   EXEC SP_EXECUTESQL @CCMD    
  END    
  
  --  (2) - VIEW ID WISE  
  SET @CSTEP = 20    
  IF (@NMODE=2)    
  BEGIN    
   SET @CCMD=N' SELECT  A1.AC_CODE, A1.AC_NAME, A1.ALIAS, A1.HEAD_CODE, A3.HEAD_NAME, CASE WHEN ISNULL(A1.INACTIVE, 0) = 0 THEN ''NO'' ELSE ''YES'' END AS INACTIVE,  
             ISNULL(A2.PRINT_NAME, '''') AS PRINT_NAME, ISNULL(A2.ADDRESS0, '''') AS ADDRESS0, ISNULL(A2.ADDRESS1, '''') AS ADDRESS1,   
             ISNULL(A2.ADDRESS2, '''') AS ADDRESS2, ISNULL(A2.AREA_CODE, '''') AS AREA_CODE, ISNULL(A2.CITY_CODE, '''') AS CITY_CODE, ISNULL(A2.TIN_NO, '''') AS TIN_NO,   
             ISNULL(A2.PAN_NO, '''') AS PAN_NO, ISNULL(A2.PHONES_O, '''') AS PHONES_O, ISNULL(A2.PHONES_R, '''') AS PHONES_R, ISNULL(A2.PHONES_FAX, '''') AS PHONES_FAX,   
             ISNULL(A2.MOBILE, '''') AS MOBILE, CASE WHEN ISNULL(A2.ENABLE_EMAIL, 0) = 0 THEN ''NO'' ELSE ''YES'' END AS ENABLE_EMAIL, ISNULL(A2.E_MAIL, '''') AS E_MAIL,  
             CASE WHEN ISNULL(A2.ALLOW_CREDITOR_DEBTOR, 0) = 0 THEN ''NO'' ELSE ''YES'' END AS ALLOW_CREDITOR_DEBTOR,  
             CASE WHEN PGM.AC_CODE IS NOT NULL  AND ISNULL(PGM.INACTIVE, 0)=0 THEN ''YES'' ELSE ''NO'' END AS CONSIDER_JOB_WORK_AGENCY,  
             DBO.UDF_PROPERCASE(A4.AREA_NAME) AS AREA_NAME, ISNULL(A4.PINCODE, '''') AS PINCODE, DBO.UDF_PROPERCASE(A5.CITY) AS [CITY],   
             ISNULL(A6.STATE_CODE, '''') AS STATE_CODE
             , DBO.UDF_PROPERCASE(A6.[STATE]) AS [STATE]  
             ,A1.LM_REMARKS
             --
             ,ISNULL(A2.AC_GST_NO,'''') AC_GST_NO
             ,ISNULL(A2.REGISTERED_GST_DEALER,0)REGISTERED_GST_DEALER
             ,ISNULL(A2.AC_GST_STATE_CODE,'''')AC_GST_STATE_CODE
             ,GSM.[GST_STATE_NAME] [GST_STATE_NAME]
          FROM LM01106 A1 (NOLOCK)   
          JOIN HD01106 A3 (NOLOCK) ON (A1.HEAD_CODE = A3.HEAD_CODE)  
          LEFT JOIN LMP01106 A2 (NOLOCK) ON (A1.AC_CODE = A2.AC_CODE)  
          LEFT JOIN PRD_AGENCY_MST PGM (NOLOCK) ON (A1.AC_CODE = PGM.AC_CODE)  
          LEFT JOIN AREA A4 (NOLOCK) ON A2.AREA_CODE = A4.AREA_CODE  
          LEFT JOIN CITY A5 (NOLOCK) ON A2.CITY_CODE=A5.CITY_CODE   
          LEFT JOIN GST_STATE_MST GSM (NOLOCK) ON GSM.GST_STATE_CODE = A2.AC_GST_STATE_CODE
          LEFT JOIN [STATE] A6 (NOLOCK) ON A6.STATE_CODE=A5.STATE_CODE  
          WHERE A1.AC_CODE = ''' + @AC_CODE + ''' '  
   PRINT @CCMD    
   EXEC SP_EXECUTESQL @CCMD    
  END   
  
  SET NOCOUNT OFF;  
 END TRY      
 BEGIN CATCH      
  SET @ERRMSG_OUT='ERROR: [P]: SPPPC_FILTER_LEDGER, [STEP]: '+CAST(@CSTEP AS VARCHAR(5))+', [MESSAGE]: ' + ERROR_MESSAGE()    
  PRINT @ERRMSG_OUT    
  
  GOTO END_PROC      
 END CATCH       
  
END_PROC:      
 IF  ISNULL(@ERRMSG_OUT,'')=''     
  SET @ERRMSG_OUT = ''    
END
