CREATE PROCEDURE SP_PPC_SHIPPING_DETAILS_VIEW
(
 @NMODE INT,
 @NSHIPPING_MODE INT=0
)
AS
BEGIN
   
   IF @NMODE=1
      GOTO LBLSHIPPING_MODE
   ELSE IF @NMODE=2
      GOTO LBLSHIPPING_MODE_DETAILS
   ELSE 
   GOTO END_PROC
   
   LBLSHIPPING_MODE:  
   
	 SELECT SHIPPING_MODE,SHIPPING_NAME 
	 FROM PPC_SHIPPING_DETAILS
	GOTO END_PROC
	 
   LBLSHIPPING_MODE_DETAILS:
   
     
	 SELECT SHIPPING_MODE,SHIPPING_NAME 
	 FROM PPC_SHIPPING_DETAILS
	 WHERE (@NSHIPPING_MODE=0 OR @NSHIPPING_MODE=SHIPPING_MODE)
    
   GOTO END_PROC


END_PROC:
END
