CREATE PROCEDURE SP3S_BANKRECON_DETAILS--(LocId 3 digit change by Sanjay:04-11-2024)
(
 @CAC_CODE VARCHAR(10)='',
 @DVCH_FM_DT DATETIME='',
 @DVCH_TO_DT DATETIME='',
 @BCHKONCLEARINGDT BIT=0,
 @cSPID	VARCHAR(50)=''
 
)
AS
BEGIN
	
	print 'reco-1:'+convert(varchar,getdate(),113)
	
	IF OBJECT_ID('tempdb..#tmpPendingReco','u') IS NOT NULL
		DROp TABLE #tmpPendingReco
	
	print 'reco-2:'+convert(varchar,getdate(),113)
    DECLARE @CDEPT_ID VARCHAR(4)
    SELECT TOP 1 @CDEPT_ID=DEPT_ID FROM NEW_APP_LOGIN_INFO (nolock) WHERE SPID=@@SPID 

	 SELECT A.VD_ID, A.VD_ID AS VS_AC_VD_ID, A.NARRATION,A.VM_ID,
			 CONVERT(CHAR(10),(CASE WHEN A.RECON_DT=''  THEN NULL ELSE A.RECON_DT END),105) AS RECONDT, A.RECON_DT AS [ORG_RECON_DT],
			 A.X_TYPE, D.VOUCHER_TYPE,X.VOUCHER_DT,  X.VOUCHER_NO,
			  --DBO.FN_GETACNAME(A.VM_ID,A.AC_CODE,A.X_TYPE) AS [AC_NAME]  , 
			  ac_name,A.AC_CODE, A.DEBIT_AMOUNT AS  [DEBIT_AMOUNT],
	 A.CREDIT_AMOUNT AS  [CREDIT_AMOUNT],  ISNULL(CHQ.CHQ_LEAF_NO  ,ISNULL(A.OPEN_CHEQUE_NO,'')) AS CHQ_LEAF_NO   
	INTO #tmpPendingReco
	FROM VD01106 A (NOLOCK) 
	JOIN VM01106 X (NOLOCK) ON X.VM_ID=A.VM_ID
	JOIN LM01106 LM (NOLOCK) ON LM.AC_CODE=A.AC_CODE
	JOIN VCHTYPE  D (NOLOCK) ON D.VOUCHER_CODE=X.VOUCHER_CODE
	LEFT OUTER JOIN VD_CHQBOOK VD_CHQ (NOLOCK) ON A.VD_ID = VD_CHQ.VD_ID 
	LEFT OUTER JOIN CHQBOOK_D CHQ (NOLOCK) ON VD_CHQ.CHQBOOK_ROW_ID = CHQ.ROW_ID 
	WHERE (@CAC_CODE='' OR A.AC_CODE=@CAC_CODE )
	AND ISNULL(A.RECON_DT,'')<>''
	AND (@BCHKONCLEARINGDT=1 OR X.VOUCHER_DT BETWEEN @DVCH_FM_DT AND @DVCH_TO_DT)
	AND (@BCHKONCLEARINGDT=0 OR A.RECON_DT BETWEEN @DVCH_FM_DT AND @DVCH_TO_DT  )
	 AND X.CANCELLED=0 
	 --AND A.VM_ID='HO357B0C09-052D-4270-93EB-9B8F2B2BFD98'
	UNION ALL
	 SELECT A.ROW_ID AS VD_ID, '' AS VS_AC_VD_ID, 'CHQ NO : ' + CHQ_NO AS NARRATION, '' AS VM_ID, 
			   CONVERT(CHAR(10),  (CASE WHEN A.RECON_DT ='' THEN NULL ELSE A.RECON_DT END),105) AS RECONDT,A.RECON_DT AS [ORG_RECON_DT], 
				A.CHQ_AMT_TYPE  AS X_TYPE, '' AS VOUCHER_TYPE, 
				A.CHQ_DT AS VOUCHER_DT, '' AS VOUCHER_NO,  B.AC_NAME ,B.AC_CODE , 
				CASE WHEN A.CHQ_AMT_TYPE ='DR' THEN CHQ_AMT ELSE 0 END AS DEBIT_AMOUNT, 
				CASE WHEN A.CHQ_AMT_TYPE ='DR' THEN 0 ELSE CHQ_AMT  END AS CREDIT_AMOUNT, '' AS CHQ_LEAF_NO 
	 FROM BANK_OP_CHQ A 
	 JOIN LM01106 B ON A.AC_CODE = B.AC_CODE  
	 WHERE (@CAC_CODE='' OR BANK_AC_CODE=@CAC_CODE ) 
	 AND (@BCHKONCLEARINGDT=1 OR A.CHQ_DT BETWEEN @DVCH_FM_DT AND @DVCH_TO_DT)
	 AND (@BCHKONCLEARINGDT=0 OR A.RECON_DT BETWEEN @DVCH_FM_DT AND @DVCH_TO_DT)  
	 AND  ISNULL(A.RECON_DT,'') <>''
	 ORDER BY VOUCHER_DT DESC ,VOUCHER_NO
	
	print 'reco-3:'+convert(varchar,getdate(),113)
	UPDATE  a set ac_name=c.ac_name from #tmpPendingReco a
	join vd01106  b (nolock) on b.VM_ID=a.vm_id
	join lm01106 c (nolock) on c.AC_CODE=b.ac_code
	where b.vd_id<>a.vd_id and (b.DEBIT_AMOUNT+b.CREDIT_AMOUNT)>=(a.DEBIT_AMOUNT+a.CREDIT_AMOUNT)

	print 'reco-4:'+convert(varchar,getdate(),113)
	select * from #tmpPendingReco

END 
/*
CREATE PROCEDURE SP3S_BANKRECON_DETAILS
(
 @CAC_CODE VARCHAR(10)='',
 @DVCH_FM_DT DATETIME='',
 @DVCH_TO_DT DATETIME='',
 @DRECON_FM_DT DATETIME='',
 @DRECON_TO_DT DATETIME=''

)
AS
BEGIN
	
	print 'reco-1:'+convert(varchar,getdate(),113)
	
	IF OBJECT_ID('tempdb..#tmpPendingReco','u') IS NOT NULL
		DROp TABLE #tmpPendingReco
	
	print 'reco-2:'+convert(varchar,getdate(),113)
    DECLARE @CDEPT_ID VARCHAR(2)
  

	 SELECT A.VD_ID, A.VD_ID AS VS_AC_VD_ID, A.NARRATION,A.VM_ID,
			 CONVERT(CHAR(10),(CASE WHEN A.RECON_DT=''  THEN NULL ELSE A.RECON_DT END),105) AS RECONDT, A.RECON_DT AS [ORG_RECON_DT],
			 A.X_TYPE, D.VOUCHER_TYPE,X.VOUCHER_DT,  X.VOUCHER_NO,
			  --DBO.FN_GETACNAME(A.VM_ID,A.AC_CODE,A.X_TYPE) AS [AC_NAME]  , 
			  ac_name,A.AC_CODE, A.DEBIT_AMOUNT AS  [DEBIT_AMOUNT],
	 A.CREDIT_AMOUNT AS  [CREDIT_AMOUNT],  ISNULL(CHQ.CHQ_LEAF_NO  ,ISNULL(A.OPEN_CHEQUE_NO,'')) AS CHQ_LEAF_NO   
	INTO #tmpPendingReco
	FROM VD01106 A (NOLOCK) 
	JOIN VM01106 X (NOLOCK) ON X.VM_ID=A.VM_ID
	JOIN LM01106 LM (NOLOCK) ON LM.AC_CODE=A.AC_CODE
	JOIN VCHTYPE  D (NOLOCK) ON D.VOUCHER_CODE=X.VOUCHER_CODE
	LEFT OUTER JOIN VD_CHQBOOK VD_CHQ (NOLOCK) ON A.VD_ID = VD_CHQ.VD_ID 
	LEFT OUTER JOIN CHQBOOK_D CHQ (NOLOCK) ON VD_CHQ.CHQBOOK_ROW_ID = CHQ.ROW_ID 
	WHERE (@CAC_CODE='' OR A.AC_CODE=@CAC_CODE )
	AND ISNULL(A.RECON_DT,'')<>''
	AND (@DVCH_FM_DT='' OR X.VOUCHER_DT BETWEEN @DVCH_FM_DT AND @DVCH_TO_DT)
	AND (@DRECON_FM_DT='' OR A.RECON_DT BETWEEN @DRECON_FM_DT AND @DRECON_TO_DT  )
	 AND X.CANCELLED=0  
	 --AND A.VM_ID='HO357B0C09-052D-4270-93EB-9B8F2B2BFD98'
	UNION ALL
	 SELECT A.ROW_ID AS VD_ID, '' AS VS_AC_VD_ID, 'CHQ NO : ' + CHQ_NO AS NARRATION, '' AS VM_ID, 
			   CONVERT(CHAR(10),  (CASE WHEN A.RECON_DT ='' THEN NULL ELSE A.RECON_DT END),105) AS RECONDT,A.RECON_DT AS [ORG_RECON_DT], 
				A.CHQ_AMT_TYPE  AS X_TYPE, '' AS VOUCHER_TYPE, 
				A.CHQ_DT AS VOUCHER_DT, '' AS VOUCHER_NO,  B.AC_NAME ,B.AC_CODE , 
				CASE WHEN A.CHQ_AMT_TYPE ='DR' THEN CHQ_AMT ELSE 0 END AS DEBIT_AMOUNT, 
				CASE WHEN A.CHQ_AMT_TYPE ='DR' THEN 0 ELSE CHQ_AMT  END AS CREDIT_AMOUNT, '' AS CHQ_LEAF_NO 
	 FROM BANK_OP_CHQ A 
	 JOIN LM01106 B ON A.AC_CODE = B.AC_CODE  
	 WHERE (@CAC_CODE='' OR BANK_AC_CODE=@CAC_CODE ) 
	 AND (@DVCH_FM_DT='' OR A.CHQ_DT BETWEEN @DVCH_FM_DT AND @DVCH_TO_DT)
	 AND (@DRECON_FM_DT='' OR A.RECON_DT BETWEEN @DRECON_FM_DT AND @DRECON_TO_DT)  
	 AND  ISNULL(A.RECON_DT,'') <>''
	 ORDER BY VOUCHER_DT DESC ,VOUCHER_NO
	
	print 'reco-3:'+convert(varchar,getdate(),113)
	UPDATE  a set ac_name=c.ac_name from #tmpPendingReco a
	join vd01106  b (nolock) on b.VM_ID=a.vm_id
	join lm01106 c (nolock) on c.AC_CODE=b.ac_code
	where b.vd_id<>a.vd_id and (b.DEBIT_AMOUNT+b.CREDIT_AMOUNT)>=(a.DEBIT_AMOUNT+a.CREDIT_AMOUNT)

	print 'reco-4:'+convert(varchar,getdate(),113)
	select * from #tmpPendingReco

END
*/