CREATE PROCEDURE SP3S_EOSS_SCHEMES_5
(
	@CSCHEMEDETROWID VARCHAR(50),
	@CSLSTITLE VARCHAR(500),
	@CROUNDITEMLEVEL VARCHAR(5),
	@CJOINSTRBUY VARCHAR(MAX),
	@CJOINSTRGET VARCHAR(MAX),
	@CPICKSLRDISCMODE VARCHAR(5),
	@CERRMSG VARCHAR(MAX) OUTPUT
)
AS 
BEGIN

	DECLARE @NORGBUYAMT NUMERIC(10,2),@NBUYAMT NUMERIC(10,2),@NGETAMT NUMERIC(10,2),@NREQGETAMT NUMERIC(10,2),
			@CPRODUCTCODE VARCHAR(50),@NMRP NUMERIC(10,2),@NQTY NUMERIC(10,2),
			@CCMDROWID VARCHAR(50),@NLOOPCNT INT,@NMODE INT,@BQUALIFIED BIT,
			@CROWID VARCHAR(100),@NSTEP INT,@NAMT NUMERIC(10,2),
			@CMRPORDER VARCHAR(10),@NREQBUYAMT NUMERIC(10,2),@BRETRY2NDCASE BIT,
			@CCMD NVARCHAR(MAX),@CBUYFILTER VARCHAR(MAX),@CGETFILTER VARCHAR(MAX),@BAPPLYSCHEMEONDISCITEMS BIT,
			@CADDFILTER VARCHAR(MAX),@CORGADDFILTER VARCHAR(MAX),@NDISCMODE INT,@NGETDISCPCT NUMERIC(6,2),
			@NFILTERMODE INT,@BPROCESSSLRENTRY BIT,@NGETFILTERMODE INT,@NTRIAL INT,@NAPPLYMODE NUMERIC(1,0)
	
	SET @BPROCESSSLRENTRY=0
	DECLARE @CENABLEOPTIMIZEDSCHEMES VARCHAR(2)
	SELECT TOP 1 @CENABLEOPTIMIZEDSCHEMES=VALUE FROM CONFIG WHERE CONFIG_OPTION='ENABLE_OPTIMIZED_EOSS_SCHEMES'		
	
	set @CENABLEOPTIMIZEDSCHEMES=isnull(@CENABLEOPTIMIZEDSCHEMES,'')

START_PROC:

	SELECT @NORGBUYAMT=0,@CPRODUCTCODE='',@NBUYAMT=0,@NGETAMT=0,@NMRP=0,@NQTY=0,
		   @CCMDROWID='',@NLOOPCNT=0,@NREQGETAMT=0,@NMODE=0,@BQUALIFIED=0,@CROWID='',
		   @NSTEP=0,@NAMT=0,@CMRPORDER='',@NREQBUYAMT=0,@BRETRY2NDCASE=0,@CCMD='',
		   @NDISCMODE=0,@CBUYFILTER='',@CGETFILTER='',@CADDFILTER='',@NFILTERMODE=0,
		   @CADDFILTER='',@CORGADDFILTER='',@NGETFILTERMODE=0
			

	IF @BPROCESSSLRENTRY=1
		SET @CORGADDFILTER='A.QUANTITY<0'
	ELSE
		SET @CORGADDFILTER='A.QUANTITY>0'
			
	IF CURSOR_STATUS('GLOBAL','SCHEMECUR') IN (0,1)
	BEGIN
		CLOSE SCHEMECUR
		DEALLOCATE SCHEMECUR
	END

BEGIN TRY        
		
	SET @NSTEP=10
	
	PRINT 'CHECK SCHEME SP3S_EOSS_SCHEMES_5'	
	SELECT @CMRPORDER='',@BQUALIFIED=0,@BRETRY2NDCASE=0
		
	IF OBJECT_ID('TEMPDB..#TEMPCMDPREV','U') IS NOT NULL
		DROP TABLE #TEMPCMDPREV

	IF OBJECT_ID('TEMPDB..#TMPCMDSCHEMES','U') IS NOT NULL
		DROP TABLE #TMPCMDSCHEMES

	SELECT @CBUYFILTER=(CASE WHEN FILTER_MODE IN (0,1) AND @CENABLEOPTIMIZEDSCHEMES<>'1'  THEN  BUY_FILTER_CRITERIA ELSE '1=1' END),
		   @CGETFILTER=(CASE WHEN GET_FILTER_MODE IN (0,1) AND @CENABLEOPTIMIZEDSCHEMES<>'1'  THEN  GET_FILTER_CRITERIA ELSE '1=1' END),
		   @NDISCMODE=DISC_METHOD,@NFILTERMODE=FILTER_MODE,@NGETFILTERMODE=GET_FILTER_MODE,
		   @BAPPLYSCHEMEONDISCITEMS=ISNULL(APPLY_SCHEME_ON_DISCOUNTED_ITEMS,0)
	FROM SCHEME_SETUP_DET
	WHERE ROW_ID=@CSCHEMEDETROWID

	IF @NFILTERMODE NOT IN (0,1)
		SELECT @CADDFILTER=@CORGADDFILTER+' AND SLSDET.ROW_ID='''+@CSCHEMEDETROWID+''''
	ELSE
		SELECT @CADDFILTER=@CORGADDFILTER+' AND 1=1'			

	SELECT @NORGBUYAMT= BUY_AMOUNT,@NBUYAMT= BUY_AMOUNT,@NGETDISCPCT=DISCOUNT_PERCENTAGE,@NAPPLYMODE=VALUE_BASED_SCHEME_MODE
	FROM SCHEME_SETUP_DET
	WHERE ROW_ID=@CSCHEMEDETROWID
					
	SET @NSTEP=15
	SELECT PRODUCT_CODE,MRP,QUANTITY,CMD_ROW_ID AS ROW_ID,CONVERT(INT,0) AS MODE,
	CONVERT(NUMERIC(10,2),0) AS DISCOUNT_AMOUNT,QUANTITY AS SCHEME_APPLIED_QTY,QUANTITY AS ORG_QUANTITY
	INTO #TMPCMDSCHEMES FROM #TMPCMD
	WHERE 1=2 
	
	--if @@spid=131
	--	select 'check #tmpcmd before buy n get n disc%',* from #tmpcmd
		
	SET @CCMD=N' SELECT A.PRODUCT_CODE,A.NET,ABS(A.QUANTITY)*(CASE WHEN A.QUANTITY<0 THEN -1 ELSE 1 END),
				 A.CMD_ROW_ID AS ROW_ID,1 AS MODE,
				 0 AS DISCOUNT_AMOUNT,0,(ABS(A.QUANTITY))*(CASE WHEN A.QUANTITY<0 THEN -1 ELSE 1 END) AS ORG_QUANTITY 
				 FROM #TMPCMD A
				 JOIN #CMDITV ITV ON ITV.PRODUCT_CODE=A.PRODUCT_CODE '+@CJOINSTRBUY+'
				 WHERE  '+(CASE WHEN @NAPPLYMODE=1 OR ISNULL(@BAPPLYSCHEMEONDISCITEMS,0)=0 THEN ' A.DISCOUNT_PERCENTAGE=0 AND ABS(A.QUANTITY)-A.SCHEME_APPLIED_QTY>0 AND ISNULL(a.scheme_setup_det_row_id,'''')=''''' ELSE '1=1' END)+
				 ' AND '+@CBUYFILTER+' AND '+@CADDFILTER
	
	PRINT @CCMD				 
	INSERT #TMPCMDSCHEMES
	EXEC SP_EXECUTESQL @CCMD

	IF @NGetFILTERMODE NOT IN (0,1)
		SELECT @CADDFILTER=@CORGADDFILTER+' AND SLSDET.ROW_ID='''+@CSCHEMEDETROWID+''''
	ELSE
		SELECT @CADDFILTER=@CORGADDFILTER+' AND 1=1'		

	SET @CCMD=N' SELECT A.PRODUCT_CODE,A.NET,ABS(A.QUANTITY)*(CASE WHEN A.QUANTITY<0 THEN -1 ELSE 1 END),
				 A.CMD_ROW_ID AS ROW_ID,2 AS MODE,
				 0 AS DISCOUNT_AMOUNT,0,(ABS(A.QUANTITY))*(CASE WHEN A.QUANTITY<0 THEN -1 ELSE 1 END) AS ORG_QUANTITY 
				 FROM #TMPCMD A
				 JOIN #CMDITV ITV ON ITV.PRODUCT_CODE=A.PRODUCT_CODE '+@CJOINSTRGET+'
				 WHERE  '+(CASE WHEN @NAPPLYMODE=1 OR ISNULL(@BAPPLYSCHEMEONDISCITEMS,0)=0 THEN 
				 ' A.DISCOUNT_PERCENTAGE=0 AND ABS(A.QUANTITY)-A.SCHEME_APPLIED_QTY>0  AND ISNULL(a.scheme_setup_det_row_id,'''')=''''' ELSE '1=1' END)+
				 ' AND '+@CGETFILTER+' AND '+@CADDFILTER
	
	PRINT @CCMD				 
	INSERT #TMPCMDSCHEMES
	EXEC SP_EXECUTESQL @CCMD
	
		
	IF NOT EXISTS (SELECT TOP 1 PRODUCT_CODE FROM #TMPCMDSCHEMES WHERE MODE=2)
	OR NOT EXISTS (SELECT TOP 1 PRODUCT_CODE FROM #TMPCMDSCHEMES WHERE MODE=1)
		GOTO EXIT_PROC
			
	SET @NSTEP=25
	
	SET @NTRIAL=1 
	

LBLCHKBUY:
					
	IF @BRETRY2NDCASE=0
		SET @CMRPORDER=''
	
	SELECT @NREQGETAMT=0,@NREQBUYAMT=0

	SET @NSTEP=30

	DECLARE SCHEMECUR CURSOR FOR SELECT PRODUCT_CODE,MRP,QUANTITY,ROW_ID FROM
	#TMPCMDSCHEMES WHERE MODE=1
				
	OPEN SCHEMECUR
	FETCH NEXT FROM SCHEMECUR INTO @CPRODUCTCODE,@NMRP,@NQTY,@CCMDROWID
	WHILE @@FETCH_STATUS=0
	BEGIN
		SET @NSTEP=40
		SET @NLOOPCNT=1
		WHILE @NLOOPCNT<=ABS(@NQTY)
		BEGIN
			SET @NREQBUYAMT=@NREQBUYAMT+@NMRP									
		    
		    SET @NSTEP=50
			UPDATE #TMPCMDSCHEMES SET QUANTITY=QUANTITY-1,
			SCHEME_APPLIED_QTY=SCHEME_APPLIED_QTY+1
			WHERE ROW_ID=@CCMDROWID
		    
		    PRINT '2:'+ STR(@NREQGETAMT)+STR(@NGETAMT)
			IF @NREQBUYAMT>=@NORGBUYAMT
			BEGIN
				SET @BQUALIFIED=1				
				BREAK
			END
		    
		    SET @NSTEP=60
			IF @BQUALIFIED=1
				BREAK
				
			SET @NLOOPCNT=@NLOOPCNT+1
		END										
		
		IF @BQUALIFIED=1
			BREAK
		
		FETCH NEXT FROM SCHEMECUR INTO @CPRODUCTCODE,@NMRP,@NQTY,@CCMDROWID
	END
	CLOSE SCHEMECUR
	DEALLOCATE SCHEMECUR
	
	
END TRY

BEGIN CATCH
  PRINT 'CATCH IN SP3S_EOSS_SCHEMES_5'       
  SET @CERRMSG='P:SP3S_EOSS_SCHEMES_5, STEP:'+LTRIM(RTRIM(STR(@NSTEP)))+', MESSAGE:'+ERROR_MESSAGE()        
  GOTO EXIT_PROC
END CATCH

EXIT_PROC:

	
	IF ISNULL(@CERRMSG,'')=''
	BEGIN
		--SELECT @BQUALIFIED,@NGETDISCPCT,* FROM #TMPCMDSCHEMES WHERE MODE=2
		IF @BQUALIFIED=0
		BEGIN
			UPDATE #TMPCMDSCHEMES SET DISCOUNT_AMOUNT=0
		END	
		ELSE
		BEGIN
			SET @NSTEP=115
			
				
			UPDATE #TMPCMDSCHEMES SET DISCOUNT_AMOUNT=MRP*ORG_QUANTITY*@NGETDISCPCT/100
			WHERE MODE=2
			
			--SELECT 'BEFORE VALUD BASE SCHEME',* FROM #TMPCMD
			
			DECLARE @CBNGNROWID VARCHAR(50)
			SET @CBNGNROWID=NEWID()

			UPDATE #TMPCMD SET DISCOUNT_AMOUNT=#TMPCMD.DISCOUNT_AMOUNT+(B.DISCOUNT_AMOUNT/B.ORG_QUANTITY)*(CASE WHEN @BPROCESSSLRENTRY=1 THEN -1 ELSE 1 END),
			SLS_TITLE=SLS_TITLE+(CASE WHEN SLS_TITLE<>'' THEN ',' ELSE '' END)+@CSLSTITLE,SCHEME_SETUP_DET_ROW_ID=@CSCHEMEDETROWID
			FROM #TMPCMDSCHEMES B WHERE B.ROW_ID=#TMPCMD.CMD_ROW_ID 
			AND B.MODE=2

			UPDATE #TMPCMD SET 	SCHEME_APPLIED_QTY=#TMPCMD.QUANTITY,SCHEME_SETUP_DET_ROW_ID=@CSCHEMEDETROWID,
			BNGN_ROW_ID=@CBNGNROWID
			FROM #TMPCMDSCHEMES B WHERE B.ROW_ID=#TMPCMD.CMD_ROW_ID 
			
			UPDATE #TMPCMD SET DISCOUNT_PERCENTAGE=ABS(ROUND((DISCOUNT_AMOUNT/(MRP*QUANTITY))*100,2)),
			NET=(MRP*QUANTITY)-DISCOUNT_AMOUNT
		END	
		
		IF @BPROCESSSLRENTRY=0 AND @CPICKSLRDISCMODE<>'3'
		BEGIN
			SET @BPROCESSSLRENTRY=1
			GOTO START_PROC
		END	
		ELSE
			GOTO END_PROC
	
	END	

END_PROC:

END
----- END OF PROCEDURE SP3S_EOSS_SCHEMES_5