CREATE PROCEDURE SP_MERGEMSTEOSSDATA
(  
 @NSPID INT  
)  
----WITH ENCRYPTION
AS  
BEGIN  
   
 BEGIN TRY  
    
  DECLARE @CERRORMSG VARCHAR(1000),@CCURDEPTID CHAR(2),@CHODEPTID CHAR(2),@CCMD NVARCHAR(MAX),  
    @CXNMASTERTABLENAME VARCHAR(100),@BPROCEED BIT,@CTABLENAME VARCHAR(100),@CMASTERKEYFIELD VARCHAR(100),  
    @CKEYFIELD VARCHAR(100),@CPARENTTABLENAME VARCHAR(100),@CPARENTPARANAME VARCHAR(100),@CCHILDPARANAME VARCHAR(100),  
    @CWHERECLAUSE VARCHAR(100),@CJOINSTR VARCHAR(1000),@CMEMOID VARCHAR(100),@CFINYEAR VARCHAR(100),  
    @NGRPCHARS INT,@NSERIESCHARS INT,@BSERIESBROKEN BIT,@CPREVMEMOID VARCHAR(40),@CMERGETABLENAME VARCHAR(50),  
    @CFIRSTMEMOID VARCHAR(40),@NPREVMEMOID INT,@NMEMONOLEN INT,@CRETCMD NVARCHAR(MAX),  
    @CDELCHILDTABLENAME VARCHAR(100),@CDELCHILDPARANAME VARCHAR(100),@CDELPARENTPARANAME VARCHAR(100),  
    @CORIGINALTABLENAME VARCHAR(100),@NLOCTYPE INT,@BDONOTMERGE BIT,@CRFXNTYPE VARCHAR(10),  
    @BINSERTONLY BIT,@BLINKEDMASTER BIT,@BPURLOC BIT,@CSOURCELOCID CHAR(2),@BSOURCEPURLOC BIT,  
    @CMISSINGMEMOID VARCHAR(40),@CGRPCODE VARCHAR(20),@BRETVAL BIT,@NPREVNO INT,@CPREVNO VARCHAR(20),  
    @BEMPHEADSUPDATED BIT,@CFILTERCONDITION VARCHAR(100),@CTABLEPREFIX VARCHAR(100),@CXNTYPE VARCHAR(10),  
    @NXNSMERGINGORDER INT,@NSTEP INT,@CBUNDLEMTABLENAME VARCHAR(100),@CBUNDLEDTABLENAME VARCHAR(100),  
    @CSLSMSTTABLENAME VARCHAR(100),@CSLSDETTABLENAME VARCHAR(100),@CLOCSLSSETTABLENAME VARCHAR(100),  
    @CSCHEMEDETTABLENAME VARCHAR(100),@CSCHEMEHHTABLENAME VARCHAR(100),@CSLSBCTABLENAME VARCHAR(100),  
    @CSLSARTTABLENAME VARCHAR(100),@NXNSSENDINGORDER INT,@CSLSMEMONO VARCHAR(20),@BMIRRORINGENABLED BIT,
    @CEOSSMERGINGTHRUWIZCOM VARCHAR(2)
    
   DECLARE @CTEMPMASTERTABLENAME VARCHAR(100), @CTEMPDETAILTABLENAME VARCHAR(100),@CTEMPLOCTABLENAME VARCHAR(100),
			@CTEMPSLSBCTABLENAME VARCHAR(100), @CTEMPSLSARTTABLENAME VARCHAR(100),@CTEMPSLSPARATABLENAME VARCHAR(100),
			@CTEMHAPPYHOURSTABLENAME VARCHAR(100),@CSCH2 VARCHAR(100),@CSCH7 VARCHAR(100),@CSCH6 VARCHAR(100),@CSCH_B VARCHAR(100),@CTEMPCONFIGTABLENAME VARCHAR(100),
			@CTEMPSLSBCGETTABLENAME VARCHAR(100), @CTEMPSLSARTGETTABLENAME VARCHAR(100),@CTEMPSLSPARAGETTABLENAME VARCHAR(100)
			
    
  SET @NSTEP=10  
    
  DECLARE @TRETMSG TABLE  (MEMO_ID VARCHAR(40),ERRMSG VARCHAR(MAX))  

	IF EXISTS (SELECT TOP 1 CONFIG_OPTION FROM CONFIG WHERE 
			   CONFIG_OPTION='MIRROR_SERVER_IP' AND VALUE<>'')
		SET @BMIRRORINGENABLED=1
	ELSE
		SET @BMIRRORINGENABLED=0

	IF @BMIRRORINGENABLED=1
	BEGIN
		SET @CERRORMSG='SALES SETUP MERGING SHIFTED TO MIRRORSERVICE....'
		GOTO END_PROC
	
	END
  
  BEGIN TRANSACTION  
     
  SELECT @CERRORMSG='',@BPROCEED=1,@NMEMONOLEN=10,@CRETCMD='',@CMEMOID='',@CXNTYPE='MSTEOSS',@BEMPHEADSUPDATED=0  
    
 
    
  SET @NSTEP=30  
    
  SET @CFILTERCONDITION=''  
     
  SELECT TOP 1 @CCURDEPTID = VALUE FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION='LOCATION_ID'  
  SELECT TOP 1 @CHODEPTID = VALUE FROM CONFIG (NOLOCK) WHERE CONFIG_OPTION='HO_LOCATION_ID'  
      
  SELECT @NLOCTYPE=LOC_TYPE,@BPURLOC=PUR_LOC FROM LOCATION (NOLOCK) WHERE DEPT_ID=@CCURDEPTID  
    
    
  SET @CMEMOID='MSTEOSS'  
    
 LBLMERGEBEFORE:  
    
     
  SET @NSTEP=60   
    
  SET @CTABLENAME='TMP_MSTEOSS_SCHEME_SETUP_LOC_' + LTRIM(RTRIM(STR(@NSPID)))  
     
  SET @CCMD=N'IF OBJECT_ID('''+@CTABLENAME+''',''U'') IS NOT NULL  
      SET @BPROCEEDOUT=1    
     ELSE  
      SET @BPROCEEDOUT=0'  
  PRINT @CCMD      
  EXEC SP_EXECUTESQL @CCMD,N'@BPROCEEDOUT BIT OUTPUT',@BPROCEEDOUT=@BPROCEED OUTPUT  
  
  SET @NSTEP=90        
  IF @BPROCEED=0  
  BEGIN  
   SET @CERRORMSG='LOCATION WISE SALES SETUP DETAIL TABLE NOT FOUND.....PLEASE GET SALES SETUP RESENT FROM HO'  
   GOTO LBLLAST  
  END  
    
  SET @NSTEP=120  
       
  SET @CCMD=N'IF NOT EXISTS (SELECT TOP 1 DEPT_ID FROM TMP_MSTEOSS_SCHEME_SETUP_LOC_'+LTRIM(RTRIM(STR(@NSPID)))+')  
      SET @BPROCEEDOUT=0    
     ELSE  
      SET @BPROCEEDOUT=1'  
  PRINT @CCMD      
  EXEC SP_EXECUTESQL @CCMD,N'@BPROCEEDOUT BIT OUTPUT',@BPROCEEDOUT=@BPROCEED OUTPUT  
  
  SET @NSTEP=150
  IF @BPROCEED=1  
  BEGIN  
     
			   SET @NSTEP=180  
			   
			     
			  SELECT   
						   @CTEMPMASTERTABLENAME='TMP_MSTEOSS_SCHEME_SETUP_MST_' + LTRIM(RTRIM(STR(@NSPID))),  
						   @CTEMPDETAILTABLENAME='TMP_MSTEOSS_SCHEME_SETUP_DET_' + LTRIM(RTRIM(STR(@NSPID))),  
						   @CTEMPLOCTABLENAME='TMP_MSTEOSS_SCHEME_SETUP_LOC_' + LTRIM(RTRIM(STR(@NSPID))),  
						   @CTEMPSLSBCTABLENAME='TMP_MSTEOSS_SCHEME_SETUP_SLSBC_' + LTRIM(RTRIM(STR(@NSPID))),  
						   @CTEMPSLSBCGETTABLENAME='TMP_MSTEOSS_SCHEME_SETUP_SLSBC_GET_' + LTRIM(RTRIM(STR(@NSPID))),  
						   @CTEMPSLSARTTABLENAME='TMP_MSTEOSS_SCHEME_SETUP_SLSART_' + LTRIM(RTRIM(STR(@NSPID))),  
						   @CTEMPSLSARTGETTABLENAME='TMP_MSTEOSS_SCHEME_SETUP_SLSART_GET_' + LTRIM(RTRIM(STR(@NSPID))),  
						   @CTEMPSLSPARATABLENAME='TMP_MSTEOSS_SCHEME_SETUP_SLSPARA_' + LTRIM(RTRIM(STR(@NSPID))),  
						   @CTEMPSLSPARAGETTABLENAME='TMP_MSTEOSS_SCHEME_SETUP_SLSPARA_GET_' + LTRIM(RTRIM(STR(@NSPID))),  
						   @CTEMHAPPYHOURSTABLENAME='TMP_MSTEOSS_SCHEME_SETUP_HAPPYHOURS_' + LTRIM(RTRIM(STR(@NSPID))),
						   @CSCH2='TMP_MSTEOSS_SCHEME_SETUP_SCH0002_1_' + LTRIM(RTRIM(STR(@NSPID))), 
						   @CSCH7='TMP_MSTEOSS_SCHEME_SETUP_SCH0007_1_' + LTRIM(RTRIM(STR(@NSPID))), 
						   @CSCH6='TMP_MSTEOSS_SCHEME_SETUP_SCH0006_1_' + LTRIM(RTRIM(STR(@NSPID))), 
						   @CSCH_B='TMP_MSTEOSS_SCHEME_SETUP_SCHB001_1_' + LTRIM(RTRIM(STR(@NSPID))), 
						   @CTEMPCONFIGTABLENAME = 'TMP_MSTEOSS_CONFIG_' + LTRIM(RTRIM(STR(@NSPID)))  
			     
			   SET @NSTEP=210     
			   SET @CCMD=N'SELECT TOP 1 @CSLSMEMONOOUT= A.MEMO_NO FROM '+@CTEMPMASTERTABLENAME+' A  
						   JOIN SCHEME_SETUP_MST B ON A.MEMO_NO=B.MEMO_NO  
						   WHERE CONVERT(DATETIME,A.LAST_UPDATE)<B.LAST_UPDATE'
			   PRINT @CCMD	     
			   EXEC SP_EXECUTESQL @CCMD,N'@CSLSMEMONOOUT VARCHAR(20) OUTPUT',@CSLSMEMONOOUT=@CSLSMEMONO OUTPUT  
			    
			    
			   SET @NSTEP=230 
			   IF ISNULL(@CSLSMEMONO,'')<>''  
			   BEGIN  
				SET @CERRORMSG='OLDER VERSION OF SALES SETUP MEMO NO. :'+@CSLSMEMONO+' FOUND IN THE SOURCE FILE.....PLEASE CHECK'  
				GOTO LBLLAST  
			   END  
			    
			   --DELETE FROM TEMP SCHEME_SETUP_MST TABLE WHICH MEMO DOES NOT BELONG TO CURRENT LOCATION
			   SET @NSTEP=260
			   SET @CCMD = N'IF OBJECT_ID('''+@CTEMPMASTERTABLENAME+''',''U'') IS NOT NULL
						     BEGIN
								DELETE FROM '+@CTEMPMASTERTABLENAME+' 
								WHERE MEMO_NO NOT IN (SELECT MEMO_NO FROM '+@CTEMPLOCTABLENAME+' WHERE DEPT_ID = '''+@CCURDEPTID+''') 
						     END'
				
			   PRINT @CCMD
			   EXEC SP_EXECUTESQL @CCMD
			   
			   --DELETE FROM TEMP SCHEME_SETUP_SLSBC TABLE WHICH MEMO DOES NOT BELONG TO CURRENT LOCATION
			   SET @NSTEP=290
			   SET @CCMD = N'IF OBJECT_ID('''+@CTEMPSLSBCTABLENAME+''',''U'') IS NOT NULL AND OBJECT_ID('''+@CTEMPDETAILTABLENAME+''',''U'') IS NOT NULL
						     BEGIN
								DELETE A FROM '+@CTEMPSLSBCTABLENAME+' A 
								JOIN  '+@CTEMPDETAILTABLENAME+' B ON B.ROW_ID = A.SCHEME_SETUP_DET_ROW_ID
								WHERE B.MEMO_NO NOT IN (SELECT MEMO_NO FROM '+@CTEMPLOCTABLENAME+' WHERE DEPT_ID = '''+@CCURDEPTID+''')
						     END'
				
			   PRINT @CCMD
			   EXEC SP_EXECUTESQL @CCMD
			   
			   --DELETE FROM TEMP SCHEME_SETUP_SLSBC_GET TABLE WHICH MEMO DOES NOT BELONG TO CURRENT LOCATION
			   SET @NSTEP=310
			   SET @CCMD = N'IF OBJECT_ID('''+@CTEMPSLSBCGETTABLENAME+''',''U'') IS NOT NULL AND OBJECT_ID('''+@CTEMPDETAILTABLENAME+''',''U'') IS NOT NULL
						     BEGIN
								DELETE A FROM '+@CTEMPSLSBCGETTABLENAME+' A 
								JOIN  '+@CTEMPDETAILTABLENAME+' B ON B.ROW_ID = A.SCHEME_SETUP_DET_ROW_ID
								WHERE B.MEMO_NO NOT IN (SELECT MEMO_NO FROM '+@CTEMPLOCTABLENAME+' WHERE DEPT_ID = '''+@CCURDEPTID+''')
						     END'
				
			   PRINT @CCMD
			   EXEC SP_EXECUTESQL @CCMD
			   
			   --DELETE FROM TEMP SCHEME_SETUP_SLSART TABLE WHICH MEMO DOES NOT BELONG TO CURRENT LOCATION
			   SET @NSTEP=340
			   SET @CCMD = N'IF OBJECT_ID('''+@CTEMPSLSARTTABLENAME+''',''U'') IS NOT NULL AND OBJECT_ID('''+@CTEMPDETAILTABLENAME+''',''U'') IS NOT NULL
						     BEGIN
								DELETE A FROM '+@CTEMPSLSARTTABLENAME+' A 
								JOIN  '+@CTEMPDETAILTABLENAME+' B ON B.ROW_ID = A.SCHEME_SETUP_DET_ROW_ID
								WHERE B.MEMO_NO NOT IN (SELECT MEMO_NO FROM '+@CTEMPLOCTABLENAME+' WHERE DEPT_ID = '''+@CCURDEPTID+''')
						     END'
				
			   PRINT @CCMD
			   EXEC SP_EXECUTESQL @CCMD
			   
			   --DELETE FROM TEMP SCHEME_SETUP_SLSART_GET TABLE WHICH MEMO DOES NOT BELONG TO CURRENT LOCATION
			   SET @NSTEP=370
			   SET @CCMD = N'IF OBJECT_ID('''+@CTEMPSLSARTGETTABLENAME+''',''U'') IS NOT NULL AND OBJECT_ID('''+@CTEMPDETAILTABLENAME+''',''U'') IS NOT NULL
						     BEGIN
								DELETE A FROM '+@CTEMPSLSARTGETTABLENAME+' A 
								JOIN  '+@CTEMPDETAILTABLENAME+' B ON B.ROW_ID = A.SCHEME_SETUP_DET_ROW_ID
								WHERE B.MEMO_NO NOT IN (SELECT MEMO_NO FROM '+@CTEMPLOCTABLENAME+' WHERE DEPT_ID = '''+@CCURDEPTID+''')
						     END'
				
			   PRINT @CCMD
			   EXEC SP_EXECUTESQL @CCMD
			   
			   --DELETE FROM TEMP SCHEME_SETUP_SLSPARA TABLE WHICH MEMO DOES NOT BELONG TO CURRENT LOCATION
			   SET @NSTEP=400
			   SET @CCMD = N'IF OBJECT_ID('''+@CTEMPSLSPARATABLENAME+''',''U'') IS NOT NULL AND OBJECT_ID('''+@CTEMPDETAILTABLENAME+''',''U'') IS NOT NULL
						     BEGIN
								DELETE A FROM '+@CTEMPSLSPARATABLENAME+' A 
								JOIN  '+@CTEMPDETAILTABLENAME+' B ON B.ROW_ID = A.SCHEME_SETUP_DET_ROW_ID
								WHERE B.MEMO_NO NOT IN (SELECT MEMO_NO FROM '+@CTEMPLOCTABLENAME+' WHERE DEPT_ID = '''+@CCURDEPTID+''')
						     END'
				
			   PRINT @CCMD
			   EXEC SP_EXECUTESQL @CCMD
			   
			   --DELETE FROM TEMP SCHEME_SETUP_SLSPARA_GET TABLE WHICH MEMO DOES NOT BELONG TO CURRENT LOCATION
			   SET @NSTEP=430
			   SET @CCMD = N'IF OBJECT_ID('''+@CTEMPSLSPARAGETTABLENAME+''',''U'') IS NOT NULL AND OBJECT_ID('''+@CTEMPDETAILTABLENAME+''',''U'') IS NOT NULL
						     BEGIN
								DELETE A FROM '+@CTEMPSLSPARAGETTABLENAME+' A 
								JOIN  '+@CTEMPDETAILTABLENAME+' B ON B.ROW_ID = A.SCHEME_SETUP_DET_ROW_ID
								WHERE B.MEMO_NO NOT IN (SELECT MEMO_NO FROM '+@CTEMPLOCTABLENAME+' WHERE DEPT_ID = '''+@CCURDEPTID+''')
						     END'
				
			   PRINT @CCMD
			   EXEC SP_EXECUTESQL @CCMD
			   
			   --DELETE FROM TEMP SCHEME_SETUP_SCH0002_1 TABLE WHICH MEMO DOES NOT BELONG TO CURRENT LOCATION
			   SET @NSTEP=440
			   SET @CCMD = N'IF OBJECT_ID('''+@CSCH2+''',''U'') IS NOT NULL AND OBJECT_ID('''+@CTEMPDETAILTABLENAME+''',''U'') IS NOT NULL
						     BEGIN
								DELETE A FROM '+@CSCH2+' A 
								JOIN  '+@CTEMPDETAILTABLENAME+' B ON B.ROW_ID = A.SCHEME_SETUP_DET_ROW_ID
								WHERE B.MEMO_NO NOT IN (SELECT MEMO_NO FROM '+@CTEMPLOCTABLENAME+' WHERE DEPT_ID = '''+@CCURDEPTID+''')
						     END'
				
			   PRINT @CCMD
			   EXEC SP_EXECUTESQL @CCMD

			   SET @NSTEP=440
			   SET @CCMD = N'IF OBJECT_ID('''+@CSCH7+''',''U'') IS NOT NULL AND OBJECT_ID('''+@CTEMPDETAILTABLENAME+''',''U'') IS NOT NULL
						     BEGIN
								DELETE A FROM '+@CSCH7+' A 
								JOIN  '+@CTEMPDETAILTABLENAME+' B ON B.ROW_ID = A.SCHEME_SETUP_DET_ROW_ID
								WHERE B.MEMO_NO NOT IN (SELECT MEMO_NO FROM '+@CTEMPLOCTABLENAME+' WHERE DEPT_ID = '''+@CCURDEPTID+''')
						     END'
				
			   PRINT @CCMD
			   EXEC SP_EXECUTESQL @CCMD			   
			   
			   --DELETE FROM TEMP SCHEME_SETUP_SCH0002_1 TABLE WHICH MEMO DOES NOT BELONG TO CURRENT LOCATION
			   SET @NSTEP=450
			   SET @CCMD = N'IF OBJECT_ID('''+@CSCH6+''',''U'') IS NOT NULL AND OBJECT_ID('''+@CTEMPDETAILTABLENAME+''',''U'') IS NOT NULL
						     BEGIN
								DELETE A FROM '+@CSCH6+' A 
								JOIN  '+@CTEMPDETAILTABLENAME+' B ON B.ROW_ID = A.SCHEME_SETUP_DET_ROW_ID
								WHERE B.MEMO_NO NOT IN (SELECT MEMO_NO FROM '+@CTEMPLOCTABLENAME+' WHERE DEPT_ID = '''+@CCURDEPTID+''')
						     END'
				
			   PRINT @CCMD
			   EXEC SP_EXECUTESQL @CCMD
			   			   

			   --DELETE FROM TEMP SCHEME_SETUP_SCH0002_1 TABLE WHICH MEMO DOES NOT BELONG TO CURRENT LOCATION
			   SET @NSTEP=460
			   SET @CCMD = N'IF OBJECT_ID('''+@CSCH_B+''',''U'') IS NOT NULL AND OBJECT_ID('''+@CTEMPDETAILTABLENAME+''',''U'') IS NOT NULL
						     BEGIN
								DELETE A FROM '+@CSCH_B+' A 
								JOIN  '+@CTEMPDETAILTABLENAME+' B ON B.ROW_ID = A.SCHEME_SETUP_DET_ROW_ID
								WHERE B.MEMO_NO NOT IN (SELECT MEMO_NO FROM '+@CTEMPLOCTABLENAME+' WHERE DEPT_ID = '''+@CCURDEPTID+''')
						     END'
				
			   PRINT @CCMD
			   EXEC SP_EXECUTESQL @CCMD

			   --DELETE FROM TEMP SCHEME_SETUP_HAPPYHOURS TABLE WHICH MEMO DOES NOT BELONG TO CURRENT LOCATION
			   SET @NSTEP=470
			   SET @CCMD = N'IF OBJECT_ID('''+@CTEMHAPPYHOURSTABLENAME+''',''U'') IS NOT NULL 
						     BEGIN
								DELETE FROM '+@CTEMHAPPYHOURSTABLENAME+' 
								WHERE MEMO_NO NOT IN (SELECT MEMO_NO FROM '+@CTEMPLOCTABLENAME+' WHERE DEPT_ID = '''+@CCURDEPTID+''') 
						     END'
				
			   PRINT @CCMD
			   EXEC SP_EXECUTESQL @CCMD
			   
			    --DELETE FROM TEMP SCHEME_SETUP_DET TABLE WHICH MEMO DOES NOT BELONG TO CURRENT LOCATION
			    SET @NSTEP=500
			    SET @CCMD = N'IF OBJECT_ID('''+@CTEMPDETAILTABLENAME+''',''U'') IS NOT NULL 
						     BEGIN
								DELETE FROM '+@CTEMPDETAILTABLENAME+' 
								WHERE MEMO_NO NOT IN (SELECT MEMO_NO FROM '+@CTEMPLOCTABLENAME+' WHERE DEPT_ID = '''+@CCURDEPTID+''') 
						     END'
				
			   PRINT @CCMD
			   EXEC SP_EXECUTESQL @CCMD
			   
			   --DELETE FROM TEMP SCHEME_SETUP_LOC TABLE WHICH MEMO DOES NOT BELONG TO CURRENT LOCATION
			   SET @NSTEP=530
			   SET @CCMD = N'IF OBJECT_ID('''+@CTEMPLOCTABLENAME+''',''U'') IS NOT NULL 
						     BEGIN
								DELETE FROM '+@CTEMPLOCTABLENAME+' WHERE DEPT_ID <> '''+@CCURDEPTID+''' 
						     END'
				
			   PRINT @CCMD
			   EXEC SP_EXECUTESQL @CCMD
			   
  END  
  ELSE  
  BEGIN  
   SET @NSTEP=560  
     
   SET @CERRORMSG='NO NEW SALES SETUP DATA FOUND.....'  
   GOTO LBLLAST  
  END  
    
 LBLDELETE:  
    
  SET @NSTEP=590
  
			DELETE FROM REP_DET WHERE REP_ID IN (SELECT REP_ID FROM REP_MST WHERE REP_CODE='SSU01')
			DELETE FROM REP_FILTER WHERE REP_ID IN (SELECT REP_ID FROM REP_MST WHERE REP_CODE='SSU01')
			DELETE FROM REP_FILTER_DET WHERE REP_ID IN (SELECT REP_ID FROM REP_MST WHERE REP_CODE='SSU01')
			DELETE FROM REP_MST WHERE REP_CODE='SSU01'

 SET @NSTEP=620
			--DELETE DATA FROM MAIN TABLES
			DELETE A FROM  SCHEME_SETUP_SCH0002_1 A
			DELETE A FROM  SCHEME_SETUP_SCH0006_1 A
			DELETE A FROM  SCHEME_SETUP_SCH0007_1 A
			DELETE A FROM  SCHEME_SETUP_SCHB001_1 A 
			DELETE A FROM  SCHEME_SETUP_SLSPARA A 
			DELETE A FROM  SCHEME_SETUP_SLSPARA_GET A 
			DELETE A FROM  SCHEME_SETUP_SLSART A 
			DELETE A FROM  SCHEME_SETUP_SLSART_GET A 
			
			DELETE A FROM  SCHEME_SETUP_SLSBC A 
			JOIN SCHEME_SETUP_DET B ON A.SCHEME_SETUP_DET_ROW_ID = B.ROW_ID
		    WHERE LEFT(B.MEMO_NO,2)=@CHODEPTID
			DELETE A FROM  SCHEME_SETUP_SLSBC_GET A 
			DELETE FROM SCHEME_SETUP_HAPPYHOURS 			  		  
			DELETE FROM SCHEME_SETUP_LOC 
			DELETE SCHEME_SETUP_DET WHERE  LEFT(MEMO_NO,2)=@CHODEPTID
			DELETE SCHEME_SETUP_MST	WHERE LEFT(MEMO_NO,2)=@CHODEPTID 

  LBLMERGE:  
            PRINT 'SCHEME_SETUP_MST'
			SET @NSTEP=650
			EXEC UPDATEMASTERXN_MIRROR 
			@CSOURCEDB='',
			@CSOURCETABLE=@CTEMPMASTERTABLENAME,
			@CDESTDB='',
			@CDESTTABLE='SCHEME_SETUP_MST',
			@CKEYFIELD1='MEMO_NO',
			@CKEYFIELD2='',
			@CKEYFIELD3='',
			@LINSERTONLY=0,
			@CFILTERCONDITION='',
			@LUPDATEONLY=0,
			@BALWAYSUPDATE=1
			
			SET @NSTEP=680		
			EXEC UPDATEMASTERXN_MIRROR 
			@CSOURCEDB='',
			@CSOURCETABLE=@CTEMPDETAILTABLENAME,
			@CDESTDB='',
			@CDESTTABLE='SCHEME_SETUP_DET',
			@CKEYFIELD1='ROW_ID',
			@CKEYFIELD2='',
			@CKEYFIELD3='',
			@LINSERTONLY=0,
			@CFILTERCONDITION='',
			@LUPDATEONLY=0,
			@BALWAYSUPDATE=1
			
			SET @NSTEP=710				
			EXEC UPDATEMASTERXN_MIRROR 
			@CSOURCEDB='',
			@CSOURCETABLE=@CTEMPSLSBCTABLENAME,
			@CDESTDB='',
			@CDESTTABLE='SCHEME_SETUP_SLSBC',
			@CKEYFIELD1='ROW_ID',
			@CKEYFIELD2='',
			@CKEYFIELD3='',
			@LINSERTONLY=0,
			@CFILTERCONDITION='',
			@LUPDATEONLY=0,
			@BALWAYSUPDATE=1
					
			SET @NSTEP=740
			EXEC UPDATEMASTERXN_MIRROR 
			@CSOURCEDB='',
			@CSOURCETABLE=@CTEMPSLSBCGETTABLENAME,
			@CDESTDB='',
			@CDESTTABLE='SCHEME_SETUP_SLSBC_GET',
			@CKEYFIELD1='ROW_ID',
			@CKEYFIELD2='',
			@CKEYFIELD3='',
			@LINSERTONLY=0,
			@CFILTERCONDITION='',
			@LUPDATEONLY=0,
			@BALWAYSUPDATE=1
			
			
			SET @NSTEP=770
			EXEC UPDATEMASTERXN_MIRROR 
			@CSOURCEDB='',
			@CSOURCETABLE=@CTEMPSLSARTTABLENAME,
			@CDESTDB='',
			@CDESTTABLE='SCHEME_SETUP_SLSART',
			@CKEYFIELD1='ROW_ID',
			@CKEYFIELD2='',
			@CKEYFIELD3='',
			@LINSERTONLY=0,
			@CFILTERCONDITION='',
			@LUPDATEONLY=0,
			@BALWAYSUPDATE=1
			
			SET @NSTEP=800
			EXEC UPDATEMASTERXN_MIRROR 
			@CSOURCEDB='',
			@CSOURCETABLE=@CTEMPSLSARTGETTABLENAME,
			@CDESTDB='',
			@CDESTTABLE='SCHEME_SETUP_SLSART_GET',
			@CKEYFIELD1='ROW_ID',
			@CKEYFIELD2='',
			@CKEYFIELD3='',
			@LINSERTONLY=0,
			@CFILTERCONDITION='',
			@LUPDATEONLY=0,
			@BALWAYSUPDATE=1
			
			SET @NSTEP=830	
			EXEC UPDATEMASTERXN_MIRROR 
			@CSOURCEDB='',
			@CSOURCETABLE=@CTEMPSLSPARATABLENAME,
			@CDESTDB='',
			@CDESTTABLE='SCHEME_SETUP_SLSPARA',
			@CKEYFIELD1='ROW_ID',
			@CKEYFIELD2='',
			@CKEYFIELD3='',
			@LINSERTONLY=0,
			@CFILTERCONDITION='',
			@LUPDATEONLY=0,
			@BALWAYSUPDATE=1
			
			SET @NSTEP=860
			EXEC UPDATEMASTERXN_MIRROR 
			@CSOURCEDB='',
			@CSOURCETABLE=@CTEMPSLSPARAGETTABLENAME,
			@CDESTDB='',
			@CDESTTABLE='SCHEME_SETUP_SLSPARA_GET',
			@CKEYFIELD1='ROW_ID',
			@CKEYFIELD2='',
			@CKEYFIELD3='',
			@LINSERTONLY=0,
			@CFILTERCONDITION='',
			@LUPDATEONLY=0,
			@BALWAYSUPDATE=1
				
			SET @NSTEP=890
			EXEC UPDATEMASTERXN_MIRROR 
			@CSOURCEDB='',
			@CSOURCETABLE=@CSCH2,
			@CDESTDB='',
			@CDESTTABLE='SCHEME_SETUP_SCH0002_1',
			@CKEYFIELD1='ROW_ID',
			@CKEYFIELD2='',
			@CKEYFIELD3='',
			@LINSERTONLY=0,
			@CFILTERCONDITION='',
			@LUPDATEONLY=0,
			@BALWAYSUPDATE=1					

			SET @NSTEP=895
			EXEC UPDATEMASTERXN_MIRROR 
			@CSOURCEDB='',
			@CSOURCETABLE=@CSCH7,
			@CDESTDB='',
			@CDESTTABLE='SCHEME_SETUP_SCH0007_1',
			@CKEYFIELD1='ROW_ID',
			@CKEYFIELD2='',
			@CKEYFIELD3='',
			@LINSERTONLY=0,
			@CFILTERCONDITION='',
			@LUPDATEONLY=0,
			@BALWAYSUPDATE=1	
			
			SET @NSTEP=900
			EXEC UPDATEMASTERXN_MIRROR 
			@CSOURCEDB='',
			@CSOURCETABLE=@CSCH6,
			@CDESTDB='',
			@CDESTTABLE='SCHEME_SETUP_SCH0006_1',
			@CKEYFIELD1='ROW_ID',
			@CKEYFIELD2='',
			@CKEYFIELD3='',
			@LINSERTONLY=0,
			@CFILTERCONDITION='',
			@LUPDATEONLY=0,
			@BALWAYSUPDATE=1					

			SET @NSTEP=910
			EXEC UPDATEMASTERXN_MIRROR 
			@CSOURCEDB='',
			@CSOURCETABLE=@CSCH_B,
			@CDESTDB='',
			@CDESTTABLE='SCHEME_SETUP_SCHB001_1',
			@CKEYFIELD1='ROW_ID',
			@CKEYFIELD2='',
			@CKEYFIELD3='',
			@LINSERTONLY=0,
			@CFILTERCONDITION='',
			@LUPDATEONLY=0,
			@BALWAYSUPDATE=1					
									
			SET @NSTEP=920
			EXEC UPDATEMASTERXN_MIRROR 
			@CSOURCEDB='',
			@CSOURCETABLE=@CTEMHAPPYHOURSTABLENAME,
			@CDESTDB='',
			@CDESTTABLE='SCHEME_SETUP_HAPPYHOURS',
			@CKEYFIELD1='ROW_ID',
		    @CKEYFIELD2='',
			@CKEYFIELD3='',
			@LINSERTONLY=0,
			@CFILTERCONDITION='',
			@LUPDATEONLY=0,
			@BALWAYSUPDATE=1
						
			SET @NSTEP=950
			EXEC UPDATEMASTERXN_MIRROR 
			@CSOURCEDB='',
			@CSOURCETABLE=@CTEMPLOCTABLENAME,
			@CDESTDB='',
			@CDESTTABLE='SCHEME_SETUP_LOC',
			@CKEYFIELD1='MEMO_NO',
			 @CKEYFIELD2='',
			@CKEYFIELD3='',
			@LINSERTONLY=0,
			@CFILTERCONDITION='',
			@LUPDATEONLY=0,
			@BALWAYSUPDATE=1
								
			
			SET @NSTEP=980	
			EXEC UPDATEMASTERXN_MIRROR 
			@CSOURCEDB='',
			@CSOURCETABLE=@CTEMPLOCTABLENAME,
			@CDESTDB='',
			@CDESTTABLE='SCHEME_SETUP_LOC',
			@CKEYFIELD1='MEMO_NO',
			 @CKEYFIELD2='',
			@CKEYFIELD3='',
			@LINSERTONLY=0,
			@CFILTERCONDITION='',
			@LUPDATEONLY=0,
			@BALWAYSUPDATE=1
						
			
			SET @NSTEP=1010	
			EXEC UPDATEMASTERXN_MIRROR 
			@CSOURCEDB='',
			@CSOURCETABLE=@CTEMPCONFIGTABLENAME,
			@CDESTDB='',
			@CDESTTABLE='CONFIG',
			@CKEYFIELD1='CONFIG_OPTION',
			@CKEYFIELD2='',
			@CKEYFIELD3='',
			@LINSERTONLY=0,
			@CFILTERCONDITION='',
			@LUPDATEONLY=0,
			@BALWAYSUPDATE=1
												
			
    
 LBLLAST:  
    
  SET @NSTEP=1030 
    
  --- ON SUCCESSFUL MERGING , DELETE ENTRY FROM XN HISTORY     
  IF @CERRORMSG=''  
  BEGIN  
	   DELETE FROM XN_HISTORY WHERE XN_TYPE=@CXNTYPE AND MEMO_ID=@CMEMOID  
	     
	   IF @@TRANCOUNT>0  
	   BEGIN  
		PRINT 'SUCCESS'  
		COMMIT TRANSACTION  
		SET @CCMD = N'IF OBJECT_ID ('''+@CTEMPMASTERTABLENAME+''',''U'') IS NOT NULL
						DROP TABLE '+@CTEMPMASTERTABLENAME+'
					IF OBJECT_ID ('''+@CTEMPDETAILTABLENAME+''',''U'') IS NOT NULL
						DROP TABLE '+@CTEMPDETAILTABLENAME+'
					IF OBJECT_ID ('''+@CTEMPLOCTABLENAME+''',''U'') IS NOT NULL
						DROP TABLE '+@CTEMPLOCTABLENAME+'
					IF OBJECT_ID ('''+@CTEMPSLSBCTABLENAME+''',''U'') IS NOT NULL
						DROP TABLE '+@CTEMPSLSBCTABLENAME+'
					IF OBJECT_ID ('''+@CTEMPSLSBCGETTABLENAME+''',''U'') IS NOT NULL
					    DROP TABLE '+@CTEMPSLSBCGETTABLENAME+'
					IF OBJECT_ID ('''+@CTEMPSLSARTTABLENAME+''',''U'') IS NOT NULL
						DROP TABLE '+@CTEMPSLSARTTABLENAME+'
					IF OBJECT_ID ('''+@CTEMPSLSARTGETTABLENAME+''',''U'') IS NOT NULL
						DROP TABLE '+@CTEMPSLSARTGETTABLENAME+'
					IF OBJECT_ID ('''+@CTEMPMASTERTABLENAME+''',''U'') IS NOT NULL
						DROP TABLE '+@CTEMPMASTERTABLENAME+'
					IF OBJECT_ID ('''+@CTEMPSLSPARATABLENAME+''',''U'') IS NOT NULL
						DROP TABLE '+@CTEMPSLSPARATABLENAME+'
					IF OBJECT_ID ('''+@CTEMPSLSPARAGETTABLENAME+''',''U'') IS NOT NULL
						DROP TABLE '+@CTEMPSLSPARAGETTABLENAME+'
					IF OBJECT_ID ('''+@CSCH2+''',''U'') IS NOT NULL
						DROP TABLE '+@CSCH2+'
					IF OBJECT_ID ('''+@CSCH7+''',''U'') IS NOT NULL
						DROP TABLE '+@CSCH7+'						
					IF OBJECT_ID ('''+@CSCH6+''',''U'') IS NOT NULL
						DROP TABLE '+@CSCH6+'
					IF OBJECT_ID ('''+@CSCH_B+''',''U'') IS NOT NULL
						DROP TABLE '+@CSCH_B+'												
					IF OBJECT_ID ('''+@CTEMPCONFIGTABLENAME+''',''U'') IS NOT NULL
						DROP TABLE '+@CTEMPCONFIGTABLENAME+''
				
				PRINT @CCMD
				--EXEC SP_EXECUTESQL @CCMD	
						
						
	
		
	   END   
  END  
  ELSE  
  BEGIN  
	   IF @@TRANCOUNT>0  
		ROLLBACK    
  END   
    
  SET @NSTEP=1060 
  
  GOTO END_PROC  
    
 END TRY  
  
 BEGIN CATCH  
    
  PRINT 'UNTRAPPED ERROR'    
  SELECT @CERRORMSG='PROCEDURE : '+ISNULL(ERROR_PROCEDURE(),'NULL P')+'STEP: '+STR(@NSTEP)+' LINE NO. :'+  
  ISNULL(LTRIM(RTRIM(STR(ERROR_LINE()))),'NULL LINE')+'MSG :'+ISNULL(ERROR_MESSAGE(),'NULL MSG')  
    
  SET @CRETCMD='SELECT '''' AS MEMO_ID,'''''+@CERRORMSG+''''' AS ERRMSG'  
    
  PRINT 'RETURN VALUE : '+ISNULL(@CRETCMD,'NULL RETCMD')+@CMEMOID  
  --EXEC SP_EXECUTESQL @CRETCMD  
    
    
  IF @@TRANCOUNT>0  
   ROLLBACK    
  
  IF CURSOR_STATUS('GLOBAL','DELCUR') IN (0,1)  
  BEGIN  
   CLOSE DELCUR  
   DEALLOCATE DELCUR  
  END  
    
  IF CURSOR_STATUS('GLOBAL','MERGECUR') IN (0,1)  
  BEGIN  
   CLOSE MERGECUR  
   DEALLOCATE MERGECUR  
  END  
    
  GOTO END_PROC
 END CATCH  

END_PROC:
    
    
  INSERT @TRETMSG  
  SELECT 'MSTEOSS',ISNULL(@CERRORMSG,'') 
    
  SELECT * FROM @TRETMSG  
    
END  
--- END OF CREATING PROCEDURE SP_MERGEMSTEOSSDATA
