CREATE PROCEDURE SP3S_IMAGE_LIST_FOR_BASE64
AS
BEGIN
DECLARE @DB VARCHAR(100),@PATH VARCHAR(100),@CCMD NVARCHAR(MAX),@ERR INT=0,@ERR_MSG VARCHAR(100)='',@bCreate BIT
SET @DB=DB_NAME()+'_IMAGE'

SET @CCMD=N'
SELECT IMG_ID,PROD_IMAGE,PROD_IMAGE_BASE64 FROM '+@DB+'..IMAGE_INFO WHERE ISNULL(PROD_IMAGE_BASE64 ,'''')='''' AND ISNULL(CONVERT(VARCHAR(MAX),PROD_IMAGE),'''')<>''''
'

PRINT @CCMD   
EXEC(@CCMD)

SET @CCMD=N'
SELECT IMG_ID,PROD_IMAGE1,PROD_IMAGE1_BASE64 FROM '+@DB+'..IMAGE_INFO WHERE ISNULL(PROD_IMAGE1_BASE64 ,'''')='''' AND ISNULL(CONVERT(VARCHAR(MAX),PROD_IMAGE1),'''')<>''''
'

PRINT @CCMD   
EXEC(@CCMD)
SET @CCMD=N'
SELECT IMG_ID,PROD_IMAGE2,PROD_IMAGE2_BASE64 FROM '+@DB+'..IMAGE_INFO WHERE ISNULL(PROD_IMAGE2_BASE64 ,'''')='''' AND ISNULL(CONVERT(VARCHAR(MAX),PROD_IMAGE2),'''')<>''''
'

PRINT @CCMD   
EXEC(@CCMD)
SET @CCMD=N'
SELECT IMG_ID,PROD_IMAGE3,PROD_IMAGE3_BASE64 FROM '+@DB+'..IMAGE_INFO WHERE ISNULL(PROD_IMAGE3_BASE64 ,'''')='''' AND ISNULL(CONVERT(VARCHAR(MAX),PROD_IMAGE3),'''')<>''''
'

PRINT @CCMD   
EXEC(@CCMD)
SET @CCMD=N'
SELECT IMG_ID,PROD_IMAGE4,PROD_IMAGE4_BASE64 FROM '+@DB+'..IMAGE_INFO WHERE ISNULL(PROD_IMAGE4_BASE64 ,'''')='''' AND ISNULL(CONVERT(VARCHAR(MAX),PROD_IMAGE4),'''')<>''''
'

PRINT @CCMD   
EXEC(@CCMD)
END