CREATE PROCEDURE SP_STRUCOMP_DYNAMIC
@CLOCID CHAR(2),
@CXNTYPE VARCHAR(10),
@CTARGETDB VARCHAR(200)='',
@CTABLESSTR VARCHAR(MAX)='',
@CERRMSG VARCHAR(MAX) OUTPUT
--WITH ENCRYPTION
AS
BEGIN
	DECLARE @NSTEP INT,@CCMD NVARCHAR(MAX),@CTABLENAME VARCHAR(200),@CCOLNAME VARCHAR(200),@CSOURCECOLDT VARCHAR(20),
			@NSOURCECOLLENGTH INT,@NSOURCECOLXPREC INT,@NSOURCECOLXSCALE INT,@BSOURCECOLNULLABLE BIT,
			@CBASETABLENAME VARCHAR(500),@BTABLENOTFOUND BIT,@BFIRSTCOL BIT,@CCREATETBLEXPR NVARCHAR(MAX),
			@CSOURCECOLLENGTH VARCHAR(10),@BCOLNOTFOUND BIT,@BCOLMISMATCH BIT,@CDEFAULTVAL VARCHAR(200),
			@CTARGETCOLDT VARCHAR(20),@NTARGETCOLXPREC INT,@NTARGETCOLXSCALE INT,@BTARGETCOLNULLABLE BIT,
			@NTARGETCOLLENGTH INT,@CDEFAULTCONSTVAL VARCHAR(200),@CSCCAPTION VARCHAR(50)
		
	DECLARE @TTARGETDBINFO TABLE (TABLENAME VARCHAR(500),COLNAME VARCHAR(500),COLDATATYPE VARCHAR(20),
								  COLLENGTH NUMERIC(5,0),COLXPREC NUMERIC(5,0),COLXSCALE NUMERIC(2,0),
							      ISCOLNULLABLE BIT,DEFAULTVAL VARCHAR(200))

	DECLARE @TTABLESLIST TABLE (TABLENAME VARCHAR(200),COLNAME VARCHAR(200),COLDATATYPE VARCHAR(10),COLLENGTH INT,
								COLXPREC INT,COLXSCALE INT,ISCOLNULLABLE BIT,DEFAULTVAL VARCHAR(500))
	
	DECLARE @TSTRUDIFF TABLE (CMDSTR VARCHAR(MAX))
	
	
	BEGIN TRY
	
		SET @NSTEP=10
		
		SET @CERRMSG = ''
		
		IF @CTARGETDB=''
			SET @CTARGETDB='WIZAPP3S_MIRROR_'+@CLOCID+'.DBO.'
		
		IF @CTABLESSTR=''
		BEGIN
			SET @NSTEP=20
			IF @CXNTYPE='SLS'
				SET @CTABLESSTR='''CMM01106'',''CMM01106_AUDIT'',''CMD01106'',''CMD01106_AUDIT'',
								''CMR01106'',''CUSTDYM'',''PREFIX'',''EMPLOYEE'',''PAYMODE_XN_DET'',''PAYMODE_MST'',
								''PAYMODE_GRP_MST'',''SKU'',''LM01106'',''HD01106'',''LMP01106'',''AREA'',''CITY'',
								''STATE'''
			ELSE
			IF @CXNTYPE='PUR'	
				SET @CTABLESSTR='''PIM01106'',''PID01106'',''PIM01106_AUDIT'',''PID01106_AUDIT'',,''SKU_BO'',''ARTICLE'',''SECTIOND'',
								''SECTIONM'',''PARA1'',''PARA2'',''PARA3'',''PARA4'',''PARA5'',''PARA6'',''SKU'',
								''SKU_OH'',''ART_ATTR'',''ATTRM'',''ATTR_KEY'',''FORM'',''UOM'',''LM01106'',''HD01106'',
								''LMP01106'',''AREA'',''CITY'',''STATE'''
			ELSE
			IF @CXNTYPE='WSL'	
				SET @CTABLESSTR='''INM01106'',''IND01106'',''INM01106_AUDIT'',''IND01106_AUDIT'',''EMPLOYEE'',''LM01106'',''HD01106'',''LMP01106'',
								''AREA'',''CITY'',''STATE'',''FORM'',''PAYMODE_XN_DET'',''PAYMODE_GRP_MST'',''PAYMODE_MST'',
								''EMPLOYEE'''
			ELSE
			IF @CXNTYPE='PO'
				SET @CTABLESSTR='''POM01106'',''POD01106'',''PARA1'',''PARA2'',''PARA3'',''PARA4'',''PARA5'',''PARA6'',''SKU'',
								 ''ART_ATTR'',''ATTRM'',''ATTR_KEY'',''FORM'',''UOM'',''LM01106'',''HD01106'',
								''LMP01106'',''AREA'',''CITY'',''STATE'''
			ELSE	
				SET @CTABLESSTR='''INM01106'''				
				
					
		END		
		
		SET @NSTEP=30
		SET @CCMD=N'SELECT TABLENAME ,COLNAME,COLDATATYPE,COLLENGTH,COLXPREC,COLXSCALE,ISCOLNULLABLE,DEFAULTVAL
					FROM W3S_TABLE_STRUCTURES WHERE TABLENAME IN ('+@CTABLESSTR+')'
		
		PRINT @CCMD
		INSERT @TTABLESLIST
		EXEC SP_EXECUTESQL @CCMD
		
		SET @NSTEP=40
		SET @CCMD=N'SELECT C.NAME AS TABLENAME,A.NAME AS COLNAME,B.NAME AS COLDATATYPE,A.LENGTH AS COLLENGTH,A.XPREC AS COLXPREC,
				   A.XSCALE AS COLXSCALE,A.ISNULLABLE AS ISCOLNULLABLE,ISNULL(D.TEXT,'''') AS DEFAULTVAL
				   FROM '+@CTARGETDB+'SYSCOLUMNS A
				   JOIN '+@CTARGETDB+'SYSTYPES B ON A.XTYPE=B.XTYPE AND B.XUSERTYPE=A.XUSERTYPE
				   JOIN '+@CTARGETDB+'SYSOBJECTS C ON A.ID=C.ID	
				   LEFT OUTER JOIN
					(SELECT A.ID,A.COLID,C.TEXT FROM '+@CTARGETDB+'SYSCONSTRAINTS A 
					 JOIN '+@CTARGETDB+'SYSOBJECTS B ON A.CONSTID=B.ID
					 JOIN '+@CTARGETDB+'SYSCOMMENTS C ON A.CONSTID = C.ID 
					 JOIN '+@CTARGETDB+'SYSOBJECTS D ON D.ID = A.ID 
					 WHERE D.NAME IN ('+@CTABLESSTR+') AND B.XTYPE=''D'') D ON D.ID=C.ID AND D.COLID=A.COLID			   
				   WHERE C.XTYPE=''U'' AND C.NAME IN ('+@CTABLESSTR+')'
		
		PRINT @CCMD
		
		INSERT @TTARGETDBINFO
		EXEC SP_EXECUTESQL @CCMD
		
		SET @NSTEP=50
		DECLARE SOURCEDBCUR CURSOR FOR SELECT TABLENAME ,COLNAME,COLDATATYPE,COLLENGTH,COLXPREC,COLXSCALE,ISCOLNULLABLE,DEFAULTVAL
		FROM @TTABLESLIST ORDER BY TABLENAME

		IF CURSOR_STATUS('GLOBAL','SOURCEDBCUR') IN (0,1)
		BEGIN
			CLOSE SOURCEDBCUR
			DEALLOCATE SOURCEDBCUR
		END
		
		SET @NSTEP=60
		OPEN SOURCEDBCUR
		FETCH NEXT FROM SOURCEDBCUR INTO @CTABLENAME,@CCOLNAME,@CSOURCECOLDT,@NSOURCECOLLENGTH,@NSOURCECOLXPREC,
										 @NSOURCECOLXSCALE,@BSOURCECOLNULLABLE,@CDEFAULTCONSTVAL
		WHILE @@FETCH_STATUS=0
		BEGIN

			SET @NSTEP=70
			SELECT @CBASETABLENAME=@CTABLENAME,@CCREATETBLEXPR='',@BFIRSTCOL=0,@BTABLENOTFOUND=0
			
			WHILE @CTABLENAME=@CBASETABLENAME AND @@FETCH_STATUS=0
			BEGIN
				
				SET @NSTEP=80
				IF @NSOURCECOLLENGTH>0
					SET @CSOURCECOLLENGTH=LTRIM(RTRIM(STR(@NSOURCECOLLENGTH)))
				ELSE
					SET @CSOURCECOLLENGTH='MAX'
							
				IF EXISTS (SELECT TABLENAME FROM @TTARGETDBINFO WHERE TABLENAME=@CTABLENAME)
				BEGIN
					SET @NSTEP=100
					SELECT @BCOLNOTFOUND=0,@BCOLMISMATCH=0
					
					IF @CSOURCECOLDT IN ('NUMERIC','DECIMAL','MONEY','REAL','SMALLMONEY','INT','TINYINT','BIGINT','BIT')			
						SET @CDEFAULTVAL='0'
					ELSE
						SET @CDEFAULTVAL=''''''
					
					SET @NSTEP=110
					
					
					IF NOT EXISTS (SELECT COLNAME FROM @TTARGETDBINFO WHERE TABLENAME=@CTABLENAME AND COLNAME=@CCOLNAME)
						SET @BCOLNOTFOUND=1
					ELSE
					BEGIN
						SET @NSTEP=120
						SELECT @CTARGETCOLDT=COLDATATYPE,@NTARGETCOLXPREC=COLXPREC,@NTARGETCOLXSCALE=COLXSCALE,
							   @BTARGETCOLNULLABLE=ISCOLNULLABLE,@NTARGETCOLLENGTH=COLLENGTH
						FROM @TTARGETDBINFO WHERE TABLENAME=@CTABLENAME AND COLNAME=@CCOLNAME
						
						
						--IGNORE THE COMPARISON OF TS COLUMN 
						IF  @CCOLNAME<>'TS' AND (@CTARGETCOLDT<>@CSOURCECOLDT OR @NSOURCECOLXPREC<>@NTARGETCOLXPREC OR
							@NSOURCECOLXSCALE<>@NTARGETCOLXSCALE OR @NTARGETCOLLENGTH<>@NSOURCECOLLENGTH
							OR (@BTARGETCOLNULLABLE<>@BSOURCECOLNULLABLE))
					   		SET @BCOLMISMATCH=1
						ELSE
							SET @BCOLMISMATCH=0
								
					END
					
					IF @BCOLMISMATCH=1 OR @BCOLNOTFOUND=1
					BEGIN
						SET @NSTEP=130
							
						IF ISNULL(@CDEFAULTCONSTVAL,'')<>''
							SET @CDEFAULTVAL=@CDEFAULTCONSTVAL
						
						SET @NSTEP=140		
						SET @CCMD=N'ALTER TABLE '+@CTARGETDB+@CTABLENAME+(CASE WHEN @BCOLMISMATCH=1 THEN ' ALTER COLUMN ' ELSE ' ADD ' END)+
								  @CCOLNAME+' '+@CSOURCECOLDT+(CASE WHEN @CSOURCECOLDT NOT IN ('DATETIME','SMALLDATETIME',
								  'TIMESTAMP','BIT','IMAGE','INT','TINYINT','SMALLINT','BIGINT','TEXT','NTEXT','VARBINARY','SYSNAME')
								   THEN '('+(CASE WHEN @CSOURCECOLDT IN ('NUMERIC','DECIMAL','MONEY','REAL','SMALLMONEY')
												  THEN LTRIM(RTRIM(STR(@NSOURCECOLXPREC)))+','+LTRIM(RTRIM(STR(@NSOURCECOLXSCALE)))+')'
												  ELSE @CSOURCECOLLENGTH+')' END)  ELSE '' END)+
								   (CASE WHEN @CSOURCECOLDT NOT IN ('TIMESTAMP') THEN 
								   (CASE WHEN @BSOURCECOLNULLABLE=0 THEN ' NOT NULL '	 ELSE '' END)+
								   (CASE WHEN @BCOLNOTFOUND=1 AND @BSOURCECOLNULLABLE=0 THEN ' DEFAULT '+@CDEFAULTVAL ELSE '' END)
									ELSE '' END)
									    
						PRINT @CCMD
						
						INSERT @TSTRUDIFF
						SELECT @CCMD
						
						EXEC SP_EXECUTESQL @CCMD						   	
					END
								
				END
				ELSE
				BEGIN
					SET @NSTEP=170
					SET @BTABLENOTFOUND=1
					IF @CCREATETBLEXPR=''
						SET @CCREATETBLEXPR='CREATE TABLE '+@CTARGETDB+@CTABLENAME+'('		
						
					SET @NSTEP=180	
					SET @CCREATETBLEXPR=@CCREATETBLEXPR+(CASE WHEN @BFIRSTCOL=1 THEN ',' ELSE ' ' END)+
										@CCOLNAME+' '+@CSOURCECOLDT+(CASE WHEN @CSOURCECOLDT NOT IN 
										('DATETIME','SMALLDATETIME','TIMESTAMP','BIT','IMAGE','INT','TINYINT',
										 'SMALLINT','BIGINT','TEXT','NTEXT','SYSNAME','VARBINARY')
										THEN '('+(CASE WHEN @CSOURCECOLDT IN ('NUMERIC','DECIMAL','MONEY',
										'REAL','SMALLMONEY')  THEN LTRIM(RTRIM(STR(@NSOURCECOLXPREC)))+','+
										LTRIM(RTRIM(STR(@NSOURCECOLXSCALE)))+')' ELSE @CSOURCECOLLENGTH+')' END)
										ELSE '' END)+(CASE WHEN @CSOURCECOLDT NOT IN ('TIMESTAMP')  THEN 
										(CASE WHEN @BSOURCECOLNULLABLE=0 THEN ' NOT NULL '	 ELSE '' END)	
										ELSE '' END)
										
					IF @BFIRSTCOL=0
						SET @BFIRSTCOL=1
						
				END	
				
				SET @NSTEP=190
				--PRINT 'TABLENAME : '+@CTABLENAME+' COLUMNNAME : '+@CCOLNAME
				FETCH NEXT FROM SOURCEDBCUR INTO @CTABLENAME,@CCOLNAME,@CSOURCECOLDT,@NSOURCECOLLENGTH,
												 @NSOURCECOLXPREC,@NSOURCECOLXSCALE,@BSOURCECOLNULLABLE,@CDEFAULTCONSTVAL
			END	
			
			IF @BTABLENOTFOUND=1
			BEGIN
				SET @NSTEP=200
				SET @CCREATETBLEXPR=@CCREATETBLEXPR+')'
				
				INSERT @TSTRUDIFF
				SELECT @CCREATETBLEXPR

				PRINT @CCREATETBLEXPR
				EXEC SP_EXECUTESQL @CCREATETBLEXPR
			END	
										 
		END					

		SET @NSTEP=210		     
		CLOSE SOURCEDBCUR
		DEALLOCATE SOURCEDBCUR
		
		GOTO END_PROC
	END TRY
	
	BEGIN CATCH
		SET @CERRMSG='P:SP_STRUCOMP_DYNAMIC, STEP:'+LTRIM(RTRIM(STR(@NSTEP)))+', MESSAGE:'+ERROR_MESSAGE()
		GOTO END_PROC
	END CATCH

END_PROC:
		
	--SELECT * FROM @TSTRUDIFF
END
