CREATE PROCEDURE SP3S_DELETE_WPS_MIRROR_TABLES
@cMemoId VARCHAR(50)
AS
BEGIN
	DECLARE @cMemoIdCopy VARCHAR(50)
	
	SET @cMemoIdCopy=@cMemoId+LEFT(@cMemoId,2)

	TRUNCATE TABLE #t

	INSERT #T
	SELECT ps_ID
	FROM WPS_WPS_MST_MIRROR B (NOLOCK) WHERE PS_id=@cMemoId OR PS_id=@cMemoIdCopy

	DELETE A FROM WPS_WPS_DET_MIRROR A JOIN #T B ON  A.PS_ID=B.PS_ID
	DELETE A FROM WPS_WPS_MST_MIRROR A JOIN #T B ON  A.PS_ID=B.PS_ID
	DELETE A FROM WPS_PMT01106_MIRROR A JOIN #T B ON  A.WPS_MEMO_ID=B.PS_ID
END		