CREATE PROCEDURE SP3S_EXCELFRORMAT_SOR
AS
BEGIN
    
select 0 as SR, 'PRODUCT_CODE' AS COLUMN_NAME, 'Product Code' AS column_caption , cast(0 as bit ) as OPEN_KEY 
UNION 
select 5 as SR, 'ARTICLE_NO' AS COLUMN_NAME, 'Article No' AS column_caption , cast(0 as bit ) as OPEN_KEY 
UNION
select 10 as SR, 'SECTION_NAME' AS COLUMN_NAME, 'Section Name' AS column_caption , cast(0 as bit ) as OPEN_KEY 
UNION
select  15 as SR,'SUB_SECTION_NAME' AS COLUMN_NAME, 'Sub Section Name' AS column_caption , cast(0 as bit ) as OPEN_KEY 
UNION	       
SELECT TOP 1 20 as SR,'PARA1_NAME' AS COLUMN_NAME,VALUE ,cast(0 as bit ) as OPEN_KEY  FROM CONFIG WHERE CONFIG_OPTION='PARA1_caption' 
UNION	       
SELECT TOP 1 25 as SR, 'PARA2_NAME' AS COLUMN_NAME,VALUE ,cast(0 as bit ) as OPEN_KEY  FROM CONFIG WHERE CONFIG_OPTION='PARA2_caption' 
UNION	       
SELECT TOP 1 30 as SR,'PARA3_NAME' AS COLUMN_NAME,VALUE ,cast(0 as bit ) as OPEN_KEY  FROM CONFIG WHERE CONFIG_OPTION='PARA3_caption' 
UNION	       
SELECT TOP 1 35 as SR,'PARA4_NAME' AS COLUMN_NAME,VALUE ,cast(0 as bit ) as OPEN_KEY  FROM CONFIG WHERE CONFIG_OPTION='PARA4_caption' 
UNION	       
SELECT TOP 1 40 as SR,'PARA5_NAME' AS COLUMN_NAME,VALUE ,cast(0 as bit ) as OPEN_KEY  FROM CONFIG WHERE CONFIG_OPTION='PARA5_caption' 
UNION	       
SELECT TOP 1 45 as SR,'PARA6_NAME' AS COLUMN_NAME,VALUE ,cast(0 as bit ) as OPEN_KEY  FROM CONFIG WHERE CONFIG_OPTION='PARA6_caption' 
UNION
SELECT 50 AS SR, COLUMN_NAME, TABLE_CAPTION AS COLUMN_CAPTION , CAST(0 AS BIT ) AS OPEN_KEY FROM CONFIG_ATTR WHERE TABLE_CAPTION <> ''
ORDER BY SR

END





