CREATE PROCEDURE  SP_PRD_ISSUE_SAMPLE
(
 @NQUERYID INT,
 @CMEMO_ID VARCHAR (100)='',
 @NISSUE_TYPE INT=0
)
AS
BEGIN

IF @NQUERYID=1
   GOTO LBLMST
ELSE IF @NQUERYID=2
   GOTO LBLDET
ELSE IF @NQUERYID=3
   GOTO LBLBAROCE_DET

LBLMST:
    
    IF @CMEMO_ID=''
    BEGIN
    SELECT MEMO_NO=CAST('LATER' AS VARCHAR(15)),
	MEMO_ID=CAST('LATER' AS VARCHAR(25)),
	FIN_YEAR=CAST('' AS VARCHAR(6)),
	MEMO_DT=CAST('' AS DATETIME),
    LAST_UPDATE=CAST('' AS DATETIME),
	CANCELLED=CAST(0 AS BIT),
	USER_CODE=CAST('' AS VARCHAR(10)),
	DEPARTMENT_ID=CAST('' AS VARCHAR(10)),
	REMARKS=CAST('' AS VARCHAR(MAX)),
	REF_ISSUE_ID=CAST('' AS VARCHAR(25)),
	BIN_ID=CAST('000' AS VARCHAR(3)),
	ISSUE_TYPE=CAST(0 AS INT) 
	WHERE 1=2
	END
	ELSE
	BEGIN
	SELECT MEMO_NO,
	MEMO_ID,
	FIN_YEAR,
	MEMO_DT,
    LAST_UPDATE,
	CANCELLED,
	USER_CODE,
	DEPARTMENT_ID,
	REMARKS,
	REF_ISSUE_ID,
	BIN_ID,
	ISSUE_TYPE
	FROM PRD_AGENCY_ISSUE_MATERIAL_MST_SAMPLE
	WHERE REF_ISSUE_ID=@CMEMO_ID AND ISSUE_TYPE=@NISSUE_TYPE
	END
GOTO END_PROC

LBLDET:
    IF @CMEMO_ID=''
    BEGIN
	SELECT CHK=CAST(0 AS BIT), MEMO_ID=CAST('LATER' AS VARCHAR(25)),
	PRODUCT_CODE=CAST('' AS VARCHAR(1000)),
	PRODUCT_CODE_TYPE=CAST(0 AS INT),
	QUANTITY=CAST(0 AS NUMERIC(12,3)),
	ROW_ID=CAST('LATER'+CAST( NEWID()AS VARCHAR(100)) AS VARCHAR(100)),
	LAST_UPDATE=GETDATE(),
	EMP_CODE=CAST('' AS VARCHAR(10)),
	ARTICLE_NO=CAST('' AS VARCHAR(100)),
	ARTICLE_NAME=CAST('' AS VARCHAR(100)),
	PARA1_NAME=CAST('' AS VARCHAR(100)),
	PARA2_NAME=CAST('' AS VARCHAR(100)),
	PARA3_NAME=CAST('' AS VARCHAR(100)),
	PARA4_NAME=CAST('' AS VARCHAR(100)),
	PARA5_NAME=CAST('' AS VARCHAR(100)),
	PARA6_NAME=CAST('' AS VARCHAR(100)),
	SECTION_NAME=CAST('' AS VARCHAR(100)),
	SUB_SECTION_NAME=CAST('' AS VARCHAR(100)),
	[PRODUCT_UID]=CAST('' AS VARCHAR(100)),
	RATE=CAST(0 AS NUMERIC(10,2)),
	UOM_NAME=CAST('' AS VARCHAR(10)),
	ITEM_REMARKS=CAST('' AS VARCHAR(MAX))
	WHERE 1=2
    END
    ELSE
    BEGIN
    SELECT CHK=CAST(0 AS BIT), A.MEMO_ID, B.PRODUCT_CODE,
	PRODUCT_CODE_TYPE,
	QUANTITY,ROW_ID,B.LAST_UPDATE,B.EMP_CODE,AR.ARTICLE_NO AS ARTICLE_NO,
	AR.ARTICLE_NAME AS ARTICLE_NAME,PARA1_NAME,PARA2_NAME,
	PARA3_NAME,PARA4_NAME,PARA5_NAME,PARA6_NAME,
	SECTION_NAME,SUB_SECTION_NAME,
	B.PRODUCT_UID,0 AS RATE,
	UOM_NAME, ITEM_REMARKS,
	A.ISSUE_TYPE 
	FROM PRD_AGENCY_ISSUE_MATERIAL_MST_SAMPLE A
	JOIN PRD_AGENCY_ISSUE_MATERIAL_DET_SAMPLE B ON A.MEMO_ID=B.MEMO_ID
	LEFT OUTER JOIN PRD_SKU C ON B.PRODUCT_UID=C.PRODUCT_UID AND B.PRODUCT_CODE_TYPE=2
	LEFT OUTER JOIN SKU ON SKU.PRODUCT_CODE=B.PRODUCT_CODE AND B.PRODUCT_CODE_TYPE=1
	LEFT OUTER JOIN ARTICLE AR ON AR.ARTICLE_CODE=ISNULL(SKU.ARTICLE_CODE,C.ARTICLE_CODE)
	LEFT JOIN PARA1 P1 ON P1.PARA1_CODE =ISNULL(C.PARA1_CODE,SKU.PARA1_CODE)
	LEFT JOIN PARA2 P2 ON P2.PARA2_CODE =ISNULL(C.PARA2_CODE,SKU.PARA2_CODE)
	LEFT JOIN PARA3 P3 ON P3.PARA3_CODE =ISNULL(C.PARA3_CODE,SKU.PARA3_CODE)
	LEFT JOIN PARA4 P4 ON P4.PARA4_CODE =ISNULL(C.PARA4_CODE,SKU.PARA4_CODE)
	LEFT JOIN PARA5 P5 ON P5.PARA5_CODE =ISNULL(C.PARA5_CODE,SKU.PARA5_CODE)
	LEFT JOIN PARA6 P6 ON P6.PARA6_CODE =ISNULL(C.PARA6_CODE,SKU.PARA6_CODE)
    LEFT OUTER JOIN UOM ON UOM.UOM_CODE=AR.UOM_CODE
    LEFT OUTER JOIN SECTIOND SD ON SD.SUB_SECTION_CODE=AR.SUB_SECTION_CODE
    LEFT OUTER JOIN SECTIONM SM ON SM.SECTION_CODE=SD.SECTION_CODE
    WHERE REF_ISSUE_ID=@CMEMO_ID AND  ISSUE_TYPE=@NISSUE_TYPE
    
    END
GOTO END_PROC

LBLBAROCE_DET:
     
     SELECT 1 AS PRODUCT_CODE_TYPE, 'RDY' AS TYPE, PRODUCT_CODE ,QUANTITY_IN_STOCK
     FROM PMT01106 WHERE QUANTITY_IN_STOCK>0
     UNION ALL
     SELECT 2 AS PRODUCT_CODE_TYPE, 'PRD' AS TYPE, PRODUCT_CODE ,QUANTITY_IN_STOCK
     FROM PRD_PMT WHERE QUANTITY_IN_STOCK>0
    
GOTO END_PROC

END_PROC:
END
