create PROCEDURE [DBO].[SP3S_INV_JOBCARD_ISSUE_9]          
(          
  @IMODE INT ,          
  @CWHERE VARCHAR(MAX)='',      
  @CAGENCYCODE VARCHAR(20)='',      
  @FINYEAR VARCHAR(10)=''  ,    
  @DEPTID VARCHAR(10)='' ,
  @NRETURNMODE INT=0
          
)      
----WITH ENCRYPTION
AS          
          
BEGIN        
 DECLARE @CCMD NVARCHAR(MAX) 
--LBLPENDINGJOBWORK: 9


	DECLARE @CMATERIAL_ISSUE_ONLY_ALLOCATED_STOCK VARCHAR(10),@CORDER_ID VARCHAR(30)
	SELECT @CMATERIAL_ISSUE_ONLY_ALLOCATED_STOCK=VALUE FROM CONFIG WHERE CONFIG_OPTION='MATERIAL_ISSUE_ONLY_ALLOCATED_STOCK'
	
  IF @NRETURNMODE=1
  BEGIN



       
    ;WITH PENDING_JOBISSUE
	AS
	(
			SELECT B.ISSUE_ID,B.ISSUE_NO,B.ISSUE_DT,B.AGENCY_CODE,A.*, 
			((A.AVG_QUANTITY+A.ADD_AVG_QUANTITY) * B.ISSUED_QTY) AS REQ_QTY, 
			B.ISSUED_QTY AS ISSUED_QTY_JW
			FROM ORD_PLAN_BOM_DET A (NOLOCK)
			JOIN
			(
				SELECT C.ROW_ID,A1.ISSUE_ID,A1.ISSUE_NO,A1.ISSUE_DT,A1.AGENCY_CODE,C.ARTICLE_CODE,C.PARA1_CODE,C.PARA2_CODE,a.job_code,
				CONVERT(NUMERIC(14,2),SUM(A.QUANTITY)) AS ISSUED_QTY
				FROM JOBWORK_ISSUE_DET A (NOLOCK)
				JOIN JOBWORK_ISSUE_MST A1 (NOLOCK) ON A1.ISSUE_ID=A.ISSUE_ID
				JOIN ORD_PLAN_BARCODE_DET B (NOLOCK) ON B.PRODUCT_CODE=A.PRODUCT_CODE
				JOIN ORD_PLAN_DET C (NOLOCK) ON C.ROW_ID=B.REFROW_ID
				JOIN ORD_PLAN_MST D (NOLOCK) ON D.MEMO_ID=C.MEMO_ID
				WHERE D.CANCELLED=0 AND ISNULL(D.SHORT_CLOSE,0)=0 AND A1.CANCELLED=0 AND A1.AGENCY_CODE=@CAGENCYCODE AND A1.location_Code =@DEPTID
				GROUP BY C.ROW_ID,A1.ISSUE_ID,A1.ISSUE_NO,A1.ISSUE_DT,A1.AGENCY_CODE, C.ARTICLE_CODE,C.PARA1_CODE,C.PARA2_CODE,a.job_code
			)B ON B.ROW_ID=A.REF_ROW_ID and a.JOB_CODE =b.job_code
			--JOIN JOBWORK_ISSUE_BOM C (NOLOCK) ON C.ISSUE_ID=B.ISSUE_ID AND C.ARTICLE_CODE=A.ARTICLE_CODE 
			--							AND C.PARA1_CODE=A.PARA1_CODE AND C.PARA2_CODE=A.PARA2_CODE
	)
	,TOTAL_BOM_ISSUE
	AS
    (
		SELECT  A1.MEMO_ID, A1.ROW_ID AS ROW_ID,
		SUM(CASE WHEN ISNULL(A5.issue_type,0)=0 THEN 1 ELSE -1 END* A6.QUANTITY) AS ISSUED_QTY
		FROM BOM_ISSUE_DET A4 (NOLOCK) 
		JOIN BOM_ISSUE_MST A5  (NOLOCK) ON A5.ISSUE_ID=A4.ISSUE_ID
		JOIN BOM_ISSUE_REF A6  (NOLOCK) ON A5.ISSUE_ID=A6.BOM_ISSUE_ID AND A4.ROW_ID=A6.BOM_DET_ROW_ID
		JOIN ORD_PLAN_BOM_DET A1  (NOLOCK) ON A1.ROW_ID=A6.ORD_PLAN_BOM_DET_ROW_ID
		WHERE A5.CANCELLED=0  AND A5.location_Code =@DEPTID--AND A1.MEMO_ID=@CWHERE 
		--and  a5.JOBWORK_ISSUE_ID=@CWHERE
		GROUP BY  A1.MEMO_ID, A1.ROW_ID 
	)
	,TOTAL_BOM_REQ
	AS
    (
		SELECT  A1.MEMO_ID, A1.ROW_ID AS ROW_ID,SUM(A1.QUANTITY) AS REQ_QTY
		FROM ORD_PLAN_BOM_DET A1  (NOLOCK) 
		GROUP BY  A1.MEMO_ID, A1.ROW_ID 
	)

	SELECT CAST(0 AS BIT) AS CHK,
	C.ISSUE_NO AS MEMO_NO,C.ISSUE_DT AS MEMO_DT,C.ISSUE_ID AS MEMO_ID,C.AGENCY_CODE,
	SUM(B.ISSUED_QTY) AS ISSUED_QTY,
	SUM(A.REQ_QTY) AS REQ_QTY,
	CONVERT(NUMERIC(14,2),SUM(ISNULL(B.ISSUED_QTY,0))) AS PENDING_QTY,
	CONVERT(NUMERIC(14,2),AVG(C.REQ_QTY)) AS ISSUED_QTY_JW,C.MEMO_ID as JOBCARD_ID
	FROM PENDING_JOBISSUE C
	JOIN  TOTAL_BOM_REQ A  ON C.ROW_ID=A.ROW_ID
	JOIN TOTAL_BOM_ISSUE B  ON B.MEMO_ID=A.MEMO_ID AND A.ROW_ID=B.ROW_ID
	WHERE ISNULL(B.ISSUED_QTY,0)>0 --AND C.REQ_QTY<=A.REQ_QTY
	GROUP BY C.ISSUE_NO ,C.ISSUE_DT ,C.ISSUE_ID ,C.AGENCY_CODE,C.MEMO_ID
	Union all --for sample Job card
	 SELECT CAST(0 AS BIT) AS CHK,
	C.ISSUE_NO AS MEMO_NO,C.ISSUE_DT AS MEMO_DT,C.ISSUE_ID AS MEMO_ID,C.AGENCY_CODE,
	SUM(CASE WHEN ISNULL(a.ISSUE_TYPE,0) =0 THEN  B.QUANTITY ELSE 0 END ) AS ISSUED_QTY,
	0 AS REQ_QTY,
	CONVERT(NUMERIC(14,2),SUM( (CASE WHEN ISNULL(a.ISSUE_TYPE,0) =0 THEN  1 ELSE -1 END) *ISNULL(B.Quantity,0))) AS PENDING_QTY,
	CONVERT(NUMERIC(14,2),0) AS ISSUED_QTY_JW,'' as JOBCARD_ID
	from BOM_ISSUE_MST a (nolock)
	join BOM_ISSUE_DET b (nolock) on a.issue_id=b.issue_id
	join jobwork_issue_mst c (nolock) on a.JOBWORK_ISSUE_ID=c.issue_id
	where a.cancelled =0 and isnull(a.JobCardType,0)=1
	group by C.ISSUE_NO ,C.ISSUE_DT ,C.ISSUE_ID ,C.AGENCY_CODE
    

	select issue_type, * from BOM_ISSUE_MST
       
  
  END
  ELSE
  BEGIN	
	
	IF OBJeCT_ID ('TEMPDB..#TMPPENDINGISSUE','U') IS NOT NULL
	   dROP TABLE #TMPPENDINGISSUE

	IF OBJeCT_ID ('TEMPDB..#TMPPENDINGISSUE','U') IS NOT NULL
	   dROP TABLE #TMPPENDINGISSUE


	   
	IF OBJECT_ID ('TEMPDB..#TMPISSUEID','U') IS NOT NULL
	   DROP TABLE #TMPISSUEID

	   SELECT A1.ISSUE_ID ,A1.ISSUE_NO ,A1.ISSUE_DT,A1.AGENCY_CODE   
	   INTO #TMPISSUEID
	   FROM JOBWORK_ISSUE_MST  A1
	   WHERE  A1.CANCELLED=0 
	   AND A1.AGENCY_CODE=@CAGENCYCODE AND A1.location_Code =@DEPTID
	   AND ISNULL(A1.ISSUE_MODE,0) =1

	   CREATE INDEX IX_ISSUE_ID_TMP ON #TMPISSUEID(ISSUE_ID)

	

	IF OBJeCT_ID ('TEMPDB..#TMPISSUE','U') IS NOT NULL
	   dROP TABLE #TMPISSUE


	   SELECT C.ROW_ID,A1.ISSUE_ID,A1.ISSUE_NO,A1.ISSUE_DT,A1.AGENCY_CODE,C.ARTICLE_CODE,C.PARA1_CODE,C.PARA2_CODE,a.job_code,
				convert(numeric(14,2),SUM(A.QUANTITY)) AS ISSUED_QTY
       INTO #TMPISSUE
	   FROM #TMPISSUEID A1  (NOLOCK)
	   JOIN JOBWORK_ISSUE_DET A (NOLOCK) ON A1.ISSUE_ID=A.ISSUE_ID
	   JOIN ORD_PLAN_BARCODE_DET B (NOLOCK) ON B.PRODUCT_CODE=A.PRODUCT_CODE
	   JOIN ORD_PLAN_DET C (NOLOCK) ON C.ROW_ID=B.REFROW_ID
	   JOIN ORD_PLAN_MST D (NOLOCK) ON D.MEMO_ID=C.MEMO_ID
	  WHERE D.CANCELLED=0 AND ISNULL(D.SHORT_CLOSE,0)=0
	  GROUP BY C.ROW_ID,A1.ISSUE_ID,A1.ISSUE_NO,A1.ISSUE_DT,A1.AGENCY_CODE, C.ARTICLE_CODE,C.PARA1_CODE,C.PARA2_CODE,a.job_code


	;WITH PENDING_JOBISSUE
	AS
	(
			SELECT B.ISSUE_ID,B.ISSUE_NO,B.ISSUE_DT,B.AGENCY_CODE,A.*, 
			((A.AVG_QUANTITY+A.ADD_AVG_QUANTITY) * B.ISSUED_QTY) AS REQ_QTY, 
			B.ISSUED_QTY AS ISSUED_QTY_JW
			FROM ORD_PLAN_BOM_DET A (NOLOCK)
			JOIN
			(
			SElECT * FROM #TMPISsUE A
				
			)B ON B.ROW_ID=A.REF_ROW_ID and a.JOB_CODE =b.job_code 
			--LEFT JOIN JOBWORK_ISSUE_BOM C (NOLOCK) ON C.ISSUE_ID=B.ISSUE_ID AND C.ARTICLE_CODE=A.ARTICLE_CODE 
			--							AND C.PARA1_CODE=A.PARA1_CODE AND C.PARA2_CODE=A.PARA2_CODE
	)
	,TOTAL_BOM_ISSUE
	AS
    (
		SELECT  A1.MEMO_ID, A1.ROW_ID AS ROW_ID,
		SUM(CASE WHEN ISNULL(A5.issue_type,0)=0 THEN 1 ELSE -1 END* A6.QUANTITY) AS ISSUED_QTY
		--SUM(A6.QUANTITY) AS ISSUED_QTY
		FROM BOM_ISSUE_DET A4 (NOLOCK) 
		JOIN BOM_ISSUE_MST A5  (NOLOCK) ON A5.ISSUE_ID=A4.ISSUE_ID
		JOIN BOM_ISSUE_REF A6  (NOLOCK) ON A5.ISSUE_ID=A6.BOM_ISSUE_ID AND A4.ROW_ID=A6.BOM_DET_ROW_ID
		JOIN ORD_PLAN_BOM_DET A1  (NOLOCK) ON A1.ROW_ID=A6.ORD_PLAN_BOM_DET_ROW_ID
		WHERE A5.CANCELLED=0  AND A5.location_Code =@DEPTID--AND A1.MEMO_ID=@CWHERE 
		GROUP BY  A1.MEMO_ID, A1.ROW_ID 
	)
	,TOTAL_BOM_REQ
	AS
    (
		SELECT  A1.MEMO_ID, A1.ROW_ID AS ROW_ID,SUM(A1.QUANTITY) AS REQ_QTY
		FROM ORD_PLAN_BOM_DET A1  (NOLOCK)
		JOIN ORD_PLAN_MST A2 (NOLOCK) ON A1.MEMO_ID =A2.MEMO_ID 
		WHERE  A2.location_code =@DEPTID 
		GROUP BY  A1.MEMO_ID, A1.ROW_ID 
	)
	

	SELECT CAST(0 AS BIT) AS CHK,
	C.ISSUE_NO AS MEMO_NO,C.ISSUE_DT AS MEMO_DT,C.ISSUE_ID AS MEMO_ID,C.AGENCY_CODE,
	SUM(B.ISSUED_QTY) AS ISSUED_QTY,
	SUM(A.REQ_QTY) AS REQ_QTY,
	CONVERT(NUMERIC(14,2),SUM(A.REQ_QTY)-SUM(ISNULL(B.ISSUED_QTY,0))) AS PENDING_QTY,
	CONVERT(NUMERIC(14,2),AVG(C.REQ_QTY)) AS ISSUED_QTY_JW,C.MEMO_ID AS JOBCARD_ID
	INTO #TMPPENDINGISSUE
	FROM PENDING_JOBISSUE C
	JOIN  TOTAL_BOM_REQ A  ON C.ROW_ID=A.ROW_ID
	LEFT OUTER JOIN TOTAL_BOM_ISSUE B  ON B.MEMO_ID=A.MEMO_ID AND A.ROW_ID=B.ROW_ID
	WHERE A.REQ_QTY>ISNULL(B.ISSUED_QTY,0) 
	GROUP BY C.ISSUE_NO ,C.ISSUE_DT ,C.ISSUE_ID ,C.AGENCY_CODE,C.MEMO_ID
     
	
	 if isnull(@CMATERIAL_ISSUE_ONLY_ALLOCATED_STOCK,'')='1'
	 begin
	     	SELECT * FROM #TMPPENDINGISSUE A 
	        WHERE A.REQ_QTY>ISNULL(A.ISSUED_QTY,0) --AND C.REQ_QTY<=A.REQ_QTY

	 end
	 else
	 begin
	     
			SELECT * FROM #TMPPENDINGISSUE A 
			WHERE A.REQ_QTY>ISNULL(A.ISSUED_QTY,0) --AND C.REQ_QTY<=A.REQ_QTY
			UNION
			SELECT CAST(0 AS BIT) AS CHK,B.ISSUE_NO AS MEMO_NO,B.ISSUE_DT AS MEMO_DT,B.ISSUE_ID AS MEMO_ID,B.AGENCY_CODE,
			0 AS ISSUED_QTY,
			0 AS REQ_QTY,
			0 AS PENDING_QTY,
			0  AS ISSUED_QTY_JW,
			'' AS JOBCARD_ID
			FROM  JOBWORK_ISSUE_MST B (NOLOCK) 
			left join  BOM_ISSUE_MST mst on mst.JOBWORK_ISSUE_ID=B.issue_id and mst.cancelled=0 AND ISNULL(MST.jobcardtype,0)=0
			LEFT JOIN #TMPPENDINGISSUE TMP ON TMP.MEMO_ID=B.ISSUE_ID
			WHERE  B.CANCELLED=0 AND B.AGENCY_CODE=@CAGENCYCODE AND B.location_Code =@DEPTID
			AND   (mst.JOBWORK_ISSUE_ID is null AND  TMP.MEMO_ID IS NULL) 
			ORDER BY MEMO_ID 

	 end
   
  
	

	--(
	--	SELECT C.ROW_ID,A1.ISSUE_ID,A1.ISSUE_NO,A1.ISSUE_DT,A1.AGENCY_CODE,C.ARTICLE_CODE,C.PARA1_CODE,C.PARA2_CODE,A.JOB_CODE,
	--			 CONVERT(NUMERIC(14,2),SUM(A.QUANTITY)) AS ISSUED_QTY
	--	FROM JOBWORK_ISSUE_DET A (NOLOCK)
	--	JOIN JOBWORK_ISSUE_MST A1 (NOLOCK) ON A1.ISSUE_ID=A.ISSUE_ID
	--	JOIN ORD_PLAN_BARCODE_DET B (NOLOCK) ON B.PRODUCT_CODE=A.PRODUCT_CODE
	--	JOIN ORD_PLAN_DET C (NOLOCK) ON C.ROW_ID=B.REFROW_ID
	--				JOIN ORD_PLAN_MST D (NOLOCK) ON D.MEMO_ID=C.MEMO_ID
	--	WHERE D.CANCELLED=0 AND A1.CANCELLED=0 AND A1.AGENCY_CODE=@CAGENCYCODE AND LEFT(A1.ISSUE_ID,2)=@DEPTID
	--	GROUP BY C.ROW_ID,A1.ISSUE_ID,A1.ISSUE_NO,A1.ISSUE_DT,A1.AGENCY_CODE, C.ARTICLE_CODE,C.PARA1_CODE,C.PARA2_CODE,A.JOB_CODE
	--)B
	--LEFT JOIN ORD_PLAN_BOM_DET A ON B.ROW_ID=A.REF_ROW_ID AND A.JOB_CODE =B.JOB_CODE 
	--left join  BOM_ISSUE_MST mst on mst.JOBWORK_ISSUE_ID=b.issue_id and mst.cancelled=0 
	--WHERE A.JOB_CODE IS NULL and mst.JOBWORK_ISSUE_ID is null
	
 END    
 END

