
--EXEC SP3S_REP_PRDGSTR '2024-01-01','2024-01-31'
CREATE PROCEDURE SP3S_REP_PRDGSTR
(
  @DFMDATE DATETIME='',
  @DTODATE DATETIME='',
  @CGSTN_NO VARCHAR(100)='',
  @CLOC_TYPE INT=0,--0 FOR ALL 1 FOR ONLY COMPANY OWNED,
  @CDEPT_ID VARCHAR(5)=''
  
)
AS
BEGIN
    
    
      SELECT ISNULL(LMP.AC_GST_NO,'')  AS [GSTIN OF JOB WORKER (JW) ],
             C.GST_STATE_CODE +'-'+C.GST_STATE_NAME AS [STATE (IN CASE OF UNREGISTERED JW) ],
             'NON SEZ' AS [JOB WORKER'S TYPE],
             BM.issue_no  AS [CHALLAN NUMBER],
             CONVERT(VARCHAR(10),BM.ISSUE_DT,105) AS [CHALLAN DATE (DD-MM-YYYY)],
             'INPUTS' AS [TYPES OF GOODS],
             ART.ARTICLE_NO+'-'+SD.SUB_SECTION_NAME AS [DESCRIPTION OF GOODS ],
             UOM.UOM_NAME AS [UNIQUE QUANTITY CODE (UQC)],
             SUM(BD.STOCK_QTY) AS [Quantity ],
             SUM(ISNULL(XN_VALUE_WITHOUT_GST,0)) AS [Taxable Value (in Rupees)],
             CASE WHEN ISNULL(IGST_AMOUNT,0)<>0 THEN CAST(CAST(BD.GST_PERCENTAGE AS NUMERIC(5,1)) AS VARCHAR(10)) 
             ELSE '' END AS [Integrated Tax Ratein (%)],
             CASE WHEN ISNULL(IGST_AMOUNT,0)=0 THEN CAST(CAST(BD.GST_PERCENTAGE/2 AS NUMERIC(5,1)) AS VARCHAR(10)) 
             ELSE '' END AS [Central Tax Rate in (%)],
             CASE WHEN ISNULL(IGST_AMOUNT,0)=0 THEN CAST(CAST(BD.GST_PERCENTAGE/2 AS NUMERIC(5,1)) AS VARCHAR(10)) 
             ELSE '' END AS [State/UT Tax Rate in (%)],
             CAST('' AS VARCHAR(100)) AS [Cess],
             CAST('' AS VARCHAR(100)) AS [Action],
             CAST('This row is validated' AS VARCHAR(100)) AS [Sheet Validation Error(s)],
             CAST('' AS VARCHAR(100)) AS 'GST Portal Validation Error(s)'

      FROM  BOM_ISSUE_MST  BM (NOLOCK)
      JOIN  BOM_ISSUE_DET  BD (NOLOCK) ON BM.ISSUE_ID =BD.issue_id 
      JOIN SKU (NOLOCK) ON SKU.PRODUCT_CODE =BD.PRODUCT_CODE
      JOIN ARTICLE ART (NOLOCK) ON ART.ARTICLE_CODE =SKU.ARTICLE_CODE
      JOIN SECTIOND SD (NOLOCK) ON SD.SUB_SECTION_CODE =ART.SUB_SECTION_CODE 
      JOIN UOM (NOLOCK) ON UOM.UOM_CODE =ART.UOM_CODE 
      JOIN LOCATION B (NOLOCK) ON B.DEPT_ID =BM.location_Code 
      JOIN prd_agency_mst AM ON AM.AGENCY_CODE=BM.AGENCY_CODE
      LEFT OUTER JOIN LMP01106 LMP (NOLOCK) ON LMP.AC_CODE =AM.AC_CODE 
      LEFT JOIN GST_STATE_MST C (NOLOCK)  ON LMP.ac_gst_state_code  =C.GST_STATE_CODE
      WHERE BM.CANCELLED =0 
      AND BM.ISSUE_DT BETWEEN @DFMDATE AND @DTODATE
      AND (@CGSTN_NO='' OR B.LOC_GST_NO=@CGSTN_NO)
      AND (@CLOC_TYPE=0 OR ISNULL(B.LOC_TYPE,0) =@CLOC_TYPE)
      AND ISNULL(BD.HSN_CODE ,'') NOT IN('','0000000000') 
	  --AND ISNULL(BD.GST_PERCENTAGE,0)>0
      GROUP BY ISNULL(LMP.AC_GST_NO,'')  ,C.GST_STATE_CODE +'-'+C.GST_STATE_NAME ,
       BM.issue_no  ,CONVERT(VARCHAR(10),BM.issue_dt ,105) ,ART.ARTICLE_NO+'-'+SD.SUB_SECTION_NAME ,UOM.UOM_NAME ,
      CASE WHEN ISNULL(IGST_AMOUNT,0)<>0 THEN CAST(CAST(BD.GST_PERCENTAGE AS NUMERIC(5,1)) AS VARCHAR(10)) ELSE '' END ,
      CASE WHEN ISNULL(IGST_AMOUNT,0)=0 THEN CAST(CAST(BD.GST_PERCENTAGE/2 AS NUMERIC(5,1)) AS VARCHAR(10)) 
      ELSE '' END
      union all
	  SELECT ISNULL(LMP.AC_GST_NO,'')  AS [GSTIN OF JOB WORKER (JW) ],
             C.GST_STATE_CODE +'-'+C.GST_STATE_NAME AS [STATE (IN CASE OF UNREGISTERED JW) ],
             'NON SEZ' AS [JOB WORKER'S TYPE],
             BM.issue_no  AS [CHALLAN NUMBER],
             CONVERT(VARCHAR(10),BM.ISSUE_DT,105) AS [CHALLAN DATE (DD-MM-YYYY)],
             'INPUTS' AS [TYPES OF GOODS],
             ART.ARTICLE_NO+'-'+SD.SUB_SECTION_NAME AS [DESCRIPTION OF GOODS ],
             UOM.UOM_NAME AS [UNIQUE QUANTITY CODE (UQC)],
             SUM(BD.quantity ) AS [Quantity ],
             SUM(ISNULL(XN_VALUE_WITHOUT_GST,0)) AS [Taxable Value (in Rupees)],
             CASE WHEN ISNULL(IGST_AMOUNT,0)<>0 THEN CAST(CAST(BD.GST_PERCENTAGE AS NUMERIC(5,1)) AS VARCHAR(10)) 
             ELSE '' END AS [Integrated Tax Ratein (%)],
             CASE WHEN ISNULL(IGST_AMOUNT,0)=0 THEN CAST(CAST(BD.GST_PERCENTAGE/2 AS NUMERIC(5,1)) AS VARCHAR(10)) 
             ELSE '' END AS [Central Tax Rate in (%)],
             CASE WHEN ISNULL(IGST_AMOUNT,0)=0 THEN CAST(CAST(BD.GST_PERCENTAGE/2 AS NUMERIC(5,1)) AS VARCHAR(10)) 
             ELSE '' END AS [State/UT Tax Rate in (%)],
             CAST('' AS VARCHAR(100)) AS [Cess],
             CAST('' AS VARCHAR(100)) AS [Action],
             CAST('This row is validated' AS VARCHAR(100)) AS [Sheet Validation Error(s)],
             CAST('' AS VARCHAR(100)) AS 'GST Portal Validation Error(s)'

      FROM  JOBWORK_ISSUE_MST   BM (NOLOCK)
      JOIN  JOBWORK_ISSUE_DET  BD (NOLOCK) ON BM.ISSUE_ID =BD.issue_id 
      JOIN 
	  (  
		 SELECT PRODUCT_CODE,ARTICLE_CODE 
		 FROM SKU (NOLOCK) 
		 Union
		 SELECT PRODUCT_CODE,ARTICLE_CODE 
		 FROM Wip_pmt (NOLOCK) 

      ) SKU  ON SKU.PRODUCT_CODE =BD.PRODUCT_CODE
      JOIN ARTICLE ART (NOLOCK) ON ART.ARTICLE_CODE =SKU.ARTICLE_CODE
      JOIN SECTIOND SD (NOLOCK) ON SD.SUB_SECTION_CODE =ART.SUB_SECTION_CODE 
      JOIN UOM (NOLOCK) ON UOM.UOM_CODE =ART.UOM_CODE 
      JOIN LOCATION B (NOLOCK) ON B.DEPT_ID =BM.location_Code 
      JOIN prd_agency_mst AM ON AM.AGENCY_CODE=BM.AGENCY_CODE
      LEFT OUTER JOIN LMP01106 LMP (NOLOCK) ON LMP.AC_CODE =AM.AC_CODE 
      LEFT JOIN GST_STATE_MST C (NOLOCK)  ON LMP.ac_gst_state_code  =C.GST_STATE_CODE
      WHERE BM.CANCELLED =0 
      AND BM.ISSUE_DT BETWEEN @DFMDATE AND @DTODATE
      AND (@CGSTN_NO='' OR B.LOC_GST_NO=@CGSTN_NO)
      AND (@CLOC_TYPE=0 OR ISNULL(B.LOC_TYPE,0) =@CLOC_TYPE)
      AND ISNULL(BD.HSN_CODE ,'') NOT IN('','0000000000') 
	  --AND ISNULL(BD.GST_PERCENTAGE,0)>0
      GROUP BY ISNULL(LMP.AC_GST_NO,'')  ,C.GST_STATE_CODE +'-'+C.GST_STATE_NAME ,
       BM.issue_no  ,CONVERT(VARCHAR(10),BM.issue_dt ,105) ,ART.ARTICLE_NO+'-'+SD.SUB_SECTION_NAME ,UOM.UOM_NAME ,
      CASE WHEN ISNULL(IGST_AMOUNT,0)<>0 THEN CAST(CAST(BD.GST_PERCENTAGE AS NUMERIC(5,1)) AS VARCHAR(10)) ELSE '' END ,
      CASE WHEN ISNULL(IGST_AMOUNT,0)=0 THEN CAST(CAST(BD.GST_PERCENTAGE/2 AS NUMERIC(5,1)) AS VARCHAR(10)) 
      ELSE '' END
      
     
      
       SELECT ISNULL(LMP.AC_GST_NO,'')  AS [GSTIN of Job Worker(JW) ],
             C.GST_STATE_CODE +'-'+C.GST_STATE_NAME AS [State (in case of unregistered JW) ],
             im.issue_no AS [Original Challan Number],
             CONVERT(VARCHAR(10),im.issue_dt ,105) AS [Original Challan Date(dd-mm-yyyy) ],
			 a.receipt_no  AS [Challan Number Issued By Jobworker],
             CONVERT(VARCHAR(10),a.receipt_dt  ,105) AS [Challan Date Issued By Jobworker(dd-mm-yyyy)],
			 jobs.job_name as [Nature Of Jobwork Done],
			 ART.ARTICLE_NO+'-'+SD.SUB_SECTION_NAME AS [DESCRIPTION OF GOODS ],
			 UOM.UOM_NAME AS [UNIQUE QUANTITY CODE (UQC)],
			 SUM(DET.QUANTITY) AS [Quantity ],
			 CAST('' AS VARCHAR(100)) AS [Losses and Wastes UNIQUE QUANTITY CODE (UQC) ],
			 CAST('' AS VARCHAR(100)) AS [Losses and Wastes QUANTITY],
			 CAST('' AS VARCHAR(100)) AS [Action],
			 CAST('This row is validated' AS VARCHAR(100)) AS [Sheet Validation Error(s)],
             CAST('' AS VARCHAR(100)) AS 'GST Portal Validation Error(s)'

     

      FROM JOBWORK_RECEIPT_MST  A (NOLOCK)
      JOIN JOBWORK_RECEIPT_DET DET (NOLOCK)  ON A.RECEIPT_ID=DET.RECEIPT_ID
	  JOIN JOBWORK_ISSUE_DET ID ON ID.ROW_ID =DET.REF_ROW_ID 
	  JOIN JOBWORK_ISSUE_MST IM (NOLOCK) ON ID.ISSUE_ID =IM.ISSUE_ID 
	  join jobs (nolock) on jobs.job_code =DET.JOB_CODE  
      JOIN 
	  (  
		 SELECT PRODUCT_CODE,ARTICLE_CODE 
		 FROM SKU (NOLOCK) 
		 Union
		 SELECT PRODUCT_CODE,ARTICLE_CODE 
		 FROM Wip_pmt (NOLOCK) 

      ) SKU  ON SKU.PRODUCT_CODE =DET.PRODUCT_CODE
      JOIN ARTICLE ART (NOLOCK) ON ART.ARTICLE_CODE =SKU.ARTICLE_CODE
      JOIN SECTIOND SD (NOLOCK) ON SD.SUB_SECTION_CODE =ART.SUB_SECTION_CODE 
      JOIN UOM (NOLOCK) ON UOM.UOM_CODE =ART.UOM_CODE 
      JOIN LOCATION B (NOLOCK) ON B.DEPT_ID =a.location_Code 
      JOIN prd_agency_mst AM ON AM.AGENCY_CODE=A.AGENCY_CODE
      LEFT OUTER JOIN LMP01106 LMP (NOLOCK) ON LMP.AC_CODE =AM.AC_CODE 
      LEFT JOIN GST_STATE_MST C (NOLOCK)  ON A.PARTY_STATE_CODE  =C.GST_STATE_CODE
      WHERE A.CANCELLED =0
      AND A.RECEIPT_DT BETWEEN @DFMDATE AND @DTODATE
      AND (@CGSTN_NO='' OR B.LOC_GST_NO=@CGSTN_NO)
      AND (@CLOC_TYPE=0 OR ISNULL(B.LOC_TYPE,0) =@CLOC_TYPE)
      AND ISNULL(DET.HSN_CODE ,'') NOT IN('','0000000000') 
	  --AND ISNULL(DET.GST_PERCENTAGE,0)>0
      GROUP BY ISNULL(LMP.AC_GST_NO,'')  ,C.GST_STATE_CODE +'-'+C.GST_STATE_NAME ,
       im.issue_no ,CONVERT(VARCHAR(10),im.issue_dt ,105) ,ART.ARTICLE_NO+'-'+SD.SUB_SECTION_NAME ,UOM.UOM_NAME,
	   IM.ISSUE_NO ,im.issue_dt,jobs.job_name,a.receipt_no ,a.receipt_dt 
      
  

END