CREATE PROCEDURE SP_WHOSALE_PENDING_REPORT    
(    
  @DFM_DT DATETIME='2019-04-01',    
  @DTODT DATETIME='2019-07-04',
  @CAC_CODE VARCHAR(MAX)='',--FILTER PENDING
  @NQTY_SKT INT=0    
      
)    
AS    
BEGIN    
          
      DECLARE @DTSQL NVARCHAR(MAX)  ,@CAC_STATUS VARCHAR(MAX)  
    
   IF @CAC_CODE=''  
	BEGIN  
	   SET @CAC_STATUS=''  
	   SET @CAC_CODE='IN('''')'  
	END  
	ELSE   
	BEGIN  
	   SET @CAC_STATUS='LATER'  
	END  
  
      
  
  
  SET @DTSQL=N'SELECT ISNULL(UPC.ORDER_ID ,MST.ORDER_ID ) AS ORDER_ID,
         BO.AC_CODE,LM.AC_NAME ,    
         BO.ORDER_NO,BO.ORDER_DT , 
         ART.ARTICLE_NO ,   
         A.PARA1_CODE ,P1.PARA1_NAME ,    
         A.PARA2_CODE ,P2.PARA2_NAME ,    
         MST.MEMO_NO AS WO_NO,    
         MST.MEMO_DT AS WO_DT ,    
         A.PRODUCT_CODE,
         A.QUANTITY AS QUANTITY,
         CAST(PMT.QUANTITY_IN_STOCK AS NUMERIC(10,0)) AS QUANTITY_IN_STOCK ,
         A.PRODUCT_CODE WIP_PRODUCT_CODE,
         B.MEMO_DT AS TTM_DT,
         B.MEMO_NO AS TTM_MEMO_NO
  FROM TRANSFER_TO_TRADING_DET A
  JOIN TRANSFER_TO_TRADING_MST B ON A.MEMO_ID =B.MEMO_ID
  JOIN PARA1 P1 ON P1.PARA1_CODE=A.PARA1_CODE     
  JOIN PARA2 P2 ON P2.PARA2_CODE =A.PARA2_CODE 
  JOIN ARTICLE ART ON ART.ARTICLE_CODE=A.ARTICLE_CODE 
  JOIN PMT01106 PMT ON PMT.PRODUCT_CODE =A.PRODUCT_CODE 
  JOIN
  (
    SELECT C.PRODUCT_CODE,A.MEMO_NO,A.MEMO_DT,
           ISNULL(BM.ORDER_NO,'''') AS  ORDER_NO,
           ISNULL(BM.ORDER_DT,'''') AS  ORDER_DT,
           ISNULL(BM.ORDER_ID,'''') AS  ORDER_ID
    FROM ORD_PLAN_MST A (NOLOCK)
    JOIN ORD_PLAN_DET B (NOLOCK) ON A.MEMO_ID=B.MEMO_ID
    JOIN ORD_PLAN_BARCODE_DET C (NOLOCK) ON B.ROW_ID=C.REFROW_ID
    LEFT JOIN BUYER_ORDER_DET BD (NOLOCK) ON BD.ROW_ID=WOD_ROW_ID
    LEFT JOIN BUYER_ORDER_MST BM (NOLOCK) ON BM.ORDER_ID=BD.ORDER_ID
    WHERE A.CANCELLED=0 AND ISNULL(BM.CANCELLED,0)=0
  ) MST ON A.PRODUCT_CODE=MST.PRODUCT_CODE
 -- JOIN PRD_WO_MST MST ON MST.MEMO_ID=A.REF_PRD_WORKORDER_MEMOID   
  LEFT OUTER JOIN JOBWORK_PMT UPC ON UPC.PRODUCT_CODE =A.PRODUCT_CODE 
 -- LEFT OUTER JOIN PRD_WO_ORDERS ORD ON ORD.MEMO_ID =A.REF_PRD_WORKORDER_MEMOID 
  LEFT OUTER JOIN BUYER_ORDER_MST BO ON BO.ORDER_ID= ISNULL(UPC.ORDER_ID ,MST.ORDER_ID )
  LEFT  JOIN LM01106 LM ON LM.AC_CODE =BO.AC_CODE 
  WHERE B.CANCELLED =0
  AND  B.MEMO_DT BETWEEN  '''+CONVERT(VARCHAR,@DFM_DT,121)+''' AND '''+CONVERT(VARCHAR,@DTODT,121)+'''
  AND ('''+RTRIM(LTRIM(STR(@NQTY_SKT)))+'''=0 OR  PMT.QUANTITY_IN_STOCK>0  ) 
  AND ('''+RTRIM(LTRIM(@CAC_STATUS))+'''='''' OR BO.AC_CODE '+@CAC_CODE+')  '
  PRINT @DTSQL
  EXEC SP_EXECUTESQL @DTSQL
    
  
END
