CREATE PROCEDURE SP_PRD_UPC_JOBS
(
 @CORDER_ID VARCHAR(100)='',
 @CPARA1_CODE VARCHAR(100)='',
 @CPARA2_CODE VARCHAR(10)='',
 @CWO_ID VARCHAR(100)=''
 )
AS
BEGIN
		IF OBJECT_ID ('TEMPDB..#TMPREC','U') IS NOT NULL
		   DROP TABLE #TMPREC


		 SELECT AG.AGENCY_NAME,  PRODUCT_CODE,B.MEMO_ID ,
		 C.JOB_CODE ,B.MEMO_NO AS REC_NO,CONVERT(VARCHAR,B.MEMO_DT,105)  AS REC_DT 
		 INTO #TMPREC
		 FROM PRD_AGENCY_MATERIAL_RECEIPT_UPC A
		 JOIN PRD_AGENCY_MATERIAL_RECEIPT_MST B ON A.MEMO_ID=B.MEMO_ID
		 JOIN AGENCY_JOBS C ON B.AGENCY_CODE= C.AGENCY_CODE
		 JOIN PRD_AGENCY_MST AG ON AG.AGENCY_CODE=C.AGENCY_CODE 
		 
		 
		 ;WITH CTE AS
		 (
		 SELECT AGENCY_NAME,PRODUCT_CODE,MEMO_ID,JOB_CODE,
				SR=ROW_NUMBER () OVER (PARTITION BY PRODUCT_CODE,JOB_CODE ORDER BY PRODUCT_CODE,JOB_CODE, MEMO_ID DESC)
		 FROM #TMPREC
		 
		 )
		 DELETE  FROM CTE WHERE SR>1
		 
		 
		 SELECT REC_NO,B.REC_DT,AGENCY_NAME,JOBS.JOB_NAME ,A.PRODUCT_CODE ,
				A.QUANTITY_IN_STOCK AS WIP_STOCK  
		 FROM PRD_UPCPMT A
		 JOIN #TMPREC B ON A.PRODUCT_CODE =B.PRODUCT_CODE AND A.JOB_CODE =B.JOB_CODE 
		 JOIN JOBS ON JOBS.JOB_CODE=A.JOB_CODE
		 JOIN (SELECT DISTINCT * FROM PRD_WO_ORDERS) ORD ON A.WO_ID =ORD.MEMO_ID 
		 WHERE A.QUANTITY_IN_STOCK>0
		 AND ISNULL(A.ORDER_ID,ORD.ORDER_ID ) =@CORDER_ID
		 AND A.PARA1_CODE =@CPARA1_CODE 
		 AND A.PARA2_CODE =@CPARA2_CODE
		 AND ISNULL(A.WO_ID ,ORD.MEMO_ID  )=@CWO_ID 
		 --GROUP BY REC_NO,B.REC_DT,AGENCY_NAME,JOBS.JOB_NAME
		
END
