CREATE PROCEDURE VALIDATEXN_ARC_BEFORE_EDIT 
@CMEMOID VARCHAR(30),
@BCANCELXN BIT,
@CERRORMSG VARCHAR(200) OUTPUT,
@CEXPRERRORMSG VARCHAR(200) OUTPUT
--WITH ENCRYPTION
AS
BEGIN
	
	DECLARE @CTEXT VARCHAR(10),@CADJBILLNO VARCHAR(20),@DADJBILLDT DATETIME,@CGVSRNO VARCHAR(50)
	
	SET @CTEXT=(CASE WHEN @BCANCELXN=1 THEN 'CANCEL' ELSE 'EDIT' END)

	IF EXISTS(SELECT TOP 1 A.MEMO_ID FROM PAYMODE_XN_DET A JOIN CMM01106 B ON A.MEMO_ID=B.CM_ID
			  WHERE A.ADJ_MEMO_ID=@CMEMOID AND B.CANCELLED=0 AND A.XN_TYPE='SLS' AND A.PAYMODE_CODE='0000002')				  
	
	BEGIN
		SET @CERRORMSG='THIS MEMO HAS BEEN SETTLED IN RETAIL SALES.........CAN NOT '+@CTEXT
		RETURN
	END
	
	IF EXISTS(SELECT TOP 1 A.MEMO_ID FROM PAYMODE_XN_DET A JOIN ARC01106 B ON A.MEMO_ID=B.ADV_REC_ID
			  WHERE A.ADJ_MEMO_ID=@CMEMOID AND B.CANCELLED=0 AND A.XN_TYPE='ARC' AND A.PAYMODE_CODE='0000002')				  
	BEGIN
		SET @CERRORMSG='THIS MEMO HAS BEEN SETTLED IN CUSTOMER PAYMENT.........CAN NOT '+@CTEXT
		RETURN
	END

	IF EXISTS (SELECT TOP 1 ADV_REC_ID FROM ARC01106 A JOIN VM01106 B ON A.ADV_REC_ID=B.BILL_ID
			   WHERE A.ADV_REC_ID=@CMEMOID  AND B.BILL_TYPE='ARC' AND B.CANCELLED=0)
	BEGIN	
		SET @CERRORMSG='THIS RECEIPT HAS BEEN POSTED INTO ACCOUNTS.........CAN NOT '+@CTEXT
		RETURN
	END

	--IF EXISTS (SELECT TOP 1 A.ADV_REC_ID FROM ARC01106 A JOIN HBD_RECEIPT B ON A.adv_rec_id=B.ADV_REC_ID 
	--			WHERE A.ADV_REC_ID=@CMEMOID  AND A.CANCELLED=0) AND @BCANCELXN<>1
	--BEGIN	
	--	SET @CERRORMSG='THIS RECEIPT HAS BEEN CREATED THROUGH RECEIPT FROM CUSTOMER.........CAN NOT '+@CTEXT
	--	RETURN
	--END
	
	--IF EXISTS (SELECT TOP 1 ADV_REC_ID FROM ARC_GVSALE_DETAILS WHERE ADV_REC_ID=@CMEMOID)
	--BEGIN
	--	DECLARE @nValidationSource NUMERIC(1,0)
	--	SET @CERRORMSG='GV(s) sold information uploaded  ...Cannot Edit'
		
	--END
END