CREATE PROCEDURE SP3SCHECKAPPROVALACCESS
(
	@CXNTYPE VARCHAR(10),
	@cdept_id varchar(5)=''
)
AS
BEGIN
	/*THIS PROCEDURES VALIDATED THE PASSED XN_TYPE IS APPLICABLE FOR THE LOCATION AND RETURNS TRUE IF VALID 
	AND FALSE IF INVALID*/
	DECLARE @CCURDEPTID VARCHAR(5),@BISVALID BIT,@CALERTMSG VARCHAR(500)
	
	SET @BISVALID=0
	
	if @cdept_id=''
	   SELECT @CCURDEPTID=DEPT_ID FROM NEW_APP_LOGIN_INFO (nolock) WHERE SPID=@@SPID 
	else
	  SET @CCURDEPTID=@CDEPT_ID
	
	IF EXISTS(SELECT TOP 1 'U' FROM LOC_XNSAPPROVAL(NOLOCK) WHERE DEPT_ID=@CCURDEPTID AND XN_TYPE=@CXNTYPE)
		SET @BISVALID=1
		
	IF @BISVALID=0
	BEGIN
		SET @CALERTMSG='CURRENT LOCATION IS NOT AUTHORIZED FOR THIS TRANSACTION.'
	END	
	
	SELECT @CALERTMSG AS ERRMSG				
END
--END OF PROCEDURE - SP3SCHECKAPPROVALACCESS
