CREATE PROCEDURE [DBO].[SP3S_INV_JOBCARD_ISSUE_18]          
(          
  @IMODE INT ,          
  @CWHERE VARCHAR(MAX)='',      
  @CAGENCYCODE VARCHAR(20)='',      
  @FINYEAR VARCHAR(10)=''  ,    
  @DEPTID VARCHAR(10)='' ,
  @NRETURNMODE INT=0
          
)      
----WITH ENCRYPTION
AS          
          
BEGIN        
 DECLARE @CCMD NVARCHAR(MAX) 
 -- LBLBUYER_ORDER_REF_NO : 18
	SELECT  A3.ORDER_ID AS BUYER_ORDER_ID,A3.ORDER_NO AS BUYER_ORDER_NO,A3.ORDER_DT AS BUYER_ORDER_DT,A3.REF_NO AS BUYER_ORDER_REF_NO
	,A22.MEMO_ID AS JOB_CARD_ID,A22.MEMO_NO AS JOB_CARD_NO
	FROM BOM_ISSUE_MST A (NOLOCK)             
	JOIN BOM_ISSUE_DET G (NOLOCK)  ON A.ISSUE_ID = G.ISSUE_ID 
	JOIN ORD_PLAN_BOM_DET B (NOLOCK)  ON B.ROW_ID= G.ORD_PLAN_BOM_DET_ROW_ID
	JOIN ORD_PLAN_DET A2 (NOLOCK)  ON A2.ROW_ID= B.REF_ROW_ID
	JOIN ORD_PLAN_MST A22 (NOLOCK)  ON A2.MEMO_ID= A22.MEMO_ID
	LEFT JOIN BUYER_ORDER_DET A1 (NOLOCK) ON A2.WOD_ROW_ID=A1.ROW_ID
	LEFT JOIN  BUYER_ORDER_MST A3 (NOLOCK) ON A1.ORDER_ID=A3.ORDER_ID
	WHERE A.ISSUE_ID=@CWHERE
	GROUP BY A3.ORDER_ID,A3.ORDER_NO,A3.ORDER_DT,A3.REF_NO,A22.MEMO_ID ,A22.MEMO_NO
END
