create PROC SP_GETCARD_DISCOUNT_PERCETAGE
(
 @CCUSTOMERCODE VARCHAR(20),
 @CPARACODE VARCHAR(20)='',
 @DREFMEMODT DATETIME='',
 @BCALLEDFROMSALESETUPPROC BIT=0,
 @BPICKCARDDISCFORSOLDITEMS BIT=0,
 @bSalesSetupInEffect BIT=1,
 @BCALLEDFROMCASHMEMO BIT=0,
 @NSPID VARCHAR(40)='',
 @CERRORMSG VARCHAR(MAX) OUTPUT
)
--WITH ENCRYPTION
AS

BEGIN
 --(dinkar) Replace  left(memoid,2) to Location_code 
	DECLARE @CPARA VARCHAR(20),@CSTEP VARCHAR(5),@NCUSTDISCOUNT_NORMAL NUMERIC(6,2),@NCUSTDISCOUNT_EOSS NUMERIC(6,2),
			@NBILLDISCAMT NUMERIC(10,2),@nNetAmount NUMERIC(10,2),@nFreshItemsSubtotal NUMERIC(10,2)
	DECLARE @CCMD NVARCHAR(MAX),@CAPPLY_DISCOUNT_LEVEL VARCHAR(2),@CENABLECARDDISCOUNT VARCHAR(2) ,
		    @cTargetTable VARCHAR(200),@cJoinStr VARCHAR(300),@cWc VARCHAR(300)

	
	BEGIN TRY
		
		SET @CSTEP='10'
		PRINT 'ENTER CARD DISCOUNT'
		SELECT TOP 1 @CPARA = VALUE FROM CONFIG WHERE CONFIG_OPTION = 'PARA_NAME_FOR_BRAND'
		IF ISNULL(@CPARA,'')=''
			SELECT TOP 1 @CPARA = VALUE FROM CONFIG WHERE CONFIG_OPTION = 'PARA_NAME_FOR_DISCOUNT'
			
		IF OBJECT_ID('TEMPDB..#TMPPARA','U') IS NOT NULL
		   DROP TABLE #TMPPARA
		
		SET @CSTEP='20'   
		SELECT CONVERT(VARCHAR(50),'') AS PRODUCT_CODE, CAST('' AS VARCHAR(100)) AS PARA_CODE 
		INTO #TMPPARA
		WHERE 1=2
		
		SELECT @cTargetTable =(CASE WHEN @bSalesSetupInEffect=1 THEN '#tmpcmd' ELSE 'sls_cmd01106_upload' END) ,
		@cWc=(CASE WHEN @bSalesSetupInEffect=1 THEN '' ELSE ' WHERE sp_id='''+@NSPID+'''' END)

		--SELECT 'CHECK #TMPCMD',* FROM #TMPCMD
		IF ISNULL(@CPARA,'') IN ('1','2','3','4','5','6')
			SET @CPARA = 'PARA' +  @CPARA
	    
		IF LEFT(ISNULL(@CPARA,''),4)='PARA'
		BEGIN
			IF @BCALLEDFROMSALESETUPPROC=0
			BEGIN
				SET @CSTEP='30'
				
				SET @CCMD = N'SELECT PRODUCT_CODE,'+@CPARA+''+'_CODE FROM SKU WHERE PRODUCT_CODE='''+@CPARACODE+''''
				PRINT @CCMD
				INSERT INTO #TMPPARA (PRODUCT_CODE,PARA_CODE)
				EXEC SP_EXECUTESQL @CCMD
			END
			ELSE
			BEGIN
				
				SET @CSTEP='40'
				SET @CCMD = N'SELECT A.PRODUCT_CODE,A.'+@CPARA+''+'_CODE FROM SKU A JOIN '+@cTargetTable+' B (NOLOCK) 
							  ON A.PRODUCT_CODE=B.PRODUCT_CODE'+@cWc
				PRINT @CCMD
				INSERT INTO #TMPPARA (PRODUCT_CODE,PARA_CODE)
				EXEC SP_EXECUTESQL @CCMD			
			END
		END

		DECLARE @cCurLocId VARCHAR(4)
		
		
		
		
		SELECT TOP 1 @cCurLocId=dept_id FROM SLS_CMD01106_UPLOAD A WHERE SP_ID=@NSPID 
		
		IF @BCALLEDFROMCASHMEMO=1
		BEGIN
			
			SELECT @NBILLDISCAMT=DISCOUNT_AMOUNT,@nNetAmount=net_amount FROM SLS_CMM01106_UPLOAD A
			WHERE SP_ID=@NSPID 

			SELECT @nFreshItemsSubtotal=SUM(NET) FROM SLS_CMd01106_UPLOAD A (NOLOCK)
			WHERE SP_ID=@NSPID AND discount_amount=0
						
			IF EXISTS (SELECT TOP 1 ECOUPON_ID FROM SLS_COUPON_REDEMPTION_INFO_UPLOAD WHERE SP_ID=@NSPID 
					   AND COUPON_DISC_AMOUNT<>0)	
				SET @NBILLDISCAMT=0
		END	
		ELSE
			SET @NBILLDISCAMT=0
			
		IF @BCALLEDFROMSALESETUPPROC=0
		BEGIN
			SET @CSTEP='50'
			SET @CCMD = N' SELECT A.CARD_NAME,PARA_NAME,PARA_CODE,DISC_PER AS [DISCOUNT_PERCENTAGE]
			FROM BWD_MST A (NOLOCK)
			JOIN BWD_DET B (NOLOCK) ON A.MEMO_ID = B.MEMO_ID 
			JOIN CUSTDYM C (NOLOCK) ON A.MEMO_ID=C.CARD_CODE
			WHERE A.PARA_NAME= '''+@CPARA+'''   AND C.CUSTOMER_CODE = '''+@CCUSTOMERCODE+''' AND B.PARA_CODE IN 
			(SELECT A.PARA_CODE FROM #TMPPARA A)
			AND C.DT_CARD_EXPIRY >'''+CONVERT(VARCHAR,@DREFMEMODT,120)+''''

			PRINT ISNULL(@CCMD,'NULL BWD') 
			EXEC SP_EXECUTESQL @CCMD 

		END	
		ELSE
		IF @BPICKCARDDISCFORSOLDITEMS=1
		BEGIN
			SET @CSTEP='60'
			--INSERT carddisc_temp	( last_update, netamt, sp_id ,DEPT_ID)  
			--SELECT GETDATE() AS  last_update,@nNetAmount AS netamt,@NSPID AS sp_id ,@cCurLocId AS DEPT_ID
			
			SET @nFreshItemsSubtotal=ISNULL(@nFreshItemsSubtotal,0)
			SELECT 		@cJoinStr=(CASE WHEN @bSalesSetupInEffect=1 THEN ' LEFT JOIN sls_cmd01106_upload sd (NOLOCK) ON sd.row_id=e.cmd_row_id AND sd.sp_id=e.sp_id' ELSE '' END),
			@cWc=(CASE WHEN @bSalesSetupInEffect=1 THEN ' AND ISNULL(sd.manual_discount,0)=0 AND ISNULL(sd.manual_dp,0)=0' ELSE
						' AND e.sp_id='''+@nSpId+''' AND ISNULL(e.manual_discount,0)=0 AND ISNULL(e.manual_dp,0)=0' END)

			SET @CCMD = N' UPDATE E SET CARD_DISCOUNT_PERCENTAGE=
			(CASE WHEN ISNULL(E.WEIGHTED_AVG_DISC_AMT,0)=0 AND E.BASIC_DISCOUNT_PERCENTAGE=0 AND '+(CASE WHEN @NBILLDISCAMT<>0 THEN '1' ELSE '0' END)+'=0
				  THEN ISNULL(BWD.EXCEPTIONAL_NORMAL_DISC_PER,BWM.NORMAL_DISC_PER) 
				  ELSE ISNULL(BWD.EXCEPTIONAL_EOSS_DISC_PER,BWM.EOSS_DISC_PER) END),CARD_DISCOUNT=1
			FROM '+@cTargetTable+' E JOIN CUSTDYM C (NOLOCK) ON 1=1
			LEFT OUTER JOIN #TMPPARA D ON E.PRODUCT_CODE=D.PRODUCT_CODE
			
			JOIN
			(SELECT A.NORMAL_DISC_PER,EOSS_DISC_PER,a.MEMO_ID,ISNULL(b.max_purchase_amount_per_bill,a.max_purchase_amount_per_bill) as max_purchase_amount_per_bill
			 FROM BWD_MST A
			 LEFT OUTER JOIN loc_bwd_mst b on b.memo_id=a.memo_id AND b.dept_id='''+@cCurLocId+''' ) BWM ON BWM.MEMO_ID=C.CARD_CODE

			LEFT OUTER JOIN
			(SELECT B.DISC_PER AS EXCEPTIONAL_NORMAL_DISC_PER,B.EOSS_DISC_PER AS EXCEPTIONAL_EOSS_DISC_PER,
			 A.MEMO_ID,B.PARA_CODE FROM BWD_MST A
			 JOIN BWD_DET B (NOLOCK) ON A.MEMO_ID = B.MEMO_ID 
			 WHERE A.PARA_NAME= '''+@CPARA+''') BWD ON BWD.MEMO_ID=C.CARD_CODE AND BWD.PARA_CODE=D.PARA_CODE
		     '+@cJoinStr+' WHERE C.CUSTOMER_CODE = '''+@CCUSTOMERCODE+''' 
			AND ('+LTRIM(RTRIM(STR(@nFreshItemsSubtotal)))+'<=ISNULL(bwm.max_purchase_amount_per_bill,0)
				  OR ISNULL(bwm.max_purchase_amount_per_bill,0)=0)
			AND (C.DT_CARD_EXPIRY >'''+CONVERT(VARCHAR,@DREFMEMODT,120)+''' OR C.DT_CARD_EXPIRY='''')'+@cWc
			

			PRINT ISNULL(@CCMD,'NULL BWD') 
			EXEC SP_EXECUTESQL @CCMD 

			IF @bSalesSetupInEffect=0 
			BEGIN
				IF EXISTS (SELECT TOP 1 product_code FROM SLS_cmd01106_UPLOAD (NOLOCK) WHERE sp_id=@nSpId AND card_discount_percentage<>0)
				BEGIN
					UPDATE sls_cmd01106_upload WITH (ROWLOCK) SET card_discount_amount=(MRP-(ISNULL(BASIC_DISCOUNT_AMOUNT,0)/QUANTITY))*ISNULL(CARD_DISCOUNT_PERCENTAGE,0)*QUANTITY/100
					WHERE sp_id=@nSpId

					UPDATE sls_cmd01106_upload WITH (ROWLOCK) SET discount_amount=ISNULL(BASIC_DISCOUNT_AMOUNT,0)+ISNULL(CARD_DISCOUNT_AMOUNT,0)
					WHERE sp_id=@nSpId

					UPDATE sls_cmd01106_upload WITH (ROWLOCK) SET DISCOUNT_PERCENTAGE=(100-(((MRP-(MRP*ISNULL(BASIC_DISCOUNT_PERCENTAGE,0)/100))-((MRP-(MRP*ISNULL(BASIC_DISCOUNT_PERCENTAGE,0)/100))
							*ISNULL(CARD_DISCOUNT_PERCENTAGE,0)/100))/MRP)*100) 
					WHERE sp_id=@nSpId AND mrp<>0
				END
			END
		END
				
		GOTO END_PROC
	END TRY
	
	BEGIN CATCH
		SET @CERRORMSG='PROCEDURE SP_GETCARD_DISCOUNT_PERCETAGE: STEP#'+@CSTEP+' '+ERROR_MESSAGE()
		GOTO END_PROC
	END CATCH				

END_PROC:
	
END
/*

select top 10 * from SLS_CMM01106_UPLOAD where left(sp_id,3)='164' order by last_update desc

savetran_sls_beforesave 1,'164bd7dd84d-ee58-4b6e-a927-790aa2d1ee4a','',''

select card_discount_percentage,card_discount_amount, slsdet_row_id,* from sls_cmd01106_upload where sp_id='164bd7dd84d-ee58-4b6e-a927-790aa2d1ee4a'

*/