CREATE PROCEDURE SP_MERGE_MIRROR_PBG_DATA
(
	@CMEMOID VARCHAR(50)
   ,@CLOCID VARCHAR(3)
   ,@CSOURCEDB VARCHAR(200)
   ,@CMERGEDB VARCHAR(200)
   ,@BMSTINSERTONLY BIT
   ,@CERRMSG VARCHAR(1000) OUTPUT
)
--WITH ENCRYPTION
AS
SET NOCOUNT ON
BEGIN
	/*
		SP_MERGE_MIRROR_PBG_DATA_208_2014_02_04 : 
		THIS PROCEDURE WILL MERGE DATA FROM TEMPORARY TABLE TO ACTUAL TABLE.
		TABLE NAMES AND ITS MERGING ORDER WILL BE FIXED AND WILL BE DEFINED HERE.	
	*/
DECLARE @CSTEP VARCHAR(100),@DTSQL NVARCHAR(MAX),@NMERGE_ORDER NUMERIC(5)
	   ,@CTABLENAME VARCHAR(200),@CTABLE_SUFFIX VARCHAR(50),@CKEYFIELD VARCHAR(200),@CDEL_ID VARCHAR(50),@CTMP_TABLENAME VARCHAR(200),@LINSERTONLY VARCHAR(1)
	   ,@CFILTERCONDITION VARCHAR(200),@LUPDATEONLY VARCHAR(1),@BALWAYSUPDATE VARCHAR(1),@FDEL CHAR(1)
	   ,@CERRMSGOUT VARCHAR(1000),@CTABLESSTR VARCHAR(MAX)
	   
DECLARE @TXNSSENDINFO TABLE (ORG_TABLENAME VARCHAR(50),TMP_TABLENAME VARCHAR(50),XN_ID VARCHAR(40))  	

BEGIN TRY

SET @CSTEP=20
	SET @CTABLE_SUFFIX=REPLACE(@CMEMOID,'-','_')
	
	GOTO EXIT_PROC
	
BEGIN TRANSACTION 
	
	SET @CSTEP=30
	SET @CSTEP=80
	SET @CTABLENAME='PBD01106'
	SET @CTMP_TABLENAME='TMP_PBG_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))
	SET @CKEYFIELD='MEMO_ID'
	
	SET @CSTEP=90
	SET @DTSQL=N'DELETE '+@CMERGEDB+'['+@CTABLENAME+'] WITH (ROWLOCK) WHERE '+@CKEYFIELD+'='''+@CMEMOID+''''
	PRINT @DTSQL
	EXEC SP_EXECUTESQL @DTSQL

	SET @CSTEP=100
	SET @CTABLENAME='PBM01106'
	SET @CTMP_TABLENAME='TMP_PBG_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))
	SET @CKEYFIELD='MEMO_ID'
	SET @CSTEP=110
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=0,@CFILTERCONDITION='',@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1 
	
	SET @CSTEP=110
	SET @CTABLENAME='PBD01106'
	SET @CTMP_TABLENAME='TMP_PBG_'+@CTABLENAME+'_'+LTRIM(RTRIM(@CTABLE_SUFFIX))
	SET @CKEYFIELD='MEMO_ID'
	SET @CSTEP=110
	EXEC UPDATEMASTERXN_MIRROR @CSOURCEDB=@CSOURCEDB,@CSOURCETABLE=@CTMP_TABLENAME,@CDESTDB=@CMERGEDB
							  ,@CDESTTABLE=@CTABLENAME,@CKEYFIELD1=@CKEYFIELD,@CKEYFIELD2='',@CKEYFIELD3=''
							  ,@LINSERTONLY=1,@CFILTERCONDITION='',@LUPDATEONLY=0
							  ,@BALWAYSUPDATE=1 
	
	/*PBM01106,PBD01106*/
	--EXECUTE THE VALIDATION PROCEDURE
	SET @CSTEP=440
	EXEC VALIDATEXN_MIRROR_PBG @CLOCID,@CMEMOID,@CMERGEDB,@CERRMSGOUT OUTPUT
	IF ISNULL(@CERRMSGOUT,'')<>''
	BEGIN
		SET @CERRMSG='P:SP_MERGE_MIRROR_PBG_DATA, STEP:'+@CSTEP+', MESSAGE:'+@CERRMSGOUT
	END	

	SET @CSTEP=450
	SET @CTABLESSTR='STATE,CITY,AREA,HD01106,LM01106,LMP01106,FORM,RMM01106,RMD01106,RMM01106_AUDIT,RMD01106_AUDIT,XNSTABLELIST'

    EXEC SP3S_DROPTEMPTABLES_MIRRORDATA
    @CXNTYPE='PBG',
    @CTABLESUFFIX=@CTABLE_SUFFIX,
    @CTABLESSTR=@CTABLESSTR

END TRY
BEGIN CATCH
	SET @CERRMSG='P:SP_MERGE_MIRROR_PBG_DATA, STEP:'+@CSTEP+', MESSAGE:'+ERROR_MESSAGE()
END CATCH
EXIT_PROC:
	IF ISNULL(@CERRMSG,'')='' AND @@TRANCOUNT>0
	BEGIN
		COMMIT
	END
	ELSE IF ISNULL(@CERRMSG,'')<>'' AND @@TRANCOUNT>0
		ROLLBACK
END	
---END OF PROCEDURE - SP_MERGE_MIRROR_PBG_DATA
