

IF NOT EXISTS (SELECT TOP 1'U' FROM CHALLAN_MAPPEDCOLS)
BEGIN

	 INSERT INTO CHALLAN_MAPPEDCOLS(WIZAPP_COL_EXPR,WIZAPP_COL,MAPPED_COL)
	SELECT 'SECTION_NAME' AS WIZAPP_COL_EXPR ,'SECTION NAME' AS WIZAPP_COL ,'SECTION_NAME' AS MAPPED_COL UNION ALL
	SELECT 'SUB_SECTION_NAME' AS WIZAPP_COL_EXPR ,'SUB SECTION NAME' AS WIZAPP_COL ,'SUB_SECTION_NAME' AS MAPPED_COL UNION ALL
	SELECT 'ARTICLE_NO' AS WIZAPP_COL_EXPR ,'ARTICLE NO' AS WIZAPP_COL ,'ARTICLE_NO' AS MAPPED_COL UNION ALL
	SELECT 'ARTICLE_NAME' AS WIZAPP_COL_EXPR ,'ARTICLE NAME' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'PARA1_NAME' AS WIZAPP_COL_EXPR ,'PARA1' AS WIZAPP_COL ,'COLOUR' AS MAPPED_COL UNION ALL
	SELECT 'PARA2_NAME' AS WIZAPP_COL_EXPR ,'PARA2' AS WIZAPP_COL ,'SIZE' AS MAPPED_COL UNION ALL
	SELECT 'PARA3_NAME' AS WIZAPP_COL_EXPR ,'PARA3' AS WIZAPP_COL ,'YEAR' AS MAPPED_COL UNION ALL
	SELECT 'PARA4_NAME' AS WIZAPP_COL_EXPR ,'PARA4' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'PARA5_NAME' AS WIZAPP_COL_EXPR ,'PARA5' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'PARA6_NAME' AS WIZAPP_COL_EXPR ,'PARA6' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'ATTR1_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR1_MST_NAME' AS WIZAPP_COL ,'BRAND' AS MAPPED_COL UNION ALL
	SELECT 'ATTR2_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR2_MST_NAME' AS WIZAPP_COL ,'GOODS' AS MAPPED_COL UNION ALL
	SELECT 'ATTR3_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR3_MST_NAME' AS WIZAPP_COL ,'PRODUCT' AS MAPPED_COL UNION ALL
	SELECT 'ATTR4_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR4_MST_NAME' AS WIZAPP_COL ,'FABRIC' AS MAPPED_COL UNION ALL
	SELECT 'ATTR5_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR5_MST_NAME' AS WIZAPP_COL ,'FABRICCONTENT' AS MAPPED_COL UNION ALL
	SELECT 'ATTR6_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR6_MST_NAME' AS WIZAPP_COL ,'ATTR_QUANTITY' AS MAPPED_COL UNION ALL
	SELECT 'ATTR7_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR7_MST_NAME' AS WIZAPP_COL ,'PATTERN' AS MAPPED_COL UNION ALL
	SELECT 'ATTR8_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR8_MST_NAME' AS WIZAPP_COL ,'SEASON' AS MAPPED_COL UNION ALL
	SELECT 'ATTR9_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR9_MST_NAME' AS WIZAPP_COL ,'FRAGRANCE' AS MAPPED_COL UNION ALL
	SELECT 'ATTR10_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR10_MST_NAME' AS WIZAPP_COL ,'MERCHANT' AS MAPPED_COL UNION ALL
	SELECT 'ATTR11_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR11_MST_NAME' AS WIZAPP_COL ,'CATEGORY' AS MAPPED_COL UNION ALL
	SELECT 'ATTR12_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR12_MST_NAME' AS WIZAPP_COL ,'DESIGN' AS MAPPED_COL UNION ALL
	SELECT 'ATTR13_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR13_MST_NAME' AS WIZAPP_COL ,'STYLE' AS MAPPED_COL UNION ALL
	SELECT 'ATTR14_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR14_MST_NAME' AS WIZAPP_COL ,'GENDER' AS MAPPED_COL UNION ALL
	SELECT 'ATTR15_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR15_MST_NAME' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'ATTR16_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR16_MST_NAME' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'ATTR17_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR17_MST_NAME' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'ATTR18_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR18_MST_NAME' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'ATTR19_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR19_MST_NAME' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'ATTR20_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR20_MST_NAME' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'ATTR21_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR21_MST_NAME' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'ATTR22_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR22_MST_NAME' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'ATTR23_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR23_MST_NAME' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'ATTR24_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR24_MST_NAME' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'ATTR25_KEY_NAME' AS WIZAPP_COL_EXPR ,'ATTR25_MST_NAME' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'PRODUCT_CODE' AS WIZAPP_COL_EXPR ,'PRODUCT CODE' AS WIZAPP_COL ,'PRODUCT_CODE' AS MAPPED_COL UNION ALL
	SELECT 'INV_NO' AS WIZAPP_COL_EXPR ,'INVOICE NO.' AS WIZAPP_COL ,'INV_NO' AS MAPPED_COL UNION ALL
	SELECT 'INV_DT' AS WIZAPP_COL_EXPR ,'INVOICE DT' AS WIZAPP_COL ,'INV_DT' AS MAPPED_COL UNION ALL
	SELECT 'REF_INV_ID' AS WIZAPP_COL_EXPR ,'REFERANCE_NO' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'REMARKS' AS WIZAPP_COL_EXPR ,'REMARKS' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'QUANTITY' AS WIZAPP_COL_EXPR ,'QUANTITY' AS WIZAPP_COL ,'QUANTITY' AS MAPPED_COL UNION ALL
	SELECT 'HSN_CODE' AS WIZAPP_COL_EXPR ,'HSN CODE' AS WIZAPP_COL ,'HSN_CODE' AS MAPPED_COL UNION ALL
	SELECT 'MRP' AS WIZAPP_COL_EXPR ,'MRP' AS WIZAPP_COL ,'MRP' AS MAPPED_COL UNION ALL
	SELECT 'DISCOUNT_PERCENTAGE' AS WIZAPP_COL_EXPR ,'DISCOUNT PERCENTAGE' AS WIZAPP_COL ,'DISCOUNT_PERCENTAGE' AS MAPPED_COL UNION ALL
	SELECT 'DISCOUNT_AMOUNT' AS WIZAPP_COL_EXPR ,'DISCOUNT AMOUNT' AS WIZAPP_COL ,'DISCOUNT_AMOUNT' AS MAPPED_COL UNION ALL
	SELECT 'XN_VALUE_WITHOUT_GST' AS WIZAPP_COL_EXPR ,'XN_VALUE_WITHOUT_GST' AS WIZAPP_COL ,'XN_VALUE_WITHOUT_GST' AS MAPPED_COL UNION ALL
	SELECT 'GST_PERCENTAGE' AS WIZAPP_COL_EXPR ,'GST_PERCENTAGE' AS WIZAPP_COL ,'GST_PERCENTAGE' AS MAPPED_COL UNION ALL
	SELECT 'IGST_AMOUNT' AS WIZAPP_COL_EXPR ,'IGST_AMOUNT' AS WIZAPP_COL ,'IGST_AMOUNT' AS MAPPED_COL UNION ALL
	SELECT 'SGST_AMOUNT' AS WIZAPP_COL_EXPR ,'SGST_AMOUNT' AS WIZAPP_COL ,'SGST_AMOUNT' AS MAPPED_COL UNION ALL
	SELECT 'CGST_AMOUNT' AS WIZAPP_COL_EXPR ,'CGST_AMOUNT' AS WIZAPP_COL ,'CGST_AMOUNT' AS MAPPED_COL UNION ALL
	SELECT 'XN_VALUE_WITH_GST' AS WIZAPP_COL_EXPR ,'XN_VALUE_WITH_GST' AS WIZAPP_COL ,'XN_VALUE_WITH_GST' AS MAPPED_COL UNION ALL
	SELECT 'ROUND_OFF' AS WIZAPP_COL_EXPR ,'ROUND OFF' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'SHIPPING_ADDRESS1' AS WIZAPP_COL_EXPR ,'SHIPPING ADDRESS1' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'SHIPPING_ADDRESS2' AS WIZAPP_COL_EXPR ,'SHIPPING ADDRESS2' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'SHIPPING_ADDRESS3' AS WIZAPP_COL_EXPR ,'SHIPPING ADDRESS3' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'SHIPPING_AREA' AS WIZAPP_COL_EXPR ,'SHIPPING AREA' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'SHIPPING_CITY' AS WIZAPP_COL_EXPR ,'SHIPPING CITY' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'SHIPPING_STATE' AS WIZAPP_COL_EXPR ,'SHIPPING STATE' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'SHIPPING_PIN' AS WIZAPP_COL_EXPR ,'SHIPPING PIN' AS WIZAPP_COL ,'' AS MAPPED_COL UNION ALL
	SELECT 'DEPT_ID' AS WIZAPP_COL_EXPR ,'SOURCE LOCATION ID' AS WIZAPP_COL ,'DEPT_ID' AS MAPPED_COL UNION ALL
	SELECT 'PARTY_DEPT_ID' AS WIZAPP_COL_EXPR ,'TARGET LOCATION ID' AS WIZAPP_COL ,'PARTY_DEPT_ID' AS MAPPED_COL 

END