IF NOT EXISTS (SELECT CONFIG_OPTION FROM CONFIG WHERE CONFIG_OPTION='UPDATE_CLOSED_PARCELDET' AND VALUE=1)
BEGIN

	PRINT 'UPDATING CLOSED COLUMN IN PARCEL DETAILS TABLES'
	

	IF NOT EXISTS (SELECT CONFIG_OPTION FROM CONFIG WHERE CONFIG_OPTION='UPDATE_CLOSED_PARCELDET')
		INSERT CONFIG (CONFIG_OPTION,VALUE,ROW_ID,LAST_UPDATE)
			   VALUES ('UPDATE_CLOSED_PARCELDET','1','',GETDATE())	
	ELSE
		UPDATE CONFIG SET VALUE='1' WHERE CONFIG_OPTION='UPDATE_CLOSED_PARCELDET'

	    UPDATE PARCEL_DET SET CLOSED=1 WHERE ISNULL(REF_MEMO_ID,'')<>'' 
END

