IF EXISTS (SELECT TOP 1 'U' FROM INFORMATION_SCHEMA .COLUMNS WHERE TABLE_NAME ='DOCWSL_PARCEL_MST_MIRROR' and COLUMN_NAME ='AC_CODE')
BEGIN
     
	ALTER TABLE  DOCWSL_PARCEL_MST_MIRROR DROP COLUMN AC_CODE
END

IF EXISTS (SELECT TOP 1 'U' FROM INFORMATION_SCHEMA .COLUMNS WHERE TABLE_NAME ='DOCPRT_PARCEL_MST_MIRROR' and COLUMN_NAME ='AC_CODE')
BEGIN
     
	ALTER TABLE  DOCPRT_PARCEL_MST_MIRROR DROP COLUMN AC_CODE
END


IF EXISTS (SELECT TOP 1 'U' FROM INFORMATION_SCHEMA .COLUMNS WHERE TABLE_NAME ='WSL_PARCEL_MST_MIRROR' and COLUMN_NAME ='AC_CODE')
BEGIN
     
	ALTER TABLE  WSL_PARCEL_MST_MIRROR DROP COLUMN AC_CODE
END


IF EXISTS (SELECT TOP 1 'U' FROM INFORMATION_SCHEMA .COLUMNS WHERE TABLE_NAME ='prt_PARCEL_MST_MIRROR' and COLUMN_NAME ='AC_CODE')
BEGIN
     
	ALTER TABLE  prt_PARCEL_MST_MIRROR DROP COLUMN AC_CODE
END
