

IF OBJECT_ID ('TEMPDB..#TMPKYYS_ARC','U') IS NOT NULL
   DROP TABLE #TMPKYYS_ARC

SELECT 'KEYS_ARC_'+CAST(LEFT(LASTKEYVAL,2) AS VARCHAR(2)) AS KEYSTABLENAME INTO #TMPKYYS_ARC FROM KEYS WHERE TABLENAME ='ARC01106'
GROUP BY CAST(LEFT(LASTKEYVAL,2) AS VARCHAR(2))


DECLARE  @CKEYSTABLE VARCHAR(100),@CCMD NVARCHAR(MAX),@CCONSTNAME VARCHAR(100)

WHILE EXISTS (SELECT TOP 1 'U' FROM #TMPKYYS_ARC)
BEGIN
     
	 SELECT TOP 1  @CKEYSTABLE=KEYSTABLENAME FROM #TMPKYYS_ARC

	IF OBJECT_ID(@CKEYSTABLE,'U') IS  NULL
	BEGIN
		PRINT 'CREATE NEW KEYS TABLE FOR ARC'
		SET @CCMD=N'SELECT * INTO ['+@CKEYSTABLE+'] FROM keys WHERE 1=2'
		EXEC SP_EXECUTESQL @CCMD	

		SET @CCONSTNAME='PK_'+@CKEYSTABLE

		SET @CCMD=N' ALTER TABLE ['+@CKEYSTABLE+'] ADD CONSTRAINT ['+@CCONSTNAME+'] PRIMARY KEY (prefix,FinYear) '
		EXEC SP_EXECUTESQL @CCMD	

		SET @CCMD=N' INSERT INTO  ['+@CKEYSTABLE+'](ColumnName,prefix,FinYear,TableName,LastKeyVal) 
		SELECT ColumnName,prefix,FinYear,TableName,LastKeyVal 
		FROM keys WHERE ''KEYS_ARC_''+CAST(LEFT(LASTKEYVAL,2) AS VARCHAR(2))='''+@CKEYSTABLE+'''
		and TABLENAME =''ARC01106''
		'
		EXEC SP_EXECUTESQL @CCMD
	END

	 DELETE FROM #TMPKYYS_ARC WHERE KEYSTABLENAME=@CKEYSTABLE
END
