
IF EXISTS(SELECT TOP 1'U' FROM SYS.tables A  JOIN SYS.foreign_keys B ON A.OBJECT_ID=B.parent_object_id
WHERE A.NAME='SCHEME_SETUP_SLSART' AND B.name='FK_SCHEME_SETUP_SLSART_ARTICLE')
ALTER TABLE SCHEME_SETUP_SLSART DROP CONSTRAINT FK_SCHEME_SETUP_SLSART_ARTICLE


