IF EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='PRD_STK_TRANSFER_MST' AND COLUMN_NAME='ref_wo_id')
BEGIN
	DECLARE @cCmd NVARCHAR(MAX)
	SET @cCmd=N'ALTER TABLE PRD_STK_TRANSFER_MST DROP COLUMN ref_wo_id'
	EXEC SP_EXECUTESQL @cCmd
END

