
INSERT INTO XNT(XN_TYPE)
SELECT DISTINCT A.XN_TYPE FROM 
(
 SELECT 'CHO' AS XN_TYPE UNION ALL
 SELECT 'CHI' UNION ALL
 SELECT 'TRO' UNION ALL
 SELECT 'TRI' UNION ALL
 SELECT 'PFI' UNION ALL
 SELECT 'CIP' 
 ) A
 LEFT OUTER JOIN XNT B ON A.XN_TYPE=B.XN_TYPE
 WHERE B.XN_TYPE IS NULL
