IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCWSL_PARCEL_MST_MIRROR' AND B.NAME='ASN_INV_NO')  ALTER TABLE DOCWSL_PARCEL_MST_MIRROR DROP COLUMN  ASN_INV_NO;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCWSL_PARCEL_MST_UPLOAD' AND B.NAME='ASN_INV_NO')  ALTER TABLE DOCWSL_PARCEL_MST_UPLOAD DROP COLUMN  ASN_INV_NO;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='WSL_PARCEL_MST_MIRROR'    AND B.NAME='ASN_INV_NO')  ALTER TABLE WSL_PARCEL_MST_MIRROR    DROP COLUMN  ASN_INV_NO;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='WSL_PARCEL_MST_UPLOAD'    AND B.NAME='ASN_INV_NO')  ALTER TABLE WSL_PARCEL_MST_UPLOAD    DROP COLUMN  ASN_INV_NO;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCPRT_PARCEL_MST_MIRROR' AND B.NAME='ASN_INV_NO')  ALTER TABLE DOCPRT_PARCEL_MST_MIRROR DROP COLUMN  ASN_INV_NO;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCPRT_PARCEL_MST_UPLOAD' AND B.NAME='ASN_INV_NO')  ALTER TABLE DOCPRT_PARCEL_MST_UPLOAD DROP COLUMN  ASN_INV_NO;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='PRT_PARCEL_MST_MIRROR'    AND B.NAME='ASN_INV_NO')  ALTER TABLE PRT_PARCEL_MST_MIRROR    DROP COLUMN  ASN_INV_NO;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='PRT_PARCEL_MST_UPLOAD'    AND B.NAME='ASN_INV_NO')  ALTER TABLE PRT_PARCEL_MST_UPLOAD    DROP COLUMN  ASN_INV_NO;


IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCWSL_PARCEL_MST_MIRROR' AND B.NAME='ASN_INV_DT')  ALTER TABLE DOCWSL_PARCEL_MST_MIRROR DROP COLUMN  ASN_INV_DT;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCWSL_PARCEL_MST_UPLOAD' AND B.NAME='ASN_INV_DT')  ALTER TABLE DOCWSL_PARCEL_MST_UPLOAD DROP COLUMN  ASN_INV_DT;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='WSL_PARCEL_MST_MIRROR'    AND B.NAME='ASN_INV_DT')  ALTER TABLE WSL_PARCEL_MST_MIRROR    DROP COLUMN  ASN_INV_DT;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='WSL_PARCEL_MST_UPLOAD'    AND B.NAME='ASN_INV_DT')  ALTER TABLE WSL_PARCEL_MST_UPLOAD    DROP COLUMN  ASN_INV_DT;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCPRT_PARCEL_MST_MIRROR' AND B.NAME='ASN_INV_DT')  ALTER TABLE DOCPRT_PARCEL_MST_MIRROR DROP COLUMN  ASN_INV_DT;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCPRT_PARCEL_MST_UPLOAD' AND B.NAME='ASN_INV_DT')  ALTER TABLE DOCPRT_PARCEL_MST_UPLOAD DROP COLUMN  ASN_INV_DT;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='PRT_PARCEL_MST_MIRROR'    AND B.NAME='ASN_INV_DT')  ALTER TABLE PRT_PARCEL_MST_MIRROR    DROP COLUMN  ASN_INV_DT;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='PRT_PARCEL_MST_UPLOAD'    AND B.NAME='ASN_INV_DT')  ALTER TABLE PRT_PARCEL_MST_UPLOAD    DROP COLUMN  ASN_INV_DT;


IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCWSL_PARCEL_MST_MIRROR' AND B.NAME='ASN_QTY')  ALTER TABLE DOCWSL_PARCEL_MST_MIRROR    DROP COLUMN  ASN_QTY;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCWSL_PARCEL_MST_UPLOAD' AND B.NAME='ASN_QTY')  ALTER TABLE DOCWSL_PARCEL_MST_UPLOAD    DROP COLUMN  ASN_QTY;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='WSL_PARCEL_MST_MIRROR'    AND B.NAME='ASN_QTY')  ALTER TABLE WSL_PARCEL_MST_MIRROR       DROP COLUMN  ASN_QTY;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='WSL_PARCEL_MST_UPLOAD'    AND B.NAME='ASN_QTY')  ALTER TABLE WSL_PARCEL_MST_UPLOAD		DROP COLUMN  ASN_QTY;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCPRT_PARCEL_MST_MIRROR' AND B.NAME='ASN_QTY')  ALTER TABLE DOCPRT_PARCEL_MST_MIRROR	DROP COLUMN  ASN_QTY;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCPRT_PARCEL_MST_UPLOAD' AND B.NAME='ASN_QTY')  ALTER TABLE DOCPRT_PARCEL_MST_UPLOAD	DROP COLUMN  ASN_QTY;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='PRT_PARCEL_MST_MIRROR'    AND B.NAME='ASN_QTY')  ALTER TABLE PRT_PARCEL_MST_MIRROR		DROP COLUMN  ASN_QTY;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='PRT_PARCEL_MST_UPLOAD'    AND B.NAME='ASN_QTY')  ALTER TABLE PRT_PARCEL_MST_UPLOAD		DROP COLUMN  ASN_QTY;


IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCWSL_parcel_mst_MIRROR' AND B.NAME='ASN_INV_AMT')  ALTER TABLE DOCWSL_parcel_mst_MIRROR DROP COLUMN  ASN_INV_AMT;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCWSL_parcel_mst_UPLOAD' AND B.NAME='ASN_INV_AMT')  ALTER TABLE DOCWSL_parcel_mst_UPLOAD DROP COLUMN  ASN_INV_AMT;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='WSL_PARCEL_MST_MIRROR'    AND B.NAME='ASN_INV_AMT')  ALTER TABLE WSL_PARCEL_MST_MIRROR	 DROP COLUMN  ASN_INV_AMT;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='WSL_parcel_mst_UPLOAD'    AND B.NAME='ASN_INV_AMT')  ALTER TABLE WSL_parcel_mst_UPLOAD    DROP COLUMN  ASN_INV_AMT;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCPRT_parcel_mst_MIRROR' AND B.NAME='ASN_INV_AMT')  ALTER TABLE DOCPRT_parcel_mst_MIRROR DROP COLUMN  ASN_INV_AMT;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCPRT_parcel_mst_UPLOAD' AND B.NAME='ASN_INV_AMT')  ALTER TABLE DOCPRT_parcel_mst_UPLOAD DROP COLUMN  ASN_INV_AMT;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='PRT_parcel_mst_MIRROR'    AND B.NAME='ASN_INV_AMT')  ALTER TABLE PRT_parcel_mst_MIRROR    DROP COLUMN  ASN_INV_AMT;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='PRT_parcel_mst_UPLOAD'    AND B.NAME='ASN_INV_AMT')  ALTER TABLE PRT_parcel_mst_UPLOAD    DROP COLUMN  ASN_INV_AMT;


IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCWSL_parcel_mst_MIRROR' AND B.NAME='PARTY_INV_NO')  ALTER TABLE DOCWSL_parcel_mst_MIRROR DROP COLUMN  PARTY_INV_NO  ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCWSL_parcel_mst_UPLOAD' AND B.NAME='PARTY_INV_NO')  ALTER TABLE DOCWSL_parcel_mst_UPLOAD DROP COLUMN  PARTY_INV_NO  ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='WSL_PARCEL_MST_MIRROR'    AND B.NAME='PARTY_INV_NO')  ALTER TABLE WSL_PARCEL_MST_MIRROR    DROP COLUMN  PARTY_INV_NO  ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='WSL_parcel_mst_UPLOAD'    AND B.NAME='PARTY_INV_NO')  ALTER TABLE WSL_parcel_mst_UPLOAD    DROP COLUMN  PARTY_INV_NO  ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCPRT_parcel_mst_MIRROR' AND B.NAME='PARTY_INV_NO')  ALTER TABLE DOCPRT_parcel_mst_MIRROR DROP COLUMN  PARTY_INV_NO  ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCPRT_parcel_mst_UPLOAD' AND B.NAME='PARTY_INV_NO')  ALTER TABLE DOCPRT_parcel_mst_UPLOAD DROP COLUMN  PARTY_INV_NO  ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='PRT_parcel_mst_MIRROR'    AND B.NAME='PARTY_INV_NO')  ALTER TABLE PRT_parcel_mst_MIRROR    DROP COLUMN  PARTY_INV_NO  ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='PRT_parcel_mst_UPLOAD'    AND B.NAME='PARTY_INV_NO')  ALTER TABLE PRT_parcel_mst_UPLOAD    DROP COLUMN  PARTY_INV_NO  ;


IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCWSL_parcel_mst_MIRROR' AND B.NAME='PARTY_INV_DT')  ALTER TABLE DOCWSL_parcel_mst_MIRROR DROP COLUMN  PARTY_INV_DT ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCWSL_parcel_mst_UPLOAD' AND B.NAME='PARTY_INV_DT')  ALTER TABLE DOCWSL_parcel_mst_UPLOAD DROP COLUMN  PARTY_INV_DT ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='WSL_PARCEL_MST_MIRROR'    AND B.NAME='PARTY_INV_DT')  ALTER TABLE WSL_PARCEL_MST_MIRROR    DROP COLUMN  PARTY_INV_DT ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='WSL_parcel_mst_UPLOAD'    AND B.NAME='PARTY_INV_DT')  ALTER TABLE WSL_parcel_mst_UPLOAD    DROP COLUMN  PARTY_INV_DT ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCPRT_parcel_mst_MIRROR' AND B.NAME='PARTY_INV_DT')  ALTER TABLE DOCPRT_parcel_mst_MIRROR DROP COLUMN  PARTY_INV_DT ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCPRT_parcel_mst_UPLOAD' AND B.NAME='PARTY_INV_DT')  ALTER TABLE DOCPRT_parcel_mst_UPLOAD DROP COLUMN  PARTY_INV_DT ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='PRT_parcel_mst_MIRROR'    AND B.NAME='PARTY_INV_DT')  ALTER TABLE PRT_parcel_mst_MIRROR    DROP COLUMN  PARTY_INV_DT ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='PRT_parcel_mst_UPLOAD'    AND B.NAME='PARTY_INV_DT')  ALTER TABLE PRT_parcel_mst_UPLOAD    DROP COLUMN  PARTY_INV_DT ;



IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCWSL_parcel_mst_MIRROR' AND B.NAME='PARTY_INV_QTY')  ALTER TABLE DOCWSL_parcel_mst_MIRROR DROP COLUMN  PARTY_INV_QTY ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCWSL_parcel_mst_UPLOAD' AND B.NAME='PARTY_INV_QTY')  ALTER TABLE DOCWSL_parcel_mst_UPLOAD DROP COLUMN  PARTY_INV_QTY ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='WSL_PARCEL_MST_MIRROR'    AND B.NAME='PARTY_INV_QTY')  ALTER TABLE WSL_PARCEL_MST_MIRROR    DROP COLUMN  PARTY_INV_QTY ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='WSL_parcel_mst_UPLOAD'    AND B.NAME='PARTY_INV_QTY')  ALTER TABLE WSL_parcel_mst_UPLOAD    DROP COLUMN  PARTY_INV_QTY ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCPRT_parcel_mst_MIRROR' AND B.NAME='PARTY_INV_QTY')  ALTER TABLE DOCPRT_parcel_mst_MIRROR DROP COLUMN  PARTY_INV_QTY ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCPRT_parcel_mst_UPLOAD' AND B.NAME='PARTY_INV_QTY')  ALTER TABLE DOCPRT_parcel_mst_UPLOAD DROP COLUMN  PARTY_INV_QTY ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='PRT_parcel_mst_MIRROR'    AND B.NAME='PARTY_INV_QTY')  ALTER TABLE PRT_parcel_mst_MIRROR    DROP COLUMN  PARTY_INV_QTY ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='PRT_parcel_mst_UPLOAD'    AND B.NAME='PARTY_INV_QTY')  ALTER TABLE PRT_parcel_mst_UPLOAD    DROP COLUMN  PARTY_INV_QTY ;


IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCWSL_parcel_mst_MIRROR' AND B.NAME='PARTY_INV_AMT')  ALTER TABLE DOCWSL_parcel_mst_MIRROR DROP COLUMN  PARTY_INV_AMT  ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCWSL_parcel_mst_UPLOAD' AND B.NAME='PARTY_INV_AMT')  ALTER TABLE DOCWSL_parcel_mst_UPLOAD DROP COLUMN  PARTY_INV_AMT  ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='WSL_PARCEL_MST_MIRROR'    AND B.NAME='PARTY_INV_AMT')  ALTER TABLE WSL_PARCEL_MST_MIRROR    DROP COLUMN  PARTY_INV_AMT  ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='WSL_parcel_mst_UPLOAD'    AND B.NAME='PARTY_INV_AMT')  ALTER TABLE WSL_parcel_mst_UPLOAD    DROP COLUMN  PARTY_INV_AMT  ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCPRT_parcel_mst_MIRROR' AND B.NAME='PARTY_INV_AMT')  ALTER TABLE DOCPRT_parcel_mst_MIRROR DROP COLUMN  PARTY_INV_AMT  ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='DOCPRT_parcel_mst_UPLOAD' AND B.NAME='PARTY_INV_AMT')  ALTER TABLE DOCPRT_parcel_mst_UPLOAD DROP COLUMN  PARTY_INV_AMT  ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='PRT_parcel_mst_MIRROR'    AND B.NAME='PARTY_INV_AMT')  ALTER TABLE PRT_parcel_mst_MIRROR    DROP COLUMN  PARTY_INV_AMT  ;
IF EXISTS (SELECT TOP 1 'U' FROM SYS.TABLES A JOIN SYS.COLUMNS B ON A.OBJECT_ID=B.OBJECT_ID  WHERE A.NAME='PRT_parcel_mst_UPLOAD'    AND B.NAME='PARTY_INV_AMT')  ALTER TABLE PRT_parcel_mst_UPLOAD    DROP COLUMN  PARTY_INV_AMT  ;
