
 UPDATE A SET
 LASTKEYVAL=  CAST(
 CASE WHEN LEN(REPLACE(LASTKEYVAL,PREFIX,''))<=6 THEN
  PREFIX+CAST(REPLICATE ('0',6-LEN(REPLACE(LASTKEYVAL,PREFIX,''))) AS VARCHAR(100))
       +REPLACE(LASTKEYVAL,PREFIX,'')   
       ELSE
     PREFIX+CAST(RIGHT(LASTKEYVAL,6) AS VARCHAR(100)) END AS VARCHAR(100))
 FROM KEYS   A 
 WHERE TABLENAME='DNPS_MST' AND FINYEAR>='01123' AND LEN(LASTKEYVAL)<>LEN(PREFIX)+6
 