CREATE TRIGGER TRG_config_DELTEMPDBENTRY
ON CONFIG FOR INSERT,UPDATE
AS
BEGIN
	IF EXISTS (SELECT TOP 1 CONFIG_OPTION FROM INSERTED WHERE CONFIG_OPTION='ENABLE_TEMP_DATABASE')
		DELETE FROM CONFIG WHERE CONFIG_OPTION='ENABLE_TEMP_DATABASE'
END



