CREATE TRIGGER [DBO].[TRG_UPD_ART_PARA1_LAST_MODIFIED_ON] ON [DBO].ART_PARA1
FOR INSERT,UPDATE
AS
BEGIN
	IF (SELECT TRIGGER_NESTLEVEL())> 1  OR dbo.FN_CHECKHOLOC()=0
		RETURN
			
	UPDATE ART_PARA1 SET LAST_MODIFIED_ON=CAST(GETDATE() AS DATE) 
	FROM DELETED B WHERE B.row_id=ART_PARA1.row_id
	AND (ART_PARA1.para1_code <> B.para1_code OR ART_PARA1.para1_desc <> B.para1_desc)
END


