CREATE TRIGGER TRG_UPDATE_HO_SYNCH_LAST_UPDATE_FOR_CNM_IRNNO ON CNM01106
FOR UPDATE
AS
BEGIN
      
	  IF EXISTS(SELECT TOP 1 'U' FROM INSERTED A join deleted   B (NOLOCK) ON A.CN_ID =B.CN_ID 
		  WHERE ISNULL(A.IRN_QR_CODE,'') <>'' AND ISNULL(B.IRN_QR_CODE,'')='')
	  BEGIN
	
		  UPDATE A SET HO_SYNCH_LAST_UPDATE ='' 
		  FROM cnm01106 A (NOLOCK) 
		  join deleted   B (NOLOCK) ON A.CN_ID =B.CN_ID 
		  WHERE ISNULL(A.IRN_QR_CODE,'') <>'' AND ISNULL(B.IRN_QR_CODE,'')=''

	 END


END

