CREATE TRIGGER [DBO].[TRG_UPD_ATTRM_LAST_MODIFIED_ON] ON [DBO].[ATTRM]  
 FOR UPDATE  
 AS  
  IF (SELECT TRIGGER_NESTLEVEL())> 1   
   RETURN  

  
          IF OBJECT_ID('TEMPDB..#TMP','U')IS NOT NULL
           DROP TABLE #TMP

        SELECT ATTRIBUTE_CODE INTO #TMP FROM DELETED
    	UPDATE ATTRM SET LAST_MODIFIED_ON=CAST(GETDATE() AS DATE) WHERE ATTRIBUTE_CODE
	    IN (SELECT ATTRIBUTE_CODE FROM #TMP)
