CREATE VIEW VW_FLOOR_STK_TRANSFER_PRINT

AS  
SELECT     
	  M.MEMO_NO   
	 ,CONVERT(VARCHAR,M.MEMO_DT,105) AS TRANSFER_DT
	 ,M.MEMO_DT 
	 ,M.MEMO_ID
	 ,M.CANCELLED     
	 ,A1.ARTICLE_NO
	 ,A1.ARTICLE_NAME
	 ,A1.ARTICLE_CODE 
	 ,P1.PARA1_NAME 
	 ,P2.PARA2_NAME 
	 ,P3.PARA3_NAME 
	 ,P4.PARA4_NAME
	 ,P5.PARA5_NAME 
	 ,P6.PARA6_NAME
	 ,SEC.SECTION_NAME
	 ,SSEC.SUB_SECTION_NAME
	 ,UOM.UOM_NAME
	 ,D.SOURCE_BIN_ID      
	 ,M.TARGET_BIN_ID    
	 ,D.QUANTITY,D.PRODUCT_CODE  
	 ,SDEP.BIN_NAME   AS SOURCE_FLOOR_NAME        
     ,TDEP.BIN_NAME AS TARGET_FLOOR_NAME      
	 ,ISNULL(SKU.PURCHASE_PRICE,0) AS PURCHASE_PRICE,ISNULL(SKU.MRP,0) AS MRP ,ISNULL(SKU.WS_PRICE,0) AS WSP  
	 ,M.REMARKS 
FROM FLOOR_ST_DET D  
JOIN FLOOR_ST_MST  M ON D.MEMO_ID=M.MEMO_ID    
JOIN BIN SDEP ON D.SOURCE_BIN_ID  = SDEP.BIN_ID        
JOIN BIN TDEP ON M.TARGET_BIN_ID  = TDEP.BIN_ID  
JOIN SKU SKU ON SKU.PRODUCT_CODE=D.PRODUCT_CODE   
JOIN ARTICLE A1 ON SKU.ARTICLE_CODE=A1.ARTICLE_CODE
JOIN SECTIOND SSEC ON SSEC.SUB_SECTION_CODE = A1.SUB_SECTION_CODE 
JOIN SECTIONM SEC ON SEC.SECTION_CODE  = SSEC.SECTION_CODE  
JOIN PARA1 P1 ON P1.PARA1_CODE = SKU.PARA1_CODE  
JOIN PARA2 P2 ON P2.PARA2_CODE = SKU.PARA2_CODE
JOIN PARA3 P3 ON P3.PARA3_CODE = SKU.PARA3_CODE
JOIN PARA4 P4 ON P4.PARA4_CODE = SKU.PARA4_CODE
JOIN PARA5 P5 ON P5.PARA5_CODE = SKU.PARA5_CODE
JOIN PARA6 P6 ON P6.PARA6_CODE = SKU.PARA6_CODE
JOIN UOM ON A1.UOM_CODE=UOM.UOM_CODE  
---END OF VIEW - VW_FLOOR_STK_TRANSFER_PRINT
