CREATE VIEW VW_WL_WSLINMSUPPLIST
AS 
SELECT T1.INV_DT AS MEMO_DT,
T1.INV_ID AS MEMO_ID,T1.INV_NO AS MEMO_NO,
(CASE WHEN T1.CANCELLED = 0 THEN T1.SUBTOTAL ELSE 0 END) AS BILL_GROSS_SALE_VALUE,
T1.DISCOUNT_PERCENTAGE AS DISCOUNT_PERCENTAGE,
(CASE WHEN T1.CANCELLED = 0 THEN T1.DISCOUNT_AMOUNT ELSE 0 END) AS DISCOUNT_AMOUNT,
(CASE WHEN T1.CANCELLED = 0 THEN T1.FREIGHT ELSE 0 END) AS FREIGHT,
(CASE WHEN T1.CANCELLED = 0 THEN T1.OTHER_CHARGES ELSE 0 END) AS OTHER_CHARGES,
(CASE WHEN T1.CANCELLED = 0 THEN T1.NET_AMOUNT ELSE 0 END) AS NET_SALE_VALUE,
T1.ROUND_OFF,
T1.GRLR_NO,
T1.SHIPPING_ADDRESS,
T1.REMARKS,
T1.GRLR_DATE,
T1.BANDALS,
T1.THROUGH,
(CASE WHEN T1.CANCELLED = 0 THEN T1.INSURANCE ELSE 0 END) AS INSURANCE,
T1.OCTROI_PERCENTAGE,
(CASE WHEN T1.CANCELLED = 0 THEN T1.OCTROI_AMOUNT ELSE 0 END) AS OCTROI_AMOUNT,
T1.PARTY_PO_NO,
T1.MANUAL_INV_NO,
(CASE WHEN T1.CANCELLED = 1 THEN 0 ELSE ISNULL(T2.TOTAL_QUANTITY,0) END) AS TOTAL_QUANTITY,
(CASE WHEN T1.CANCELLED = 1 THEN 0 ELSE ISNULL(T2.ITEM_DISCOUNT_AMOUNT,0) END) AS ITEM_DISCOUNT_AMOUNT,
(CASE WHEN T1.CANCELLED = 1 THEN 0 ELSE ISNULL(T2.ITEM_GROSS_SALE_VALUE,0) END) AS ITEM_GROSS_SALE_VALUE,
T3.AC_NAME AS CUSTOMER_NAME,T5.EMP_NAME AS SALES_PERSON,
(CASE WHEN T1.INV_MODE = 1 THEN 'PARTY INVOICE' ELSE 'GROUP INVOICE' END) AS INVOICE_TYPE, 
(CASE WHEN T1.CANCELLED = 1 THEN 'CANCELLED' ELSE '' END) AS CANCELLED,
T6.DEPT_ID ,T6.DEPT_NAME,
(CASE WHEN T1.APPROVED = 1 THEN 'YES' ELSE 'NO' END) AS APPROVED,
(CASE WHEN T1.POSTEDINAC  = 1 THEN 'POSTED' ELSE 'PENDING' END) AS AC_POSTED,  
T1.FIN_YEAR,
COM.COMPANY_CODE,
T1.MEMO_TYPE,
L.DEPT_ID AS LOC_ID,
L.DEPT_NAME AS LOC_NAME,
F.FORM_NAME AS TAX_TYPE,
T2.TAX_PERCENTAGE,T2.TAX_AMOUNT,ISNULL(T10.NO_OF_BOXES,0) AS NO_OF_BOXES    
FROM INMSUPP T1 (NOLOCK)
JOIN LMV01106 T3 ON T3.AC_CODE = T1.AC_CODE
JOIN EMPLOYEE T5 ON T5.EMP_CODE = T1.EMP_CODE
LEFT OUTER JOIN LOCATION T6 ON T6.DEPT_ID = T1.PARTY_DEPT_ID  
LEFT OUTER JOIN 
(
 SELECT INV_ID,ITEM_FORM_ID,ITEM_TAX_PERCENTAGE AS TAX_PERCENTAGE,
        SUM(QUANTITY) AS TOTAL_QUANTITY,SUM(DISCOUNT_AMOUNT) AS ITEM_DISCOUNT_AMOUNT,
		SUM(QUANTITY*RATE) AS ITEM_GROSS_SALE_VALUE,SUM(ITEM_TAX_AMOUNT) AS TAX_AMOUNT
 FROM INDSUPP 
 GROUP BY INV_ID,ITEM_FORM_ID,ITEM_TAX_PERCENTAGE
) T2 ON T2.INV_ID=T1.INV_ID 
 
LEFT OUTER JOIN   
(  
  SELECT  COUNT(DISTINCT BOX_NO) AS NO_OF_BOXES,INV_ID FROM INDSUPP GROUP BY INV_ID
) T10 ON T10.INV_ID=T1.INV_ID  

LEFT OUTER JOIN COMPANY COM ON 1=1 AND COM.COMPANY_CODE='01'
LEFT OUTER JOIN LOCATION  L (NOLOCK) ON T1.location_code/*LEFT(T1.INV_ID,2)*//*Rohit 05-11-2024*/ = L.DEPT_ID    
LEFT OUTER JOIN FORM F ON T2.ITEM_FORM_ID = F.FORM_ID
