CREATE VIEW VW_WL_PURCHASEINVOICELIST   

AS             
SELECT     
A.RECEIPT_DT AS 'RECEIPT_DT',   
A.MRR_ID AS 'MEMO_ID',     
A.MRR_NO ,   
B.AC_NAME AS 'SUPPLIER_NAME',    
A.INV_NO AS 'CHALLAN_NO',     
A.BILL_NO AS 'BILL_NO',   
A.INV_DT AS 'PARTY_BILL_DATE',    

(CASE WHEN A.INV_MODE=1 THEN 'PARTY INVOICE' ELSE 'GROUP INVOICE' END) AS INVOICE_TYPE ,  
(CASE WHEN A.POSTEDINAC  = 1 OR ISNULL(VM.VM_ID,'')<>'' THEN 'POSTED' ELSE 'PENDING' END) AS AC_POSTED ,   
(CASE WHEN A.CANCELLED = 1 THEN 'CANCELLED' ELSE '' END) AS CANCELLED,  
(CASE WHEN A.CANCELLED = 0 THEN A.SUBTOTAL  ELSE 0 END) AS 'SUBTOTAL',    
A.DISCOUNT_PERCENTAGE AS 'DISCOUNT_PERCENTAGE',    
(CASE WHEN A.CANCELLED = 0 THEN A.DISCOUNT_AMOUNT  ELSE 0 END)  AS 'BILL_DISCOUNT_AMOUNT',   
(CASE WHEN A.CANCELLED = 0 THEN ISNULL(D.TOTAL_QUANTITY,0) ELSE 0 END)  AS TOTAL_QUANTITY,   
(CASE WHEN A.CANCELLED = 0 THEN A.FREIGHT  ELSE 0 END) AS 'FREIGHT',    
(CASE WHEN A.CANCELLED = 0 THEN A.OTHER_CHARGES  ELSE 0 END) AS 'OTHER_CHARGES',    
(CASE WHEN A.CANCELLED = 0 THEN A.ROUND_OFF  ELSE 0 END) AS 'ROUND_OFF',  
(CASE WHEN A.CANCELLED = 0 THEN ISNULL(D.TOTAL_MRP_VALUE,0) ELSE 0 END) AS TOTAL_MRP_VALUE,    
(CASE WHEN A.CANCELLED = 0 THEN A.TOTAL_AMOUNT  ELSE 0 END) AS 'NET_PURCHASE_VALUE',            
A.RECEIVED_BY AS 'RECEIVED_BY', A.REMARKS AS 'REMARKS',      
H.USERNAME AS 'CREATED_BY_USER',    
A.FIN_YEAR,A.MEMO_TYPE, BIN.BIN_NAME AS BIN,  
L.DEPT_ID  AS LOC_ID,L.DEPT_NAME AS LOC_NAME  
,(CASE WHEN ISNULL(PB.REF_MRR_ID ,'') = '' THEN 'PENDING' ELSE 'BILL RAISED' END) AS BILL_STATUS ,
 F.FORM_NAME AS TAX_TYPE,D.TAX_PERCENTAGE ,D.TAX_AMOUNT     
FROM PIM01106 A (NOLOCK)             
JOIN LM01106 B (NOLOCK)  ON A.AC_CODE = B.AC_CODE            
JOIN USERS H (NOLOCK) ON A.USER_CODE = H.USER_CODE  
JOIN BIN  (NOLOCK) ON BIN.BIN_ID = A.BIN_ID 
LEFT OUTER JOIN VM_MRR VM (NOLOCK) ON VM.MRR_ID=A.MRR_ID  
LEFT OUTER JOIN   
(  
	SELECT MRR_ID, FORM_ID,TAX_PERCENTAGE ,SUM(QUANTITY) AS 'TOTAL_QUANTITY',     
	SUM(QUANTITY*MRP) AS 'TOTAL_MRP_VALUE',    
	SUM(GROSS_PURCHASE_PRICE * QUANTITY) AS 'ITEM_GROSS_AMOUNT',  
	SUM(DISCOUNT_AMOUNT) AS 'ITEM_DISCOUNT_AMOUNT' , SUM(TAX_AMOUNT) AS TAX_AMOUNT
	FROM PID01106(NOLOCK) GROUP BY MRR_ID  , FORM_ID,TAX_PERCENTAGE
) D ON D.MRR_ID=A.MRR_ID   
LEFT OUTER JOIN LOCATION  L (NOLOCK) ON A.DEPT_ID = L.DEPT_ID   
LEFT OUTER JOIN  

(
 SELECT MRR_ID AS REF_MRR_ID FROM PIM01106 (NOLOCK) WHERE PIM_MODE=5 AND 
 CANCELLED = 0
) PB ON A.MRR_ID = PB.REF_MRR_ID      
 LEFT OUTER JOIN FORM F(NOLOCK) ON D.FORM_ID = F.FORM_ID
