CREATE VIEW VW3S_WIPXNS
AS
SELECT SM.MEMO_ID,SM.MEMO_NO,SM.RECEIPT_DT AS XN_DT,'SPI' AS XN_TYPE,WP.PRODUCT_CODE,SD.QUANTITY
	  ,SD.PURCHASE_PRICE AS RATE,CONVERT(NUMERIC(18,2),0) AS VALUE_ADD
	  ,(SD.QUANTITY*SD.PURCHASE_PRICE) AS NET_VALUE
	  ,'0000000' AS JOB_CODE
	  ,WP.WIP_UID
FROM SNC_MST SM(NOLOCK)
JOIN SNC_DET SD(NOLOCK) ON SM.MEMO_ID=SD.MEMO_ID
JOIN WIP_PMT WP(NOLOCK) ON SD.ROW_ID=WP.XN_ROW_ID
WHERE SM.CANCELLED=0 AND WIP=1
UNION ALL
SELECT JIM.ISSUE_ID,JIM.ISSUE_NO,JIM.ISSUE_DT AS XN_DT,'JWI' AS XN_TYPE,JID.PRODUCT_CODE,-JID.QUANTITY
	  ,JID.PREV_JOB_RATE AS RATE,CONVERT(NUMERIC(18,2),JID.JOB_RATE) AS VALUE_ADD
	  ,(JID.QUANTITY*(JID.PREV_JOB_RATE+JID.JOB_RATE)) AS NET_VALUE
	  ,JID.JOB_CODE
	  ,JID.WIP_UID
FROM JOBWORK_ISSUE_MST JIM(NOLOCK)
JOIN JOBWORK_ISSUE_DET JID(NOLOCK) ON JIM.ISSUE_ID=JID.ISSUE_ID
WHERE JIM.WIP=1 AND JIM.CANCELLED=0 
-----PENDING JOBWORK ISSUE DETAILS SHOULD BE CONSIDERED IN OPENING STOCK
--UNION ALL
--SELECT JIM.ISSUE_NO,JIM.ISSUE_DT AS XN_DT,'PWI' AS XN_TYPE,JID.PRODUCT_CODE,JID.QUANTITY
--	  ,JID.PREV_JOB_RATE AS RATE,CONVERT(NUMERIC(18,2),JID.JOB_RATE) AS VALUE_ADD
--	  ,(JID.QUANTITY*(JID.PREV_JOB_RATE+JID.JOB_RATE)) AS NET_VALUE
--	  ,JID.JOB_CODE
--	  ,JID.WIP_UID
--FROM JOBWORK_ISSUE_MST JIM(NOLOCK)
--JOIN JOBWORK_ISSUE_DET JID(NOLOCK) ON JIM.ISSUE_ID=JID.ISSUE_ID
--LEFT JOIN JOBWORK_RECEIPT_DET JRD(NOLOCK) ON JRD.REF_ROW_ID=JID.ROW_ID
--LEFT JOIN JOBWORK_RECEIPT_MST JRM(NOLOCK) ON JRD.RECEIPT_ID=JRM.RECEIPT_ID
--WHERE JIM.WIP=1 AND JIM.CANCELLED=0 AND ISNULL(JRM.CANCELLED,0)=0 AND JID.QUANTITY-ISNULL(JRD.QUANTITY,0)>0 
UNION ALL
SELECT JRM.RECEIPT_ID,JRM.RECEIPT_NO,JRM.RECEIPT_DT AS XN_DT,'JWR' AS XN_TYPE,JRD.PRODUCT_CODE,JRD.QUANTITY
	  ,JRD.PREV_JOB_RATE AS RATE,CONVERT(NUMERIC(18,2),JRD.JOB_RATE) AS VALUE_ADD
	  ,(JRD.QUANTITY*(JRD.PREV_JOB_RATE+JRD.JOB_RATE)) AS NET_VALUE
	  ,JRD.JOB_CODE
	  ,WP.WIP_UID
FROM JOBWORK_RECEIPT_MST JRM(NOLOCK)
JOIN JOBWORK_RECEIPT_DET JRD(NOLOCK) ON JRM.RECEIPT_ID=JRD.RECEIPT_ID
JOIN WIP_PMT WP(NOLOCK) ON JRD.ROW_ID=WP.XN_ROW_ID
WHERE JRM.WIP=1 AND JRM.CANCELLED=0 
UNION ALL
SELECT SM.MEMO_ID,SM.MEMO_NO,SM.RECEIPT_DT AS XN_DT,'SPR' AS XN_TYPE,WP.PRODUCT_CODE,-SCD.QUANTITY
	  ,SCD.PURCHASE_PRICE AS RATE,CONVERT(NUMERIC(18,2),0) AS VALUE_ADD
	  ,(SCD.QUANTITY*SCD.PURCHASE_PRICE) AS NET_VALUE
	  ,WP.JOB_CODE
	  ,WP.WIP_UID
FROM SNC_MST SM(NOLOCK)
JOIN SNC_CONSUMABLE_DET SCD(NOLOCK) ON SCD.MEMO_ID=SM.MEMO_ID
JOIN WIP_PMT WP(NOLOCK) ON SCD.WIP_UID=WP.WIP_UID
WHERE SM.CANCELLED=0 AND SM.WIP=0
--END OF VIEW -VW3S_WIPXNS
