CREATE VIEW VW_WL_PRD_WSRINV_REP  

AS  
SELECT T1.CN_ID ,  
T1.CN_DT AS MST_XN_DT ,  
T1.CN_NO AS MST_MEMO_NO,  
T1.SUBTOTAL AS MST_SUBTOTAL,  
T1.DISCOUNT_PERCENTAGE AS MST_DISCOUNT_PERCENTAGE ,  
T1.DISCOUNT_AMOUNT AS MST_DISCOUNT_AMOUNT ,  
T1.FREIGHT AS MST_FREIGHT ,  
T1.OTHER_CHARGES AS MST_OTHER_CHARGES ,  
T1.TOTAL_AMOUNT AS MST_TOTAL_AMOUNT ,  
T1.REMARKS AS MST_REMARKS ,  
T1.GRLR_DATE AS MST_GRLR_DATE ,  
T1.BANDALS AS MST_BANDALS ,  
T1.THROUGH AS MST_THROUGH ,  
T1.TAX_PERCENTAGE AS MST_TAX_PERCENTAGE ,  
T1.TAX_AMOUNT AS MST_TAX_AMOUNT ,  
T1.MANUAL_INV_NO AS MST_MANUAL_INV_NO,  
T1.EXCISE_ACCESSIBLE_AMOUNT AS MST_EXCISE_ACCESSIBLE_AMOUNT,  
T1.EXCISE_EDU_CESS_PERCENTAGE AS MST_EXCISE_EDU_CESS_PERCENTAGE ,  
T1.EXCISE_HEDU_CESS_PERCENTAGE AS MST_EXCISE_HEDU_CESS_PERCENTAGE,  
T1.EXCISE_DUTY_PERCENTAGE AS MST_EXCISE_DUTY_PERCENTAGE,  
T1.EXCISE_EDU_CESS_AMOUNT AS MST_EXCISE_EDU_CESS_AMOUNT,  
T1.EXCISE_HEDU_CESS_AMOUNT AS MST_EXCISE_HEDU_CESS_AMOUNT,  
T1.EXCISE_DUTY_AMOUNT AS MST_EXCISE_DUTY_AMOUNT,  
T1.EXCISE_ACCESSIBLE_PERCENTAGE AS MST_EXCISE_ACCESSIBLE_PERCENTAGE,  
T1.ROUND_OFF AS MST_ROUND_OFF,  
T2.PRODUCT_UID MST_PRODUCT_UID,  
T2.QUANTITY AS CAL_QUANTITY,  
T2.RATE AS CAL_RATE,  
T2.DISCOUNT_PERCENTAGE AS CAL_DISCOUNT_PERCENTAGE,  
T2.DISCOUNT_AMOUNT AS CAL_DISCOUNT_AMOUNT,  
(T2.QUANTITY*T2.RATE)-T2.DISCOUNT_AMOUNT AS CAL_AMOUNT,  
T3.AC_NAME AS MST_AC_NAME,  
T4.FORM_NAME AS MST_FORM_NAME,  
  
(CASE WHEN T1.CANCELLED = 1 THEN 'CANCELLED' ELSE '' END) AS MST_CANCELLED  
,T1.CN_NO  
,T1.CN_DT  
,T1.AC_CODE  
,T1.REMARKS  
,T1.SUBTOTAL  
,T1.DISCOUNT_PERCENTAGE  
,T1.DISCOUNT_AMOUNT  
,T1.OTHER_CHARGES  
,T1.FREIGHT  
,T1.TAX_PERCENTAGE  
,T1.TAX_AMOUNT  
,T1.ROUND_OFF  
,T1.TOTAL_AMOUNT  
,T1.CANCELLED  
,T1.DEPT_ID  
,T1.CHECKED_BY  
,T1.SENT_BY  
,T1.COMPANY_CODE  
,T1.FORM_ID  
,T1.USER_CODE  
,T1.LAST_UPDATE  
,T1.TS  
,T1.SENT_TO_HO  
,T1.FIN_YEAR  
,T1.THROUGH  
,T1.GRLR_DATE  
,T1.GRLR_NO  
,T1.BANDALS  
,T1.CN_TYPE  
,T1.RATE_DIFF  
,T1.LOCAL_SALES  
,T1.PARTY_DEPT_ID  
,T1.UPLOADED_TO_ACTIVSTREAM  
,T1.BROKER_AC_CODE  
,T1.BROKER_COMM_PERCENTAGE  
,T1.BROKER_COMM_AMOUNT  
,T1.ROUTE_FORM1  
,T1.ROUTE_FORM2  
,T1.DT_CODE  
,T1.DISCOUNT_PER_PCS  
,T1.POSTEDINAC  
,T1.EDT_USER_CODE  
,T1.CN_TIME  
,T1.MANUAL_INV_NO  
,T1.CNC_DT  
,T1.BILL_LEVEL_TAX  
,T1.CUSTOM_DUTY_MARK_DOWN_PCT  
,T1.BILL_LEVEL_TAX_METHOD  
,T1.RFOPT_UPDATED  
,T1.EXCISE_ACCESSIBLE_PERCENTAGE  
,T1.EXCISE_ACCESSIBLE_AMOUNT  
,T1.EXCISE_EDU_CESS_PERCENTAGE  
,T1.EXCISE_HEDU_CESS_PERCENTAGE  
,T1.EXCISE_DUTY_PERCENTAGE  
,T1.EXCISE_EDU_CESS_AMOUNT  
,T1.EXCISE_HEDU_CESS_AMOUNT  
,T1.EXCISE_DUTY_AMOUNT  
,T1.EXCISE_INVOICE  
,T1.MODE  
,T2.PRINT_LABEL  
,T2.RFNET  
,T2.RFNET_WOTAX  
,T2.LOCAL_TAX_STATUS  
,T2.RATE  
,T2.CHALLAN_ID  
,T2.CN_TAX_METHOD  
,T2.NET_RATE  
,T2.OH_AMOUNT  
,T2.RATE_PER_CONV_UOM  
,T2.CUSTOM_DUTY_PER  
,T2.CUSTOM_DUTY_AMT  
,T2.CVD_PER  
,T2.EDU_CESS_CVD  
,T2.H_EDU_CESS_CVD  
,T2.CVD_AMT  
,T2.EDU_CESS_CUSTOM  
,T2.TOTAL_CUSTOM_DUTY_AMT  
,T2.H_EDU_CESS_CUSTOM  
,T2.INV_NO  
,T2.INV_DT  
,T2.EMP_CODE  
,T2.EXCISE_MRP  
,T2.PRODUCT_UID  
,T2.QUANTITY  
,T2.ROW_ID  
,T3.AC_NAME  
,T3.ALIAS  
,T3.HEAD_CODE  
,T3.CLOSING_BALANCE  
,T3.CLOSING_BALANCE_CR_DR  
,T3.PRINT_LEDGER  
,T3.PRINT_NAME  
,T3.ADDRESS0  
,T3.ADDRESS1  
,T3.ADDRESS2  
,T3.AREA_CODE  
,T3.AREA_NAME  
,T3.PINCODE  
,T3.CITY_CODE  
,T3.CITY  
,T3.STATE_CODE  
,T3.STATE  
,T3.CST_NO  
,T3.CST_DT  
,T3.SST_NO  
,T3.SST_DT  
,T3.TIN_NO  
,T3.TIN_DT  
,T3.PHONES_R  
,T3.PHONES_O  
,T3.PHONES_FAX  
,T3.MOBILE  
,T3.E_MAIL  
,T3.TAX_CODE  
,T3.CREDIT_DAYS  
,T3.BILL_BY_BILL  
,T3.ON_HOLD  
,T3.THROUGH_BROKER  
,T3.BROKER_COMM_PERCENT  
,T3.CREDIT_LIMIT  
,T3.ALLOW_CREDITOR_DEBTOR  
,T3.DPWEF_DT  
,T3.CST_PERCENTAGE  
,T3.PAN_NO  
,T3.CUSTOMER_CODE  
,T3.GLN_NO  
,T3.MP_PERCENTAGE  
,T3.MRP_CALC_MODE  
,T3.TDS_CODE  
,T3.INV_RATE_TYPE  
,T3.OUTSTATION_PARTY  
,T3.SALES_AC_CODE  
,T3.USERNAME  
,T3.EDT_USERNAME  
,T4.FORM_NAME  
,T4.PURCHASE_AC_CODE  
,T4.SALE_AC_CODE  
,T4.TAX_AC_CODE  
,T4.POST_TAX_SEPARATELY  
,T4.PUR_RETURN_AC_CODE  
,T4.SALE_RETURN_AC_CODE  
,T4.PHYSICAL_FORM  
,T4.SERIES  
,T4.EXCISE_EDU_CESS_AC_CODE  
,T4.EXCISE_HEDU_CESS_AC_CODE  
,T4.EXCISE_DUTY_AC_CODE  
,LCT.DEPT_NAME AS BILLED_LOCATION_DEPT_NAME  
,LCT.MAJOR_DEPT_ID AS BILLED_LOCATION_MAJOR_DEPT_ID  
,LCT.LOC_TYPE AS BILLED_LOCATION_LOC_TYPE  
,LCT.AREA_CODE AS BILLED_LOCATION_AREA_CODE  
,LA.AREA_NAME AS BILLED_LOCATION_AREA  
,LC.CITY AS BILLED_LOCATION_CITY  
,LS.STATE AS BILLED_LOCATION_STATE  
,LRG.REGION_NAME AS BILLED_LOCATION_REGION  
,LCT.DATE_OF_OPENING AS BILLED_LOCATION_DATE_OF_OPENING  
,LCT.REPORT_BLOCKED AS BILLED_LOCATION_REPORT_BLOCKED  
,LCT.ACCOUNTS_POSTING_DEPT_ID AS BILLED_LOCATION_ACCOUNTS_POSTING_DEPT_ID  
,LCT.CONTROL_AC_CODE AS BILLED_LOCATION_CONTROL_AC_CODE  
,LCT.UPD_PURINFO AS BILLED_LOCATION_UPD_PURINFO  
,LCT.SSPL_REG_KEY AS BILLED_LOCATION_SSPL_REG_KEY  
,LCT.WIZCOM_ENABLED AS BILLED_LOCATION_WIZCOM_ENABLED  
,LCT.EXCISABLE AS BILLED_LOCATION_EXCISABLE  
,LCT.FR_TYPE AS BILLED_LOCATION_FR_TYPE  
,LCT.PRIMARY_EMAIL_PORT AS BILLED_LOCATION_PRIMARY_EMAIL_PORT  
,LCT.PRIMARY_EMAIL AS BILLED_LOCATION_PRIMARY_EMAIL  
,LCT.PRIMARY_EMAIL_SMTP AS BILLED_LOCATION_PRIMARY_EMAIL_SMTP  
,LCT.PRIMARY_EMAIL_PWD AS BILLED_LOCATION_PRIMARY_EMAIL_PWD  
,LCT.PRIMARY_EMAIL_SSL AS BILLED_LOCATION_PRIMARY_EMAIL_SSL  
,LCT.SSPL_GRP_CODE AS BILLED_LOCATION_SSPL_GRP_CODE  
,LCT.PUR_LOC AS BILLED_LOCATION_PUR_LOC  
,LCT.ADDRESS1 AS BILLED_LOCATION_ADDRESS1  
,LCT.ADDRESS2 AS BILLED_LOCATION_ADDRESS2  
,LCT.DEPT_AC_CODE AS BILLED_LOCATION_DEPT_AC_CODE  
,LCT.LST_NO AS BILLED_LOCATION_LST_NO  
,LCT.LST_DT AS BILLED_LOCATION_LST_DT  
,LCT.DEPT_ALIAS AS BILLED_LOCATION_DEPT_ALIAS  
,LCT.PHONE AS BILLED_LOCATION_PHONE  
,LLCT.DEPT_NAME AS LOCATION_DEPT_NAME  
,LLCT.MAJOR_DEPT_ID AS LOCATION_MAJOR_DEPT_ID  
,LLCT.LOC_TYPE AS LOCATION_LOC_TYPE  
,LLCT.AREA_CODE AS LOCATION_AREA_CODE  
,LLA.AREA_NAME AS LOCATION_AREA  
,LLC.CITY AS LOCATION_CITY  
,LLS.STATE AS LOCATION_STATE  
,LLRG.REGION_NAME AS LOCATION_REGION  
,LLCT.DATE_OF_OPENING AS LOCATION_DATE_OF_OPENING  
,LLCT.REPORT_BLOCKED AS LOCATION_REPORT_BLOCKED  
,LLCT.ACCOUNTS_POSTING_DEPT_ID AS LOCATION_ACCOUNTS_POSTING_DEPT_ID  
,LLCT.CONTROL_AC_CODE AS LOCATION_CONTROL_AC_CODE  
,LLCT.UPD_PURINFO AS LOCATION_UPD_PURINFO  
,LLCT.SSPL_REG_KEY AS LOCATION_SSPL_REG_KEY  
,LLCT.WIZCOM_ENABLED AS LOCATION_WIZCOM_ENABLED  
,LLCT.EXCISABLE AS LOCATION_EXCISABLE  
,LLCT.FR_TYPE AS LOCATION_FR_TYPE  
,LLCT.PRIMARY_EMAIL_PORT AS LOCATION_PRIMARY_EMAIL_PORT  
,LLCT.PRIMARY_EMAIL AS LOCATION_PRIMARY_EMAIL  
,LLCT.PRIMARY_EMAIL_SMTP AS LOCATION_PRIMARY_EMAIL_SMTP  
,LLCT.PRIMARY_EMAIL_PWD AS LOCATION_PRIMARY_EMAIL_PWD  
,LLCT.PRIMARY_EMAIL_SSL AS LOCATION_PRIMARY_EMAIL_SSL  
,LLCT.SSPL_GRP_CODE AS LOCATION_SSPL_GRP_CODE  
,LLCT.PUR_LOC AS LOCATION_PUR_LOC  
,LLCT.ADDRESS1 AS LOCATION_ADDRESS1  
,LLCT.ADDRESS2 AS LOCATION_ADDRESS2  
,LLCT.DEPT_AC_CODE AS LOCATION_DEPT_AC_CODE  
,LLCT.LST_NO AS LOCATION_LST_NO  
,LLCT.LST_DT AS LOCATION_LST_DT  
,LLCT.DEPT_ALIAS AS LOCATION_DEPT_ALIAS  
,LLCT.PHONE AS LOCATION_PHONE  
,LLLLCT.DEPT_NAME AS LOCATION_MAJJOR_DEPT_NAME  
,EMP.EMP_NAME  
,EMP.EMP_ALIAS  
,EMP.EMP_HEAD  
,MEMP.EMP_NAME AS EMP_HEAD_NAME  
,DLM.AC_NAME AS EXCISE_DUTY_AC_NAME  
,ELM.AC_NAME AS  EXCISE_EDU_CESS_AC_NAME  
,HLM.AC_NAME AS EXCISE_HEDU_CESS_AC_NAME  
,PRLM.AC_NAME AS PUR_RETURN_AC_NAME  
,SRLM.AC_NAME AS SALE_RETURN_AC_NAME  
,PLM.AC_NAME AS  PURCHASE_AC_NAME  
,SLM.AC_NAME AS   SALE_AC_NAME  
,TLM.AC_NAME AS TAX_AC_NAME
,ART.ARTICLE_NO ,P1.PARA1_NAME ,P2.PARA2_NAME
FROM PRD_CNM01106 T1  
JOIN PRD_CND01106 T2 ON T1.CN_ID = T2.CN_ID  
JOIN LMV01106 T3 ON T3.AC_CODE = T1.AC_CODE  
JOIN FORM   T4 ON T4.FORM_ID = T1.FORM_ID  
JOIN LOCATION LCT ON T1.BILLED_FROM_DEPT_ID=LCT.DEPT_ID
JOIN LOCATION LLCT ON T1.DEPT_ID=LLCT.DEPT_ID  
JOIN COMPANY CMP ON T1.COMPANY_CODE=CMP.COMPANY_CODE  
LEFT OUTER JOIN AREA LA ON LCT.AREA_CODE=LA.AREA_CODE  
LEFT OUTER JOIN CITY LC ON LA.CITY_CODE=LC.CITY_CODE  
LEFT OUTER JOIN STATE LS ON LC.STATE_CODE=LS.STATE_CODE  
LEFT OUTER JOIN REGIONM LRG ON LS.REGION_CODE=LRG.REGION_CODE   
JOIN AREA LLA ON LLCT.AREA_CODE=LLA.AREA_CODE  
JOIN CITY LLC ON LLA.CITY_CODE=LLC.CITY_CODE  
JOIN STATE LLS ON LLC.STATE_CODE=LLS.STATE_CODE  
JOIN REGIONM LLRG ON LLS.REGION_CODE=LLRG.REGION_CODE   
JOIN LOCATION LLLLCT ON LLCT.MAJOR_DEPT_ID=LLLLCT.DEPT_ID  
JOIN EMPLOYEE EMP ON T2.EMP_CODE=EMP.EMP_CODE  
JOIN EMPLOYEE MEMP ON EMP.EMP_HEAD=MEMP.EMP_CODE  
JOIN LM01106 DLM ON T4.EXCISE_DUTY_AC_CODE=DLM.AC_CODE  
JOIN LM01106 ELM ON T4.EXCISE_EDU_CESS_AC_CODE=ELM.AC_CODE  
JOIN LM01106 HLM ON T4.EXCISE_HEDU_CESS_AC_CODE=HLM.AC_CODE  
JOIN LM01106 PRLM ON T4.PUR_RETURN_AC_CODE=PRLM.AC_CODE  
JOIN LM01106 SRLM ON T4.SALE_RETURN_AC_CODE=SRLM.AC_CODE  
JOIN LM01106 PLM ON T4.PURCHASE_AC_CODE=PLM.AC_CODE  
JOIN LM01106 SLM ON T4.SALE_AC_CODE=SLM.AC_CODE  
JOIN LM01106 TLM ON T4.TAX_AC_CODE=TLM.AC_CODE  
JOIN PRD_SKU SKU ON T2.PRODUCT_UID=SKU.PRODUCT_UID  
JOIN ARTICLE ART ON SKU.ARTICLE_CODE = ART.ARTICLE_CODE 
JOIN PARA1 P1 ON SKU.PARA1_CODE = P1.PARA1_CODE 
JOIN PARA2 P2 ON SKU.PARA2_CODE = P2.PARA2_CODE
