CREATE VIEW VW_ISSUE_MATERIAL_PRINT 

AS
SELECT DISTINCT  ARTSET.ARTICLE_NO AS ARTICLE_SET_NO  ,ARTSET.ARTICLE_NAME AS ARTICLE_SET_NAME  
	,ARTCOMP.ARTICLE_NO AS COMPONENT_NO  ,ARTCOMP.ARTICLE_NAME AS COMPONENT_NAME  ,ARTDET.ARTICLE_NO   
	,ARTDET.ARTICLE_NAME ,ARTDET.ARTICLE_DESC ,PARA1.PARA1_NAME AS COLOR  ,PARA2.PARA2_NAME AS SIZE
	,DET.REF_PRD_WORKORDER_MEMOID AS [WORK ORDER ID]  ,WOM.MEMO_NO AS WORK_ORDER_NO  ,WOM.REF_NO
  , M.MEMO_NO   ,M.MEMO_DT   ,M.MEMO_ID   ,M.REMARKS   ,M.CANCELLED ,M.USER_CODE ,USERS.USERNAME ,DET.JOB_CODE   
  ,JOBS.JOB_NAME , '' AS [JOB TARGET DATE]  --CONVERT(VARCHAR,TGT.TARGET_DT,106) AS [JOB TARGET DATE] 
  ,UOM.UOM_NAME
  
  ,M.SOURCE_DEPARTMENT_ID   ,SDEP.DEPARTMENT_NAME AS SOURCE_DEPARTMENT_NAME  
  ,M.TARGET_DEPARTMENT_ID   ,TDEP.DEPARTMENT_NAME AS TARGET_DEPARTMENT_NAME  
  ,M.COMPANY_CODE   ,D.GROSS_WEIGHT   ,D.NO_OF_PCS    ,D.QUANTITY    
  ,D.TYPE  ,EMP.EMP_FNAME+' '+EMP.EMP_LNAME AS PC_NAME
FROM PRD_ISSUE_MATERIAL_MST M   
JOIN PRD_ISSUE_MATERIAL_DET DET ON M.MEMO_ID=DET.MEMO_ID 
JOIN PRD_WO_MST WOM ON DET.REF_PRD_WORKORDER_MEMOID = WOM.MEMO_ID   
JOIN PRD_DEPARTMENT_MST SDEP ON M.SOURCE_DEPARTMENT_ID  = SDEP.DEPARTMENT_ID  
JOIN PRD_DEPARTMENT_MST TDEP ON M.TARGET_DEPARTMENT_ID  = TDEP.DEPARTMENT_ID  
JOIN JOBS ON DET.JOB_CODE = JOBS.JOB_CODE   
JOIN USERS ON M.USER_CODE = USERS.USER_CODE   
JOIN ARTICLE ARTSET ON WOM.ARTICLE_SET_CODE = ARTSET.ARTICLE_CODE    
JOIN PRD_ISSUE_MATERIAL_DET D ON M.MEMO_ID = D.MEMO_ID   
JOIN ARTICLE ARTDET ON D.ARTICLE_CODE = ARTDET.ARTICLE_CODE   
JOIN UOM ON ARTDET.UOM_CODE=UOM.UOM_CODE
JOIN PARA1  ON D.PARA1_CODE = PARA1.PARA1_CODE   
JOIN PARA2  ON D.PARA2_CODE = PARA2.PARA2_CODE   
JOIN ARTICLE ARTCOMP ON D.REF_COMPONENT_ARTICLE_CODE = ARTCOMP.ARTICLE_CODE  
LEFT OUTER JOIN EMP_MST EMP ON EMP.EMP_ID=WOM.EMP_CODE
