CREATE VIEW VW_WL_ARCMST
AS
SELECT A.ADV_REC_ID,A.FIN_YEAR,
(CASE WHEN A.ARC_TYPE=1 THEN 'RECEIPT' ELSE 'PAYMENT' END) AS [MST_ARC_TYPE],
(CASE WHEN A.ARCT=1 THEN 'OUTSTANDING' 
	  WHEN A.ARCT=2 THEN 'ADVANCE VOUCHERS'
	  ELSE 'OTHER CHARGES' END) AS [MST_AC_TYPE],A.ADV_REC_NO AS MST_MEMO_NO,A.ADV_REC_DT AS MST_XN_DT,
CUST.CUSTOMER_TITLE AS MST_CUSTOMER_TITLE,CUST.CUSTOMER_FNAME AS MST_CUSTOMER_FNAME,CUST.CUSTOMER_LNAME AS MST_CUSTOMER_LNAME ,
A.REMARKS AS MST_REMARKS,
A.AMOUNT AS CAL_AMOUNT,A.DISCOUNT_AMOUNT AS CAL_DISCOUNT_AMOUNT,A.NET_AMOUNT AS CAL_NET_AMOUNT,C.USERNAME AS MST_USERNAME,
PMST.PAYMODE_NAME AS MST_PAYMODE_NAME,B.REMARKS AS MST_PAYMENT_REMARKS,B.AMOUNT AS CAL_PAYMENT_AMOUNT ,A.DISCOUNT_PERCENTAGE AS CAL_DISCOUNT_PERCENTAGE
FROM ARC01106 A
JOIN PAYMODE_XN_DET B ON B.MEMO_ID=A.ADV_REC_ID AND B.XN_TYPE='ARC'
JOIN USERS C ON C.USER_CODE=A.USER_CODE
JOIN PAYMODE_MST PMST ON PMST.PAYMODE_CODE=B.PAYMODE_CODE
JOIN CUSTDYM CUST ON CUST.CUSTOMER_CODE=A.CUSTOMER_CODE
