CREATE VIEW VW_ARTICLE_QBF

AS  
SELECT A.ARTICLE_CODE,
A.ALIAS AS MST_ALIAS,
A.ARTICLE_DESC AS MST_ARTICLE_DESC,
A.ARTICLE_NAME AS MST_ARTICLE_NAME,
A.ARTICLE_NO AS MST_ARTICLE_NO,
A.CODING_SCHEME AS MST_CODING_SCHEME,
A.MP_PERCENTAGE AS MST_MP_PERCENTAGE,
A.MRP AS MST_MRP,
A.PURCHASE_PRICE AS MST_PURCHASE_PRICE,
A.REMARKS AS MST_REMARKS,
A.WSP_PERCENTAGE AS MST_WP_PERCENTAGE,
A.WHOLESALE_PRICE AS MST_WS_PRICE,
C.UOM_NAME AS MST_UOM_NAME,
D.SUB_SECTION_NAME AS MST_SUB_SECTION_NAME,
E.SECTION_NAME AS MST_SECTION_NAME,ISNULL(F.ATTRIBUTE_NAME,'') AS ATTRIBUTE_NAME ,
ISNULL(F.KEY_NAME ,'') AS KEY_NAME,A.ARTICLE_TYPE ,A.INACTIVE,ISNULL(G.ARTICLE_NO,'') AS MST_ARTICLE_SET_NAME 
,A.FIX_WEIGHT AS MST_FIX_WEIGHT,
A.WSP_PERCENTAGE AS MST_WSP_PERCENTAGE,
A.WHOLESALE_PRICE AS MST_WHOLESALE_PRICE,
A.FIX_MRP AS MST_FIX_MRP ,
A.DISCOUNT_PERCENTAGE  AS MST_DISCOUNT_PERCENTAGE,
A.GROSS_PURCHASE_PRICE AS MST_GROSS_PURCHASE_PRICE,
A.DISCOUNT_AMOUNT AS MST_DISCOUNT_AMOUNT 
FROM ARTICLE A (NOLOCK)
JOIN UOM C (NOLOCK) ON A.UOM_CODE = C.UOM_CODE
JOIN SECTIOND D (NOLOCK) ON A.SUB_SECTION_CODE = D.SUB_SECTION_CODE
JOIN SECTIONM E (NOLOCK) ON D.SECTION_CODE = E.SECTION_CODE
LEFT OUTER JOIN 
(SELECT ARTICLE_CODE,ATTRIBUTE_NAME,KEY_NAME FROM  ART_ATTR A (NOLOCK)
 JOIN ATTRM B (NOLOCK) ON B.ATTRIBUTE_CODE = A.ATTRIBUTE_CODE 
JOIN ATTR_KEY C (NOLOCK) ON C.KEY_CODE = A.KEY_CODE)  F ON A.ARTICLE_CODE = F.ARTICLE_CODE
LEFT OUTER JOIN  ARTICLE G ON A.ARTICLE_SET_CODE = G.ARTICLE_CODE
