CREATE VIEW VW_STOCKSTATUS_REPORT_1
--WITH ENCRYPTION
AS
SELECT 'AORDER' AS [S_NO],WO.MEMO_NO AS [WO_NO],DEP.DEPARTMENT_NAME  AS DEPARTMENT, WO.REF_NO, 
ARTICLE_NO,PARA1_NAME AS COLOR,PARA2_NAME AS SIZE, CAST(QUANTITY_IN_STOCK AS NUMERIC(10,2)) AS STOCK,CAST(ISNULL(WIP,0) AS NUMERIC(10,2)) AS WIP, E.UOM_NAME 
,S.PURCHASE_PRICE AS [XN_PP] 
FROM PRD_PMT A (NOLOCK) 
JOIN PRD_SKU S ON A.PRODUCT_UID= S.PRODUCT_UID 
LEFT OUTER JOIN PRD_WO_MST WO(NOLOCK) ON WO.MEMO_ID=S.WORK_ORDER_ID 
JOIN ARTICLE B (NOLOCK) ON S.ARTICLE_CODE= B.ARTICLE_CODE  
JOIN PARA1 C (NOLOCK) ON S.PARA1_CODE = C.PARA1_CODE  
JOIN PARA2 D (NOLOCK) ON S.PARA2_CODE = D.PARA2_CODE 
JOIN UOM E ON B.UOM_CODE= E.UOM_CODE  
JOIN PRD_DEPARTMENT_MST DEP ON DEP.DEPARTMENT_ID=A.DEPARTMENT_ID
WHERE  (WIP > 0 OR QUANTITY_IN_STOCK > 0)

UNION ALL

SELECT 'BORDER' AS [S_NO], C.MEMO_NO AS [WO_NO], D.AGENCY_NAME  AS DEPARTMENT, C.REF_NO, 
ARTICLE_NO,PARA1_NAME AS COLOR,PARA2_NAME AS SIZE
,A.QUANTITY AS STOCK,CAST(ISNULL(WIP,0) AS NUMERIC(10,2)) AS WIP, E1.UOM_NAME
,E.PURCHASE_PRICE  
FROM PRD_AGENCY_ISSUE_MATERIAL_DET A
JOIN PRD_AGENCY_ISSUE_MATERIAL_MST B ON A.MEMO_ID=B.MEMO_ID	
JOIN PRD_WO_MST C ON  C.MEMO_ID=A.REF_PRD_WORKORDER_MEMOID
JOIN PRD_AGENCY_MST D ON D.AGENCY_CODE=B.REF_AGENCY_CODE 
JOIN PRD_SKU E ON E.PRODUCT_UID=A.PRODUCT_UID
JOIN PRD_PMT F ON F.PRODUCT_UID=A.PRODUCT_UID
JOIN ARTICLE B1 (NOLOCK) ON E.ARTICLE_CODE= B1.ARTICLE_CODE  
JOIN PARA1 C1 (NOLOCK) ON E.PARA1_CODE = C1.PARA1_CODE  
JOIN PARA2 D1 (NOLOCK) ON E.PARA2_CODE = D1.PARA2_CODE 
JOIN UOM E1 ON B1.UOM_CODE= E1.UOM_CODE  
LEFT OUTER JOIN PRD_AGENCY_MATERIAL_RECEIPT_DET T1 ON T1.REF_ROW_ID=A.ROW_ID	
JOIN PRD_AGENCY_MATERIAL_RECEIPT_MST T2 ON T1.MEMO_ID=T2.MEMO_ID
WHERE   B.CANCELLED=0 AND A.QUANTITY <> T1.QUANTITY  AND T2.CANCELLED=0
