CREATE VIEW VW_WL_PRD_PURCHASERETURNLIST    

AS     
SELECT  T3.AC_NAME AS CUSTOMER_NAME,      
T1.RM_DT AS MEMO_DT,   
T1.RM_NO AS MEMO_NO,  
T5.DEPARTMENT_NAME AS DEPARTMENT ,    
(CASE WHEN T1.CANCELLED = 0 THEN T1.SUBTOTAL ELSE 0 END) AS GROSS_RETURN_VALUE,      
T1.DISCOUNT_PERCENTAGE AS DISCOUNT_PERCENTAGE ,      
(CASE WHEN T1.CANCELLED = 0 THEN T1.DISCOUNT_AMOUNT ELSE 0 END) AS DISCOUNT_AMOUNT ,      
(CASE WHEN T1.CANCELLED = 0 THEN T1.FREIGHT ELSE 0 END) AS FREIGHT,      
(CASE WHEN T1.CANCELLED = 0 THEN T1.OTHER_CHARGES ELSE 0 END) AS OTHER_CHARGES,      
(CASE WHEN T1.CANCELLED = 0 THEN T1.TOTAL_AMOUNT ELSE 0 END) AS NET_RETURN_VALUE,      
T1.ROUND_OFF,      
T1.REMARKS ,      
(CASE WHEN T1.CANCELLED = 1 THEN 0 ELSE ISNULL(T2.TOTAL_QUANTITY,0) END) AS TOTAL_QUANTITY,      
(CASE WHEN T1.CANCELLED = 1 THEN 0 ELSE ISNULL(T2.ITEM_GROSS_RETURN_VALUE,0) END) AS ITEM_GROSS_RETURN_VALUE,      
T1.RM_ID AS MEMO_ID,    
T4.FORM_NAME,      
(CASE WHEN T1.CANCELLED = 1 THEN 'CANCELLED' ELSE '' END) AS CANCELLED ,     
(CASE WHEN T1.POSTEDINAC  = 1 OR ISNULL(VM.BILL_ID,'')<>'' THEN 'POSTED' ELSE 'PENDING' END) AS AC_POSTED ,  
T1.FIN_YEAR   ,
F.FORM_NAME AS TAX_TYPE,T2.TAX_PERCENTAGE ,T2.TAX_AMOUNT    
FROM PRD_RMM01106 T1      
JOIN LMV01106 T3 ON T3.AC_CODE = T1.AC_CODE      
JOIN FORM   T4 ON T4.FORM_ID = T1.FORM_ID      
JOIN PRD_DEPARTMENT_MST T5 ON T1.DEPARTMENT_ID=T5.DEPARTMENT_ID     
LEFT OUTER JOIN VM01106 VM ON VM.BILL_ID=T1.RM_ID AND VM.CANCELLED=0  
LEFT OUTER JOIN       
(
   SELECT RM_ID,ITEM_FORM_ID,ITEM_TAX_PERCENTAGE AS TAX_PERCENTAGE,
         SUM(QUANTITY) AS TOTAL_QUANTITY,SUM(QUANTITY*PURCHASE_PRICE) AS ITEM_GROSS_RETURN_VALUE,
         SUM(ITEM_TAX_AMOUNT) AS TAX_AMOUNT    
 FROM PRD_RMD01106 GROUP BY RM_ID,ITEM_FORM_ID,ITEM_TAX_PERCENTAGE
 ) T2 ON T2.RM_ID=T1.RM_ID   
LEFT OUTER JOIN FORM F ON T2.ITEM_FORM_ID = F.FORM_ID
