create VIEW VW_WSL_PRINT_MST

AS
	SELECT  USERS.USERNAME,  C.AC_NAME AS SUPP_NAME, 
           C.ADDRESS1 + ' ' + C.ADDRESS2 + ', ' + C.AREA_NAME + ' ' + C.CITY + ' ' + C.STATE AS 'SUPP_ADDRESS',
           INM01106.*, CONVERT(CHAR(10),CASE WHEN INV_DT='' THEN NULL ELSE INV_DT END ,105)  AS RM_DT1
    FROM INM01106  
   -- JOIN FORM ON INM01106.FORM_ID = FORM.FORM_ID  
    JOIN USERS ON INM01106.USER_CODE = USERS.USER_CODE 
    JOIN LMV01106 C ON INM01106.AC_CODE = C.AC_CODE
