CREATE VIEW VW_WL_WSLINV

AS 
SELECT T1.INV_ID,  
T1.INV_DT AS MST_XN_DT,  
T1.INV_NO AS MST_MEMO_NO,  
T1.SUBTOTAL AS MST_SUBTOTAL,  
T1.DISCOUNT_PERCENTAGE AS MST_DISCOUNT_PERCENTAGE ,  
T1.DISCOUNT_AMOUNT AS MST_DISCOUNT_AMOUNT ,  
T1.FREIGHT AS MST_FREIGHT ,  
T1.OTHER_CHARGES AS MST_OTHER_CHARGES ,  
T1.NET_AMOUNT AS MST_NET_AMOUNT ,  
T1.ROUND_OFF AS MST_ROUNDOFF,  
T1.REMARKS AS MST_REMARKS ,  
T1.GRLR_DATE AS MST_GRLR_DATE ,  
T1.BANDALS AS MST_BANDALS ,  
T1.THROUGH AS MST_THROUGH ,  
T1.INSURANCE AS MST_INSURANCE ,  
T2.ITEM_TAX_PERCENTAGE AS MST_TAX_PERCENTAGE ,  
T2.ITEM_TAX_AMOUNT AS MST_TAX_AMOUNT ,  
T1.OCTROI_PERCENTAGE AS MST_OCTROI_PERCENTAGE,  
T1.OCTROI_AMOUNT AS MST_OCTROI_AMOUNT,  
T1.PARTY_DA_NO AS MST_PARTY_DA_NO ,  
T1.PARTY_PO_NO AS MST_PARTY_PO_NO ,  
T1.MANUAL_INV_NO AS MST_MANUAL_INV_NO,  
T2.PRODUCT_CODE AS MST_PRODUCT_CODE,  
T2.QUANTITY AS CAL_QUANTITY,
T2.PARTY_MRP,  
T2.RATE AS CAL_RATE,  
T2.DISCOUNT_PERCENTAGE AS CAL_DISCOUNT_PERCENTAGE,  
T2.DISCOUNT_AMOUNT AS CAL_DISCOUNT_AMOUNT,  
(T2.QUANTITY*T2.RATE)-T2.DISCOUNT_AMOUNT AS CAL_AMOUNT,  
T2.QUANTITY*T6.MRP AS CAL_AMOUNT_MRP,  
T3.AC_NAME AS MST_AC_NAME,  
T3.ADDRESS0,T3.ADDRESS1,T3.ADDRESS2,T3.AREA_NAME,T3.PINCODE,  
T3.CITY,T3.STATE,T3.CST_NO,T3.CST_DT,T3.SST_NO,T3.SST_DT,T3.TIN_NO,T3.TIN_DT,  
T3.PHONES_R,T3.PHONES_O,T3.PHONES_FAX,T3.MOBILE,T3.E_MAIL,
T4.FORM_NAME AS MST_FORM_NAME,  
T5.EMP_NAME AS MST_EMP_NAME,  
T6.MRP AS CAL_MRP,  
(CASE WHEN T1.CANCELLED = 1 THEN 'CANCELLED' ELSE '' END) AS MST_CANCELLED,  
T2.BOX_NO,SECTION_NAME,SUB_SECTION_NAME,ARTICLE_NO,ARTICLE_DESC,ARTICLE_NAME,  
PARA1_NAME,PARA2_NAME,PARA3_NAME,PARA4_NAME,PARA5_NAME,PARA6_NAME,  
P2.PARA2_ORDER,UOM.UOM_NAME,UOM.UOM_TYPE,  
T1.EXCISE_ACCESSIBLE_PERCENTAGE,T1.EXCISE_ACCESSIBLE_AMOUNT,T1.EXCISE_DUTY_PERCENTAGE,T1.EXCISE_DUTY_AMOUNT,  
T1.EXCISE_EDU_CESS_PERCENTAGE,T1.EXCISE_EDU_CESS_AMOUNT,T1.EXCISE_HEDU_CESS_PERCENTAGE,T1.EXCISE_HEDU_CESS_AMOUNT,  
T1.DEPT_ID,T1.EXCISE_INVOICE 
,T1.AC_CODE  
,T1.INV_NO  
,T1.INV_DT  
,T1.SUBTOTAL  
,T1.DISCOUNT_PERCENTAGE  
,T1.DISCOUNT_AMOUNT  
,T1.FREIGHT  
,T1.PACKING  
,T1.OTHER_CHARGES  
,T1.NET_AMOUNT  
,T1.REMARKS  
,T1.ROUND_OFF  
,T1.CANCELLED  
,T1.CHECKED_BY  
,T1.SENT_BY  
,T1.COMPANY_CODE  
,T1.USER_CODE  
,T1.LAST_UPDATE  
,T1.TS  
,T1.GRLR_NO  
,T1.GRLR_DATE  
,T1.FIN_YEAR  
,T1.BANDALS  
,T1.THROUGH  
,T1.FORM_NO  
,T1.SENT_TO_HO  
,T1.UPLOADED_TO_ACTIVSTREAM  
,T1.BROKER_AC_CODE  
,T1.BROKER_COMM_PERCENTAGE  
,T1.BROKER_COMM_AMOUNT  
,T1.ROUTE_FORM1  
,T1.ROUTE_FORM2  
,T1.PARTY_DA_NO  
,T1.PARTY_PO_NO  
,T1.PAY_MODE
,T1.INSURANCE  
,T1.EMP_CODE  
,T1.DT_CODE  
,T1.POSTEDINAC  
,T1.EDT_USER_CODE  
,T1.INV_TIME  
,T1.SMS_SENT  
,T1.MANUAL_INV_NO  
,T2.ITEM_TAX_PERCENTAGE AS TAX_PERCENTAGE  
,T2.ITEM_TAX_AMOUNT  AS TAX_AMOUNT
,T2.ITEM_TAX_PERCENTAGE 
,T2.ITEM_TAX_AMOUNT  
,T1.OCTROI_PERCENTAGE  
,T1.OCTROI_AMOUNT  
,T1.INV_MODE  
,T1.EXPORTED  
,T1.PARTY_DEPT_ID  
,T1.APPROVED  
,T1.INV_TYPE
,T1.XFER_TYPE 
,T1.SHIPPING_ADDRESS
,T1.SHIPPING_ADDRESS2
,T1.SHIPPING_ADDRESS3
,T1.SHIPPING_AREA_NAME
,T1.SHIPPING_PIN
,T1.SHIPPING_CITY_NAME
,T1.SHIPPING_STATE_NAME
,T2.PRODUCT_CODE  
,T2.QUANTITY  
,T2.RATE  
,T2.ROW_ID  
,T2.PRINT_LABEL  
,T2.RFNET  
,T2.RFNET_WOTAX  
,T2.NET_RATE  
,T2.MRP  
,T2.BOX_DT  
,T3.AC_NAME  
,T3.ALIAS  
,T3.HEAD_CODE  
,T3.CLOSING_BALANCE  
,T3.CLOSING_BALANCE_CR_DR  
,T3.PRINT_LEDGER  
,T3.PRINT_NAME  
,T3.AREA_CODE  
,T3.CITY_CODE  
,T3.STATE_CODE  
,T3.CREDIT_DAYS  
,T3.BILL_BY_BILL  
,T3.ON_HOLD  
,T3.THROUGH_BROKER  
,T3.BROKER_COMM_PERCENT  
,T3.CREDIT_LIMIT  
,T3.ALLOW_CREDITOR_DEBTOR  
,T3.DPWEF_DT  
,T3.CST_PERCENTAGE  
,T3.PAN_NO  
,T3.GLN_NO  
,T3.MP_PERCENTAGE  
,T3.MRP_CALC_MODE  
,T3.TDS_CODE  
,T3.INV_RATE_TYPE  
,T3.OUTSTATION_PARTY  
,T3.SALES_AC_CODE  
,T3.USERNAME  
,T3.EDT_USERNAME  
,T4.FORM_NAME  
,T4.PURCHASE_AC_CODE  
,T4.SALE_AC_CODE  
,T4.TAX_AC_CODE  
,T4.POST_TAX_SEPARATELY  
,T4.PUR_RETURN_AC_CODE  
,T4.SALE_RETURN_AC_CODE  
,T4.PHYSICAL_FORM  
,T4.SERIES  
,T4.EXCISE_EDU_CESS_AC_CODE  
,T4.EXCISE_HEDU_CESS_AC_CODE  
,T4.EXCISE_DUTY_AC_CODE  
,T5.EMP_NAME  
,T5.EMP_ALIAS  
,T5.EMP_HEAD  
,T6.PARA1_CODE  
,T2.AUTO_SRNO 
,T6.PARA2_CODE  
,T6.PURCHASE_PRICE  
,T6.PARA3_CODE  
,T6.RECEIPT_DT  
,T6.PARA4_CODE  
,T6.PARA5_CODE  
,T6.PARA6_CODE  
,T6.DT_CREATED  
,T6.WS_PRICE  
,T6.IMAGE_NAME  
,T6.CHALLAN_NO  
,T6.FIX_MRP  
,T7.CODING_SCHEME  
,T7.UOM_CODE  
,T7.PARA1_SET  
,T7.PARA2_SET  
,T7.INACTIVE  
,T7.SKU_CODE  
,T7.SUB_SECTION_CODE  
,T7.DISCON  
,T7.WHOLESALE_PRICE  
,T7.WSP_PERCENTAGE  
,T7.MIN_PRICE  
,T7.STOCK_NA  
,T7.ARTICLE_TYPE  
,T7.CREATED_ON  
,T7.ARTICLE_GROUP_CODE  
,T7.GENERATE_BARCODES_WITHARTICLE_PREFIX  
,T7.ARTICLE_GEN_MODE  
,T7.ARTICLE_PRD_MODE  
,T7.ARTICLE_SET_CODE  
,T7.OH_PERCENTAGE  
,T7.OH_AMOUNT  
,T8.SECTION_CODE  
,T8.MFG_CATEGORY  
,USERS.MAJOR_USER_CODE  
,USERS.USER_ALIAS  
,USERS.DISCOUNT_PERCENTAGE_LEVEL  
,USERS.VIEW_DATA_AFTER_DFM  
,USERS.EMAIL  
,LCT.DEPT_NAME  
,LCT.MAJOR_DEPT_ID  
,LCT.LOC_TYPE  
,LCT.DATE_OF_OPENING  
,LCT.REPORT_BLOCKED  
,LCT.ACCOUNTS_POSTING_DEPT_ID  
,LCT.CONTROL_AC_CODE  
,LCT.UPD_PURINFO  
,LCT.SSPL_REG_KEY  
,LCT.WIZCOM_ENABLED  
,LCT.EXCISABLE  
,LCT.FR_TYPE  
,LCT.PRIMARY_EMAIL_PORT  
,LCT.PRIMARY_EMAIL  
,LCT.PRIMARY_EMAIL_SMTP  
,LCT.PRIMARY_EMAIL_PWD  
,LCT.PRIMARY_EMAIL_SSL  
,LCT.SSPL_GRP_CODE  
,LCT.PUR_LOC  
,LCT.ADDRESS1 AS LOCATION_ADDRESS1  
,LCT.ADDRESS2 AS LOCATION_ADDRESS2  
,LCT.DEPT_AC_CODE  
,LCT.LST_NO  
,LCT.LST_DT  
,LCT.DEPT_ALIAS  
,LCT.PHONE  
,LA.AREA_NAME AS LOCATION_AREA  
,LC.CITY AS LOCATION_CITY  
,LS.STATE AS LOCATION_STATE  
,LRG.REGION_NAME AS LOCATION_REGION  
,EU.USERNAME AS EDIT_USER,T6.PRODUCT_NAME
,ISNULL(PAY.CURRENCY_CONVERSION_RATE,1) AS CURRENCY_CONVERSION_RATE 
,AT1.ATTR1_KEY_NAME,AT2.ATTR2_KEY_NAME,AT3.ATTR3_KEY_NAME,AT4.ATTR4_KEY_NAME,AT5.ATTR5_KEY_NAME,AT6.ATTR6_KEY_NAME,
AT7.ATTR7_KEY_NAME,AT8.ATTR8_KEY_NAME,AT9.ATTR9_KEY_NAME,AT10.ATTR10_KEY_NAME,AT11.ATTR11_KEY_NAME,AT12.ATTR12_KEY_NAME,
AT13.ATTR13_KEY_NAME,AT14.ATTR14_KEY_NAME,AT15.ATTR15_KEY_NAME,AT16.ATTR16_KEY_NAME,AT17.ATTR17_KEY_NAME,AT18.ATTR18_KEY_NAME,
AT19.ATTR19_KEY_NAME,AT20.ATTR20_KEY_NAME,AT21.ATTR21_KEY_NAME,AT22.ATTR22_KEY_NAME,AT23.ATTR23_KEY_NAME,AT24.ATTR24_KEY_NAME,
AT25.ATTR25_KEY_NAME 
,WM.PS_ID
,WM.PS_NO
,WM.PS_DT
,CMP.PAN_NO AS COMPANY_PAN_NO
,CMP.EMAIL_ID AS COMPANY_EMAIL_ID
,CMP.PWD AS COMPANY_PWD
,CMP.STATE AS COMPANY_STATE
,CMP.COUNTRY AS COMPANY_COUNTRY
,CMP.MOBILE AS COMPANY_MOBILE
,CMP.CONTACT_NAME AS COMPANY_CONTACT_NAME
,CMP.TDS_AC_NO AS COMPANY_TDS_AC_NO
,CMP.COMPANY_CODE AS COMPANY_COMPANY_CODE
,CMP.COMPANY_NAME AS COMPANY_COMPANY_NAME
,CMP.ALIAS AS COMPANY_ALIAS
,CMP.ADDRESS1 AS COMPANY_ADDRESS1
,CMP.ADDRESS2 AS COMPANY_ADDRESS2
,CMP.CITY AS COMPANY_CITY
,CMP.TIN_NO AS COMPANY_TIN_NO
,CMP.TAN_NO AS COMPANY_TAN_NO
,CMP.PHONES_FAX AS COMPANY_PHONES_FAX
,CMP.CST_NO AS COMPANY_CST_NO
,CMP.CST_DT AS COMPANY_CST_DT
,CMP.SST_NO AS COMPANY_SST_NO
,CMP.SST_DT AS COMPANY_SST_DT
,CMP.GRP_CODE AS COMPANY_GRP_CODE
,CMP.ADDRESS9 AS COMPANY_ADDRESS9
,CMP.PRINT_ADDRESS AS COMPANY_PRINT_ADDRESS
,CMP.WORKABLE AS COMPANY_WORKABLE
,CMP.PIN AS COMPANY_PIN
,CMP.LOGO_PATH AS COMPANY_LOGO_PATH
,CMP.WEB_ADDRESS AS COMPANY_WEB_ADDRESS
,CMP.SSPL_FIRST_HDSR AS COMPANY_SSPL_FIRST_HDSR
,CMP.POLICY_NO AS COMPANY_POLICY_NO
,CMP.GRP_NAME AS COMPANY_GRP_NAME
,CMP.CIN AS COMPANY_CIN
,PD1.BILTY_NO AS PARCEL_BILTY_NO
,PD1.HANDLED_BY
,PD1.GATE_ENTRY_NO
,PD1.TOTALQUANTITY
,0 AS TOTAL_BOXES
,PD1.RECEIPT_DT AS BILTY_DT
,LMT.TERMS_NAME
,T2.ITEM_EXCISE_ACCESSIBLE_PERCENTAGE
,T2.ITEM_EXCISE_ACCESSIBLE_AMOUNT
,T2.ITEM_EXCISE_DUTY_PERCENTAGE
,T2.ITEM_EXCISE_DUTY_AMOUNT
,T2.ITEM_EXCISE_EDU_CESS_PERCENTAGE
,T2.ITEM_EXCISE_EDU_CESS_AMOUNT
,T2.ITEM_EXCISE_HEDU_CESS_PERCENTAGE
,T2.ITEM_EXCISE_HEDU_CESS_AMOUNT
,T2.ITEM_EXCISE_MRP
,T6.VENDOR_EAN_NO
,LCT1.ADDRESS1 AS TARGET_LOCATION_ADDRESS1  
,LCT1.ADDRESS2 AS TARGET_LOCATION_ADDRESS2
,LCT1.TIN_NO AS TARGET_LOCATION_TIN_NO
,LCT1.TAN_NO AS TARGET_LOCATION_TAN_NO
,LCT1.PHONE AS TARGET_LOCATION_PHONE
,LA1.AREA_NAME AS TARGET_LOCATION_AREA  
,LA1.PINCODE AS TARGET_LOCATION_PINCODE
,LC1.CITY AS TARGET_LOCATION_CITY  
,LS1.STATE AS TARGET_LOCATION_STATE  
,BRD.AC_NAME AS BROKER_NAME  
,PD1.PAY_TYPE AS PAY_TYPE
,LRG1.REGION_NAME AS TARGET_LOCATION_REGION  
,'' AS PAYMODES
,'' AS PAYAMOUNT
,'20'+RIGHT((T1.FIN_YEAR -1),2)+'- 20'+ RIGHT(T1.FIN_YEAR,2)AS FIN_PRINT
,USERS.USERNAME AS BILLUSER
,T6.ONLINE_PRODUCT_CODE,
PS_NO_DETAILS=COALESCE(STUFF((SELECT DISTINCT  ','+ RTRIM(LTRIM(WPS.PS_NO)) FROM  IND01106 IND JOIN  WPS_MST  WPS ON IND.PS_ID=WPS.PS_ID   
WHERE IND.INV_ID  =T1.INV_ID FOR XML PATH('')),1,1,''),'') 

FROM INM01106 T1  
JOIN IND01106 T2 ON T1.INV_ID = T2.INV_ID  
LEFT JOIN WPS_MST WM ON T2.PS_ID=WM.PS_ID
JOIN LMV01106 T3 ON T3.AC_CODE = T1.AC_CODE 
LEFT OUTER JOIN LMV01106 BRD ON T1.BROKER_AC_CODE = BRD.AC_CODE  
JOIN FORM   T4 ON T4.FORM_ID = T2.ITEM_FORM_ID   
LEFT OUTER JOIN 
(SELECT * FROM (SELECT ROW_NUMBER() OVER (PARTITION BY MEMO_ID ORDER BY CURRENCY_CONVERSION_RATE) AS SNO,MEMO_ID,CURRENCY_CONVERSION_RATE FROM PAYMODE_XN_DET  WHERE XN_TYPE='WSL' ) A WHERE A.SNO =1) 
PAY ON T1.INV_ID = PAY.MEMO_ID  
LEFT OUTER JOIN EMPLOYEE T5 ON T5.EMP_CODE = T1.EMP_CODE  
JOIN SKU T6 ON T6.PRODUCT_CODE = T2.PRODUCT_CODE  
JOIN ARTICLE T7 ON T7.ARTICLE_CODE=T6.ARTICLE_CODE  
JOIN SECTIOND T8 ON T8.SUB_SECTION_CODE=T7.SUB_SECTION_CODE  
JOIN SECTIONM T9 ON T9.SECTION_CODE=T8.SECTION_CODE  
JOIN PARA1 P1 ON P1.PARA1_CODE=T6.PARA1_CODE  
JOIN PARA2 P2 ON P2.PARA2_CODE=T6.PARA2_CODE  
JOIN PARA3 P3 ON P3.PARA3_CODE=T6.PARA3_CODE  
JOIN PARA4 P4 ON P4.PARA4_CODE=T6.PARA4_CODE  
JOIN PARA5 P5 ON P5.PARA5_CODE=T6.PARA5_CODE  
JOIN PARA6 P6 ON P6.PARA6_CODE=T6.PARA6_CODE  
JOIN UOM ON UOM.UOM_CODE = T7.UOM_CODE  
LEFT OUTER JOIN ARTICLE_FIX_ATTR ATTR  (NOLOCK) ON T6.ARTICLE_CODE = ATTR.ARTICLE_CODE 
LEFT OUTER JOIN ATTR1_MST AT1 (NOLOCK) ON AT1.ATTR1_KEY_CODE=ATTR.ATTR1_KEY_CODE
LEFT OUTER JOIN ATTR2_MST AT2 (NOLOCK) ON AT2.ATTR2_KEY_CODE=ATTR.ATTR2_KEY_CODE
LEFT OUTER JOIN ATTR3_MST AT3 (NOLOCK) ON AT3.ATTR3_KEY_CODE=ATTR.ATTR3_KEY_CODE
LEFT OUTER JOIN ATTR4_MST AT4 (NOLOCK) ON AT4.ATTR4_KEY_CODE=ATTR.ATTR4_KEY_CODE
LEFT OUTER JOIN ATTR5_MST AT5 (NOLOCK) ON AT5.ATTR5_KEY_CODE=ATTR.ATTR5_KEY_CODE
LEFT OUTER JOIN ATTR6_MST AT6 (NOLOCK) ON AT6.ATTR6_KEY_CODE=ATTR.ATTR6_KEY_CODE
LEFT OUTER JOIN ATTR7_MST AT7 (NOLOCK) ON AT7.ATTR7_KEY_CODE=ATTR.ATTR7_KEY_CODE
LEFT OUTER JOIN ATTR8_MST AT8 (NOLOCK) ON AT8.ATTR8_KEY_CODE=ATTR.ATTR8_KEY_CODE
LEFT OUTER JOIN ATTR9_MST AT9 (NOLOCK) ON AT9.ATTR9_KEY_CODE=ATTR.ATTR9_KEY_CODE
LEFT OUTER JOIN ATTR10_MST AT10 (NOLOCK) ON AT10.ATTR10_KEY_CODE=ATTR.ATTR10_KEY_CODE
LEFT OUTER JOIN ATTR11_MST AT11 (NOLOCK) ON AT11.ATTR11_KEY_CODE=ATTR.ATTR11_KEY_CODE
LEFT OUTER JOIN ATTR12_MST AT12 (NOLOCK) ON AT12.ATTR12_KEY_CODE=ATTR.ATTR12_KEY_CODE
LEFT OUTER JOIN ATTR13_MST AT13 (NOLOCK) ON AT13.ATTR13_KEY_CODE=ATTR.ATTR13_KEY_CODE
LEFT OUTER JOIN ATTR14_MST AT14 (NOLOCK) ON AT14.ATTR14_KEY_CODE=ATTR.ATTR14_KEY_CODE
LEFT OUTER JOIN ATTR15_MST AT15 (NOLOCK) ON AT15.ATTR15_KEY_CODE=ATTR.ATTR15_KEY_CODE
LEFT OUTER JOIN ATTR16_MST AT16 (NOLOCK) ON AT16.ATTR16_KEY_CODE=ATTR.ATTR16_KEY_CODE
LEFT OUTER JOIN ATTR17_MST AT17 (NOLOCK) ON AT17.ATTR17_KEY_CODE=ATTR.ATTR17_KEY_CODE
LEFT OUTER JOIN ATTR18_MST AT18 (NOLOCK) ON AT18.ATTR18_KEY_CODE=ATTR.ATTR18_KEY_CODE
LEFT OUTER JOIN ATTR19_MST AT19 (NOLOCK) ON AT19.ATTR19_KEY_CODE=ATTR.ATTR19_KEY_CODE
LEFT OUTER JOIN ATTR20_MST AT20 (NOLOCK) ON AT20.ATTR20_KEY_CODE=ATTR.ATTR20_KEY_CODE
LEFT OUTER JOIN ATTR21_MST AT21 (NOLOCK) ON AT21.ATTR21_KEY_CODE=ATTR.ATTR21_KEY_CODE
LEFT OUTER JOIN ATTR22_MST AT22 (NOLOCK) ON AT22.ATTR22_KEY_CODE=ATTR.ATTR22_KEY_CODE
LEFT OUTER JOIN ATTR23_MST AT23 (NOLOCK) ON AT23.ATTR23_KEY_CODE=ATTR.ATTR23_KEY_CODE
LEFT OUTER JOIN ATTR24_MST AT24 (NOLOCK) ON AT24.ATTR24_KEY_CODE=ATTR.ATTR24_KEY_CODE
LEFT OUTER JOIN ATTR25_MST AT25(NOLOCK) ON AT25.ATTR25_KEY_CODE=ATTR.ATTR25_KEY_CODE----***************************************************  
JOIN USERS ON T1.USER_CODE=USERS.USER_CODE  
JOIN LOCATION LCT ON T1.DEPT_ID=LCT.DEPT_ID  
JOIN AREA LA ON LCT.AREA_CODE=LA.AREA_CODE  
JOIN CITY LC ON LA.CITY_CODE=LC.CITY_CODE  
JOIN STATE LS ON LC.STATE_CODE=LS.STATE_CODE  
JOIN REGIONM LRG ON LS.REGION_CODE=LRG.REGION_CODE 
LEFT JOIN LOCATION LCT1 ON T1.PARTY_DEPT_ID=LCT1.DEPT_ID 
LEFT JOIN AREA LA1 ON LCT1.AREA_CODE=LA1.AREA_CODE  
LEFT JOIN CITY LC1 ON LA1.CITY_CODE=LC1.CITY_CODE  
LEFT JOIN STATE LS1 ON LC1.STATE_CODE=LS1.STATE_CODE  
LEFT JOIN REGIONM LRG1 ON LS1.REGION_CODE=LRG1.REGION_CODE    
JOIN USERS EU ON T1.EDT_USER_CODE=EU.USER_CODE   
JOIN COMPANY CMP ON CMP.COMPANY_CODE='01'
LEFT JOIN LM_TERMS LM ON LM.TERMS_CODE=T1.TERMS_CODE
LEFT JOIN LEDGER_TERMS LMT ON LMT.USER_CODE=LM.TERMS_CODE
LEFT OUTER JOIN parcel_det  PB ON PB.REF_MEMO_ID=T1.INV_ID
LEFT OUTER JOIN
(
   SELECT PM1.PAY_TYPE, PM1.BILTY_NO,PM1.HANDLED_BY,PM1.GATE_ENTRY_NO, PM1.RECEIPT_DT,
   A.ref_memo_id , A.PARCEL_MEMO_ID,SUM(QUANTITY) AS TOTALQUANTITY FROM PARCEL_DET A (NOLOCK) 
   JOIN parcel_mst PM1 (NOLOCK) ON A.parcel_memo_id =PM1.parcel_memo_id 
   WHERE PM1.xn_type ='WSL'
   GROUP BY PM1.PAY_TYPE,PM1.BILTY_NO,PM1.HANDLED_BY,PM1.GATE_ENTRY_NO, PM1.RECEIPT_DT,A.ref_memo_id ,A.PARCEL_MEMO_ID
)PD1 ON PD1.ref_memo_id=T1.INV_ID 
