CREATE VIEW CMV01106
--WITH ENCRYPTION
AS
SELECT 
NET + (NET * ( SELECT ( CASE WHEN CMM.SUBTOTAL<>0 
						THEN ((CMM.DISCOUNT_AMOUNT)*100/CMM.SUBTOTAL) 
						ELSE 0 END ) AS ADD_PER 
			   FROM CMM01106 
			   WHERE CM_ID = CMD.CM_ID))/100 AS NET2,
CMD.*, CMM.CM_NO
FROM CMD01106 CMD JOIN CMM01106 CMM ON CMD.CM_ID=CMM.CM_ID
