CREATE VIEW   VW_PRD_TTM_PRINT
AS

	   SELECT  COM.COMPANY_NAME,COM.ADDRESS1 AS COM_ADDRESS1,COM.ADDRESS2 AS COM_ADDRESS2,COM.CITY COM_CITY,COM.PHONES_FAX,COM.LOGO_PATH,
			   LM.AC_NAME,LM.ADDRESS0,LM.ADDRESS1,LM.ADDRESS2,CITY.CITY AS AG_CITY,
			   B.MEMO_ID AS ORDER_ID,B.MEMO_NO AS ORDER_NO,    
			   AR.ARTICLE_NO AS FG_ARTICLE_NO,    
			   B.MEMO_ID AS [REF_PRD_WORKORDER_MEMOID], 
			   A.MEMO_ID , TM.MEMO_DT,TM.MEMO_NO,     
			   A.ARTICLE_CODE AS ARTICLE_CODE,    
			   AR.ARTICLE_NAME AS FG_ARTICLE_NAME,    
			   P1.PARA1_CODE,P1.PARA1_NAME AS COLOR,    
			   P2.PARA2_CODE,P2.PARA2_NAME AS SIZE,    
			   A.WO_QTY,A.QTY AS QTY ,A.ROW_ID  AS ROW_ID,      
			   P3.PARA3_NAME  AS PARA3_NAME    
			  ,P4.PARA4_NAME AS PARA4_NAME    
			  ,P5.PARA5_NAME AS PARA5_NAME    
			  ,P6.PARA6_NAME AS PARA6_NAME    
			  ,SD.SUB_SECTION_NAME    
			  ,SM.SECTION_NAME,    
			   A.PRODUCT_CODE    
			  ,A.COST_PRICE    
			  ,A.INCREASE_PER ,A.PURCHASE_PRICE    
			,A.MRP    
			,A.WS_PRICE    
			,A.AMOUNT    
			,A.TOTAL_COST_PRICE    
			,A.PRINT_LABEL        
			,OP1.PARA1_NAME AS OLD_PARA1_NAME    
			,OP2.PARA2_NAME AS OLD_PARA2_NAME    
			,OP3.PARA3_NAME  AS OLD_PARA3_NAME    
			,OP4.PARA4_NAME AS OLD_PARA4_NAME    
			,OP5.PARA5_NAME AS OLD_PARA5_NAME    
			,OP6.PARA6_NAME AS OLD_PARA6_NAME      
			 ,A.OLD_PARA1_CODE    
			,A.OLD_PARA2_CODE    
			,A.OLD_PARA3_CODE    
			,A.OLD_PARA4_CODE    
			,A.OLD_PARA5_CODE    
			,A.OLD_PARA6_CODE 
			,A.WIP_PRODUCT_CODE    
		FROM PRD_TRANSFER_MAIN_DET (NOLOCK) A   
		JOIN PRD_TRANSFER_MAIN_MST TM ON A.MEMO_ID=TM.MEMO_ID  
		JOIN PRD_WO_MST (NOLOCK) B ON A.REF_PRD_WORKORDER_MEMOID=B.MEMO_ID    
		JOIN ARTICLE (NOLOCK) AR ON A.ARTICLE_CODE=AR.ARTICLE_CODE    
		JOIN SECTIOND SD ON SD.SUB_SECTION_CODE=AR.SUB_SECTION_CODE    
		JOIN SECTIONM SM ON SD.SECTION_CODE=SM.SECTION_CODE    
		JOIN PARA1 P1 ON P1.PARA1_CODE=A.PARA1_CODE    
		JOIN PARA2 P2 ON P2.PARA2_CODE=A.PARA2_CODE    
		JOIN PARA3 P3 ON P3.PARA3_CODE=A.PARA3_CODE    
		JOIN PARA4 P4 ON P4.PARA4_CODE=A.PARA4_CODE    
		JOIN PARA5 P5 ON P5.PARA5_CODE=A.PARA5_CODE    
		JOIN PARA6 P6 ON P6.PARA6_CODE=A.PARA6_CODE     
		LEFT OUTER JOIN PARA1 OP1 ON OP1.PARA1_CODE=A.OLD_PARA1_CODE    
		LEFT OUTER JOIN PARA2 OP2 ON OP2.PARA2_CODE=A.OLD_PARA2_CODE    
		LEFT OUTER JOIN PARA3 OP3 ON OP3.PARA3_CODE=A.OLD_PARA3_CODE    
		LEFT OUTER JOIN PARA4 OP4 ON OP4.PARA4_CODE=A.OLD_PARA4_CODE    
		LEFT OUTER JOIN PARA5 OP5 ON OP5.PARA5_CODE=A.OLD_PARA5_CODE    
		LEFT OUTER JOIN PARA6 OP6 ON OP6.PARA6_CODE=A.OLD_PARA6_CODE  
		LEFT OUTER JOIN PRD_UPCPMT PMT ON PMT.PRODUCT_CODE=A.WIP_PRODUCT_CODE 
		LEFT OUTER JOIN BUYER_ORDER_MST MST ON MST.ORDER_ID=PMT.ORDER_ID
		LEFT OUTER JOIN LMV01106 LM ON LM.AC_CODE=ISNULL(MST.AC_CODE  ,B.AC_CODE)
		LEFT JOIN CITY  ON CITY.CITY_CODE=LM.CITY_CODE
		LEFT JOIN COMPANY COM ON COM.COMPANY_CODE='01'
