CREATE VIEW VW_PCIN_LIST

AS
 SELECT T1.MEMO_ID,T1.MEMO_NO,T2.DEPT_NAME AS SOURCE_LOCATION,T3.DEPT_NAME AS TARGET_LOCATION ,T1.MEMO_DT,T1.AMOUNT,  
  T1.REMARKS,T1.FIN_YEAR,T4.USERNAME,T1.USER_CODE  ,T1.source_location_code,T1.location_Code
  FROM PCI_MST T1  
  JOIN LOCATION T2 ON T1.location_code/*LEFT(T1.MEMO_NO,2)*//*Rohit 04-11-2024*/=T2.DEPT_ID  
  JOIN LOCATION T3 ON T1.source_location_code/*RIGHT(LEFT(T1.MEMO_NO,4),2)*//*Rohit 04-11-2024*/=T3.DEPT_ID  
  JOIN USERS T4 ON T4.USER_CODE=T1.USER_CODE  
  WHERE RECEIPT_DT <> '' AND CANCELLED=0


