CREATE VIEW VW_SIZE_NA_LIST
AS
 SELECT CAST(1 AS BIT) AS CHK, A.MEMO_ID,A.MEMO_NO,A.MEMO_DT,  
               A.AGENCY_CODE ,AM.AGENCY_NAME  ,  
               ART.ARTICLE_CODE,ART.ARTICLE_NO,ART.ARTICLE_NAME,  
               P2.para2_set AS  SIZEGROUP_NAME ,  
               P1.PARA1_CODE,P1.PARA1_NAME AS COLOR,  
               P3.PARA3_CODE,P3.PARA3_NAME BUYER_STYLE_NO,  
               SKU.PARA2_CODE,P2.PARA2_NAME SIZE,  
               B.PRODUCT_CODE,  
               B.QUANTITY  
   FROM PPC_FG_BARCODE_NA_MST A (NOLOCK) 
   JOIN PPC_FG_BARCODE_NA_DET B (NOLOCK)   ON A.MEMO_ID =B.MEMO_ID   
   JOIN SKU (NOLOCK) ON SKU.PRODUCT_CODE=B.PRODUCT_CODE   
   JOIN ARTICLE ART (NOLOCK) ON SKU.ARTICLE_CODE =ART.ARTICLE_CODE 
   JOIN PRD_AGENCY_MST  AM (NOLOCK) ON AM.AGENCY_CODE =A.AGENCY_CODE 
   JOIN PARA1 P1 (NOLOCK) ON SKU.PARA1_CODE =P1.PARA1_CODE 
   JOIN PARA2 P2 (NOLOCK) ON SKU.PARA2_CODE =P2.PARA2_CODE 
   JOIN PARA3 P3 (NOLOCK) ON SKU.PARA3_CODE =P3.PARA3_CODE 
