CREATE VIEW VW_BILL_PAYMODE  
--WITH ENCRYPTION
AS  
SELECT A.XN_TYPE, A.MEMO_ID,  
  SUM(CASE WHEN B.PAYMODE_GRP_CODE = '0000001' THEN AMOUNT ELSE 0 END) AS CASH_AMOUNT,  
    
  SUM(CASE WHEN B.PAYMODE_GRP_CODE = '0000002' THEN AMOUNT ELSE 0 END) AS CC_AMOUNT,  
  
  SUM(CASE WHEN B.PAYMODE_GRP_CODE = '0000003' AND  A.PAYMODE_CODE = '0000001'  
     THEN AMOUNT ELSE 0 END) AS CN_AMOUNT,  
  
  SUM(CASE WHEN B.PAYMODE_GRP_CODE = '0000003' AND A.PAYMODE_CODE = '0000002'  
     THEN AMOUNT ELSE 0 END) AS ADVANCE_AMOUNT_ADJUSTED,  
  
  SUM(CASE WHEN B.PAYMODE_GRP_CODE = '0000003' AND A.PAYMODE_CODE NOT IN ( '0000001', '0000002' )  
     THEN AMOUNT ELSE 0 END) AS OTHER_DOC_AMOUNT,  
  
  
  SUM(CASE WHEN A.PAYMODE_CODE='0000004' THEN AMOUNT ELSE 0 END) AS CREDIT_AMOUNT,
  SUM(CASE WHEN A.PAYMODE_CODE='CMR0001' THEN AMOUNT ELSE 0 END) AS CREDIT_REFUND_AMOUNT,  
  
  SUM(CASE WHEN B.PAYMODE_GRP_CODE NOT IN ( '0000001','0000002','0000003','0000004','PYTGW01') AND A.PAYMODE_CODE = '0000003'  
     THEN AMOUNT ELSE 0 END) AS BANK_CHARGES,  

  SUM(CASE WHEN B.PAYMODE_GRP_CODE  IN ( 'WCGV001') OR A.PAYMODE_CODE='GVC0001' THEN AMOUNT ELSE 0 END) AS GIFT_VOUCHERS,    
  
  SUM(CASE WHEN B.PAYMODE_GRP_CODE  IN ( 'PYTGW01')  THEN AMOUNT ELSE 0 END) AS WALLET,    
  
  SUM(CASE WHEN B.PAYMODE_GRP_CODE NOT IN ( '0000001','0000002','0000003','0000004','WCGV001','PYTGW01')  
	AND A.PAYMODE_CODE NOT IN ('0000003' ,'GVC0001') THEN AMOUNT ELSE 0 END) AS MISC_AMOUNT  
     
FROM PAYMODE_XN_DET A (NOLOCK)  
JOIN PAYMODE_MST B (NOLOCK) ON A.PAYMODE_CODE = B.PAYMODE_CODE  
JOIN PAYMODE_GRP_MST C (NOLOCK) ON B.PAYMODE_GRP_CODE = C.PAYMODE_GRP_CODE  
GROUP BY A.XN_TYPE, A.MEMO_ID  
--******************************** END OF VIEW VW_BILL_PAYMODE
