CREATE VIEW VW_PRD_PACKSLIP_LIST    

AS    
SELECT T1.PS_ID,T1.PS_NO,T1.PS_DT,DT1.TOTAL_QTY,  ISNULL(T4.AC_NAME,'') AS AC_NAME,
T4.ADDRESS0+' '+T4.ADDRESS1+' '+T4.ADDRESS2 +' '+ T4.AREA_NAME AS [ADDRESS],T4.CITY,T4.[STATE],T4.PINCODE,  
ISNULL(T6.DEPARTMENT_NAME,'') AS DEPARTMENT_NAME ,
(CASE WHEN T1.CANCELLED =1 THEN 'CANCELLED' ELSE '' END) AS  CANCELLED,  
T1.REMARKS,T1.SUBTOTAL,  T1.NET_AMOUNT ,  
(CASE WHEN T3.PS_ID IS NOT NULL  THEN 'SETTLED' ELSE 'PENDING' END) AS [STATUS] ,
T1.PS_ID AS MEMO_ID,T1.FIN_YEAR ,WOM.MEMO_NO AS WO_NO,WOM.REF_NO , EM.EMP_TITLE +' '+EM.EMP_FNAME+' '+EM.EMP_LNAME AS CO_ORDINATOR
,CASE WHEN ISNULL(PO.PO_ID,'')='' THEN '' ELSE 'PO RAISED' END AS PO_STATUS            
,POM.PO_NO AS PO_NUMBER,T3.INV_NO AS INV_NUMBER

FROM PRD_PS_MST T1   
JOIN 
(
SELECT PS_ID , SUM(QUANTITY) AS TOTAL_QTY
FROM PRD_PS_DET
GROUP BY PS_ID
)DT1 ON DT1.PS_ID=T1.PS_ID

LEFT OUTER JOIN  PRD_WO_MST WOM ON WOM.MEMO_ID=T1.REF_WO_ID 
LEFT OUTER JOIN EMP_MST EM ON EM.EMP_ID=WOM.EMP_CODE
LEFT OUTER JOIN   
(
SELECT A.PS_ID,B.INV_NO FROM PRD_IND01106 A 
JOIN PRD_INM01106 B ON A.INV_ID=B.INV_ID  
JOIN PRD_PS_MST C ON C.PS_ID=A.PS_ID  
WHERE B.CANCELLED=0 GROUP BY A.PS_ID,B.INV_NO
) T3 ON T3.PS_ID=T1.PS_ID  
LEFT OUTER JOIN PRD_PO_WSL PO ON PO.INV_ID=T1.PS_ID
JOIN LMV01106 T4 ON T4.AC_CODE = T1.AC_CODE      
LEFT OUTER JOIN PRD_DEPARTMENT_MST T6 ON T6.DEPARTMENT_ID = T1.DEPARTMENT_ID      
LEFT OUTER JOIN PRD_POM01106 POM ON POM.PO_ID=PO.PO_ID
