CREATE VIEW VW_TRACK_REPORT_1    
--WITH ENCRYPTION
AS    
    
SELECT  XN_TYPE,AI.QUANTITY,  
  OM.AC_CODE,OM.REF_NO,OM.ORDER_NO,ISNULL(CONVERT(VARCHAR,OM.ORDER_DT ,105),'') AS ORDER_DT,    
        ISNULL(CONVERT(VARCHAR,OM.TRAIL_DT ,105),'') AS TRIAL_DT ,    
        ISNULL(CONVERT(VARCHAR,OM.DELIVERY_DT ,105),'') AS DELIVERY_DT,      
        LM.AC_NAME,ODA.ARTICLE_NO AS SET_NO,WOM.MEMO_ID AS WORK_ORDER_ID,WODA.ARTICLE_NO AS COMP_NO,      
        ISNULL(AI.K_NAME,ISNULL(AG.AGENCY_NAME,'')) AS K_NAME,ISNULL(AI.CHALLAN_NO,'') AS CHALLAN_NO,    
        ISNULL(AI.DEPARTMENT ,ISNULL(E1.JOB_NAME,'')) AS DEPARTMENT,      
        ISNULL(CONVERT(VARCHAR,AI.ISSUE_DT ,105),' ') AS ISSUE_DT,    
        --ISNULL(CONVERT(VARCHAR,AI.RECEIVE_DT,105),' ') AS RECEIVE_DT,      
        CASE WHEN ISNULL(CONVERT(VARCHAR,PRD_JOBS.TARGET_DT,105),'')='' THEN ''     
             WHEN  ISNULL(CONVERT(VARCHAR,PRD_JOBS.TARGET_DT,105),'')='01-01-1900' THEN '' ELSE CONVERT(VARCHAR,PRD_JOBS.TARGET_DT,105) END  AS TARGET_DT,      
        ISNULL(EMP.EMP_FNAME,'')+' '+ISNULL(EMP.EMP_LNAME,'') AS ALLOCATED_TO,      
        ISNULL(CONVERT(VARCHAR,DTM.MEMO_DT,105),'') AS COMPLETION_DT  ,      
        CASE WHEN ISNULL(CONVERT(VARCHAR,DTM.MEMO_DT,105),'')<>''THEN       
             CASE WHEN DATEDIFF(DAY,OM.DELIVERY_DT,DTM.MEMO_DT) <0  THEN 0 ELSE DATEDIFF(DAY,OM.DELIVERY_DT,DTM.MEMO_DT) END       
             ELSE        
             CASE WHEN DATEDIFF(DAY,OM.DELIVERY_DT,GETDATE())<0 THEN 0 ELSE DATEDIFF(DAY,OM.DELIVERY_DT,GETDATE()) END       
             END AS NET_DELAY ,      
        CASE WHEN ISNULL(CONVERT(VARCHAR,DTM.MEMO_DT,105),'')<>''THEN       
        CASE WHEN DATEDIFF(DAY,DTM.MEMO_DT,OM.DELIVERY_DT) <0  THEN 0 ELSE DATEDIFF(DAY,DTM.MEMO_DT,OM.DELIVERY_DT) END       
             ELSE        
             CASE WHEN DATEDIFF(DAY,GETDATE(),OM.DELIVERY_DT)<0 THEN 0 ELSE DATEDIFF(DAY,GETDATE(),OM.DELIVERY_DT) END       
             END  AS DAYS_TO_GO,ISNULL(PRD_JOBS.JOB_ORDER,0) AS JOB_ORDER ,AI.ISSUE_NO --,AI.RECEIPT_NO  
    ,AI.RATE,AI.BOM_RM AS BOM_RM,AI.NEW_RATE  
      
FROM BUYER_ORDER_MST  OM  (NOLOCK)    
JOIN BUYER_ORDER_DET OD (NOLOCK) ON OD.ORDER_ID=OM.ORDER_ID      
JOIN ARTICLE ODA (NOLOCK) ON ODA.ARTICLE_CODE=OD.ARTICLE_CODE      
JOIN PRD_WO_MST WOM (NOLOCK) ON WOM.ARTICLE_SET_CODE=OD.ARTICLE_CODE AND WOM.REF_NO=OM.REF_NO      
JOIN LMV01106 LM (NOLOCK) ON LM.AC_CODE=OM.AC_CODE      
JOIN PRD_WO_DET WOD (NOLOCK) ON WOD.MEMO_ID=WOM.MEMO_ID     
--JOIN PRD_WO_SUB_DET WOSD (NOLOCK) WOSD.REF_ROW_ID=WOD.ROW_ID  
--JOIN  PRD_SKU SKU (NOLOCK) ON SKU.WORK_ORDER_ID=WOM.MEMO_ID  
--JOIN ARTICLE SKART (NOLOCK) ON SKU.ARTICLE_CODE=SKART.ARTICLE_CODE   
JOIN ARTICLE WODA (NOLOCK) ON WODA.ARTICLE_CODE=WOD.ARTICLE_CODE      
LEFT OUTER JOIN EMP_MST EMP (NOLOCK) ON EMP.EMP_ID=WOM.EMP_CODE      
LEFT OUTER JOIN       
(  
 --PURCHASE    
 SELECT  'PUR' AS XN_TYPE,SK.WORK_ORDER_ID AS REF_PRD_WORKORDER_MEMOID,LM.AC_NAME AS K_NAME,'' AS CHALLAN_NO,    
         SK.COMPONENT_CODE AS REF_COMPONENT_ARTICLE_CODE ,ART.ARTICLE_NO,'PURCHASE' AS DEPARTMENT,      
         A.ARTICLE_CODE, B.RECEIPT_DT AS ISSUE_DT,'00000' AS JOB_CODE,B.MRR_NO AS ISSUE_NO ,  
         A.PURCHASE_PRICE AS RATE  ,AR.ARTICLE_NO AS BOM_RM,A.QUANTITY, SK.PURCHASE_PRICE AS NEW_RATE  
 FROM PRD_PID01106 A (NOLOCK)        
 JOIN PRD_PIM01106 B (NOLOCK) ON A.MRR_ID = B.MRR_ID        
 JOIN PRD_DEPARTMENT_MST D ON D.DEPARTMENT_ID=B.DEPARTMENT_ID      
 JOIN PRD_SKU SK ON SK.PRODUCT_UID=A.PRODUCT_UID    
 JOIN ARTICLE AR ON AR.ARTICLE_CODE=SK.ARTICLE_CODE   
 JOIN ARTICLE ART ON SK.COMPONENT_CODE=ART.ARTICLE_CODE  
 JOIN LM01106 LM ON B.AC_CODE=LM.AC_CODE   
 JOIN UOM ON AR.UOM_CODE=UOM.UOM_CODE  
 WHERE  B.CANCELLED = 0 AND A.PRODUCT_UID<>'' AND AR.STOCK_NA=0  
   
 UNION ALL  
 --PURCHASE RETURN  
 SELECT  'PRT' AS XN_TYPE,SK.WORK_ORDER_ID AS REF_PRD_WORKORDER_MEMOID,LM.AC_NAME AS K_NAME,'' AS CHALLAN_NO,    
         SK.COMPONENT_CODE AS REF_COMPONENT_ARTICLE_CODE ,ART.ARTICLE_NO,'PURCHASE' AS DEPARTMENT,      
         SK.ARTICLE_CODE, B.RM_DT AS ISSUE_DT,'00000' AS JOB_CODE,B.RM_NO AS ISSUE_NO ,  
         A.PURCHASE_PRICE AS RATE  ,AR.ARTICLE_NO AS BOM_RM,A.QUANTITY, SK.PURCHASE_PRICE AS NEW_RATE  
 FROM PRD_RMD01106 A (NOLOCK)        
 JOIN PRD_RMM01106 B (NOLOCK) ON A.RM_ID = B.RM_ID        
 JOIN PRD_DEPARTMENT_MST D ON D.DEPARTMENT_ID=B.DEPARTMENT_ID      
 JOIN PRD_SKU SK ON SK.PRODUCT_UID=A.PRODUCT_UID      
 JOIN ARTICLE AR ON AR.ARTICLE_CODE=SK.ARTICLE_CODE      
 JOIN ARTICLE ART ON SK.COMPONENT_CODE=ART.ARTICLE_CODE  
 JOIN LM01106 LM ON B.AC_CODE=LM.AC_CODE   
 JOIN UOM ON AR.UOM_CODE=UOM.UOM_CODE  
 WHERE B.CANCELLED = 0  AND A.PRODUCT_UID<>'' AND AR.STOCK_NA=0     
   
 UNION ALL  
 --PACKSLIP  
 SELECT  'WSL' AS XN_TYPE,SK.WORK_ORDER_ID AS REF_PRD_WORKORDER_MEMOID,LM.AC_NAME AS K_NAME,'' AS CHALLAN_NO,    
         SK.COMPONENT_CODE AS REF_COMPONENT_ARTICLE_CODE ,ART.ARTICLE_NO,'SALE' AS DEPARTMENT,      
         SK.ARTICLE_CODE, B.PS_DT AS ISSUE_DT,'00000' AS JOB_CODE,B.PS_NO AS ISSUE_NO ,  
         A.RATE AS RATE  ,AR.ARTICLE_NO AS BOM_RM,A.QUANTITY , SK.PURCHASE_PRICE AS NEW_RATE  
 FROM PRD_PS_DET A (NOLOCK)        
 JOIN PRD_PS_MST B (NOLOCK) ON A.PS_ID= B.PS_ID  
 JOIN PRD_DEPARTMENT_MST D ON D.DEPARTMENT_ID=B.DEPARTMENT_ID      
 JOIN PRD_SKU SK ON SK.PRODUCT_UID=A.PRODUCT_UID      
 JOIN ARTICLE AR ON AR.ARTICLE_CODE=SK.ARTICLE_CODE      
 JOIN ARTICLE ART ON SK.COMPONENT_CODE=ART.ARTICLE_CODE  
 JOIN LM01106 LM ON B.AC_CODE=LM.AC_CODE   
 JOIN UOM ON AR.UOM_CODE=UOM.UOM_CODE  
 WHERE B.CANCELLED = 0  AND A.PRODUCT_UID<>'' AND AR.STOCK_NA=0     
   
 UNION ALL  
 --WHOLESALE  
 SELECT  'WSL' AS XN_TYPE,SK.WORK_ORDER_ID AS REF_PRD_WORKORDER_MEMOID,LM.AC_NAME AS K_NAME,'' AS CHALLAN_NO,    
         SK.COMPONENT_CODE AS REF_COMPONENT_ARTICLE_CODE ,ART.ARTICLE_NO,'SALE' AS DEPARTMENT,      
         SK.ARTICLE_CODE, B.INV_DT AS ISSUE_DT,'00000' AS JOB_CODE,B.INV_NO AS ISSUE_NO ,  
         A.RATE AS RATE  ,AR.ARTICLE_NO AS BOM_RM,A.QUANTITY , SK.PURCHASE_PRICE AS NEW_RATE  
 FROM PRD_IND01106 A (NOLOCK)        
 JOIN PRD_INM01106 B (NOLOCK) ON A.INV_ID = B.INV_ID        
 JOIN PRD_DEPARTMENT_MST D ON D.DEPARTMENT_ID=B.DEPARTMENT_ID      
 JOIN PRD_SKU SK ON SK.PRODUCT_UID=A.PRODUCT_UID      
 JOIN ARTICLE AR ON AR.ARTICLE_CODE=SK.ARTICLE_CODE      
 JOIN ARTICLE ART ON SK.COMPONENT_CODE=ART.ARTICLE_CODE  
 JOIN LM01106 LM ON B.AC_CODE=LM.AC_CODE   
 JOIN UOM ON AR.UOM_CODE=UOM.UOM_CODE  
 WHERE B.CANCELLED = 0 AND B.INV_MODE=2 AND AR.STOCK_NA=0  
   
 UNION ALL  
 --WHOLESALE RETURN  
 SELECT  'WSR' AS XN_TYPE,SK.WORK_ORDER_ID AS REF_PRD_WORKORDER_MEMOID,LM.AC_NAME AS K_NAME,'' AS CHALLAN_NO,    
         SK.COMPONENT_CODE AS REF_COMPONENT_ARTICLE_CODE ,ART.ARTICLE_NO,'SALE' AS DEPARTMENT,      
         SK.ARTICLE_CODE, B.CN_DT AS ISSUE_DT,'00000' AS JOB_CODE,B.CN_NO AS ISSUE_NO ,  
         A.RATE AS RATE  ,AR.ARTICLE_NO AS BOM_RM,A.QUANTITY , SK.PURCHASE_PRICE AS NEW_RATE  
 FROM PRD_CND01106 A (NOLOCK)        
 JOIN PRD_CNM01106 B (NOLOCK) ON A.CN_ID = B.CN_ID  
 JOIN PRD_DEPARTMENT_MST D ON D.DEPARTMENT_ID=B.DEPARTMENT_ID      
 JOIN PRD_SKU SK ON SK.PRODUCT_UID=A.PRODUCT_UID      
 JOIN ARTICLE AR ON AR.ARTICLE_CODE=SK.ARTICLE_CODE      
 JOIN ARTICLE ART ON SK.COMPONENT_CODE=ART.ARTICLE_CODE  
 JOIN LM01106 LM ON B.AC_CODE=LM.AC_CODE   
 JOIN UOM ON AR.UOM_CODE=UOM.UOM_CODE  
 WHERE B.CANCELLED = 0  AND AR.STOCK_NA=0      
   
 UNION ALL  
 --AGENCY MATERIAL RECEIPT  
 SELECT  'AMR' AS XN_TYPE,SK.WORK_ORDER_ID AS REF_PRD_WORKORDER_MEMOID,AJ.AGENCY_NAME AS K_NAME,'' AS CHALLAN_NO,    
         SK.COMPONENT_CODE AS REF_COMPONENT_ARTICLE_CODE ,ART.ARTICLE_NO,DEP.DEPARTMENT_NAME AS DEPARTMENT,      
         SK.ARTICLE_CODE, D.MEMO_DT AS ISSUE_DT,'00000' AS JOB_CODE,D.MEMO_NO AS ISSUE_NO ,  
         C.RATE AS RATE  ,AR.ARTICLE_NO AS BOM_RM,C.QUANTITY , SK.PURCHASE_PRICE AS NEW_RATE  
 FROM PRD_AGENCY_MATERIAL_RECEIPT_DET C         
 JOIN PRD_AGENCY_MATERIAL_RECEIPT_MST D ON D.MEMO_ID=C.MEMO_ID                  
 JOIN PRD_AGENCY_ISSUE_MATERIAL_DET B ON B.ROW_ID=C.REF_ROW_ID                
 JOIN ARTICLE ART ON ART.ARTICLE_CODE=B.REF_COMPONENT_ARTICLE_CODE          
 JOIN PRD_AGENCY_MST AJ ON AJ.AGENCY_CODE=D.AGENCY_CODE      
 JOIN PRD_SKU SK ON SK.PRODUCT_UID=C.XN_PRODUCT_UID      
 JOIN ARTICLE AR ON AR.ARTICLE_CODE=SK.ARTICLE_CODE  
 JOIN PRD_DEPARTMENT_MST DEP ON DEP.DEPARTMENT_ID=D.DEPARTMENT_ID   
 JOIN UOM ON AR.UOM_CODE=UOM.UOM_CODE  
 WHERE D.CANCELLED=0 AND AR.STOCK_NA=0  
   
 UNION ALL  
 --AGENCY MATERIAL ISSUE  
 SELECT  'AMI' AS XN_TYPE,SK.WORK_ORDER_ID AS REF_PRD_WORKORDER_MEMOID,AJ.AGENCY_NAME AS K_NAME,'' AS CHALLAN_NO,    
         SK.COMPONENT_CODE AS REF_COMPONENT_ARTICLE_CODE ,ART.ARTICLE_NO,DEP.DEPARTMENT_NAME AS DEPARTMENT,      
         SK.ARTICLE_CODE, D.MEMO_DT AS ISSUE_DT,'00000' AS JOB_CODE,D.MEMO_NO AS ISSUE_NO ,  
         C.RATE AS RATE  ,AR.ARTICLE_NO AS BOM_RM,C.QUANTITY , SK.PURCHASE_PRICE AS NEW_RATE  
 FROM PRD_AGENCY_ISSUE_MATERIAL_DET  C         
 JOIN PRD_AGENCY_ISSUE_MATERIAL_MST D ON D.MEMO_ID=C.MEMO_ID                  
 JOIN PRD_AGENCY_MST AJ ON AJ.AGENCY_CODE=D.REF_AGENCY_CODE      
 JOIN PRD_SKU SK ON SK.PRODUCT_UID=C.PRODUCT_UID      
 JOIN ARTICLE AR ON AR.ARTICLE_CODE=SK.ARTICLE_CODE  
 JOIN ARTICLE ART ON SK.COMPONENT_CODE=ART.ARTICLE_CODE  
 JOIN PRD_DEPARTMENT_MST DEP ON DEP.DEPARTMENT_ID=D.DEPARTMENT_ID   
 JOIN UOM ON AR.UOM_CODE=UOM.UOM_CODE  
 LEFT OUTER JOIN   
 (   
   SELECT REF_ROW_ID FROM      PRD_AGENCY_MATERIAL_RECEIPT_DET A        
   JOIN PRD_AGENCY_MATERIAL_RECEIPT_MST B ON A.MEMO_ID=B.MEMO_ID   
   WHERE B.CANCELLED =0  
 ) RC  ON RC.REF_ROW_ID = C.ROW_ID     
 WHERE RC.REF_ROW_ID  IS NULL AND D.CANCELLED=0 AND AR.STOCK_NA=0  
   
 UNION ALL  
 --INHOUSE MATERIAL ISSUE  
 SELECT  'IMI' AS XN_TYPE,SK.WORK_ORDER_ID AS REF_PRD_WORKORDER_MEMOID,'IN HOUSE' AS K_NAME,'' AS CHALLAN_NO,    
         SK.COMPONENT_CODE AS REF_COMPONENT_ARTICLE_CODE ,ART.ARTICLE_NO,DP.DEPARTMENT_NAME AS DEPARTMENT,      
         SK.ARTICLE_CODE, D.MEMO_DT AS ISSUE_DT,'00000' AS JOB_CODE,D.MEMO_NO AS ISSUE_NO ,  
         C.PURCHASE_PRICE AS RATE  ,AR.ARTICLE_NO AS BOM_RM,C.QUANTITY , SK.PURCHASE_PRICE AS NEW_RATE  
 FROM PRD_ISSUE_MATERIAL_DET  C         
 JOIN PRD_ISSUE_MATERIAL_MST D ON D.MEMO_ID=C.MEMO_ID                  
 JOIN PRD_SKU SK ON SK.PRODUCT_UID=C.PRODUCT_UID      
 JOIN ARTICLE AR ON AR.ARTICLE_CODE=SK.ARTICLE_CODE   
 JOIN ARTICLE ART ON SK.COMPONENT_CODE=ART.ARTICLE_CODE  
 JOIN UOM ON AR.UOM_CODE=UOM.UOM_CODE     
 JOIN PRD_DEPARTMENT_MST DP ON DP.DEPARTMENT_ID=D.SOURCE_DEPARTMENT_ID      
 LEFT OUTER JOIN   
 (   
   SELECT REF_ROW_ID FROM      PRD_MATERIAL_RECEIPT_DET A        
   JOIN PRD_MATERIAL_RECEIPT_MST B ON A.MEMO_ID=B.MEMO_ID   
   WHERE B.CANCELLED =0  
 ) RC  ON RC.REF_ROW_ID = C.ROW_ID     
 WHERE RC.REF_ROW_ID  IS NULL AND D.CANCELLED=0  AND AR.STOCK_NA=0  
   
 UNION ALL  
 --INHOUSE MATERIAL RECEIPT  
 SELECT  'IMR' AS XN_TYPE,SK.WORK_ORDER_ID AS REF_PRD_WORKORDER_MEMOID,'IN HOUSE' AS K_NAME,'' AS CHALLAN_NO,    
         SK.COMPONENT_CODE AS REF_COMPONENT_ARTICLE_CODE ,ART.ARTICLE_NO,DP.DEPARTMENT_NAME AS DEPARTMENT,      
         SK.ARTICLE_CODE, D.MEMO_DT AS ISSUE_DT,'00000' AS JOB_CODE,D.MEMO_NO AS ISSUE_NO ,  
         B.PURCHASE_PRICE AS RATE  ,AR.ARTICLE_NO AS BOM_RM,C.QUANTITY , SK.PURCHASE_PRICE AS NEW_RATE  
 FROM PRD_MATERIAL_RECEIPT_DET  C         
 JOIN PRD_MATERIAL_RECEIPT_MST D ON D.MEMO_ID=C.MEMO_ID                  
 JOIN PRD_ISSUE_MATERIAL_DET B ON B.ROW_ID=C.REF_ROW_ID                 
 JOIN PRD_SKU SK ON SK.PRODUCT_UID=B.PRODUCT_UID      
 JOIN ARTICLE AR ON AR.ARTICLE_CODE=SK.ARTICLE_CODE      
 JOIN ARTICLE ART ON SK.COMPONENT_CODE=ART.ARTICLE_CODE  
 JOIN UOM ON AR.UOM_CODE=UOM.UOM_CODE  
 JOIN PRD_DEPARTMENT_MST DP ON DP.DEPARTMENT_ID=D.DEPARTMENT_ID      
 WHERE D.CANCELLED=0 AND AR.STOCK_NA=0  
  
 UNION ALL  
 --OUTPUT CONSUMPTION  
 SELECT  'OPC' AS XN_TYPE,SK.WORK_ORDER_ID AS REF_PRD_WORKORDER_MEMOID,'IN HOUSE' AS K_NAME,'' AS CHALLAN_NO,    
         SK.COMPONENT_CODE AS REF_COMPONENT_ARTICLE_CODE ,ART.ARTICLE_NO,DP.DEPARTMENT_NAME AS DEPARTMENT,      
         SK.ARTICLE_CODE, B.MEMO_DT AS ISSUE_DT,'00000' AS JOB_CODE,B.MEMO_NO AS ISSUE_NO ,  
         C.PURCHASE_PRICE AS RATE  ,AR.ARTICLE_NO AS BOM_RM,C.QUANTITY , SK.PURCHASE_PRICE AS NEW_RATE  
 FROM PRD_DEPARTMENT_OUTPUT_DET C  
 JOIN PRD_DEPARTMENT_OUTPUT_MST B ON B.MEMO_ID=C.MEMO_ID             
 JOIN PRD_SKU SK ON SK.PRODUCT_UID=C.PRODUCT_UID      
 JOIN ARTICLE AR ON AR.ARTICLE_CODE=SK.ARTICLE_CODE      
 JOIN ARTICLE ART ON SK.COMPONENT_CODE=ART.ARTICLE_CODE   
 JOIN UOM ON AR.UOM_CODE=UOM.UOM_CODE  
 JOIN PRD_DEPARTMENT_MST DP ON DP.DEPARTMENT_ID=B.DEPARTMENT_ID    
 WHERE B.CANCELLED=0 AND AR.STOCK_NA=0  
   
 UNION ALL  
 --OUTPUT   
 SELECT  'OP' AS XN_TYPE,SK.WORK_ORDER_ID AS REF_PRD_WORKORDER_MEMOID,'IN HOUSE' AS K_NAME,'' AS CHALLAN_NO,    
         SK.COMPONENT_CODE AS REF_COMPONENT_ARTICLE_CODE ,ART.ARTICLE_NO,DP.DEPARTMENT_NAME AS DEPARTMENT,      
         SK.ARTICLE_CODE, B.MEMO_DT AS ISSUE_DT,'00000' AS JOB_CODE,B.MEMO_NO AS ISSUE_NO ,  
         SK.PURCHASE_PRICE AS RATE  ,AR.ARTICLE_NO AS BOM_RM,C.QUANTITY , SK.PURCHASE_PRICE AS NEW_RATE  
 FROM PRD_OP_MATERIAL_CON_RWM_DET C  
 JOIN PRD_OP_MATERIAL_CON_MST B ON B.MEMO_ID=C.MEMO_ID             
 JOIN PRD_SKU SK ON SK.PRODUCT_UID=C.PRODUCT_UID      
 JOIN ARTICLE AR ON AR.ARTICLE_CODE=SK.ARTICLE_CODE      
 JOIN ARTICLE ART ON SK.COMPONENT_CODE=ART.ARTICLE_CODE  
 JOIN UOM ON AR.UOM_CODE=UOM.UOM_CODE  
 JOIN PRD_DEPARTMENT_MST DP ON DP.DEPARTMENT_ID=B.SOURCE_DEPARTMENT_ID   
 WHERE B.CANCELLED=0 AND AR.STOCK_NA=0 AND B.MODE=0  
   
 UNION ALL      
    --READYMADE RECEIVE  
 SELECT  'RMR' AS XN_TYPE,SK.WORK_ORDER_ID AS REF_PRD_WORKORDER_MEMOID,'IN HOUSE' AS K_NAME,'' AS CHALLAN_NO,    
         SK.COMPONENT_CODE AS REF_COMPONENT_ARTICLE_CODE ,ART.ARTICLE_NO,DP.DEPARTMENT_NAME AS DEPARTMENT,      
         SK.ARTICLE_CODE, B.MEMO_DT AS ISSUE_DT,'00000' AS JOB_CODE,B.MEMO_NO AS ISSUE_NO ,  
         SK.PURCHASE_PRICE AS RATE  ,AR.ARTICLE_NO AS BOM_RM,C.QUANTITY , SK.PURCHASE_PRICE AS NEW_RATE  
 FROM PRD_READY_RECEIVE_DET C                
 JOIN PRD_READY_RECEIVE_MST B ON B.MEMO_ID=C.MEMO_ID             
 JOIN PRD_SKU SK ON SK.PRODUCT_UID=C.PRODUCT_UID    
 JOIN ARTICLE AR ON AR.ARTICLE_CODE=SK.ARTICLE_CODE      
 JOIN ARTICLE ART ON C.REF_COMPONENT_CODE=ART.ARTICLE_CODE  
 JOIN UOM ON AR.UOM_CODE=UOM.UOM_CODE  
 JOIN LM01106 LM ON B.AC_CODE=LM.AC_CODE  
 JOIN PRD_DEPARTMENT_MST DP ON DP.DEPARTMENT_ID=B.DEPARTMENT_ID    
 WHERE B.CANCELLED=0 AND AR.STOCK_NA=0  
  
 UNION ALL      
    --FINISH CONSUMPTION  
 SELECT  'FINC' AS XN_TYPE,SK.WORK_ORDER_ID AS REF_PRD_WORKORDER_MEMOID,'IN HOUSE' AS K_NAME,'' AS CHALLAN_NO,    
         SK.COMPONENT_CODE AS REF_COMPONENT_ARTICLE_CODE ,ART.ARTICLE_NO,DP.DEPARTMENT_NAME AS DEPARTMENT,      
         SK.ARTICLE_CODE, B.MEMO_DT AS ISSUE_DT,'00000' AS JOB_CODE,B.MEMO_NO AS ISSUE_NO ,  
         SK.PURCHASE_PRICE AS RATE  ,AR.ARTICLE_NO AS BOM_RM,C.QUANTITY , SK.PURCHASE_PRICE AS NEW_RATE  
 FROM PRD_FINISH_DET C                
 JOIN PRD_FINISH_MST B ON B.MEMO_ID=C.MEMO_ID             
 JOIN PRD_SKU SK ON SK.PRODUCT_UID=C.PRODUCT_UID      
 JOIN ARTICLE AR ON AR.ARTICLE_CODE=SK.ARTICLE_CODE      
 JOIN ARTICLE ART ON SK.COMPONENT_CODE=ART.ARTICLE_CODE  
 JOIN UOM ON AR.UOM_CODE=UOM.UOM_CODE  
 JOIN PRD_DEPARTMENT_MST DP ON DP.DEPARTMENT_ID=B.DEPARTMENT_ID   
 WHERE B.CANCELLED=0 AND AR.STOCK_NA=0   
   
) AI ON AI.REF_PRD_WORKORDER_MEMOID=WOD.MEMO_ID AND WOD.ARTICLE_CODE=AI.REF_COMPONENT_ARTICLE_CODE      
  
LEFT OUTER JOIN PRD_STK_TRANSFER_DTM_MST DTM ON WOD.MEMO_ID=DTM.REF_WO_ID AND DTM.CANCELLED=0      
LEFT OUTER JOIN PRD_WO_ART_JOBS PRD_JOBS ON PRD_JOBS.REF_ROW_ID=WOD.ROW_ID     
JOIN JOBS E1 ON E1.JOB_CODE=PRD_JOBS.JOB_CODE      
LEFT OUTER JOIN PRD_AGENCY_MST AG ON AG.AGENCY_CODE=PRD_JOBS.AGENCY_CODE
