CREATE VIEW SPPPC_VW_UOM_RM_PRINT
AS  
  SELECT B.MEMO_ID,B.MEMO_NO,B.MEMO_DT ,UOM.UOM_NAME ,SUM(A.QUANTITY ) AS QUANTITY
  FROM PPC_AGENCY_ISSUE_MATERIAL_DET A (NOLOCK) 
  JOIN PPC_AGENCY_ISSUE_MATERIAL_MST B (NOLOCK) ON A.MEMO_ID=B.MEMO_ID  
  JOIN PPC_SKU SKU (NOLOCK) ON SKU.PRODUCT_UID=A.PRODUCT_UID  
  JOIN ARTICLE ART (NOLOCK) ON ART.ARTICLE_CODE=SKU.ARTICLE_CODE  
  JOIN UOM (NOLOCK) ON UOM.UOM_CODE =ART.UOM_CODE   
  WHERE B.CANCELLED=0  
  GROUP BY B.MEMO_ID,B.MEMO_NO,B.MEMO_DT ,UOM.UOM_NAME
