CREATE VIEW VW_BUY_PLAN
AS
    
               SELECT BUDGET_PLAN_MEMO_NO,BUDGET_PLAN_NAME,A.MEMO_NO,A.MEMO_DT,A.CANCELLED,A.APPROVEDLEVELNO,
               B.ARTICLE_CODE,C.ARTICLE_NO,  B.PARA1_CODE,P1.PARA1_NAME, B.PARA2_CODE,P2.PARA2_NAME,
               B.PARA3_CODE,P3.PARA3_NAME,B.PARA4_CODE,P4.PARA4_NAME, B.PARA5_CODE,P5.PARA5_NAME,B.PARA6_CODE,
               P6.PARA6_NAME,
               B.MRP,B.PURCHASE_PRICE,B.QUANTITY
               FROM BUY_PLAN_MST A(NOLOCK)
               JOIN BUY_PLAN_DET B(NOLOCK) ON A.MEMO_NO=B.MEMO_NO
               JOIN BUDGET_PLAN_MST F(NOLOCK) ON F.MEMO_NO=BUDGET_PLAN_MEMO_NO
               JOIN ARTICLE C ON C.ARTICLE_CODE=B.ARTICLE_CODE
               JOIN PARA1 P1 ON P1.PARA1_CODE=B.PARA1_CODE
               JOIN PARA2 P2 ON P2.PARA2_CODE=B.PARA2_CODE
               JOIN PARA3 P3 ON P3.PARA3_CODE=B.PARA3_CODE
               JOIN PARA4 P4 ON P4.PARA4_CODE=B.PARA4_CODE
               JOIN PARA5 P5 ON P5.PARA5_CODE=B.PARA5_CODE
               JOIN PARA6 P6 ON P6.PARA6_CODE=B.PARA6_CODE
