CREATE VIEW VW_CASHMEMO_PRINT_MST

AS
SELECT * FROM--FROM
(
	SELECT A.CM_TIME,A.CM_ID,A.CM_NO,A.CM_DT,A.SUBTOTAL,A.DISCOUNT_PERCENTAGE,A.DISCOUNT_AMOUNT,
	A.NET_AMOUNT,A.CUSTOMER_CODE,A.CANCELLED,A.REMARKS,C.USERNAME,A.ATD_CHARGES 
	,B.USER_CUSTOMER_CODE,B.CUSTOMER_TITLE,B.CUSTOMER_FNAME,B.CUSTOMER_LNAME
	,B.ADDRESS1,B.ADDRESS2,'' AS AREA,'' AS CITY,'' AS PINCODE,'' AS STATE,B.PHONE1,B.PHONE2,B.MOBILE,B.EMAIL
	,ADDRESS9 ,X.TOTAL_QTY,X.TOTAL_TAX,''  AS AMOUNT_IN_WORDS,''  AS PAYMENTDETAILS   ,P.*
	,A.SUBTOTAL+A.SUBTOTAL_R AS NET_SUBTOTAL
	,(A.SUBTOTAL+A.SUBTOTAL_R-X.TOTAL_TAX) AS NET_SUBTOTAL_WOTAX
	,E.EMP_NAME AS SALE_PERSON1
	,E1.EMP_NAME AS SALE_PERSON2
	,E2.EMP_NAME AS SALE_PERSON3,COM.*,CMD_DISCOUNT,MRPVALUE
	,[VAL_AMT_5],[VAL_AMT_DEC25],[VAL_AMT_12_5],[VAL_AMT_DEC63]
	FROM CMM01106 A (NOLOCK) 
	JOIN CUSTDYM B (NOLOCK) ON B.CUSTOMER_CODE=A.CUSTOMER_CODE  
	JOIN USERS C (NOLOCK) ON C.USER_CODE=A.USER_CODE
	LEFT OUTER JOIN VW_BILL_PAYMODE P ON P.MEMO_ID=A.CM_ID AND P.XN_TYPE='SLS'
	JOIN 
	( SELECT CM_ID,MAX(EMP_CODE) AS EMP_CODE,MAX(EMP_CODE1) AS EMP_CODE1,MAX(EMP_CODE2) AS EMP_CODE2
			,SUM(QUANTITY) AS TOTAL_QTY,SUM(TAX_AMOUNT) AS TOTAL_TAX,CAST(SUM(DISCOUNT_AMOUNT)AS NUMERIC(10,2)) AS CMD_DISCOUNT,
			CAST(SUM(MRP*QUANTITY) AS NUMERIC(10,2)) AS MRPVALUE,
			
			CAST(SUM(CASE WHEN TAX_PERCENTAGE=5.25 THEN (NET - CMM_DISCOUNT_AMOUNT)*5/100
			ELSE 0 END) AS NUMERIC(10,2))AS [VAL_AMT_5],
			CAST(SUM(CASE WHEN TAX_PERCENTAGE=5.25 THEN (NET - CMM_DISCOUNT_AMOUNT)*0.25/100
			ELSE 0 END) AS NUMERIC(10,2))AS [VAL_AMT_DEC25],
			
			CAST(SUM(CASE WHEN TAX_PERCENTAGE=13.13 THEN (NET - CMM_DISCOUNT_AMOUNT)*12.5/100
			ELSE 0 END) AS NUMERIC(10,2))AS [VAL_AMT_12_5],
			CAST(SUM(CASE WHEN TAX_PERCENTAGE=13.13 THEN (NET - CMM_DISCOUNT_AMOUNT)*0.63/100
			ELSE 0 END) AS NUMERIC(10,2))AS [VAL_AMT_DEC63]
			
	       
		
	
		FROM CMD01106 (NOLOCK) 
		GROUP BY CM_ID
	)X ON X.CM_ID=A.CM_ID
	JOIN EMPLOYEE E ON X.EMP_CODE=E.EMP_CODE
	JOIN EMPLOYEE E1 ON X.EMP_CODE1=E1.EMP_CODE
	JOIN EMPLOYEE E2 ON X.EMP_CODE2=E2.EMP_CODE
	
	LEFT OUTER JOIN 
	( 
	    SELECT COMPANY_NAME ,ADDRESS1 AS COMPANY_ADD1,ADDRESS2 AS  COMPANY_ADD2,
	    CITY AS COMPANY_CITY,TIN_NO AS COMPANY_TIN,TAN_NO COMPANY_TAN_NO,ADDRESS9 AS COMPANY_ADDRESS9,
	         PRINT_ADDRESS AS COMPANY_PRINT_ADDRESS9,PIN AS COMPANY_PIN,CIN AS COMPANY_CIN,
	         PAN_NO AS COMPANY_PAN,EMAIL_ID AS COMPANY_EAMIL,STATE AS  COMPANY_STATE,
	         MOBILE AS COMPANY_MOBILE,PHONES_FAX AS COMPANY_PHONE
		FROM COMPANY (NOLOCK) 
		WHERE COMPANY_CODE= '01'
	)COM ON 1=1
	
	)R
