CREATE VIEW VW_WL_PRD_WSLCRNOTE_QBF  

AS   
SELECT T1.MEMO_PREFIX AS MST_MEMO_PREFIX,T1.CN_ID ,  
T1.CN_DT AS MST_CN_DT ,  
T1.CN_NO AS MST_CN_NO, 
T1.FIN_YEAR AS MST_FIN_YEAR, 
T1.SUBTOTAL AS MST_SUBTOTAL,  
T1.DISCOUNT_PERCENTAGE AS MST_DISCOUNT_PERCENTAGE ,  
T1.DISCOUNT_AMOUNT AS MST_DISCOUNT_AMOUNT ,  
T1.FREIGHT AS MST_FREIGHT ,  
T1.OTHER_CHARGES AS MST_OTHER_CHARGES ,  
T1.TOTAL_AMOUNT AS MST_TOTAL_AMOUNT ,  
T1.REMARKS AS MST_REMARKS ,  
T1.GRLR_DATE AS MST_GRLR_DATE ,  
T1.BANDALS AS MST_BANDALS ,  
T1.THROUGH AS MST_THROUGH ,  
T1.TAX_PERCENTAGE AS MST_TAX_PERCENTAGE ,  
T1.TAX_AMOUNT AS MST_TAX_AMOUNT ,  
T1.MANUAL_INV_NO AS MST_MANUAL_INV_NO,  
T1.EXCISE_ACCESSIBLE_AMOUNT AS MST_EXCISE_ACCESSIBLE_AMOUNT,  
T1.EXCISE_EDU_CESS_PERCENTAGE AS MST_EXCISE_EDU_CESS_PERCENTAGE ,  
T1.EXCISE_HEDU_CESS_PERCENTAGE AS MST_EXCISE_HEDU_CESS_PERCENTAGE,  
T1.EXCISE_DUTY_PERCENTAGE AS MST_EXCISE_DUTY_PERCENTAGE,  
T1.EXCISE_EDU_CESS_AMOUNT AS MST_EXCISE_EDU_CESS_AMOUNT,  
T1.EXCISE_HEDU_CESS_AMOUNT AS MST_EXCISE_HEDU_CESS_AMOUNT,  
T1.EXCISE_DUTY_AMOUNT AS MST_EXCISE_DUTY_AMOUNT,  
T1.EXCISE_ACCESSIBLE_PERCENTAGE AS MST_EXCISE_ACCESSIBLE_PERCENTAGE,  
T1.ROUND_OFF AS MST_ROUND_OFF,  
T2.PRODUCT_UID,  
T2.QUANTITY,  
T2.RATE,  
T2.DISCOUNT_PERCENTAGE,  
T2.DISCOUNT_AMOUNT,  
T2.QUANTITY*T2.RATE AS AMOUNT,  
T3.AC_NAME AS MST_AC_NAME,  
T4.FORM_NAME AS MST_FORM_NAME
FROM PRD_CNM01106 T1  
JOIN PRD_CND01106 T2 ON T1.CN_ID = T2.CN_ID  
JOIN LMV01106 T3 ON T3.AC_CODE = T1.AC_CODE  
JOIN FORM   T4 ON T4.FORM_ID = T1.FORM_ID
