CREATE VIEW VW_TILL_LIFT_REPORT     
AS     

SELECT 	
A.*,C.USERNAME,LM.AC_NAME,MST.TILL_NAME,LMST.AC_NAME AS TILL_AC_NAME,
(CASE WHEN ISNULL(D.VALUE,'')='' OR ISNULL(A.MEMO_ID,'')='' THEN '' ELSE D.VALUE+'TILLTRANSFER\'+A.MEMO_ID+'.JPG' END) AS IMAGE_PATH 
FROM TILL_LIFTS A
JOIN TILL_SHIFT_MST B ON A.SHIFT_ID=B.SHIFT_ID
JOIN TILL_MST MST ON MST.TILL_ID=B.TILL_ID
JOIN USERS C ON A.USER_CODE=C.USER_CODE	
LEFT JOIN CONFIG D ON  CONFIG_OPTION='ART_PICT_PATH' AND ISNULL(VALUE,'')<>''
LEFT OUTER JOIN LMV01106 LM ON A.AC_CODE=LM.AC_CODE
LEFT OUTER JOIN LMV01106  LMST ON LMST.AC_CODE=MST.AC_CODE
