create VIEW VW_DNPS_QBF     

AS         
SELECT     
A.PS_ID,     
A.PS_DT AS 'MST_XN_DT',     
A.PS_NO AS 'MST_PS_NO',     
U.USERNAME AS 'MST_USERNAME',    
B.AC_NAME AS 'MST_SUPP_NAME',      
B.ADDRESS0 AS 'MST_ADDRESS0',    
B.ADDRESS1 AS 'MST_ADDRESS1',    
B.ADDRESS2 AS 'MST_ADDRESS2',    
B.AREA_NAME AS 'MST_AREA_NAME',    
B.CITY AS 'MST_CITY',    
B.PINCODE AS 'MST_PINCODE',    
B.STATE AS 'MST_STATE',                
A.REMARKS AS 'MST_REMARKS',    
A.FIN_YEAR AS 'MST_FIN_YEAR',    
C.PRODUCT_CODE AS 'PRODUCT_CODE',   
SKU.INV_NO AS BILL_NO,   
LEFT(c.PRODUCT_CODE, ISNULL(NULLIF(CHARINDEX ('@',c.PRODUCT_CODE)-1,-1),LEN(c.PRODUCT_CODE ))) AS 'MST_PRODUCT_CODE',     
C.QUANTITY AS 'MST_QUANTITY',    
D.ARTICLE_NO AS 'ARTICLE_NO',     
D.ARTICLE_NAME AS 'ARTICLE_NAME',    
D.ARTICLE_DESC AS 'ARTICLE_DESC',    
P1.PARA1_NAME AS 'PARA1_NAME',     
P2.PARA2_NAME AS 'PARA2_NAME',     
P3.PARA3_NAME AS 'PARA3_NAME',  
P4.PARA4_NAME AS 'PARA4_NAME',    
P5.PARA5_NAME AS 'PARA5_NAME',     
P6.PARA6_NAME AS 'PARA6_NAME',    
C.TS AS 'TS',    
C.QUANTITY AS 'QUANTITY',    
E.SUB_SECTION_NAME AS 'SUB_SECTION_NAME',       
F.SECTION_NAME AS 'SECTION_NAME',    
H.UOM_NAME AS 'UOM_NAME',    
SKU.INV_NO  AS 'INV_NO',    
SKU.INV_DT AS 'INV_DT',    
COM.COMPANY_CODE  
,A.PS_DT AS MST_PS_DT 
,A.AC_CODE AS MST_AC_CODE  
,A.LAST_UPDATE AS MST_LAST_UPDATE  
,A.CANCELLED AS MST_CANCELLED  
,A.USER_CODE AS MST_USER_CODE  
,A.PS_MODE AS MST_PS_MODE 
,A.PARTY_DEPT_ID AS MST_PARTY_DEPT_ID  
,B.AC_NAME  
,B.ALIAS  
,B.HEAD_CODE  
,B.CLOSING_BALANCE  
,B.CLOSING_BALANCE_CR_DR  
,B.PRINT_LEDGER  
,B.INACTIVE  
,B.PRINT_NAME  
,B.ADDRESS0  
,B.ADDRESS1  
,B.ADDRESS2  
,B.AREA_CODE  
,B.AREA_NAME  
,B.PINCODE  
,B.CITY_CODE  
,B.CITY  
,B.STATE_CODE  
,B.STATE  
,B.CST_NO  
,B.CST_DT  
,B.SST_NO  
,B.SST_DT  
,B.TIN_NO  
,B.TIN_DT  
,B.PHONES_R  
,B.PHONES_O  
,B.PHONES_FAX  
,B.MOBILE  
,B.E_MAIL  
,B.TAX_CODE  
,B.CREDIT_DAYS  
,B.BILL_BY_BILL  
,B.ON_HOLD  
,B.THROUGH_BROKER  
,B.BROKER_AC_CODE  
,B.BROKER_COMM_PERCENT  
,B.CREDIT_LIMIT  
,B.ALLOW_CREDITOR_DEBTOR  
,B.DPWEF_DT  
,B.CST_PERCENTAGE  
,B.PAN_NO  
,B.CUSTOMER_CODE  
,B.GLN_NO  
,B.MP_PERCENTAGE  
,B.MRP_CALC_MODE  
,B.TDS_CODE  
,B.INV_RATE_TYPE  
,B.OUTSTATION_PARTY  
,B.SALES_AC_CODE  
,B.USERNAME  
,B.EDT_USERNAME  
,C.DEPT_ID  
,SKU.ARTICLE_CODE  
,SKU.PARA1_CODE  
,SKU.PARA2_CODE  
,SKU.PARA3_CODE  
,SKU.RECEIPT_DT  
,SKU.PARA4_CODE  
,SKU.PARA5_CODE  
,SKU.PARA6_CODE  
,SKU.MRP  
,SKU.DT_CREATED  
,SKU.WS_PRICE  
,SKU.IMAGE_NAME  
,SKU.CHALLAN_NO  
,SKU.FIX_MRP  
,D.CODING_SCHEME  
,D.PARA1_SET  
,D.PARA2_SET  
,D.SKU_CODE  
,D.SUB_SECTION_CODE  
,D.DISCON  
,D.WHOLESALE_PRICE  
,D.WSP_PERCENTAGE  
,D.MIN_PRICE  
,D.STOCK_NA  
,D.ARTICLE_TYPE  
,D.CREATED_ON  
,D.ARTICLE_GROUP_CODE  
,D.GENERATE_BARCODES_WITHARTICLE_PREFIX  
,D.ARTICLE_GEN_MODE  
,D.ARTICLE_PRD_MODE  
,D.ARTICLE_SET_CODE  
,D.OH_PERCENTAGE  
,D.OH_AMOUNT  
,E.SECTION_CODE  
,E.MFG_CATEGORY  
,U.MAJOR_USER_CODE  
,U.USER_ALIAS  
,U.DISCOUNT_PERCENTAGE_LEVEL  
,U.VIEW_DATA_AFTER_DFM  
,U.EMAIL  
,H.UOM_TYPE  
,LCT.DEPT_NAME  
,LCT.MAJOR_DEPT_ID  
,LCT.LOC_TYPE  
,LCT.DATE_OF_OPENING  
,LCT.REPORT_BLOCKED  
,LCT.ACCOUNTS_POSTING_DEPT_ID  
,LCT.CONTROL_AC_CODE  
,LCT.UPD_PURINFO  
,LCT.SSPL_REG_KEY  
,LCT.WIZCOM_ENABLED  
,LCT.EXCISABLE  
,LCT.FR_TYPE  
,LCT.PRIMARY_EMAIL_PORT  
,LCT.PRIMARY_EMAIL  
,LCT.PRIMARY_EMAIL_SMTP  
,LCT.PRIMARY_EMAIL_PWD  
,LCT.PRIMARY_EMAIL_SSL  
,LCT.SSPL_GRP_CODE  
,LCT.PUR_LOC  
,LCT.DEPT_AC_CODE  
,LCT.LST_NO  
,LCT.LST_DT  
,LCT.DEPT_ALIAS  
,LCT.PHONE  
,LA.AREA_NAME AS LOCATION_AREA  
,LC.CITY AS LOCATION_CITY  
,LS.STATE AS LOCATION_STATE  
,LRG.REGION_NAME AS LOCATION_REGION  
,B.AC_CODE AS SUPPLIER_AC_CODE  
,B.AC_NAME AS SUPPLIER_AC_NAME  
,B.ALIAS AS SUPPLIER_ALIAS  
,B.HEAD_CODE AS SUPPLIER_HEAD_CODE  
,B.CLOSING_BALANCE AS SUPPLIER_CLOSING_BALANCE  
,B.CLOSING_BALANCE_CR_DR AS SUPPLIER_CLOSING_BALANCE_CR_DR  
,B.PRINT_LEDGER AS SUPPLIER_PRINT_LEDGER  
,B.LAST_UPDATE AS SUPPLIER_LAST_UPDATE  
,B.INACTIVE AS SUPPLIER_INACTIVE  
,B.PRINT_NAME AS SUPPLIER_PRINT_NAME  
,B.ADDRESS0 AS SUPPLIER_ADDRESS0  
,B.ADDRESS1 AS SUPPLIER_ADDRESS1  
,B.ADDRESS2 AS SUPPLIER_ADDRESS2  
,B.AREA_CODE AS SUPPLIER_AREA_CODE  
,B.AREA_NAME AS SUPPLIER_AREA_NAME  
,B.PINCODE AS SUPPLIER_PINCODE  
,B.CITY_CODE AS SUPPLIER_CITY_CODE  
,B.CITY AS SUPPLIER_CITY  
,B.STATE_CODE AS SUPPLIER_STATE_CODE  
,B.STATE AS SUPPLIER_STATE  
,B.CST_NO AS SUPPLIER_CST_NO  
,B.CST_DT AS SUPPLIER_CST_DT  
,B.SST_NO AS SUPPLIER_SST_NO  
,B.SST_DT AS SUPPLIER_SST_DT  
,B.TIN_NO AS SUPPLIER_TIN_NO  
,B.TIN_DT AS SUPPLIER_TIN_DT  
,B.PHONES_R AS SUPPLIER_PHONES_R  
,B.PHONES_O AS SUPPLIER_PHONES_O  
,B.PHONES_FAX AS SUPPLIER_PHONES_FAX  
,B.MOBILE AS SUPPLIER_MOBILE  
,B.E_MAIL AS SUPPLIER_E_MAIL  
,B.TAX_CODE AS SUPPLIER_TAX_CODE  
,B.CREDIT_DAYS AS SUPPLIER_CREDIT_DAYS  
,B.DISCOUNT_PERCENTAGE AS SUPPLIER_DISCOUNT_PERCENTAGE  
,B.BILL_BY_BILL AS SUPPLIER_BILL_BY_BILL  
,B.ON_HOLD AS SUPPLIER_ON_HOLD  
,B.THROUGH_BROKER AS SUPPLIER_THROUGH_BROKER  
,B.BROKER_AC_CODE AS SUPPLIER_BROKER_AC_CODE  
,B.BROKER_COMM_PERCENT AS SUPPLIER_BROKER_COMM_PERCENT  
,B.CREDIT_LIMIT AS SUPPLIER_CREDIT_LIMIT  
,B.ALLOW_CREDITOR_DEBTOR AS SUPPLIER_ALLOW_CREDITOR_DEBTOR  
,B.DPWEF_DT AS SUPPLIER_DPWEF_DT  
,B.CST_PERCENTAGE AS SUPPLIER_CST_PERCENTAGE  
,B.PAN_NO AS SUPPLIER_PAN_NO  
,B.FORM_ID AS SUPPLIER_FORM_ID  
,B.CUSTOMER_CODE AS SUPPLIER_CUSTOMER_CODE  
,B.GLN_NO AS SUPPLIER_GLN_NO  
,B.MP_PERCENTAGE AS SUPPLIER_MP_PERCENTAGE  
,B.MRP_CALC_MODE AS SUPPLIER_MRP_CALC_MODE  
,B.TDS_CODE AS SUPPLIER_TDS_CODE  
,B.COMPANY_CODE AS SUPPLIER_COMPANY_CODE  
,B.INV_RATE_TYPE AS SUPPLIER_INV_RATE_TYPE  
,B.OUTSTATION_PARTY AS SUPPLIER_OUTSTATION_PARTY  
,B.SALES_AC_CODE AS SUPPLIER_SALES_AC_CODE  
,B.USER_CODE AS SUPPLIER_USER_CODE  
,B.EDT_USER_CODE AS SUPPLIER_EDT_USER_CODE  
,B.USERNAME AS SUPPLIER_USERNAME  
,B.EDT_USERNAME AS SUPPLIER_EDT_USERNAME  
,SKU.PRODUCT_NAME 
,SKU.PURCHASE_PRICE,
LCT.DEPT_NAME AS MST_DEPT_NAME ,d.ARTICLE_PACK_SIZE 
,A.location_Code
FROM DNPS_MST A (NOLOCK)           
JOIN LMV01106 B (NOLOCK)  ON A.AC_CODE = B.AC_CODE          
JOIN DNPS_DET C (NOLOCK) ON A.PS_ID = C.PS_ID          
JOIN SKU (NOLOCK) ON C.PRODUCT_CODE = SKU.PRODUCT_CODE      
JOIN ARTICLE D (NOLOCK)  ON SKU.ARTICLE_CODE = D.ARTICLE_CODE          
JOIN SECTIOND E (NOLOCK)  ON D.SUB_SECTION_CODE = E.SUB_SECTION_CODE           
JOIN SECTIONM F (NOLOCK) ON E.SECTION_CODE = F.SECTION_CODE           
JOIN PARA1 P1 (NOLOCK)  ON SKU.PARA1_CODE = P1.PARA1_CODE          
JOIN PARA2 P2 (NOLOCK)  ON SKU.PARA2_CODE = P2.PARA2_CODE          
JOIN PARA3 P3 (NOLOCK)  ON SKU.PARA3_CODE = P3.PARA3_CODE   
JOIN PARA4 P4 (NOLOCK)  ON SKU.PARA4_CODE = P4.PARA4_CODE   
JOIN PARA5 P5 (NOLOCK)  ON SKU.PARA5_CODE = P5.PARA5_CODE     
JOIN PARA6 P6 (NOLOCK)  ON SKU.PARA6_CODE = P6.PARA6_CODE         
JOIN USERS U (NOLOCK)  ON A.USER_CODE = U.USER_CODE       
JOIN UOM H (NOLOCK)  ON D.UOM_CODE = H.UOM_CODE    
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  
LEFT OUTER JOIN LOCATION LCT (NOLOCK) ON A.PARTY_DEPT_ID=LCT.DEPT_ID  
LEFT OUTER JOIN AREA LA ON LCT.AREA_CODE=LA.AREA_CODE  
LEFT OUTER JOIN CITY LC ON LA.CITY_CODE=LC.CITY_CODE  
LEFT OUTER JOIN STATE LS ON LC.STATE_CODE=LS.STATE_CODE  
LEFT OUTER JOIN REGIONM LRG ON LS.REGION_CODE=LRG.REGION_CODE  
JOIN COMPANY COM ON 1=1 AND COM.COMPANY_CODE ='01'
