CREATE VIEW VW_WL_FIXEDITEMMASTER    

AS    
     
SELECT A.PRODUCT_CODE AS MST_PRODUCT_CODE  ,B.ARTICLE_NO AS MST_ARTICLE_NO,D.SECTION_NAME AS MST_SECTION_NAME,  
C.SUB_SECTION_NAME AS MST_SUB_SECTION_NAME,E.PARA1_NAME AS MST_PARA1_NAME,    
F.PARA2_NAME AS MST_PARA2_NAME,G.PARA3_NAME AS MST_PARA3_NAME,H.PARA4_NAME AS MST_PARA4_NAME,  
I.PARA5_NAME AS MST_PARA5_NAME,  
J.PARA6_NAME AS MST_PARA6_NAME,A.PURCHASE_PRICE AS MST_PURCHASE_PRICE,A.MRP AS MST_MRP ,A.WS_PRICE AS MST_WS_PRICE    
FROM SKU A     
JOIN ARTICLE B ON  A.ARTICLE_CODE= B.ARTICLE_CODE     
JOIN SECTIOND C ON B.SUB_SECTION_CODE= C.SUB_SECTION_CODE    
JOIN SECTIONM D ON C.SECTION_CODE= D.SECTION_CODE    
JOIN PARA1 E ON A.PARA1_CODE= E.PARA1_CODE    
JOIN PARA2 F ON A.PARA2_CODE= F.PARA2_CODE    
JOIN PARA3 G ON A.PARA3_CODE= G.PARA3_CODE    
JOIN PARA4 H ON A.PARA4_CODE= H.PARA4_CODE    
JOIN PARA5 I ON A.PARA5_CODE= I.PARA5_CODE    
JOIN PARA6 J ON A.PARA6_CODE= J.PARA6_CODE
WHERE B.CODING_SCHEME =1
