CREATE VIEW [DBO].[VW_JOB_ISSUELIST]  

AS  
SELECT  M.ISSUE_NO AS ISSUE_NO,     
   M.ISSUE_DT AS ISSUE_DATE,     
  (CASE WHEN M.CANCELLED = 1 THEN 'CANCELLED' ELSE '' END) AS CANCELLED ,   
  (CASE WHEN WIP =1 THEN 'WIP' ELSE (CASE WHEN M.ISSUE_TYPE = 1 THEN 'WITH STOCK' ELSE 'WITHOUT STOCK' END) END) AS MEMO_TYPE,   
  M.ISSUE_NO AS MEMO_ID,    
        C.AGENCY_NAME AS AGENCY_NAME ,M.FIN_YEAR  ,M.location_Code  
FROM    JOBWORK_ISSUE_MST M (NOLOCK) JOIN     
        PRD_AGENCY_MST C (NOLOCK) ON M.AGENCY_CODE = C.AGENCY_CODE
