CREATE VIEW VW_JOBCARD_LIST     
AS               
SELECT       
A.MEMO_DT AS 'MEMO_DT',     
A.MEMO_ID AS 'MEMO_ID',       
A.MEMO_NO,     
B.AC_NAME AS 'SUPPLIER_NAME',      
(CASE WHEN A.CANCELLED = 1 THEN 'CANCELLED' ELSE '' END) AS CANCELLED,    
(CASE WHEN A.CANCELLED = 0 THEN A.SUBTOTAL  ELSE 0 END) AS 'SUBTOTAL',            
(CASE WHEN A.ORD_PLAN_MODE = 1 THEN 'BILL LEVEL'  ELSE 'ITEM LEVEL' END) AS 'CONSUMABLE_AT',            
A.REMARKS AS 'REMARKS',        
H.USERNAME AS 'CREATED_BY_USER',      
A.FIN_YEAR,
BIN.BIN_NAME AS BIN,    
L.DEPT_ID AS LOC_ID,
L.DEPT_NAME AS LOC_NAME,
A.TOTAL_QUANTITY_STR   ,A.location_code
FROM ORD_PLAN_MST A (NOLOCK)               
JOIN LM01106 B (NOLOCK)  ON A.AC_CODE = B.AC_CODE              
JOIN USERS H (NOLOCK) ON A.USER_CODE = H.USER_CODE    
JOIN BIN  (NOLOCK) ON BIN.BIN_ID = A.BIN_ID      
LEFT OUTER JOIN LOCATION  L (NOLOCK) ON A.DEPT_ID = L.DEPT_ID
